### PR TITLE
Allow user to specify BUILD_DIR when using compile.sh

### PR DESCRIPTION
**Pull request by aerorahul**
## Description
The GFS and GEFS applications call `compile.sh` to build the ufs-weather-model.
As it stands currently, the ufs-weather-model build directory ends up in the source tree of the GFS and GEFS.
The GFS and GEFS are collecting all the build directories of the components in a single location for the applications.

This PR:
- allows a user (or application) to specify a `BUILD_DIR` before invoking `compile.sh`.  This allows the build directory to be out of the source directory.
- does not alter the default behavior of the script `compile.sh`.

### Input data additions/changes
- [X] No changes are expected to input data.

### Anticipated changes to regression tests:
- [X] No changes are expected to any regression test.

## Subcomponents involved:
- [X] none

### Library Updates/Changes
- [X] Not Needed

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
None

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA A quick sanity check on orion/hera works perfectly fine for this BUILD_DIR fix. We can apply this fix to the next PR once you approve.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
Hi, @aerorahul . Wanted to make you aware that once #1815 is synced and conflicts resolved, we're planning to add your code changes in this PR to that one. We'll ensure you're credited as well. Please let me know if you have any questions regarding this.

**Comment by aerorahul** [comment]
> @aerorahul please bring these up to date with respective authoritative repositories
> 
> * ufs-weather-model **NOT** up to date
> * fv3 **NOT** up to date

done.

**Comment by zach1221** [comment]
#1815 has been merged into ufs-community:develop, with the one code change from this PR. Unless you have any objections, I will close this PR. @aerorahul

**Pull request closed without merging**
