### PR TITLE
small cloud tuning from Greg Thompson

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR only updates the FV3 and ccpp/physics submodule pointer to include new cloud tuning for ice clouds aloft by Greg Thompson.

### Issue(s) addressed

https://github.com/NCAR/ccpp-physics/issues/966

## Testing

The changes were tested using rt.conf on Hera/Intel. All tests pass except for those using the Thompson MP scheme, which fail in run_result as expected due to the new tuning.

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

https://github.com/ufs-community/ccpp-physics/pull/1
https://github.com/NOAA-EMC/fv3atm/pull/580

### CODE REVIEW

**Comment by jkbk2004** [comment]
@grantfirl sorry for delaying. But we will merge in #1399 around lunch time today. Then we can start working on this PR.

**Comment by jkbk2004** [comment]
@grantfirl we are trying to see if we can add in fms upgrade (g2tmpl and crtm as well). One or two days delay is possible for this pr. Also, Dustin's #1394 is on hold. But we are giving a priority for emc ccpp fork branch switch after #1394. So schedules for ccpp prs a bit tangled. If progress can be made on #1394, commit schedule issue can be resolved very nicely. But I will check with emc code managers.

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl Is this ready to get tested today?

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA @ChunxiZhang-NOAA The underlying physics code changes are certainly ready to test, although it looks like there will be an issue testing this because the ccpp-physics PR is into the ufs/dev branch right now, and the ufs/dev branch is behind NCAR/main. I think that the PRs that were merged into NCAR/main since ufs/dev was forked off have changed some baselines, so the UFS RTs will basically be testing old code against newer baselines, which, I'm guessing, is no good. @ChunxiZhang-NOAA We could change the target of the ccpp-physics PR back into NCAR/main if @BrianCurtis-NOAA would like to work on this today. I know that you wanted to merge Dustin's "accumulated cleanup" PR into NCAR/main before syncing, but I'm not sure that it is ready yet, so perhaps we should just change the target of the Thompson tuning PR to avoid delaying EMC code managers?

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA FYI, I have a doctor's appointment for the next hour or so, but will be back to help after 11 ET.

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl It sounds like getting UFS using ufs-community/ccpp-physics should be a higher priority? @ChunxiZhang-NOAA Is this something you could get done by tomorrow?

**Comment by ChunxiZhang-NOAA** [comment]
@grantfirl @BrianCurtis-NOAA I thought this PR would be merged **AFTER** the fv3atm pointed to ufs-community/ccpp-physics ufs/dev branch. Currently, I am still waiting for Dustin's PR[#956](https://github.com/NCAR/ccpp-physics/pull/956). If this PR is not ready by the end of day today, I will just go ahead and sync the ufs/dev branch with NCAR/main, then create a PR to make fv3atm point to ufs/dev.

**Comment by dustinswales** [comment]
@ChunxiZhang-NOAA @jkbk2004 @grantfirl I suggest to proceed without[#956](https://github.com/NCAR/ccpp-physics/pull/956). 
It's not a critical PR, just cleanup, and I'm still having some issues with two RTs that aren't matching the baselines.

**Comment by ChunxiZhang-NOAA** [comment]
@dustinswales @jkbk2004 @grantfirl  Ok, I will start the transition process without [#956](https://github.com/NCAR/ccpp-physics/pull/956).

**Comment by BrianCurtis-NOAA** [comment]
@dustinswales 
> I suggest to proceed without[#956](https://github.com/NCAR/ccpp-physics/pull/956). It's not a critical PR, just cleanup, and I'm still having some issues with two RTs that aren't matching the baselines.

You may want to compare the outputs manually. It may lead you into finding if its a code issue or if new baselines need to be generated because of your changes.

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA All of the submodules have been updated after Chunxi made the switch to use the ufs-community/ufs/dev branch of ccpp-physics. This should be ready to test now if you'd like to return to it.

**Comment by jkbk2004** [comment]
@grantfirl There is still time. But we are considering to merge in #1453 to this PR. Its just one file change on jenkinsfile that has no impact to other tests.

**Comment by grantfirl** [comment]
> @grantfirl There is still time. But we are considering to merge in #1453 to this PR. Its just one file change on jenkinsfile that has no impact to other tests.

@jkbk2004 OK, that is fine with me. I'm waiting to update the PR branches associated with this one until #1437 is merged. If you would like me to update beforehand, just let me know.

**Comment by jkbk2004** [comment]
@grantfirl thanks so much! please, go ahead to combine in the change in @jessemcfarland #1453. I think it makes a sense to prepare since today is Friday.  #1437 is a bit heavy pr.

**Comment by grantfirl** [comment]
@jkbk2004 This PR and its submodule PRs have been updated to the latest development code, so it should be ready to test.

**Comment by jkbk2004** [comment]
@grantfirl @BrianCurtis-NOAA I will be away from desk next a few hours. Can you add new BL_DATE=20221017?

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl Your on the top of the commit queue. Please update to the latest develop in UFSWM and change the BL_DATE in rt.sh to 20221017.

**Comment by grantfirl** [comment]
OK, @BrianCurtis-NOAA I'll do this now.

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA Should be good to go now.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1051599583/20221017150025/ufs-weather-model
[BL] Error: Test compile_001 failed in run_compile failed 
[BL] Error: Test compile_002 failed in run_compile failed 
[BL] Error: Test compile_003 failed in run_compile failed 
[BL] Error: Test compile_004 failed in run_compile failed 
[BL] Error: Test compile_005 failed in run_compile failed 
[BL] Error: Test compile_006 failed in run_compile failed 
[BL] Error: Test compile_007 failed in run_compile failed 
[BL] Error: Test compile_008 failed in run_compile failed 
[BL] Error: Test compile_009 failed in run_compile failed 
[BL] Error: Test compile_010 failed in run_compile failed 
[BL] Error: Test compile_011 failed in run_compile failed 
[BL] Error: Test compile_012 failed in run_compile failed 
[BL] Error: Test compile_013 failed in run_compile failed 
[BL] Error: Test compile_014 failed in run_compile failed 
[BL] Error: Test compile_015 failed in run_compile failed 
[BL] Error: Test compile_016 failed in run_compile failed 
[BL] Error: Test compile_017 failed in run_compile failed 
[BL] Error: Test compile_018 failed in run_compile failed 
[BL] Error: Test compile_021 failed in run_compile failed 
[BL] Error: Test compile_022 failed in run_compile failed 
[BL] Error: Test compile_023 failed in run_compile failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1051599583/20221017200008/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1051599583/20221017220129/ufs-weather-model
[RT] Error: Test cpld_restart_bmark_p8 011 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by jkbk2004** [comment]
We will skip the test on Cheyenne. It will be down until Oct. 20. @grantfirl we can start merging process.

**Comment by grantfirl** [comment]
> We will skip the test on Cheyenne. It will be down until Oct. 20. @grantfirl we can start merging process.

OK, will do.

**Comment by grantfirl** [comment]
https://github.com/NOAA-EMC/fv3atm/pull/580 is ready for review/merge.

**Review by ChunxiZhang-NOAA — COMMENTED** [review]
Looks good.

**Comment by zach1221** [comment]
Jenkins-ci logs attached.
[ufs-weather-model » ort-docker-wrapper-pipeline » PR-1410 #5 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9814327/ufs-weather-model.ort-docker-wrapper-pipeline.PR-1410.5.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
@grantfirl we can merge in here with fv3atm hash update and reverting branch in gitmodules.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA @DusanJovic-NOAA We will skip cheyenne for this pr. Can you go ahead to approve?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
