### PR TITLE
Add valid time to the 6 tile cubed sphere grid history files

### LINKED ISSUE #1252: Add valid time to the 6 tile cubed sphere grid history files
## Description
In the PR#1073 (issue #1052), a "valid_time" variable was added to the model history files written out by the module_write_netcdf.F90 subroutine. However the 6 tile cubed sphere grid history files written out by the subroutine ESMFproto_FieldBundleWrite do not have the valid_time added yet.
 
### Solution
Code changes need to be added to ESMFproto_FieldBundleWrite to output "valid_time" variable.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. checkout ufs-weather-model develop branch.
2. run control_CubedSphereGrid test (cd ufs-weather-model/tests; ./rt.sh -n control_CubedSphereGrid )
3. Check out the output file (sfcf000.tile*.nc), there is no time_iso variable in it.

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

Add 'time_iso' variable to cubed sphere grid output when ESMF write routines are used. This variable has already been added to the parallel version of the netcdf write routine.
This PR includes changes from https://github.com/NOAA-EMC/fv3atm/pull/515

New regression test has been added that outputs history files with all 6 cubed sphere tiles in a single file.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1252

## Testing

How were these changes tested? Yes.
What compilers / HPCs was it tested with? Intel. Hera
Are the changes covered by regression tests? Yes.
Have the ufs-weather-model regression test been run? On what platform?
Will the code updates change regression test baseline? Yes. New netcdf variable has been added to the history files.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss2.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? Yes.
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/550

### CODE REVIEW

**Review by junwang-noaa — COMMENTED** [review]
Thanks for updating the code, the changes look good to me.

**Comment by DusanJovic-NOAA** [comment]
I had to revert commit that changes the calendar type from 'julian' to 'gregorian' because some restart (warm start) tests have calendar type set to julian in the input data:

```
$ find . -name coupler.res
./FV3_input_data384/INPUT_L127_GDAS/coupler.res
./FV3_input_data_conus13km/INPUT/coupler.res
./FV3_input_data_L149/INPUT/coupler.res

$ cat ./FV3_input_data384/INPUT_L127_GDAS/coupler.res
     2        (Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)
  2021  03  21  18     0     0        Model start time:   year, month, day, hour, minute, second
  2021  03  21  21     0     0        Current model time: year, month, day, hour, minute, second

$ cat ./FV3_input_data_conus13km/INPUT/coupler.res
     2        (Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)
  2021     5    12    16     0     0        Model start time:   year, month, day, hour, minute, second
  2021     5    12    16     0     0        Current model time: year, month, day, hour, minute, second

$ cat ./FV3_input_data_L149/INPUT/coupler.res
     2        (Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)
  2021     3    22     6     0     0        Model start time:   year, month, day, hour, minute, second
  2021     3    23     0     0     0        Current model time: year, month, day, hour, minute, second
```
Changing calendar will require new input data directory.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA Brian wants a bit more time with AQM PR. Can we start working on this PR to create new BL?

**Comment by DusanJovic-NOAA** [comment]
`control_CubedSphereGrid_parallel` test crashes on wcoss2 with this error:
```
ADIOI_CRAY_WRITECONTIG(243): filename='atmf000.nc' error='Bad address' errno=14 PE=00144 W_rec=00038 off=000000000
0 len=0000001021 See MPICH_MPIIO_ABORT_ON_RW_ERROR.                                                                  
 file: module_write_netcdf.F90 line:         450 NetCDF: HDF error                                                    
MPICH Notice [Rank 144] [job id d832cad5-4e30-4665-a7df-8948dcaf4b5b] [Thu Jun 23 13:17:32 2022] [nid001413] - Abort(1)
 (rank 144 in comm 496): application called MPI_Abort(comm=0x84000001, 1) - process 144
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/963206649/20220623180009/ufs-weather-model
[BL] Error: Test hafs_global_1nest_atm 082 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn 086 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/963206649/20220623180021/ufs-weather-model
[BL] Error: Test control_csawmg_debug 051 failed in run_test failed 
[BL] Error: Test control_thompson_debug 056 failed in run_test failed 
[BL] Error: Test regional_debug 060 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_ocn_wav 078 failed in run_test failed 
[BL] Error: Test datm_cdeps_iau_gefs 084 failed in run_test failed 
[BL] Error: Test datm_cdeps_stochy_gefs 085 failed in run_test failed 
[BL] Error: Test datm_cdeps_bulk_gefs 087 failed in run_test failed 
[BL] Error: Test datm_cdeps_mx025_cfsr 088 failed in run_test failed 
[BL] Error: Test datm_cdeps_3072x1536_cfsr 090 failed in run_test failed 
[BL] Error: Test datm_cdeps_gfs 091 failed in run_test failed 
[BL] Error: Test compile_006 failed in run_compile failed 
[BL] Error: Test compile_017 failed in run_compile failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
WCOSS_Dell_P3 on baseline creation: + echo 'Test cpld_debug_noaero_p8 007 failed in run_test failed '
Test cpld_debug_noaero_p8 007 failed in run_test failed
```
+ echo 'Test cpld_debug_noaero_p8 007 failed in run_test failed '
+ read -r failed_test_name
+ echo 'Test control_stochy_debug 051 failed in run_test failed '
Test control_stochy_debug 051 failed in run_test failed
+ echo 'Test control_stochy_debug 051 failed in run_test failed '
+ read -r failed_test_name
+ echo 'Test rap_rrtmgp_debug 071 failed in run_test failed '
Test rap_rrtmgp_debug 071 failed in run_test failed
+ echo 'Test rap_rrtmgp_debug 071 failed in run_test failed '
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/963206649/20220624130021/ufs-weather-model
[RT] Error: Test rrfs_v1beta 058 failed in check_result failed 
[RT] Error: Test rrfs_v1beta 058 failed in run_test failed 
[RT] Error: Test control_ras 067 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA we need to copy over two BL files on jet. @DeniseWorthen all test passed. You can leave final comments and approve the PR.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we are ready to merge fv3atm PR.

**Comment by DeniseWorthen** [comment]
@jkbk2004 What did you mean when you told Brian "we need to copy over two BL files on jet"?

**Comment by jkbk2004** [comment]
> @jkbk2004 What did you mean when you told Brian "we need to copy over two BL files on jet"?

I recreated two BL files on jet (control_ras  rrfs_v1beta) and passed ok now.

**Comment by jkbk2004** [comment]
> > @jkbk2004 What did you mean when you told Brian "we need to copy over two BL files on jet"?
> 
> I recreated two BL files on jet (control_ras rrfs_v1beta) and passed ok now.

Everything ready to merge the fv3atm PR and update pointers.

**Comment by DeniseWorthen** [comment]
@jkbk2004 So the initial baselines for those two tests were not reproducible when we first ran the verification RT? Do we know why?

**Comment by jkbk2004** [comment]
> /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/963206649/20220624130021/ufs-weather-model

fv_core.res.tile4.nc ............ALT CHECK......NOT OK ?

**Comment by jkbk2004** [comment]
> > /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/963206649/20220624130021/ufs-weather-model
> 
> fv_core.res.tile4.nc ............ALT CHECK......NOT OK ?

nccmp tells some of variables do not exist in those initial BL files. Somehow jet got trouble to correctly finish up writing out files.
Jet system issue.

**Comment by jkbk2004** [comment]
@DeniseWorthen can we merge in Dusan's fv3atm PR? we need one more approval there.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Ready for merge.

**Pull request merged**
