### PR TITLE
Add PIO switch to WW3 to avoid build errors

### LINKED ISSUE #2502: WW3 cannot build pre-and-post processing jobs
## Description
In PR https://github.com/ufs-community/ufs-weather-model/pull/2445 WW3 was updated with PR https://github.com/NOAA-EMC/WW3/pull/1303 which makes references to modules that are only in the cap code.  This means that we cannot run the end-to-end system (for example see: https://github.com/NOAA-EMC/global-workflow/pull/3106#issuecomment-2484169044).  

We will need ot make an update to WW3 so that we can compile the pre-and post-scripts within the dev/ufs-weather-model.  

### To Reproduce:
The easiest way to reproduce this is to clone the g-w, update the model to the hash in develop and then build all or just the ww3 pre/post: 

```
git clone https://github.com/noaA-EMC/global-workflow
cd global-workflow/
git submodule update --init --recursive 
cd sorc/ufs_model.fd/
git checkout develop
git submodule update --init --recursive 
cd ../
./build_ww3prepost.sh 
```

## Additional context
@sbanihash had noticed this while reviewing a PR    FYI @jswhit who ran into this in g-w. 

@sbanihash and myself will be meeting with @MatthewMasarik-NOAA first thing tomorrow morning to find a solution.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR updates the WW3 submodule to address a build issue that arose in PR    

This fixes https://github.com/ufs-community/ufs-weather-model/issues/2502

### Commit Message:

```
* UFSWM -  updates WW3 subcomponent
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - 
    * ccpp-physics - 
    * atmos_cubed_sphere - 
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 -  Updated to add PIO switch to avoid build error 
  * fire_behavior
  * stochastic_physics - 
```
Update WW3 to add PIO switch to avoid build error. 

### Priority:

* Critical Bugfix: The workflow cannot update to the latest version of ufs-weather-model until the WW3 build issue is addressed. 

### UFSWM:

* Closes #2502

### Sub component Pull Requests:

* WW3: https://github.com/NOAA-EMC/WW3/pull/1324

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Note this was also tested in g-w with 1 test.  G-W branch is here: https://github.com/JessicaMeixner-NOAA/global-workflow/tree/bug/addPIOswitch 
And output of test is here: /work2/noaa/marine/jmeixner/hercules/piogw/test04 (it's still going, but it's far enough along to say that it worked).  Standalone WW3 regression tests were also run. Details in the WW3 PR.

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004  - Is there anything else I need to do on my end other than keep this PR up to date with the top of develop?   In my opinion, this PR can be combined with whatever make sense to others.  Just let me know if there are other things I can do from my end.    Note I will be on leave Wed-Friday but will be back on Monday.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA We will schedule to bring this pr in early next week: Monday or Tuesday.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @jkbk2004  - Please let me know if there's anything I need to do from my end.

**Comment by jkbk2004** [comment]
merged with #2483

**Pull request closed without merging**
