### PR TITLE
Fix out-of-bounds access in module_diag_hailcast.F90 which crashes RRFS on WCOSS2

### LINKED ISSUE #1814: Typo when setting DO_MYJPBL to true in certain RTs
## Description
Some of the regression tests list `DO_MYJPBL=.true` (no period after `.true`). It seems like this might not successfully set DO_MYJPBL to true. Thus far, this typo appears in: 

- rrfs_conus13km_hrrr_warm
- rrfs_conus13km_hrrr_warm_restart_mismatch
- rrfs_smoke_conus13km_hrrr_warm_debug
- rrfs_smoke_conus13km_hrrr_warm_debug_2threads
- rrfs_smoke_conus13km_radar_tten_warm

It may also appear in other tests, although these are the ones where I noticed it. 

### To Reproduce:
Look at the code! ;) 
I am unclear on what the actual effect of this typo is on results, so someone else may want to run these tests and see if DO_MYJPBL is actually getting set to true or if the default `.false.` value remains because `.true` is invalid. 

## Additional context
This may need to be fixed in other RTs; someone will need to verify. 

## Output
N/A

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [x] Add list of all failed regression tests in "Regression Tests" section.

### Description
Fixes a bug that can crash the RRFS ensembles. When KBAS=1, there's an out-of-bounds write in an array. That corrupts memory and occasionally crashes the model.

Also, I remove from default_vars.sh the unused DO_MYJPBL variable whose value contains a typo.

### Commit Message

```
Eliminate an out-of-bounds write in FV3 dynamical core hail diagnostic code.

FV3 component GFDL_atmos_cubed_sphere submodule:

The module_diag_hailcast.F90 has a KBAS index which can have the value of 1. When it has that value, a later line writes to address 0 of a 1-based array. This caused the RRFS ensemble to crash on WCOSS2.
```

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [x] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Git Issues Fixed By This PR

- fixes https://github.com/ufs-community/ufs-weather-model/issues/1814

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3: https://github.com/NOAA-EMC/fv3atm/pull/746
    - [x] GFDL_atmos_cubed_sphere: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/308
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.

### Regression Tests:
- [x] No changes are expected to any regression test.

</details>

### Libraries

- [x] Not Needed

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
This is a draft because I discovered I used the wrong fix. I need to do this instead:

```diff
-    DO k=KBAS,nz
+    DO k=KBAS+1,nz
        RWA_new(k) = RWA_new(k) / (h1d(k)-h1d(k-1))
     ENDDO
 ```

I'm testing this now on WCOSS2 and Hera.

**Comment by SamuelTrahanNOAA** [comment]
The correct fix works too. This is ready for review.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA do you think we can combine this pr to @dustinswales 's #2035 ? All no baseline changes. For this pr, just need to point to the cubed-sphere branch.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA do you think we can combine this pr to @dustinswales 's #2035 ? All no baseline changes. For this pr, just need to point to the cubed-sphere branch.

This PR needs more testing and review before it can be merged. The original developer of the code needs to confirm my fix is correct. Also, the parallels are still testing the change.

**Comment by SamuelTrahanNOAA** [comment]
I've changed this to a draft to reflect the fact that it needs more review.

**Comment by SamuelTrahanNOAA** [comment]
There are more errors in the module_diag_hailcast.F90 code than I first thought. I'm waiting to hear back from the original developer about how to fix them.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - This has been ready for review for several days. I forgot to mark it so.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA can you sync up branch? wcoss2 file system maintenance this week. So we may go ahead with no baseline change PR first.

**Comment by SamuelTrahanNOAA** [comment]
>  can you sync up branch? wcoss2 file system maintenance this week. So we may go ahead with no baseline change PR first.

@jkbk2004 - Yes, it is up to date now.

**Comment by jkbk2004** [comment]
@zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA FYI: this PR is ready.

**Comment by BrianCurtis-NOAA** [comment]
If we're skipping WCOSS2 we can't properly test this PR, right?

**Comment by jkbk2004** [comment]
> If we're skipping WCOSS2 we can't properly test this PR, right?

@BrianCurtis-NOAA @SamuelTrahanNOAA I think we should move on to merge this PR even only with RDHPCS tests. Government shutdown risk is not still cleared out. In that case, GFDL feds will not be available.

**Comment by SamuelTrahanNOAA** [comment]
> > If we're skipping WCOSS2 we can't properly test this PR, right?
> 
> @BrianCurtis-NOAA @SamuelTrahanNOAA I think we should move on to merge this PR even only with RDHPCS tests. Government shutdown risk is not still cleared out. In that case, GFDL feds will not be available.

There has been some minimal testing on WCOSS with RRFS. That isn't as thorough as a regression test.

Is Acorn available?

**Comment by BrianCurtis-NOAA** [comment]
> > > If we're skipping WCOSS2 we can't properly test this PR, right?
> > 
> > 
> > @BrianCurtis-NOAA @SamuelTrahanNOAA I think we should move on to merge this PR even only with RDHPCS tests. Government shutdown risk is not still cleared out. In that case, GFDL feds will not be available.
> 
> There has been some minimal testing on WCOSS with RRFS. That isn't as thorough as a regression test.
> 
> Is Acorn available?

@SamuelTrahanNOAA was this issue also on Acorn. I would be OK if the WCOSS2 issue is present here, and using the Acorn RT to confirm it's fixed.

**Comment by SamuelTrahanNOAA** [comment]
> > > > If we're skipping WCOSS2 we can't properly test this PR, right?
> > > 
> > > 
> > >  I think we should move on to merge this PR even only with RDHPCS tests. Government shutdown risk is not still cleared out. In that case, GFDL feds will not be available.
> > 
> > 
> > There has been some minimal testing on WCOSS with RRFS. That isn't as thorough as a regression test.
> > Is Acorn available?
> 
>  was this issue also on Acorn. I would be OK if the WCOSS2 issue is present here, and using the Acorn RT to confirm it's fixed.

I'm more concerned about whether the results change for other tests.

We know this doesn't stop all the crashes. That's why Anning has another fix. There's a bug fix in the DA code. Most likely, there'll be a dozen more bug fixes before this is operational.

**Comment by SamuelTrahanNOAA** [comment]
I've retested it with one of the failing cases. The test was on Hera, but it fails in debug mode reliably on Hera without the fix.

The latest fix still works.

**Comment by BrianCurtis-NOAA** [comment]
For now, Acorn is a full pass. Not happy with these long term WCOSS2 outages

**Comment by SamuelTrahanNOAA** [comment]
> For now, Acorn is a full pass. Not happy with these long term WCOSS2 outages

Acorn was created to lessen the impact of these outages, and also security concerns. WCOSS2's predecessors didn't have a mid-sized test system. You are witnessing the Acorn test machine serving its intended purpose.

**Comment by jkbk2004** [comment]
OK! I think we can move on for merging process. @SamuelTrahanNOAA I am moving to https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/308 to ask merging there.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA FV3 pr was merged.

**Comment by SamuelTrahanNOAA** [comment]
I've reverted the .gitmodules changes and updated the FV3 hash to NOAA-EMC develop's head.

This PR is ready for final review and merge.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
