### PR TITLE
Update CDEPS tests with GEFS forcing

### LINKED ISSUE #1770: SW rad appears shifted in CDEPS gefs forcing
## Description

In the CDEPS-datm tests, the input gefs forcing appears to be time shifted.

### To Reproduce:

Compare the ``dswrf`` at a point on 0E in the input files for the cdeps control ``cfsr``, ``gefs`` and ``gfs`` regression tests. The strongest SW down should be at hour 12.

For the GFS input data at 0E, 10N, with the hour=12 value marked:

Screen Shot 2023-05-26 at 12 28 46 PM

The same figure for the CFSR (black) and GEFS (red), also with hour=12 marked:

Screen Shot 2023-05-26 at 12 32 16 PM

For GEFS, the highest SW value occurs at hour=18.

### PR DESCRIPTION
**Pull request by binli2337**
## Description
The shortwave radiation fields in the GEFS forcing file show that the maximum incoming shortwave radiation fields do not occur at local noon but at 18:00 local time. The stream_offset parameter in the datm.streams file will be used to make the 6-hour time shift.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
datm_cdeps_control_gefs
datm_cdeps_iau_gefs
datm_cdeps_stochy_gefs
datm_cdeps_bulk_gefs
datm_cdeps_mx025_gefs

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Closes #1770 

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
RegressionTests_hera

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@binli2337 Unless you are using these settings, would you consider setting these both to 0 ? The verbosity especially makes the PET logs unreadable.

https://github.com/ufs-community/ufs-weather-model/blob/5d47ea8b820596930e5d82a486b8bf97c4c283bc/tests/parm/nems.configure.datm_cdeps.IN#L94-L95

**Comment by binli2337** [comment]
@DeniseWorthen The nems.configure.datm_cdeps.IN file has been updated.

**Comment by binli2337** [comment]
[RegressionTests_hera.txt](https://github.com/ufs-community/ufs-weather-model/files/11780237/RegressionTests_hera.txt)

**Comment by FernandoAndrade-NOAA** [comment]
@binli2337 Just a note that we'll start working on this PR after #1769 is complete and merged in, we're waiting on some final RT results before getting started with the merging process.

**Comment by FernandoAndrade-NOAA** [comment]
#1769 was merged in, please go ahead and sync with develop. Thank you
@binli2337

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA Just a heads up, getting started with jenkins ci testing for this PR

**Comment by FernandoAndrade-NOAA** [comment]
jenkins ci has completed with cpld_control_nowave_noaero_p8 failing, verifying with a manual run on hera to see if it's a pipeline issue. Otherwise, other tests pass.

**Comment by FernandoAndrade-NOAA** [comment]
Attached jenkins ci log. cpld_control_nowave_noaero_p8 dbg fails due to the time limit. bit, dcp, rst, and std pass in the manual run on Hera @zach1221 fyi
[ufs-weather-model » ort-docker-pipeline » PR-1776 #1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/11828605/ufs-weather-model.ort-docker-pipeline.PR-1776.1.Console.Jenkins.txt)

**Comment by BrianCurtis-NOAA** [comment]
I've started the Acorn testing, WCOSS2 is unavailable today, so since the changing tests are skipped on WCOSS2, there is essentially no baseline change and skipping it shouldn't cause any issues.

**Comment by zach1221** [comment]
@FernandoAndrade-NOAA the dbg ORT timeout error is a known issue, where investigation is on-going I believe. You have to increase wall-clock to get it to pass. If that is the only failure I think you can move on to the regression testing.

**Comment by zach1221** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1374669447/20230622101838/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_57905
Please make changes and add the following label back: cheyenne-BL

**Comment by zach1221** [comment]
***Automated RT Failure Notification***
Machine: jet
Job: BL
Repo location: /lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1374669447/20230622161905/ufs-weather-model
Please manually delete: /lfs4/HFIP/hfv3gfs/role.epic/RT_RUNDIRS/role.epic/FV3_RT/rt_290380
/lfs4/HFIP/hfv3gfs/role.epic/RT/NEMSfv3gfs/develop-20230621
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back: jet-BL

**Comment by DeniseWorthen** [comment]
What is the issue with Jet and Cheyenne jobs? Why is it finding a baseline already created?

**Comment by FernandoAndrade-NOAA** [comment]
Creating baseline manually on Jet in the meantime while we figure out what's going on with Cheyenne and Jet

**Comment by zach1221** [comment]
The first jobs failed part way through because they were started without a token I think, so I started them again but the baseline directories were already created. I'll get it taken care of.

**Comment by zach1221** [comment]
Apologies for the delay. Testing is finished, we'll proceed now with final reviews.

**Review by sadeghitabas — APPROVED** [review]

**Comment by jkbk2004** [comment]
Ok! all tests are done. Please go ahead for approvals.

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
