### PR TITLE
fix nstf setting for coupled model, update atm aerosol test to use P8 configuration

### LINKED ISSUE #879: Adjust NSTF_NAME for coupled tests
## Description

The NSTF_NAME for the coupled control tests (all resolutions) uses ``NSTF_NAME=2,1,0,0,0``. The restart tests use ``NSTF_NAME=2,0,0,0,0``. Since the ICs used for the P7 tests do not need to spinup the nst model, we should use no-spinup for both the control and restart tests.

## Solution
For coupled model, set the default value ``NSTF_NAME=2,0,0,0,0``. Remove the setting of ``NSTF_NAME=2,0,0,0,0`` in coupled restart tests.

### LINKED ISSUE #1216: DOGP_LWSCAT is set incorrectly for cpld*p8 tests
## Description

In the coupled section of default_vars for the coupled model, the variable `` DOGP_LWSCAT`` is set as ``.true``, which does not provide the correct logical flag of "T".  

```
# P8 RRTMGP
export DO_RRTMGP=.false.
export DOGP_CLDOPTICS_LUT=.true.
export DOGP_LWSCAT=.true
export DOGP_SGS_CNV=.true.
```

The control_p8 tests set this variable manually within each P8 test, and it appears to be set correctly as ``.true.`` in all standalone P8 tests.

### LINKED ISSUE #1219: Update atm_aerosol test to use P8 configuration
## Description

The  atm_aerosol test is not current with the P8 configuration. For debugging purposes, it is helpful to have a non-coupled RT which exercises the Aerosol configuration used in the prototypes. 

## Solution

Update the atm_aerosol test to the current P8 configuration.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #879 
- fixes #1219 
- fixes #1216 

## Testing

This branch was tested against the existing ``develop-20220517`` at 062a0fd for both hera.intel and hera.gnu. The following tests failed, as expected:

- all cpld tests (bug fix for ``DOGP_LWSCAT`` and change to ``NSTF_NAME``)
- atmaero_control_p8 (new test; no baseline)

For the new ``atmaero_control_p8`` test, the ``input.nml`` and aerosol rc files were compared against the existing ``cpld_control_p8`` test. The files were identical except for the following 
```
<   ccpp_suite = 'FV3_GFS_v17_p8'
---
>   ccpp_suite = 'FV3_GFS_v17_coupled_p8'
26c26
<   domains_stack_size = 3000000
---
>   domains_stack_size = 8000000
150,151c150,151
<   min_seaice   = 0.15
<   use_cice_alb = .false.
---
>   min_seaice   = 1.0e-6
>   use_cice_alb = .true.
227,230c227,230
<   cplflx       = .false.
<   cplice       = .false.
<   cplwav       = .false.
<   cplwav2atm   = .false.
---
>   cplflx       = .true.
>   cplice       = .true.
>   cplwav       = .true.
>   cplwav2atm   = .true.
```

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] wcoss2
- [x] opnReqTest for newly added/changed feature. Tested at cc508eeb, the ``atmaero_control_p8`` test passed bit_base, dbg_base, dcp, fhz, mpi, rst, std_base and thr oRT tests.
- [ ] CI

## Dependencies

None. Script level changes only.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@ChunxiZhang-NOAA The new ``atmaero_control_p8`` test passed all the oRTs.

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA The new `atmaero_control_p8` test passed all the oRTs.

Great to know!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/936244575/20220531193016/ufs-weather-model
[BL] Error: Test hafs_regional_docn 072 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/936244575/20220531143016/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/936244575/20220531152913/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by DeniseWorthen** [comment]
Most orion jobs seemed to have run OK, but 5 reported failure with same error. When looking at the actual run directories though, all these seemed to have completed.

```
Error: request( chd:label job_status 'running' /regtest_213621/regional_control ) failed! Server replied with: EOF(Server did not reply or mixing ssl and non-ssl)
```

The log file for the tests that passed did not get created, so I will re-run the RT job.

**Comment by DeniseWorthen** [comment]
I've gotten the same compile error twice on Dell-P3 for the ATMW job:
```
ifort: error #10105: /gpfs/dell1/usrx/local/prod/intel/2018UP04/compilers_and_libraries_2018.5.274/linux/bin/intel64/fortcom: core dumped
ifort: warning #10102: unknown signal(1080568304)
ifort: error #10106: Fatal error in /gpfs/dell1/usrx/local/prod/intel/2018UP04/compilers_and_libraries_2018.5.274/linux/bin/intel64/fortcom, terminated by unknown
compilation aborted for /gpfs/dell2/emc/modeling/noscrub/Denise.Worthen/ufs-weather-model/WW3/model/src/w3iogomd.F90 (code 1)
make[2]: *** [WW3/model/src/CMakeFiles/ww3_lib.dir/w3iogomd.F90.o] Error 1
make[1]: *** [WW3/model/src/CMakeFiles/ww3_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
ifort: error #10105: /gpfs/dell1/usrx/local/prod/intel/2018UP04/compilers_and_libraries_2018.5.274/linux/bin/intel64/fortcom: core dumped
ifort: warning #10102: unknown signal(-1688806928)
ifort: error #10106: Fatal error in /gpfs/dell1/usrx/local/prod/intel/2018UP04/compilers_and_libraries_2018.5.274/linux/bin/intel64/fortcom, terminated by unknown
compilation aborted for /gpfs/dell2/emc/modeling/noscrub/Denise.Worthen/ufs-weather-model/FV3/io/module_write_netcdf.F90 (code 1)
make[2]: *** [FV3/CMakeFiles/fv3atm.dir/io/module_write_netcdf.F90.o] Error 1
make[1]: *** [FV3/CMakeFiles/fv3atm.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by BrianCurtis-NOAA** [comment]
What was the issue with Dell P3 and Orion?

**Comment by DeniseWorthen** [comment]
Dell-P3 compiled on the third try. I'm not sure what the error meant on orion. I don't think I've seen that one before.

**Comment by DeniseWorthen** [comment]
Original labels on Cheyenne don't seem to have started, so re-trying.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/936244575/20220531223017/ufs-weather-model
[RT] Error: Test rap_sfcdiff_debug 083 failed in run_test failed 
[RT] Error: Test hafs_regional_docn_oisst 093 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by DeniseWorthen** [comment]
On jet.intel, the hafs failure was a timeout. The rap_sfcdiff_debug test failed with 
```
144:  file: module_write_netcdf.F90 line:          207 Permission denied
144: Abort(1) on node 144 (rank 144 in comm 496): application called MPI_Abort(comm=0x84000002, 1) - process 144
```
The job appeared to actually run but failed writing something at Finalize.

**Comment by DeniseWorthen** [comment]
On Cheyenne.intel, a lot of baseline jobs have failed. They all seem to be associated with the same error in the run_*.log:

```
run_001_cpld_control_p8.log:chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

and then later

```
322 min. TEST 001 cpld_control_p8 is waiting in a queue,  status: Q jobid 4476288
run_test.sh terminated PID=34571
++ [[ pbs = \p\b\s ]]
++ echo 'run_util.sh: interrupt_job qsub_id = 4476288'
run_util.sh: interrupt_job qsub_id = 4476288
```

**Comment by BrianCurtis-NOAA** [comment]
Didn't Cheyenne tend to kill pbs jobs at the midnight time for that machine? 5 hours and 22 minutes is a long time to run too. I' have never seen that Cheyenne error before, though.

**Comment by DeniseWorthen** [comment]
I put in a ticket to the help desk on Cheyenne. The job Q seems stuck---just a few jobs running but almost all are just sitting in the Q (not just mine). 

(edit: I started the jobs manually on Cheyenne early this morning)

**Comment by climbfuji** [comment]
1pm MT I think is when it kills jobs started by cron … jobs in the queue or running in PBS aren’t affected, but the auto-rt/rt.sh scripts are.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/936244575/20220601094513/ufs-weather-model
[BL] Error: Test atmaero_control_p8 098 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by DeniseWorthen** [comment]
I think I need to increase resources on cheyenne.intel for the new atmaero p8 test

```
0:  ... DONE microphysical lookup tables
108:MPT ERROR: Could not register RMA window with the HCA. There may not be
108:    enough memory.
108:MPT ERROR: Rank 108(g:108) is aborting with error code 0.
108:    Process ID: 60233, Host: r3i6n6, Program: /glade/scratch/epicufsrt/FV3_RT/rt_30952/atmaero_control_p8/fv3.exe
108:    MPT Version: HPE MPT 2.25  08/14/21 03:05:20
```

**Comment by DeniseWorthen** [comment]
All RTs are finished.

**Review by junwang-noaa — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@MinsukJi-NOAA Please review

**Pull request merged**
