### PR TITLE
Update CDEPS component; update documentation FAQ about setting resources and turning off output; update FAQ documentation (was 1608); update drag suite intent mods (was 1612) 

### LINKED ISSUE #1593: Update CDEPS component
## Description

 The NOAA-EMC/CDEPS will be updated to include a few recent changes from ESCOMP/CDEPS. The CDEPS component in the ufs-weather-model will be updated at the same time.

## Related to

- CDEPS issue: https://github.com/NOAA-EMC/CDEPS/issues/51
- CDPES PR: https://github.com/NOAA-EMC/CDEPS/pull/52

### PR DESCRIPTION
**Pull request by binli2337**
## Description
The NOAA-EMC/CDEPS will be updated to include recent changes from ESCOMP/CDEPS. The CDEPS component in the ufs-weather-model will be updated at the same time.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [x] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):
- Closes #1608 
- Closes #1612 

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Depends on NOAA-EMC/CDEPS/pull/52
- Depends on NOAA-EMC/fv3atm/pull/627
- Depends on ufs-community/ccpp-physics/pull/40
- Closes #1593   

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [x] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by binli2337** [comment]
@jkbk2004 The "test/update_cdeps" branch has been updated.

**Comment by jkbk2004** [comment]
> @jkbk2004 The "test/update_cdeps" branch has been updated.

Thanks, @binli2337 We are considering to combine this pr with #1612 and #1608. We are trying to make a progress on #1529 today. I will keep you posted.

**Comment by jkbk2004** [comment]
@binli2337 It's likely we will merge in #1529 this afternoon. After the merge, can we coordinate to combine in #1608 and #1612 to this pr?

**Comment by jkbk2004** [comment]
@binli2337 we just merged #1529. As noted before, we will try to combine in #1608 and #1612 to this pr. #1608 is doc update. So @DeniseWorthen will create a direct pr to your branch. For #1612, you can point to the fv3 branch.

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1228090127/20230221024514/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
hera gnu issue was srun time out problem.

**Comment by zach1221** [comment]
Please see Jenkins-ci logs attached. All tests passed.
[ufs-weather-model » ort-docker-pipeline » PR-1597 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10796083/ufs-weather-model.ort-docker-pipeline.PR-1597.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
All tests are done successfully. We can start merging process.

**Comment by jkbk2004** [comment]
@binli2337 fv3 pr was merged. new hash is https://github.com/NOAA-EMC/fv3atm/commit/d9e619ed4a5e685b3558e0b1bf6929880960864b

can you update the submodule pointer and revert changes in gitmodules?

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
