### PR TITLE
Few small fixes to Thompson MP

### PR DESCRIPTION
**Pull request by grantfirl**
## Description
(Description from @gthompsnWRF)

This PR includes 3 small fixes to Thompson microphysics:

1. The minimum size of snow was increased (some months ago) but it was noted that the min size of snow is used to determine the upper-most size bin of cloud ice.  It was set to 5 times the min size of snow, which is exceedingly large for the cloud ice category.  Therefore, the constant was reduced to 2 - making cloud ice largest size bin of 600 microns which is plenty big enough, giving more resolution to all the ice size bins.

2. In testing RRFS with @ericaligo-NOAA and @RuiyuSun for a specific case study, it was noted that rain was evaporating with a large rate producing a temperature tendency of 27C/hour.  We traced the issue to an extremely large number of rain drops that appears to be produced by colliding rain and graupel - which has an explicit drop breakup (splash if you will) from the collisions making 5 drops per collision.  This was forcing the rain (formed by melting graupel) to tends towards 500 microns (0.5 mm) which is too small.  So the constant used for collisions was reduced to 1.5 in an effort to keep rain larger (thus reducing evaporation).
 
3. There was an oversight in the code for melting snow and graupel.  When RH is below saturation, the wetbulb temperature could be below 0C in which case ice does not melt.  Instead, the ice (snow/graupel) will sublimate first until wetbulb temperature goes above melting.  So the code fix now enforces that either melting occurs or sublimation, not both.

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [X] Changes are expected to the following tests: 

<details><summary>Tests effected by changes in this PR:</summary>
001 cpld_control_p8_mixedmode_intel failed in check_result
cpld_control_p8_mixedmode_intel 001 failed in run_test
002 cpld_control_gfsv17_intel failed in check_result
cpld_control_gfsv17_intel 002 failed in run_test
003 cpld_control_p8_intel failed in check_result
cpld_control_p8_intel 003 failed in run_test
005 cpld_control_qr_p8_intel failed in check_result
cpld_control_qr_p8_intel 005 failed in run_test
007 cpld_2threads_p8_intel failed in check_result
cpld_2threads_p8_intel 007 failed in run_test
008 cpld_decomp_p8_intel failed in check_result
cpld_decomp_p8_intel 008 failed in run_test
009 cpld_mpi_p8_intel failed in check_result
cpld_mpi_p8_intel 009 failed in run_test
010 cpld_control_ciceC_p8_intel failed in check_result
cpld_control_ciceC_p8_intel 010 failed in run_test
011 cpld_control_c192_p8_intel failed in check_result
cpld_control_c192_p8_intel 011 failed in run_test
013 cpld_bmark_p8_intel failed in check_result
cpld_bmark_p8_intel 013 failed in run_test
015 cpld_control_noaero_p8_intel failed in check_result
cpld_control_noaero_p8_intel 015 failed in run_test
016 cpld_control_nowave_noaero_p8_intel failed in check_result
cpld_control_nowave_noaero_p8_intel 016 failed in run_test
017 cpld_debug_p8_intel failed in check_result
cpld_debug_p8_intel 017 failed in run_test
018 cpld_debug_noaero_p8_intel failed in check_result
cpld_debug_noaero_p8_intel 018 failed in run_test
019 cpld_control_noaero_p8_agrid_intel failed in check_result
cpld_control_noaero_p8_agrid_intel 019 failed in run_test
020 cpld_control_c48_intel failed in check_result
cpld_control_c48_intel 020 failed in run_test
021 cpld_control_p8_faster_intel failed in check_result
cpld_control_p8_faster_intel 021 failed in run_test
022 cpld_control_pdlib_p8_intel failed in check_result
cpld_control_pdlib_p8_intel 022 failed in run_test
025 cpld_debug_pdlib_p8_intel failed in check_result
cpld_debug_pdlib_p8_intel 025 failed in run_test
040 control_p8_intel failed in check_result
control_p8_intel 040 failed in run_test
042 control_qr_p8_intel failed in check_result
control_qr_p8_intel 042 failed in run_test
044 control_decomp_p8_intel failed in check_result
control_decomp_p8_intel 044 failed in run_test
045 control_2threads_p8_intel failed in check_result
control_2threads_p8_intel 045 failed in run_test
046 control_p8_lndp_intel failed in check_result
control_p8_lndp_intel 046 failed in run_test
047 control_p8_rrtmgp_intel failed in check_result
control_p8_rrtmgp_intel 047 failed in run_test
048 control_p8_mynn_intel failed in check_result
control_p8_mynn_intel 048 failed in run_test
049 merra2_thompson_intel failed in check_result
merra2_thompson_intel 049 failed in run_test
050 regional_control_intel failed in check_result
regional_control_intel 050 failed in run_test
052 regional_control_qr_intel failed in check_result
regional_control_qr_intel 052 failed in run_test
054 regional_decomp_intel failed in check_result
regional_decomp_intel 054 failed in run_test
055 regional_2threads_intel failed in check_result
regional_2threads_intel 055 failed in run_test
056 regional_noquilt_intel failed in check_result
regional_noquilt_intel 056 failed in run_test
057 regional_netcdf_parallel_intel failed in check_result
regional_netcdf_parallel_intel 057 failed in run_test
058 regional_2dwrtdecomp_intel failed in check_result
regional_2dwrtdecomp_intel 058 failed in run_test
060 rap_control_intel failed in check_result
rap_control_intel 060 failed in run_test
061 regional_spp_sppt_shum_skeb_intel failed in check_result
regional_spp_sppt_shum_skeb_intel 061 failed in run_test
062 rap_decomp_intel failed in check_result
rap_decomp_intel 062 failed in run_test
063 rap_2threads_intel failed in check_result
rap_2threads_intel 063 failed in run_test
065 rap_sfcdiff_intel failed in check_result
rap_sfcdiff_intel 065 failed in run_test
066 rap_sfcdiff_decomp_intel failed in check_result
rap_sfcdiff_decomp_intel 066 failed in run_test
068 hrrr_control_intel failed in check_result
hrrr_control_intel 068 failed in run_test
069 hrrr_control_qr_intel failed in check_result
hrrr_control_qr_intel 069 failed in run_test
070 hrrr_control_decomp_intel failed in check_result
hrrr_control_decomp_intel 070 failed in run_test
071 hrrr_control_2threads_intel failed in check_result
hrrr_control_2threads_intel 071 failed in run_test
074 rrfs_v1beta_intel failed in check_result
rrfs_v1beta_intel 074 failed in run_test
077 rrfs_smoke_conus13km_hrrr_warm_intel failed in check_result
rrfs_smoke_conus13km_hrrr_warm_intel 077 failed in run_test
078 rrfs_smoke_conus13km_hrrr_warm_qr_intel failed in check_result
rrfs_smoke_conus13km_hrrr_warm_qr_intel 078 failed in run_test
079 rrfs_smoke_conus13km_hrrr_warm_2threads_intel failed in check_result
rrfs_smoke_conus13km_hrrr_warm_2threads_intel 079 failed in run_test
080 rrfs_conus13km_hrrr_warm_intel failed in check_result
rrfs_conus13km_hrrr_warm_intel 080 failed in run_test
081 rrfs_smoke_conus13km_radar_tten_warm_intel failed in check_result
rrfs_smoke_conus13km_radar_tten_warm_intel 081 failed in run_test
088 control_p8_faster_intel failed in check_result
control_p8_faster_intel 088 failed in run_test
089 regional_control_faster_intel failed in check_result
regional_control_faster_intel 089 failed in run_test
090 rrfs_smoke_conus13km_hrrr_warm_debug_intel failed in check_result
rrfs_smoke_conus13km_hrrr_warm_debug_intel 090 failed in run_test
091 rrfs_smoke_conus13km_hrrr_warm_debug_2threads_intel failed in check_result
rrfs_smoke_conus13km_hrrr_warm_debug_2threads_intel 091 failed in run_test
092 rrfs_conus13km_hrrr_warm_debug_intel failed in check_result
rrfs_conus13km_hrrr_warm_debug_intel 092 failed in run_test
101 control_debug_p8_intel failed in check_result
control_debug_p8_intel 101 failed in run_test
102 regional_debug_intel failed in check_result
regional_debug_intel 102 failed in run_test
103 rap_control_debug_intel failed in check_result
rap_control_debug_intel 103 failed in run_test
104 hrrr_control_debug_intel failed in check_result
hrrr_control_debug_intel 104 failed in run_test
105 rap_unified_drag_suite_debug_intel failed in check_result
rap_unified_drag_suite_debug_intel 105 failed in run_test
106 rap_diag_debug_intel failed in check_result
rap_diag_debug_intel 106 failed in run_test
107 rap_cires_ugwp_debug_intel failed in check_result
rap_cires_ugwp_debug_intel 107 failed in run_test
108 rap_unified_ugwp_debug_intel failed in check_result
rap_unified_ugwp_debug_intel 108 failed in run_test
109 rap_lndp_debug_intel failed in check_result
rap_lndp_debug_intel 109 failed in run_test
110 rap_progcld_thompson_debug_intel failed in check_result
rap_progcld_thompson_debug_intel 110 failed in run_test
111 rap_noah_debug_intel failed in check_result
rap_noah_debug_intel 111 failed in run_test
112 rap_sfcdiff_debug_intel failed in check_result
rap_sfcdiff_debug_intel 112 failed in run_test
113 rap_noah_sfcdiff_cires_ugwp_debug_intel failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug_intel 113 failed in run_test
114 rrfs_v1beta_debug_intel failed in check_result
rrfs_v1beta_debug_intel 114 failed in run_test
115 rap_clm_lake_debug_intel failed in check_result
rap_clm_lake_debug_intel 115 failed in run_test
116 rap_flake_debug_intel failed in check_result
rap_flake_debug_intel 116 failed in run_test
118 regional_spp_sppt_shum_skeb_dyn32_phy32_intel failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32_intel 118 failed in run_test
119 rap_control_dyn32_phy32_intel failed in check_result
rap_control_dyn32_phy32_intel 119 failed in run_test
120 hrrr_control_dyn32_phy32_intel failed in check_result
hrrr_control_dyn32_phy32_intel 120 failed in run_test
121 hrrr_control_qr_dyn32_phy32_intel failed in check_result
hrrr_control_qr_dyn32_phy32_intel 121 failed in run_test
122 rap_2threads_dyn32_phy32_intel failed in check_result
rap_2threads_dyn32_phy32_intel 122 failed in run_test
123 hrrr_control_2threads_dyn32_phy32_intel failed in check_result
hrrr_control_2threads_dyn32_phy32_intel 123 failed in run_test
124 hrrr_control_decomp_dyn32_phy32_intel failed in check_result
hrrr_control_decomp_dyn32_phy32_intel 124 failed in run_test
128 rrfs_smoke_conus13km_fast_phy32_intel failed in check_result
rrfs_smoke_conus13km_fast_phy32_intel 128 failed in run_test
129 rrfs_smoke_conus13km_fast_phy32_qr_intel failed in check_result
rrfs_smoke_conus13km_fast_phy32_qr_intel 129 failed in run_test
132 rap_control_dyn64_phy32_intel failed in check_result
rap_control_dyn64_phy32_intel 132 failed in run_test
133 rap_control_debug_dyn32_phy32_intel failed in check_result
rap_control_debug_dyn32_phy32_intel 133 failed in run_test
134 hrrr_control_debug_dyn32_phy32_intel failed in check_result
hrrr_control_debug_dyn32_phy32_intel 134 failed in run_test
135 rap_control_dyn64_phy32_debug_intel failed in check_result
rap_control_dyn64_phy32_debug_intel 135 failed in run_test
137 hafs_regional_atm_thompson_gfdlsf_intel failed in check_result
hafs_regional_atm_thompson_gfdlsf_intel 137 failed in run_test
175 control_p8_atmlnd_sbs_intel failed in check_result
control_p8_atmlnd_sbs_intel 175 failed in run_test
176 atmwav_control_noaero_p8_intel failed in check_result
atmwav_control_noaero_p8_intel 176 failed in run_test
178 atmaero_control_p8_intel failed in check_result
atmaero_control_p8_intel 178 failed in run_test
179 atmaero_control_p8_rad_intel failed in check_result
atmaero_control_p8_rad_intel 179 failed in run_test
180 atmaero_control_p8_rad_micro_intel failed in check_result
atmaero_control_p8_rad_micro_intel 180 failed in run_test
187 control_p8_gnu failed in check_result
control_p8_gnu 187 failed in run_test
189 rap_control_gnu failed in check_result
rap_control_gnu 189 failed in run_test
190 rap_decomp_gnu failed in check_result
rap_decomp_gnu 190 failed in run_test
191 rap_2threads_gnu failed in check_result
rap_2threads_gnu 191 failed in run_test
193 rap_sfcdiff_gnu failed in check_result
rap_sfcdiff_gnu 193 failed in run_test
194 rap_sfcdiff_decomp_gnu failed in check_result
rap_sfcdiff_decomp_gnu 194 failed in run_test
196 hrrr_control_gnu failed in check_result
hrrr_control_gnu 196 failed in run_test
197 hrrr_control_qr_gnu failed in check_result
hrrr_control_qr_gnu 197 failed in run_test
198 hrrr_control_2threads_gnu failed in check_result
hrrr_control_2threads_gnu 198 failed in run_test
199 hrrr_control_decomp_gnu failed in check_result
hrrr_control_decomp_gnu 199 failed in run_test
202 rrfs_v1beta_gnu failed in check_result
rrfs_v1beta_gnu 202 failed in run_test
203 rrfs_smoke_conus13km_hrrr_warm_gnu failed in check_result
rrfs_smoke_conus13km_hrrr_warm_gnu 203 failed in run_test
204 rrfs_smoke_conus13km_hrrr_warm_qr_gnu failed in check_result
rrfs_smoke_conus13km_hrrr_warm_qr_gnu 204 failed in run_test
205 rrfs_smoke_conus13km_hrrr_warm_2threads_gnu failed in check_result
rrfs_smoke_conus13km_hrrr_warm_2threads_gnu 205 failed in run_test
206 rrfs_smoke_conus13km_radar_tten_warm_gnu failed in check_result
rrfs_smoke_conus13km_radar_tten_warm_gnu 206 failed in run_test
207 rrfs_conus13km_hrrr_warm_gnu failed in check_result
rrfs_conus13km_hrrr_warm_gnu 207 failed in run_test
211 regional_debug_gnu failed in check_result
regional_debug_gnu 211 failed in run_test
212 rap_control_debug_gnu failed in check_result
rap_control_debug_gnu 212 failed in run_test
213 hrrr_control_debug_gnu failed in check_result
hrrr_control_debug_gnu 213 failed in run_test
214 rap_diag_debug_gnu failed in check_result
rap_diag_debug_gnu 214 failed in run_test
215 rap_noah_sfcdiff_cires_ugwp_debug_gnu failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug_gnu 215 failed in run_test
216 rap_progcld_thompson_debug_gnu failed in check_result
rap_progcld_thompson_debug_gnu 216 failed in run_test
217 rrfs_v1beta_debug_gnu failed in check_result
rrfs_v1beta_debug_gnu 217 failed in run_test
220 control_debug_p8_gnu failed in check_result
control_debug_p8_gnu 220 failed in run_test
221 rrfs_smoke_conus13km_hrrr_warm_debug_gnu failed in check_result
rrfs_smoke_conus13km_hrrr_warm_debug_gnu 221 failed in run_test
222 rrfs_smoke_conus13km_hrrr_warm_debug_2threads_gnu failed in check_result
rrfs_smoke_conus13km_hrrr_warm_debug_2threads_gnu 222 failed in run_test
223 rrfs_conus13km_hrrr_warm_debug_gnu failed in check_result
rrfs_conus13km_hrrr_warm_debug_gnu 223 failed in run_test
224 rap_flake_debug_gnu failed in check_result
rap_flake_debug_gnu 224 failed in run_test
225 rap_clm_lake_debug_gnu failed in check_result
rap_clm_lake_debug_gnu 225 failed in run_test
227 rap_control_dyn32_phy32_gnu failed in check_result
rap_control_dyn32_phy32_gnu 227 failed in run_test
228 hrrr_control_dyn32_phy32_gnu failed in check_result
hrrr_control_dyn32_phy32_gnu 228 failed in run_test
229 hrrr_control_qr_dyn32_phy32_gnu failed in check_result
hrrr_control_qr_dyn32_phy32_gnu 229 failed in run_test
230 rap_2threads_dyn32_phy32_gnu failed in check_result
rap_2threads_dyn32_phy32_gnu 230 failed in run_test
231 hrrr_control_2threads_dyn32_phy32_gnu failed in check_result
hrrr_control_2threads_dyn32_phy32_gnu 231 failed in run_test
232 hrrr_control_decomp_dyn32_phy32_gnu failed in check_result
hrrr_control_decomp_dyn32_phy32_gnu 232 failed in run_test
236 rrfs_smoke_conus13km_phy32_gnu failed in check_result
rrfs_smoke_conus13km_phy32_gnu 236 failed in run_test
237 rrfs_smoke_conus13km_phy32_qr_gnu failed in check_result
rrfs_smoke_conus13km_phy32_qr_gnu 237 failed in run_test
240 rap_control_dyn64_phy32_gnu failed in check_result
rap_control_dyn64_phy32_gnu 240 failed in run_test
241 rap_control_debug_dyn32_phy32_gnu failed in check_result
rap_control_debug_dyn32_phy32_gnu 241 failed in run_test
242 hrrr_control_debug_dyn32_phy32_gnu failed in check_result
hrrr_control_debug_dyn32_phy32_gnu 242 failed in run_test
243 rap_control_dyn64_phy32_debug_gnu failed in check_result
rap_control_dyn64_phy32_debug_gnu 243 failed in run_test
244 cpld_control_p8_gnu failed in check_result
cpld_control_p8_gnu 244 failed in run_test
245 cpld_control_nowave_noaero_p8_gnu failed in check_result
cpld_control_nowave_noaero_p8_gnu 245 failed in run_test
246 cpld_debug_p8_gnu failed in check_result
cpld_debug_p8_gnu 246 failed in run_test
247 cpld_control_pdlib_p8_gnu failed in check_result
cpld_control_pdlib_p8_gnu 247 failed in run_test
248 cpld_debug_pdlib_p8_gnu failed in check_result
cpld_debug_pdlib_p8_gnu 248 failed in run_test
</details>

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [X] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- ufs-community/ccpp-physics/pull/69
- NOAA-EMC/fv3atm/pull/654

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hi @grantfirl, I see that CCPP [#68](https://github.com/ufs-community/ccpp-physics/pull/68) was closed out and included in [#69](https://github.com/ufs-community/ccpp-physics/pull/69) which was approved, but PR author asked to hold for some additional results. Could you add 69 to your template and confirm if it's good to go?

**Comment by grantfirl** [comment]
> Hi @grantfirl, I see that CCPP [#68](https://github.com/ufs-community/ccpp-physics/pull/68) was closed out and included in [#69](https://github.com/ufs-community/ccpp-physics/pull/69) which was approved, but PR author asked to hold for some additional results. Could you add 69 to your template and confirm if it's good to go?

Yes, I'll update this PR to point to the latest code and update the descriptions, etc., although the developers requested a pause on merging this until they debug a crash.

**Comment by zach1221** [comment]
Hi, @grantfirl 

Hope all's well. Just wanted to check in and see if you've received any update from the developers regarding the crash they've been debugging?

**Comment by gthompsnWRF** [comment]
> Hi, @grantfirl
> 
> Hope all's well. Just wanted to check in and see if you've received any update from the developers regarding the crash they've been debugging?


I am personally waiting to hear back from @RuiyuSun, because it seems my changes are potentially fine after all, because Ruiyu was testing items one at a time and seeing a crash whereas all items together are working (I think).

**Comment by RuiyuSun** [comment]
> > Hi, @grantfirl
> > Hope all's well. Just wanted to check in and see if you've received any update from the developers regarding the crash they've been debugging?
> 
> I am personally waiting to hear back from @RuiyuSun, because it seems my changes are potentially fine after all, because Ruiyu was testing items one at a time and seeing a crash whereas all items together are working (I think).

The issue is still here. It seems the issue is related to the snow sublimation change. I am running two additional experiments to double check.

**Comment by RuiyuSun** [comment]
> > > Hi, @grantfirl
> > > Hope all's well. Just wanted to check in and see if you've received any update from the developers regarding the crash they've been debugging?
> > 
> > 
> > I am personally waiting to hear back from @RuiyuSun, because it seems my changes are potentially fine after all, because Ruiyu was testing items one at a time and seeing a crash whereas all items together are working (I think).
> 
> The issue is still here. It seems the issue is related to the snow sublimation change. I am running two additional experiments to double check.

I conducted two experiments. One used all the changes in this PR. It crashed. The other experiment used original snow melting and sublimation. The experiment successfully completed the 144 hour forecast.

**Comment by grantfirl** [comment]
Here is the Hera RT log. Any test using Thompson MP is expected to fail, and the list of failed tests IS consistent with this.
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12147287/RegressionTests_hera.log)

**Comment by BrianCurtis-NOAA** [comment]
I'm correcting the ccpp-physics PR link. It should be numbered 69 and not 68.

**Comment by grantfirl** [comment]
> I'm correcting the ccpp-physics PR link. It should be numbered 69 and not 68.

Thanks, @BrianCurtis-NOAA. This PR and submodule PRs are up-to-date again as of right now.

**Comment by FernandoAndrade-NOAA** [comment]
#1842 was merged in, please go ahead and sync your branches with the latest develop

**Comment by grantfirl** [comment]
> #1842 was merged in, please go ahead and sync your branches with the latest develop

@FernandoAndrade-NOAA Finished with syncing to top-of-develop(s).

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA, getting started with jenkins ci for this PR.

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA @BrianCurtis-NOAA note: @SadeghTabas-NOAA confirms he is able to run a test with develop branch for DISKNM=/scratch2/NAGAPE/epic/UFS-WM_RT.

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins CI logs are attached, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1734 #1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/12254070/ufs-weather-model.ort-docker-pipeline.PR-1734.1.Console.Jenkins.txt)

**Comment by zach1221** [comment]
I'm getting failures when trying to compile the s2s_aoflux.intel suite (for the cpld_control_noaero_p8_agrid case). err log doesn't show much, other than ifort warnings before failing. Anyone else experiencing this as well? image

edit this is on Gaea, but I believe Jet failed above for same issue.

**Comment by FernandoAndrade-NOAA** [comment]
Jet's failure seems related to building ccpp physics from a glance at the out file in the rundir:
```
[ 54%] Built target ccpp_physics
make[1]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/role.epic/RT_RUNDIRS/role.epic/FV3_RT/rt_219785/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel'
_______________________________________________________________
Start Epilog on node x300 for job 53521693 :: Thu Aug  3 19:54:19 UTC 2023
Job 53521693 finished for user role.epic in partition xjet with exit code 2:0
```

err:
```
/lfs4/HFIP/hfv3gfs/role.epic/RT_RUNDIRS/role.epic/FV3_RT/rt_219785/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/FV3/ccpp/physics/ccpp_FV3_GFS_v17_coupled_p8_sfcocn_physics_cap.F90(135): remark #15009: fv3_gfs_v17_coupled_p8_sfcocn_physics_cap_mp_FV3_Gfs_v17_coupled_p8_sfcocn_physics_init_cap_ has been targeted for automatic cpu dispatch
make: *** [all] Error 2
```

**Comment by DeniseWorthen** [comment]
That test uses ccpp as the host model for calculating fluxes. There may need to be additional changes in the associated files in CMEPS, but that wouldn't explain why only jet. 

https://github.com/NOAA-EMC/CMEPS/tree/emc/develop/ufs/ccpp

**Comment by jkbk2004** [comment]
@grantfirl `/lfs4/HFIP/hfv3gfs/role.epic/RT_RUNDIRS/role.epic/FV3_RT/rt_219785/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/CMEPS-interface/phy\
sics/ccpp_FV3_sfc_ocean_physics_cap.F90(103): error #6404: This name does not have a type, and must have an explicit type.   [CDATA]
      initialized(cdata%ccpp_instance) = .true.
------------------^`

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 the Gaea error isn't shown in your outputs. It does show a remark that is common but non-fatal to builds.

**Comment by DeniseWorthen** [comment]
@zach1221 @FernandoAndrade-NOAA The build is not sequential. You need to look through the entire err log to find any ": error" occurrences. It is not enough to just look at the end of the file.

**Comment by jkbk2004** [comment]
@grantfirl we will hold this pr a bit until the build issue get resolved.

**Comment by grantfirl** [comment]
@jkbk2004 So, the only issue is the cpld_control_noaero_p8_agrid test on Jet?

**Comment by jkbk2004** [comment]
> @jkbk2004 So, the only issue is the cpld_control_noaero_p8_agrid test on Jet?

Same thing happens on hera as well.
`/scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_268880/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/CMEPS-interface/p\
hysics/ccpp_FV3_sfc_ocean_physics_cap.F90(103): error #6404: This name does not have a type, and must have an explicit \
type.   [CDATA]
      initialized(cdata%ccpp_instance) = .true.
------------------^`

**Comment by BrianCurtis-NOAA** [comment]
> compile_s2s_aoflux_intel

@grantfirl it is the compile_s2s_aoflux_intel, not the test

**Comment by grantfirl** [comment]
@jkbk2004 OK, I'm running this test on Hera to see if I can help debug it.

**Comment by grantfirl** [comment]
@jkbk2004 @BrianCurtis-NOAA I can reproduce the error on Hera/intel. I think it is related to updating the ccpp/framework pointer. I'm going to revert to the previously-working ccpp-framework commit and retry. If this works, I'll debug the issue and update the ccpp/framework pointer in another PR.

**Comment by grantfirl** [comment]
@FernandoAndrade-NOAA @zach1221 @jkbk2004 @BrianCurtis-NOAA The error was related to one of the latest ccpp-framework commits. I've reverted the ccpp-framework hash so that this PR can continue.

**Comment by zach1221** [comment]
@grantfirl I think we're planning to begin working this PR now that 1864 is merged. Can you please resolve your conflicts and sync up your branch? Also, the Hera log you posted above lists out cases expected to change baselines, correct?

**Comment by grantfirl** [comment]
> @grantfirl I think we're planning to begin working this PR now that 1864 is merged. Can you please resolve your conflicts and sync up your branch? Also, the Hera log you posted above lists out cases expected to change baselines, correct?

OK, sorry for the delay. I've synced everything up. Yes, the RT log lists expected failed tests. They're also listed in the description, although it copied/pasted in terribly. It's a lot of tests with changed results -- any that use Thompson MP.

**Comment by zach1221** [comment]
Re-running jenkins-ci. I think the issues seen on 1864, with this pipeline, should be resolved @FernandoAndrade-NOAA

**Comment by zach1221** [comment]
jenkins-ci is complete. ORTs passed.
[Uploading Jenkins-ci 1734 ORTs.pdf…]()

**Comment by FernandoAndrade-NOAA** [comment]
Jet RTs passed, however I don't have permission to push the log to your fork @grantfirl

**Comment by grantfirl** [comment]
> FernandoAndrade-NOAA

I just added you as a collaborator.

**Comment by zach1221** [comment]
I had some tests fail on cheyenne due to disk space and wallclock. Re-running them now, however I have to run them sequentially as ecflow is not working either at the moment. So cheyenne will take a bit longer.

**Comment by junwang-noaa** [comment]
@FernandoAndrade-NOAA the wcoss2 log file is now on hera at:

/scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_wcoss2.log

**Comment by junwang-noaa** [comment]
Here is the acorn log file: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_acorn.log. Thanks

**Comment by zach1221** [comment]
@grantfirl testing is complete. We can begin the merge process of the sub-component PRs.

**Comment by grantfirl** [comment]
> @grantfirl testing is complete. We can begin the merge process of the sub-component PRs.

@zach1221 The ccpp-physics is merged and the fv3atm PR branch is pointing to it and ready to merge.

**Review by sadeghitabas — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
