### PR TITLE
Pull in units updates from FV3

### PR DESCRIPTION
**Pull request by DWesl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:

This PR updates units definitions to be machine-readable: 
- W rather than w as a symbol for watts
- m rather than M as a symbol for meters
- Pa rather than pa as a symbol for pascals (and hPa for hectopascals)
- mbar rather than mb as a symbol for millibar

### Commit Message:

```
* UFSWM - Update units attributes in netCDF output to be machine-readable
  * FV3 - Update units attributes in netCDF output to be machine-readable
    * atmos_cubed_sphere - Update units attributes in netCDF output to be machine-readable
```

### Priority:

* Normal

### UFSWM:

* None

### Sub component Pull Requests:

* FV3: NOAA-EMC/fv3atm#859
  * atmos_cubed_sphere: NOAA-GFDL/GFDL_atmos_cubed_sphere#356

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
I ran a subset of tests on Hera and everything looks good. @jkbk2004 This PR is ready for review and merge. It does need new baselines.

**Comment by DWesl** [comment]
Should I merge updates from the main/develop branch into the FV3 PR, and update the hash here?

**Comment by jkbk2004** [comment]
> Should I merge updates from the main/develop branch into the FV3 PR, and update the hash here?

@DWesl yes, please keep syncing up. I may do some pre-tests to make this pr ready to commit. We are currently working on #2445.

**Comment by jkbk2004** [comment]
merged with #2475

**Pull request closed without merging**
