### PR TITLE
Create 'coupler.res' log file in write grid comp. Explicitly specify chunk sizes in restart files

### LINKED ISSUE #2020: restart file IO problems found in RRFS cycling test
## Description
When test the latest ufs-weather-model (41b17244c634) code for RRFS application. We found several issues related to the restart file and output file IO:

1) need more memory for output quilting. This is solved by adding more core for quilting.
2) the "coupler.res" is not the last file to write in the restart files. This caused some trouble in workflow to decide if all the restart files are available or not. It is better to write the "coupler.res" after all other restart files so it can be used as a flag for complete restart files writing process. 
3) The chunksize of restart files are not right. Several RRFS applications use parallel netcdf IO that depends on right chunksize (nx * ny). This code cannot generate right chunksize for RRFS applications when "quilting_restart=.true.".
4) calendar type used by RRFS needs to set to 2 ('julian') instead of 3 ('gregorian') when generates "coupler.res".
 
### To Reproduce:

All those issues were found in RRFS_A parallel test on CACTUS.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13518448/RegressionTests_hera.log)

- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

When the restart files are written by the write grid component, the log file (coupler.res) must also be written by write grid comp to ensure that it is written after all other restart files have already be created.

The chunk sizes are now explicitly specified in restart file when quilting_restart is used, and are equal to the Nx x Ny in horizontal and 1 in all other dimensions.

### Associated UFSWM Issue to close

Closes #2020

### Subcomponent Pull Requests

NOAA-EMC/fv3atm/pull/726

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [x] Orion
  - [x] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA rrfs team requested to commit this pr first for operational application.  Can you sync up the branch?

**Review by junwang-noaa — DISMISSED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Acorn is sitting on it's last item and it's queued still, it's been there for at least a few hours. There are no current fail-tests in the working directory. I plan on killing the last task on Acorn so we don't need to wait. The queue on Acorn is being used by the SA's, so I don't think this long wait is about the resources needed for this test being too high.

**Comment by zach1221** [comment]
> Acorn is sitting on it's last item and it's queued still, it's been there for at least a few hours. There are no current fail-tests in the working directory. I plan on killing the last task on Acorn so we don't need to wait. The queue on Acorn is being used by the SA's, so I don't think this long wait is about the resources needed for this test being too high.

@BrianCurtis-NOAA ok I think we're good to go then.

**Comment by zach1221** [comment]
@DusanJovic-NOAA fv3atm pr is merged. Please revert change in .gitmodules and update the submodule hash.
https://github.com/NOAA-EMC/fv3atm/commit/a82381c0b751a15e5343de5078ef836b2c444c89

**Comment by BrianCurtis-NOAA** [comment]
Did you find any consistency in the run taking longer than 30 or a history of higher run times?

**Comment by jkbk2004** [comment]
> Did you find any consistency in the run taking longer than 30 or a history of higher run times?

Sorry for confusing commit remarks.. Actually the case is cpld_debug_pdlib_p8 on jet. The baseline was originated from #1967. Somehow the test log wasn't reported in the report for a few PRs. But  1882 sec is not bad on jet in a sense jet is small machine. On Orion and hercules, the case is taking about 1500 sec. I am trying to confirm and recover missing baseline case on jet  At least, I was catching up the case on jet from last PR and this PR. So, we can let this pr move on to be merged. I will update in tomorrow's tag up.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Im confused. We have changes in this PR for cpld_debug_p8 but you mention cpld_debug_pdlib_p8 and missing baselines? Do we need the cpld_debug_p8 changes?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA Oh! my mistake. it's cpld_debug_pdlib_p8 issue as the jet log show at the end. I am fixing now.

**Comment by jkbk2004** [comment]
All set now.

**Comment by DeniseWorthen** [comment]
@jkbk2004 The pdlib tests were restricted to only hera, orion, wcoss2 and cheyenne, but they got turned on everywhere in https://github.com/ufs-community/ufs-weather-model/pull/1967. So the last two weeks worth of pdlib tests should show up in the jet logs but the test does not show up in the log for that PR's commit. Why is the test not running on jet?


You can see here that the test (25) is not reported:

 https://github.com/ufs-community/ufs-weather-model/blob/f431fbe177445d74879a909bc815d427480c1973/tests/logs/RegressionTests_jet.log#L1568-L1578

**Comment by jkbk2004** [comment]
As I said, somehow the case was missing for the commits on Nov 22/27/29 and Dec but reported on Dec 4 and this pr. I am recovering now. cases are running and shows around 1880 sec. Anyway, no need to hold this pr. We can merge this pr. I will report the result of recovering missing jet cases in previous baseline dates tomorrow.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
cpld_debug_pdlib_p8 is all recovered on jet for baselines: develop-20231117 and develop-20231122.  timing is around 1800 ~ 1900 sec. So bumping up wlclk makes a sense.  @zach1221 it's ok to proceed to merge this pr.

**Comment by zach1221** [comment]
> cpld_debug_pdlib_p8 is all recovered on jet for baselines: develop-20231117 and develop-20231122. timing is around 1800 ~ 1900 sec. So bumping up wlclk makes a sense. @zach1221 it's ok to proceed to merge this pr.

Ok, I'll need one more approval. Waiting on that.

**Comment by BrianCurtis-NOAA** [comment]
Please wait until after the CM meeting to merge.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
