### PR TITLE
Fix CICE decomposition settings; update MOM6 to GFDL 20210914 main branch commit (was PR#803)

### LINKED ISSUE #802: update MOM6 to GFDL main branch 20210914 commit
## Description
GFDL updated its main branch of MOM6 on 20210914 (see detail at https://github.com/NOAA-GFDL/MOM6/pull/1491), need to make corresponding updating in EMC repository
## Solution
update MOM6 in EMC repository, also update ufs-weather-model
## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### LINKED ISSUE #815: cpld_bmark_v16 regression test ice_in inconsistency
## Description
When cpld_bmark_v16 regression test runs, the block_size_y seems incorrect.
```
    nprocs            = 48
    nx_global         = 1440
    ny_global         = 1080
    block_size_x      = 60
    block_size_y      = 160 
```
Shouldn't block_size_y be 540?

Nevertheless, the simulation completes successfully.

### To Reproduce:
```
$ git clone --recurse-submodules https://github.com/ufs-community/ufs-weather-model
$ cd ufs-weather-model/tests
$ ./rt.sh -n cpld_bmark_v16 -k >out 2>&1 &
```
Go to ``$RUNDIR`` and take a look at lines 158 to 162 of ``ice_in``

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Fixes cice decomposition parameters for ice_in_template. The change in decomposition was not correctly accounted for in PR #791 with the removal of ``edit_inputs``. When ``NPROC_ICE``  is set to a non-default value, new values of the decomposition parameters need to be set.

### Issue(s) addressed

- fixes #815 
- fixes #802 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- Testing on hera.intel for all tests which utilize CICE showed no changes to baselines are expected.
- Ice_in files from 1deg,1/2deg and 1/4deg coupled and datm runs were compared to copies from an RT prior to the commit of PR#791 and were found to be identical.
- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI

## Dependencies

MOM6 PR [#76](https://github.com/NOAA-EMC/MOM6/pull/76)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jiandewang would you please run RTs on WCOSS cray and dell? Thanks.

**Comment by jiandewang** [comment]
@DeniseWorthen OK will do right away

**Comment by jiandewang** [comment]
@DeniseWorthen I scp-ed wcoss-cray RT log to HERA at
/scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For_Denise/UFS-RT-log-20210920

**Comment by jiandewang** [comment]
job failed on P3 due to disk full, re-run them now by switching from using ptmp to stmp

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/736926843/20210920173008/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_6727
Test cpld_control_c384 008 failed failed 
Test cpld_control_c384 008 failed in run_test failed 
Test hafs_regional_datm_cdeps 088 failed failed 
Test hafs_regional_datm_cdeps 088 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Review by junwang-noaa — APPROVED** [review]

**Comment by jiandewang** [comment]
I am kept on having disk full issue on wcoss-p3. 
A question here: after one job is done and run log show PASS, can I delete that directory in rt-xxxx ? I understand there are few cases that restart run will rely on previous run.

**Comment by junwang-noaa** [comment]
I believe you can delete the run directory rt-xxxx/test if you see the
rt_test under ufs-weather-model/tests/log*dell*. But you can not delete the
whole RT directory rt-xxxx

**Comment by jiandewang** [comment]
@junwang-noaa this is what I am doing now, otherwise rt.sh won't be able to finish

**Comment by jiandewang** [comment]
@DeniseWorthen dell-p3 run log is on HERA
/scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For_Denise/UFS-RT-log-20210920

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@jiandewang We're ready to merge this PR once MOM6 has been updated. @JessicaMeixner-NOAA would you please review the MOM6 PR? Thanks.

**Comment by jiandewang** [comment]
@DeniseWorthen updated MOM6, thanks

**Pull request merged**
