### PR TITLE
Updates to C3 and SAS convection schemes

### LINKED ISSUE #1964: Updates to C3 and SAS cumulus convection schemes
## Description
Optimal tuning parameters are found to be different in the prognostic closure formulation shared by SAS and C3 convection schemes for RRFS/GFS and HAFS applications. Therefore I propose to bring them out as namelist parameters.

## Solution
Create a PR that brings out the parameters as tuning parameters.

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: /scratch2/BMC/gsienkf/Lisa.Bengtsson/RegressionTests_hera.log
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
*Brings out tuning parameters from the progsigma_calc.F90, which are used in the saSAS and C3 shallow and deep cumulus convection schemes.
*Adds a limiter on area fraction to not exceed 0.95 after final tuning
*Updates the regression test namelist used for gfsv17 (HR3) tests, to include extracted parameters in the namelist.

For RRFSv1 ensemble members using saSAS convection, workflow updates are needed.

Some justification for the PR can be found here: https://docs.google.com/presentation/d/11WVCFAb-JM628N2RyAWLqjxxrSovKU8AB72xBZJ1FfI/edit#slide=id.p

### Associated UFSWM Issue to close
Closes https://github.com/ufs-community/ufs-weather-model/issues/1964

### Subcomponent Pull Requests
https://github.com/ufs-community/ccpp-physics/pull/122
https://github.com/NOAA-EMC/fv3atm/pull/715

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by lisa-bengtsson** [comment]
All RT's pass on Hera:
/scratch2/BMC/gsienkf/Lisa.Bengtsson/RegressionTests_hera.log
No changes to baselines.

**Comment by BrianCurtis-NOAA** [comment]
Incomplete is just waiting on PR review in FV3atm

**Comment by lisa-bengtsson** [comment]
@BrianCurtis-NOAA @SamuelTrahanNOAA my understanding is that we will close this PR and the corresponding FV3 PR as it's been merged with Sam's PR on the global nest. Sam can you confirm that I can close these?

**Comment by BrianCurtis-NOAA** [comment]
OK that's fine. If you add `closes #1965` to Sam's PR it should close this PR once his is merged. No need to do anything here except keeping the note it's a part of his. Thanks!

**Pull request closed without merging**
