### PR TITLE
ufs_public_release: update submodule pointer for fv3atm for ccpp-framework and ccpp-physics bugfixes

### PR DESCRIPTION
**Pull request by DomHeinzeller**
Update submodule pointers for ccpp-framework and ccpp-physics for several bugfixes.

Update submodule pointer for GFDL_atmos_cubed_sphere for documentation update from @valbonakunkel-noaa.

Associated PRs:
https://github.com/ufs-community/ufs-weather-model/pull/35
https://github.com/NOAA-EMC/fv3atm/pull/47
https://github.com/NCAR/ccpp-framework/pull/255
https://github.com/NCAR/ccpp-physics/pull/387
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/12

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Hi, Dom,

Can we add the pull request :

https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/12

to your ufs-weather-model pull request #35?  Thanks

Jun

**Comment by climbfuji** [comment]
> Hi, Dom, Can we add the pull request : [NOAA-EMC/GFDL_atmos_cubed_sphere#12](https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/12) to your ufs-weather-model pull request #35? Thanks Jun
> […](#)

Will do. Need to rerun the regtests (I already completed all of them), but that's no problem.

**Comment by junwang-noaa** [comment]
Thank you!

Jun

**Comment by DomHeinzeller** [comment]
Regression tests passed on all three platforms, logs updated as usual in the PR.

[rt_cheyenne_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4110104/rt_cheyenne_intel.log)
[rt_cheyenne_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4110105/rt_cheyenne_gnu.log)
[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4110106/rt_hera_intel.log)

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
