### PR TITLE
Add new PBL diagnostic variables dkt and dku

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description
This PR adds new PBL diagnostic variables dkt and dku (atmosphere heat and momentum diffusivity) used in HAFS. This PR should not change answers, neither require any library or module updates.

### Issue(s) addressed
- addresses NCAR/ccpp-physics/issues/606 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
**- [ ] jet.intel NOTE: SKIPPED DUE TO JET PM**
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on NCAR/ccpp-physics/pull/607
- waiting on noaa-emc/fv3atm/pull/269

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
ufs-weather-model regression tests on Hera have passed successfully.

**Comment by BrianCurtis-NOAA** [comment]
Good morning @BinLiu-NOAA , you're on top of the commit queue now. Could you please bring your ufs-weather-model fork up-to-date with ufs-weather-model/develop and make sure your FV3 fork is also up-to-date with fv3atm/develop? Thank you.

**Comment by climbfuji** [comment]
> Good morning @BinLiu-NOAA , you're on top of the commit queue now. Could you please bring your ufs-weather-model fork up-to-date with ufs-weather-model/develop and make sure your FV3 fork is also up-to-date with fv3atm/develop? Thank you.

@BrianCurtis-NOAA please note the comment I left in the fv3atm PR that needs to be addressed (in addition to updating to the head of the authoritative branches): https://github.com/NOAA-EMC/fv3atm/pull/269#discussion_r616655423

**Comment by BrianCurtis-NOAA** [comment]
> > Good morning @BinLiu-NOAA , you're on top of the commit queue now. Could you please bring your ufs-weather-model fork up-to-date with ufs-weather-model/develop and make sure your FV3 fork is also up-to-date with fv3atm/develop? Thank you.
> 
> @BrianCurtis-NOAA please note the comment I left in the fv3atm PR that needs to be addressed (in addition to updating to the head of the authoritative branches): [NOAA-EMC/fv3atm#269 (comment)](https://github.com/NOAA-EMC/fv3atm/pull/269#discussion_r616655423)

Yes, make sure you fix the fv3atm issue and update the pointer here afterwards. Thanks Dom.

**Comment by BrianCurtis-NOAA** [comment]
Trying out the hera intel/gnu RT's and will add others if they pass.

**Comment by BrianCurtis-NOAA** [comment]
Don't forget to bring this branch up-to-date with ufs-community/ufs-weather-model: develop after you bring your fv3atm branch up-to-date as well.

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/608013381/20210420143044/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_108353
Test fv3_gfs_v16_RRTMGP 006 failed in run_test failed 
Test fv3_gfs_v16_stochy 004 failed in run_test failed 
Test fv3_gfs_v16 002 failed in run_test failed 
Test fv3_gfdlmp 001 failed in run_test failed 
Test fv3_gfs_v16_flake 005 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-RT

**Comment by BinLiu-NOAA** [comment]
@BrianCurtis-NOAA I am working on to bring this branch up to date with the latest develop branch. It is currently 1-2 commits behind. Will let you know once it's done. Should be done shortly. Thanks!

**Comment by BinLiu-NOAA** [comment]
@BrianCurtis-NOAA I have just synced this branch with the latest develop branch. And if it might be useful, I am running the regression tests on Orion now, under this directory with freshly cloned and checked out feature branch.
/work/noaa/hwrf/save/bliu/ufs_dktdkudiag

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I have just synced this branch with the latest develop branch. And if it might be useful, I am running the regression tests on Orion now, under this directory with freshly cloned and checked out feature branch.
> /work/noaa/hwrf/save/bliu/ufs_dktdkudiag

It is useful. If it passes push the log file to your branch. If it doesn't we can see how the hera intel job goes, they may have different outcomes.

**Comment by BinLiu-NOAA** [comment]
@BrianCurtis-NOAA, Sure will do. So far, the RTs are running fine on Orion. If everything passes, I will commit in the regression test log on Orion accordingly.

**Comment by BrianCurtis-NOAA** [comment]
@BinLiu-NOAA On the right side of this PR there is an option to "Allow edits from Maintainers". In order for the scripts to automatically push the logs to this PR that option needs to be checked (allowed). If you don't wish to allow this, then we will have to find a way to get you the Log files to upload yourself.

**Comment by BinLiu-NOAA** [comment]
The RTs on Orion finished successfully. Regression log file has just committed.

**Comment by BinLiu-NOAA** [comment]
@BrianCurtis-NOAA, I could not find the option to "Allow edits from Maintainers" you mentioned for this PR. If possible, please feel free to edit and enable this option. In the meantime, I sent you an invitation to give you write access to this fork's feature/dktdiagnostic branch. After you accept the invitation, you should be able to commit and push your changes in. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
@BinLiu-NOAA Thanks for checking. I am getting cray issues:
```
FAILED TESTS:
Test fv3_thompson_no_aero_debug 064 failed failed
Test fv3_thompson_no_aero_debug 064 failed in run_test failed
Test fv3_regional_control_debug 058 failed failed
Test fv3_regional_control_debug 058 failed in run_test failed
```
Working dir: /gpfs/hps3/stmp/Brian.Curtis/FV3_RT/rt_13270

**Comment by BinLiu-NOAA** [comment]
@BrianCurtis-NOAA I looked one of the failed test err log:
/gpfs/hps3/stmp/Brian.Curtis/FV3_RT/rt_13270/fv3_thompson_no_aero_debug/err
 in fcst run phase 2, na=          35
forrtl: Device or resource busy
forrtl: severe (38): error during write, unit 50, file /gpfs/hps3/stmp/Brian.Curtis/FV3_RT/rt_13270/fv3_thompson_no_aero_debug/PET120.ESMF_LogFile
Image              PC                Routine            Line        Source
fv3.exe            000000000B46229E  Unknown               Unknown  Unknown
fv3.exe            000000000B4C9240  Unknown               Unknown  Unknown
fv3.exe            000000000B4C48E8  Unknown               Unknown  Unknown
fv3.exe            0000000001503AC2  esmf_logerrmod_mp        1011  ESMF_LogErr.F90
fv3.exe            000000000151334A  esmf_logerrmod_mp        2736  ESMF_LogErr.F90
fv3.exe            00000000014FEA9F  f_esmf_logwrite0_          40  ESMF_LogErr_C.F90
fv3.exe            000000000064FF8C  _ZN5ESMCI6LogErr5         350  ESMCI_LogErr.C
fv3.exe            000000000069799E  _ZN5ESMCI2VM10log        2497  ESMCI_VM.C
fv3.exe            0000000001DF4940  c_esmc_vmlogmemin        2078  ESMCI_VM_F.C
fv3.exe            000000000169FBEF  esmf_vmmod_mp_esm        6008  ESMF_VM.F90
fv3.exe            0000000002DFAC3B  fv3gfs_cap_mod_mp        1223  fv3_cap.F90

By any chance, there might be system side issue (file system, io, wallclock limit, etc.), which could have caused the failure?

**Comment by BrianCurtis-NOAA** [comment]
It's very possible. Once my Dell P3 run is done i'll retry the cray.

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/608013381/20210420230014/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_237457
Test datm_bulk_cfsr 105 failed failed 
Test datm_bulk_cfsr 105 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
hera intel test error was a slurm issue, nothing related to the RT's, I'm re-running that one test and will add it to the log

**Comment by BrianCurtis-NOAA** [comment]
@MinsukJi-NOAA i'm not sure if the issue showing for the failed run-ci tests is something we should be concerned about. Do we need to change anything?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA i'm not sure if the issue showing for the failed run-ci tests is something we should be concerned about. Do we need to change anything?

@BrianCurtis-NOAA this is an ec2/docker issue and not a testing issue, and i suggest going ahead with the PR. I expect this issue to be fixed with an upcoming PR.

**Comment by BrianCurtis-NOAA** [comment]
@MinsukJi-NOAA Thanks!

I'm just waiting on the failed test to re-run on hera.intel, still sitting in pending

**Review by junwang-noaa — APPROVED** [review]
The code can be committed once all RT (except jet) is done and the FV3 repo is updated.

**Comment by BrianCurtis-NOAA** [comment]
FV3 PR is merged. Please revert .gitmodules and update pointer to NOAA-EMC:develop

**Comment by BinLiu-NOAA** [comment]
@BrianCurtis-NOAA, Done to revert .gitmodules and update pointer to NOAA-EMC:develop. Please double check. 
Thanks!

**Comment by BrianCurtis-NOAA** [comment]
The hash's match. Waiting on @climbfuji approval.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
