### PR TITLE
Updates for P8 

### LINKED ISSUE #1350: Updates for P8
## Description
In response to the mini-P8c runs, we will make the following updates: 
* Revert calculation of T2m (@HelinWei-NOAA )
* Set do_gsl_drag_tofd=false as this resolved the stability issues similar to those reported in https://github.com/ufs-community/ufs-weather-model/issues/1277) 
* Updates to aerosol configuration (@bbakernoaa) 

## Solution
A PR with the above changes. 

## Alternatives
N/A 

## Related to

- (CCPP issue for T2m)

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [x] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR updates the following: 
* This reverts the calculation of T2m in NOAH-MP as it was found in p8c that it tends to result in overly low t2min and overly high t2max values. (CCPP PR) 
* Sets do_gsl_drag_tofd=false as this solved the stability issues seen when first trying to run P8c 
* Updates to aerosol configuration: 
 --- Update the RT to mimic the p8 aerosol configuration. Updates the wet deposition coefficient for organic carbon from 0.3 -> 0.4. Updates the dust to use the 10km file that is used within P8c and p8

File to be copied in RT data folder is on hera: 
 /scratch1/NCEPDEV/global/glopara/data/gocart_emissions/Dust/FENGSHA_p81_10km_inputs.nc 
and should be added to : 
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20220414/GOCART/p8/ExtData/dust/

### Issue(s) addressed

- fixes #1350 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [x] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? Yes 
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/565
- waiting on https://github.com/NCAR/ccpp-physics/pull/948

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 I have updated the PR with Barry's updates.  There is one new input file which I copied to the location on hera but not any other machine.  The PR was updated to indicate it needs the new input data.

**Comment by jkbk2004** [comment]
> @jkbk2004 I have updated the PR with Barry's updates. There is one new input file which I copied to the location on hera but not any other machine. The PR was updated to indicate it needs the new input data.

Sure! If orion comes back this evening or tomorrow, we may start testing the PR tomorrow or Monday. We are currently working on #1317 now.

**Comment by JessicaMeixner-NOAA** [comment]
@HelinWei-NOAA have you run the regtests with your ccpp-physics updates?   I'm having issues with the compile for: 
`COMPILE | -DAPP=ATM -DDEBUG=ON -D32BIT=ON                                                                                         |                                         | fv3 |
`

for example I get this error: 

```
/scratch1/NCEPDEV/stmp2/Jessica.Meixner/FV3_RT/rt_175447/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90(5012): error #6405: The same named entity from different modules and/or program units cannot be referenced.   [CDATA]
               ierr = FV3_GFS_v16_coupled_p8_sfcocn_time_vary_tsfinal_cap(cdata=cdata)
--------------------------------------------------------------------------------^
compilation aborted for /scratch1/NCEPDEV/stmp2/Jessica.Meixner/FV3_RT/rt_175447/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90 (code 1)
make[2]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/physics/ccpp_static_api.F90.o] Error 1
make[1]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/all] Error 2

```

**Comment by JessicaMeixner-NOAA** [comment]
I got the same error above when I ran from the develop branch, so perhaps this is just some weird user error on my end?

**Comment by jkbk2004** [comment]
> I got the same error above when I ran from the develop branch, so perhaps this is just some weird user error on my end?

@JessicaMeixner-NOAA let me check on cheyenne.

**Comment by jkbk2004** [comment]
> > I got the same error above when I ran from the develop branch, so perhaps this is just some weird user error on my end?
> 
> @JessicaMeixner-NOAA let me check on cheyenne.
Both develop and this branches build ok.

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 thank you for the sanity check.  I guess I did something on my end.  Glad things are working.  FYI @HelinWei-NOAA

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Are you sure the bmark_p8 oRT test ran? The log you posted appears empty.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Are you sure the bmark_p8 oRT test ran? The log you posted appears empty.

Today is not my day for running tests apparently... Let me try this again...

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA Tests on orion passed.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1009952215/20220730143022/ufs-weather-model
[BL] Error: Test atmaero_control_p8 097 failed in run_test failed 
[BL] Error: Test atmaero_control_p8_rad 098 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1009952215/20220730143006/ufs-weather-model
[BL] Error: Test cpld_control_p8 001 failed in run_test failed 
[BL] Error: Test cpld_control_ciceC_p8 002 failed in run_test failed 
[BL] Error: Test cpld_control_c192_p8 003 failed in run_test failed 
[BL] Error: Test cpld_bmark_p8 004 failed in run_test failed 
[BL] Error: Test cpld_debug_p8 007 failed in run_test failed 
[BL] Error: Test atmaero_control_p8 107 failed in run_test failed 
[BL] Error: Test atmaero_control_p8_rad 108 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA all RT tests move smoothly. This PR is for p8. So, do we need to consider to tun ORT tests for other p8 test cases?

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 I'm happy to run any oRT tests that are required. Please let me know which additional tests are required and I will do that ASAP.

**Comment by jkbk2004** [comment]
> @jkbk2004 I'm happy to run any oRT tests that are required. Please let me know which additional tests are required and I will do that ASAP.

Yeah, cpld_bmrak_p8 covers a lot. But can you give a try to do with cpld_control_* cases that we have ort log files in the repo? It will be great if we update with some of those cases.

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 will do!

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 running the cpld_control_ciceC_p8 oRT now.  Otherwise, I have no plans to run the additional p8 test without aerosols since the oRTs with aerosols are working.  If that'd needed, please let me know and I'll be happy to run it after the ciceC oRTs.

**Comment by jkbk2004** [comment]
> @jkbk2004 running the cpld_control_ciceC_p8 oRT now. Otherwise, I have no plans to run the additional p8 test without aerosols since the oRTs with aerosols are working. If that'd needed, please let me know and I'll be happy to run it after the ciceC oRTs.

@JessicaMeixner-NOAA Thanks for adding more ORT results. Should be enough for the PR approval. @BrianCurtis-NOAA The PR should be ready once we have wcoss2/acorn tests in. Maybe we can set to merge by tomorrow. A side note again: more complete solution to continuous and full ORT will be when we add in Jenkins-based CI capability.

**Comment by junwang-noaa** [comment]
@bbakernoaa I saw all the cpld tests have reduced >10% run time and >30% memory usage. May I ask how much resolution change is in the new dust mission file compared to previous emission files FENGSHA_SOILGRIDS2019_GEFSv12_v1.2.nc/FENGSHA_Albedo_drag_v1.nc/randomforestensemble_uthres.nc? Thank you!

**Comment by BrianCurtis-NOAA** [comment]
as of 10PM, Acorn isn't wanting to run RT's. I'll talk to Dusan to see how he ran them previously. Skip for this PR.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA We can start merging process. I will go to fv3 pr to ask for final review and merge there. @DusanJovic-NOAA @DeniseWorthen Please, go ahead for final review.

**Comment by DeniseWorthen** [comment]
It doesn't look like the dcp oRT was run for the cpld cases.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
> It doesn't look like the dcp oRT was run for the cpld cases.

On second look, this seems correct.  This was an oversight on my part.  I can run this as soon as hera is back online.  In the future, it would be helpful to have clearer instructions on what specific tests with what specific options are required to avoid mistakes like this in the future.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @DeniseWorthen I was asking to check ORTs of this PR on EPIC side. I will make sure. I think he was testing on Orion.

**Comment by BrianCurtis-NOAA** [comment]
> > It doesn't look like the dcp oRT was run for the cpld cases.
> 
> On second look, this seems correct. This was an oversight on my part. I can run this as soon as hera is back online. In the future, it would be helpful to have clearer instructions on what specific tests with what specific options are required to avoid mistakes like this in the future.

I want to second that there is no documentation on what needs to be run for ORT and it would be helpful to component devs like Jessica to have such a document. We call ORT's unit tests for some reason on the Wiki (https://github.com/ufs-community/ufs-weather-model/wiki/Running-unit-tests-using-utest) so that documentation needs to change and a section to be added on what ORT's need to be run for each type of test (regional, global, etc..) I've created an issue here: #1363

**Comment by jkbk2004** [comment]
> > > It doesn't look like the dcp oRT was run for the cpld cases.
> > 
> > 
> > On second look, this seems correct. This was an oversight on my part. I can run this as soon as hera is back online. In the future, it would be helpful to have clearer instructions on what specific tests with what specific options are required to avoid mistakes like this in the future.
> 
> I want to second that there is no documentation on what needs to be run for ORT and it would be helpful to component devs like Jessica to have such a document. We call ORT's unit tests for some reason on the Wiki (https://github.com/ufs-community/ufs-weather-model/wiki/Running-unit-tests-using-utest) so that documentation needs to change and a section to be added on what ORT's need to be run for each type of test (regional, global, etc..) I've created an issue here: #1363

I am asking Zach/EPIC to follow up ORT runs for new PRs until we have a good solution with Jenkins option.

**Comment by jkbk2004** [comment]
> > It doesn't look like the dcp oRT was run for the cpld cases.
> 
> On second look, this seems correct. This was an oversight on my part. I can run this as soon as hera is back online. In the future, it would be helpful to have clearer instructions on what specific tests with what specific options are required to avoid mistakes like this in the future.

Can you remind me about the point? cpld_bmark_p8_dcp ran, right?

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 for the ort for  cpld_bmark_p8  dcp did run.  But for cpld_control_ciceC_p8 and  cpld_control_p8 I unintentionally left out dcp

**Comment by JessicaMeixner-NOAA** [comment]
The oRT dcp test has now been run for cpld_control_ciceC_p8 and cpld_control_p8 and the log files have been updated.   @jkbk2004 @DeniseWorthen

**Comment by jkbk2004** [comment]
> The oRT dcp test has now been run for cpld_control_ciceC_p8 and cpld_control_p8 and the log files have been updated. @jkbk2004 @DeniseWorthen

@JessicaMeixner-NOAA Sure! I merged in [fv3atm#565](https://github.com/NOAA-EMC/fv3atm/pull/565). Can you update submodule pointer and revert branch in gitmodules?

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 FV3 has been updated

**Review by DeniseWorthen — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen @jkbk2004 apologies for my oversights and thank you for your patience in working with me to get this committed! It is much appreciated.   This is the anticipated "Prototype8" hash now.  Would it be possible to get a tag for this?

**Comment by DeniseWorthen** [comment]
Thanks @JessicaMeixner-NOAA. I've created a  [Prototype-P8](https://github.com/ufs-community/ufs-weather-model/releases/tag/Prototype-P8) tag.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @DeniseWorthen !!!

**Pull request merged**
