### PR TITLE
Adjust GFS diagnostic Aerosol Optical Depth (AOD) output to the exact 550nm

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR is created to adjust the GFS diagnostic Aerosol Optical Depth (AD) output to the exact 550nm in FV3/ccpp/physics/physics/radiation_aerosols.f.

### Issue(s) addressed

- fixes #<[15](https://github.com/ufs-community/ccpp-physics/issues/15)>

## Testing
The RT was conducted on hera.intel.  All cpld_* RTs will change baselines due to changed variables (*_aod550) in sfcf*.nc files.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on ufs-community/ccpp-physics/pull/<[16](https://github.com/ufs-community/ccpp-physics/pull/16)>
- waiting on noaa-emc/fv3atm/pull/<[597](https://github.com/NOAA-EMC/fv3atm/pull/597)>

### CODE REVIEW

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA We can start working on this pr. can you resolve the conflicts?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Sure. I will make my branch update-to-date. I will let you know when it is ready.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA @BrianCurtis-NOAA I will let the RTs runs over weekend with baseline creation.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 @BrianCurtis-NOAA Sounds a good plan. This branch is update-to-date and ready for the commit process.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1100942881/20221110204558/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by jkbk2004** [comment]
For jenin-ci, there is work-in-progress to update input data file container. We will reactivate jenins-ci from next pr. @ChunxiZhang-NOAA @DusanJovic-NOAA @BrianCurtis-NOAA we can start merging process with final comments and approvals.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 May I merge ccpp-physics PR now?

**Comment by jkbk2004** [comment]
> @jkbk2004 May I merge ccpp-physics PR now?

@ChunxiZhang-NOAA sure! please, go ahead to merge.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 ccpp-physics PR has been merged. I've reverted the submodule pointer to ccpp-physics for fv3atm.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA OK! lets merge the pr here with hash update on fv3atm.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Sure. I've reverted the pointer and updated the hash.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
