### PR TITLE
CCPP framework (metadata parser) update, and update several units in CCPP metadata in fv3atm and ccpp-physics, use Python 3.6+

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

With the metadata parser update in NCAR/ccpp-framework#415, a stricter checking of units will be enforced. This includes the replacement of "convenience units" such as `log(Pa)` with 1. Corresponding changes are made in ccpp-physics and fv3atm.

The ccpp-framework update requires Python 3.6 or newer - load Python 3.7.9 modules on Cheyenne, all other platforms are already using 3.6 or newer.

No changes to the regression test results, no changes to the input data.

### Issue(s) addressed

Fixes https://github.com/NCAR/ccpp-framework/issues/416

## Testing

Regression tests were run against the existing baselines on Hera with Intel and GNU at the tiime the PRs were created (11/09 and 11/10). All tests passed.

[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/7513869/RegressionTests_hera.intel.log)
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/7513873/RegressionTests_hera.gnu.log)

Full regression tests will be run when it is time to commit:

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [n/a] opnReqTest for newly added/changed feature
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/907/commits/89bb666678d2ed7f7f59595a46934ab0cdb512ad

## Dependencies

- waiting on https://github.com/NCAR/ccpp-framework/pull/415
- waiting on https://github.com/NCAR/ccpp-physics/pull/775
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/422

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/777675382/20211123100010/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_69245
Test compile 001 failed failed 
Test compile 001 failed failed 
Test compile 002 failed failed 
Test compile 002 failed failed 
Test compile 003 failed failed 
Test compile 003 failed failed 
Test compile 004 failed failed 
Test compile 004 failed failed 
Test compile 005 failed failed 
Test compile 005 failed failed 
Test compile 006 failed failed 
Test compile 006 failed failed 
Test compile 007 failed failed 
Test compile 007 failed failed 
Test compile_001 failed in run_compile failed 
Test compile_002 failed in run_compile failed 
Test compile_003 failed in run_compile failed 
Test compile_004 failed in run_compile failed 
Test compile_005 failed in run_compile failed 
Test compile_006 failed in run_compile failed 
Test compile_007 failed in run_compile failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/777675382/20211123101508/ufs-weather-model
Please make changes and add the following label back:
cheyenne-gnu-RT

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/777675382/20211123121508/ufs-weather-model
Please make changes and add the following label back:
orion-intel-RT

**Comment by climbfuji** [comment]
The error on orion is new to me, all compile jobs failed with a slurm error:
```
sbatch: error: resolve_ctls_from_dns_srv: res_nsearch error: No error
sbatch: error: fetch_config: DNS SRV lookup failed
sbatch: error: _establish_config_source: failed to fetch config
sbatch: fatal: Could not establish a configuration source
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/777675382/20211123181517/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_11916
Test control_decomp 015 failed failed 
Test control_decomp 015 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: hera
> Compiler: intel
> Job: RT
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/777675382/20211123181517/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_11916
> Test control_decomp 015 failed failed
> Test control_decomp 015 failed in run_test failed
> Please make changes and add the following label back:
> hera-intel-RT

This test timed out:
```
srun: Warning: can't honor --ntasks-per-node set to 40 which doesn't match the requested tasks 150 with the number of requested nodes 4. Ignoring --ntasks-per-node.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
  0: slurmstepd: error: *** STEP 25551887.0 ON h19c25 CANCELLED AT 2021-11-23T19:29:13 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 25551887 ON h19c25 CANCELLED AT 2021-11-23T19:29:13 DUE TO TIME LIMIT ***
```
Will rerun manually and append to log, then commit.

**Comment by climbfuji** [comment]
Submodule pointer for fv3atm looks correct (c72ba60), please check and merge if satisfied.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@DeniseWorthen is on leave for the rest of this week, I will remove her from the list of reviewers.

**Pull request merged**
