### PR TITLE
Cleanup grandfathered-in constants in CCPP - round 1

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [n/a] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR updates the submodule pointer for fv3atm and ccpp-physics for the changes described in the associated PRs below. The motivation behind these changes is that physical parameterizations should receive constants (e.g. gravitational acceleration) from the host model via the argument list instead of importing them from some Fortran module or defining them locally. This ensures consistency and enhances interoperability.

The changes in ccpp-physics lead to different answers for the two tests `control_csawmg` and `control_csawmgt` with Intel in PROD mode. With GNU (PROD, DEBUG) and with Intel in DEBUG mode, the results are identical with the previous baseline, thus a consequence of the optimization.

### Issue(s) addressed

These PRs are a step towards resolving issues https://github.com/NCAR/ccpp-physics/issues/104 and https://github.com/NCAR/ccpp-physics/issues/245.

## Testing

Regression tests were run against the existing baselines on July 29, 2021, on Gaea/Intel. All tests passed.

[RegressionTests_gaea.intel.log](https://github.com/ufs-community/ufs-weather-model/files/6904027/RegressionTests_gaea.intel.log

Final regression testing:

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1120107778

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/525
https://github.com/NOAA-EMC/fv3atm/pull/360
https://github.com/ufs-community/ufs-weather-model/pull/726

### CODE REVIEW

**Comment by climbfuji** [comment]
CI tests failed, because the CI tests use old suite definition files that are no longer in use by any of the regression tests and that are removed as part of my commits:
```
FV3_GFS_2017_coupled
FV3_GFS_2017_satmedmf_coupled
FV3_GFS_v15p2_coupled
FV3_GFS_v16_coupled
FV3_GFS_v16_couplednsst
```
We will need to update the CI tests to use suite definition files that are relevant for the current code base.

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/699889232/20210811030036/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_24317
Test compile 006 failed failed 
Test compile 007 failed failed 
Please make changes and add the following label back:
hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/699889232/20210811030007/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_48521
Test compile 002 failed failed 
Test compile 001 failed failed 
Test compile 003 failed failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/699889232/20210811033039/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_6116
Test compile 002 failed failed 
Test compile 003 failed failed 
Test compile 001 failed failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/699889232/20210810220012/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_143518
Test compile 001 failed failed 
Test compile 003 failed failed 
Test compile 002 failed failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/699889232/20210811030016/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_284701
Test compile 003 failed failed 
Test compile 001 failed failed 
Test compile 002 failed failed 
Please make changes and add the following label back:
jet-intel-BL

**Comment by climbfuji** [comment]
> CI tests failed, because the CI tests use old suite definition files that are no longer in use by any of the regression tests and that are removed as part of my commits:
> 
> ```
> FV3_GFS_2017_coupled
> FV3_GFS_2017_satmedmf_coupled
> FV3_GFS_v15p2_coupled
> FV3_GFS_v16_coupled
> FV3_GFS_v16_couplednsst
> ```
> 
> We will need to update the CI tests to use suite definition files that are relevant for the current code base.

Update. I reverted the commits that removed the suite definition files. Rerun all tests.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/699889232/20210811070012/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_65956
Please make changes and add the following label back:
cheyenne-gnu-BL

**Comment by climbfuji** [comment]
> Machine: cheyenne
> Compiler: gnu
> Job: BL
> Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/699889232/20210811070012/ufs-weather-model
> Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_65956
> Please make changes and add the following label back:
> cheyenne-gnu-BL

These tests all passed (first created the baseline, then verified against tit), I am going to upload the log manually. Not sure what happened.

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/699889232/20210811080025/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_48063
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/699889232/20210811090012/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_387698
Test control_noahmp_debug 072 failed in check_result failed 
Test control_noahmp_debug 072 failed in run_test failed 
Test control_thompson_no_aero_debug 075 failed in check_result failed 
Test control_thompson_no_aero_debug 075 failed in run_test failed 
Test control_thompson_debug 074 failed in check_result failed 
Test control_thompson_debug 074 failed in run_test failed 
Test control_ras_debug 071 failed in check_result failed 
Test control_ras_debug 071 failed in run_test failed 
Test control_stochy_debug 062 failed in check_result failed 
Test control_stochy_debug 062 failed in run_test failed 
Test control_lheatstrg_debug 065 failed in check_result failed 
Test control_lheatstrg_debug 065 failed in run_test failed 
Test control_ca_debug 063 failed in check_result failed 
Test control_ca_debug 063 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel_debug 061 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel_debug 061 failed in run_test failed 
Test control_ugwpv1_debug 070 failed in check_result failed 
Test control_ugwpv1_debug 070 failed in run_test failed 
Test control_diag_debug 073 failed in check_result failed 
Test control_diag_debug 073 failed in run_test failed 
Test control_debug 058 failed in check_result failed 
Test control_debug 058 failed in run_test failed 
Test control_CubedSphereGrid_debug 060 failed in check_result failed 
Test control_CubedSphereGrid_debug 060 failed in run_test failed 
Test control_lndp_debug 064 failed in check_result failed 
Test control_lndp_debug 064 failed in run_test failed 
Test control_rrtmgp_debug 067 failed in check_result failed 
Test control_rrtmgp_debug 067 failed in run_test failed 
Test control_thompson_extdiag_debug 076 failed in check_result failed 
Test control_thompson_extdiag_debug 076 failed in run_test failed 
Test control_2threads_debug 059 failed in check_result failed 
Test control_2threads_debug 059 failed in run_test failed 
Test cpld_debug 016 failed in check_result failed 
Test cpld_debug 016 failed in run_test failed 
Test control_merra2_debug 066 failed in check_result failed 
Test control_merra2_debug 066 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 080 failed in check_result failed 
Test fv3_rrfs_v1beta_debug 080 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 081 failed in check_result failed 
Test fv3_rrfs_v1alpha_debug 081 failed in run_test failed 
Test control_csawmg_debug 068 failed in check_result failed 
Test control_csawmg_debug 068 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 082 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 082 failed in run_test failed 
Test fv3_gsd_debug 078 failed in check_result failed 
Test fv3_gsd_debug 078 failed in run_test failed 
Test regional_control_debug 077 failed in check_result failed 
Test regional_control_debug 077 failed in run_test failed 
Test control_csawmgt_debug 069 failed in check_result failed 
Test control_csawmgt_debug 069 failed in run_test failed 
Test control_ca 030 failed in check_result failed 
Test control_ca 030 failed in run_test failed 
Test control_lndp 031 failed in check_result failed 
Test control_lndp 031 failed in run_test failed 
Test control_CubedSphereGrid 022 failed in check_result failed 
Test control_CubedSphereGrid 022 failed in run_test failed 
Test control_stochy 028 failed in check_result failed 
Test control_stochy 028 failed in run_test failed 
Test control_lheatstrg 032 failed in check_result failed 
Test control_lheatstrg 032 failed in run_test failed 
Test control_lseaspray 033 failed in check_result failed 
Test control_lseaspray 033 failed in run_test failed 
Test control_decomp 018 failed in check_result failed 
Test control_decomp 018 failed in run_test failed 
Test control_2threads 019 failed in check_result failed 
Test control_2threads 019 failed in run_test failed 
Test control 017 failed in check_result failed 
Test control 017 failed in run_test failed 
Test control_fhzero 021 failed in check_result failed 
Test control_fhzero 021 failed in run_test failed 
Test cpld_decomp 004 failed in check_result failed 
Test cpld_decomp 004 failed in run_test failed 
Test cpld_ca 005 failed in check_result failed 
Test cpld_ca 005 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 023 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel 023 failed in run_test failed 
Test cpld_control 001 failed in check_result failed 
Test cpld_control 001 failed in run_test failed 
Test control_rrtmgp 035 failed in check_result failed 
Test control_rrtmgp 035 failed in run_test failed 
Test cpld_2threads 003 failed in check_result failed 
Test cpld_2threads 003 failed in run_test failed 
Test regional_quilt_2threads 047 failed in check_result failed 
Test regional_quilt_2threads 047 failed in run_test failed 
Test control_merra2 034 failed in check_result failed 
Test control_merra2 034 failed in run_test failed 
Test control_c48 024 failed in check_result failed 
Test control_c48 024 failed in run_test failed 
Test regional_quilt 046 failed in check_result failed 
Test regional_quilt 046 failed in run_test failed 
Test regional_control 044 failed in check_result failed 
Test regional_control 044 failed in run_test failed 
Test fv3_gsd_diag_debug 079 failed in check_result failed 
Test fv3_gsd_diag_debug 079 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 083 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 083 failed in run_test failed 
Test cpld_control_wave 015 failed in check_result failed 
Test cpld_control_wave 015 failed in run_test failed 
Test control_c192 025 failed in check_result failed 
Test control_c192 025 failed in run_test failed 
Test control_ugwpv1 039 failed in check_result failed 
Test control_ugwpv1 039 failed in run_test failed 
Test control_ras 040 failed in check_result failed 
Test control_ras 040 failed in run_test failed 
Test fv3_rrfs_v1beta 055 failed in check_result failed 
Test fv3_rrfs_v1beta 055 failed in run_test failed 
Test fv3_rrfs_v1alpha 052 failed in check_result failed 
Test fv3_rrfs_v1alpha 052 failed in run_test failed 
Test fv3_rap 053 failed in check_result failed 
Test fv3_rap 053 failed in run_test failed 
Test fv3_hrrr 054 failed in check_result failed 
Test fv3_hrrr 054 failed in run_test failed 
Test control_flake 038 failed in check_result failed 
Test control_flake 038 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 056 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson 056 failed in run_test failed 
Test control_thompson 041 failed in check_result failed 
Test control_thompson 041 failed in run_test failed 
Test control_thompson_no_aero 042 failed in check_result failed 
Test control_thompson_no_aero 042 failed in run_test failed 
Test control_noahmp 043 failed in check_result failed 
Test control_noahmp 043 failed in run_test failed 
Test cpld_control_c192 006 failed in check_result failed 
Test cpld_control_c192 006 failed in run_test failed 
Test datm_control_cfsr 089 failed in check_result failed 
Test datm_control_cfsr 089 failed in run_test failed 
Test regional_quilt_hafs 048 failed in check_result failed 
Test regional_quilt_hafs 048 failed in run_test failed 
Test regional_quilt_netcdf_parallel 049 failed in check_result failed 
Test regional_quilt_netcdf_parallel 049 failed in run_test failed 
Test control_csawmg 036 failed in check_result failed 
Test control_csawmg 036 failed in run_test failed 
Test fv3_gsd 051 failed in check_result failed 
Test fv3_gsd 051 failed in run_test failed 
Test hafs_regional_atm 084 failed in check_result failed 
Test hafs_regional_atm 084 failed in run_test failed 
Test datm_bulk_gefs 094 failed in check_result failed 
Test datm_bulk_gefs 094 failed in run_test failed 
Test control_csawmgt 037 failed in check_result failed 
Test control_csawmgt 037 failed in run_test failed 
Test control_c384gdas 027 failed in check_result failed 
Test control_c384gdas 027 failed in run_test failed 
Test datm_control_gefs 091 failed in check_result failed 
Test datm_control_gefs 091 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 057 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 057 failed in run_test failed 
Test datm_control_iau_gefs 092 failed in check_result failed 
Test datm_control_iau_gefs 092 failed in run_test failed 
Test datm_bulk_cfsr 093 failed in check_result failed 
Test datm_bulk_cfsr 093 failed in run_test failed 
Test regional_quilt_RRTMGP 050 failed in check_result failed 
Test regional_quilt_RRTMGP 050 failed in run_test failed 
Test control_c384 026 failed in check_result failed 
Test control_c384 026 failed in run_test failed 
Test hafs_regional_atm_ocn 085 failed in check_result failed 
Test hafs_regional_atm_ocn 085 failed in run_test failed 
Test datm_cdeps_control_cfsr 098 failed in check_result failed 
Test datm_cdeps_control_cfsr 098 failed in run_test failed 
Test datm_cdeps_bulk_cfsr 101 failed in check_result failed 
Test datm_cdeps_bulk_cfsr 101 failed in run_test failed 
Test datm_cdeps_control_gefs 100 failed in check_result failed 
Test datm_cdeps_control_gefs 100 failed in run_test failed 
Test datm_cdeps_bulk_gefs 102 failed in check_result failed 
Test datm_cdeps_bulk_gefs 102 failed in run_test failed 
Test cpld_bmark_v16 010 failed in check_result failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Test datm_cdeps_multiple_files_cfsr 105 failed in check_result failed 
Test datm_cdeps_multiple_files_cfsr 105 failed in run_test failed 
Test datm_debug_cfsr 097 failed in check_result failed 
Test datm_debug_cfsr 097 failed in run_test failed 
Test hafs_regional_docn 086 failed in check_result failed 
Test hafs_regional_docn 086 failed in run_test failed 
Test hafs_regional_docn_oisst 087 failed in check_result failed 
Test hafs_regional_docn_oisst 087 failed in run_test failed 
Test control_atmwav 107 failed in check_result failed 
Test control_atmwav 107 failed in run_test failed 
Test cpld_control_c384 008 failed in check_result failed 
Test cpld_control_c384 008 failed in run_test failed 
Test cpld_bmark_v16_nsst 012 failed in check_result failed 
Test cpld_bmark_v16_nsst 012 failed in run_test failed 
Test cpld_bmark_wave_v16 013 failed in check_result failed 
Test cpld_bmark_wave_v16 013 failed in run_test failed 
Test datm_mx025_gefs 096 failed in check_result failed 
Test datm_mx025_gefs 096 failed in run_test failed 
Test datm_mx025_cfsr 095 failed in check_result failed 
Test datm_mx025_cfsr 095 failed in run_test failed 
Test datm_cdeps_mx025_cfsr 103 failed in check_result failed 
Test datm_cdeps_mx025_cfsr 103 failed in run_test failed 
Test datm_cdeps_mx025_gefs 104 failed in check_result failed 
Test datm_cdeps_mx025_gefs 104 failed in run_test failed 
Test datm_cdeps_debug_cfsr 106 failed in check_result failed 
Test datm_cdeps_debug_cfsr 106 failed in run_test failed 
Test cpld_bmark_wave_v16_p7b 014 failed in check_result failed 
Test cpld_bmark_wave_v16_p7b 014 failed in run_test failed 
Test hafs_regional_datm_cdeps 088 failed in check_result failed 
Test hafs_regional_datm_cdeps 088 failed in run_test failed 
Test control_c384gdas_wav 108 failed in check_result failed 
Test control_c384gdas_wav 108 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Comment by climbfuji** [comment]
@DusanJovic-NOAA ready for commit - fv3atm submodule pointer is updated and correct. Thanks!

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
