### PR TITLE
Reduce fhmax for cpld_c192_p7 test; update to ESMF 8.2.0 and MAPL 2.11.0

### LINKED ISSUE #878: reduce forecast hours for cpld_control_c192_p7 and adjust restart test
## Description

The cpld_control_c192_p7 test runs for ``fhmax=48``. The associated restart test restarts at hour 12 and runs out for 36 hours. During regression testing, this test often times out. 

## Solution
We should reduce the forecast length for the control test and adjust the restart test to match.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Reduces fhmax for ``coupled_control_c192_p7`` test and associated restart test. A new baseline will be required for the c192 coupled test pair.

### Issue(s) addressed

- fixes #878

## Testing

The adjusted test passed a control/restart test on hera.intel. The adjusted control test ran in under 15mins.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/runs/4106812227?check_suite_focus=true

## Dependencies

None

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/764962795/20211104081509/ufs-weather-model
/glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20211101/GNU
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
cheyenne-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/764962795/20211104141509/ufs-weather-model
/lfs4/HFIP/h-nems/emc.nemspara/RT/NEMSfv3gfs//develop-20211101/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/764962795/20211104091516/ufs-weather-model
/work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211101/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/764962795/20211104141507/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211101/GNU
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/764962795/20211104081617/ufs-weather-model
/glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20211101/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/764962795/20211104141512/ufs-weather-model
/lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20211101/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/764962795/20211104141649/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211101/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-intel-BL

**Comment by MinsukJi-NOAA** [comment]
CI was able to pass without updating the esmf library.  But I will get the container esmf library updated in a future PR.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
