### PR TITLE
initialize scalar field when created for non-CSG (cube-sphere grid) components

### LINKED ISSUE #2338: cpld_debug_gfsv17_intel failure on Derecho in the PR 2324
## Description

The cpld_debug_gfsv17_intel case passes when running on the develop branch. But it crashes from https://github.com/ufs-community/ufs-weather-model/pull/2324 with error message:
```
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
libpthread-2.31.s  000014C29057C8C0  Unknown               Unknown  Unknown
fv3.exe            0000000012250BF8  med_mp_datainitia        2147  med.F90
```

### LINKED ISSUE #2369: cpl_scalar fields should be initialized in non-CSG components when created
## Description

Non-CSG components do not use or set the scalar index for ``NTile``. In certain cases, the scalar field value for this index has been found to be non-zero (NaN in debug compiles). This is the cause of the failure reported in #2338.  

### To Reproduce:

Run the case reported in #2338 and modify the required routines to print out the cpl_scalar values retrieved by CMEPS from each component.

## Additional context

So far, this condition was found on a single platform and only for intel debug. I was able to force a GNU debug compile on Derecho, and the case did not fail. It has also not been seen for any component other than MOM6, even though all components (WW3, CICE and MOM6) create and set the scalar field in the same way. 

Initializing the scalar field in MOM6 alone resolves #2338, but initialization should be done for all non-CSG components (those which do not use the ``NTile`` scalar).

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Initializes the scalar field when created for MOM6, CICE and WW3.

### Commit Message:

```
* UFSWM - 
  * CICE - initialize scalar field when created
  * MOM6 - initialize scalar field when created
  * WW3 - initialize scalar field when created
```

### Priority:

* Normal

### UFSWM:

* Closes #2369 
* Closes #2338 
### Sub component Pull Requests:

* CICE: https://github.com/NOAA-EMC/CICE/pull/83
* MOM6: https://github.com/NOAA-EMC/MOM6/pull/135
* WW3: https://github.com/NOAA-EMC/WW3/pull/1274

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.

The ``cpld_debug_gfsv17_intel `` baseline on derecho will need to be created. A test baseline using this PR was created and was B4B on re-run.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
The test_changes.list was empty, so I couldn't commit it (shows no diff w/ previous file).

**Comment by jkbk2004** [comment]
@zach1221 @FernandoAndrade-NOAA can we check if derecho is available for a quick pre-test? If we have resource issue on derecho, I suggest to move to #2375 and prepare.

**Comment by zach1221** [comment]
> @zach1221 @FernandoAndrade-NOAA can we check if derecho is available for a quick pre-test? If we have resource issue on derecho, I suggest to move to #2375 and prepare.

I'm running on derecho now and the jobs are submitting ok so far.

**Comment by jiandewang** [comment]
I am not in front of computer at this moment, will do MOM merging around 9:30pm tonight

**Comment by jiandewang** [comment]
just merged MOM6, hash # 4b8777eb

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
