### PR TITLE
update fv3 file path length

### PR DESCRIPTION
**Pull request by jedwards4b**
Make variables for file path length consistent - this is needed for CIME test generation.  

https://github.com/NOAA-EMC/fv3atm/pull/43?email_source=notifications&email_token=ABOXUGHHOXIDYVHIWQN6OOLQ5Z7HDA5CNFSM4KG3W6VKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCRYVJ5A#pullrequestreview-342971636

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hera. @jedwards4b please commit there two log files to your branch.
@climbfuji can you run regtest on Cheyenne and send log files.

[Compile_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/4067078/Compile_hera.intel.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/4067079/RegressionTests_hera.intel.log)

**Comment by climbfuji** [comment]
I just started the tests on Cheyenne, if they don't finish in time I will send you the logs tomorrow.

**Comment by jedwards4b** [comment]
@climbfuji Thanks Dom, tomorrow is fine.

**Comment by climbfuji** [comment]
Cheyenne+GNU

also in /glade/work/heinzell/fv3/ufs-weather-model/ufs-weather-model-pr-jedwards-20200115/gnu/tests/

[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4069212/RegressionTests_cheyenne.gnu.log)
[Compile_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4069213/Compile_cheyenne.gnu.log)

**Comment by climbfuji** [comment]
Cheyenne+Intel

also in /glade/work/heinzell/fv3/ufs-weather-model/ufs-weather-model-pr-jedwards-20200115/intel/tests/

[Compile_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/4069315/Compile_cheyenne.intel.log)
[RegressionTests_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/4069316/RegressionTests_cheyenne.intel.log)

**Comment by jedwards4b** [comment]
@climbfuji I've updated these logs in the branch - thanks.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
