### PR TITLE
[production/RRFS.v1] MYNN PBL & Smoke update for RRFS.v1

### PR DESCRIPTION
**Pull request by haiqinli**
## Commit Queue Requirements:

- [ V] Fill out all sections of this template.
- [ V] All sub component pull requests have been reviewed by their code managers.
- [ V] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ V] Commit 'test_changes.list' from previous step
---
### Commit Message:

```
* UFSWM - 
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - 
    * ccpp-physics - MYNN PBL, Smoke and subgrid cloud fraction.
    * atmos_cubed_sphere - hail diagnostics, and average of smoke/dust.
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 - 
  * stochastic_physics - 
```

### Priority:

* AQM:
* CDEPS:
* CICE:
* CMEPS:
* CMakeModules:
* FV3:
  * ccpp-physics:https://github.com/ufs-community/ccpp-physics/pull/180
  * atmos_cubed_sphere: https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/87

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.
* PR Updates/Changes Baselines.
* No Baseline Changes.

### Input data Changes:
* None.

  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
@haiqinli Given the physics changes, this PR should change RT baselines. I'm wondering if we could combine this with https://github.com/ufs-community/ufs-weather-model/pull/2161 and the scientists involved with the RRFS.v1 release could OK the results change for us. @AndersJensen-NOAA is working on looking at the changes from https://github.com/ufs-community/ufs-weather-model/pull/2161 separately, but if this PR is also changing the answer, it seems like they could be combined and folks (e.g. scientists involved with the RRFS release) could review the output for skill for the combined PRs to save time.

**Comment by grantfirl** [comment]
@haiqinli Also, are there any more updates coming for the RRFS release? I thought that this was supposed to be frozen a while ago...

**Comment by haiqinli** [comment]
@grantfirl Sure, let's combine the changes from https://github.com/ufs-community/ufs-weather-model/pull/2161. We may also add a little smoke diurnal cycle updates into this PR. I hope these are all our changes for the code freeze. Thanks.

**Comment by grantfirl** [comment]
@haiqinli Who has been involved with approving results changes for the RRFS.v1 release?

**Comment by haiqinli** [comment]
> @haiqinli Who has been involved with approving results changes for the RRFS.v1 release?

Joe, Ravan and Ming.

**Comment by grantfirl** [comment]
@haiqinli Please merge in the latest production/RRFS.v1 branch

**Comment by MatthewPyle-NOAA** [comment]
@haiqinli Will echo @grantfirl  - can you update your branch so we can proceed with this one?

**Comment by haiqinli** [comment]
@MatthewPyle-NOAA Sorry, I forgot to push it back. The update is done.

**Comment by grantfirl** [comment]
@MatthewPyle-NOAA Haiqin said that he is adding one more update to the smoke physics code before we test/approve/merge this one.

**Comment by MatthewPyle-NOAA** [comment]
Sounds good.  Thanks @haiqinli and @grantfirl

**Comment by haiqinli** [comment]
@grantfirl All the updates and merging works are done, and the regression test is also successfully done. It is ready for testing. Thanks.

**Comment by grantfirl** [comment]
@MatthewPyle-NOAA @haiqinli I think that we're ready to test this one. @haiqinli has the MYNN PBL, smoke, and cloud fraction changes from @JiliDong-NOAA all staged in this PR and the RT log shows the expected RT failures. @haiqinli Please double-check that the failures listed are all expected. The MYNN PBL changes alone should change the results for all tests using RAP and HRRR suites.

**Comment by grantfirl** [comment]
@haiqinli Thanks for all of the work combining things. It looks like we were writing a comment at the same time!

**Comment by MatthewPyle-NOAA** [comment]
I'll test and update the baselines on WCOSS2.  Thanks!

**Comment by MatthewPyle-NOAA** [comment]
Is anyone else having trouble with this PR?    I had a few debug tests crash:

hrrr_control_debug_intel 021 failed in run_test
hrrr_gf_debug_intel 022 failed in run_test
hrrr_c3_debug_intel 023 failed in run_test
hrrr_control_debug_dyn32_phy32_intel 042 failed in run_test

All had this complaint about RHO_DRY.

```
+ mpiexec -n 256 -ppn 128 -depth 1 ./fv3.exe
forrtl: severe (408): fort: (7): Attempt to use pointer RHO_DRY when it is not associated with a target
```

**Comment by grantfirl** [comment]
> Is anyone else having trouble with this PR? I had a few debug tests crash:
> 
> hrrr_control_debug_intel 021 failed in run_test hrrr_gf_debug_intel 022 failed in run_test hrrr_c3_debug_intel 023 failed in run_test hrrr_control_debug_dyn32_phy32_intel 042 failed in run_test
> 
> All had this complaint about RHO_DRY.
> 
> ```
> + mpiexec -n 256 -ppn 128 -depth 1 ./fv3.exe
> forrtl: severe (408): fort: (7): Attempt to use pointer RHO_DRY when it is not associated with a target
> ```

I think I know how to fix this, although I'm not sure why these failures weren't caught by @haiqinli 's tests. Please stand by a sec while I take a look.

**Comment by grantfirl** [comment]
> Is anyone else having trouble with this PR? I had a few debug tests crash:
> 
> hrrr_control_debug_intel 021 failed in run_test hrrr_gf_debug_intel 022 failed in run_test hrrr_c3_debug_intel 023 failed in run_test hrrr_control_debug_dyn32_phy32_intel 042 failed in run_test
> 
> All had this complaint about RHO_DRY.
> 
> ```
> + mpiexec -n 256 -ppn 128 -depth 1 ./fv3.exe
> forrtl: severe (408): fort: (7): Attempt to use pointer RHO_DRY when it is not associated with a target
> ```

@haiqinli @MatthewPyle-NOAA Please see https://github.com/haiqinli/fv3atm/pull/2 for the fix. @haiqinli Please merge this so that tests can be restarted.

**Comment by grantfirl** [comment]
> > Is anyone else having trouble with this PR? I had a few debug tests crash:
> > hrrr_control_debug_intel 021 failed in run_test hrrr_gf_debug_intel 022 failed in run_test hrrr_c3_debug_intel 023 failed in run_test hrrr_control_debug_dyn32_phy32_intel 042 failed in run_test
> > All had this complaint about RHO_DRY.
> > ```
> > + mpiexec -n 256 -ppn 128 -depth 1 ./fv3.exe
> > forrtl: severe (408): fort: (7): Attempt to use pointer RHO_DRY when it is not associated with a target
> > ```
> 
> @haiqinli @MatthewPyle-NOAA Please see [haiqinli/fv3atm#2](https://github.com/haiqinli/fv3atm/pull/2) for the fix. @haiqinli Please merge this so that tests can be restarted.

This error only shows up in debug mode because that is when `check all` is used as a compilation flag.

**Comment by haiqinli** [comment]
@grantfirl @MatthewPyle-NOAA This fix has been merged. Thanks.

**Comment by MatthewPyle-NOAA** [comment]
@haiqinli - can you update everything so this PR points at the latest fix?

**Comment by haiqinli** [comment]
@MatthewPyle-NOAA Sure, it is done. Thanks.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @haiqinli and @grantfirl - testing on WCOSS went smoothly this time.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA Orion queue has been slow. I think it should be ok to skip orion.

**Comment by MatthewPyle-NOAA** [comment]
That works for me @jkbk2004

**Comment by jkbk2004** [comment]
> That works for me @jkbk2004

@MatthewPyle-NOAA Great! We can start merging process.

**Comment by jkbk2004** [comment]
@haiqinli can you update fv3 hash and revert change in gitmodules? correct hash is https://github.com/NOAA-EMC/fv3atm/commit/f9a17596cc4beda4eaf7706cb67e991918afd23f

**Comment by haiqinli** [comment]
@jkbk2004 The fv3 hash has been updated to [NOAA-EMC/fv3atm@f9a1759](https://github.com/NOAA-EMC/fv3atm/commit/f9a17596cc4beda4eaf7706cb67e991918afd23f). Thanks.

**Pull request merged**
