### PR TITLE
Bug fix for the NoahMP tiled t2m and q2m

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR is created on behalf of Helin Wei and the Land team@EMC

This PR fixed a bug for the NoahMP internal diagnosed tiled values for t2m and q2m. Those values over the bared soil have been improved significantly after the bug fix.

### Issue(s) addressed

The issue is described in ccpp-physics PR https://github.com/ufs-community/ccpp-physics/pull/25.

## Testing

A full regression test was conducted on hera.intel.  All RTs using the NoahMP scheme failed due to the failed result check, which is expected. The failed RTs are:
cpld_control_p8 001 failed in check_result
cpld_2threads_p8 003 failed in check_result
cpld_esmfthreads_p8 004 failed in check_result
cpld_decomp_p8 005 failed in check_result
cpld_mpi_p8 006 failed in check_result
cpld_control_ciceC_p8 007 failed in check_result
cpld_control_c192_p8 008 failed in check_result
cpld_bmark_p8 010 failed in check_result
cpld_control_noaero_p8 012 failed in check_result
cpld_control_nowave_noaero_p8 013 failed in check_result
cpld_debug_p8 014 failed in check_result
cpld_debug_noaero_p8 015 failed in check_result
cpld_control_noaero_p8_agrid 016 failed in check_result
cpld_control_c48 017 failed in check_result
cpld_warmstart_c48 018 failed in check_result
control_p8 040 failed in check_result
control_p8_lndp 041 failed in check_result
control_decomp_p8 043 failed in check_result
control_2threads_p8 044 failed in check_result
control_p8_rrtmgp 045 failed in check_result
merra2_thompson 046 failed in check_result
rrfs_v1beta 068 failed in check_result
rrfs_v1nssl 069 failed in check_result
rrfs_v1nssl_nohailnoccn 070 failed in check_result
control_debug_p8 092 failed in check_result
rrfs_v1beta_debug 107 failed in check_result
control_p8_atmlnd_sbs 154 failed in check_result
atmaero_control_p8 156 failed in check_result
atmaero_control_p8_rad 157 failed in check_result
atmaero_control_p8_rad_micro 158 failed in check_result

A full ORT test passed for control_p8.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- acorn.intel (skipped due to work on queue)
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on ufs-community/ccpp-physics/pull/<[25](https://github.com/ufs-community/ccpp-physics/pull/25)>
- waiting on noaa-emc/fv3atm/pull/<[607](https://github.com/NOAA-EMC/fv3atm/pull/607)>

### CODE REVIEW

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 This PR is ready for the commit process.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA sure! I am adding new BL_DATE.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Thank you Jong!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1142052108/20221202003016/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1142052108/20221202031147/ufs-weather-model
[RT] Error: Test control_c384 028 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1142052108/20221202003007/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1142052108/20221202022746/ufs-weather-model
[RT] Error: Test cpld_restart_c192_p8 009 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by jkbk2004** [comment]
Once again, timing out issue for a few cases on gaea/jet. Manually covered ok. We will skip jenkins-ci. @BrianCurtis-NOAA what about acorn?

**Comment by BrianCurtis-NOAA** [comment]
> Once again, timing out issue for a few cases on gaea/jet. Manually covered ok. We will skip jenkins-ci. @BrianCurtis-NOAA what about acorn?

skipped as queue still down

**Comment by jkbk2004** [comment]
Sure! @ChunxiZhang-NOAA we are ready to merge in the pr.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA fv3 pr was merged. Please, go ahead to revert gitmodules branch and update submodule pointer.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Done.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
