### PR TITLE
NCAR-main PR#956

### PR DESCRIPTION
**Pull request by dustinswales**
## Description

This PR contains new interstitial variables in GFS_typedefs to accommodate changes in the underlying physics. These changes are mostly related to the removal of a radiation configuration(data) module, physparam.f. Runtime information is set in GFS_typedefs and provided through the ccpp infrastructure, instead of referencing physparam.f throughout the physics.

### Issue(s) addressed
Detailed in [NCAR #956](https://github.com/NCAR/ccpp-physics/pull/956)

## Testing

Tested on Cheyenne and Hera with Intel.
Updates need for the RRTMGP RTs (see conversation in https://github.com/NCAR/ccpp-physics/pull/956)

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests:  control_p8_rrtmgp

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- depends on NOAA-EMC/fv3atm/pull/623
- depends on ufs-community/ccpp-physics/pull/38

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by zach1221** [comment]
Hi, @dustinswales. We are going to merge PR #1599 soon, then we'll begin working this one. Would you be able to resolve conflicts?

**Comment by dustinswales** [comment]
@zach1221 Should be all up-to-date now.

**Comment by zach1221** [comment]
@dustinswales thank you. Please attach your test logs as well, if you have them.

**Comment by dustinswales** [comment]
@zach1221 Sorry, I just wiped my logs when I synced. (I will make note to save for future PRs)

**Comment by jkbk2004** [comment]
@dustinswales hycom is pointing to https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface. Can you fix? this pr has nothing to do with hycom.

**Comment by zach1221** [comment]
Please see Jenkins-ci logs attached. ORT have passed.
[ufs-weather-model » ort-docker-pipeline » PR-1604 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10844791/ufs-weather-model.ort-docker-pipeline.PR-1604.1.Console.Jenkins.pdf)

**Comment by dustinswales** [comment]
> @dustinswales hycom is pointing to https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface. Can you fix? this pr has nothing to do with hycom.

@jkbk2004 Sorry, I don't see any issues w/ hycom?

**Comment by jkbk2004** [comment]
> > @dustinswales hycom is pointing to https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface. Can you fix? this pr has nothing to do with hycom.
> 
> @jkbk2004 Sorry, I don't see any issues w/ hycom?

It should point to develop/HYCOM-interface. And I see 6 commit ahead in your ncar-main-PR956 branch
. I am wondering how test passes if some code change in hycom.

**Comment by dustinswales** [comment]
> > > @dustinswales hycom is pointing to https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface. Can you fix? this pr has nothing to do with hycom.
> > 
> > 
> > @jkbk2004 Sorry, I don't see any issues w/ hycom?
> 
> It should point to develop/HYCOM-interface. And I see 6 commit ahead in your ncar-main-PR956 branch . I am wondering how test passes if some code change in hycom.

It's [pointing](https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface) to the correct. [place](https://github.com/ufs-community/ufs-weather-model/tree/develop/HYCOM-interface). No? ([The 6 commits are only in the FV3](https://github.com/ufs-community/ufs-weather-model/compare/develop...dustinswales:ufs-weather-model:ncar-main-PR956))

**Comment by jkbk2004** [comment]
> > > > @dustinswales hycom is pointing to https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface. Can you fix? this pr has nothing to do with hycom.
> > > 
> > > 
> > > @jkbk2004 Sorry, I don't see any issues w/ hycom?
> > 
> > 
> > It should point to develop/HYCOM-interface. And I see 6 commit ahead in your ncar-main-PR956 branch . I am wondering how test passes if some code change in hycom.
> 
> It's [pointing](https://github.com/dustinswales/ufs-weather-model/tree/ncar-main-PR956/HYCOM-interface) to the correct. [place](https://github.com/ufs-community/ufs-weather-model/tree/develop/HYCOM-interface). No? ([The 6 commits are only in the FV3](https://github.com/ufs-community/ufs-weather-model/compare/develop...dustinswales:ufs-weather-model:ncar-main-PR956))

let me try to build test for a hafs case.

**Comment by DeniseWorthen** [comment]
I also don't understand the issue. Dustin's PR is using HYCOM hash [2443753](https://github.com/NOAA-EMC/HYCOM-src/tree/24437531dcf8580aadaf6ebeb9de544ccfc674f9). That is the current hash in UWM.

**Comment by jkbk2004** [comment]
> I also don't understand the issue. Dustin's PR is using HYCOM hash [2443753](https://github.com/NOAA-EMC/HYCOM-src/tree/24437531dcf8580aadaf6ebeb9de544ccfc674f9). That is the current hash in UWM.

I could be wrong. let me test manually on cheyenne to confirm.

**Comment by jkbk2004** [comment]
[RegressionTests_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10845685/RegressionTests_cheyenne.intel.log)
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10845686/RegressionTests_cheyenne.gnu.log)
Ignore my previous comment! Confirm all fine. We need to create new baseline only for control_p8_rrtmgp

**Comment by jkbk2004** [comment]
@zach1221 I will extend my test on cheyenne to create and copy control_p8_rrtmgp to new BL_DATE.

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1234188003/20230228173019/ufs-weather-model
[RT] Error: Test cpld_debug_p8 015 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 092 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1234188003/20230228110118/ufs-weather-model
[RT] Error: Test compile_001 failed in run_compile failed 
[RT] Error: Test compile_002 failed in run_compile failed 
[RT] Error: Test compile_003 failed in run_compile failed 
[RT] Error: Test compile_004 failed in run_compile failed 
[RT] Error: Test compile_005 failed in run_compile failed 
[RT] Error: Test compile_006 failed in run_compile failed 
[RT] Error: Test compile_007 failed in run_compile failed 
[RT] Error: Test compile_008 failed in run_compile failed 
[RT] Error: Test compile_009 failed in run_compile failed 
[RT] Error: Test compile_010 failed in run_compile failed 
[RT] Error: Test compile_011 failed in run_compile failed 
[RT] Error: Test compile_012 failed in run_compile failed 
[RT] Error: Test compile_013 failed in run_compile failed 
[RT] Error: Test compile_014 failed in run_compile failed 
[RT] Error: Test compile_015 failed in run_compile failed 
[RT] Error: Test compile_016 failed in run_compile failed 
[RT] Error: Test compile_017 failed in run_compile failed 
[RT] Error: Test compile_018 failed in run_compile failed 
[RT] Error: Test compile_019 failed in run_compile failed 
[RT] Error: Test compile_020 failed in run_compile failed 
[RT] Error: Test compile_021 failed in run_compile failed 
[RT] Error: Test compile_025 failed in run_compile failed 
[RT] Error: Test compile_026 failed in run_compile failed 
[RT] Error: Test compile_027 failed in run_compile failed 
[RT] Error: Test compile_028 failed in run_compile failed 
[RT] Error: Test compile_029 failed in run_compile failed 
Please make changes and add the following label back: orion-intel-RT

**Comment by zach1221** [comment]
Time out issue caused two tests to fail on Gaea, those were run successfully via manual process. 
Orion failures also appear system related. We'll attempt to complete those manually as well.

**Comment by jkbk2004** [comment]
Sounds like orion system issue with git module: need version 28. Some people started complaining about it.

**Comment by BrianCurtis-NOAA** [comment]
You can skip Cactus for this. I've confirmed the permissions were incorrect on 12 tests in the develop-20230227 directory and fixed that issue. This was the cause of the 12 tests that failed the RT. Let's not delay this any further.

**Comment by jkbk2004** [comment]
Sure, we will start merging process.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dustinswales can you update fv3 hash https://github.com/NOAA-EMC/fv3atm/commit/c932926825c1729fa41d127f8e8115007047722d ?

**Pull request merged**
