### PR TITLE
Update ci

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Latest PR #448 removed the ccpp string from test names; e.g. fv3_ccpp_control is now fv3_control.
This PR updates utest- and ci- related files to keep up to date with the new convention.

### Issue(s) addressed

No issue created since it's a quick and minor fix.

## Testing

This PR only affects ci and utest related files, no RT is required. It can be combined with other PR's in the queue since changes are minor. CI test will run to make sure it can be completed without error.

## Dependencies

No dependencies

### CODE REVIEW

**Comment by climbfuji** [comment]
Thanks, Minsuk, for making those changes. Sorry that I didn't think about changing the test names for the CI.

**Comment by MinsukJi-NOAA** [comment]
> Thanks, Minsuk, for making those changes. Sorry that I didn't think about changing the test names for the CI.

No worries Dom. I missed it as well.

**Comment by pjpegion** [comment]
@MinsukJi-NOAA I'm happy to pull this PR in with https://github.com/ufs-community/ufs-weather-model/pull/372

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA I'm happy to pull this PR in with #372

Phil, I made a PR to your stoch_updates branch for #372

**Comment by junwang-noaa** [comment]
Merged in #372, close PR.

**Pull request closed without merging**
