### PR TITLE
Link full CDEPS library at compile time instead of data components.

### LINKED ISSUE #416: Having more flexible Cmake build system
## Description
I am currently working on integrating CDEPS data components with the model under HAFS application. This also requires extensive work related with the Cmake build system to build different data component configurations as well as adding PIO to support both CMEPS and CDEPS. The good news is that the initial version is ready in the following repository that supports DATM+DOCN and DATM+HYCOM configurations (FV3+DOCN will be available soon). 

https://github.com/hafs-community/ufs-weather-model.git - feature/hafs_couplehycom_cdeps branch

While I was working with the Cmake build I had couple of issues related with the Cmake build system and I would like to bring them to your attention. I think that these needs to be addressed in the near future.

- The current Cmake build system is not flexible enough to turn on/off individual model components and this requires lots of customization in the Cmake build system especially to support new data components provided by the CDEPS and other possible applications/components. One example for it is that FMS needs to build in all the cases even if I build CDEPS DATM+HYCOM case, that does not require FMS. Currently, there is no way to activate FMS only if FV3 or MOM6 are activated. Also, there is no way to turn on/off MOM6 and CICE explicitly such as MOM6=Y or CICE=Y. Those are just controlled by S2S build shortcut, which also makes the build more complicated. I think that those components also need to follow the same implementation way like WW3 and HYCOM. Since data components will be available soon and having multiple ocean components like MOM6, HYCOM, having flexible build system that allows to create different combinations of model components by turning on/off them easily by defining dependency between them will be crucial for the UFS model. This will simplify the top level Cmake file and also enable easy development and integration of other applications such as HAFS.

-  S2S shortcut is also creating another confusion because rather than tuning on CMPES, MOM6 and CICE explicitly. You could just set S2S=Y. This does not follow the current convention and requires additional customization when new dependencies and components will be available. One example of it is that i had problem related with supporting S2S related configurations by extending PIO support for CMEPS and CDEPS under the modeling system. It took extensive time for me to figure out that S2S also requires additional hack to make S2S RT test runs without any problem. The shortcuts like S2S can be still available but maybe the implementation logic can be revisited such as if you set S2S=Y it could trigger CMEPS=Y, MOM6=Y and CICE=Y rater then adding/activating them inside the S2S block or defining their dependencies such as FMS.

## Solution
The easiest solution is to follow the same logic used in WW3 and HYCOM and allow explicit control for all components including FV3, FMS etc. This will allow to user build only required components and reduce the executable size and improve the model performance slightly. 

## Alternatives
N/A

## Related to
N/A

### PR DESCRIPTION
**Pull request by aerorahul**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories
- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories (In progress)
- [x] An Issue describing the work contained in this PR has been created in the ufs-weather-model #416

## Description

This PR creates a full CDEPS static library instead of assembling individual data component libraries.
This will allow users to choose a data component at runtime instead of at compile time.

There is one issue with this however:
At compile time, the following compiler definition is added:
```
list(APPEND _ufs_defs_private FRONT_CDEPS_DATM=atm_comp_nuopc)
```

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #416 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

None.

### CODE REVIEW

**Review by uturuncoglu — APPROVED** [review]
I think, this is the same change that i previously tested under HAFS without any issue and it allowed me to compile data ocean also. Thanks for this quick fix.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
Thanks for making the code changes. Maybe we can combine this PR with PR#603, which is planned for tomorrow.

**Comment by MinsukJi-NOAA** [comment]
@aerorahul I will pull the code changes in this PR into #603 for commit today. Please let me know if you have comments/questions.

**Comment by aerorahul** [comment]
@MinsukJi-NOAA 
I have not run the tests, but @DusanJovic-NOAA did.
He found that all the `datm_cdeps` tests failed.
I don't know much about CDEPS and building one library or multiple libraries cause different results.
@uturuncoglu may have some ideas.

**Comment by uturuncoglu** [comment]
@aerorahul it was working in may side. could you share the exact error with me. BTW, my Orion account is expired and it is hard for me to test the issue until it is activated again.

**Comment by DusanJovic-NOAA** [comment]
I was testing other PR (#615) that also includes cdeps changes, I beleive the same as this PR, and this is the error I get:
```
20210602 114004.124 INFO             PET28 (dshr_advertise) flds_scalar_name = cpl_scalars
20210602 114004.124 INFO             PET28 (dshr_advertise) flds_scalar_num =            3
20210602 114004.124 INFO             PET28 (dshr_advertise) : flds_scalar_index_nx =            1
20210602 114004.124 INFO             PET28 (dshr_advertise) : flds_scalar_index_ny =            2
20210602 114004.124 ERROR            PET28 /lustre/f2/pdata/esrl/gsd/ufs/hpc-stack-v1.1.0/src/hpc-stack-v1.1.0/pkg/ESMF_8_1_1/src/Infrastructure/Base/src/ESMCI_Info.C:830 Info::get(): Key not found (JSON trace will follow): /NUOPC/Instance/diro
20210602 114004.124 ERROR            PET28 ESMCI_Info.C:832 Info::get() Attribute not set  - [json.exception.out_of_range.403] key 'diro' not found
20210602 114004.125 ERROR            PET28 ESMCI_Info.C:836 Info::get() Attribute not set  - Internal subroutine call returned Error
20210602 114004.125 ERROR            PET28 ESMC_InfoCDef.C:601 ESMC_InfoGetCH() Attribute not set  - Internal subroutine call returned Error
20210602 114004.125 ERROR            PET28 ESMF_Info.F90:984 ESMF_InfoGetCH() Attribute not set  - Internal subroutine call returned Error
20210602 114004.125 ERROR            PET28 src/addon/NUOPC/src/NUOPC_Comp.F90:611 Attribute not set  - Passing error in return code
20210602 114004.125 ERROR            PET28 dshr_mod.F90:181 Attribute not set  - Passing error in return code
20210602 114004.125 ERROR            PET28 ice_comp_nuopc.F90:187 Attribute not set  - Passing error in return code
20210602 114004.125 ERROR            PET28 EARTH grid component:src/addon/NUOPC/src/NUOPC_Driver.F90:2570 Attribute not set  - Phase 'IPDv01p1' Initialize for modelComp 4: ICE did not return ESMF_SUCCESS
20210602 114004.125 ERROR            PET28 EARTH grid component:src/addon/NUOPC/src/NUOPC_Driver.F90:1267 Attribute not set  - Passing error in return code
20210602 114004.125 ERROR            PET28 EARTH grid component:src/addon/NUOPC/src/NUOPC_Driver.F90:466 Attribute not set  - Passing error in return code
20210602 114004.125 ERROR            PET28 module_NEMS_GRID_COMP.F90:396 Attribute not set  - Breaking out of subroutine
20210602 114004.125 ERROR            PET28 MAIN_NEMS.F90:476 Attribute not set  - Aborting NEMS
20210602 114004.125 INFO             PET28 Finalizing ESMF
```
Maybe the error is due to unrelated change in that PR. Not sure.

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA in this configuration do you have data ice? I am not sure why you are getting this error but adding following section to nems.configure for all data components will help you pass the issue. 

```
[COMP]_modelio::
     diro = .
     logfile = [COMP].log
::
```

BTW, [COMP] needs to be replaced with the name of the component such as ICE, OCN etc. The [COMP] in the logfile can be lowercase.

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA BTW, maybe I did not get any error in my cases because I am always adding those attributes in nems.configure.

**Comment by uturuncoglu** [comment]
@aerorahul i am not sure but maybe providing combined library to the model is not a good idea. If this configuration has real ICE component such as CICE and providing combined library could case a confusion in the NEMS side until we add all data components in there such as ATM and OCN.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA in this configuration do you have data ice? I am not sure why you are getting this error but adding following section to nems.configure for all data components will help you pass the issue.
> 
> ```
> [COMP]_modelio::
>      diro = .
>      logfile = [COMP].log
> ::
> ```
> 
> BTW, [COMP] needs to be replaced with the name of the component such as ICE, OCN etc. The [COMP] in the logfile can be lowercase.

I do not know, the following tests failed:

Test 107 datm_debug_cfsr PASS
Test 108 datm_cdeps_control_cfsr **FAIL**
Test 110 datm_cdeps_control_gefs **FAIL**
Test 111 datm_cdeps_bulk_cfsr **FAIL**
Test 112 datm_cdeps_bulk_gefs **FAIL**
Test 113 datm_cdeps_mx025_gefs **FAIL**
Test 114 datm_cdeps_multiple_files_cfsr **FAIL**
Test 115 datm_cdeps_debug_cfsr **FAIL**
Test 116 fv3_gfdlmprad PASS
Test 117 fv3_gfdlmprad_atmwav PASS

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA if you look at following file which is used for CDEPS RTs, `https://github.com/aerorahul/ufs-weather-model/blob/feature/cmake_flags_cleanup/tests/parm/nems.configure.datm_cdeps.IN` there is no such attributes in there and it has active ice component. If you look at NEMS side there is no DICE and if FRONT_CICE6 is same with ice_comp_nuopc.F90, which seems like that `https://github.com/NOAA-EMC/CICE/blob/2eca569055a0bcbd0f72859bc7d71ba802231ffe/cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90`, it explains the confusion. You could not add both dice and real ice (CICE) together to the executable. So, this is because I was always proposing control CDEPS data models individually and adding their library individually. If you still go with combined library, this will require lots of additional work in NEMS and also active model components side.

**Comment by aerorahul** [comment]
I am going to close this PR.  It is not worth holding up the queue.  Please continue discussion in this PR or open a new issue.
We need to identify why linking with the entire CDEPS library at build time and choosing data components at runtime is problematic.

**Comment by uturuncoglu** [comment]
@aerorahul I think that we need to resolve this as soon as possible because this is preventing me to continue development in HAFS side that i am already behind of my schedule. I waited for the GEFS and CFSR CDEPS PR as well as build changes that bring APP but those creates additional conflicts and issues in HAFS side and we need to think more general about it. I think that best way is to solve the issue is to support enabling individual data components and get rid of linking combined CDEPS library. I don't want to implement a workaround in HAFS level that you might not like.

**Comment by junwang-noaa** [comment]
I created a ufs-weather-model issue #616
<https://github.com/ufs-community/ufs-weather-model/issues/616> to continue
the discussion.

**Comment by uturuncoglu** [comment]
@aerorahul The CDEPS PR is merged recently. So, I just wonder if is this PR will be merged to the develop soon? Thanks.

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA @junwang-noaa I am solving issue with missing `[COMP]_modelio` attribute in CDEPS. This was working for me because I had version of NEMS in HAFS fork that pass `_modelio` attributes to the components, which is not merged with the NEMS NOAA/EMC fork due to the lots of delay in my side and also CDEPS work in UFS level. I am thinking solution like,

1) NEMS provides those attributes if they are in the nems.configure
2) If not CDEPS will use its defaults for them. 

BTW, we could support both configurations without any issue. Anyway, i'll make PR in CDEPS and NEMS part when this is ready along with other staff that are needed for data ocean configurations. Let me know if you have suggestions.

**Comment by uturuncoglu** [comment]
I implemented both of them and testing now. If you don't mind could you give me permission for CDEPS NOAA/EMC fork. Since HAFS fork is outdated, I am pointing NOAA/EMC fork at this point to work on HAFS side.

**Comment by junwang-noaa** [comment]
What permission do you need for CDEPS NOAA-EMC repo? Do you need to create
new branches?

**Comment by uturuncoglu** [comment]
@junwang-noaa yes, that will be helpful. thanks.

**Comment by uturuncoglu** [comment]
@junwang-noaa @aerorahul I think that this modification is not tested with the existing CDEPS DATM configurations. Right? If so, there might be an issue with this change because I have an issue in CDEPS that is explained in here (https://github.com/NOAA-EMC/CDEPS/issues/32). I was trying to test the modifications that are done in here under HAFS and it seems that the CDEPS does not read datm.stream file. This could be an build issue and maybe `DISABLE_FoX` is not passed correctly. Anyway, I'll try to revert this back under HAFS and test HAFS DATM configuration again.

**Comment by uturuncoglu** [comment]
@junwang-noaa @aerorahul Okay. I confirmed that I could run the HAFS/DATM configuration successfully if I revert the changes in the PR. I think there is an issue in passing `DISABLE_FoX` to the build. Maybe we do not need this PR anymore since we changed the module name in CDEPS side and I could include data ocean individually to the top level CMakeLists.txt.

**Comment by junwang-noaa** [comment]
@uturuncoglu I did test CDEPS [PR #31](https://github.com/NOAA-EMC/CDEPS/pull/31) with this PR to run CDEPS DATM test, and and the CDEPS DATM tests run successfully.

**Comment by uturuncoglu** [comment]
@junwang-noaa Thanks. Maybe it fas failing for me because I used @aerorahul's patch to test it. It might include missing part. Anyway, I'll test data ocean configuration and let you know.

**Comment by uturuncoglu** [comment]
@junwang-noaa JFYI, I did not need access to create branch in CDEPS NOAA-EMC repository at this point because i synced HAFS fork with NOAA-EMC. Thanks for you help.

**Comment by aerorahul** [comment]
#642 absorbed this PR.
Closing.

**Pull request closed without merging**
