### PR TITLE
Update CICE cap for optional features; use UPP as submodule (was #904)

### LINKED ISSUE #41: Update NUOPC cap for new features
The NUOPC cap for CICE6 needs to be updated to implement recent features added to CICE6

- addition of optional cap-level debugging for a single model location (set using ``latpnt(1) , lonpnt(1)``) using flag ``debug_model`` in ice_in
- addition of required calls and parameters associated with the implementation of Advanced Snow Physics in Icepack https://github.com/CICE-Consortium/Icepack/pull/360. 

The optional snow physics are not currently exercised in UWM but are required to fully test a fix for ``meltsliq`` initialization (https://github.com/CICE-Consortium/Icepack/pull/376) when compiling with debug option ``-init=snan,arrays`` . See  related UWM Issue [580](https://github.com/ufs-community/ufs-weather-model/issues/580).

The proposed fix does allow UWM to run in debug model with NaN initialization if ``tr_snow`` is false. Setting ``tr_snow`` to true still fails for the array ``meltsliq`` and additional debugging will be required to determine a fix when ``tr_snow`` is true.

To run a test using ``tr_snow``, the following were added to ice_in:

```
...
    restart_pond_lvl  = .false.
    tr_snow      = .false.
    restart_snow = .false.
    tr_aero      = .false.
...

&snow_nml
    snwredist       = 'bulk'
    snwlvlfac       =    0.3
    rsnw_fall       =  100.0
    snw_aging_table = 'test'
/

&icefields_snow_nml
/
```

### LINKED ISSUE #905: Use UPP as a submodule
UPP library is updated very frequently, which requires making a UPP release, building it using hpc-stack on all supported platforms and then updating modules in ufs-weather-model. We can just add the upp as a submodule in fv3atm repo and update that submodule whenever we need to update inline post.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- Updates CICE cap for optional features
- Uses UPP as a FV3atm submodule (@DusanJovic-NOAA)
- remove CA namelist settings from HAFS related input.nml files
- removes ``control_ca_restart`` test (unused). CA restart is now tested in the cpld and control P7 test suites.
- adds 35d RT test (``cpld_bmark_p7_35d``) which can be used with ``rt_35d.conf`` (@MinsukJi-NOAA)

### Issue(s) addressed

- fixes https://github.com/NOAA-EMC/CICE/issues/41 
- fixes https://github.com/ufs-community/ufs-weather-model/issues/905

## Testing

The full RT for both Intel and GNU was run on Hera. All baselines were B4B.

During RT testing, new versions of g2tmpl were used on dell and gaea. Baselines changed for the following tests due to the comparison of the GrbF00 and GrbF24 files

```
regional_quilt 034 failed in check_result
regional_quilt_2threads 035 failed in check_result
regional_quilt_RRTMGP 038 failed in check_result
```

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1481651452

## Dependencies

- waiting on https://github.com/NOAA-EMC/CICE/pull/42
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/421

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@lisa-bengtsson I've moved the ca-namelist defaults into the FV3 section of default_vars. The baselines all passed, but if you could check if I've missed something. Thanks.

**Comment by lisa-bengtsson** [comment]
@DeniseWorthen what is the aim of the FV3 section? Since the CA is false there, no other parameters needs to be listed there either, they only matter if do_ca = True. If the CA is true, such as in P7, then I suggest to list all the other settings as well, not only the three you moved, such as:

export NCA=1
export NCELLS=5
export NLIVES=12
export NTHRESH=18
export NSEED=1
export NFRACSEED=0.5
export CA_TRIGGER=.true.
export NSPINUP=1
export ISEED_CA=12345

To me it looks like the way it was before is OK, but I also don't fully know what the FV3 section is for. I also see that the control_ca and control_ca_restart tests have been removed, with that it looks like the P7 configuration is now the only configuration that tests the CA. With this change I hope the P7 coupled tests are always tested for any new code to enter develop so the CA code doesn't break.

**Comment by DeniseWorthen** [comment]
In preparing an answer for you, I've noticed that I didn't catch a problem w/ your commit for the CA namelists. 

Default_vars has several sections, one for the FV3 defaults and then one for the additional modes we run the whole system in (coupled, cdeps, hafs etc). If you're running standalone, the default_vars for the other modes never get called. So, in default_vars, the part starting with say 

```
export_cpl ()
{
```

never gets triggered. But that is where all the CA settings are located (as you point out, CA is off by default in standalone). So in order to turn CA on in standalone P7, we need to set the CA-related variables in the actual tests (eg ``control_p7``). From there, they get inserted into the ``cpld_control.nml.IN`` namelist which is shared by coupled and standalone P7. The point of putting the new settings in the fv3 portion of default_vars is that they would then be used as defaults in the standalone P7 tests. 

What I just noticed though is that the standalone P7 tests were not touched in your PR. They still explicitly use
```
 # P7 CA
export DO_CA=.true.
export CA_SGS=.true.
export CA_GLOBAL=.false.
export NCA=1
export SCELLS=2600
export TLIVES=1800
export NSEED=1
export NFRACSEED=0.5
export CA_TRIGGER=.true.
export NSPINUP=1
export ISEED_CA=12345
```

So I'm concerned that the previous values have been used, not the new namelist settings. Would the model have run if that were true?

Regarding the removal of the previous CA restart test, since CA is on by default in any P7 test (coupled or standalone), CA gets tested for reproducibility, debug, decomp, threading and restart for both standalone and coupled for every commit.

**Comment by lisa-bengtsson** [comment]
Hi Denise, no the model would not run with those namelist settings, there are no longer any scells or tlives scales. Where is the namelist for the standalone test located? I tried to grep for scells and SCELLS in my test/ directory and below but cannot find any files containing this. default_vars.sh has this:

P7 CA                                                                                                                                                   
export DO_CA=.true.
export CA_SGS=.true.
export CA_GLOBAL=.false.
export NCA=1
export NCELLS=5
export NLIVES=12
export NTHRESH=18
export NSEED=1
export NFRACSEED=0.5
export CA_TRIGGER=.true.
export NSPINUP=1
export ISEED_CA=12345

**Comment by DeniseWorthen** [comment]
The tests/tests/control*p7 contain the manual settings of the CA variables. 

But you're right, I think we're OK because I checked one of the tests I did today. For control_p7, the namelist does contain the ncells, nlives and nthresh settings.  It must have to do w/ the order of how the variable replacement is done. But I think we need to fix it anyway---remove the old settings from the tests/tests/control*p7 and use the three new namelist variables in the FV3 part of default_vars.


The part of P7 CA that you list above in default_vars is inside of ``export_cpl ()`` (LN 695).

**Comment by lisa-bengtsson** [comment]
tests/tests.control*p7 was updated with my PR. There are not old settings there from what I can see.

**Comment by DeniseWorthen** [comment]
I'm sorry---I was looking in an older working directory which hasn't had your changes merged in yet. 

I think I'll quit while I'm behind and think some more about whether we need to do anything w/ the default vars at all.

**Comment by lisa-bengtsson** [comment]
Ok, good. Yeah it could perhaps go in both places. e.g both the P7 section and the FV3 section. I am not sure if it is needed or not, can have a closer look next week. Have a nice weekend!

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]
35 day tests look good. In my test, all 8 tests were able to run for 2 days.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/779394120/20211119151506/ufs-weather-model
Please make changes and add the following label back:
gaea-intel-RT

**Comment by DeniseWorthen** [comment]
Hera.intel/gnu passed because g2tmpl/1.10.0 is available (1.9.1 is also available). The Gaea tests failed all compiles because g2tmpl can't be found---I can't find any version, but I'm probably not looking in the right way.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/779394120/20211119180007/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_13150
Test regional_quilt 034 failed in check_result failed 
Test regional_quilt 034 failed in run_test failed 
Test regional_quilt_2threads 035 failed in check_result failed 
Test regional_quilt_2threads 035 failed in run_test failed 
Test regional_quilt_RRTMGP 038 failed in check_result failed 
Test regional_quilt_RRTMGP 038 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by DeniseWorthen** [comment]
On Dell, the following tests all failed comparing the GrbF00 and GrbF24 files

```
regional_quilt 034 failed in check_result
regional_quilt_2threads 035 failed in check_result
regional_quilt_RRTMGP 038 failed in check_result
```

**Comment by climbfuji** [comment]
Same for gaea. I think I have seen this before on gaea when switching from my stack to Kyle's stack. The obvious elephant in the room is the g2tmpl library, which was older in Kyle's stack than in mine, affecting the regional inline post.

**Comment by WenMeng-NOAA** [comment]
It would be better to use g2tmp/1.10.0 for some grib2 names correction.

**Comment by DusanJovic-NOAA** [comment]
> Same for gaea. I think I have seen this before on gaea when switching from my stack to Kyle's stack. The obvious elephant in the room is the g2tmpl library, which was older in Kyle's stack than in mine, affecting the regional inline post.

This basically means we need to take out the UPP changes and have them merged as a separate PR with new baselines, or update baselines in this PR. It's unfortunate that loading a non-existent module gets undetected and we silently end up using the older version of the module. We need to figure out how to fix that.

**Comment by junwang-noaa** [comment]
I'd suggest to create new baseline and get the module issue fixed later.

**Comment by dusanjovic** [comment]
I tried to set g2tmpl module load to a version that does not exist (g2tmpl/99.0.0), and module load still works. I think that's because, for example, on Gaea:
```
$ grep load /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/mpi/intel/18.0.6.288/cray-mpich/7.7.11/upp/10.0.10.lua
load("bacio", "g2", "g2tmpl", "ip", "sp", "w3nco", "w3emc", "crtm")
```
I think modules should just list:
```
$ grep prereq /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/mpi/intel/18.0.6.288/cray-mpich/7.7.11/upp/10.0.10.lua
prereq("bacio", "g2", "g2tmpl", "ip", "sp", "w3nco", "w3emc", "crtm")
```
and not load other modules, especially not without explicit version.

**Comment by DusanJovic-NOAA** [comment]
WCOSS (Cray and Dell) logs are here:
/scratch1/NCEPDEV/stmp2/Dusan.Jovic/pr910/RegressionTests_wcoss_cray.log
/scratch1/NCEPDEV/stmp2/Dusan.Jovic/pr910/RegressionTests_wcoss_dell_p3.log

**Pull request merged**
