### PR TITLE
Update damping and time step parameters

### LINKED ISSUE #2305: Update damping and time step for global RT tests
## Description

A PR [#2575](https://github.com/NOAA-EMC/global-workflow/pull/2575) was committed to global workflow to use explicit Rayleigh damping for u/v and implicit damping to w. The changes need to be made to ufs wm global regression test so that the same configurations are used in RT and G-W. 

## Related to

Global workflow [PR#2575](https://github.com/NOAA-EMC/global-workflow/pull/2575)

### PR DESCRIPTION
**Pull request by dpsarmie**
- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR changes the damping and time step parameters to new updated values that were created for Global Workflow (https://github.com/NOAA-EMC/global-workflow/pull/2575). These values should improve reliability and allow for longer timesteps to be used in the model. A new section was introduced in default_vars.sh because the parameter values are resolution dependent. 

### Commit Message:
```
* UFSWM - Update default parameter values for damping based off of work done for GW 
```

### Priority:
* Normal

### UFSWM:
* Closes #2305
* Changes based off of the following PR: https://github.com/NOAA-EMC/global-workflow/pull/2575

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by dpsarmie** [comment]
There are some reliability issues occurring with testing on Hercules (conus13km_debug_2threads_intel was not generating files on a consistent basis).  I will do more testing on Hercules and test on Hera to see if there are similar issues. 

I will also document changes to run times if significant.

K_SPLIT variable in default_vars will need to be moved/cleaned up.

**Comment by XiaqiongZhou-NOAA** [comment]
could you also add corresponding changes related to https://github.com/NOAA-EMC/global-workflow/pull/2751

**Comment by CatherineThomas-NOAA** [comment]
@XiaqiongZhou-NOAA : There have been problems with the omega PR #2327 in other applications and it's being reverted.  Take a look at PR #2362 and [Issue #346](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/346).

**Comment by XiaqiongZhou-NOAA** [comment]
> @XiaqiongZhou-NOAA : There have been problems with the omega PR #2327 in other applications and it's being reverted. Take a look at PR #2362 and [Issue #346](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/346).

I assume PR#2362 will be merged soon and Issue#346 already has a fix. It has already a fix https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/349

**Comment by dpsarmie** [comment]
@XiaqiongZhou-NOAA Yes, I can roll the omega calc update into this PR also. There are still a handful of tests that are failing with the new damping parameters that I need to look into. If I can't resolve it soon, then I'll just make a separate PR for the omega calc.

**Comment by CatherineThomas-NOAA** [comment]
Thanks for the correction @XiaqiongZhou-NOAA, I misunderstood the state of things.

**Comment by dpsarmie** [comment]
A quick update on this PR:

The new parameters are causing multiple issues with the regression tests. I'm compiling a list of the affected runs and I'll update it later today. I've been troubleshooting and found that if I revert K_SPLIT to its original value, then the crashes are resolved.

It also seems like some of the runs have also extended their runtime with the new parameter values (and using the default K_SPLIT) but I'm trying to replicate the issue just to verify.

Either way, the omega calculation has been added to a separate PR (https://github.com/ufs-community/ufs-weather-model/pull/2373) while this issue is addressed. 

I'll post another update in here with a Google Doc documenting the affected tests.

**Comment by yangfanglin** [comment]
New damping settings should only be applied to 127-layer global model RTs

**Comment by junwang-noaa** [comment]
@yangfanglin The global tests that Dan is testing are running with L127 levels.

**Comment by yangfanglin** [comment]
Which RTs and on what platform the runs are failing ?   Might be worthwhile running the global-workflow CI tests mentioned in this PR https://github.com/NOAA-EMC/global-workflow/pull/2575  and crosschecking namelist settings.

**Comment by dpsarmie** [comment]
So these are the results I've compiled so far: [Google Docs link](https://docs.google.com/spreadsheets/d/13MfRdJ7QR4yHzcp0dkhtl8l_L5uKXCpV52nx5NfxDmY/edit?usp=drive_link)

K_SPLIT and DELTIM seem to be the two variables causing the most issues. 

The common error in the **_cpld_** cases is the following:
**NaN in input field of mpp_reporducing_sum(_2d), this indicates numerical instability**

I'm going through the other test logs to see what the issues are because some of failures are being caused by exceeding the allotted wall clock time. 

@yangfanglin: Yes, I agree that we should look at the input.nml files to make sure that they are identical before diving deeper into the errors. Do you happen to have a copy of the GW CI test input.nml available? These tests were all run on Hera but I'm seeing similar issues on Hercules.

**Comment by dpsarmie** [comment]
I've added changes to default_vars.sh and am currently performing one last test that cleans up some of the variable definitions in the regression tests (there were repeated variables). I am still unable to have a stable run with the reduced value of k_split. I've generated a namelist from GW and tried to emulate it without any success. 

I would ask to see if there is a namelist that uses these updated values for a resolution that is not C48.  For now, I've left the default k_split. From what I've read, k_split should only affect stability and isn't changing the core physics of the system.

We should also discuss how many tests we want to move over to v1. There are multiple tests that are using v0, others are using new HR4 variables, etc. For the RTs, I'm thinking we should keep some older configurations as long as they are still supported by UFS.

**Comment by junwang-noaa** [comment]
@yangfanglin Can your group help with this? Currently the configurations were updated in global workflow, but it failed in the UFS WM rt.

**Comment by XiaqiongZhou-NOAA** [comment]
> I've added changes to default_vars.sh and am currently performing one last test that cleans up some of the variable definitions in the regression tests (there were repeated variables). I am still unable to have a stable run with the reduced value of k_split. I've generated a namelist from GW and tried to emulate it without any success.
> 
> I would ask to see if there is a namelist that uses these updated values for a resolution that is not C48. For now, I've left the default k_split. From what I've read, k_split should only affect stability and isn't changing the core physics of the system.
> 
> We should also discuss how many tests we want to move over to v1. There are multiple tests that are using v0, others are using new HR4 variables, etc. For the RTs, I'm thinking we should keep some older configurations as long as they are still supported by UFS.

Can you list all n_split, k_split, detlm and resolution? Generally we can not only increase K_split, have to consider detlm/(k_split*n_split)?

**Comment by XiaqiongZhou-NOAA** [comment]
> @yangfanglin Can your group help with this? Currently the configurations were updated in global workflow, but it failed in the UFS WM rt.

Fanglin is in training. I believe @KevinViner-NOAA suggested this update.

**Comment by dpsarmie** [comment]
> > I've added changes to default_vars.sh and am currently performing one last test that cleans up some of the variable definitions in the regression tests (there were repeated variables). I am still unable to have a stable run with the reduced value of k_split. I've generated a namelist from GW and tried to emulate it without any success.
> > I would ask to see if there is a namelist that uses these updated values for a resolution that is not C48. For now, I've left the default k_split. From what I've read, k_split should only affect stability and isn't changing the core physics of the system.
> > We should also discuss how many tests we want to move over to v1. There are multiple tests that are using v0, others are using new HR4 variables, etc. For the RTs, I'm thinking we should keep some older configurations as long as they are still supported by UFS.
> 
> Can you list all n_split, k_split, detlm and resolution? Generally we can not only increase K_split, have to consider detlm/(k_split*n_split)?

We can use a C96 run as an example. n_split is 4, k_split is 1, and deltim is 600.  That should match what is in the GW config (https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.ufs#L132) and is being set in the default_vars.sh (https://github.com/dpsarmie/ufs-weather-model/blob/fix/updateDampingParm/tests/default_vars.sh#L944).

I was able to get the C48 runs converted over with the GW parameters and all other runs at C96 and finer are stable if k_split is set to its default value (ex. k_split = 2 for C96 runs).

Thank you for any help or information you might be able to provide.

**Comment by XiaqiongZhou-NOAA** [comment]
> > > I've added changes to default_vars.sh and am currently performing one last test that cleans up some of the variable definitions in the regression tests (there were repeated variables). I am still unable to have a stable run with the reduced value of k_split. I've generated a namelist from GW and tried to emulate it without any success.
> > > I would ask to see if there is a namelist that uses these updated values for a resolution that is not C48. For now, I've left the default k_split. From what I've read, k_split should only affect stability and isn't changing the core physics of the system.
> > > We should also discuss how many tests we want to move over to v1. There are multiple tests that are using v0, others are using new HR4 variables, etc. For the RTs, I'm thinking we should keep some older configurations as long as they are still supported by UFS.
> > 
> > 
> > Can you list all n_split, k_split, detlm and resolution? Generally we can not only increase K_split, have to consider detlm/(k_split*n_split)?
> 
> We can use a C96 run as an example. n_split is 4, k_split is 1, and deltim is 600. That should match what is in the GW config (https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.ufs#L132) and is being set in the default_vars.sh (https://github.com/dpsarmie/ufs-weather-model/blob/fix/updateDampingParm/tests/default_vars.sh#L944).
> 
> I was able to get the C48 runs converted over with the GW parameters and all other runs at C96 and finer are stable if k_split is set to its default value (ex. k_split = 2 for C96 runs).
> 
> Thank you for any help or information you might be able to provide.


If k_split=2 and n_split=4, deltim=600, this will decrease dynamic time step or acoustic time step (deltm/(k_split*n_split) too much. The new setting (k_split=1,n_split=4 and deltim=600) should be dynamically stable. The crash is probably due to other issues. It is not a good solution just decrease dynamic time step.

**Comment by dpsarmie** [comment]
> If k_split=2 and n_split=4, deltim=600, this will decrease dynamic time step or acoustic time step (deltm/(k_split*n_split) too much. The new setting (k_split=1,n_split=4 and deltim=600) should be dynamically stable. The crash is probably due to other issues. It is not a good solution just decrease dynamic time step.

Agreed. I'm also working on unifying the namelist parameters between the RTs and GW, so having two different settings wouldn't be optimal.
Is there a namelist available for a current run available for a resolution that isn't C48? I generated a C48/C96 GW namelist but it might be beneficial to look at a working one in case I'm doing something wrong on my end. Also, which hash of the UFS model is GW currently working with?

**Comment by CatherineThomas-NOAA** [comment]
@dpsarmie Are your failures on WCOSS2?  In the global-workflow, we've had forecast instability for a C48 CI test when running on WCOSS2 but the same case is stable on Hera.  We haven't figured out a cause yet, but are also investigating. See [g-w #2732](https://github.com/NOAA-EMC/global-workflow/pull/2732), [#2751](https://github.com/NOAA-EMC/global-workflow/pull/2751).

The g-w is using the hash [c127601](https://github.com/ufs-community/ufs-weather-model/tree/c12760125ce7c5a85e8ced92d7f37c9ad6a59afe).  PR [#2751](https://github.com/NOAA-EMC/global-workflow/pull/2751) is attempting to update that to a more recent hash.

**Comment by dpsarmie** [comment]
@CatherineThomas-NOAA This is on both Hera and Hercules. I also have the C48 cases stable on those platforms with the new parameters.  
The instabilities are occurring with other resolutions. I don't know if you all are also having issues at other resolutions.

**Comment by CatherineThomas-NOAA** [comment]
@dpsarmie Thanks for clarifying.  I don't know of any recurring instabilities at other resolutions.  I used the g-w parameters in a 6 week cycling experiment for ATM only at C384 det, C192 ens and had no issues.

**Comment by dpsarmie** [comment]
@CatherineThomas-NOAA Thanks for info! I'll keep testing on my end to see what is the issue with the RTs. 
Do you have a working input.nml file that you can share (any res)? I'm just trying to do a sanity check to make sure I'm didn't do something silly when generating the GW namelist. Thanks again.

**Comment by CatherineThomas-NOAA** [comment]
@RuiyuSun: Can you point @dpsarmie to one of your input.nml files?

**Comment by RuiyuSun** [comment]
@CatherineThomas-NOAA @dpsarmie an example is ufs.input.nml at /lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/ROTDIRS/s2sw2/gfs.20210323/12/conf on CACTUS. The main change I made is the time step inner (dt_inner) to Thompson microphysics scheme. I think in the C48 experiment with deltim=1200s the dt_inner (=1200s) is too large the scheme. I reduced it to dt_inner=600s to stabilize the crashed case on CACTUS.

**Comment by RuiyuSun** [comment]
@dpsarmie The proposed solution to the crashed C48 case in the omega PR is  to add a line in the config.fcst as shown below. 

    if [[ "${sedi_semi}" == .true. ]]; then export dt_inner=${DELTIM} ; fi
    **if [[ dt_inner -gt 300 ]]; then export  dt_inner=300; fi**

**Comment by dpsarmie** [comment]
> @dpsarmie The proposed solution to the crashed C48 case in the omega PR is to add a line in the config.fcst as shown below.
> 
> ```
> if [[ "${sedi_semi}" == .true. ]]; then export dt_inner=${DELTIM} ; fi
> **if [[ dt_inner -gt 300 ]]; then export  dt_inner=300; fi**
> ```

Thank @RuiyuSun and everyone. I've added a similar fix to the RTs and the first couple of tests seem to be working now. Thanks again.

**Comment by junwang-noaa** [comment]
@RuiyuSun since DELTIM is different for C48/C96/C192 test cases, and dt_inner needs to be divisible by DELTIM, can we set dt_inner to be half of DELTIM?
```
if [[ "${sedi_semi}" == .true. ]]; then export dt_inner=${DELTIM}/2 ; fi
```

**Comment by RuiyuSun** [comment]
@junwang-noaa Perhaps I gave you wrong information. The deltim doesn't have to divisible by dt_inner. deltim/dt_inner will be rounded up to the nearest whole number. What I am afraid if dt_inner=deltim/2 is used dt_inner is still too large for some C48 cases.

**Comment by dpsarmie** [comment]
All of the tests have been updated with the new parameters, but there were some RT specific issues that needed workarounds:

- I checked the RTs and the new parameters were stable for all of them. Unfortunately, some of the RTs had longer runtimes than what was originally allotted for in the RTs. Increasing the allotted runtime is not feasible, so those tests were changed to allow them to run under the time limit.
- There is an error raised in the CCPP module for the `control_c48 gnu` case on `Hera`. This test runs fine with the intel compiler and the gnu case runs fine on Hercules. I took a quick look at it and couldn't find a quick resolution. The test has a temporary case for the hera/gnu combination, which allows it to run without the new parameters temporarily. I will create an issue and try to fix the error in another PR.

Let me know if anyone has any objections. Thanks again for the help and collaboration on this PR.

**Comment by dpsarmie** [comment]
This is to expand on the `control_c48 gnu` issue on Hera:

An issue was created here: https://github.com/ufs-community/ccpp-physics/issues/224
and the specific error is here: https://github.com/ufs-community/ccpp-physics/blob/2a50cccd916cceafaf031f4cd14f2ecef277be8f/physics/Interstitials/UFS_SCM_NEPTUNE/GFS_phys_time_vary.fv3.F90#L279

I configured control_c48 to work on Hera for now with the older parameters, but it should be fixed for future use.
My vote is to go ahead since this issue seems to be isolated to Hera, but you all let me know what you think.

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA @zach1221 I confirm control_c48_gnu runs ok on hera w/o crashing. So, this pr looks good to commit. @BrianCurtis-NOAA FYI

**Comment by zach1221** [comment]
@dpsarmie I'm getting a failure on Hercules during the test run for control_c48_gnu. It compiles and begins running, then fails with:
0: [hercules-03-06:mpi_rank_0][MPID_Init] [Performance Suggestion]: Application has requested for multi-thread capability. If allocating memory from different pthreads/OpenMP threads, please consider setting MV2_USE_ALIGNED_ALLOC=1 for improved performance.
0: Use MV2_USE_THREAD_WARNING=0 to suppress this error message.
5: An error occurred in ccpp_physics_init

**Comment by dpsarmie** [comment]
@zach1221 Weird, I've never seen that error before, but from the wording it looks like a warning rather than a hard error.

I tried to confirm on Hercules but I'm running into the issue that Denise opened yesterday: https://github.com/ufs-community/ufs-weather-model/issues/2432

```
rt.sh: Setting up hercules...
Linking /work2/noaa/stmp/dsarmien/stmp/dsarmien/FV3_RT/rt_3206146 to /work/noaa/stmp/dsarmien/final_tests_ufs/tests/run_dir
Run regression test in: /work2/noaa/stmp/dsarmien/stmp/dsarmien/FV3_RT/rt_3206146
rt.sh: Checking & Updating test configuration...
find: ‘/work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/develop-20240909/’: Permission denied
```

image
Global access seems to be completely locked out for all users on the previous two baselines.

**Comment by zach1221** [comment]
@dpsarmie I havent finished the 20240909 because of the control_c48 failure. I will open up the permissions though.

**Comment by zach1221** [comment]
@dpsarmie ok, the permissions should be open on develop-20240909.

**Comment by dpsarmie** [comment]
Thanks @zach1221. I confirmed that there is an issue and I'm trying to troubleshoot it now. I'll ping you when this PR is ready to get looked at again.

**Comment by dpsarmie** [comment]
@zach1221 I added a general gnu catch to the control_c48 test. It looks like there's a bigger issue with CCPP and the C48/UGWPV1 configuration. 
You can go ahead and retest on Hercules. It should work now.

**Comment by FernandoAndrade-NOAA** [comment]
@dpsarmie `cpld_restart_gfsv17 intel` `cpld_restart_bmark_p8 intel` and `cpld_restart_pdlib_p8 intel` are still failing after recreation, resync, and rerun on Hera and Gaea FYI @zach1221 @jkbk2004

**Comment by dpsarmie** [comment]
@FernandoAndrade-NOAA So you're able to run and generate the baselines for these restart tests but then they fail on a subsequent check? I'm just making sure that this isn't a runtime issue.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA So you're able to run and generate the baselines for these restart tests but then they fail on a subsequent check? I'm just making sure that this isn't a runtime issue.

No errors during runtime or baseline generation, this seems to be an issue with the results not being identical, please refer to the following on Hera as an example:
`/scratch1/NCEPDEV/stmp2/Fernando.Andrade-maldonado/FV3_RT/rt_815536/cpld_restart_gfsv17_intel/RESTART/`

`/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/wm/2363/ufs-weather-model/tests/logs/log_hera/rt_cpld_restart_gfsv17_intel.log`

**Comment by zach1221** [comment]
> > @FernandoAndrade-NOAA So you're able to run and generate the baselines for these restart tests but then they fail on a subsequent check? I'm just making sure that this isn't a runtime issue.
> 
> No errors during runtime or baseline generation, this seems to be an issue with the results not being identical, please refer to the following on Hera as an example: `/scratch1/NCEPDEV/stmp2/Fernando.Andrade-maldonado/FV3_RT/rt_815536/cpld_restart_gfsv17_intel/RESTART/`
> 
> `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/wm/2363/ufs-weather-model/tests/logs/log_hera/rt_cpld_restart_gfsv17_intel.log`

I am also seeing this persistently on orion/hercules with cpld_restart_gfsv17_intel, cpld_restart_bmark_p8_intel, and cpld_restart_pdlib_p8_intel.

**Comment by BrianCurtis-NOAA** [comment]
It could be the bug in the generation of the rt_temp.conf where a test dependency isn't handled correctly.

**Comment by dpsarmie** [comment]
Ok I think I found the issue. I was able to fix the gfsv17 case by making the K_SPLIT/N_SPLIT consistent between the the control and the restart RT.
After doing this I ran the `cpld_restart_gfsv17` test and created new baselines, then reran it and checked against the newly created baselines and it passed.

I've pushed changes to the other RTs that were causing issues for you all. I'm currently testing the other cases and will let you all know once those pass.

Still not 100% sure on why this is the case/fix but I'll worry about that later.

**Comment by dpsarmie** [comment]
@zach1221 @FernandoAndrade-NOAA Ok, all three restarts should be good to go. I made new baselines and checked them on Hera. Let me know if you run into any issues.

**Comment by BrianCurtis-NOAA** [comment]
@dpsarmie my cpld_mpi_pdlib_p8 intel tests are failing comparisons on Acorn and WCOSS2

**Comment by zach1221** [comment]
> @dpsarmie my cpld_mpi_pdlib_p8 intel tests are failing comparisons on Acorn and WCOSS2

I'm having this exact issue, failing to compare, on both hercules and orion. Can't say yet on Derecho as it's been super slow.

**Comment by jkbk2004** [comment]
It turns out this PR needs additional troubleshooting. @zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA Can we schedule #2220 to commit today?

**Comment by BrianCurtis-NOAA** [comment]
> It turns out this PR needs additional troubleshooting. @zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA Can we schedule #2220 to commit today?

I think @dpsarmie has one last adjustment to make, and #2220 is still in draft status, i don't know why you're even considering it at this point.

**Comment by dpsarmie** [comment]
I'm testing the changes that I just merged on Hercules to see if I get the same error.  It should be a quick check and I'll report back once it's done.

**Comment by dpsarmie** [comment]
Ok, cpld_mpi_pdlib and the other associated files passed on Hercules. @zach1221 @BrianCurtis-NOAA 

```
RT.SH OPTIONS USED:
* (-m) - COMPARE AGAINST CREATED BASELINES
* (-e) - USE ECFLOW

PASS -- COMPILE 's2sw_pdlib_intel' [19:11, 17:39] ( 1 warnings 10 remarks )
PASS -- TEST 'cpld_control_pdlib_p8_intel' [16:26, 13:54](2070 MB)
PASS -- TEST 'cpld_restart_pdlib_p8_intel' [09:22, 06:52](1392 MB)
PASS -- TEST 'cpld_mpi_pdlib_p8_intel' [18:28, 15:30](1995 MB)
```

**Comment by zach1221** [comment]
Ok @BrianCurtis-NOAA @jkbk2004 testing is complete. We're ready for review.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
