### PR TITLE
Update CDEPS component, add hailcast code in FV3/atmos_cubed_sphere and reduce wall clock time used for the cpld_control_c192_p8 test on Jet

### LINKED ISSUE #1144: Update CDEPS component and reduce wall clock time used for the cpld_control_c192_p8 test on Jet
## Description
The develop branch of NOAA-EMC/CDEPS will be updated to include the latest changes from ESCOMP/CDEPS. The ufs-weather-model will be updated at the same time. The wall clock time used for the cpld_control_c192_p8 test cannot be completed within 30 minutes on Jet. The default_vars.sh will be updated so that the cpld_control_c192_p8 test can be finished within 30 minutes on Jet.

## Solution
1. Update CDEPS component in ufs-weather-model.
2. Update default_vars.sh.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- https://github.com/NOAA-EMC/CDEPS/issues/44
- https://github.com/NOAA-EMC/CDEPS/pull/45

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
Update CDEPS component and reduce wall clock time used for the cpld_control_c192_p8 test on Jet.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1144 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- https://github.com/NOAA-EMC/CDEPS/pull/45
- https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/164

Co-authored-by Yunheng Wang  <yunheng.wang@noaa.gov>

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Please update the cpld_bmark_p8 resources on jet, instead of changing wall clock time for all the platforms. Thanks

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/900607016/20220428121513/ufs-weather-model
[RT] Error: Test compile_007 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by DeniseWorthen** [comment]
Compile failed on Cheyenne.gnu for -DAPP=NG-GODAS with

EDIT: Sorry, those were the warnings, not the errors I posted prevously. The actual errors were

```
shr_infnan_mod.F90.in:195:25:

Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
shr_infnan_mod.F90.in:195:25:

Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
shr_infnan_mod.F90.in:208:25:

Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
shr_infnan_mod.F90.in:208:25:

Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
shr_infnan_mod.F90.in:213:14:

Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
shr_infnan_mod.F90.in:213:14:

Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
shr_infnan_mod.F90.in:200:14:

Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
shr_infnan_mod.F90.in:200:14:
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/900607016/20220428181514/ufs-weather-model
[RT] Error: Test compile_007 failed in run_compile failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by jkbk2004** [comment]
> Compile failed on Cheyenne.gnu for -DAPP=NG-GODAS with
> 
> EDIT: Sorry, those were the warnings, not the errors I posted prevously. The actual errors were
> 
> ```
> shr_infnan_mod.F90.in:195:25:
> 
> Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> shr_infnan_mod.F90.in:195:25:
> 
> Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> shr_infnan_mod.F90.in:208:25:
> 
> Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> shr_infnan_mod.F90.in:208:25:
> 
> Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> shr_infnan_mod.F90.in:213:14:
> 
> Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> shr_infnan_mod.F90.in:213:14:
> 
> Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> shr_infnan_mod.F90.in:200:14:
> 
> Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> shr_infnan_mod.F90.in:200:14:
> ```

@DeniseWorthen this is the change I added to use gnu11.2 on cheyenne. previously ==. When I run with rt_gnu.conf, it ran ok. Let me double check,

**Comment by jkbk2004** [comment]
> > Compile failed on Cheyenne.gnu for -DAPP=NG-GODAS with
> > EDIT: Sorry, those were the warnings, not the errors I posted prevously. The actual errors were
> > ```
> > shr_infnan_mod.F90.in:195:25:
> > 
> > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > shr_infnan_mod.F90.in:195:25:
> > 
> > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > shr_infnan_mod.F90.in:208:25:
> > 
> > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > shr_infnan_mod.F90.in:208:25:
> > 
> > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > shr_infnan_mod.F90.in:213:14:
> > 
> > Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> > shr_infnan_mod.F90.in:213:14:
> > 
> > Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> > shr_infnan_mod.F90.in:200:14:
> > 
> > Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> > shr_infnan_mod.F90.in:200:14:
> > ```
> 
> @DeniseWorthen this is the change I added to use gnu11.2 on cheyenne. previously ==. When I run with rt_gnu.conf, it ran ok. Let me double check,

@binli2337 can you revert the change in shr_infnan_mod.F90? I think we don't need to hold the issue with gnu10.1 since the chenge is regarding gnu11.2.

**Comment by DusanJovic-NOAA** [comment]
> > > Compile failed on Cheyenne.gnu for -DAPP=NG-GODAS with
> > > EDIT: Sorry, those were the warnings, not the errors I posted prevously. The actual errors were
> > > ```
> > > shr_infnan_mod.F90.in:195:25:
> > > 
> > > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > > shr_infnan_mod.F90.in:195:25:
> > > 
> > > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > > shr_infnan_mod.F90.in:208:25:
> > > 
> > > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > > shr_infnan_mod.F90.in:208:25:
> > > 
> > > Error: Intrinsic operator ‘.eq.’ referenced at (1) not found in module ‘ieee_arithmetic’
> > > shr_infnan_mod.F90.in:213:14:
> > > 
> > > Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> > > shr_infnan_mod.F90.in:213:14:
> > > 
> > > Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> > > shr_infnan_mod.F90.in:200:14:
> > > 
> > > Error: Operands of comparison operator ‘.eq.’ at (1) are TYPE(ieee_class_type)/TYPE(ieee_class_type)
> > > shr_infnan_mod.F90.in:200:14:
> > > ```
> > 
> > 
> > @DeniseWorthen this is the change I added to use gnu11.2 on cheyenne. previously ==. When I run with rt_gnu.conf, it ran ok. Let me double check,
> 
> @binli2337 can you revert the change in shr_infnan_mod.F90? I think we don't need to hold the issue with gnu10.1 since the chenge is regarding gnu11.2.

BTW, file `shr_infnan_mod.F90` must not be edited, see the comment at the beginning of the file.

```
!===================================================
! DO NOT EDIT THIS FILE, it was generated using genf90.pl
! Any changes you make to this file may be lost
!===================================================
```

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA As I know UFS uses the static files that is generated by genf90 previously. UFS follow this road to get rid of genf90 dependency. @DeniseWorthen please correct me if I am wrong.

**Comment by jkbk2004** [comment]
> @DusanJovic-NOAA As I know UFS uses the static files that is generated by genf90 previously. UFS follow this road to get rid of genf90 dependency. @DeniseWorthen please correct me if I am wrong.

@DusanJovic-NOAA @uturuncoglu gnu11.2 on cheyenne has a trouble with loading module operator(==). Could it be Fortran 2003 standard issue applied in this file?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA As I know UFS uses the static files that is generated by genf90 previously. UFS follow this road to get rid of genf90 dependency. @DeniseWorthen please correct me if I am wrong.

I know, but I would still prefer that the necessary changes are first made to the template file, then (manually) re-generate this file, so that we preserve the consistency between template and generated file.

**Comment by DusanJovic-NOAA** [comment]
> > @DusanJovic-NOAA As I know UFS uses the static files that is generated by genf90 previously. UFS follow this road to get rid of genf90 dependency. @DeniseWorthen please correct me if I am wrong.
> 
> @DusanJovic-NOAA @uturuncoglu gnu11.2 on cheyenne has a trouble with loading module operator(==). Could it be Fortran 2003 standard issue applied in this file?

According to standard `operator(==)` should be used to compare two `type(ieee_class_type)` values.

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA I agree. The re-generation of the file could solve the issue since it is used regularly under CESM and they are also testing model with different compiler combos. So, new version of genf90 might address the issue. Any suggestion @jedwards4b?

**Comment by uturuncoglu** [comment]
@DusanJovic-NOAA here is the location and version of genf90 used in the latest version of CDEPS.
https://github.com/ESCOMP/CDEPS/blob/8c0b97954b437cdc62aa693ad96511d1d498e1e5/share/CMakeLists.txt#L36

**Comment by uturuncoglu** [comment]
and the command need to be applied to the template files,

https://github.com/ESCOMP/CDEPS/blob/8c0b97954b437cdc62aa693ad96511d1d498e1e5/share/CMakeLists.txt#L53

**Comment by jedwards4b** [comment]
The original of this file is using the correct '==' operators.  https://github.com/ESCOMP/CESM_share/blob/main/src/shr_infnan_mod.F90.in#L195   Did you change these to .eq. in your copy?

**Comment by jkbk2004** [comment]
> The original of this file is using the correct '==' operators. https://github.com/ESCOMP/CESM_share/blob/main/src/shr_infnan_mod.F90.in#L195 Did you change these to .eq. in your copy?

@jedwards4b '==' has compile issue with gnu11.2. I blindly replaced with .eq. @binli2337 I think best way is to revert to original and address the issue when we upgrade to gnu11.2

**Review by junwang-noaa — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
