### PR TITLE
Add zstandard compression to fv3atm; change references from "nems" to "ufs", allow file clobbering for GOCART history files (was #1948)

### LINKED ISSUE #1756: use ufs-appropriate named files and executables
## Description

There are multiple legacy references to "NEMS" and references to standalone fv3 that are still used with the current UFS.

## Solution

We need to gradually transition away from the legacy terms to a naming convention appropriate to the current UWM. This will have RT impacts (but should not change any baseline) as well as G-W impacts.

A partial list includes:

CMEPS: references to nems in the field exchange modules and coupling types
Scripts/tests: references to nems.configure
Executables: all executables are named fv3.exe

### LINKED ISSUE #1955: fix file clobbering issue with GOCART history files
## Description
In UFS coupled tests with GOCART, it is found that when existing gocart history files are not removed in the run directory, the job will fail when resubmitted in the same run directory. This issue is fixed in MAPL and GOCART. A configuration variable will be added in GOCART configuration file to fix the issue.   

A related issue is on GOCART[ #256](https://github.com/GEOS-ESM/GOCART/issues/256)

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Add option to enable zstandard compression in fv3atm.

New model_configure configuration parameter has been added (zstandard_level). Valid values are 0-19 (default is 0). Value 0 turns off compression, values 1-19 specify the level of compression (1=fastest compression, 19=best compression ratio),

This PR is combined with #1948 (@DeniseWorthen)

### Associated UFSWM Issue to close

https://github.com/ufs-community/ufs-weather-model/issues/1927

- closes #1955
- closes #1756
- required by #1648 

### Subcomponent Pull Requests

https://github.com/NOAA-EMC/fv3atm/pull/706
- depends on https://github.com/NOAA-EMC/CMEPS/pull/101

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Review by junwang-noaa — DISMISSED** [review]

**Comment by DusanJovic-NOAA** [comment]
On Hera the nccmp (version 1.9.0.1 from spack-stack) fails with 'Illegal instruction' error:

```
baseline dir = /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20231002/control_p8_intel
working dir  = /scratch1/NCEPDEV/stmp2/Dusan.Jovic/FV3_RT/rt_308812/control_p8_intel
Checking test 001 control_p8_intel results ....
 Comparing sfcf000.nc ............ALT CHECK..rt_utils.sh: line 324: 30915 Illegal instruction     nccmp -d -S -q -f -g -B --Attribute=checksum --warn=format ${RTPWD}/${CNTL_DIR}_${RT_COMPILER}/${i} ${RUNDIR}/${i} > ${i}_nccmp.log 2>&1
....ERROR
```

This happens on ecflow node (hecflow01). When I run this test without ecflow (on login node), nccmp runs fine.

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hera (using rocoto due to the above issue with nccmp on ecflow nodes) [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12820819/RegressionTests_hera.log)

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hercules (using ecflow) 
[RegressionTests_hercules.log](https://github.com/ufs-community/ufs-weather-model/files/12820829/RegressionTests_hercules.log)

**Review by junwang-noaa — DISMISSED** [review]

**Comment by zach1221** [comment]
@DusanJovic-NOAA once we have merged PR#1920, I think we'll begin working on this PR. Would you be able to combine @DeniseWorthen's PR #[1948](https://github.com/ufs-community/ufs-weather-model/pull/1948) into this one?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA once we have merged PR#1920, I think we'll begin working on this PR. Would you be able to combine @DeniseWorthen's PR #[1948](https://github.com/ufs-community/ufs-weather-model/pull/1948) into this one?

I can try.

**Comment by zach1221** [comment]
> > @DusanJovic-NOAA once we have merged PR#1920, I think we'll begin working on this PR. Would you be able to combine @DeniseWorthen's PR #[1948](https://github.com/ufs-community/ufs-weather-model/pull/1948) into this one?
> 
> I can try.

@DusanJovic-NOAA #1920 has now been merged. Please feel free to combine in 1948 and sync up your branch with develop.

**Comment by DusanJovic-NOAA** [comment]
> > > @DusanJovic-NOAA once we have merged PR#1920, I think we'll begin working on this PR. Would you be able to combine @DeniseWorthen's PR #[1948](https://github.com/ufs-community/ufs-weather-model/pull/1948) into this one?
> > 
> > 
> > I can try.
> 
> @DusanJovic-NOAA #1920 has now been merged. Please feel free to combine in 1948 and sync up your branch with develop.

@zach1221 @DeniseWorthen Done.

**Comment by jkbk2004** [comment]
cpld_restart_gfsv17_intel- crashing on hera: /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_226010/cpld_restart_gfsv17_intel/err
```
141: Abort(1) on node 141 (rank 141 in comm 496): application called MPI_Abort(comm=0x84000002, 1) - process 141
...
180: fv3.exe            0000000005C9059B  Unknown               Unknown  Unknown
180: libpthread-2.17.s  00002AB6D481B630  Unknown               Unknown  Unknown
180: fv3.exe            00000000019C8226  yownodepool_mp_co         151  yownodepool.F90
180: fv3.exe            00000000019C8350  yownodepool_mp_in         191  yownodepool.F90
180: fv3.exe            0000000001D4C275  yowpdlibmain_mp_i         395  yowpdlibmain.F90
180: fv3.exe            0000000001D332DF  pdlib_w3profsmd_m         263  w3profsmd_pdlib.F90
180: fv3.exe            0000000001A94156  w3initmd_mp_w3ini         752  w3initmd.F90
180: fv3.exe            00000000019A77A8  wav_comp_nuopc_mp        1638  wav_comp_nuopc.F90
```

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2/Acorn
cpld_[restart/mpi/debug]_gfsv17_intel all fail at runtime with an MPICH abort

**Comment by zach1221** [comment]
@jkbk2004 I too am getting this on Orion. For cpld_restart_gfsv17_intel, cpld_mpi_gfsv17_intel and cpld_debug_gfsv17_intel.

**Comment by jkbk2004** [comment]
> @jkbk2004 I too am getting this on Orion. For cpld_restart_gfsv17_intel, cpld_mpi_gfsv17_intel and cpld_debug_gfsv17_intel.

Exactly those cases are crashing on hera.

**Comment by DeniseWorthen** [comment]
> cpld_restart_gfsv17_intel- crashing on hera: /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_226010/cpld_restart_gfsv17_intel/err
> 
> ```
> 141: Abort(1) on node 141 (rank 141 in comm 496): application called MPI_Abort(comm=0x84000002, 1) - process 141
> ...
> 180: fv3.exe            0000000005C9059B  Unknown               Unknown  Unknown
> 180: libpthread-2.17.s  00002AB6D481B630  Unknown               Unknown  Unknown
> 180: fv3.exe            00000000019C8226  yownodepool_mp_co         151  yownodepool.F90
> 180: fv3.exe            00000000019C8350  yownodepool_mp_in         191  yownodepool.F90
> 180: fv3.exe            0000000001D4C275  yowpdlibmain_mp_i         395  yowpdlibmain.F90
> 180: fv3.exe            0000000001D332DF  pdlib_w3profsmd_m         263  w3profsmd_pdlib.F90
> 180: fv3.exe            0000000001A94156  w3initmd_mp_w3ini         752  w3initmd.F90
> 180: fv3.exe            00000000019A77A8  wav_comp_nuopc_mp        1638  wav_comp_nuopc.F90
> ```

There is nothing in this PR that should have impacted the WW3 pdlib case so this is curious.

**Comment by DusanJovic-NOAA** [comment]
I see this error in one of the PET error files:
```
20231031 131945.409 ERROR            PET141 atmos_model.F90:3154 Not found  - Failure to populate exported field: inst_pres_interface
20231031 131945.409 ERROR            PET141 module_fcst_grid_comp.F90:500 Not found  - Passing error in return code
20231031 131945.409 ERROR            PET141 module_fcst_grid_comp.F90:1245 Not found  - Passing error in return code
20231031 131945.409 ERROR            PET141 fv3_cap.F90:1017 Not found  - Passing error in return code
20231031 131945.409 ERROR            PET141 ATM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:978 Not found  - Passing error in return code
20231031 131945.409 ERROR            PET141 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2838 Not found  - Phase 'IPDvXp04' Initialize for modelComp 2: ATM did not return ESMF_SUCCESS
20231031 131945.409 ERROR            PET141 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:1975 Not found  - Passing error in return code
20231031 131945.409 ERROR            PET141 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:481 Not found  - Passing error in return code
20231031 131945.409 ERROR            PET141 UFS.F90:386 Not found  - Aborting UFS
20231031 131945.409 INFO             PET141 Finalizing ESMF
```

**Comment by DusanJovic-NOAA** [comment]
Those three failed tests are still using NEMS_CONFIGURE:

```
$ grep -r NEMS_CONFIGURE .
./tests/cpld_mpi_gfsv17:export NEMS_CONFIGURE=nems.configure.cpld_noaero_outwav.IN
./tests/cpld_restart_gfsv17:export NEMS_CONFIGURE=nems.configure.cpld_noaero_outwav.IN
./tests/cpld_debug_gfsv17:export NEMS_CONFIGURE=nems.configure.cpld_noaero_outwav.IN

```

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Thanks. That's because these are added tests, so they didn't have the changes I had made in my PR. Let me fix them.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Actually it might be easier for you to fix, now that these have been combined. The change in each test should  be
```
-export NEMS_CONFIGURE=nems.configure.cpld_noaero_outwav.IN
+export UFS_CONFIGURE=ufs.configure.cpld_noaero_outwav.IN
```

**Comment by DusanJovic-NOAA** [comment]
@DeniseWorthen Done. Please double check. 630f983

**Comment by BrianCurtis-NOAA** [comment]
> @DeniseWorthen Done. Please double check. [630f983](https://github.com/ufs-community/ufs-weather-model/commit/630f983da23f0e7ccc1803d8219fc8451c773d82)

I made these changes a bit ago and Acorn has finished successfully, can confirm they are the correct changes.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Looks good, thanks.

**Comment by zach1221** [comment]
Testing is complete. Let's start the merging process of the sub-component PRs.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA CMEPS has been merged [e5d08d4](https://github.com/NOAA-EMC/CMEPS/commit/e5d08d4233b0c783a4840dcbc3252a170e3c3bb1)

**Comment by zach1221** [comment]
@DusanJovic-NOAA fv3atm sub-pr merged. Please revert gitmodule url and update hash. fv3atm hash: 1250b416f526f102c021bf1ab62f583bcba2d249

**Comment by junwang-noaa** [comment]
@DeniseWorthen would you please create an issue in global-workflow about the nems.configure and file clobber updates when this version of model is updated in GW? Thanks

**Comment by bbakernoaa** [comment]
I had included the clobber update in a PR for the global-workflow here
https://github.com/NOAA-EMC/global-workflow/pull/1989

**Comment by DeniseWorthen** [comment]
The nems->ufs GW issue is https://github.com/NOAA-EMC/global-workflow/issues/1942

**Review by jkbk2004 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
