### PR TITLE
ufs_public_release: update version number for CCPP, disable dynamic CCPP, cleanup work and bug fixes for regression tests

### PR DESCRIPTION
**Pull request by climbfuji**
- cleanup regression tests: remove unused regression test configurations, run scripts and namelist templates
- add CCPP and IPD regression tests for comparison in REPRO mode (GFSv15p2 and GFSv16beta)
- disable inline post on all supported platforms
- fix regression tests: correct run scripts, check for output from tests in debug mode
- convert namelist templates to unix line endings
- disable dynamic CCPP build
- update date tag for regression test baseline
- update submodule pointer for the stochastic_physics submodule
- update of gaea modulefiles and regression test baseline directories (from develop)
- update of cheyenne default queue (from develop)

With these changes,
- results are bit-for-bit identical between the IPD and CCPP tests in REPRO mode on Hera and Cheyenne using the Intel compiler,
- results are bit-for-bit identical between the IPD and CCPP tests in REPRO mode on macOS using the GNU compiler (1hr fcst only instead of the usual 24h fcst)
- all tests complete in DEBUG mode instead of crashing, silent failures are avoided by explicitly checking for the output files (see issue https://github.com/ufs-community/ufs-weather-model/issues/23)

Known issue: The results differ between the IPD and CCPP tests in REPRO mode on Cheyenne using the GNU compiler for 24hr fcst runs. I have not tested if the results are still identical after 1hr (since they are on macOS). For this reason, the IPD verification against the CCPP results in REPRO mode are turned off for Cheyenne+GNU.

### CODE REVIEW

**Comment by climbfuji** [comment]
Associated PRs:

https://github.com/NCAR/ccpp-framework/pull/247
https://github.com/NCAR/ccpp-physics/pull/374
https://github.com/NOAA-EMC/fv3atm/pull/33
https://github.com/ufs-community/ufs-weather-model/pull/25

**Comment by climbfuji** [comment]
New regression test baselines have been created on Cheyenne and are currently located in:
```
/glade/p/ral/jntp/GMTB/NEMSfv3gfs/RT/TMP_ufs-public-release-20200107
```
On hera, they are in:
```
/scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_UFS_PUBLIC_RELEASE_INTEL
```
Once the code review is complete, I can rename the Cheyenne baseline and EMC will need to move the Hera baseline into the right place before running the regression tests once more and updating the logs in the ufs-weather-model PR.

**Comment by climbfuji** [comment]
All regression tests have passed and the logs have been updated in the PR.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA this is ready from my side. Took me three attempts to revert the `.gitmodules` change correctly.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
