### PR TITLE
Merge HAFSv1 related developments back to the develop branch

### LINKED ISSUE #182: Modularization of moving nest and storm tracker functionality.
**Is your feature request related to a problem? Please describe.**
Modularization of moving nest and storm tracker functionality

**Describe the solution you'd like**
GFDL requests a code update with the following features:

1. Take moving nested grid code and move it into its own component (at the same level as atmos_cubed_sphere). 
2. Physics code must be moved out of FV3 or its submodules.
3. Access FV3 exclusively through APIs defined in atmosphere.F90

**Describe alternatives you've considered**
AOML and GFDL agreed to initial changes for PR 179, and these additional steps to be accomplished in an upcoming release.

**Additional context**
Additional comments from GFDL:

You may consider promoting the moving nested grid to be a separate 
component, on the same level as atmos_cubed_sphere. This would be similar to the implementation of stochastic physics. In this case, the moving nest implementation would still be dependent upon FV3 but not necessarily a part of it, and communicates with FV3 through the APIs defined in atmosphere.F90. Additionally, the vortex tracker could also be separate from the moving nest code.

While many others have implemented new capabilities within #ifdef/#endif blocks, there is a tendency to overuse this approach to mask out features which may have limited adoption.  Along with the modularization recommended above, it may be acceptable to include moving nest options directly within the model without an #ifdef block.

Please note that the vast majority of FV3-based model users will not be concerned with the moving nested grids. This is especially true for our many users outside of the UFS (NASA, GFDL, NCAR, etc.) and we need to ensure the unified codebase is useful for all of our users.

Other notes:

Have computational performance (and repro?) baselines been performed to ensure other applications have not seen degraded performance?

If the simplified version of Tim’s GFDL Hurricane Tracker is useful outside of this context maybe it is better to separate it from the moving nest code

Will GFDL be responsible for maintaining the moving nested-grid code once the merge is complete? If so, it would be useful if AOML could provide some sort of documentation to explain how this works.

### LINKED ISSUE #1515: Bring in HAFSv1 related developments
## Description
Merge HAFSv1 related developments back to ufs-weather-model develop branch.

## Solution
HAFSv1 related developments has been tested with the HAFS application. Will merge related branches/submodules back to corresponding authoritative branches.

## Alternatives
N/A.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- addressed by ufs-community/ufs-weather-model/pull<pr_number>
- related to NOAA-EMC/fv3atm/pull/610
- related to NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/227
- related to NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/182
- related to NOAA-EMC/HYCOM-src/pull/3

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

Bring in HAFSv1 related developments back to ufs-weather-model develop branch. 

- Details about the HAFS related FV3ATM changes can be seen from NOAA-EMC/fv3atm/pull/610.
- Update the HYCOM submodule, which fixed the momentum flux for HAFS FV3ATM-HYCOM coupling.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes ufs-community/ufs-weather-model/issues/1515
- fixes NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/182

## Testing

- Regression testing were conducted at the ufs-weather-model level and the HAFS application level.
- Only HAFS related regression tests get changing results (which is expected). All other regression tests got identical results. This does indicate new baseline will need be created at least for the HAFS related RTs.
- Note: No updates for input data 

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on NOAA-EMC/fv3atm/pull/610
- waiting on NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/227
- waiting on ufs-community/ccpp-physics/pull/27
- waiting on NOAA-EMC/HYCOM-src/pull/3

### CODE REVIEW

**Comment by jkbk2004** [comment]
@BinLiu-NOAA we are about to merge in #1514. Then, we like to work on this pr.

**Comment by BinLiu-NOAA** [comment]
@jkbk2004, Thanks for letting us know! I saw PR #1514 has already been merged. So, I will sync it up later today. Thanks!

**Comment by jkbk2004** [comment]
> @jkbk2004, Thanks for letting us know! I saw PR #1514 has already been merged. So, I will sync it up later today. Thanks!

Sure! I hope the ccpp and cubed sphere dependencies are fully reviewed and ready to go for the regression tests. We can start testing tomorrow.

**Comment by BinLiu-NOAA** [comment]
@jkbk2004, this PR is not up to date with the latest develop branch and its corresponding submodules. Thanks!

**Comment by jkbk2004** [comment]
@BinLiu-NOAA I don't have hafs-community repository. can you add me to https://github.com/hafs-community/ufs-weather-model ?

**Comment by jkbk2004** [comment]
@BinLiu-NOAA we need to add BL_DATE=20221212

**Comment by BinLiu-NOAA** [comment]
@jkbk2004, I have invited you to hafs-community. Please accept the invitation. Also, BL_DATE=20221212 is updated accordingly. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1144582046/20221213070011/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1144582046/20221213130017/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by jkbk2004** [comment]
All tests are done. We can start merging process.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@BinLiu-NOAA fv3atm pr was merged. We can finish merging the pr. Please, update the fv3atm submodule pointer.

**Comment by BinLiu-NOAA** [comment]
@jkbk2004, done, all the submodules are up to date now. Thanks a lot!

**Comment by jkbk2004** [comment]
> @jkbk2004, done, all the submodules are up to date now. Thanks a lot!

@BinLiu-NOAA Great to see heavy changes finalized. merging now.

**Pull request merged**
