### PR TITLE
Update CICE for advanced snow physics, history file timestamping and history file precision

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Implements advanced snow physics in Icepack and CICE. Fixes history file issue when the initial time is not at hour 0. This is needed for the update to the coupled RT tests, which use an initial time of hour=6 since it impacts the history file timestamp. 

Changes are required in ``ice_in`` to accommodate both the advanced snow physics as well as a renaming of the evp algorithm.

### Issue(s) addressed

See CICE issue [#37](https://github.com/NOAA-EMC/CICE/issues/37) for a more complete description of changes.

## Testing

All baselines for tests using CICE will change, even with the advanced snow physics option turned off.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1238604024

## Dependencies

- waiting on CICE PR [#38](https://github.com/NOAA-EMC/CICE/pull/38)
- waiting on IcePack PR [#6](https://github.com/NOAA-EMC/Icepack/pull/6)

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
I cannot comment on the CICE changes, but the changes in this PR are straightforward. Hopefully the Gaea issues will be addressed soon by the sysadmins so that we can reduce the wallclock time for compile jobs and run jobs again.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/716696085/20210915134513/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_5602
Baseline creation and move successful
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/716696085/20210915145627/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_19780
Test cpld_bmark_wave_v16_p7b 014 failed failed 
Test cpld_bmark_wave_v16_p7b 014 failed in run_test failed 
Test hafs_regional_atm_ocn 086 failed failed 
Test hafs_regional_atm_ocn 086 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/716696085/20210915133006/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_36997
Test regional_control 024 failed failed 
Test regional_control 024 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/716696085/20210915193006/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_33977
Test regional_restart 036 failed in check_result failed 
Test regional_restart 036 failed in run_test failed 
Test control_stochy 028 failed failed 
Test control_stochy 028 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by DeniseWorthen** [comment]
I think the failed Gaea test revealed a problem with how the ``regional_control`` and ``regional_restart`` tests are set up and/or run. This is what I think happened:

The rt.conf has:

```
RUN     | regional_control                                                |                                         | fv3 |
RUN     | regional_restart                                                |                                         | fv3 | regional_control
```

So regional_restart is both run during baseline creation and is dependent on regional_control. The ``regional_restart`` test uses ``fv3_regional_restart`` as it's ``CNTL_DIR``.

The Gaea Auto-BL reported a failure for ``regional_control`` so I re-ran that test. But the ``regional_restart`` test was not run by Auto-BL because ``regional_control`` itself failed. The BL created by Auto-BL is missing the ``regional_restart`` baseline. But only the ``regional_control`` was reported as a failed test.

When Auto-BL reported that ``regional_control`` failed, I created a baseline for that test manually and moved it to the BL directory. 

When Auto-RT reported that ``regional_restart`` and ``control_stochy`` had both failed, I assumed both were from time-outs and set a manual test for ``regional_control``,``regional_restart`` and ``control_stochy`` . I ran both the control and restart for regional because I assumed restart was dependent on control.

But in fact the ``regional_restart`` failed because the baseline itself was missing. 

I can go back and create the ``regional_restart`` manually, but I think we need to resolve how the control/restart test is being run for the regional.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/716696085/20210915090008/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_321097
Test control_c192 015 failed failed 
Test control_c192 015 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 013 failed failed 
Test control_wrtGauss_netcdf_parallel 013 failed in run_test failed 
Test control_ca 019 failed failed 
Test control_ca 019 failed in run_test failed 
Test control_stochy 018 failed failed 
Test control_stochy 018 failed in run_test failed 
Test control_rrtmgp 035 failed failed 
Test control_rrtmgp 035 failed in run_test failed 
Test control_csawmg 036 failed failed 
Test control_csawmg 036 failed in run_test failed 
Test control_csawmgt 037 failed failed 
Test control_csawmgt 037 failed in run_test failed 
Test control_flake 038 failed failed 
Test control_flake 038 failed in run_test failed 
Test control_ugwpv1 039 failed failed 
Test control_ugwpv1 039 failed in run_test failed 
Test control_ras 040 failed failed 
Test control_ras 040 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by DeniseWorthen** [comment]
All the Orion failures were time-outs. I can retrieve all but three from my attempt at a manual BL creation. I'll need to get the flake,ugwpv1 and ras BLs created and then still run the verify step.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
