### PR TITLE
update WW3 with its develop branch

### LINKED ISSUE #1624: Update WW3 with its develop branch
## Description
Belated routine update of WW3 merging updates from its develop branch to the dev/ufs-weather-model branch of WW3.  

## Solution
PR to update WW3 with it's develop branch.  

## Alternatives
none. 

## Related to
None

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Description
Belated routine update of WW3 to merge in updates from develop to the dev/ufs-weather-model branch of WW3 in ufs-weather-model. 
This PR now brings in the ability to use the SCOTCH domain decomposition library (alternative to ParMETIS).  This PR will not take advantage of this feature on the ufs-weather-model level, but it is included in the WW3 update. 

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):

(This PR could be combined with any other PR that does not involve WW3.  This should not be combined with other PRs that update WW3). 

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on NOAA-EMC/WW3/pull/914
- Closes #1624 

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Please attach the regression tests gnu and intel log showing no baselines change with this PR to a comment here.

**Review by BrianCurtis-NOAA — APPROVED** [review]
No impactful changes to UFSWM, approved for testing once it's in commit queue.

**Comment by JessicaMeixner-NOAA** [comment]
@BrianCurtis-NOAA  here are the logs: 
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10824927/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10824928/RegressionTests_hera.intel.log)

**Comment by JessicaMeixner-NOAA** [comment]
I pushed 2 recent updates to the WW3 develop branch to this sync.  This will fix the CI (again) and merges in the update which includes the ability to use SCOTCH instead of ParMETIS (not actually turned on).  I also merged the latest ufs-weather-model and re-ran tests: 
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10875290/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10875291/RegressionTests_hera.intel.log)
There are still no answer changes in this PR.

**Comment by zach1221** [comment]
Hi, @JessicaMeixner-NOAA we're going to start working through this PR next and begin testing.

**Comment by zach1221** [comment]
Please see jenkins-ci logs attached. ORTs have passed.
[ufs-weather-model » ort-docker-pipeline » PR-1625 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10942447/ufs-weather-model.ort-docker-pipeline.PR-1625.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1253252250/20230310134519/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 @zach1221 It looks like all the regression tests have passed, are we ready for the WW3 PR to be merged?

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @zach1221 Sure! go ahead to merge in the WW3 dependency.

**Comment by JessicaMeixner-NOAA** [comment]
WW3 PR has been merged and committed to this PR.

**Review by jkbk2004 — APPROVED** [review]

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /mnt/lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1253252250/20230310140711/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Pull request merged**
