### PR TITLE
Fix potential divide by zero in ww3; Add timers to WW3 cap (was #2086); Allow MOM6 to write non-interval restarts (was #2099)

### LINKED ISSUE #1159: Appendtail (called by w3fld1 and w3fld2) can get NaNs from variable "avg"
**Describe the bug**

The variable AVG in  SR appendtail can be zero and results in NaNs being returned to w3fld2 in array ``SPC2``. This is triggered when implementing wave-ice coupling (using CICE) in UWM and CESM. When a NaN is returned, fld2 will fail-safe with the code

```
    IF (.not.((CD .LT. 0.01).AND.(CD .GT. 0.0005)).or. .not.(NO_ERR)) THEN
      !Fail safe to bulk
```

In debug mode, the model will fail but typically at a point longer than the UWM debug RTs, which are 3 hours (ie, the model fails after 8 hours). 

This may or may not be caught by WW3 standalone RTs. @MatthewMasarik-NOAA What is the longest debug RT test that utilizes FLD1 or FLD2?

**To Reproduce**

Set up a case w/ wave-ice coupling in UWM and run the debug case> 8hours. The model will fail w/ ``float invalid``. In non-debug, the model does not fail but produces the log message 

``Calculated Wind/Cd: ',UREF,CD,UST`` 

where both CD and UST are NaN.

**Expected behavior**

Division using ``avg`` should not occur when ``avg==0.0``.

@NickSzapiro-NOAA

### LINKED ISSUE #1162: Allow timer log functionality in the meshcap
**Is your feature request related to a problem? Please describe.**

For https://github.com/ufs-community/ufs-weather-model/issues/1367, we are adding timer logs to the individual cap. We need to add this function to the mesh cap in a way similar to that done for CICE in https://github.com/NOAA-EMC/CICE/pull/63

**Describe the solution you'd like**
Mimic the functionality that was added to CICE

**Describe alternatives you've considered**
None

**Additional context**

None

### LINKED ISSUE #1976: Enable controlling MOM6 ocean restart files with a more flexible approach
## Description

Currently, when running coupled ufs-weather-model configurations with ocean coupling (e.g. MOM6), users can only control the restart file output interval through, for example, restart_n = 24 and restart_option = nhours, meaning every 24 hours. In addition, MOM6 also write out the restart file at the end of the forecast. 

However, for ocean data assimilation (DA) purpose, one would need output the MOM6 restart files at forecast hour 6 (or hours 3, 6, 9), providing first guess for DA. 

Meanwhile, it is definitely too expensive (for IO bandwidth/time and disk space) to write out restart files every 6 hours through the restart_n=6 option throughout the forecast length. With that, it would be beneficial to make it somewhat flexible to control the MOM6 ocean restart file output frequency.
## Solution

Improve the current method to enable somewhat more flexible method to control the MOM6 ocean restart file output frequency.

## Alternatives

N/A.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [x] Add list of all failed regression tests in "Regression Tests" section.

## PR Information
 
- closes https://github.com/NOAA-EMC/WW3/pull/1163
- closes  https://github.com/NOAA-EMC/MOM6/pull/126
- needed by  https://github.com/ufs-community/ufs-weather-model/issues/1367
### Description

Prevent divide-by-zero when using WAV-ICE coupling in UWM

Update WW3 to enable run timers in the cap. As with the CICE and MOM6 caps, the feature is enabled by setting
``RunTimeLog = true`` in the ALLCOMP_attributes.

The timer log will be ``log.ww3.timer`` which will show

```
20210322   60000   21600 WW3 InitializeRealize time: 0.7798858
20210322   60000   21600 WW3 ModelAdvance time since last step:  4.489980
20210322   61200   22320 WW3 ModelAdvance time:  2.570183
20210322   61200   22320 WW3 ModelAdvance time since last step:  8.023816
20210322   62400   23040 WW3 ModelAdvance time:  1.164186
20210322   62400   23040 WW3 ModelAdvance time since last step: 0.1100351E-01
```
Also adds the capability of reading a WW3 configuration attribute to allow WW3 timesteps to over-write timesteps saved in pre-created mod_def file. This allows the same mod_def file to be used for either inner or outer loop coupling. To test the feature, a version of mod_def.mx100 was created with the "outer loop" timesteps:

```
$ if outerloop: 3600 900 1800 30
 720 360 360 30
```

This mod_def was then used for the cpld_control RTs, but adding the WAV attribute:

```
# WAV #
WAV_model:                      ww3
...(snip)
  dt_in = 720,360,360,30
::
```

All tests passed.

See also #2099 for description for non-interval restarts in MOM6.

### Commit Message

```
fix potential divide by zero in WW3 appendtail routine
add timers to WW3 mesh cap
add non-interval restart capability to MOM6
```
### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [X] Normal Required by PR #2072 

### Git Issues Fixed By This PR

- fixes https://github.com/NOAA-EMC/WW3/issues/1162
- fixes https://github.com/NOAA-EMC/WW3/issues/1159
- fixes #1976

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [x] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

Note: Prior to the cpld GNU tests being disabled on Hercules, the debug tests using ww3 failed using that later GNU compiler.

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [ ] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I know there was an email (?) about combining the two WW3 PRs but I can't find it now. I want to be sure it is oK to combine https://github.com/NOAA-EMC/WW3/pull/1163 and https://github.com/NOAA-EMC/WW3/pull/1164.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen Yes - feel free to combine!

**Comment by jiandewang** [comment]
@DeniseWorthen that's totally fine.  I will push your work back to main repo. once this is done.

**Comment by DeniseWorthen** [comment]
@jkbk2004 We also have the option of combining in the MOM6 restart PR #2099 since it also does not change baselines.

**Comment by jkbk2004** [comment]
@DeniseWorthen we need more time on #2066 and #2059. Please, feel free to combine with #2099 to this pr. Whenever ready, we can start working on this pr. @zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA FYI

**Comment by FernandoAndrade-NOAA** [comment]
@jkbk2004 @zach1221 FYI I've updated Jet's rocoto version in rt.sh to 1.3.6 after the default was upgraded following the recent maintenance. Otherwise a not found error would be triggered.

**Comment by zach1221** [comment]
Ok, regression is should be complete, since we're skipping Gaea and WCOSS. We can begin the merge process with WW3 [#1163](https://github.com/NOAA-EMC/WW3/pull/1163) and MOM6 [#126](https://github.com/NOAA-EMC/MOM6/pull/126) .

**Comment by BrianCurtis-NOAA** [comment]
> Ok, regression is should be complete, since we're skipping Gaea and WCOSS. We can begin the merge process with WW3 [#1163](https://github.com/NOAA-EMC/WW3/pull/1163) and MOM6 [#126](https://github.com/NOAA-EMC/MOM6/pull/126) .

@zach1221 WCOSS2 is almost done. It opened back up this AM and i'll have those logs in a little bit.

**Comment by zach1221** [comment]
> > Ok, regression is should be complete, since we're skipping Gaea and WCOSS. We can begin the merge process with WW3 [#1163](https://github.com/NOAA-EMC/WW3/pull/1163) and MOM6 [#126](https://github.com/NOAA-EMC/MOM6/pull/126) .
> 
> @zach1221 WCOSS2 is almost done. It opened back up this AM and i'll have those logs in a little bit.

Oh, ok. No problem. Thanks, Brian.

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 all good to start merge process

**Comment by zach1221** [comment]
@DeniseWorthen WW3 sub-pr has been merged already. Hash: https://github.com/NOAA-EMC/WW3/commit/4ffc47e10e3d3f3bbee50251aacb28b7e0165b92

**Comment by zach1221** [comment]
MOM6 is merged as well. Hash: https://github.com/NOAA-EMC/MOM6/commit/c8a7325c040b4cb1327c55c8248e8e66972239a5

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
