### PR TITLE
Post update

### LINKED ISSUE #2126: missing reflectivity when using NSSL microphysics, Cu and inline post
## Description

When running RRFS ensemble members using NSSL microphysics and Cu with inline post on, there are areas of missing reflectivity. This is caused by UPP not having the correct hook for reflectivity processing with imp_physics=17/18 (NSSL microphysics).

### To Reproduce:

run rrfs forecast with NSSL microphysics and Cu. Have inline post on
check the reflectivity for areas of missing values

## Output

See slides for reflectivity before and after fix:
[missing_refl_forPR.pptx](https://github.com/ufs-community/ufs-weather-model/files/14181562/missing_refl_forPR.pptx)

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [x] Add list of all failed regression tests in "Regression Tests" section.

### Description

This PR will update UPP to the latest commit. With the updated UPP, this PR will fix the missing reflectivity bug when using NSSL MP and inline post together by adding nssl mp to microphysics options when assigning model reflectivity.
### Commit Message

UPP will be brought to the commit to fix the missing reflectivity bug for NSSL MP cases.

### Priority
- [x] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Blocking Dependencies

- NOAA-EMC/fv3atm#774
### Git Issues Fixed By This PR

- Closes #2126

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
  - NOAA-EMC/fv3atm#774
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

regional_wofs_intel 063

rrfs_v1nssl_intel 077

rrfs_v1nssl_nohailnoccn_intel 078

grib2 output will be changed by this PR for tests with NSSL microphysics and inline post combined together

```
regional_wofs_intel 063

rrfs_v1nssl_intel 077

rrfs_v1nssl_nohailnoccn_intel 078
```

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [ ] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by JiliDong-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14040992/RegressionTests_hera.log)

**Comment by JiliDong-NOAA** [comment]
need more time to investigate the failed RT

**Comment by JiliDong-NOAA** [comment]
After further investigation, the failed RTs are expected with the baseline changes from:
1. REFZI and REFZR are switched to missing values as expected, which is similar to what Thompson microphysics scheme does
2. missing value are handled differently for reflectivity when switching to the correct block: previousy missing values will be reset to dbzmin and they are now kept as is.

**Comment by jkbk2004** [comment]
@JiliDong-NOAA What is your timeline to commit this PR? If there is any urgency waiting for this PR, we will give a priority.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA What is your timeline to commit this PR? If there is any urgency waiting for this PR, we will give a priority.

I don't have a timeline for this PR, but it will still be good to get it committed soon as this PR is essentially a bug fix.

**Comment by BrianCurtis-NOAA** [comment]
There are still requests waiting in your NOAA-EMC/fv3atm#774 PR. It would be helpful to know why this is a **critical** bugfix.

**Comment by JiliDong-NOAA** [comment]
> ## Commit Queue Requirements:
> * [x]  Fill out all sections of this template.
> * [ ]  All sub component pull requests have been reviewed by their code managers.
> * [x]  Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
> * [x]  Add list of all failed regression tests in "Regression Tests" section.
> 
> ## PR Information
> ### Description
> This PR will update UPP to the latest commit. With the updated UPP, this PR will fix the missing reflectivity bug when using NSSL MP and inline post together by adding nssl mp to microphysics options when assigning model reflectivity.
> 
> ### Commit Message
> UPP will be brought to the latest commit.
> 
> ### Priority
> * [x]  Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
> * [ ]  High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
> * [ ]  Normal
> 
> ### Blocking Dependencies
> [NOAA-EMC/fv3atm#774](https://github.com/NOAA-EMC/fv3atm/pull/774)
> 
> ### Git Issues Fixed By This PR
> ## Changes
> ### Subcomponent (with links)
> * [ ]  AQM
> * [ ]  CDEPS
> * [ ]  CICE
> * [ ]  CMEPS
> * [ ]  CMakeModules
> * [x]  FV3
> * [ ]  GOCART
> * [ ]  HYCOM
> * [ ]  MOM6
> * [ ]  NOAHMP
> * [ ]  WW3
> * [ ]  stochastic_physics
> * [ ]  none
> 
> ### Input data
> * [x]  No changes are expected to input data.
> * [ ]  Changes are expected to input data:
>   
>   * [ ]  New input data.
>   * [ ]  Updated input data.
> 
> ### Regression Tests:
> * [ ]  No changes are expected to any regression test.
> * [x]  Changes are expected to the following tests:
> 
> FAILED REGRESSION TESTS
> ### Libraries
> * [x]  Not Needed
> * [ ]  Needed
>   
>   * [ ]  Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
>   * [ ]  Add issue link from JCSDA/spack-stack following this item
> 
> ### Testing Log:
> * RDHPCS
>   
>   * [ ]  Hera
>   * [ ]  Orion
>   * [ ]  Hercules
>   * [ ]  Jet
>   * [ ]  Gaea
>   * [ ]  Derecho
> * WCOSS2
>   
>   * [ ]  Dogwood/Cactus
>   * [ ]  Acorn
> * CI
>   
>   * [ ]  Completed
> * opnReqTest
>   
>   * [ ]  N/A
>   * [ ]  Log attached to comment



> There are still requests waiting in your [NOAA-EMC/fv3atm#774](https://github.com/NOAA-EMC/fv3atm/pull/774) PR. It would be helpful to know why this is a **critical** bugfix.

I just:

1. synced the PR with develop
2. updated FV3 request by adding explanation and slides to PR template
3. created issues for ufs-weather-model and FV3 and referred in PR

Here is the slides showing reflectivity before and after the fix. 

[missing_refl_forPR.pptx](https://github.com/ufs-community/ufs-weather-model/files/14181615/missing_refl_forPR.pptx)

Please let me know what else I need to do.

**Comment by JiliDong-NOAA** [comment]
> There are still requests waiting in your [NOAA-EMC/fv3atm#774](https://github.com/NOAA-EMC/fv3atm/pull/774) PR. It would be helpful to know why this is a **critical** bugfix.

I just:

1. synced the PR with develop
2. updated FV3 request by adding explanation and slides to PR template
3. created issues for ufs-weather-model and FV3 and referred in PR

Here is the slides showing reflectivity before and after the fix. 

[missing_refl_forPR.pptx](https://github.com/ufs-community/ufs-weather-model/files/14181615/missing_refl_forPR.pptx)

Please let me know what else I need to do.

**Comment by BrianCurtis-NOAA** [comment]
Thanks Jili! The Hera log you have attached to the PR is just an xml formatted file and the Hera log you committed to the PR is still in a merge conflict state.

The commited log shows the following:
```
FAILED TESTS: 
063 regional_wofs_intel failed in check_result
regional_wofs_intel 063 failed in run_test
077 rrfs_v1nssl_intel failed in check_result
rrfs_v1nssl_intel 077 failed in run_test
078 rrfs_v1nssl_nohailnoccn_intel failed in check_result
rrfs_v1nssl_nohailnoccn_intel 078 failed in run_test
```
Could you update the top post with the names of the tests and not the numbers of them? I can accept the committed log as an example of what tests fail for now.

**Comment by JiliDong-NOAA** [comment]
> Thanks Jili! The Hera log you have attached to the PR is just an xml formatted file and the Hera log you committed to the PR is still in a merge conflict state.
> 
> The commited log shows the following:
> 
> ```
> FAILED TESTS: 
> 063 regional_wofs_intel failed in check_result
> regional_wofs_intel 063 failed in run_test
> 077 rrfs_v1nssl_intel failed in check_result
> rrfs_v1nssl_intel 077 failed in run_test
> 078 rrfs_v1nssl_nohailnoccn_intel failed in check_result
> rrfs_v1nssl_nohailnoccn_intel 078 failed in run_test
> ```
> 
> Could you update the top post with the names of the tests and not the numbers of them? I can accept the committed log as an example of what tests fail for now.

PR template updated with failed RT tests name added.

**Comment by zach1221** [comment]
@JiliDong-NOAA We're ready to begin testing this PR. Can you please sync up your branch?

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA We're ready to begin testing this PR. Can you please sync up your branch?

Done

**Comment by zach1221** [comment]
Testing is complete. Let's move to merge the fv3atm sub-pr.

**Comment by zach1221** [comment]
@JiliDong-NOAA fv3atm sub-pr is merged. Please update submodule hash and revert .gitmodule url.
https://github.com/NOAA-EMC/fv3atm/commit/9dec0faa6eafefc4b01f3cd117231619fb0670f4

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA fv3atm sub-pr is merged. Please update submodule hash and revert .gitmodule url. [NOAA-EMC/fv3atm@9dec0fa](https://github.com/NOAA-EMC/fv3atm/commit/9dec0faa6eafefc4b01f3cd117231619fb0670f4)

.gitmodules reverted and FV3 updated

**Review by sadeghitabas — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
