### PR TITLE
Update CCPP standard names for consistency

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [n/a] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR only updates the submodule pointer for fv3atm for the CCPP standard name updates described in the associated PRs below (in fv3atm and ccpp-physics). No changes to the input data or the results.

## Testing

Regression tests are run on all tier-1 platforms against the existing baselines, except Cheyenne (still under maintenance):

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [-] cheyenne.intel (skip, maintenance)
- [-] cheyenne.gnu (skip, maintenance)
- [X] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1076391676

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/715
https://github.com/NOAA-EMC/fv3atm/pull/356
https://github.com/ufs-community/ufs-weather-model/pull/719

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/698974631/20210728151511/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_456945
Test cpld_control_c192 006 failed failed 
Test cpld_control_c192 006 failed in run_test failed 
Test cpld_control_c384 008 failed failed 
Test cpld_control_c384 008 failed in run_test failed 
Test cpld_bmark_wave_v16 013 failed failed 
Test cpld_bmark_wave_v16 013 failed in run_test failed 
Test cpld_bmark_v16_nsst 012 failed failed 
Test cpld_bmark_v16_nsst 012 failed in run_test failed 
Test control_c192 024 failed failed 
Test control_c192 024 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 023 failed failed 
Test control_wrtGauss_netcdf_parallel 023 failed in run_test failed 
Test control_lheatstrg 031 failed failed 
Test control_lheatstrg 031 failed in run_test failed 
Test control_csawmgt 036 failed failed 
Test control_csawmgt 036 failed in run_test failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Test control_c384 025 failed failed 
Test control_c384 025 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Comment by climbfuji** [comment]
> Machine: orion
> Compiler: intel
> Job: RT
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/698974631/20210728151511/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_456945
> Test cpld_control_c192 006 failed failed
> Test cpld_control_c192 006 failed in run_test failed
> Test cpld_control_c384 008 failed failed
> Test cpld_control_c384 008 failed in run_test failed
> Test cpld_bmark_wave_v16 013 failed failed
> Test cpld_bmark_wave_v16 013 failed in run_test failed
> Test cpld_bmark_v16_nsst 012 failed failed
> Test cpld_bmark_v16_nsst 012 failed in run_test failed
> Test control_c192 024 failed failed
> Test control_c192 024 failed in run_test failed
> Test control_wrtGauss_netcdf_parallel 023 failed failed
> Test control_wrtGauss_netcdf_parallel 023 failed in run_test failed
> Test control_lheatstrg 031 failed failed
> Test control_lheatstrg 031 failed in run_test failed
> Test control_csawmgt 036 failed failed
> Test control_csawmgt 036 failed in run_test failed
> Test cpld_bmark_v16 010 failed failed
> Test cpld_bmark_v16 010 failed in run_test failed
> Test control_c384 025 failed failed
> Test control_c384 025 failed in run_test failed
> Please make changes and add the following label back:
> orion-intel-RT

Seems like these tests timed out. I am on orion now, the file system response is really, really slow. Will try to run again manually, but since the filesystem is still slow I guess we will have timeouts again.

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
orion.intel done at last - we can start the merge process

**Comment by climbfuji** [comment]
Ready to merge, please check again and click the magic button. Thanks!

**Pull request merged**
