### PR TITLE
bug fixes: kchunk3d ignored, hailwat uninitialized in dycore, tile_num wrong for nests

### LINKED ISSUE #2209: extremely verbose write statement in FV3
## Description
This write statement produces many megabytes of output for some configurations. It is enough to have a significant impact on the runtime:

```f90
write(0,*) ' history_type_store_data3D kinds ', kind_phys, kind(work), lbound(work), ubound(work), size(work)
```

### To Reproduce:
Run FV3 with the write component. Witness the write statement

### LINKED ISSUE #2227: MPI_Type_contiguous Encounters Invalid Count
## Description

An MPI-related fatal error occurred during the execution of the code, leading to job cancellation.

### To Reproduce:

Compilers: intel/2022.1.2, impi/2022.1.2, stack-intel/2021.5.0, stack-intel-oneapi-mpi/2021.5.1
Platform: Hera (Rocky 8)
1. copy the canned test case from /scratch2/BMC/wrfruc/Sijie.Pan/ufs-ar/comroot/fcst.test
2. submit slurm job submit_ufs_model.sh.
3. check the output file slurm-${jobid}.out

## Additional context

The problem specifically arises on the 2304th core.

## Output

[ufs_model_crash.log](https://github.com/ufs-community/ufs-weather-model/files/14877488/ufs_model_crash.log)

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Fixes these bugs:

1. Fix from @DusanJovic-NOAA wherein the  `kchunk3d` setting in model_configure was ignored. This caused an abort due to a negative index in an MPI call on some platforms. This my have been due to a 32-bit integer wraparound, but we cannot confirm that.
2. A hailwat variable was uninitialized in the FV3 dynamical core. Now it is set to the hailwat tracer index.
3. The tile_num sent to CCPP in FV3 was wrong for the nest because it was the index of the tile in the mosaic (index 1) instead of the "global tile number" (index 7). This is corrected by having the dynamical core pass the "global tile number" up to the model.

No answers should change.

### Commit Message:

```
* UFSWM - None.
  * FV3 - Write component will use kchunk3d. Model init sends the right tile number to CCPP.
    * atmos_cubed_sphere - Initialize the hailwat variable. Pass global_tile index to model.
```

### Priority:

* Critical

### UFSWM:

Issues:
* UFSWM: fixes https://github.com/ufs-community/ufs-weather-model/issues/2209
* UFSWM: fixes https://github.com/ufs-community/ufs-weather-model/issues/2227
  * FV3: https://github.com/NOAA-EMC/fv3atm/issues/797
    * GFDL_atmos_cubed_sphere:
      * https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/328
      * https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/329

Note: Although #2227 is an issue in this repository, the bug is in FV3.

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/806
  * atmos_cubed_sphere: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/331

### UFSWM Blocking Dependencies:

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA EPIC wants to go with this PR next. Could you run the full suite on Hera and commit the test_changes.list please?

**Comment by SamuelTrahanNOAA** [comment]
I am rerunning regression tests now. 259 of 299 tests have completed and none have failed. I disabled job resubmission, so this means the tests are passing on the first try.

**Comment by SamuelTrahanNOAA** [comment]
Could someone please request reviews from these individuals?

@DusanJovic-NOAA @zhanglikate @kayeekayee @spanNOAA @ChristianBoyer-NOAA

They have been involved in testing the fix for the critical kchunk3d bug

**Comment by BrianCurtis-NOAA** [comment]
> Could someone please request reviews from these individuals?
> 
> @DusanJovic-NOAA @zhanglikate @kayeekayee @spanNOAA @ChristianBoyer-NOAA
> 
> They have been involved in testing the fix for the critical kchunk3d bug

Only Dusan seems to be allowed as a requested reviewer, but the others can still give a review i believe

**Comment by SamuelTrahanNOAA** [comment]
Regression tests passed. No baseline changes.

EDIT: Regression tests passed on *Hera*. I didn't run them anywhere else.

**Review by zhanglikate — APPROVED** [review]
I finished my testing for more than 84 hrs using the April 2 version global workflow, which is working well.

**Comment by SamuelTrahanNOAA** [comment]
I've merged develop. Those changes were all CICE, so they should not affect this PR's changes nor the bug people are encountering. Hence, I am *not* rerunning regression tests unless someone asks me to do that. Code managers will run regression tests in the ordinary testing process.

**Comment by BrianCurtis-NOAA** [comment]
> I've merged develop. Those changes were all CICE, so they should not affect this PR's changes nor the bug people are encountering. Hence, I am _not_ rerunning regression tests unless someone asks me to do that. Code managers will run regression tests in the ordinary testing process.

So everyone knows, the intention for the full RT suite being run is not to be re-done unless code changes related to the bug/feature being added/fixed are made. So merging with develop is not in that category and does not need to be rerun.

**Comment by SamuelTrahanNOAA** [comment]
I've retested my nested global case inside the global-workflow and it has passed the failure point. (I had already tested it outside the workflow.) This triad of fixes still work for me. I look forward to seeing them in the develop branch.

**Comment by jkbk2004** [comment]
We are going to start working on this pr today. @FernandoAndrade-NOAA @BrianCurtis-NOAA FYI

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Comment by SamuelTrahanNOAA** [comment]
Jet hasn't finished. Did something go wrong over there?

I've had lots of little technical issues while running on Jet since the Rocky upgrade.

**Comment by FernandoAndrade-NOAA** [comment]
> Jet hasn't finished. Did something go wrong over there?
> 
> I've had lots of little technical issues while running on Jet since the Rocky upgrade.

It was just a little slow yesterday, it looks like it passed, I'll push it up shortly.

**Comment by zach1221** [comment]
We can proceed with the merging process. I'll follow up on the cubed-sphere

**Comment by SamuelTrahanNOAA** [comment]
The cubed-sphere PR has been merged. I updated the FV3 PR to point to the authoritative .gitmodules and cubed sphere.

You can proceed to merging the FV3 PR.

**Review by jkbk2004 — DISMISSED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA FV3 merged.. hash: https://github.com/NOAA-EMC/fv3atm/commit/37e7d4859db4eb75472091abc650831060037715

**Comment by SamuelTrahanNOAA** [comment]
I have reverted .gitmodules and pointed FV3 to the head of the authoritative develop branch.

This PR is ready for final review and merge.

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
