### PR TITLE
release/p8c: updated the TKE-EDMF PBL and saSAS cumulus scheme plus bug fix for the Thompson scheme (issue #881)

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [Yes ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. 

- [ Yes] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [Yes] An Issue describing the work contained in this PR has been created. 
        Please see issue #881

- [Yes] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.
       As described in issue #881. This PR updated the TKE-EDMF PBL scheme and the saSAS cumulus scheme. As a result, most of  RTs are changed and require new baseline. 

- [No] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR is for the subcomponents updates PR#882 for ccpp-physics and PR#503 for FV3

### Issue(s) addressed

Updated the TKE-EDMF PBL scheme and saSAS cumulus scheme

## Testing

Tested on Hera.intel. Many RTs are failed due to the changes of the PBL and cumulus scheme used in those PRs.
Please refer to the RT log file: /scratch1/NCEPDEV/hwrf/save/Chunxi.Zhang/PRs/RegressionTests_hera.intel.log

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NCAR/ccpp-physics/pull/#882
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/503

### CODE REVIEW

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA please bring these up to date with respective authoritative repositories
> 
> * ufs-weather-model **NOT** up to date

Updated ufs-weather-model

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/882544732/20220401100015/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20220329/INTEL
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/882544732/20220401160015/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220329/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by MinsukJi-NOAA** [comment]
@ChunxiZhang-NOAA please update the baseline date:
```
diff --git a/tests/rt.sh b/tests/rt.sh
index a4967b52..763d368c 100755
--- a/tests/rt.sh
+++ b/tests/rt.sh
@@ -485,7 +485,7 @@ if [[ $TESTS_FILE =~ '35d' ]] || [[ $TESTS_FILE =~ 'weekly' ]]; then
   TEST_35D=true
 fi
 
-BL_DATE=20220329
+BL_DATE=20220401
 if [[ $MACHINE_ID = hera.* ]] || [[ $MACHINE_ID = orion.* ]] || [[ $MACHINE_ID = cheyenne.* ]] || [[ $MACHINE_ID = gaea.* ]] || [[ $MACHINE_ID = jet.* ]] || [[ $MACHINE_ID = s4.* ]]; then
   RTPWD=${RTPWD:-$DISKNM/NEMSfv3gfs/develop-${BL_DATE}/${RT_COMPILER^^}}
 else
```

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA please update the baseline date:
> 
> ```
> diff --git a/tests/rt.sh b/tests/rt.sh
> index a4967b52..763d368c 100755
> --- a/tests/rt.sh
> +++ b/tests/rt.sh
> @@ -485,7 +485,7 @@ if [[ $TESTS_FILE =~ '35d' ]] || [[ $TESTS_FILE =~ 'weekly' ]]; then
>    TEST_35D=true
>  fi
>  
> -BL_DATE=20220329
> +BL_DATE=20220401
>  if [[ $MACHINE_ID = hera.* ]] || [[ $MACHINE_ID = orion.* ]] || [[ $MACHINE_ID = cheyenne.* ]] || [[ $MACHINE_ID = gaea.* ]] || [[ $MACHINE_ID = jet.* ]] || [[ $MACHINE_ID = s4.* ]]; then
>    RTPWD=${RTPWD:-$DISKNM/NEMSfv3gfs/develop-${BL_DATE}/${RT_COMPILER^^}}
>  else
> ```

@MinsukJi-NOAA BL_DATE has been updated to 20220401

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/882544732/20220401161517/ufs-weather-model
[BL] Error: Test compile_009 failed in run_compile failed 
Please make changes and add the following label back: jet-intel-BL

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by grantfirl** [comment]
@junwang-noaa Please let me know when you'd like to start the merge process.

**Comment by junwang-noaa** [comment]
@grantfirl All RT/CI are done, please commit CCPP physics PR #882. Thank you!

**Comment by grantfirl** [comment]
> @grantfirl All RT/CI are done, please commit CCPP physics PR #882. Thank you!

Done. @ChunxiZhang-NOAA https://github.com/NOAA-EMC/fv3atm/pull/503 is ready to update for merging.

**Comment by ChunxiZhang-NOAA** [comment]
> > @grantfirl All RT/CI are done, please commit CCPP physics PR #882. Thank you!
> 
> Done. @ChunxiZhang-NOAA [NOAA-EMC/fv3atm#503](https://github.com/NOAA-EMC/fv3atm/pull/503) is ready to update for merging.

.gitmodules under FV3 directory is updated.

**Comment by MinsukJi-NOAA** [comment]
@ChunxiZhang-NOAA. FV3 was committed. Please revert the fv3 submodule pointer in the ufs weather model.

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA. FV3 was committed. Please revert the fv3 submodule pointer in the ufs weather model.

@MinsukJi-NOAA  Done.

**Pull request merged**
