### PR TITLE
[production/RRFS.v1] Add clear-sky shortwave downward at surface flux to available diagnostics.

### PR DESCRIPTION
**Pull request by dustinswales**
## Description:
This PR adds a new diagnostic, instantaneous downward shortwave flux at the surface assuming clear-sky conditions.
This is needed for RRFSv1.

Analogous to #2248 into develop.

### Commit Message:
N/A

### Priority:
High: Time-sensitive project. Needed for RRFSv1.

### UFSWM:
N/A

### Sub component Pull Requests:
* [FV3: NOAA-EMC/fv3atm#825](https://github.com/NOAA-EMC/fv3atm/pull/825)
* [ccpp-physics: ufs-community/ccpp-physics#198](https://github.com/ufs-community/ccpp-physics/pull/198)

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.
* PR Updates/Changes Baselines.
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* None.

---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [x] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@dustinswales can you sync up branches? We will go ahead for testing.

**Comment by dustinswales** [comment]
@jkbk2004 Sorry, I was out Friday. All synced up now.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA This pr ran ok on hera and hercules. We can move on merging after the test on wcoss2.

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 Good to merge from my perspective.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Approving....

**Pull request merged**
