### PR TITLE
update mom6 to its main branch 20221112 commit, add ci test in fv3atm

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

need to update MOM6 to its main branch 20221112 commit (no BL change)
### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes UFS #1491 
- fixes MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/105

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/105
MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/106
If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jiandewang Please add the dependent PR information (the PR which you have open for MOM6)

**Comment by jiandewang** [comment]
> @jiandewang Please add the dependent PR information (the PR which you have open for MOM6)

added.

**Comment by jkbk2004** [comment]
@jiandewang there is a minor fv3atm pr [603](https://github.com/NOAA-EMC/fv3atm/pull/603). Can we combine fv3atm pr [603](https://github.com/NOAA-EMC/fv3atm/pull/603) to this pr? just need to use @dustinswales 's fv3atm branch and hash.

**Comment by jiandewang** [comment]
> @jiandewang there is a minor fv3atm pr [603](https://github.com/NOAA-EMC/fv3atm/pull/603). Can we combine fv3atm pr [603](https://github.com/NOAA-EMC/fv3atm/pull/603) to this pr? just need to use @dustinswales 's fv3atm branch and hash.

OK I will combine that later tonight and let you know (I am not at home at this moment)

**Comment by jiandewang** [comment]
I just did the submodule switch, @dustinswales can you double check on my change ?

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1121965890/20221118214505/ufs-weather-model
[RT] Error: Test compile_011 failed in run_compile failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 looks like you have everything tested for merge. I will skip Acorn due to NCO running tests on Acorn and asking me to stop my acorn run last week for this PR.

**Comment by jiandewang** [comment]
@DeniseWorthen @JessicaMeixner-NOAA can you check https://github.com/NOAA-EMC/MOM6/pull/106 ?

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang checking now

**Comment by jiandewang** [comment]
@jkbk2004 I am going to merging MOM6 and revert its submodule, do we need review for fv3atm from someone ?

**Comment by jkbk2004** [comment]
> @jkbk2004 I am going to merging MOM6 and revert its submodule, do we need review for fv3atm from someone ?

Sure! I asked @dustinswales to revert ccpp branch and update ccpp hash on fv3atm pr.

**Comment by jiandewang** [comment]
@jkbk2004 MOM6 submodule has been reverted to dev/emc

**Comment by jkbk2004** [comment]
@jiandewang can you update fv3atm hash and revert branch?

**Comment by jiandewang** [comment]
> @jiandewang can you update fv3atm hash and revert branch?

so Dustin has merged fv3atm to main branch ? what's the right hash # it should be ?

**Comment by jkbk2004** [comment]
> > @jiandewang can you update fv3atm hash and revert branch?
> 
> so Dustin has merged fv3atm to main branch ? what's the right hash # it should be ?

It's https://github.com/NOAA-EMC/fv3atm/commit/f7651747cc61b2d7faa7eca3e1b9a1cdbfca9653

**Review by binli2337 — APPROVED** [review]
Looks good.

**Comment by jiandewang** [comment]
> > > @jiandewang can you update fv3atm hash and revert branch?
> > 
> > 
> > so Dustin has merged fv3atm to main branch ? what's the right hash # it should be ?
> 
> It's [NOAA-EMC/fv3atm@f765174](https://github.com/NOAA-EMC/fv3atm/commit/f7651747cc61b2d7faa7eca3e1b9a1cdbfca9653)

fv3atm pointing to develop branch now

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
