### PR TITLE
RRFS debug & 2threads variants fixed plus many boundary condition bugs

### LINKED ISSUE #5: module_sf_ruclsm imprecision breaks gfortran in debug mode for RRFS tests
# Description

The module_sf_ruclsm has comparisons to zero, which break the code when numbers are very close to 0, such as 1e-322. This happens with the gfortran compiler when compled -DDEBUG=ON since the option to truncate subnormal numbers is turned off.

## Steps to Reproduce

1. Fix bugs in the fv_regional_bc.F90 that prevent RRFS from running in DEBUG=ON mode
2. Run one of the RRFS tests in DEBUG=ON mode with the gnu compiler on Hera
3. View the resulting core dumps using gdb
4. Sadness

## Additional Context

The model will fail much earlier, due to known bugs. I'm about to submit a PR and some issues to fix that.

### LINKED ISSUE #218: uninitialized or incorrectly initialized memory in fv_regional_bc.F90
**Describe the bug**

The ps_reg variable in fv_regional_bc.F90 is initialized to -9999999 Pa, which propagates throughout the model. All other boundary arrays were initialized to signalling NaN. Not initializing this one to signalling NaN masked many other bugs. 

These are some of the bugs it masked inside the GFDL_atmos_cubed_sphere repository; there are others outside it:

1. Remapping winds does a two point average of the current point and -9999999.
2. Remapping winds uses -9999999 as pressure on velocity boundary points beyond the scalar boundary points.
3. The -9999999 is copied to Atm%ps throughout the domain, beyond the boundary, on all processors that touch the domain boundary.
4. Due to item 3, the RRFS hasn't been able to run in DEBUG=ON mode since this bug was introduced.
5. The pressure data is not read in on velocity points outside the scalar boundary.  (It can't be, since the the boundary condition files lack that data entirely.)
6. The blending code blends data beyond boundary regions.
7. The code accesses i-1 and j-1 indices, but processes the south boundary before the east and west boundary. That means two south boundary processes are accessing uninitialized regions instead of the east and west boundary.

There are other issues, outside the dynamical core, which were masked by this bug. I'll link to those issues once I create or find them.

- https://github.com/ufs-community/ufs-weather-model/issues/1222
- https://github.com/ufs-community/ufs-weather-model/issues/1436
- https://github.com/ufs-community/ccpp-physics/issues/5
- https://github.com/NOAA-EMC/fv3atm/issues/586

It should also be noted that many users have found dubious values the model receives from the boundary conditions. These bugs may be the cause. However, we'll have to run parallels of multiple configurations to confirm that.

**To Reproduce**

1. Read the code and find the ps_reg=-9999999
2. Replace that with ps_reg=real_snan
3. Compile in DEBUG=ON mode.
4. Run it and see the bugs.
6. Fix the bugs one by one and see more appear.

**Expected behavior**

1. Boundary data should be correct.
2. The boundary code should not write to non-boundary regions within the domain.
3. Blending code should not blend data beyond the domain boundary.
4. The best practice of initializing to real_snan should be followed.
5. The code should pass in DEBUG=ON
8. Changing the threads, layout, or task count, should not change the results.

**System Environment**
The ufs-weather-model build system targets hera.intel and hera.gnu, which use:

- OS: CentOS 7.9.2009
- Compiler(s): Intel 2022.1.2 and GCC 9.2.0
- MPI type, and version: Intel MPI using the SLURM srun launcher
- netCDF Version: 4.7.4
- Configure options: cmake option "-DDEBUG=ON"

**Additional context**
None.

### LINKED ISSUE #1436: Regional boundary data lacks pressure on non-scalar velocity points
## Description

~~The fv_regional_bc.F90 requires surface pressure on all velocity points for wind remapping. Velocity boundary points go beyond scalar boundary points, and the surface pressure is only available on scalar boundary points.  Surface pressure must extend beyond velocity points, to i-1 and j-1 locations relative to velocity points. That means the surface pressure boundary regions must be larger than they are now, by 2. We also need the surface pressure "boundary region" to include one point within the domain. I don't know where this issue originates, but I know it is a problem in the regression test input data.~~

The code should only be reading surface pressures in regions where it already has that data. Reading outside those regions is a bug; the extent of the boundary is not at fault.

*Edit Sep 27*: Surface pressure is needed beyond velocity points.
*Edit Oct 3*: Needing surface pressure beyond those points was a bug.

### To Reproduce:

Read the files, OR initialize ps_reg to real_snan to fv_regional_bc.F90. Eventually, after fixing a series of other bugs, you'll encounter invalid surface pressure data on velocity points.

## Additional context

FIXME: Link to other issues and PRs

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/218
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/220

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This fixes many bugs in the fv_regional_bc.F90, and adds workarounds for two issues that couldn't be fixed. Also, the module_sf_ruclsm had two variables with troubles during gfortran debug mode, because subnormal number truncation was disabled. This is expected to improve some of the boundary issues seen in RRFS runs, and will be incorporated into RRFS parallels as soon as possible.

The result is that the RRFS can run in debug mode, and the 2threads variant matches the control and are now enabled in the conf files. Sadly, the restart and decomp do not match the control; they're in the tests/tests directory, but are commented out in the conf files. All rrfs conus13km tests all have a timestep of 120s now, instead of 60s, which should slightly offset the cost of having more of them. 

RRFS-Smoke fails all variants, and crashes during restart, for known reasons. This is being fixed in the RRFS_dev branch (NOAA-GSL fork) which has a much newer and improved RRFS-Smoke. Fixing problems in the much older version in ufs-community would take more labor than is available, so those fixes will come in when the RRFS changes are merged to the authoritative repositories. Syncing the repositories is a high priority for RRFS developers.

All tests that have regional boundary conditions or use the RUC LSM may change results.

## (Partially) Incorporated PRs

Pull request #1431, which corrected Rocoto support, was used during testing, so that is merged into this PR.

The GFDL_atmos_cubed_sphere changes for #1158 have already been merged to dev/emc, so they're in this PR's dependency at that level (https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219). However, the rest of that PR has NOT been combined into this one. This doesn't seem to have had any impact on the regression tests. That is expected because #1158 did not change any actual code in GFDL_atmos_cubed_sphere. The meat of that PR is elsewhere.

The GFDL_atmos_cubed_sphere PR https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/220 from @kaiyuan-cheng is included, which fixes most of the issues mentioned here in a simpler manner than my own fixes.

### Issue(s) addressed

Fixes https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/218
Fixes https://github.com/ufs-community/ccpp-physics/issues/5
Fixes https://github.com/ufs-community/ufs-weather-model/issues/1436

This solves half of the problem described in https://github.com/ufs-community/ufs-weather-model/issues/1222. Do NOT close that issue. The other half, the decomp and restart variants, do not work yet. 

These are newly-discovered bugs, for which this PR adds workarounds. The bugs should be fixed, and the workarounds removed:

workaround for https://github.com/NOAA-EMC/fv3atm/issues/586 (Do NOT close that issue.)

## Testing

All regression tests in rt.conf and rt_gnu.conf pass on hera.gnu, jet.intel, and hera.intel. 

Some test variants that fail are commented out, but I kept them in tests/tests for debugging purposes. Specifically, these are the decomp and restart variants. The conus13km tests are all warm starts from data assimilation system output, so their restart tests require an extra variable. All extra logic needed to run a restart is present in the disabled conus13km files.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219
https://github.com/NOAA-EMC/fv3atm/pull/587
https://github.com/ufs-community/ccpp-physics/pull/6

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
This PR is going into the RRFS parallels as an emergency fix. The parallels run out of the RRFS_dev branch in the NOAA-GSL fork, and that emergency PR is here:

https://github.com/NOAA-GSL/ufs-weather-model/pull/150

Regression testing in that PR is complete, and it is ready for merge once it is reviewed. We need more reviews of the GFDL_atmos_cubed_sphere (boundary condition) changes.

If you have knowledge of the regional boundary condition code, please review the authoritative repo PR for that:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219

The corresponding emergency PR for the GFDL_atmos_cubed_sphere is here:

https://github.com/NOAA-GSL/GFDL_atmos_cubed_sphere/pull/12

and it only differs in the destination of the PR, which is identical to an older hash of GFDL_atmos_cubed_sphere dev/emc. Hopefully, mixing versions won't cause any problems.

**Comment by SamuelTrahanNOAA** [comment]
Nothing in this PR should affect threading, so the 2threads cases were probably fixed by an earlier PR. I haven't had a chance to confirm that or track down what fixed it.  My priority is the boundary condition bug fixes detected by debug mode.  However, once this PR is merged, we'll have regression tests to ensure the RRFS 2threads and debug variants don't fail again.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 I'd like to delay this PR until https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219 has been properly reviewed. Could you please reschedule this PR to next week?

*Edit*: I meant to put this comment in the GFDL_atmos_cubed_sphere PR https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219. I just copied it there.

**Comment by jkbk2004** [comment]
> @jkbk2004 I'd like to delay this PR until [NOAA-GFDL/GFDL_atmos_cubed_sphere#219](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219) has been properly reviewed. Could you please reschedule this PR to next week?
> 
> _Edit_: I meant to put this comment in the GFDL_atmos_cubed_sphere PR [NOAA-GFDL/GFDL_atmos_cubed_sphere#219](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219). I just copied it there.

I will update with new commit date.

**Comment by BrianCurtis-NOAA** [comment]
This PR is on the top of the commit queue. I see that the ccpp-physics PR is approved by three people already, and the fv3atm PR is just a holder for the ccp-physics and atmos-cubed changes. So we should wait on code approvals from atmos_cubed_sphere reviewers before proceeding with testing here.

**Comment by SamuelTrahanNOAA** [comment]
@BrianCurtis-NOAA Yes, I am waiting for re-review of that PR (https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219). It had major issues which @kaiyuan-cheng has since fixed in a PR to another branch (https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/220). I adapted the fixes to dev/emc. There are two fresh requests for review, so hopefully I'll hear back soon.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA I delayed the commit date of this pr to Friday (Oct 7).

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA We have open commit schedule today. If no need to rush for this PR, we can reschedule this PR to next Wednesday (Oct 12) to give enough time. On the other hand, we can use time to work on some ccpp PRs.

**Comment by SamuelTrahanNOAA** [comment]
I think we should go ahead with testing. We can't wait too much longer, or another commit will break RRFS restart or 2threads support, especially if the commit is in CCPP. At this point, I think anyone who is going to review the PR has done so. I'm certain the fixes are correct; it's just a question of whether there are better ones, and it may take any amount of time for someone to invent a better fix (if there is one).

**Comment by jkbk2004** [comment]
> I think we should go ahead with testing. We can't wait too much longer, or another commit will break RRFS restart or 2threads support, especially if the commit is in CCPP. At this point, I think anyone who is going to review the PR has done so. I'm certain the fixes are correct; it's just a question of whether there are better ones, and it may take any amount of time for someone to invent a better fix (if there is one).

Thanks! Let's start testing today. I will add baseline change label now.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA it seems your branches are forked from ncar institutional fork: ufs-wm, fv3atm. Can you make sure all sync up? #1431 was already combined in this PR. So that we can start working on this PR. Do we expect baseline changes only on rrfs or other regional cases as well including hrrr, rap ?

**Comment by SamuelTrahanNOAA** [comment]
The branches for this PR and its descendants are now up to date with the authoritative branches. My choice of origin for my fork does not matter in any way whatsoever; all that matters is the starting point for my branch, which was the authoritative branches.

I just deleted all upstream branches from my ufs-weather-model fork to avoid any further confusion (develop, dtc/develop, and gsl-related ones). This, too, does not affect anything at all, since I always start from the branches in the authoritative repository via the arcane secrets of multiple remotes.

**Comment by SamuelTrahanNOAA** [comment]
> Do we expect baseline changes only on rrfs or other regional cases as well including hrrr, rap ?

Anything that has boundary conditions is expected to change results due to the fv_regional_bc.F90 bug fixes. Configurations that use RUC LSM might change results due to the lsm_ruc.F90 imprecision fix. (They'd need to have snow depth >0 and <1e-20 on at least one point.)

**Comment by jkbk2004** [comment]
Thanks @SamuelTrahanNOAA ! I will add new BL_DATE.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA we are considering to update stochastic_physics git migration to this PR as well: #1447

**Comment by SamuelTrahanNOAA** [comment]
> we are considering to update stochastic_physics git migration to this PR as well: https://github.com/ufs-community/ufs-weather-model/pull/1447

I will need to confirm this does not break RRFS debug or 2threads mode. I don't expect it will, but I want to confirm.

**Comment by SamuelTrahanNOAA** [comment]
> I will need to confirm this does not break RRFS debug or 2threads mode. I don't expect it will, but I want to confirm.

I have merged #1447 and you can go ahead with testing. There is no way this could break anything; it only updates the URL, not the hash.

**Comment by jkbk2004** [comment]
> > I will need to confirm this does not break RRFS debug or 2threads mode. I don't expect it will, but I want to confirm.
> 
> I have merged #1447 and you can go ahead with testing. There is no way this could break anything; it only updates the URL, not the hash.

Thanks!

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 Please test cheyenne.gnu first. It is the fussiest platform, so it is the most likely to find any remaining RRFS debug issues. The debug settings for gfortran with UFS disable subnormal number truncation, which breaks the logic of many physics schemes unless one is careful about treatment of near-zero numbers. I've tested for that elsewhere, but cheyenne.gnu has proven most useful at detecting issues in the past.

*Edit: It is specifically the gfortran debug settings in UFS that disable subnormal number truncation.*

**Comment by jkbk2004** [comment]
> @jkbk2004 Please test cheyenne.gnu first. It is the fussiest platform, so it is the most likely to find any remaining RRFS debug issues. The debug settings for gfortran with UFS disable subnormal number truncation, which breaks the logic of many physics schemes unless one is careful about treatment of near-zero numbers. I've tested for that elsewhere, but cheyenne.gnu has proven most useful at detecting issues in the past.
> 
> _Edit: It is specifically the gfortran debug settings in UFS that disable subnormal number truncation._

Yeah, I am logging into cheyenne. I will let hera.gnu run as well.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1064533473/20221012163011/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20221007/GNU
Please make changes and add the following label back: hera-gnu-BL

**Comment by jkbk2004** [comment]
Oops! I am adding new BL_DATE.

**Comment by DusanJovic-NOAA** [comment]
> @jkbk2004 Please test cheyenne.gnu first. It is the fussiest platform, so it is the most likely to find any remaining RRFS debug issues. The debug settings for gfortran with UFS disable subnormal number truncation, which breaks the logic of many physics schemes unless one is careful about treatment of near-zero numbers. I've tested for that elsewhere, but cheyenne.gnu has proven most useful at detecting issues in the past.
> 
> _Edit: It is specifically the gfortran debug settings in UFS that disable subnormal number truncation._

Which gfortran debug settings in UFS specifically disable subnormal number truncation?

**Comment by SamuelTrahanNOAA** [comment]
> Which gfortran debug settings in UFS specifically disable subnormal number truncation?

It comes in the vast swath of options enabled by `-O2`. I've skimmed the manpage and I cannot find the specific option that enables it.

**Comment by DusanJovic-NOAA** [comment]
> > Which gfortran debug settings in UFS specifically disable subnormal number truncation?
> 
> It comes in the vast swath of options enabled by `-O2`. I've skimmed the manpage and I cannot find the specific option that enables it.

So you are saying subnormal number truncation is enabled by -O2 in gfortran. Are you sure?

**Comment by SamuelTrahanNOAA** [comment]
> So you are saying subnormal number truncation is enabled by -O2 in gfortran. Are you sure?

The errors I saw in RUC LSM were due to subnormal numbers, which are zero with `-O2`. That is a bug in RUC LSM, not an issue with optimization because physics scheme shouldn't assume that very small snow heights will be identically zero. This is especially problematic with x86-64 since scalar floating-point operations are 80 bit. Either you should compare to zero with an epsilon, or truncate explicitly.  I went with the later fix since it is more concise.

My concern in the widespread tests of RRFS in debug mode is that other platforms will have numerical issues elsewhere in the code, and I'll need some more fixes. We shall know soon.

**Comment by DusanJovic-NOAA** [comment]
Ok. I just want to make sure we are not using a setting in the debug mode that is responsible for breaking many physics schemes. If the reason they are broken is in the logic of the algorithm then that's a different issue.

**Comment by SamuelTrahanNOAA** [comment]
> Ok. I just want to make sure we are not using a setting in the debug mode that is responsible for breaking many physics schemes. If the reason they are broken is in the logic of the algorithm then that's a different issue.

That is my hope. At this point, I am so crunched for time for other projects that I'll be satisfied with successful regression tests.

**Comment by zach1221** [comment]
Jenkins-ci logs attached.
[ufs-weather-model » ort-docker-wrapper-pipeline » PR-1437 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9777692/ufs-weather-model.ort-docker-wrapper-pipeline.PR-1437.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA all tests are done. We can start merging in dependencies first.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA go ahead to update on fv3atm submodule pointer and revert the branch. and we can merge.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 The FV3 submodule hash and URL have been updated. This PR is ready for merge.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
