### PR TITLE
Add 'netcdf' and 'grib2' to input 'source' options in regional IC/LBC routines

### LINKED ISSUE #97: (dev/emc) Regional IC/LBC routines allows only gfs nemsio string as global attribute source (reopened)
- This is the same as #95, which was closed without merged.
- The regional IC/LBC routines allows only one source string "FV3GFS GAUSSIAN NEMSIO FILE" as the global attribute source of the input data even though other input types such as "FV3GFS GAUSSIAN NETCDF FILE" and "FV3GFS GRIB2 FILE" are available in chgres_cube.
- This restriction makes the LAM/LAM-DA experiments using netcdf and grib2 files for IC fail during initialization.
- Since the 'nemsio' format is not provided in the real-time data directory any more and it is replaced by 'netcdf', this part of the source string should be modified.

### LINKED ISSUE #281: Regional IC/LBC routines in atmos_cubed_sphere allow only 'nemsio' as global attribute 'source'
## Description
- The regional IC/LBC routines treat 'netcdf' and 'grib2' as the global attribute 'source' in input files differently from 'nemsio' though these three have the same logic in atmos_cubed_sphere.
- The global attribute 'source' is the output attribute of 'chgres_cube' and it has seven types. the other two names for 'netcdf' and 'grib2' need to be added to the regional IC/LBC routines in atmos_cubed_sphere.

## Dependency:
- NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/97

### LINKED ISSUE #523: Regional IC/LBC routines in atmos_cubed_sphere allow only 'nemsio' as global attribute 'source'
## Description
- The regional IC/LBC routines treat 'netcdf' and 'grib2' as the global attribute 'source' in input files differently from 'nemsio' though these three have the same logic in atmos_cubed_sphere.
- The global attribute 'source' is the output attribute of 'chgres_cube' and it has seven types. the other two names for 'netcdf' and 'grib2' need to be added to the regional IC/LBC routines in atmos_cubed_sphere.

## Dependency
- NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/97
- NOAA-EMC/fv3atm/issues/281

### PR DESCRIPTION
**Pull request by chan-hoo**
## Description
- Add 'netcdf' and 'grib2' to the input 'source' option in the regional IC/LBC routines of atmos_cubed_sphere.
- Since the logic of 'netcdf' or 'grib2' in the code is the same as that of 'nemsio', these three types are put in the same category.

## Issue(s) addressed
- fixes #523 
- fixes NOAA-EMC/fv3atm/issues/281
- fixes NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/97

## Testing
- Passed the regression test of the ufs weather model on WCOSS (dell/cray) and Hera with intel compiler.
- Completed a LAMDA test successfully with 'netcdf' input files from GFS.

Regression tests:
- [x] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies
- waiting on NOAA-EMC/fv3atm/pull/283
- waiting on NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/96

## Contributors
@JamesAbeles-NOAA, @EricRogers-NOAA

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@chan-hoo You PR is next in line. Can you please make sure your fv3atm and ufs-weather-model repositories are up to date with the latest develop branch?

**Comment by MinsukJi-NOAA** [comment]
@chan-hoo , please update the FV3 submodule in your ufs-weather-model branch as well

**Comment by DusanJovic-NOAA** [comment]
fv3atm branch https://github.com/chan-hoo/fv3atm/tree/feature/ic_netcdf is not up to date with upstream

**Comment by chan-hoo** [comment]
@DusanJovic-NOAA @MinsukJi-NOAA , due to a critical technical issue, I'll close this PR and re-open it.

**Pull request closed without merging**
