### PR TITLE
MYNN-EDMF, MYNN surface layer, and Thompson AA updates (combines 1940)

### PR DESCRIPTION
**Pull request by joeolson42**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
The following PR consists of updates to 3 schemes and related modules:

1. MYNN-EDMF
- optimization work: fixed 8-plume model instead of variable number plume. maintains performance
- bug fix to correct grid mean vs in-cloud mixing ratios. Now requires namelist variable lcnorm (set to true)
- adjustments to cloud pdf to better fit modified thompson scheme

2. MYNN surface layer
- tweak to Czil parameter to improve diurnal cycle of T and wsp.

3. Thompson aerosol-aware microphysics
- change to nucleation rates to fix marine drizzle problem
- minimum effective radii of 7 microns over water

### Subcomponent Pull Requests

- NOAA-EMC/fv3atm/pull/712
- ufs-community/ccpp-physics/pull/120

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA We found another trigger for this issue https://github.com/ufs-community/ccpp-physics/issues/114 in https://github.com/ufs-community/ccpp-physics/pull/120. We've narrowed down the exact line that causes a runtime (FPE exception) for the rrfs_v1beta_debug_intel test and it is only a proximate cause, not the ultimate cause, similar to how the problem showed up before, except now it is being triggered by a change in the PBL scheme instead of MP.

I suppose that we have a choice to merge as-is (assuming that the rest of the code changes are approved and pass expected tests) or add a simple bugfix as proposed in https://github.com/ufs-community/ccpp-physics/issues/114, just so the failing test will complete. Do you have a preference?

Once this is figured out, the plan is to test https://github.com/ufs-community/ccpp-physics/pull/120 and https://github.com/ufs-community/ccpp-physics/pull/116 separately to make sure that the appropriate tests are failing in each, then combine them for the queue.

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl If there's no priority for this PR (I can't recall if it was), then I see no problem adding a bugfix here. The `incomplete` label is a way we can tell what PR's have not finished the PR Author Checklist and/or are missing an attached logfile.

**Comment by grantfirl** [comment]
Any tests that use MYNN EDMF PBL, MYNN SFC, or Thompson MP should change results.

The following RTs are expected to fail due to changed BL:
053 control_p8_mynn_intel failed in check_result
control_p8_mynn_intel 053 failed in run_test
054 merra2_thompson_intel failed in check_result
merra2_thompson_intel 054 failed in run_test
055 regional_control_intel failed in check_result
regional_control_intel 055 failed in run_test
057 regional_control_qr_intel failed in check_result
regional_control_qr_intel 057 failed in run_test
059 regional_decomp_intel failed in check_result
regional_decomp_intel 059 failed in run_test
060 regional_2threads_intel failed in check_result
regional_2threads_intel 060 failed in run_test
061 regional_noquilt_intel failed in check_result
regional_noquilt_intel 061 failed in run_test
062 regional_netcdf_parallel_intel failed in check_result
regional_netcdf_parallel_intel 062 failed in run_test
063 regional_2dwrtdecomp_intel failed in check_result
regional_2dwrtdecomp_intel 063 failed in run_test
064 regional_wofs_intel failed in check_result
regional_wofs_intel 064 failed in run_test
065 rap_control_intel failed in check_result
rap_control_intel 065 failed in run_test
066 regional_spp_sppt_shum_skeb_intel failed in check_result
regional_spp_sppt_shum_skeb_intel 066 failed in run_test
067 rap_decomp_intel failed in check_result
rap_decomp_intel 067 failed in run_test
068 rap_2threads_intel failed in check_result
rap_2threads_intel 068 failed in run_test
070 rap_sfcdiff_intel failed in check_result
rap_sfcdiff_intel 070 failed in run_test
071 rap_sfcdiff_decomp_intel failed in check_result
rap_sfcdiff_decomp_intel 071 failed in run_test
073 hrrr_control_intel failed in check_result
hrrr_control_intel 073 failed in run_test
074 hrrr_control_qr_intel failed in check_result
hrrr_control_qr_intel 074 failed in run_test
075 hrrr_control_decomp_intel failed in check_result
hrrr_control_decomp_intel 075 failed in run_test
076 hrrr_control_2threads_intel failed in check_result
hrrr_control_2threads_intel 076 failed in run_test
079 rrfs_v1beta_intel failed in check_result
rrfs_v1beta_intel 079 failed in run_test
080 rrfs_v1nssl_intel failed in check_result
rrfs_v1nssl_intel 080 failed in run_test
081 rrfs_v1nssl_nohailnoccn_intel failed in check_result
rrfs_v1nssl_nohailnoccn_intel 081 failed in run_test
087 regional_control_faster_intel failed in check_result
regional_control_faster_intel 087 failed in run_test
097 regional_debug_intel failed in check_result
regional_debug_intel 097 failed in run_test
098 rap_control_debug_intel failed in check_result
rap_control_debug_intel 098 failed in run_test
099 hrrr_control_debug_intel failed in check_result
hrrr_control_debug_intel 099 failed in run_test
100 hrrr_gf_debug_intel failed in check_result
hrrr_gf_debug_intel 100 failed in run_test
101 hrrr_c3_debug_intel failed in check_result
hrrr_c3_debug_intel 101 failed in run_test
102 rap_unified_drag_suite_debug_intel failed in check_result
rap_unified_drag_suite_debug_intel 102 failed in run_test
103 rap_diag_debug_intel failed in check_result
rap_diag_debug_intel 103 failed in run_test
104 rap_cires_ugwp_debug_intel failed in check_result
rap_cires_ugwp_debug_intel 104 failed in run_test
105 rap_unified_ugwp_debug_intel failed in check_result
rap_unified_ugwp_debug_intel 105 failed in run_test
106 rap_lndp_debug_intel failed in check_result
rap_lndp_debug_intel 106 failed in run_test
107 rap_progcld_thompson_debug_intel failed in check_result
rap_progcld_thompson_debug_intel 107 failed in run_test
108 rap_noah_debug_intel failed in check_result
rap_noah_debug_intel 108 failed in run_test
109 rap_sfcdiff_debug_intel failed in check_result
rap_sfcdiff_debug_intel 109 failed in run_test
110 rap_noah_sfcdiff_cires_ugwp_debug_intel failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug_intel 110 failed in run_test
111 rrfs_v1beta_debug_intel failed in check_result
rrfs_v1beta_debug_intel 111 failed in run_test
112 rap_clm_lake_debug_intel failed in check_result
rap_clm_lake_debug_intel 112 failed in run_test
113 rap_flake_debug_intel failed in check_result
rap_flake_debug_intel 113 failed in run_test
115 regional_spp_sppt_shum_skeb_dyn32_phy32_intel failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32_intel 115 failed in run_test
116 rap_control_dyn32_phy32_intel failed in check_result
rap_control_dyn32_phy32_intel 116 failed in run_test
117 hrrr_control_dyn32_phy32_intel failed in check_result
hrrr_control_dyn32_phy32_intel 117 failed in run_test
118 hrrr_control_qr_dyn32_phy32_intel failed in check_result
hrrr_control_qr_dyn32_phy32_intel 118 failed in run_test
119 rap_2threads_dyn32_phy32_intel failed in check_result
rap_2threads_dyn32_phy32_intel 119 failed in run_test
120 hrrr_control_2threads_dyn32_phy32_intel failed in check_result
hrrr_control_2threads_dyn32_phy32_intel 120 failed in run_test
121 hrrr_control_decomp_dyn32_phy32_intel failed in check_result
hrrr_control_decomp_dyn32_phy32_intel 121 failed in run_test
125 conus13km_control_intel failed in check_result
conus13km_control_intel 125 failed in run_test
128 rap_control_dyn64_phy32_intel failed in check_result
rap_control_dyn64_phy32_intel 128 failed in run_test
129 rap_control_debug_dyn32_phy32_intel failed in check_result
rap_control_debug_dyn32_phy32_intel 129 failed in run_test
130 hrrr_control_debug_dyn32_phy32_intel failed in check_result
hrrr_control_debug_dyn32_phy32_intel 130 failed in run_test
131 conus13km_debug_intel failed in check_result
conus13km_debug_intel 131 failed in run_test
132 conus13km_debug_qr_intel failed in check_result
conus13km_debug_qr_intel 132 failed in run_test
133 conus13km_debug_2threads_intel failed in check_result
conus13km_debug_2threads_intel 133 failed in run_test
134 conus13km_radar_tten_debug_intel failed in check_result
conus13km_radar_tten_debug_intel 134 failed in run_test
135 rap_control_dyn64_phy32_debug_intel failed in check_result
rap_control_dyn64_phy32_debug_intel 135 failed in run_test
180 atmaero_control_p8_rad_micro_intel failed in check_result
atmaero_control_p8_rad_micro_intel 180 failed in run_test
190 rap_control_gnu failed in check_result
rap_control_gnu 190 failed in run_test
191 rap_decomp_gnu failed in check_result
rap_decomp_gnu 191 failed in run_test
192 rap_2threads_gnu failed in check_result
rap_2threads_gnu 192 failed in run_test
194 rap_sfcdiff_gnu failed in check_result
rap_sfcdiff_gnu 194 failed in run_test
195 rap_sfcdiff_decomp_gnu failed in check_result
rap_sfcdiff_decomp_gnu 195 failed in run_test
197 hrrr_control_gnu failed in check_result
hrrr_control_gnu 197 failed in run_test
198 hrrr_control_qr_gnu failed in check_result
hrrr_control_qr_gnu 198 failed in run_test
199 hrrr_control_2threads_gnu failed in check_result
hrrr_control_2threads_gnu 199 failed in run_test
200 hrrr_control_decomp_gnu failed in check_result
hrrr_control_decomp_gnu 200 failed in run_test
203 rrfs_v1beta_gnu failed in check_result
rrfs_v1beta_gnu 203 failed in run_test
205 regional_debug_gnu failed in check_result
regional_debug_gnu 205 failed in run_test
206 rap_control_debug_gnu failed in check_result
rap_control_debug_gnu 206 failed in run_test
207 hrrr_control_debug_gnu failed in check_result
hrrr_control_debug_gnu 207 failed in run_test
208 hrrr_gf_debug_gnu failed in check_result
hrrr_gf_debug_gnu 208 failed in run_test
209 hrrr_c3_debug_gnu failed in check_result
hrrr_c3_debug_gnu 209 failed in run_test
210 rap_diag_debug_gnu failed in check_result
rap_diag_debug_gnu 210 failed in run_test
211 rap_noah_sfcdiff_cires_ugwp_debug_gnu failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug_gnu 211 failed in run_test
212 rap_progcld_thompson_debug_gnu failed in check_result
rap_progcld_thompson_debug_gnu 212 failed in run_test
213 rrfs_v1beta_debug_gnu failed in check_result
rrfs_v1beta_debug_gnu 213 failed in run_test
217 rap_flake_debug_gnu failed in check_result
rap_flake_debug_gnu 217 failed in run_test
218 rap_clm_lake_debug_gnu failed in check_result
rap_clm_lake_debug_gnu 218 failed in run_test
220 rap_control_dyn32_phy32_gnu failed in check_result
rap_control_dyn32_phy32_gnu 220 failed in run_test
221 hrrr_control_dyn32_phy32_gnu failed in check_result
hrrr_control_dyn32_phy32_gnu 221 failed in run_test
222 hrrr_control_qr_dyn32_phy32_gnu failed in check_result
hrrr_control_qr_dyn32_phy32_gnu 222 failed in run_test
223 rap_2threads_dyn32_phy32_gnu failed in check_result
rap_2threads_dyn32_phy32_gnu 223 failed in run_test
224 hrrr_control_2threads_dyn32_phy32_gnu failed in check_result
hrrr_control_2threads_dyn32_phy32_gnu 224 failed in run_test
225 hrrr_control_decomp_dyn32_phy32_gnu failed in check_result
hrrr_control_decomp_dyn32_phy32_gnu 225 failed in run_test
229 conus13km_control_gnu failed in check_result
conus13km_control_gnu 229 failed in run_test
232 rap_control_dyn64_phy32_gnu failed in check_result
rap_control_dyn64_phy32_gnu 232 failed in run_test
233 rap_control_debug_dyn32_phy32_gnu failed in check_result
rap_control_debug_dyn32_phy32_gnu 233 failed in run_test
234 hrrr_control_debug_dyn32_phy32_gnu failed in check_result
hrrr_control_debug_dyn32_phy32_gnu 234 failed in run_test
235 conus13km_debug_gnu failed in check_result
conus13km_debug_gnu 235 failed in run_test
236 conus13km_debug_qr_gnu failed in check_result
conus13km_debug_qr_gnu 236 failed in run_test
237 conus13km_debug_2threads_gnu failed in check_result
conus13km_debug_2threads_gnu 237 failed in run_test
238 conus13km_radar_tten_debug_gnu failed in check_result
conus13km_radar_tten_debug_gnu 238 failed in run_test
239 rap_control_dyn64_phy32_debug_gnu failed in check_result
rap_control_dyn64_phy32_debug_gnu 239 failed in run_test

**Comment by grantfirl** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13313150/RegressionTests_hera.log)

**Comment by grantfirl** [comment]
After merging in #1940, all tests using RUC LSM should also change results. There is significant overlap with the previous MYNN changes.

063 rap_control_intel failed in check_result
rap_control_intel 063 failed in run_test
064 regional_spp_sppt_shum_skeb_intel failed in check_result
regional_spp_sppt_shum_skeb_intel 064 failed in run_test
065 rap_decomp_intel failed in check_result
rap_decomp_intel 065 failed in run_test
066 rap_2threads_intel failed in check_result
rap_2threads_intel 066 failed in run_test
068 rap_sfcdiff_intel failed in check_result
rap_sfcdiff_intel 068 failed in run_test
069 rap_sfcdiff_decomp_intel failed in check_result
rap_sfcdiff_decomp_intel 069 failed in run_test
071 hrrr_control_intel failed in check_result
hrrr_control_intel 071 failed in run_test
072 hrrr_control_decomp_intel failed in check_result
hrrr_control_decomp_intel 072 failed in run_test
073 hrrr_control_2threads_intel failed in check_result
hrrr_control_2threads_intel 073 failed in run_test
094 rap_control_debug_intel failed in check_result
rap_control_debug_intel 094 failed in run_test
095 hrrr_control_debug_intel failed in check_result
hrrr_control_debug_intel 095 failed in run_test
096 hrrr_gf_debug_intel failed in check_result
hrrr_gf_debug_intel 096 failed in run_test
097 hrrr_c3_debug_intel failed in check_result
hrrr_c3_debug_intel 097 failed in run_test
098 rap_unified_drag_suite_debug_intel failed in check_result
rap_unified_drag_suite_debug_intel 098 failed in run_test
099 rap_diag_debug_intel failed in check_result
rap_diag_debug_intel 099 failed in run_test
100 rap_cires_ugwp_debug_intel failed in check_result
rap_cires_ugwp_debug_intel 100 failed in run_test
101 rap_unified_ugwp_debug_intel failed in check_result
rap_unified_ugwp_debug_intel 101 failed in run_test
102 rap_lndp_debug_intel failed in check_result
rap_lndp_debug_intel 102 failed in run_test
103 rap_progcld_thompson_debug_intel failed in check_result
rap_progcld_thompson_debug_intel 103 failed in run_test
105 rap_sfcdiff_debug_intel failed in check_result
rap_sfcdiff_debug_intel 105 failed in run_test
108 rap_clm_lake_debug_intel failed in check_result
rap_clm_lake_debug_intel 108 failed in run_test
109 rap_flake_debug_intel failed in check_result
rap_flake_debug_intel 109 failed in run_test
111 regional_spp_sppt_shum_skeb_dyn32_phy32_intel failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32_intel 111 failed in run_test
112 rap_control_dyn32_phy32_intel failed in check_result
rap_control_dyn32_phy32_intel 112 failed in run_test
113 hrrr_control_dyn32_phy32_intel failed in check_result
hrrr_control_dyn32_phy32_intel 113 failed in run_test
114 rap_2threads_dyn32_phy32_intel failed in check_result
rap_2threads_dyn32_phy32_intel 114 failed in run_test
115 hrrr_control_2threads_dyn32_phy32_intel failed in check_result
hrrr_control_2threads_dyn32_phy32_intel 115 failed in run_test
116 hrrr_control_decomp_dyn32_phy32_intel failed in check_result
hrrr_control_decomp_dyn32_phy32_intel 116 failed in run_test
119 conus13km_control_intel failed in check_result
conus13km_control_intel 119 failed in run_test
122 rap_control_dyn64_phy32_intel failed in check_result
rap_control_dyn64_phy32_intel 122 failed in run_test
123 rap_control_debug_dyn32_phy32_intel failed in check_result
rap_control_debug_dyn32_phy32_intel 123 failed in run_test
124 hrrr_control_debug_dyn32_phy32_intel failed in check_result
hrrr_control_debug_dyn32_phy32_intel 124 failed in run_test
125 conus13km_debug_intel failed in check_result
conus13km_debug_intel 125 failed in run_test
126 conus13km_debug_qr_intel failed in check_result
conus13km_debug_qr_intel 126 failed in run_test
127 conus13km_debug_2threads_intel failed in check_result
conus13km_debug_2threads_intel 127 failed in run_test
128 conus13km_radar_tten_debug_intel failed in check_result
conus13km_radar_tten_debug_intel 128 failed in run_test
129 rap_control_dyn64_phy32_debug_intel failed in check_result
rap_control_dyn64_phy32_debug_intel 129 failed in run_test
180 rap_control_gnu failed in check_result
rap_control_gnu 180 failed in run_test
181 rap_decomp_gnu failed in check_result
rap_decomp_gnu 181 failed in run_test
182 rap_2threads_gnu failed in check_result
rap_2threads_gnu 182 failed in run_test
184 rap_sfcdiff_gnu failed in check_result
rap_sfcdiff_gnu 184 failed in run_test
185 rap_sfcdiff_decomp_gnu failed in check_result
rap_sfcdiff_decomp_gnu 185 failed in run_test
187 hrrr_control_gnu failed in check_result
hrrr_control_gnu 187 failed in run_test
188 hrrr_control_noqr_gnu failed in check_result
hrrr_control_noqr_gnu 188 failed in run_test
189 hrrr_control_2threads_gnu failed in check_result
hrrr_control_2threads_gnu 189 failed in run_test
190 hrrr_control_decomp_gnu failed in check_result
hrrr_control_decomp_gnu 190 failed in run_test
196 rap_control_debug_gnu failed in check_result
rap_control_debug_gnu 196 failed in run_test
197 hrrr_control_debug_gnu failed in check_result
hrrr_control_debug_gnu 197 failed in run_test
198 hrrr_gf_debug_gnu failed in check_result
hrrr_gf_debug_gnu 198 failed in run_test
199 hrrr_c3_debug_gnu failed in check_result
hrrr_c3_debug_gnu 199 failed in run_test
200 rap_diag_debug_gnu failed in check_result
rap_diag_debug_gnu 200 failed in run_test
202 rap_progcld_thompson_debug_gnu failed in check_result
rap_progcld_thompson_debug_gnu 202 failed in run_test
207 rap_flake_debug_gnu failed in check_result
rap_flake_debug_gnu 207 failed in run_test
208 rap_clm_lake_debug_gnu failed in check_result
rap_clm_lake_debug_gnu 208 failed in run_test
210 rap_control_dyn32_phy32_gnu failed in check_result
rap_control_dyn32_phy32_gnu 210 failed in run_test
211 hrrr_control_dyn32_phy32_gnu failed in check_result
hrrr_control_dyn32_phy32_gnu 211 failed in run_test
212 rap_2threads_dyn32_phy32_gnu failed in check_result
rap_2threads_dyn32_phy32_gnu 212 failed in run_test
213 hrrr_control_2threads_dyn32_phy32_gnu failed in check_result
hrrr_control_2threads_dyn32_phy32_gnu 213 failed in run_test
214 hrrr_control_decomp_dyn32_phy32_gnu failed in check_result
hrrr_control_decomp_dyn32_phy32_gnu 214 failed in run_test
217 conus13km_control_gnu failed in check_result
conus13km_control_gnu 217 failed in run_test
220 rap_control_dyn64_phy32_gnu failed in check_result
rap_control_dyn64_phy32_gnu 220 failed in run_test
221 rap_control_debug_dyn32_phy32_gnu failed in check_result
rap_control_debug_dyn32_phy32_gnu 221 failed in run_test
222 hrrr_control_debug_dyn32_phy32_gnu failed in check_result
hrrr_control_debug_dyn32_phy32_gnu 222 failed in run_test
223 conus13km_debug_gnu failed in check_result
conus13km_debug_gnu 223 failed in run_test
224 conus13km_debug_qr_gnu failed in check_result
conus13km_debug_qr_gnu 224 failed in run_test
225 conus13km_debug_2threads_gnu failed in check_result
conus13km_debug_2threads_gnu 225 failed in run_test
226 conus13km_radar_tten_debug_gnu failed in check_result
conus13km_radar_tten_debug_gnu 226 failed in run_test
227 rap_control_dyn64_phy32_debug_gnu failed in check_result
rap_control_dyn64_phy32_debug_gnu 227 failed in run_test

**Comment by grantfirl** [comment]
I'm running full RTs on Hera for the combined PR now. I'll post results when it is finished.

**Comment by grantfirl** [comment]
Combined PR RT log
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13369635/RegressionTests_hera.log)

Expected failures:
053 control_p8_mynn_intel failed in check_result
control_p8_mynn_intel 053 failed in run_test
054 merra2_thompson_intel failed in check_result
merra2_thompson_intel 054 failed in run_test
055 regional_control_intel failed in check_result
regional_control_intel 055 failed in run_test
057 regional_decomp_intel failed in check_result
regional_decomp_intel 057 failed in run_test
058 regional_2threads_intel failed in check_result
regional_2threads_intel 058 failed in run_test
059 regional_noquilt_intel failed in check_result
regional_noquilt_intel 059 failed in run_test
060 regional_netcdf_parallel_intel failed in check_result
regional_netcdf_parallel_intel 060 failed in run_test
061 regional_2dwrtdecomp_intel failed in check_result
regional_2dwrtdecomp_intel 061 failed in run_test
062 regional_wofs_intel failed in check_result
regional_wofs_intel 062 failed in run_test
063 rap_control_intel failed in check_result
rap_control_intel 063 failed in run_test
064 regional_spp_sppt_shum_skeb_intel failed in check_result
regional_spp_sppt_shum_skeb_intel 064 failed in run_test
065 rap_decomp_intel failed in check_result
rap_decomp_intel 065 failed in run_test
066 rap_2threads_intel failed in check_result
rap_2threads_intel 066 failed in run_test
068 rap_sfcdiff_intel failed in check_result
rap_sfcdiff_intel 068 failed in run_test
069 rap_sfcdiff_decomp_intel failed in check_result
rap_sfcdiff_decomp_intel 069 failed in run_test
071 hrrr_control_intel failed in check_result
hrrr_control_intel 071 failed in run_test
072 hrrr_control_decomp_intel failed in check_result
hrrr_control_decomp_intel 072 failed in run_test
073 hrrr_control_2threads_intel failed in check_result
hrrr_control_2threads_intel 073 failed in run_test
075 rrfs_v1beta_intel failed in check_result
rrfs_v1beta_intel 075 failed in run_test
076 rrfs_v1nssl_intel failed in check_result
rrfs_v1nssl_intel 076 failed in run_test
077 rrfs_v1nssl_nohailnoccn_intel failed in check_result
rrfs_v1nssl_nohailnoccn_intel 077 failed in run_test
083 regional_control_faster_intel failed in check_result
regional_control_faster_intel 083 failed in run_test
093 regional_debug_intel failed in check_result
regional_debug_intel 093 failed in run_test
094 rap_control_debug_intel failed in check_result
rap_control_debug_intel 094 failed in run_test
095 hrrr_control_debug_intel failed in check_result
hrrr_control_debug_intel 095 failed in run_test
096 hrrr_gf_debug_intel failed in check_result
hrrr_gf_debug_intel 096 failed in run_test
097 hrrr_c3_debug_intel failed in check_result
hrrr_c3_debug_intel 097 failed in run_test
098 rap_unified_drag_suite_debug_intel failed in check_result
rap_unified_drag_suite_debug_intel 098 failed in run_test
099 rap_diag_debug_intel failed in check_result
rap_diag_debug_intel 099 failed in run_test
100 rap_cires_ugwp_debug_intel failed in check_result
rap_cires_ugwp_debug_intel 100 failed in run_test
101 rap_unified_ugwp_debug_intel failed in check_result
rap_unified_ugwp_debug_intel 101 failed in run_test
102 rap_lndp_debug_intel failed in check_result
rap_lndp_debug_intel 102 failed in run_test
103 rap_progcld_thompson_debug_intel failed in check_result
rap_progcld_thompson_debug_intel 103 failed in run_test
104 rap_noah_debug_intel failed in check_result
rap_noah_debug_intel 104 failed in run_test
105 rap_sfcdiff_debug_intel failed in check_result
rap_sfcdiff_debug_intel 105 failed in run_test
106 rap_noah_sfcdiff_cires_ugwp_debug_intel failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug_intel 106 failed in run_test
107 rrfs_v1beta_debug_intel failed in check_result
rrfs_v1beta_debug_intel 107 failed in run_test
108 rap_clm_lake_debug_intel failed in check_result
rap_clm_lake_debug_intel 108 failed in run_test
109 rap_flake_debug_intel failed in check_result
rap_flake_debug_intel 109 failed in run_test
111 regional_spp_sppt_shum_skeb_dyn32_phy32_intel failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32_intel 111 failed in run_test
112 rap_control_dyn32_phy32_intel failed in check_result
rap_control_dyn32_phy32_intel 112 failed in run_test
113 hrrr_control_dyn32_phy32_intel failed in check_result
hrrr_control_dyn32_phy32_intel 113 failed in run_test
114 rap_2threads_dyn32_phy32_intel failed in check_result
rap_2threads_dyn32_phy32_intel 114 failed in run_test
115 hrrr_control_2threads_dyn32_phy32_intel failed in check_result
hrrr_control_2threads_dyn32_phy32_intel 115 failed in run_test
116 hrrr_control_decomp_dyn32_phy32_intel failed in check_result
hrrr_control_decomp_dyn32_phy32_intel 116 failed in run_test
119 conus13km_control_intel failed in check_result
conus13km_control_intel 119 failed in run_test
122 rap_control_dyn64_phy32_intel failed in check_result
rap_control_dyn64_phy32_intel 122 failed in run_test
123 rap_control_debug_dyn32_phy32_intel failed in check_result
rap_control_debug_dyn32_phy32_intel 123 failed in run_test
124 hrrr_control_debug_dyn32_phy32_intel failed in check_result
hrrr_control_debug_dyn32_phy32_intel 124 failed in run_test
125 conus13km_debug_intel failed in check_result
conus13km_debug_intel 125 failed in run_test
126 conus13km_debug_qr_intel failed in check_result
conus13km_debug_qr_intel 126 failed in run_test
127 conus13km_debug_2threads_intel failed in check_result
conus13km_debug_2threads_intel 127 failed in run_test
128 conus13km_radar_tten_debug_intel failed in check_result
conus13km_radar_tten_debug_intel 128 failed in run_test
129 rap_control_dyn64_phy32_debug_intel failed in check_result
rap_control_dyn64_phy32_debug_intel 129 failed in run_test
170 atmaero_control_p8_rad_micro_intel failed in check_result
atmaero_control_p8_rad_micro_intel 170 failed in run_test
180 rap_control_gnu failed in check_result
rap_control_gnu 180 failed in run_test
181 rap_decomp_gnu failed in check_result
rap_decomp_gnu 181 failed in run_test
182 rap_2threads_gnu failed in check_result
rap_2threads_gnu 182 failed in run_test
184 rap_sfcdiff_gnu failed in check_result
rap_sfcdiff_gnu 184 failed in run_test
185 rap_sfcdiff_decomp_gnu failed in check_result
rap_sfcdiff_decomp_gnu 185 failed in run_test
187 hrrr_control_gnu failed in check_result
hrrr_control_gnu 187 failed in run_test
188 hrrr_control_noqr_gnu failed in check_result
hrrr_control_noqr_gnu 188 failed in run_test
189 hrrr_control_2threads_gnu failed in check_result
hrrr_control_2threads_gnu 189 failed in run_test
190 hrrr_control_decomp_gnu failed in check_result
hrrr_control_decomp_gnu 190 failed in run_test
193 rrfs_v1beta_gnu failed in check_result
rrfs_v1beta_gnu 193 failed in run_test
195 regional_debug_gnu failed in check_result
regional_debug_gnu 195 failed in run_test
196 rap_control_debug_gnu failed in check_result
rap_control_debug_gnu 196 failed in run_test
197 hrrr_control_debug_gnu failed in check_result
hrrr_control_debug_gnu 197 failed in run_test
198 hrrr_gf_debug_gnu failed in check_result
hrrr_gf_debug_gnu 198 failed in run_test
199 hrrr_c3_debug_gnu failed in check_result
hrrr_c3_debug_gnu 199 failed in run_test
200 rap_diag_debug_gnu failed in check_result
rap_diag_debug_gnu 200 failed in run_test
201 rap_noah_sfcdiff_cires_ugwp_debug_gnu failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug_gnu 201 failed in run_test
202 rap_progcld_thompson_debug_gnu failed in check_result
rap_progcld_thompson_debug_gnu 202 failed in run_test
203 rrfs_v1beta_debug_gnu failed in check_result
rrfs_v1beta_debug_gnu 203 failed in run_test
207 rap_flake_debug_gnu failed in check_result
rap_flake_debug_gnu 207 failed in run_test
208 rap_clm_lake_debug_gnu failed in check_result
rap_clm_lake_debug_gnu 208 failed in run_test
210 rap_control_dyn32_phy32_gnu failed in check_result
rap_control_dyn32_phy32_gnu 210 failed in run_test
211 hrrr_control_dyn32_phy32_gnu failed in check_result
hrrr_control_dyn32_phy32_gnu 211 failed in run_test
212 rap_2threads_dyn32_phy32_gnu failed in check_result
rap_2threads_dyn32_phy32_gnu 212 failed in run_test
213 hrrr_control_2threads_dyn32_phy32_gnu failed in check_result
hrrr_control_2threads_dyn32_phy32_gnu 213 failed in run_test
214 hrrr_control_decomp_dyn32_phy32_gnu failed in check_result
hrrr_control_decomp_dyn32_phy32_gnu 214 failed in run_test
217 conus13km_control_gnu failed in check_result
conus13km_control_gnu 217 failed in run_test
220 rap_control_dyn64_phy32_gnu failed in check_result
rap_control_dyn64_phy32_gnu 220 failed in run_test
221 rap_control_debug_dyn32_phy32_gnu failed in check_result
rap_control_debug_dyn32_phy32_gnu 221 failed in run_test
222 hrrr_control_debug_dyn32_phy32_gnu failed in check_result
hrrr_control_debug_dyn32_phy32_gnu 222 failed in run_test
223 conus13km_debug_gnu failed in check_result
conus13km_debug_gnu 223 failed in run_test
224 conus13km_debug_qr_gnu failed in check_result
conus13km_debug_qr_gnu 224 failed in run_test
225 conus13km_debug_2threads_gnu failed in check_result
conus13km_debug_2threads_gnu 225 failed in run_test
226 conus13km_radar_tten_debug_gnu failed in check_result
conus13km_radar_tten_debug_gnu 226 failed in run_test
227 rap_control_dyn64_phy32_debug_gnu failed in check_result
rap_control_dyn64_phy32_debug_gnu 227 failed in run_test

**Comment by FernandoAndrade-NOAA** [comment]
Thanks for posting results and a log file for Hera @grantfirl. We'd like to begin testing on this PR next, @joeolson42 could you please resync all your branches and resolve conflicts?

**Comment by grantfirl** [comment]
> Thanks for posting results and a log file for Hera @grantfirl. We'd like to begin testing on this PR next, @joeolson42 could you please resync all your branches and resolve conflicts?

@joeolson42 @FernandoAndrade-NOAA Branches are all synced up now and ready for testing.

**Comment by grantfirl** [comment]
@joeolson42 I can't edit the PR description, so you might want to update the checkboxes that we're ready to go. It's probably not a big deal though since I pasted all the info in the comments. Also, maybe edit the PR title to mention updating RUC LSM.

**Comment by joeolson42** [comment]
@grantfirl done. checkboxes updated.

**Comment by DeniseWorthen** [comment]
@zach1221 please remove the incomplete label if this PR is actually complete.

**Comment by DeniseWorthen** [comment]
@FernandoAndrade-NOAA If this PR has been combined with another, please edit the title to indicate that.

**Comment by jkbk2004** [comment]
This PR is ready. Please, go ahead to review and approve.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
