### PR TITLE
Updates of ccpp-framework and ccpp-physics (merge ccpp-framework feature/capgen into main/20240308) Combined PR #2190

### PR DESCRIPTION
**Pull request by climbfuji**
## Commit Queue Requirements:
- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
    - done before and after the ccpp-physics discussion/code changes
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR updates the submodule pointer for the changes in fv3atm, ccpp-framework and ccpp-physics described in the associated PRs below: in ccpp-framework, merge feature/capgen into main; in ccpp-physics and fv3atm, use `flashes per minute` as the unit for lightning threat and then scale to `flashes per 5 minute` in the diagnostic output.

The ccpp-physics and fv3atm change leads to different answers for the `conus13km_*` regression tests (confirmed by @SamuelTrahanNOAA).

### Commit Message:
```
* UFSWM - 
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - Update submodule pointers for ccpp-framework and ccpp-physics. Change units flashes 5 min-1 to flashes min-1 and update long name to make clear this is per 5 minutes.
    * ccpp-physics - In physics/Interstitials/UFS_SCM_NEPTUNE/maximum_hourly_diagnostics.meta: change units flashes 5 min-1 to flashes min-1 and update long name to make clear this is per 5 minutes.
    * ccpp-framework - Update main from feature/capgen as of 2024-03-08 (includes optional argument updates in feature/capgen). Only commit on top of the merge is https://github.com/NCAR/ccpp-framework/commit/6cdd38a032d89d0f79c66f37f0c7172e59f135cd which is required to parse the metadata in the Unified Forecast System / ccpp-physics (underscores in units, e.g. degree_north).
    * atmos_cubed_sphere - 
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 - 
  * stochastic_physics - 
```

### Priority:

* Normal

### UFSWM:
This set of PRs is part of the broader issue of transitioning the CCPP Framework code generator from `ccpp_prebuild` to `capgen`. Specifically, this issue is required for https://github.com/NCAR/ccpp-framework/issues/540 which in turn is required to fix the `-check all` issues with unallocated arrays.

### Sub component Pull Requests:

* AQM:
* CDEPS:
* CICE:
* CMEPS:
* CMakeModules:
* FV3 - https://github.com/NOAA-EMC/fv3atm/pull/796
  * ccpp-physics - https://github.com/ufs-community/ccpp-physics/pull/182
  * ccpp-framework - https://github.com/NCAR/ccpp-framework/pull/546
  * atmos_cubed_sphere:
* GOCART:
* HYCOM:
* MOM6:
* NOAHMP:
* WW3:
* stochastic_physics:
* None

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* Baseline changes (thanks to @SamuelTrahanNOAA for retesting after the ccpp-physics discussion):
    * All conus13km tests fail, as expected:
```
[dheinzel@hercules-login-2 tests]$ cat fail_test_conus13km_*
conus13km_control_gnu failed in check_result
conus13km_control_gnu failed in run_test
conus13km_control_intel failed in check_result
conus13km_control_intel failed in run_test
conus13km_debug_2threads_gnu failed in check_result
conus13km_debug_2threads_gnu failed in run_test
conus13km_debug_2threads_intel failed in check_result
conus13km_debug_2threads_intel failed in run_test
conus13km_debug_gnu failed in check_result
conus13km_debug_gnu failed in run_test
conus13km_debug_intel failed in check_result
conus13km_debug_intel failed in run_test
conus13km_debug_qr_gnu failed in check_result
conus13km_debug_qr_gnu failed in run_test
conus13km_debug_qr_intel failed in check_result
conus13km_debug_qr_intel failed in run_test
conus13km_radar_tten_debug_gnu failed in check_result
conus13km_radar_tten_debug_gnu failed in run_test
conus13km_radar_tten_debug_intel failed in check_result
conus13km_radar_tten_debug_intel failed in run_test
```
    * Lightning threat differences are on the order of 1e-7 or less, indicating it all works.
    * All other tests passed.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
I suggest https://github.com/ufs-community/ccpp-physics/pull/182 be split to its own PR since it is expected to be answer-changing. All conus13km tests will change their lightning threat output by 1e-6 or so due to a unit conversion. This way, we can isolate any answer changes in *this* pull request with only capgen.

**Comment by climbfuji** [comment]
> I suggest [ufs-community/ccpp-physics#182](https://github.com/ufs-community/ccpp-physics/pull/182) be split to its own PR since it is expected to be answer-changing. All conus13km tests will change their lightning threat output by 1e-6 or so due to a unit conversion. This way, we can isolate any answer changes in _this_ pull request with only capgen.

There are no answer changes except the ones you identified. I ran the full regression test suite before adding your changes in and all results were b4b identical.

**Comment by climbfuji** [comment]
> > I suggest [ufs-community/ccpp-physics#182](https://github.com/ufs-community/ccpp-physics/pull/182) be split to its own PR since it is expected to be answer-changing. All conus13km tests will change their lightning threat output by 1e-6 or so due to a unit conversion. This way, we can isolate any answer changes in _this_ pull request with only capgen.
> 
> There are no answer changes except the ones you identified. I ran the full regression test suite before adding your changes in and all results were b4b identical.

In fact, in commit d8d13e21f564001df59db9e5c87e14289aa3737b (that is before adding your changes and updating the submodule pointers up to the top-level repository), I committed the file `test_changes.list` from my full RT run on Hercules, and it shows zero changes (it removes two lines of tests that had changing results in a previous PR). So that's all documented and we can safely add your ccpp-physics lightning thread changes on top, in my opinion.

**Comment by FernandoAndrade-NOAA** [comment]
Hi @climbfuji, PR #2180 was merged in and we'd like to get started on testing this PR. Please go ahead and sync up your branches / resolve any conflicts, thanks.

**Comment by FernandoAndrade-NOAA** [comment]
Please also verify any test changes in this PR by committing the updated test_changes.list file

**Comment by climbfuji** [comment]
> Please also verify any test changes in this PR by committing the updated test_changes.list file

I'll need to rerun the full regression tests for that again. Will do on Hercules.

**Comment by climbfuji** [comment]
> Please also verify any test changes in this PR by committing the updated test_changes.list file

All done, I committed the file and also updated the PR description.

**Comment by BrianCurtis-NOAA** [comment]
on WCOSS2 i'm still getting differences in lightning values
```
brian.curtis@clogin09:/lfs/h2/emc/nems/noscrub/brian.curtis/git/climbfuji/ufs-weather-model/tests> nccmp 
-d -S -q -f -B --Attribute=checksum --warn=format /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20240312/conus13km_control_intel/sfcf000.nc /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_198874/conus13km_control_intel/sfcf000.nc
Variable Group Count          Sum      AbsSum          Min          Max       Range         Mean     StdDev
ltg2_max /         5 -2.68221e-07 2.68221e-07 -5.96046e-08 -2.98023e-08 2.98023e-08 -5.36442e-08 1.3328e-08
ltg3_max /         5 -1.67638e-08 1.67638e-08 -3.72529e-09 -1.86265e-09 1.86265e-09 -3.35276e-09   8.33e-10
```
I'm curious if this shows up with RDHPCS machines, or maybe  messed up the baseline generation? I compared the baselines I generated with the ones in my baseline storage area and they were identical, though.

**Comment by BrianCurtis-NOAA** [comment]
Nevermind about that. I didn't bring in the bldate.conf change before testing. My bad. All looks good.

**Comment by BrianCurtis-NOAA** [comment]
Skipping Acorn as it's still down.

**Comment by zach1221** [comment]
@climbfuji fv3atm has merged now. 
hash: https://github.com/NOAA-EMC/fv3atm/commit/fae9bc25629b8518f416fcc333b57c128cf5c6b9

**Comment by climbfuji** [comment]
> @climbfuji fv3atm has merged now. hash: [NOAA-EMC/fv3atm@fae9bc2](https://github.com/NOAA-EMC/fv3atm/commit/fae9bc25629b8518f416fcc333b57c128cf5c6b9)

Updated, please check. Thanks!

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
