### PR TITLE
Add GFDL Land Model 4.0 

### PR DESCRIPTION
**Pull request by JustinPerket**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Introduces the GFDL Land Model version 4.0 (LM4.0) with NUOPC Driver.  Functional but not scientically valid for Data Atmosphere mode with CDEPS.

Adds these two nested submodules:

 * LM4-NUOPC driver - hosted at github.com/NOAA-GFDL/LM4-NUOPC-driver. NUOPC cap/driver for LM4
   * LM4.0 - submodule of LM4 NUOPC driver, hosted at https://github.com/NOAA-GFDL/LM4/

### Commit Message:

```
* UFSWM - Adds GFDL Land Model version 4 (LM4) as a component model, functional in Data Atmosphere mode
  * CMEPS - Small modifications for coupling of LM4
 * LM4-NUOPC driver - new model component hosted at github.com/NOAA-GFDL/LM4-NUOPC-driver. NUOPC Cap for LM4
   * LM4.0 - submodule of LM4 NUOPC driver, hosted at https://github.com/NOAA-GFDL/LM4/
 

```

### Priority:

* Normal

### UFSWM:

* No current Issue (TBD?)

### Sub component Pull Requests:

* CMEPS: https://github.com/NOAA-EMC/CMEPS/pull/113

New Sub components:

* LM4-NUOPC-driver: https://github.com/NOAA-GFDL/LM4-NUOPC-driver
  * LM 4.0 tag: https://github.com/NOAA-GFDL/lm4/releases/tag/land_lad2_2021.02

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.
 - adds CDEPS LM4 datm cold start and restart tests, `datm_cdeps_lm4_c96_gswp3` and `datm_cdeps_lm4_c96_gswp3_rst`
 - full description at https://github.com/NOAA-GFDL/LM4-NUOPC-driver/blob/develop/README.md
* PR should not affect existing Tests/Baselines.

### Input data Changes:

LM4 copies input data files from `@[INPUTDATA_LM4] ` , a temporary development variable for path to GFDL data. It is set in `rt.sh` for these machines:

- Gaea: `INPUTDATA_LM4=${INPUTDATA_LM4:-/gpfs/f5/gfdl/world-shared/cmip6/datasets/CM4/common}`
- Hera: ` INPUTDATA_LM4=${INPUTDATA_LM4:-/scratch2/GFDL/gfdlscr/Justin.Perket/cmip6/datasets/CM4/common}`
- Orion: `INPUTDATA_LM4=${INPUTDATA_LM4:-/work/noaa/gfdlscr/pdata/gfdl/cmip6/datasets/CM4/common}`

UFS's grid_spec.nc references aXl mosaic tile files that are required by LM4, but are not included in current UFS input paths.
Therefore in development, this untars `@[INPUTDATA_LM4]/c96_grid/c96_OM4_025_grid_No_mg_drag_v20160808.tar` for consistent grid_spec.nc and related files

Additionally, the following files are needed by LM4:

      @[INPUTDATA_LM4]/c96_LM4/c96_topo_rough_land.nc.tar
      @[INPUTDATA_LM4]/common_LM4/biodata.nc
      @[INPUTDATA_LM4]/common_LM4/cover_type.nc
      @[INPUTDATA_LM4]/common_LM4/geohydrology.nc
      @[INPUTDATA_LM4]/common_LM4/geohydrology_table_2a2n.nc 
      @[INPUTDATA_LM4]/common_LM4/ground_type.nc
      @[INPUTDATA_LM4]/common_LM4/landuse.nc
      @[INPUTDATA_LM4]/common_LM4/soil_brdf.nc
      @[INPUTDATA_LM4]/common_LM4/soil_type_hwsd_5minute.nc -> ./INPUT/soil_type.nc

### Library Changes/Upgrades:

For UFS-LM4 to be functional in Debug Mode, currently a Debug version of FMS is needed. https://github.com/JCSDA/spack-stack/issues/1288 addresses this.
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by JustinPerket** [comment]
After taking upstream updates, ran RTs on Gaea ( [a029179](https://github.com/ufs-community/ufs-weather-model/pull/2146/commits/a029179eeb7753e873b4d4932052835678f46e04)  and [fe9b122](https://github.com/ufs-community/ufs-weather-model/pull/2146/commits/fe9b122f797d48c731512a16e2ef010d05020bc1) ). All RTs passed, except for the new fire test cpld_regional_atm_fbh failed.

**Comment by JustinPerket** [comment]
> After taking upstream updates, ran RTs on Gaea ( [a029179](https://github.com/ufs-community/ufs-weather-model/pull/2146/commits/a029179eeb7753e873b4d4932052835678f46e04) and [fe9b122](https://github.com/ufs-community/ufs-weather-model/pull/2146/commits/fe9b122f797d48c731512a16e2ef010d05020bc1) ). All RTs passed, except for the new fire test cpld_regional_atm_fbh failed.

Now fixed. All RTs passing now.

**Comment by jkbk2004** [comment]
@JustinPerket can you keep syncing up branches? I like to do some pre-test runs to see if we can schedule to commit this pr.

**Comment by JustinPerket** [comment]
> @JustinPerket can you keep syncing up branches? I like to do some pre-test runs to see if we can schedule to commit this pr.

Ok, sure. I did that just now on temp branches. I just need to double check everything is good.

**Comment by JustinPerket** [comment]
@jkbk2004 . Ok, done. I'll try to keep it more in sync.

**Comment by jkbk2004** [comment]
@JustinPerket I am wondering if you can put new LM4 input C48 files somewhere on hera? I only see c96 files at /scratch2/GFDL/gfdlscr/Justin.Perket/cmip6/datasets/CM4/common. Also, we have an issue to access /gpfs/f5/gfdl/world-shared on gaea.  I created /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/INPUTDATA_LM4: c96_LM4 and c96_grid. I will add c48_LM4 and c48_grid once c48 files are available at hera or orion.

**Comment by JustinPerket** [comment]
My bad, The C48 test is not currently functional. I'll soon make a commit to remove it, and mentions of it.

Also the GFDL path in rt.sh has changed to:
`INPUTDATA_LM4=${INPUTDATA_LM4:-/gpfs/f5/gfdl_a/world-shared/cmip6/datasets/CM4/common}`.
I'll update the path in the PR text now.

**Comment by JustinPerket** [comment]
If we are at that point, Could the permanent path be something like `$INPUTDATA_ROOT/LM4_input_data` to match the other models' directory structure? The `$INPUTDATA_LM4` path was mean to be temporary until a more permanent home under `$INPUTDATA_ROOT` was created. 


When there is a permanent home under INPUTDATA, I can then cleanup `rt.sh` so that it would simply defined in the run section like WW3,  by (for example):

`INPUTDATA_ROOT_LM4=${INPUTDATA_ROOT}/LM4_input_data`


Also,`$INPUTDATA_LM4`  has a lot of other GFDL data that is not needed by LM4, especially running only for now with data atmosphere. So I created temporary directories on Hera and gaea that have just the data needed to be copied to the epic input data paths:
```bash
# hera  
export INPUTDATA_LM4=/scratch2/GFDL/gfdlscr/Justin.Perket/LM4_input_data/
#gaea 
export INPUTDATA_LM4=/gpfs/f5/gfdl_b/scratch/Justin.Perket/LM4_input_data/
```

This tree shows the only additional input files needed from the GFDL directories:

```
.
├── c96_grid
│   └── c96_OM4_025_grid_No_mg_drag_v20160808.tar
├── c96_LM4
│   └── c96_topo_rough_land.nc.tar
├── common_LM4
│   ├── biodata.nc
│   ├── cover_type.nc
│   ├── geohydrology.nc
│   ├── geohydrology_table_2a2n.nc
│   ├── ground_type.nc
│   ├── landuse.nc
│   ├── soil_brdf.nc
│   └── soil_type_hwsd_5minute.nc
├── forcings
│   └── landuse
│       └── LUH2
│           └── v2.0h
│               ├── irrigation.v20210513.nc
│               ├── landfrac.nc
│               ├── states.nc
│               └── transitions.nc
└── README.md
```

I've just tested this with a temp branch that tweaks a couple of the input paths, [JustinPerket:/cleanup/inputdata_lm4](https://github.com/JustinPerket/ufs-weather-model/tree/cleanup/inputdata_lm4) . If you check it out and export the path for hera or gaea, it should work for your testing.

**Comment by DeniseWorthen** [comment]
@JustinPerket I thought there was a requirement to have an FMS debug build in order to commit a debug test for this new component?

**Comment by JustinPerket** [comment]
@climbfuji  did put debug FMS build in the [Spack stack 1.8 Todo, based on my issue.](https://github.com/orgs/JCSDA/projects/6/views/1?filterQuery=1288. )

But I was not planning on committing a debug regression test with this PR. I now realize what I wrote above can be interpreted as such, my bad. I will edit the "Library Changes/Upgrades" section to be more clear.

I thought it was required that the LM4 app just be able to use the '-DDEBUG=ON' option. If it is not required, I think it would be a good idea for ongoing development. It's much more tedious to debug issues between UFS and LM4 otherwise. So I did not think that reviewing this PR had to be dependent on Spack stack 1.8 being released.  If the release is close at hand, I'm happy to wait and save UFS reviewers/gatekeepers' time. Then I'd commit a small Cmake change here so that LM4 and only LM4 uses the FMS debug build. Otherwise, I was planning on making a future small PR to do this.

**Comment by DusanJovic-NOAA** [comment]
PR description says "PR Adds New Tests/Baselines" but I do not see any changes in rt.conf. How is this component going to be regression tested. I do see lm4_tests.com, but the comment in that file says it's a temporary. Is that file going to be committed? 

I also do not see any gnu tests. Does this component support gnu compiler?

The lm4 repository that's used by this component did not have any commit in last 3 years. Is it still supported? 

I wonder which application is going to use this component? Is that application going to be used in any of the NCEP production systems?

**Comment by JustinPerket** [comment]
I'm just about to commit the new tests being in `rt.conf`, and removing `lm4_tests.conf`. They are cold start and warm restart GSWP3 tests, and are described in (https://github.com/NOAA-GFDL/LM4-NUOPC-driver/tree/develop?tab=readme-ov-file#running-with-regression-tests)
My baseline dir on Gaea is at: `/gpfs/f5/gfdl_b/scratch/Justin.Perket/RT_BASELINE/Justin.Perket/FV3_RT//REGRESSION_TEST/datm_cdeps_lm4_gswp3_intel` (I'm not sure why `rt.sh` generates a path like that).
I also have baselines on Hera, but can't confirm the path right now, I still can't access after the downtime.

No, it does not currently support gnu. Is that a requirement? 

The tag is the LM4.0 release. It is still currently actively used. The design enables the driver repository to check out an existing, unmodified, release tag of the GFDL Land Model.

**Comment by jkbk2004** [comment]
@JustinPerket Do you think @[INPUTDATA_LM4] can be replaced with @[INPUTDATA_ROOT]/INPUTDATA_LM4? LM4 input files are available at baseline input directory. For example, the files are available on hera:
```
Jong.Kim@hfe04:/scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/INPUTDATA_LM4$ ls
c96_LM4  c96_grid  common_LM4
```

**Comment by JustinPerket** [comment]
Thanks @jkbk2004 . I'm ready to do that. But maybe it got lost in the comments, `INPUTDATA_LM4` was just meant to be the bash variable name. Could the directory be named `LM4_input_data` to fit more with the other directories? 

Also, apologies, the `gfdlscr` group on Orion have been having unresolved permission issues lately, so I have not been able to update files/paths on Orion. Temporarily, any data/paths on Orion should be considered out of date.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 I think we should lean towards moving this PR to draft form until the Orion directory issues can get resolved.

**Comment by BrianCurtis-NOAA** [comment]
> @jkbk2004 I think we should lean towards moving this PR to draft form until the Orion directory issues can get resolved.

Maybe with the files going into INPUTDATA_ROOT the paths might not matter?

**Comment by JustinPerket** [comment]
> Maybe with the files going into INPUTDATA_ROOT the paths might not matter?

I would agree. I just committed using this for the path:
```bash
INPUTDATA_LM4=${INPUTDATA_LM4:-${INPUTDATA_ROOT}/LM4_input_data}
```

So it is no longer machine-specific paths. `$INPUTDATA_LM4` will be under `$INPUTDATA_ROOT` unless you assign it.
If it is not possible to move `${INPUTDATA_ROOT}/INPUTDATA_LM4` to `${INPUTDATA_ROOT}/LM4_input_data`, let me know.

**Comment by JustinPerket** [comment]
I now have temporary access to my orion work directory, pending resolution of the ticket with MSU and RDHPCS. So I was able to test on Orion, and now all the machines I work with now have up to date baselines for the LM4 tests:


```
orion:  /work/noaa/gfdlscr/jperket/stmp/jperket/FV3_RT/REGRESSION_TEST/datm_cdeps_lm4_gswp3_intel
hera:   /scratch1/NCEPDEV/stmp4/Justin.Perket/FV3_RT/REGRESSION_TEST/datm_cdeps_lm4_gswp3_intel
gaea:  /gpfs/f5/gfdl_b/scratch/Justin.Perket/RT_BASELINE/Justin.Perket/FV3_RT//REGRESSION_TEST/datm_cdeps_lm4_gswp3_intel
```

**Comment by zach1221** [comment]
Running ORTs and receiving an error during the test run.
./opnReqTest: line 227: INPUTDATA_LM4: unbound variable

**Comment by JustinPerket** [comment]
> Running ORTs and receiving an error during the test run. ./opnReqTest: line 227: INPUTDATA_LM4: unbound variable

Oh sorry about that. I haven't used ./opnReqTest  much because I primary develop and test on Gaea. It look like I forgot to define INPUTDATA_LM4 in the run section like this:

```bash
########################################################################                                                                                                                                  
####                              RUN                               ####                                                                                                                                  
########################################################################                                                                                                                                  

mkdir -p ${STMP}/${USER}
NEW_BASELINE=${STMP}/${USER}/FV3_OPNREQ_TEST/OPNREQ_TEST
RTPWD=${NEW_BASELINE}
INPUTDATA_ROOT=${INPUTDATA_ROOT:-$DISKNM/NEMSfv3gfs/input-data-20240501}
INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20240214/
INPUTDATA_ROOT_BMIC=${INPUTDATA_ROOT_BMIC:-$DISKNM/NEMSfv3gfs/BM_IC-20220207}
INPUTDATA_LM4=${INPUTDATA_LM4:-${INPUTDATA_ROOT}/LM4_input_data}
```

I'll commit this now. Please bear with me as brush up on the wikis to use opnReqTest on hera/orion. Is it as simple as running `./opnReqTest -n datm_cdeps_lm4_gswp3` for me to use?

**Comment by zach1221** [comment]
@JustinPerket correct from tests directory run (./opnReqTest -n control_p8 -a epic -c bit) for example.
I'm retesting now though and can keep you posted.

**Comment by JustinPerket** [comment]
ok, I'm trying to test as well, though I am not on the epic account. I started by trying `./opnReqTest -n control_p8 -a $ACCNR -c bit`, but am not having much success. Can it only run on Hera?

Previously on Gaea, I couldn't run because it says `unknown machine ID. edit detect_machine.sh file`. It looks like Gaea is not supported?

On Orion, it seems to look for the nonexistent module `gcc/8.3.0`. I only see `gcc/12.2.0`. It also seems to use `DISKNM=/work/noaa/nems/emc.nemspara/RT` instead of ` DISKNM=/work/noaa/epic/UFS-WM_RT/`

On hera, it did build and submit, but the job has been stuck in the queue for a while.

**Comment by BrianCurtis-NOAA** [comment]
We're also missing a test_changes.list from either Hera or Hercules.

**Comment by zach1221** [comment]
@JustinPerket Yes, Hera and Orion/Hercules are the machines supported on the ORT script. Generally I'll use Hera/gnu to run the tests. I just finished ORTs with control_p8_gnu using std,bit,mpi,dbg,dcp,rst,thr tests and all passed.

**Comment by DeniseWorthen** [comment]
@zach1221 This PR adds a new land component that uses a DATM. Why does the ORT for control_p8_gnu matter?

**Comment by zach1221** [comment]
> @zach1221 This PR adds a new land component that uses a DATM. Why does the ORT for control_p8_gnu matter?

Hi, @DeniseWorthen. We usually run the same cases for ORT against every PR, control_p8, a coupled and a regional case. I haven't finished testing yet, but plan to run with the new datm case as well.

**Comment by zach1221** [comment]
@JustinPerket running the new case with standard base  `./opnReqTest -n datm_cdeps_lm4_gswp3  -a epic -c std `,  I receive the below error. 

cases to run: std_base
/scratch1/NCEPDEV/stmp2/Zachary.Shrader/rt-2146/tests/opnReqTests/wrt_env.sh: line 1: OUTPUT_FH: unbound variable

**Comment by JustinPerket** [comment]
> We're also missing a test_changes.list from either Hera or Hercules.

e33c9451 committed the log of running rt.conf on Hera, 3 weeks ago. Since the new lm4 tests were in a different file and not rt.conf, test_changes.list remained empty. So it was not committed. I can rerun now on Hera if desired.

**Comment by jkbk2004** [comment]
> @JustinPerket running the new case with standard base `./opnReqTest -n datm_cdeps_lm4_gswp3 -a epic -c std `, I receive the below error.
> 
> cases to run: std_base /scratch1/NCEPDEV/stmp2/Zachary.Shrader/rt-2146/tests/opnReqTests/wrt_env.sh: line 1: OUTPUT_FH: unbound variable

@zach1221 I think it's different issue to address general application capability of ORT system. datm_cdeps_lm4_gswp3 is not necessary for operational requirement.  I don't think ORT OUTPUT_FH issue is specifically related to this spr.

**Comment by JustinPerket** [comment]
> @JustinPerket running the new case with standard base `./opnReqTest -n datm_cdeps_lm4_gswp3 -a epic -c std `, I receive the below error.
> 
> cases to run: std_base /scratch1/NCEPDEV/stmp2/Zachary.Shrader/rt-2146/tests/opnReqTests/wrt_env.sh: line 1: OUTPUT_FH: unbound variable

I remember getting a similar error yesterday, and also when running datm_cdeps_lnd_gswp3 to compare. But I was not certain I was using opnReqTest correctly.

**Comment by jkbk2004** [comment]
ORT script system is quite hard wired and far from being perfect.

**Comment by FernandoAndrade-NOAA** [comment]
I do not have permission to push RT logs to this branch, please add permissions for @zach1221 and I, @JustinPerket

**Comment by JustinPerket** [comment]
Invites should be sent

> I do not have permission to push RT logs to this branch, please add permissions for @zach1221 and I, @JustinPerket

**Comment by JustinPerket** [comment]
I was also rerunning RTs on Hera, but it'll take quite a while for me to get through the queue.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 and Acorn RT Logs on Hera at: /scratch1/NCEPDEV/stmp2/Brian.Curtis

**Comment by FernandoAndrade-NOAA** [comment]
Ok, we should be good to go, I'll let the sub PR know to continue with the merge.

**Comment by FernandoAndrade-NOAA** [comment]
Sub PR is merged in, please go ahead and revert the related gitmodules change and update the commit, thank you.

**Comment by jkbk2004** [comment]
@JustinPerket Note that CMEPS new hash is https://github.com/NOAA-EMC/CMEPS/commit/24e9eed4ffe8138bef635c8f916f91b142595675

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Comment by JustinPerket** [comment]
> @JustinPerket Note that CMEPS new hash is [NOAA-EMC/CMEPS@24e9eed](https://github.com/NOAA-EMC/CMEPS/commit/24e9eed4ffe8138bef635c8f916f91b142595675)

Thanks! (Sorry, I was out of the office yesterday)

**Pull request merged**
