### PR TITLE
NCAR/main PR #66 (Bugfix and optimization of prognostic closure for the P8 physics suite)

### PR DESCRIPTION
**Pull request by dustinswales**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR corrects a bug when using the prognostic closure (progsigma = true) to compute the q-tendency due to microphysics even if the diagnostic flags are false. It also optimizes the cloudbase massflux value for shallow and deep convection to work with the overall P8 physics suite.

New baselines are needed for the test: control_c384_progsigma

This update does not change the results in the control tests.

###issues
It addresses the issue: https://github.com/NCAR/ccpp-physics/issues/960

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [x] CI

###dependencies
https://github.com/NCAR/ccpp-physics/pull/967
https://github.com/ufs-community/ccpp-physics/pull/13

@lisa-bengtsson

### CODE REVIEW

**Comment by grantfirl** [comment]
New baselines are needed for the test: control_c384_progsigma

This update does not change the results in the control tests.

**Comment by jkbk2004** [comment]
@grantfirl @ChunxiZhang-NOAA @BrianCurtis-NOAA @zach1221 I am adding new BL_DATE. baseline change only for control_c384_progsigma. I will manually create that case and copy over with all other existing cases.

**Comment by jkbk2004** [comment]
> @grantfirl @ChunxiZhang-NOAA @BrianCurtis-NOAA @zach1221 I am adding new BL_DATE. baseline change only for control_c384_progsigma. I will manually create that case and copy over with all other existing cases.

@dustinswales FYI: comment above

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1078056534/20221009213006/ufs-weather-model
[RT] Error: Test compile_011 failed in run_compile failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by zach1221** [comment]
Jenkins-CI run logs attached.
[ufs-weather-model » ort-docker-wrapper-pipeline » PR-1451 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9749455/ufs-weather-model.ort-docker-wrapper-pipeline.PR-1451.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA what about the RT run on wcoss2?

**Comment by ChunxiZhang-NOAA** [comment]
> @BrianCurtis-NOAA what about the RT run on wcoss2?

Same question. I didn't see the RT log for wcoss2.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Can you copy the RT test check boxes from the PR template for this PR  and fill them out acordingly?

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dustinswales we need to start merging process. @ChunxiZhang-NOAA ccpp dependency first? Can you merge in on ccpp side first?

**Comment by dustinswales** [comment]
@jkbk2004 Merged into ufs/dev.
[Upstream submodule fv3atm pointers have been updated](https://github.com/NOAA-EMC/fv3atm/pull/592/commits/88357c889c0b6f3041571861aeb86a873f2ea94d)

**Comment by jkbk2004** [comment]
@dustinswales Time to update fv3atm hash and revert branch in gitmodules.

**Pull request merged**
