### PR TITLE
Update Prototype test suite to initial P8 configuration; turn on RRTMGP

### LINKED ISSUE #940: Update Prototype Test suites P7->P8
## Description
The existing P7 test suite for coupled and uncoupled needs to be updated to the initial P8 test suite by enabling RRTMGP.

## Solution

Make the required changes in default_vars and the standalone P7 tests, rename the tests and make the required changes in rt.conf

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- adds new default values of ``DO_RRTMGP`` and ``CCPP_SUITE=FV3_GFS_v16_coupled_p8`` for the coupled model in ``default_vars``
- adds same two settings to all standalone (``control_[]_p7``) tests since these are not default settings for the standalone
- adds namelist variables required for the ``DO_RRTMGP`` option to ``cpld_control_run.IN``
- updates test names from ``p7`` to ``p8`` and makes required changes in rt.conf
- retains ``cpld_bmark_p7`` test by setting ``DO_RRTMGP`` to false and  ``CCPP_SUITE=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1`` 
- adds 35d versions of ``cpld_bmark_p8`` and update ``rt_35d.conf``.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #940 
- fixes Indexing bug in SW cloud-sampling routine. (dustinswales/ccpp-physics@0a545c6#diff-ab383f7b24008085d38216e27611d9db32967aa782caf00525886f1c46407665L102)
- Reverts bug introduced by NCAR/ccpp-physics#627. A little background. In this PR, the surface albedo calculation was moved out of the SW scheme and to the start of the radiation loop. In RRTMGP, the calculation of the solar-zenith angle was not moved out of the scheme along with the surface-albedo calculation. The SZA is an input to the subroutine to compute the surface-albedo.

## Testing

- New baselines are required for all P7 tests (standalone and coupled) in order to update to the initial P8 feature set with RRTMGP turned on
- An initial baseline was created for hera.intel and all tests passed against that baseline. 
- Baselines were run on hera.intel against ``develop-20111130``. The following tests failed as expected:

Missing baselines:
 - all cpld p8 tests
 - all control p8 tests

Answer changes:
 - regional_RRTMGP 
 - control_rrtmgp 
 - control_rrtmgp_c192
 - control_rrtmgp_debug 

However, the cpld_bmark_p7 test also failed. This was not expected since RRTMGP is not active in this test and the SDF remains ``FV3_GFS_v16_coupled_nsstNoahmpUGWPv1``.

At 8f53730, hera.gnu baselines all pass except for the following:

Missing baselines:
- control_p8
- control_debug_p8
- cpld_control_c96_p8
- cpld_debug_p8

Answer changes:
- control_rrtmgp
- control_rrtmgp_debug

At 8f53730, hera.intel baselines showed the same results as previously but the ``cpld_bmark_p7`` now passed, as expected.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

- https://github.com/NOAA-EMC/fv3atm/pull/428
- https://github.com/NCAR/ccpp-physics/pull/782

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
Are the test files `cpld_control_*_p8`, `cpld_decomp_p8`, `cpld_restart_p8`, and etc. missing `export DO_RRTMGP=.true.`? I see `export DO_RRTMGP=.true.` in `control_p8`. Are we not enabling rrtmgp for cpld p8 tests?

**Comment by DeniseWorthen** [comment]
DO_RRTMGP=.true.  along w/ the change to the default CCPP SDF is made in the export_cpl section of default_vars:

```
@@ -1036,7 +1036,7 @@ export eps_imesh=1.0e-1

 # FV3 defaults
 export FRAC_GRID=.true.
-export CCPP_SUITE=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1
+export CCPP_SUITE=FV3_GFS_v16_coupled_p8
 export INPUT_NML=cpld_control.nml.IN
 export FIELD_TABLE=field_table_gfsv16
 export DIAG_TABLE=diag_table_template
@@ -1120,6 +1120,9 @@ export USE_CICE_ALB=.false.
 export KTHERM=2
 export TFREEZE_OPTION=mushy

+# P8 RRTMGP
+export DO_RRTMGP=.true.
+

```

For the standalone, we can't set these in the export_fv3 section so I put them in the individual control P8 tests.

**Comment by MinsukJi-NOAA** [comment]
> DO_RRTMGP=.true. along w/ the change to the default CCPP SDF is made in the export_cpl section of default_vars:
> 
> ```
> @@ -1036,7 +1036,7 @@ export eps_imesh=1.0e-1
> 
>  # FV3 defaults
>  export FRAC_GRID=.true.
> -export CCPP_SUITE=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1
> +export CCPP_SUITE=FV3_GFS_v16_coupled_p8
>  export INPUT_NML=cpld_control.nml.IN
>  export FIELD_TABLE=field_table_gfsv16
>  export DIAG_TABLE=diag_table_template
> @@ -1120,6 +1120,9 @@ export USE_CICE_ALB=.false.
>  export KTHERM=2
>  export TFREEZE_OPTION=mushy
> 
> +# P8 RRTMGP
> +export DO_RRTMGP=.true.
> +
> ```
> 
> For the standalone, we can't set these in the export_fv3 section so I put them in the individual control P8 tests.

I missed that. Thanks for the explanation.

**Comment by DeniseWorthen** [comment]
@dustinswales Please update your FV3 branch for further testing. I have found that the ``cpld_bmark_p7`` test does not reproduce against the current baseline, which is not expected (see the PR description for all the testing). Would you expect that any of your changes would change answers if RRTMGP is not active?

**Comment by dustinswales** [comment]
@DeniseWorthen 
The answers should not change if GP is off.
I'm updating my code now and re-running opnReqTest script.

**Comment by MinsukJi-NOAA** [comment]
> @DeniseWorthen The answers should not change if GP is off. I'm updating my code now and re-running opnReqTest script.

@dustinswales `opnReqTest` does not compare against the saved baselines (I believe @DeniseWorthen is referring to the baseline from 20211130: https://github.com/DeniseWorthen/ufs-weather-model/blob/745cebde8cb4ad950ed0de37f15f09c911f83af9/tests/rt.sh#L463). You will need to use `./rt.sh -n cpld_bmark_p7 -k`

**Comment by DeniseWorthen** [comment]
@dustinswales I got a seg fault when I tried to run the cpld_debug_p8 test in rt_gnu.conf. Note I have not yet updated FV3 in my PR branch. The error is:

```
  0:  in fcst comp init, fcst_ntasks=         144
  0:  num_atmos_calls=          30 time_init=        2021           3          22           6           0           0 time_atmos=        2021           3          22           6           0           0 time_end=        2021           3          22          12           0           0 dt_atmos=         720 Run_length=       21600
 78: At line 3675 of file /scratch2/NCEPDEV/climate/Denise.Worthen/WORK/ufs_p8_gnu/FV3/ccpp/data/GFS_typedefs.F90
 78: Fortran runtime error: Cannot match namelist object name h2o_co2_o3_n2o_ch4_o2
 78:
```

My run directory on hera is ``/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_21968/cpld_debug_p8``. Could you check if there seems anything wrong w/ the input.nml?

(edit: the control_p8, control_debug_p8 and cpld_control_c96_p8 test also failed w/ the same error).

**Comment by DeniseWorthen** [comment]
I think the issue is the missing quotes around the file names in the input.nml. That seems to have resolved the gnu debug issue. Note I had no problem w/ the intel debug tests, even though they also lacked the quotes.

**Comment by dustinswales** [comment]
@DeniseWorthen 
Yesterday we found an issue using gnu, https://github.com/dustinswales/fv3atm/commit/e34a7d4c49439e1dab8f174fe0030a9e848c1591, which is the same line you are having an error at. 
Did you update the fv3atm you are using?

**Comment by DeniseWorthen** [comment]
@dustinswales I thought that replacing the quotes in the input.nml (see my last commit) resolved the GNU problem but now I'm not sure. I will update my FV3.

**Comment by DeniseWorthen** [comment]
I'm having trouble updating FV3. It is trying to checkout out ccpp/physics hash 4031e8f but can't find it.

**Comment by dustinswales** [comment]
@DeniseWorthen 
Sorry, I forgot to push my physics. Should be all good now.

**Comment by dustinswales** [comment]
@DeniseWorthen 
Once small thing that got lost along the way that you need to add in:
diff --git a/tests/parm/cpld_control.nml.IN b/tests/parm/cpld_control.nml.IN
index 339f3050..020183bd 100644
--- a/tests/parm/cpld_control.nml.IN
+++ b/tests/parm/cpld_control.nml.IN
@@ -225,10 +225,7 @@ deflate_level=1
```
-  use_LW_jacobian    = .true.
-  damp_LW_fluxadj    = .true.
-  lfnc_k             = 3125.
-  lfnc_p0            = 60000.
+  use_LW_jacobian    = .false.
```

**Comment by DeniseWorthen** [comment]
The cpld_bmark_p7 test is now reproducing after fixing the namelist and updating FV3.

**Comment by dustinswales** [comment]
> The cpld_bmark_p7 test is now reproducing after fixing the namelist and updating FV3.
Excellent!

**Comment by DeniseWorthen** [comment]
@dustinswales I will be closing this PR since the feature is not being included in the P8 feature set at this time. Please open a new PR with your FV3 feature branch and add just your single test ``cpld_control_p7_rrtmgp``. We'll then be able to at least commit your current RRTMGP fixes.

**Comment by dustinswales** [comment]
@DeniseWorthen 
Can we just reopen my original PR...

**Comment by DeniseWorthen** [comment]
I can do that, but it seemed that PR would require quite a bit of cleanup to remove all the additional tests. Opening a new PR won't push you later in the Q if that is what you are concerned about.

**Comment by dustinswales** [comment]
@DeniseWorthen 
I need to do some cleanup first, then will open a new PR

**Comment by DeniseWorthen** [comment]
OK, we're discussing the Q right now, and it looks like 12/7 would be the target date.

**Comment by DeniseWorthen** [comment]
Closing; The updates and fixes to RRTMGP will come in a new PR, currently scheduled for commit on 12/7.

**Pull request closed without merging**
