### PR TITLE
correct tasks calculation in rt.sh so rocoto workflow will run

### LINKED ISSUE #1430: rt.sh $TASKS and $NODES are wrong, breaking rocoto workflow
## Description

The `$TASKS` and `$NODES` calculations in rt.sh are wrong; the new ones are in run_tests.sh. They should be moved to rt_utils.sh so they can be called in both locations.

### To Reproduce:
Run the cpld_bmark_esmfthreads_p8 test on hera using Rocoto

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR are specified below.

- [ ] ~~Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.~~

- [ ] ~~New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.~~

## Description

The `$TASKS` calculation in rt.sh is incorrect; the correct calculations are in run_tests.sh, which breaks the Rocoto workflow. This PR moves those calculations to rt_utils.sh so they can be called from both scripts.

It is unlikely this will affect any test on any platform, except when running the Rocoto workflow. However, it should be tested on all platforms with baseline generation just to be sure. To avoid wasting resources, this PR should be combined with another that requires new baselines.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/1430

## Testing

Hera gnu using rocoto and ecflow.

- [ ] hera.intel
- [X] hera.gnu - using ecflow and rocoto
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

None.

### CODE REVIEW

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA we are trying to combine #1425 and #1418 to this PR. I am going to ask Jun and Ratko to create PRs to you branch. Is it ok for you ?

**Comment by SamuelTrahanNOAA** [comment]
No, I won't have time to test that today because I'm working on two urgent PRs for the RRFS (in a fork).

**Comment by jkbk2004** [comment]
No problem! I will merge in these PRs separately then.

**Comment by SamuelTrahanNOAA** [comment]
This PR is already in #1437 so you could merge it with that one.

**Comment by jkbk2004** [comment]
> This PR is already in #1437 so you could merge it with that one.

That's the option. Thanks for the note.

**Comment by jkbk2004** [comment]
this pr was merged with #1437.

**Pull request closed without merging**
