### PR TITLE
Use nuopc labels in fv3cap. Refactor ModelAdvance in fv3cap

### LINKED ISSUE #652: an empty "data_table" file is required for standalone runs
## Description

For the coupled or datm applications,  the ``data_table`` file provides the name and use information for the river runoff data file. It is applied in MOM6 using the data_override function. For standalone ATM tests, an empty data_file is required to be present in the run directory or else the run fails. 

### To Reproduce:

Remove the empty data_table file from a standalone FV3 run directory, the run will fail.

## Additional context

The cause is the call to `` data_override_init`` in ``module_fcst_grid_comp.F90``.  Testing with hera intel/gnu shows that removing this call (and the associated ``use data_override_mod,  only: data_override_init`` ) does not change baselines. The  empty ``data_table`` file is not required at run time.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [ ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

* Update fv3atm to use NUOPC semantic labels in fv3cap, and refactor ModelAdvance.
* Update NEMS. Removed NEMS grid component (no need to set PE_MEMBER01: in model_configure anymore)
* Cleanup CMakeLists.txt

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI https://github.com/ufs-community/ufs-weather-model/actions/runs/1037618789

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/NEMS/pull/104
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/330

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
Removes the requirement to have an empty data_table in the run directory. I've tested with control and 2 coupled configurations (one using data_override to apply runoff, one w/o) and all baselines pass.

```
diff --git a/module_fcst_grid_comp.F90 b/module_fcst_grid_comp.F90
index 618e86f..f9831b2 100644
--- a/module_fcst_grid_comp.F90
+++ b/module_fcst_grid_comp.F90
@@ -210,7 +210,7 @@ if (rc /= ESMF_SUCCESS) write(0,*) 'rc=',rc,__FILE__,__LINE__; if(ESMF_LogFoundE
     integer :: jsc, jec, isc, iec, nlev
     type(domain2D) :: domain
     integer :: n, fcstNpes, tmpvar
-    logical :: single_restart
+    logical :: single_restart, fexist
     integer, allocatable, dimension(:) :: isl, iel, jsl, jel
     integer, allocatable, dimension(:,:,:) :: deBlockList

@@ -404,9 +404,12 @@ if (rc /= ESMF_SUCCESS) write(0,*) 'rc=',rc,__FILE__,__LINE__; if(ESMF_LogFoundE
      call  atmos_model_init (atm_int_state%Atm,  atm_int_state%Time_init, &
                              atm_int_state%Time_atmos, atm_int_state%Time_step_atmos)
 !
-     call data_override_init ( ) ! Atm_domain_in  = Atm%domain, &
-                                 ! Ice_domain_in  = Ice%domain, &
-                                 ! Land_domain_in = Land%domain )
+     inquire(FILE='data_table', EXIST=fexist)
+     if (fexist) then
+       call data_override_init ( ) ! Atm_domain_in  = Atm%domain, &
+                                   ! Ice_domain_in  = Ice%domain, &
+                                   ! Land_domain_in = Land%domain )
+     endif
```

**Review by aerorahul — APPROVED** [review]
changes at the UFS level look good to me.
thanks for the cleanup

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/674640428/20210716091506/ufs-weather-model
Please make changes and add the following label back:
gaea-intel-RT

**Review by climbfuji — APPROVED** [review]
Nice cleanup work!

**Comment by climbfuji** [comment]
Looks like all tests passed. That was quick.

**Comment by junwang-noaa** [comment]
Notes: the control_atm_aerosols results changed due to ESMF remapping option synchronized (only allow setting with reproducibility requirement). Baseline results for all other tests do not change

**Pull request merged**
