### PR TITLE
Ugwp fhzero bugfix

### LINKED ISSUE #908: FHZERO bug
## Description
 Changing the output frequency affect the resulting forecast.

### To Reproduce:
What compilers/machines are you seeing this with?
  Intel compiler in hera

Give explicit steps to reproduce the behavior.
1.  Checkout latest ufs-weather-model
2.  copy the control_p7 test to control_p7_fhzero
3. add export FHZERO=3 to control_p7_fhzero
4. run  both control_p7 and control_p7_fhzero tests keeping the output

Compare the restart files, and any instantaneous field, such as ugrd, and you will see differences

## Additional context

I tested this with "control", which is GFS_V16 physics, and that physics suite doesn't contain this bug.

### PR DESCRIPTION
**Pull request by mdtoy**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR updates the .gitmodules pointer to NOAA-EMC/fv3atm branch that fixes a bug in the UGWP drag suite (both "unified_ugwp" and "ugwpv1_gsldrag" schemes) where the changing the "fhzero" (diagnostic bucket) variable in the input.nml would change the forecast, which should not happen. This does change the expected answer from Regression Testing.
Thanks to @pjpegion for identifying the bug.

### Issue(s) addressed

This PR fixes ufs-community/ufs-weather-model issue [#908](https://github.com/ufs-community/ufs-weather-model/issues/908)

## Testing

The update passed the Operation Requirement Testing. On Hera, see the following log file for the test result:
/scratch1/BMC/wrfruc/mtoy/git_local/ufs-weather-model/tests/OpnReqTests_hera.intel.log  (included in this PR)

- [x] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

None.

Do PRs in upstream repositories need to be merged first?
No.

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@mdtoy Would you please recover the content in the PR template? We need that for the code commit process.

**Comment by mdtoy** [comment]
> @mdtoy Would you please recover the content in the PR template? We need that for the code commit process.

@junwang-noaa I just recovered the PR template.

**Comment by mdtoy** [comment]
> @mdtoy please bring these up to date with respective authoritative repositories
> 
> * ufs-weather-model **NOT** up to date
> * ww3 **NOT** up to date

I just made the updates.

**Comment by climbfuji** [comment]
@mdtoy Thanks for confirming your changes with the OpnReqTest. I believe this PR was replaced by https://github.com/ufs-community/ufs-weather-model/pull/918, can you confirm please?

**Comment by mdtoy** [comment]
Yes, it looks like PR #917 was replaced by #918.

— Mike

**Pull request closed without merging**
