### PR TITLE
Use global-workflow detect_machine.sh to keep consistent between projects

### LINKED ISSUE #2096: Bring in detect_machine.sh from global workflow for consistency across the community.
## Description

The global workflow team has an updated script to detect the machine the script is currently using. It uses a regexp method to detect the machine either by hostname or the directory structure. This script should be kept consistent across the ufs community.

## Solution

* Bring in (update): https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/detect_machine.sh to the ufs-weather-model 
* Add `global-workflow admins` to the codeowners for detect_machine.sh so they are aware of any changes we make to the script and can bring them into their repository.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch. [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14177426/RegressionTests_hera.log)
- [x] Add list of all failed regression tests in "Regression Tests" section.

### Description

Bring in the global-workflow detect_machine.sh to keep consistent between projects.

### Commit Message

```
Bring in the global-workflow detect_machine.sh to keep consistent between projects. (Closes #2096 )
```

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [X] Normal

### Blocking Dependencies

None

### Git Issues Fixed By This PR

- Closes #2096 

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [X] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 This is the PR I mentioned that will change RT_MACHINE to just MACHINE. https://github.com/BrianCurtis-NOAA/ufs-weather-model/blob/2cb8cb04444348b221079934d443243044e4cbb0/tests/detect_machine.sh#L62

**Comment by BrianCurtis-NOAA** [comment]
@HenryWinterbottom-NOAA Here is the PR.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I see cheyenne in detect_machine.sh. We cleaned up cheyenne. Syncing issue?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I see cheyenne in detect_machine.sh. We cleaned up cheyenne. Syncing issue?

This is a shared file between global-workflow and UFSWM now, so i'll confirm with them if they need to support Cheyenne still. 

Do you know if this still hold true on Gaea?:
```
elif [[ -d /lustre && -d /ncrc ]] ; then
  # We are on GAEA.
  MACHINE_ID=gaea
```

**Comment by jkbk2004** [comment]
> > @BrianCurtis-NOAA I see cheyenne in detect_machine.sh. We cleaned up cheyenne. Syncing issue?
> 
> This is a shared file between global-workflow and UFSWM now, so i'll confirm with them if they need to support Cheyenne still.
> 
> Do you know if this still hold true on Gaea?:
> 
> ```
> elif [[ -d /lustre && -d /ncrc ]] ; then
>   # We are on GAEA.
>   MACHINE_ID=gaea
> ```

I think it should be: /lustre is gone with f2
```
elif [[ -d /gpfs && -d /ncrc ]] ; then
```

**Comment by BrianCurtis-NOAA** [comment]
Cheyenne is off, forgot it happened end of Dec. And I'll make the change for Gaea, thanks.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA can you sync up branch? We will try to combine with #2115

**Comment by jkbk2004** [comment]
@ulmononian manually picked up files change from this pr. @BrianCurtis-NOAA you can check at #2115

**Pull request closed without merging**
