### PR TITLE
MOM6 bugfixes, GFDL update, update CDMBGWD settings; fix for restart reproducibility (without waves) when USE_LA_LI2016=True, sign error on fprec passed to ocean, GFDL update, resolution dependent cdmbgwd settings

### LINKED ISSUE #380: non-reproducibility of non-wave benchmark configuration when ``USE_LA_li2016=True``
## Description

The non-wave benchmark tests are not reproducible when ``USE_LA_li2016=True``. 

Details are provided here: MOM6 Issue [#46](https://github.com/NOAA-EMC/MOM6/issues/46)

### LINKED ISSUE #389: hord_dp value in input.benchmark_v16.nml.IN
The value of hord_dp should be "-5" in input.benchmark_v16.nml.IN, according to Xiaqiong Zhou. Thanks.

### LINKED ISSUE #394: update cdmbgwd namelist values
## Description

Namelist values for cdmbgwd need updating.

## Solution

The following settings should be used used in both GFSv15p2 (64levels) and also GFSv16(127levels) namelists. These optimal values for different resolutions were tested and evaluated during GFS.v15 and GFS.v16 developments.  They have been included as default values in the global model workflow config.fv3

C96:   cdmbgwd="0.14,1.8,1.0,1.0"
C192:  cdmbgwd="0.23,1.5,1.0,1.0"
C384:  cdmbgwd="1.1,0.72,1.0,1.0"
C768: cdmbgwd="4.0,0.15,1.0,1.0"

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

The non-wave benchmark tests are not reproducible unless ``USE_LA_LI2016`` is set False. The desired setting for the benchmark configuration is True.

A bug fix has been found by @breichl to insert missing halo updates in the nuopc cap when either the A or B Stagger location is specified.

This update will change baselines for all non-wave benchmark tests. Currently these tests have set ``USE_LA_LI2016=False `` to maintain restart reproducibility. 

This update will also change baselines due to the sign error fix on the latent heat contribution to the ocean from frozen precip (fprec) in the nuopc cap.

The GFDL update is from their MOM6 main branch on 20210120 which contains EMC's wave coupling code, alone with some minor code standardization and documentation. No answer changes are included in this.

### Issue(s) addressed
Issue #380 
Issue #389 
Issue #394 
MOM6 Issue [#46](https://github.com/NOAA-EMC/MOM6/issues/46)
MOM6 Issue [#50](https://github.com/NOAA-EMC/MOM6/issues/50)
MOM6 Issue [#53](https://github.com/NOAA-EMC/MOM6/issues/53)

Includes PR [#385](https://github.com/ufs-community/ufs-weather-model/pull/385)

## Dependencies

Dependent MOM6 [PR51](https://github.com/NOAA-EMC/MOM6/pull/51)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jiandewang and @JessicaMeixner-NOAA This is in the commit queue for update at some point; I added you both as reviewers but nothing needs to be done at this point. Thanks.

**Comment by jiandewang** [comment]
@DeniseWorthen thanks for combining these three into one commit in ufs, otherwise they will wait in queue for long time.

**Comment by DeniseWorthen** [comment]
Yes, will do. I added the setting differently in the standalone vs the coupled because the coupled model uses the same namelist for different resolutions.

**Comment by DeniseWorthen** [comment]
Tests have passed on hera.intel, so I'm marking this as ready for review.

**Review by climbfuji — COMMENTED** [review]
Looks ok to me. Creating new baseline on gaea now, will send the logs when testing is finished and approve after the MOM6 submodule pointer is updated and the change to `.gitmodules` is reverted.

**Comment by DeniseWorthen** [comment]
I had to change the walkclk time for the test fv3_ccpp_gfs_v16_RRTMGP_c192L127 on cheyenne.intel. It just barely timed out (didn't finish writing the restarts) the first time, used 1824 secs the second time. Should I commit this change or should we add it to a later commit?

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
Let's add it to a later PR since most RT finished. Dom, Can we have this
time change for  fv3_ccpp_gfs_v16_RRTMGP_c192L127 test in the ugwd PR?

**Comment by climbfuji** [comment]
> Let's add it to a later PR since most RT finished. Dom, Can we have this time change for fv3_ccpp_gfs_v16_RRTMGP_c192L127 test in the ugwd PR?
> […](#)

Someone will need to remind me, but yes, no problem. gaea RT still running for this MOM6 PR.

**Comment by DeniseWorthen** [comment]
All logs are posted and CI is running.

**Comment by junwang-noaa** [comment]
Thanks, Dom. I will remind you if it is not in your PR.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
