### PR TITLE
Move sfc emis alb calculation to its own scheme and make z0 composite consistent

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

Substantial changes to CCPP physics to move surface emissivity/albedo calculation to its own scheme and to make surface roughness length composite consistent when fractional landmask is used. Updates to `FV3GFS_io.F90` to write additional fields to the restart files (this requires removing the UGWPv1 warmstart test).

Additional changes:
- Bug fixes for coupled model for GNU from @DeniseWorthen 
- Bug fixes for 35-day runs from @DeniseWorthen 
- Update for CI tests from @MinsukJi-NOAA 

**Note.** This PR changes the results of almost all regression tests (intentionally) due to the updates in calculating surface emissivity and surface albedo, and - for tests using fractional landmask - the changes in ccpp-physics `GFS_surface_composites_post_run` (calculate composite of fluxes consistently).

### Regression testing against existing baseline with final code

Regression testing against existing baseline on hera with GNU (2021/05/12): all but two tests fail due to b4b differences, but all tests run to completion.

[rt_hera_gnu_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/6470109/rt_hera_gnu_against_existing.log)
[rt_hera_gnu_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/6470110/rt_hera_gnu_against_existing_fail_test.log)
[rt_hera_gnu_against_existing_log_hera.gnu.tar.gz](https://github.com/ufs-community/ufs-weather-model/files/6470111/rt_hera_gnu_against_existing_log_hera.gnu.tar.gz)

The following tests pass for hera with GNU:
```
log_hera.gnu/rt_013_fv3_esg_HAFS_v0_hwrf_thompson.log:Test 013 fv3_esg_HAFS_v0_hwrf_thompson PASS
log_hera.gnu/rt_029_fv3_esg_HAFS_v0_hwrf_thompson_debug.log:Test 029 fv3_esg_HAFS_v0_hwrf_thompson_debug PASS
```

Regression testing against existing baseline on hera with Intel (2021/05/12): all except nine tests fail due to b4b differences, but all tests run to completion.

[rt_hera_intel_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/6473113/rt_hera_intel_against_existing.log)
[rt_hera_intel_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/6473118/rt_hera_intel_against_existing_fail_test.log)
[rt_hera_intel_against_existing_log_hera.intel.tar.gz](https://github.com/ufs-community/ufs-weather-model/files/6473119/rt_hera_intel_against_existing_log_hera.intel.tar.gz)

The following tests pass for hera with Intel:
```
log_hera.intel/rt_097_fv3_esg_HAFS_v0_hwrf_thompson_debug.log:Test 097 fv3_esg_HAFS_v0_hwrf_thompson_debug PASS
log_hera.intel/rt_100_datm_control_cfsr.log:Test 100 datm_control_cfsr PASS
log_hera.intel/rt_101_datm_restart_cfsr.log:Test 101 datm_restart_cfsr PASS
log_hera.intel/rt_102_datm_control_gefs.log:Test 102 datm_control_gefs PASS
log_hera.intel/rt_103_datm_bulk_cfsr.log:Test 103 datm_bulk_cfsr PASS
log_hera.intel/rt_104_datm_bulk_gefs.log:Test 104 datm_bulk_gefs PASS
log_hera.intel/rt_105_datm_mx025_cfsr.log:Test 105 datm_mx025_cfsr PASS
log_hera.intel/rt_106_datm_mx025_gefs.log:Test 106 datm_mx025_gefs PASS
log_hera.intel/rt_107_datm_debug_cfsr.log:Test 107 datm_debug_cfsr PASS
```

### Regression testing against existing baseline with `iemis=1`/`ialb=1` changes rolled back

To understand better where the changes of the regression test results come from, I temporarily rolled back the changes for `iemis=1` and `ialb=1` in `radiation_surface.f` and ran the regression tests against the existing baselines on hera with Intel and GNU.

With GNU, the following tests fail due to b4b differences, as expected (but all run to completion):
```
fv3_gfs_v16_RRTMGP_debug
fv3_rrfs_v1beta_debug
fv3_rrfs_v1alpha_debug
fv3_gsd_debug
fv3_rrfs_v1beta
fv3_rrfs_v1alpha
fv3_gfs_v16_RRTMGP
fv3_gsd
```

With Intel, the following tests failed, again as expected (because Intel in PROD mode gives different answers for the otherwise unchanged tests using `iemis=1` and `ialb=1`; note that these tests pass in debug mode, see below).
```
cpld_debugfrac
fv3_control
fv3_lndp
fv3_control_32bit
fv3_decomp
fv3_ca
fv3_stochy
fv3_wrtGauss_nemsio_c192
fv3_wrtGauss_nemsio
fv3_wrtGauss_netcdf_esmf
fv3_wrtGlatlon_netcdf
fv3_gfdlmp_32bit
fv3_wrtGauss_netcdf
fv3_2threads
fv3_stretched
fv3_wrtGauss_netcdf_parallel
fv3_lheatstrg
fv3_gfdlmprad_32bit_post
fv3_thompson
fv3_thompson_no_aero
cpld_ca
fv3_rrfs_v1beta
fv3_hrrr
fv3_rap
fv3_rrfs_v1alpha
fv3_stretched_nest
cpld_control
cpld_2threads
cpld_controlfrac
cpld_decomp
cpld_satmedmf
fv3_gsd
fv3_gfdlmp
fv3_cpt
fv3_gfs_v16_stochy
fv3_gfdlmprad_noahmp
fv3_satmedmf
fv3_gfdlmprad_gwd
fv3_satmedmfq
cpld_control_wave
fv3_gfs_v16
fv3_gfs_v16_RRTMGP
fv3_csawmg
cpld_control_c192
fv3_gfs_v16_RRTMGP_debug
cpld_controlfrac_c192
fv3_regional_quilt_RRTMGP
fv3_gfsv16_csawmg
fv3_gfsv16_csawmgt
fv3_gfs_v16_flake
fv3_gocart_clm
fv3_HAFS_v0_hwrf_thompson
fv3_gsd_debug
fv3_rrfs_v1beta_debug
fv3_rrfs_v1alpha_debug
fv3_gsd_diag3d_debug
fv3_gfs_v16_ras
fv3_gfsv16_ugwpv1
fv3_gfsv16_ugwpv1_warmstart
fv3_esg_HAFS_v0_hwrf_thompson
cpld_bmark
cpld_bmarkfrac_v16_nsst
cpld_bmarkfrac_v16
cpld_bmarkfrac
cpld_bmarkfrac_wave_v16
cpld_bmarkfrac_wave
cpld_bmark_wave
cpld_control_c384
cpld_controlfrac_c384
fv3_gfdlmprad_atmwav
fv3_gfdlmprad
fv3_wrtGauss_nemsio_c768
```
The following tests pass with Intel:
```
cpld_debug
fv3_multigases_repro
fv3_regional_control
fv3_regional_restart
fv3_regional_quilt
fv3_regional_quilt_hafs
fv3_regional_quilt_netcdf_parallel
fv3_gfs_v16_debug
fv3_regional_control_debug
fv3_control_debug
fv3_stretched_nest_debug
fv3_thompson_debug
fv3_thompson_no_aero_debug
fv3_HAFS_v0_hwrf_thompson_debug
fv3_esg_HAFS_v0_hwrf_thompson_debug
fv3_gfsv16_ugwpv1_debug
fv3_gfs_v16_ras_debug
datm_control_cfsr
datm_restart_cfsr
datm_control_gefs
datm_bulk_cfsr
datm_bulk_gefs
datm_mx025_cfsr
datm_mx025_gefs
datm_debug_cfsr
```
The temporary reversal to the original `iemis=1`/`ialb=1` code will be removed before committing the ccpp-physics code.

### Final regression testing

New baselines will be created and used to verify on all tier-1 platforms. The new baseline date tag is 20210527.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/627
https://github.com/NCAR/ccpp-framework/pull/366
https://github.com/NOAA-EMC/fv3atm/pull/285
https://github.com/ufs-community/ufs-weather-model/pull/529
https://github.com/NOAA-EMC/CMEPS/pull/47

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/616413849/20210518171508/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_65512
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/616413849/20210518185136/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_63000
Test cpld_restartfrac 004 failed in check_result failed 
Test cpld_restartfrac 004 failed in run_test failed 
Test cpld_restartfrac_c192 012 failed in check_result failed 
Test cpld_restartfrac_c192 012 failed in run_test failed 
Test cpld_restart_bmarkfrac_v16 023 failed in check_result failed 
Test cpld_restart_bmarkfrac_v16 023 failed in run_test failed 
Test cpld_restart_bmarkfrac 020 failed in check_result failed 
Test cpld_restart_bmarkfrac 020 failed in run_test failed 
Test cpld_restartfrac_c384 016 failed in check_result failed 
Test cpld_restartfrac_c384 016 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/616413849/20210518231514/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_149466
Test cpld_control_c384 007 failed in run_test failed 
Test cpld_bmarkfrac_v16_nsst 012 failed in run_test failed 
Test cpld_controlfrac_c384 008 failed in run_test failed 
Test cpld_bmarkfrac 010 failed in run_test failed 
Test cpld_bmarkfrac_v16 011 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/616413849/20210519041509/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_9824
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/616413849/20210519050538/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_39486
Test cpld_restartfrac 004 failed in check_result failed 
Test cpld_restartfrac 004 failed in run_test failed 
Test cpld_restartfrac_c192 012 failed in check_result failed 
Test cpld_restartfrac_c192 012 failed in run_test failed 
Test cpld_restart_bmarkfrac 020 failed in check_result failed 
Test cpld_restart_bmarkfrac 020 failed in run_test failed 
Test cpld_restart_bmarkfrac_v16 023 failed in check_result failed 
Test cpld_restart_bmarkfrac_v16 023 failed in run_test failed 
Test cpld_restartfrac_c384 016 failed in check_result failed 
Test cpld_restartfrac_c384 016 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/616413849/20210519041511/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_80582
Test fv3_multigases_debug 082 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/616413849/20210526174512/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_331855
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/616413849/20210526190353/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_301666
Test cpld_restart_bmarkfrac 020 failed failed 
Test cpld_restart_bmarkfrac 020 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by climbfuji** [comment]
> Machine: orion
> Compiler: intel
> Job: BL
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/616413849/20210526174512/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_331855
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/616413849/20210526190353/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_301666
> Test cpld_restart_bmarkfrac 020 failed failed
> Test cpld_restart_bmarkfrac 020 failed in run_test failed
> Please make changes and add the following label back:
> orion-intel-BL

Grmpf ... the usual stuff. Will try this test again.
```
172: forrtl: severe (174): SIGSEGV, segmentation fault occurred
172: Image              PC                Routine            Line        Source
172: fv3.exe            0000000004D40CF9  Unknown               Unknown  Unknown
172: libpthread-2.17.s  00002ACB3D3E85D0  Unknown               Unknown  Unknown
172: fv3.exe            0000000000C7E6D0  _ZN5ESMCI2DD31Set         771  stl_vector.h
172: fv3.exe            0000000000CDB6B7  _ZN5ESMCI6ComPat1        6536  ESMCI_VMKernel.C
172: fv3.exe            0000000000C2AB19  _ZN5ESMCI2DD25set        1376  sparseMatMulStoreLinSeqVect.h
172: fv3.exe            0000000000C22287  _ZN5ESMCI27sparse        2010  sparseMatMulStoreLinSeqVect.h
172: fv3.exe            0000000000C1EDDF  _ZN5ESMCI5Array18        9188  ESMCI_Array.C
172: fv3.exe            0000000000C1DDB9  _ZN5ESMCI5Array17        8658  ESMCI_Array.C
172: fv3.exe            0000000000954DAA  c_esmc_arraysmmst        1068  ESMCI_Array_F.C
```

**Comment by MinsukJi-NOAA** [comment]
@climbfuji, is it possible to include a one-line fix for CI, which is due to the cdeps submodule now pointing to the develop branch? This will allow us to run ci for this PR.
```
diff --git a/tests/ci/repo_check.sh b/tests/ci/repo_check.sh
index 22bd90d..36c7c2b 100755
--- a/tests/ci/repo_check.sh
+++ b/tests/ci/repo_check.sh
@@ -56,7 +56,7 @@ datm[branch]='develop'
 datm[dir]='DATM'
 
 cdeps[repo]='https://github.com/NOAA-EMC/CDEPS'
-cdeps[branch]='emc/develop'
+cdeps[branch]='develop'
 cdeps[dir]='CDEPS-interface/CDEPS'
 
 cmake[repo]='https://github.com/NOAA-EMC/CMakeModules'
 ```

**Comment by climbfuji** [comment]
> @climbfuji, is it possible to include a one-line fix for CI, which is due to the cdeps submodule now pointing to the develop branch? This will allow us to run ci for this PR.
> 
> ```
> diff --git a/tests/ci/repo_check.sh b/tests/ci/repo_check.sh
> index 22bd90d..36c7c2b 100755
> --- a/tests/ci/repo_check.sh
> +++ b/tests/ci/repo_check.sh
> @@ -56,7 +56,7 @@ datm[branch]='develop'
>  datm[dir]='DATM'
>  
>  cdeps[repo]='https://github.com/NOAA-EMC/CDEPS'
> -cdeps[branch]='emc/develop'
> +cdeps[branch]='develop'
>  cdeps[dir]='CDEPS-interface/CDEPS'
>  
>  cmake[repo]='https://github.com/NOAA-EMC/CMakeModules'
> ```

@MinsukJi-NOAA Done, please check commit 5cb58011bd1e0a5f4c6832a30a3cd1bcf8f0a087

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA Done, please check commit [5cb5801](https://github.com/ufs-community/ufs-weather-model/commit/5cb58011bd1e0a5f4c6832a30a3cd1bcf8f0a087)

Thanks!

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
CMEPS has been merged so you can revert the gitmodules. Hash is 1513f5c

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
I just pulled in branch bugfix/p7a_35dfix from @DeniseWorthen. These changes were tested on top of the PR on Gaea and gave b4b identical results for all coupled tests.

**Comment by climbfuji** [comment]
This is ready to merge. Please double-check the submodule pointers and click the magic button ... thanks!

**Pull request merged**
