### PR TITLE
Update CMEPS for latest ESCOMP/master; Update PIO to 2.5.2; Refactor modules

### LINKED ISSUE #415: Update modulefiles directory to use pio/2.5.2 in ufs-weather-model
## Description
The CDEPS component will soon be added to the ufs-weather-model repository.  Currently pio/2.5.1 is used in ufs-weather-model. The new CDEPS component needs to use pio/2.5.2.

## Solution
Replace pio/2.5.1 with pio/2.5.2 in sub-directories under modulefiles directory for all supported platforms.

## Related to
- required to test MOM6_CICE6_CDEPS application under ufs-weather-model.

### LINKED ISSUE #428: Model does not catch invalid coupling mode
The nems.configure file contains an entry coupling_mode, that should be nems_frac or nems_orig for global coupled runs.  If something else is entered, like nems.orig, the model does not give an error, but fails to provide all of the coupling fields to the ocean model, and the model runs, but without any fluxes from atmosphere to ocean.

### LINKED ISSUE #510: Coupled model uses "SUITE_NAME" as variable; it should be CCPP_SUITE
## Description

The variable ``SUITE_NAME`` should be changed to ``CCPP_SUITE`` in the coupled model tests.

## Additional context

The change needs to be made in ``default_vars``, the input nmls used by the coupled tests (``input.benchmark_ccpp.nml.IN, input.benchmark_v16.nml.IN, input.mom6_ccpp.nml.IN``) and in all the cpld tests which are using a non-default suite setting.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

* Updates CMEPS to the latest emc/develop
* Removes shr_pio_mod.F90 from CMEPS-interface/CMakeLists.txt
* Removes two files (pio_in and med_modelio.nml) from tests/parm and run directory
* Updates pio module to 2.5.2 for all platforms
* Replaces SUITE_NAME with CCPP_SUITE in coupled tests
* Refactors modules into ufs_common and ufs_common_debug (PR #482)
* switches to use h-nems area on jet
 
### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 

CMEPS [#37 ](https://github.com/NOAA-EMC/CMEPS/issues/37)
UFS weather [#415](https://github.com/ufs-community/ufs-weather-model/issues/415)
UFS weather [#428](https://github.com/ufs-community/ufs-weather-model/issues/428)
UFS weather #510

## Testing

* The full RT suite (intel and gnu) were run on hera on 4/5/21 and all tests are B4B with current baselines (develop-20210401).  
* The full RT also passed on Gaea against develop-20210401.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

- waiting on CMEPS PR [#36](https://github.com/NOAA-EMC/CMEPS/pull/36)

co-author: @binli2337 
co-author: @DusanJovic-NOAA

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/602704560/20210409084509/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_275314
Test cpld_2threads 076 failed in check_result failed 
Test cpld_2threads 076 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Comment by DeniseWorthen** [comment]
I repeated the failed orion test by copying the cpld_control and cpld_2threads run directories and running both again. Both tests passed manual comparison of the mediator restart file w/ the develop-20210406 cpld_control test.

I will keep a copy of the auto-rt log and re-run the 2threads test manually.

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@DeniseWorthen Has CI been run? Otherwise I think it's ready for commit. Thanks for all the testing!

**Review by binli2337 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
> @DeniseWorthen Has CI been run? Otherwise I think it's ready for commit. Thanks for all the testing!

I ran CI  when I commited the cheyenne.gnu log but it doesn't look like it worked.

**Review by climbfuji — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
> > @DeniseWorthen Has CI been run? Otherwise I think it's ready for commit. Thanks for all the testing!
> 
> I ran CI when I commited the cheyenne.gnu log but it doesn't look like it worked.

The thr and dbg tests failed. Considering they are the jobs that take the longest, i believe they failed because the next commit automatically stopped the ec2 instances. I am working on a PR to fix this re-occurring issue in CI test.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
