### PR TITLE
Coupled model: IPD-CCPP b4b for coupled model, bugfix for stochastic physics

### PR DESCRIPTION
**Pull request by climbfuji**
This PR only updates .gitmodules and the submodule pointer for fv3atm for code review and testing.

Associated PRs:
https://github.com/NCAR/ccpp-physics/pull/417
https://github.com/NOAA-EMC/fv3atm/pull/86
https://github.com/ufs-community/ufs-weather-model/pull/91

For regression testing, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
I ran rt.sh on hera.intel against the existing baseline, and all tests pass. Given that it is likely that we will make changes to fix the initialization of cice variables in IPD and CCPP, I will not upload the logs and wait for the changes to be finalized.

**Comment by climbfuji** [comment]
Regression tests all passed on hera.intel using rt.sh, regression test logs updated in the PR.

[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4384983/rt_hera_intel.log)

**Comment by climbfuji** [comment]
Regression tests passed on wcoss_dell_p3 using rt.sh and NEMSCompsetRun, regression test logs updated in the PR.

**Comment by climbfuji** [comment]
Regression tests passed on wcoss_cray using rt.sh and NEMSCompsetRun, regression test logs updated in the PR.

**Comment by climbfuji** [comment]
Regression tests passed on hera.intel using NEMSCompsetRun - regression test logs updated in the PR. This completes the testing, ready to merge.

**Review by SMoorthi-emc — APPROVED** [review]

**Comment by climbfuji** [comment]
Ok, ufs-weather-model is ready as well.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
