### PR TITLE
update FV3 to better handle data source for regional model LBC processing and combined with #1730 WW3 update

### PR DESCRIPTION
**Pull request by Jili-Dong**
### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

rrfs_smoke_conus13km_hrrr_warm 
rrfs_smoke_conus13km_hrrr_warm_2threads 
rrfs_conus13km_hrrr_warm 
rrfs_smoke_conus13km_radar_tten_warm 
rrfs_smoke_conus13km_hrrr_warm_debug 
rrfs_smoke_conus13km_hrrr_warm_debug_2threads 
rrfs_conus13km_hrrr_warm_debug
rrfs_conus13km_hrrr_warm_restart_mismatch

The above tests have incorrect processing of LBC which has been corrected by this PR. A slide has been attached in discussions to explain the difference.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):
#1730 

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
combined with #1730 
Depends on [fv3atm#646](https://github.com/NOAA-EMC/fv3atm/pull/646)

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

Related to submodule FV3:

https://github.com/NOAA-EMC/fv3atm/pull/646

It is not expected to change any RT results.

Related to issue:
#1716

### CODE REVIEW

**Comment by jkbk2004** [comment]
@Jili-Dong There are two urgent PRs on-going this week: #1720 and another PR physics. We need to re-schedule this PR to next week.

**Comment by Jili-Dong** [comment]
@jkbk2004 could you combine this PR with any of the PR you mentioned as this PR is a quite simple one and won't change any baseline

**Comment by jkbk2004** [comment]
Since it just needs to point to the cubed sphere branch, the best chance is to combine with next physics PR that we are targeting by Friday. I will keep you posted.

**Comment by Jili-Dong** [comment]
@jkbk2004 sounds good. Thanks

**Comment by jkbk2004** [comment]
[RegressionTests_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11356664/RegressionTests_cheyenne.intel.log)
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11356665/RegressionTests_cheyenne.gnu.log)

**Comment by jkbk2004** [comment]
@Jili-Dong can you add PR description section? you can copy in the pr template: https://github.com/ufs-community/ufs-weather-model/blob/develop/.github/pull_request_template.md

**Comment by DeniseWorthen** [comment]
@jkbk2004 This shows compile_008 still failed on cheyenne.intel. I thought the compile was removed for cheyenne?

Will you try to combine this with #1730 ?

**Comment by Jili-Dong** [comment]
@jkbk2004 PR description section added

**Comment by jkbk2004** [comment]
@Jili-Dong can you combine in @MatthewMasarik-NOAA #1730 ww3 branch? Or I may jump in to see if I can directly update your fork. @MatthewMasarik-NOAA if you are still available, can you create a direct pr to Jili's branch?

**Comment by Jili-Dong** [comment]
@jkbk2004 sure. Let me try combine #1730

**Comment by Jili-Dong** [comment]
@jkbk2004 @MatthewMasarik-NOAA #1730 has been combined with this PR. Please let me know if it looks right.

**Comment by jkbk2004** [comment]
@Jili-Dong thanks for following up! can you update pr title to reflect #1730 and add a line to the linked PR section in the description? I will let the tests run over weekend. @BrianCurtis-NOAA I am running on this PR.

**Comment by Jili-Dong** [comment]
@jkbk2004 updated as requested

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1318832252/20230429160014/ufs-weather-model
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 073 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 074 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 075 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 076 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug 084 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug_2threads 085 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm_debug 086 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1318832252/20230429161516/ufs-weather-model
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 018 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 019 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 020 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 021 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug 034 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug_2threads 035 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm_debug 036 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /mnt/lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1318832252/20230429160711/ufs-weather-model
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 067 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 068 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 069 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 070 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug 078 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug_2threads 079 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm_debug 080 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by Jili-Dong** [comment]
@jkbk2004 apparently when I said there wouldn't be any baseline change, I hadn't considered each and every scenario in RTs. Those 7 failed RTs are related to regional warm start and these baselines need to be updated with the forecast from this PR. I have attached a slide to explain this. Please let me know if it is clear enough.
[data_source.pptx](https://github.com/ufs-community/ufs-weather-model/files/11360219/data_source.pptx)

**Comment by DeniseWorthen** [comment]
Why did the tests pass on Cheynne.intel ? It looks they were "alt check ok" but they still passed.

**Comment by jkbk2004** [comment]
Looks like nccmp -B option is not supported on Cheyenne. Sounds like rt script marks OK if exit code doesn't return specifically 1. I will test w/o -B. @DusanJovic-NOAA Do you think nccmp performance may get worse w/o -B ? We can ask system admin to re-install nccmp. @zach1221 @FernandoAndrade-NOAA FYI: possible item to follow up.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA note that rrfs_conus13km_hrrr_warm_restart_mismatch changes as well.

**Comment by zach1221** [comment]
Jenkins-ci logs attached. ORTs passed Ok.
[ufs-weather-model » ort-docker-pipeline » PR-1715 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11366952/ufs-weather-model.ort-docker-pipeline.PR-1715.1.Console.Jenkins.pdf)

@jkbk2004 I can inquire about nccmp with Cheyenne system admin, no problem.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA skip the test on acorn?

**Comment by BrianCurtis-NOAA** [comment]
No, looks to be almost done.

**Comment by jkbk2004** [comment]
All tests are done. we can start merging process.

**Comment by jkbk2004** [comment]
@Jili-Dong fv3 pr and ww3 pr were merged. Can you update hases and revert change in gitmodules? fv3 hash: https://github.com/NOAA-EMC/fv3atm/commit/832803b1611faa135309674ee5e4c3a072b55523  ww3 hash: https://github.com/NOAA-EMC/WW3/commit/7c932242fd120b189cb17f48799e3cd00260621c

**Comment by Jili-Dong** [comment]
> @Jili-Dong fv3 pr and ww3 pr were merged. Can you update hases and revert change in gitmodules? fv3 hash: [NOAA-EMC/fv3atm@832803b](https://github.com/NOAA-EMC/fv3atm/commit/832803b1611faa135309674ee5e4c3a072b55523) ww3 hash: [NOAA-EMC/WW3@7c93224](https://github.com/NOAA-EMC/WW3/commit/7c932242fd120b189cb17f48799e3cd00260621c)

@jkbk2004 gitmodules and hashes updated

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
