### PR TITLE
Add 3-moment option for NSSL cloud microphysics

### PR DESCRIPTION
**Pull request by MicroTed**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log.nssl3m.txt](https://github.com/ufs-community/ufs-weather-model/files/12785161/RegressionTests_hera.log.nssl3m.txt)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Adds support for NSSL microphysics option of 3-moment rain, graupel, and hail (or just rain and graupel if the hail species is deactivated). This predicts the reflectivity moment (6th moment in diameter), which in turn predicts the shape parameter of the gamma function particle size distribution.

### Associated UFSWM Issue to close

N/A
### Subcomponent Pull Requests

 PR for CCPP: https://github.com/ufs-community/ccpp-physics/pull/110
 PR for FV3 with added variables needed by CCPP: https://github.com/NOAA-EMC/fv3atm/pull/702

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

<details><summary>Tests affected by changes in this PR:</summary>
Yes, it will change regional_wofs, rrfs_v1nssl, and rrfs_v1nssl_nohailnoccn because of some changes to the NSSL microphysics scheme that is used with the tests.
Failed tests (comparisons): regional_wofs, rrfs_v1nssl, rrfs_v1nssl_nohailnoccn

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by MicroTed** [comment]
The addition of -mcmodel=medium to Intel.cmake was needed on jet to avoid a link error. I think this is because jet compiles for multiple targets, which increases the code size enough to not fit in the 'small' mcmodel. (No problem on hera)

**Comment by grantfirl** [comment]
@MicroTed Is this ready to be out of draft?

**Comment by MicroTed** [comment]
@grantfirl  I suppose so, and the FV3 one, too.

**Comment by zach1221** [comment]
Hi, @MicroTed . I think we're ready to begin testing of this PR next. Can you please sync up your branch to resolve conflicts?

**Comment by jkbk2004** [comment]
@MicroTed can you sync up at the fv3atm level? Ihttps://github.com/NOAA-EMC/fv3atm/pull/702

**Comment by MicroTed** [comment]
@jkbk2004 I think everything should be up to date now.

**Comment by zach1221** [comment]
@jkbk2004 @BrianCurtis-NOAA beginning testing of this PR.

**Comment by zach1221** [comment]
@jkbk2004 @MicroTed does the atmos_cubed_sphere hash need to be updated as well ? I think it may be old. We're pointing to 52bf91 vs ufs-communitu:develop: caba092

**Comment by MicroTed** [comment]
@zach1221 You may not have the last push I did for fv3atm? I'll check if I neglected to update at the ufs_weather_model level.

**Comment by MicroTed** [comment]
@zach1221  That seemed to be it -- should be fixed now. Sorry for missing that step!

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA FYI, the cpld_bmark_p8_intel BL creation needed an increase in time limit for Gaea within default_vars.sh. A standalone test creation run for that case showed in the timestamp that it took around 36-37 minutes, a bit over the default of 30 I believe.

**Comment by DeniseWorthen** [comment]
The last commit for the cpld_bmark_p8 test on gaea showed

```
   0: The total amount of wall time                        = 606.710669
```

**Comment by FernandoAndrade-NOAA** [comment]
Just to be clear, this timeout was during the BL creation run for rt.sh. After the time limit increase, there was no issue and the current successful Gaea log for this PR shows around the same runtime at `604.509965`.
The previously failed run on Gaea is available at 
```/lustre/f2/scratch/Fernando.Andrade-maldonado/FV3_RT/rt_21322/cpld_bmark_p8_intel/```

**Comment by BrianCurtis-NOAA** [comment]
I don't understand. Were all baselines generated on RDHPCS or just the new ones listed in this PR ?

**Comment by jkbk2004** [comment]
On hera, I confirm that only nssl and wof cases change results.

**Comment by zach1221** [comment]
Right, just regional_wofs, rrfs_v1nssl, and rrfs_v1nssl_nohailnoccn baselines changed.

**Comment by BrianCurtis-NOAA** [comment]
> On hera, I confirm that only nssl and wof cases change results.

I copied over the 20231024 baselines to 20231102 and did baselines for the nssl/wofs tests and a large percentage of my tests failed in comparison.

I wanted to confirm in the process of creating baselines, that you copied over the old baselines to the new baselines and added the changed baselines.

**Comment by BrianCurtis-NOAA** [comment]
I will re-do my git clone and try once more.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA yes, I copied existing from 20231024 over to 20231102, then created new ones for those three cases mentioned previously, added them to 20231102. Then finally ran the matching against 20231102.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA yes, I copied existing from 20231024 over to 20231102, then created new ones for those three cases mentioned previously, added them to 20231102. Then finally ran the matching against 20231102.

Thanks Zach, then it was probably me. Apologies for the delay.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA acorn test underway?

**Comment by zach1221** [comment]
Regression testing is complete. I'll follow up on the ccpp-physics PR to begin the merging process.

**Comment by zach1221** [comment]
@MicroTed please revert .gitmodule url changes and update the submodule hash for fv3atm. 
hash:0dbc9ed837c3b179f545696ef93ac950e1f816ea

**Comment by MicroTed** [comment]
@zach1221  Thanks! They should be updated now

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
