### PR TITLE
Add CICE end of run restart file capability+Update submodule FV3/atmos_cubed_sphere to fix a typo when printing out the nest grid corner locations #2323+Bump urllib3 from 2.2.1 to 2.2.2 in /doc/UsersGuide #2329 + Orion changes for switch to new OS - Rocky-9 #2336

### LINKED ISSUE #1207: allow cice, cmeps and mom6 to write restarts at end of run
## Description
Currently these restarts are controlled as frequencies. If the run ends prior to the next frequency unit, no restart is written. Implementing this will allow additional flexibility in RT design.

## Solution

Restart writing needs to be linked to the stop_alarm.

## Related

-MOM6 https://github.com/NOAA-EMC/MOM6/issues/90

### LINKED ISSUE #2236: Ensure restart-at-end functionality is working in CMEPS
## Description
This UFS WM issue is related to CMEPS issue https://github.com/NOAA-EMC/CMEPS/issues/118.
It will allow UFS WM to write out CMEPS restart files at the end of whole integration.

### PR DESCRIPTION
**Pull request by dpsarmie**
The CICE hash includes changed that will add the ability to write a restart file at the end of the run via the CMEPS configuration. This is in conjunction with a similar PR for the MOM6 model.

## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR adds changes to the CICE submodule that allows for the creation of restart files at the end of the model run. This option is controlled in CMEPS via the write_restart_at_endofrun config option. This should allow for files to be written when the interval write time does not sync up with the total run time (ex. 27h forecast with 12h restart write intervals).  This change was also done in another PR for MOM6.

### Commit Message:
```
  * CICE - Adds restart write capability at the end of a run for CICE
  * FV3 - 
    * atmos_cubed_sphere - Update submodule FV3/atmos_cubed_sphere to fix a typo when printing out the nest grid corner locations
    * doc/UsersGuide/requirements.txt: Bumps [urllib3](https://github.com/urllib3/urllib3) from 2.2.1 to 2.2.2.
    * Orion Spack stack modulefile update: Rocky-9
    * update detect_machine.sh: hercules
```

### Priority:
* Normal

## Git Tracking
* Closes #2236 and [CMEPS issue 118](https://github.com/NOAA-EMC/CMEPS/issues/118)
* Closes #1207

### Sub component Pull Requests:
* UFS-WM: https://github.com/ufs-community/ufs-weather-model/pull/2336
* CICE: https://github.com/NOAA-EMC/CICE/pull/77
* FV3ATM:  (https://github.com/NOAA-EMC/fv3atm/pull/847) PR-2323
* atmos_cubed_sphere: (https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/341) PR-2323

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@dpsarmie Since at this point we'd have the capability to turn this for CMEPS, CICE and MOM6, we'd want to add a configurable setting to the various ufs.configure files. We can set that false by default, but that will allow the G-W to set it optionally .true.

**Comment by dpsarmie** [comment]
> @dpsarmie Since at this point we'd have the capability to turn this for CMEPS, CICE and MOM6, we'd want to add a configurable setting to the various ufs.configure files. We can set that false by default, but that will allow the G-W to set it optionally .true.

@DeniseWorthen That makes sense.  The change will be rolled into this PR. The ufs.configure files have been changed and retested everything for completeness.

**Comment by DeniseWorthen** [comment]
@dpsarmie We need this as a configurable variable, so that users can set it true if they need to but we can use false in the RT.

**Comment by DeniseWorthen** [comment]
@dpsarmie Thanks for making those changes. I think this is ready.

**Comment by dpsarmie** [comment]
@DeniseWorthen Ok great! The RTs just finished on Hercules using the latest version of the branch and it was good to go on my end.

**Comment by jkbk2004** [comment]
@dpsarmie can you sync up branches? We like to start working on this pr. Can you combine in #2323 to this pr? Just need to points to @BinLiu-NOAA 's fv3 feature branch: https://github.com/NOAA-EMC/fv3atm/pull/847

**Comment by dpsarmie** [comment]
@jkbk2004 I just want ahead and edited the gitmodules file to point to Bin's branch and brought the PR up to date. Let me know if you need anything else.

**Comment by FernandoAndrade-NOAA** [comment]
@dpsarmie I'm not seeing Bin's latest commit in your FV3, only the latest  fv3 develop commit of 07c26d1 which does not look like it contains Bin's newer a6fdff7 for atmos cubed sphere. Could you double check your hashes for fv3/atmos cubed sphere?

`4fd5f0e` for FV3 and `a6fdff7` for atmos cubed sphere should be present

**Comment by dpsarmie** [comment]
@FernandoAndrade-NOAA Sorry, I had it in [1561588](https://github.com/ufs-community/ufs-weather-model/pull/2324/commits/1561588ceaeac2a0c27e86eba548eeb57db64a75) but then overwrote it back with the [e5b9eed](https://github.com/ufs-community/ufs-weather-model/pull/2324/commits/e5b9eed725baf8edb4a32f9600972e9048ca5989) commit. Looks like Jong made the update to the hash. Thanks Jong!

**Comment by jkbk2004** [comment]
@dpsarmie it looks reverted. Let me fix one more time. I will update urllib3 version as well: #2329

**Comment by jkbk2004** [comment]
All looks good. @FernandoAndrade-NOAA This PR is ready for testing. @zach1221 I will check if I can run on Orion. @BrianCurtis-NOAA FYI

**Comment by zach1221** [comment]
> All looks good. @FernandoAndrade-NOAA This PR is ready for testing. @zach1221 I will check if I can run on Orion. @BrianCurtis-NOAA FYI

I followed up on the fv3atm for a review.

**Comment by zach1221** [comment]
@dpsarmie @jkbk2004 fyi, cpld_debug_gfsv17_intel is failing consistently on Derecho. There are a bunch of unused line warnings for INPUT/MOM_input. Error logs are here: /glade/derecho/scratch/zshrader/FV3_RT/rt_96451/cpld_debug_gfsv17_intel
The test dies with message: forrtl: error (65): floating invalid

Trying with develop branch now to see what happens.

**Comment by DeniseWorthen** [comment]
The warnings are just warnings and always appear. The line is question 
```
libpthread-2.31.s  000014C29057C8C0  Unknown               Unknown  Unknown
fv3.exe            0000000012250BF8  med_mp_datainitia        2147  med.F90
```

is not being changed and the ufs.configure (where it is reading the real_ntile) is also not changed.

**Comment by zach1221** [comment]
The cpld_debug_gfsv17_intel case passes when running on the develop branch.

**Comment by DeniseWorthen** [comment]
@dpsarmie It doesn't look like you updated your CICE hash to include the change to the cice-wrapper.

**Comment by jkbk2004** [comment]
@dpsarmie I see your feature branch has one more commit: https://github.com/dpsarmie/CICE/commit/9733e45c9219eba27a7632ddc0de5b338cca6b5d?

**Comment by DeniseWorthen** [comment]
I ran the test at develop on derecho, but added the ``write_restart_at_endofrun = .false.`` to the ufs.configure and it failed. So something odd is going on.

**Comment by zach1221** [comment]
> I ran the test at develop on derecho, but added the `write_restart_at_endofrun = .false.` to the ufs.configure and it failed. So something odd is going on.

Yes, I just did this as well, with same result.

**Comment by DeniseWorthen** [comment]
@zach1221 Can you check and make sure other debug tests that use CMEPS and also have this new config set (eg ``datm_cdeps_debug_cfsr`` or ``hafs_regional_storm_following_1nest_atm_ocn_debug`` or ``cpld_debug_pdlib_p8`` ) do run on derecho?

**Comment by zach1221** [comment]
> @zach1221 Can you check and make sure other debug tests that use CMEPS and also have this new config set (eg `datm_cdeps_debug_cfsr` or `hafs_regional_storm_following_1nest_atm_ocn_debug` or `cpld_debug_pdlib_p8` ) do run on derecho?

Sure, I'll run them again.

**Comment by DeniseWorthen** [comment]
The change that Dan just added won't impact any RT. It just changes the name of the CICE forecast log from fXXX to fXXXX.

**Comment by zach1221** [comment]
> The change that Dan just added won't impact any RT. It just changes the name of the CICE forecast log from fXXX to fXXXX.

Ok, understood. Also I can confirm that datm_cdeps_debug_cfsr , hafs_regional_storm_following_1nest_atm_ocn_debug and cpld_debug_pdlib_p8 are all still passing.

**Comment by DeniseWorthen** [comment]
@zach1221 I'd like to copy over one of your other debug test rundirs. Where are they located?

**Comment by jkbk2004** [comment]
As some debugging is needed, I propose to move to #2290 (priority PR) first. @zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA  FYI

**Comment by zach1221** [comment]
> @zach1221 I'd like to copy over one of your other debug test rundirs. Where are they located?

Apologies for the delay. Please see rundir below for failed case.
/glade/derecho/scratch/zshrader/FV3_RT/rt_96451/cpld_debug_gfsv17_intel

**Comment by DeniseWorthen** [comment]
@zach1221 I think you misunderstood. You said that you could confirm that the other debug tests ran OK on derecho. Where are those rundirs located?

**Comment by zach1221** [comment]
> @zach1221 I think you misunderstood. You said that you could confirm that the other debug tests ran OK on derecho. Where are those rundirs located?

Sure, location is here.
/glade/derecho/scratch/zshrader/FV3_RT/rt_10335

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 We are OK disabling that test on Derecho and moving forward. Please create an issue with all we've learned about the problem so we can follow up on fixing it.

**Comment by jkbk2004** [comment]
@dpsarmie @zach1221 can we create git issue to follow on derecho cpld_debug_gfsv17_intel failure ? We can turn off the case on derecho and go for merging. @BrianCurtis-NOAA @DeniseWorthen would it be ok?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA Thanks!

**Comment by jkbk2004** [comment]
https://github.com/ufs-community/ufs-weather-model/issues/2338

**Comment by jkbk2004** [comment]
Sorry for the delay. But we can move on for merging process with cpld_debug_gfsv17_intel disabled on derecho.

**Comment by DeniseWorthen** [comment]
@jkbk2004 We don't have a derecho log yet.

**Comment by FernandoAndrade-NOAA** [comment]
Ok I think we're set to continue, the failed test in the Derecho log has already been disabled in a previous commit.

**Comment by DeniseWorthen** [comment]
CICE has been merged hash [9452de8](https://github.com/NOAA-EMC/CICE/commit/9452de8c3cb43fb2628f0722e6a51f79429d2160)

**Review by jkbk2004 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Pull request merged**
