### PR TITLE
Update in-line post for RRFS and GFS

### LINKED ISSUE #1688: Update in-line post read interface for RRFS and GFS
## Description
The UPP off-line post read interface has been updates with changes for RRFS and GFS development at the UPP repository.

## Solution
These changes should be sync to the read interface for in-line post.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
## Description
Update in-line post for RRFS and GFS:

- Update upp submodule revision
- Sync the read interface changes from off-line post to in-line post for RRFS and GFS
- Sync the read interface changes from off-line post to in-line post for GEFS-Aerosols model and CCPP-CHEM model
- Rename global FV3 in-line post itag file from post_itag to post_itag_gfs
- Rename global FV3 in-line post control files from postxconfig-NT.txt to postxconfig-NT-gfs.txt, and postxconfig-NT_FH00.txt to postxconfig-NT-gfs_FH00.txt

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 
There will be changes of in-line post results in grib2 GFSPRS* for global FV3 tests due to new fields added, such as test control_p8.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Please link dependent pull requests.
Depends on NOAA-EMC/fv3atm/pull/641

Please link the related issues to be closed with this PR, whether in this repository, or in another repository.
Closes [1688](https://github.com/ufs-community/ufs-weather-model/issues/1688)

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Review by junwang-noaa — DISMISSED** [review]
Looks good to me

**Comment by jkbk2004** [comment]
@WenMeng-NOAA #1704 was merged. Can you sync up branch? Also, if you have a regression test log, you may attach. Once @junwang-noaa @DusanJovic-NOAA approve the fv3 pr, we can start testing with Jenkins-ci first.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 I just synced my UFS branch and FV3 branch. I started on the regression tests on WCOSS2.

**Comment by WenMeng-NOAA** [comment]
The regression test on WCOSS2 Dogwood was finished with new baseline at /u/wen.meng/ptmp/FV3_RT/REGRESSION_TEST_INTEL

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Is there a Hera or Cheyenne Intel/GNU RT attached?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @WenMeng-NOAA tested on wcoss2. But I was checking yesterday hera to see how many baseline changes. Looked like running ok. I will attach hera logs.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA @WenMeng-NOAA tested on wcoss2. But I was checking yesterday hera to see how many baseline changes. Looked like running ok. I will attach hera logs.

@jkbk2004 OK. I think it's important to have the RT's that compare against previous baselines as it is the data that shows us what RT's change.

**Comment by BrianCurtis-NOAA** [comment]
@WenMeng-NOAA I see you updated your FV3 commit hash. Are there any other changes you need? We typically need to restart RT's if there are any major commits to the PR repo.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I see you updated your FV3 commit hash. Are there any other changes you need? We typically need to restart RT's if there are any major commits to the PR repo.

@BrianCurtis-NOAA There should no changes expected from my commit today comparing the RT conducted yesterday.

**Comment by jkbk2004** [comment]
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11223904/RegressionTests_hera.intel.log)
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11223907/RegressionTests_hera.gnu.log)

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1296973670/20230413085212/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_1501
Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1296973670/20230413092902/ufs-weather-model
[RT] Error: Test control_stochy 002 failed in run_test failed 
[RT] Error: Test control_ras 003 failed in run_test failed 
[RT] Error: Test control_p8 004 failed in run_test failed 
[RT] Error: Test rap_control 005 failed in run_test failed 
[RT] Error: Test rap_decomp 006 failed in run_test failed 
[RT] Error: Test rap_2threads 007 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 009 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 010 failed in run_test failed 
[RT] Error: Test hrrr_control 012 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 013 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp 014 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 016 failed in run_test failed 
[RT] Error: Test rap_control_dyn32_phy32 037 failed in run_test failed 
[RT] Error: Test hrrr_control_dyn32_phy32 038 failed in run_test failed 
[RT] Error: Test rap_2threads_dyn32_phy32 039 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads_dyn32_phy32 040 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp_dyn32_phy32 041 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32 044 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1296973670/20230413090711/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_66556
Test hafs_regional_atm_ocn 084 failed in run_test failed 
Test regional_atmaq 120 failed in run_test failed 
Test regional_atmaq_faster 121 failed in run_test failed 
Test compile_022 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2:
```
Test cpld_bmark_p8 004 failed in run_test failed
Test control_latlon 012 failed in run_test failed
Test control_wrtGauss_netcdf_parallel 013 failed in run_test failed
Test control_c192 015 failed in run_test failed
Test control_c384 016 failed in run_test failed
Test control_c384gdas 017 failed in run_test failed
Test control_stochy 018 failed in run_test failed
Test control_lndp 019 failed in run_test failed
Test control_iovr4 020 failed in run_test failed
Test control_iovr5 021 failed in run_test failed
Test control_p8 022 failed in run_test failed
Test control_p8_lndp 023 failed in run_test failed
Test control_p8_rrtmgp 024 failed in run_test failed
Test control_p8_mynn 025 failed in run_test failed
Test merra2_thompson 026 failed in run_test failed
Test rap_control 031 failed in run_test failed
Test rap_sfcdiff 033 failed in run_test failed
Test hrrr_control 034 failed in run_test failed
Test rrfs_v1beta 035 failed in run_test failed
Test rrfs_v1nssl 036 failed in run_test failed
Test rrfs_v1nssl_nohailnoccn 037 failed in run_test failed
Test control_csawmg 042 failed in run_test failed
Test control_csawmgt 043 failed in run_test failed
Test control_ras 044 failed in run_test failed
Test control_p8_faster 046 failed in run_test failed
Test rap_control_dyn32_phy32 073 failed in run_test failed
Test hrrr_control_dyn32_phy32 074 failed in run_test failed
Test rap_control_dyn64_phy32 075 failed in run_test failed'
Test atmaero_control_p8 095 failed in run_test failed
Test atmaero_control_p8_rad 096 failed in run_test failed
Test atmaero_control_p8_rad_micro 097 failed in run_test failed
```
From control_p8:
```
+ mpiexec -n 256 -ppn 128 -depth 1 ./fv3.exe
Using non-aerosol-aware version of Thompson microphysics
   calling table_ccnAct routine
   creating qc collision eff tables
   creating rain evap table
   creating ice converting to snow table
   creating rain collecting graupel table
   creating freezing of water drops table
  ... DONE microphysical lookup tables
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fv3.exe            0000000003FDBEDA  Unknown               Unknown  Unknown
libpthread-2.31.s  0000148BF84C18C0  Unknown               Unknown  Unknown
fv3.exe            0000000001CA7BA4  post_fv3_mp_set_p        2403  post_fv3.F90
fv3.exe            0000000001C18AF2  post_fv3_mp_post_         157  post_fv3.F90
```

**Comment by WenMeng-NOAA** [comment]
Please hold on RT testing. I will run single test for new changes committed today.

**Comment by FernandoAndrade-NOAA** [comment]
Attached are the jenkins-ci log, ORTs did not pass
[ufs-weather-model » ort-docker-pipeline » PR-1690 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11226149/ufs-weather-model.ort-docker-pipeline.PR-1690.1.Console.Jenkins.pdf)

**Comment by WenMeng-NOAA** [comment]
The changes at FV3 were finalized. My UFS branch is ready for RT testing.

**Comment by WenMeng-NOAA** [comment]
The UFS RT testing can be run through on WCOSS2. The new baseline is at /u/wen.meng/ptmp/FV3_RT/REGRESSION_TEST_INTEL on WCOSS2 dogwood. @BrianCurtis-NOAA @jkbk2004 @FernandoAndrade-NOAA

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1296973670/20230413144514/ufs-weather-model
[BL] Error: Test cpld_control_p8 033 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1296973670/20230413150014/ufs-weather-model
[BL] Error: Test hafs_regional_atm_wav 087 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_ocn_wav 088 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn_debug 097 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 098 failed in run_test failed 
[BL] Error: Test hafs_regional_docn_oisst 100 failed in run_test failed 
[BL] Error: Test hafs_regional_datm_cdeps 101 failed in run_test failed 
[BL] Error: Test datm_cdeps_control_cfsr 102 failed in run_test failed 
[BL] Error: Test datm_cdeps_control_gefs 103 failed in run_test failed 
[BL] Error: Test datm_cdeps_iau_gefs 104 failed in run_test failed 
[BL] Error: Test datm_cdeps_stochy_gefs 105 failed in run_test failed 
[BL] Error: Test datm_cdeps_ciceC_cfsr 106 failed in run_test failed 
[BL] Error: Test datm_cdeps_bulk_cfsr 107 failed in run_test failed 
[BL] Error: Test datm_cdeps_bulk_gefs 108 failed in run_test failed 
[BL] Error: Test datm_cdeps_mx025_cfsr 109 failed in run_test failed 
[BL] Error: Test datm_cdeps_mx025_gefs 110 failed in run_test failed 
[BL] Error: Test datm_cdeps_3072x1536_cfsr 111 failed in run_test failed 
[BL] Error: Test datm_cdeps_gfs 112 failed in run_test failed 
[BL] Error: Test datm_cdeps_debug_cfsr 113 failed in run_test failed 
[BL] Error: Test datm_cdeps_control_cfsr_faster 114 failed in run_test failed 
[BL] Error: Test datm_cdeps_lnd_gswp3 115 failed in run_test failed 
[BL] Error: Test control_p8_atmlnd_sbs 116 failed in run_test failed 
[BL] Error: Test atmwav_control_noaero_p8 117 failed in run_test failed 
[BL] Error: Test control_atmwav 118 failed in run_test failed 
[BL] Error: Test atmaero_control_p8 119 failed in run_test failed 
[BL] Error: Test atmaero_control_p8_rad 120 failed in run_test failed 
[BL] Error: Test atmaero_control_p8_rad_micro 121 failed in run_test failed 
[BL] Error: Test regional_atmaq 122 failed in run_test failed 
[BL] Error: Test regional_atmaq_debug 123 failed in run_test failed 
[BL] Error: Test regional_atmaq_faster 124 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by jkbk2004** [comment]
All tests are done. Gaea and acorn tests will be skipped. We can start merging this pr. @WenMeng-NOAA can you update fv3 hash and revert change in gitmodules?

**Comment by WenMeng-NOAA** [comment]
> All tests are done. Gaea and acorn tests will be skipped. We can start merging this pr. @WenMeng-NOAA can you update fv3 hash and revert change in gitmodules?

Done! @jkbk2004

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
