### PR TITLE
Split CCPP finalize into physics_finalize and (framework) finalize, fix CCPP's metadata2html.py

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR updates the submodule pointers for fv3atm and ccpp-physics for the changes in the dependent PRs below. In brief:
- fv3atm: split CCPP finalize into `physics_finalize` and (framework) `finalize`; minor CCPP cleanup and documentation updates
- ccpp-framework: Fix `metadata2html.py` (scientific documentation generator), add some more documentation to `ccpp_prebuild.py`

### Issue(s) addressed

- fixes https://github.com/NCAR/ccpp-framework/issues/437

### Preliminary regression testing

Regression tests pass against existing baselines on Hera with Intel and GNU.

[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/8147405/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/8147406/RegressionTests_hera.intel.log)

### Final regression testing

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NCAR/ccpp-framework/pull/438
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/487

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Hey @climbfuji We've been pushing that all UFS PR's have a related/linked UFS Issue. Could you please make sure this has one?

**Comment by climbfuji** [comment]
@BrianCurtis-NOAA I am quoting the above instructions:

> An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR  are specified below.

An issue has been created in ccpp-framework, which is one of the sub-components, as per instructions. There are no changes in the ufs-weather-model branch, just submodule pointer updates, therefore creating an issue here instead of where it belongs doesn't make too much sense to me.

**Comment by climbfuji** [comment]
@MinsukJi-NOAA run-ci failed with
```
Step 15/16 : RUN ./opnReqTest -n $test_name -c $build_case -z && tar -cvzf fv3.tar.gz fv3_*.exe modules.fv3_*
[114](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:114)
 ---> Running in 3b18b1b9757b
[115](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:115)
3b18b1b9757b
[116](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:116)
WARNING: UNKNOWN PLATFORM
[117](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:117)
test name: cpld_control_c96_p8
[118](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:118)
cases to compile: std
[119](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:119)
compiling std with compile option -DAPP=S2SW -DUFS_GOCART=ON -DCCPP_SUITES=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1,FV3_GFS_v16_coupled_p7_rrtmgp,FV3_GFS_v17_coupled_p8
[120](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:120)
Died with error code 1
[121](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:121)
The command '/bin/sh -c ./opnReqTest -n $test_name -c $build_case -z && tar -cvzf fv3.tar.gz fv3_*.exe modules.fv3_*' returned a non-zero code: 1
[122](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:122)

[123](https://github.com/ufs-community/ufs-weather-model/runs/5500141320?check_suite_focus=true#step:3:123)
Error: Process completed with exit code 1.
```
Do you know why?

**Comment by junwang-noaa** [comment]
@climbfuji The wcoss RT finished successfully and the log files are at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
Hash for fv3atm updated ([b2272de](https://github.com/NOAA-EMC/fv3atm/commit/b2272dea5d2eec97e267a920e5a7af11c52f431b)), apart from the CI issue - unrelated to this PR - it's ready to merge.

**Pull request merged**
