### PR TITLE
Add bash linting to CI. Cleanup .sh scripts a bit. Address .sh bugs. Adds -v Verbose option. (#2218)  Remove nowarn Intel compiler flag

### LINKED ISSUE #1984: Compiler warnings may not be suppressed
Currently in the top-level cmake and in atmos_cube_sphere cmake we use the `-nowarn` flag (Intel compiler) which suppress all compiler warnings. 

```
$ grep -r nowarn .
./cmake/Intel.cmake:set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -g -traceback -fpp -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte -qno-opt-dynamic-align")
./FV3/atmos_cubed_sphere/cmake/compiler_flags_Intel_Fortran.cmake:set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -g -traceback -fpp -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte -qno-opt-dynamic-align ${${kind}_flags}")
```

According to "[NCEP Central Operations WCOSS Implementation Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf
)" this is not allowed (page 15 section IV B. (5)):

_"Code must compile without errors or warnings. Errors and warnings may not be suppressed, and the compiler warning level ("-W" options) must be at least the default one."_

We should remove this flag (from ufs-weather-model and atmos_cubed_sphere) and start working on eliminating all warnings.

### LINKED ISSUE #2087: RT "passes" even when multiple tests fail due to Disk quota error
## Description

I attempted to run a full RT on Hera for a PR. I got a successful log file but happened to notice the last test in the log, which should be ``datm_cdeps_control_cfsr_gnu`` test was not the last test in the log. The final test was 

```
Test 213 control_wam_debug_gnu PASS
``` 

I then looked at the run_ files in ``logs/log_hera`` and found 52 tests which failed due to disk quota. The RT run directory was deleted and no ``fail`` files were present in the tests directory. 

See /scratch1/NCEPDEV/nems/Denise.Worthen/WORK/ufs_dw/tests

### LINKED ISSUE #2109: Bring in "ShellCheck" linting as a GH action for any changes in shell scripts
## Description

Proper/consistent syntax for shell scripts is important. Currently there are inconsistencies in the UFSWM bash scripts.

## Solution

Consistent with the global workflow group, we should bring in a github action that checks any and all shell script changes from PR's and verifies they meet consistent standards. This capability is provided by ShellCheck (https://www.shellcheck.net/).

All current bash scripts should be cleaned up using ShellCheck, and a github action should be created and used to make sure future script changes meet that standard.

### LINKED ISSUE #2148: Broken symlinks for run_dir cause rt.sh to not remove symlink and error out when trying to create new link.
## Description

Broken symlinks for run_dir cause rt.sh to not remove symlink and error out when trying to create new link.

### To Reproduce:

- Run rt.sh
- remove the actual location of run_dir, do not touch symlink
- Run rt.sh

### Fix?
Try using -L check along with -e to weed out if the symlink is broken.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

- Add bash linting to CI:
  - uses superlinter to check for consistent bash code writing
- Cleans up .sh scripts to comply with superlinter
- Cleans up .sh scripts to be more consistent, easier to read.
- Add's -v verbose option if debugging outputs needed, otherwise simplifies rt.sh run echo's.
- Addresses smaller bugs
  - quota/timeout search logic adjusted.
  - check for dirs existing (DISKNM, STMP, PTMP) before starting.
  - adjustments/cleanup to ecflow/rocoto sections
  - rt.sh will attempt to start ecflow, and only stop ecflow if it started from rt.sh.
  - fix for issue where run_dir will not delete properly.
- Remove -nowarn compiler flag from cmake/Intel.cmake
- Explicitly disable two warnings:
  - warning #5462: Global name too long.
  - remark #7712: This variable has not been used.
### Commit Message:

```
* UFSWM
- Add bash linting to CI:
  - uses superlinter to check for consistent bash code writing
- Cleans up .sh scripts to comply with superlinter
- Cleans up .sh scripts to be more consistent, easier to read.
- Add's -v verbose option if debugging outputs needed, otherwise simplifies rt.sh run echo's.
- Addresses smaller bugs
  - quota/timeout search logic adjusted.
  - check for dirs existing (DISKNM, STMP, PTMP) before starting.
  - adjustments/cleanup to ecflow/rocoto sections
  - rt.sh will attempt to start ecflow, and only stop ecflow if it started from rt.sh.
  - fix for issue where run_dir will not delete properly.
* FV3: Address compiler warnings
  * atmos_cubed_sphere: Address compiler warnings.
```

### Priority:

* Normal

### UFSWM:

* Closes #2109
* Closes #1984 
* Closes #2087  
* Closes #2148 
### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/813
  * atmos_cubed_sphere: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/324
* stochastic_physics: https://github.com/NOAA-PSL/stochastic_physics/pull/78

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
I've brought over all info from #2218 and am running the full RT suite on Hera to double check no baselines are changing.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA hercules, and orion are running fine. Derecho keeps aborting though when I try to use ecflow. If I attempt to run sequentially, without a workflow, rt.sh will just exit. Can you try running a job on Derecho as well, to see the behavior?

**Comment by zach1221** [comment]
Also, ORT fails on control_p8_gnu.
+ echo 'rt_utils.sh: std_base: Computing PET bounds and tasks.'
rt_utils.sh: line 83: RTVERBOSE: unbound variable
Died with error code 1

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 try adding to the opnreq script `export RTVERBOSE=false` early enough that when you source rt_utils it will see RTVERBOSE.

I'll run on Derecho this AM and see what I can see.

**Comment by zach1221** [comment]
Still working the derecho issue, fyi. Everything else should be done.

**Comment by zach1221** [comment]
Ok jobs are running now on Derecho.

**Comment by zach1221** [comment]
Ok we're ready to merge finally.

**Comment by BrianCurtis-NOAA** [comment]
Almost, I would like a little time to see if i can get Acorn finished.

**Comment by BrianCurtis-NOAA** [comment]
Skipping Acorn. Start merge.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA fv3atm merged. Hash: https://github.com/NOAA-EMC/fv3atm/commit/979bcab28f63b37411698cd9d23d04d0b0fe3a7e

**Comment by BrianCurtis-NOAA** [comment]
I have the FV3 updated, but waiting on stochastic_physics before pushing. Who normally merges in stochastic_physics?

**Comment by zach1221** [comment]
> I have the FV3 updated, but waiting on stochastic_physics before pushing. Who normally merges in stochastic_physics?

Oh, Phil Pegion generally. I can leave a comment there.

**Comment by zach1221** [comment]
Ok, @BrianCurtis-NOAA . We should be ready now, Stoch Physics is merged.

**Review by jkbk2004 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Shouldn't you link other bug reports so that they'll be closed ? 2087 maybe 2150 and also 2148?

**Comment by DeniseWorthen** [comment]
I've added the additional issues close. I'm not sure if #2150 is fixed, so I'll leave that open for now.

**Pull request merged**
