### PR TITLE
Update CMEPS to allow CICE6 albedos -> ATM

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Updates CMEPS to allow CICE6 albedos to be exported to ATM

### Issue(s) addressed

Issue #700 

## Testing

Testing on Hera.intel and gnu (coupled and datm/cdeps RTs only) shows that new baselines will be required for coupled tests because of the additional albedo fields present in the coupler restart file. All other files compared for coupled tests are B4B. 

[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/6871388/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/6871389/RegressionTests_hera.intel.log)

The control_c192 regression test was run for 5 days and the mediator history files were written at each pass through the fast coupling loop. The following figure shows the 4 components of albedo exported to the ATM at approximately 180E,78N on tile 3:

atmexp tile3 albedo

The following figure shows the 4 components of albedo exported to the ATM at approximately 20E,65S  on tile 6:

atmexp tile6 albedo

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- cheyenne.intel (skipped, machine down all week)
- cheyenne.gnu (skipped, machine down all week)
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1071979849

## Dependencies

CMEPS PR [#55](https://github.com/NOAA-EMC/CMEPS/pull/55)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/696192749/20210727150038/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_5346
Please make changes and add the following label back:
hera-gnu-BL

**Comment by DeniseWorthen** [comment]
Sorry everyone. I forgot to update the BLDATE.

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/696192749/20210727150009/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_19204
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/696192749/20210727151517/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_15148
Test control_atmwav 085 failed in run_test failed 
Test datm_mx025_cfsr 075 failed in run_test failed 
Test datm_mx025_gefs 076 failed in run_test failed 
Test datm_cdeps_mx025_gefs 083 failed in run_test failed 
Test control_atm_aerosols 086 failed in run_test failed 
Test datm_cdeps_mx025_cfsr 082 failed in run_test failed 
Test fv3_gsd_debug 064 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 069 failed in run_test failed 
Test fv3_gsd_diag_debug 065 failed in run_test failed 
Test datm_debug_cfsr 077 failed in run_test failed 
Test datm_cdeps_debug_cfsr 084 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/696192749/20210727100009/ufs-weather-model
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/696192749/20210727150010/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_240734
Test regional_control 031 failed in run_test failed 
Test cpld_control_c384 004 failed in run_test failed 
Test control_c384gdas 016 failed in run_test failed 
Test cpld_bmark_wave_v16 007 failed in run_test failed 
Test cpld_control_wave 009 failed in run_test failed 
Test cpld_bmark_v16 005 failed in run_test failed 
Test cpld_bmark_v16_nsst 006 failed in run_test failed 
Test control_lndp 019 failed in run_test failed 
Test control_ca 018 failed in run_test failed 
Test control_thompson 028 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 013 failed in run_test failed 
Test control_lseaspray 021 failed in run_test failed 
Test control_lheatstrg 020 failed in run_test failed 
Test control_flake 025 failed in run_test failed 
Test control_ras 027 failed in run_test failed 
Test control_CubedSphereGrid 012 failed in run_test failed 
Test control_ugwpv1 026 failed in run_test failed 
Test control_noahmp 030 failed in run_test failed 
Test control_rrtmgp 023 failed in run_test failed 
Test control_thompson_no_aero 029 failed in run_test failed 
Test control_stochy 017 failed in run_test failed 
Test control 011 failed in run_test failed 
Test cpld_bmark_wave_v16_p7b 008 failed in run_test failed 
Test control_csawmgt 024 failed in run_test failed 
Test control_c384 015 failed in run_test failed 
Test cpld_ca 002 failed in run_test failed 
Test cpld_control 001 failed in run_test failed 
Test control_merra2 022 failed in run_test failed 
Test cpld_control_c192 003 failed in run_test failed 
Test control_c192 014 failed in run_test failed 
Test regional_quilt_hafs 034 failed in run_test failed 
Test regional_quilt 033 failed in run_test failed 
Test regional_quilt_netcdf_parallel 035 failed in run_test failed 
Test regional_quilt_RRTMGP 036 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
All RTs are complete and gitmodules have been update. Ready to merge. @BrianCurtis-NOAA can you please review?

**Review by BrianCurtis-NOAA — APPROVED** [review]
Confirmed hash's as well. Looks good.

**Pull request merged**
