### PR TITLE
 Add an option in dynamics to calculate omega in non-hydrostatic runs similar to hydrostatic method

### LINKED ISSUE #1970: control_ras fails to compare on Acorn
### To Reproduce:

./rt.sh -n control_ras intel

## Output

```
Job id 2445311
TEST 001 control_ras_intel is waiting to enter the queue
TEST 001 control_ras_intel is submitted 
1 min. TEST 001 control_ras_intel is running,  status: R jobid 2445311
2 min. TEST 001 control_ras_intel is running,  status: R jobid 2445311
3 min. TEST 001 control_ras_intel is running,  status: R jobid 2445311
4 min. TEST 001 control_ras_intel is running,  status: R jobid 2445311
qstat: 2445311.abqs01 Job has finished, use -x or -H to obtain historical job information
qstat: 2445311.abqs01 Job has finished, use -x or -H to obtain historical job information
5 min. TEST 001 control_ras_intel is finished,  status: - jobid 2445311
+ [[ false = false ]]
+ check_results
+ '[' -o xtrace ']'
+ set_x='set -x'
+ set +x

baseline dir = /lfs/h1/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20231024/control_ras_intel
working dir  = /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_59169/control_ras_intel
Checking test 001 control_ras_intel results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf024.nc ............ALT CHECK......NOT OK
 Comparing atmf000.nc ............ALT CHECK......NOT OK
 Comparing atmf024.nc ............ALT CHECK......NOT OK
 Comparing GFSFLX.GrbF00 .........OK
 Comparing GFSFLX.GrbF24 .........NOT OK
 Comparing GFSPRS.GrbF00 .........NOT OK
 Comparing GFSPRS.GrbF24 .........NOT OK
Test 001 control_ras_intel FAIL Tries: 2
```

### PR DESCRIPTION
**Pull request by XiaqiongZhou-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

This is to bring an update in dycore. An option is added in dynamics to calculate the omega in non-hydrostatics runs similar to hydrostatic method.

### Commit Message:

```
    * atmos_cubed_sphere - 
                         A new parameter, pass_full_omega_to_physics_in_non_hydrostatic_mode, has been added in 
                         dycore. When set to true, the omega calculation will match that of hydrostatic runs, using the 
                         formula omega = dp/dt. The default value is false, where the calculation remains
                         omega = w * dp/dz as before.
```

### Priority:

* Closes https://github.com/ufs-community/ufs-weather-model/issues/1970

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/849
  * atmos_cubed_sphere : https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/344/

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [ ] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by zach1221** [comment]
@XiaqiongZhou-NOAA would you be able to sync up your PR branches and provide Hera regression testing log for this PR?

**Comment by jkbk2004** [comment]
@zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA This PR is ready.

**Comment by FernandoAndrade-NOAA** [comment]
Please be aware that there may be issues with the Jet RTs, there has been a reduction in performance due to hardware failures. The Jet support team is working on getting those resolved. I have a run going right now, but it is extremely slow. @jkbk2004 FYI

**Comment by BrianCurtis-NOAA** [comment]
Hercules logs show two failed tests due to timeout

**Comment by zach1221** [comment]
> Hercules logs show two failed tests due to timeout

Yes, we think they are failing due to spack issue with mvapich2. It shows as timeout though in the rt log.

**Comment by jkbk2004** [comment]
Can we move on for merging? It's better to catch up subcomponent PR to be merged. I mean due to July 4 schedule.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
