### PR TITLE
Compile CICE with safe CPU instructions

### LINKED ISSUE #1262: S2SWA app crashes on xjet when initializing CICE
## Description
The model crashes on xjet at line 1146 of ice_init.F90 with an "illegal instruction" error when initializing the CICE component.  This is verified for the S2SWA app, but is likely also true for any S2S* app.

I believe I have tracked it down to the CMakeLists.txt in CICE-interface, which appends `-xHOST` to `CMAKE_Fortran_FLAGS` [on line 10](https://github.com/ufs-community/ufs-weather-model/blob/4376018fb484033f2c1cf73c7993a0bd4489ada9/CICE-interface/CMakeLists.txt#L10).

### To Reproduce:
What compilers/machines are you seeing this with?  Intel 18.0.5.274 and IMPI 2018.4.274
Give explicit steps to reproduce the behavior.
1. Check out revision [5c2d1a92](https://github.com/ufs-community/ufs-weather-model/commit/5c2d1a92) (or likely newer)
2. Compile the model on one of the head nodes
3. Copy the executable into a run directory
4. Submit a slurm job to xjet (or likely any partition except kjet)

Note, I have not tested this on any other partition.

## Additional context
The regression tests also run on xjet, but they are also compiled there.

- Needed for noaa-emc/global-workflow/pull/357

## Output

**output logs**
The complete log is attached with a snippet of the crash itself shown below.

```
36 + srun -l --export=ALL -n 2844 /lfs1/NESDIS/nesdis-rdo2/David.Huber/para/stmp/RUNDIRS/upd_s2sw/2013040100/gfs/fcst.31082/ufs_model
   0:
   0:
   0: * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
   0:      PROGRAM ufs       HAS BEGUN. COMPILED       0.00     ORG: np23
   0:      STARTING DATE-TIME  JUN 07,2022  18:41:15.733  158  TUE   2459738
   0:
   0:
   0: UFS Aerosols: Initializing ...
2604:  (input_data) Reading setup_nml
2604:  (input_data) Reading grid_nml
2604:  (input_data) Reading tracer_nml
2604:  (input_data) Reading thermo_nml
2604:  (input_data) Reading dynamics_nml
2604:  (input_data) Reading shortwave_nml
2604:  (input_data) Reading ponds_nml
2604:  (input_data) Reading snow_nml
2604:  (input_data) Reading forcing_nml
2604:  Diagnostic output will be in file
2604:  ice_diag.d
2604:
2679: forrtl: severe (168): Program Exception - illegal instruction
2679: Image              PC                Routine            Line        Source
2679: ufs_model          0000000007AC602E  Unknown               Unknown  Unknown
2679: libpthread-2.17.s  00002BA83838F630  Unknown               Unknown  Unknown
2679: ufs_model          00000000073491E2  ice_init_mp_input        1146  ice_init.F90
2679: ufs_model          00000
[gfsfcst.log](https://github.com/ufs-community/ufs-weather-model/files/8863899/gfsfcst.log)
0000719B652  cice_initmod_mp_c          53  CICE_InitMod.F90
2679: ufs_model          0000000006F03E84  ice_comp_nuopc_mp         624  ice_comp_nuopc.F90
2679: ufs_model          0000000000A2EADE  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
2679: ufs_model          0000000000A32A96  ESMCI_FTableCallE         824  ESMCI_FTable.C
2679: ufs_model          0000000000DA6EAF  _ZN5ESMCI3VMK5ent        2308  ESMCI_VMKernel.C
2679: ufs_model          00000000010AEEBA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
2679: ufs_model          0000000000A30177  c_esmc_ftablecall         981  ESMCI_FTable.C
2679: ufs_model          00000000009462C1  esmf_compmod_mp_e        1222  ESMF_Comp.F90
2679: ufs_model          00000000009DB3B4  esmf_gridcompmod_        1407  ESMF_GridComp.F90
2679: ufs_model          00000000008EE29F  nuopc_driver_mp_l        2565  NUOPC_Driver.F90
2679: ufs_model          0000000000912D9C  nuopc_driver_mp_i        1264  NUOPC_Driver.F90
2679: ufs_model          000000000091BC65  nuopc_driver_mp_i         455  NUOPC_Driver.F90
2679: ufs_model          0000000000A2EADE  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
2679: ufs_model          0000000000A32A96  ESMCI_FTableCallE         824  ESMCI_FTable.C
2679: ufs_model          0000000000DA6EAF  _ZN5ESMCI3VMK5ent        2308  ESMCI_VMKernel.C
2679: ufs_model          00000000010AEEBA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
2679: ufs_model          0000000000A30177  c_esmc_ftablecall         981  ESMCI_FTable.C
2679: ufs_model          00000000009462C1  esmf_compmod_mp_e        1222  ESMF_Comp.F90
2679: ufs_model          00000000009DB3B4  esmf_gridcompmod_        1407  ESMF_GridComp.F90
2679: ufs_model          000000000041A976  MAIN__                    381  UFS.F90
2679: ufs_model          00000000004197DE  Unknown               Unknown  Unknown
2679: libc-2.17.so       00002BA8387D4555  __libc_start_main     Unknown  Unknown
2679: ufs_model          00000000004196E9  Unknown               Unknown  Unknown
```
[gfsfcst.log](https://github.com/ufs-community/ufs-weather-model/files/8864014/gfsfcst.log)

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
## Description

The CICE component is currently compiled with Intel using the `-xHOST` flag, which specifies CPU instructions based on the node performing the compilation.  In the case of systems like Jet, this causes an issue as the head nodes are comprised of Skylake architecture capable of interpreting certain instructions like AVX-512, while the xjet partition is comprised of Haswell cores that cannot interpret AVX-512 instructions.  Thus, when attempting to run a coupled forecast on xjet after compiling on the head node, the UFS will crash.

Note that this could also be an issue for Hercules/Orion (if Hercules-compiled executables should run on Orion).

To fix this, `-xHOST` has been removed from the CICE interface CMake file so that the instructions specified in [configure_jet.intel.cmake](https://github.com/ufs-community/ufs-weather-model/blob/develop/cmake/configure_jet.intel.cmake) and [Intel.cmake](https://github.com/ufs-community/ufs-weather-model/blob/develop/cmake/Intel.cmake) can be inherited.  This does change regression test results for all coupled Intel tests, even on Hera, as `-xHOST` builds with, among other things, AVX-512 instructions while the new configuration will send AVX-2 instructions.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

All GNU RTs should not see a change.  The following Intel, coupled RTs will change due to new compiler instructions:
cpld_control_p8_mixedmode
cpld_control_gfsv17
cpld_control_p8
cpld_2threads_p8
cpld_esmfthreads_p8
cpld_decomp_p8
cpld_mpi_p8
cpld_control_ciceC_p8
cpld_control_c192_p8
cpld_bmark_p8
cpld_control_noaero_p8
cpld_control_nowave_noaero_p8
cpld_control_noaero_p8_agrid
cpld_control_c48
cpld_warmstart_c48
datm_cdeps_control_cfsr
datm_cdeps_control_gefs
datm_cdeps_iau_gefs
datm_cdeps_stochy_gefs
datm_cdeps_ciceC_cfsr
datm_cdeps_bulk_cfsr
datm_cdeps_bulk_gefs
datm_cdeps_mx025_cfsr
datm_cdeps_mx025_gefs
datm_cdeps_multiple_files_cfsr
datm_cdeps_3072x1536_cfsr
datm_cdeps_gfs

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [x] CICE (Change to build only)
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Closes #1262 

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@DavidHuber-NOAA Are any performance impacts expected from this fix?

**Comment by DavidHuber-NOAA** [comment]
@DeniseWorthen I would expect some minor performance changes, but nothing terribly significant.  Having run the full RT suite on xjet, kjet, and Hera, I can say that no tests failed due to time limit.

**Comment by BrianCurtis-NOAA** [comment]
There are no changes in CICE repo, this is strictly building on UFSWM. So this should be ready for commit queue.

@DavidHuber-NOAA or @DeniseWorthen if you can double check on the reproducibility (create baselines then check against those baselines) on one of the changed tests that would be helpful to double check. We will attempt to start running RT's later this afternoon.

**Comment by DavidHuber-NOAA** [comment]
@BrianCurtis-NOAA Sure, I will test cpld_control_c48.

**Comment by DavidHuber-NOAA** [comment]
@BrianCurtis-NOAA I rebaselined cpld_control_c48 and then tested against it and results were identical.

**Comment by jkbk2004** [comment]
I am adding new BL_DATE.

**Comment by jkbk2004** [comment]
We will start testing from hera.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1191748279/20230118180015/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1191748279/20230118180008/ufs-weather-model
Please make changes and add the following label back: gaea-intel-BL

**Comment by jkbk2004** [comment]
We will skip cheyenne. It's under maintenance whole week. with that, all tests are done. Can we have final approvals to start merging in?

**Comment by jkbk2004** [comment]
FYI: we will resume to test with jenkins-ci again from next pr.

**Comment by DeniseWorthen** [comment]
@jkbk2004 CISL just sent notification that all services are returned.

**Comment by jkbk2004** [comment]
> @jkbk2004 CISL just sent notification that all services are returned

let me check.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
