### PR TITLE
[develop]: Documentation updates + Submodule pointer update (fv3atm, ccpp-framework) for ccpp-framework PR 600 (bug fix for unit conversion error in ccpp_prebuild.py ) #2464 + Update chunksizes for cubed sphere grid #2465

### LINKED ISSUE #2439: writing native grid atmf history files is too slow in FV3ATM
## Description

The G-W gdas fcst job slows down significantly when the option of writing the native grid history files is turned on. Besides the resources issue on write grid component, it is also found that the model writes native grid atmf history files significantly slower than writing the Gaussian grid atmf history files or writing the native grid restart files. The timing from Dave's test is showing below:

nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                                             ./atmf003.nc write time is   **18.91891** at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                           ./cubed_sphere_grid_atmf003.nc write time is  **184.79446** at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                           ./cubed_sphere_grid_sfcf003.nc write time is   36.00565 at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                                             ./sfcf003.nc write time is   36.36828 at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                   RESTART/20211220.210000.fv_core.res.nc write time is    **5.30265** at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                RESTART/20211220.210000.fv_srf_wnd.res.nc write time is    0.01886 at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                 RESTART/20211220.210000.fv_tracer.res.nc write time is    **7.70513** at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                      RESTART/20211220.210000.phy_data.nc write time is    7.28120 at fcst   03:00
nid002370.dogwood.wcoss2.ncep.noaa.gov 2544:                      RESTART/20211220.210000.sfc_data.nc write time is    3.23882 at fcst   03:00

### LINKED ISSUE #2462: Update WM Documentation
## Description
- Review Inputs/Outputs chapter for changes to the LND component ahead of Land DA release
- Add `fd_ufs.yaml` documentation
- Add documentation for `tests-dev` Python scripts

## Solution
Revise documentation described above.

## Alternatives
N/A

## Related to
Required _ahead_ of Land DA release (scheduled for 10/30/24)

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
## Description:
This PR updates to the Input/Output chapter of the documentation to include info on `fd_ufs.yaml` and to update the land-related sections. 
This PR also generates documentation from the docstrings in the `tests-dev` Python scripts. 
You can view the docs in my fork here: https://gsp-wm.readthedocs.io/en/text-landda/ 

### Commit Message:

```
* UFSWM - 
  Update LND I/O docs
  Add fd_ufs.yaml docs
  Add tests-dev docs
* UFSWM - Change the default chunking for the cubed sphere history files to use only the horizontal grid size of each of the tiles.
   * FV3 - Change the default chunking for the cubed sphere history files to use only the horizontal grid size of each of the tiles.
   * FV3 - Submodule pointer update for ccpp-framework PR 600 (bug fix for unit conversion error in ccpp_prebuild.py)
```

### Priority:
* High: Hoping to get changes in ahead of Land DA v2.0.0 release

### UFSWM:
* Closes #2462 
* Closes https://github.com/NCAR/ccpp-framework/pull/600
* Closes #2439

### Sub component Pull Requests:
* FV3: NOAA-EMC/fv3atm#876
* FV3: https://github.com/NOAA-EMC/fv3atm/pull/878
  * ccpp-physics: https://github.com/NCAR/ccpp-framework/pull/600

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [ ] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - Acorn skipped due to machine maintenance 
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by gspetro-NOAA** [comment]
Note that I have toggled on the functionality to build docs for every PR.
If you click on "Details" after the `docs/readthedocs.org:ufs-weather-model` check at the bottom of the PR, you will either see the PR docs, the build progress (if it hasn't completed), or the traceback (if it fails). I believe that after 90 days, the build is deleted, so the docs are not stored indefinitely, but this will ensure that there are no obvious issues with the PR docs. 

It is possible to turn on a "warn as error" functionality in the docs that will fail the build check when warnings appear (rather than just failing for errors). Let me know if you'd like me to turn on this functionality. It has the benefit of catching small issues as they occur (such as changes to URLs in the docs), which is helpful for maintenance. However, developers may not like having to fix issues like this that are outside their PR scope, even if they are usually small/simple fixes. That said, I'm happy to work with them to put the fixes into their PR or a subsequent PR if such issues occur.

**Comment by jkbk2004** [comment]
@gspetro-NOAA can you sync up branch? I will try to combine in #2465.

**Comment by jkbk2004** [comment]
Jobs on Jet are still not moving. Note that baseline is restored and available at /lfs5/HFIP/hfv3gfs/role.epic/RT/NEMSfv3gfs/develop-20241011. We need to skip Jet.

**Comment by FernandoAndrade-NOAA** [comment]
@jkbk2004 FYI Derecho is having persistent timeout issues with the s2swa_faster_intel compile

**Comment by jkbk2004** [comment]
We can start merging process for this pr.  We will follow the Derecho issue with https://github.com/ufs-community/ufs-weather-model/issues/2479. @ulmononian @RatkoVasic-NOAA FYI

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
