### PR TITLE
NSSL ccpp-physics bugfixes and new ccpp-framework debugging feature

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR only updates the CCPP Physics and Framework submodules to pull in NSSL MP ORT bugfixes and a new debugging (python) feature of ccpp-framework.

The CCPP Physics bugfixes are also part of https://github.com/NOAA-EMC/fv3atm/pull/514, https://github.com/ufs-community/regional_workflow/pull/708, and https://github.com/ufs-community/ufs-weather-model/pull/1158, but are included in this PR since those PRs are on hold and this will at least get the bugfixes merged in preparation for the upstream PRs.

### Issue(s) addressed

https://github.com/NCAR/ccpp-physics/issues/916

## Testing

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [] cheyenne.intel (machine down this week)
- [] cheyenne.gnu (machine down this week)
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI [2304394050](https://github.com/ufs-community/ufs-weather-model/actions/runs/2304394050)

Changes baseline for rrfs_v1nssl RT only.

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/904
- waiting on https://github.com/NCAR/ccpp-framework/pull/419
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/529

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl You're on deck (later today or tomorrow) for this PR. I wanted to check if this PR is ready to go or if we need to push it back a day or two?

**Comment by grantfirl** [comment]
> @grantfirl You're on deck (later today or tomorrow) for this PR. I wanted to check if this PR is ready to go or if we need to push it back a day or two?

This is ready to go. All PR branches have been updated.

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl since one baseline changes I'll just run new baselines for that one test. Please change BL_DATE to 20220511.

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl I got the CRAY RT done so I brought in the BL_DATE change myself. Gives me a head start for AutoRT jobs.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/929011081/20220511020006/ufs-weather-model
[RT] Error: Test hafs_regional_atm 093 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl @junwang-noaa All tests passed. Ready for merges to start and .gitmodules revert.

**Review by junwang-noaa — APPROVED** [review]

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA Wow, that was quick. Thanks for your evening-time work. I'll go ahead and start the merge now.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl fv3atm merged, update hash and revert .gitmodules please

**Comment by grantfirl** [comment]
> @grantfirl fv3atm merged, update hash and revert .gitmodules please

@BrianCurtis-NOAA Done

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
