### PR TITLE
Update global atm-only control_c$resolution tests for GFSv17/GEFSv13 configuration

### LINKED ISSUE #1819: Update global atm-only control_c$resolution tests
## Description
Currently only control_p8 global atm RT test is using the GFSv17/GEFSv13 configuration. control_c48, control_c192 and control_384 are still using the old GFSv16 configuration. In this issue, control_c48, control_c192 and control_384 will be updated to have same configuration as control_p8. 

## Solution
Update the three atm only tests to use GFSv17/GEFSv13 configuration.

### PR DESCRIPTION
**Pull request by sadeghitabas**
## Description

Currently only control_p8 global atm RT test is using the GFSv17/GEFSv13 configuration. control_c48, control_c192 and control_384 are still using the old GFSv16 configuration. In this PR, control_c48, control_c192 and control_384 will be updated to have same configuration as control_p8.

### Input data additions/changes
- [ ] No changes are expected to input data.
- [x] Changes are expected to input data:
  - [ ] New input data.
  - [x] Updated input data.

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

### Library Updates/Changes

- [ ] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved in section below
- [ ] Confirm reviews completed in ALL sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Closes https://github.com/ufs-community/ufs-weather-model/issues/1819
## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@SadeghTabas-NOAA just wanted to make sure you saw the cpld_control_gfsv17 test which is the coupled test we're keeping up to date with the currently targeted GFSv17 configuration.

**Comment by sadeghitabas** [comment]
@JessicaMeixner-NOAA Thank you for your suggestion, I've focused on the ATM-only tests right now, but as you said the cpld test is the one you keep updated, I'll take a look on that one as well and make updates. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
@SadeghTabas-NOAA I'm not asking you to make updates to the GFSv17 test, just wanted to make sure you knew that's the test that we are keeping up to date with the GFSv17 targeted configuration if that'd be of use.  Although if you make the corresponding update for https://github.com/NOAA-EMC/global-workflow/issues/1612 in this PR, that test will need updated.

**Comment by sadeghitabas** [comment]
@JessicaMeixner-NOAA I did not know, thanks for letting me know.

**Comment by junwang-noaa** [comment]
There will be a new PR for this task, the PR is closed.

**Pull request closed without merging**
