### PR TITLE
2D advection of cellular automata (Combined PR# 1804)

### LINKED ISSUE #1869: Add capability to advect CA cells/cloud objects with the wind on the cellular automata grid
## Description

This development adds a capability to advect CA cells (or - in the future - 2D cloud objects) with a mean level wind. The updated CA/cloud state is then used to inform on convective initiation in saSAS (and -in the future - the C3 convection scheme)

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: /scratch2/BMC/gsienkf/Lisa.Bengtsson/ufs-weather-model-CAadvection2/tests/logs/RegressionTests_hera.log
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
This development adds a capability to advect CA cells (or - in the future - 2D cloud objects) with a mean level wind. The updated CA/cloud state is then used to inform on convective initiation in saSAS (and -in the future - the C3 convection scheme)

*Add namelist ca_advect as control switch.
*Ensure the same definition for halo sizes are used in the domain construction, as when allocating data to be used in the atmospehre_scalar_field_halo routines.
*Update halo size from 1 to 3.
*Bring in U,V and control flags from FV3 to CA driver routines - compute mean level wind
*2D advection of CA cells

### Associated UFSWM Issue to close
Closes: https://github.com/ufs-community/ufs-weather-model/issues/1869

### Subcomponent Pull Requests
- Depends on FV3: https://github.com/NOAA-EMC/fv3atm/pull/686
- Depends on stochastic_physics: https://github.com/NOAA-PSL/stochastic_physics/pull/62

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [x] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [ ] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by lisa-bengtsson** [comment]
Log to RT test intel on Hera:
/scratch2/BMC/gsienkf/Lisa.Bengtsson/ufs-weather-model-CAadvection2/tests/logs/RegressionTests_hera.log

All jobs pass. No anticipated baseline changes.

**Comment by zach1221** [comment]
@lisa-bengtsson would you be open to combining UFS-WM PR# [1804](https://github.com/ufs-community/ufs-weather-model/pull/1804) into this one? It's just documentation changes.

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson would you be open to combining UFS-WM PR# [1804](https://github.com/ufs-community/ufs-weather-model/pull/1804) into this one? It's just documentation changes.

Yes no problem.

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA, FYI following fv3 sub pr approval and sync, this pr looks good for testing after we advance through the current queue.

**Comment by zach1221** [comment]
@lisa-bengtsson Ok, I think we're ready to begin testing against this PR. If you can combine the changes from [1804](https://github.com/ufs-community/ufs-weather-model/pull/1804) in this one and sync up your branch/resolve conflicts, then we should be good to go.

**Comment by lisa-bengtsson** [comment]
@zach1221 I have synced up the branch. I wonder how I can easiest combine the changes from 1804 with this PR? A merge?

**Comment by zach1221** [comment]
> @zach1221 I have synced up the branch. I wonder how I can easiest combine the changes from 1804 with this PR? A merge?

I usually just clone the PRs, make the updates, then push back to the branch. There's probably an easier way but that's my method. I'm happy to do it, if that's ok?

**Comment by lisa-bengtsson** [comment]
> > @zach1221 I have synced up the branch. I wonder how I can easiest combine the changes from 1804 with this PR? A merge?
> 
> I usually just clone the PRs, make the updates, then push back to the branch. There's probably an easier way but that's my method. I'm happy to do it, if that's ok?

That would be great if you could do it, thank you!

**Comment by zach1221** [comment]
ORTs passed. Jenkins-ci log attached.

[Jenkins-ci 1870 ORTs.pdf](https://github.com/ufs-community/ufs-weather-model/files/12517519/Jenkins-ci.1870.ORTs.pdf)

**Comment by BrianCurtis-NOAA** [comment]
> ORTs passed. Jenkins-ci log attached. Uploading Jenkins-ci 1870 ORTs.pdf…

This link is broken.

**Comment by zach1221** [comment]
> > ORTs passed. Jenkins-ci log attached. Uploading Jenkins-ci 1870 ORTs.pdf…
> 
> This link is broken.

should be fixed.

**Comment by zach1221** [comment]
Testing is complete. I will follow up on the stochastic physics sub-pr to begin the merging process.

**Comment by zach1221** [comment]
@lisa-bengtsson Stochastic physics PR #[62](https://github.com/NOAA-PSL/stochastic_physics/pull/62) has been merged. Please update the submodule pointer and revert the change in .gitmodule url.
hash: fed14957ba8fa9789b86c2df413b76a9eef633ae

**Comment by BrianCurtis-NOAA** [comment]
fv3 merged: https://github.com/NOAA-EMC/fv3atm/commit/379ef21b1a117848fca255de4da048778e561c95

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by lisa-bengtsson** [comment]
Thank you!

**Pull request merged**
