### PR TITLE
Bugfixes for RRTMGP

### PR DESCRIPTION
**Pull request by dustinswales**
### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
[NOAA-EMC #655](https://github.com/NOAA-EMC/fv3atm/pull/655)
[Fix to allow for threading in RRTMGP #70](https://github.com/ufs-community/ccpp-physics/pull/70)
Addresses [UWM:ccpp-physics Issue #59](https://github.com/ufs-community/ccpp-physics/issues/59)

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hi @dustinswales, could you sync with develop, link the FV3 sub PR, and provide any Hera intel/gnu or Cheyenne intel/gnu logs?

**Comment by dustinswales** [comment]
> Hi @dustinswales, could you sync with develop, link the FV3 sub PR, and provide any Hera intel/gnu or Cheyenne intel/gnu logs?

Done. (No logs, I wiped them when updating, but tested on Cheyenne Intel)

**Comment by FernandoAndrade-NOAA** [comment]
@dustinswales, #1743 was merged in, could you resync with develop and resolve conflicts? We can get started with jenkins-ci and ORTs following that.

**Comment by FernandoAndrade-NOAA** [comment]
Hi @dustinswales, just checking in if you're ready to sync and resolve conflicts in order to proceed with testing this PR

**Comment by dustinswales** [comment]
@FernandoAndrade-NOAA sorry for the delay. I will sync in the coming hour

**Comment by jkbk2004** [comment]
Looks like all code changes only for check error messages. No baseline change and all tests pass on cheyenne. @dustinswales can we confirm?

**Comment by DeniseWorthen** [comment]
@jkbk2004 Were the RTs ever run for this PR? It seems that you are finding no change in baseline, but there was an expected change (in the PR description) that the control_p8_rrtmgp test would change. We don't know if it should or not because the pre-commit logs don't seem to have been posted.

**Comment by jkbk2004** [comment]
Yeah, we need @dustinswales to confirm.

**Comment by dustinswales** [comment]
@jkbk2004 @DeniseWorthen 
The RTs haven’t been run yet. I synced last week, and again last night. I thought that @FernandoAndrade-NOAA was initiating the testing?
(I’m not sure where that Cheyenne log came from in ea795b7e879f0f831b266cc46f192dee7bead88b)

**Comment by DeniseWorthen** [comment]
@dustinswales Thanks....I think my confusion is that you listed in the description that the baseline would change for control_p8_rrtmgp. Do you know for sure that is expected?

**Comment by dustinswales** [comment]
@DeniseWorthen Yes, the control_p8_rrtmgp should need new baselines, but now I'm nervous and rechecking on Cheyenne.

**Comment by dustinswales** [comment]
@DeniseWorthen @jkbk2004 I looks like I was mistaken. I just reran on Cheyenne and the baselines didn't change for the RRTMGP test, /glade/work/dswales/UFS/RRTMGP/ufs-weather-model/tests/logs/RegressionTests_cheyenne.log.

**Comment by FernandoAndrade-NOAA** [comment]
Attached are the jenkins ci logs from earlier, ORTs passed. @dustinswales I'd like to double check with you whether there are any baseline changes expected, including the control_p8_rrtmgp? Just making sure before I start up the full RTs. Thank you.
[ufs-weather-model » ort-docker-pipeline » PR-1751 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11680655/ufs-weather-model.ort-docker-pipeline.PR-1751.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA FYI: on-going this pr with no baseline change

**Comment by dustinswales** [comment]
> Attached are the jenkins ci logs from earlier, ORTs passed. @dustinswales I'd like to double check with you whether there are any baseline changes expected, including the control_p8_rrtmgp? Just making sure before I start up the full RTs. Thank you. [ufs-weather-model » ort-docker-pipeline » PR-1751 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11680655/ufs-weather-model.ort-docker-pipeline.PR-1751.1.Console.Jenkins.pdf)

@FernandoAndrade-NOAA Correct. No baseline changes.

**Comment by FernandoAndrade-NOAA** [comment]
Sub FV3 PR #[655](https://github.com/NOAA-EMC/fv3atm/pull/655) has been merged in. Please go ahead and update hash and gitmodules

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
