### PR TITLE
Updated settings for NoahMP, Thompson and RRTMGP in RTs

### LINKED ISSUE #1173: Update namelist settings of the Thompson, NoahMP and RRTMGP for RTs
## Description
The namelist settings for the Thompson and NoahMP scheme need to be updated in order to keep up with the fast development of P8C. Currently, sedi_semi is set to false and decfl is set to 8 for all Thompson scheme related RTs. Due to the computing efficiency issue for the RRTMGP scheme, the RRTMGP scheme in suite_FV3_GFS_v17_coupled_p8 and suite_FV3_GFS_v17_p8 was reverted to RRTMG.

## Solution
Set/add those namelist variables in default_var.sh and/or the test files in the tests directory.

### LINKED ISSUE #1185: DNATS exported as 2 in RT's without GOCART aerosol
## Description

DNATS should be set to 0 in control_p8 tests without GOCART aerosols, otherwise ozone and tke will not be advected in the dycore. 

control_2threads_p8
control_debug_p8
control_decomp_p8
control_p8
control_restart_p8

Should all have DNATS = 0 as the field_table does not include GOCART aerosols.

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.
 
## Description
The namelist settings for the NoahMP scheme and the Thompson scheme are modified in RTs (issue #1173), e.g.,
       NoahMP: iopt_trs=2, note that this is just a placeholder because iopt_trs is set to 2 by default in GFS_typedefs.F90
       Thompson: Bug fixed for DNATS=2 to DNATS=0 in control_*_p8 (issue #1185 )
                           sedi_semi is set to .true.;  decfl=10
                   The following description of decfl is provided by Songyou Hong and Ruiyu Sun: 
                    DeCFL is the ratio of CFL time step = dt/dz*Vt. Since it contains model time step, dt and vertical resolution, dz, it 
                    is independent of integration time step and vertical resolution. Based on 1D experiment, the ratio of CFL time 
                    step, DeCFL is numerically reasonable up to 12. For safety, it is set as 10. 
                    The smaller DeCFL increase the number of Semi_Lagrangian loops and does not change the overall results.
                    But, the increased number of iteration deteriorate the numerical accuracy, even though not discernible, 
                    due to the increased number of interpolation from Lagrangian to Eulerian grids.
         RRTMGP:  RRTMGP in suite_FV3_GFS_v17_p8 and suite_FV3_GFS_v17_coupled_p8 were reverted to RRTMG
                           the following SDFs were deleted:
                                   suite_FV3_GFS_v15p2_RRTMGP.xml
                                   suite_FV3_GFS_v15_thompson_mynn_RRTMGP.xml
                                   suite_FV3_GFS_v16_coupled_p7_rrtmgp.xml
                                   suite_FV3_GFS_v16_p7_rrtmgp.xml
                                   suite_FV3_GFS_v16_RRTMGP.xml
                                   suite_FV3_GFSv17alp_cpldnsstrasugwprrtmgp.xml

                    The following RTs were deleted:
                             regional_RRTMGP
                             control_rrtmgp
                             control_rrtmgp_c192
                             control_rrtmgp_debug
                                  
### Issue(s) addressed

- fixes #1173 
- fixes #1185 

## Testing
RTs are done on hera.intel. Due to the changes to the Thompson and RRTMGP scheme, the following tests failed when comparing resutls:
Test cpld_control_p8 001 failed in check_result failed 
Test cpld_control_p8 001 failed in run_test failed 
Test cpld_2threads_p8 002 failed in check_result failed 
Test cpld_2threads_p8 002 failed in run_test failed 
Test cpld_decomp_p8 003 failed in check_result failed 
Test cpld_decomp_p8 003 failed in run_test failed 
Test cpld_mpi_p8 004 failed in check_result failed 
Test cpld_mpi_p8 004 failed in run_test failed 
Test cpld_bmark_p8 005 failed in check_result failed 
Test cpld_bmark_p8 005 failed in run_test failed 
Test cpld_control_c96_p8 006 failed in check_result failed 
Test cpld_control_c96_p8 006 failed in run_test failed 
Test cpld_control_c192_p8 008 failed in check_result failed 
Test cpld_control_c192_p8 008 failed in run_test failed 
Test cpld_control_c384_p8 010 failed in check_result failed 
Test cpld_control_c384_p8 010 failed in run_test failed 
Test cpld_debug_p8 012 failed in check_result failed 
Test cpld_debug_p8 012 failed in run_test failed 
Test control_p8 031 failed in check_result failed 
Test control_p8 031 failed in run_test failed 
Test control_decomp_p8 033 failed in check_result failed 
Test control_decomp_p8 033 failed in run_test failed 
Test control_2threads_p8 034 failed in check_result failed 
Test control_2threads_p8 034 failed in run_test failed 
Test control_p8_rrtmgp 035 failed in check_result failed 
Test control_p8_rrtmgp 035 failed in run_test failed 
Test regional_control 036 failed in check_result failed 
Test regional_control 036 failed in run_test failed 
Test regional_control_2dwrtdecomp 038 failed in check_result failed 
Test regional_control_2dwrtdecomp 038 failed in run_test failed 
Test regional_noquilt 039 failed in check_result failed 
Test regional_noquilt 039 failed in run_test failed 
Test regional_2threads 040 failed in check_result failed 
Test regional_2threads 040 failed in run_test failed 
Test regional_netcdf_parallel 041 failed in check_result failed 
Test regional_netcdf_parallel 041 failed in run_test failed 
Test regional_3km 042 failed in check_result failed 
Test regional_3km 042 failed in run_test failed 
Test rap_control 043 failed in check_result failed 
Test rap_control 043 failed in run_test failed 
Test rap_rrtmgp 044 failed in check_result failed 
Test rap_rrtmgp 044 failed in run_test failed 
Test regional_spp_sppt_shum_skeb 045 failed in check_result failed 
Test regional_spp_sppt_shum_skeb 045 failed in run_test failed 
Test rap_2threads 046 failed in check_result failed 
Test rap_2threads 046 failed in run_test failed 
Test rap_sfcdiff 048 failed in check_result failed 
Test rap_sfcdiff 048 failed in run_test failed 
Test hrrr_control 050 failed in check_result failed 
Test hrrr_control 050 failed in run_test failed 
Test rrfs_v1beta 051 failed in check_result failed 
Test rrfs_v1beta 051 failed in run_test failed 
Test rrfs_conus13km_hrrr_warm 054 failed in check_result failed 
Test rrfs_conus13km_hrrr_warm 054 failed in run_test failed 
Test rrfs_conus13km_radar_tten_warm 055 failed in check_result failed 
Test rrfs_conus13km_radar_tten_warm 055 failed in run_test failed 
Test control_thompson 060 failed in check_result failed 
Test control_thompson 060 failed in run_test failed 
Test control_thompson_no_aero 061 failed in check_result failed 
Test control_thompson_no_aero 061 failed in run_test failed 
Test control_debug_p8 073 failed in check_result failed 
Test control_debug_p8 073 failed in run_test failed 
Test control_thompson_debug 074 failed in check_result failed 
Test control_thompson_debug 074 failed in run_test failed 
Test control_thompson_no_aero_debug 075 failed in check_result failed 
Test control_thompson_no_aero_debug 075 failed in run_test failed 
Test control_thompson_extdiag_debug 076 failed in check_result failed 
Test control_thompson_extdiag_debug 076 failed in run_test failed 
Test control_thompson_progcld_thompson_debug 077 failed in check_result failed 
Test control_thompson_progcld_thompson_debug 077 failed in run_test failed 
Test regional_debug 078 failed in check_result failed 
Test regional_debug 078 failed in run_test failed 
Test rap_control_debug 079 failed in check_result failed 
Test rap_control_debug 079 failed in run_test failed 
Test rap_unified_drag_suite_debug 080 failed in check_result failed 
Test rap_unified_drag_suite_debug 080 failed in run_test failed 
Test rap_diag_debug 081 failed in check_result failed 
Test rap_diag_debug 081 failed in run_test failed 
Test rap_cires_ugwp_debug 082 failed in check_result failed 
Test rap_cires_ugwp_debug 082 failed in run_test failed 
Test rap_unified_ugwp_debug 083 failed in check_result failed 
Test rap_unified_ugwp_debug 083 failed in run_test failed 
Test rap_lndp_debug 084 failed in check_result failed 
Test rap_lndp_debug 084 failed in run_test failed 
Test rap_flake_debug 085 failed in check_result failed 
Test rap_flake_debug 085 failed in run_test failed 
Test rap_progcld_thompson_debug 086 failed in check_result failed 
Test rap_progcld_thompson_debug 086 failed in run_test failed 
Test rap_noah_debug 087 failed in check_result failed 
Test rap_noah_debug 087 failed in run_test failed 
Test rap_rrtmgp_debug 088 failed in check_result failed 
Test rap_rrtmgp_debug 088 failed in run_test failed 
Test rap_sfcdiff_debug 089 failed in check_result failed 
Test rap_sfcdiff_debug 089 failed in run_test failed 
Test rap_noah_sfcdiff_cires_ugwp_debug 090 failed in check_result failed 
Test rap_noah_sfcdiff_cires_ugwp_debug 090 failed in run_test failed 
Test rrfs_v1beta_debug 091 failed in check_result failed 
Test rrfs_v1beta_debug 091 failed in run_test failed 
Test hafs_regional_atm_thompson_gfdlsf 094 failed in check_result failed 
Test hafs_regional_atm_thompson_gfdlsf 094 failed in run_test failed 

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [ ] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies
- waiting on noaa-emc/fv3atm (https://github.com/NOAA-EMC/fv3atm/pull/527)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220505120014/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20220503/INTEL
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220505180015/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220503/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by junwang-noaa** [comment]
@ChunxiZhang-NOAA Please change BL_DATE to 20220508 in rt.sh

**Comment by ChunxiZhang-NOAA** [comment]
> 

Ah, I forgot that, but 20220505 or 2020508?

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220505183012/ufs-weather-model
[BL] Error: Test control_p8_lndp 020 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220505123010/ufs-weather-model
[BL] Error: Test control_p8_lndp 020 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Hera.intel: `atparse.bash: line 28: IOPT_TRS: unbound variable`

Update: Same with Cheyenne, both run dirs only have the following files: fv3.exe  fv3_run  input.nml  module-setup.sh  modules.fv3  ufs_common  ufs_common_debug

**Review by yangfanglin — APPROVED** [review]
Updates to the namelist options look correct.  It also helps to reduce the number of SDF files.

**Comment by ChunxiZhang-NOAA** [comment]
> /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220505183012/ufs-weather-model



> Hera.intel: `atparse.bash: line 28: IOPT_TRS: unbound variable`
> 
> Update: Same with Cheyenne, both run dirs only have the following files: fv3.exe fv3_run input.nml module-setup.sh modules.fv3 ufs_common ufs_common_debug

This RT is added by commit 9bf10ca I believe. I didn't noticed it when I merged remote-tracking branch this morning. I will add OPT_TRS to this RT.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220506021510/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220506031639/ufs-weather-model
[RT] Error: Test control_p8 031 failed in check_result failed 
[RT] Error: Test control_p8 031 failed in run_test failed 
[RT] Error: Test control_decomp_p8 034 failed in check_result failed 
[RT] Error: Test control_decomp_p8 034 failed in run_test failed 
[RT] Error: Test control_2threads_p8 035 failed in check_result failed 
[RT] Error: Test control_2threads_p8 035 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 036 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 036 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220505201508/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220505214224/ufs-weather-model
[RT] Error: Test control_p8 031 failed in check_result failed 
[RT] Error: Test control_p8 031 failed in run_test failed 
[RT] Error: Test control_decomp_p8 034 failed in check_result failed 
[RT] Error: Test control_decomp_p8 034 failed in run_test failed 
[RT] Error: Test control_2threads_p8 035 failed in check_result failed 
[RT] Error: Test control_2threads_p8 035 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220506153018/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220506164146/ufs-weather-model
[RT] Error: Test control_p8 031 failed in check_result failed 
[RT] Error: Test control_p8 031 failed in run_test failed 
[RT] Error: Test control_decomp_p8 034 failed in check_result failed 
[RT] Error: Test control_decomp_p8 034 failed in run_test failed 
[RT] Error: Test control_2threads_p8 035 failed in check_result failed 
[RT] Error: Test control_2threads_p8 035 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 036 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 036 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220506093013/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220506110118/ufs-weather-model
[RT] Error: Test control_p8 031 failed in check_result failed 
[RT] Error: Test control_p8 031 failed in run_test failed 
[RT] Error: Test control_decomp_p8 034 failed in check_result failed 
[RT] Error: Test control_decomp_p8 034 failed in run_test failed 
[RT] Error: Test control_2threads_p8 035 failed in check_result failed 
[RT] Error: Test control_2threads_p8 035 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/920072834/20220507153011/ufs-weather-model
[BL] Error: Test control_rrtmgp_debug 028 failed in run_test failed 
[BL] Error: Test compile_001 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/920072834/20220507213014/ufs-weather-model
[BL] Error: Test control_rrtmgp_debug 028 failed in run_test failed 
[BL] Error: Test compile_001 failed in run_compile failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by junwang-noaa** [comment]
@ChunxiZhang-NOAA @BrianCurtis-NOAA  How is the RT on dell?

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa The Dell P3 RT's all passed but I used `cat` on the log files from the three attempts. We will need to adjust the BUILD_JOBS for Dell P3 to 2 since that's the only way a couple of the compiles were successful.

**Comment by junwang-noaa** [comment]
Thanks, Brian. @DusanJovic-NOAA Can we make the BUILD_JOBS change in your PR? Thanks

**Comment by junwang-noaa** [comment]
@ChunxiZhang-NOAA your fv3atm PR is merged, please update the fv3atm submodule in your ufs-weather-model branch. Thansk

**Comment by DusanJovic-NOAA** [comment]
> Thanks, Brian. @DusanJovic-NOAA Can we make the BUILD_JOBS change in your PR? Thanks

Done.

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA your fv3atm PR is merged, please update the fv3atm submodule in your ufs-weather-model branch. Thansk

@junwang-noaa Done.

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
