### PR TITLE
[production/AQM.v7] Updates to FV3/ccpp/physics , FV3/upp and FV3/atmos_cubed_sphere for AQMv7 EE2 compliance

### LINKED ISSUE #2002: [production/AQM.v7]  model compilation with debug mode
All executable codes must be compiled and tested with debug mode.  The debug flag must have -g but at least needs to have -check all and -ftrapuv.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## PR Author Checklist:

- [X] I have linked PR's from all sub-components involved in section below. 
- [X] I am confirming reviews are completed in ALL sub-component PR's.
- [X] These code changes have been tested extensively along with the ufs-srweather-app workflows
- [x] I have filled out all sections of the template.

## Description
This PR brings in all changes related to meeting EE2 standards for NCO implementation.

### Associated UFSWM Issue to close
- Closes #2002 

### Blocking Dependencies
None

### Subcomponents involved:
- [X] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- This has been tested extensively by @JianpingHuang-NOAA for use with the ufs-srweather-app workflow

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

### Testing Log:
- WCOSS2
  - [x] Dogwood/Cactus

</details>

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA is it required to remove the additional components in the code? I am not sure if this is necessary to remove all the other components.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA is it required to remove the additional components in the code? I am not sure if this is necessary to remove all the other components.

@junwang-noaa I have been told that NCO only wants the items applicable to AQM and WCOSS2, that includes the subcomponents.

**Comment by junwang-noaa** [comment]
Do they provide some documentation for this? @aerorahul is it an EE2 standard? We are using unified model, it's kind of going back tIn GFSv16 and HAFSv1 we have

**Comment by aerorahul** [comment]
This is the first time I am seeing this.
Why are we deleting non-AQM components from the ufs-weather-model?  This is not an EE2 standard requirement explicitly stated.

**Comment by BinLiu-NOAA** [comment]
FYI., for HAFSv1 operational implementation, we mentioned and insisted that ufs-weather-model is a community developed modeling framework and system. And we cannot remove source code/components just for an individual application's (e.g., HAFS purpose. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
I am not sure it's explicitly stated either, and I can revert those changes easily, so whatever the final decision is will be a quick fix. @rmontuoro do you have anything to add on what NCO is getting back to you about?

**Comment by JianpingHuang-NOAA** [comment]
@junwang-noaa @aerorahul @BinLiu-NOAA   This is what NCO told us.

Below is from NCO

It's more IV.C.10 "Remove all references to developer work areas and all development tools (benchmarking, etc.) before submitting to IDSB."

**Comment by JianpingHuang-NOAA** [comment]
This is only for production/AQM.v7 branch, not for Develop branch.

**Comment by aerorahul** [comment]
> @junwang-noaa @aerorahul @BinLiu-NOAA This is what NCO told us.
> 
> Below is from NCO
> 
> It's more IV.C.10 "Remove all references to developer work areas and all development tools (benchmarking, etc.) before submitting to IDSB."

IV.C refers to Interpreted code (bash, ksh, perl) in the vertical structure e.g. `jobs`, `scripts`, `ush`.  
I am not sure I find any development areas in those that refer to the model's infrastructure.

**Comment by JianpingHuang-NOAA** [comment]
Jus forward the NCO's email to you. And copied below

**Remove all references to developer work areas and all development tools (Sec. IV-C-10). e.g.:

“RUN_ENVIR” sections in if statements

Test files in ush/: machine/*.yaml files, rocoto_fake_slurm/, python_utils/test_data, test_retrieve_data.py, etc

All non-wcoss related files under modulefiles/**

This is part of the reasons that we got returned.

**Comment by JianpingHuang-NOAA** [comment]
@aerorahul

**Comment by DusanJovic-NOAA** [comment]
By removing all this 'unused' code from this branch, it becomes very difficult if not impossible to merge in some critical bug fixes from develop branch (or vice-versa from this branch to develop) in the future For example for AQM.v7.1. OK, 
cherry-picking will probably work. So effectively this code is not 'a branch' of any other branch (develop) in this repo, in which case you can as well just create a separate repository for AQM application without 'unnecessary' code.

**Comment by JianpingHuang-NOAA** [comment]
My understand is that we just modify the.gitmodule file that allows NCO to check out the components that AQM.v7 implementation needs. We have not deleted any un-used codes.   Please correct me if I am wrong, Brian @BrianCurtis-NOAA

**Comment by BrianCurtis-NOAA** [comment]
> My understand is that we just modify the.gitmodule file that allows NCO to check out the components that AQM.v7 implementation needs. We have not deleted any un-used codes. Please correct me if I am wrong, Brian @BrianCurtis-NOAA

I haven't heard anything that specific from NCO to require removing any _more_ than we already have. I think the discussion is on bringing back any .gitmodules, subcomponents, or modulefiles, or cmake/ platform specific code.

**Comment by DusanJovic-NOAA** [comment]
> My understand is that we just modify the.gitmodule file that allows NCO to check out the components that AQM.v7 implementation needs. We have not deleted any un-used codes. Please correct me if I am wrong, Brian @BrianCurtis-NOAA

OK, sorry, by unused code I didn't mean source code but files like configuration files, module files, entire test directory  etc. I still think merging this branch with other branches will be difficult.

**Comment by BrianCurtis-NOAA** [comment]
Management has come to the agreement that we move forward as-is with the .gitmodules, modulefiles, tests, cmake/ and sub-component removals.

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA Can you review please.

**Review by JianpingHuang-NOAA — APPROVED** [review]

**Comment by JianpingHuang-NOAA** [comment]
Approved with my successful test.

**Review by JianpingHuang-NOAA — APPROVED** [review]

**Pull request merged**
