### PR TITLE
Thompson MP cloud tuning

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR improves cloud fraction when using Thompson MP. See NCAR/ccpp-physics#809 for more details.

This will require new baselines for regression tests that use Thompson MP.

### Issue(s) addressed

No GitHub issues; tuning for better cloud performance

## Testing

Full rt.conf tests run on Hera/Intel. Tests that use Thompson MP will require new baselines due to parameter tuning.

See NCAR/ccpp-physics#809 for some scientific results.

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1695301758

## Dependencies

- waiting on https://github.com/NOAA-EMC/fv3atm/pull/463
- waiting on https://github.com/NCAR/ccpp-physics/pull/809

### CODE REVIEW

**Comment by grantfirl** [comment]
Failed RTs that need new baselines (all use Thompson MP):
regional_control 035 failed in check_result
regional_control 035 failed in run_test
regional_noquilt 037 failed in check_result
regional_noquilt 037 failed in run_test
regional_2threads 038 failed in check_result
regional_2threads 038 failed in run_test
regional_hafs 039 failed in check_result
regional_hafs 039 failed in run_test
regional_netcdf_parallel 040 failed in check_result
regional_netcdf_parallel 040 failed in run_test
regional_RRTMGP 041 failed in check_result
regional_RRTMGP 041 failed in run_test
rap_control 042 failed in check_result
rap_control 042 failed in run_test
rap_2threads 043 failed in check_result
rap_2threads 043 failed in run_test
rap_sfcdiff 045 failed in check_result
rap_sfcdiff 045 failed in run_test
hrrr_control 047 failed in check_result
hrrr_control 047 failed in run_test
rrfs_v1beta 048 failed in check_result
rrfs_v1beta 048 failed in run_test
control_thompson 055 failed in check_result
control_thompson 055 failed in run_test
control_thompson_no_aero 056 failed in check_result
control_thompson_no_aero 056 failed in run_test
control_thompson_debug 070 failed in check_result
control_thompson_debug 070 failed in run_test
control_thompson_no_aero_debug 071 failed in check_result
control_thompson_no_aero_debug 071 failed in run_test
control_thompson_extdiag_debug 072 failed in check_result
control_thompson_extdiag_debug 072 failed in run_test
regional_debug 073 failed in check_result
regional_debug 073 failed in run_test
rap_control_debug 074 failed in check_result
rap_control_debug 074 failed in run_test
rap_unified_drag_suite_debug 075 failed in check_result
rap_unified_drag_suite_debug 075 failed in run_test
rap_diag_debug 076 failed in check_result
rap_diag_debug 076 failed in run_test
rap_cires_ugwp_debug 077 failed in check_result
rap_cires_ugwp_debug 077 failed in run_test
rap_unified_ugwp_debug 078 failed in check_result
rap_unified_ugwp_debug 078 failed in run_test
rap_noah_debug 079 failed in check_result
rap_noah_debug 079 failed in run_test
rap_rrtmgp_debug 080 failed in check_result
rap_rrtmgp_debug 080 failed in run_test
rap_lndp_debug 081 failed in check_result
rap_lndp_debug 081 failed in run_test
rap_sfcdiff_debug 082 failed in check_result
rap_sfcdiff_debug 082 failed in run_test
rap_flake_debug 083 failed in check_result
rap_flake_debug 083 failed in run_test
rap_noah_sfcdiff_cires_ugwp_debug 084 failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug 084 failed in run_test
rrfs_v1beta_debug 085 failed in check_result
rrfs_v1beta_debug 085 failed in run_test

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/816730657/20220113111511/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_22049
Baseline creation and move successful
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/816730657/20220113122855/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_48935
Test hafs_regional_telescopic_2nests_atm 095 failed in check_result failed 
Test hafs_regional_telescopic_2nests_atm 095 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by junwang-noaa** [comment]
@DeniseWorthen would you please take a look at the RT test hafs_regional_telescopic_2nests_atm on Cheyenne? Thanks!

**Comment by junwang-noaa** [comment]
@grantfirl  The wcoss log files are on hera at /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/.

**Comment by junwang-noaa** [comment]
@grantfirl the hera/jet/orion/gaea log files are on hera at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/. Please commit all those log files to your ufs-weather-model branch. Thanks

**Comment by DeniseWorthen** [comment]
@grantfirl The Cheyenne.gnu log is located on cheyenne here:

/glade/work/worthen/PR1005/ufs-weather-model-gnu/tests

I also added to hera here:

/scratch1/NCEPDEV/stmp2/Denise.Worthen/PR1005

**Comment by grantfirl** [comment]
> @grantfirl the hera/jet/orion/gaea log files are on hera at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/. Please commit all those log files to your ufs-weather-model branch. Thanks

@junwang-noaa Can you change permissions on /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_orion.intel.log to 644? Right now, it is 640 and I cannot copy it. The others are all fine.

**Comment by grantfirl** [comment]
> @grantfirl The Cheyenne.gnu log is located on cheyenne here:
> 
> /glade/work/worthen/PR1005/ufs-weather-model-gnu/tests
> 
> I also added to hera here:
> 
> /scratch1/NCEPDEV/stmp2/Denise.Worthen/PR1005

@DeniseWorthen Is the same test failing with Cheyenne/gnu? I thought it was Cheyenne/intel with the issue.

**Comment by DeniseWorthen** [comment]
@grantfirl The hafs_regional_telescopic_2nests_atm is not tested with GNU, so the baselines passed. But with Intel, it fails comparison for with the baseline.

**Comment by grantfirl** [comment]
> /glade/scratch/dtcufsrt/FV3_RT/rt_48935

OK, I'm sorry that I misunderstood the comment for Cheyenne/gnu logs. Those are just for me to commit and push. Understood now.

**Comment by junwang-noaa** [comment]
> > @grantfirl the hera/jet/orion/gaea log files are on hera at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/. Please commit all those log files to your ufs-weather-model branch. Thanks
> 
> @junwang-noaa Can you change permissions on /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_orion.intel.log to 644? Right now, it is 640 and I cannot copy it. The others are all fine.

Done

**Comment by grantfirl** [comment]
@junwang-noaa Is there something that I can do to my fork of ufs-weather-model to make it pushable for autort?

**Comment by junwang-noaa** [comment]
You need to be a ufs-community collaborator, I think you are now. If you have any test ufs-weather-model branch, I can give a try

**Comment by climbfuji** [comment]
> @grantfirl The hafs_regional_telescopic_2nests_atm is not tested with GNU, so the baselines passed. But with Intel, it fails comparison for with the baseline.

Is it failing for all files, including all the restart files? In other words, are the results really different? Or is it just a variable in one of the diagnostic files that is different?

**Comment by grantfirl** [comment]
> Is it failing for all files, including all the restart files? In other words, are the results really different? Or is it just a variable in one of the diagnostic files that is different?

@climbfuji It's only comparing 2 files for this test:

Comparing atmf006.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.nc ............ALT CHECK......NOT OK

It's strange because as far as I can tell, this test doesn't use Thompson MP which is what was changed. There is one small code change in GFS_rrtmg_pre that changes one variable that only gets used when calling the progcld_thompson subroutine. To me, it looks like nothing in the physics changes should affect this test whatsoever. Would it be possible to have something wrong with the new baseline that was created?

**Comment by climbfuji** [comment]
Possible. A good test would be to take the new code, create another temporary baseline for this test, and then try to verify against that baseline instead of the one in the official location. We can use the “-c” flag for rt.sh to create a new temporary baseline, and the “-m” flag to verify against it in a second step.

**Comment by grantfirl** [comment]
@climbfuji Agreed. That was going to be my next step. Running nccmp on the two files and looking at all the differences, they are pretty extensive. It looks like most of the surface file differences are at the 6th or 7th significant digit but some of the cloud variables are different at the first significant digit.

**Comment by grantfirl** [comment]
@DeniseWorthen @junwang-noaa @climbfuji I recreated the baseline for the hafs_regional_telescopic_2nests_atm test on Cheyenne/intel and reran the test against the new baseline and it passed, meaning that it reproduced just fine. So, my guess is that something strange happened with the creation of baselines for this test on Cheyenne/intel. As mentioned above, looking at the code changes, there should be no way that any of it should affect this particular test.

Can we recreate baselines on Cheyenne/intel again and rerun the full RTs there to see if it was just a fluke?

**Comment by DeniseWorthen** [comment]
I think if you've created a new baseline for the test and verified against it, we probably have to conclude it was a fluke. 

I think we could move your new baseline for that test into the baseline area and re-run auto-rt to verify all baselines still pass. Do you have write permission to /glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs? If not, point me to your new baseline for the failed test and I will move it.

**Comment by grantfirl** [comment]
@DeniseWorthen I copied the new baseline for that test that I created into /glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20220113/INTEL and I renamed the original one created yesterday with the _old appendix. Interestingly, the file _sizes_ are actually different too between the 2 baselines with the ones created yesterday being larger by a few KB. It should be ready to rerun auto-rt on Cheyenne/intel then.

**Comment by grantfirl** [comment]
BTW, I didn't delete the /glade/scratch/dtcufsrt/FV3_RT/rt_48935 directory as directed by auto-rt. Will this fail automatically now?

**Comment by DeniseWorthen** [comment]
No, it will create a new rt_ directory for the new run.

**Comment by grantfirl** [comment]
Looking in /glade/scratch/dtcufsrt/autort/tests/auto/pr/816730657/20220114150014/ufs-weather-model/tests, it looks like the Cheyenne/Intel RTs were now successful.

**Comment by DeniseWorthen** [comment]
Yes, I can even see a commit message for the log but nothing has shown up yet. Can you grab it from 

/glade/scratch/dtcufsrt/autort/tests/auto/pr/816730657/20220114150014/ufs-weather-model/tests

**Comment by junwang-noaa** [comment]
@grantfirl would you please commit CCPP PR#809? Thanks

**Review by junwang-noaa — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Have the CI tests been run?

**Comment by grantfirl** [comment]
> Have the CI tests been run?

It looks like @MinsukJi-NOAA did last week. Does it need to happen again?

**Comment by MinsukJi-NOAA** [comment]
> > Have the CI tests been run?
> 
> It looks like @MinsukJi-NOAA did last week. Does it need to happen again?

CI was run previously; no need to run again.

**Review by climbfuji — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@grantfirl dusan is on leave this week so I think we should not wait for his review.

**Pull request merged**
