### PR TITLE
Create ESMF field attributes using the same kind as field data values

### LINKED ISSUE #1564: When esmf 8.4.0 is used coupled configuration tests fail
## Description

ESMF version 8.4.0 (and I believe 8.3.0 release but not 8.3.0b09) uses updated PIO library which has stricter attribute type checks, which causes model to fail due to mismatched floating point type (float vs double) used for some attributes (_FillValue and missing_value).

### To Reproduce:

Build ESMF 8.4.0, use it to build the model and run one of the coupled regression tests, for example cpld_control_p8. It will fail with this error:

 ```
20230111 163655.058 ERROR            PET144 ESMCI_PIO_Handler.C:1184 ESMCI::PIO_Handler::arrayWriteOn The NetCDF Library returned an error  -  Attempting to end definition of variable: bc1, (PIO/NetCDF error = NetCDF: Not a valid data type or _FillValue type mismatch)
20230111 163655.059 ERROR            PET144 ESMCI_IO_Handler.C:455 ESMCI::IO_Handler::arrayWrite() The NetCDF Library returned an error  - Internal subroutine call returned Error
20230111 163655.059 ERROR            PET144 ESMCI_IO.C:723 ESMCI::IO::write() The NetCDF Library returned an error  - Internal subroutine call returned Error
20230111 163655.059 ERROR            PET144 ESMCI_IO.C:494 ESMCI::IO::write() The NetCDF Library returned an error  - Internal subroutine call returned Error
20230111 163655.059 ERROR            PET144 ESMCI_IO_F.C:171 c_esmc_iowrite() Unable to write to file  - Internal subroutine call returned Error
20230111 163655.059 ERROR            PET144 ESMF_IO.F90:523 ESMF_IOAddArray() Unable to write to file  - Internal subroutine call returned Error
20230111 163655.059 ERROR            PET144 ESMF_FieldBundle.F90:17681 ESMF_FieldBundleWrite() Unable to write to file  - Internal subroutine call returned Error
20230111 163655.059 ERROR            PET144 module_wrt_grid_comp.F90:3388 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 module_wrt_grid_comp.F90:2951 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 module_wrt_grid_comp.F90:2117 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 fv3_cap.F90:1124 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 ATM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:2207 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:3488 Unable to write to file  - Phase 'phase2' Run for modelComp 2 did not return ESMF_SUCCESS
20230111 163655.059 ERROR            PET144 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:3726 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:3403 Unable to write to file  - Passing error in return code
20230111 163655.059 ERROR            PET144 UFS.F90:403 Unable to write to file  - Aborting UFS
20230111 163655.059 INFO             PET144 Finalizing ESMF
```

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description
This PR fixes the mismatch between ESMF field attributes and field data values types in fv3atm history files, and prevents model failure when ESMF v8.4.0 is used due to type mismatch check in underlying PIO library.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

Netcdf filed attributes (_FillValue and missing_value) will be changed but regression tests should pass with `ALT_CHECK......OK`. No changes in actual data values are expected.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Depends on https://github.com/NOAA-EMC/fv3atm/pull/618
Closes https://github.com/ufs-community/ufs-weather-model/issues/1564

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we can start working on this pr. Can you sync up branch? we are considering to add regional_control to ci.test. @zach1221 can you create a pr to Dusan's branch to add in ci.test change?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA we can start working on this pr. Can you sync up branch? we are considering to add regional_control to ci.test. @zach1221 can you create a pr to Dusan's branch to add in ci.test change?

I just synced my branches with develop.

**Comment by zach1221** [comment]
@jkbk2004 I have created the [PR]( https://github.com/DusanJovic-NOAA/ufs-weather-model/pull/37) for jenkins-ci regional_control.

**Comment by jkbk2004** [comment]
@zach1221 thanks! @DusanJovic-NOAA can you merge in Zach's pr to your branch?

**Comment by DusanJovic-NOAA** [comment]
> @zach1221 thanks! @DusanJovic-NOAA can you merge in Zach's pr to your branch?

Merged.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Please don't forget, we now require that upstream PR's are reviewed PRIOR to being allowed in the commit queue. This PR has not passed that requirement!

**Comment by BrianCurtis-NOAA** [comment]
Also, we should be getting the UFSWM PR reviewed prior to commit queue as well.

**Comment by jkbk2004** [comment]
> Also, we should be getting the UFSWM PR reviewed prior to commit queue as well.

Sure! Thanks for reminding!

**Comment by jkbk2004** [comment]
Code change only on fv_nggps_diag.f90 at the cubed sphere fvGFS driver level. The dependency https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/236 was approved. We can go ahead to review and approve for the pr.

**Review by zach1221 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
On Dogwood there is an issue with compiles going over the wallclock, but when I run them manually they run in 10-15 minutes, well before the wallclock.

**Comment by BrianCurtis-NOAA** [comment]
I will try one last time. Then I will skip and we can merge. It seems a random issue server side, not from the code.

**Comment by jkbk2004** [comment]
> I will try one last time. Then I will skip and we can merge. It seems a random issue server side, not from the code.

sure!

**Comment by BrianCurtis-NOAA** [comment]
It seems the transition to dogwood or cactus seems to make RT's run a little weird. Please skip Dogwood and Acorn. I need to look into what's going on with more time available.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA https://github.com/NOAA-EMC/fv3atm/pull/618 was merged.

**Pull request merged**
