### PR TITLE
[production/RRFS.v1] "to use fms/2024.1 & RUC LSM deep soil temperature updates"

### PR DESCRIPTION
**Pull request by haiqinli**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
### Commit Message:

```
* UFSWM -  
  * FV3 - 
    * ccpp-physics - 

### Priority:
<!--
Please provide the priority you would prefer this pull request to have.
* High: Time-sensitive project.
Please delete the ones that are not applicable
-->
* High: for the RRFS.v1

## Git Tracking

### Sub component Pull Requests:
<!--
Please provide a list of sub-components involved with this pull request.
Please provide links to the sub-component pull requests as shown below.
Please delete what is not needed.

-->
* FV3: https://github.com/NOAA-EMC/fv3atm/pull/852
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/217
 
### UFSWM Blocking Dependencies:
* None

---
## Changes
### Regression Test Changes (Please commit test_changes.list):
<!--
Please let us know if this PR creates new baselines, changes baselines or not.
* PR Updates/Changes Baselines.
-->

### Input data Changes:
<!--
If there are any changes to input-data for a test, please provide information here.
Please delete what is not needed.
-->
* None.

### Library Changes/Upgrades:
<!-- Library updates take time. Please provide library and version information here.
** SPECIAL INSTRUCTIONS **
If this PR needs updates to libraries please make sure to accomplish the following tasks:
- Create separate issue in (https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- Add issue link from JCSDA/spack-stack following this item <!-- for example: "* JCSDA/spack-stack#1757"

Please delete what is not needed.
-->
* No Updates
  
---
<!-- STOP!!! THE FOLLOWING IS FOR CODE MANAGERS ONLY. PLEASE DO NOT FILL OUT -->
## Testing Log:
- RDHPCS
  - [*] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [*] Derecho
- WCOSS2
  - [*] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
@haiqinli @jkbk2004 Starting to work on this one on WCOSS - creating new baselines.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA I am catching up on RDHPCS side.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA there is hercules file system issue.  I am trying to see if I can use Derecho for additional test.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA sorry for delay. I pushed Derecho test log ok. I will double to check if I can recover hercules baseline later. I think we can start merging process. I will go to sub PRs.

**Comment by MatthewPyle-NOAA** [comment]
Thanks for the update, @jkbk2004

**Review by jkbk2004 — APPROVED** [review]
@MatthewPyle-NOAA this pr can be merged with commit message.
```
* to compile the model with new fms/2024.01

* Update the RUC LSM deep soil temperature from climatology to real forecast.
```

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA Just to remind to clean up unnecessary commit messages when squash merge.

**Pull request merged**
