### PR TITLE
Update fms lib to use the version installed with avx

### PR DESCRIPTION
**Pull request by junwang-noaa**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

When the FMS was moved out of ufs-weather-model repository, the compile options to build fms library should be the same as the fms was built inside ufs-weather-model. The avx compile option was missed on hera. This needs to be fixed.

With the FMS library built with avx, the MOM6 results will change. This change as impact on all the regression test with mom6. New baseline needs to be created. There is no impact on all other platforms.

### Issue(s) addressed

- fixes ufs-weather-model issue [#777](https://github.com/ufs-community/ufs-weather-model/issues/777)

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI

## Dependencies

There is no dependency for this PR

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/721444382/20210829214521/ufs-weather-model
/work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20210830/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/721444382/20210830024505/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_43538
Test control_c384gdas 027 failed failed 
Test control_c384gdas 027 failed in run_test failed 
Test regional_restart 044 failed failed 
Test regional_restart 044 failed in run_test failed 
Test cpld_control_c384 008 failed failed 
Test cpld_control_c384 008 failed in run_test failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Test cpld_bmark_wave_v16_p7b 014 failed failed 
Test cpld_bmark_wave_v16_p7b 014 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
I checked all the 5 failed tests on gaea has error: JOB CANCELLED DUE TO TIME LIMIT". Will resubmit those tests

**Review by climbfuji — APPROVED** [review]
What about the CI tests?

**Comment by junwang-noaa** [comment]
It is still running. When it is done, we can commit the PR

**Pull request merged**
