### PR TITLE
Officially changed the ccpp-physics pointer to ufs-community/ccpp-physics ufs/dev branch for fv3atm

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR is for officially changing the ccpp-physics pointer from NCAR/ccpp-physics main branch to ufs-community/ccpp-physics ufs/dev branch in fv3atm. NO baselines changes for this PR.

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
- waiting on noaa-emc/fv3atm/pull/<[584](https://github.com/NOAA-EMC/fv3atm/pull/584)>

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
No code changes in UFSWM. Just pointing to a new fv3atm hash that only changes its .gitmodules to point to the new ccpp-physics fork/hash in ufs-community. No need to test these changes.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Just curious, why are we making this change?

**Comment by BrianCurtis-NOAA** [comment]
> Just curious, why are we making this change?

Agreement between NCAR and EMC so ccpp-physics can support other models in NCAR:main with someone taking on a role to sync them with a certain frequency.

**Comment by ChunxiZhang-NOAA** [comment]
> Just curious, why are we making this change?

It is the decision made by EMC and DTC. Most UFS related ccpp-physics PRs will go to this fork.

**Review by junwang-noaa — APPROVED** [review]

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA fv3 pr was merged. we can merge in this pr with submodule pointer update and revert in gitmodules.

**Comment by ChunxiZhang-NOAA** [comment]
@BrianCurtis-NOAA Done.

**Review by BrianCurtis-NOAA — APPROVED** [review]
@jkbk2004 It all looks good. Go ahead with merge.

**Pull request merged**
