### PR TITLE
update MOM6 to its main branch 20220317 commit

### LINKED ISSUE #1128: update MOM6 to its main branch 20220317 commit
MOM6 main branch was updated on 20220317, see detail at https://github.com/mom-ocean/MOM6/pull/1559. Need to update dev/emc correspondingly.

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

MOM6 main branch was updated on 20220317, which is based on FSU code updating to allow the ODA incremental counts (ncount) to be register in the restart file. No answer change is expected with this updating.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1128 
- MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/86

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by binli2337** [comment]
@jiandewang Please submit a PR from your feature/update-MOM6-20220317 branch to my feature/weekly_tests branch at https://github.com/binli2337/ufs-weather-model. Thanks!

This PR will be combined with #1132.

**Comment by jiandewang** [comment]
@binli2337 I just created the PR https://github.com/binli2337/ufs-weather-model/pull/3, thanks.

**Comment by jiandewang** [comment]
this PR is combined and done with https://github.com/ufs-community/ufs-weather-model/pull/1136

**Comment by junwang-noaa** [comment]
The code was committed. The PR is closed.

**Pull request closed without merging**
