### PR TITLE
 Bump libraries on WCOSS2 to ip/4.0.0 w3emc/2.12.0 and all platforms to fms/2024.01

### LINKED ISSUE #2358: Install FMS 2024.01 and test with UFSWM
## Description

FMS 2024.01 contains features/fixes we need with the UFSWM.
We'd like to see it installed on (if not already)
- [ ] Acorn
- [ ] WCOSS2 (Dogwood/Cactus)
- [x] Spack Stack 1.6 (RDHPCS)
Tier 1 machines:
- [x] Hera (Intel): /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Hera (GNU): /scratch2/NCEPDEV/stmp1/role.epic/spack-stack/spack-stack-1.6.0_gnu13/envs/fms-2024.01/install/modulefiles/Core
- [x] Gaea-C5 (Intel): /ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Gaea-C6 (Intel): /ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Jet (Intel): /contrib/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Orion (Intel): /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Hercules (GNU & Intel): /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/fms-2024.02/install/modulefiles/Core
- [x] Derecho (GNU & Intel): /glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] AWS (Intel): /contrib/spack-stack-rocky8/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [x] Azure (Intel): /contrib/spack-stack-rocky8/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core
- [ ] GCP (Intel) - out of resources

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Bump libraries on WCOSS2 to ip/4.0.0 w3emc/2.12.0 and fms/2024.01

### Commit Message:

```
* UFSWM - Bump libraries on WCOSS2 to ip/4.0.0 w3emc/2.12.0 and fms/2024.01
```

### Priority:

* Normal

### UFSWM:

* Closes #2358 

### Sub component Pull Requests:

* None

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.
  * cpld_control_sfs intel

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@XiaqiongZhou-NOAA is there any reason why cpld_control_sfs intel might fail in comparison? Are there any special FMS features that it uses?

Thanks for your help!

**Comment by BrianCurtis-NOAA** [comment]
There is also a possibility that the latest prod switch brought in an issue where we can just create new baselines for that test and be good to go.

**Comment by BrianCurtis-NOAA** [comment]
@XiaqiongZhou-NOAA I tested the current develop branch with that test on wcoss2 and it also failed, so i'll go ahead and regenerate that baseline and re-compare with these changes. I'll let you know if any issue crops up again.

**Comment by jkbk2004** [comment]
@zach1221 @FernandoAndrade-NOAA @RatkoVasic-NOAA can we apply ufs_common update in this pr for fms2024.01? I understand tests are done at hera, hercules, orion. But we need to make sure the new FMS is ready on Gaea, jet, and Derecho as well. @RatkoVasic-NOAA do we have any issue on those machines?

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 I finished all machines (except of GCP, for which we don't have resources). You can start testing all machines with new FMS environment. [Here is list of directories](https://github.com/ufs-community/ufs-weather-model/issues/2358#issue-2395541743).

**Comment by BrianCurtis-NOAA** [comment]
I can bump the ufs_common, sure.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I think we should be able to commit this pr today. Can you update ufs_common as well?

**Comment by BrianCurtis-NOAA** [comment]
I'm going to run WCOSS2 RT again as the FMS location was put into a default location. Please run on a GNU supported platform to verify it's all good for RDHPCS testing.

**Comment by jkbk2004** [comment]
@zach1221 @FernandoAndrade-NOAA I am running on hera and hercules. Go ahead to pick up other machines.

**Comment by BrianCurtis-NOAA** [comment]
@AlexanderRichert-NOAA can you install FMS 2024.01 on Acorn's spack stack 1.6.0 ?

**Comment by AlexanderRichert-NOAA** [comment]
@BrianCurtis-NOAA I've installed FMS 2024.01 on Acorn based on the spack-stack 1.6.0 unified environment: /lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.6.0/envs/unified-env-fms-2024.01/install/modulefiles/Core

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I've installed FMS 2024.01 on Acorn based on the spack-stack 1.6.0 unified environment: /lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.6.0/envs/unified-env-fms-2024.01/install/modulefiles/Core

@AlexanderRichert-NOAA Thank you! I have verified the modulefile loads and fms 2024.01 shows up. I'm running tests on Acorn now.

**Comment by BrianCurtis-NOAA** [comment]
@AlexanderRichert-NOAA I can't get the following two libraries to load via your spack build:
  {["g2"]              = "3.5.1"},
  {["g2tmpl"]          = "1.13.0"},

**Comment by RatkoVasic-NOAA** [comment]
@AlexanderRichert-NOAA I used this in spack.yaml for all fms@2024.01 installations:
```
    - upp-env %intel ^g2tmpl@1.13.0 ^g2@3.5.1
    - ip %intel
    - nco@5.0.6 %intel
    - met@11.1.0 %intel
    - metplus@5.1.0 %intel
    - fms@2024.01 %intel
    - prod-util@2.1.1 %intel
    - wgrib2@2.0.8 %intel
    - grib-util@1.3.0 %intel ^g2@3.5.1
    - ufs-weather-model-env %intel ^g2tmpl@1.13.0 ^g2@3.5.1
    - upp-env %gcc ^g2tmpl@1.13.0 ^g2@3.5.1
```
nco, met and met+ were needed for SRW, you probably don't need that in WCOSS2.

**Comment by AlexanderRichert-NOAA** [comment]
Sorry, I installed those then forget to update here. Please try the same environment again.

**Comment by BrianCurtis-NOAA** [comment]
How is the ORT coming along?

**Comment by FernandoAndrade-NOAA** [comment]
They needed to be rerun manually due to disk quota, they should hopefully finish soon.

**Comment by DusanJovic-NOAA** [comment]
Why do we run ORT if there are no code changes and no baseline changes?

**Review by jkbk2004 — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
