### PR TITLE
Updates for NOAA Cloud Rocky 8 platforms

### PR DESCRIPTION
**Pull request by natalie-perlin**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:
Updated modulefile and rt.sh to use NOAA Cloud Rocky8 platforms
Files changed:
- modulefiles/ufs_noaacloud.intel.lua (loading spack-stack procedure change)
- tests/rt.sh  (use rocoto module on Rocky 8 platforms)

## Dependencies:

https://github.com/ufs-community/ufs-srweather-app/pull/1129

### Commit Message:

Updates for use Rocky8 OS on NOAA Cloud platforms.

```
* UFSWM - 
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - 
    * ccpp-physics - 
    * atmos_cubed_sphere - 
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 - 
  * stochastic_physics - 
```

### Priority:

* Normal.

### UFSWM:

https://github.com/ufs-community/ufs-weather-model/issues/2433
* Closes #
https://github.com/ufs-community/ufs-weather-model/issues/2433
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by natalie-perlin** [comment]
NOTE: Running actual tests on any NOAA CSP requires input data and baselines to be stages on that platform. Not yet available at the time. Please update on the testing process!

**Comment by zach1221** [comment]
@natalie-perlin I created new baselines on AWS and Azure rocky8 instances, dated develop-20240909, using the rocky8 spack-stack installations. In the process of creating the new baselines I was able to verify running regression tests on the two platforms. I've added the changes I used to get the tests to pass.

**Review by RatkoVasic-NOAA — APPROVED** [review]
Looks good. Approved.

**Comment by natalie-perlin** [comment]
@jkbk2004 @zach1221 - Could this PR be closed, as all the relevant changes were merged through PR#2431?
https://github.com/ufs-community/ufs-weather-model/pull/2431/files#diff-38c4a02bffd6eec565a221ea266c2254ef4a1aba4d56cd1ae28a1f867f65d7e3

**Comment by zach1221** [comment]
> @jkbk2004 @zach1221 - Could this PR be closed, as all the relevant changes were merged through PR#2431? https://github.com/ufs-community/ufs-weather-model/pull/2431/files#diff-38c4a02bffd6eec565a221ea266c2254ef4a1aba4d56cd1ae28a1f867f65d7e3

Yes, I think it can be closed.

**Comment by natalie-perlin** [comment]
Closed, as relevant changes merged through #2431 
https://github.com/ufs-community/ufs-weather-model/pull/2431

**Pull request closed without merging**
