### PR TITLE
Add import/export fields for fv3-jedi coupling

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

This PR adds import and export fields to support fv3-jedi coupling
fd_nems.yaml file is updated to include fields used in fv3-jedi coupling. It is actual file now, not a symlink to a file in CMEPS repo.
No baseline change, no new input data.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [ ] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on NOAA-EMC/fv3atm/pull/301

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/647749343/20210520074509/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_52206
Test fv3_control_32bit 047 failed in check_result failed 
Test fv3_control_32bit 047 failed in run_test failed 
Test fv3_gfdlmp_32bit 062 failed in check_result failed 
Test fv3_gfdlmp_32bit 062 failed in run_test failed 
Test fv3_gfdlmprad_32bit_post 063 failed in check_result failed 
Test fv3_gfdlmprad_32bit_post 063 failed in run_test failed 
Test fv3_hrrr 068 failed in check_result failed 
Test fv3_hrrr 068 failed in run_test failed 
Test fv3_rrfs_v1alpha 066 failed in check_result failed 
Test fv3_rrfs_v1alpha 066 failed in run_test failed 
Test fv3_thompson 069 failed in check_result failed 
Test fv3_thompson 069 failed in run_test failed 
Test fv3_thompson_no_aero 070 failed in check_result failed 
Test fv3_thompson_no_aero 070 failed in run_test failed 
Test fv3_rrfs_v1beta 071 failed in check_result failed 
Test fv3_rrfs_v1beta 071 failed in run_test failed 
Test fv3_rap 067 failed in check_result failed 
Test fv3_rap 067 failed in run_test failed 
Test fv3_regional_quilt_netcdf_parallel 054 failed in check_result failed 
Test fv3_regional_quilt_netcdf_parallel 054 failed in run_test failed 
Test fv3_regional_quilt 052 failed in check_result failed 
Test fv3_regional_quilt 052 failed in run_test failed 
Test fv3_regional_quilt_hafs 053 failed in check_result failed 
Test fv3_regional_quilt_hafs 053 failed in run_test failed 
Test fv3_regional_control 050 failed in check_result failed 
Test fv3_regional_control 050 failed in run_test failed 
Test fv3_stretched 048 failed in check_result failed 
Test fv3_stretched 048 failed in run_test failed 
Test fv3_stretched_nest 049 failed in check_result failed 
Test fv3_stretched_nest 049 failed in run_test failed 
Test fv3_gsd 065 failed in check_result failed 
Test fv3_gsd 065 failed in run_test failed 
Test fv3_regional_quilt_RRTMGP 055 failed in check_result failed 
Test fv3_regional_quilt_RRTMGP 055 failed in run_test failed 
Test fv3_cpt 064 failed in check_result failed 
Test fv3_cpt 064 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
> Machine: cheyenne
> Compiler: intel
> Job: RT
> Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/647749343/20210520074509/ufs-weather-model
> Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_52206
> Test fv3_control_32bit 047 failed in check_result failed
> Test fv3_control_32bit 047 failed in run_test failed
> Test fv3_gfdlmp_32bit 062 failed in check_result failed
> Test fv3_gfdlmp_32bit 062 failed in run_test failed
> Test fv3_gfdlmprad_32bit_post 063 failed in check_result failed
> Test fv3_gfdlmprad_32bit_post 063 failed in run_test failed
> Test fv3_hrrr 068 failed in check_result failed
> Test fv3_hrrr 068 failed in run_test failed
> Test fv3_rrfs_v1alpha 066 failed in check_result failed
> Test fv3_rrfs_v1alpha 066 failed in run_test failed
> Test fv3_thompson 069 failed in check_result failed
> Test fv3_thompson 069 failed in run_test failed
> Test fv3_thompson_no_aero 070 failed in check_result failed
> Test fv3_thompson_no_aero 070 failed in run_test failed
> Test fv3_rrfs_v1beta 071 failed in check_result failed
> Test fv3_rrfs_v1beta 071 failed in run_test failed
> Test fv3_rap 067 failed in check_result failed
> Test fv3_rap 067 failed in run_test failed
> Test fv3_regional_quilt_netcdf_parallel 054 failed in check_result failed
> Test fv3_regional_quilt_netcdf_parallel 054 failed in run_test failed
> Test fv3_regional_quilt 052 failed in check_result failed
> Test fv3_regional_quilt 052 failed in run_test failed
> Test fv3_regional_quilt_hafs 053 failed in check_result failed
> Test fv3_regional_quilt_hafs 053 failed in run_test failed
> Test fv3_regional_control 050 failed in check_result failed
> Test fv3_regional_control 050 failed in run_test failed
> Test fv3_stretched 048 failed in check_result failed
> Test fv3_stretched 048 failed in run_test failed
> Test fv3_stretched_nest 049 failed in check_result failed
> Test fv3_stretched_nest 049 failed in run_test failed
> Test fv3_gsd 065 failed in check_result failed
> Test fv3_gsd 065 failed in run_test failed
> Test fv3_regional_quilt_RRTMGP 055 failed in check_result failed
> Test fv3_regional_quilt_RRTMGP 055 failed in run_test failed
> Test fv3_cpt 064 failed in check_result failed
> Test fv3_cpt 064 failed in run_test failed
> Please make changes and add the following label back:
> cheyenne-intel-RT

Looks like these are all tests compiled with `32BIT=Y`. Example:
```
heinzell@cheyenne1:/glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/647749343/20210520074509/ufs-weather-model/tests> cat log_cheyenne.intel/rt_047_fv3_control_32bit.log

baseline dir = /glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20210517/INTEL/fv3_control_32bit
working dir  = /glade/scratch/briancurtis/FV3_RT/rt_52206/fv3_control_32bit
Checking test 047 fv3_control_32bit results ....
 Comparing atmos_4xdaily.tile1.nc ............ALT CHECK......NOT OK
 Comparing atmos_4xdaily.tile2.nc ............ALT CHECK......NOT OK
 Comparing atmos_4xdaily.tile3.nc ............ALT CHECK......NOT OK
 Comparing atmos_4xdaily.tile4.nc ............ALT CHECK......NOT OK
 Comparing atmos_4xdaily.tile5.nc ............ALT CHECK......NOT OK
 Comparing atmos_4xdaily.tile6.nc ............ALT CHECK......NOT OK
 Comparing phyf000.tile1.nc ............ALT CHECK......NOT OK
 Comparing phyf000.tile2.nc ............ALT CHECK......NOT OK
 Comparing phyf000.tile3.nc ............ALT CHECK......NOT OK
 Comparing phyf000.tile4.nc ............ALT CHECK......NOT OK
 Comparing phyf000.tile5.nc ............ALT CHECK......NOT OK
 Comparing phyf000.tile6.nc ............ALT CHECK......NOT OK
 Comparing phyf024.tile1.nc ............ALT CHECK......NOT OK
 Comparing phyf024.tile2.nc ............ALT CHECK......NOT OK
 Comparing phyf024.tile3.nc ............ALT CHECK......NOT OK
 Comparing phyf024.tile4.nc ............ALT CHECK......NOT OK
 Comparing phyf024.tile5.nc ............ALT CHECK......NOT OK
 Comparing phyf024.tile6.nc ............ALT CHECK......NOT OK
 Comparing dynf000.tile1.nc ............ALT CHECK......NOT OK
 Comparing dynf000.tile2.nc ............ALT CHECK......NOT OK
 Comparing dynf000.tile3.nc ............ALT CHECK......NOT OK
 Comparing dynf000.tile4.nc ............ALT CHECK......NOT OK
 Comparing dynf000.tile5.nc ............ALT CHECK......NOT OK
 Comparing dynf000.tile6.nc ............ALT CHECK......NOT OK
 Comparing dynf024.tile1.nc ............ALT CHECK......NOT OK
 Comparing dynf024.tile2.nc ............ALT CHECK......NOT OK
 Comparing dynf024.tile3.nc ............ALT CHECK......NOT OK
 Comparing dynf024.tile4.nc ............ALT CHECK......NOT OK
 Comparing dynf024.tile5.nc ............ALT CHECK......NOT OK
 Comparing dynf024.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile6.nc ............ALT CHECK......NOT OK

0:The total amount of wall time                        = 40.663099

Test 047 fv3_control_32bit FAIL
```

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/647749343/20210520150007/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_29697
Test fv3_regional_quilt_netcdf_parallel 054 failed in check_result failed 
Test fv3_regional_quilt_netcdf_parallel 054 failed in run_test failed 
Test fv3_regional_control 050 failed in check_result failed 
Test fv3_regional_control 050 failed in run_test failed 
Test fv3_regional_quilt_hafs 053 failed in check_result failed 
Test fv3_regional_quilt_hafs 053 failed in run_test failed 
Test fv3_regional_quilt 052 failed in check_result failed 
Test fv3_regional_quilt 052 failed in run_test failed 
Test fv3_control_32bit 047 failed in check_result failed 
Test fv3_control_32bit 047 failed in run_test failed 
Test fv3_regional_quilt_RRTMGP 055 failed in check_result failed 
Test fv3_regional_quilt_RRTMGP 055 failed in run_test failed 
Test fv3_stretched 048 failed in check_result failed 
Test fv3_stretched 048 failed in run_test failed 
Test fv3_stretched_nest 049 failed in check_result failed 
Test fv3_stretched_nest 049 failed in run_test failed 
Test fv3_gfdlmp_32bit 062 failed in check_result failed 
Test fv3_gfdlmp_32bit 062 failed in run_test failed 
Test fv3_gfdlmprad_32bit_post 063 failed in check_result failed 
Test fv3_gfdlmprad_32bit_post 063 failed in run_test failed 
Test fv3_rrfs_v1alpha 066 failed in check_result failed 
Test fv3_rrfs_v1alpha 066 failed in run_test failed 
Test fv3_gsd 065 failed in check_result failed 
Test fv3_gsd 065 failed in run_test failed 
Test fv3_cpt 064 failed in check_result failed 
Test fv3_cpt 064 failed in run_test failed 
Test fv3_rap 067 failed in check_result failed 
Test fv3_rap 067 failed in run_test failed 
Test fv3_hrrr 068 failed in check_result failed 
Test fv3_hrrr 068 failed in run_test failed 
Test fv3_thompson 069 failed in check_result failed 
Test fv3_thompson 069 failed in run_test failed 
Test fv3_thompson_no_aero 070 failed in check_result failed 
Test fv3_thompson_no_aero 070 failed in run_test failed 
Test fv3_rrfs_v1beta 071 failed in check_result failed 
Test fv3_rrfs_v1beta 071 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/647749343/20210521071509/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_2976
Test fv3_satmedmf 046 failed in run_test failed 
Test fv3_satmedmfq 047 failed in run_test failed 
Test fv3_csawmg 045 failed in run_test failed 
Test compile 012 failed failed 
Test fv3_wrtGauss_netcdf 022 failed in run_test failed 
Test fv3_wrtGlatlon_netcdf 024 failed in run_test failed 
Test fv3_multigases 032 failed in run_test failed 
Test fv3_wrtGauss_nemsio 025 failed in run_test failed 
Test fv3_lheatstrg 031 failed in run_test failed 
Test fv3_stretched_nest 035 failed in run_test failed 
Test fv3_stretched 034 failed in run_test failed 
Test fv3_regional_quilt_netcdf_parallel 040 failed in run_test failed 
Test fv3_wrtGauss_netcdf_esmf 021 failed in run_test failed 
Test fv3_wrtGauss_netcdf_parallel 023 failed in run_test failed 
Test fv3_regional_quilt_RRTMGP 041 failed in run_test failed 
Test fv3_regional_quilt 038 failed in run_test failed 
Test fv3_control_32bit 033 failed in run_test failed 
Test fv3_lndp 029 failed in run_test failed 
Test fv3_stochy 027 failed in run_test failed 
Test fv3_regional_quilt_hafs 039 failed in run_test failed 
Test fv3_gfdlmprad_gwd 043 failed in run_test failed 
Test fv3_ca 028 failed in run_test failed 
Test fv3_gfdlmp 042 failed in run_test failed 
Test fv3_wrtGauss_nemsio_c192 026 failed in run_test failed 
Test fv3_control 019 failed in run_test failed 
Test fv3_gfdlmprad_noahmp 044 failed in run_test failed 
Test compile 018 failed failed 
Test fv3_regional_control 036 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Disk Quota issues on Cheyenne, working on it

**Review by junwang-noaa — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Ready for merge.

**Pull request merged**
