### PR TITLE
Update inline post

### LINKED ISSUE #645: The in-line post interface clean up
## Description
Dusan suggests that the in-line post interface needs a clean up for legacy setting and code format.  

## Solution

>  I'm looking at the code I thought I should mention, there are many OMP directives in which im is listed as shared variable but it is not used in the code at all, for example
> 
> !$omp parallel do default(none) private(i,j) shared(jsta,jend,im,spval,pt,pd,pint,ista,iend)
>       do j=jsta,jend
>         do i=ista,iend
>           pd(i,j)     = spval
>           pint(i,j,1) = pt
>         end do
>       end do
> Also, code indentation is terrible, it is very difficult to reason about the code and understand the logic with inconsistent indentation. This file (post_fv3.F90) requires some serious clean up.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### LINKED ISSUE #1748: Inline post: move computation of diagnostic variables outside a do loop that loads arrays from a bundle
In inline post the computation of diagnostic variables here:

https://github.com/NOAA-EMC/fv3atm/blob/160b422dc1d294623cc8ebfabfbe7d28d7c65c62/io/post_fv3.F90#L4353

from line 4353 to 4413 (and several other loops) should me moved outside of the field loop (after file_loop_all loop) . Those additional fields should be computed when all the fields from the fields bundle have been assigned values, otherwise these fields will be computed when each field is assigned values.

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
## Description

Update inline post with:

- Clean up legacy code in inline post interface

- Relocate computation of diagnostic variables

- Sync changes from offline post interface

- Update upp revision

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
The UPP output grib2 files for global and regional FV3, such as datasets GFSPRS, NATLEV, PRSLEV due to upp upgrade.

[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/11937917/RegressionTests_hera.log)
[RegressionTests_hera-0702.log](https://github.com/ufs-community/ufs-weather-model/files/12017687/RegressionTests_hera-0702.log)

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.: attached WCOSS2 test log
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on PR: NOAA-EMC/fv3atm/pull/666
- Closes NOAA-EMC/fv3atm/issues/645
- Closes ufs-community/ufs-weather-model/issues/1748

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@WenMeng-NOAA Can we check the status of this pr? If good status, can we follow up to attach pre regression test log?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Can we check the status of this pr? If good status, can we follow up to attach pre regression test log?

@jkbk2004 I have been waiting for my FV3 PR reviewed. Meanwhile I can sync my branch for regression testing.

**Comment by WenMeng-NOAA** [comment]
WCOSS2 RT test log
[RegressionTests_wcoss2.log](https://github.com/ufs-community/ufs-weather-model/files/11902002/RegressionTests_wcoss2.log)

**Comment by jkbk2004** [comment]
@WenMeng-NOAA All pre test looks good. Can you try to combine in @BrianCurtis-NOAA #1810 ort script update?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA All pre test looks good. Can you try to combine in @BrianCurtis-NOAA #1810 ort script update?

@jkbk2004 What is the best way to combine my PR #1794 and @BrianCurtis-NOAA 's PR #1810? Manually pick up his changes and commit in my branch?

**Comment by jkbk2004** [comment]
> > @WenMeng-NOAA All pre test looks good. Can you try to combine in @BrianCurtis-NOAA #1810 ort script update?
> 
> @jkbk2004 What is the best way to combine my PR #1794 and @BrianCurtis-NOAA 's PR #1810? Manually pick up his changes and commit in my branch?

  git clone -b upp_june https://github.com/WenMeng-NOAA/ufs-weather-model
  cd ufs-weather-model/
  git remote add upstream https://github.com/BrianCurtis-NOAA/ufs-weather-model
  git fetch upstream
  git merge upstream/fixortdbg
  git push origin upp_june

**Comment by WenMeng-NOAA** [comment]
> > > @WenMeng-NOAA All pre test looks good. Can you try to combine in @BrianCurtis-NOAA #1810 ort script update?
> > 
> > 
> > @jkbk2004 What is the best way to combine my PR #1794 and @BrianCurtis-NOAA 's PR #1810? Manually pick up his changes and commit in my branch?
> 
> git clone -b upp_june https://github.com/WenMeng-NOAA/ufs-weather-model cd ufs-weather-model/ git remote add upstream https://github.com/BrianCurtis-NOAA/ufs-weather-model git fetch upstream git merge upstream/fixortdbg git push origin upp_june

@jkbk2004 Done.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, looks like this is ready for testing, getting started with jenkins ci @BrianCurtis-NOAA

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 we're Hera RT's ran? Where is that log?

**Comment by jkbk2004** [comment]
> @jkbk2004 we're Hera RT's ran? Where is that log?

Attached hera log in the pr description above. No crash on hera. Jenkins-ci underway. I am going to manually submit BL creation on hera now.

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA can you check jenkins-ci status?

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA can you check jenkins-ci status?

regional_control_gnu thr and dcp failed, I'll start a manual run on Hera

**Comment by FernandoAndrade-NOAA** [comment]
Apologies for the delay, there were timeout issues with std case. dcp regional_control_gnu is still running at the moment, thr test case failed during the comparisons to NATLEV.GrbF06 and PRSLEV.GrbF06

**Comment by jkbk2004** [comment]
@WenMeng-NOAA I see several cases fail on hera as well: regional_control_intel, regional_control_qr_intel, regional_decomp_intel, regional_2threads_intel, regional_2dwrtdecomp_intel,, regional_control_faster_intel. Baselines were created ok but these cases don't reproduce in the runs to compare.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA FYI: note above.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I see several cases fail on hera as well: regional_control_intel, regional_control_qr_intel, regional_decomp_intel, regional_2threads_intel, regional_2dwrtdecomp_intel,, regional_control_faster_intel. Baselines were created ok but these cases don't reproduce in the runs to compare.

@jkbk2004 There is a bug fix including in upp revision upgrade. That would make changes of regional grib2 files. Could you provide me your run directories on  Here?

**Comment by WenMeng-NOAA** [comment]
> > @WenMeng-NOAA I see several cases fail on hera as well: regional_control_intel, regional_control_qr_intel, regional_decomp_intel, regional_2threads_intel, regional_2dwrtdecomp_intel,, regional_control_faster_intel. Baselines were created ok but these cases don't reproduce in the runs to compare.
> 
> @jkbk2004 There is a bug fix including in upp revision upgrade. That would make changes of regional grib2 files. Could you provide me your run directories on Here?

@jkbk2004 I looked into your testing log on Hera. It's consistent with mine. The changes of grib2 files for global (GFSPRS*) and regional (NATLEV*, PRSLEV*) are expected due to upp revision upgrade.

**Comment by jkbk2004** [comment]
> > > @WenMeng-NOAA I see several cases fail on hera as well: regional_control_intel, regional_control_qr_intel, regional_decomp_intel, regional_2threads_intel, regional_2dwrtdecomp_intel,, regional_control_faster_intel. Baselines were created ok but these cases don't reproduce in the runs to compare.
> > 
> > 
> > @jkbk2004 There is a bug fix including in upp revision upgrade. That would make changes of regional grib2 files. Could you provide me your run directories on Here?
> 
> @jkbk2004 I looked into your testing log on Hera. It's consistent with mine. The changes of grib2 files for global (GFSPRS*) and regional (NATLEV*, PRSLEV*) are expected due to upp revision upgrade.

experiment is at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_289959/regional_control_intel. Sounds like still some issue with grib2 files. I see 
 Comparing PRSLEV.GrbF06 .........NOT OK
 Comparing NATLEV.GrbF06 .........NOT OK

**Comment by WenMeng-NOAA** [comment]
> > > > @WenMeng-NOAA I see several cases fail on hera as well: regional_control_intel, regional_control_qr_intel, regional_decomp_intel, regional_2threads_intel, regional_2dwrtdecomp_intel,, regional_control_faster_intel. Baselines were created ok but these cases don't reproduce in the runs to compare.
> > > 
> > > 
> > > @jkbk2004 There is a bug fix including in upp revision upgrade. That would make changes of regional grib2 files. Could you provide me your run directories on Here?
> > 
> > 
> > @jkbk2004 I looked into your testing log on Hera. It's consistent with mine. The changes of grib2 files for global (GFSPRS*) and regional (NATLEV*, PRSLEV*) are expected due to upp revision upgrade.
> 
> experiment is at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_289959/regional_control_intel. Sounds like still some issue with grib2 files. I see Comparing PRSLEV.GrbF06 .........NOT OK Comparing NATLEV.GrbF06 .........NOT OK

@jkbk2004 These are upp output files in grib2 for regional.  With upp revision upgrade in this PR, the grib2 files will not be bite-wise identical. I did field-by-field data values comparison and would think the changes mainly come from grib2 head message (except visibility change). These are expected.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 A fix was implemented in the inline post interface. From my single testing, it can solve the reproducibility issue. Can you testing with my latest commit?

**Comment by jkbk2004** [comment]
> @jkbk2004 A fix was implemented in the inline post interface. From my single testing, it can solve the reproducibility issue. Can you testing with my latest commit?

@WenMeng-NOAA sure! I will keep you posted.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 I just tweaked the fix and committed it.

**Comment by jkbk2004** [comment]
> @jkbk2004 I just tweaked the fix and committed it.

@WenMeng-NOAA Failed cases reproduce ok with the fix on hera.

**Comment by jkbk2004** [comment]
@WenMeng-NOAA can you sync up branch? we may start working on this pr while we prepare #1777.

**Comment by jkbk2004** [comment]
@WenMeng-NOAA Do you have hera test log to attach?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA can you sync up branch? we may start working on this pr while we prepare #1777.

@jkbk2004 During syncing process, there are some conflicts in tests/rt.sh which I combined changes from @BrianCurtis-NOAA 's PR #1810. Can someone help me to solve them? My tests/rt.sh file with conflicts can be accessed at  /u/wen.meng/noscrub/ufs_wen/ufs-weather-model on WCOSS2 Dogwood. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
@WenMeng-NOAA if you made no changes yourself to rt.sh, then use `git checkout -- tests/rt.sh` and then `git pull` from ufs-weather-model/develop again.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA can you sync up branch? we may start working on this pr while we prepare #1777.

@jkbk2004 Done.

**Comment by jkbk2004** [comment]
@WenMeng-NOAA Can we attach any test log from hera? You already attached wcoss2 log but any additional test log from hera will be helpful to move the pr.

**Comment by zach1221** [comment]
Looks like completed Hera pre-test logs have been attached. So, I'll add this PR to the commit queue and we can begin testing. @jkbk2004

**Comment by zach1221** [comment]
jenkins-ci is finished. ORTs all passed.
[ufs-weather-model » ort-docker-pipeline » PR-1794 #2 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/12021993/ufs-weather-model.ort-docker-pipeline.PR-1794.2.Console.Jenkins.pdf)

**Comment by BrianCurtis-NOAA** [comment]
I don't understand the Hera logs. With the tests that are mentioned to fail with this PR, the Hera RT shows things passing and failing for both of them. We typically like PR authors to run the full Hera RT suite and keep the failures in it, so we can look through to make sure it all makes sense.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA do you think the logs should be cleaned up and re-added before proceeding?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA do you think the logs should be cleaned up and re-added before proceeding?

Do what the logs show failing make sense with the code changes?

**Comment by zach1221** [comment]
Ok, I've cleaned up the logs and left just the failures.
[RegressionTests_hera-0702 (1).log](https://github.com/ufs-community/ufs-weather-model/files/12028874/RegressionTests_hera-0702.1.log)

**Comment by BrianCurtis-NOAA** [comment]
> > @BrianCurtis-NOAA do you think the logs should be cleaned up and re-added before proceeding?
> 
> Do what the logs show failing make sense with the code changes?

To answer that. The logs in both cases show the regional tests fail, then there is one test in which hrrr tests fail as well but it's an older test.

I am assuming the regional tests shown in the logs will fail and I will start Acorn/WCOSS2 baselines with those tests. 
```
001 regional_control_intel failed in check_result
regional_control_intel 001 failed in run_test
003 regional_control_qr_intel failed in check_result
regional_control_qr_intel 003 failed in run_test
005 regional_decomp_intel failed in check_result
regional_decomp_intel 005 failed in run_test
006 regional_2threads_intel failed in check_result
regional_2threads_intel 006 failed in run_test
007 regional_2dwrtdecomp_intel failed in check_result
regional_2dwrtdecomp_intel 007 failed in run_test
008 regional_control_faster_intel failed in check_result
regional_control_faster_intel 008 failed in run_test
```

**Comment by BrianCurtis-NOAA** [comment]
Failure on WCOSS2
```
 ...
 Comparing GFSPRS.GrbF00 .........NOT OK
 Comparing GFSPRS.GrbF24 .........NOT OK
```
failed tests:
```
FAILED TESTS:
011 cpld_bmark_p8_intel failed in check_result
cpld_bmark_p8_intel 011 failed in run_test
018 control_flake_intel failed in check_result
control_flake_intel 018 failed in run_test
020 control_latlon_intel failed in check_result
control_latlon_intel 020 failed in run_test
021 control_wrtGauss_netcdf_parallel_intel failed in check_result
control_wrtGauss_netcdf_parallel_intel 021 failed in run_test
023 control_c192_intel failed in check_result
control_c192_intel 023 failed in run_test
024 control_c384_intel failed in check_result
control_c384_intel 024 failed in run_test
025 control_c384gdas_intel failed in check_result
control_c384gdas_intel 025 failed in run_test
026 control_stochy_intel failed in check_result
control_stochy_intel 026 failed in run_test
028 control_lndp_intel failed in check_result
control_lndp_intel 028 failed in run_test
029 control_iovr4_intel failed in check_result
control_iovr4_intel 029 failed in run_test
030 control_iovr5_intel failed in check_result
control_iovr5_intel 030 failed in run_test
031 control_p8_intel failed in check_result
control_p8_intel 031 failed in run_test
033 control_qr_p8_intel failed in check_result
control_qr_p8_intel 033 failed in run_test
035 control_decomp_p8_intel failed in check_result
control_decomp_p8_intel 035 failed in run_test
036 control_2threads_p8_intel failed in check_result
control_2threads_p8_intel 036 failed in run_test
037 control_p8_lndp_intel failed in check_result
control_p8_lndp_intel 037 failed in run_test
038 control_p8_rrtmgp_intel failed in check_result
control_p8_rrtmgp_intel 038 failed in run_test
039 control_p8_mynn_intel failed in check_result
control_p8_mynn_intel 039 failed in run_test
040 merra2_thompson_intel failed in check_result
merra2_thompson_intel 040 failed in run_test
050 regional_wofs_intel failed in check_result
regional_wofs_intel 050 failed in run_test
051 rap_control_intel failed in check_result
rap_control_intel 051 failed in run_test
052 regional_spp_sppt_shum_skeb_intel failed in check_result
regional_spp_sppt_shum_skeb_intel 052 failed in run_test
053 rap_decomp_intel failed in check_result
rap_decomp_intel 053 failed in run_test
054 rap_2threads_intel failed in check_result
rap_2threads_intel 054 failed in run_test
056 rap_sfcdiff_intel failed in check_result
rap_sfcdiff_intel 056 failed in run_test
057 rap_sfcdiff_decomp_intel failed in check_result
rap_sfcdiff_decomp_intel 057 failed in run_test
059 rrfs_v1beta_intel failed in check_result
rrfs_v1beta_intel 059 failed in run_test
060 rrfs_v1nssl_intel failed in check_result
rrfs_v1nssl_intel 060 failed in run_test
061 rrfs_v1nssl_nohailnoccn_intel failed in check_result
rrfs_v1nssl_nohailnoccn_intel 061 failed in run_test
069 control_csawmg_intel failed in check_result
control_csawmg_intel 069 failed in run_test
070 control_csawmgt_intel failed in check_result
control_csawmgt_intel 070 failed in run_test
071 control_ras_intel failed in check_result
control_ras_intel 071 failed in run_test
073 control_p8_faster_intel failed in check_result
control_p8_faster_intel 073 failed in run_test
103 regional_spp_sppt_shum_skeb_dyn32_phy32_intel failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32_intel 103 failed in run_test
104 rap_control_dyn32_phy32_intel failed in check_result
rap_control_dyn32_phy32_intel 104 failed in run_test
105 hrrr_control_dyn32_phy32_intel failed in check_result
hrrr_control_dyn32_phy32_intel 105 failed in run_test
106 hrrr_control_qr_dyn32_phy32_intel failed in check_result
hrrr_control_qr_dyn32_phy32_intel 106 failed in run_test
107 rap_2threads_dyn32_phy32_intel failed in check_result
rap_2threads_dyn32_phy32_intel 107 failed in run_test
108 hrrr_control_2threads_dyn32_phy32_intel failed in check_result
hrrr_control_2threads_dyn32_phy32_intel 108 failed in run_test
109 hrrr_control_decomp_dyn32_phy32_intel failed in check_result
hrrr_control_decomp_dyn32_phy32_intel 109 failed in run_test
113 rrfs_smoke_conus13km_fast_phy32_intel failed in check_result
rrfs_smoke_conus13km_fast_phy32_intel 113 failed in run_test
114 rrfs_smoke_conus13km_fast_phy32_qr_intel failed in check_result
rrfs_smoke_conus13km_fast_phy32_qr_intel 114 failed in run_test
117 rap_control_dyn64_phy32_intel failed in check_result
rap_control_dyn64_phy32_intel 117 failed in run_test
121 hafs_regional_atm_intel failed in check_result
hafs_regional_atm_intel 121 failed in run_test
131 hafs_global_multiple_4nests_atm_intel failed in check_result
hafs_global_multiple_4nests_atm_intel 131 failed in run_test
132 hafs_global_multiple_4nests_atm_qr_intel failed in check_result
hafs_global_multiple_4nests_atm_qr_intel 132 failed in run_test
133 hafs_regional_specified_moving_1nest_atm_intel failed in check_result
hafs_regional_specified_moving_1nest_atm_intel 133 failed in run_test
141 atmaero_control_p8_intel failed in check_result
atmaero_control_p8_intel 141 failed in run_test
142 atmaero_control_p8_rad_intel failed in check_result
atmaero_control_p8_rad_intel 142 failed in run_test
143 atmaero_control_p8_rad_micro_intel failed in check_result
atmaero_control_p8_rad_micro_intel 143 failed in run_test
```
I only ran new baselines for the failures in the hera log, since there were only a handful of them. So I assume there were more failures than initially shown. This is why we need a full Hera RT suite compared to current baselines.

I will need time to create all baselines on both WCOSS2 and Acorn.

**Comment by uturuncoglu** [comment]
@BrianCurtis-NOAA JFYI, I saw this issue before when I change the ESMF version (from 8.3.0b09 to some thing 8.5.0 beta version). At this point, I am working on land component and need to use ESMF 8.5.0 beta version for some feature and had similar issue when I run the RTs. The sfc files were fine but i was getting same error from pressure files. I am not sure maybe there is some code in the inline post that makes 3d interpolation etc. and causes the issue. I am not sure it is related with the ESMF or not since I have no idea which ESMF version is used in here but ESMF 8.5 could lead to some answer changes (it will be releases in a couple of weeks) and there are some fixed in the interpolation side.

**Comment by zach1221** [comment]
Hi, @WenMeng-NOAA . Hera, is mostly finished. The baselines are created, but I'm hung up on the comparing step of RT cases hrrr_control, hrrr_control_qr, hrrr_control_decomp, and hrrr_control_2threads with intel. The RESTART 20210322.120000.fv_tracer.res.tile#.nc tiles continue to error in the matching.

image

**Comment by WenMeng-NOAA** [comment]
> Hi, @WenMeng-NOAA . Hera, is mostly finished. The baselines are created, but I'm hung up on the comparing step of RT cases hrrr_control, hrrr_control_qr, hrrr_control_decomp, and hrrr_control_2threads with intel. The RESTART 20210322.120000.fv_tracer.res.tile#.nc tiles continue to error in the matching.
> 
> image

My PR should have impact on inline post output files in grib2 only, such as data sets GFSPRS, GFSFLX, NATLEV, PRSLEV.

**Comment by jkbk2004** [comment]
@WenMeng-NOAA quick nc comparison shows
nccmp -mf -x recdata,rec /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20230711/hrrr_control_intel/RESTART/20210322.120000.fv_core.res.tile3.nc /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_99171/hrrr_control_intel/RESTART/20210322.120000.fv_core.res.tile3.nc
DIFFER : FILE FORMATS : NC_FORMAT_NETCDF4 <> NC_FORMAT_64BIT

**Comment by zach1221** [comment]
Let me double check as well by running these cases against develop.

**Comment by zach1221** [comment]
@jkbk2004 hrrr_control intel matches when ran with the ufs-wm develop branch, fyi.

**Comment by DusanJovic-NOAA** [comment]
See #1777 and #1832

**Comment by zach1221** [comment]
Hi, @WenMeng-NOAA  . Wanted to make you aware that once #1815 is synced and conflicts resolved, we're planning to add your code changes in this PR to that one. We'll ensure you're credited as well. Please let me know if you have any questions regarding this.

Edit: to clarify, the changes to detect_machine.sh only.

**Comment by WenMeng-NOAA** [comment]
> Hi, @WenMeng-NOAA . Wanted to make you aware that once #1815 is synced and conflicts resolved, we're planning to add your code changes in this PR to that one. We'll ensure you're credited as well. Please let me know if you have any questions regarding this.
> 
> Edit: to clarify, the changes to detect_machine.sh only.

@zach1221 Combing the changes from my PR in #1815 is working for me. Thanks!

**Comment by zach1221** [comment]
Good morning, @WenMeng-NOAA . I think we're ready to start over with our testing of this PR. Could you please sync up your branch with ufs-community:develop?

**Comment by WenMeng-NOAA** [comment]
> Good morning, @WenMeng-NOAA . I think we're ready to start over with our testing of this PR. Could you please sync up your branch with ufs-community:develop?

@zach1221 Just synced.

**Comment by zach1221** [comment]
Jenkins-ci 1794 log attached. ORTs have passed.
[Jenkins-ci 1794.pdf](https://github.com/ufs-community/ufs-weather-model/files/12175094/Jenkins-ci.1794.pdf)

**Comment by zach1221** [comment]
Ok, testing is complete. I'll follow up on the fv3atm sub-pr so we can begin the merging process.

**Comment by zach1221** [comment]
@WenMeng-NOAA the fv3atm sub-pr has been merged. Please update the submodule pointer and revert the change in gitmodules.
fv3atm hash: 6d17939836dd5665854a88931552f17e56c1c377

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA the fv3atm sub-pr has been merged. Please update the submodule pointer and revert the change in gitmodules. fv3atm hash: 6d17939836dd5665854a88931552f17e56c1c377

@zach1221 Done.

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
