### PR TITLE
Update CMEPS; add ATM ORT test (was #1747); update Gaea stack location (was #1758)

### LINKED ISSUE #87: update to latest escomp/main
PRs merged at ESCOMP are needed to update NOAA-EMC

* updates multiple cime and cesm related files
* adds optional check for NaN in export FBs. This requires additional share modules, which are available in the CDEPS repo. Changes are made in the CMakeList.txt in the CMEPS-interface to access these modules. The check for NaNs in off by default. It can be enabled by adding a configuration variable in the MED attributes `` check_for_nans = true``

### LINKED ISSUE #1706: support ORT for ATMW application
## Description
Currently the ORT system supports global/regional atmosphere standalone and coupled S2S applications. In this issue, the ORT will support ATMW application by running ORT tests (threads, decomposition, MPI tasks, restart and debug tests) with atmwav_control_noaero_p8

## Solution
Update ORT scripts to support ATMW application.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

- Updates CMEPS to the latest ESCOMP/main. 
- Adds a new configuration variable to mediator attributes ``pio_rearranger=box``. This is required because the default rearranger for CMEPS was switched to ``subset``. Information from J.Edwards is that _The subset rearranger scales better but is slower at small task counts._ 

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11599445/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11599446/RegressionTests_hera.intel.log)

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):
- https://github.com/ufs-community/ufs-weather-model/pull/1747
- https://github.com/ufs-community/ufs-weather-model/pull/1758
## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- https://github.com/NOAA-EMC/CMEPS/pull/88
- closes https://github.com/NOAA-EMC/CMEPS/issues/87
- closes #1706 

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@SadeghTabas-NOAA @natalie-perlin Please update your PR #1758 and PR #1747 and I will combine w/ this PR. Thanks.

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen The log files are downloading as blank files. Could you please reattach your Hera log files?

**Comment by BrianCurtis-NOAA** [comment]
Why are we running tests when we haven't even met the commit queue standards? This is not yet even ready for the commit queue.

**Comment by zach1221** [comment]
I can generate the hera logs and attach as soon as possible. No problem.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I don't know why the logs I posted are empty and they are no longer available. 

And yes, I also wondered when I saw the jet log pop up. Why are we running tests when we haven't gotten logs from @SadeghTabas-NOAA and my logs turn out to be empty ?

**Comment by DeniseWorthen** [comment]
@zach1221 The logs are a pre-commit step. It turned out mine were blank for some reason, and Sadegh hadn't posted either his full RT logs or his ORT logs.

This PR should never have been scheduled w/o verifying it was ready.

**Comment by zach1221** [comment]
We'll hold off on running any tests until the pre-commit hera logs and @SadeghTabas-NOAA's ORT  logs are made available. I can re-run Jet as well.

**Comment by DeniseWorthen** [comment]
@zach1221 The issue is that now my PR already contains the changes from the other two PRs. Are you suggesting I go back to my commit [af1b223](https://github.com/ufs-community/ufs-weather-model/pull/1752/commits/af1b2239ae77e8d696d913de3de7c943a21ec791) and run the hera tests?

**Comment by zach1221** [comment]
My understanding is that we'd need hera test logs from this combined PR.

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen can you bring in Sadegh's PR again to gain that opnReqTest log? Otherwise I'm OK with this PR moving forward. Can you run the Hera RT manually. If no RT's change it will also be the log pushed to the repo.

**Comment by DeniseWorthen** [comment]
@zach1221 What is the issue with Cheyenne?

**Comment by zach1221** [comment]
@DeniseWorthen Jenkins failed to contact Cheyenne due to an issue with one of the wrapper scripts. I've contacted our Platform team, and have the tests running manually.

**Comment by zach1221** [comment]
Looks like jenkins-ci had similar issue and failed. I'll look into that as well

**Comment by zach1221** [comment]
While we continue to look into the jenkins-ci pipeline. I'm just running those same ORTs manually on Hera, to check for issues.

**Comment by zach1221** [comment]
My manual test runs of ORT with cases control_p8, regional_control and cpld_control_nowave_noaero_p8 passed on Hera. The jenkins-ci sandbox was also successful, logs below. Testing is now complete, so we can begin the merging process for the sub-component PRs.

[sandbox » ufs-wm-ci-debug #195 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11749734/sandbox.ufs-wm-ci-debug.195.Console.Jenkins.pdf)

**Review by sadeghitabas — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
