### PR TITLE
Add 2d domain decomposition to the inline post

### PR DESCRIPTION
**Pull request by JesseMeng-NOAA**
https://github.com/ufs-community/ufs-weather-model/commit/f09e45bfd8420c8456f67db6ccb54b30b246b852
plus UPP post_2d_decomp

Resubmit an update from previous PR, after many updates in upp and other fv3atm submodules.

The community upp is currently decomposed on latitudes (y-direction) only. As the ufs-weather-model is making 2D decomposition in both latitudes and longitudes (Y and X), one of the upp refactoring tasks is to support ufs-weather-model inline post 2D decomposition functionality.

A fv3atm PR was submitted with modified io/ drivers to call upp/post_2d_decomp,
https://github.com/NOAA-EMC/fv3atm/pull/533

The upp/post_2d_decomp branch can be found at
https://github.com/WenMeng-NOAA/UPP/tree/post_2d_decomp

# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- https://github.com/ufs-community/ufs-weather-model/issues/1078

## Testing

To test this PR,

1. Build the BASE with ufs-weather-model/develop
run control fv3 and regional_control fv3

2. Checkout the branch for this PR
https://github.com/JesseMeng-NOAA/ufs-weather-model/tree/upp_unify_inline_2d
run control_2dwrtdecomp and regional_control_2dwrtdecomp

3. Compare the results to confirm identical outputs are reproduced.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

https://github.com/JesseMeng-NOAA/fv3atm/tree/feature/upp_unify_inline_2d
https://github.com/WenMeng-NOAA/UPP/tree/post_2d_decomp

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/fv3atm/pull/533

### CODE REVIEW

**Comment by jkbk2004** [comment]
@JesseMeng-NOAA I tested ok on Cheyenne/intel: control_2dwrtdecomp and regional_control_2dwrtdecomp. Can you sync up the branch to head of develop: 3 commits behind? So that we can run regression tests.

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA I tested ok on Cheyenne/intel: control_2dwrtdecomp and regional_control_2dwrtdecomp. Can you sync up the branch to head of develop: 3 commits behind? So that we can run regression tests.

Updated

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa The UPP repository develop branch is not officially committed the changes for UPP 2D decomposition yet.  The UPP submodule in this PR still points to the branch under my UPP fork.  So this PR is not ready for merging,

**Comment by jkbk2004** [comment]
> @junwang-noaa The UPP repository develop branch is not officially committed the changes for UPP 2D decomposition yet. The UPP submodule in this PR still points to the branch under my UPP fork. So this PR is not ready for merging,

@WenMeng-NOAA what is timeline for the update of UPP develop branch?

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 I would expect the end of this week. We have a minor update for the UPP 2D decomposition.

**Comment by jkbk2004** [comment]
> @jkbk2004 I would expect the end of this week. We have a minor update for the UPP 2D decomposition.

@WenMeng-NOAA @JesseMeng-NOAA Thanks! Keep me posted.

**Comment by jkbk2004** [comment]
@JesseMeng-NOAA If the PR is ready, we can start working on the PR to re-run RTs. We merged in #1157 and fv3atm dependency. Can you sync up your branches to the head of develop: ufs-wm and fv3atm?

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA If the PR is ready, we can start working on the PR to re-run RTs. We merged in #1157 and fv3atm dependency. Can you sync up your branches to the head of develop: ufs-wm and fv3atm?

Updated.

**Comment by jkbk2004** [comment]
@JesseMeng-NOAA In your fv3atm branch, ccpp physics and framework hashes are behind. Can you sync up to head of fv3atm develop branch?

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA In your fv3atm branch, ccpp physics and framework hashes are behind. Can you sync up to head of fv3atm develop branch?

Please reconfirm the branch has the correct hashes. Thanks.
https://github.com/JesseMeng-NOAA/ufs-weather-model/tree/upp_unify_inline_2d
https://github.com/JesseMeng-NOAA/fv3atm/tree/feature/upp_unify_inline_2d/ccpp
ccpp-framework 167313e
ccpp-physics 1a9b050

**Comment by jkbk2004** [comment]
> > @JesseMeng-NOAA In your fv3atm branch, ccpp physics and framework hashes are behind. Can you sync up to head of fv3atm develop branch?
> 
> Please reconfirm the branch has the correct hashes. Thanks. https://github.com/JesseMeng-NOAA/ufs-weather-model/tree/upp_unify_inline_2d https://github.com/JesseMeng-NOAA/fv3atm/tree/feature/upp_unify_inline_2d/ccpp ccpp-framework 167313e ccpp-physics 1a9b050

@JesseMeng-NOAA Looks good. I will go ahead to test again.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @MinsukJi-NOAA If possible, go ahead to run RTs on wcoss/wcoss2.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @WenMeng-NOAA RTs all pass. I think the PR is ready to merge. Can you leave review comments?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@JesseMeng-NOAA can you update fv3atm hash and revert fv3atm pointer at gitmodules? so that we can merge in.

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA can you update fv3atm hash and revert fv3atm pointer at gitmodules? so that we can merge in.

Updated.

**Pull request merged**
