### PR TITLE
GPU-enabled version of Grell-Freitas convection in ccpp-physics

### PR DESCRIPTION
**Pull request by DomHeinzeller**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR only updates the submopdule pointers for ccpp-physics and fv3atm for the changes described in https://github.com/NCAR/ccpp-physics/pull/859.

### Issue(s) addressed

Fixes https://github.com/NCAR/ccpp-physics/issues/860

## Testing

Regression tests were run on Hera with Intel and GNU. For GNU, all results were b4b identical. For Intel, results were identical in DEBUG mode. The PROD results for physics suites using Grell-Freitas were different with Intel, but all tests ran to completion and run-to-run/restart reproducibility was tested as well. This is expected because of some of the optimizations that were made to the actual code to run efficiently on GPUs (for example, replace string switches with integer switches).

Full regression tests will be run on all tier-1 platforms at the time of commit.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [n/a] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/859
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/479

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
@junwang-noaa @DusanJovic-NOAA @MinsukJi-NOAA Do you see why the CI tests are not running? I added the run-ci label twice and it got removed by the bot, but nothing happened. I didn't get any error message either.

All tier-1 tests except wcoss are completed, I just started baseline creation on both wcoss systems.

**Comment by junwang-noaa** [comment]
I am seeing it running. Now it finished all the build jobs.

**Comment by climbfuji** [comment]
> I am seeing it running. Now it finished all the build jobs.

Thanks for that! Not sure why it didn't do it for me (@climbfuji), tried twice today.

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Hash for fv3atm is correct (https://github.com/NOAA-EMC/fv3atm/commit/277517d148b4d473fabe3f6d64ffabe46ab73824), ready to merge.

**Pull request merged**
