### PR TITLE
Update inline post for multiple domains

### LINKED ISSUE #1306: Enable inline post on multiple atm output grids in HAFS application
## Description
Code changes are required to enable the inline post on the multiple atm output grids in HAFS' nesting runs.

## Solution
Update the inline post code on the write grid component, changes may be required on UPP code too.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- PR will be made to fv3atm, upp and ufs-weather-model when the code changes are ready.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR updates FV3 inline post to support multiple domains (nests).

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1306

## Testing

How were these changes tested? Regression test on Hera
What compilers / HPCs was it tested with? Hera/Intel
Are the changes covered by regression tests? 
Yes. two HAFS tests will run inline post (`hafs_regional_specified_moving_1nest_atm` and `hafs_global_multiple_4nests_atm`). Also, grib outputs in current `control_latlon` tests are incorrect, dlat, dlon are zero (fixed in this PR):
```
$ wgrib2 -grid /work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220729/INTEL/control_latlon/GFSFLX.GrbF00
1:0:grid_template=0:winds(N/S):
        lat-lon grid:(360 x 181) units 1e-06 input WE:SN output WE:SN res 48
        lat -90.000000 to 90.000000 by 0.000000
        lon 0.000000 to 359.000000 by 0.000000 #points=65160
```

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? Yes.
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/fv3atm/pull/570

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA We rescheduled to work on this PR tomorrow. Actually, we like to combine this PR with Brian's lua PR #1376 if possible.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we can start working on this pr but @BrianCurtis-NOAA can we check if we can combine in #1376 ?

**Comment by BrianCurtis-NOAA** [comment]
There are more changes needed for changing to .lua in the testing scripts. I'm finding out the bugs still. We can do #1376 later.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1015029726/20220830204517/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1015029726/20220830203014/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1015029726/20220830213016/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by jkbk2004** [comment]
disk space issue on hera/stmp. Still quite some space available on nems. I will manually run the tests there.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @DusanJovic-NOAA All tests are done. I added reviewers.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I can only review based on passing the RTs or not. I would like to make sure that @BinLiu-NOAA will review.

**Comment by BrianCurtis-NOAA** [comment]
Acorn typically should be done, considering it ran OK last PR. It seems the machine has a mind of its own and a lot of baseline creation jobs failed today. I am assuming that running on Acorn being that it's a test machine and a small one, that we won't necessarily get what we want out of it all the time. For this reason, I still want to make sure that in the process of the PR, you at least check with whomever is running on Acorn to verify if it can be skipped and don't assume it will be.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA, Sure! We can take time for review from @BinLiu-NOAA.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we can merge in this pr after submodule pointer update and reverting changes in gitmodules.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
