### PR TITLE
(1) update MOM6 to its main branch 20220629 updating (NCAR 20220603 candidate) (2) add temperature limiter in SPPT

### LINKED ISSUE #1301: update MOM6 to its main branch 20220629 commit
MOM6 main branch is updated on 20220629 (NCAR 20220603 candidate), need to make corresponding updating in UFS. Note a new BL is needed for this updating as a wave related bug is fixed (see detail at https://github.com/mom-ocean/MOM6/pull/1571)

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.
A wave related bug is detected and fixed in this updating which change answers for coupled jobs
- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

MOM6 main branch is updated on 20220629, need to make corresponding updating in UFS
### Issue(s) addressed
#1301 and MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/94

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1301 and https://github.com/ufs-community/ufs-weather-model/pull/1333
- fixes MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/94 and https://github.com/NOAA-EMC/MOM6/issues/96

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [ ] wcoss2.intel Not available
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/94 and PR https://github.com/NOAA-EMC/MOM6/pull/95
If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/MOM6/pull/95

### CODE REVIEW

**Comment by jiandewang** [comment]
@jkbk2004 I just updated my UFS branch, you can start when you have time (I know you are in the meeting now)

**Comment by jkbk2004** [comment]
@jiandewang cice6 c-grid pr was just merged. We can start working on this PR. Jet is still down. So we can pla to continue test until tomorrow.

**Comment by jiandewang** [comment]
@jkbk2004 sounds good

**Comment by BrianCurtis-NOAA** [comment]
Cactus is down today until about 4pm. Can skip.

**Comment by jiandewang** [comment]
@jkbk2004 Let me know when it's the time to change BL date and merging MOM6

**Comment by DeniseWorthen** [comment]
@jiandewang BL_date was changed already (62a9d9d). We'll merge this afternoon to make time for UIFCW activities.

**Comment by jiandewang** [comment]
@DeniseWorthen OK I am going to merge MOM6 and change submodule in UFS

**Comment by jiandewang** [comment]
MOM6 submodule is pointing to dev/emc now

**Comment by DeniseWorthen** [comment]
@jiandewang please check again for the MOM6 hash. emc/develop is at ec1d17e

**Comment by jiandewang** [comment]
> @jiandewang please check again for the MOM6 hash. emc/develop is at ec1d17e

I forgot to do submodule sync

**Comment by jiandewang** [comment]
@DeniseWorthen can you check again ?

**Comment by DeniseWorthen** [comment]
I still see your ufs-weather-model branch using MOM6 hash  a249742. 

I think we need to be sure we ran the BL with the correct MOM6 hash. Did you add Phil's change to what you had for the MOM6 update?

**Comment by jiandewang** [comment]
> I still see your ufs-weather-model branch using MOM6 hash a249742.
> 
> I think we need to be sure we ran the BL with the correct MOM6 hash. Did you add Phil's change to what you had for the MOM6 update?

what about now ? yes Phil's change is in it (hash #a24974211)

**Comment by jiandewang** [comment]
@DeniseWorthen can you check MOM6 hash again? I think it is the correct one now.

**Comment by DeniseWorthen** [comment]
@jiandewang The hash is now correct (ec1d17e)

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @DeniseWorthen @binli2337 I am back on line now. Can we go ahead to approve the PR and merge in?

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
