### PR TITLE
NSSL MP update: documentation update and parameter name change

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## Description
This PR updates documentation for NSSL MP parameters and changes two parameter name. 

- Initialized from @MicroTed ccpp-physics PR: https://github.com/ufs-community/ccpp-physics/pull/77

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on https://github.com/NOAA-EMC/fv3atm/pull/662

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by grantfirl** [comment]
FYI, the CCPP physics PR that this references was combined with https://github.com/ufs-community/ccpp-physics/pull/76 to try to save code management work, but I'm not 100% sure that the combined PR (https://github.com/ufs-community/ccpp-physics/pull/76) should go in. We either need to resolve the conversation there about its status or ask the author of https://github.com/ufs-community/ccpp-physics/pull/77 to de-combine the PRs if the conversation is not resolved soon.

**Comment by jkbk2004** [comment]
@JiliDong-NOAA Is regression test log available?

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA Is regression test log available?

@jkbk2004 I haven't done any regression test so far. Will start on Hera today.

**Comment by jkbk2004** [comment]
> > @JiliDong-NOAA Is regression test log available?
> 
> @jkbk2004 I haven't done any regression test so far. Will start on Hera today.

@JiliDong-NOAA sure! go ahead to attach the log to the pr description once the test is done.

**Comment by JiliDong-NOAA** [comment]
> > > @JiliDong-NOAA Is regression test log available?
> > 
> > 
> > @jkbk2004 I haven't done any regression test so far. Will start on Hera today.
> 
> @JiliDong-NOAA sure! go ahead to attach the log to the pr description once the test is done.

It looks like ccpp-physics in this PR is not synced with the latest commit. Should I wait for it to get synced before trying RT? @jkbk2004 @MicroTed

**Comment by grantfirl** [comment]
@JiliDong-NOAA Yes, I think that https://github.com/ufs-community/ccpp-physics/pull/77 needs to be updated to ufs/dev before you test. If @MicroTed is unavailable to do this, you can always manually merge in ufs/dev on the machine you're using before running rt.sh.

**Comment by JiliDong-NOAA** [comment]
thanks @MicroTed @grantfirl . FV3 and ufs-weather-model have been synced as well. Regression tests are being running on Hera and WCOSS2. Orion is down today and I will try once it is back.

**Comment by jkbk2004** [comment]
@JiliDong-NOAA Can you attach hera test log? so we can move this pr forward.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA Can you attach hera test log? so we can move this pr forward.

it is still running. I am not sure if I use the right command: "rt.sh -l rt.conf"

**Comment by JiliDong-NOAA** [comment]
got an error in RT hafs_regional_1nest_atm_qr_intel 

`Comparing RESTART/20200825.180000.sfc_data.nc ............ALT CHECK......ERROR`

this is strange as this PR shouldn't change any forecast, particularly when NSSL MP is not used. Could this be a system issue? I will run an individual RT for hafs_regional_1nest_atm_qr_intel.

**Comment by JiliDong-NOAA** [comment]
> got an error in RT hafs_regional_1nest_atm_qr_intel
> 
> `Comparing RESTART/20200825.180000.sfc_data.nc ............ALT CHECK......ERROR`
> 
> this is strange as this PR shouldn't change any forecast, particularly when NSSL MP is not used. Could this be a system issue? I will run an individual RT for hafs_regional_1nest_atm_qr_intel.

The individual RT of hafs_regional_1nest_atm_qr passed OK. @jkbk2004 Is there any way to pick up from this failed RT test and resume? Restarting the whole suite of RTs will take another 20 hours to finish the first 138 RTs.

**Comment by DeniseWorthen** [comment]
> > @JiliDong-NOAA Can you attach hera test log? so we can move this pr forward.
> 
> it is still running. I am not sure if I use the right command: "rt.sh -l rt.conf"

@JiliDong-NOAA You did not use ecflow, which is why the test took so long. It ran each test sequentially. To run using ecflow, you need to log into the ecflow node (ssh hecflow01) and then use ``./rt.sh  -e -a ACCT >output 2>&1 &``. 

I use nems for ACCT. Yours may be different.

**Comment by JiliDong-NOAA** [comment]
> > > @JiliDong-NOAA Can you attach hera test log? so we can move this pr forward.
> > 
> > 
> > it is still running. I am not sure if I use the right command: "rt.sh -l rt.conf"
> 
> @JiliDong-NOAA You did not use ecflow, which is why the test took so long. It ran each test sequentially. To run using ecflow, you need to log into the ecflow node (ssh hecflow01) and then use `./rt.sh -e -a ACCT >output 2>&1 &`.
> 
> I use nems for ACCT. Yours may be different.

Ah I see. thanks @DeniseWorthen ! I will do as you suggested.

**Comment by JiliDong-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/11909823/RegressionTests_hera.log)
[RegressionTests_wcoss2.log](https://github.com/ufs-community/ufs-weather-model/files/11909993/RegressionTests_wcoss2.log)
@jkbk2004 hera and wcoss2 rt logs uploaded.

**Comment by DeniseWorthen** [comment]
@JiliDong-NOAA Great. Brian tells me it is no longer required to log into an ecflow node, so you should be able to just skip that step.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA Great. Brian tells me it is no longer required to log into an ecflow node, so you should be able to just skip that step.

Thanks again @DeniseWorthen

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I'm adding this PR to the commit queue, and beginning testing.

**Comment by zach1221** [comment]
Jenkins-ci attached. ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1775 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11920077/ufs-weather-model.ort-docker-pipeline.PR-1775.1.Console.Jenkins.pdf)

**Comment by zach1221** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1374260656/20230630140303/ufs-weather-model
Please make changes and add the following label back: cheyenne-RT

**Comment by zach1221** [comment]
Testing is complete, we can begin the merging process. I'll follow up on the ccpp-physics sub-pr #77.

**Comment by jkbk2004** [comment]
@JiliDong-NOAA fv3 pr was merged. can you update submodule pointer and revert change in gitmodiles? New fv3 hash is https://github.com/NOAA-EMC/fv3atm/commit/e1de62f23cb66424f39e32a827c16c973a7103a2

**Review by sadeghitabas — DISMISSED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by JiliDong-NOAA** [comment]
FV3 updated

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
