### PR TITLE
Update CICE6 to allow WW3-CICE6 coupling; add a cdeps test using C-grid for sea ice dynamics (was #1390)

### LINKED ISSUE #52: Add optional Wave-Ice Coupling to NUOPC cap
Implementation of Wave-Ice Coupling between WW3 and CICE6 requires added exchange fields between WW3 and CICE6 in the NUOPC cap. These field exchanges need to be optionally allowed only when WW3-CICE6 coupling is desired.

### LINKED ISSUE #1389: hafs tests incorrectly set coupling fields for waves
## Description
In PR #1305 the ``INPUT_CURFIELD`` and ``INPUT_ICEFLD`` used for ``ww3_shel.inp`` were set incorrectly for the HAFS tests which use waves. The values were set in ``default_vars`` as

```
export INPUT_CURFLD='C F     Currents'
export INPUT_ICEFLD='C F     Ice concentrations'
```

The value for the hafs-atm-wav test should be ``F F`` for both variables; for the hafs-atm-wav-ocn tests, the value for the Ice should be ``F F``.

### To Reproduce:

Run the ``hafs_regional_atm_wav``, ``hafs_regional_atm_ocn_wav`` and ``hafs_regional_storm_following_1nest_atm_ocn_wav`` tests and examine the ww3_shel.inp in each run directory.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below. 

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Adds the required field exchanges within the NUOPC cap to couple WW3 and CICE6. This allows eventual implementation of  wave-ice coupling developed by CESM in UWM. 

To test w/in UWM, additional changes are required:

- the meshcap needs an update (https://github.com/NOAA-EMC/WW3/pull/757)
- a new mesh cap switch file with ``IC4`` needs to be added. Either the nml or inp file needs to specify ice parameters 1,5 as "C" and EF needs to be an output variable ``&OUTS E3D = 1, USSP = 1, IUSSP = 3, STK_WN = 0.04, 0.110, 0.3305 /``

- a new ``mod_def`` file with ``&SIC4 IC4METHOD = 8 `` needs to be created and added to the input directory
- the following variables need to be added to ``ice_in``
```
nfsd         = 12 (in grid_nml)
tr_fsd       = .true. (in tracer_nml)
wave_spec_type  = 'constant' (in forcing_nml)
```
- the attribute ``wav_coupling_to_cice = true`` needs to be added to nems.configure (in ALLCOMP_attributes)

### Issue(s) addressed

- fixes https://github.com/NOAA-EMC/CICE/issues/52
- allows implementation of required feature within CESM to enable future merging of WW3 meshcap into develop
- fixes #1389 

## Testing

The additional files and settings described above were added to a sandbox on Cheyenne. The ``cpld_debug_noaero_p8`` test was run for both Intel and GNU with mediator history files for ICE and WAV enabled. Both jobs ran to completion and the exchanged fields (``Si_thick``, ``Si_floediam``, ``Sw_elevation_spectrum``) appeared reasonable. 

A 10d simulation using the ``cpld_control_noaero_p8`` RT was also run, comparing the wave-ice solution against develop. The ice concentration and thickness changes are in-line w/ intuition that wave-ice interactions will impact marginal ice-zone thermodynamics, with enhanced breakup leading to increased lateral melt. Shown are ice concentration and thickness differences which arise from including wave-ice coupling.

waveiceNH

waveiceSH

Both Hera.Intel and Hera.GNU were run at 17f16051 and all tests except for ``cpld_control_ciceC_p8`` reproduced. The change in the ciceC test is due to a change in the ``visc_method`` default to ``avg_zeta`` brought in with the update to Consortium/main. A test was run for this test retaining the ``visc_method`` as ``avg_strength`` and the develop-20220805 baseline for this test reproduced.

After adding the fix for the HAFS wav configurations 83edc463, the ``hafs_regional_atm_ocn_wav`` and ``hafs_regional_atm_wav`` tests will also change baseliens.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/CICE/pull/51

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DeniseWorthen @BrianCurtis-NOAA I will start creating new BL from hera.

**Comment by DeniseWorthen** [comment]
@jkbk2004 The BL date has not been updated.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I don't think the jobs on hera had picked up yet before I removed the labels.

**Comment by jkbk2004** [comment]
@DeniseWorthen Thanks for catching it!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1034797158/20220829214507/ufs-weather-model
[BL] Error: Test cpld_control_noaero_p8_agrid 007 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by jkbk2004** [comment]
@DeniseWorthen all tests are done ok. We can move on to merge.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
Ready for approvals and merge.

**Review by BrianCurtis-NOAA — APPROVED** [review]
Hash is good.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
