### PR TITLE
Update CDEPS component in the ufs-weather-model

### LINKED ISSUE #48: Update CDEPS to include the recent changes from ESCOMP/CDEPS
The CDEPS will be updated to include changes from 20220811 (# a42fb93)

Updates from ESCOMP/CDEPS include the following features:

- Add a fillvalue attribute for pio subroutines.
- Add fixes to put in coszen interpolation for CIAF and GIAF compsets.
- Add nitrogen deposition to datm streams for CLMNDEP, JRA and CORE.
- Move pio initialization from advertise to realization phase.

### LINKED ISSUE #1371: Update CDEPS component in the ufs-weather-model
## Description
The NOAA-EMC/CDEPS will be updated to include a few recent changes from ESCOMP/CDEPS. The CDEPS component in the ufs-weather-model will be updated at the same time.

## Solution
Update CDEPS component.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
-  needed by https://github.com/NOAA-EMC/CDEPS/pull/49

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description
The NOAA-EMC/CDEPS will be updated to include recent changes from ESCOMP/CDEPS. The CDEPS component in the ufs-weather-model will be updated at the same time.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1371 
- fixes https://github.com/NOAA-EMC/CDEPS/issues/48

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting: https://github.com/NOAA-EMC/CDEPS/pull/49

### CODE REVIEW

**Comment by jkbk2004** [comment]
@binli2337  we can start testing the pr. can you sync up one more time?

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1028698447/20220819150015/ufs-weather-model
[RT] Error: Test hafs_global_multiple_4nests_atm 125 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1028698447/20220820020015/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
@binli2337 all tests are done ok. let's go ahead to merge in [cdeps pr#49](https://github.com/NOAA-EMC/CDEPS/pull/49)

**Comment by binli2337** [comment]
@junwang-noaa Can you merge the CDEPS pr? Thanks.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DeniseWorthen pr is ready to merge. can we have final approval?

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
