### PR TITLE
use ungridded dimensions for stokes drift exchange

### LINKED ISSUE #1526: Use ungridded dimensions for partitioned stokes drift exchange between wav<->ocn
## Description

The WW3 mesh cap has the capability to use ungridded dimensions to transfer fields. This allows the 6 fields (3 each for x,y) used to exchange the partitioned stokes drift between WW3 and MOM6 to be simplified to only 2 fields. The MOM6 and WW3 caps used in UFS can be simplified as a result. 

## Solution

The ability to import and export the stokes drift using ungridded dimensions is present in both MOM6 and the WW3 mesh cap. The  feature needs to be enabled for UWM. Changes will be required in MOM6, CMEPS and WW3.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Enables the use of ungridded dimensions for the exchange of partitioned stokes drift between MOM6 and WW3.

### Issue(s) addressed

- fixes #1526 

## Testing

All baselines were run on Cheyenne.intel and Cheyenne.gnu. Since this PR changes the field names within the mediator restart files, the restart file was removed from the file comparison list for all wave-enabled tests. All tests were B4B at 9805fea50. New baselines will be required solely because of the field name changes in the mediator restart files.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
 
- https://github.com/NOAA-EMC/WW3/pull/863
- https://github.com/NOAA-EMC/MOM6/pull/108
- https://github.com/NOAA-EMC/CMEPS/pull/80 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DeniseWorthen If not necessary to wait for another wave pr, we can start working on this pr.

**Comment by DeniseWorthen** [comment]
@jkbk2004 There is a comment on [https://github.com/NOAA-EMC/WW3/pull/863](https://github.com/NOAA-EMC/WW3/pull/863) from @MatthewMasarik-NOAA that this PR won't be merged until after Jan 3.

**Comment by jkbk2004** [comment]
Thanks for the note. We will move to #1529.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen I don't plan to merge develop into dev/ufs-weather-model while Jessica is away.  I have tested this PR on my end though running the RT suite, and all runs ran fine, with some failing in run_check, though you've noted a baseline change.  If you're able to proceed with this PR please go ahead.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA The baselines will change only because the name of the fields stored in mediator restart files will change.

But I'm confused by saying "If you're able to proceed with this PR please go ahead." We need need to be able to merge the component level PRs in order to commit to UWM. So we won't be able to work on the UWM PR until we're sure that WW3 will also be able to be merged.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen sure we should probably wait then.

**Comment by jkbk2004** [comment]
@DeniseWorthen can you sync up branch?

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen I took care of the merge. Acorn/Cactus logs updated.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1154306112/20230103150020/ufs-weather-model
[BL] Error: Test compile_001 failed in run_compile failed 
[BL] Error: Test compile_002 failed in run_compile failed 
[BL] Error: Test compile_003 failed in run_compile failed 
[BL] Error: Test compile_004 failed in run_compile failed 
[BL] Error: Test compile_005 failed in run_compile failed 
[BL] Error: Test compile_006 failed in run_compile failed 
[BL] Error: Test compile_007 failed in run_compile failed 
[BL] Error: Test compile_020 failed in run_compile failed 
[BL] Error: Test compile_021 failed in run_compile failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by DeniseWorthen** [comment]
There appears to have been an issue checking out MOM6....it is empty.

**Comment by jkbk2004** [comment]
> There appears to have been an issue checking out MOM6....it is empty.

It could be git/orion issue.  Let me see if it runs on my account.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1154306112/20230103210011/ufs-weather-model
[BL] Error: Test regional_atmaq 115 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by jkbk2004** [comment]
@DeniseWorthen two cases fail on cheyenne.intel: cpld_restart_c192_p8 and hafs_global_multiple_4nests_atm. Path is /glade/scratch/jongkim/rt-1527-intel/jongkim/FV3_RT/rt_43747.

**Comment by jkbk2004** [comment]
develop branch has no problem for those cases. MPT ERROR: process_vm_readv() had error: 3

**Comment by DeniseWorthen** [comment]
The HAFS case does is standalone and this PR has no impact. I ran both intel and gnu for this pr for testing, so either it is a glitch, or something in the meantime has changed.

**Comment by DeniseWorthen** [comment]
I have obtained the same two failures independently. I will need time to debug. The restart c192 case is core-dumping on the FV3/CMEPS PEs. The hafs case for me failed w/ the usual "MPT: shepherd terminated" error.

**Comment by DeniseWorthen** [comment]
The c192 tests do not currently use the same TPN=18 setting that the c96 uses (we don't run the bmark on cheyenne). I can get the c192 test to run w/ TPN=18.

**Comment by jkbk2004** [comment]
> The c192 tests do not currently use the same TPN=18 setting that the c96 uses (we don't run the bmark on cheyenne). I can get the c192 test to run w/ TPN=18.

Yeas, both cpld_restart_c192_p8 and hafs_global_multiple_4nests_atm work on cheyenne now with TPN=18.

**Review by jkbk2004 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Can you please review?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Can you please review?

Yes. One moment.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
