### PR TITLE
update MOM6 to its main repository 20230703 and 20230811 updating

### LINKED ISSUE #1849: update MOM6 to its main repo 20230731 and 20230811 commit
MOM6 main repository was updated on 20230731 (GFDL-candidate-20230703, see detail at https://github.com/mom-ocean/MOM6/pull/1603) and 20230811 (GMAO-gun-bug-fixing, see detail at https://github.com/mom-ocean/MOM6/pull/1605). Need to make corresponding updating in UWM. A new BL is needed as several variables were removed from restart files although there is no real answer change in this updating.

### PR DESCRIPTION
**Pull request by jiandewang**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

MOM6 main repository was updated on 20230731 which is the original GFDL-candidate-20230703 (see detail at https://github.com/mom-ocean/MOM6/pull/1603). Before this commit is merged to dev/emc, a gnu realted bug (see detail at https://github.com/mom-ocean/MOM6/pull/1605) was reported by GMAO and a new commit was made to MOM6 main repository on 20230811. Need to update dev/emc MOM6 correspondingly for both two updating.

### Associated UFSWM Issue to close

Close #1849 

### Subcomponent Pull Requests

MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/115,  https://github.com/NOAA-EMC/MOM6/issues/118 and MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/119

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [x] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR: all coupled tests include DATM</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by jiandewang** [comment]
[RegressionTests_hera.log.pdf](https://github.com/ufs-community/ufs-weather-model/files/12328736/RegressionTests_hera.log.pdf)
upload HERA rt.sh run log, note all the failure (NOT OK) are with MOM6 restart files

**Comment by FernandoAndrade-NOAA** [comment]
Hi @jiandewang, #1807 was merged in. Please go ahead and sync up your branches with the latest develop and we'll get started with testing, thank you.

**Comment by jiandewang** [comment]
> Hi @jiandewang, #1807 was merged in. Please go ahead and sync up your branches with the latest develop and we'll get started with testing, thank you.

just sync-ed my branch

**Comment by FernandoAndrade-NOAA** [comment]
All but one of the Jenkins ORTs passed. @zach1221 FYI, looks like a test failed during the stage data step, rst case for cpld_control_nowave_noaero_p8

**Comment by zach1221** [comment]
@FernandoAndrade-NOAA I see. I think it's an issue with the new container. I'll verify ORT manually on Hera for now, so we can move forward with testing.
[Uploading Jenkins-ci 1864 ORTs.pdf…]()

Here's the logs. Everything passed except for Regional_control dcp & thr. I'll run those on Hera.
Edit: adding Regional_control logs for thr and dcp. These ORTs passed.
[OpnReqTests_regional_control_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/12344655/OpnReqTests_regional_control_hera.log.txt)

**Comment by FernandoAndrade-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: jet Job: BL Repo location: /lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1473195741/20230815162218/ufs-weather-model Please make changes and add the following label back: jet-BL

Rerunning manually. Please ignore this failure notice. It's likely a disk space quota that was reached today and is being cleared out. It could also likely be the compile_swswa_faster_intel timing out, it has regularly needed a higher build time limit.

**Comment by junwang-noaa** [comment]
@zach1221 The wcoss2 log file is at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_wcoss2.log.

**Comment by zach1221** [comment]
Thanks, @junwang-noaa ! I'll get it.

**Comment by zach1221** [comment]
Good morning,  @junwang-noaa . Are we skipping Acorn for this PR?

**Comment by junwang-noaa** [comment]
@zach1221 Some tests hang on acorn when creating baseline last night, I reran them, now the baseline was generated. Now I am running full RT.

**Comment by junwang-noaa** [comment]
@zach1221 acorn RT log file is now on hera at: 
/scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_acorn.log

**Comment by zach1221** [comment]
@jiandewang testing is complete on this PR, so we can begin with the merging process of the sub-component PR.

**Comment by jiandewang** [comment]
@DeniseWorthen can you review MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/119 and let me know when it's time for me to do the submodule revert ?

**Comment by jiandewang** [comment]
just merged MOM6 PR, going to do submodule revert

**Comment by zach1221** [comment]
Thanks, @jiandewang . You may now update the submodule pointer and revert the .gitmodule change, following the merge of the MOM6 sub-component PR #119
MOM6 hash: 06acdc8e15ea9acf499b26f7f40c9852249c0690

**Comment by jiandewang** [comment]
MOM6 submodule reverted

**Review by DeniseWorthen — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
