### PR TITLE
Improve radiative fluxes and cloud cover in FV3 for HR1

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
This PR is associated with ccpp-physics PR#19 to improve radiative fluxes and cloud cover calculation in GFSv17 by modifying the Thompson microphysics scheme and its connection to the radiation scheme. This implementation is for HR1.

### Issue(s) addressed
- fixes  ufs-community/ccpp-physics issue#<[21](https://github.com/ufs-community/ccpp-physics/issues/21)>

## Testing
The regression tests are conducted on hera.intel and all the tests used the Thompson microphysics scheme failed due to baseline changes. The control_p8, which uses the Thompson scheme, was selected for the ORT test, and the ORT test was successful.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies
- waiting on ufs-community/ccpp-physics/pull/<[19](https://github.com/ufs-community/ccpp-physics/pull/19)>
- waiting on noaa-emc/fv3atm/pull/<[599](https://github.com/NOAA-EMC/fv3atm/pull/599)>

### CODE REVIEW

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA we can start working on this pr. Can you resolve the conflicts?

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA we can start working on this pr. Can you resolve the conflicts?

I will make the changes and let you know when it is ready.

**Comment by zach1221** [comment]
Jenkins-ci logs attached.
[ufs-weather-model » ort-docker-pipeline » PR-1481 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9956499/ufs-weather-model.ort-docker-pipeline.PR-1481.1.Console.Jenkins.pdf)

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA all test are done. we can start merging process. Can you merge in the ccpp dependency first?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Sure. ccpp-physics PR#19 was merged into ufs/dev. I will update the pointer and hash.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 ccpp-physics pointer was reverted in fv3atm.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA fv3 pr was merged. we can merge in this pr with hash update and reverting gitmodules branch.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Done.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
