### PR TITLE
[production/AQM.v7] AQMv7.1 upgrades

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Code was tested in either a production or development environment as applicable.
---
### Commit Message:

```
* AQM - AQM.v7.1
```

### Priority:

* High: v7.1 for production

### UFSWM:

* None

### Sub component Pull Requests:

* AQM: NOAA-EMC/AQM#99

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- WCOSS2
  - [ ] Dogwood/Cactus

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA has confirmed that this has been tested successfully (since the /tests dir was removed for implementation).

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA gaea is down today but it will be interesting to do some pretest on gaea for regional_atmaq cases.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 this is for production/AQM.v7 so just need a review of the code. Testing has been completed externally by the AQM devs.

**Comment by jkbk2004** [comment]
Looks good: code a lot cleaner! I am going to approve the pr. @BrianCurtis-NOAA let us know if you want us to do tests on any RDHPCS side.

**Review by jkbk2004 — APPROVED** [review]
Looks good: code a lot cleaner!

**Pull request merged**
