### PR TITLE
Add 'valid time' variable using ISO string format

### LINKED ISSUE #1052: Write out valid time as a string in history files
## Description
Currently, UFS write-grid component writes out valid time like so:
```
	double time(time) ;
		time:calendar = "JULIAN" ;
		time:calendar_type = "JULIAN" ;
		time:cartesian_axis = "T" ;
		time:long_name = "time" ;
		time:units = "hours since 2021-03-22 06:00:00" ;
```
This requires routines to compute the valid time using the value of time(t) and the unit string. These are in `w3emc` but is not a trivial thing to do without external libraries.

It would be nice to have something akin to the following added:
```
	char valid_time(time, nchars) ;
		valid_time:calendar = "JULIAN" ;
		valid_time:calendar_type = "JULIAN" ;
		valid_time:cartesian_axis = "T" ;
		valid_time:long_name = "valid time" ;
		valid_time:units = "ISO 8601 Date String" ;
```
So that one can easily grab: `2022-02-16T17:11:00Z`
This will be useful for a few things, most notably 1) checking in FV3-JEDI that the valid time from a cubed-sphere history file is at the expected time and 2) having an easy variable for plotting model output.

## Solution
Add a string representation of the model valid time to the history files.

## Alternatives
Add an integer representation of the model valid time to the history files.

## Related to
Adding cube-sphere history I/O to FV3-JEDI.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Add 'valid time' variable using ISO string format to netcdf history files.

### Issue(s) addressed

- fixes https://github.com/ufs-community/ufs-weather-model/issues/1052

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/492

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/869689833/20220316143013/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: jet Compiler: intel Job: BL [BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/869689833/20220316143013/ufs-weather-model Please make changes and add the following label back: jet-intel-BL

I'd recommend running jet manually until I can figure out the issues with their ecflow.

**Comment by grantfirl** [comment]
@DusanJovic-NOAA FYI, I'm going to be out of the office from about 12:45 - 3:00 MT. If you'd like to begin the merge process during this time, please notify @climbfuji @mkavulich or @SamuelTrahanNOAA to push the merge button on https://github.com/NCAR/ccpp-physics/pull/870.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA FYI, I'm going to be out of the office from about 12:45 - 3:00 MT. If you'd like to begin the merge process during this time, please notify @climbfuji @mkavulich or @SamuelTrahanNOAA to push the merge button on [NCAR/ccpp-physics#870](https://github.com/NCAR/ccpp-physics/pull/870).

All regression tests passed. [NCAR/ccpp-physics#870](https://github.com/NCAR/ccpp-physics/pull/870) can be merged.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
