### PR TITLE
update MOM6 to its main repo. 20240228 updating

### LINKED ISSUE #2165: update MOM6 to its main repository 20240228 commit
This is a big PR which originally was GFDL 20231113 candidate PR (https://github.com/mom-ocean/MOM6/pull/1616).
The original PR failed to retain UFS BL on wcoss2 but are fine on all other platforms. With Marshall and Bob's further modification, it can retain UFS BL on wcoss2 for 1x1, half and quarter degree settings now. Discussion on the root cause of the original failing of retain BL can be found in the original PR (https://github.com/mom-ocean/MOM6/pull/1616) and the last commit from Marshall in ths PR.
new BL are needed for:

- cpld_control_c48: two new variables are being added in this setting (p_surf_EOS=True), this is why you will see all files are OK in cmp except ocean restart files on all platforms (except wcoss2). For wcoss2 it changed answers.

- hafs_regional_storm_following_1nest_atm_ocn_wav_mom6: a bug fixing is included which changed answer in this PR

note the original DEFAULT_2018_ANSWERS=T has changed to DEFAULT_ANSWER_DATE=20181231 in MOM_input

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

This PR contains many non-Boussinesq related code enhancement, alone with many new features (see detail at https://github.com/mom-ocean/MOM6/pull/1616 and https://github.com/NOAA-EMC/MOM6/pull/127).

### Commit Message:

```

  * MOM6 - 
update MOM6 to its main repo. 20240228 updating (which is the original GFDL 20231113 candidate PR)
```

### Priority:
* High: this is a longlasting PR which finally reached merging staging (after 3.5 months). Need to merge it to dev/emc and start to work on "remove compiling warning" right after this. Due to the complication of this PR, it's better to treat it as an independent PR.

### UFSWM:

close #2165 

### Sub component Pull Requests:

* MOM6: PR https://github.com/NOAA-EMC/MOM6/pull/127

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

(1)  cpld_control_c48: two new variables are being added in this setting (p_surf_EOS=True), this is why you will see all files are OK in cmp except ocean restart files on all platforms (except wcoss2). For wcoss2 answers are being changed.
(2) hafs_regional_storm_following_1nest_atm_ocn_wav_mom6: a bug fixing is included which changed answer in this PR

### Input data Changes:

* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jiandewang** [comment]
- due to the super size and complication, this PR branch has been tested on all platforms (thanks for the help from @DeniseWorthen and @jkbk2004). Regression logs:
- HERA: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_hera.log
- GAEA: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_gaea.log
- WCOSS2: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_wcoss2.log
- ORION: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_orion.log
- HERCULES: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_hercules.log

**Comment by jiandewang** [comment]
just sync-ed to latest UFSWM

**Comment by jiandewang** [comment]
got greenlight from @DeniseWorthen and @JessicaMeixner-NOAA for MOM6 PR

**Comment by jiandewang** [comment]
just added test_changes.list in my branch

**Comment by FernandoAndrade-NOAA** [comment]
@zach1221 @jkbk2004 FYI Gaea has run into errors with the `hafs_regional_storm_following_1nest_atm_ocn_wav_mom6` test during runtime. It seems to be caused by obsolete runtime flags:
`/gpfs/f5/epic/scratch/Fernando.Andrade-maldonado/FV3_RT/rt_73775/hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel/err`
```
360: FATAL from PE     0: MOM_obsolete_params: DEFAULT_2018_ANSWERS is an obsolete run-time flag, and should not be used. Instead use DEFAULT_ANSWER_DATE.
```

**Comment by jiandewang** [comment]
sorry my fault. I modified this in global coupled cases but forgot to modify for HAFS case. I will modify that once I get back home

**Comment by jiandewang** [comment]
just modify MOM_input_hafs, @FernandoAndrade-NOAA can you re-launch the job ?

**Comment by BrianCurtis-NOAA** [comment]
Acorn can be skipped. Still looking into the issues there, but they don't seem to be related to this PR.

**Comment by jiandewang** [comment]
just merged MOM6

**Comment by zach1221** [comment]
> just merged MOM6

Thanks, @jiandewang . Please update hash and revert the .gitmodule url.
https://github.com/NOAA-EMC/MOM6/commit/10521a921d2f442de19a0cda240d912fd918c40c

**Comment by jiandewang** [comment]
in meeting now, will do in 20min

**Comment by jiandewang** [comment]
just did submodule revert

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
