### PR TITLE
Move IO related configuration from fv3_cap to write grid component

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Update fv3_cap's SetServices to use ONLY the semantic labels for each of the phases
Move IO related configuration from fv3_cap to write grid component
Code cleanup.

Is a change of answers expected from this PR? No.
Are any library updates included in this PR (modulefiles etc.)? No.

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [ ] jet.intel - down for maintenance
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on NOAA-EMC/fv3atm/pull/318

### CODE REVIEW

**Review by rsdunlapiv — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/652803767/20210608060010/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_8386
Test cpld_debug 028 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/652803767/20210608120040/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_303256
Test cpld_control 027 failed failed 
Test cpld_control 027 failed in run_test failed 
Test cpld_debug 028 failed failed 
Test cpld_debug 028 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/652803767/20210608063008/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_9082
Test cpld_debug 028 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
cheyenne is a "MISSING file" on all comparisons.

**Comment by DusanJovic-NOAA** [comment]
> Machine: hera
> Compiler: gnu
> Job: RT
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/652803767/20210608120040/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_303256
> Test cpld_control 027 failed failed
> Test cpld_control 027 failed in run_test failed
> Test cpld_debug 028 failed failed
> Test cpld_debug 028 failed in run_test failed
> Please make changes and add the following label back:
> hera-gnu-RT

```
$ tail -n 30 /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_303256/cpld_control/err
150: WARNING from PE     0: Unused line in INPUT/MOM_input : LT_MOD_LAC4 = 0.0
150: 
150: 
150: WARNING from PE     0: Unused line in INPUT/MOM_input : LT_MOD_LAC5 = 0.22
150: 
  0:  in fcst comp init, ntasks=         144
  0:  num_atmos_calls=          96 time_init=        2016          10           3           0           0           0 time_atmos=        2016          10           3           0           0           0 time_end=        2016          10           4           0           0           0 dt_atmos=         900 Run_length=       86400
 54: Fatal error in PMPI_Wait: Message truncated, error stack:
 54: PMPI_Wait(216)....................: MPI_Wait(request=0xe49d4b4, status=0xce53680) failed
 54: MPIR_Wait(112)....................: 
 54: MPIDI_CH3U_Receive_data_found(131): Message from rank 51 and tag 2 truncated; 1560 bytes received but buffer size is 792
102: Fatal error in PMPI_Wait: Message truncated, error stack:
102: PMPI_Wait(216)....................: MPI_Wait(request=0xf204f14, status=0xce53680) failed
102: MPIR_Wait(112)....................: 
102: MPIDI_CH3U_Receive_data_found(131): Message from rank 99 and tag 2 truncated; 1560 bytes received but buffer size is 792
  6: 
  6: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
  6: 
  6: Backtrace for this error:
 29: 
 29: FATAL from PE    29: mpp_sync_self: size_recv does not match of data received
 29: 
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
  0: slurmstepd: error: *** STEP 19570477.0 ON h13c35 CANCELLED AT 2021-06-08T12:28:35 ***
srun: error: h13c40: tasks 154-191: Killed
srun: launch/slurm: _step_signal: Terminating StepId=19570477.0
srun: error: h13c38: tasks 78-115: Killed
srun: error: h13c36: tasks 39-77: Killed
srun: error: h13c35: tasks 0-38: Killed
srun: error: h13c39: tasks 116-153: Killed

```


```
$ tail -n 30 /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_303256/cpld_debug/err
184: PMPI_Bcast(434)...............: 
184: MPIR_Bcast_impl(310)..........: 
184: MPIR_Bcast_intra_auto(189)....: 
184: MPIR_Bcast_intra_smp(105).....: 
184: MPIR_Bcast_impl(310)..........: 
184: MPIR_Bcast_intra_auto(223)....: 
184: MPIR_Bcast_intra_binomial(182): Failure during collective
189: Fatal error in PMPI_Bcast: Unknown error class, error stack:
189: PMPI_Bcast(448)...............: MPI_Bcast(buf=0x7ffef9874058, count=8, MPI_BYTE, root=0, comm=comm=0xc4000008) failed
189: PMPI_Bcast(434)...............: 
189: MPIR_Bcast_impl(310)..........: 
189: MPIR_Bcast_intra_auto(189)....: 
189: MPIR_Bcast_intra_smp(105).....: 
189: MPIR_Bcast_impl(310)..........: 
189: MPIR_Bcast_intra_auto(223)....: 
189: MPIR_Bcast_intra_binomial(182): Failure during collective
  0: slurmstepd: error: *** STEP 19570527.0 ON h13c35 CANCELLED AT 2021-06-08T12:31:29 ***
srun: error: h13c36: tasks 39-49,51-62,64-73,75-77: Exited with exit code 2
srun: launch/slurm: _step_signal: Terminating StepId=19570527.0
srun: error: h13c38: tasks 78-97,99-110,112-115: Exited with exit code 2
srun: error: h13c35: tasks 0-1,3-14,16-25,27-38: Exited with exit code 2
srun: error: h13c35: task 15: Floating point exception (core dumped)
srun: error: h13c38: task 111: Floating point exception (core dumped)
srun: error: h13c36: task 63: Floating point exception (core dumped)
srun: error: h13c39: tasks 116-121,123-143: Exited with exit code 2
srun: error: h13c39: tasks 122,144-153: Killed
srun: error: h15c23: tasks 154-191: Killed
srun: error: h13c38: task 98: Killed
srun: error: h13c35: tasks 2,26: Killed
srun: error: h13c36: tasks 50,74: Killed

```

**Comment by climbfuji** [comment]
The last time I saw this was on Cheyenne for ALL model runs (when the code was ok and I had to patch FMS). If this is only for a few tests on hera, then it looks like a bug in the code (variable kind mismatch?).

**Comment by DeniseWorthen** [comment]
The cpld debug on cheyenne.gnu failed with: 

```
34:At line 1000 of file /glade/scratch/dtcufsrt/autort/tests/auto/pr/652803767/20210608063008/ufs-weather-model/FV3/atmos_cubed_sphere/tools/fv_grid_tools.F90
34:Fortran runtime error: Index '97' of dimension 1 of array 'grid' outside of expected range (30:68)
```

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/652803767/20210608091507/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_50479
Test control_ras 009 failed in run_test failed 
Test control 001 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 013 failed in run_test failed 
Test control_stochy 003 failed in run_test failed 
Test cpld_debug 028 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by DusanJovic-NOAA** [comment]
@rsdunlapiv I had to revert one commit (using semantic labels in fv3_cap) from this PR because cpld tests failed using GNU compilers on Hera and Cheyenne. We need to find out why.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/652803767/20210608113008/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_32527
Test fv3_rrfs_v1alpha_debug 070 failed in run_test failed 
Test control_flake 031 failed in run_test failed 
Test cpld_restart_c384 008 failed in run_test failed 
Test cpld_restart_bmark_v16 010 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/652803767/20210608173013/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_27076
Test control_wrtGauss_netcdf_parallel 021 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by DusanJovic-NOAA** [comment]
> Machine: gaea
> Compiler: intel
> Job: RT
> Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/652803767/20210608173013/ufs-weather-model
> Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_27076
> Test control_wrtGauss_netcdf_parallel 021 failed in run_test failed
> Please make changes and add the following label back:
> gaea-intel-RT

```
$ tail /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_27076/control_wrtGauss_netcdf_parallel/err
 MXFLD is:          999
 size of lvlsxml:       150000
 size of post_avblflds param         104
 in readxml. nfld=         104 nrecout=         113
 post_fname=GFSFLX.GrbF05
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 268826806.0 ON nid01111 CANCELLED AT 2021-06-08T18:01:46 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 268826806 ON nid01111 CANCELLED AT 2021-06-08T18:01:46 DUE TO TIME LIMIT ***
srun: got SIGCONT
srun: forcing job termination
```
All tests except this one finished successfully. Since gaea.intel tests already passed in the previous commit, I'm not going to rerun this again.

**Comment by DusanJovic-NOAA** [comment]
Ready for review/merge.

**Review by climbfuji — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
