### PR TITLE
Bring in changes from production/AQM.v7

### LINKED ISSUE #1585: enable debug mode in regional AQM
## Description
It is required to run AQMv7 in debug mode for operational implementation.

## Solution
Resolve issues in CMAQ.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Description

This PR bring in changes from the production/AQM.v7 branch enabling debug mode to be run in the ATMAQ application.

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [X] Changes are expected to the following tests: 

regional_atmaq, regional_atmaq_debug, regional_atmaq_faster

## Subcomponents involved:
- [X] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Closes #1585
- Depends on NOAA-EMC/AQM/pull/68

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10985625/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10985626/RegressionTests_hera.intel.log)

Only the atmaq tests will need new baselines

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA We don't need to rush for other PRs. Also this PR is ready. We can start working on this PR. Can you put new BL_DATE=20230320 ? Then I will go ahead to copy over baselines on RDHPCs and create new aqm baselines.

**Comment by zach1221** [comment]
Jenkins-ci logs attached. ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1656 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11023686/ufs-weather-model.ort-docker-pipeline.PR-1656.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
Gaea queue wasn't moving yesterday. Gaea system admin is currently working on lustre file system. We will skip Gaea for this pr.

**Comment by BrianCurtis-NOAA** [comment]
> Gaea queue wasn't moving yesterday. Gaea system admin is currently working on lustre file system. We will skip Gaea for this pr.

Want to start merge?

**Comment by jkbk2004** [comment]
Sure! We can start merging process.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Ready for reviews/merge.

**Review by sadeghitabas — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
