### PR TITLE
sync ww3

### PR DESCRIPTION
**Pull request by aliabdolali**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

- w3nco has been merged with w3emc.  w3emc/2.9.2 contains identical code as w3nco with the exception of gblevents.
- The ufs wm will be updated to use w3emc/2.9.2. 
- Sync WW3/dev/ufs-weather-model to the top of WW3/develop
- No changes in the results and no need to recreate new mod_def files.

### Issue(s) addressed
- fixes (https://github.com/ufs-community/ufs-weather-model/issues/1125)

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/WW3/pull/750

### CODE REVIEW

**Comment by jkbk2004** [comment]
@aliabdolali We are working to merge in #1349 (with other two combined PRs): likely to merge in today. Can you check #1328? lib updates: w3emc2.9.2 and pio2.5.3 (on wcoss2). I think those changes can be directly combined into this PR.

**Comment by aliabdolali** [comment]
@jkbk2004 I am not able to connect to WCOSS2, can I check it on Hera?

**Comment by jkbk2004** [comment]
@aliabdolali I was asking Brian to check on wcoss2. Let's take time today to clear issues. No need to rush. If we start testing tomorrow, we can let the machines run on over weekend.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 is prod only right now. I just merged my PR, so I think this one is up @jkbk2004 . @aliabdolali Would I be correct that all tests that use WW3 will change baselines? Is there any new input data?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@aliabdolali There is no .gitmodule change pointing to the your WW3 sync branch. Please update your .gitmodule to show the fork and branch you are using for this PR.

**Comment by DusanJovic-NOAA** [comment]
This PR will not fix #1125. #1328 will fix #1125. Please update the PR description.

**Comment by jkbk2004** [comment]
closing  this pr since merged thru #1328.

**Pull request closed without merging**
