### PR TITLE
Platform-594 AutoRT Jenkins

### PR DESCRIPTION
**Pull request by kbooker79**
## Description

This PR adds the codebase a Jenkins variant of existing crontab initiated AutoRT.  These are the Python and shell script code changes necessary to run AutoRT in the context of the Jenkins CI/CD system on all of the tier-1 platforms.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
#1531 was closed and this pr is just created. There are still separate steps we need to deactivate crontab to start test one machine at a time though. I like to start getting review comments. @BrianCurtis-NOAA I am separately following up  with baseline storage location issues. Jenkins hookup is done by epic role account but our baselines are under emc.nemspara: write permission issue across two role accounts. We can talk more about that issue at tagup.

**Comment by jkbk2004** [comment]
@kbooker79 can you sync up branch?

**Review by zach1221 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
How is something getting approved if the ufs-weather and fv3 are not up to date?

**Comment by kbooker79** [comment]
> @kbooker79 can you sync up branch?

@jkbk2004 I've synced my develop branch.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by jkbk2004** [comment]
@kbooker79 can you check the cheyenne failure notice?

**Comment by jkbk2004** [comment]
@kbooker79 I also wonder if Brian's git id is connected in the autoRT script?

**Comment by kbooker79** [comment]
> 



> 

@jkbk2004, please add the labels back and try again with the legacy AutoRT.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/1215793622/20230125140011/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1215793622/20230125200007/ufs-weather-model
[RT] Error: Test hrrr_control_decomp_dyn32_phy32 106 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
@kbooker79 is there any reason you are not working on your forked feature branch?

**Comment by jkbk2004** [comment]
@kbooker79 I see /glade/scratch/dtcufsrt on cheyenne test. it should be epicufsrt.

**Comment by kbooker79** [comment]
> @kbooker79 I see /glade/scratch/dtcufsrt on cheyenne test. it should be epicufsrt.



> @kbooker79 I see /glade/scratch/dtcufsrt on cheyenne test. it should be epicufsrt.

@jkbk2004, I noticed that as well...I just made the change.

**Comment by jkbk2004** [comment]
The cheyenne jenkins pipeline runs ok without any confliction. This PR is ready.

**Comment by sadeghitabas** [comment]
I did an RT for hera.intel and hera.gnu as well, you can find it below:
/scratch1/NCEPDEV/nems/Sadegh.Tabas/git/PR1580/

**Review by sadeghitabas — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
One thing I notice is that the removal of the labels is through my account still (using Cheyenne as an example). The goal is to remove my account from all aspects of the autort process.

**Comment by jkbk2004** [comment]
> One thing I notice is that the removal of the labels is through my account still (using Cheyenne as an example). The goal is to remove my account from all aspects of the autort process.

@kbooker79 can you make sure again?

**Comment by DeniseWorthen** [comment]
@kbooker79 Please add a description for what this PR does, as requested in the PR template:

``
Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?
``

**Comment by kbooker79** [comment]
> @kbooker79 Please add a description for what this PR does, as requested in the PR template:
> 
> `Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?`

This has been updated as requested.

**Comment by kbooker79** [comment]
> > One thing I notice is that the removal of the labels is through my account still (using Cheyenne as an example). The goal is to remove my account from all aspects of the autort process.
> 
> @kbooker79 can you make sure again?

@jkbk2004, it's not using your account specifically.  This is being taken care of via the automation and is no way tied to you.

**Comment by jkbk2004** [comment]
> > > One thing I notice is that the removal of the labels is through my account still (using Cheyenne as an example). The goal is to remove my account from all aspects of the autort process.
> > 
> > 
> > @kbooker79 can you make sure again?
> 
> @jkbk2004, it's not using your account specifically. This is being taken care of via the automation and is no way tied to you.

@kbooker79 the point is why it still uses Brian's account when it removes label. can you check again?

**Comment by jkbk2004** [comment]
looks good! all sets.

**Pull request merged**
