### PR TITLE
PLATFORM 989/PLATFORM 1000 - Develop a label (manual) triggered pipeline based on CM team's approval of UFS-WM.  New and improved, now with parallelization. (Combined PR 2057 and PR 2039)

### LINKED ISSUE #2067: New AutoRT for UFS-WM
## Description

Create new autort jenkins pipeline that is simplified, more reliable and runs via jenkinsfile. Capabilities of running regression tests, creating and syncing baselines and pushing logs to the pull request will remain. Pipeline will run on new platforms hercules, gaea-c5 and derecho as well.

## Solution

Work is on-going in the below pull requests.
https://github.com/ufs-community/ufs-weather-model/pull/2057
https://github.com/ufs-community/ufs-weather-model/pull/2039
https://github.com/ufs-community/ufs-weather-model/pull/2017

### PR DESCRIPTION
**Pull request by kbooker79**
…ssion testing in parallel.

## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

This pull request, instantiates Jenkins CI/CD against NOAA on-prem Tier1 platforms based on Github labels attached to the PR (i.e. hera-RT, or jet-BL). The test baselines are updated based on the label. If a Tier1 system contains a label with -BL is selected, new baselines are created before the regression tests are run. Notifications are sent to the appropriate channel on the EPIC Slack workspace.  This is an update on PR-1988 and allows multiple tier-1 platforms to be ran at once and includes a gate for Sonarqube testing.  

## Commit Message

Feature...Instantiates Jenkins CI/CD regression tests against various NOAA on-prem Tier-1 platforms.
### Associated UFSWM Issue to close

Closes #2067 

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

### Input data
- [ ] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@kbooker79 We're adding a Commit Message requirement to the PRs. Please add one in the space provided.

**Comment by jkbk2004** [comment]
A feature branch is not allowed at the weather model authoritative repo. Users can work on their own fork branch. Note that https://github.com/ufs-community/ufs-weather-model/tree/PR-2017 will be deleted.

**Comment by kbooker79** [comment]
> A feature branch is not allowed at the weather model authoritative repo. Users can work on their own fork branch. Note that https://github.com/ufs-community/ufs-weather-model/tree/PR-2017 will be deleted.

That feature branch, was a mistake from doing some testing. This PR itself was created from a proper fork as prescribed.

**Comment by kbooker79** [comment]
This PR now incorporates the features from PR 2057 and PR 2039

**Comment by dustinswales** [comment]
This has been merged into #2035

**Comment by DeniseWorthen** [comment]
@kbooker79 You refer to combining 2057 and 2039. Is that a typo? You mean that 2039 has been combined into this PR 2017, right?

**Comment by kbooker79** [comment]
> @kbooker79 You refer to combining 2057 and 2039. Is that a typo? You mean that 2039 has been combined into this PR 2017, right?

@DeniseWorthen, no that is correct. 2057 was a draft PR and the contents of both it and 2039 are being merged into this PR (2017)

**Comment by DeniseWorthen** [comment]
I just looked at the log posted for Orion. It does not look like the conflicts are being resolved correctly. Has this been fixed?

```
<<<<<<< HEAD
Wed Jan  3 18:37:28 CST 2024
Start Regression test

Testing UFSWM Hash: f4f080e6f954f6febab16de1922f35231a197541
=======
Wed Jan  3 16:01:04 CST 2024
Start Regression test

Testing UFSWM Hash: 5e4cd6254a6419bd1e82f49de8ffc34c58bb7fb6
>>>>>>> 758c1d0d2d6cb2748d3634c44aa39419ac9878f1
Testing With Submodule Hashes:
 37cbb7d6840ae7515a9a8f0dfd4d89461b3396d1 AQM (v0.2.0-37-g37cbb7d)
 2aa6bfbb62ebeecd7da964b8074f6c3c41c7d1eb CDEPS-interface/CDEPS (cdeps0.4.17-38-g2aa6bfb)
 50aa2c97882fbc9d4918813a22169fe97b424564 CICE-interface/CICE (CICE6.0.0-444-g50aa2c9)
 53bae532ddd2623230cdfea221a0784b80060d35 CMEPS-interface/CMEPS (cmeps_v0.4.1-2300-g53bae53)
 cabd7753ae17f7bfcc6dad56daf10868aa51c3f4 CMakeModules (v1.0.0-28-gcabd775)
 bba399053d3939241938f19ee598895eea54fd65 FV3 (remotes/origin/production/HREF.v3beta-289-gbba3990)
 041422934cae1570f2f0e67239d5d89f11c6e1b7 GOCART (sdr_v2.1.2.6-119-g0414229)
 35789c757766e07f688b4c0c7c5229816f224b09 HYCOM-interface/HYCOM (2.3.00-121-g35789c7)
 a36cb73d6924f6cf56a72b5799bef3d75fe4dd61 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-9871-ga36cb73d6)
 569e354ababbde7a7cd68647533769a5c966468d NOAHMP-interface/noahmp (v3.7.1-303-g569e354)
 02693d837f2cd99d20ed08515878c2b5e9525e64 WW3 (6.07.1-343-g02693d83)
 37e740526993fd162d092266ced19c625fbc3d8e stochastic_physics (ufs-v2.0.0-193-g37e7405)
<<<<<<< HEAD
Compile atmaero_intel elapsed time 649 seconds. -DAPP=ATMAERO -DCCPP_SUITES=FV3_GFS_v17_p8 -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release
Compile atmaq_debug_intel elapsed time 238 seconds. -DAPP=ATMAQ -DCCPP_SUITES=FV3_GFS_v15p2 -DDEBUG=ON -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Debug
```

**Comment by kbooker79** [comment]
> I just looked at the log posted for Orion. It does not look like the conflicts are being resolved correctly. Has this been fixed?
> 
> ```
> <<<<<<< HEAD
> Wed Jan  3 18:37:28 CST 2024
> Start Regression test
> 
> Testing UFSWM Hash: f4f080e6f954f6febab16de1922f35231a197541
> =======
> Wed Jan  3 16:01:04 CST 2024
> Start Regression test
> 
> Testing UFSWM Hash: 5e4cd6254a6419bd1e82f49de8ffc34c58bb7fb6
> >>>>>>> 758c1d0d2d6cb2748d3634c44aa39419ac9878f1
> Testing With Submodule Hashes:
>  37cbb7d6840ae7515a9a8f0dfd4d89461b3396d1 AQM (v0.2.0-37-g37cbb7d)
>  2aa6bfbb62ebeecd7da964b8074f6c3c41c7d1eb CDEPS-interface/CDEPS (cdeps0.4.17-38-g2aa6bfb)
>  50aa2c97882fbc9d4918813a22169fe97b424564 CICE-interface/CICE (CICE6.0.0-444-g50aa2c9)
>  53bae532ddd2623230cdfea221a0784b80060d35 CMEPS-interface/CMEPS (cmeps_v0.4.1-2300-g53bae53)
>  cabd7753ae17f7bfcc6dad56daf10868aa51c3f4 CMakeModules (v1.0.0-28-gcabd775)
>  bba399053d3939241938f19ee598895eea54fd65 FV3 (remotes/origin/production/HREF.v3beta-289-gbba3990)
>  041422934cae1570f2f0e67239d5d89f11c6e1b7 GOCART (sdr_v2.1.2.6-119-g0414229)
>  35789c757766e07f688b4c0c7c5229816f224b09 HYCOM-interface/HYCOM (2.3.00-121-g35789c7)
>  a36cb73d6924f6cf56a72b5799bef3d75fe4dd61 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-9871-ga36cb73d6)
>  569e354ababbde7a7cd68647533769a5c966468d NOAHMP-interface/noahmp (v3.7.1-303-g569e354)
>  02693d837f2cd99d20ed08515878c2b5e9525e64 WW3 (6.07.1-343-g02693d83)
>  37e740526993fd162d092266ced19c625fbc3d8e stochastic_physics (ufs-v2.0.0-193-g37e7405)
> <<<<<<< HEAD
> Compile atmaero_intel elapsed time 649 seconds. -DAPP=ATMAERO -DCCPP_SUITES=FV3_GFS_v17_p8 -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release
> Compile atmaq_debug_intel elapsed time 238 seconds. -DAPP=ATMAQ -DCCPP_SUITES=FV3_GFS_v15p2 -DDEBUG=ON -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Debug
> ```

I believe @zach1221 fixed the conflicts.  It should be correct now.

**Comment by DeniseWorthen** [comment]
I don't understand---you mean someone needs to manually resolve conflicts?

**Comment by zach1221** [comment]
> I don't understand---you mean someone needs to manually resolve conflicts?

Let me re-check. I tried to resolve the conflicts manually and may have missed something.

**Comment by DeniseWorthen** [comment]
@zach1221 But why did you need to resolve manually? Is there something about the feature that is not working?

**Comment by zach1221** [comment]
> @zach1221 But why did you need to resolve manually? Is there something about the feature that is not working?

No I think it's working now, just retesting, but I saw the logs were old and not matching develop. So, I was trying to sync up the branch.

**Comment by DeniseWorthen** [comment]
The Gaea log shows that the RT failed

```
FAILED TESTS: 
compile_s2swa_32bit_intel failed in run_compile

REGRESSION TEST FAILED
Thu 04 Jan 2024 03:18:15 PM EST
Elapsed time: 01h:21m:41s. Have a nice day!
```

Shouldn't the commit message indicate that the RT failed?

**Comment by zach1221** [comment]
> The Gaea log shows that the RT failed
> 
> ```
> FAILED TESTS: 
> compile_s2swa_32bit_intel failed in run_compile
> 
> REGRESSION TEST FAILED
> Thu 04 Jan 2024 03:18:15 PM EST
> Elapsed time: 01h:21m:41s. Have a nice day!
> ```
> 
> Shouldn't the commit message indicate that the RT failed?

Yes, I saw. Trying to confirm if it's system related or not. The messaging we can change.

**Comment by zach1221** [comment]
I found the log for that compile suite, it looks like it never started. There's no error log or out log. 
The first line of compile_s2swa_32bit_intel.log says: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

I'll try running gaea again after derecho/orion have completed.

**Comment by jkbk2004** [comment]
@kbooker79 can you sync up branch?

**Comment by zach1221** [comment]
@jkbk2004 ok, I think you should be good to test. Just add the Hercules BL label and it should kick off

**Comment by zach1221** [comment]
@kbooker79 WM PR 2164 is now merged. I will close this PR.

**Pull request closed without merging**
