### PR TITLE
Move unused ccpp suites to 'suites_not_used' directory

### LINKED ISSUE #510: Move deprecated suite definition files (SDFs) into a 'untested' subdirectory
## Description
Many suite definition files (SDFs) are no longer supported by regression tests (RTs). Therefore, there are high risks that those SDFs will encounter errors when used in applications. We decided to move those SDFs into a 'untested' subdirectory under the ccpp/suites directory. Users can modify and test those deprecated SDFs.  

**The SDFs that will be saved are:**
FV3_GFS_v17_p8
FV3_GFS_v17_p8_rrtmgp
FV3_GFS_v17_coupled_p8
FV3_GFS_v17_coupled_p8_sfcocn
FV3_GFS_v15p2
FV3_GFS_v15_thompson_mynn_lam3km
FV3_GFS_v16
FV3_GFS_v16_csawmg
FV3_GFS_v16_ras
FV3_GFS_v16_fv3wam
FV3_RAP
FV3_RAP_RRTMGP
FV3_RAP_sfcdiff
FV3_RAP_unified_ugwp
FV3_RAP_cires_ugwp
FV3_RAP_flake
FV3_RAP_noah
FV3_RAP_noah_sfcdiff_cires_ugwp
FV3_HRRR
FV3_HRRR_smoke
FV3_RRFS_v1beta
FV3_RRFS_v1nssl
FV3_WoFS_v0
FV3_HAFS_v1_gfdlmp_tedmf
FV3_HAFS_v1_gfdlmp_tedmf_nonsst
FV3_HAFS_v1_thompson_tedmf_gfdlsf
FV3_HAFS_v1_thompson_noahmp_nonsst
FV3_HAFS_v1_thompson_noahmp
FV3_HAFS_v1_thompson_nonsst
FV3_HAFS_v1_thompson

**Those 4 SDFs are compiled but not in any RTs**
FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp
FV3_GFS_v15_thompson_mynn
FV3_GFS_v16_ugwpv1
FV3_GFS_v16_noahmp

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

This PR moves all unused ccpp suite definition files to a separate directory (suites_not_used). In FV3/ccpp/suites we currently have 101 suite definition files. Only 27 are actually used (tested). 

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Library Updates/Changes

- [x] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
Depends on NOAA-EMC/fv3atm/pull/665
Closes NOAA-EMC/fv3atm/issues/510

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Regression test log files:
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/11749255/RegressionTests_hera.log)
[RegressionTests_orion.log](https://github.com/ufs-community/ufs-weather-model/files/11749256/RegressionTests_orion.log)

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA We can work on this pr. can you sync up branch?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA We can work on this pr. can you sync up branch?

Done

**Comment by FernandoAndrade-NOAA** [comment]
It looks like control_p8 dbg has failed in jenkins ci, verifying on Hera with a manual run

**Comment by FernandoAndrade-NOAA** [comment]
@jkbk2004 Looks like the failure is due to a timeout in the control_p8_intel with dbg, other cases pass

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins ci logs are attached
[ufs-weather-model » ort-docker-pipeline » PR-1793 #1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/11888013/ufs-weather-model.ort-docker-pipeline.PR-1793.1.Console.Jenkins.txt)

**Comment by BrianCurtis-NOAA** [comment]
> @jkbk2004 Looks like the failure is due to a timeout in the control_p8_intel with dbg, other cases pass

Fixes are in #1810

**Comment by FernandoAndrade-NOAA** [comment]
> > @jkbk2004 Looks like the failure is due to a timeout in the control_p8_intel with dbg, other cases pass
> 
> Fixes are in #1810

Awesome, thanks for the note. The test passed after increasing the wallclock limit in the default_vars.sh, looks like that PR fixes the issue altogether.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, testing is complete. I'll go ahead and leave a notice on the FV3 sub PR to get started with the merge process

**Comment by jkbk2004** [comment]
All tests are done. We can start merging process.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA fv3 pr was merged. We can merge here with hash update.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA fv3 pr was merged. We can merge here with hash update.

Ready for merge.

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
