### PR TITLE
Update upp submodule with the latest UPP release upp_v10.0.12

### LINKED ISSUE #504: Update upp submodule for fixing UPHL issue found in 3-km RRFS North American grid
## Description
There is is an issue found from inline post for UPHL 2-5km issue in 3-km RRFS North American grid

## Solution
Update upp submodule with the latest UPP release upp_v10.0.12.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms? Yes, on WCOSS1-Dell
3. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes? Yes.
- Will the baseline results change? Yes
- If yes, please give brief explanation of your code updates on the regression test.
  There might be updates from inline post output grib2 files

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>: No
- ncar/ccpp-physics/pull/<pr_number>: No
- associated ufs-weather-model/pull/<pr_number>: No

### LINKED ISSUE #1126: Update upp submodule for fixing UPHL issue found in 3-km RRFS North American grid
## Description
There is is an issue found from inline post for UPHL 2-5km issue in 3-km RRFS North American grid.

## Solution
Update upp submodule with the latest UPP release upp_v10.0.12.

## Alternatives
None.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- [FV3 Issue #504](https://github.com/NOAA-EMC/fv3atm/issues/504)
- [FV3 PR #505](https://github.com/NOAA-EMC/fv3atm/pull/505)

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes [#1126](https://github.com/ufs-community/ufs-weather-model/issues/1126) 
- fixes [noaa-emc/fv3atm/issues/#504](https://github.com/NOAA-EMC/fv3atm/issues/504)

## Testing

How were these changes tested? What compilers / HPCs was it tested with? UFS RT tests were conducted on wcoss_dell_p3.
There are changed results expected from inline post output dataset "PRSLEV.GrbF".
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes.
 Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on [noaa-emc/fv3atm/pull/<505>](https://github.com/NOAA-EMC/fv3atm/pull/505)

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA Would you please fill the form at the top of PR (click on the buttons if it applies). Thanks

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Updated. Thanks!

**Comment by binli2337** [comment]
@WenMeng-NOAA Please submit a PR from your upp_update_rrfs branch to my feature/weekly_tests branch at https://github.com/binli2337/ufs-weather-model/tree/feature/weekly_tests. Thanks!

This PR will be combined with PR #1132 .

**Comment by binli2337** [comment]
@WenMeng-NOAA PR #1127 has been combined with PR #1132. Thanks!

**Comment by WenMeng-NOAA** [comment]
@binli2337 Thanks! @junwang-noaa Should I close this PR?

**Comment by junwang-noaa** [comment]
The code updates was merged. The PR will be closed.

**Comment by junwang-noaa** [comment]
Sure. Please check if PR#1132 has all the information from PR#1127. Thanks

**Pull request closed without merging**
