### PR TITLE
Convert all global (uncoupled) and regional tests to use quilting restart

### LINKED ISSUE #1627: Transition to fv3atm write grid component restart capability for single domain
## Description
This work is to update the regression test to use the write grid component restart capability developed un issue #1587. In issue #1587, the initial code updates were developed to allow the write grid component to write out single domain fv3atm restart files, the same as those written out by the FMS. The restart reproducibility is also maintained. Three sample test case for cpld_control_p8, control_p8 and regional_control are added to regression test suite for testing and transition purpose. This issue is intended to resolve possible issues raising at the experiment testing time after the initial code is committed to the develop branch and to transition the current regression restart tests for those applications that use fms restart to write grid component restart.  A separate issue will cover the future work for multiple domain restart files for HAFS and regional apps. 

## Solution
This new feature needs to be verified in global and regional workflow, and in the parallel (or parallel like) testing before we completely switch to write grid component restart capability.

### LINKED ISSUE #1971: update MOM6 to its main repo 20231025 (NCAR-candidate), 20231031 (GMAO FMS_cap) and 20231106 (GFDL readthedocs.yml configuration) commit
MOM6 main repository had two updating in the past week:
(1) NCAR-candidate-2023-09-13 which was merged on 20231025
(2) GMAO FMS_cap which was merged on 20231031
see detail at https://github.com/NOAA-EMC/MOM6/issues/121
(3) GFDL readthedocs.yml configuration which was merged on 20231106
see detail at https://github.com/mom-ocean/MOM6/pull/1613#event-10874919543
no answer change is expected.
We need to update dev/emc repo correspondingly.

### LINKED ISSUE #1973: Update the revision of upp submodule
## Description
The current upp version (harsh: fae617b) under FV3 includes two fix files postxconfig-NT-GEFS-aerosol.txt and postxconfig-NT-gefs-aerosol.txt. That causes a colliding issue for local checkout. See report [here](https://github.com/NOAA-EMC/UPP/issues/804).

## Solution
Update upp revision to the latest commit (harsh: 7fbc413) from UPP repository which remove the legacy file postxconfig-NT-gefs-aerosol.txt.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12929393/RegressionTests_hera.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

All global (uncoupled) and regional test are converted to use quilting restart. Two regression tests, one global (control_p8) and one regional (hrrr_control) are also running with FMS I/O restart in addition to quilting restart. All other tests that are currently running quiting restart (tests with '_qr' in the name) are removed.

Includes and Closes #1972
Includes and Closes #1974

### Associated UFSWM Issue to close

Closes #1627
Closes #1973 (From #1974)
Closes #1971 (from #1972)

### Subcomponent Pull Requests

NOAA-EMC/fv3atm/pull/713
NOAA-EMC/fv3atm/pull/717 (from #1974)
NOAA-EMC/MOM6/pull/122 (from #1972)

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [x] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Regression test passed one Hera: 
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12929393/RegressionTests_hera.log)

**Comment by SamuelTrahanNOAA** [comment]
I'm curious. Why aren't you making this change to the coupled tests?

**Comment by DusanJovic-NOAA** [comment]
@junwang-noaa suggested that at this point we should only change uncoupled tests.

**Comment by SamuelTrahanNOAA** [comment]
I trust her judgement, but I'm still curious about the reason. If she's willing to share it, I'd be grateful.

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA The purpose of the moving restart writing from forecast to write grid component is to save forecast time. In the coupled configuration, only fv3 is using write grid component while other components are still doing IO on the forecast grid component. So at restart time even though fv3 can move on with forecast but it has to wait for other components to finish writing their restart files, some of which may take longer time than fv3. Also for the higher resolution case than C96, writing restart files may require increase write group since now write grid comp takes longer time to finish. So we won't get speed up 
 in coupled tests while may need to increase resources. Because of these reasons, I suggested not to add the feature in the coupled test at this time.

**Comment by SamuelTrahanNOAA** [comment]
Ah, well, perhaps one day the other coupled components will have quilt servers, too.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we are considering to combine in #1972 (mom6 update) and #1974 (upp hash update) to this pr. All no baseline change. Can you combine in those PRs?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA we are considering to combine in #1972 (mom6 update) and #1974 (upp hash update) to this pr. All no baseline change. Can you combine in those PRs?

Done.

**Comment by zach1221** [comment]
I added code change, so we can resolve issue [1440](https://github.com/ufs-community/ufs-weather-model/issues/1440) when this PR is merged.

**Comment by FernandoAndrade-NOAA** [comment]
Jet had failures with `control_c384_intel` and `control_c384gdas_intel`
run directory is available at
`
/lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_240434
`
It looks like a memory issue, I'm seeing an out of memory error in the err file

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA there is a chance for those two cases to get hitting max requested/allowed memory on jet. In your run, I see control_c192_intel maximum resident set size (KB) = 719668 is slightly getting bigger than current develop 697100 (KB). I tried to increase resource but it sounds like still same problem. It might be worth to set option in job script #SBATCH --mem-per-cpu=##G.  We can create git issue fr further investigation.

**Comment by jkbk2004** [comment]
> @FernandoAndrade-NOAA there is a chance for those two cases to get hitting max requested/allowed memory on jet. In your run, I see control_c192_intel maximum resident set size (KB) = 719668 is slightly getting bigger than current develop 697100 (KB). I tried to increase resource but it sounds like still same problem. It might be worth to set option in job script #SBATCH --mem-per-cpu=##G. We can create git issue fr further investigation.

somehow it hits around core level
```
 55: libpthread-2.17.s  00002AF93EC60630  Unknown               Unknown  Unknown
 55: fv3.exe            000000000268796C  tp_core_mod_mp_yp         888  tp_core.F90
 55: fv3.exe            000000000266BD86  tp_core_mod_mp_fv         168  tp_core.F90
 55: fv3.exe            00000000025F828E  sw_core_mod_mp_d_        1016  sw_core.F90
 55: fv3.exe            000000000210D25B  dyn_core_mod_mp_d         882  dyn_core.F90
 55: libiomp5.so        00002AF93B7EBBB3  __kmp_invoke_micr     Unknown  Unknown
 55: libiomp5.so        00002AF93B767FAC  __kmp_fork_call       Unknown  Unknown
 55: libiomp5.so        00002AF93B729CB5  __kmpc_fork_call      Unknown  Unknown
 55: fv3.exe            00000000020FE7A2  dyn_core_mod_mp_d         770  dyn_core.F90
```

**Review by SamuelTrahanNOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
> > @FernandoAndrade-NOAA there is a chance for those two cases to get hitting max requested/allowed memory on jet. In your run, I see control_c192_intel maximum resident set size (KB) = 719668 is slightly getting bigger than current develop 697100 (KB). I tried to increase resource but it sounds like still same problem. It might be worth to set option in job script #SBATCH --mem-per-cpu=##G. We can create git issue fr further investigation.
> 
> somehow it hits around core level
> 
> ```
>  55: libpthread-2.17.s  00002AF93EC60630  Unknown               Unknown  Unknown
>  55: fv3.exe            000000000268796C  tp_core_mod_mp_yp         888  tp_core.F90
>  55: fv3.exe            000000000266BD86  tp_core_mod_mp_fv         168  tp_core.F90
>  55: fv3.exe            00000000025F828E  sw_core_mod_mp_d_        1016  sw_core.F90
>  55: fv3.exe            000000000210D25B  dyn_core_mod_mp_d         882  dyn_core.F90
>  55: libiomp5.so        00002AF93B7EBBB3  __kmp_invoke_micr     Unknown  Unknown
>  55: libiomp5.so        00002AF93B767FAC  __kmp_fork_call       Unknown  Unknown
>  55: libiomp5.so        00002AF93B729CB5  __kmpc_fork_call      Unknown  Unknown
>  55: fv3.exe            00000000020FE7A2  dyn_core_mod_mp_d         770  dyn_core.F90
> ```

There are no memory allocation calls on that line:

```f90
          do j=js-1,je+1
             do i=ifirst,ilast
                bl(i,j) = al(i,j  ) - q(i,j)   ! <---- here
                br(i,j) = al(i,j+1) - q(i,j)
                b0(i,j) = bl(i,j) + br(i,j)
                smt5(i,j) = bl(i,j)*br(i,j) < 0.
             enddo
          enddo
```

The `bl` and `al` arrays are local:

```f90
 real:: al(ifirst:ilast,js-1:je+2)
 real, dimension(ifirst:ilast,js-1:je+1):: bl, br, b0
```

and `q` is an argument to the subroutine:

```f90
 real   , INTENT(IN) :: q(ifirst:ilast,jsd:jed)
```

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - Where is the log file from your failed Jet run?

**Comment by jkbk2004** [comment]
> /lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_240434

/lfs4/HFIP/h-nems/Fernando.Andrade-maldonado/RT_RUNDIRS/Fernando.Andrade-maldonado/FV3_RT/rt_240434

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA local arrays look ok in tp_core. I rather think Jet is small memory machine: 61G per node for xjet. Compared to other machines, it's a lot smaller. Unless we use Jet bigmem partition. Not exactly same case but similarity is with https://github.com/ufs-community/ufs-weather-model/issues/1695  @BrianCurtis-NOAA #SBATCH --mem-per-cpu=##G option is not available on jet.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA local arrays look ok in tp_core. I rather think Jet is small memory machine: 61G per node for xjet. Compared to other machines, it's a lot smaller. Unless we use Jet bigmem partition. Not exactly same case but similarity is with #1695 @BrianCurtis-NOAA #SBATCH --mem-per-cpu=##G option is not available on jet.

That's not the option you should be using anyway.  You need to decrease the number of ranks per node or increase the number of cpus per rank.

**Comment by SamuelTrahanNOAA** [comment]
In my tests, the control_c384gdas_intel and control_c384_intel are killed by the out-of-memory killer.

Increasing the memory use is a problem with the model, not with Jet.

**Comment by SamuelTrahanNOAA** [comment]
> Increasing the memory use is a problem with the model, not with Jet.

Actually, it might be a problem with the post, not the model. You've updated the post in this PR.

**Comment by SamuelTrahanNOAA** [comment]
I'm able to run these changes on top of mine in #1941 if I tweak the number of write ranks and ppn for the c384 tests on jet.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA great! Then, we can turn off control_c384/gdas/jet at this pr and try to turn on in #1941.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA great! Then, we can turn off control_c384/gdas/jet at this pr and try to turn on in #1941.

@jkbk2004 - The c192 tests are *not* failing for me. Also, I'm using Rocoto. Some aspect of your problem may be ecFlow-specific.

**Comment by BrianCurtis-NOAA** [comment]
> > @SamuelTrahanNOAA great! Then, we can turn off control_c384/gdas/jet at this pr and try to turn on in #1941.
> 
> @jkbk2004 - The c192 tests are _not_ failing for me. Also, I'm using Rocoto. Some aspect of your problem may be ecFlow-specific.

Mind testing those with ecflow for your PR ? @jkbk2004 try rocoto for the failing tests, see if the results differ. Would be good to know if ecflow is truly the culprit.

**Comment by DusanJovic-NOAA** [comment]
I see control_c384gdas sets TPN to 18 on jet (change from the default 24), while control_c384gdas does not. Why? Are they both crashing with OOM? What's the difference between those two tests? Why do we run both of them, isn't control_c384 just a special case of control_c384gdas? Is there a realistic scenario where control_c384gdas runs fine but control_c384 dosn't? Who maintains these tests?

**Comment by jkbk2004** [comment]
If I adjust TPN, crashing point moves around. Quite some random behavior. @FernandoAndrade-NOAA Can you confirm the case is not much to do with ecflow/rocoto issue? Then, we will make a decision to turn off these cases on jet.

**Comment by jkbk2004** [comment]
BTW, #1974 works fine with control_c384/gdas cases on jet.

**Comment by FernandoAndrade-NOAA** [comment]
> If I adjust TPN, crashing point moves around. Quite some random behavior. @FernandoAndrade-NOAA Can you confirm the case is not much to do with ecflow/rocoto issue? Then, we will make a decision to turn off these cases on jet.

It seems that way to me. I've switched to running RTs on Jet with ecflow for about a month now, this is the first time I've run into this issue with these cases.

**Comment by SamuelTrahanNOAA** [comment]
My #1941 branch worked until I merged this branch's changes. Then two C384 tests failed on Jet. I'm pretty sure it's from this branch's changes. I was able to fix it by tweaking the number of write ranks and PPNs. I'm testing that in ecflow now. Compiling takes a while on Jet, so it may be a few hours.

**Comment by SamuelTrahanNOAA** [comment]
My fix for the Jet crashes is here:

https://github.com/DusanJovic-NOAA/ufs-weather-model/pull/39

It increases the write task counts and/or reduces the tasks per node for the failing jobs.

**Comment by DusanJovic-NOAA** [comment]
> My fix for the Jet crashes is here:
> 
> [DusanJovic-NOAA#39](https://github.com/DusanJovic-NOAA/ufs-weather-model/pull/39)
> 
> It increases the write task counts and/or reduces the tasks per node for the failing jobs.

Merged. Thanks Sam.

**Comment by SamuelTrahanNOAA** [comment]
@FernandoAndrade-NOAA @jkbk2004 - Could you please test Jet again, now that Dusan has merged my fixes?

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA @jkbk2004 - Could you please test Jet again, now that Dusan has merged my fixes?

Looks good after those changes, thanks!

**Comment by FernandoAndrade-NOAA** [comment]
My mistake on the review requests, sub prs still need to get merged in.

**Comment by SamuelTrahanNOAA** [comment]
> My mistake on the review requests, sub prs still need to get merged in.

The FV3 PR is already approved. Someone needs to press the Merge button.

**Comment by jkbk2004** [comment]
@jiandewang All test are done. Can you merge in the MOM6 pr?

**Comment by jkbk2004** [comment]
https://github.com/NOAA-EMC/fv3atm/pull/713 was merged

**Comment by jiandewang** [comment]
> [@SamuelTrahanNOAA](/SamuelTrahanNOAA) [SamuelTrahanNOAA](/SamuelTrahanNOAA) mentioned this pull request [ Nov 13, 2023 ](#ref-pullrequest-1943664393)
> [ new global_nest_v1 suite and #1965 #1941 ](/ufs-community/ufs-weather-model/pull/1941)
>  Open
> 36 tasks

just merged
commit a36cb73d6924f6cf56a72b5799bef3d75fe4dd61 (HEAD -> dev/emc, origin/dev/emc, origin/HEAD)
Merge: 02d4dc455 80a93f633
Author: jiandewang <jiande.wang@noaa.gov>
Date:   Tue Nov 14 08:12:33 2023 -0500

    Merge pull request #122 from jiandewang/feature/update-NCAR-GMAO-20231031

    update MOM6 to its main repo 20231025 (NCAR candidate) and 20231031(GMAO FMS_cap) updating

**Comment by jkbk2004** [comment]
MOM6 PR was merged as well: https://github.com/NOAA-EMC/MOM6/commit/a36cb73d6924f6cf56a72b5799bef3d75fe4dd61

**Review by jiandewang — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
