### PR TITLE
Adding a few JEDI-related aliases into the `fd_ufs.yaml` file+Add option to specify fv3atm history and inline post files output directory #2254 + Bump jinja2 from 3.1.3 to 3.1.4 in /doc/UsersGuide #2270

### LINKED ISSUE #2084: allow output which is controlled by FMS (diag_table) to be optionally written to specified directory
## Description

Currently all MOM6) gets written to the current working directory. For G-W, it is preferable that this output be in a configurable location, e.g. ``ATM_OUTPUT``. For MOM6, there is currently a ``MOM6_OUTPUT`` directory available, but the model output itself is not written to that directory. 

## Solution

Update the ``diag_table`` files with a configurable location. For MOM6, this requires for example:

```
 ######################
"./MOM6_OUTPUT/ocn%4yr%2mo%2dy%2hr",      6,  "hours", 1, "hours", "time", 6, "hours", "1901 1 1 0 0 0"
##############################################
# ocean output TSUV and others
 "ocean_model", "SSH",       "SSH",      "./MOM6_OUTPUT/ocn%4yr%2mo%2dy%2hr","all",.true.,"none",2
....
```

For the  RTs, the output directory for the ATM should be maintained in the current working directory so that the list of baseline comparison files does not need to change. This can be done by using ``export ATM_OUTPUT = ./`` which will be used for the ATM portion of the diag_table.

### LINKED ISSUE #2262: Need aliases for JEDI-UFS in fd_ufs.yaml
## Description
For the JEDI-UFS integration, several aliases are needed in `fd_ufs.yaml` to be able to exchange variables:

## Solution
See https://github.com/ufs-community/ufs-weather-model/pull/2215

## Alternatives
Hardcode in JEDI-UFS interface (not preferred)

## Related to
n/a

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

For the JEDI-UFS integration, several aliases are needed in `fd_ufs.yaml`. This PR adds the missing aliases.

Add new model_configure option (fv3atm_output_dir) to specify directory in which all history and inline post files will be saved.

### Commit Message:
```
* UFSWM - Add several aliases in `fd_ufs.yaml` needed for JEDI-UFS. Add new model_configure option (fv3atm_output_dir) to specify directory in which all fv3atm history and inline post files will be saved.
  * FV3 -  Add new model_configure option (fv3atm_output_dir) to specify directory in which all history and inline post files will be saved.
```

### Priority:
* Normal

#### ISSUES
* Closes #2262
* Closes #2084
#### MERGED PR'S
* Closes #2254 
* Closes #2270 

### Sub component Pull Requests:
* FV3: NOAA-EMC/fv3atm#826

### UFSWM Blocking Dependencies:
* None
---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by climbfuji** [comment]
@jkbk2004 JCSDA needs this PR - I can pick it up where it is and get it ready. Can we add this to the commit queue for tomorrow's meeting?

**Comment by climbfuji** [comment]
@jkbk2004 I ran rt.sh for this PR on Derecho for the latest commit (https://github.com/ufs-community/ufs-weather-model/pull/2215/commits/9299932bbda8eaa0acfd2f4e7d7be0f9101a5b9e) - which is up to date with develop - and all regression tests passed against the existing baseline. `test_changes.list` submitted as requested. PR is ready!

**Comment by jkbk2004** [comment]
@fabiolrdiniz can you sync up the branch one more time? We can start working on this pr. Note that we are considering to combine in #2253 and #2254.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA I combined in #2254 to this pr.

**Comment by zach1221** [comment]
I'll do a prelim test of the combined PR on hercules.

Tests all passed. 
[RegressionTests_hercules.log](https://github.com/ufs-community/ufs-weather-model/files/15240400/RegressionTests_hercules.log)

**Comment by zach1221** [comment]
@FernandoAndrade-NOAA @BrianCurtis-NOAA I think we can begin testing here.

**Comment by zach1221** [comment]
Regression testing is complete. We can proceed with merging process.

**Comment by BrianCurtis-NOAA** [comment]
The template is incomplete. We're probably not using that commit message. When we merge many PR's into one it's important to make sure the template is also updated.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by zach1221** [comment]
> The template is incomplete. We're probably not using that commit message. When we merge many PR's into one it's important to make sure the template is also updated.

Commit message is updated.

**Comment by DusanJovic-NOAA** [comment]
> > The template is incomplete. We're probably not using that commit message. When we merge many PR's into one it's important to make sure the template is also updated.
> 
> Commit message is updated.

Please do not use ampersand sign in commit message

**Comment by BrianCurtis-NOAA** [comment]
> > The template is incomplete. We're probably not using that commit message. When we merge many PR's into one it's important to make sure the template is also updated.
> 
> Commit message is updated.

I've made edits, it should look more like this. we don't need all the extra information. I had to bring in issues we're closing with this PR from other PR's

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
