### PR TITLE
P7b: Update BM ICs for soil variables release

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [ ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This updates the input data date.  The update in the input file is so that the land-spin up for NOAH-MP is included in the sfc files for soil variables for the BM7_ICs.  

### Issue(s) addressed

- Issue #624 

## Testing

Currently, the 35 day tests are being run with a 20 min wall clock to ensure that all IC dates for benchmarks initialize.
Will update the thread when these have completed.  

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

No dependencies

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Sanity check of 20 minute time limit runs for new sfc files for this branch are here: 
/scratch1/NCEPDEV/stmp2/Jessica.Meixner/FV3_RT/rt_229257

**Comment by junwang-noaa** [comment]
Can you confirm if the land ICs are from:
/scratch1/NCEPDEV/stmp2/Michael.Barlage/spinup/mini8a/jarvis or from
/scratch1/NCEPDEV/stmp2/Michael.Barlage/spinup/mini7a/jarvis
?

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa they are from /scratch1/NCEPDEV/stmp2/Michael.Barlage/spinup/mini7a/jarvis 

diff /scratch1/NCEPDEV/stmp2/Michael.Barlage/spinup/mini7a/jarvis/2013040100/sfc_data.tile1.nc /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20210608/FV3_input_frac/BM7_IC/2013040100/gfs/C384_L127/INPUT/sfc_data.tile1.nc

diff /scratch1/NCEPDEV/stmp2/Michael.Barlage/spinup/mini7a/jarvis/2013040100/sfc_data.tile1.nc /scratch1/NCEPDEV/stmp2/Jessica.Meixner/FV3_RT/rt_229257/cpld_bmarkfrac_wave_v16_noahmp_35d_2013040100/INPUT/sfc_data.tile1.nc 


@barlage @LydiaStefanova-NOAA @jiandewang and others can you please help double check my work and confirm that this is in fact what we want as well?  This PR and PR #625 are using the same inputs.

**Comment by jiandewang** [comment]
I confirm that the land IC in Jessica's short runs are identical to what's in Mike's directory. The ocean results in Jessica's short runs are different from what I had in the previous "wrong" P7a run. (they are suppose to be different)

**Comment by LydiaStefanova-NOAA** [comment]
And I confirm that the difference in soil temperatures in the [the new runs vs the "wrong" P7a at fh000] match the differences in the [ICs in Mike's directory vs the ICs used for the "wrong" P7a]

**Comment by JessicaMeixner-NOAA** [comment]
Since for the p7b branch, we are going to wait for the reorganized input directory, should I just close this PR?

**Comment by junwang-noaa** [comment]
Yes, please do, thanks.

**Pull request closed without merging**
