### PR TITLE
Update CDEPS component in ufs-weather-model

### LINKED ISSUE #1740: Update CDEPS component in ufs-weather-model
## Description
The CDEPS repository has been updated. The CDEPS component in the ufs-weather-model needs to be updated. Main changes related to the UFS applications are in the data ocean component.

## Solution
Update CDEPS component
Update namelist used in data ocean model

### PR DESCRIPTION
**Pull request by binli2337**
## Description
The CDEPS repository has been updated. The CDEPS component in the ufs-weather-model needs to be updated.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [x] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
https://github.com/NOAA-EMC/CDEPS/pull/55
Fixes #1740 

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by zach1221** [comment]
Hi, @binli2337 . We're going to create a PR soon to your branch to combine #1699 with this PR. In anticipation of that, could you sync up your branch with this PR so it's up to date, please?

**Comment by jkbk2004** [comment]
@binli2337 can you sync up branch? If we can combine in #1669, we can start working on this pr.

**Comment by zach1221** [comment]
Hi, @binli2337 your changes have been combined into #1699 , so we can work from that PR to merge both yours and Sadegh changes. Please let me know if you have any issues with this.

**Comment by zach1221** [comment]
Changes from this PR were combined into #1699 . PR #1699 has just been merged into ufs-community:develop, so this PR can now be closed.

**Pull request closed without merging**
