### PR TITLE
update CMEPS to allow bilinear ATM<->WAV mapping for global coupled application; utilize custom restart names for WW3 (was #1684) 

### LINKED ISSUE #85: map using bilinear + nearest source-to-destination for ATM-WAV
When coupling ATM and WAV, the fields exchanged between the components are state fields, not fluxes. They should be mapped bilinearly to better preserve the gradients in the fields.

### LINKED ISSUE #1590: For a "continue" run, WW3 should not start unless a restart is present
## Description

Currently WW3 can always start "cold", without a WW3 restart file present. This is not desirable w/in UWM since it could lead to unexpected results if a WW3 restart is expected but instead WW3 starts cold (e.g. the WW3 restart is not present for some reason). 

## Solution

In UWM, WW3 should fail if the ``runtype=continue`` and no WW3 restart file is present. This feature should be added to the mesh cap in order to not interfere w/ other use cases.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Changes the mapping of state fields between ATM and WAV for the coupled model to use bilinear with nearest-source-to-destination filling.

A test case was run using the ``cpld_control_p8`` test for 24 hours with and w/o this change. The following figure shows the difference in ``U10M`` along ~62S, from 90W:40W imported by the WAV model with the current mapping (``mapnstod_consf``, black line) vs the change in this PR (``mapbilnr_nstod``, red line).

Screen Shot 2023-03-29 at 10 03 35 AM

The  impact on the ``Z0`` imported by the ATM at ~0.5S,6E (on the coast of Brazil, where a large difference in ``Z0`` is seen) for the current mapping (red) vs this PR (black) is shown below

Screen Shot 2023-03-29 at 10 25 09 AM

In the bmark test, the difference in ``Z0`` imported by the ATM on tile 1 (scaled by 1.0e4) after 6 hours is shown below

Screen Shot 2023-03-29 at 11 20 05 AM

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

This will change baselines for all coupled tests using ATM-WAV coupling. HAFS wave tests do not change since their mapping is mapfillv_bilnr and does not change.

Full RTs on cheyenne show the following:

GNU: 
```
FAILED TESTS:
Test cpld_control_p8 047 failed in check_result failed
Test cpld_control_p8 047 failed in run_test failed
Test cpld_debug_p8 049 failed in check_result failed
Test cpld_debug_p8 049 failed in run_test failed
```
INTEL: 
```
FAILED TESTS:
Test cpld_control_p8_mixedmode 001 failed in check_result failed
Test cpld_control_p8_mixedmode 001 failed in run_test failed
Test cpld_control_gfsv17 002 failed in check_result failed
Test cpld_control_gfsv17 002 failed in run_test failed
Test cpld_control_p8 003 failed in check_result failed
Test cpld_control_p8 003 failed in run_test failed
Test cpld_control_qr_p8 005 failed in check_result failed
Test cpld_control_qr_p8 005 failed in run_test failed
Test cpld_2threads_p8 007 failed in check_result failed
Test cpld_2threads_p8 007 failed in run_test failed
Test cpld_decomp_p8 008 failed in check_result failed
Test cpld_decomp_p8 008 failed in run_test failed
Test cpld_mpi_p8 009 failed in check_result failed
Test cpld_mpi_p8 009 failed in run_test failed
Test cpld_control_ciceC_p8 010 failed in check_result failed
Test cpld_control_ciceC_p8 010 failed in run_test failed
Test cpld_control_c192_p8 011 failed in check_result failed
Test cpld_control_c192_p8 011 failed in run_test failed
Test cpld_control_noaero_p8 013 failed in check_result failed
Test cpld_control_noaero_p8 013 failed in run_test failed
Test cpld_debug_p8 015 failed in check_result failed
Test cpld_debug_p8 015 failed in run_test failed
Test cpld_debug_noaero_p8 016 failed in check_result failed
Test cpld_debug_noaero_p8 016 failed in run_test failed
```

[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11101512/RegressionTests_cheyenne.gnu.log)
[RegressionTests_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11101513/RegressionTests_cheyenne.intel.log)

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):

- PR #1684 
## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Fixes https://github.com/NOAA-EMC/CMEPS/issues/85
- Depends on https://github.com/NOAA-EMC/CMEPS/pull/86
- Associated with Issue https://github.com/ufs-community/ufs-weather-model/issues/1556
- Fixes https://github.com/ufs-community/ufs-weather-model/issues/1590

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jkbk2004 I had to recreate my CMEPS update PR and then re-merged the ww3 restart name change. This PR is equivalent to the previous  PR #1685

**Comment by jkbk2004** [comment]
Sure! @zach1221 @BrianCurtis-NOAA this pr replaces #1685. I am adding new bl date.

**Comment by jkbk2004** [comment]
@DeniseWorthen two cases fail on jet: hafs_regional_datm_cdeps and regional_noquilt. I think regional_noquilt time out issue. But hafs_regional_datm_cdeps shows something hycom side in out file: error in zaiopf -  can't open unit  13. can you check /lfs4/HFIP/h-nems/Jong.Kim/RT_RUNDIRS/Jong.Kim/FV3_RT/rt_52646/hafs_regional_datm_cdeps/out ? All ran ok on hera though.

**Comment by zach1221** [comment]
Please see jenkins-ci logs attached. ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1692 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11133623/ufs-weather-model.ort-docker-pipeline.PR-1692.1.Console.Jenkins.pdf)

**Comment by DeniseWorthen** [comment]
@jkbk2004 I will look, but I suspect a jet system issue. This PR does not touch anything in hycom or cdeps.

**Comment by DeniseWorthen** [comment]
There is a timeout message in the hafs_regional_datm_cdeps err log also. It seems to have hung. But I will run the test independently to check.

**Comment by jkbk2004** [comment]
> There is a timeout message in the hafs_regional_datm_cdeps err log also. It seems to have hung. But I will run the test independently to check.

I agree the time out case usually ended up with that hycom error message. Same thing occasionally happens even with develop branch. I think we need to turn those cases off on jet.

**Comment by BrianCurtis-NOAA** [comment]
We can't keep turning off tests that don't work. The issues need to be addressed with the machine admins and/or fixes in the UFSWM.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA It does seem that jet is a flakey platform in general and it is difficult for either us or sys admins to debug intermittent issues. Generally we have the "2 tries" but even that doesn't seem to be enough for jet.

**Comment by DeniseWorthen** [comment]
I don't think this causes the time-outs, but we should reduce the debug flags here. There is no reason for those to be anything other than 0 as a default. The higher settings simply report min/max values for import/export states for example. They do not actually turn on any sort of compiler-debug options.

```
nems.configure.hafs_atm_docn.IN:93:  dbug_flag = 20
nems.configure.hafs_atm_ocn.IN:122:  dbug_flag = 20
nems.configure.hafs_atm_ocn_wav.IN:134:  dbug_flag = 6
nems.configure.hafs_atm_wav.IN:96:  dbug_flag = 6
```

**Comment by DeniseWorthen** [comment]
The current jet log shows this test taking almost 24 minutes. On Cheyenne.intel, it takes a 21 minutes. I would suggest we reduce the fhmax for this test to 12 or even 6. It is currently 24 but all the other HAFS tests are only 6 hours.

**Comment by jkbk2004** [comment]
> The current jet log shows this test taking almost 24 minutes. On Cheyenne.intel, it takes a 21 minutes. I would suggest we reduce the fhmax for this test to 12 or even 6. It is currently 24 but all the other HAFS tests are only 6 hours.

Sounds like consistent 6 hour across hafs tests makes a sense. same way for regional_noquilt, right?

**Comment by DeniseWorthen** [comment]
I think reducing fhmax may work sometimes, but I just ran a the hafs_regional_datm_cdeps case on Jet w/ fhmax=12 and it didn't even finish 12 hours. It was a half-hour short when it ran out of wall clock. I just think there are just system issues w/ Jet.

**Comment by jkbk2004** [comment]
On jet, these 5 cases are continuously facing the time-out issue: regional_noquilt hafs_regional_datm_cdeps regional_wofs regional_atmaq regional_atmaq_faster. @DeniseWorthen @BrianCurtis-NOAA sounds like turning off all regional aqm cases on jet, too much? Other than that, Jet RT log is available to push.

**Comment by DeniseWorthen** [comment]
I already pushed a commit to remove regional_noquilt and hafs_regional_datm_cdeps for jet.intel. Now the other regional tests are timing-out?

**Comment by jkbk2004** [comment]
> I already pushed a commit to remove regional_noquilt and hafs_regional_datm_cdeps for jet.intel. Now the other regional tests are timing-out?

Yes, I keep seeing those 3 other cases continue to hit the time limit. I vote to turn those off if possible. We will create an issue and revisit the issue along with that.

**Comment by DeniseWorthen** [comment]
I will push a commit to remove regional_wofs, regional_atmaq, regional_atmaq_faster from jet.intel.

**Comment by jkbk2004** [comment]
I am writing an issue to address the jet time-out cases. We can start merging process. @DeniseWorthen @BrianCurtis-NOAA Can you go ahead to merge in CMEPS PR?

**Comment by jkbk2004** [comment]
issue was created #1695

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
All set! @BrianCurtis-NOAA @SadeghTabas-NOAA please, go ahead to approve the pr.

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
