### PR TITLE
Fourth reconciliation PR from production/RRFS.v1 + Add PIO switch to WW3 to avoid build errors #2512

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:

This PR bring the changes from https://github.com/ufs-community/ufs-weather-model/pull/2170 into the develop branch and is work from @haiqinli.

-- Update the MYNN PBL, Smoke and subgrid cloud fraction for the RRFS.v1 code freeze.
-- Merge the bugfix in the HAILCAST diagnostic code (unit issue)

This PR also combines changes from https://github.com/ufs-community/ufs-weather-model/pull/2512

### Commit Message:

```
* UFSWM - MYNN PBL, Smoke and subgrid cloud fraction.
  * FV3 - MYNN PBL, Smoke and subgrid cloud fraction.
    * ccpp-physics - MYNN PBL, Smoke and subgrid cloud fraction.
    * atmos_cubed_sphere - hail diagnostics, and average of smoke/dust.
  * WW3 -  Updated to add PIO switch to avoid build error 
```

### Priority:

* High: Needed for SRW App

### UFSWM:

* None

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/883
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/230
  * atmos_cubed_sphere: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/363
* GOCART:
* HYCOM:
* MOM6:
* NOAHMP:
* WW3: https://github.com/NOAA-EMC/WW3/pull/1324
* fire_behavior:
* stochastic_physics:
* None

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
Note: As discussed with @masih-e @danrosen25 @pedro-jm, this PR, together with changes in https://github.com/ufs-community/ufs-weather-model/pull/2481 fixes a problem in the new fire behavior regression test (cpld_regional_atm_fbh) whereby the values of kinematic_surface_upward_sensible_heat_flux_of_fire, surface_upward_specific_humidity_flux_of_fire, and smoke_emission_of_fire are not correctly being transferred from the fire behavior module to the CCPP physics because of an error in CCPP metadata.

**Comment by jkbk2004** [comment]
@grantfirl can you sync up the branches? We can start working on this pr. #2512 (hotfix for PIO WW3 build issue and no impact on baselines) can be combined into this pr. Just need to point to https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/addPIOswitch

**Comment by grantfirl** [comment]
> @grantfirl can you sync up the branches? We can start working on this pr. #2512 (hotfix for PIO WW3 build issue and no impact on baselines) can be combined into this pr. Just need to point to https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/addPIOswitch

Finished syncing and combining #2512.

**Comment by MatthewMasarik-NOAA** [comment]
@FernandoAndrade-NOAA noaa-emc/ww3/pull/1324 has been merged.

**Comment by jkbk2004** [comment]
@grantfirl the fv3 pr was merged: new hash https://github.com/NOAA-EMC/fv3atm/commit/1648e176fa869d0ca9ce9ea5822b3594afd8c353

**Review by JessicaMeixner-NOAA — APPROVED** [review]
WW3 commit hash looks good.  Thank you @grantfirl  and @jkbk2004  for including the WW3 fix in this PR!!

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
