### PR TITLE
add a cdeps test using GFSv16 input data

### LINKED ISSUE #1069: Add a CDEPS test using GFSv16 input data
## Description
A new CDEPS test will be added to use GFSv16 input data.

## Solution
1. A CDEPS test using GFSv16 input data will be added to the regression test suite.
2. The mushy-layer thermodynamic option will be used in CICE.
3. New GFSv16 input data will be added to the input-data-20211210/DATM_CDPES/GFS directory.

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [x] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Add a new CDEPS test using GFSv16 input data

### Issue(s) addressed

- fixes #1069 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

### CODE REVIEW

**Comment by binli2337** [comment]
@DeniseWorthen The code has been updated. Thanks.

**Comment by BrianCurtis-NOAA** [comment]
Do we still need to get the new baseline for the new test before the intel tests pass?

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I created the single new test baseline for intel and added it to the existing baseline.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/866818037/20220311160012/ufs-weather-model
[RT] Error: Test control_fhzero 014 failed in run_test failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel 017 failed in run_test failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel_debug 062 failed in run_test failed 
[RT] Error: Test hafs_regional_atm 090 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn 092 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 095 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
```
Checking test 014 control_fhzero results ....
 Comparing sfcf000.nc ............ALT CHECK......ERROR

Checking test 017 control_wrtGauss_netcdf_parallel results ....
 Comparing sfcf000.nc ............ALT CHECK......ERROR

Checking test 062 control_wrtGauss_netcdf_parallel_debug results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf001.nc ............ALT CHECK......ERROR

Checking test 090 hafs_regional_atm results ....
 Comparing atmf006.nc ............ALT CHECK......ERROR

Checking test 092 hafs_regional_atm_ocn results ....
 Comparing atmf006.nc ............ALT CHECK......ERROR

Checking test 095 hafs_regional_docn results ....
 Comparing atmf006.nc ............ALT CHECK......ERROR
```

**Review by junwang-noaa — APPROVED** [review]

**Comment by binli2337** [comment]
There are 12 failed tests on wcoss_dell_p3. I will rerun those tests.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/866818037/20220311194514/ufs-weather-model
[RT] Error: Test control_fhzero 014 failed in run_test failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel 017 failed in run_test failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel_debug 062 failed in run_test failed 
[RT] Error: Test hafs_regional_atm 090 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn 092 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 095 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: jet Compiler: intel Job: RT [RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/866818037/20220311194514/ufs-weather-model [RT] Error: Test control_fhzero 014 failed in run_test failed [RT] Error: Test control_wrtGauss_netcdf_parallel 017 failed in run_test failed [RT] Error: Test control_wrtGauss_netcdf_parallel_debug 062 failed in run_test failed [RT] Error: Test hafs_regional_atm 090 failed in run_test failed [RT] Error: Test hafs_regional_atm_ocn 092 failed in run_test failed [RT] Error: Test hafs_regional_docn 095 failed in run_test failed Please make changes and add the following label back: jet-intel-RT

Same as last time. Is this similar to the issues we were seeing with the PR before Dom's?

**Comment by junwang-noaa** [comment]
No, I have not seen such issue in jet RT.

**Pull request merged**
