### PR TITLE
Add FV3 suite WoFS_v0

### LINKED ISSUE #1168: Add a new suite definition file to FV3 (FV3_WoFS_v0) for SRW release
## Description
Add a new suite definition file to FV3 (FV3_WoFS_v0) to use the NSSL cloud microphysics scheme with Noah LSM. For use use with the next SRW app release

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- https://github.com/ufs-community/ufs-weather-model/pull/1158

### PR DESCRIPTION
**Pull request by MicroTed**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

Adds new suite definition file to FV3 (FV3_WoFS_v0) to use the NSSL cloud microphysics scheme with Noah LSM. For use use with the next SRW app release.

## Testing

Testing done on Jet

- [x] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [x] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [x] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?

"waiting for other repos"
- dependency for ufs-community/regional_workflow/pull/708
- waiting on noaa-emc/fv3atm/pull/514
- ORT failures (rst and dcp) fixed by https://github.com/NCAR/ccpp-physics/pull/904

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@MicroTed It looks to me you created two PRs, #1158 and #1159, maybe they can be combined? Also please fill up information on the checklist, description, issues( all the PRs need to have an issue associated), testing information and dependencies(any submodule needs to be updated).  Thanks

**Comment by MicroTed** [comment]
@junwang-noaa  Only one of the drafts will be used, depending on whether the RT tests for v1nssl should be converted to WoFS_v0 or not. I may have jumped the gun a little on that.. 1158 just adds the new SDF without touching the RT files, which is the easiest path.

**Comment by RatkoVasic-NOAA** [comment]
@MicroTed could you please try to run case with this new SDF by reversing MPI layout in input.nml file. For example, if you have layout = 6,11 - try with layout = 11,6 (this will change MPI decomposition)
For the compilation flag please add option -DREPRO=ON (this will use less aggressive optimization)
Purpose of this is to see if we get bit-wise identical results with two different MPI layouts.

*NOTE* Our current SDF (suite_FV3_GFS_v15_thompson_mynn_lam3km.xml) is reproducing results only with coarse resolution (currently tested in UFS regression tests), but at 3km it is creating different results.

**Comment by MicroTed** [comment]
@RatkoVasic-NOAA 

>  please try to run case

Sure thing. Is there any particular current RT test that would be good?

> by reversing MPI layout in input.nml file

My experience with changing the layout is that optimization has to be off completely (to turn off vectorization). Otherwise there can be a change in the "leftover" operations that don't fit into the vector and have different round-off characteristics. It has been a few years since I've tested that, so YMMV.

**Comment by RatkoVasic-NOAA** [comment]
@MicroTed 
Dynamics-only is reproducing results in different MPI layout, so should with physics (which is column-only and independent of MPI).

There are two tests in rt,conf:
RUN     | regional_control
RUN     | regional_3km

First one uses low resolution and second one high resolution. Just reminder to use -DREPRO=ON in COMPILE line, and of course, use suite_FV3_WoFS_v0.xml in same line.
Also, you have to use your input.nml and model_configure files.
When you run rt.sh, run it with -k option (which will keep run directories). Then you go in each run directory (save output) and resubmit job_card (with edited layout line in input.nml).

**Comment by MicroTed** [comment]
@RatkoVasic-NOAA 
I guess it is expected that regional_3km has no real convection in the domain for a 6hr forecast? There doesn't seem to be much for the microphysics to do there.

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA I guess it is expected that regional_3km has no real convection in the domain for a 6hr forecast? There doesn't seem to be much for the microphysics to do there.

Right

**Comment by junwang-noaa** [comment]
@MicroTed May I ask if you ran the decomposition test as Ratko suggested (reversing MPI layout in input.nml file)? We need to run the ORT test(threading, decomposition, restart reproducibility test and debug test ) for new physics suite. Thanks.

**Comment by MicroTed** [comment]
> Dynamics-only is reproducing results in different MPI layout, so should with physics (which is column-only and independent of MPI).

Not completely column-only -- the Thompson interface (mp_thompson.F90) has 2D loops that will vary in width with MPI. The NSSL scheme is 2D within the microphysics code (works on 2D slabs rather than just columns)

@junwang-noaa  I did try flipping the layout on the regional_3km, and results do change, even after changing the REPRO options to '-fp-model precise'

**Comment by junwang-noaa** [comment]
@MicroTed is the test reproducing with restart runs?
@ligiabernardet @ywangwof @arunchawla-NOAA The new suite file FV3_WoFS_v0 does not reproduce decomposition. Do you want it to be in SRW v2 release?

**Comment by ywangwof** [comment]
Yes. We want it to be in the SRW v2 release. Could you provide more details about the decomposition reproducing? Actually, this PR just adds one CCPP suite file. I am wondering why it will impact the decomposition?

**Comment by junwang-noaa** [comment]
@ywangwof The requirement for public release is that the suite files are well tested. When developers run the test using the suite file (e.g. regional_3km_wofs) with different threads, different decomposition, and restart they will get same answer. The test can also run in debug mode. These tests are required for public release (@ligiabernardet please let me know if the requirement is changed).

**Comment by MinsukJi-NOAA** [comment]
@MicroTed 

In the `rt.conf` file, you have a new test `regional_3km_wofs`. However, your new test file is `tests/tests/regional_3km_wofsv0`. These two names have to match to be able to run the regression test.

**Comment by MicroTed** [comment]
> These two names have to match to be able to run the regression test.

@MinsukJi-NOAA Thanks for pointing that out! I renamed the file.

**Comment by MicroTed** [comment]
> could you please try to run case with this new SDF by reversing MPI layout in input.nml file. For example, if you have layout = 6,11 - try with layout = 11,6 (this will change MPI decomposition)

@RatkoVasic-NOAA 
I have done some tests with this, and I find the same behavior you get with suite_FV3_GFS_v15_thompson_mynn_lam3km.xml. The WoFS suite has reproducible results for regional_control (10,6 vs. 6,10) but not for various tests on 3km grids. (Even with DEBUG=ON.) The NSSL microphysics module is virtually the same as in WRF, where it has no problems with the reproducibility tests. So I suspect there is something common to both SDFs or namelist options that could be the culprit. 

At this point, it seems reasonable to note that there is an issue somewhere and move on?

**Comment by JeffBeck-NOAA** [comment]
Pinging @junwang-noaa, since I think Ratko may be on leave. It sounds like there is a systematic problem with physics reproducibility at higher resolutions that we'll need to address at some point, but it's unrelated to the SDFs themselves.  Therefore, do you think we could get this PR back into the merge queue?  Thanks!

**Comment by junwang-noaa** [comment]
@JeffBeck-NOAA Since this suite file is for CCPP v6 public release. Please check with @ligiabernardet and @ChunxiZhang-NOAA, if both of them are OK to have the suite file in fv3/ccpp/suites, we will continue with this PR. Thanks.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @junwang-noaa.  I'll check with them.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @junwang-noaa!

@ligiabernardet, @ChunxiZhang-NOAA, regarding the reproducibility issue, do you know if this a problem with a specific physics parameterization or a combination of physics?  I'm just trying to get a feeling for how we should proceed with the PR, since it's just an SDF and no physics code is being committed.  Thanks!

**Comment by ligiabernardet** [comment]
I don't know which schemes/suites pass the reproducibility/decomposition tests. @grantfirl @ChunxiZhang-NOAA Do you have this information?

**Comment by ChunxiZhang-NOAA** [comment]
@ligiabernardet The NSSL MP scheme probably is not tested for reproducibility/decomposition. The suite WoFS_v0 is only one scheme different to the RRFS_v1nssl suite, e.g., WoFS_v0 uses Noah_lsm, while RRFS_v1nssl uses Noahmp_lsm. The decomposition reproducibility issue could be caused by the NSSL MP itself or the treatment of the lateral boundary conditions in the regional runs.

**Comment by JeffBeck-NOAA** [comment]
@ChunxiZhang-NOAA, so the NSSL MP parameterization was merged before reproducibility/decomposition testing for physics was required?  I would certainly agree with new parameterizations being tested, but since this PR is just an SDF XML for existing physics, I would advocate for noting the testing that @MicroTed conducted and moving ahead.  It does sound like dedicated funds/time are needed to get to the bottom of the reproducibility problem soon, as it impacts multiple physics parameterizations, and only at certain resolutions.  It'd be good to narrow it down to either the physics or the LBCs first.

**Comment by MicroTed** [comment]
The Thompson and NSSL schemes both have reproducible results in WRF, and the CCPP versions likely do not change that. Since the two mentions SDFs with either scheme have different results at 3km vs. large scale, it suggest that the issue is not either microphysics scheme (or something common to both in the cap-end drivers).

It is definitely worth pursuing the root(s) of this issue (though not necessarily for this PR). Is there a dx <= 3km test where a particular suite has reproducible output? An ideal setup with periodic BC may help to isolate or rule out some physics packages.

**Comment by ChunxiZhang-NOAA** [comment]
I did ORT tests for the NSSL MP scheme. The ORT tests were based on a low resolution global domain and it forecasted 24 hours. The findings are:
1) The dcp test: 
     For rrfs_v1nssl, the dcp test failed. Interestingly, with fhcyc=24, the difference started from fh21 plus one time step; with fhcyc=0, the difference started from fh21 or fh21 minus one time step. Still don't know what caused the problem because gcycle was not called with either fhcyc=0 or fhcyc=24 at fh21.
     For rrfs_v1nssl_nohailnoccn, the dcp test passed. The dcp test for the rrfs_v1beta passed too, and the only difference between rrfs_v1beta and rrfs_v1nssl is the MP scheme.  So I guess there are bugs in dynamics related to adding the extra tracer hail or the treatment of CCN (less likely) in the NSSL scheme.
2) The rst test:
    Since the rst tests for both rrfs_v1nssl and rrfs_v1nssl_nohailnoccn failed, I guess there are bugs for restart variables in this scheme. It needs to check if all the intermediate variables are written out correctly and not reinitialized in the code. 
The differences between the SDF rrfs_v1nssl and WoFS_v0 are very small, .e.g., rrfs_v1nssl employed the NoahMP land surface scheme and the WoFS_v0 employed the Noah land surface scheme. Probably the decomposition and restart issues are mainly caused by the NSSL MP scheme. 
One question for Ted: why <scheme>GFS_suite_interstitial_3</scheme>
                                                 <scheme>GFS_suite_interstitial_4</scheme>
                                          are not included in the rrfs_v1nssl and WoFS_v0 SDFs?

**Comment by ywangwof** [comment]
@ChunxiZhang-NOAA The dcp test failure may relate to the initialization of "`water_nc`" in _field_table_. It should be "`0.0`" but not `1.e30`. It is a bug I found while testing the **WoFS_v0** suite. I suppose it is also presented in the _field_table_ for **rrfs_v1nssl** suite. Please confirm. 
```
# prognostic cloud water number concentration
 "TRACER", "atmos_mod", "water_nc"
           "longname",     "cloud liquid water number concentration"
           "units",        "/kg"
       "profile_type", "fixed", "surface_value=0.0" /
```

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA The dcp test failure may relate to the initialization of "`water_nc`" in _field_table_. It should be "`0.0`" but not `1.e30`. It is a bug I found while testing the **WoFS_v0** suite. I suppose it is also presented in the _field_table_ for **rrfs_v1nssl** suite. Please confirm.
> 
> ```
> # prognostic cloud water number concentration
>  "TRACER", "atmos_mod", "water_nc"
>            "longname",     "cloud liquid water number concentration"
>            "units",        "/kg"
>        "profile_type", "fixed", "surface_value=0.0" /
> ```

@ywangwof It is '0.0' in the field_table in the rrfs_v1nssl tests.

**Comment by MicroTed** [comment]
> 2\. One question for Ted: why GFS_suite_interstitial_3
>     GFS_suite_interstitial_4
>     are not included in the rrfs_v1nssl and WoFS_v0 SDFs?

@ChunxiZhang-NOAA The interstitial routines are left out because there is no convection parameterization scheme. As far as I could tell, those routines do not do anything if a CPS is not active, so I took them out. If that is incorrect, I can put them back in.

**Comment by grantfirl** [comment]
> > 2. One question for Ted: why GFS_suite_interstitial_3
> > GFS_suite_interstitial_4
> > are not included in the rrfs_v1nssl and WoFS_v0 SDFs?
> 
> @ChunxiZhang-NOAA The interstitial routines are left out because there is no convection parameterization scheme. As far as I could tell, those routines do not do anything if a CPS is not active, so I took them out. If that is incorrect, I can put them back in.

@ChunxiZhang-NOAA To chime in, I agree with @MicroTed that those schemes can safely be left out of the SDF in this suite.

**Comment by MinsukJi-NOAA** [comment]
@ChunxiZhang-NOAA Regarding the restart test, I believe the restart ORT failure for `regional_3km_wofs` may have to do with the test setup. I was working to resolve this, but couldn't figure it out. Similarly, I could not set up a restart ORT for `regional_3km`. @RatkoVasic-NOAA Is it possible to set a test case for restart regression test for `regional_3km`, so that I can correctly configure ORT test?

**Comment by MicroTed** [comment]
> We need to run the ORT test(threading, decomposition, restart reproducibility test and debug test ) for new physics suite.

@junwang-noaa Is there a particular procedure laid out somewhere for these tests that we can follow? It didn't come up in the CCPP process, though it seems it probably should have. Thanks!

**Comment by RatkoVasic-NOAA** [comment]
>  @RatkoVasic-NOAA Is it possible to set a test case for restart regression test for `regional_3km`, so that I can correctly configure ORT test?

 @MinsukJi-NOAA  I'm back and working on it.

**Comment by ChunxiZhang-NOAA** [comment]
> > > 2. One question for Ted: why GFS_suite_interstitial_3
> > >    GFS_suite_interstitial_4
> > >    are not included in the rrfs_v1nssl and WoFS_v0 SDFs?
> > 
> > 
> > @ChunxiZhang-NOAA The interstitial routines are left out because there is no convection parameterization scheme. As far as I could tell, those routines do not do anything if a CPS is not active, so I took them out. If that is incorrect, I can put them back in.
> 
> @ChunxiZhang-NOAA To chime in, I agree with @MicroTed that those schemes can safely be left out of the SDF in this suite.

@MicroTed @grantfirl Thanks!

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA Regarding the restart test, I believe the restart ORT failure for `regional_3km_wofs` may have to do with the test setup. I was working to resolve this, but couldn't figure it out. Similarly, I could not set up a restart ORT for `regional_3km`. @RatkoVasic-NOAA Is it possible to set a test case for restart regression test for `regional_3km`, so that I can correctly configure ORT test?

The ORT restart tests I conducted was global C96 for rrfs_v1nssl and rrfs_v1nssl_nohailnoccn. Both of them failed.

**Comment by MicroTed** [comment]
> The ORT restart tests I conducted was global C96 for rrfs_v1nssl and rrfs_v1nssl_nohailnoccn. Both of them failed.

@ChunxiZhang-NOAA Could you point me to these? I'm not familiar with these tests. I suppose it is fairly simple and straightforward? 
Assuming that the tests work for rrfs_v1beta, the only difference then is the cloud microphysics scheme, and I can try to look from there.

**Comment by ChunxiZhang-NOAA** [comment]
@MicroTed  Sure, I will send you an email very soon. It is simple and straightforward.

**Comment by arunchawla-NOAA** [comment]
Can we get to the bottom of why these suites are failing even at the coarser resolutions ?

**Comment by MinsukJi-NOAA** [comment]
@ChunxiZhang-NOAA Can you send me step-by-step instructions for me to try to reproduce your findings?

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA Can you send me step-by-step instructions for me to try to reproduce your findings?

@MinsukJi-NOAA  Sure, I sent you an email just now.

**Comment by JeffBeck-NOAA** [comment]
> Can we get to the bottom of why these suites are failing even at the coarser resolutions ?

My understanding is that they aren't.  At least not with @MicroTed's tests with the NSSL MP.

**Comment by MicroTed** [comment]
> My understanding is that they aren't.  At least not with @MicroTed's tests with the NSSL MP.

I think that was referring to restart tests for reproducibility? That's something I have not tested (it hadn't come up before), and haven't had time yet to really investigate.

**Comment by arunchawla-NOAA** [comment]
The rrfs_v1nssl tests also seem to be failing. Bottom line is we should have ORT tests pass. I understand that this is new requirement and there are suites that are already in develop that are failing, but we should really get to the bottom of these and try and identify where the problem is, before adding more suites to develop. Our codes should be robust enough that they pass domain decomposition, restart reproducibility tests

**Comment by MinsukJi-NOAA** [comment]
I was able to reproduce @ChunxiZhang-NOAA ORT results.
* `rrfs_v1nssl` fails decomposition and restart
*  `rrfs_v1nssl_nohailnoccn` fails restart
* `rrfs_v1beta` passes

**Comment by ChunxiZhang-NOAA** [comment]
> I was able to reproduce @ChunxiZhang-NOAA ORT results.
> 
> * `rrfs_v1nssl` fails decomposition and restart
> * `rrfs_v1nssl_nohailnoccn` fails restart
> * `rrfs_v1beta` passes

Thank you Minsuk. Good to know.

**Comment by MicroTed** [comment]
The restart reproducibility failure was a pretty simple fix, at least for rrfs_v1nssl_nohailnoccn. Now testing rrfs_v1nssl.

rrfs_v1nssl passes the restart test, but doesn't fix the dcp test.

Update 2: Setting nssl_ccn_on=.false. makes the dcp test work, so apparently the hail category is not an issue. Rather, something related to predicting ccn.

**Comment by MinsukJi-NOAA** [comment]
> The restart reproducibility failure was a pretty simple fix, at least for rrfs_v1nssl_nohailnoccn. Now testing rrfs_v1nssl.
> 
> rrfs_v1nssl passes the restart test, but doesn't fix the dcp test.
> 
> Update 2: Setting nssl_ccn_on=.false. makes the dcp test work, so apparently the hail category is not an issue. Rather, something related to predicting ccn.

That is great @MicroTed! Would you commit your code changes? I will run the ORTs to confirm they work.

**Comment by MicroTed** [comment]
> Would you commit your code changes?

@MinsukJi-NOAA The restart fix is in CCPP:
https://github.com/MicroTed/ccpp-physics
branch: nssl_restart

I have a lead on the ccn prediction issue, but haven't nailed it down exactly where or why.

**Comment by RatkoVasic-NOAA** [comment]
> The restart reproducibility failure was a pretty simple fix, at least for rrfs_v1nssl_nohailnoccn. Now testing rrfs_v1nssl.
> 
@MicroTed what was the fix?
Thanks.

**Comment by MicroTed** [comment]
> @MicroTed what was the fix?

@RatkoVasic-NOAA  For the restart issue, the problem was running a subroutine call that creates number concentrations from the single-moment initial condition on the first time step. It only needed the restart flag added to the logic to prevent running that routine for the first step of a warm start.

By the way, the opnReqTest doesn't have a setup section for Jet. Does it not work there, or has it just not been needed? Fortunately I can "borrow" a little time on hera for these tests, but jet has been my main platform.

**Comment by RatkoVasic-NOAA** [comment]
> By the way, the opnReqTest doesn't have a setup section for Jet. Does it not work there, or has it just not been needed? Fortunately I can "borrow" a little time on hera for these tests, but jet has been my main platform.

@MinsukJi-NOAA  do you know the answer?

**Comment by MinsukJi-NOAA** [comment]
@RatkoVasic-NOAA @MicroTed opnReqTest has not been set up for Jet. I will add and test jet support -- but probably not for this PR.

On Hera, you can save time using ecflow:
1. After login to Hera, `ssh hecflow01`
2. `cd ufs-weather-model/tests`
3. `./opnReqTest -n rrfs_v1nssl_nohailnoccn -c thr,dcp,rst,dbg -ek >&out`

**Comment by MicroTed** [comment]
The dcp test for the global works if nssl_invertccn=.false. I don't understand yet why the "true" option fails, but it is used for LAM domains to avoid needing BCs for the CCN variable (BC can be just zero).

**Comment by MicroTed** [comment]
The dcp issue seems to be fixed. I opened a PR for CCPP for both the restart and dcp fixes:

https://github.com/NCAR/ccpp-physics/pull/904

**Comment by MinsukJi-NOAA** [comment]
> The dcp issue seems to be fixed. I opened a PR for CCPP for both the restart and dcp fixes:
> 
> [NCAR/ccpp-physics#904](https://github.com/NCAR/ccpp-physics/pull/904)

Passing of the `rrfs_v1nssl` decomposition test confirmed.

**Comment by MinsukJi-NOAA** [comment]
@MicroTed I have made a PR to your `wofs_sdf` branch. All changes are related only to ORT test and confined in the `tests/opnReqTests/` directory. After you merge in these changes, you can invoke `./opnReqTests -n regional_3km_wofs -c thr,dcp,dbg`. My finding so far is that the decomposition test fails. The only difference I see between `suite_FV3_WoFS_v0.xml` and `suite_FV3_RRFS_V1nssl.xml` is `lsm_noah` vs `noahmpdrv`.

**Comment by MicroTed** [comment]
> My finding so far is that the decomposition test fails.

@MinsukJi-NOAA  OK, good to know, and thanks for doing that -- I have't gone back to the 3km test yet. Considering that FV3_GFS_v15_thompson_mynn_lam3km also has trouble with decomposition for the 3km test, maybe it is not surprising. Maybe even expected?

**Comment by junwang-noaa** [comment]
@MicroTed If I understand correctly, the suite_FV3_RRFS_V1nssl.xml has decomposition test passed. So for the suite file suite_FV3_WoFS_v0.xml, are you considering using noahmpdrv instead of lsm_noah for the regional_3km_wofs decomposition test?

**Comment by MicroTed** [comment]
> the suite_FV3_RRFS_V1nssl.xml has decomposition test passed

Yes, it passes the rrfs_v1nssl RT case, which is a global coarse grid. But, like the lam3km suite, apparently not on the 3km regional grid. Is there a regional case that passes decomposition? The rt.conf has a comment that rap_decomp and rap_sfcdiff_decomp also don't work. Is there one that does work?

**Comment by junwang-noaa** [comment]
If the suite_FV3_WoFS_v0.xml is going to be used by SRW as a regional test, I think the decomposition test needs to be fixed, if not please set up a global test case with suite_FV3_WoFS_v0.xml, so  the ORT will pass.

**Comment by MicroTed** [comment]
> SRW as a regional test, I think the decomposition test needs to be fixed

Sure, I can add the global test. It works fine. I'm also testing regional_control adapted for the WoFS_v0 suite, but that has a note that restart tests don't work?

Update: "Test dcp regional_wofs PASS" So whatever the problem is with the 3km test, it is likely that same thing that affects both the lam3km and wofs suites. 
@junwang-noaa  Do you have a preference for adding the global test, the regional (coarse grid) test, or both for the WoFS suite?

**Comment by junwang-noaa** [comment]
@MicroTed I'd suggest to add the test that will be used in public release and fix the issue if there is. I think Ratko is also debugging the lam3km test case, maybe you can work with him.

**Comment by MicroTed** [comment]
Update: We found that the regional_3km_wofs passes the decomposition test if nrows_blend=0. The problem with nrows_blend > 0 appears to be the setting of loop limits for the blending points in the corner MPI tiles (in the bc_time_interpolation subroutine in fv_regional_bc.F90).

**Comment by MicroTed** [comment]
Nevermind this -- I think there is another route.
--------
Would be OK to proceed with the FV3 PR to add the WoFS suite so it can be included in the SRW-v3? https://github.com/NOAA-EMC/fv3atm/pull/514
At this point the remaining ORT issues appear to be in the dycore rather than the physics suite.  
Thanks!

**Comment by junwang-noaa** [comment]
A PR with the suite files was committed to the SRW public release branch. 
This PR will be moved to Q4FY2022 regression test development EPIC, it will be committed after the restart issue is resolved..

**Comment by SamuelTrahanNOAA** [comment]
This PR included changes to GFDL_atmos_cubed_sphere which have already been merged.

**Comment by DeniseWorthen** [comment]
Closing in favor of PR #1460

**Pull request closed without merging**
