### PR TITLE
Implementation of CCPP timestep_init and timestep_final phases

### LINKED ISSUE #338: Implementation of CCPP timestep_init and timestep_final phases
## Description

Add CCPP `timestep_init` and `timestep_final` phases to ufs-weather-model, fv3atm, GFDL_atmos_cubed_sphere, ccpp-framework, ccpp-physics.

The `timestep_init` phase will take the place of and run the `time_vary` group of the CCPP suite definition files, i.e. run at the beginning of every time step. The `timestep_final` phase will be added at the end of the physics calls at every time step (not doing anything at the moment).

Same as for the CCPP `init` and `final` phases, `timestep_init` and `timestep_final` will automatically run over all blocks at the same time (same as the `time_vary` group), and the conversion of the blocked data into contiguous arrays and back happens in the auto-generated caps (instead of manually inside the `time_vary` physics). This allows us to remove the dependency on the GFS DDTs in the calls to the `time_vary` physics. It also simplifies greatly the calls to `gcycle`/`sfcsub`.

No changes required for the suite definition files or the regression test configuration.

Because the data conversions happen in different places, and the loops over the individual blocks inside the `time_vary` physics is removed, it is possible that this will change the answer in full/prod mode. In debug or repro mode, b4b identical results are expected. This will need to be confirmed when it is time for committing the PRs listed below.

## Solution
The implementation of these changes requires five PRs across the different repositories:

https://github.com/ufs-community/ufs-weather-model/pull/337
https://github.com/NOAA-EMC/fv3atm/pull/217
https://github.com/NCAR/ccpp-physics/pull/534
https://github.com/NCAR/ccpp-framework/pull/344
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/47

## Alternatives
None.

## Related to
See above.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Code changes thus far:
- Update .gitmodules and submodule pointer for fv3atm for code review and testing

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/338.

## Testing

**Testing (12/30/2020)** against official baseline on hera with Intel (`rt.conf`) and GNU (`rt_gnu.conf`): all regression tests pass.

[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/5756460/RegressionTests_hera.intel.log)
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/5756461/RegressionTests_hera.gnu.log)

**Testing (01/04/2021)** against official baseline on hera with Intel (`rt.conf`) after moving the code to clear diagnostic buckets using GFS DDT-bound procedures from `atmos_model.F90` to `CCPP_driver.F90` in fv3atm: all regression tests pass.

[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/5766610/RegressionTests_hera.intel.log)

**Final regression testing 01/07/2021:**

- regression tests passed on all tier-1 platforms: cheyenne.gnu, cheyenne.intel, gaea.intel, hera.gnu, hera.intel, jet.intel, orion.intel, wcoss_cray wcoss_dell_p3; logs updated in the PR

## Dependencies

https://github.com/ufs-community/ufs-weather-model/pull/337
https://github.com/NOAA-EMC/fv3atm/pull/217
https://github.com/NCAR/ccpp-physics/pull/534
https://github.com/NCAR/ccpp-framework/pull/344
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/47

### CODE REVIEW

**Comment by climbfuji** [comment]
@MinsukJi-NOAA do you know why the CI tests fail for this draft PR? The error message is not giving any details, just:
```
compiling std with compile option CCPP=Y SUITES=FV3_GFS_2017
109 Died with error code 2
110 The command '/bin/sh -c ./utest -n $test_name -c $build_case -z' returned a non-zero code: 2
111
112 Error: Process completed with exit code 2.
```
The code compiles and runs on my Mac with GNU.

I'd appreciate any insight you may have. Thanks!

**Comment by climbfuji** [comment]
I am opening this PR for review. I will have to pull in updates from NOAA-EMC develop before it is the turn for this PR (I am aware of the "WW3 submodule update" PR, the "Remove IPD/MOM6 submodule update" PR, and Dusan's `rt.sh` PR thus far). But the code changes itself should be final.

I don't know yet whether the results will change with full optimization flags on for Intel. On my Mac with GNU, the results are b4b identical for the suites I have tested so far (`GFS_v16beta`).

**Comment by climbfuji** [comment]
> @MinsukJi-NOAA do you know why the CI tests fail for this draft PR? The error message is not giving any details, just:
> 
> ```
> compiling std with compile option CCPP=Y SUITES=FV3_GFS_2017
> 109 Died with error code 2
> 110 The command '/bin/sh -c ./utest -n $test_name -c $build_case -z' returned a non-zero code: 2
> 111
> 112 Error: Process completed with exit code 2.
> ```
> 
> The code compiles and runs on my Mac with GNU.
> 
> I'd appreciate any insight you may have. Thanks!

This should be fixed in #331 (which has been pulled into this PR).

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
CI tests are running. Once those pass, this PR is ready to merge.

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa CI tests passed, please review and merge whenever it is convenient for you. Thanks and happy weekend!

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
