### PR TITLE
update MOM6 to its main branch 20230206 updating and remove cpld_esmfthreads_p8

### LINKED ISSUE #1598: drop cpld_esmfthreads_p8 test
## Description

The ``cpld_esmfthreads_p8`` test can be dropped after PR #1523 which made all tests use esmf-managed threading. 

## Solution

Remove the test from rt.conf and tests/tests.

### PR DESCRIPTION
**Pull request by jiandewang**
## Description

MOM6 main branch is updated on 20230206, this is based on EMC ungridded dimension pstokes PR (https://github.com/mom-ocean/MOM6/pull/1591), but being added through cherry-pick the ci failure fixing from dev/gfdl.
need to make corresponding updating in dev/emc and ufs-weather-model. No answer change is expected.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [x] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- fixes UFS issue #1601 
- fixes MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/110
- fixes #1598

MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/111

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [x] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jiandewang** [comment]
[HERA_intel-log.pdf](https://github.com/ufs-community/ufs-weather-model/files/10671446/HERA_intel-log.pdf)

**Comment by jiandewang** [comment]
[HERA-gun-log.pdf](https://github.com/ufs-community/ufs-weather-model/files/10672074/HERA-gun-log.pdf)

**Comment by jiandewang** [comment]
@jkbk2004 can you give a bit high priority for this PR by combining it with upcoming PR as https://github.com/ufs-community/ufs-weather-model/pull/1599 is pending on it. It only has one line of script level change to fix MOM6 CI issue, no any code or answer change.

**Comment by DeniseWorthen** [comment]
It might be worthwhile to fix Issue #1598 with this PR since doesn't have any code changes either. All it needs is to remove the ``tests/cpld_esmfthreads_p8`` file and remove ``cpld_esmfthreads_p8`` from the rt.conf

**Comment by jiandewang** [comment]
> It might be worthwhile to fix Issue #1598 with this PR since doesn't have any code changes either. All it needs is to remove the `tests/cpld_esmfthreads_p8` file and remove `cpld_esmfthreads_p8` from the rt.conf

@DeniseWorthen sure will do that

**Comment by jiandewang** [comment]
> > It might be worthwhile to fix Issue #1598 with this PR since doesn't have any code changes either. All it needs is to remove the `tests/cpld_esmfthreads_p8` file and remove `cpld_esmfthreads_p8` from the rt.conf
> 
> @DeniseWorthen sure will do that

@DeniseWorthen can you double check on what I did for Issue #1598 ?

**Comment by DeniseWorthen** [comment]
@jiandewang Looks good.

**Comment by jkbk2004** [comment]
@jiandewang sounds like to resolve a conflict on fv3.

**Comment by jiandewang** [comment]
> @jiandewang sounds like to resolve a conflict on fv3.

I may did the merging in the wrong order, waiting for Jun's instruction. My branch was not up to date (as you just had one commit today), while Jun's is up to date. I did the merge before sync mine

**Comment by jiandewang** [comment]
just checked Jun's branch, it turned out that neither her nor mine branch did sync before I did the merging. Things are being messed up so let me delete my branch and start from new, will ask Jun to do the same thing, then Jun can re-issue a PR to my branch.

**Comment by jkbk2004** [comment]
@jiandewang I think you can reopen once @junwang-noaa update https://github.com/junwang-noaa/fv3atm/tree/hafs_movingnest

**Comment by jiandewang** [comment]
> @jiandewang I think you can reopen once @junwang-noaa update https://github.com/junwang-noaa/fv3atm/tree/hafs_movingnest

just removed old and re-issue a new (clean) PR https://github.com/ufs-community/ufs-weather-model/pull/1606

**Comment by jkbk2004** [comment]
> > @jiandewang I think you can reopen once @junwang-noaa update https://github.com/junwang-noaa/fv3atm/tree/hafs_movingnest
> 
> just removed old and re-issue a new (clean) PR #1606

sure!

**Pull request closed without merging**
