### PR TITLE
Update WW3 

### LINKED ISSUE #1473: Update WW3
## Description

The WW3 develop branch has been updated to include auto-formatting, removal of whitespace and cleanup of some #ifdefs. These changes need to be added to the dev/ufs-weather-model branch and then UWM needs to be updated.

A bug associated with the export of the wave spectrum when coupling with CICE6 is also fixed (see issue https://github.com/NOAA-EMC/WW3/issues/843)

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Updates WW3 for auto-formatting, cleanup of whitespace and some #ifdef removal.

### Issue(s) addressed

fixes #1473 

## Testing

All tests containing waves were run on hera.intel and hera.gnu. All baselines were b4b at [9ae1b4f](https://github.com/DeniseWorthen/ufs-weather-model/commit/9ae1b4f1006a7a2022e97dab4e9bd5a02e4114bb). Tests were re-run after wave_spectrum export fix and were again b4b  at [170614b](https://github.com/ufs-community/ufs-weather-model/pull/1474/commits/170614bd5f7b8f541986a79a875b1dcdde1d058e)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

waiting on https://github.com/NOAA-EMC/WW3/pull/840

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA This PR is being combined with a couple of AQM PRs and is going to start testing today for commit. The changes in WW3 are whitespace + a bug fix.

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA This PR is being combined with a couple of AQM PRs and is going to start testing today for commit. The changes in WW3 are whitespace + a bug fix.

@DeniseWorthen, great!  Thanks for the update.  We'll start looking at the bug fix on our end.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA Just FYI, we have no application which exercises the cice6-wave coupling. The issue was found during testing for an unrelated CMEPS PR.

**Comment by MatthewMasarik-NOAA** [comment]
@DeniseWorthen okay, thanks for the heads up.  I'll make note of that.

**Comment by DeniseWorthen** [comment]
Closing; PR  is combined with #1476

**Pull request closed without merging**
