### PR TITLE
RRTMGP refactoring

### PR DESCRIPTION
**Pull request by dustinswales**
## Description

This PR contains changes to FV3/ccpp-physics for the RRTMGP scheme, along with additional cleanup of the RRTMGP UFS regression tests (to harmonize the GP tests to be consistent with their counterparts).

Changes to [NOAA-EMC/fv3atm #619](https://github.com/NOAA-EMC/fv3atm/pull/619)
- Cleanup of RRTMGP Interstitial variables.
- New namelist options for RRTMGP scheme.
- Simplification to RRTMGP SDFs.

Changes to[ufs-communitu/ccpp-physics #34](https://github.com/ufs-community/ccpp-physics/pull/34)
- Major refactoring of RRTMGP interstitials. collapse all rrtmgp_lw(sw) scheme files into rrtmgp_lw(sw)_main schemes. This reduces the number of Interstitial fields needed by the GP scheme and allows us to use the rte-rrtmgp submodule directly, w/o the need for a special branch containing the CCPP hooks.
- For longwave radiation calculation, add "blocking" capability to main loop.
- Fix bug in coupling of RRTMGP shortwave radiation to surface.
- CMake cleanup.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests:  (RRTMGP enabled tests)

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Depends on https://github.com/NOAA-EMC/fv3atm/pull/619
- Depends on https://github.com/ufs-community/ccpp-physics/pull/34

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@dustinswales can you resolve the conflicts?

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA FYI: running this pr on hera now.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1202119880/20230201213011/ufs-weather-model
[BL] Error: Test control_c48 001 failed in run_test failed 
[BL] Error: Test control_stochy 002 failed in run_test failed 
[BL] Error: Test control_ras 003 failed in run_test failed 
[BL] Error: Test control_diag_debug 012 failed in run_test failed 
[BL] Error: Test control_ras_debug 020 failed in run_test failed 
[BL] Error: Test control_stochy_debug 021 failed in run_test failed 
[BL] Error: Test compile_006 failed in run_compile failed 
[BL] Error: Test compile_007 failed in run_compile failed 
[BL] Error: Test compile_008 failed in run_compile failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1202119880/20230201214513/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by jkbk2004** [comment]
@dustinswales @ChunxiZhang-NOAA code crashes. sounds like issue on namelist forrtl: severe (19): invalid reference to variable in NAMELIST input, unit -5, file Internal Formatted NML Read, line -1, position 22

experiment is at /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_18364/control_CubedSphereGrid

**Comment by dustinswales** [comment]
@jkbk2004 Sorry, I found a typo, should be all square now.

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1202119880/20230202062711/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_33663
Test control_c48 001 failed in run_test failed 
Test control_stochy 002 failed in run_test failed 
Test control_ras 003 failed in run_test failed 
Test control_diag_debug 012 failed in run_test failed 
Test control_ras_debug 020 failed in run_test failed 
Test control_stochy_debug 021 failed in run_test failed 
Test compile_006 failed in run_compile failed 
Test compile_007 failed in run_compile failed 
Test compile_008 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
On WCOSS2 I'm getting failures still: For example on control_CubedSphereGrid I get `RRTMGP_PHYS_BLKSZ: unbound variable`. It's similar in other tests. Please run this on Hera with Intel and GNU, and verify this PR passes RT, then we can come back to it. I'd recommend moving onto the next PR.

**Comment by jkbk2004** [comment]
Yes, some more build issues as well.
`Error: Generic subroutine 'random_number' at (1) is not consistent with an intrinsic subroutine interface
/scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/rt-1571-gnu/FV3/ccpp/physics/physics/rrtmgp_lw_main.F90:458:53:

  458 |                    call random_number(rng1D,rng_stat)
      |                                                     1`

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1202119880/20230202064209/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_48301
Test cpld_control_noaero_p8_agrid 010 failed in run_test failed 
Test cpld_control_c48 011 failed in run_test failed 
Test cpld_warmstart_c48 012 failed in run_test failed 
Test control_CubedSphereGrid 013 failed in run_test failed 
Test control_CubedSphereGrid_parallel 014 failed in run_test failed 
Test control_latlon 015 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 016 failed in run_test failed 
Test control_c48 017 failed in run_test failed 
Test control_c192 018 failed in run_test failed 
Test control_c384 019 failed in run_test failed 
Test control_c384gdas 020 failed in run_test failed 
Test control_stochy 021 failed in run_test failed 
Test control_lndp 022 failed in run_test failed 
Test control_iovr4 023 failed in run_test failed 
Test control_iovr5 024 failed in run_test failed 
Test control_p8 025 failed in run_test failed 
Test control_p8_lndp 026 failed in run_test failed 
Test control_p8_rrtmgp 027 failed in run_test failed 
Test merra2_thompson 028 failed in run_test failed 
Test regional_control 029 failed in run_test failed 
Test regional_noquilt 030 failed in run_test failed 
Test regional_netcdf_parallel 031 failed in run_test failed 
Test regional_wofs 032 failed in run_test failed 
Test rap_control 033 failed in run_test failed 
Test regional_spp_sppt_shum_skeb 034 failed in run_test failed 
Test rap_sfcdiff 035 failed in run_test failed 
Test hrrr_control 036 failed in run_test failed 
Test rrfs_v1beta 037 failed in run_test failed 
Test rrfs_v1nssl 038 failed in run_test failed 
Test rrfs_v1nssl_nohailnoccn 039 failed in run_test failed 
Test rrfs_conus13km_hrrr_warm 040 failed in run_test failed 
Test rrfs_smoke_conus13km_hrrr_warm 041 failed in run_test failed 
Test rrfs_conus13km_radar_tten_warm 042 failed in run_test failed 
Test control_ras 045 failed in run_test failed 
Test control_CubedSphereGrid_debug 049 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel_debug 050 failed in run_test failed 
Test control_stochy_debug 051 failed in run_test failed 
Test control_ras_debug 055 failed in run_test failed 
Test control_diag_debug 056 failed in run_test failed 
Test control_atmwav 109 failed in run_test failed 
Test compile_002 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
> On WCOSS2 I'm getting failures still: For example on control_CubedSphereGrid I get `RRTMGP_PHYS_BLKSZ: unbound variable`. It's similar in other tests. Please run this on Hera with Intel and GNU, and verify this PR passes RT, then we can come back to it. I'd recommend moving onto the next PR.

@BrianCurtis-NOAA @jkbk2004 
I fixed a bug in the namelist. I'm re running the tests now.

**Comment by BrianCurtis-NOAA** [comment]
How is this coming along?

**Comment by jkbk2004** [comment]
I checked on cheyenne again yesterkday night. intel progress. But I still see gnu build failures:
`Error: Generic subroutine ‘random_number’ at (1) is not consistent with an intrinsic subroutine interface
/glade/scratch/jongkim/UFS-RT-tests/rt-1571-gnu/FV3/ccpp/physics/physics/rrtmgp_lw_main.F90:458:53:

  458 |                    call random_number(rng1D,rng_stat)
      |                                                     1`

**Comment by dustinswales** [comment]
@jkbk2004 @BrianCurtis-NOAA 
I think I found the problem. There was a change added after this work began that snuck in. (This work was mostly done early 2022)
There were changes to two files, [rrtmgp_lw(sw)_cloud_sampling.F90](https://github.com/ufs-community/ccpp-physics/commit/a35dfda1762ac4dcc37957a15b076104599a4d87), which were removed from this PR. The contents of these modules were merged in rrtmgp_lw(sw)_main.F90, but not the change by @DomHeinzeller back in May 2022.
I'm adding this change in now and will test.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1202119880/20230206181514/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by zach1221** [comment]
@jkbk2004 I'm running the rest of the Jet tests manually.

**Comment by jkbk2004** [comment]
All tests are done. We can start merging process.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dustinswales can you update the fv3 pointer and revert the change in gitmodules here?

**Pull request merged**
