### PR TITLE
Update WW3 for PIO/netCDF restarts

### LINKED ISSUE #1298: Add netcdf restart and history files using PIO (parallel netCDF) for dev/ufs-weather-model
**Is your feature request related to a problem? Please describe.**

WW3 uses binary I/O. This includes the initialization file, the history files and the restart file. The mesh cap branch includes a capability for run-time output of 'gridded mean fields' in netCDF. The current netCDF history capability writes netCDF serially.  Switching to PIO would allow history output in parallel, which allows for potential scalability benefits with large meshes.

The binary restart files from WW3 are difficult to debug. For large unstructured domains, the writing of restart files for UFS is also found to be too slow. Implementing PIO/netCDF restarts would resolve both issues. 

**Describe the solution you'd like**
Implement PIO+PnetCDF capability for both run-time history files as well as restart files for the dev/ufs-weather-model branch.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
### Commit Message:

```
* UFSWM - add PIO settings to WAV attributes in ufs.configure templates
* UFSWM - update ww3_shel.nml to allow for the ice field to be written to the restart file when required (i.e, waves in the slow loop)
* UFSWM - add WW3 restart files to comparison lists
  * WW3 - Add netCDF PIO capability for restarts and run-time history
```

### Priority:

* High - required for GFSv17

### UFSWM:

* Closes  https://github.com/NOAA-EMC/WW3/issues/1298

### Sub component Pull Requests:

* WW3: https://github.com/NOAA-EMC/WW3/pull/1303

### UFSWM Blocking Dependencies:

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

New Baselines are required for all tests which include the WAV component. Answers do not change, but the comparison lists will now include a WW3 netCDF restart file. Note we do not currently compare the WW3 binary restart files for any global coupled test because they don't in general reproduce themselves. 

To verify no answer changes, the WW3 restarts were temporarily removed from comparison lists but with netcdf restarts written and used for restart tests. All baselines passed against the develop-20240909 on hercules at [0b0a048](https://github.com/ufs-community/ufs-weather-model/pull/2445/commits/0b0a048e6266efb647878cacc5d4a908c9c9c1d2)

I've continued to test this PR against the current develop branch using the method of temporarily removing the netCDF WW3 restart files from the comparison lists. This feature branch  has continued to pass as the final changes were made to the WW3 feature branch, most recently using [79cfd42](https://github.com/ufs-community/ufs-weather-model/pull/2445/commits/79cfd42ad656e3b0bf729562fab927efb2012a2b). 

I've also created a baseline using this PR at the above hash and verified against it. In this case, the netCDF restart files are being compared. All baselines pass.

In testing, it was found that Hercules+GNU failed for the subset rearranger, but worked for box. The relevant tests were switched to box only for Hercules+GNU tests. To verify that the problem is a platform (Hercules) issue, GNU tests were then run on Derecho against a self-baseline and all tests passed at [677cfd9](https://github.com/ufs-community/ufs-weather-model/pull/2445/commits/677cfd972f98573e8af0b8a7dc8690f3d004c98a). 

```
rt_cpld_control_nowave_noaero_p8_gnu.log:Test cpld_control_nowave_noaero_p8_gnu PASS
rt_cpld_control_p8_gnu.log:Test cpld_control_p8_gnu PASS
rt_cpld_control_pdlib_p8_gnu.log:Test cpld_control_pdlib_p8_gnu PASS
rt_cpld_debug_p8_gnu.log:Test cpld_debug_p8_gnu PASS
rt_cpld_debug_pdlib_p8_gnu.log:Test cpld_debug_pdlib_p8_gnu PASS
```

On Hercules, a full RT ``test_changes.list`` has been committed. Examining the log files shows test failues are due to missing netCDF WW3 restarts. For these tests, no files were found to 'not compare'.

```
rt_atmwav_control_noaero_p8_intel.log: Comparing ufs.atmw.ww3.r.2021-03-22-64800.nc ............MISSING baseline
rt_cpld_2threads_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_bmark_p8_intel.log: Comparing ufs.cpld.ww3.r.2013-04-01-21600.nc ............MISSING baseline
rt_cpld_control_c192_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-43200.nc ............MISSING baseline
rt_cpld_control_ciceC_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_gfsv17_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_noaero_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_p8.v2.sfc_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_p8_faster_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_p8_mixedmode_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_pdlib_p8_gnu.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_pdlib_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_control_qr_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_debug_gfsv17_intel.log: Comparing ufs.cpld.ww3.r.2021-03-22-32400.nc ............MISSING baseline
rt_cpld_debug_noaero_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-22-32400.nc ............MISSING baseline
rt_cpld_debug_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-22-32400.nc ............MISSING baseline
rt_cpld_debug_pdlib_p8_gnu.log: Comparing ufs.cpld.ww3.r.2021-03-22-32400.nc ............MISSING baseline
rt_cpld_debug_pdlib_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-22-32400.nc ............MISSING baseline
rt_cpld_decomp_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_mpi_gfsv17_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_cpld_mpi_p8_intel.log: Comparing ufs.cpld.ww3.r.2021-03-23-21600.nc ............MISSING baseline
rt_hafs_regional_atm_ocn_wav_intel.log: Comparing ufs.hafs.ww3.r.2019-08-29-21600.nc ............MISSING baseline
rt_hafs_regional_atm_wav_intel.log: Comparing ufs.hafs.ww3.r.2019-08-29-21600.nc ............MISSING baseline
```

### Input data Changes:

* None
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
I found an issue when using ``subset`` by default + GNU + debug. I need to determine what is happening, but Hercules is down for maintenance today.

Edit---just realized downtime is tomorrow, so I will see if I can get this debugged today.

**Comment by jkbk2004** [comment]
Code is crashing on Gaea. Experiment path: /gpfs/f5/epic/scratch/Jong.Kim/RT_RUNDIRS/Jong.Kim/FV3_RT/rt_2431768/atmwav_control_noaero_p8_intel
```
+ srun --label -n 256 ./fv3.exe
151: forrtl: severe (174): SIGSEGV, segmentation fault occurred
151: Image              PC                Routine            Line        Source
151: libpthread-2.31.s  00007FDC23EAD910  Unknown               Unknown  Unknown
151: libmpi_intel.so.1  00007FDC22E141C2  Unknown               Unknown  Unknown
srun: error: c5n1298: task 151: Exited with exit code 174
```
develop branch runs ok on gaea.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I can't see your run directory on Gaea. I'll do my own test.

**Comment by DeniseWorthen** [comment]
@jkbk2004 Did all other tests run to completion on Gaea?

**Comment by jkbk2004** [comment]
> @jkbk2004 Did all other tests run to completion on Gaea?

@DeniseWorthen cpld_debug_pdlib_p8_intel fails on gaea as well. pretty much same error messages. Runs on all other machines are ok.

**Comment by DeniseWorthen** [comment]
Hm, that is very odd, because I tested extensively on Gaea in debug for the unstructured mesh. But all my testing was prior to the upgrade. It is failing at a call to piosync in the atmwav test, which makes me think it might be a platform issue. I'm also seeing a lot of sticky behaviour w/ file system (worse than normal for Gaea) since the upgrade. The atmw test will run with ``box``, I'll try the same fix for the pdlib debug.

**Comment by DeniseWorthen** [comment]
I've also gotten the atmwav test to run w/ subset but w/ increased resources. We're not using everything we're requesting right now (the job_card requests 256 and we're only using 180). Bumping the ww3 resources a bit resolves the issue w/ this test. Still debugging the debug test---which is running close to it's wall clock anyway.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I've made platform specific modifications to the two tests on Gaea and run successfully.

**Comment by jkbk2004** [comment]
I continue to see more failures. All libpthread-2.31.s error. Looks like some impact on none wave hafs cases. It may need to adjust with general resource increase thru the change on gaea TPN.  Note that develop branch runs ok.
```
hafs_regional_1nest_atm_intel failed in run_test
hafs_regional_atm_ocn_wav_intel failed in run_test
hafs_regional_storm_following_1nest_atm_intel failed in run_test
hafs_regional_storm_following_1nest_atm_ocn_wav_inline_intel failed in run_test
hafs_regional_storm_following_1nest_atm_ocn_wav_intel failed in run_test
hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel failed in run_test
hafs_regional_telescopic_2nests_atm_intel failed in run_test
atmwav_control_noaero_p8_intel failed in run_test
cpld_control_pdlib_p8_intel failed in run_test
cpld_debug_noaero_p8_intel failed in run_test
cpld_debug_p8_intel failed in run_test
cpld_debug_pdlib_p8_intel failed in run_test
cpld_control_pdlib_p8_intel failed in run_test
cpld_debug_noaero_p8_intel failed in run_test
cpld_debug_p8_intel failed in run_test
```

**Comment by DeniseWorthen** [comment]
@jkbk2004 As I said earlier, I can't see into your Gaea run directories. I will need to repeat the tests on Gaea.

**Comment by DeniseWorthen** [comment]
@jkbk2004 If you have another PR ready, please move on w/ it and give me time to debug.

**Comment by DeniseWorthen** [comment]
@jkbk2004 Also, are these failures Gaea specific, or are you seeing similar failures elsewhere?

**Comment by jkbk2004** [comment]
> @jkbk2004 Also, are these failures Gaea specific, or are you seeing similar failures elsewhere?

@DeniseWorthen Issue is gaea specific. I think the issue might be resolved with resource increase like TPN=84 or 96. I think gaea default TPN=128.

**Comment by DeniseWorthen** [comment]
@jkbk2004 The test failures that do not include waves do not make any sense. There should not be any impact on a non-wave containing test. These three tests are not different than the develop branch. 

```
hafs_regional_1nest_atm_intel failed in run_test
hafs_regional_storm_following_1nest_atm_intel failed in run_test
hafs_regional_telescopic_2nests_atm_intel failed in run_test
```

**Comment by DeniseWorthen** [comment]
@jkbk2004 I've reset the default rearranger for WW3 to ``box`` for all cases. I've run all non-standalone baselines on Gaea w/ this change and all tests run to completion with the only difference w/ current baselines being the addition of the WW3 netcdf restart files. I believe this PR is now ready.

**Comment by DeniseWorthen** [comment]
@jkbk2004 What is the scheduled commit date for this PR?

**Comment by jkbk2004** [comment]
> @jkbk2004 What is the scheduled commit date for this PR?

@DeniseWorthen wcoss2 is on maintenance this week. so we decided to let PRs with no baseline change go first. 11/11 is veterans day. We can schedule this PR on 11/12.

**Comment by jkbk2004** [comment]
@DeniseWorthen can you sync up branch? we can start working on this pr.

**Comment by FernandoAndrade-NOAA** [comment]
Leaving a note that Orion is consistently failing `hafs_regional_atm_ocn_wav_intel` during baseline creation runtime due to time limit, I'm rerunning with an increased time limit. Gaea RTs showed changes in intelllvm tests as well. They've been regenerated and are rerunning. Jet is still running.

**Comment by DeniseWorthen** [comment]
@FernandoAndrade-NOAA Can you confirm that the Gaea LLVM RTs failed because the WW3 netcdf restarts would have been missing from the baseline?

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA Can you confirm that the Gaea LLVM RTs failed because the WW3 netcdf restarts would have been missing from the baseline?

Correct, the errors in the logs were due to missing baselines.

**Comment by jkbk2004** [comment]
Baseline develop-20241112 was created ok on Derecho: /glade/derecho/scratch/epicufsrt/ufs-weather-model/RT/NEMSfv3gfs/develop-20241112. Due to ecflow and rocoto issue on the machine, we will skip Derecho RT log.

**Comment by jkbk2004** [comment]
anyway, regarding derecho ecflow issue:
```
Error: request( --begin=regtest_14784 ) failed!  Server reply: BeginCmd::doHandleRequest:  Begin failed as suite 'regtest_14784' is not loaded.
```
in contact with sys admin. Rocoto issue on derecho: rocotorun and rocotstat iteration gets stuck with long list of jobs.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, we should be all set then. I'll leave a note in the subcomponent PR.

**Review by jkbk2004 — APPROVED** [review]

**Review by NickSzapiro-NOAA — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Pull request merged**
