### PR TITLE
update cubed sphere gitmodules for perturbation/increments for cold starts

### LINKED ISSUE #339: FV3 is not able to apply DA increment when cold staring
Currently,  the ability to read in an analysis increment is inside the warm_start section of the code.  So if a user tried to apply an increment to the initial condition, the model runs, but nothing is applied.  
 The solution is to move the call to read_da_inc outside the if external_ic/restart logic.

### PR DESCRIPTION
**Pull request by pjpegion**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:

Currently the model can only read in an increment file if initializing with a restart file. This functionality is also used to read in ensemble perturbations, and should also work for a external initial condition. The solution is to move the call to read_da_inc outside the if external_ic/restart logic.

There should be no changes to any regression tests.

### Commit Message:

```
  * FV3 - 
    * atmos_cubed_sphere - 
```

### Priority:

* High: This is needed for the SFS baseline

### UFSWM:

- fixes NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/339]
### Sub component Pull Requests:

- FV3: NOAA-EMC/fv3atm/pull/832
- atmos_cubed_sphere:[NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/340]

### UFSWM Blocking Dependencies:
* Blocked by
None

---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@pjpegion note that we are considering to combine this pr to #2259.

**Comment by pjpegion** [comment]
great, thanks

**Comment by jiandewang** [comment]
@jkbk2004 is it OK to also combine #2275 here ? It is a super simple one with no BL change.

**Comment by jkbk2004** [comment]
@pjpegion can you sync up branches? @jiandewang yes, we can combine this pr and #2275 to #2259

**Review by climbfuji — COMMENTED** [review]
I looked at the changes, and I don't see a problem. But I am not qualified to approve the PR since I know nothing about these changes.

**Comment by BrianCurtis-NOAA** [comment]
Hey @jkbk2004 please describe the debugging you did on Gaea to find out why you had a failure in one of the compiles where there was no similar failure on other machines. This leans towards an issue with Gaea, and not necessarily this PR.

**Comment by DeniseWorthen** [comment]
I was just looking back at the wcoss2/pio thread (#2232) and I saw the same same sfccycle message reported [here](https://github.com/ufs-community/ufs-weather-model/issues/2232#issuecomment-2090847167). What is the common thread between these two cases, both showing the same sfccyle error?

edit---the wcoss2 is, afaik, meant to be equivalent to the SS 1.6 libraries.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA I will double check but I was seeing build issue on gaea
```
/gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
      CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
-----------^
compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
cycle.F90 (code 1)
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
```

**Comment by DusanJovic-NOAA** [comment]
I just ran the full regression test on Gaea using the branch from this PR and it passed successfully.  See the logs here:

/gpfs/f5/nggps_emc/scratch/Dusan.Jovic/ufs/cs_perts/ufs-weather-model/tests

**Review by aerorahul — DISMISSED** [review]
I have looked at the changes in this PR as well as changes in the dependency repos for FV3ATM and atmos_cubed_sphere.
This is a required functionality for replay with coldstart initial conditions for the ensemble that need to read a perturbation from another source.

I have not tested the changes, but this feature is being developed in the global-workflow.  See associated PR https://github.com/NOAA-EMC/global-workflow/pull/2638

**Comment by jkbk2004** [comment]
> I have looked at the changes in this PR as well as changes in the dependency repos for FV3ATM and atmos_cubed_sphere. This is a required functionality for replay with coldstart initial conditions for the ensemble that need to read a perturbation from another source.
> 
> I have not tested the changes, but this feature is being developed in the global-workflow. See associated PR [NOAA-EMC/global-workflow#2638](https://github.com/NOAA-EMC/global-workflow/pull/2638)

@aerorahul Thanks for the review!

**Comment by jkbk2004** [comment]
@pjpegion can you sync up branches? I don't have permission to your cubed sphere branch. We like to combine this pr to #2301.

**Pull request closed without merging**
