### PR TITLE
Rename CCPP branches from master to main, several small changes in ccpp-physics

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR and dependencies below change the name of the ccpp-framework and ccpp-physics branches from "main" to "master" and, in addition, include a few small updates and bugfixes in ccpp-framework and ccpp-physics.

Also included: bug fixes for wcoss_dell_p3 modulefiles to correctly load cmake (from @DusanJovic-NOAA)

**Update 2021/05/14**

This PR now contains the following two PRs:
- https://github.com/ufs-community/ufs-weather-model/pull/570 Change CI triggering method from @MinsukJi-NOAA; no update to input data, no changes to regression test results
- https://github.com/ufs-community/ufs-weather-model/pull/574, Add a new cdeps test from @binli2337; additional files required that can be added to existing input data directory, but no changes to regression test results

**Update 2021/05/17**

The changes in file `GFS_suite_interstitial.F90` (use assumed-size array declarations) in ccpp-physics PR https://github.com/NCAR/ccpp-physics/pull/652/files change the regression test baseline for the following three tests with Intel in PROD mode:
```
cpld_bmarkfrac_v16
cpld_bmarkfrac_wave
cpld_bmarkfrac_wave_v16
```
Note that only one file is different, the model run itself completes w/o changes to the final checksums (this is the same for all three tests):
```
Dom.Heinzeller@hfe06:/scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-emc-develop-20210512-various-ccpp-changes/intel/tests [intel|gsd-hpcs]> cat log_hera.intel/rt_025_cpld_bmarkfrac_wave.log
baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20210513/INTEL/cpld_bmarkfrac_wave
working dir  = /scratch1/NCEPDEV/stmp2/Dom.Heinzeller/FV3_RT/rt_265707/cpld_bmarkfrac_wave
Checking test 025 cpld_bmarkfrac_wave results ....
 Comparing phyf024.tile1.nc .........OK
 Comparing phyf024.tile2.nc .........OK
 Comparing phyf024.tile3.nc .........OK
 Comparing phyf024.tile4.nc .........OK
 Comparing phyf024.tile5.nc .........OK
 Comparing phyf024.tile6.nc .........OK
 Comparing dynf024.tile1.nc .........OK
 Comparing dynf024.tile2.nc .........OK
 Comparing dynf024.tile3.nc .........OK
 Comparing dynf024.tile4.nc .........OK
 Comparing dynf024.tile5.nc .........OK
 Comparing dynf024.tile6.nc .........OK
 Comparing 20130402.000000.out_grd.gwes_30m .........OK
 Comparing 20130402.000000.out_pnt.points .........OK
 Comparing 20130402.000000.restart.gwes_30m .........OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_core.res.tile2.nc .........OK
 Comparing RESTART/fv_core.res.tile3.nc .........OK
 Comparing RESTART/fv_core.res.tile4.nc .........OK
 Comparing RESTART/fv_core.res.tile5.nc .........OK
 Comparing RESTART/fv_core.res.tile6.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile2.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile3.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile4.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile5.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile6.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc .........OK
 Comparing RESTART/fv_tracer.res.tile2.nc .........OK
 Comparing RESTART/fv_tracer.res.tile3.nc .........OK
 Comparing RESTART/fv_tracer.res.tile4.nc .........OK
 Comparing RESTART/fv_tracer.res.tile5.nc .........OK
 Comparing RESTART/fv_tracer.res.tile6.nc .........OK
 Comparing RESTART/phy_data.tile1.nc .........OK
 Comparing RESTART/phy_data.tile2.nc .........OK
 Comparing RESTART/phy_data.tile3.nc .........OK
 Comparing RESTART/phy_data.tile4.nc .........OK
 Comparing RESTART/phy_data.tile5.nc .........OK
 Comparing RESTART/phy_data.tile6.nc .........OK
 Comparing RESTART/sfc_data.tile1.nc .........OK
 Comparing RESTART/sfc_data.tile2.nc .........OK
 Comparing RESTART/sfc_data.tile3.nc .........OK
 Comparing RESTART/sfc_data.tile4.nc .........OK
 Comparing RESTART/sfc_data.tile5.nc .........OK
 Comparing RESTART/sfc_data.tile6.nc .........OK
 Comparing RESTART/MOM.res.nc .........OK
 Comparing RESTART/MOM.res_1.nc .........OK
 Comparing RESTART/MOM.res_2.nc .........OK
 Comparing RESTART/MOM.res_3.nc .........OK
 Comparing RESTART/iced.2013-04-02-00000.nc .........OK
 Comparing RESTART/ufs.cpld.cpl.r.2013-04-02-00000.nc ............ALT CHECK......NOT OK
  0: The total amount of wall time                        = 917.045422
Test 025 cpld_bmarkfrac_wave FAIL
```
This difference is acceptable and due to the Intel compiler optimization. The new regression test baseline date is 20210517.

### Issue(s) addressed

See associated PRs listed below.

## Testing

Regression tests will be run on all tier-1 platforms prior to committing the chaanges.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

https://github.com/NCAR/ccpp-framework/pull/372
https://github.com/NCAR/ccpp-physics/pull/658
https://github.com/NOAA-EMC/fv3atm/pull/300
https://github.com/ufs-community/ufs-weather-model/pull/572

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@climbfuji, #570 has been updated to the latest develop. However you want to incorporate it into your PR... Thanks!

**Comment by MinsukJi-NOAA** [comment]
CI test needs to be skipped because of the CI-related changes in this PR; simply do not add the 'run-ci' label.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/643540985/20210514170008/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_16493
Test fv3_control_debug 017 failed in run_test failed 
Test fv3_gfdlmp 001 failed in run_test failed 
Test fv3_gfs_v16_flake 005 failed in run_test failed 
Test fv3_gfsv16_ugwpv1_warmstart 015 failed in run_test failed 
Test fv3_gfsv16_ugwpv1 014 failed in run_test failed 
Test fv3_gsd_debug 021 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 020 failed in run_test failed 
Test fv3_thompson_no_aero_debug 023 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 019 failed in run_test failed 
Test fv3_thompson_debug 022 failed in run_test failed 
Test fv3_gsd 007 failed in run_test failed 
Test fv3_rrfs_v1beta 011 failed in run_test failed 
Test fv3_thompson_no_aero 009 failed in run_test failed 
Test fv3_thompson 008 failed in run_test failed 
Test fv3_rrfs_v1alpha 010 failed in run_test failed 
Test fv3_gfs_v16_stochy 004 failed in run_test failed 
Test fv3_gfs_v16_ras 016 failed in run_test failed 
Test fv3_gfs_v16_RRTMGP 006 failed in run_test failed 
Test fv3_gfs_v16 002 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/643540985/20210517164511/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_47450
Test fv3_wrtGauss_netcdf_parallel 023 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by climbfuji** [comment]
> Machine: gaea
> Compiler: intel
> Job: BL
> Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/643540985/20210517164511/ufs-weather-model
> Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_47450
> Test fv3_wrtGauss_netcdf_parallel 023 failed in run_test failed
> Please make changes and add the following label back:
> gaea-intel-BL

This failure was due to a bad node. I reran the failed baseline creation job (only one), synced the combined data to the final baseline location, and added the gaea-intel-rt label. It's crunching numbers now.

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/643540985/20210517204510/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_12293
Test fv3_wrtGauss_netcdf_parallel 037 failed in check_result failed 
Test fv3_wrtGauss_netcdf_parallel 037 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/643540985/20210517160020/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_222287
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/643540985/20210517171515/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_59387
Test cpld_bmark_wave 024 failed failed 
Test cpld_bmark_wave 024 failed in run_test failed 
Test cpld_bmarkfrac 019 failed failed 
Test cpld_bmarkfrac 019 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/643540985/20210517224508/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_36695
Test fv3_wrtGauss_netcdf_parallel 037 failed in check_result failed 
Test fv3_wrtGauss_netcdf_parallel 037 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by climbfuji** [comment]
> Machine: orion
> Compiler: intel
> Job: BL
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/643540985/20210517160020/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_222287
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/643540985/20210517171515/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_59387
> Test cpld_bmark_wave 024 failed failed
> Test cpld_bmark_wave 024 failed in run_test failed
> Test cpld_bmarkfrac 019 failed failed
> Test cpld_bmarkfrac 019 failed in run_test failed
> Please make changes and add the following label back:
> orion-intel-BL

These two tests failed because of the same error in the "verify" phase (creating baselines worked fine).
```
312:
312: WARNING from PE     0: Unused line in INPUT/MOM_input : SURFBAND_WAVENUMBERS = 0.04, 0.11, 0.3305
312:
119: forrtl: severe (174): SIGSEGV, segmentation fault occurred
119: Image              PC                Routine            Line        Source
119: fv3.exe            0000000004CCC669  Unknown               Unknown  Unknown
119: libpthread-2.17.s  00002AE2B84995D0  Unknown               Unknown  Unknown
119: fv3.exe            0000000004D9B5A1  Unknown               Unknown  Unknown
119: fv3.exe            0000000000C34F5A  _ZNSt6vectorIiSaI         372  stl_algobase.h
119: fv3.exe            0000000000C2ACEB  _ZN5ESMCI2DD25set        8502  ESMCI_Array.C
119: fv3.exe            0000000000C22247  _ZN5ESMCI27sparse        2010  sparseMatMulStoreLinSeqVect.h
119: fv3.exe            0000000000C1ED9F  _ZN5ESMCI5Array18        9188  ESMCI_Array.C
```
I believe we had this in the past. I am going to run the verify step manually on orion over night.

**Comment by climbfuji** [comment]
> Machine: gaea
> Compiler: intel
> Job: RT
> Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/643540985/20210517224508/ufs-weather-model
> Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_36695
> Test fv3_wrtGauss_netcdf_parallel 037 failed in check_result failed
> Test fv3_wrtGauss_netcdf_parallel 037 failed in run_test failed
> Please make changes and add the following label back:
> gaea-intel-RT

This was my stupid mistake, running verify step again.

**Comment by DeniseWorthen** [comment]
On Dell, I had two errors creating baselines: 
1.   disk quota error (fv3_rrfs_v1alpha)
2.  datm_cdeps_multiple_files_cfsr failed with error `[0] Abort with message No such file or directory in file /usrx/local/nceplibs/dev/hpc-stack/src/hpc-stack/pkg/pio 2.5.2/src/clib/pioc_support.c at line 2747`

I was able to generate the fv3_rrfs_v1apha baseline after deleting the oldest baseline (develop-20210301). The datm failed the second time with the same error.

Run directory: /gpfs/dell2/ptmp/Denise.Worthen/FV3_RT/rt_25766/datm_cdeps_multiple_files_cfsr
Build directory: /gpfs/dell2/emc/modeling/noscrub/Denise.Worthen/ufs-weather-model

Other than this datm test, the baseline is ready for verify on dell-p3.

**Comment by binli2337** [comment]
@DeniseWorthen  A few new input files needed by this new cdeps test were not on this wcoss-p3. I have copied the new input files to the input-data-20210518 directory. Please try this test again. Thanks!

**Comment by climbfuji** [comment]
Finally, all tests passed. As per @MinsukJi-NOAA 's instruction, we need to skip the CI tests for this commit. I will merge ccpp-framework and ccpp-physics now.

**Review by junwang-noaa — APPROVED** [review]
Code looks good to me. Need to change the submodules back to official repo.

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
We need to revert the cdeps gitmodule.

**Comment by climbfuji** [comment]
> We need to revert the cdeps gitmodule.

I am confused, this change is from @binli2337 and has been used for all tests?

**Comment by DeniseWorthen** [comment]
Yes, you merged it to this PR branch at 2bf1c9e, right?

**Comment by climbfuji** [comment]
> Yes, you merged it to this PR branch at [2bf1c9e](https://github.com/ufs-community/ufs-weather-model/commit/2bf1c9ecec8808a230e65026a636e1fa1cf54fd0), right?

I pulled in https://github.com/ufs-community/ufs-weather-model/pull/574 without any further changes to CDEPS.

**Comment by DeniseWorthen** [comment]
The gitmodules in this PR still points to a @binli2337 branch of CDEPS. That was merged to develop I believe.

**Comment by climbfuji** [comment]
> The gitmodules in this PR still points to a @binli2337 branch of CDEPS. That was merged to develop I believe.

Got it. Let me try to update the submodule pointer, hopefully the code is still the same.

**Comment by climbfuji** [comment]
> > The gitmodules in this PR still points to a @binli2337 branch of CDEPS. That was merged to develop I believe.
> 
> Got it. Let me try to update the submodule pointer, hopefully the code is still the same.

This should be good now, please check. Code is identical before/after update of submodule pointer.

**Review by DeniseWorthen — APPROVED** [review]
Looks good to me.

**Review by binli2337 — APPROVED** [review]
Updated files look good.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
