### PR TITLE
fix type mis-matches in nst water property module

### LINKED ISSUE #1980: fixing the missing type-kind specifications in one of the nst modules causes two regression tests to fail comparison
## Description

Both ``sw_ps_9bw`` and ``sw_ps_9b_aw`` within ``ccpp/physics/physics/module_nst_water_prop.f90`` lack a kind definition for the input arguments. See https://github.com/ufs-community/ccpp-physics/issues/125

## To Reproduce 

Add ``kind=kind_phys`` to the input arguments for the two modules above. Running the UWM RTs will fail for two tests only. Both tests fail in comparing the wave restart file.

```
[Hera: hfe03] /scratch1/NCEPDEV/nems/Denise.Worthen/WORK/ufs_dev/tests: grep NOT logs/RegressionTests_hera.log
4862: Comparing ufs.hafs.ww3.r.2019-08-29-21600 .........NOT OK
5793: Comparing ufs.atmw.ww3.r.2021-03-22-64800 .........NOT OK
```

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13338853/RegressionTests_hera.log)
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13467994/RegressionTests_hera.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Updates one of the nst modules in CCPP to fix missing type-kind specifications and other variable type mis-matches. 

### Associated UFSWM Issue to close

- fixes #1980 

Note original testing showed this was a non-B4B change for two wave model restarts, but re-testing this change shows it to be B4B for all cases. 

Tests were re-run at  6b49fd578 and all tests passed.

Tests were re-run at 24e92073 after NST modules were modified to remove column 6 continuations and other changes and all tests passed.

### Subcomponent Pull Requests

- https://github.com/ufs-community/ccpp-physics/pull/126
- https://github.com/NOAA-EMC/fv3atm/pull/719
### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Are we using "incomplete" when the only thing missing is reviews? Maybe we should have a different label for that case. To me, "incomplete" are issues that the maker of the PR should remedy (missing logs, dependent PRs and issues not listed etc). It's really up to CMs to review and approve the code and often the developer has no real control over that. Many developers don't even have the ability to assign a reviewer, for example.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA As it turns out, I'm finding additional type-mismatches now that I've gone back and attempted to compile the nst modules from w/in CMEPS. So I'll need to make additional changes in my ccpp/physics PR.

**Comment by zach1221** [comment]
@DeniseWorthen I did some additional testing on Gaea C5 PR #1784 and everything passed. Can you combine the code changes from that PR into this one for us, please?

**Comment by zach1221** [comment]
Ok done with testing. Let's begin the merge process, beginning with ccpp-physics [#126 ](https://github.com/ufs-community/ccpp-physics/pull/126).

**Comment by zach1221** [comment]
@DeniseWorthen fv3atm is merged . New hash: https://github.com/NOAA-EMC/fv3atm/commit/7eec3ceb4062ad761af2b6f6a9e133f1b948b3e1

**Review by jkbk2004 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
