### PR TITLE
Adding a regression test "cpld_bmark_wave_frac"

### PR DESCRIPTION
**Pull request by ShanSunNOAA**
This is a benchmark regression test for C384L64, based on "cpld_bmark_wave". It uses a different set of input data, which needs to be copied over from /scratch2/BMC/gsd-fv3-dev/FV3-MOM6-CICE5/input-data-20201201_frac/FV3_input_frac/ to the default path, before the test is run. 

This refers to Issue #285.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
After I get my bulk flux PR merged I was going to be opening a PR for updating the restart regression tests (Issue #316). I think it makes sense to combine this PR with the upcoming restart PRs. What do you think?

**Comment by ShanSunNOAA** [comment]
I agree. The components are here to grep.

**Comment by ShanSunNOAA** [comment]
This PR is replaced by #326, where the upper level codes are identical. The difference is the MOM6 submodule is uploaded correctly in #326.

**Comment by DusanJovic-NOAA** [comment]
If this is replaced by #326 please close this PR.

**Comment by ShanSunNOAA** [comment]
Just did. Sorry that I was unable to correct a submodule successfully in
#322, and decided to replace it with #326.

Yes, Denise, let us merge regression tests related into one PR.

Shan

**Pull request closed without merging**
