### PR TITLE
Add a new cdeps test

### LINKED ISSUE #568: Add a new cdeps test that uses multiple data stream files
## Description

For the current cdeps regression tests, only one input data stream file is used in each of the experiments. A new test needs to be added to test the capability of CDEPS to use multiple data stream files in a single experiment.

## Solution

Add a new test "datm_cdeps_multiple_files_cfsr".

## Related to
https://github.com/NOAA-EMC/CDEPS/issues/27

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [ ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Add a new cdeps regression test that uses multiple data stream files.

The following additional input files need to be added to the DATM_CDEPS/CFSR/201110 directory:
cfsr.2011100100.nc
cfsr.2011100106.nc
cfsr.2011100112.nc
cfsr.2011100118.nc
cfsr.2011100200.nc

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #568 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/CDEPS/pull/28

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
@binli2337 is this PR finalized so that I can pull it into #572 ?

**Comment by binli2337** [comment]
@climbfuji Yes, this PR is finalized.

**Comment by DeniseWorthen** [comment]
@binli2337 Where is the data staged that needs to be added? Have you added it to Hera's 0518 input-data yet?

**Comment by binli2337** [comment]
@DeniseWorthen New input files have been added to input-data-20210518/DATM_CDEPS/CFSR on Hera, Orion, Jet and Gaea.

**Comment by climbfuji** [comment]
> @DeniseWorthen New input files have been added to input-data-20210518/DATM_CDEPS/CFSR on Hera, Orion, Jet and Gaea.

I'll copy them to cheyenne and s3

**Comment by climbfuji** [comment]
This PR has been pulled into https://github.com/ufs-community/ufs-weather-model/pull/572 and will be merged as part of it.

**Comment by binli2337** [comment]
@climbfuji New input files have been copied to wcoss-p3.

**Comment by binli2337** [comment]
This PR has been combined with other PR.

**Pull request closed without merging**
