### PR TITLE
CCPP/physics v6 documentation updates + empty CCPP phase subroutine cleanup

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

-  [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This pull request only updated the ccpp-physics submodule pointer in accordance with https://github.com/NCAR/ccpp-physics/pull/944 which updates the main ccpp-physics branch with documentation updates from the version 6 release and cleans up unnecessary empty CCPP phase subroutines.

### Issue(s) addressed

fixes https://github.com/NCAR/ccpp-physics/issues/949

## Testing

- [X] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/944
https://github.com/NOAA-EMC/fv3atm/pull/566

### CODE REVIEW

**Comment by grantfirl** [comment]
@jkbk2004 A couple of weeks ago, you mentioned something about combining this with other documentation updates. Has there been any movement on the other documentation updates? I'd like not to see https://github.com/NCAR/ccpp-physics/pull/944 get too old and out-of-date. Plus, I've noticed a small bug that needs to be fixed for the SCM introduced in a recently-merged ccpp-physics PR that needs to be fixed and I'm trying to decide whether to add on to #944, do it separately, or add it to other work.

**Comment by jkbk2004** [comment]
@grantfirl #1354 contains small updates on sphinx style files. We can merge w/o testing. For #1355, we can schedule to merge in early next week (Monday or Tuesday). If you want to add a SCM fix, I think it will be good to separate out. New PR list is not tight coming weeks. I don't see any problem to work on #1355 from Monday. Let me know if this scheduling works.

**Comment by jkbk2004** [comment]
@grantfirl #1358 was just merged in. We can start working on this PR. With one quick sanity test run, I think we can ask reviewers' approvals.

**Comment by jkbk2004** [comment]
@grantfirl can you sync up v6_to_main_plus_empty_sub branch to develop? We merged in mom6 update PR late Friday afternoon. With a quick build check, I think we can move on to merge this PR.

**Comment by grantfirl** [comment]
> @grantfirl can you sync up v6_to_main_plus_empty_sub branch to develop? We merged in mom6 update PR late Friday afternoon. With a quick build check, I think we can move on to merge this PR.

@jkbk2004 OK, finished merging in the latest develop branch.

**Comment by jkbk2004** [comment]
@grantfirl PR is ok with cheyenne.intel. But I am double checking with cheyenne.gnu. I think I may confirm with hera/intel/gnu as well.

**Comment by jkbk2004** [comment]
I tested the PR on Cheyenne intel/gnu as well. No impact on BL. We can start merging in the PR.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
> I tested the PR on Cheyenne intel/gnu as well. No impact on BL. We can start merging in the PR.

OK, I'm going to start the merge process in ccpp-physics.

**Comment by grantfirl** [comment]
@jkbk2004 https://github.com/NCAR/ccpp-physics/pull/944 is merged. https://github.com/NOAA-EMC/fv3atm/pull/566 is ready for review/merge.

**Comment by jkbk2004** [comment]
@grantfirl merged [https://github.com/NOAA-EMC/fv3atm/pull/566](https://github.com/NOAA-EMC/fv3atm/pull/566) Can you revert gitmodule here and update fv3 submodule pointer?

**Comment by grantfirl** [comment]
> @grantfirl merged [NOAA-EMC/fv3atm#566](https://github.com/NOAA-EMC/fv3atm/pull/566) Can you revert gitmodule here and update fv3 submodule pointer?

@jkbk2004 Done.

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
