### PR TITLE
UFS-SRW v3.0.0 SciDoc updates

### LINKED ISSUE #96: Update scientific documentation for the UFS-SRW App v3.0.0 release
## Description
Scientific documentation is typically kept up-to-date at least on release schedules. 

## Solution
Update documentation to reflect scientific changes in supported suites, including any new schemes.

### PR DESCRIPTION
**Pull request by grantfirl**
## PR Author Checklist:

- [X] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [ ] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: I ran full RT on Hera and a couple of tests initially failed but passed with a second run, so all tests pass. I can attach partial success log and 2 repeated test logs if necessary.
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [ ] I have filled out all sections of the template.

## Description
This PR updates the scientific documentation in the CCPP physics for UFS-SRW App v3.0.0 release. This should be code comments and text files only and should not have any effect on model results.

### Associated UFSWM Issue to close
Closes https://github.com/ufs-community/ccpp-physics/issues/96

### Subcomponent Pull Requests
https://github.com/NOAA-EMC/fv3atm/pull/685
https://github.com/ufs-community/ccpp-physics/pull/91

### Blocking Dependencies
Depends on subcomponent PRs:
https://github.com/NOAA-EMC/fv3atm/pull/685
https://github.com/ufs-community/ccpp-physics/pull/91

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [X] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hi @grantfirl, I see you left a comment in the template that you had Hera RT running. Could you attach the Hera log results here?

**Comment by jkbk2004** [comment]
It's just doc update. I don't think we need full regression test. @grantfirl do you think doc update files can be combined to Sam's PR https://github.com/ufs-community/ccpp-physics/pull/92 ? We will start working on Sam's #1844 today.

**Comment by grantfirl** [comment]
> It's just doc update. I don't think we need full regression test. @grantfirl do you think doc update files can be combined to Sam's PR [ufs-community/ccpp-physics#92](https://github.com/ufs-community/ccpp-physics/pull/92) ? We will start working on Sam's #1844 today.

Yes, I think that it's fine to combine. @SamuelTrahanNOAA Do you mind pulling [mkavulich:srw300_scidoc_noimages](https://github.com/mkavulich/ccpp-physics/tree/srw300_scidoc_noimages) into your [SamuelTrahanNOAA:tanya-fix-20230724](https://github.com/SamuelTrahanNOAA/ccpp-physics/tree/tanya-fix-20230724) branch and pushing for testing purposes?

@FernandoAndrade-NOAA Thanks for the reminder. I just checked the log file on the test that I ran on Hera and it actually had 2 failures (see below). Was there a known issue with these tests or with baselines last week? If not, I can rerun these tests to verify.

FAILED TESTS:
049 merra2_thompson_intel failed in check_result
merra2_thompson_intel 049 failed in run_test
180 atmaero_control_p8_rad_micro_intel failed in check_result
atmaero_control_p8_rad_micro_intel 180 failed in run_test

**Comment by grantfirl** [comment]
I've updated all of the branches from ufs-weather-model down (locally -- haven't pushed anything yet) and am rerunning those couple tests on Hera to see if it was a glitch. This is more for my own curiosity than anything. Looking at the changes in ccpp-physics there is no way it should affect anything...

**Comment by zach1221** [comment]
> I've updated all of the branches from ufs-weather-model down (locally -- haven't pushed anything yet) and am rerunning those couple tests on Hera to see if it was a glitch. This is more for my own curiosity than anything. Looking at the changes in ccpp-physics there is no way it should affect anything...

@grantfirl there's no issues with the below tests that I'm aware of on Hera. Please let us know how your re-testing goes.
049 merra2_thompson_intel failed in check_result
merra2_thompson_intel 049 failed in run_test
180 atmaero_control_p8_rad_micro_intel failed in check_result
atmaero_control_p8_rad_micro_intel 180 failed in run_test

**Comment by FernandoAndrade-NOAA** [comment]
> > It's just doc update. I don't think we need full regression test. @grantfirl do you think doc update files can be combined to Sam's PR [ufs-community/ccpp-physics#92](https://github.com/ufs-community/ccpp-physics/pull/92) ? We will start working on Sam's #1844 today.
> 
> Yes, I think that it's fine to combine. @SamuelTrahanNOAA Do you mind pulling [mkavulich:srw300_scidoc_noimages](https://github.com/mkavulich/ccpp-physics/tree/srw300_scidoc_noimages) into your [SamuelTrahanNOAA:tanya-fix-20230724](https://github.com/SamuelTrahanNOAA/ccpp-physics/tree/tanya-fix-20230724) branch and pushing for testing purposes?


I've asked the CCPP sub pr for additional assigned reviewer approval and to sync up as well since it seems it's behind compared to the ufs/dev branch. It looks like Sam's will need syncing as well.

**Comment by grantfirl** [comment]
> > I've updated all of the branches from ufs-weather-model down (locally -- haven't pushed anything yet) and am rerunning those couple tests on Hera to see if it was a glitch. This is more for my own curiosity than anything. Looking at the changes in ccpp-physics there is no way it should affect anything...
> 
> @grantfirl there's no issues with the below tests that I'm aware of on Hera. Please let us know how your re-testing goes. 049 merra2_thompson_intel failed in check_result merra2_thompson_intel 049 failed in run_test 180 atmaero_control_p8_rad_micro_intel failed in check_result atmaero_control_p8_rad_micro_intel 180 failed in run_test

With all updated code, the tests pass on Hera just fine. I'm guessing it was a full disc space allocation issue since my first retest failed compilation due to lack of space.

**Comment by FernandoAndrade-NOAA** [comment]
Sounds good, thanks for syncing up the CCPP sub pr! Please go ahead and sync up for the other components / resolve conflicts in this PR just to avoid any potential issues with combining

**Comment by zach1221** [comment]
Closing this PR as the combined PR [#1844](https://github.com/ufs-community/ufs-weather-model/pull/1844) has been merged.

**Pull request closed without merging**
