### PR TITLE
Bring AutoRT updates into develop

### LINKED ISSUE #752: Bring AutoRT updates from BrianCurtis-NOAA:feature/autort-bl into develop
## Description
It has been a while since the updates for the current running AutoRT has been brought into develop for storage.

Bring AutoRT updates from BrianCurtis-NOAA:feature/autort-bl into develop

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
# PR Checklist

- [ ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description
This PR contains all the updates made to the Automated Regression Testing since the last commit involving the tests/auto directory

## Testing
These changes were continually tested on a daily basis.

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] CI

## Dependencies
None

## Linked Issue
Closes #752

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Note: I have no intention to stop using BrianCurtis-NOAA:feature/autort-bl for the cronjobs etc. I think this is a good time to bring these updates into develop. It's been a while.

**Comment by climbfuji** [comment]
@BrianCurtis-NOAA the updates in this PR is what is used by autoRT on all the platforms except wcoss, correct? If so, then I think we should merge this right away. No need to run regression tests, because the `tests/auto/*` files aren't used by anything else than autoRT.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA the updates in this PR is what is used by autoRT on all the platforms except wcoss, correct? If so, then I think we should merge this right away. No need to run regression tests, because the `tests/auto/*` files aren't used by anything else than autoRT.

Correct. This is whats used currently on all platforms except WCOSS.

**Review by climbfuji — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
Brian, thank you very much for bringing the code changes back to the develop branch.

**Pull request merged**
