### PR TITLE
update MOM6 to its main repository 20230504 updating

### PR DESCRIPTION
**Pull request by jiandewang**
## Description
MOM6 main repository is updated on 20230504 which contains the original NCAR-20230302-candidate and GFDL-20230406-candidate code updating). Details on code updating can be seen at https://github.com/mom-ocean/MOM6/pull/1599 and https://github.com/mom-ocean/MOM6/pull/1594 . No answer change is expected
### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [x] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Depends on NOAA-EMC/MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/113 
- Fixes corresponding UFS issue #1735

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jiandewang** [comment]
add testing RT-log here:
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11403011/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11403012/RegressionTests_hera.intel.log)
[RegressionTests_orion.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11403014/RegressionTests_orion.intel.log)
[RegressionTests_wcoss2.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11403015/RegressionTests_wcoss2.intel.log)

**Comment by jiandewang** [comment]
@jkbk2004 I just sync-ed to today Zach's commit

**Comment by jkbk2004** [comment]
> @jkbk2004 I just sync-ed to today Zach's commit

Cool! We will start working on this pr. @FernandoAndrade-NOAA @BrianCurtis-NOAA FYI

**Comment by BrianCurtis-NOAA** [comment]
We need reviews in the subcomponent PR.

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA looks like the MOM6 subcomponent PR was approved. I'll go ahead and get started with jenkins-ci.

**Comment by FernandoAndrade-NOAA** [comment]
Please see the attached logs for jenkins ci results. ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1736 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11520939/ufs-weather-model.ort-docker-pipeline.PR-1736.1.Console.Jenkins.pdf)

**Comment by BrianCurtis-NOAA** [comment]
Skipping acorn is OK.

**Comment by FernandoAndrade-NOAA** [comment]
Testing is complete, as we're skipping Acorn, so we can begin the merging process.

**Review by jkbk2004 — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
