### PR TITLE
Feature/pratemax

### PR DESCRIPTION
**Pull request by ericaligo-NOAA**
Ready for review
# PR Checklist
https://github.com/ufs-community/ufs-weather-model/issues/576

Only standalone model (regional configurations) should include a new field in the diag_table:
"gfs_phys",    "pratemax",   "pratemax",    "fv3_history2d",  "all",  .false.,  "none",  2

## Description

This PR adds the hourly maximum precipitation rate in mm/hr for all microphysical schemes and will be used only by regional configurations.  Results for regional configurations will change because pratemax, as noted above, will be added to the diag_table.  Global configurations will not use pratemax, therefore, results would be unchanged.  

### Issue(s) addressed
https://github.com/ufs-community/ufs-weather-model/issues/576

## Testing
Tested on hera with intel. New baseline was created for the regional configuration and a 2nd RT was run to confirm bit identical results.  For global applications, no new baseline was created and results were bit identical.

## Dependencies
fv3atm,ccpp/physics
https://github.com/NOAA-EMC/fv3atm/pull/327
https://github.com/NCAR/ccpp-physics/pull/675

### CODE REVIEW

**Review by junwang-noaa — CHANGES_REQUESTED** [review]
Eric, my understanding is that you only changed the fv3 and ccpp/physics in order to output pratemax. It looks to me the CDEPS, CICE, CMEPS and ww3 are not up to date yet, please sync with the top of ufs-weather-model develop branch.

**Comment by ericaligo-NOAA** [comment]
Hi, yes, you're correct.  I did a git merge origin/develop this morning 
in ufs-weather-model. It always fails for some of those you listed so I 
do a git add, commit and push.  Is that not right?

**Comment by ericaligo-NOAA** [comment]
I thought they were.  Please provide detailed instructions on how I 
should do that.  Thanks.

**Comment by MinsukJi-NOAA** [comment]
> I thought they were.  Please provide detailed instructions on how I should do that.  Thanks.

@ericaligo-NOAA, the hashes are different as shown below:

CICE: 2eca569 (ericaligo-NOAA:feature/pratemax) vs. 9d88d92 (UFS latest develop)
WW3: 0a6f4d2 vs. 097bbb6
CMEPS: a42078d vs. e40bc30
CDEPS: dc5c15c vs. 07ca4a3

**Pull request closed without merging**
