### PR TITLE
Replace w3nco with w3emc/2.9.2

### LINKED ISSUE #1125: Replace w3nco with w3emc/2.9.1
## Description
`w3nco` has been merged with `w3emc` and the latter is preferred going forward.
`w3emc/2.9.1+` contains identical code as `w3nco` with the exception of `gblevents`.
This project does not depend on `gblevents`.

## Solution
Replace dependency of `w3nco` with `w3emc` in the modulefile as well as in the build system.

## Alternatives
None.

### PR DESCRIPTION
**Pull request by junwang-noaa**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

w3nco has been merged with w3emc.  w3emc/2.9.2 contains identical code as w3nco with the exception of gblevents.
The ufs wm will be updated to use w3emc/2.9.2.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1125

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss2.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
-  fv3atm PR: https://github.com/NOAA-EMC/fv3atm/pull/561
- CCPP physics PR: https://github.com/NCAR/ccpp-physics/pull/946
- WW3 PR: https://github.com/NOAA-EMC/WW3/pull/740

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@jkbk2004 @BrianCurtis-NOAA @DeniseWorthen FYI. This PR has ww3 branch from Ali. It is up to date.

@aliabdolali Your ufs-weather-model PR#1364 is combined with this PR. I am pointing to your ww3 branch: https://github.com/aliabdolali/WW3/tree/sync_dev_Aug1 in this PR. Please let me know if that is right branch. Thanks

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — COMMENTED** [review]
Code-wise OK. Will approve with correct hash's once PR finished.

**Comment by aliabdolali** [comment]
> @jkbk2004 @BrianCurtis-NOAA @DeniseWorthen FYI. This PR has ww3 branch from Ali. It is up to date.
> 
> @aliabdolali Your ufs-weather-model PR#1364 is combined with this PR. I am pointing to your ww3 branch: https://github.com/aliabdolali/WW3/tree/sync_dev_Aug1 in this PR. Please let me know if that is right branch. Thanks

Yes Jun, this is the correct branch. It includes your PR to WW3/dev/ufs-weather-model (for w3emc instead of w3nco) + merge top of WW3/develop.

**Review by aliabdolali — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@aliabdolali @JessicaMeixner-NOAA I am pointing to Ali's ww3 branch. May I ask if the ww3 updates will change results or not? If yes, I need to change the baseline date. Please let me know, thanks.

**Comment by junwang-noaa** [comment]
@jkbk2004 @BrianCurtis-NOAA This PR is up to date. Once I hear from Ali/Jessica, we can start RT. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
I would have to run a test to be sure.  I don't think they would, but I'm assuming @aliabdolali would already know the answer to that.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa I saw in: https://github.com/ufs-community/ufs-weather-model/pull/1364 that @aliabdolali  mentioned: 
"No changes in the results and no need to recreate new mod_def files." 
So I'm assuming no new baseline is needed.

**Comment by aliabdolali** [comment]
> @junwang-noaa I saw in: #1364 that @aliabdolali mentioned: "No changes in the results and no need to recreate new mod_def files." So I'm assuming no new baseline is needed.

Correct, no new baseline is needed.

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa Please change the w3nco requirement in CMakeLists.txt to w3emc and the correct version.
https://github.com/junwang-noaa/ufs-weather-model/blob/96eb447aeaffc7230ca7ab6d863243785ae3f9c0/CMakeLists.txt#L135

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Thanks for catching it!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/994447846/20220810134510/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: hera Compiler: intel Job: RT [RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/994447846/20220810134510/ufs-weather-model Please make changes and add the following label back: hera-intel-RT

cpld_restart_bmark_p8 failed it seems. The log file didn't write though, so it didn't make it until the end. I know we're at quota like usual on Hera, so that might have played a role.

**Comment by DeniseWorthen** [comment]
That log shows it passing (took 2 tries):

```
/scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/994447846/20220810134510/ufs-weather-model/tests/log_hera.intel/rt_011_cpld_restart_bmark_p8.log
```

**Comment by BrianCurtis-NOAA** [comment]
> That log shows it passing (took 2 tries):
> 
> ```
> /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/994447846/20220810134510/ufs-weather-model/tests/log_hera.intel/rt_011_cpld_restart_bmark_p8.log
> ```

Cool. It wasn't there when I checked. @jkbk2004 will need to see why the log writing failed.

**Comment by jkbk2004** [comment]
> rt_011_cpld_restart_bmark_p8.log
In rt.sh, ecflow_run ran ok but it didn't go thru the next line, right? cat ${LOG_DIR}/compile_*_time.log

**Comment by jkbk2004** [comment]
> > rt_011_cpld_restart_bmark_p8.log
> > In rt.sh, ecflow_run ran ok but it didn't go thru the next line, right? cat ${LOG_DIR}/compile_*_time.log

sounds like all ecflow jobs marked out 'exit 0' though.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/994447846/20220810151509/ufs-weather-model
[RT] Error: Test regional_3km_decomp 049 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
@junwang-noaa cpld_bmark_p8/cheyenne.intel is not moving in que: 128 nodes. Can we consdier to turn off cpld_bmark_p8 cases on cheyenne until we figure out a solution?

**Comment by junwang-noaa** [comment]
That's OK to me.

**Comment by BrianCurtis-NOAA** [comment]
Acorn is having issues, there's no new baselines so nothing I need to run later, it's OK to skip Acorn.

**Comment by jkbk2004** [comment]
There was cpld_bmark case resource issue on cheyenne. Temporarily turning off those cases on cheyenne, all tests are completed ok. Please, leave final comments. Can we move on to merge in? we can start with [ccpp#946](https://github.com/NCAR/ccpp-physics/pull/946) [fv3atm#561](https://github.com/NOAA-EMC/fv3atm/pull/561) and then [#740](https://github.com/NOAA-EMC/WW3/pull/740)

**Comment by grantfirl** [comment]
> There was cpld_bmark case resource issue on cheyenne. Temporarily turning off those cases on cheyenne, all tests are completed ok. Please, leave final comments. Can we move on to merge in? we can start with [ccpp#946](https://github.com/NCAR/ccpp-physics/pull/946) [fv3atm#561](https://github.com/NOAA-EMC/fv3atm/pull/561) and then [#740](https://github.com/NOAA-EMC/WW3/pull/740)

@jkbk2004 I can merge https://github.com/NCAR/ccpp-physics/pull/946 when ready. Just let me know.

**Comment by jkbk2004** [comment]
> [NCAR/ccpp-physics#946](https://github.com/NCAR/ccpp-physics/pull/946)

@grantfirl sure! go ahead to merge in [ccpp#946](https://github.com/NCAR/ccpp-physics/pull/946)

**Comment by aliabdolali** [comment]
@junwang-noaa please let me know once I can merge https://github.com/NOAA-EMC/WW3/pull/750 to WW3/dev/ufs-weather-model, so you can revert changes in .gitmodules

**Comment by junwang-noaa** [comment]
@aliabdolali Please merge ww3 PR. I am waiting for fv3 PR to be committed, then I will update the gitmodule in ufs-weather-model branch.

**Comment by aliabdolali** [comment]
> @aliabdolali Please merge ww3 PR. I am waiting for fv3 PR to be committed, then I will update the gitmodule in ufs-weather-model branch.

I just merged it. Please revert your changes in .gitmodules.

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA @jkbk2004 fv3 and ww3 branches are now point to official branches.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
