### PR TITLE
sync ww3/dev/ufs-weather-model

### LINKED ISSUE #1115: Segfaults when running cpld aerosol model with GNU 9 and 10
## Description
Currently, CI includes tests for `cpld_control_c96_p8` and its debug run.
Due to changes introduced in #1071, the `cpld_control_c96_p8` test with GNU results in segfaults originating from `ufs-weather-model/GOCART/ESMF/UFS/Aerosol_Cap.F90:321` for runs both in a Docker container and on Hera.

## Solution
Switch `cpld_control_c96_p8` with `cpld_control_c96_noaero_p8` in CI. Also make changes to `opnReqTest` script and CI (library update and input data update) that are needed after the aerosol update.

## Update
CI tests have been made and merged into the UFS weather model via #1087. However, this issue will be kept open to address the segfault issue when running the coupled aerosol model with GNU 9 and 10. The issue title has been updated accordingly.

### PR DESCRIPTION
**Pull request by aliabdolali**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
Sync WW3/dev/ufs-weather-model to the top of WW3/develop
No changes in the results and no need to recreate new mod_def files.
### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1115

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI 8de079e

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/WW3/pull/714

### CODE REVIEW

**Comment by aliabdolali** [comment]
The regtests are submitted on hera, will post updates on changes soon

**Comment by aliabdolali** [comment]
@junwang-noaa @DeniseWorthen 
There are no changes in results, so we can combine it with another PR.

**Comment by junwang-noaa** [comment]
@aliabdolali Can we work on the PR today?

**Comment by aliabdolali** [comment]
> @aliabdolali Can we work on the PR today?

@junwang-noaa I think so, my test on Hera showed no changes in the outputs, so we are good to merge.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/942708115/20220523164517/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/942708115/20220523151513/ufs-weather-model
[RT] Error: Test control_c384gdas_wav 125 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by DeniseWorthen** [comment]
The hera.intel failure was a time-out, but the model apparently hung, since it never got further than realizing the connected fields. I will repeat the test and append the log.

**Comment by DeniseWorthen** [comment]
@aliabdolali The control_c384gdas_wav on hera is apparently hanging. You said you ran the full RT on hera so you saw no issue w/ this test? I have a run directory here

```
/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_20834/control_c384gdas_wav
```

**Comment by aliabdolali** [comment]
> @aliabdolali The control_c384gdas_wav on hera is apparently hanging. You said you ran the full RT on hera so you saw no issue w/ this test? I have a run directory here
> 
> ```
> /scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_20834/control_c384gdas_wav
> ```

@DeniseWorthen yes, it ran successfully. see /scratch1/NCEPDEV/stmp2/Ali.Abdolali/Source/May21UFS/tests/RegressionTests_hera.intel.log

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/942708115/20220523211512/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by DeniseWorthen** [comment]
@aliabdolali Your test was prior to the intel commit (it used develop-20220517). We'll need to figure out what changed and why it is now hanging. 

The jet failures may be related to disk quota so I'm going to try again after cleaning up.

**Review by junwang-noaa — APPROVED** [review]

**Comment by aliabdolali** [comment]
> @aliabdolali Your test was prior to the intel commit (it used develop-20220517). We'll need to figure out what changed and why it is now hanging.
> 
> The jet failures may be related to disk quota so I'm going to try again after cleaning up.

my standalone ww3 for c384gdas_wav failed with the new intel and following lib
  ```
module load cmake/3.20.1
  module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
  module load hpc/1.1.0
  module load hpc-intel/2022.1.2
  module load hpc-impi/2022.1.2
  module load netcdf/4.7.4
  module load jasper/2.0.25
  module load zlib/1.2.11
  module load libpng/1.6.37
  module load hdf5/1.10.6
  module load bacio/2.4.1
  module load g2/3.4.5
  module load w3nco/2.4.1
```
I am checking more

**Comment by junwang-noaa** [comment]
@aliabdolali Just let you know besides the intel compiler version update, three libraries were updated: jasper, pio and g2. Also the png lib is renamed and updated to libpng/1.6.37.

**Comment by aliabdolali** [comment]
@junwang-noaa in my run, I changed the following

module load hpc-intel/2022.1.2
module load hpc-impi/2022.1.2
module load jasper/2.0.25
module load zlib/1.2.11
module load libpng/1.6.37
module load g2/3.4.5

 and it failed, note that g2, libpng, zlib, and jasper are required for ww3_grib, which is not related to the failure. I ran a serial job and it worked fine, so it might be related to impi

**Comment by aliabdolali** [comment]
@junwang-noaa 
Based on my test, the impi is the issue
I used the following and the test passed:

module load cmake/3.20.1
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-intel/2022.1.2
**module load hpc-impi/2021.3.0**
module load netcdf/4.7.4
module load jasper/2.0.25
module load zlib/1.2.11
module load libpng/1.6.37
module load hdf5/1.10.6
module load bacio/2.4.1
module load g2/3.4.5
module load w3nco/2.4.1

**Comment by junwang-noaa** [comment]
@aliabdolali @DeniseWorthen I copied Denise's run directory (/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_20834/control_c384gdas_wav) and reran the test. It ran to the end, taking 718s.  

My run directory: /scratch1/NCEPDEV/stmp2/Jun.Wang/control_c384gdas_wav

**Comment by junwang-noaa** [comment]
Also we are using the same impi version (hpc-impi/2022.1.2) on Orion, the control_c384gdas_wav test passed.

**Comment by DeniseWorthen** [comment]
@junwang-noaa You made no changes when you copied my run directory and re-ran?

**Comment by junwang-noaa** [comment]
Right, I just copied the run directory and reran the case.
I am checking out Ali's branch and will run RT with the control_c384gdas_wav test only.

**Comment by DeniseWorthen** [comment]
I don't understand. The original auto-RT failure showed the run just hanging and timing out. Then I repeated the test using a checkout of his branch and got the same result (that is the run directory you copied). What could explain this?

I'm also re-running the single test now.

**Comment by DeniseWorthen** [comment]
My re-run of the control_c384gdas_wav test got a lot further, then appears to hang once again. It has been running for almost 20 mins and has not advanced. I'm really not at all sure what is happening.

/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_15788/control_c384gdas_wav

**Comment by junwang-noaa** [comment]
This time the job hang when I submitted the rt.sh. Let's try to change the impi version on hera to hpc-impi/2021.3.0. 

@kgerheiser @Hang-Lei-NOAA FYI.

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA @kgerheiser Would you please install the hpc-stack with impi 2021.3.0 on hera? One of the regression test hang with impi 2022.12, the developer said that the impi 2021.3.0 makes the test pass. Thank.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/942708115/20220527131512/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Comment by junwang-noaa** [comment]
The last test is not finished yet on hera.intel, while the autoRT is done.

**Comment by DeniseWorthen** [comment]
It looks like the c384 restart job finally finished, but it never really advanced from what I can tell. It just timed out.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/942708115/20220527131518/ufs-weather-model
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 088 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by junwang-noaa** [comment]
I am rerunning the RT on hera

**Comment by DeniseWorthen** [comment]
This is the same test that we had problems w/ on Bin Liu's PR.

**Comment by junwang-noaa** [comment]
The  hafs_regional_atm_thompson_gfdlsf did not start to run on jet. Will rerun it.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/942708115/20220527201507/ufs-weather-model
[RT] Error: Test cpld_control_c384_p8 010 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Pull request merged**
