### PR TITLE
Update CMEPS; fix aux history functionality for float variable type; Switch to using Aux history files in atm_ds2s_docn_dice test; Remove IFI tests (was #2417)

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Sync with ESCOMP, including fix for aux history output from EMC.

### Commit Message:

```
* UFSWM - 
  * CMEPS - fix aux history functionality; sync with ESCOMP
  * UFSWM - use auxiliary history files as input for atm_ds2s_docn_dice; remove the IFI tests
```

### Priority:

* Normal

### UFSWM:

- https://github.com/NOAA-EMC/CMEPS/issues/123
- #2398 
- #2416 
### Sub component Pull Requests:

* CMEPS: https://github.com/NOAA-EMC/CMEPS/pull/124

---
### Regression Test Changes (Please commit test_changes.list):

* A new baseline is required for the ``atm_ds2s_docn_dice`` test. 

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by NickSzapiro-NOAA** [comment]
Can we enable atm_ds2s_docn_dice on wcoss2 and acorn in rt.conf?

**Comment by BrianCurtis-NOAA** [comment]
> Can we enable atm_ds2s_docn_dice on wcoss2 and acorn in rt.conf?

If you've tested and they work, absolutely

**Comment by NickSzapiro-NOAA** [comment]
I don't have active accounts to test on these machines right now. With use_float=.true. as is, testing is to check that sfc\*nc and atm\*nc look similar between cpld_control_nowave_noaero_p8 and atm_ds2s_docn_dice. I'm happy to look at output if it can be moved but also understand if there is no time.

**Comment by FernandoAndrade-NOAA** [comment]
This PR is next for testing, please sync and bring in the changes from #2417

**Comment by zach1221** [comment]
Testing is complete. We can begin the merging process.

**Review by jkbk2004 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Pull request merged**
