### PR TITLE
Send Evap rate from ATM to OCN

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Adds the evaporative flux to the export fields available from ATM; CMEPS uses this flux instead of internally converting from the latent heat flux.

This is an incremental update related to [#1807](https://github.com/ufs-community/ufs-weather-model/pull/1807). Adding the evaporative flux change created non-B4B answers so I would like to commit this PR first since the other changes in #1807 result only in changes to the mediator restart files but otherwise reproduce.

A test case was run using the ``cpld_control_nowave_noaero_p8`` test. Instantaneous mediator history files were written for the OCN component. At the first pass through the coupling sequence, the difference between the evaporative flux sent to the ocean is ~O-15. This is due to the difference in converting from latent->evap in the atmosphere vs doing the conversion in CMEPS. The difference between the current code and this change at the end of the first coupling loop, scaled by 1.0e14 shows random differences:

Screen Shot 2023-06-28 at 4 36 37 PM

At the end of 24 hour, the evaporative flux sent to the OCN and the difference between the develop branch and the feature branch is shown below. The differences are small compared to the field value.

Screen Shot 2023-06-28 at 3 41 32 PM

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/11905653/RegressionTests_hera.log)

Coupled tests will change baselines due to round-off level differences associated moving the latent->evap conversion from CMEPS to the ATM. No baselines are expected to change DATM tests since they the evaporative flux calculated in the mediator's aoflux routine. 

The following test fail on Hera, as expected.

```
1:138:Test 001 cpld_control_p8_mixedmode_intel FAIL
2:209:Test 002 cpld_control_gfsv17_intel FAIL
3:281:Test 003 cpld_control_p8_intel FAIL
4:353:Test 005 cpld_control_qr_p8_intel FAIL
5:413:Test 007 cpld_2threads_p8_intel FAIL
6:473:Test 008 cpld_decomp_p8_intel FAIL
7:533:Test 009 cpld_mpi_p8_intel FAIL
8:605:Test 010 cpld_control_ciceC_p8_intel FAIL
9:665:Test 011 cpld_control_c192_p8_intel FAIL
10:720:Test 013 cpld_bmark_p8_intel FAIL
11:791:Test 015 cpld_control_noaero_p8_intel FAIL
12:860:Test 016 cpld_control_nowave_noaero_p8_intel FAIL
13:920:Test 017 cpld_debug_p8_intel FAIL
14:979:Test 018 cpld_debug_noaero_p8_intel FAIL
15:1105:Test 020 cpld_control_c48_intel FAIL
16:1107:Test 021 cpld_warmstart_c48_intel FAIL
17:1179:Test 023 cpld_control_p8_faster_intel FAIL
18:1250:Test 024 cpld_control_pdlib_p8_intel FAIL
19:1309:Test 027 cpld_debug_pdlib_p8_intel FAIL
24:7117:Test 234 cpld_control_p8_gnu FAIL
25:7186:Test 235 cpld_control_nowave_noaero_p8_gnu FAIL
26:7246:Test 236 cpld_debug_p8_gnu FAIL
27:7317:Test 237 cpld_control_pdlib_p8_gnu FAIL
28:7376:Test 238 cpld_debug_pdlib_p8_gnu FAIL
```

Four hafs tests fail because the special (fill) value in the mediator files is no longer being scaled by ``rtime`` prior to export by ATM

```
20:4203:Test 134 hafs_regional_atm_ocn_intel FAIL
21:4237:Test 136 hafs_regional_atm_ocn_wav_intel FAIL
22:4739:Test 151 hafs_regional_docn_intel FAIL
23:4754:Test 152 hafs_regional_docn_oisst_intel FAIL
```

For the hafs tests, all files are B4B except for

```
957:rt_134_hafs_regional_atm_ocn_intel.log:9: Comparing ufs.hafs.cpl.hi.2019-08-29-21600.nc ............ALT CHECK......NOT OK
958:rt_134_hafs_regional_atm_ocn_intel.log:10: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
959:rt_136_hafs_regional_atm_ocn_wav_intel.log:12: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
960:rt_151_hafs_regional_docn_intel.log:7: Comparing ufs.hafs.cpl.hi.2019-08-29-21600.nc ............ALT CHECK......NOT OK
961:rt_151_hafs_regional_docn_intel.log:8: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
962:rt_152_hafs_regional_docn_oisst_intel.log:7: Comparing ufs.hafs.cpl.hi.2019-08-29-21600.nc ............ALT CHECK......NOT OK
963:rt_152_hafs_regional_docn_oisst_intel.log:8: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
```

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Library Updates/Changes

- [x] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- partial fix for https://github.com/NOAA-EMC/CMEPS/issues/93
- depends on https://github.com/NOAA-EMC/CMEPS/pull/96
- depends on https://github.com/NOAA-EMC/fv3atm/pull/672
- creates https://github.com/ufs-community/ufs-weather-model/issues/1822

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
It looks like cpld_warmstart_c48_intel crashed (not baseline check failure). @DeniseWorthen can you confirm?

**Comment by DeniseWorthen** [comment]
@jkbk2004 I suspect I know the issue. Please provide the run directory location so I can check.

**Comment by jkbk2004** [comment]
/scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_278330/cpld_warmstart_c48_intel

**Comment by DeniseWorthen** [comment]
Checking either the mediator.log or PET log would have shown the reason:

mediator.log:
```
(med.F90:DataInitialize) read_restart =  T
 (med_io_read_init_iodesc) ERROR: atmImp_Faxa_evap is not present, aborting
```

PET00.ESMF_LogFile
```
20230704 125749.682 INFO             PET00 (med_io_read_init_iodesc) ERROR: atmImp_Faxa_evap is not present, aborting
```

This is the only coupled test which includes a ``warmstart`` test (meaning it starts up from staged ICs generated by an actual model run), which was a request of the G-W developers when the super-low res tests were committed. 

Fixing this test failure will require a new set of updated ICs for this test. However, since the pre-staged files for the warm-start test will need to be updated again for PR #1807, I would propose we turn this test off until #1807  is up for commit.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I just realized I need to turn off the c48-5deg restart test also. Making change now.

**Review by junwang-noaa — DISMISSED** [review]

**Review by BrianCurtis-NOAA — DISMISSED** [review]

**Comment by BrianCurtis-NOAA** [comment]
A cool feature of GitHub is that you can close other PR's with other PR's. So in this you should add 'closes #1810 ' and upon merge of this PR, that PR will be closed.

**Comment by DeniseWorthen** [comment]
Thans Brian, I had originally in the linked PR section that it "fixes....1810" but I changed it to "closes....1810". I bet fixes doesn't work for PRs, only issues.

**Comment by BrianCurtis-NOAA** [comment]
> Thans Brian, I had originally in the linked PR section that it "fixes....1810" but I changed it to "closes....1810". I bet fixes doesn't work for PRs, only issues.

unfortunately it only works if the keyword used is the only one before the # of the issue/PR. This is why it's important to use the - before the keyword because GitHub will add the whole title for you automatically.

**Comment by BrianCurtis-NOAA** [comment]
Also the one that says "partially resolves" will probably close that item. You may want to just say 'partial fix' I don't think 'fix' is a keyword.

**Comment by DeniseWorthen** [comment]
You're right---it removed that from the "merging this PR will close...." on the sidebar.

I think we should use as many of these automatic features as we can. I really liked Sam's use of the drop down menu. I thought that was really clever for tidy-ing up the PR information.

**Comment by FernandoAndrade-NOAA** [comment]
jenkins ci logs are attached, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1812 #1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/11962566/ufs-weather-model.ort-docker-pipeline.PR-1812.1.Console.Jenkins.txt)

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 If Cheyenne fails with a UNBOUND VARIABLE let me know. I may have to pull my PR.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 I ran this PR on WCOSS2/Acorn yesterday and it kept giving me UNBOUND VARIABLE errors. I tested on Hera without issue. I've had @DeniseWorthen revert those changes for now so I can at least get WCOSS2/Acorn working before bringing #1810 into a future PR.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA All other RDHPCS are running ok even with #1810. Hera is down for maintenance. But It ran ok on Hera. Some cases are still running on Jet. @zach1221 @FernandoAndrade-NOAA FYI

**Comment by BrianCurtis-NOAA** [comment]
> 

That's great to hear. The code changes enough with my fixes for WCOSS2/Acorn that I want to re-test it on Hera when it's back before I put it into a future PR. Plus I need to get WCOSS2 back before I test my fixes on it.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA just to confirm. wcoss2 test will come, right? We can still try to combine in #1810 with a quick follow-up when hera comes back online this evening. And still we can merge in this pr first thing tomorrow morning.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA just to confirm. wcoss2 test will come, right? We can still try to combine in #1810 with a quick follow-up when hera comes back online this evening. And still we can merge in this pr first thing tomorrow morning.

WCOSS2 still has an issue. I'll get back to it in the AM with hopes to finish early on.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I tested #1810 on hera. No problem on hera. Once you confirm with wcoss2, then we can combine #1810 back into this pr. @DeniseWorthen FYI

**Comment by DeniseWorthen** [comment]
Since testing is complete, it would be better to add #1810 to the next PR.

**Comment by BrianCurtis-NOAA** [comment]
On WCOSS2, the baselines generated for hrrr_control that 4 tests are comparing against, are failing comparisons for different restart tiles each time a new baseline is generated. I'm assuming at this point it's a guessing game when a new baseline for that test will not break at one tile in comparison. I do not know why WCOSS2 is the only platform having this issue.

@DeniseWorthen have we seen this issue before? I recall something along these lines.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA it might be worth to make a quick sanity check for hrrr_control with develop branch on wcoss2.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA it might be worth to make a quick sanity check for hrrr_control with develop branch on wcoss2.

Sure give me a little bit to run against current baselines, and then to create new baselines and compare against those.

**Comment by jkbk2004** [comment]
@DeniseWorthen fv3 pr was merged.

**Review by BrianCurtis-NOAA — DISMISSED** [review]

**Review by zach1221 — DISMISSED** [review]

**Comment by sadeghitabas** [comment]
Could you please update the gitmodules and pointer?

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
