### PR TITLE
Fix uninitialized min_rand variable in Thompson MP when using SPP

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This bug is the result of differences between the module_mp_thompson.F routine in WRF and what is in CCPP.  The "min_rand" variable was defined as the following in the WRF-based Thompson MP module:

```
#if ( defined( DM_PARALLEL ) && ( ! defined( STUBMPI ) ) )
      min_rand = wrf_dm_max_real ( MINVAL(rand_pert(i_start:i_end,1,j_start:j_end)) )
#else
      min_rand = MINVAL ( rand_pert(i_start:i_end,1,j_start:j_end) )
#endif
```

However, this block of code is not in the module_mp_thompson.F90 CCPP routine.  Since it's not included, the "min_rand" variable is defined, but uninitialized.  It's then used in the following SPP "if" statement (but only when SPP is turned on):

```
if (rand_perturb_on .ne. 0) then
    if (MOD(rand_perturb_on,2) .ne. 0) rand1 = rand_pert(i,1)
    m = RSHIFT(ABS(rand_perturb_on),1)
    if (MOD(m,2) .ne. 0) rand2 = rand_pert(i,1)*2.
    m = RSHIFT(ABS(rand_perturb_on),2)
    if (MOD(m,2) .ne. 0) rand3 = 0.25*(rand_pert(i,1)+ABS(min_rand))
    m = RSHIFT(ABS(rand_perturb_on),3)
endif
```

The result is that "min_rand" is filled with whatever is in memory at the time, which could be zeros or random junk, rendering the regional stochastic physics RT test with SPP non-reproducible.  The solution is to define and initialize an "abs_min_rand" variable (previously min_rand) prior to this "if" statement as follows:

`REAL:: rand1, rand2, rand3, abs_min_rand`

...

`abs_min_rand = ABS(MINVAL(rand_pert(:,1)))`

Then the "if" statement above is modified to replace the "min_rand" line with:

`if (MOD(m,2) .ne. 0) rand3 = 0.25*(rand_pert(i,1)+abs_min_rand)`

This modification was tested to accurately output the absolute value of the minimum value of the domain-wide random pattern field, identical to what was done in WRF.

Results from the regional_spp_sppt_shum_skeb regression test will change based on this PR, now that the uninitialized variable is set correctly, but new input data is not required.

### Issue(s) addressed

Fixes NCAR/ccpp-physics [Issue #891](https://github.com/NCAR/ccpp-physics/issues/891).

## Testing

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [] jet.intel (skip due to maintenance)
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: [011b2c3](https://github.com/ufs-community/ufs-weather-model/pull/1152/commits/011b2c3a91f8a63f9ff4a966000170924dc2252b)

## Dependencies

Depends on the following PRs from [fv3atm](https://github.com/NOAA-EMC/fv3atm/pull/516), [ccpp-physics](https://github.com/NCAR/ccpp-physics/pull/892), and [stochastic_physics](https://github.com/noaa-psd/stochastic_physics/pull/57).

@jwolff-ncar, @willmayfield, @bluefinweiwei, @michelleharrold, @judithberner, @gsketefian

### CODE REVIEW

**Review by SamuelTrahanNOAA — APPROVED** [review]

**Review by SamuelTrahanNOAA — CHANGES_REQUESTED** [review]
This PR will not have consistent results between thread counts due to this line in module_mp_thompson.F90

```
abs_min_rand = ABS(MINVAL(rand_pert(:,1)))
```

**Comment by junwang-noaa** [comment]
Nice catch, Sam!

**Comment by JeffBeck-NOAA** [comment]
All blocks are consolidated into a single 1D array in the stochastic physics wrapper (stochastic_physics_wrapper.F90) before `spp_wts_mp` is passed to module_mp_thompson.F90 as `rand_pert`:

```
do nb=1,Atm_block%nblks
      GFS_Data(nb)%Coupling%spp_wts_mp(:,:) = spp_wts(nb,1:GFS_Control%blksz(nb),:,n)
end do
```

**Comment by SamuelTrahanNOAA** [comment]
It will still depend on MPI decomposition (layout_x and layout_y) since different ranks will have different parts of the domain.

**Comment by JeffBeck-NOAA** [comment]
@SamuelTrahanNOAA, please see the latest changes to this PR, which I believe will resolve your concerns. The code is now working (ran the RT test; baselines change) and calculates the maximum random perturbation value based on namelist settings brought in from stochastic_physics.

**Comment by SamuelTrahanNOAA** [comment]
There is a minor issue in the mp_thompson.meta, and two submodules are old, as of the moment I tested: fv3atm and stochastic_physics.

**Comment by JeffBeck-NOAA** [comment]
Thanks @SamuelTrahanNOAA.  I fixed the metadata issues in the ccpp/physics repo PR.  The submodules should be up-to-date now too.

**Review by SamuelTrahanNOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
On hera.intel, all tests except regional_spp_sppt_shum_skeb match their baselines. That means these changes do not modify results beyond what is expected.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA Please do another merge with ufs-weather-model develop branch, your PR is on the top of the queue.

Also if you haven't done previously, please add me (BrianCurtis-NOAA) as a collaborator on your fork so our automated regression testing system can push to your branch.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA Also please update BL_DATE in rt.sh to 20220412

**Comment by JeffBeck-NOAA** [comment]
@BrianCurtis-NOAA, ufs-weather-model has been updated, along with the rt.sh file.  I also confirmed that you are a collaborator on my fork.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA one more adjustment if you could please, in modulefiles/ufs_common change fms/2021.04 to fms/2022.01 i've tested it with intel/gnu and it does not change results.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA one more adjustment if you could please, in modulefiles/ufs_common change fms/2021.04 to fms/2022.01 i've tested it with intel/gnu and it does not change results.

Done!

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA I'm creating new baselines for the one INTEL test you mentioned previously `regional_spp_sppt_shum_skeb` and will start the Automated system once I get all the machines done and baselines moved.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @BrianCurtis-NOAA!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/898113491/20220412140012/ufs-weather-model
[RT] Error: Test control 001 failed in run_test failed 
[RT] Error: Test control_c48 003 failed in run_test failed 
[RT] Error: Test control_stochy 004 failed in run_test failed 
[RT] Error: Test control_flake 005 failed in run_test failed 
[RT] Error: Test control_rrtmgp 006 failed in run_test failed 
[RT] Error: Test control_thompson 007 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero 008 failed in run_test failed 
[RT] Error: Test control_ras 009 failed in run_test failed 
[RT] Error: Test control_p8 010 failed in run_test failed 
[RT] Error: Test rap_control 011 failed in run_test failed 
[RT] Error: Test rap_2threads 012 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 014 failed in run_test failed 
[RT] Error: Test hrrr_control 016 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 017 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 018 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_radar_tten_warm 019 failed in run_test failed 
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test rap_diag_debug 024 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 025 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 026 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 027 failed in run_test failed 
[RT] Error: Test control_thompson_debug 028 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero_debug 029 failed in run_test failed 
[RT] Error: Test control_thompson_extdiag_debug 030 failed in run_test failed 
[RT] Error: Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 035 failed in run_test failed 
[RT] Error: Test cpld_control_c96_noaero_p8 037 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 038 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 039 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/898113491/20220412144510/ufs-weather-model
[RT] Error: Test control 001 failed in run_test failed 
[RT] Error: Test control_c48 003 failed in run_test failed 
[RT] Error: Test control_stochy 004 failed in run_test failed 
[RT] Error: Test control_flake 005 failed in run_test failed 
[RT] Error: Test control_rrtmgp 006 failed in run_test failed 
[RT] Error: Test control_thompson 007 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero 008 failed in run_test failed 
[RT] Error: Test control_ras 009 failed in run_test failed 
[RT] Error: Test control_p8 010 failed in run_test failed 
[RT] Error: Test rap_control 011 failed in run_test failed 
[RT] Error: Test rap_2threads 012 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 014 failed in run_test failed 
[RT] Error: Test hrrr_control 016 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 017 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 018 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_radar_tten_warm 019 failed in run_test failed 
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test rap_diag_debug 024 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 025 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 026 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 027 failed in run_test failed 
[RT] Error: Test control_thompson_debug 028 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero_debug 029 failed in run_test failed 
[RT] Error: Test control_thompson_extdiag_debug 030 failed in run_test failed 
[RT] Error: Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 035 failed in run_test failed 
[RT] Error: Test cpld_control_c96_noaero_p8 037 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 038 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 039 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/898113491/20220412203009/ufs-weather-model
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test rap_diag_debug 024 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 025 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 026 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 027 failed in run_test failed 
[RT] Error: Test control_thompson_debug 028 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero_debug 029 failed in run_test failed 
[RT] Error: Test control_thompson_extdiag_debug 030 failed in run_test failed 
[RT] Error: Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 035 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 038 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/898113491/20220412151512/ufs-weather-model
[RT] Error: Test control 001 failed in run_test failed 
[RT] Error: Test control_c48 003 failed in run_test failed 
[RT] Error: Test control_stochy 004 failed in run_test failed 
[RT] Error: Test control_flake 005 failed in run_test failed 
[RT] Error: Test control_rrtmgp 006 failed in run_test failed 
[RT] Error: Test control_thompson 007 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero 008 failed in run_test failed 
[RT] Error: Test control_ras 009 failed in run_test failed 
[RT] Error: Test control_p8 010 failed in run_test failed 
[RT] Error: Test rap_control 011 failed in run_test failed 
[RT] Error: Test rap_2threads 012 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 014 failed in run_test failed 
[RT] Error: Test hrrr_control 016 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 017 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 018 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_radar_tten_warm 019 failed in run_test failed 
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test rap_diag_debug 024 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 025 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 026 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 027 failed in run_test failed 
[RT] Error: Test control_thompson_debug 028 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero_debug 029 failed in run_test failed 
[RT] Error: Test control_thompson_extdiag_debug 030 failed in run_test failed 
[RT] Error: Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 035 failed in run_test failed 
[RT] Error: Test cpld_control_c96_noaero_p8 037 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 038 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 039 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa seems the fms/2022.01 changes baselines for GNU only, I had thought I tested it but maybe I configured something wrong when I tested. I just reran UFSWM develop branch GNU with fms/2022.01 and it failed. Apologies there.

@JeffBeck-NOAA I reverted the fms change. Hopefully the GNU tests pass now.

**Comment by JeffBeck-NOAA** [comment]
> @junwang-noaa seems the fms/2022.01 changes baselines for GNU only, I had thought I tested it but maybe I configured something wrong when I tested. I just reran UFSWM develop branch GNU with fms/2022.01 and it failed. Apologies there.
> 
> @JeffBeck-NOAA I reverted the fms change. Hopefully the GNU tests pass now.

Thanks, @BrianCurtis-NOAA!  I was wondering if that was the cause of the GNU failures.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/898113491/20220412161511/ufs-weather-model
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test rap_diag_debug 024 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 025 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 026 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 027 failed in run_test failed 
[RT] Error: Test control_thompson_debug 028 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero_debug 029 failed in run_test failed 
[RT] Error: Test control_thompson_extdiag_debug 030 failed in run_test failed 
[RT] Error: Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 035 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 038 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/898113491/20220412221508/ufs-weather-model
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test rap_diag_debug 024 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 025 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 026 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 027 failed in run_test failed 
[RT] Error: Test control_thompson_debug 028 failed in run_test failed 
[RT] Error: Test control_thompson_no_aero_debug 029 failed in run_test failed 
[RT] Error: Test control_thompson_extdiag_debug 030 failed in run_test failed 
[RT] Error: Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 035 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 038 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA looks like the same GNU tests fail for hera and cheyenne. (maybe it's not FMS?)

**Comment by JeffBeck-NOAA** [comment]
@BrianCurtis-NOAA, found it:

```
105: An error occurred in ccpp_physics_run for group physics, block    2 and thread    1 (ntX=   1):
105: Detected size mismatch for variable GFS_Control%spp_prt_list in group physics before mp_thompson_run, expected        0 but got        1
```

The stochastic physics field `spp_prt_list` should be undefined when SPP isn't turned on (`spp_prt_list_out` doesn't get set to `spp_prt_list(n_var_spp)` in stochastic_physics/stochastic_physics.F90 unless `n_var_spp` is greater than 0).  Also, there's this block in `GFS_typedefs.F90`, so CCPP shouldn't get anything (since do_spp = .false.):

```
    if (Model%do_spp) then
      allocate(Model%spp_var_list(Model%n_var_spp))
      allocate(Model%spp_prt_list(Model%n_var_spp))
      allocate(Model%spp_stddev_cutoff(Model%n_var_spp))
      Model%spp_var_list(:) = ''
      Model%spp_prt_list(:) = clear_val
      Model%spp_stddev_cutoff(:) = clear_val
    end if
```

@grantfirl, @SamuelTrahanNOAA, do you have a second to see if you understand what's happening here?  Maybe I need to remove the "if" statement above and allocate those fields regardless?  I'm looking at this failed run on Hera here: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_26731/control_thompson_no_aero_debug.  Thank you!

**Comment by junwang-noaa** [comment]
@JeffBeck-NOAA @SamuelTrahanNOAA @grantfirl May I ask if you have a solution for the issue with gnu compiler?

**Comment by grantfirl** [comment]
> @BrianCurtis-NOAA, found it:
> 
> ```
> 105: An error occurred in ccpp_physics_run for group physics, block    2 and thread    1 (ntX=   1):
> 105: Detected size mismatch for variable GFS_Control%spp_prt_list in group physics before mp_thompson_run, expected        0 but got        1
> ```
> 
> The stochastic physics field `spp_prt_list` should be undefined when SPP isn't turned on (`spp_prt_list_out` doesn't get set to `spp_prt_list(n_var_spp)` in stochastic_physics/stochastic_physics.F90 unless `n_var_spp` is greater than 0). Also, there's this block in `GFS_typedefs.F90`, so CCPP shouldn't get anything (since do_spp = .false.):
> 
> ```
>     if (Model%do_spp) then
>       allocate(Model%spp_var_list(Model%n_var_spp))
>       allocate(Model%spp_prt_list(Model%n_var_spp))
>       allocate(Model%spp_stddev_cutoff(Model%n_var_spp))
>       Model%spp_var_list(:) = ''
>       Model%spp_prt_list(:) = clear_val
>       Model%spp_stddev_cutoff(:) = clear_val
>     end if
> ```
> 
> @grantfirl, @SamuelTrahanNOAA, do you have a second to see if you understand what's happening here? Maybe I need to remove the "if" statement above and allocate those fields regardless? I'm looking at this failed run on Hera here: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_26731/control_thompson_no_aero_debug. Thank you!

@JeffBeck-NOAA Sorry for not getting to this until now. I think that Dom found a similar bug. I'll take a look, but it may be fixed by editing the metadata. I'll get back to you in a bit after looking more closely.

**Comment by grantfirl** [comment]
@JeffBeck-NOAA Please see https://github.com/NOAA-EMC/fv3atm/pull/516/files#r850486153. Once that is fixed, try to run the GNU tests again and see if it fixes the issue.

**Comment by JeffBeck-NOAA** [comment]
@BrianCurtis-NOAA, can you please kick off the GNU tests again (maybe just a single machine to start)?  I believe I've fixed the problem thanks to help from @grantfirl.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA Please see https://github.com/NOAA-EMC/fv3atm/pull/516/files#r850486153. Once that is fixed, try to run the GNU tests again and see if it fixes the issue.

Thank you, @grantfirl!  This fixed the problem.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA We're back with you on the top of the queue. Please update to the HEAD of develop and update the BL_DATE to todays date and I will get started with the new baselines for the one test.

**Comment by JeffBeck-NOAA** [comment]
Thanks @BrianCurtis-NOAA, I just pulled in the HEAD of develop and updated BL_DATE.

**Comment by BrianCurtis-NOAA** [comment]
Thanks @JeffBeck-NOAA I'm checking Cheyenne intel/gnu AutoRT. There may be a failure for the regional_spp test, but that's OK. Once completed I will know what I need to do either way.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/898113491/20220418174512/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: jet Compiler: intel Job: RT [RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/898113491/20220418174512/ufs-weather-model Please make changes and add the following label back: jet-intel-RT

ecflow issue (will try again):
```
Client::handle_connect: Ran out of end points: connection error( Connection refused 
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/898113491/20220418181513/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Jet is in maintenance today. Will keep checking and run RT's if available before merge.

**Review by junwang-noaa — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
@JeffBeck-NOAA Can you please make the following changes to 2 files to update CI? This does not affect any RT results.
```
diff --git a/tests/ci/ci.sh b/tests/ci/ci.sh
index 0ea1a2f6..9c9804cf 100755
--- a/tests/ci/ci.sh
+++ b/tests/ci/ci.sh
@@ -75,7 +75,7 @@ if [ $BUILD = "true" ]; then
 elif [ $RUN == "true" ]; then
 
   docker volume rm -f DataVolume >/dev/null &&
-    docker run -d --rm -v DataVolume:/tmp minsukjinoaa/input-data:20211210
+    docker run -d --rm -v DataVolume:/tmp minsukjinoaa/input-data:20220414
 
   docker create -u builder -e "CI_TEST=true" -e "USER=builder" \
                 -e "RT_MACHINE=linux.gnu" -e "RT_COMPILER=gnu" \

diff --git a/tests/opnReqTest b/tests/opnReqTest
index e6aa93e0..abee341e 100755
--- a/tests/opnReqTest
+++ b/tests/opnReqTest
@@ -624,7 +624,7 @@ fi
 mkdir -p ${STMP}/${USER}
 NEW_BASELINE=${STMP}/${USER}/FV3_OPNREQ_TEST/OPNREQ_TEST
 RTPWD=${NEW_BASELINE}
-INPUTDATA_ROOT=${INPUTDATA_ROOT:-$DISKNM/NEMSfv3gfs/input-data-20211210}
+INPUTDATA_ROOT=${INPUTDATA_ROOT:-$DISKNM/NEMSfv3gfs/input-data-20220414}
 INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20211113/
 INPUTDATA_ROOT_BMIC=${INPUTDATA_ROOT_BMIC:-$DISKNM/NEMSfv3gfs/BM_IC-20220207}
```

**Comment by JeffBeck-NOAA** [comment]
@MinsukJi-NOAA, CI updates applied.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS Dell P3:
```
+ echo 'Test control_csawmg_debug 072 failed in run_test failed '
Test control_csawmg_debug 072 failed in run_test failed
+ echo 'Test control_csawmg_debug 072 failed in run_test failed '
+ read -r failed_test_name
+ echo 'Test rap_cires_ugwp_debug 085 failed in run_test failed '
Test rap_cires_ugwp_debug 085 failed in run_test failed
+ echo 'Test rap_cires_ugwp_debug 085 failed in run_test failed '
+ read -r failed_test_name
+ echo 'Test rap_unified_ugwp_debug 086 failed in run_test failed '
Test rap_unified_ugwp_debug 086 failed in run_test failed
+ echo 'Test rap_unified_ugwp_debug 086 failed in run_test failed '
+ read -r failed_test_name
+ echo 'Test rap_flake_debug 088 failed in run_test failed '
Test rap_flake_debug 088 failed in run_test failed
+ echo 'Test rap_flake_debug 088 failed in run_test failed '
```

Here's the common error
```
[23] Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_send_ud.c at line 2143: vc_reserve
_area->RNDV_SEND_STATUS == RNDV_SEND_WAITING_FIN_REPLY
```

I'll run overnight maybe a temp issue

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA This is the random failure we have seen on dell recently. This might be related to the I_DAPL setting, we are planning to move to Intel 2021 to get rid of the error.

**Comment by BrianCurtis-NOAA** [comment]
All set for review and merge this AM. All baselines were regenerated on Dell/Cray after a hiccup due to two prod switches causing a delay and all IC's needed to be copied over from Hera to WCOSS.

**Comment by junwang-noaa** [comment]
@grantfirl Would you please commit CCPP PR#892?
@pjpegion Would you please commit stochastic physics PR#57? Thanks

**Comment by grantfirl** [comment]
> @grantfirl Would you please commit CCPP PR#892? @pjpegion Would you please commit stochastic physics PR#57? Thanks

@junwang-noaa https://github.com/NCAR/ccpp-physics/pull/892 has been merged. I gave @JeffBeck-NOAA a heads up to update https://github.com/NOAA-EMC/fv3atm/pull/516.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA it looks like both stochastic physics and ccpp/physics were merged. Please get FV3 updated first then update UFS with stochastic physics and FV3 changes.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA FV3 is updated, please update .gitmodules and the hash's for stochastic-physics and FV3.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA stochastic_physics pointer should be `2b1240f` but it's `00d063e` in your repo. Please fix.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA FV3 pointer should be `70cafa6` but it's `45a9e9b` in your repo. Please fix.

**Comment by BrianCurtis-NOAA** [comment]
@JeffBeck-NOAA Thanks! Looks OK to me now. Merging into UFS.

**Comment by JeffBeck-NOAA** [comment]
@BrianCurtis-NOAA, thanks, I was having problems with the submodules, then realized I needed "git submodule sync".  For some reason, this wasn't required for the fv3atm submodule to update ccpp-physics.

**Pull request merged**
