### PR TITLE
release/public-v1: Python 3 compatibility for CCPP prebuild scripts

### PR DESCRIPTION
**Pull request by climbfuji**
This PR only updates the submodule pointer for fv3atm (and temporarily .gitmodules for code review and testing) for the changes described in https://github.com/NCAR/ccpp-framework/pull/271/files.

Associated PRs:
https://github.com/NCAR/ccpp-framework/pull/271/files
https://github.com/NOAA-EMC/fv3atm/pull/88
https://github.com/ufs-community/ufs-weather-model/pull/92

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
All regression tests passed, logs have been updated in the PR. Ready to merge (starting with ccpp-framework).

[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4381837/rt_hera_intel.log)
[rt_cheyenne_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4381835/rt_cheyenne_gnu.log)
[rt_cheyenne_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4381836/rt_cheyenne_intel.log)

**Comment by junwang-noaa** [comment]
Dom,

So do you want this PR comes in before Anning's? If that is, we need to let
Anning and Dusan know as they are running RT now.

**Comment by climbfuji** [comment]
This is for the public release branch, not master / develop.

**Comment by junwang-noaa** [comment]
Sorry, missed that, so what is the plan to public release tags? I don't
know we are still making code changes to the public release branch.

**Comment by climbfuji** [comment]
I don't know. I was just asked to make this change. @ligiabernardet @arunchawla-NOAA

**Comment by arunchawla-NOAA** [comment]
I was under the impression this would be done at a later date. Is this something you want to accelerate? There is also a patch for ufs-utils/chgres to account for bad temperature data. Want to make sure they are done at the same time.

**Comment by climbfuji** [comment]
It doesn't matter to me as long as the PR doesn't age off. I don't need the Python 3 capability in the public release branch, but I was under the impression that this is requested by the users.

**Comment by climbfuji** [comment]
Thanks for merging the fv3atm PR. This is ready to go - submodule pointer updated, change to .gitmodules reverted.

**Comment by jedwards4b** [comment]
Is the intention to do a minor release of the mrweather-app with this change?  1.0.1?

**Comment by climbfuji** [comment]
> Is the intention to do a minor release of the mrweather-app with this change? 1.0.1?

@jedwards4b there was some back and forth regarding where minor releases and bugfix releases come from. We concluded that it makes sense to create minor releases (1.x) and bugfix releases (1.x.y) from the release/public-v1 branches. This is in line with how EMC does minor releases and considerably less work than creating the minor releases from the development branches. The next major release 2.0.0, of course, will be created from the development branches.

The Python 3 compatibility was considered as "more than just a bugfix", hence we would be creating a 1.1.0 release. There are updates and bugfixes to other components (e.g. UFS_UTILS) that we would like to include in the 1.1.0 release. We will thus wait after merging the Python 3 compatibility updates until we have all the ducks in the row for creating a 1.1.0 release.

Does this sound reasonable to you?

**Comment by jedwards4b** [comment]
@climbfuji This does not sound unreasonable.  Can we create an issue in the mrweather-app repo with a plan and timeline for the 1.1.0 release?

**Comment by ligiabernardet** [comment]
I created an issue on app this morning. Please add there.

**Comment by junwang-noaa** [comment]
I would suggest not to create new release tags too frequently unless there
are urgent issues to fix. We can collect all the  issues during certain
period of time and commit the changes to release branch, then release them,
rather than make a tag for each commit.

**Comment by ligiabernardet** [comment]
Jun, I agree.
I suggest we continue the conversation about future App release in the App
repo
https://github.com/ufs-community/ufs-mrweather-app/issues/149

**Comment by climbfuji** [comment]
Great, @DusanJovic-NOAA @junwang-noaa please merge this PR when it is convenient for you. The only changes were in ccpp-physics, which has been merged already.

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
Thank you!

**Pull request merged**
