### PR TITLE
Dycore semi-implicit solver update 

### PR DESCRIPTION
**Pull request by XiaqiongZhou-NOAA**
## Description

To bring semi-implicit solver update in dynamics to UFS. A new baseline should be created since it will change the results. 

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [X] Changes are expected to the following tests: 
        all regression tests.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on https://github.com/NOAA-EMC/fv3atm/pull/648
- Depends on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/266

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@XiaqiongZhou-NOAA sounds like fv3 dependency PR was tested on wcoss2.  If test result (log file) is attached to the pr, it will speed up the commit process. I mean if available. Either way, we will use jenkins-ci as pre-test.

**Comment by XiaqiongZhou-NOAA** [comment]
I have merged latest UFS to my branch and will rerun the regression tests to create a new baseline on wcoss2.
Please let me know if there are anything else I can do.

**Comment by jkbk2004** [comment]
@XiaqiongZhou-NOAA hold a bit. We are working on #1509. You may try to re-run after #1509 is merged, We can help to re-run on Cheyenne.

**Comment by XiaqiongZhou-NOAA** [comment]
OK, but I am afraid I do not have access to Cheyenne.

**Comment by jkbk2004** [comment]
Sure! We still have time. We will help to test on Cheyenne while jenkin-ci runs. Hera scratch1 disk quota issue this morning. I am trying to clean up a bit. I will keep you posted.

**Comment by jkbk2004** [comment]
@XiaqiongZhou-NOAA We can start working on this pr. #1509 was merged. Can you sync up?

**Comment by XiaqiongZhou-NOAA** [comment]
Synced

**Comment by jkbk2004** [comment]
[RegressionTests_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11336978/RegressionTests_cheyenne.intel.log)
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11336979/RegressionTests_cheyenne.gnu.log)

**Comment by XiaqiongZhou-NOAA** [comment]
[RegressionTests_wcoss2.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11337506/RegressionTests_wcoss2.intel.log)

**Comment by XiaqiongZhou-NOAA** [comment]
"Test 008 compile FAIL" in cheyenne.intel.log. Any issues there?

**Comment by jkbk2004** [comment]
> "Test 008 compile FAIL" in cheyenne.intel.log. Any issues there?

cpld_control_p8_faster was turned off on cheyenne. I think we should turn off the 008 build on cheyenne as well.

**Comment by zach1221** [comment]
@jkbk2004 cpld_control_nowave_noaero_p8 failed the ORT debug test, when running jenkins-ci against this PR. Everything else passed. I'll look into the failure.

**Comment by jkbk2004** [comment]
@zach1221 we need a decision about jenkins-ci cpld_control_nowave_noaero_p8. Can you give a try to run ort cpld_control_nowave_noaero_p8 on here or hera?

**Comment by zach1221** [comment]
@jkbk2004 Yes, I'll test again on Hera now.

**Comment by zach1221** [comment]
@jkbk2004 cpld_control_nowave_noaero_p8 passed ORTs using both intel/gnu compilers on Hera.

**Comment by jkbk2004** [comment]
all test are done. we can start merging process. thanks @zach1221 for following with ORT.

**Comment by jkbk2004** [comment]
@XiaqiongZhou-NOAA fv3 pr was merged. Can you update hash and revert change in gitmodules? correct hash is https://github.com/NOAA-EMC/fv3atm/commit/e0d95b11393585e8b88f00664030a27964645b98

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
