### PR TITLE
fix NSSL MP init issue when initialized from other microphysics schemes

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [ ] Add list of all failed regression tests in "Regression Tests" section.

### Description

This is the fix from Ted Mansell @MicroTed on NSSL MP initialization to check if there is missing number of concentration for any non-zero hydrometers mixing ratio. NSSL MP will calculate N from mixing ratio in the first timestep if missing value is found. This fix will guarantee that NSSL MP enters the correct warm/cold start initializations.
### Commit Message

fix NSSL MP init issue when initialized from other microphysics schemes

### Priority
- [x] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [x] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Blocking Dependencies

- https://github.com/NOAA-EMC/fv3atm/pull/764
- https://github.com/ufs-community/ccpp-physics/pull/157
### Git Issues Fixed By This PR

https://github.com/ufs-community/ufs-weather-model/issues/2100

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- NOAA-EMC/fv3atm/pull/764
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [ ] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by JiliDong-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13977633/RegressionTests_hera.log)

**Comment by jkbk2004** [comment]
@JiliDong-NOAA can you sync up branches? Once branches are synced up, I will try to follow up to combine this PR to #2104 at physics PR level.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA can you sync up branches? Once branches are synced up, I will try to follow up to combine this PR to #2104 at physics PR level.

Thanks. All submodules synced up.

**Comment by BrianCurtis-NOAA** [comment]
@JiliDong-NOAA EPIC would like to get to this PR next. Once a merge of the current UFSWM PR completes, please make sure that you updates hashes from FV3 once that is updated.

**Comment by zach1221** [comment]
@JiliDong-NOAA Please sync up your branch. We'd like to begin testing against this PR.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA Please sync up your branch. We'd like to begin testing against this PR.

Done.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I think we're ready to work this PR. I'm going to start my tests.

**Comment by zach1221** [comment]
Hercules is being a bit slow today. One test left pending, but it may be a while longer.

**Comment by zach1221** [comment]
Testing is complete. Let's begin with the merging process on ccpp-physics [#157](https://github.com/ufs-community/ccpp-physics/pull/157)

**Comment by JiliDong-NOAA** [comment]
.gitmodules reverted and FV3 updated

**Comment by zach1221** [comment]
@JiliDong-NOAA fv3atm PR is merged. Please update the submodule hash and revert the change in .gitmodule url.
hash: https://github.com/NOAA-EMC/fv3atm/commit/ef04de2c2a2109dbe2cc6992f6658b7af2875002

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA fv3atm PR is merged. Please update the submodule hash and revert the change in .gitmodule url. hash: [NOAA-EMC/fv3atm@ef04de2](https://github.com/NOAA-EMC/fv3atm/commit/ef04de2c2a2109dbe2cc6992f6658b7af2875002)

Done.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
