### PR TITLE
Check-in Jenkins Docker ORT CI

### PR DESCRIPTION
**Pull request by jessemcfarland**
# PR Checklist

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR adds a Jenkins pipeline to this repository that enables the Docker ORT CI workflow on the EPIC Jenkins server.

## Testing

To test the pipeline, a new label, `jenkins-ci` must be created and added to this PR. Subsequent builds can be triggered by adding a comment with the string `REBUILD`.

### CODE REVIEW

**Comment by jessemcfarland** [comment]
REBUILD

**Comment by jessemcfarland** [comment]
REBUILD

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 is this ready to go now?

**Comment by jkbk2004** [comment]
> @jkbk2004 is this ready to go now?
I was about to add reviewers. We can start reviews after seeing ORT run.

**Comment by BrianCurtis-NOAA** [comment]
Just noting: If there is supposed to be details in the ORT task, it comes back with a 404 error.

**Comment by flampouris** [comment]
@jessemcfarland please communicate the log file to the appropriate members.

**Comment by jkbk2004** [comment]
@jessemcfarland can you attach the log file output to this PR conversation? so that reviewers can take a look.

**Comment by BrianCurtis-NOAA** [comment]
We can merge this in as there is no change to the running of the model/physics etc.

What I would encourage is that the details for Jenkins tasks be made available to those in the public as this whole project is a community one. If this is possible, but not for a while, then it would be good to allow me to see the logs as I am responsible for operational targets of the UFSWM.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by jessemcfarland** [comment]
> We can merge this in as there is no change to the running of the model/physics etc.
> 
> What I would encourage is that the details for Jenkins tasks be made available to those in the public as this whole project is a community one. If this is possible, but not for a while, then it would be good to allow me to see the logs as I am responsible for operational targets of the UFSWM.

@BrianCurtis-NOAA I'm working on gathering the logs now. I'll attach them to the PR shortly. We're still discussing the access model for Jenkins including access to the logs for PRs.

**Comment by jessemcfarland** [comment]
Here are the Jenkins logs for the last pipeline run: [ufs-weather-model_PR-1411_jenkins_logs.zip](https://github.com/ufs-community/ufs-weather-model/files/9708831/ufs-weather-model_PR-1411_jenkins_logs.zip)

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Should the label be removed once the job has started?

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA Best option is to run job when the label is added. Once jobs runs, jenkins will remove the label. And iterative steps ... Will come with a final solution for triggering mechanism.

**Pull request merged**
