### PR TITLE
Feature/refconv

### PR DESCRIPTION
**Pull request by ericaligo-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13420648/RegressionTests_hera.log)
[RegressionTests_hera_newbaseline.log](https://github.com/ufs-community/ufs-weather-model/files/13420650/RegressionTests_hera_newbaseline.log)
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
@RuiyuSun and I compute convective reflectivity for Thompson or NSSL microphysics and with GF deep, shallow or SAS deep convection. I removed the calculation that was in cu_gf_driver_post.F90 and cu_gf_driver_post.meta, and associated parameters, and added the code to GFS_MP_generic_post.F90. The 3D refl_10cm array will be changed only for configurations running with deep and/or shallow convection. In the process of creating a new baseline. I had to modify regional.nml.IN and change imfhalcnv and imfdeepconv from 2 to -1 otherwise the code would try to calculate convective reflectivity despite no calls for deep/shallow convection.

https://github.com/ufs-community/ccpp-physics/pull/129
https://github.com/NOAA-EMC/fv3atm/pull/720
https://github.com/ufs-community/ufs-weather-model/issues/1968
https://github.com/NOAA-EMC/fv3atm/issues/716
https://github.com/ufs-community/ccpp-physics/issues/123

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
FAILED TESTS: 
132 hafs_regional_atm_thompson_gfdlsf_intel failed in check_result
hafs_regional_atm_thompson_gfdlsf_intel 132 failed in run_test

The above configuration failed because lradar = .true. and both imfshalcnv and imfdeepcnv=.true. The failure was due to differences in all reflectivity fields as to be expected. Other configurations that set lradar =.true. did not fail because imfshalcnv and imfdeepcnv=.false. If there's no shallow or deep convection being used, the reflectivity fields will not be modified.
below -->
<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by grantfirl** [comment]
@ericaligo-NOAA Please remember to attach your RegressionTest_hera.log in the description that shows the expected failures (which RTs should require new baselines).

**Comment by grantfirl** [comment]
> @ericaligo-NOAA Please remember to attach your RegressionTest_hera.log in the description that shows the expected failures (which RTs should require new baselines).

I think that an RT log from orion should suffice too, if you already have that.

**Comment by jkbk2004** [comment]
@ericaligo-NOAA can you sync up your branch to prepare to commit the pr?

**Comment by DeniseWorthen** [comment]
@ericaligo-NOAA Could you please clarify which test baselines will change? You say "Any RT that outputs refl_10cm", but CMs don't know which tests that might be.

In your first attached log (not the one with "new baseline") only these tests show as failed:

```
FAILED TESTS: 
132 hafs_regional_atm_thompson_gfdlsf_intel failed in check_result
hafs_regional_atm_thompson_gfdlsf_intel 132 failed in run_test
```

Is that correct?

**Comment by ericaligo-NOAA** [comment]
Thanks for pointing that out! My statement is not correct, and you're right
that the only failure was the one you noted. Looking at the results it was
related only to the reflectivity, which was to be expected. For this
particular configuration that failed it was because lradar = .true. and it
was running with deep and shallow convection. The other configurations that
had lradar = .true., which are all/mostly regional applications, were not
running with convection (imfshalcnv = imfdeepcnv = false). If there's no
convection being run, then the reflectivity fields will not be different.
Hope this makes sense.

Eric

**Comment by ericaligo-NOAA** [comment]
Done.

**Comment by DeniseWorthen** [comment]
@ericaligo-NOAA Thanks, that does make sense. Would you please edit the PR to clarify that only this test is impacted because of the combination of lradar=.true. + deep and shallow convection "on".

**Comment by ericaligo-NOAA** [comment]
Done!

**Comment by zach1221** [comment]
The jenkins-ci ORTs did complete and pass however it failed at the end during the process that generates the push notification I think, so it never notified. Attached are the logs.


[Jenkins-ci 1996 ORTs.pdf](https://github.com/ufs-community/ufs-weather-model/files/13518499/Jenkins-ci.1996.ORTs.pdf)

**Comment by zach1221** [comment]
Testing complete, we can start the merging process.

**Comment by zach1221** [comment]
@jkbk2004 if you don't mind. Can you revert the fv3atm .gitmodule url and update the hash: https://github.com/NOAA-EMC/fv3atm/commit/1f7af4b8abc69d6f8c9a435804ea55ba18d18df2

**Comment by BrianCurtis-NOAA** [comment]
> @jkbk2004 if you don't mind. Can you revert the fv3atm .gitmodule url and update the hash: [NOAA-EMC/fv3atm@1f7af4b](https://github.com/NOAA-EMC/fv3atm/commit/1f7af4b8abc69d6f8c9a435804ea55ba18d18df2)

The .gitmodules edit was not in what was committed to fv3atm develop branch, just need to update to the develop fv3atm hash.

**Review by sadeghitabas — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
