### PR TITLE
update GF for RRFS 2023 HWT SFE

### PR DESCRIPTION
**Pull request by haiqinli**
## Description
1). A update of the Grell-Freitas (GF) convection for RRFS;
2). A update of RUC LSM to use BNU soil property for RRFS;
3). This is an urgent PR for RRFS 2023 HWT SFE, which will start on May 1st, 2023;
4). related PRs for fv3atm and ccpp-physics 
    fv3atm: https://github.com/NOAA-EMC/fv3atm/pull/644
    ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/64

### Input data additions/changes
- [ V] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [ V] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [V ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ V] Link PR's from all sub-components involved
- [ V] Confirm reviews completed in sub-component PR's
- [ V] Add all appropriate labels to this PR.
- [ V] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ V] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Testing Day Checklist:

- [ V] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ V] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [V ] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by grantfirl** [comment]
@haiqinli Could you add a list of the tests that are expected to fail? I see that you have the new baseline directories listed in https://github.com/NOAA-EMC/fv3atm/pull/644 and that you have committed successful RT logs, but we need to know which RTs fail. I suppose if you committed the RT logs that have a list of failures, that would have worked, but I think that the UFS code managers just want a list of the expected RT failures listed in the description or the comment section here.

**Comment by haiqinli** [comment]
@grantfirl Sure, I am starting to do a regression test against the original baseline, and will add a list of the tests that are expected to fail when it is done. Thanks.

**Comment by grantfirl** [comment]
@jkbk2004 This PR is a high priority due to it being needed for the RRFS and the HWT spring experiment. Could this be added to the queue after https://github.com/ufs-community/ufs-weather-model/pull/1669?

**Comment by haiqinli** [comment]
@grantfirl The following lists the tests are expected to fail on Hera with Intel compiler. Thanks.

fail_test_057  fail_test_063  fail_test_073  fail_test_085  fail_test_100  fail_test_105  fail_test_112  fail_test_119
fail_test_058  fail_test_065  fail_test_074  fail_test_096  fail_test_101  fail_test_106  fail_test_113  fail_test_120
fail_test_059  fail_test_066  fail_test_075  fail_test_097  fail_test_102  fail_test_107  fail_test_114  fail_test_121
fail_test_060  fail_test_067  fail_test_083  fail_test_098  fail_test_103  fail_test_110  fail_test_115
fail_test_062  fail_test_072  fail_test_084  fail_test_099  fail_test_104  fail_test_111  fail_test_118

**Comment by jkbk2004** [comment]
> @jkbk2004 This PR is a high priority due to it being needed for the RRFS and the HWT spring experiment. Could this be added to the queue after #1669?

@grantfirl sure, I think we can start working on this pr today. will keep you posted.

**Comment by FernandoAndrade-NOAA** [comment]
@haiqinli Could you sync your branch with the latest develop? I can get started on jenkins-ci after that. Thank you

**Comment by DeniseWorthen** [comment]
@haiqinli The list of "fail_test" you provided doesn't tell us which actual test failed. Could you provide the list of the failed tests by name?

**Comment by jkbk2004** [comment]
@haiqinli @grantfirl since the PR needs urgency, can you sync up and respond to @DeniseWorthen's comment ? I see about 35 cases changing results. Those are the cases that use GF scheme and RUC LSM, right?

**Comment by haiqinli** [comment]
@jkbk2004 @DeniseWorthen Yes, the cases with GF convection and RUC LSM are changed. I am rerunning the regression test, and will add the detailed cases when it is done. Thanks.

**Comment by haiqinli** [comment]
@FernandoAndrade-NOAA My branch has been synced with the latest develop. Thanks.

**Comment by haiqinli** [comment]
@grantfirl @DeniseWorthen @jkbk2004 After syncing all the components, the compiling of the regression test failed (/scratch1/BMC/gsd-fv3-dev/NCEPDEV/stmp4/Haiqin.Li/Haiqin.Li/FV3_RT/rt_33652/compile_001.log.0). Would you like to have a look and give me some suggestions? Thanks.

**Comment by FernandoAndrade-NOAA** [comment]
@haiqinli The current hashes used in the ufs weather model for ww3 and upp are:
ww3
```081d5a64f205caac7f920acec6004b1a184f5709```
upp
```dccb32176930676ef2a258eb65571ab4e3f7e7a4```
Please adjust to point to those hashes, thank you

**Comment by haiqinli** [comment]
@FernandoAndrade-NOAA Yes, it works after pointing to the correct hashes of upp and WW3. Thanks.

**Comment by haiqinli** [comment]
@grantfirl @DeniseWorthen @jkbk2004 @FernandoAndrade-NOAA 
The following lists the tests are expected to fail on Hera with Intel compiler. Thanks.
The regression test run directory is /scratch1/BMC/gsd-fv3-dev/NCEPDEV/stmp4/Haiqin.Li/Haiqin.Li/FV3_RT/rt_200304.

hrrr_control_2threads.err.0  rap_flake_debug.err.0                    regional_spp_sppt_shum_skeb.err.0
hrrr_control_debug.err.0     rap_lndp_debug.err.0                     rrfs_conus13km_hrrr_warm_debug.err.0
hrrr_control_decomp.err.0    rap_noah_debug.err.0                     rrfs_conus13km_hrrr_warm.err.0
hrrr_control.err.0           rap_noah_sfcdiff_cires_ugwp_debug.err.0  rrfs_smoke_conus13km_hrrr_warm_2threads.err.0
rap_2threads.err.0           rap_progcld_thompson_debug.err.0         rrfs_smoke_conus13km_hrrr_warm_debug_2threads.err.0
rap_cires_ugwp_debug.err.0   rap_sfcdiff_debug.err.0                  rrfs_smoke_conus13km_hrrr_warm_debug.err.0
rap_control_debug.err.0      rap_sfcdiff_decomp.err.0                 rrfs_smoke_conus13km_hrrr_warm.err.0
rap_control.err.0            rap_sfcdiff.err.0                        rrfs_smoke_conus13km_radar_tten_warm.err.0
rap_decomp.err.0             rap_unified_drag_suite_debug.err.0
rap_diag_debug.err.0         rap_unified_ugwp_debug.err.0

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA Yes, it works after pointing to the correct hashes of upp and WW3. Thanks.

Looks like WW3 is good to go, but your UPP is still pointing to 87a7542, please point to
```dccb32176930676ef2a258eb65571ab4e3f7e7a4```

**Comment by haiqinli** [comment]
@FernandoAndrade-NOAA Thanks. The UPP hash has been pointed to dccb32176930676ef2a258eb65571ab4e3f7e7a4. Thanks.

**Comment by jkbk2004** [comment]
So, basically all rap,  rrfs, hrrr cases are baseline change cases. I am attaching @haiqinli 's hera log files as pre-test results.
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11264910/RegressionTests_hera.intel.log)
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11264911/RegressionTests_hera.gnu.log)

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA I'm running ci for this now

**Comment by BrianCurtis-NOAA** [comment]
Looks like the FV3 PR was not approved yet.

**Comment by FernandoAndrade-NOAA** [comment]
Please see the attached file for jenkins-ci logs, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1713 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11268168/ufs-weather-model.ort-docker-pipeline.PR-1713.1.Console.Jenkins.pdf)

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1314245435/20230418213710/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_67659
Test hafs_regional_atm_ocn 084 failed in run_test failed 
Test hafs_regional_atm_wav 085 failed in run_test failed 
Test hafs_regional_atm_ocn_wav 086 failed in run_test failed 
Test hafs_global_multiple_4nests_atm 090 failed in run_test failed 
Test hafs_regional_storm_following_1nest_atm_ocn_wav 096 failed in run_test failed 
Test hafs_regional_docn 097 failed in run_test failed 
Test hafs_regional_docn_oisst 098 failed in run_test failed 
Test hafs_regional_datm_cdeps 099 failed in run_test failed 
Test atmaero_control_p8 117 failed in run_test failed 
Test atmaero_control_p8_rad 118 failed in run_test failed 
Test atmaero_control_p8_rad_micro 119 failed in run_test failed 
Test compile_008 failed in run_compile failed 
Test compile_029 failed in run_compile failed 
Test compile_030 failed in run_compile failed 
Test compile_032 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1314245435/20230419033014/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1314245435/20230419042022/ufs-weather-model
[RT] Error: Test cpld_control_p8 048 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA I am trying to manually run those failed cases on hera.gnu and cheyenne.intel.

**Comment by jkbk2004** [comment]
I was checking jet. Quite slurm input/output issue: "/var/spool/slurmd/job26295598/slurm_script: line 0: echo: write error: Input/output error". I will let all jobs go thru and check again. Sounds like we need more time.

**Comment by jkbk2004** [comment]
BTW, clearly file system issue on jet, I think.

**Comment by jkbk2004** [comment]
all tests are done. we can start merging process.

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Comment by jkbk2004** [comment]
@haiqinli fv3 pr was merged. can you update hash and revert change in gitmodules?

**Comment by jkbk2004** [comment]
@haiqinli correct hash is https://github.com/NOAA-EMC/fv3atm/commit/aed060737ad8e65b4a101e5c61724fb8adbe94f5

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
