### PR TITLE
update MOM6 to remove compiling warning

### LINKED ISSUE #2196: update MOM6 to eliminate compiling warning
Thanks for @marshallward, the updated code will eliminate compiling warning for MOM6 in UFS

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

This updated MOM6 code will eliminate all compiling warning

### Commit Message:

Please provide concise information for The UFS-WM and/or each sub-component:
Please delete what is not needed.
  * MOM6 - update MOM6 code to eliminate all compiling warning 

### Priority:

* Normal

### UFSWM:
close #2196 

### Sub component Pull Requests:
MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/128
MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/130

### UFSWM Blocking Dependencies:
* None

---
## Changes
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jiandewang** [comment]
@jkbk2004 this is a very simple PR so it can be combined with other PR

**Comment by jiandewang** [comment]
wcoss2 run log: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_wcoss2.log
HERA run log: https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_hera.log

**Comment by jiandewang** [comment]
results from "grep warning err" contain no any MOM6 related stuff

grep warning err
/lfs/h2/emc/ptmp/jiande.wang/FV3_RT/rt_22400/compile_s2s_intel/build_fv3_s2s_intel/FV3/ccpp/physics/ccpp_FV3_GFS_v17_coupled_p8_stochastics_cap.F90(60): warning #5462: Global name too long, shortened from: ccpp_fv3_gfs_v17_coupled_p8_stochastics_cap_mp_FV3_GFS_V17_COUPLED_P8_STOCHASTICS_TSFINAL_CAP to: pp_fv3_gfs_v17_coupled_p8_stochastics_cap_mp_FV3_GFS_V17_COUPLED_P8_STOCHASTICS_TSFINAL_CAP
/lfs/h2/emc/ptmp/jiande.wang/FV3_RT/rt_22400/compile_s2s_intel/build_fv3_s2s_intel/FV3/ccpp/physics/ccpp_FV3_GFS_v17_coupled_p8_cap.F90(37): warning #5462: Global name too long, shortened from: ccpp_fv3_gfs_v17_coupled_p8_stochastics_cap_mp_FV3_GFS_V17_COUPLED_P8_STOCHASTICS_TSFINAL_CAP to: pp_fv3_gfs_v17_coupled_p8_stochastics_cap_mp_FV3_GFS_V17_COUPLED_P8_STOCHASTICS_TSFINAL_CAP
/lfs/h2/emc/ptmp/jiande.wang/FV3_RT/rt_22400/compile_s2s_intel/build_fv3_s2s_intel/FV3/ccpp/physics/ccpp_static_api.F90(42): warning #5462: Global name too long, shortened from: ccpp_fv3_gfs_v17_coupled_p8_stochastics_cap_mp_FV3_GFS_V17_COUPLED_P8_STOCHASTICS_TSFINAL_CAP to: pp_fv3_gfs_v17_coupled_p8_stochastics_cap_mp_FV3_GFS_V17_COUPLED_P8_STOCHASTICS_TSFINAL_CAP
/var/tmp/pbs.121904511.cbqs01/ifortvHEhMY.i90: warning #6178: The return value of this FUNCTION has not been defined.   [MY_POINTER]
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.62, needed by /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.so, may conflict with libjpeg.so.9

**Comment by zach1221** [comment]
Hi, @jiandewang , are you able to provide a commit message, in the template above, for your code changes in this PR?

**Comment by jiandewang** [comment]
> Hi, @jiandewang , are you able to provide a commit message, in the template above, for your code changes in this PR?

just added that

**Comment by zach1221** [comment]
Hi, @jiandewang can you sync up your PR branch here?

**Comment by jiandewang** [comment]
> Hi, @jiandewang can you sync up your PR branch here?

just sync-ed

**Comment by jkbk2004** [comment]
merged with #2202

**Pull request closed without merging**
