### PR TITLE
Third reconciliation PR from production/RRFS.v1

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:
This is mainly work from @AndersJensen-NOAA. This PR is identical to https://github.com/ufs-community/ufs-weather-model/pull/2161, but targets develop instead of the RRFSv1 release branch.

This PR is the first of many that will modernized, modularize, and streamline Thompson-Eidhammer microphysics.

This PR includes:

The addition of parameterized kind: REAL -> real(kind_phys)
Consistent indentation
Removal of GOTO statements
Add physical constant metadata needed by Thompson MP

### Commit Message:

```
* UFSWM - Thompson-Eidhammer microphysics code formatting
  * FV3 - Thompson-Eidhammer microphysics code formatting
    * ccpp-physics - Thompson-Eidhammer microphysics code formatting
```

### Priority:

* High: Needed for SRW App

### UFSWM:

* None

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/882
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/229

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

All tests that use Thompson MP will have non bit-for-bit results due to high significant digit changes in physical constants. There is no substantial change in results as tested by @AndersJensen-NOAA in https://github.com/ufs-community/ufs-weather-model/pull/2161.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@grantfirl can you sync up branch? we can start working on this pr.

**Comment by grantfirl** [comment]
> @grantfirl can you sync up branch? we can start working on this pr.

@jkbk2004 OK, should be good to go.

**Comment by FernandoAndrade-NOAA** [comment]
Changes also occurred in intelllvm cases + `control_c48_lnd_iau_intel` across Hera, Gaea, and Jet on my side. The same changes are likely for Orion and Hercules as well. Recreating baselines for those cases now.

**Review by zach1221 — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
I would like to reiterate my request that someone from EMC needs to review all PR's before merge. I was in the middle of my review when it was merged.

**Comment by jkbk2004** [comment]
All code changes are pretty much at physics level and all approved ok at sub components.

**Pull request merged**
