### PR TITLE
Smoke/Dust updates for RRFS code freeze

### PR DESCRIPTION
**Pull request by haiqinli**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

1. Include convective transport and wet removal of smoke/dust in the GF convection.
2. A new dry deposition option for smoke/dust.
3. Update the diurnal cycle of biomass burning emissions.
4. Clean the smoke code.

## Commit Message

This smoke/dust update PR is for the RRFS code freeze.

### Subcomponent Pull Requests

- closes ufs-community/ccpp-physics/pull/135
- closes NOAA-EMC/fv3atm/pull/728

### Blocking Dependencies

"None"

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
FAILED TESTS:
conus13km_control_intel
conus13km_debug_intel
conus13km_debug_qr_intel
conus13km_debug_2threads_intel
conus13km_radar_tten_debug_intel
conus13km_control_gnu
conus13km_debug_gnu
conus13km_debug_qr_gnu
conus13km_debug_2threads_gnu
conus13km_radar_tten_debug_gnu

<details><summary>Tests effected by changes in this PR:</summary>
The above RT's will be changed by the code updates. Since the inclusion of convective transport and wet removal of smoke/dust; a new dry deposition; and updated smoke emission inputs. The log file of regression test run is attached.
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13540338/RegressionTests_hera.log)

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@haiqinli Please check the code for errors. Your Hera log indicates the listed tests failed to run, not that the results did not compare.

**Comment by haiqinli** [comment]
> @haiqinli Please check the code for errors. Your Hera log indicates the listed tests failed to run, not that the results did not compare.

Thanks for pointing this out. We introduced a new namelist option "ebb_dcycle" to support fire emission for different mode. ebb_dcycle=1 is the original option (we call it retro run mode) to read hourly emission and fire radiation power, and corresponds to the fire emission input data in the regression test run case. ebb_dcycle=2 is the new option (we call it forecast mode) to read daily mean fire emission, fire radiation power, fire duration and fire potential, and calculate the diurnal cycle of biomass burning emission within RRFS-SD. ebb_dcycle=2 will be used for RRFS-A parallel run, and was set as default configuration in the code. Since ebb_dcyle is not available in the input namelist of the regression test run cases, and the fire emission input data in the regression test run cases is for ebb_dcycle=1. Thus those regression test runs failed. I will update the code to use ebb_dcycle=1 as default configuration, and rerun the regression test. Will update the log file when the regression test rerun is done. Thanks.

**Comment by DeniseWorthen** [comment]
@haiqinli Thanks. You also note that new input-data is required. Is that correct? If yes, please provide the location where the data is currently staged so that code managers can transfer it to all the platforms.

You indicate this is for a code freeze. Do you have date when this will be required? We need to know if this is a high priority PR.

**Comment by haiqinli** [comment]
@DeniseWorthen Yes, we need to update the fire emission input data. We are processing a real case for conus13km, and will update when we make it done. Yes, this PR is for the RRFSv1 code freeze. We will also update when we get the exact required date. Thanks.

**Comment by DeniseWorthen** [comment]
@haiqinli We're adding a Commit Message requirement to the PRs. Please add one in the space provided.

**Comment by haiqinli** [comment]
@DeniseWorthen We have updated the PR to address UFS code reviewers's comments, and rerun the regression test run. If we run the forecast mode for diurnal cycle of plume, the vegetation fraction from RUC LSM is required, but it is not available in the conus13km regression test cases. So I set the retro mode with hourly fire emission as default for the conus13km regression test cases, and we don't need to update the input files. The log file of regression test run is attached. Thanks.
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13720478/RegressionTests_hera.log)

**Comment by DeniseWorthen** [comment]
@haiqinli Thanks. Do you have a target date this is required by?

**Comment by haiqinli** [comment]
@DeniseWorthen It would be great if we can process this PR this week. Thanks.

**Comment by DeniseWorthen** [comment]
@jkbk2004 Please note the requested priority for this PR.

**Comment by jkbk2004** [comment]
Thanks for reminding! Several priority PRs are going-on. #2044 is on-going.  I think we can commit this pr tomorrow.

**Comment by zach1221** [comment]
@haiqinli I think we're going to begin regression testing on this PR next. Can you please sync up your branch?

**Comment by jkbk2004** [comment]
@haiqinli can you sync up the branches? so we can work on this pr.

**Comment by haiqinli** [comment]
@jkbk2004 @zach1221 Yes, I am starting to sync my branch, and will update when it is done. Thanks.

**Comment by zach1221** [comment]
@haiqinli did you intend to close this PR?

**Comment by haiqinli** [comment]
@zach1221 No. I just synced with the authoritative repository.

**Comment by haiqinli** [comment]
@jkbk2004 @zach1221 The branches have been synced up. Thanks.

**Comment by jkbk2004** [comment]
@haiqinli can you re-open https://github.com/NOAA-EMC/fv3atm/pull/728 ?

**Comment by haiqinli** [comment]
@jkbk2004 Reopened. Thanks.

**Comment by zach1221** [comment]
On Hercules, I'm getting segmentation faults - invalid memory reference on four gnu cases: rap_control_gnu, rap_sfcdiff_gnu, rap_control_dyn32_phy32_gnu, and rap_control_dyn64_phy32_gnu. 
/work2/noaa/stmp/zshrader/stmp/zshrader/FV3_RT/rt_3090376

**Comment by jkbk2004** [comment]
> On Hercules, I'm getting segmentation faults - invalid memory reference on four gnu cases: rap_control_gnu, rap_sfcdiff_gnu, rap_control_dyn32_phy32_gnu, and rap_control_dyn64_phy32_gnu. /work2/noaa/stmp/zshrader/stmp/zshrader/FV3_RT/rt_3090376

rap cases are not supposed to be affected by this pr.

**Comment by zach1221** [comment]
> > On Hercules, I'm getting segmentation faults - invalid memory reference on four gnu cases: rap_control_gnu, rap_sfcdiff_gnu, rap_control_dyn32_phy32_gnu, and rap_control_dyn64_phy32_gnu. /work2/noaa/stmp/zshrader/stmp/zshrader/FV3_RT/rt_3090376
> 
> rap cases are not supposed to be affected by this pr.

I'll test them against the develop branch.

**Comment by haiqinli** [comment]
> > On Hercules, I'm getting segmentation faults - invalid memory reference on four gnu cases: rap_control_gnu, rap_sfcdiff_gnu, rap_control_dyn32_phy32_gnu, and rap_control_dyn64_phy32_gnu. /work2/noaa/stmp/zshrader/stmp/zshrader/FV3_RT/rt_3090376
> 
> rap cases are not supposed to be affected by this pr.

Yes, the rap cases should not be affected by this pr.

**Comment by jkbk2004** [comment]
@haiqinli @grantfirl @SamuelTrahanNOAA @Qingfu-Liu Can you check if this pr might have some impact on the call cu_gf_deep_run() for middle GF convection cu_gf_driver.F90 line 769 and 856 ? Sounds like memory issue is triggered there.

**Comment by jkbk2004** [comment]
> @haiqinli @grantfirl @SamuelTrahanNOAA @Qingfu-Liu Can you check if this pr might have some impact on the call cu_gf_deep_run() for middle GF convection cu_gf_driver.F90 line 769 and 856 ? Sounds like memory issue is triggered there.

Note that develop branch has no problem.

**Comment by jkbk2004** [comment]
> @haiqinli @grantfirl @SamuelTrahanNOAA @Qingfu-Liu Can you check if this pr might have some impact on the call cu_gf_deep_run() for middle GF convection cu_gf_driver.F90 line 769 and 856 ? Sounds like memory issue is triggered there.

@hu5970 FYI: all other tests pass except a few Hercules/gnu rap cases.

**Comment by SamuelTrahanNOAA** [comment]
I see many big local arrays in cu_gf_deep.F90. One of their dimensions is nchem, which may be zero. If smoke is enabled, nchem=3. What does the Intel and GNU compiler do when a dimension is 0? Do they allocate the array with a dimension of 1? Or is it not allocated at all?

**Comment by haiqinli** [comment]
Actually I also sent the nchem as input to the MYNN PBL, and defined some local arrays in module_bl_mynn.F90.

**Comment by haiqinli** [comment]
In the develop branch, I used the following,
1448     integer              :: nchem = 3       !< number of prognostic chemical species (vertically mixied)
1449     integer              :: ndvel = 3       !< number of prognostic chemical species (which are deposited, usually =nchem)

In this PR, I changed it as, 
1458     integer              :: nchem           !< number of prognostic chemical species (vertically mixied)
1459     integer              :: ndvel           !< number of prognostic chemical species (which are deposited, usually =nchem)

@SamuelTrahanNOAA Maybe we should change it back?

**Comment by SamuelTrahanNOAA** [comment]
If you're passing in the correct value for nchem, it should be better than 3. When smoke/dust is disabled, nchem=0, and the model *should* use less memory.

You could try hard-coding it to 3 and see what happens.

**Comment by haiqinli** [comment]
@jkbk2004 Would you like to try hard-coding nchem=3 in ccpp/data/GFS_typedefs.F90 for Hercules/gnu? Or should I update the PR with hard-coding nchem=3? Thanks.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - Can you tell us how to reproduce the problem?

**Comment by jkbk2004** [comment]
@haiqinli try to update on physics feature branch. I will try to manually update on hercules/gnu. @SamuelTrahanNOAA the issue only pops up on hercules/gnu. If you don't have access to hercules, I think I will follow up to check on hercules.

**Comment by jkbk2004** [comment]
> @jkbk2004 Would you like to try hard-coding nchem=3 in ccpp/data/GFS_typedefs.F90 for Hercules/gnu? Or should I update the PR with hard-coding nchem=3? Thanks.

@haiqinli I tried to set in GFS_typedefs.F90
```
    integer              :: nchem = 3           !< number of prognostic chemical species (vertically mixied)
    integer              :: ndvel = 3          !< number of prognostic chemical species (which are deposited, usually =nchem)
```
But I see still same issue.

**Comment by haiqinli** [comment]
> hercules/gnu.

@jkbk2004 Thank you very much for trying this. I am also checking the code, and will update if I can find something.

**Comment by DusanJovic-NOAA** [comment]
Regardless of the value of nchem and ndvel (0 or 3) the arrays like chem3d are never allocated if Model%rrfs_sd is false, which probably is for these rap tests. In that case status of chem3d pointer in disassociated. Disassociated pointer should not be passed to dummy array (which is not pointer itself) with explicit shape, like chem3d is in cu_gf_deep_run.

**Comment by SamuelTrahanNOAA** [comment]
> Regardless of the value of nchem and ndvel (0 or 3) the arrays like chem3d are never allocated if Model%rrfs_sd is false, which probably is for these rap tests. In that case status of chem3d pointer in disassociated. Disassociated pointer should not be passed to dummy array (which is not pointer itself) with explicit shape, like chem3d is in cu_gf_deep_run.

@haiqinli - I believe @DusanJovic-NOAA's suggestion is to change the dimensions to `:`

**Comment by haiqinli** [comment]
> > Regardless of the value of nchem and ndvel (0 or 3) the arrays like chem3d are never allocated if Model%rrfs_sd is false, which probably is for these rap tests. In that case status of chem3d pointer in disassociated. Disassociated pointer should not be passed to dummy array (which is not pointer itself) with explicit shape, like chem3d is in cu_gf_deep_run.
> 
> @haiqinli - I believe @DusanJovic-NOAA's suggestion is to change the dimensions to `:`

@SamuelTrahanNOAA @DeniseWorthen Thank you very much for your suggestions. I will update the feather branch with dimension to ":".

**Comment by jkbk2004** [comment]
@haiqinli keep me posted. I will check on hercules.

**Comment by haiqinli** [comment]
@jkbk2004 I have updated the feature brach of ccpp-physics and fv3atm. Thanks.

**Comment by DeniseWorthen** [comment]
@haiqinli Did you commit your changes? You say you've updated your branch, but I don't see any update here.

**Comment by haiqinli** [comment]
@DeniseWorthen I am sorry that only the fv3atm and ccpp-physics were updated. The feature branch of ufs-weather-model is just updated. Thanks!

**Comment by jkbk2004** [comment]
rap_control_gnu is running ok with the fix on hercules. I will finish remaining test on hercules and push test log. @zach1221 FYI

**Comment by jkbk2004** [comment]
FYI: sanity check shows no impact of last commit on existing tests on other machines. So all tests are done. We can start merging process.

**Comment by haiqinli** [comment]
@jkbk2004 Thank you very much for your updates! I am available to work with you to update the submodules.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
