### PR TITLE
Update CMake build system for AQM

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
AQM Currently fails debug builds and has an issue with building serially and module_mod. The changes in this PR address the below issues in AQM

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
https://github.com/NOAA-EMC/AQM/issues/10
https://github.com/NOAA-EMC/AQM/issues/14

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on [AQM #15](https://github.com/NOAA-EMC/AQM/pull/15)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Ran regional_atmaq on hera.intel and no changes to baselines.

```
baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220929/INTEL/regional_atmaq
working dir  = /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_RT/rt_22168/regional_atmaq
Checking test 001 regional_atmaq results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf003.nc .........OK
 Comparing sfcf006.nc .........OK
 Comparing atmf000.nc .........OK
 Comparing atmf003.nc .........OK
 Comparing atmf006.nc .........OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc .........OK
 Comparing RESTART/phy_data.nc .........OK
 Comparing RESTART/sfc_data.nc .........OK
Test 001 regional_atmaq PASS
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1074988407/20221005174511/ufs-weather-model
[RT] Error: Test control_restart 002 failed in run_test failed 
[RT] Error: Test control_p8 006 failed in run_test failed 
[RT] Error: Test rap_control 007 failed in run_test failed 
[RT] Error: Test rap_decomp 008 failed in run_test failed 
[RT] Error: Test rap_2threads 009 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 011 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 012 failed in run_test failed 
[RT] Error: Test hrrr_control 014 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 015 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp 016 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 018 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 019 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_radar_tten_warm 020 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 021 failed in run_test failed 
[RT] Error: Test control_debug 022 failed in run_test failed 
[RT] Error: Test control_diag_debug 023 failed in run_test failed 
[RT] Error: Test rap_control_debug 025 failed in run_test failed 
[RT] Error: Test hrrr_control_debug 026 failed in run_test failed 
[RT] Error: Test rap_diag_debug 027 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 028 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 029 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 030 failed in run_test failed 
[RT] Error: Test control_ras_debug 031 failed in run_test failed 
[RT] Error: Test control_stochy_debug 032 failed in run_test failed 
[RT] Error: Test control_debug_p8 033 failed in run_test failed 
[RT] Error: Test rap_restart_dyn32_phy32 040 failed in run_test failed 
[RT] Error: Test hrrr_control_restart_dyn32_phy32 041 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32 042 failed in run_test failed 
[RT] Error: Test rap_control_debug_dyn32_phy32 043 failed in run_test failed 
[RT] Error: Test hrrr_control_debug_dyn32_phy32 044 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32_debug 045 failed in run_test failed 
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 047 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 049 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA it turns out git version issue on jenkins-ci side. I am running on a sandbox jenkins pipeline. it is running ok but slow as the sandbox was set up as sequential. We are ok to move on to merge the PR.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
NOAA-EMC/AQM/pull/15 is merged. Ready for merge here.

**Comment by junwang-noaa** [comment]
@jkbk2004 Does Jenkins-CI run OK? Can users see the run log file?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA Zach is monitoring the Jenkins-ci run with fix now. Let's merge in jenkins-ci log first thing tomorrow. I like to force to have jenkins-ci log.

**Comment by zach1221** [comment]
Run log below from Jenkins. Please let me know if anything else is needed. 
[ufs-weather-model » ort-docker-wrapper-pipeline » PR-1445 #3 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9729488/ufs-weather-model.ort-docker-wrapper-pipeline.PR-1445.3.Console.Jenkins.pdf)

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
> Run log below from Jenkins. Please let me know if anything else is needed. [ufs-weather-model » ort-docker-wrapper-pipeline » PR-1445 #3 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9729488/ufs-weather-model.ort-docker-wrapper-pipeline.PR-1445.3.Console.Jenkins.pdf)

@zach1221 We need to resolve the public accessibility issue of full jenkins-ci log outputs in the PR. Please, continue to follow up with Jenkins team.

**Pull request merged**
