### PR TITLE
CCPP framework update and metadata bug fixes

### LINKED ISSUE #744: Bring updates of the CCPP metadata parser in feature/capgen to the ccpp-framework main branch - 1st round
## Description

The CCPP framework metadata parser must be updated with the latest code in the `feature/capgen` branch. Since this code contains more consistency checks, updates and bug fixes for the fv3atm and ccpp-physics metadata will be required.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR only updates the submodule pointer for fv3atm, which contains updates to ccpp-framework (in particular the metadata parser) and bug fixes for the CCPP metadata in fv3atm and ccpp-physics.

This update is needed to prepare for a future transition to the next-generation code generator `capgen.py` (instead of `ccpp_prebuild.py`). `ccpp_prebuild.py` under the hood uses the metadata parser from `capgen.py`, and the latest improvements and consistency checks made there (branch `feature/capgen` in ccpp-framework) are now brought back to the authoritative code base.

Also: change queue on Cheyenne from economy to regular to avoid regression tests being killed at 1:00am after sitting in the queue for many hours.

There are no Fortran code changes and no changes to the input data or the regression test results.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/744.

## Testing

**Preliminary regression testing**

Regression tests were run on Hera with Intel against the existing baselines, all tests passed.

**Final regression testing**

- [X] hera.intel (redone due to changes in ccpp-framework following code review)
- [X] hera.gnu (redone due to changes in ccpp-framework following code review)
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [X] CI - 87e5510 and https://github.com/ufs-community/ufs-weather-model/pull/745/commits/103fe82cbb11db57d67653eea99c7a76c47e5999

## Dependencies

- waiting on https://github.com/NCAR/ccpp-framework/pull/391
- waiting on https://github.com/earth-system-radiation/rte-rrtmgp/pull/133
- waiting on https://github.com/NCAR/ccpp-physics/pull/718
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/367

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/711664683/20210817181513/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_225914
Test compile 002 failed failed 
Test compile 001 failed failed 
Test compile 005 failed failed 
Test compile 003 failed failed 
Test compile 004 failed failed 
Test compile 008 failed failed 
Test compile 006 failed failed 
Test compile 007 failed failed 
Test compile 013 failed failed 
Test compile 010 failed failed 
Test compile 012 failed failed 
Test compile 011 failed failed 
Test compile 009 failed failed 
Test compile 014 failed failed 
Test compile 019 failed failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by climbfuji** [comment]
> /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/711664683/20210817181513/ufs-weather-model

Same problem as on the wcoss systems, this is now fixed. Will submit auto-rt again.

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/711664683/20210817131515/ufs-weather-model
Please make changes and add the following label back:
orion-intel-RT

**Comment by climbfuji** [comment]
> Machine: orion
> Compiler: intel
> Job: RT
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/711664683/20210817131515/ufs-weather-model
> Please make changes and add the following label back:
> orion-intel-RT

@junwang-noaa @DusanJovic-NOAA for your information, we canceled the auto-rt runs on orion, because the jobs were not progressing at all due to the fairshare of the project being used. All ten compile jobs were still pending two hours after they were submitted. I used another project (running `rt.sh` manually) and the jobs kicked off immediately.

**Comment by climbfuji** [comment]
All tests passed. Waiting for the ccpp-framework approval before we can merge (tomorrow morning).

**Comment by climbfuji** [comment]
Update 08/18/2021: the code review for ccpp-framework led to a few small changes that have no impact on the code. I checked that the auto-generated code is 100% identical before/after making the changes in commit https://github.com/NCAR/ccpp-framework/pull/391/commits/53aa9dc7cffd8fd0c7dce57902b8d5b1345d3fdb. Nonetheless, I will rerun the regression tests on Hera with Intel and GNU to be absolutely sure everything is fine. I will also rerun the CI tests.

**Comment by climbfuji** [comment]
fv3atm submodule pointer has been updated, hash verified. All tests passed, including all reruns. Ready to merge.

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa should we wait for more approvals or merge, given that it's only a submodule pointer update?

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
