### PR TITLE
update MOM6 to its main branch 20220820

### LINKED ISSUE #1378: update MOM6 to its main 20220820 updating and switch to use infra/FMS2 code in UFS
MOM6 main branch is updated on 20220820 (see detail at https://github.com/mom-ocean/MOM6/pull/1582), need to updating dev/emc correspondingly.
Also per discussion with Bin Li, we will switch to use MOM6 infra/FMS2 code
No BL change in this PR

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?
* MOM6 main branch is updated on 20220820, need to make corresponding updating in UFS
* also we will switch to use MOM6 infra/FMS2 code in UFS
* no BL change
### Issue(s) addressed
UFS #1378 
MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/101
Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1378 
- fixes MOM6 https://github.com/NOAA-EMC/MOM6/issues/101
## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/MOM6/pull/102

### CODE REVIEW

**Comment by jiandewang** [comment]
@jkbk2004 I just sync-ed the PR, it is ready now

**Comment by jiandewang** [comment]
@jkbk2004 I just sync-ed the PR, it is ready now

**Comment by jiandewang** [comment]
@jkbk2004 I just sync-ed the PR, it is ready now

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1032241634/20220822233006/ufs-weather-model
[RT] Error: Test compile_011 failed in run_compile failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by DeniseWorthen** [comment]
@jiandewang are you able to run RTs on WCOSS2?

**Comment by jiandewang** [comment]
> @jiandewang are you able to run RTs on WCOSS2?

@DeniseWorthen just launched on wcoss 2

**Comment by jiandewang** [comment]
wcoss2 job finished, run log committed

**Comment by jkbk2004** [comment]
@jiandewang @DeniseWorthen @ChunxiZhang-NOAA compile failure is captured on gaea for the case -DAPP=ATM -DDEBUG=ON -D32BIT=ON
</lustre/f2/pdata/ncep_shared/cmake-3.20.1/bin/cmake -E touch FV3/ccpp/CMakeFiles/fv3ccpp.dir/driver/GFS_restart.F90.o.provides.build
/lustre/f2/scratch/Jong.Kim/FV3_RT/rt_8893/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90(13538): error #6405: The same named entity from different modules and/or program units cannot be referenced.   [CDATA]
               ierr = FV3_GFS_v16_coupled_noahmp_fast_physics_final_cap(cdata=cdata)
------------------------------------------------------------------------------^
compilation aborted for /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_8893/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90 (code 1)
make[2]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/build.make:127: FV3/ccpp/CMakeFiles/fv3ccpp.dir/physics/ccpp_static_api.F90.o] Error 1>

**Comment by jiandewang** [comment]
> @jiandewang @DeniseWorthen @ChunxiZhang-NOAA compile failure is captured on gaea for the case -DAPP=ATM -DDEBUG=ON -D32BIT=ON </lustre/f2/pdata/ncep_shared/cmake-3.20.1/bin/cmake -E touch FV3/ccpp/CMakeFiles/fv3ccpp.dir/driver/GFS_restart.F90.o.provides.build /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_8893/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90(13538): error #6405: The same named entity from different modules and/or program units cannot be referenced. [CDATA] ierr = FV3_GFS_v16_coupled_noahmp_fast_physics_final_cap(cdata=cdata) ------------------------------------------------------------------------------^ compilation aborted for /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_8893/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90 (code 1) make[2]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/build.make:127: FV3/ccpp/CMakeFiles/fv3ccpp.dir/physics/ccpp_static_api.F90.o] Error 1>

@jkbk2004 I just had a try, it works fine. See
/lustre/f2/scratch/ncep/Jiande.Wang/FV3_RT/rt_41942/compile_001
So I guess your issue maybe is related to machine.

**Comment by jkbk2004** [comment]
> > @jiandewang @DeniseWorthen @ChunxiZhang-NOAA compile failure is captured on gaea for the case -DAPP=ATM -DDEBUG=ON -D32BIT=ON </lustre/f2/pdata/ncep_shared/cmake-3.20.1/bin/cmake -E touch FV3/ccpp/CMakeFiles/fv3ccpp.dir/driver/GFS_restart.F90.o.provides.build /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_8893/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90(13538): error #6405: The same named entity from different modules and/or program units cannot be referenced. [CDATA] ierr = FV3_GFS_v16_coupled_noahmp_fast_physics_final_cap(cdata=cdata) ------------------------------------------------------------------------------^ compilation aborted for /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_8893/compile_001/build_fv3_001/FV3/ccpp/physics/ccpp_static_api.F90 (code 1) make[2]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/build.make:127: FV3/ccpp/CMakeFiles/fv3ccpp.dir/physics/ccpp_static_api.F90.o] Error 1>
> 
> @jkbk2004 I just had a try, it works fine. See /lustre/f2/scratch/ncep/Jiande.Wang/FV3_RT/rt_41942/compile_001 So I guess your issue maybe is related to machine.

Yeah, looks like gaea machine issue. BTW all tests passed. we can move on for merging.

**Comment by jiandewang** [comment]
MOM6 merged, is it the time for me to revert MOM6 submodule ?

**Comment by DeniseWorthen** [comment]
@jiandewang yes, please revert and commit the update to the gitmodules

**Comment by jkbk2004** [comment]
> MOM6 merged, is it the time for me to revert MOM6 submodule ?

sure! go ahead to revert the change in gitmodule and update mom6 submodule pointer.

**Comment by jiandewang** [comment]
MOM6 submodule now points to dev/emc, hash # 

commit af12e89c771aed8d54cb3b996ec9e13db1685366 (HEAD, origin/dev/emc, origin/HEAD, dev/emc)
Merge: 55e047243 d077295d1
Author: jiandewang <jiande.wang@noaa.gov>
Date:   Wed Aug 24 09:41:37 2022 -0400
    Merge pull request #102 from jiandewang/feature/update-to-main-20220820
    update to MOM6 20220820 main branch

**Review by DeniseWorthen — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@jiandewang can you change line 28 in gitmodules  to branch = dev/emc?

**Comment by jiandewang** [comment]
> @jiandewang can you change line 28 in gitmodules to branch = dev/emc?

@jkbk2004 sorry for the typo, fixed

**Pull request merged**
