### PR TITLE
Update CICE with latest Consortium/main

### LINKED ISSUE #58: updates from Consortium/main
PRs merged at Consortium/main need to be added to our local fork. These include:

- An update for the floe-size distribution when wave-cice coupling is enabled (https://github.com/CICE-Consortium/CICE/pull/813). This updates Icepack with a bug fix for lateral melt (https://github.com/CICE-Consortium/Icepack/pull/424). UFS does not currently have a wave-ice coupling test, but this would change answers to any current configuration testing wave-ice coupling.

- An update for added metadata for history files https://github.com/CICE-Consortium/CICE/pull/816

- Minor other updates including
https://github.com/CICE-Consortium/CICE/pull/812
https://github.com/CICE-Consortium/CICE/pull/817
https://github.com/CICE-Consortium/CICE/pull/818
https://github.com/CICE-Consortium/CICE/pull/810
https://github.com/CICE-Consortium/CICE/pull/801
https://github.com/CICE-Consortium/CICE/pull/806
https://github.com/CICE-Consortium/CICE/pull/820

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Updates CICE for latest merges at Consortium/main

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [x] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- depends on https://github.com/NOAA-EMC/CICE/pull/59
- closes https://github.com/NOAA-EMC/CICE/issues/58

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11041351/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11041353/RegressionTests_hera.intel.log)

### CODE REVIEW

**Comment by zach1221** [comment]
@DeniseWorthen I think we'll start working through this PR next. I'll begin adding labels and testing.

**Comment by zach1221** [comment]
There is still issue with jenkins-ci. I'm running same ORTs manually against this PR now on Hera.

**Comment by zach1221** [comment]
The ci ORTs, listed below, have passed on hera
control_p8: thr mpi dcp rst bit dbg
regional_control: thr dcp
cpld_control_nowave_noaero_p8: rst dbg

**Comment by zach1221** [comment]
All tests are done, I think we can start the merging process. @DeniseWorthen I'll leave a comment in CICE [#59](https://github.com/NOAA-EMC/CICE/pull/59) requesting that pr to be merged.

**Comment by zach1221** [comment]
Actually wcoss/acorn still need to be run, apologies. @BrianCurtis-NOAA are you able to run the RTs for these platforms?

**Comment by DeniseWorthen** [comment]
@zach1221 Thanks. Before I do that, I want to be sure everyone is OK w/ the issue of the hash and the .gitmodule that I posted in the slack channel.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA do you think wcoss will run or are we good to skip it and proceed with merging?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA do you think wcoss will run or are we good to skip it and proceed with merging?

It's still slow and hitting wall clocks. I may need to increase wallclock on wcoss if this keeps happening after switches. Skip WCOSS2.

**Comment by zach1221** [comment]
Alright, thank you, Brian. Skipping wcoss this time.

**Comment by DeniseWorthen** [comment]
@zach1221 I've double and triple checked---the new hash for CICE is [5840cd1](https://github.com/NOAA-EMC/CICE/commit/5840cd1931e2e32b9dfded0c19049d0f1ec3d04c), which is the current hash in the PR. @BrianCurtis-NOAA will you also double check? 

Even though it seems to work, I don't think I'll make the mistake of not changing the .gitmodules again, because this feels very weird.

**Comment by BrianCurtis-NOAA** [comment]
> @zach1221 I've double and triple checked---the new hash for CICE is [5840cd1](https://github.com/NOAA-EMC/CICE/commit/5840cd1931e2e32b9dfded0c19049d0f1ec3d04c), which is the current hash in the PR. @BrianCurtis-NOAA will you also double check?
> 
> Even though it seems to work, I don't think I'll make the mistake of not changing the .gitmodules again, because this feels very weird.

Looks good to me

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
I checked out my feature/updcice branch. It is using NOAA-EMC/CICE. Hash is 
```
 5840cd1931e2e32b9dfded0c19049d0f1ec3d04c CICE-interface/CICE (CICE6.0.0-440-g5840cd1)
 a4779cc71125b40a7db3a4da8512247cbf2b0955 CICE-interface/CICE/icepack (Icepack1.1.0-147-ga4779cc)
```

**Comment by zach1221** [comment]
Thank you for confirming, Denise.

**Comment by BrianCurtis-NOAA** [comment]
Acorn/Cactus testing part of #1679

**Pull request merged**
