### PR TITLE
Enable cpl_scalars export from ATM and NoahMP for use by CMEPS

### LINKED ISSUE #2171: enable cpl_scalars in coupled model for CSG and regional domains
## Description

One of the most powerful features of the CMEPS mediator is the capabilty to write out mediator history files. These history files are a fundamental tool for diagnosing the fields exchanged between components. They are enabled either at the component level via config or by enabling a special mediator phase for history writing. See Discussion [https://github.com/ufs-community/ufs-weather-model/discussions/934](https://github.com/ufs-community/ufs-weather-model/discussions/934) for details. 

CMEPS uses a scalar field within the exportState of a component to determine how to decompose the internal CMEPS fields, which are on a mesh, into the 2-d fields of structured grid component. This currently is enabled for MOM6, CICE6 and WW3 (when on a structured grid). For FV3, the capability currently exists through a work-around which allows the setting of a config variable for the cube-sphere tile size. This does not work for regional grids however. Without having the ATM exchange fields on the tiles, mediator history files need to be post-processed to create fields which can be visualized. This is cumbersome and makes the history files more difficult to use.

## Solution

Add the required ``cpl_scalars`` export to FV3. This will enable an additional index in the ``cpl_scalars`` array which will contain the number of tiles, either 6 for the CSG or 1 for the regional, and the nx,ny size of each tile. A similar method can also be used for NoahMP. 

Modify CMEPS to recognize the additional index in the ``cpl_scalars`` and, when non-zero, use the index to set the number of 2-d domains to write in the history files.

Add the required config variables to ufs.configure. These will be of the form

```
      ScalarFieldCount = 3
      ScalarFieldIdxGridNX = 1
      ScalarFieldIdxGridNY = 2
      ScalarFieldIdxGridNTile = 3
      ScalarFieldName = cpl_scalars
```

This will place the number of tiles into the third index of the ``cpl_scalar`` array, which will allow CMEPS to write CSG or single tile FV3 or NoahMP history files decomposed into the required number of tiles.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
### Commit Message:

```
  * CMEPS - allow additional dimension in cpl_scalars for CSG and regional ATM domains for use in mediator history files 
  * CMEPS - fix mapping mask for lnd->atm
  * FV3 - add export of cpl_scalars
  * NOAHMP - add export of cpl_scalars
```

### Priority:

* Normal

### UFSWM:

- closes https://github.com/ufs-community/ufs-weather-model/issues/2171

### Sub component Pull Requests:

* CMEPS: https://github.com/NOAA-EMC/CMEPS/pull/115
* FV3: https://github.com/NOAA-EMC/fv3atm/pull/794
* NoahMP: https://github.com/NOAA-EMC/noahmp/pull/8

### UFSWM Blocking Dependencies:

- https://github.com/ESCOMP/CMEPS/pull/436
---
### Regression Test Changes (Please commit test_changes.list):

The following tests change baselines because the format of the mediator history file which is compared changes (the fields are now on the regional tile instead of the mesh). All other files in these tests are B4B
- hafs_regional_atm_ocn_intel, hafs_regional_docn_intel, hafs_regional_docn_oisst_intel

The control_p8_atmlnd_intel fails comparison because of a change in the mapping masks. This bug was found during extensive testing of the NoahMP PR (see https://github.com/NOAA-EMC/noahmp/pull/8#issuecomment-1992695392)

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jkbk2004 If I am going to test this, then I should test it one last time against Rocky8 on Hera (since Hera is still our only GNU platform). Why is the update to Rocky8 not the priority PR for today? Only 4 nodes are still unmigrated, which means anyone working w/ UWM on Hera is sharing just those 4 nodes.

**Comment by DusanJovic-NOAA** [comment]
> @jkbk2004 If I am going to test this, then I should test it one last time against Rocky8 on Hera (since Hera is still our only GNU platform). Why is the update to Rocky8 not the priority PR for today? Only 4 nodes are still unmigrated, which means anyone working w/ UWM on Hera is sharing just those 4 nodes.

We run GNU tests on Hercules.

**Comment by jkbk2004** [comment]
I agree. #2194 is high priority.

**Comment by DeniseWorthen** [comment]
We do not run coupled tests for GNU on Hercules.

**Comment by DusanJovic-NOAA** [comment]
> We do not run coupled tests for GNU on Hercules.

I see, do you remember why we skip coupled tests on Hercules?

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA We are waiting for an FMS update in SS1.6 I believe.

**Comment by uturuncoglu** [comment]
@DeniseWorthen I wonder about the timeline for this PR. The actual land fix is depends on it. Thanks.

**Comment by DeniseWorthen** [comment]
@uturuncoglu Yes. I've been in a holding pattern after the Hera/Rocky8 transition because we lost GNU testing capability for some of the coupled tests on Hera and we are waiting for stack/1.6 in order to get back our GNU functionality on Hercules. I don't like not being able to fully test w/ GNU. I was hoping the Hera/R8 issues would be resolved quickly but at this point, I am going to proceed w/ the final testing w/o fully testing GNU. Hopefully we can get it committed next week. Thanks.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I am going to start the final testing of this PR. I'd like to get it committed next week, to allow #2191 to proceed.

**Comment by FernandoAndrade-NOAA** [comment]
#2193 has been merged in, please sync and resolve merge conflicts, thank you.

**Comment by DeniseWorthen** [comment]
@FernandoAndrade-NOAA It should be good to go. Let me know if you spot any issues.

**Comment by FernandoAndrade-NOAA** [comment]
Looks good to go from my side, @zach1221 @BrianCurtis-NOAA FYI starting testing for this PR.

**Comment by FernandoAndrade-NOAA** [comment]
Two tests timed out on Hera, rerunning with increased time limit.
```
regional_atmaq_debug intel
cpld_debug_pdlib_p8 gnu
```

**Comment by zach1221** [comment]
Derecho is still not up, so I think we'll push the Hera logs here soon and skip for this PR. Then catch up the baselines in the next.

**Comment by FernandoAndrade-NOAA** [comment]
Hera log pushed up alongside a time limit increase for the two failing tests.

**Comment by zach1221** [comment]
Ok, @DeniseWorthen fv3atm is merged now as well.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
