### PR TITLE
update CICE with latest consortium/main

### LINKED ISSUE #55: Update to latest Consortium/main
Updates to include the following PRs which are not expected to change baselines:

https://github.com/CICE-Consortium/CICE/pull/778. This PR simplifies the initialization of the dynamics and removes unnecessary code or allocations.

https://github.com/CICE-Consortium/CICE/pull/790. This PR renames cicedynB to cicedyn (with link) and fixes some metadata in netcdf files for C-grid.

The following PRs change answers as noted:

https://github.com/CICE-Consortium/CICE/pull/802. This PR changes calculation of stress12T to give non-zero values for the C-grid. It will change answers only for the C-grid test.

https://github.com/CICE-Consortium/CICE/pull/799. This PR contains a bug fix for the accumulation of salt and freshwater fluxes when ktherm=2 (ie, mushy thermo) as well as a new feature to use the actual bulk-salinity of sea ice to calculate the fluxes. Without the saltflux feature turned on, sea ice is assumed to have a constant bulk salinity of 4psu. The new feature allows the actual sea ice salinity prognostically determined by the mushy therm scheme to determine the salt flux. The bug fix changes all UFS baselines which use ktherm=2.

The relevant section of code in ``icepack/columnphysics/icepack_therm_itd.F90`` which contained the bug is:

```
      if (update_ocn_f) then
         if (ktherm <= 1) then
            dfresh = -rhoi*vi0new/dt
            dfsalt = ice_ref_salinity*p001*dfresh
            fresh  = fresh + dfresh
            fsalt  = fsalt + dfsalt
         ! elseif (ktherm == 2) the fluxes are added elsewhere
         endif
```

See Icepack issue https://github.com/CICE-Consortium/Icepack/issues/390

Baseline changes for the NG-GODAS tests are due to code refactoring associated with the saltflux feature, since the debug test case reproduces.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Updates CICE to the latest Consortium/main. 

Includes a bug-fix for ktherm=2 (mushy thermodynamics) with optional new feature to use the actual (prognostic) bulk ice salinity in place of constant (4psu) ice salinity when ktherm=2. This feature is not turned on in this PR. To enable the feature, a new namelist option should be added to the ``forcing_nml`` in ice_in:

``saltflux_option = 'prognostic'``

This feature should only be used with ktherm=2. Enabling it would change baselines for all ktherm=2 tests.

The ``cicedynB`` subdirectory has also be renamed to ``cicedyn``, with associated changes in ``cice_files.cmake``.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

Changes were tested on cheyenne.intel and cheyenne.gnu with the following results:

-All coupled tests (which all use ktherm=2) and the single NG-GODAS test using ktherm=2 (``datm_cdeps_gfs``) will change answers due to bug-fix. This was verified by running the  baselines with the 2-line bug-fix reverted.  Baselines using ktherm=2 reproduced in this case  except the ``cpld_control_ciceC_p8`` test. The C-grid test changes due to additional bug-fix that is only applicable to C-grid.

-All NG-GODAS tests using ktherm=1, with the exception of debug, will change answers due to code refactoring associated with new prognostic salt-flux feature. 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [x] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Depends on https://github.com/NOAA-EMC/CICE/pull/56

Closes https://github.com/NOAA-EMC/CICE/issues/55
## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
We can start testing this PR. I will try from hera.

**Comment by zach1221** [comment]
Jenkins-ci ORT output
[ORT 1562 Output logs.pdf](https://github.com/ufs-community/ufs-weather-model/files/10468801/ORT.1562.Output.logs.pdf)

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1191480151/20230120194508/ufs-weather-model
Please make changes and add the following label back: gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Dogwood (WCOSS2) was having issues on Friday and it's going to be unavailable today. Will need to create baselines after it comes back.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
