### PR TITLE
First reconciliation PR from production/RRFS.v1

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [X] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:

This PR is identical to https://github.com/ufs-community/ufs-weather-model/pull/2147, but brings these changes from the production/RRFS.v1 branch to the develop branch instead.

### Commit Message:

```
* UFSWM - physics updates for RRFS.v1 code freeze
  * FV3 - physics updates for RRFS.v1 code freeze
    * ccpp-physics - physics updates for RRFS.v1 code freeze
    
```

### Priority:

* High: Needed for SRW App

### UFSWM:

* None

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/872
  * ccpp-physics:https://github.com/ufs-community/ccpp-physics/pull/226

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines. 

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [ ] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
@jkbk2004 @haiqinli I decided to start this PR by itself because the next PR that was merged into the production/RRFS.v1 branch has parts that may not be needed (that were a temporary solution to pass the `-check all` debug flag). That will require a bit of work on my part to see what of the next PR needs to be brought over to develop. In the meantime, we can at least start the process with this PR.

**Comment by grantfirl** [comment]
All pre-test RT failures are consistent with the physics code changes.

**Comment by jkbk2004** [comment]
@grantfirl we can start working on this pr. can you sync up branch?

**Comment by grantfirl** [comment]
> @grantfirl we can start working on this pr. can you sync up branch?

@jkbk2004 OK, finished syncing.

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA @BrianCurtis-NOAA We will skip Jet/Gaea/Derecho. Jet queue is too busy. Gaea C5 system upgrade continues. Derecho allocation is still not available.

**Comment by BrianCurtis-NOAA** [comment]
> @FernandoAndrade-NOAA @BrianCurtis-NOAA We will skip Jet/Gaea/Derecho. Jet queue is too busy. Gaea C5 system upgrade continues. Derecho allocation is still not available.

I would recommend waiting for Gaea C5 to come back and be patient with Jet. Since I don't know the situation for the Derecho allocation, if we are still waiting on that by the time C5 comes back and Jet is done, then I think that would be OK at that point/situation.

**Comment by jkbk2004** [comment]
Jobs on Jet is not moving. @ulmononian @RatkoVasic-NOAA Gaea C5 system libraries are completed updated. An issue is created at https://github.com/ufs-community/ufs-weather-model/issues/2472. @BrianCurtis-NOAA We need to skip Jet/Gaea/Derecho. What about acorn? I think we should merge this pr.

**Comment by BrianCurtis-NOAA** [comment]
> Jobs on Jet is not moving. @ulmononian @RatkoVasic-NOAA Gaea C5 system libraries are completed updated. An issue is created at #2472. @BrianCurtis-NOAA We need to skip Jet/Gaea/Derecho. What about acorn? I think we should merge this pr.

@jkbk2004 I understand your situation is less than desirable given the priority of this PR in the community. I would still encourage you to be patient and resolve as many machine issues as you can. If the EPIC spack team can get a working spack-stack on the C5 upgrades ASAP, that would be a great push. Let's talk about Jet and Derecho at todays meeting as well.

Acorn was finished but I forgot to go grab the log before they started work, i'm going to try to see if i can get it, but i'll know by the meeting today if that's going to happen or not.

**Comment by ulmononian** [comment]
> > Jobs on Jet is not moving. @ulmononian @RatkoVasic-NOAA Gaea C5 system libraries are completed updated. An issue is created at #2472. @BrianCurtis-NOAA We need to skip Jet/Gaea/Derecho. What about acorn? I think we should merge this pr.
> 
> @jkbk2004 I understand your situation is less than desirable given the priority of this PR in the community. I would still encourage you to be patient and resolve as many machine issues as you can. If the EPIC spack team can get a working spack-stack on the C5 upgrades ASAP, that would be a great push. Let's talk about Jet and Derecho at todays meeting as well.
> 
> Acorn was finished but I forgot to go grab the log before they started work, i'm going to try to see if i can get it, but i'll know by the meeting today if that's going to happen or not.

fyi: spack-stack installation to accommodate c5 upgrade is ongoing (@RatkoVasic-NOAA).

**Comment by jkbk2004** [comment]
Jet/Derecho are still not available. We will skip those machines. We can go ahead to merge this pr.

**Comment by jkbk2004** [comment]
@grantfirl new fv3 hash is https://github.com/NOAA-EMC/fv3atm/commit/1e10d62a971e4114faea90ae2f134664f3a9ef02

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
