### PR TITLE
CCPP cloud cover change for Thompson MP associated with Xu Randall, several bug fixes for regression testing scripts

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR only updates the submodule pointers for fv3atm and ccpp-physics for the changes in the associated PRs: remove old comments in `GFS_typedefs.F90`, increase cloud cover for Thompson MP by passing convective cloud water mixing ratio to `progcld6`.

Results for regression using Thompson MP, but not MYNN PBL or GF, change.

This PR contains several bugfixes for the regression testing scripts contributed by @DusanJovic-NOAA (branch rt_logs), part of commit https://github.com/ufs-community/ufs-weather-model/pull/962/commits/dd6ab9616312584b6ea6e6e644ab4bf4844c8d60

### Issue(s) addressed

Fixes https://github.com/NCAR/ccpp-physics/issues/765

## Testing

Regression test were run against existing baselines on Hera with Intel and GNU. As expected, the following tests had different results (but ran to completion), all other tests verified against the existing baseline:
```
control_thompson 054 failed in check_result
control_thompson 054 failed in run_test
control_thompson_no_aero 055 failed in check_result
control_thompson_no_aero 055 failed in run_test
control_thompson_debug 071 failed in check_result
control_thompson_debug 071 failed in run_test
control_thompson_no_aero_debug 072 failed in check_result
control_thompson_no_aero_debug 072 failed in run_test
control_thompson_extdiag_debug 073 failed in check_result
control_thompson_extdiag_debug 073 failed in run_test
```
[rt_hera_gnu_verify_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/7727868/rt_hera_gnu_verify_against_existing.log)
[rt_hera_gnu_verify_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/7727867/rt_hera_gnu_verify_against_existing_fail_test.log)
[rt_hera_intel_verify_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/7727871/rt_hera_intel_verify_against_existing.log)
[rt_hera_intel_verify_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/7727870/rt_hera_intel_verify_against_existing_fail_test.log)

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- (n/a) opnReqTest for newly added/changed feature
- (skip for this PR, CI problems will be fixed in next PR) CI

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/789
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/443

### CODE REVIEW

**Comment by climbfuji** [comment]
CI tests failed (`control_2thrds`). Weird, because the changes should only affect runs with Thompson MP. I will run `rt.sh` against the existing baselines (which also run `control_2thrds`). They passed yesterday, but I will try again.

**Comment by climbfuji** [comment]
A rerun against the existing baseline (20211214) led to the following failures w b4b differences as expected:
```
control_thompson 054 failed in check_result
control_thompson 054 failed in run_test
control_thompson_no_aero 055 failed in check_result
control_thompson_no_aero 055 failed in run_test
control_thompson_debug 071 failed in check_result
control_thompson_debug 071 failed in run_test
control_thompson_no_aero_debug 072 failed in check_result
control_thompson_no_aero_debug 072 failed in run_test
control_thompson_extdiag_debug 073 failed in check_result
control_thompson_extdiag_debug 073 failed in run_test
```
This and the fact that creating new baselines and verifying against them worked on Hera with Intel and GNU suggests that the control_2thrds test itself should be ok. No idea why the CI tests failed.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/803950133/20211218024509/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_55836
Test compile_013 failed in run_compile failed 
Please make changes and add the following label back:
jet-intel-BL

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: jet
> Compiler: intel
> Job: BL
> Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/803950133/20211218024509/ufs-weather-model
> Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_55836
> Test compile_013 failed in run_compile failed
> Please make changes and add the following label back:
> jet-intel-BL

jet ... one of these again:

```
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error at /misc/apps/cmake/3.20.1/share/cmake-3.20/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/apps/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/bin/mpiicpc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_55836/compile_013/build_fv3_013/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_76805/fast && gmake: Makefile: No such file or directory
    gmake: *** No rule to make target `Makefile'.  Stop.
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/803950133/20211218171509/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_165542
Test rap_cires_ugwp_debug 075 failed in check_result failed 
Test rap_cires_ugwp_debug 075 failed in run_test failed 
Test rap_unified_ugwp_debug 076 failed in check_result failed 
Test rap_unified_ugwp_debug 076 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by climbfuji** [comment]
CI tests failed again, this time for another test.
```
Removing intermediate container 6abba5774a46
108
 ---> 16ff0f5d1ec1
109
Step 14/16 : WORKDIR $HOME/ufs-weather-model/tests
110
 ---> Running in 644cfe70694f
111
Removing intermediate container 644cfe70694f
112
 ---> 2e002e7f609f
113
Step 15/16 : RUN ./opnReqTest -n $test_name -c $build_case -z && tar -cvzf fv3.tar.gz fv3_*.exe modules.fv3_*
114
 ---> Running in d08fc22c431b
115
d08fc22c431b
116
Machine:  linux.gnu     Account:  nems
117
WARNING: UNKNOWN PLATFORM
118
test name: cpld_control_c96_p7
119
cases to compile: dbg
120
compiling dbg with compile option -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1,FV3_GFS_v16_coupled_p7_rrtmgp -DDEBUG=ON
121
Died with error code 2
122
The command '/bin/sh -c ./opnReqTest -n $test_name -c $build_case -z && tar -cvzf fv3.tar.gz fv3_*.exe modules.fv3_*' returned a non-zero code: 2
```

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Hash for fv3atm is correct (71f27b2), ready to merge

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
