### PR TITLE
update mom6 to its main repo. 20240824 commit (FMA)

### LINKED ISSUE #2411: update MOM6 to its main repo. 20240824 commit (FMA PR)
MOM6 main repo. is updated on 20240824 (FMA PR), see detail at https://github.com/mom-ocean/MOM6/pull/1634. Need to update dev/emc correspondingly. Note this update will require new BL on wcoss2

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
MOM6 main repo. was updated on 20240824 which is GFDL's FMA PR (see detail at https://github.com/mom-ocean/MOM6/pull/1634. This updating is aimed to eliminate future FMA related non-reproduciable issue on wcoss2. So a new BL is needed for wcoss2 but not for other platforms.

### Commit Message:

```
  MOM6 - update MOM6 to its main repo. 20240824 updating (GFDL's FMA PR)
```

### Priority:
Normal

### UFSWM:

* Closes #2411 

### Sub component Pull Requests:
 - MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/138

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* PR Updates/Changes Baselines: new BL is needed for wcoss2

### Input data Changes:
* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jiandewang** [comment]
add HERA full test log:
[Regression-HERA.log.pdf](https://github.com/user-attachments/files/16743665/Regression-HERA.log.pdf)

**Comment by jiandewang** [comment]
@jkbk2004 can you put this PR in commit queue ? Thanks

**Comment by jkbk2004** [comment]
> @jkbk2004 can you put this PR in commit queue ? Thanks

@jiandewang Sure! I updated the table: possible commit date around 08/30 or 09/02.

**Comment by jiandewang** [comment]
> > @jkbk2004 can you put this PR in commit queue ? Thanks
> 
> @jiandewang Sure! I updated the table: possible commit date around 08/30 or 09/02.

sounds good. Thanks

**Comment by jiandewang** [comment]
@jkbk2004 
https://github.com/ufs-community/ufs-weather-model/wiki/Commit-Queue
here you marked PR #2412 as no BL chnage. In fact this requires a new BL on wcoss2

**Comment by jkbk2004** [comment]
> @jkbk2004 https://github.com/ufs-community/ufs-weather-model/wiki/Commit-Queue here you marked PR #2412 as no BL chnage. In fact this requires a new BL on wcoss2

@jiandewang Got it! I updated the table.

**Comment by FernandoAndrade-NOAA** [comment]
@jiandewang This PR is next for testing, please go ahead and sync/resolve conflicts.

**Comment by jkbk2004** [comment]
Full RT ran ok on orion but it seems rt.sh has an issue to create log.: /work/noaa/epic/jongkim/UFS-RT/orion/rt-2412/tests/logs/log_orion. @zach1221 @FernandoAndrade-NOAA Please, skip Orion log.

**Comment by zach1221** [comment]
Looks like we'll need to skip Derecho as well due to issue #2429

**Comment by DeniseWorthen** [comment]
How about just fixing issue #2429 instead?

**Comment by jkbk2004** [comment]
Develop branch has same build issue on Derecho. We had no problem with previous PRs. @RatkoVasic-NOAA it points lib is corrupted. If no quick fix is available, we will skip Derecho to merge this PR.

**Comment by zach1221** [comment]
Derecho looks like it's running  now. Hopefully I'll have completed logs soon.

**Comment by zach1221** [comment]
Testing is complete.

**Comment by jiandewang** [comment]
MOM6 merged with hash # 5e0c21f
UWM submodule reverted

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
