### PR TITLE
Update release branches for submodules, bugfix for compiling FMS, remove WW3

### PR DESCRIPTION
**Pull request by climbfuji**
- From Dusan: remove WW3 submodule.
- Update submodules (branches) for UFS public release for FV3, NEMS, stochastic_physics, FMS (with code changes for FMS). The code changes for FMS changed the baseline as a result of the quad precision bug fix contained in the update. Without the update of FMS, the changes proposed here do not change the answer.
- Update NEMS submodule to include a recent bugfix for Open MPI (https://github.com/NOAA-EMC/NEMS/pull/25).
- Remove affinity.c from list of files to compile from FMS; this file is not needed and causes the model build to fail on newer Linux versions (e.g. Ubuntu).
- Suggestion: update of `build.sh` to make it easier for the user to understand what is happening (Why is there an executable ufs_weather_model if the last step of the build says "creating NEMS.x"? Why does it take so long for the script to do anything?) and why it is failing (currently, if `ccpp_prebuild.py` fails, the call to `build.sh` doesn't report anything, and the user has no idea that `ccpp_prebuild.py` failed and that there is a separate log file to look into).

New regression test baseline is `ufs-public-release-20200206`.

Associated PRs:
https://github.com/NOAA-EMC/fv3atm/pull/60
https://github.com/ufs-community/ufs-weather-model/pull/50

For regression testing, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing: currently creating new baseline (see comment above about the baseline result change).

**Comment by junwang-noaa** [comment]
Dom,

I committed the GFDL dycore branch fv3atm change. You can update your
ufs-weather-model branch now. Thanks.

**Comment by climbfuji** [comment]
I will, thank you. I would like to confirm - because I was surprised by the code changes in FMS - that these have been tested on other systems. Has this update been made for the develop branch? Do we know if it works on native Linux, macOS as well as on the platforms that we have been testing on? Just to make sure ... Thanks.

**Comment by climbfuji** [comment]
Regression test baseline on hera was created. Please sync /scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_INTEL/ to /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/ufs-public-release-20200206/ - thank you!

**Comment by JessicaMeixner-NOAA** [comment]
If you remove WW3 submodule, you might want to remove the parts of compset/fv3.input, tests/compile.sh and any other rt test that deal with ww3 too?

**Comment by climbfuji** [comment]
> If you remove WW3 submodule, you might want to remove the parts of compset/fv3.input, tests/compile.sh and any other rt test that deal with ww3 too?

I don't think that is required. The NEMSCompsetRun is not described anywhere, users can't run it anyway unless they are on one of the few platforms that support it. tests/compile.sh only runs the few tests in tests/rt.conf, none of which uses WW3=Y. I assume that removing the ww3 directory was primarily to reduce the size of the repo (remember my comment earlier that the regression tests are all part of the repo and make up a significant fraction of the number of files / size of the model). There are so many other "inconsistencies" in the sense that code is (partly) in repository that is never exercised (e.g. NAM physics, the namphysics directory was removed but we didn't comb through all the CMakeLists.txt and makefile files to remove the reference for it; same for the dynamic CCPP build).

**Comment by DusanJovic-NOAA** [comment]
> Regression test baseline on hera was created. Please sync /scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_INTEL/ to /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/ufs-public-release-20200206/ - thank you!

Done.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Regression tests passed against the newly created baseline on all systems:

[rt_cheyenne_gnu_create.log](https://github.com/ufs-community/ufs-weather-model/files/4171646/rt_cheyenne_gnu_create.log)
[rt_cheyenne_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4171647/rt_cheyenne_gnu.log)
[rt_cheyenne_intel_create.log](https://github.com/ufs-community/ufs-weather-model/files/4171648/rt_cheyenne_intel_create.log)
[rt_cheyenne_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4171649/rt_cheyenne_intel.log)
[rt_hera_intel_create.log](https://github.com/ufs-community/ufs-weather-model/files/4171650/rt_hera_intel_create.log)
[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4171651/rt_hera_intel.log)

**Comment by climbfuji** [comment]
Do not merge this PR yet. I tried to compile the code on macOS using the clang+gfortran compiler and it failed:
```
[100%] Building Fortran object CMakeFiles/NEMS.exe.dir/NEMS/src/MAIN_NEMS.F90.o
[100%] Linking Fortran executable NEMS.exe
Undefined symbols for architecture x86_64:
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined..2 in libfms.a(create_xgrid.c.o)
      _.omp_outlined..4 in libfms.a(create_xgrid.c.o)
      _.omp_outlined..7 in libfms.a(create_xgrid.c.o)
      _.omp_outlined..8 in libfms.a(create_xgrid.c.o)
  "___kmpc_for_static_init_4", referenced from:
      _.omp_outlined..2 in libfms.a(create_xgrid.c.o)
      _.omp_outlined..4 in libfms.a(create_xgrid.c.o)
      _.omp_outlined..7 in libfms.a(create_xgrid.c.o)
      _.omp_outlined..8 in libfms.a(create_xgrid.c.o)
  "___kmpc_fork_call", referenced from:
      _create_xgrid_2dx2d_order1 in libfms.a(create_xgrid.c.o)
      _create_xgrid_2dx2d_order2 in libfms.a(create_xgrid.c.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
I will revert the FMS change for testing and see if it compiles or not.

**Comment by climbfuji** [comment]
The error on macOS with clang is unrelated to FMS. Please go ahead and merge this. Sorry for the delay, better to double check.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
