### PR TITLE
Remove compiler warnings for CMEPS and CICE; Add traditional threading templates for global apps and append _esmf for templates using ESMF-managed threading (was #2179)

### LINKED ISSUE #1984: Compiler warnings may not be suppressed
Currently in the top-level cmake and in atmos_cube_sphere cmake we use the `-nowarn` flag (Intel compiler) which suppress all compiler warnings. 

```
$ grep -r nowarn .
./cmake/Intel.cmake:set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -g -traceback -fpp -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte -qno-opt-dynamic-align")
./FV3/atmos_cubed_sphere/cmake/compiler_flags_Intel_Fortran.cmake:set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -g -traceback -fpp -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte -qno-opt-dynamic-align ${${kind}_flags}")
```

According to "[NCEP Central Operations WCOSS Implementation Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf
)" this is not allowed (page 15 section IV B. (5)):

_"Code must compile without errors or warnings. Errors and warnings may not be suppressed, and the compiler warning level ("-W" options) must be at least the default one."_

We should remove this flag (from ufs-weather-model and atmos_cubed_sphere) and start working on eliminating all warnings.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Removes compiler warnings for CMEPS and CICE. Adds new templates for traditional threading in global applications

### Commit Message:

```
* CICE and CMEPS - Remove compiler warnings.
* UFSWM - Allow flexibility to use traditional or ESMF-managed threading for global apps.
```

### Priority:

* Normal

### UFSWM:

* Resolves #1984 for CMEPS and CICE
* Related to #1764 
* Will address https://github.com/NOAA-EMC/global-workflow/issues/2277

### Sub component Pull Requests:

* CICE: https://github.com/NOAA-EMC/CICE/pull/75
* CMEPS: https://github.com/NOAA-EMC/CMEPS/pull/114

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Without fixing the top-level CMakeList, compiler warnings could creep back to any component, is that right? So do we wait for all components to eliminate warnings before changing the top-level?

Or, in CICE for example, should I add -nowarn to this line
```
set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -FR -convert big_endian -assume byterecl -ftz -align array64byte")
```

**Comment by BrianCurtis-NOAA** [comment]
> @DusanJovic-NOAA Without fixing the top-level CMakeList, compiler warnings could creep back to any component, is that right? So do we wait for all components to eliminate warnings before changing the top-level?

The compiler won't fail with warnings, so we don't have to wait before changing top-level CMakeLists.txt. It will be beneficial to have that GFortran GH action to spit out all of them so we can keep track and discuss with those groups.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Won't GFortran (with its equivalent of -nowarn) spit out a lot more warnings than intel?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Won't GFortran (with its equivalent of -nowarn) spit out a lot more warnings than intel?

Yes

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Without fixing the top-level CMakeList, compiler warnings could creep back to any component, is that right? So do we wait for all components to eliminate warnings before changing the top-level?
> 
> Or, in CICE for example, should I add -nowarn to this line
> 
> ```
> set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -FR -convert big_endian -assume byterecl -ftz -align array64byte")
> ```

Do not add -nowarn, that will suppress the warnings

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Yes, of course! Sorry I wasn't thinking.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I re-ran after merging in Rahu's PR, but since the test_changes.list doesn't change (it is still empty), it seems I'm not able to commit it.

**Comment by BrianCurtis-NOAA** [comment]
That is fine. @jkbk2004 @FernandoAndrade-NOAA @zach1221 please note that if dev branch had an empty test_changes.list and the next PR also has an empty test_changes.list, as long as the PR author notes that in the PR somewhere, it's OK not to have that committed.

**Comment by zach1221** [comment]
Running ORTs now.

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 I noticed the commit message for the first gaea log was "completed" which makes sense even if it failed. You might want to see if it's possible to ascertain a failure even when completed and have the commit message show a failure. To me it's confusing when all logs might commit as completed but not all will have passed.

**Comment by zach1221** [comment]
> @zach1221 I noticed the commit message for the first gaea log was "completed" which makes sense even if it failed. You might want to see if it's possible to ascertain a failure even when completed and have the commit message show a failure. To me it's confusing when all logs might commit as completed but not all will have passed.

Hey, @BrianCurtis-NOAA . I can't argue with that. I'd like it to be a little clearer as well, so that's something we can create additional tasks for.

**Comment by BrianCurtis-NOAA** [comment]
Acorn down for at least 2 weeks. Please skip.

**Comment by zach1221** [comment]
I think we'll need to skip Orion. It's just been spinning at a high number of jobs for quite some time now.

**Review by jkbk2004 — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
