### PR TITLE
Regional restart regression test fixed

### LINKED ISSUE #881: Correct regional regression tests
## Description
Regional regression tests were not testing functionality correctly. There was issue with variable TREF (nstf_name values) which caused restart not to reproduce results.

## Solution
I plan on restructuring regional regression tests. I'll put correct values for nstf_name variable,

## Related to
This will fix the bug #408

### LINKED ISSUE #908: FHZERO bug
## Description
 Changing the output frequency affect the resulting forecast.

### To Reproduce:
What compilers/machines are you seeing this with?
  Intel compiler in hera

Give explicit steps to reproduce the behavior.
1.  Checkout latest ufs-weather-model
2.  copy the control_p7 test to control_p7_fhzero
3. add export FHZERO=3 to control_p7_fhzero
4. run  both control_p7 and control_p7_fhzero tests keeping the output

Compare the restart files, and any instantaneous field, such as ugrd, and you will see differences

## Additional context

I tested this with "control", which is GFS_V16 physics, and that physics suite doesn't contain this bug.

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [X] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Fixed regional regression tests wrt restart. Additionally renamed and corrected regional tests.
Fixed the issue of the accumulation bucket FHZERO impacting resulting forecast.

Results are changed.

### Issue(s) addressed

- fixes [#881](https://github.com/ufs-community/ufs-weather-model/issues/908) 
- fixes bug [#408 ](https://github.com/ufs-community/ufs-weather-model/issues/908)
- fixes bug [#908](https://github.com/ufs-community/ufs-weather-model/issues/908)

## Testing

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [X] wcoss_cray
- [ ] wcoss_dell_p3 (no access)
- [x] opnReqTest for newly added/changed feature (with the FHZEO fix)
- [ ] CI

### Dependencies:
fv3atm PR [#425](https://github.com/NOAA-EMC/fv3atm/pull/425)
CCPP PR [#779](https://github.com/NCAR/ccpp-physics/pull/779)

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA Thanks for fixing the restart test!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/782288563/20211201001512/ufs-weather-model
Please make changes and add the following label back:
hera-gnu-BL

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
Approved. I noticed the CI tests failed again.

**Comment by MinsukJi-NOAA** [comment]
> Approved. I noticed the CI tests failed again.

CI failed for regional tests because of the changed write component PEs. This will be fixed in #927.

**Comment by MinsukJi-NOAA** [comment]
> > Approved. I noticed the CI tests failed again.
> 
> CI failed for regional tests because of the changed write component PEs. This will be fixed in #927.

There are many hard coded values in `model_configure_regional.IN`, including `write_tasks_per_group: 8`. Ideally, these should be done through export variables; something to think about in the future.

**Comment by RatkoVasic-NOAA** [comment]
@MinsukJi-NOAA which variables in model_configure_regional.IN would you like to put as a passing argument (other than mentioned write_tasks_per_group)?
Since it is easy fix, do you want me to change it, or you will do it?

**Pull request merged**
