### PR TITLE
A few miscellaneous minor fixes to regression test scripts

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

This PR includes a number of small changes in rt scripts, mostly code cleanup and changes that reduce the amount of prints to stdout

1) Print 'ECFLOW Tasks Remaining' message only when the number of tasks changes
2) Remove explicit 'set -e'. Use -v command line option for verbose mode
3) Remove 'Computing PET bounds and tasks' message
4) Fix bugs with log generation script (from @BrianCurtis-NOAA )
5) Uncomment new_compile=true in rocoto_create_compile_task
6) Removed unneeded colonifnco

### Commit Message:

```
* UFSWM - A few miscellaneous minor fixes to regression test scripts
 - Print 'ECFLOW Tasks Remaining' message only when the number of tasks changes
 - Remove explicit 'set -e'. Use -v command line option for verbose mode
 - Remove 'Computing PET bounds and tasks' message
 - Fix bugs with log generation script (from @BrianCurtis-NOAA)
 - Uncomment new_compile=true in rocoto_create_compile_task
 - Removed unneeded colonifnco
```

### Priority:

* Normal

### UFSWM:

* None

### Sub component Pull Requests:

* None

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hera [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/15499983/RegressionTests_hera.log)

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA @zach1221 I think we need to go for testing this pr (not to combine with #2271).  @BrianCurtis-NOAA FYI

**Comment by BrianCurtis-NOAA** [comment]
Do we want to combine this into my WCOSS2 PR ?

**Comment by jkbk2004** [comment]
> Do we want to combine this into my WCOSS2 PR ?

@BrianCurtis-NOAA Good idea to combine with that! Please, go ahead.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request closed without merging**
