### PR TITLE
Combination CCPP-related PR for ozone diagnostics, metadata intent bugfixes, sfcsub.F landmask bugfix, and canopy resistance output

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:

This PR contains ccpp-physics changes to fix bugs:
 - metadata intents: https://github.com/ufs-community/ccpp-physics/pull/201
 - sfcsub.F landmask: https://github.com/ufs-community/ccpp-physics/pull/202

and for more diagnostic output:
 - ozone diagnostics change: https://github.com/ufs-community/ccpp-physics/pull/196
 - canopy resistance added: https://github.com/ufs-community/ccpp-physics/pull/204

All of the above PRs were combined into one:
- ufs-community/ccpp-physics#205

Replaces: https://github.com/ufs-community/ufs-weather-model/pull/2253

### Commit Message:

```
* UFSWM, CMEPS, FV3/ccpp_physics - CCPP Physics bugfixes for metadata intents and sfcsub.f landmask and output changes for ozone diagnostics and canopy resistance
```

### Priority:

* Normal

### Sub component Pull Requests:

* CMEPS: NOAA-EMC/CMEPS#119 (metadata only)
* FV3: NOAA-EMC/fv3atm#831
  * ccpp-physics: ufs-community/ccpp-physics#205

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

The changes to the ozone production/loss and mixing diagnostics will cause result changes for tests that output these terms. Any tests that use `diag_additional_control_dtend` or `diag_additional_rap_dtend` will be affected. See the test_changes.list file for specific tests.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
@jkbk2004 Apologies for the delay on this one. We ran into some RT failures related to NOAHMP as a component land model that we needed to fix. We're all good to go now.

**Comment by jkbk2004** [comment]
> @jkbk2004 Apologies for the delay on this one. We ran into some RT failures related to NOAHMP as a component land model that we needed to fix. We're all good to go now.

@grantfirl sounds good!

**Comment by jkbk2004** [comment]
@grantfirl Can you sync up branches? We like to commit this pr today.

**Comment by grantfirl** [comment]
> @grantfirl Can you sync up branches? We like to commit this pr today.

@jkbk2004 Finished

**Comment by BrianCurtis-NOAA** [comment]
Waiting on labels and a new bl_date I believe.

**Comment by BrianCurtis-NOAA** [comment]
There's still a review needed in https://github.com/ufs-community/ccpp-physics/pull/205

**Comment by grantfirl** [comment]
> There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)

@BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.

**Comment by BrianCurtis-NOAA** [comment]
> > There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)
> 
> @BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.



> > There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)
> 
> @BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.

I agree, 1 is fine, but it seems there are revisions that are not from keeping up-to-date with auth repo (past the previous code review), and I would prefer all code is reviewed if possible prior to testing.

**Comment by grantfirl** [comment]
> > > There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)
> > 
> > 
> > @BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.
> 
> > > There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)
> > 
> > 
> > @BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.
> 
> I agree, 1 is fine, but it seems there are revisions that are not from keeping up-to-date with auth repo (past the previous code review), and I would prefer all code is reviewed if possible prior to testing.

Understood, and you're correct. I'll request re-review.

**Comment by grantfirl** [comment]
> > > There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)
> > 
> > 
> > @BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.
> 
> > > There's still a review needed in [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205)
> > 
> > 
> > @BrianCurtis-NOAA We only need 1 for ccpp/physics PRs going into ufs/dev, so we should be good to go. However, this PR was assembled from 4 smaller PRs that were all reviewed and approved independently. I've reviewed the independent PRs, but cannot review my own combination.
> 
> I agree, 1 is fine, but it seems there are revisions that are not from keeping up-to-date with auth repo (past the previous code review), and I would prefer all code is reviewed if possible prior to testing.

@BrianCurtis-NOAA Approval for [ufs-community/ccpp-physics#205](https://github.com/ufs-community/ccpp-physics/pull/205) has been achieved.

**Comment by zach1221** [comment]
Testing is now complete. We can move to begin the merge process starting with ccpp-physics.

**Comment by zach1221** [comment]
@grantfirl fv3atm and noah-mp are merged. Please update submodule hashes and .gitmodule urls.
https://github.com/NOAA-EMC/fv3atm/commit/10271c97aa884f64d0c2003c3202eb229cc1d65b
https://github.com/NOAA-EMC/noahmp/commit/ec38ea3d902644cd4519d5fe060316859ccdc108

**Comment by grantfirl** [comment]
> * Bugfix: update data type for use_2m_diagnostics_calculated_by_lake_model NOAA-EMC/CMEPS#119

Sure, although we still need https://github.com/NOAA-EMC/CMEPS/pull/119 to be merged, right?

**Comment by zach1221** [comment]
> > * Bugfix: update data type for use_2m_diagnostics_calculated_by_lake_model [Bugfix: update data type for use_2m_diagnostics_calculated_by_lake_model NOAA-EMC/CMEPS#119](https://github.com/NOAA-EMC/CMEPS/pull/119)
> 
> Sure, although we still need [NOAA-EMC/CMEPS#119](https://github.com/NOAA-EMC/CMEPS/pull/119) to be merged, right?

Correct. We've requested it. Feel free to wait for that one to be merged, so you can do them all at once.

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl @zach1221 CMEPS has been merged: https://github.com/NOAA-EMC/CMEPS/commit/2d837b16af326b09ff4018daab4de84f4deff7ec

**Comment by grantfirl** [comment]
@BrianCurtis-NOAA @zach1221 This is ready to go.

**Comment by BrianCurtis-NOAA** [comment]
I've cleaned up the description/commit message a bit.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
