### PR TITLE
Allow HAFS app to be compiled with 64bit FMS

### LINKED ISSUE #1545: The HAFSW application with moving-nest needs to be built with the 64bit FMS library
## Description
The HAFSW application with moving nest cannot be built with the 64bit FMS library.

The 64bit FMS is required for the mixed-mode HAFS-MOM6. The 64bit FMS is also required for the HAFS-MOM6 with moving nest.

## Solution
The moving_nest code needs to be revised to be compatible with 64bit FMS.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

The HAFSW application with moving nest cannot be built with the 64bit FMS library.

The 64bit FMS is required for the mixed-mode HAFS-MOM6. The 64bit FMS is also required for the HAFS-MOM6 with moving nest.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on NOAA-EMC/fv3atm/pull/626
- Closes ufs-community/ufs-weather-model/issues/1545

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA Can you attach to the PR comments the GNU and Intel logs showing that all tests pass current baselines?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Can you attach to the PR comments the GNU and Intel logs showing that all tests pass current baselines?

Regression tests (intel and gnu) passed on Hera.

[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10777305/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10777306/RegressionTests_hera.intel.log)

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can you sync up fv3 branch? We may combine this pr to #1578. @SadeghTabas-NOAA can point to the fv3 branch.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA can you sync up fv3 branch? We may combine this pr to #1578. @SadeghTabas-NOAA can point to the fv3 branch.

I just synced my fv3atm branch

**Comment by DeniseWorthen** [comment]
Committed with PR #1578

**Pull request closed without merging**
