### PR TITLE
Reduce memory required by MERRA2 option; fix diag_tables for P7 tests; adds C384 P7 tests to Cheyenne.intel

### LINKED ISSUE #698: C384 P7 coupled tests fail on cheyenne
## Description

This job fails to run at startup with an error: ``MPT: shepherd terminated: r5i4n4.ib0.cheyenne.ucar.edu - job aborting``

### To Reproduce:

Cheyenne.intel

## Additional context

Found during testing for PR #639. The test was turned off for cheyenne.intel until the issue can be resolved. 

Since the wave model cannot be compile in debug mode, an equivalent test was created for a non-wave bmark_p7b configuration. The test can be accessed using rt.test in this [branch](https://github.com/DeniseWorthen/ufs-weather-model/tree/test2)

When running in debug mode, the model fails with the following:

```
2:MPT:     header=header@entry=0x7ffdcfe45c10 "MPT ERROR: Rank 32(g:32) received signal SIGFPE(8).\n\tProcess ID: 62280, Host: r7i7n1, Program: /glade/scratch/worthen/FV3_RT/rt_13027/cpld_bmark_v16_p7b/fv3.exe\n\tMPT Version: HPE MPT 2.22  03/31/20 15"...) at sig.c:340
32:MPT: #3  0x00002b177c55e4ff in first_arriver_handler (signo=signo@entry=8,
32:MPT:     stack_trace_sem=stack_trace_sem@entry=0x2b1786c00080) at sig.c:489
32:MPT: #4  0x00002b177c55e793 in slave_sig_handler (signo=8, siginfo=<optimized out>,
32:MPT:     extra=<optimized out>) at sig.c:565
32:MPT: #5  <signal handler called>
32:MPT: #6  0x0000000008047c67 in module_sf_noahmplsm::energy (parameters=..., ice=0,
32:MPT:     vegtyp=17, ist=1, nsnow=3, nsoil=4, isnow=0, dt=300,
32:MPT:     rhoair=1.1787577636261917, sfcprs=101003.09822185335,
32:MPT:     qair=0.011852218429786931, sfctmp=296.38129134030879,
32:MPT:     thair=296.38129134030879, lwdn=345.52102043841046, uu=3.4295500034750659,
32:MPT:     vv=-3.4672281739002062, zref=10.812501434103201,
32:MPT:     co2air=39.896223797632075, o2air=21109.64752836735, solad=..., solai=...,
32:MPT:     cosz=-0.91289500682162039, igs=1, eair=1910.8519305175637,
32:MPT:     tbot=299.26776123046875, zsnso=..., zsoil=..., elai=0, esai=0, fwet=0,
32:MPT:     foln=1, fveg=0, pahv=0, pahg=0, pahb=0, qsnow=0, dzsnso=...,
32:MPT:     lat=0.21661703129464016, canliq=0, canice=0, iloc=6, jloc=-9999,
32:MPT:     z0wrf=nan(0x7baddadbaddad), imelt=..., snicev=..., snliqv=..., epore=...,
32:MPT:     t2m=nan(0x7baddadbaddad), fsno=0, sav=0, sag=0,
32:MPT:     qmelt=nan(0x7baddadbaddad), fsa=0, fsr=0, taux=nan(0x7baddadbaddad),
32:MPT:     tauy=nan(0x7baddadbaddad), fira=nan(0x7baddadbaddad),
32:MPT:     fsh=nan(0x7baddadbaddad), fcev=nan(0x7baddadbaddad),
32:MPT:     fgev=nan(0x7baddadbaddad), fctr=nan(0x7baddadbaddad),
32:MPT:     trad=nan(0x7baddadbaddad), psn=nan(0x7baddadbaddad),
32:MPT:     apar=nan(0x7baddadbaddad), ssoil=nan(0x7baddadbaddad), btrani=...,
32:MPT:     btran=9.9999999999999995e-07, ponding=nan(0x7baddadbaddad),
32:MPT:     ts=nan(0x7baddadbaddad), latheav=nan(0x7baddadbaddad),
32:MPT:     latheag=nan(0x7baddadbaddad), frozen_canopy=3435973836,
32:MPT:     frozen_ground=3435973836, tv=291.71072387695312, tg=291.71072387695312,
32:MPT:     stc=..., snowh=0, eah=2000, tah=291.71072387695312, sneqvo=0, sneqv=0,
32:MPT:     sh2o=..., smc=..., snice=..., snliq=..., albold=0.65000000000000002, cm=0,
32:MPT:     ch=0, dx=-9999, dz8w=-9999, q2=0.011852218429786931, tauss=0, laisun=0,
32:MPT:     laisha=0, rb=0, errmsg=..., errflg=0, qc=-9999, qsfc=9.99e+20,
32:MPT:     psfc=101128.33749723693, t2mv=0, t2mb=nan(0x7baddadbaddad), fsrv=0,
32:MPT:     fsrg=0, rssun=nan(0x7baddadbaddad), rssha=nan(0x7baddadbaddad), albd=...,
32:MPT:     albi=..., albsnd=..., albsni=..., bgap=0, wgap=0,
32:MPT:     tgv=nan(0x7baddadbaddad), tgb=nan(0x7baddadbaddad),
32:MPT:     q1=nan(0x7baddadbaddad), q2v=0, q2b=nan(0x7baddadbaddad),
32:MPT:     q2e=nan(0x7baddadbaddad), chv=0, chb=nan(0x7baddadbaddad),
32:MPT:     emissi=nan(0x7baddadbaddad), pah=0, shg=0, shc=0,
32:MPT:     shb=nan(0x7baddadbaddad), evg=0, evb=nan(0x7baddadbaddad), ghv=0,
32:MPT:     ghb=nan(0x7baddadbaddad), irg=0, irc=0, irb=nan(0x7baddadbaddad), tr=0,
32:MPT:     evc=0, chleaf=0, chuc=0, chv2=0, chb2=nan(0x7baddadbaddad),
32:MPT:     .tmp.ERRMSG.len_V$698=512)
```

### LINKED ISSUE #865: diag_tables for P7 tests do not include merra2 variables
## Description

MERRA2 is used by default in the P7 tests (standalone and coupled). During the commit for PR #765 , the diag_tables used by the tests were not updated to include the MERRA2 output.

### To Reproduce:

Examine the forecast files for any P7 test. The MERRA2 variables (e.g, ``AOD_550``) are not present.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- Updates the ingest of MERRA2 data to reduce the memory footprint of the ingested data.
- Adds MERRA2 fields to the forecast files for both Coupled and Standalone P7 tests. Removes fields which are not also present in ``diag_table_gfsv16``
- Adds C384 P7 tests (``cpld_control_c384_p7`` and ``cpld_bmark_p7``) tests to Cheyenne.intel

### Issue(s) addressed

- fixes #865 
- fixes #698 

## Testing

Testing on hera.intel and hera.gnu show that all P7 tests (coupled and standalone) fail comparison only because of the changes to the forecast files associated with the updated ``diag_table``. All common fields in the forecast files are B4B and all restart files are B4B. 

For hera.gnu, the failed tests are:
```
control_debug_p7 029 failed in check_result
cpld_debug_p7 033 failed in check_result
control_p7 010 failed in check_result
cpld_control_p7 032 failed in check_result
```

For hera.intel, the failed tests are:
```
control_debug_p7 063 failed in check_result
control_p7 026 failed in check_result
cpld_control_p7 001 failed in check_result
control_decomp_p7 028 failed in check_result
cpld_decomp_p7 004 failed in check_result
cpld_2threads_p7 003 failed in check_result
control_2threads_p7 029 failed in check_result
cpld_debug_p7 011 failed in check_result
cpld_control_wave_p7 005 failed in check_result
cpld_bmark_p7 010 failed in check_result
cpld_control_c384_p7 008 failed in check_result
cpld_control_c192_p7 006 failed in check_result
```
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/7322197/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/7322198/RegressionTests_hera.intel.log)

Comparing the ``sfcf006.nc`` file in the ``cpld_control_c384_p7`` test against the current baseline using the comparison tool ``cprnc`` gives the result:

```
SUMMARY of cprnc:
 A total number of    158 fields were compared
          of which      0 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of      0 fields could not be analyzed
 A total number of      6 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files DIFFER only in their field lists
```

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] CI

## Dependencies

- ncar/ccpp [#757](https://github.com/NCAR/ccpp-physics/pull/757)
- noaa-emc/fv3atm [#410](https://github.com/NOAA-EMC/fv3atm/pull/410)

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
Thanks for getting the C384 P7 tests going on Cheyenne!

**Comment by junwang-noaa** [comment]
@DeniseWorthen Is the diag_table for cpld_bmark_p7 correct? Since it has merra2 update, I assume the diag_table will contain the 6 AOD fields too.

**Comment by DeniseWorthen** [comment]
@junwang-noaa All the coupled tests use the same file, ``diag_table_template``. This is identical to ``diag_table_gfsv16_merra2`` but with the addition of the MOM6 output. The standalone P7 tests will now also use ``diag_table_gfsv16_merra2``.

**Comment by DeniseWorthen** [comment]
Closed. Code will be committed in PR #831

**Pull request closed without merging**
