### PR TITLE
update WW3 with latest develop

### LINKED ISSUE #1668: Sync with latest WW3 develop
## Description
This is for a sync with the latest WW3 develop.  Recent updates include: 
* fix ust,ustdir,asf and add ussp when running with domain decomposition WW3 PR https://github.com/NOAA-EMC/WW3/pull/943
* fixes for logic statements and restart file corruption WW3 PR https://github.com/NOAA-EMC/WW3/pull/949 
* adds block explicit (and many other updates) WW3 PR https://github.com/NOAA-EMC/WW3/pull/888

## Solution
Will provide a PR to dev/ufs-waether-model branch of WW3 and a PR to ufs-weather-model --- anticipated by 3/23 

## Alternatives
None

## Related to
https://github.com/ufs-community/ufs-weather-model/issues/1556

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Description
This updates WW3 with it's latest develop branch.  The PRs of note include: 
* fix ust,ustdir,asf and add ussp when running with domain decomposition WW3 PR https://github.com/NOAA-EMC/WW3/pull/943
* fixes for logic statements and restart file corruption WW3 PR https://github.com/NOAA-EMC/WW3/pull/949 
* adds block explicit (and many other updates) WW3 PR https://github.com/NOAA-EMC/WW3/pull/888

This PR is not expected to change answers and was [tested](https://github.com/ufs-community/ufs-weather-model/issues/1556#issuecomment-1479895300) with the in-development work of @DeniseWorthen for unstructured grid in coupled cases.    This PR can be combined with any PR that is not a change to WW3 if needed. 

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
fixes https://github.com/ufs-community/ufs-weather-model/issues/1668
WW3 PR: https://github.com/NOAA-EMC/WW3/pull/957

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11043935/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11043936/RegressionTests_hera.intel.log)

**Comment by DeniseWorthen** [comment]
@jkbk2004 Please consider prioritizing this PR. Thanks.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA note this pr is combine with #1633. we started working on.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA note this pr is combine with #1633. we started working on.

Thanks for the information. Please let me know if there's anything I need to do from my end.  I'll watch for when it'll be time for merging the WW3 PR.

**Comment by jkbk2004** [comment]
merged in with #1633

**Pull request closed without merging**
