### PR TITLE
Update WW3 with fb_coupling_fields; add cice fix for zlvs

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR updates WW3 to a version that adds the option of 2 more input fields.  Therefore this requires modifications to the input file ww3_multi.inp which is updated here.  

Baselines will change because an extra field is added into the WW3 restart file and therefore the WW3 binary restart file is changed.  New mod_def files are not needed. 

### Issue(s) addressed

- WW3 issue https://github.com/NOAA-EMC/WW3/issues/206
- CICE issue [#28](https://github.com/NOAA-EMC/CICE/issues/28)

## Testing

New baselines for the wave tests were created on hera.intel and the wave related tests were then run and passed that new baseline.  

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

WW3 branch is here: https://github.com/ukmo-waves/WW3/tree/fb_coupling_fields

- waiting on  https://github.com/NOAA-EMC/WW3/pull/285  (merged 5/17)
- waiting on CICE [PR #29](https://github.com/NOAA-EMC/CICE/pull/29)

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Is this PR ready for commit? Have you run test with with PR?

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa yes, it should be ready to be committed.  When the PR was created, I created a new baseline and tested against it, and all wave tests passed (only wave tests were run).  I have not recreated those baselines for the subsequent merges with develop branch.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA we made two big PRs recently, it would be good you can merge with your branch, and then at least test on one platform, your PR will be the next in the commit queue, adequate testing can help to have a smooth code commit. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
develop has been merged in and a few extra files have been changed based on the recent updates.  In addition, the 35 day tests for the coupled model will need new ICs.  They should all be ready on hera (just waiting for hera to come back up).   I'm in the process of creating a baseline to then check against for the wave tests.

**Comment by JessicaMeixner-NOAA** [comment]
The ATMW test passed after creating a new baseline.  I'm creating the S2SW baseline to run against now.  In addition, I'm testing the 35 day tests with the new ICs I made (not the full 35 day runs, but just making sure they all start okay).  @junwang-noaa @DeniseWorthen  or others, please let me know if there is any other additional pre-testing that would be helpful to ensure the commit process can go as smoothly as possible.

**Comment by junwang-noaa** [comment]
Thanks for doing the testing, Jessica. Since CICE6 update PR610 is ready, we'd like to commit that so that we can create P7b branch. Your PR will be combined with PR#584 and is planned to be committed on Monday 6/7.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I removed the comparison of the W3 restarts from the comparison list for the v16_wave test when I needed to adjust the number of forecast hours. Will the changes you made #544 with the template automatically create restarts at the right forecast hour?

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen it will not automatically do that but I can check for that and re-add it back if that's the goal.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen if we change WW3RSTDTHR = FHMAX that would write the restart at the end of the run, is that what you want?  Currently it defaults to every 12 hours. 

Alternatively we could change WW3RSTDTHR to the dt of restarts needed in hours. (It gets converted to seconds in the edit_inputs.sh script.  Let me know which test and what the value is and I can add it to this PR.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I think we do want that it writes at the end of the run, whatever FHMAX is.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa @DeniseWorthen @DusanJovic-NOAA 
What is the preference for an updated WW3 35 day IC input structure?  I had two thoughts: 
@[INPUTDATA_ROOT]/WW3_input_data_YYYYMMDD/BM_IC_GEFS
or 
@[INPUTDATA_ROOT]/WW3_IC_YYYYMMDD/BM_IC_GEFS

These will vary more slowly than the MOD_DEFs so I lean towards: 
@[INPUTDATA_ROOT]/WW3_IC_YYYYMMDD/BM_IC_GEFS

but am open to whatever makes the most sense to others.

**Comment by DeniseWorthen** [comment]
The existing BM ICs for the ATM are staged in the fv3_input_frac directory. I do not think this is the correct place. We've been carrying the new ATM ICs in the fv3_input_frac because that is how Shan provided them. But I believe they should be separated out into a new BM_IC-YYYYMMDD directory. 

In the new  BM_IC-YYYYMMDD directory, we should clean out the old cfsr atm and wave ics. It should contain only the input used to run the now-current BM configuration (atm, ocn, ice, wave). This is why I raised the issue today of how many BM configurations do we need to maintain in the RT (current and "minus 1"). The different tests would point to different BM_IC directories. I put the BM7_IC in fv3_input_frac because of time pressure to get the P7a running, but I knew at the time it was going to be trouble. 

The non-35d wave RTs do not use wave ICs so those tests will get updated mod-defs from the @[INPUTDATA_ROOT]/WW3_input_data_YYYYMMDD as is currently the case.

**Comment by JessicaMeixner-NOAA** [comment]
For WW3, since it's a binary restart file that will have to be recreated occasionally, running old BM configurations/ICs is not possible.  

So to move forward with this PR, do I need to make under the input directory a 
BM-IC-YYYMMDD directory and then put the WW3 ICs there?  

Or do I need to create an entirely new INPUT directory, clean out old files, create the new BM-IC-YYYYMMDD directory?  

Either is fine with me I would just like to know so I can move forward with this PR and make sure it's ready the next time it becomes its turn in the commit queue.

**Comment by JessicaMeixner-NOAA** [comment]
Also is there a preferred subfolder structure in the BM-IC-YYYMMDD directory?

**Comment by DeniseWorthen** [comment]
But only the 35d tests use wave ICs, correct? The regular RTs do not use wave ICs.

**Comment by JessicaMeixner-NOAA** [comment]
> But only the 35d tests use wave ICs, correct? The regular RTs do not use wave ICs.

Correct, only the 35 day tests use wave ICs.  The regular rt-tests do not use wave ICs.

**Comment by JessicaMeixner-NOAA** [comment]
The last update of WW3 (@aliabdolali) that was merged today also requires an update of ICs/restart files.  I'm assuming since this has not been committed yet, we should go ahead and update to the latest WW3 with those new ICs.   Depending on queue times, this could be ready tomorrow or shortly there after. 

This PR is a somewhat dependent on BM IC clean up, but I'm unsure what I need to do versus how much I just need to wait for this to happen and then update afterwards. Since I heard nothing on this PR thread yesterday I started to clean things up as best as I understood them, but that seems to be duplicating @DeniseWorthen's work.  

What is the preferred path forward for this PR?

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Yes, I was busy yesterday w/ a commit. I did not get a chance to respond to this comment thread. Sorry about that.

We have a PR from Dusan this morning and then we're holding the commit Q open for 2 days to allow Dom to give his tutorial. So this PR will be Friday at the earliest I believe.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @DeniseWorthen  

Friday is fine.  That should give me plenty of time to create new ICs with the latest WW3 so we can keep up to date with WW3.    One thing that would be helpful to know before then: do I continue with the current structure of BM ICs or do I attempt a clean up on this?  This is still unclear to me.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Please see Denise' comments on ufs-weather-model issue #624. I think there is some miscommunication.  The wave ICs issue in #573 and the impact on P7 benchmarks have never been discussed at the Wednesday's coupled model meeting, we only see the potential impact when working on this PR. The original plan is to have this PR combined with the PR#623(previous #584), since the PR #623 has updates for P7b, we decided to make separate commit for PR#573. I appreciate if we can list this issue in prototype document and discuss it at the coupled model meeting so that we can all stay on the same page.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa  apologies if this has not gotten enough attention at previous Wednesday Coupled Modeling tag-ups, we will be sure to remedy that tomorrow and discuss this issue in great detail (FYI: @LydiaStefanova-NOAA @AvichalMehra-NOAA).  Please note that this corresponds to the "Prototype 7 settings" document for (d) in the P7c list.  I have just added more details.  It also corresponds to the agenda item  "Create new wave ICs" under "Prototype 7" > "Status on running mini-prototypes" > "For 7b +" .  Look forward to clearing this up in tomorrow's meeting.

**Comment by junwang-noaa** [comment]
Thanks, appreciate this information.

**Comment by DeniseWorthen** [comment]
> Thanks @DeniseWorthen
> 
> Friday is fine. That should give me plenty of time to create new ICs with the latest WW3 so we can keep up to date with WW3. One thing that would be helpful to know before then: do I continue with the current structure of BM ICs or do I attempt a clean up on this? This is still unclear to me.

Since the Land ICs will also need to be corrected, I am taking the opportunity to create a new BM_IC_YYYYMMDD directory and a new input-data-YYYYMMDD. 

The new BM_IC _YYYYMMDD will contain the corrected ATM ICs and W3 ICs (that will conform to post-PR #573). The existing FV3_input_frac/BM7_IC will be removed. I need to work on how to retain/point to the remaining ICs and I may need to adjust this plan once I get into testing.

**Comment by DeniseWorthen** [comment]
I believe that Dom's PR #595 will change some baselines.

I normally pick the commit date as the day I start working on the commit, regardless of when it actually finishes. In this case, that would be develop-20210611

**Comment by JessicaMeixner-NOAA** [comment]
I will wait for Dom's PR before making baselines and use the name you suggest @DeniseWorthen

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Please point your gitmodules to my CICE bug fix [branch](https://github.com/DeniseWorthen/CICE/tree/bugfix/initzlvs). I have tested this fix with both intel and gnu. I'll edit the PR description to add the added information. Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen done! Let me know if there's anything else I need to do.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA would you please add one line in ufs-weather-model/.github/pull_request_template.md

 - [ ] wcoss_cray
 - [ ] wcoss_dell_p3
+- [ ] CI

Thanks.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa it's been added, let me know if it needs modifying.

**Comment by junwang-noaa** [comment]
Great, thanks!

**Review by junwang-noaa — APPROVED** [review]
Code changes look good to me, needs to confirm all RTs are done.

**Comment by DeniseWorthen** [comment]
All RTs completed and CI has passed. CICE has been merged so once the submodule has been reverted we're ready for commit.

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
