### PR TITLE
Use nccmp to compare netcdf files in regression test on NOAA R&D machines. Update WW3

### LINKED ISSUE #1657: Use nccmp to compare netcdf files in regression testing
## Description
Currently in regression testing we compare netcdf output files using unix `cmp` tool first, and if it returns error code (i.e. files are not bit-for-bit identical), we fall back to `comapre_ncfile.py` script. The issue with using this script, in addition to requiring non-standard python packages, and in addition to being slow, is that it does not compare global and field attributes, and other metadata. It just compares data values, which is not sufficient in all situations. For example we want to compare field's checksum attribute in fv3atm restart files.

## Solution
Use `nccmp` instead of `comapre_ncfile.py`. This will require that nccmp is available on all platforms we run regression test.

## Alternatives
Continue to use compare_ncfile.py

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description
Update `rt_util.sh` to use `nccmp` utility to compare netcdf outputs against the baseline instead of using custom python script. Currently only on NOAA R&D machines (hera, orion, gaea and jet).

Fixes https://github.com/ufs-community/ufs-weather-model/issues/1657
### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [x] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA  On Cheyenne, nccmp/1.8.2.1 is available. Is there any reason not to include that platform also?

**Comment by DavidHuber-NOAA** [comment]
S4 also has nccmp/1.8.9.0 and I'm happy to test it there.

**Comment by DusanJovic-NOAA** [comment]
I do not have access to cheyenne and S4, so I didn't know whether nccmp is available and which module and how should be loaded. I didn't want to break anything that currently works. Please feel free to make the required changes and test it. I'll then include your changes.

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA do you see any RT test time change with this update?

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA can you test this pr to confirm nccmp on cheyenne?

**Comment by DavidHuber-NOAA** [comment]
S4 has nccmp installed under hpc-stack, which would require loading the compilers, etc.  I have requested it to be installed in a more easily accessible location, but it may take some time.  I will include it here before the PR closes if possible, but otherwise I will add it in at a later time.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA do you see any RT test time change with this update?

No significant change in RT test time. For example cpld_control_qr_p8 test which does not produce bit-by-bit identical restart files and must use alternative comparison of netcdf files currently runs in about 355 seconds: 

https://github.com/ufs-community/ufs-weather-model/blob/b6146cd3f797d74d60e040dbdbd51d5e4bccbf92/tests/RegressionTests_orion.intel.log#L379

while my test runs in about 350 seconds:

```
  0: The total amount of wall time                        = 350.140382
  0: The maximum resident set size (KB)                   = 3197440

Test 005 cpld_control_qr_p8 PASS
```

on Orion.

**Comment by FernandoAndrade-NOAA** [comment]
@jkbk2004 adding Cheyenne to the checks seems fine:
```
0:The total amount of wall time                        = 327.542930
0:The maximum resident set size (KB)                   = 2719748

Test 001 cpld_control_qr_p8 PASS

```

**Comment by DusanJovic-NOAA** [comment]
> @jkbk2004 adding Cheyenne to the checks seems fine:
> 
> ```
> 0:The total amount of wall time                        = 327.542930
> 0:The maximum resident set size (KB)                   = 2719748
> 
> Test 001 cpld_control_qr_p8 PASS
> ```

@FernandoAndrade-NOAA Did you run the test on Cheyenne using nccmp? What changes did you make? Can you open PR to my branch or point me to your branch. Or just post the diffs here in the PR. Or just tell what I need to change in order to use nccmp on Cheyenne. Thanks

**Comment by FernandoAndrade-NOAA** [comment]
> > @jkbk2004 adding Cheyenne to the checks seems fine:
> > ```
> > 0:The total amount of wall time                        = 327.542930
> > 0:The maximum resident set size (KB)                   = 2719748
> > 
> > Test 001 cpld_control_qr_p8 PASS
> > ```
> 
> @FernandoAndrade-NOAA Did you run the test on Cheyenne using nccmp? What changes did you make? Can you open PR to my branch or point me to your branch. Or just post the diffs here in the PR. Or just tell what I need to change in order to use nccmp on Cheyenne. Thanks

@DusanJovic-NOAA yes on Cheyenne and Jet. For Cheyenne, no major changes I just added Cheyenne to the MACHINE_ID if statements in rt_utils.sh (line 361) and run_test.sh (line 109)

**Comment by DusanJovic-NOAA** [comment]
> > > @jkbk2004 adding Cheyenne to the checks seems fine:
> > > ```
> > > 0:The total amount of wall time                        = 327.542930
> > > 0:The maximum resident set size (KB)                   = 2719748
> > > 
> > > Test 001 cpld_control_qr_p8 PASS
> > > ```
> > 
> > 
> > @FernandoAndrade-NOAA Did you run the test on Cheyenne using nccmp? What changes did you make? Can you open PR to my branch or point me to your branch. Or just post the diffs here in the PR. Or just tell what I need to change in order to use nccmp on Cheyenne. Thanks
> 
> @DusanJovic-NOAA yes on Cheyenne and Jet. For Cheyenne, no major changes I just added Cheyenne to the MACHINE_ID if statements in rt_utils.sh (line 361) and run_test.sh (line 109)

Thanks

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can we combine in #1717 to this pr? We just need to point to ww3 branch https://github.com/jessicameixner-noaa/WW3/tree/feature/syncWW30419. Once combined, I like to ask to modify the PR title to reflect #1717.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA can we combine in #1717 to this pr? We just need to point to ww3 branch https://github.com/jessicameixner-noaa/WW3/tree/feature/syncWW30419. Once combined, I like to ask to modify the PR title to reflect #1717.

Done.

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA @JessicaMeixner-NOAA @MatthewMasarik-NOAA We're going to begin testing for this PR

**Comment by FernandoAndrade-NOAA** [comment]
Attached are the jenkins ci logs, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1702 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11298647/ufs-weather-model.ort-docker-pipeline.PR-1702.1.Console.Jenkins.pdf)

**Comment by JessicaMeixner-NOAA** [comment]
Are there still outstanding tests for this PR or should we start merging WW3?

**Comment by BrianCurtis-NOAA** [comment]
```
baseline dir = /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20230418/INTEL/atmaero_control_p8
working dir  = /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_66056/atmaero_control_p8
Checking test 027 atmaero_control_p8 results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf024.nc .........OK
 Comparing atmf000.nc .........OK
 Comparing atmf024.nc .........OK
 Comparing GFSFLX.GrbF00 .........OK
 Comparing GFSFLX.GrbF24 .........OK
 Comparing GFSPRS.GrbF00 .........OK
 Comparing GFSPRS.GrbF24 .........OK
 Comparing gocart.inst_aod.20210323_0600z.nc4 .........OK
 Comparing RESTART/20210323.060000.coupler.res .........OK
 Comparing RESTART/20210323.060000.fv_core.res.nc .........OK
 Comparing RESTART/20210323.060000.fv_core.res.tile1.nc .........OK
 Comparing RESTART/20210323.060000.fv_core.res.tile2.nc .........OK
 Comparing RESTART/20210323.060000.fv_core.res.tile3.nc .........OK
 Comparing RESTART/20210323.060000.fv_core.res.tile4.nc .........OK
 Comparing RESTART/20210323.060000.fv_core.res.tile5.nc .........OK
 Comparing RESTART/20210323.060000.fv_core.res.tile6.nc .........OK
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile2.nc .........OK
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile3.nc .........OK
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile4.nc .........OK
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile5.nc .........OK
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile6.nc .........OK
 Comparing RESTART/20210323.060000.fv_tracer.res.tile1.nc .........OK
 Comparing RESTART/20210323.060000.fv_tracer.res.tile2.nc .........OK
 Comparing RESTART/20210323.060000.fv_tracer.res.tile3.nc .........OK
 Comparing RESTART/20210323.060000.fv_tracer.res.tile4.nc .........OK
 Comparing RESTART/20210323.060000.fv_tracer.res.tile5.nc .........OK
 Comparing RESTART/20210323.060000.fv_tracer.res.tile6.nc .........OK
 Comparing RESTART/20210323.060000.phy_data.tile1.nc .........OK
 Comparing RESTART/20210323.060000.phy_data.tile2.nc .........OK
 Comparing RESTART/20210323.060000.phy_data.tile3.nc .........OK
 Comparing RESTART/20210323.060000.phy_data.tile4.nc .........OK
 Comparing RESTART/20210323.060000.phy_data.tile5.nc ............ALT CHECK......ERROR
```

**Comment by BrianCurtis-NOAA** [comment]
seems weird it also errored and didn't complete tile 6.

**Comment by SamuelTrahanNOAA** [comment]
Is there a log somewhere of the error message coming out of nccmp?

**Comment by jkbk2004** [comment]
Gaea C4 is not available these days. I think we will handle C4 issue with C5 migration.

**Comment by SamuelTrahanNOAA** [comment]
> Gaea C4 is not available these days

The paths in the error message are not GAEA paths. They look like WCOSS2 or Acorn to me:

> baseline dir = /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20230418/INTEL/atmaero_control_p8
> working dir  = /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_66056/atmaero_control_p8

**Comment by jkbk2004** [comment]
> > Gaea C4 is not available these days
> 
> The paths in the error message are not GAEA paths. They look like WCOSS2 or Acorn to me:
> 
> > baseline dir = /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20230418/INTEL/atmaero_control_p8
> > working dir  = /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_66056/atmaero_control_p8

Yeah, @BrianCurtis-NOAA test error is from wcoss2.

**Comment by BrianCurtis-NOAA** [comment]
Yes WCOSS2:
```
brian.curtis@clogin02:/lfs/h2/emc/nems/noscrub/brian.curtis/git/DusanJovic-NOAA/ufs-weather-model/tests> 
module load python/3.8.6
brian.curtis@clogin02:/lfs/h2/emc/nems/noscrub/brian.curtis/git/DusanJovic-NOAA/ufs-weather-model/tests> ./compare_ncfile.py /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_66056/atmaero_control_p8/RESTART/20210323.060000.phy_data.tile5.nc /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20230418/INTEL/atmaero_control_p8/RESTART/20210323.060000.phy_data.tile5.nc
Traceback (most recent call last):
  File "./compare_ncfile.py", line 6, in <module>
    with Dataset(sys.argv[1]) as nc1, Dataset(sys.argv[2]) as nc2:
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format: b'/lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20230418/INTEL/atmaero_control_p8/RESTART/20210323.060000.phy_data.tile5.nc'
```
This is the second straight failure for this test.

**Comment by DusanJovic-NOAA** [comment]
That file is empty:
```
clogin01:/u/dusan.jovic> ls -l /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20230418/INTEL/atmaero_control_p8/RESTART/
total 1427328
-rw-r--r-- 1 emc.nems nems       300 Apr 19 19:23 20210323.060000.coupler.res
-rw-r--r-- 1 emc.nems nems     18784 Apr 19 19:23 20210323.060000.fv_core.res.nc
-rw-r--r-- 1 emc.nems nems  37610116 Apr 19 19:23 20210323.060000.fv_core.res.tile1.nc
-rw-r--r-- 1 emc.nems nems  37610116 Apr 19 19:23 20210323.060000.fv_core.res.tile2.nc
-rw-r--r-- 1 emc.nems nems  37610116 Apr 19 19:23 20210323.060000.fv_core.res.tile3.nc
-rw-r--r-- 1 emc.nems nems  37610116 Apr 19 19:23 20210323.060000.fv_core.res.tile4.nc
-rw-r--r-- 1 emc.nems nems  37610116 Apr 19 19:23 20210323.060000.fv_core.res.tile5.nc
-rw-r--r-- 1 emc.nems nems  37610116 Apr 19 19:23 20210323.060000.fv_core.res.tile6.nc
-rw-r--r-- 1 emc.nems nems     92200 Apr 19 19:23 20210323.060000.fv_srf_wnd.res.tile1.nc
-rw-r--r-- 1 emc.nems nems     92200 Apr 19 19:23 20210323.060000.fv_srf_wnd.res.tile2.nc
-rw-r--r-- 1 emc.nems nems     92200 Apr 19 19:23 20210323.060000.fv_srf_wnd.res.tile3.nc
-rw-r--r-- 1 emc.nems nems     92200 Apr 19 19:23 20210323.060000.fv_srf_wnd.res.tile4.nc
-rw-r--r-- 1 emc.nems nems     92200 Apr 19 19:23 20210323.060000.fv_srf_wnd.res.tile5.nc
-rw-r--r-- 1 emc.nems nems     92200 Apr 19 19:23 20210323.060000.fv_srf_wnd.res.tile6.nc
-rw-r--r-- 1 emc.nems nems 163883040 Apr 19 19:23 20210323.060000.fv_tracer.res.tile1.nc
-rw-r--r-- 1 emc.nems nems 163883040 Apr 19 19:23 20210323.060000.fv_tracer.res.tile2.nc
-rw-r--r-- 1 emc.nems nems 163883040 Apr 19 19:23 20210323.060000.fv_tracer.res.tile3.nc
-rw-r--r-- 1 emc.nems nems 163883040 Apr 19 19:23 20210323.060000.fv_tracer.res.tile4.nc
-rw-r--r-- 1 emc.nems nems 163883040 Apr 19 19:23 20210323.060000.fv_tracer.res.tile5.nc
-rw-r--r-- 1 emc.nems nems 163883040 Apr 19 19:23 20210323.060000.fv_tracer.res.tile6.nc
-rw-r--r-- 1 emc.nems nems  38950016 Apr 19 19:23 20210323.060000.phy_data.tile1.nc
-rw-r--r-- 1 emc.nems nems  38950016 Apr 19 19:23 20210323.060000.phy_data.tile2.nc
-rw-r--r-- 1 emc.nems nems  38950016 Apr 19 19:23 20210323.060000.phy_data.tile3.nc
-rw-r--r-- 1 emc.nems nems  38950016 Apr 19 19:23 20210323.060000.phy_data.tile4.nc
-rw-r--r-- 1 emc.nems nems         0 Apr 19 19:23 20210323.060000.phy_data.tile5.nc
-rw-r--r-- 1 emc.nems nems  38950016 Apr 19 16:10 20210323.060000.phy_data.tile6.nc
-rw-r--r-- 1 emc.nems nems   9538756 Apr 19 16:10 20210323.060000.sfc_data.tile1.nc
-rw-r--r-- 1 emc.nems nems   9538756 Apr 19 16:10 20210323.060000.sfc_data.tile2.nc
-rw-r--r-- 1 emc.nems nems   9538756 Apr 19 16:10 20210323.060000.sfc_data.tile3.nc
-rw-r--r-- 1 emc.nems nems   9538756 Apr 19 16:10 20210323.060000.sfc_data.tile4.nc
-rw-r--r-- 1 emc.nems nems   9538756 Apr 19 16:10 20210323.060000.sfc_data.tile5.nc
-rw-r--r-- 1 emc.nems nems   9538756 Apr 19 16:10 20210323.060000.sfc_data.tile6.nc

```

**Comment by BrianCurtis-NOAA** [comment]
Why would one tile not write?

**Comment by BrianCurtis-NOAA** [comment]
OK, well. I will redo that baseline again from develop branch. Then run the test again. Thanks for the catch @DusanJovic-NOAA

**Comment by SamuelTrahanNOAA** [comment]
> Why would one tile not write?

Three thoughts:

1. *Was that the baseline you generated, or was it copied from Dogwood?* If it is copied, make sure you use rsync, and run rsync twice. The second run will confirm that there is nothing left to transfer. Don't ever use scp; it is not fault tolerant.
2. *Do you compare against the baseline that you generate for a PR?* That should have caught a zero-sized baseline file.
3. *Do you have the logs from the baseline generation?* It may give us clues as to why the copy failed. (Unless the baseline was copied from another machine.)

**Comment by BrianCurtis-NOAA** [comment]
> > Why would one tile not write?
> 
> Three thoughts:
> 
> 1. _Was that the baseline you generated, or was it copied from Dogwood?_ If it is copied, make sure you use rsync, and run rsync twice. The second run will confirm that there is nothing left to transfer. Don't ever use scp; it is not fault tolerant.
> 2. _Do you compare against the baseline that you generate for a PR?_ That should have caught a zero-sized baseline file.
> 3. _Do you have the logs from the baseline generation?_ It may give us clues as to why the copy failed. (Unless the baseline was copied from another machine.)

With all the switches, probably 1, since 2 is Yes and 3 is Yes. I'm not sure what @RatkoVasic-NOAA does, but it may be worth at least double checking his CRON/script.

**Comment by SamuelTrahanNOAA** [comment]
> With all the switches, probably 1, since 2 is Yes and 3 is Yes. I'm not sure what @RatkoVasic-NOAA does, but it may be worth at least double checking his CRON/script.

You should also avoid "cp" or "mv" within the same machine. A large filesystem operation can be unreliable. Rsync is fault tolerant, and it will confirm the transfer was complete on a second run.

The only exception is a "mv" within the same fileset of the same filesystem in the same cluster. In that special case, "mv" is a unit operation. That makes it especially safe.

**Comment by RatkoVasic-NOAA** [comment]
If you are talking about syncing data between two WCOSS2 machines, I'm using rsync in cron. There's a log file for each day in /u/emc.nems/ratko.vasic/202*

**Comment by RatkoVasic-NOAA** [comment]
I see that file with zero size is on both machines.

**Comment by BrianCurtis-NOAA** [comment]
@RatkoVasic-NOAA Thanks for checking on Dogwood! The new baseline was OK and passed testing, so hopefully it was a random issue and not a long term one.

**Review by DeniseWorthen — DISMISSED** [review]

**Review by zach1221 — DISMISSED** [review]

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA all tests are done. Please, go ahead to merge ww3 PR.

**Comment by JessicaMeixner-NOAA** [comment]
WW3 has been merged.  New hash is [e026bcc](https://github.com/NOAA-EMC/WW3/commit/e026bcc3c748580c0e0e22d6b9394356a37d6ef8)

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
