### PR TITLE
To update dycore to the GFDL dev/emc (the FV3 202101 version )

### LINKED ISSUE #497: git submodule checkout error
## Description
Cloning the develop branch in the ufs-weather-model repository gives the following errors:
<pre>Cloning into 'FV3'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 4673 (delta 6), reused 5 (delta 1), pack-reused 4650
Receiving objects: 100% (4673/4673), 8.39 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3350/3350), done.
fatal: reference is not a tree: 0e05075456800f0c5abd7bfb1ce6f89b26dd7989
</pre>

### To Reproduce:
git clone --recursive -b develop https://github.com/ufs-community/ufs-weather-model

## Output

**Screenshots**

**output logs**

### PR DESCRIPTION
**Pull request by XiaqiongZhou-NOAA**
This PR  is to use the GFDL dycore repository dev/emc. The GFDL  dev/emc branch of dycore was synchronized with the GFDL master, which included the FV3 202101 upgrade except inline GFDL_MP:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/releases/tag/FV3-202101-public

New baseline should be created.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies
https://github.com/NOAA-EMC/fv3atm/pull/262
https://github.com/NCAR/ccpp-physics/pull/597

### CODE REVIEW

**Comment by climbfuji** [comment]
Thanks. We will need to check out the two dycore branches, our current dev/emc in NOAA-EMC and the new branch in NOAA-GFDL, to see the differences. What I am a little worried about is the added `public` statements in the ccpp-physics PR. Are these variables used (i.e. imported) somewhere in the dycore? It goes somewhat against the CCPP rules to do that. We can certainly do the merge, and later on think about how to do this in a more CCPP-compliant way.

**Review by climbfuji — APPROVED** [review]
Approved - `.gitmodules` and submodule pointer for fv3atm will need to be updated once https://github.com/NOAA-EMC/fv3atm/pull/262 is merged.

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
fv3atm submodule pointer is correct - do we need for the CI tests to finish or has this been done already?

**Comment by DusanJovic-NOAA** [comment]
I do not see any green check marks, so probably not. I forgot, how do we start CI?

**Comment by MinsukJi-NOAA** [comment]
> I do not see any green check marks, so probably not. I forgot, how do we start CI?

write "run-ci" in a commit message

**Comment by DusanJovic-NOAA** [comment]
> write "run-ci" in a commit message

Thanks. @XiaqiongZhou-NOAA please make another commit with "run-ci" in a commit message.

**Comment by XiaqiongZhou-NOAA** [comment]
Should I commit something?
or just type" git commit -m "run-ci"  "

**Comment by climbfuji** [comment]
> Should I commit something? or just type" git commit -m "run-ci" "
> […](#)

If you do that, you probably need to add something like `--allow-empty`, but git will complain and tell you what to do.

**Comment by MinsukJi-NOAA** [comment]
Some CI tests are failing due to issues in auto management of the ec2 instances: More recent commits caused the instances to shut down in the middle of test runs. This will have to be fixed in a future PR. For this PR, I suggest we move forward since some tests managed to complete.

**Comment by climbfuji** [comment]
> Some CI tests are failing due to issues in auto management of the ec2 instances: More recent commits caused the instances to shut down in the middle of test runs. This will have to be fixed in a future PR. For this PR, I suggest we move forward since some tests managed to complete.

Ok with me, please merge.

**Comment by DusanJovic-NOAA** [comment]
Are there any tests in CI that are not in rt_gnu tests? If there are maybe we should add them to rt_gnu.

**Comment by MinsukJi-NOAA** [comment]
> Are there any tests in CI that are not in rt_gnu tests? If there are maybe we should add them to rt_gnu.

I see fv3_control_debug in rt_gnu. That's about it.

**Pull request merged**
