### PR TITLE
Update for Jet, bug fixes in running with frac_grid=T and GFDL MP, and in restarting with frac_grid=T 

### LINKED ISSUE #227: [BUG]: frac_grid input in non-frac mode is not restart reproducible in coupled model at c96,c192 or c384
**Describe the bug**

- When using the new frac_grid input in non-frac mode, FV3 does not restart repro for up to 8 fields.

- When using the original FV3_input_data384, FV3 does restart repro.

**To Reproduce**
Checkout this branch: https://github.com/DeniseWorthen/ufs-s2s-model/tree/feature/restart

- This branch has restart tests at c96mx100, c192mx050 and c384mx025 added, each using a 1d run, a 12h run and then a restart from the 12h run. 

- The nems.configure has an added mediator history write phase added at each timestep. 

- The rt.conf has only the 3 restart for each resolution active. 

- When any one resolution is run, first the 1d and 12h runs complete. The restart test starts after the 12h run completes, using the restart files produced in that run. Comparisons should then be made between the just completed 1d run and the restart run (not the baseline!).  

- For any given resolution, compare the mediator history file at the first timestep of the restart run against the same timestep of the continuous run, eg:

> cprnc -m s2s_control_c384/RESTART/ufs.s2s.cpl.hi.2016-10-03-43650.nc s2s_restart_c384/RESTART/ufs.s2s.cpl.hi.2016-10-03-43650.nc |grep RMS

produces:

> 57: RMS atmImp_Faxa_rain                 1.2255E-09            NORMALIZED  3.5022E-05
> 73: RMS atmImp_Faxa_snow                 8.4771E-11            NORMALIZED  3.2261E-05
> 82: RMS atmImp_Faxa_swndf                6.0959E-02            NORMALIZED  1.7366E-03
> 98: RMS atmImp_Faxa_swvdf                1.3133E-01            NORMALIZED  2.6185E-03
> 128: RMS atmImp_Sa_pbot                   5.4215E-06            NORMALIZED  5.5112E-11
> 144: RMS atmImp_Sa_shum                   3.6325E-10            NORMALIZED  3.9001E-08
> 153: RMS atmImp_Sa_tbot                   1.7967E-05            NORMALIZED  6.2125E-08
> 176: RMS atmImp_Sa_z                      1.4080E-06            NORMALIZED  6.1957E-08

These are the 8 fields which are not the same the first time FV3 sends fields to the mediator after restart.

- Since the mediator history files contain the atm fields on the mesh, an additional step is required to put them onto a tile grid to view. This [ncl script](https://github.com/DeniseWorthen/PLOTS/blob/feature/hera/unwind_restarttests.ncl) can be used to transfer the mesh fields to the tile for any resolution. The user must point to their own run directory, called ``RT`` in this script. The tool will produce files such as ``ufs.s2s.cpl.hi.43650.tile3.nc`` which can be compared between the 1d and restart runs.

- To show that the original FV3_input_data384 does reproduce, uncomment the line 

> #export FRAC_GRID_INPUT='.F.'

in the s2s c384 tests (in tests/tests).

- A copy of cprnc is located here: /scratch1/NCEPDEV/stmp2/Denise.Worthen/cprnc

**Expected behavior**

**Additional context**
Add any other context about the problem here. Directly reference any issues or PRs in this or other repositories that this is related to, nd describe how they are related.

### LINKED ISSUE #271: UFS weather model port to JET
## Description

UFS weather model will be needed for multiple experiments that will be run on JET. For that reason we need to elevate JET to Tier -1 support. 

## Solution

Port UFS weather model built to use hpc-stack on JET

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

This is related to hpc-stack being installed on JET. Please see issue 
https://github.com/NOAA-EMC/hpc-stack/issues/54

### LINKED ISSUE #272: restart reproducibility issue for global fv3 runs
## Description
It is found that the global fv3 (including the regression test cases) can not reproduce in restart cases  when model restarts from fh=24hrs (e.g. control runs for 48hr, restart runs from 24hr to 48hr, results at fh=48hr from control and restart are different).  However the code does reproduces when restart starts within 24 hrs and the results are compared at fh<=24. (e.g. control 24hr, restart 12hr->24hr,results at fh=24hr are identical), results do not reproduce when compared at longer forecast time than 24hr.  E.g. control runs 36hr, restart runs from 12hr to 36hr, results from control and restart are identical at 24hr, but not at fh=36hr.  

### To Reproduce:
The issue can be reproduced on all the supported platforms including hera, orion, wcoss.
1. Check out the code, and run fv3 control regression test for 48hr with restart interval set to 24 in model_configure
2. Copy the run directory, remove all the output files (dynf*, phyf*, logf*). Copy the restart files at 24 hr in 1) to the input directory in 2), rename those files without the date in the file name. 
3. Change following namelist variable:
warm_start=.true.
    nggps_ic=.false.
    external_ic=.false.
    mountain=.true.
    make_nh=.false.
    na_init=0
if model is running with cold start having nst spin up (nstf_name (2)=1), the nstf_name(2) should be turned off for restart. (nstf_name(2)=0) e.g.: nstf_name=2,0,1,0,5  
submit the job.  then compare output files with those created in 1)

### LINKED ISSUE #286: Bug fixes that broke the restart reproducible for fractional grid
In FV3GFS_io.F90, when the fractional grid is used, it filters out bad water temperature in the initial conditions if it is below freezing. This would filter out bad water temperature in the restart stage as well, breaking the reproducibility after restart. 

I suggest using this filter at the initial starting time only, since restart should be a data-read-in process, and not filter out unrealistic values occasionally generated in the model for some reasons.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR updates the modulefile for jet.intel to enable UPP v10.0.0. The hpc-stack v1.0.0 pre-release is used for this. Small changes are made to `tests.rt.sh` for jet.intel and gaea.intel (consistency with other platforms).

The submodule pointer update for fv3atm addresses bugs in the ufs-weather-model with `frac_grid=T` and GFDL microphysics, and with restarting the model when `frac_grid=T` (from @shansun6 and @SMoorthi-emc).

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/286.
Fixes https://github.com/ufs-community/ufs-weather-model/issues/227.
Does it also fix https://github.com/ufs-community/ufs-weather-model/issues/272? @junwang-noaa @SMoorthi-emc 
Fixes #271.

## Testing

Regression tests passed on all current and new tier-1 platforms: hera.{gnu,intel}, cheyenne.{gnu,intel}, wcoss_cray, wcoss_dell_p3, gaea.intel, orion.intel, jet.intel

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/524
https://github.com/NOAA-EMC/fv3atm/pull/204
https://github.com/ufs-community/ufs-weather-model/pull/304

### CODE REVIEW

**Review by BinLiu-NOAA — APPROVED** [review]
The modulefiles/jet.intel/fv3 changes look good to me. And they are right now consistent with (almost identical to) those on Hera.

**Comment by kgerheiser** [comment]
Does that mean the tests passed with these changes?

**Comment by climbfuji** [comment]
> Does that mean the tests passed with these changes?

Thus far I ran only one test through `rt.sh` to create a new baseline, and then verify against it - that worked. I'll try to create a complete baseline and verify against it as part of the regression testing on all platforms (tomorrow).

**Comment by ShanSunNOAA** [comment]
I may have forgotten to mention that Moorthi's bugfix in ccpp/physics alone in this comment would change results in the default control experiment. Thus new baselines would be needed.

**Comment by climbfuji** [comment]
> I may have forgotten to mention that Moorthi's bugfix in ccpp/physics alone in this comment would change results in the default control experiment. Thus new baselines would be needed.

Thanks, yes, that is what I was expecting. I am running tests on hera with gnu and intel overnight against the existing baselines to see what has changed, and in parallel create new baselines for both compilers.

**Comment by BinLiu-NOAA** [comment]
> Does that mean the tests passed with these changes?

Use this version of modulefiles/jet.intel/fv3, my build with a hafs test branch on Jet also went through successfully.

**Comment by DeniseWorthen** [comment]
@shansun6 Will this PR also resolve our issue #227 ?

**Comment by ShanSunNOAA** [comment]
Hi Denise,

Yes, it does. I thought the fix went in earlier.

How to edit this PR? Could you edit the PR, if you can? I see Dom had done
that - thanks.

Shan

**Comment by climbfuji** [comment]
> Hi Denise, Yes, it does. I thought the fix went in earlier. How to edit this PR? Could you edit the PR, if you can? I see Dom had done that - thanks. Shan
> […](#)

Added it.

**Comment by ShanSunNOAA** [comment]
Thanks, Dom!

Shan

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
I did verify that this branch passes the coupled restart tests in frac mode for both 12h->1d (12h) and 12h->2d (36h).

**Comment by ShanSunNOAA** [comment]
Thanks, Denise, for this info! Is this with the default physics or the
benchmark physics?  -Shan

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@shansun6 my restart tests are all just the control (default) cases.

**Pull request merged**
