### PR TITLE
A bug fix for wet scavenging of aerosols and a minor modification for moisture property calculation

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
## Description
A bug fix in mass flux divergence computation for wet scavenging of aerosols and a minor modification in moisture property calculation for the saSAS cumulus scheme.  **This bug fix will change the baselines.**

### Issue(s) addressed 
- fixes Issue #[[898](https://github.com/NCAR/ccpp-physics/issues/898)] in NCAR/ccpp-physics

## Testing
RTs are tested on hera.intel. Many tests were failed due to the baseline changes. 

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [ ] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: [3f0717b](https://github.com/ufs-community/ufs-weather-model/pull/1176/commits/3f0717be5e4c2232750900ba56b4e790433084c3)

## Dependencies
- waiting on NCAR/ccpp-physics/pull/[[900](https://github.com/NCAR/ccpp-physics/pull/900)]
- waiting on noaa-emc/fv3atm/pull/[520](https://github.com/NOAA-EMC/fv3atm/pull/520)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Oh, @ChunxiZhang-NOAA if you haven'y yet, make sure I (BrianCurtis-NOAA) am a collaborator on your fork, so AutoRT can push logs when it's done.

**Comment by ChunxiZhang-NOAA** [comment]
> Oh, @ChunxiZhang-NOAA if you haven'y yet, make sure I (BrianCurtis-NOAA) am a collaborator on your fork, so AutoRT can push logs when it's done.

@BrianCurtis-NOAA Added you as a collaborator just now.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/910830177/20220420171516/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/910830177/20220420111514/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/910830177/20220420121850/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by ChunxiZhang-NOAA** [comment]
> > Oh, @ChunxiZhang-NOAA if you haven'y yet, make sure I (BrianCurtis-NOAA) am a collaborator on your fork, so AutoRT can push logs when it's done.
> 
> @BrianCurtis-NOAA Added you as a collaborator just now.

**Comment by BrianCurtis-NOAA** [comment]
@ChunxiZhang-NOAA it looks like when you closed the PR the auto-delete code ran and thus your jobs failed. It looks like you should add labels `hera-intel-BL` and `cheyenne-intel-RT`

**Review by DeniseWorthen — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/910830177/20220421121510/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/910830177/20220421121506/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/910830177/20220421132120/ufs-weather-model
[RT] Error: Test control_c384gdas 025 failed in run_test failed 
[RT] Error: Test control_csawmgt_debug 072 failed in run_test failed 
[RT] Error: Test control_diag_debug 074 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm 105 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Review by MinsukJi-NOAA — APPROVED** [review]

**Pull request merged**
