### PR TITLE
Update EMC develop from NCAR dtc/develop 2020/03/17

### PR DESCRIPTION
**Pull request by climbfuji**
Update EMC / develop (fv3atm, NEMS, ufs-weather-model) and NCAR / master (ccpp-framework, ccpp-physis) from NCAR dtc/develop. The changes are:

ccpp-framework:
- bugfixes for handling optional arguments (no impact on current setup)
- bugfix for debug messages (no impact on current setup)

ccpp-physics:
- GFSv16 physics updates
- add moninedmf_hafs
- scientific documentation for NoahMP and satmedmfvdifq
- bugfix for threading (avoid dead lock) when calculating Thompson MP lookup tables
- addition of radar reflectivity reset switch for Thompson MP, bugfix for non-aerosol Thompson runs (from @ericaligo-noaa)
- fractional landmask changes (from @shansun6)
- CCPP version of RAS, updates to shoc and MG (from @SMoorthi-emc)
- bugfixes when levr < levs (from @SMoorthi-emc)

NEMS:
- selective merge of ufs-public release hotfix for OpenMPI (from @mark-a-potts)

fv3atm / ufs-weather-model:
- fractional landmask changes (from @shansun6)
- hera.gnu build target for old gmake CCPP build

ufs-weather-model:
- hera.gnu build target with regression test config `rt_gnu.conf` (same as used on Cheyenne); this initial version uses the UFS public release v1.0.0 NCEPLIBS
- re-enable IPD REPRO, CCPP REPRO, CCPP PROD regression tests; IPD REPRO and CCPP REPRO are bit-for-bit identical
- bugfixes for some CCPP regression tests (IAU dry mass fixer)
- addition of two-way coupled CCPP regression tests, removal of old IPD Thompson test, addition of several debug tests (Thompson non-aero and GSD suite) to cover more physics options in DEBUG mode
- change logic in `rt.sh` that COMPILE or APPBUILD lines without a machine name are executed on all machines (similar to what is done for the RUN lines)

Associated PRs:

https://github.com/NOAA-EMC/NEMS/pull/43
https://github.com/NCAR/ccpp-physics/pull/410
https://github.com/NCAR/ccpp-framework/pull/268
https://github.com/NOAA-EMC/fv3atm/pull/81
https://github.com/ufs-community/ufs-weather-model/pull/84

See below for regression testing information.

### CODE REVIEW

**Comment by climbfuji** [comment]
As described in detail in the step-by-step updates of NCAR dtc/develop from EMC develop, there are changes to the regression test baseline. Firstly, all NoahMP related results changed as part of the fractional landmask PR from @shansun6. Secondly, the IPD REPRO and CCPP PROD baselines have been added again (and CCPP REPRO tests successfully against IPD REPRO). Thirdly, for the new hera.gnu target, an (empty) baseline directory has been created based on the discussion in the PRs listed below (all GFDLMP tests hang indefinitely on hera, but the Zhao-Carr MP debug tests run to completion - although they do not test any output files).

On hera, the new baseline (containing subdirectories INTEL and GNU) should be rsync-ed from
```
/scratch1/BMC/gmtb/ufs-weather-model/RT/NEMSfv3gfs/develop-20200317/
```
to
```
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20200317/
```
prior to running the regression tests. An additional input file was added:
```
$RTPWD/FV3_input_data_gsd/field_table_thompson_noaero
```
At least this file need to be copied over to WCOSS before creating a new baseline. There is no INTEL or GNU subdirectory on WCOSS.

Recent PRs to NCAR dtc/develop (oldest to newest):

https://github.com/NCAR/ufs-weather-model/pull/24
https://github.com/NCAR/ufs-weather-model/pull/26
https://github.com/NCAR/ufs-weather-model/pull/27
https://github.com/NCAR/ufs-weather-model/pull/28

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA @SMoorthi-emc @shansun6 @ericaligo-noaa

**Comment by climbfuji** [comment]
Regression tests pass for hera.intel - regression test logs updated in the PR.

[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4345519/rt_hera_intel.log)

**Comment by climbfuji** [comment]
Regression testing on hera.gnu: "pass" in a sense that all compilations are successful and that the model runs start, however all of them hang after the model initialization. For the control debug tests (for which no output is checked, this is still reported as successful). For the purpose of this PR, namely getting the build structure in place, this is sufficient.

In the future, we will need to figure out why the runs hang on Hera (they work fine with the same compiler flags on Cheyenne) - maybe this is an issue with the software stack / the OpenMPI library.

[Compile_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4345673/Compile_hera.gnu.log)
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4345678/RegressionTests_hera.gnu.log)
[rt_hera_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4345679/rt_hera_gnu.log)

**Comment by climbfuji** [comment]
Regression testing on cheyenne.gnu: first create a new baseline, then verify against it using `rt_gnu.conf`: all tests pass.

Create

[Compile_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4346613/Compile_cheyenne.gnu.log)
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4346614/RegressionTests_cheyenne.gnu.log)
[rt_cheyenne_gnu_create.log](https://github.com/ufs-community/ufs-weather-model/files/4346615/rt_cheyenne_gnu_create.log)

Verify

[Compile_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4346625/Compile_cheyenne.gnu.log)
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4346626/RegressionTests_cheyenne.gnu.log)
[rt_cheyenne_gnu_verify.log](https://github.com/ufs-community/ufs-weather-model/files/4346627/rt_cheyenne_gnu_verify.log)

**Comment by climbfuji** [comment]
NEMSCompsetRun tests passed on hera.intel, logs updated in the PR.

**Comment by climbfuji** [comment]
From @DusanJovic-NOAA: both rt.sh and NEMSCompsetRun passed on wcoss_cray.

Regression test logs updated in the PR.

**Comment by climbfuji** [comment]
From @DusanJovic-NOAA: both rt.sh and NEMSCompsetRun passed on wcoss_dell.

Regression test logs updated in the PR.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA I updated the fv3atm submodule pointer following the merge of https://github.com/NOAA-EMC/fv3atm/pull/81. Please check the PR. Thanks!

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
It looks good to me.

**Pull request merged**
