### PR TITLE
develop: merge HWRF version of saSAS with GFS version

### PR DESCRIPTION
**Pull request by climbfuji**
Changes in this PR:
- add a new regression test that uses the HWRF versions of saSAS deep and shallow convection
- update how the sutils module is loaded on hera and jet
- contains @MinsukJi-NOAA's unit testing branch
- contains @DusanJovic-NOAA's butterfly effect branch (changes in GFDL_atmos_cubed_sphere only)

Note: The changes in the ccpp-physics PR https://github.com/NCAR/ccpp-physics/pull/423 lead to different results for two existing regression tests in PROD mode: `fv3_ccpp_regional_c768` and `fv3_ccpp_stretched_nest`. In a separate comment below, I will describe in detail my investigation that allowed me to conclude that this change is acceptable.

Associated PRs:

https://github.com/NCAR/ccpp-physics/pull/423
https://github.com/NOAA-EMC/fv3atm/pull/93
https://github.com/ufs-community/ufs-weather-model/pull/94

Tested together with https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/21.

For regression testing, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
**Changes in the regression test results for two existing regression tests in PROD mode: fv3_ccpp_regional_c768 and fv3_ccpp_stretched_nest.**

I investigated in detail why the results change for these two tests because of the changes in https://github.com/NCAR/ccpp-physics/pull/423.
- both regression tests are using non-uniform block sizes
- for `fv3_ccpp_stretched_nest`:
```
48: WARNING from PE    48: atmos_modeldefine_blocks_packed: domain (  35  24) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of    8
```
- for `fv3_ccpp_regional_c768`:
```
  0: WARNING from PE     0: atmos_modeldefine_blocks_packed: domain (  87  60) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of    4
```
(side note: I believe this is also why we have seen issues with these tests on some platforms in the past)
- the REPRO versions of these tests are bit-for-bit identical with the existing baselines
- the changes are coming from `samfdeepcnv.f`
    - I added debug print statements in the original GFS code and the merged HWRF-GFS code (starting from output variables that were different and tracing it backwards)
    - once I added print statements around the "offending" local variables (one or more of the following: `dellal`, `xlamud`, `xlamue`, `frh`), both versions of the code gave the same results
- for `fv3_ccpp_regional_c768`: I change the default layout from `20,24` to `24,20` so that all blocks are uniform, and I did this in both the original code and the code in this PR. After making the change, the two versions gave bit-for-bit identical results, but both were different from the existing baseline (when run in PROD mode)
- after fixing a bug in the implementation of `samfshal` (see commit https://github.com/NCAR/ccpp-physics/pull/423/commits/71eace19a5f42b60f64816575c425d34624c6018), not used by test `fv3_ccpp_regional_c768`, I attempted to do the same for `fv3_ccpp_stretched_nest`. I changed the blocksize from 32 to 24 for the outer domain in the original code and in this PR, and the warnings about non-uniform block sizes went away. However, the results are still different. My further investigation showed that the difference first shows up in `samfdeepcnv.f` in the first time step. For the first time step, I get b4b identical results between the current version in develop and the combined version in this PR if I add the following debug print statements before the block of code shown below (around line 1000 in the combined version). If I comment out the print statements (which print minimum/maximum/checksum of the array passed in), then the results for xlamue and/or xlamud differ. This is of course only in PROD mode. In REPRO mode, the current version in develop and the combined version in this PR always give the same results. I also ran this in debug mode and didn't spot anything obvious. 
```
c
c  final entrainment and detrainment rates as the sum of turbulent part and
c    organized one depending on the environmental relative humidity
c    (Bechtold et al., 2008; Derbyshire et al., 2011)
c
      !call print_var(-999, 0, 1, '978 xlamud', xlamud)
      !call print_var(-999, 0, 1, '978 xlamue', xlamue)
      !call print_var(-999, 0, 1, '978 fent1', fent1)
      !call print_var(-999, 0, 1, '978 fent2', fent2)
      !call print_var(-999, 0, 1, '978 km1   ', km1)
      !call print_var(-999, 0, 1, '978 im    ', im)
      !call print_var(-999, 0, 1, '978 cnvflg', cnvflg)
      !call print_var(-999, 0, 1, '978 kmax  ', kmax)
      !call print_var(-999, 0, 1, '978 frh   ', frh)
      !call print_var(-999, 0, 1, '978 cxlamd', cxlamd)
      !call print_var(-999, 0, 1, '978 cxlame', cxlame)

      if (hwrf_samfdeep) then
        do k = 2, km1
        do i=1,im
          if(cnvflg(i) .and.
     &      (k > kbcon(i) .and. k < kmax(i))) then
              tem = cxlamu * frh(i,k) * fent2(i,k)
              xlamue(i,k) = xlamue(i,k)*fent1(i,k) + tem
          endif
        enddo
        enddo
      else
        do k = 2, km1
        do i=1,im
          if(cnvflg(i) .and.
     &      (k > kbcon(i) .and. k < kmax(i))) then
              tem = cxlame * frh(i,k) * fent2(i,k)
              xlamue(i,k) = xlamue(i,k)*fent1(i,k) + tem
              tem1 = cxlamd * frh(i,k)
              xlamud(i,k) = xlamud(i,k) + tem1
          endif
        enddo
        enddo
      endif
```
- In another test, I turned the logical `hwrf_samfdeep` into a parameter set to `.false.` (instead of using an argument whose value is not known at compile time). This made the differences disappear, too.

This lets me conclude that the code changes are correct and that what we are seeing are the results of a different compiler optimization. Note that changing the blocksize or the layout changes the results of the regression tests anyway, hence new baselines are needed.

**Comment by junwang-noaa** [comment]
> **Changes in the regression test results for two existing regression tests in PROD mode: fv3_ccpp_regional_c768 and fv3_ccpp_stretched_nest.**
> 
> I investigated in detail why the results change for these two tests because of the changes in [NCAR/ccpp-physics#423](https://github.com/NCAR/ccpp-physics/pull/423).
> 
> * both regression tests are using non-uniform block sizes
> * for `fv3_ccpp_stretched_nest`:
> 
> ```
> 48: WARNING from PE    48: atmos_modeldefine_blocks_packed: domain (  35  24) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of    8
> ```
> 
> * for `fv3_ccpp_regional_c768`:
> 
> ```
>   0: WARNING from PE     0: atmos_modeldefine_blocks_packed: domain (  87  60) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of    4
> ```
> 
> (- side note: I believe this is also why we have seen issues with these tests on some platforms in the past)
> 
> * the REPRO versions of these tests are bit-for-bit identical with the existing baselines
> * the changes are coming from `samfdeepcnv.f`
>   
>   * I added debug print statements in the original GFS code and the merged HWRF-GFS code (starting from output variables that were different and tracing it backwards)
>   * once I added print statements around the "offending" local variables (one or more of the following: `dellal`, `xlamud`, `xlamue`, `frh`), both versions of the code gave the same results
> * for `fv3_ccpp_regional_c768`: I change the default layout from `20,24` to `24,20` so that all blocks are uniform, and I did this in both the original code and the code in this PR. After making the change, the two versions gave bit-for-bit identical results, but both were different from the existing baseline (when run in PROD mode)
> * I did not (yet) attempt the same experiment for `fv3_ccpp_stretched_nest`
> 
> This lets me conclude that the differences are arising from "peel" loops when non-uniform blocks are used (for a discussion about vectorization and peel/remainder loops, see https://software.intel.com/en-us/articles/what-are-peel-and-remainder-loops-fortran-vectorization-support). Peel loops leading to non-reproducible results is a common and well known problem (and the solution is to either change the code/setup to not have peel loops, or to turn off vectorization).
> 
> As such, I recommend to accept the bit-for-bit differences in CCPP PROD mode for these two tests as part of this PR. Going forward, we should consider changing the setup of these regression tests (for example like I did it in my test for `fv3_ccpp_regional_c768` described above). However, we should retain one clearly labeled test that exercises/tests the capability to use non-uniform block sizes.
> 

Thanks for checking this. I agree we should never use layout that leads to indivisible block domain. Please confirm that the fv3_ccpp_stretched_nest get identical results when it has uniform blocks.

**Comment by climbfuji** [comment]
> **Changes in the regression test results for two existing regression tests in PROD mode: fv3_ccpp_regional_c768 and fv3_ccpp_stretched_nest.**
> 
> I investigated in detail why the results change for these two tests because of the changes in [NCAR/ccpp-physics#423](https://github.com/NCAR/ccpp-physics/pull/423).
> 
> * both regression tests are using non-uniform block sizes
> * for `fv3_ccpp_stretched_nest`:
> 
> ```
> 48: WARNING from PE    48: atmos_modeldefine_blocks_packed: domain (  35  24) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of    8
> ```
> 
> * for `fv3_ccpp_regional_c768`:
> 
> ```
>   0: WARNING from PE     0: atmos_modeldefine_blocks_packed: domain (  87  60) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of    4
> ```
> 
> (- side note: I believe this is also why we have seen issues with these tests on some platforms in the past)
> 
> * the REPRO versions of these tests are bit-for-bit identical with the existing baselines
> * the changes are coming from `samfdeepcnv.f`
>   
>   * I added debug print statements in the original GFS code and the merged HWRF-GFS code (starting from output variables that were different and tracing it backwards)
>   * once I added print statements around the "offending" local variables (one or more of the following: `dellal`, `xlamud`, `xlamue`, `frh`), both versions of the code gave the same results
> * for `fv3_ccpp_regional_c768`: I change the default layout from `20,24` to `24,20` so that all blocks are uniform, and I did this in both the original code and the code in this PR. After making the change, the two versions gave bit-for-bit identical results, but both were different from the existing baseline (when run in PROD mode)
> * I did not (yet) attempt the same experiment for `fv3_ccpp_stretched_nest`
> 
> This lets me conclude that the differences are arising from "peel" loops when non-uniform blocks are used (for a discussion about vectorization and peel/remainder loops, see https://software.intel.com/en-us/articles/what-are-peel-and-remainder-loops-fortran-vectorization-support). Peel loops leading to non-reproducible results is a common and well known problem (and the solution is to either change the code/setup to not have peel loops, or to turn off vectorization).
> 
> As such, I recommend to accept the bit-for-bit differences in CCPP PROD mode for these two tests as part of this PR. Going forward, we should consider changing the setup of these regression tests (for example like I did it in my test for `fv3_ccpp_regional_c768` described above). However, we should retain one clearly labeled test that exercises/tests the capability to use non-uniform block sizes.
> 
> Thanks for checking this. I agree we should never use layout that leads to indivisible block domain. Please confirm that the fv3_ccpp_stretched_nest get identical results when it has uniform blocks.

Thanks, will try that tomorrow. Back to basic math ;-)

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA @ligiabernardet @mzhangw @grantfirl @llpcarson 

Update on the remaining b4b issue in test `fv3_ccpp_stretched_nest` after changing the block size to avoid non-uniform blocks: the difference first shows up in samfdeepcnv.f in the first time step. For the first time step, I get b4b identical results between the current version in develop and the combined version in this PR if I add the following debug print statements before the block of code shown below (around line 1000 in the combined version). If I comment out the print statements (which print minimum/maximum/checksum of the array passed in), then the results for `xlamue` and/or `xlamud` differ. This is of course only in PROD mode. In REPRO mode, the current version in develop and the combined version in this PR always give the same results. I also ran this in debug mode and didn't spot anything obvious. I don't know how much further I should investigate this. Maybe try replacing the `hwrf_samfdeep` variable with a parameter (just for testing) and see if I get b4b identical result with the current version in develop?

We may have to accept that this test changes answer in CCPP PROD mode when the PR is merged.

```
c
c  final entrainment and detrainment rates as the sum of turbulent part and
c    organized one depending on the environmental relative humidity
c    (Bechtold et al., 2008; Derbyshire et al., 2011)
c
      !call print_var(-999, 0, 1, '978 xlamud', xlamud)
      !call print_var(-999, 0, 1, '978 xlamue', xlamue)
      !call print_var(-999, 0, 1, '978 fent1', fent1)
      !call print_var(-999, 0, 1, '978 fent2', fent2)
      !call print_var(-999, 0, 1, '978 km1   ', km1)
      !call print_var(-999, 0, 1, '978 im    ', im)
      !call print_var(-999, 0, 1, '978 cnvflg', cnvflg)
      !call print_var(-999, 0, 1, '978 kmax  ', kmax)
      !call print_var(-999, 0, 1, '978 frh   ', frh)
      !call print_var(-999, 0, 1, '978 cxlamd', cxlamd)
      !call print_var(-999, 0, 1, '978 cxlame', cxlame)

      if (hwrf_samfdeep) then
        do k = 2, km1
        do i=1,im
          if(cnvflg(i) .and.
     &      (k > kbcon(i) .and. k < kmax(i))) then
              tem = cxlamu * frh(i,k) * fent2(i,k)
              xlamue(i,k) = xlamue(i,k)*fent1(i,k) + tem
          endif
        enddo
        enddo
      else
        do k = 2, km1
        do i=1,im
          if(cnvflg(i) .and.
     &      (k > kbcon(i) .and. k < kmax(i))) then
              tem = cxlame * frh(i,k) * fent2(i,k)
              xlamue(i,k) = xlamue(i,k)*fent1(i,k) + tem
              tem1 = cxlamd * frh(i,k)
              xlamud(i,k) = xlamud(i,k) + tem1
          endif
        enddo
        enddo
      endif
```

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA @ligiabernardet @mzhangw @grantfirl @llpcarson 

Next and final update as far as I am concerned. If I turn `hwrf_samfdeep` into a parameter set to `.false.`, the differences to the current version in develop go away, too (without the print statements).

**Comment by climbfuji** [comment]
**Note:** these PRs were fully merged into the NCAR dtc/hwrf-physics branch, see https://github.com/ufs-community/ufs-weather-model/pull/94 and associated PRs listed in there. The reason why the current PR and PRs listed here are proposed for EMC develop / NCAR master separately is the change in the regression test baseline results because of the change o of the `blocksize` for the two tests as described above. Once https://github.com/ufs-community/ufs-weather-model/pull/94 et al. are merged into EMC develop / NCAR master, NCAR dtc/hwrf-physics can be formally updated from these branches (all commits already included). The remaining commits to NCAR dtc/hwrf-physics can be merged back to EMC develop / NCAR master afterwards easily, because they do not change the answer and are related to HWRF physics only.

**Comment by climbfuji** [comment]
Update 2020/06/03: I updated all PRs with the latest changes from the authoritative repositories and ran the regression tests on hera.intel using `rt.conf`. Compared to the authoritative EMC baseline, the following three tests fail as expected, all others pass:
```
fv3_ccpp_gfdlmp_hwrfsas # new test, missing baseline
fv3_ccpp_stretched_nest # change in blocksize / MPI layout
fv3_ccpp_regional_c768 # change in blocksize / MPI layout
```

I also tested this code against the HWRF baseline (from branch NCAR dtc/hwrf-physics), the following tests failed (as expected):
```
fv3_ccpp_ca # new test, missing baseline
fv3_ccpp_regional_control # do_sat_adj = .true. was added to develop, but not yet to dtc/hwrf-physics
fv3_ccpp_regional_quilt # do_sat_adj = .true. was added to develop, but not yet to dtc/hwrf-physics
fv3_ccpp_regional_restart # do_sat_adj = .true. was added to develop, but not yet to dtc/hwrf-physics
fv3_ccpp_regional_c768 # do_sat_adj = .true. was added to develop, but not yet to dtc/hwrf-physics
```


[rt_hera_intel_against_existing_baseline.log](https://github.com/ufs-community/ufs-weather-model/files/4725829/rt_hera_intel_against_existing_baseline.log)
[rt_hera_intel_against_existing_baseline_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/4725830/rt_hera_intel_against_existing_baseline_fail_test.log)

[rt_hera_intel_against_existing_hwrf_baseline.log](https://github.com/ufs-community/ufs-weather-model/files/4725831/rt_hera_intel_against_existing_hwrf_baseline.log)
[rt_hera_intel_against_existing_hwrf_baseline_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/4725832/rt_hera_intel_against_existing_hwrf_baseline_fail_test.log)

**Comment by climbfuji** [comment]
Manual testing of code on macOS: code compiles with clang+gfortran and gcc+gfortran, using `compile.sh` and `compile_cmake.sh`, for CCPP and IPD.

Manual testing on jet: code compiles with Intel (18) in DEBUG and PROD mode for CCPP, using both `compile.sh` and `compile_cmake.sh`.

**Comment by climbfuji** [comment]
After creating new baselines, the regression tests passed on hera.intel, wcoss_cray, wcoss_dell_p3. Logs updated in the PR.

**Comment by climbfuji** [comment]
Regression testing on orion against existing baseline (20200512). All tests pass except `fv3_ccpp_stretched_nest` and `fv3_ccpp_regional_c768` as expected.

[rt_orion_intel_verify_against_existing_baseline.log](https://github.com/ufs-community/ufs-weather-model/files/4730279/rt_orion_intel_verify_against_existing_baseline.log)
[rt_orion_intel_verify_against_existing_baseline_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/4730280/rt_orion_intel_verify_against_existing_baseline_fail_test.log)

I then created a new baseline for date tag 20200603, all tests pass in the create step.

[rt_orion_intel_create.log](https://github.com/ufs-community/ufs-weather-model/files/4730283/rt_orion_intel_create.log)

Finally, I ran the regression test against the newly created baseline and all tests pass. Logs updated in the PR.

[rt_orion_intel_verify.log](https://github.com/ufs-community/ufs-weather-model/files/4730805/rt_orion_intel_verify.log)

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
