### PR TITLE
Faster compile and HAFS app to be compiled with 64bit

### LINKED ISSUE #1572: Test the FASTER compile option in UFS applications
## Description
The FASTER compile option is added to UFS to speed up the HAFS runs. This compile option needs to be tested in all the UFS applications for reproducibility and run time saving. If that is confirmed, we will replace the RELEASE compile mode options with the FASTER compile options.

## Solution
Test the FASTER compile option in other applications including: ATM, S2SWA, NG-GODAS, ATML and ATMAQ

### PR DESCRIPTION
**Pull request by sadeghitabas**
…MAQ in rt.conf

## Description
This PR contains changes to rt.conf for FASTER compile UFS regression tests. 
Changes to rt.conf:
- FASTER compile option turned on for ATM, S2SWA, NG-GODAS, ATML and ATMAQ

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):
PR https://github.com/ufs-community/ufs-weather-model/pull/1610
## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Closes https://github.com/ufs-community/ufs-weather-model/issues/1572
- Linked PR: https://github.com/ufs-community/ufs-weather-model/pull/1610
## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@SadeghTabas-NOAA Code change looks good to me. Please run RT to check the run time change and if there are any failed test. Thanks

**Comment by sadeghitabas** [comment]
hera.intel job completed. RT passed, however the runtime increased significantly.

**Comment by sadeghitabas** [comment]
It looks like, the FASTER compile option makes the runs significantly slower than before. Please find the full RT results for Orion and Hera in the following directory:
Orion: /work/noaa/nems/stabas/git/PR1578/
Hera: /scratch1/NCEPDEV/nems/Sadegh.Tabas/git/SadeghTabas-NOAA/PR1578_20230130

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA I was wondering if it slows down across all cases? then, we may need more time for the pr.

**Comment by sadeghitabas** [comment]
@jkbk2004 I'm doing the RT test for jet and gaea as well, I'll let you know once its done, I'll upload the logs here.

**Comment by sadeghitabas** [comment]
RT job on jet completed, the FASTER compile option makes the runs significantly slower than before. Please find the full RT results for jet in the following directory:
jet: /lfs4/HFIP/h-nems/Sadegh.Tabas/git/SadeghTabas-NOAA/PR1578/

**Comment by BrianCurtis-NOAA** [comment]
Seems that the verdict is we should not use the FASTER option at all?

**Comment by sadeghitabas** [comment]
@BrianCurtis-NOAA I guess the current version of Faster Compile makes the process much slower and it needs modification or not using it at all.

**Comment by sadeghitabas** [comment]
I made a [google sheet](https://docs.google.com/spreadsheets/d/1yy-hU8xNj6o0NKAEDUW2LmHgeLvzg13Ue-vSy0NKA4E/edit?usp=sharing) for the Faster Compile option results. It seems Faster Compile made the Compiles process slower, however it increased the speed for the Tests.

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA #1604 was merged. can you sync up? mainly log files. it might be easier way to save your log files and attach in the PR after sync up.

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA mom6/fv3 restart file format was updated. you can take a look: https://github.com/SadeghTabas-NOAA/ufs-weather-model/blob/FASTER_Compile_Test/tests/tests/control_p8 Another thing to check is this pr adds 4 *_faster test cases and no impact on all other cases. Then, we might combine with #1610. We need to point to @DusanJovic-NOAA hafs_64bit_fms fv3 branch. Sorry I am flipping my mind about combing PRs. If you agree, we can save time in that way.

**Comment by sadeghitabas** [comment]
@jkbk2004 Thanks for letting me know, do I just need to update control_p8_faster test or we need to do the RTs again as well? Also, do you want me to combine with https://github.com/ufs-community/ufs-weather-model/pull/1610 or Dusan is going to do that? Thanks

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA cpld_control_p8_faster, datm_cdeps_control_cfsr_faster, and regional_atmaq_faster are needed to be updated for new restart file format. Take a look at files (tests/tests directory) of cpld_control_p8, datm_cdeps_control_cfsr, and regional_atmaq. Once you update those, I can give a try to test on cheyenne.

**Comment by sadeghitabas** [comment]
@jkbk2004 I've updated those tests, please feel free to give it a try on cheyenne. Thanks

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA those four cases are running ok on cheyenne. I will revert BL_DATE. I want to wait a bit more to see if @DusanJovic-NOAA can sync up his fv3 branch at #1610.

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA can you point to Dusan's fv3 branch and hash https://github.com/DusanJovic-NOAA/fv3atm/tree/c2c1c8de76d9bb187fbec035a00beaec0f2ace56 ?

**Comment by jkbk2004** [comment]
gitmodules change
  url = https://github.com/DusanJovic-NOAA/fv3atm
  branch = hafs_64bit_fms

and fv3 submodule pointer update to the hash https://github.com/DusanJovic-NOAA/fv3atm/tree/c2c1c8de76d9bb187fbec035a00beaec0f2ace56

**Comment by sadeghitabas** [comment]
@jkbk2004 Its combined with https://github.com/ufs-community/ufs-weather-model/pull/1610. Sorry for the delay. Thanks

**Comment by zach1221** [comment]
Please see jenkins-ci logs attached. ORTs have passed.
[ufs-weather-model » ort-docker-pipeline » PR-1578 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10889076/ufs-weather-model.ort-docker-pipeline.PR-1578.1.Console.Jenkins.pdf)

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1213491813/20230304082210/ufs-weather-model
[RT] Error: Test datm_cdeps_control_gefs 132 failed in run_test failed 
[RT] Error: Test datm_cdeps_ciceC_cfsr 135 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_gefs 137 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1213491813/20230304203007/ufs-weather-model
[RT] Error: Test cpld_control_p8_faster 021 failed in check_result failed 
[RT] Error: Test cpld_control_p8_faster 021 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
Cheyenne and Gaea sporadically unstable. re-submission of jobs worked out ok for failed cases.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @SadeghTabas-NOAA once tests are confirmed on wcoss2, this pr is ready for merging.

**Comment by DeniseWorthen** [comment]
@SadeghTabas-NOAA Could you please edit the title so that we can easily see in the commit list that this also committed the change for HAFs in 64 Bit mode?

**Comment by sadeghitabas** [comment]
@BrianCurtis-NOAA  Thanks,
@DeniseWorthen I modified the title, thanks.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 @SadeghTabas-NOAA All WCOSS2 related testing is completed. Apologies for the delay.

**Review by zach1221 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA fv3 pr was merged. Can you update submodule pointer and revert change in gitmodules?

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA can you make sure about fv3 hash? correct one is https://github.com/NOAA-EMC/fv3atm/commit/841842846333801890cd3166c36581a6e9c2267b

**Pull request merged**
