### PR TITLE
Fifth reconciliation PR from production/RRFS.v1

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:

This work is identical to https://github.com/ufs-community/ufs-weather-model/pull/2214, but targeting the develop branch instead.

This is work from @jordanschnell and their description is as follows:
For ebb_dcycle==1 (retrospective fire emissions), the 3-d emissions were incorrectly assgined assigned at all levels using the surface data.

### Commit Message:

```
* UFSWM - Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)
  * FV3 - Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)
    * ccpp-physics - Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)
```

### Priority:

* High: Needed for SRW App

### UFSWM:

* None

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/884
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/231

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
As of Monday morning Dec. 9, I'm re-running regression tests due to a bug fix that I needed to add into https://github.com/ufs-community/ccpp-physics/pull/231. This bugfix is expected to change the same tests as in https://github.com/ufs-community/ccpp-physics/pull/194: merra2_thompson intel
atmaero_control_p8_rad_micro intel

**Comment by jkbk2004** [comment]
@grantfirl can you sync up branches? We can start working on this pr.

**Comment by grantfirl** [comment]
> @grantfirl can you sync up branches? We can start working on this pr.

OK, it should be ready to test. Regarding my retests, they actually didn't cause changes to the other tests (merra2_thompson intel
atmaero_control_p8_rad_micro intel) as expected. So, the original test_changes.list that is currently committed should still be valid, I think.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 and Acorn are down tomorrow. We might need to move on to a PR that doesn't change baselines.

**Comment by jkbk2004** [comment]
@grantfirl we can restart testing this pr. can you sync up branch one more time?

**Comment by grantfirl** [comment]
> @grantfirl we can restart testing this pr. can you sync up branch one more time?

@jkbk2004 Finished syncing

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @FernandoAndrade-NOAA We can go ahead to merge if we skip acorn.

**Comment by BrianCurtis-NOAA** [comment]
I have a ticket about some Acorn issues sent out without a resolution yet. We can skip that machine.

**Comment by jkbk2004** [comment]
@grantfirl new fv3 hash is https://github.com/NOAA-EMC/fv3atm/commit/a7d46eee01a78f0915373ebc58c9b20ba14a6c36

**Review by NickSzapiro-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
