### PR TITLE
Ignore empty fv3atm output bundle

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

Fix model crash if one or the fv3atm output bundles does not have any field. See: https://github.com/NOAA-EMC/fv3atm/issues/676

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Library Updates/Changes

- [ ] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Depends on NOAA-EMC/fv3atm/issues/676
- Depends on fv3atm Sub-pr - (https://github.com/NOAA-EMC/fv3atm/pull/679)

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Review by junwang-noaa — DISMISSED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA We consider to combine this pr with #1811. can you sync up branch? so we can prepare.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA Once #1815 is ready, we will let #1815 go first though.

**Comment by DusanJovic-NOAA** [comment]
My branches are updated.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA Can you take a look at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_98984/rrfs_smoke_conus13km_fast_phy32_qr_intel ? It crashes.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Can you take a look at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_98984/rrfs_smoke_conus13km_fast_phy32_qr_intel ? It crashes.

I just updated FV3 submodule.

**Comment by DusanJovic-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12112422/RegressionTests_hera.log)

**Comment by zach1221** [comment]
Hello, @DusanJovic-NOAA . PR 1794 has been merged. Can you sync up your branch with develop and resolve conflicts here? That way we can begin testing through this PR next.

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA @zach1221 could we add #1813 to this?

**Comment by zach1221** [comment]
> @DusanJovic-NOAA @zach1221 could we add #1813 to this?

I'm ok with that, if Dusan is. I can just copy over the template and commit directly to this PR.

**Comment by DusanJovic-NOAA** [comment]
> > @DusanJovic-NOAA @zach1221 could we add #1813 to this?
> 
> I'm ok with that, if Dusan is. I can just copy over the template and commit directly to this PR.

I'm also ok with that.

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins ci log is attached, ORTs passed. 
[ufs-weather-model » ort-docker-pipeline » PR-1825 #1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/12187311/ufs-weather-model.ort-docker-pipeline.PR-1825.1.Console.Jenkins.txt)

**Comment by zach1221** [comment]
Testing is complete. I'll follow up on the fv3atm sub-pr to begin the merging process.

**Comment by BrianCurtis-NOAA** [comment]
New FV3 hash: https://github.com/NOAA-EMC/fv3atm/commit/1158696c9bbf3500525e08d398d0ade345793ea3

**Comment by zach1221** [comment]
@DusanJovic-NOAA fv3atm sub-pr #679 has been merged. Please update the submodule point revert the change in gitmodules.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Comment by zach1221** [comment]
Closes #1813

**Pull request merged**
