### PR TITLE
Supplementary physics updates for RRFS code freeze

### PR DESCRIPTION
**Pull request by haiqinli**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [ ] Add list of all failed regression tests in "Regression Tests" section.

### Description

This is a supplementary physics update PR for the RRFS code freeze. Thanks updates are as follows:
MYNN: 1) cosmetic fix to the cloud fractions in (relatively rare) conditions with unsaturated grid cells and positive mixing ratios; 2) very slight increase in diffusion in stable conditions; 3) momentum transport bug fix--missing rho.
RUC LSM: Computation of the new snow fraction uses now snow with variable density to reduce cold bias.
GF: Adjust the scale-awareness in the 1st hour forecast to reduce precipitation bias.
Smoke and Dust: Fix the diurnal cycle of smoke, dust emission over frozen soil, dry deposition.

### Priority
- [X] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Blocking Dependencies

fv3atm PR[#773](https://github.com/NOAA-EMC/fv3atm/pull/773)
ccpp-physics PR[#161](https://github.com/ufs-community/ccpp-physics/pull/161)

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [X] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

FAILED TESTS:
control_p8_mynn_intel regional_control_intel regional_decomp_intel regional_2threads_intel
regional_noquilt_intel regional_netcdf_parallel_intel regional_2dwrtdecomp_intel
regional_wofs_intel rap_control_intel regional_spp_sppt_shum_skeb_intel rap_decomp_intel 
rap_2threads_intel rap_sfcdiff_intel rap_sfcdiff_decomp_intel hrrr_control_intel
hrrr_control_decomp_intel hrrr_control_2threads_intel rrfs_v1beta_intel
rrfs_v1nssl_intel rrfs_v1nssl_nohailnoccn_intel regional_control_faster_intel
regional_debug_intel rap_control_debug_intel hrrr_control_debug_intel
hrrr_gf_debug_intel hrrr_c3_debug_intel rap_unified_drag_suite_debug_intel
rap_diag_debug_intel rap_cires_ugwp_debug_intel rap_unified_ugwp_debug_intel
rap_lndp_debug_intel rap_progcld_thompson_debug_intel rap_noah_debug_intel
rap_sfcdiff_debug_intel rap_noah_sfcdiff_cires_ugwp_debug_intel rrfs_v1beta_debug_intel
rap_clm_lake_debug_intel rap_flake_debug_intel gnv1_c96_no_nest_debug_intel
regional_spp_sppt_shum_skeb_dyn32_phy32_intel rap_control_dyn32_phy32_intel
hrrr_control_dyn32_phy32_intel rap_2threads_dyn32_phy32_intel
hrrr_control_2threads_dyn32_phy32_intel hrrr_control_decomp_dyn32_phy32_intel
conus13km_control_intel  rap_control_dyn64_phy32_intel rap_control_debug_dyn32_phy32_intel
hrrr_control_debug_dyn32_phy32_intel conus13km_debug_intel conus13km_debug_qr_intel
conus13km_debug_2threads_intel conus13km_radar_tten_debug_intel
rap_control_dyn64_phy32_debug_intel gnv1_nested_intel rap_control_gnu
rap_decomp_gnu rap_2threads_gnu rap_sfcdiff_gnu rap_sfcdiff_decomp_gnu
hrrr_control_gnu hrrr_control_noqr_gnu hrrr_control_2threads_gnu hrrr_control_decomp_gnu
rrfs_v1beta_gnu regional_debug_gnu rap_control_debug_gnu hrrr_control_debug_gnu
hrrr_gf_debug_gnu hrrr_c3_debug_gnu rap_diag_debug_gnu rap_noah_sfcdiff_cires_ugwp_debug_gnu
rap_progcld_thompson_debug_gnu rrfs_v1beta_debug_gnu rap_flake_debug_gnu
rap_clm_lake_debug_gnu gnv1_c96_no_nest_debug_gnu rap_control_dyn32_phy32_gnu
hrrr_control_dyn32_phy32_gnu rap_2threads_dyn32_phy32_gnu hrrr_control_2threads_dyn32_phy32_gnu
hrrr_control_decomp_dyn32_phy32_gnu conus13km_control_gnu rap_control_dyn64_phy32_gnu
rap_control_debug_dyn32_phy32_gnu hrrr_control_debug_dyn32_phy32_gnu conus13km_debug_gnu
conus13km_debug_qr_gnu conus13km_debug_2threads_gnu
conus13km_radar_tten_debug_gnu rap_control_dyn64_phy32_debug_gnu

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by zach1221** [comment]
Hi, @haiqinli . We may begin testing against this PR next. Can you please sync up your branch?

**Comment by grantfirl** [comment]
> Hi, @haiqinli . We may begin testing against this PR next. Can you please sync up your branch?

The physics PR hasn't been reviewed yet. I'll work on that now.

**Comment by grantfirl** [comment]
> > Hi, @haiqinli . We may begin testing against this PR next. Can you please sync up your branch?
> 
> The physics PR hasn't been reviewed yet. I'll work on that now.

The ccpp-physics PR is approved and ready to test. @zach1221

**Comment by zach1221** [comment]
Thanks, @grantfirl . I think we may combine this PR into 1845. We'll keep you posted.

**Comment by jkbk2004** [comment]
merged with #1845

**Pull request closed without merging**
