### PR TITLE
[production/AQM.v7] Revert AQM Debug mode changes that are causing strange issues in retro runs

### LINKED ISSUE #1581: The latest AQM workflow got strange O3 and PM2.5 predictions
## Description

AQM with the latest workflow was tested and shows very strange behavior for both O3 nd PM2.5 predictions.  It seems that the model may not be able to read emissions correctly ?

Tracking along with NOAA-EMC/AQM/issues/56

  - #1583

## Output

plot_grp1 timeseries OZONE 2022-07-01_12 2022-07-18_12 all CONUS
plot_grp1 timeseries PM2 5 2022-07-01_12 2022-07-18_12 all CONUS

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Description

This PR reverts code changes in AQM causing unexpected behavior in retro runs.

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [X] Changes are expected to the following tests: 

regional_atmaq baselines will change and regional_atmaq_debug will no longer be tested

## Subcomponents involved:
- [X] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

 - Fixes #1581
 - Depends on NOAA-EMC/AQM/pull/57

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Hera is another system used by the AQM group. I will get hera added to RT in the PR that will bring in new changes to allow AQM to run in debug mode. @jkbk2004 Do you see any other needs before merge?

**Comment by jkbk2004** [comment]
> Hera is another system used by the AQM group. I will get hera added to RT in the PR that will bring in new changes to allow AQM to run in debug mode. @jkbk2004 Do you see any other needs before merge?

Actually no! We can follow up on develop branch separately.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 should look good, double check and feel free to merge.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I want to confirm again about BL_DATE=20230128, looks like the production branch was cut with BL_DATE=20230112. Creating new one with 20230128 wasn't bad idea. We can follow up on other machines same way.

**Comment by BrianCurtis-NOAA** [comment]
Yes this is intended as the production baselines will diverge from develop branch.

**Pull request merged**
