### PR TITLE
Combo for ccpp/physics #41 and #45 and ccpp/framework submodule pointer update for #462

### LINKED ISSUE #44: add three parameters to namelist for NSSL MP
## Description
To support RRFS multiphysics ensemble, three parameters in NSSL MP are being added to input.nml, including rain shape parameter (nssl_alphar), graupel-droplet collection efficiency (nssl_ehw0_in) and hail-droplet collection efficiency (nssl_ehlw0_in)

## Solution
Related PR will be submitted shortly

### PR DESCRIPTION
**Pull request by grantfirl**
## Description
This PR combines 2 ccpp/physics PRs and 1 ccpp/framework PR.

ccpp/physics PR41: changes CMakeLists.txt to depend on the SP library. This is required for JEDI: https://github.com/JCSDA/ufs-bundle/issues/19

ccpp/physics PR45: exposes 3 NSSL MP parameters to the physics namelist

ccpp/framework PR462: addresses an error message bug in the unit conversion part of ccpp_prebuild

**No answer changes are expected for any of these changes.**

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [X] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [X] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [X] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
https://github.com/ufs-community/ccpp-physics/pull/53
https://github.com/NOAA-EMC/fv3atm/pull/634

- fixes https://github.com/ufs-community/ccpp-physics/issues/44
- partially addresses https://github.com/JCSDA/ufs-bundle/issues/19
- fixes https://github.com/NCAR/ccpp-framework/issues/458

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [X] Hera
    - [x] Orion
    - [ ] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by grantfirl** [comment]
Hera/Intel full RT log (SUCCESSFUL):

[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10963069/RegressionTests_hera.intel.log)

**Comment by zach1221** [comment]
Hi, @grantfirl! We're going to begin working to test/review this PR soon, could you sync up your branch, please?

**Comment by jkbk2004** [comment]
@grantfirl #1547 was merged: ww3 hash update (https://github.com/NOAA-EMC/WW3/tree/af544dca5bf49bf3c3ad8d47b786e8211dcf4bba).

**Comment by grantfirl** [comment]
@jkbk2004 OK, I'll update the PR branches now. Sorry for the delay.

**Comment by jkbk2004** [comment]
sure!

**Comment by grantfirl** [comment]
@zach1221 @jkbk2004 OK, only the ufs-weather-model branch needed to be updated, so everything should be good to test now.

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Review by Qingfu-Liu — DISMISSED** [review]

**Comment by zach1221** [comment]
Please see jenkins-ci ORT logs attached. Everything passed ok.
[ufs-weather-model » ort-docker-pipeline » PR-1654 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10973360/ufs-weather-model.ort-docker-pipeline.PR-1654.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1273689206/20230314153054/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /mnt/lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1273689206/20230315000052/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1273689206/20230314203030/ufs-weather-model
[RT] Error: Test cpld_debug_p8 015 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by zach1221** [comment]
Hi, @grantfirl . Could you provide me with permission to push logs to this PR?

**Comment by grantfirl** [comment]
@zach1221 I invited you as a collaborator to my fork of ufs-weather-model. I think that this should do it.

**Comment by jkbk2004** [comment]
All cases ran ok on orion but rt script exit out w/o cat logs. Manually updated the log for orion.

**Comment by jkbk2004** [comment]
jet is not stable. no baseline change. so we will skip jet.

**Comment by jkbk2004** [comment]
cpld_control_p8_faster case on cheyenne. it takes about 1819 to 1879 compile time. But the case itself builds ok if build time is extended.

**Comment by zach1221** [comment]
@grantfirl We can start the merge process now. Can you please merge your ccpp PR ?

**Comment by grantfirl** [comment]
> @grantfirl We can start the merge process now. Can you please merge your ccpp PR ?

@zach1221 OK, I merged the ccpp PR and updated the fv3atm PR branch in anticipation of merge.

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Review by sadeghitabas — DISMISSED** [review]

**Comment by grantfirl** [comment]
I updated .gitmodules and FV3 submodule pointer after fv3atm merge. This is ready for final review/merge.

**Review by jkbk2004 — APPROVED** [review]

**Comment by zach1221** [comment]
@SadeghTabas-NOAA would you be able to provide approval once more? You previous one was dismissed after the commit.

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
