### PR TITLE
CCPP CMake cleanup, update submodule pointer for stochastic_physics to include emergency bugfix for restart runs

### LINKED ISSUE #945: Cleanup of CCPP Cmake build config, fix bug in 32-bit compiler flags passed to ccpp-physics
## Description
Despite several rounds of improvement, there is still redundancy w.r.t. how the CCPP cmake build is configured in the UFS WM (and fv3atm). In a next step, the following items will be addressed:
- Clean up the the complicated logic inside ccpp-physics' `CMakeLists.txt` that deals with special compiler flags for certain files, turning off OpenMP for another set of files. Currently, this is repeated for each compiler. This can be rearranged and unnecessary logic replaced. This will require adjustments in the ufs-weather-modeel and fv3atm cmake configs.
- Remove legacy cmake settings in both ccpp-physics and ccpp-framework. These settings are an artifact from the "good old days" when the UFS WM (NEMSfv3gfs at that time) used gnumake, but CCPP already used cmake. When UFS switched to cmake, not all of the now redundant settings were removed.
- Further legacy code stems from different settings for the two host models UFS and SCM, which is no longer required due to refactoring the cmake builds for the host models. This is a big step towards making the CCPP build config host model independent.
- Lastly, with the removal of the dynamic CCPP two years ago, several settings in the ccpp-framework and ccpp-physics `CMakeLists.txt` are no longer required.

While working on this, it was also found that the 32-bit UFS WM build incorrectly passes the `-no-prec-div -no-prec-sqrt` flags for the "fast physics" (saturation adjustment) to ccpp-physics. These should only be passed to the "slow physics", which are always built in 64-bit, but not to the fast physics when built in 32-bit.

## Solution
Clean up ccpp-framework and ccpp-physics various `CMakeLists.txt` files and make the necessary adjustments and corrections in fv3atm and ufs-weather-model. Following the commit, an update for the CCPP SCM build system will be required.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR makes changes in the CMake config files for Intel and GNU that are required by the cleanup of the CCPP cmake config in fv3atm, ccpp-framework, ccpp-physics.

This also fixes a bug in the current build config that adds `-no-prec-div -no-pre-sqrt` to the CCPP 32bit compile options, although it should only be added to the 64bit compile options. This used to be the case in the past when IPD and CCPP coexisted, but for some unknown reason the bug was introduced since then.

This bug fix changes the results of all 32bit regression tests that use GFDL MP with the saturation adjustment in the dycore. In addition, because the flag `-xCORE-AVX2` is removed from the ccpp-physics compiler flags, the preceding `-march=core-avx2` applies and the results of most other regression tests change as well. Removing the Intel-chip specific flags is something that was recommended to us because the next operational system wcoss2 does not have Intel chips.

Last minute change 2021/12/13: the submodule pointer for ccpp-physics is updated to include an emergency bugfix for the cellular automata code when the model is warm-started and the CA restart files are not in the input directory (https://github.com/noaa-psd/stochastic_physics/pull/50). This does not affect the UFS WM regression tests (verified by running the regression tests with the emergency bugfix included against the newly created baseline that did not have the emergency bugfix).

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/945

## Testing

Regression tests were run on Hera with Intel and GNU during the development. Full regression tests will be run on all tier-1 platforms at the time of commit.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/943/commits/f826dbabbaa365264e7e9adbfed8d9551f93486a

**Rerun of regression tests/CI tests against newly created baselines after including the stochastic_physics emergency bugfix:**
- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/943/commits/8395e78c9b1a50fc99a6408c03de07ac518adeaf

## Dependencies

- waiting on https://github.com/NCAR/ccpp-framework/pull/420
- waiting on https://github.com/NCAR/ccpp-physics/pull/792
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/436

### CODE REVIEW

**Review by SamuelTrahanNOAA — APPROVED** [review]
Remember to change the .gitmodules back!

**Review by aerorahul — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@climbfuji Will this PR also fix the ufs-weather-model REPRO mode?

**Comment by climbfuji** [comment]
> @climbfuji Will this PR also fix the ufs-weather-model REPRO mode?

Yes, I am confident it does. Here are the REPRO compiler flags for one file in ccpp-physics. Notice that there is no `-O3` flag anymore:
```
cd /scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-develop-cleanup-cmake-flags-part2/intel_repro/tests/build_fv3/FV3/ccpp/physics && /apps/intel/compilers_and_libraries_2018/linux/mpi/intel64/bin/mpiifort -DFV3 -DINTERNAL_FILE_NML -DMOIST_CAPPA -DMPI -DNEMS_GSM -DREPRO -DUSE_COND -I/scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-develop-cleanup-cmake-flags-part2/intel_repro/tests/build_fv3/FV3/ccpp/physics -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/w3nco/2.4.1/include_d -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/include -g -traceback -fpp -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -nowarn -sox -align array64byte -qno-opt-dynamic-align -real-size 64 -O2 -debug minimal -fp-model consistent -qoverride-limits -O2 -fPIC   -qopenmp -c /scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-develop-cleanup-cmake-flags-part2/intel_repro/FV3/ccpp/physics/physics/mp_thompson_pre.F90 -o CMakeFiles/ccpp_physics.dir/physics/mp_thompson_pre.F90.o
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/794640118/20211213191515/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_144999
Test compile_006 failed in run_compile failed 
Please make changes and add the following label back:
jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
All regression tests passed, also for the rerun after updating the submodule pointer for `stochastic_physics` to include an emergency bugfix. Will start with merging the CCPP PRs.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by climbfuji** [comment]
Hash for fv3atm is correct (a1b0f33), ready to merge.

**Pull request merged**
