### PR TITLE
Sync with ESCOMP/CDEPS (2024-12-16) + Add support for traditional threading (#2533)

### PR DESCRIPTION
**Pull request by NickSzapiro-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Merge authoritative ESCOMP into EMC fork for bug fix for alarm code in CDEPS share code used by CMEPS

Description of adding support for traditional threading is available in https://github.com/ufs-community/ufs-weather-model/pull/2533

### Commit Message:

```
* UFSWM - This PR adds support for traditional (non esmf managed) threading. ESMF managed threading is still default.
* UFSWM - Sync with ESCOMP/CDEPS (2024-12-16)
  * CDEPS - Sync with ESCOMP/CDEPS (2024-12-16)
```

### Priority:

* High: bugfix blocking CMEPS from writing mediator history files (critical for debugging)

### UFSWM:

* Closes #https://github.com/NOAA-EMC/CDEPS/issues/67

### Sub component Pull Requests:

* CDEPS: https://github.com/NOAA-EMC/CDEPS/pull/68

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Review by DeniseWorthen — DISMISSED** [review]
Looks good. Thanks for getting this fix in so quickly.

**Comment by jkbk2004** [comment]
@NickSzapiro-NOAA Please, go ahead to sync up branch and combine in #2533. @DusanJovic-NOAA FYI

**Comment by NickSzapiro-NOAA** [comment]
I can do this in an hour or two. Please feel free to make the changes, if
that makes a difference

**Comment by NickSzapiro-NOAA** [comment]
@jkbk2004 @DusanJovic-NOAA Should be ready

**Comment by jkbk2004** [comment]
we can start merging process.

**Comment by NickSzapiro-NOAA** [comment]
CDEPS was merged and updated here. Should be ready. Thank you @jkbk2004 @BrianCurtis-NOAA

**Review by jkbk2004 — APPROVED** [review]

**Review by dpsarmie — APPROVED** [review]

**Pull request merged**
