### PR TITLE
Bug fix for ccpp-physics routine sfcsub.F

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on Hera.
- [x] Commit 'test_changes.list' from previous step
---
## Description:

A bug fix was made to ccpp-physics routine sfcsub.F. This PR updates the version
of ccpp-physics used by ufs-weather-model.

### Commit Message:

  * FV3 - 
    * ccpp-physics - In sfcsub.F, fix the setting of the model land mask used to interpolate GLDAS data.

### Priority:

* Normal

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/827
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/202

### UFSWM Blocking Dependencies:

* None

### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
All regression tests passed on Hera: 
https://github.com/GeorgeGayno-NOAA/ufs-weather-model/blob/sfcsub_fix/tests/logs/RegressionTests_hera.log

**Comment by jkbk2004** [comment]
@GeorgeGayno-NOAA Can you sync up the branches? We will try to see if we can combine along with #2215 and #2254.

**Comment by grantfirl** [comment]
> @GeorgeGayno-NOAA Can you sync up the branches? We will try to see if we can combine along with #2215 and #2254.

@jkbk2004 I've already combined this into #2264. I'll get it updated, although there was a little discussion left on one of the combined ccpp-physics PRs that is finishing up.

**Comment by jkbk2004** [comment]
> > @GeorgeGayno-NOAA Can you sync up the branches? We will try to see if we can combine along with #2215 and #2254.
> 
> @jkbk2004 I've already combined this into #2264. I'll get it updated, although there was a little discussion left on one of the combined ccpp-physics PRs that is finishing up.

@grantfirl thanks for the note! it helps. We will separately go with #2215 and #2254.

**Comment by grantfirl** [comment]
@jkbk2004 This can be closed in favor of https://github.com/ufs-community/ufs-weather-model/pull/2264

**Pull request closed without merging**
