### PR TITLE
Add CLM Lake Model and update Flake

### LINKED ISSUE #1510: Add the CLM Lake Model and generate lake data on a regional grid.
## Description
The operational upgrade plan for RRFS is to run the CLM Lake Model. Hence, we must implement that in UFS.

## Solution
Add it to CCPP.

## Alternatives
Switch back to WRF? Get the Flake model to work, and produce good results?

## Related to
No related issues.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description
This PR adds the CLM Lake Model, updates the Flake model, and adds an experimental feature to run both NSST and a lake model on lake points. The FV3_HRRR suite uses clm_lake by default, and the long-forgotten control_flake tests now exists.

### Input data additions/changes
- [x] There will be new input data. 

HERA: /scratch2/BMC/wrfruc/Samuel.Trahan/lakes/RT/NEMSfv3gfs/input-data-20221101/lake_p8_water_fraction2020

### Anticipated changes to regression tests:
- [x] Changes are expected to the following tests: 

Only tests that have lake data and LKM=1 will change results. This is the list:

- control_flake
- hrrr_control
- hrrr_control_decomp
- hrrr_control_2threads
- hrrr_control_restart
- hrrr_control_debug
- rap_clm_lake_debug
- rap_flake_debug
- hrrr_control_dyn32_phy32
- hrrr_control_2threads_dyn32_phy32
- hrrr_control_decomp_dyn32_phy32
- hrrr_control_restart_dyn32_phy32
- hrrr_control_debug_dyn32_phy32

To test this, I did the following for hera.intel and hera.gnu:

1. Ran against the 20230407 baseline to get the list of tests that change.
2. Copied the baseline data and replaced only the changed tests' baselines.
3. Verified against that.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Closes https://github.com/ufs-community/ufs-weather-model/issues/1510
- Depends on https://github.com/ufs-community/ccpp-physics/pull/26
- Depends on https://github.com/NOAA-EMC/fv3atm/pull/606
- Depends on https://github.com/NOAA-EMC/CMEPS/pull/77

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [x] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]
@SamuelTrahanNOAA As far as I can tell, the changes in this repository are all good.

**Review by tanyasmirnova — APPROVED** [review]

**Review by tanyasmirnova — DISMISSED** [review]

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA the 2thread problem is fixed now in rrfs? Great news!

**Comment by SamuelTrahanNOAA** [comment]
> the 2thread problem is fixed now in rrfs? Great news!

I think so. I forgot to turn on frac_ice in the conus13km tests, though. I'm rerunning now to confirm that works.

**Comment by SamuelTrahanNOAA** [comment]
It works. I've taken the PRs out of draft status. I'm working on the finishing touches now: move the new input data, update subcomponents, and double-check everything.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 At long last, this PR is ready for review and testing.

**Review by tanyasmirnova — DISMISSED** [review]

**Comment by grantfirl** [comment]
@jkbk2004 The ccpp-physics PR has been reviewed/approved. I think that this is ready to work on whenever UFS code managers can fit it in the queue.

**Comment by zach1221** [comment]
@SamuelTrahanNOAA We'll start working through this PR next. @BrianCurtis-NOAA fyi.

**Comment by SamuelTrahanNOAA** [comment]
I have updated this to the top of develop. It is ready for review and testing.

**Comment by SamuelTrahanNOAA** [comment]
This PR needs new input data. Make sure you propagate that data, or the tests will fail.

From the PR description:

HERA: /scratch2/BMC/wrfruc/Samuel.Trahan/lakes/RT/NEMSfv3gfs/input-data-20221101/lake_p8_water_fraction2020

**Comment by BrianCurtis-NOAA** [comment]
> This PR needs new input data. Make sure you propagate that data, or the tests will fail.
> 
> From the PR description:
> 
> HERA: /scratch2/BMC/wrfruc/Samuel.Trahan/lakes/RT/NEMSfv3gfs/input-data-20221101/lake_p8_water_fraction2020

@jkbk2004 @zach1221 On hera you need to get his data into the input directory before we can sync

**Comment by zach1221** [comment]
Ok, since there's new input data, I'll just run the ORTs manually on Hera, as the jenkins-ci input-data image will need to be updated.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @zach1221 all rsynced ok. new input files at: /scratch2/BMC/wrfruc/Samuel.Trahan/lakes/RT/NEMSfv3gfs/input-data-20221101/lake_p8_water_fraction2020

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA @zach1221 all rsynced ok. new input files at: /scratch2/BMC/wrfruc/Samuel.Trahan/lakes/RT/NEMSfv3gfs/input-data-20221101/lake_p8_water_fraction2020

Then machines need to sync with: /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/

**Comment by SamuelTrahanNOAA** [comment]
>  /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/

Wasn't November 1, 2022 a while ago? Why don't you change the date?

**Comment by zach1221** [comment]
ORTs passed successfully on Orion.

**Comment by BrianCurtis-NOAA** [comment]
> > /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/
> 
> Wasn't November 1, 2022 a while ago? Why don't you change the date?

Typically we only change the input-data if there is a large/major change needed for RT's/new features that overwrites current input data. If there is new input data like this PR, then we can just add it to that instead.

**Comment by zach1221** [comment]
Since there's only a few tests that have changed baselines, I'm creating the new ones manually. I'll add the RT labels once finished.

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1142034258/20230425092639/ufs-weather-model
[RT] Error: Test control_flake 005 failed in check_result failed 
[RT] Error: Test control_flake 005 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1142034258/20230425090417/ufs-weather-model
[RT] Error: Test compile_008 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1142034258/20230425173015/ufs-weather-model
[RT] Error: Test control_flake 005 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by zach1221** [comment]
We'll skip Gaea on this PR, so testing is finished and we can begin the merging process @SamuelTrahanNOAA .

**Comment by DeniseWorthen** [comment]
CMEPS is ready [fe2c158](https://github.com/NOAA-EMC/CMEPS/commit/fe2c15820c27808260c313fa5caa0ae69e987dae)

**Comment by SamuelTrahanNOAA** [comment]
The FV3 and CMEPS submodules now point to their authoritative repos and hashes.

**Comment by zach1221** [comment]
I'll request final approval and then we should be able to merge this PR.

**Review by jkbk2004 — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
