### PR TITLE
HAFSv1 needed HYCOM, UPP, g2tmpl, ugwp, and moving nesting related updates

### LINKED ISSUE #1543: Update submodule FV3/upp for HAFSv1
## Description
Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Update submodule FV3 to point to the latest UPP develop branch, needed for HAFSv1 code freeze.

## Solution
Add a clear and concise description of what you want to happen.
Update submodule FV3/upp

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.
N/A

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- fixed by ufs-community/ufs-weather-model/pull/<pr_number>
- fixed by noaa-emc/fv3atm/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [x] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

HAFSv1 needed updates and changes, including:
- Update submodule FV3/UPP to point its latest develop branch and update postxconfig-NT-hafs.txt.
- Switch to use g2tmpl/1.10.2.
- Switch to use the unified ugwp scheme for HAFS CCPP suites and regression tests.
- Update submodule HYCOM and enable debug and check all build for the HYCOM component (from @danrosen25 and @BijuThomas-NOAA).
- Fix the artificial gravity wave issue caused by HAFS moving nest leading edge crossing steep topography by enable using same coarse grid topography in the moving nest leading edge (from @wramstrom).
- Bug fix in calculation of moving-nest halo weights identified by @BijuThomas-NOAA in DDEBUG=ON builds (from @wramstrom).

Notes: 
- Will change baseline results so new baseline will need to be generated. 
- New input data under FV3_hafs_input_data need to be added/populated.
Please use and populate the following FV3_hafs_input_data to replace its counterpart:
/scratch1/NCEPDEV/hwrf/save/Bin.Liu/RT/NEMSfv3gfs/input-data-20221101/FV3_hafs_input_data
This FV3_hafs_input_data dir is backward compatible, since there are only new files added. No changes for existing files. In this case, no need to update INPUT data version unless that is preferred.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes ufs-community/ufs-weather-model/issues/1543
- addresses ufs-community/ufs-weather-model/issues/1441
- addresses ufs-community/ufs-weather-model/issues/1550

## Testing

Regression tests on WCOSS2 went through successfully. Baseline changes are expected.

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting for noaa-emc/fv3atm/pull/613
- depend upon NOAA-EMC/HYCOM-src/pull/2
- waiting for ufs-community/ufs-weather-model/pull/1554

### CODE REVIEW

**Comment by jkbk2004** [comment]
@BinLiu-NOAA we are working on #1523. It's like to merge in #1523 tomorrow morning. Then we can open up our schedule for this pr, if you are working tomorrow.

**Comment by BinLiu-NOAA** [comment]
Thanks, @jkbk2004! For HAFSv1, we are still waiting for some potential UPP develop branch updates. Also, this PR could be combined with another WW3 submodule update (also needed by HAFSv1). With that, I am setting this PR as draft PR for now.

**Comment by jkbk2004** [comment]
sounds good!

**Comment by jkbk2004** [comment]
@BinLiu-NOAA can we check if it's ok to schedule this pr to commit on Monday? or if you like to merge by Monday morning, then we can make a decision to work from today.

**Comment by BinLiu-NOAA** [comment]
Thanks, @jkbk2004! We are still waiting 1-2 changes from WW3 and/or UPP for this PR. So, if possible, can we try to target this PR merge saying next Wednesday (01/11)? Please also make sure the PR #1554 is ahead of this PR if possible. Thanks!

**Comment by jkbk2004** [comment]
@BinLiu-NOAA we expect baseline change, right? I will add new BL_DATE.

**Comment by jkbk2004** [comment]
Oh! we need to rsync the input data. New data on hera, right?

**Comment by BinLiu-NOAA** [comment]
Thanks, @jkbk2004! Please see the PR description section regarding the INPUT DATA change (copied here as well):

New input data under FV3_hafs_input_data need to be added/populated.
Please use and populate the following FV3_hafs_input_data to replace its counterpart:
/scratch1/NCEPDEV/hwrf/save/Bin.Liu/RT/NEMSfv3gfs/input-data-20221101/FV3_hafs_input_data
This FV3_hafs_input_data dir is backward compatible, since there are only new files added. No changes for existing files. In this case, no need to update INPUT data version unless that is preferred.

BTW, please feel free to update this PR as needed. I am on travel today, might not be able to check emails or GitHub status in time. Thanks!

**Review by WenMeng-NOAA — APPROVED** [review]
The updates of UPP related parts (postxconfi*, g2tmpl, upp revision) look good to me.

**Comment by BrianCurtis-NOAA** [comment]
@BinLiu-NOAA What specific tests are supposed to change? I looked over the PR but didn't see if all tests change or if only maybe the HAFS tests change.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA What specific tests are supposed to change? I looked over the PR but didn't see if all tests change or if only maybe the HAFS tests change.

@BrianCurtis-NOAA, Most (if not all) HAFS RTs will have changing results. In the meantime, the update of pointing to the latest develop branch of UPP as well as the g2tmpl version could change results for other relevant RTs. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1171593275/20230112154512/ufs-weather-model
[BL] Error: Test hafs_regional_specified_moving_1nest_atm 090 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm 091 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn 092 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 094 failed in run_test failed 
[BL] Error: Test compile_012 failed in run_compile failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by BinLiu-NOAA** [comment]
For [BL] Error: Test compile_012 failed in run_compile failed, I saw the following message in:
/scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_395/compile_012/err
```
/scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_395/compile_012/build_fv3_012/FV3/ccpp/physics/ccpp_static_api.F90(14229): error #6405: The same named entity from different modules and/or program units cannot be referenced.   [CDATA]
               ierr = FV3_GFS_cpld_rasmgshocnsst_time_vary_final_cap(cdata=cdata)
---------------------------------------------------------------------------^
compilation aborted for /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_395/compile_012/build_fv3_012/FV3/ccpp/physics/ccpp_static_api.F90 (code 1)
make[2]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/physics/ccpp_static_api.F90.o] Error 1
make[1]: *** [FV3/ccpp/CMakeFiles/fv3ccpp.dir/all] Error 2
make: *** [all] Error 2
```
I am not sure why we got this error on Hera. I am including @ChunxiZhang-NOAA here to see if he has any clues. Thanks!

**Comment by BinLiu-NOAA** [comment]
For the four failed HAFS moving nest RTs on Hera:
[BL] Error: Test hafs_regional_specified_moving_1nest_atm 090 failed in run_test failed
[BL] Error: Test hafs_regional_storm_following_1nest_atm 091 failed in run_test failed
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn 092 failed in run_test failed
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 094 failed in run_test failed
under:
/scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_395/
I am trying to include @wramstrom here for his help to look at this. BTW, another information related, these Hera failed RTs did ran through successfully on my WCOSS2 RT tests though.

**Comment by jkbk2004** [comment]
I tested further on other machines. common failures with hafs_regional_specified_moving_1nest_atm, hafs_regional_storm_following_1nest_atm, hafs_regional_storm_following_1nest_atm_ocn, hafs_regional_storm_following_1nest_atm_ocn_wav

**Comment by jkbk2004** [comment]
build failures seems to be random. When I run manually, most of machines builds ok all intel cases. but I see a similar build failure on jet as hera. I am not sure we are seeing the same behavior as https://github.com/ufs-community/ufs-weather-model/issues/1450

**Comment by BinLiu-NOAA** [comment]
@jkbk2004, thanks for checking the build failure on Hera!

For the HAFS moving-nesting RT failures, we have some updates from @wramstrom. And @BijuThomas-NOAA and I are doing some further testing now. If things go well, we will push into this PR and proceed. Thanks!

**Comment by BinLiu-NOAA** [comment]
> @jkbk2004, thanks for checking the build failure on Hera!
> 
> For the HAFS moving-nesting RT failures, we have some updates from @wramstrom. And @BijuThomas-NOAA and I are doing some further testing now. If things go well, we will push into this PR and proceed. Thanks!

@jkbk2004, Just another update that the HAFS moving-nesting RT failures have been fixed, the HAFS RTs went through on both Hera and WCOSS2. Changes have been committed back to the corresponding PR branches as well.

So, at this point, the only unknown/unclear thing is the "[BL] Error: Test compile_012 failed in run_compile failed" issue on Hera. For that, it is not clear to me what is the root cause (Hera system or something else). I saw @DusanJovic-NOAA was able to compile without issues, but you and @ChunxiZhang-NOAA got the same build error.

With that, if we want to proceed the RTs for this PR, we will need to re-generate the baseline and re-run against the new baseline for all platforms.

Thanks!

**Comment by jkbk2004** [comment]
Sure @BinLiu-NOAA I will start re-running from hera. I will manually run due to the build issue. I keep posing in this conversation.

**Comment by BinLiu-NOAA** [comment]
Just another update that I completed the full set of regression tests on WCOSS2 with the latest PR branch status. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Why was -DCCPP_SUITES added to the debug tests?

**Comment by jkbk2004** [comment]
> @jkbk2004 Why was -DCCPP_SUITES added to the debug tests?

We noticed compile 012 has random build issue. The problem is clearly noticed on jet. The build issue behaves way better with specifically adding-DCCPP_SUITES options that we need on regression test. With this change, no impact on result.

**Review by DeniseWorthen — APPROVED** [review]
I think it would have been better to include one or more debug tests for HAFS since the issue w/ HYCOM is now fixed w/ this update. I don't think we have any other moving-nest applications so that feature should be tested in the HAFS application.

**Comment by BrianCurtis-NOAA** [comment]
> > @jkbk2004 Why was -DCCPP_SUITES added to the debug tests?
> 
> We noticed compile 012 has random build issue. The problem is clearly noticed on jet. The build issue behaves way better with specifically adding-DCCPP_SUITES options that we need on regression test. With this change, no impact on result.

@DusanJovic-NOAA if i recall correctly, we removed CCPP_SUITES in order to test a build with all suites, get rid of a few extra builds as well. Were there any other reasons we removed the CCPP_SUITES option for the debug builds?

@jkbk2004 If there are build issues with a compile of all suites, then I think at the very least an issue should be made about this so we can return a build with all suites.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA if i recall correctly, we removed CCPP_SUITES in order to test a build with all suites, get rid of a few extra builds as well. Were there any other reasons we removed the CCPP_SUITES option for the debug builds?

Correct. However, currently we have 96 suites. but only about a third is used/tested. There was discussion about removing all unnecessary suites. See: https://github.com/NOAA-EMC/fv3atm/issues/510

**Comment by BinLiu-NOAA** [comment]
> I think it would have been better to include one or more debug tests for HAFS since the issue w/ HYCOM is now fixed w/ this update. I don't think we have any other moving-nest applications so that feature should be tested in the HAFS application.

@DeniseWorthen, yes, we plan to add a debug HAFS RT in a future PR. Thanks!

**Comment by jkbk2004** [comment]
> > > @jkbk2004 Why was -DCCPP_SUITES added to the debug tests?
> > 
> > 
> > We noticed compile 012 has random build issue. The problem is clearly noticed on jet. The build issue behaves way better with specifically adding-DCCPP_SUITES options that we need on regression test. With this change, no impact on result.
> 
> @DusanJovic-NOAA if i recall correctly, we removed CCPP_SUITES in order to test a build with all suites, get rid of a few extra builds as well. Were there any other reasons we removed the CCPP_SUITES option for the debug builds?
> 
> @jkbk2004 If there are build issues with a compile of all suites, then I think at the very least an issue should be made about this so we can return a build with all suites.

Yes, we can create an issue to extend discussion to https://github.com/ufs-community/ufs-weather-model/issues/1450

**Comment by jkbk2004** [comment]
created a new issue https://github.com/ufs-community/ufs-weather-model/issues/1568

**Comment by BrianCurtis-NOAA** [comment]
I've made some changes that only effect WCOSS2 systems. It moves to a newer ecflow version on those systems and forces the use of their ecflow login nodes. This is to resolve an issue where their script ecfrunjob was hanging and causing 100% cpu usage and memory leakage on the regular login nodes.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Ready for upstream merges.

**Comment by jkbk2004** [comment]
@BinLiu-NOAA can you update submodule pointers and revert branches in gitmodules? so we can finish merging.

**Comment by BinLiu-NOAA** [comment]
@jkbk2004 The submodules should be up to date now. Thanks!

**Comment by BinLiu-NOAA** [comment]
@jkbk2004, BTW, once this PR is merged, could you please help to branch out a production/hafs.v1 branch from the develop (which will be used for HAFSv1 code freeze). Feel free to let me know if that is not recommended. If so, we will just create and host this production/hafs.v1 branch inside the hafs-community fork instead. Thanks!

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA @junwang-noaa  I believe the place to create the tag would be here on UWM rather than hafs-community. Jun, is that right?

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA @junwang-noaa I believe the place to create the tag would be here on UWM rather than hafs-community. Jun, is that right?

@DeniseWorthen, that would also be what we would prefer to, branching out inside ufs-weather-model official repo (saying production/hafs.v1) and then later on creating a tag for code delivery and implementation. Thanks!

**Comment by DeniseWorthen** [comment]
That sounds good. I referred to a tag, but you actually want a new branch, production/hafs.v1.

**Comment by BinLiu-NOAA** [comment]
> That sounds good. I referred to a tag, but you actually want a new branch, production/hafs.v1.

@DeniseWorthen, at this moment, for HAFSv1 code freeze, we would like to have a branch (production/hafs.v1). There may or may not be further changes needed before we delivery the HAFSv1 package to NCO later on (in several weeks). And when we deliver the code to NCO, we can create a tag from this production/hafs.v1 branch then. Thanks!

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA production/hafs.v1 branch has been created. Good luck!

**Comment by jkbk2004** [comment]
> @BinLiu-NOAA production/hafs.v1 branch has been created. Good luck!

Thanks @DeniseWorthen for following up with the branch!

**Comment by BinLiu-NOAA** [comment]
Thanks, @jkbk2004 and @DeniseWorthen!

**Pull request merged**
