### PR TITLE
[AQM] [FV3] [WW3] Enable CMAQ scavenging and wet removal in resolved clouds, ESMF 8.4 support for AQM, Update WW3.

### LINKED ISSUE #5: ESMF_IOFMT_BIN deprecated in ESMF 8.4.0.
Issue: ESMF_IOFMT_BIN is deprecated in v8.4.0.

Fix:We have one call to ESMF_IOFMT_BIN in https://github.com/NOAA-EMC/AQM/blob/9fd5978c748de6e753de1f0663d28a2f70a1d480/src/io/aqmio/aqmio.F90#L445 but according to @JianpingHuang-NOAA there is no reading or writing of binary data in AQM and this section of code can be removed.

### LINKED ISSUE #23: Enable CMAQ's simplistic scavenging and wet removal in resolved clouds
CMAQ-provided simplistic scavenging and wet removal schemes for resolved clouds need to be enabled in AQM.

### LINKED ISSUE #1473: Update WW3
## Description

The WW3 develop branch has been updated to include auto-formatting, removal of whitespace and cleanup of some #ifdefs. These changes need to be added to the dev/ufs-weather-model branch and then UWM needs to be updated.

A bug associated with the export of the wave spectrum when coupling with CICE6 is also fixed (see issue https://github.com/NOAA-EMC/WW3/issues/843)

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR enables CMAQ-provided simplistic scavenging and wet removal in resolved clouds

### Issue(s) addressed
Fixes NOAA-EMC/AQM/issues/23
Fixes #1473 
Fixes NOAA-EMC/AQM/issues/5

### Additional PR's closed (merged)
Closes: #1474 (WW3 update)
Closes: #1476 (AQM ESMF 8.4 support))

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel                                                                                                                                               
- [x] hera.gnu                                                                                                                                                 
- [x] orion.intel                                                                                                                                              
- [x] cheyenne.intel                                                                                                                                           
- [x] cheyenne.gnu                                                                                                                                             
- [x] gaea.intel                                                                                                                                               
- [x] jet.intel                                                                                                                                                
- [x] wcoss2.intel                                                                                                                                             
- [x] acorn.intel                                                                                                                                              
- [ ] opnReqTest for newly added/changed feature                                                                                                               
- [x] CI  

## Dependencies
Depends on: NOAA-EMC/AQM/pull/24
Depends on: NOAA-EMC/fv3atm/pull/593
Depends on: NOAA-EMC/WW3/pull/840

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Baselines are changing and it's expected, but only for regional_atmaq
```
baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20221007/INTEL/regional_atmaq
working dir  = /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_RT/rt_11339/regional_atmaq
Checking test 001 regional_atmaq results ....
 Comparing sfcf000.nc ............ALT CHECK......NOT OK
 Comparing sfcf003.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.nc ............ALT CHECK......NOT OK
 Comparing atmf000.nc ............ALT CHECK......NOT OK
 Comparing atmf003.nc ............ALT CHECK......NOT OK
 Comparing atmf006.nc ............ALT CHECK......NOT OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.nc .........OK
 Comparing RESTART/sfc_data.nc .........OK
```

**Comment by BrianCurtis-NOAA** [comment]
Hera.intel for atmaq testing for reproducability with new baseline:
```
baseline dir = /scratch1/NCEPDEV/stmp4/Brian.Curtis/FV3_RT/REGRESSION_TEST_INTEL/regional_atmaq
working dir  = /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_RT/rt_17561/regional_atmaq
Checking test 001 regional_atmaq results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf003.nc .........OK
 Comparing sfcf006.nc .........OK
 Comparing atmf000.nc .........OK
 Comparing atmf003.nc .........OK
 Comparing atmf006.nc .........OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc .........OK
 Comparing RESTART/phy_data.nc .........OK
 Comparing RESTART/sfc_data.nc .........OK
Test 001 regional_atmaq PASS
```

**Comment by zach1221** [comment]
Jenkins-ci run logs attached.
[ufs-weather-model » ort-docker-pipeline » PR-1456 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9840420/ufs-weather-model.ort-docker-pipeline.PR-1456.1.Console.Jenkins.pdf)

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1087776613/20221021101509/ufs-weather-model
[RT] Error: Test control_c384gdas 034 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 134 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 136 failed in run_test failed 
Please make changes and add the following label back: orion-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Ignore the Acorn log for now. Pushed the module updates for acorn based on discussion in code managers channel.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I am noticing some lom/lua issue on cheyenne after maintenance. Not all RT cases but some cases
`"/glade/scratch/jongkim/pr-dev/jongkim/FV3_RT/rt_52814/cpld_debug_p8" has too
many non-modulefiles (648). Please make sure that modulefiles are in their own
directory and not mixed in with non-modulefiles (e.g. source code)`

**Comment by jkbk2004** [comment]
@zach1221 I created issue #1470. I think we don't need to hold the PR. @BrianCurtis-NOAA let's start merging process.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
I've been told to hold on this PR by @JianpingHuang-NOAA. There are some changes that he wants to discuss with @rmontuoro before these changes become official.

**Review by zach1221 — APPROVED** [review]

**Comment by rmontuoro** [comment]
@BrianCurtis-NOAA - I've added a bugfix to the AQM [feature/aqm-rescld-wdep](https://github.com/rmontuoro/AQM/tree/feature/aqm-rescld-wdep) branch linked to this PR that should address @JianpingHuang-NOAA concerns. This update does not affect the baseline and requires additional testing.

Note, however, that the `regional_atmaq` regression test also needs to be updated with the following change to `aqm.rc`:
```
diff --git a/tests/parm/aqm/aqm.rc b/tests/parm/aqm/aqm.rc
index d600cb7c..5c5964a3 100644
--- a/tests/parm/aqm/aqm.rc
+++ b/tests/parm/aqm/aqm.rc
@@ -29,7 +29,7 @@ ctm_pmdiag: true
 #
 #  Input emissions
 #
-emission_sources: anthro bio fire
+emission_sources: anthro fire
 
 #
 #  Anthropogenic
```
This will result in a change in the R/T baseline.

**Comment by JianpingHuang-NOAA** [comment]
but why git log still shows the last commit date on Oct. 13?

commit 0d2703d20b63ea4330e0824fc3e79ff766c88bb0
Merge: 76b058c2 25390861
Author: Raffaele Montuoro ***@***.***>
Date:   Thu Oct 13 16:40:35 2022 +0000

**Comment by rmontuoro** [comment]
@JianpingHuang-NOAA - @BrianCurtis-NOAA will update the AQM submodule in this PR to include the latest commit.

**Comment by BrianCurtis-NOAA** [comment]
@rmontuoro This PR will be next, combined with 1476 (the ESMF 8.4 changes). I discussed with Jianping, who will work on his fixes using this code base, to which we will be a PR later that we can review.

Can you please update your fv3atm branch with the latest develop?

**Comment by JianpingHuang-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***>  I believe that
Raffale has fixed the issue related to the resolved cloud scavenging with
the updated code. I was hoping that I could get the final test done today
but WCOSS2 is not available for development test until tomorrow.  @Raffaele
Montuoro - NOAA Federal ***@***.***>

**Comment by rmontuoro** [comment]
@BrianCurtis-NOAA - I've updated my [feature/enable-aqm-aod](https://github.com/rmontuoro/fv3atm/commits/feature/enable-aqm-aod) branch to the latest [fv3atm:develop](https://github.com/NOAA-EMC/fv3atm/tree/develop) branch.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA - I've updated my [feature/enable-aqm-aod](https://github.com/rmontuoro/fv3atm/commits/feature/enable-aqm-aod) branch to the latest [fv3atm:develop](https://github.com/NOAA-EMC/fv3atm/tree/develop) branch.

@rmontuoro one last request (I think) before testing. Can you merge into this AQM branch (feature/aqm-rescld-wdep) your feature/esmf-binary-io branch?

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA So can we confirm #1476 and #1474 will be combined to this pr?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA So can we confirm #1476 and #1474 will be combined to this pr?

Yes, need to finish merging in things, though.

**Comment by BrianCurtis-NOAA** [comment]
OK @jkbk2004 We are just waiting for @rmontuoro to merge in something to his AQM branch. You will need to create new BL's for regional_atmaq.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 All set for testing.

**Comment by jkbk2004** [comment]
> @jkbk2004 All set for testing.

Sure! I will go ahead.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1087776613/20221102163020/ufs-weather-model
[RT] Error: Test regional_atmaq 147 failed in check_result failed 
[RT] Error: Test regional_atmaq 147 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 lets merge in the AM, any update on Orion?

**Comment by jkbk2004** [comment]
> @jkbk2004 lets merge in the AM, any update on Orion?

@BrianCurtis-NOAA Orion is back now. No problem to merge first thing tomorrow morning.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I am moving to [fv3atm pr 593](https://github.com/NOAA-EMC/fv3atm/pull/593) to ask merge there.

**Comment by jkbk2004** [comment]
> @BrianCurtis-NOAA I am moving to [fv3atm pr 593](https://github.com/NOAA-EMC/fv3atm/pull/593) to ask merge there.

@BrianCurtis-NOAA the fv3atm pr was merged. With the hash update, we can merge in this pr,

**Pull request merged**
