### PR TITLE
update CMEPS

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

Updates CMEPS to latest ESCOMP/main; removes references to 'master', removes unused variables, fixes issue of incorrect units in mediator output files when mesh or grid is in radians and not degrees

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test.  All hera.intel and hera.gnu baselines are B4B at c5d202bb
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

 - Depends on NOAA-EMC/CMEPS/pull/82

Issues Addressed:
 - NOAA-EMC/CMEPS/issues/81
 - NOAA-EMC/CMEPS/issues/83

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by zach1221** [comment]
Hello, @DeniseWorthen and @BrianCurtis-NOAA
Are we ready to start requesting reviews and adding RT labels to this PR?

**Comment by jkbk2004** [comment]
FYI, #1529 was delayed. We can start working on this PR.

**Comment by DeniseWorthen** [comment]
We should have reviews on CMEPS PR before starting.

**Review by BrianCurtis-NOAA — APPROVED** [review]
No UFSWM code to review. Approved for testing.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Is the EPIC github bot going to be used for the pushes and label updates?

**Comment by zach1221** [comment]
Hi, @BrianCurtis-NOAA. I think I can speak to your question. Right now the CI team is working to create a new email address for the NOAA EPIC service account. Then your name/account can be replaced with the service account.

**Comment by BrianCurtis-NOAA** [comment]
> Hi, @BrianCurtis-NOAA. I think I can speak to your question. Right now the CI team is working to create a new email address for the NOAA EPIC service account. Then your name/account can be replaced with the service account.

Awesome, thanks for the update.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1201713042/20230130143025/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1201713042/20230130201511/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by DeniseWorthen** [comment]
The hera.gnu cpld_control_p8 timed out.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1201713042/20230130125710/ufs-weather-model
[RT] Error: Test regional_atmaq_debug 151 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by DeniseWorthen** [comment]
The cheyenne.intel regional_atmaq_debug timed out.

**Comment by jkbk2004** [comment]
Sounds like Orion has system issue today.

**Comment by jkbk2004** [comment]
> The cheyenne.intel regional_atmaq_debug timed out.



> The cheyenne.intel regional_atmaq_debug timed out.

I like to trun off regional_atmaq_debug since the time-out issue continues. @BrianCurtis-NOAA FYI

**Comment by BrianCurtis-NOAA** [comment]
> I like to trun off regional_atmaq_debug since the time-out issue continues. @BrianCurtis-NOAA FYI

Thats OK, the upcoming AQM PR will be disabling it anyways.

**Comment by BrianCurtis-NOAA** [comment]
> I like to trun off regional_atmaq_debug since the time-out issue continues. @BrianCurtis-NOAA FYI

Thats OK, the upcoming AQM PR will be disabling it anyways.

**Comment by BrianCurtis-NOAA** [comment]
the coupler files are having a weird time on Acorn comparing, but using nccmp they are identical, so something weird is going on. I usually am OK if WCOSS2 or Acorn pass, but with Cactus having issues, and Acorn as well its different. Let's not delay this any more. I'll work on it early tomorrow morning in hopes to have one pass before merge.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
