### PR TITLE
Update CDEPS component and remove DATM component

### LINKED ISSUE #839: Remove DATM and related files
## Description
The CDEPS has been integrated into the UFS. The DATM submodule and related files can be removed.

## Solution
The DATM submodule and related tests will be removed. Scripts and configuration files related to DATM tests will also be removed.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related.

### LINKED ISSUE #844: Update CDEPS component to the latest master branch of ESCOMP/CDEPS
## Description
Some updates have been made to the master branch of ESCOMP/CDEPS. The develop branch of NOAA-EMC/CDEPS will be updated soon and the CDEPS component in ufs-weather-model will be updated at the same time.

## Solution
The CDEPS component will point to the latest develop branch of NOAA-EMC/CDEPS after CDEPS PR #37 (https://github.com/NOAA-EMC/CDEPS/pull/37) is merged.

## Related to
CDEPS PR: https://github.com/NOAA-EMC/CDEPS/pull/37

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

The CDEPS component will be updated to include the latest changes from ESCOMP/CDEPS.
The DATM component will be removed and related scripts and configuration files will also be removed.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #839 
- fixes #844 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] CI: Skip due to DATM submodule related changes in CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/CDEPS/pull/37

### CODE REVIEW

**Comment by binli2337** [comment]
@junwang-noaa The code is ready.

**Comment by junwang-noaa** [comment]
I started RT on cray

**Comment by DeniseWorthen** [comment]
There are still some remaining files w/ references to NEMSDatm: cmake/configure_apps.cmake and CMakeLists.txt. 

I also think we need to clean up the NEMS/src/module_EARTH_GRID_component, which has both FRONT_NEMS_DATM and FRONT_CDEPS_DATM. This would have required a NEMS PR also.

**Comment by MinsukJi-NOAA** [comment]
@binli2337 please make these changes to a single file `tests/ci/repo_check.sh`. This removes datm and and adds hycom to CI checking if the submodules are up to date. This change will take effect in the next PR, meaning CI needs to be skipped for this PR.
```
diff --git a/tests/ci/repo_check.sh b/tests/ci/repo_check.sh
index 3981e7b..843e004 100755
--- a/tests/ci/repo_check.sh
+++ b/tests/ci/repo_check.sh
@@ -13,8 +13,8 @@ result() {
 }
 
 # Declare variables
-declare -A base fv3 mom6 cice ww3 stoch gocart nems cmeps datm cdeps cmake
-submodules="fv3 mom6 cice ww3 stoch gocart nems cmeps datm cdeps cmake"
+declare -A base fv3 mom6 cice ww3 stoch gocart nems cmeps cdeps hycom cmake
+submodules="fv3 mom6 cice ww3 stoch gocart nems cmeps cdeps hycom cmake"
 comment=''
 ownerID=$1
 
@@ -55,14 +55,14 @@ cmeps[repo]='https://github.com/NOAA-EMC/CMEPS'
 cmeps[branch]='emc/develop'
 cmeps[dir]='CMEPS-interface/CMEPS'
 
-datm[repo]='https://github.com/NOAA-EMC/NEMSdatm'
-datm[branch]='develop'
-datm[dir]='DATM'
-
 cdeps[repo]='https://github.com/NOAA-EMC/CDEPS'
 cdeps[branch]='develop'
 cdeps[dir]='CDEPS-interface/CDEPS'
 
+hycom[repo]='https://github.com/NOAA-EMC/HYCOM-src'
+hycom[branch]='emc/develop'
+hycom[dir]='HYCOM-interface/HYCOM'
+
 cmake[repo]='https://github.com/NOAA-EMC/CMakeModules'
 cmake[branch]='develop'
 cmake[dir]='CMakeModules'

```

**Comment by binli2337** [comment]
@MinsukJi-NOAA  OK.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/747670691/20211015150017/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_15351
Test compile 007 failed failed 
Please make changes and add the following label back:
hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/747670691/20211015091511/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_48988
Test compile 007 failed failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by binli2337** [comment]
@DeniseWorthen Could you delete /glade/scratch/dtcufsrt/FV3_RT/rt_48988 on cheyenne? Thanks.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/747670691/20211015150015/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_62229
Test hafs_regional_atm 073 failed in run_test failed 
Test control_rrtmgp 040 failed failed 
Test control_rrtmgp 040 failed in run_test failed 
Test cpld_control_c192_p7 005 failed failed 
Test cpld_control_c192_p7 005 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by DeniseWorthen** [comment]
@binli2337 I've removed the run directory. It isn't actually necessary to delete them before re-running the auto-RT.

**Comment by binli2337** [comment]
@DeniseWorthen Thanks!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/747670691/20211015120014/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_69000
Test control_thompson_extdiag_debug 025 failed failed 
Test control_thompson_extdiag_debug 025 failed in run_test failed 
Test control_diag_debug 017 failed failed 
Test control_diag_debug 017 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by DeniseWorthen** [comment]
The control_thompson_extdiag_debug failure on cheyenne was

```
77:mp_thompson_post_run: ttendlim applied 1/4064 times at timestep 1
144:
144:Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
144:
144:Backtrace for this error:
144:#0  0x2b697cd00aff in ???
144:#1  0x10b8723 in ???
144:#2  0x10b78a1 in ???
144:#3  0x10b62fa in ???
```
I'll try copying the run directory and try re-running.

The control_diag_debug  was a time-out.

**Comment by junwang-noaa** [comment]
@binli2337 cray log file is at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_wcoss_cray.log

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
It looks like CDEPS has been updated, so once the submodule is reverted I will approve.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
Nice cleanup work!

**Review by DeniseWorthen — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Pull request merged**
