### PR TITLE
A MERRA2 aerosol interpolation bug was found by RRFS 

### LINKED ISSUE #152: Bug and Proposed Solution in MERRA Aerosol Code
# Description

The RRFS team has encountered several model crashes over the past several days. After running the model in debug mode we think we have traced the source of the bug to [aerinterp.F90](https://github.com/NCAR/ccpp-physics/blob/61b419f132ea24cbe191e34f1bbfcedf2c66e0dd/physics/aerinterp.F90). We have a possible solution for the bug, described below.

**The bug**: Occurs in the subroutine [aerinterpol](https://github.com/NCAR/ccpp-physics/blob/61b419f132ea24cbe191e34f1bbfcedf2c66e0dd/physics/aerinterp.F90#L282C18-L282C29) with an array out of bounds issue [on line 435](https://github.com/NCAR/ccpp-physics/blob/61b419f132ea24cbe191e34f1bbfcedf2c66e0dd/physics/aerinterp.F90#L435) with the second index of the aerpres array. Here is the error:

> forrtl: severe (408): fort: (2): Subscript #2 of the array AERPRES has value 503 which is greater than the upper bound of 72

It appears that this array re-uses the indices of `i1` and `i2`.  These indices used previously in the same routine and were defined by values that can have much larger numbers than 72 (see [lines 392-395](https://github.com/NCAR/ccpp-physics/blob/61b419f132ea24cbe191e34f1bbfcedf2c66e0dd/physics/aerinterp.F90#L392)). Specifically it appears they take on values that are likely the size of the horizontal dimension of the MERRA file (nlons\*nlats, which is 576\*361) and not related to the vertical dimension (which is up to 72). We noticed there is an edge case where `i1` and `i2` may not get re-assigned later in the code, and hence a value larger than 72 may make it to line 435. We think this is causing the problem. Jili Dong found the following issue associated with an if-statement beginning with a loop on [line 428](https://github.com/NCAR/ccpp-physics/blob/61b419f132ea24cbe191e34f1bbfcedf2c66e0dd/physics/aerinterp.F90#L428):

```
             DO  k=1, levsaer-1      !! from sfc to toa
              IF(prsl(j,L) < aerpres(j,k) .and. prsl(j,L)>aerpres(j,k+1)) then
                 i1 = k
                 i2 = min(k+1,levsaer)
                 exit
              ENDIF
             ENDDO
```

Here is how Jili explains it: Note that when searching for the k level where prsl falls within aerpres, the code uses `<` or `>`. If `prsl` equals exactly to `aerpres(i,k)` or `aerpres (j,k+1)`, this if block will be skipped. If the block is skipped then line 435 will use indice values that we set for a different purpose earlier in the code.

The proposed solution from Jili:

Should this "if" statement be changed to the following?

`IF(prsl(j,L) <= aerpres(j,k) .and. prsl(j,L)>aerpres(j,k+1)) then`

Note that Jili has just changed the `<` to `<=`. We have tested this and so far it has fixed three crashes that we've had. So it seems to be working so far.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Run RRFS cycle 202401080000 in debug mode.

## Additional Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Machine: WCOSS2
* Compiler: 
* Suite Definition File or Scheme: RRFS
* Reference other issues or PRs in other repositories that this is related to, and how they are related.

## Output

See above

### PR DESCRIPTION
**Pull request by AnningCheng-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [x] Add list of all failed regression tests in "Regression Tests" section.

### Commit Message

```
-fix array out of bounds issue in physics aerinterpol.F90 (ufs-community/ccpp-physics#152)
```

### Priority
- [X] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [X] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Blocking Dependencies
 
- Depends on ufs-community/ccpp-physics#153
- Depends on NOAA-EMC/fv3atm#750

### Git Issues Fixed By This PR

 - fixes ufs-community/ccpp-physics#152 

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [X] Changes are expected to the following tests:
New baselines are needed for all conus_13km related tests. Namely:
conus13km_2threads  conus13km_debug           conus13km_debug_decomp  conus13km_decomp            conus13km_restart
conus13km_control   conus13km_debug_2threads  conus13km_debug_qr      conus13km_radar_tten_debug  conus13km_restart_mismatch

<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by AnningCheng-NOAA** [comment]
Here is the log file for the regression tests. All test with use_Merra2=T and iaer=1011 passed. A few tests related conus13k failed with use_Merra2=F and iaer=1011 options, which does not make sense,  because iaer asks for reading MERRA2 data, but use_Merra2 turn off the data access. 

[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13874673/RegressionTests_hera.log)

**Comment by AnningCheng-NOAA** [comment]
use_merra2 is overwritten by the regional*.IN and rrfs*IN files in directory fv3_conf.    use_merra2=T was dded in conus13km_control to avoid confusion.  

The issue of the failed tests is related to the bug fixed.  A simple tests is done by adding the following line in /scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model_wk/FV3/ccpp/physics/physics/MP/Morrison_Gettelman/aerinterp.F90
429               if(prsl(j,L) == aerpres(j,k)) write(*,*)"RRFS prsl=aerpres"
and the  "RRFS prsl=aerpres" is shown in /scratch1/NCEPDEV/stmp2/Anning.Cheng/FV3_RT/rt_176886/conus13km_control_intel/out.  
So the bug fixed does modify the baseline results. 

On the whole, The regression tests in Hera are successful and the code is in good shape to be merged into the trunk .  New baselines are needed in all conus_13km related RT tests.

**Comment by jkbk2004** [comment]
@AnningCheng-NOAA can you sync up the branch? we will start working on this pr once the branches are synced up.

**Comment by AnningCheng-NOAA** [comment]
Jong, done

**Comment by jkbk2004** [comment]
@AnningCheng-NOAA I synced up CICE/MOM6/Stochastic-physics hashes. Files changed look ok now. Can you confirm?

**Comment by AnningCheng-NOAA** [comment]
Looks good now.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA This pr is ready. conus 13km cases change.

**Comment by jkbk2004** [comment]
@AnningCheng-NOAA I updated commit messages above. Please, feel free to add or change the commit messages.

**Comment by DeniseWorthen** [comment]
@AnningCheng-NOAA You should update the FV3 hash in your UWM PR branch now that you merged the CI change.

**Comment by AnningCheng-NOAA** [comment]
Denise: Could you give me some instructions on how to update the hash?

**Comment by DeniseWorthen** [comment]
In your UWM branch, you just need to pull in the update to FV3 and then add it. 

You should see (git status) something like this

```
modified:   FV3 (new commits, untracked content)
```

so git add then git commit.

Make sure the FV3 hash in your UWM branch is 1042921

**Comment by AnningCheng-NOAA** [comment]
done. Thank you! Denise

**Comment by jkbk2004** [comment]
All tests are done. We can start merging process.

**Comment by jkbk2004** [comment]
@AnningCheng-NOAA can you update fv3 hash? correct one is https://github.com/NOAA-EMC/fv3atm/commit/095a1d578a2adf4f10b0f0134160e31ac8aa2f11

**Comment by AnningCheng-NOAA** [comment]
done, Jong

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we have one thing to clear on fv3 develop commit. @AlexanderRichert-NOAA committed https://github.com/NOAA-EMC/fv3atm/commit/138aab1b4dcc98143803941301c81e3e933fecdc and @AnningCheng-NOAA synced against that hash. But My question is if it's ok to bring in the change. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA we have one thing to clear on fv3 develop commit. @AlexanderRichert-NOAA committed [NOAA-EMC/fv3atm@138aab1](https://github.com/NOAA-EMC/fv3atm/commit/138aab1b4dcc98143803941301c81e3e933fecdc) and @AnningCheng-NOAA synced against that hash. But My question is if it's ok to bring in the change. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI

Sorry, what exactly is the issue with [NOAA-EMC/fv3atm@138aab1](https://github.com/NOAA-EMC/fv3atm/commit/138aab1b4dcc98143803941301c81e3e933fecdc), what do we need to clear?

**Comment by jkbk2004** [comment]
> > @DusanJovic-NOAA we have one thing to clear on fv3 develop commit. @AlexanderRichert-NOAA committed [NOAA-EMC/fv3atm@138aab1](https://github.com/NOAA-EMC/fv3atm/commit/138aab1b4dcc98143803941301c81e3e933fecdc) and @AnningCheng-NOAA synced against that hash. But My question is if it's ok to bring in the change. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI
> 
> Sorry, what exactly is the issue with [NOAA-EMC/fv3atm@138aab1](https://github.com/NOAA-EMC/fv3atm/commit/138aab1b4dcc98143803941301c81e3e933fecdc), what do we need to clear?

No issue but to make sure we are synching with the hash.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
