### PR TITLE
Moving nest inline post fix

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR fixes the inline post for moving domain (nests). The lat/lon coordinates must be updated in the run phase of the write grid component ever time inline post is executed.

### Issue(s) addressed

https://github.com/ufs-community/ufs-weather-model/issues/1409

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? Yes.
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/fv3atm/pull/581

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can you sync up branch? we can start working on this pr. I assume we only need to update hafs_regional_specified_moving_1nest_atm and turn the case on orion/wcoss2.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA can you sync up branch? we can start working on this pr. I assume we only need to update hafs_regional_specified_moving_1nest_atm and turn the case on orion/wcoss2.

Correct. I just synced my branch with develop. Enabled hafs_regional_specified_moving_1nest_atm test on orion and wcoss2 and updated BL_DATE

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA Should baselines need to be created for anything other than the one test on WCOSS2/Orion?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Should baselines need to be created for anything other than the one test on WCOSS2/Orion?

Yes. on all platforms where that one test is running, the grib files will be updated.

**Comment by BrianCurtis-NOAA** [comment]
> > @DusanJovic-NOAA Should baselines need to be created for anything other than the one test on WCOSS2/Orion?
> 
> Yes. on all platforms where that one test is running, the grib files will be updated.

Thanks. @jkbk2004 All machines but jet, need to create that one baseline before running tests.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA sure! I will start working on hera first.

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA You can merge fv3atm PR and update hash/.gitmodules. I can review the fv3atm PR if you need.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
