### PR TITLE
Add end of run restart functionality to MOM6

### LINKED ISSUE #2285: add writing end of run restart file in MOM6
currently MOM6 nuopc_cap lack the capability to write out end of restart file if restart_n is not a factor of the total run length. This updating will allow the writing of end of run restart file regardless of restart_n setting. Thanks for Daniel Sarmiento's work.

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:

This PR allows the user to create restart files at the end of a run in MOM using the write_restart_at_endofrun configuration option in CMEPS. 

### Commit Message:

* update MOM6 with the capability to write out restart file at the end of run (author: Daniel Sarmiento)
* replace KVML to KV_ML_INVZ2 in MOM_input to eliminate run time warning

  * MOM6 - 
### Priority:
* Normal

### UFSWM:

* Closes #2285 

### Sub component Pull Requests:

* MOM6: PR https://github.com/NOAA-EMC/MOM6/pull/133

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jiandewang** [comment]
[RegressionTests_hera.log.pdf](https://github.com/ufs-community/ufs-weather-model/files/15336945/RegressionTests_hera.log.pdf)
 upload HERA run log file

**Comment by jiandewang** [comment]
@jkbk2004 can you add this PR to UWM commit queue ? It has been fully tested. No BL change needed so you can combine it woth other PR

**Comment by jkbk2004** [comment]
> @jkbk2004 can you add this PR to UWM commit queue ? It has been fully tested. No BL change needed so you can combine it woth other PR

@jiandewang Sure!

**Comment by jiandewang** [comment]
combined with https://github.com/ufs-community/ufs-weather-model/pull/2205

**Pull request closed without merging**
