### PR TITLE
Update develop from gsd/develop 2020/06/30

### PR DESCRIPTION
**Pull request by climbfuji**
Changes in this PR:
- updates to GSL regression tests, add three tests to `rt.conf`, remove unnecessary regression test configuration files for GSL physics
- turn on AVX2 flags for wcoss_dell_p3

This PR needs to be squashed into one commit when merged, using the description of the PR as commit message.

Associated PRs:
https://github.com/NCAR/ccpp-physics/pull/465
https://github.com/NCAR/ccpp-framework/pull/307
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/30
https://github.com/NOAA-EMC/fv3atm/pull/134
https://github.com/ufs-community/ufs-weather-model/pull/156

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Preliminary testing against existing baseline for hera.gnu using rt_gnu.conf: the following tests fail with bit-for-bit mismatches as expected (but run to completion), all others pass:
```
fv3_ccpp_thompson_no_aero
fv3_ccpp_thompson
fv3_ccpp_gsd
```
[rt_hera_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4854123/rt_hera_gnu.log)
[rt_hera_gnu_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/4854126/rt_hera_gnu_fail_test.log)

**Comment by climbfuji** [comment]
Preliminary testing against existing baseline for hera.intel using `rt.conf`: the following tests fail with bit-for-bit mismatches  or missing baselines as expected (but run to completion), all others pass:
```
fv3_ccpp_rap
fv3_ccpp_thompson_no_aero
fv3_ccpp_thompson
fv3_ccpp_hrrr
fv3_ccpp_gsd
fv3_ccpp_gsd_debug
fv3_ccpp_thompson_no_aero_debug
fv3_ccpp_thompson_debug
fv3_ccpp_gsd_diag3d_debug
```
[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4854726/rt_hera_intel.log)
[rt_hera_intel_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/4854727/rt_hera_intel_fail_test.log)

**Comment by climbfuji** [comment]
Regression tests passed for hera.intel, hera.gnu, orion.intel; logs updated in the PR.

**Comment by climbfuji** [comment]
Regression tests passed for wcoss_cray; logs updated in the PR.

**Comment by climbfuji** [comment]
Regression tests passed for wcoss_dell_p3; logs updated in the PR - ready to merge.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA this PR is ready to merge

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
