### PR TITLE
cmake in the FV3 dycore

### LINKED ISSUE #814: Move cmake build of dycore from fv3atm to dycore.
## Description

See FV3atm issue https://github.com/NOAA-EMC/fv3atm/issues/390

### PR DESCRIPTION
**Pull request by aerorahul**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR moves the CMake build of the dycore from [fv3atm](https://github.com/NOAA-EMC/fv3atm) into [GFDL_atmos_cubed_sphere](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere)

Is a change of answers expected from this PR? No
Are any library updates included in this PR (modulefiles etc.)? No

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #814 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1262313153

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/389
- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/141

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/735741103/20210917153018/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_44434
Test hafs_regional_docn 085 failed in run_test failed 
Test hafs_regional_docn_oisst 086 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/735741103/20210917211506/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_47560
Test compile 011 failed failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by MinsukJi-NOAA** [comment]
@aerorahul can you make the following single file change to help debug the current CI issue? This change will not take effect in this PR, but in the next PR:
```
diff --git a/tests/ci/check_status.py b/tests/ci/check_status.py
index c39e6d3..994c5de 100755
--- a/tests/ci/check_status.py
+++ b/tests/ci/check_status.py
@@ -80,6 +80,7 @@ def check_ec2(url, request, myid):
             in_progress.append(x["id"])
 
     while True:
+        print("in_progress: ", in_progress)
         if len(in_progress) == 0:
             break
         time.sleep(20)
@@ -94,6 +95,7 @@ def check_ec2(url, request, myid):
                 break
             if start_status == "completed" and stop_status == "completed":
                 done.append(cid)
+        print("done: ", done)
         if len(done) != 0:
             [workflows.pop(k) for k in done]
             [in_progress.remove(k) for k in done]

```

**Comment by aerorahul** [comment]
> @aerorahul can you make the following single file change to help debug the current CI issue? This change will not take effect in this PR, but in the next PR:
> 
> ```
> diff --git a/tests/ci/check_status.py b/tests/ci/check_status.py
> index c39e6d3..994c5de 100755
> --- a/tests/ci/check_status.py
> +++ b/tests/ci/check_status.py
> @@ -80,6 +80,7 @@ def check_ec2(url, request, myid):
>              in_progress.append(x["id"])
>  
>      while True:
> +        print("in_progress: ", in_progress)
>          if len(in_progress) == 0:
>              break
>          time.sleep(20)
> @@ -94,6 +95,7 @@ def check_ec2(url, request, myid):
>                  break
>              if start_status == "completed" and stop_status == "completed":
>                  done.append(cid)
> +        print("done: ", done)
>          if len(done) != 0:
>              [workflows.pop(k) for k in done]
>              [in_progress.remove(k) for k in done]
> ```

done in abd3f0e

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/735741103/20210922143009/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_2710
Test cpld_restart 002 failed failed 
Test cpld_restart 002 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by DusanJovic-NOAA** [comment]
> _**Automated RT Failure Notification**_
> Machine: hera
> Compiler: intel
> Job: RT
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/735741103/20210922143009/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_2710
> Test cpld_restart 002 failed failed
> Test cpld_restart 002 failed in run_test failed
> Please make changes and add the following label back:
> hera-intel-RT

```
31 min. TEST 002 cpld_restart is running,  status: R jobid 23426475
Slurm unknown status -. Check sacct ...
23426475                  TIMEOUT          rt_2710_002 
23426475.ba+            CANCELLED                batch 
23426475.ex+            COMPLETED               extern 
23426475.0                 FAILED              fv3.exe 
32 min. TEST 002 cpld_restart is TIMEOUT,  status: - jobid 23426475
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/735741103/20210922143017/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_147530
Test cpld_control_wave 014 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by DusanJovic-NOAA** [comment]
> _**Automated RT Failure Notification**_
> Machine: jet
> Compiler: intel
> Job: RT
> Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/735741103/20210922143017/ufs-weather-model
> Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_147530
> Test cpld_control_wave 014 failed in run_test failed
> Please make changes and add the following label back:
> jet-intel-RT

```
$ tail log_jet.intel/run_014_cpld_control_wave.log 
+ __set_x='set -x'
+ set +x
+ [[ slurm = \n\o\n\e ]]
+ [[ false = \f\a\l\s\e ]]
+ submit_and_wait job_card
+ [[ -z job_card ]]
+ '[' -o xtrace ']'
+ set_x='set -x'
+ set +x
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation

```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/735741103/20210922143008/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_46398
Test cpld_ca 005 failed failed 
Test cpld_ca 005 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Review by junwang-noaa — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
