### PR TITLE
Update CICE; add support for restart test when running single RT (was PR 1058); update MOM6 (was PR 1060)

### LINKED ISSUE #1051: CHL_FILE has been setup twice in MOM_input_05
## Description
in MOM_input_05_template the following is duplicated:
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/MOM_input_template_050#L825-L833
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/MOM_input_template_050#L726-L732

solution: remove the 1st section in the above

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

### LINKED ISSUE #1057: Issue with running single restart test
## Description
A single RT can be run using `./rt.sh -n [test name]` command but when same command is used for the restart tests, it does not run the dependency test (the control). This causes failure in the regression test since the restart files are not available. As a workaround, i am creating a custom rt.conf file that includes only subset of the RTs such as cpld_control_c96_p8 and cpld_restart_c96_p8 to run only those tests.

## Following information can be used to see the issue:
1. checkout UFS weather model
`git clone --recursive https://github.com/ufs-community/ufs-weather-model.git`
2. goto test directory `cd ufs-weather-model/tests`
3. try run coupled restart test using `./rt.sh -n cpld_restart_c96_p8`
4. the test will fail due to missing restart files

## Solution
The issue can be solved by extending `rt.sh` script by providing multiple entry to `-n` option like `./rt.sh -n cpld_control_c96_p8,cpld_restart_c96_p8`

## Alternatives
The `rt_single` function in `./rt.sh`  can be modified to check the RT for dependency and include the dependency test to the `rt.conf.single` file.

### LINKED ISSUE #1059: update MOM6 to its main branch 20220217 commit
MOM6 main branch was updated on 20220217 (see detail at  https://github.com/mom-ocean/MOM6/pull/1556#issuecomment-1043449272), need to make corresponding updating in ufs-weather-model
Note these parameters default values have been changed:

- INTERNAL_WAVE_SPEED_BETTER_EST (now .true.)
- EPBL_MLD_BISECTION (now .false.)
- BBL_USE_EOS (now set to the value of USE_EOS)

in MOM_input, we will set INTERNAL_WAVE_SPEED_BETTER_EST = False and EPBL_MLD_BISECTION = True explicitly to retain current answer. BBL_USE_EOS is set explicitly in current MOM_input so the change has no impact in answer

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Updates CICE in UWM with the latest changes from Consortium/main. Updates MOM6 to latest from MOM6/main. Adds ability to run restart test when running single RT.

### Issue(s) addressed

- fixes CICE-EMC issue [#46](https://github.com/NOAA-EMC/CICE/issues/46)
- fixes #1057 
- fixes #1059 
- fixes #1051 

## Testing

All baselines on hera.gnu and hera.intel pass at [66ebe20](https://github.com/DeniseWorthen/ufs-weather-model/commit/66ebe20264c70f251f58d73b7d366bf91a1bd161).

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI [87926ab](https://github.com/ufs-community/ufs-weather-model/pull/1045/commits/87926ab57aba9b0f1b17775ed99a1b00f3da8851)

## Dependencies

- waiting on https://github.com/NOAA-EMC/CICE/pull/45
- waiting on https://github.com/NOAA-EMC/MOM6/pull/85

Co-authors: 
@uturuncoglu
@jiandewang

### CODE REVIEW

**Comment by jiandewang** [comment]
@DeniseWorthen let me know when it's the turn to run rt.sh for this combined PR, I will run wcoss and HERA gnu.

**Comment by jiandewang** [comment]
@DeniseWorthen cray and dell jobs are done, see log files on HERA at /scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For_Denise/PR-1045

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/847875580/20220224101511/ufs-weather-model
[RT] Error: Test rap_restart 047 failed in check_result failed 
[RT] Error: Test rap_restart 047 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_cfsr 106 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_gefs 107 failed in run_test failed 
[RT] Error: Test datm_cdeps_multiple_files_cfsr 110 failed in run_test failed 
[RT] Error: Test compile_008 failed in run_compile failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by DeniseWorthen** [comment]
The DATM tests all completed but failed with the same error:

```
2: FATAL from PE     0: NETCDF ERROR: Permission denied File=MOM6_OUTPUT/ocean.stats.nc
```

The rap_restart test failed in:

```
 Comparing atmf024.nc ............ALT CHECK......NOT OK
``` 

The Compile failure was for the DEBUG rap tests. Looking at the compile log, it appears to have successfully compiled. 

I will rerun the auto-rt after cleaning out the old RT run directories.

**Comment by jiandewang** [comment]
@DeniseWorthen can you add "fixing issue https://github.com/ufs-community/ufs-weather-model/issues/1051" in the PR description ?

**Review by jiandewang — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@binli2337 Could you please also review/approve? Jiande doesn't appear to have the right permissions to approve a uwm PR.

**Review by junwang-noaa — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Pull request merged**
