### PR TITLE
update MOM6 to its main repo. 20240401 commit

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

update MOM6 to its main repo. 20240401 commit (see detail at https://github.com/mom-ocean/MOM6/pull/1621)

### Commit Message:
update MOM6 to its main repo. 20240401 commit (NCAR-candidate-20240319)

```
* UFSWM - 
  * MOM6 - 
```

### Priority:

* Normal

### UFSWM:

* Closes # #2239 
* Closes # #2244 
* Closes # #2192 

### Sub component Pull Requests:
MOM6 PR: https://github.com/NOAA-EMC/MOM6/pull/132

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jiandewang** [comment]
@jkbk2004 can you add this PR to the commit queue ? It is a relative simple one with no BL change so can be combined with other PR

**Comment by FernandoAndrade-NOAA** [comment]
@jiandewang #2173 has been merged in and we'd like to get started with testing for this PR, please go ahead and re-sync your branch, thanks!

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA I saw you merged some of your fixing in this PR, are you plan to process this PR today ?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I saw you merged some of your fixing in this PR, are you plan to process this PR today ?

Yes, we are processing it right now. @zach1221 is running hera to make sure we get any early indication of failures, and i'm running on WCOSS2 to get it in before the prod switch tomorrow morning.

**Comment by jiandewang** [comment]
> > @BrianCurtis-NOAA I saw you merged some of your fixing in this PR, are you plan to process this PR today ?
> 
> Yes, we are processing it right now. @zach1221 is running hera to make sure we get any early indication of failures, and i'm running on WCOSS2 to get it in before the prod switch tomorrow morning.

thanks for the heads up. It is great that you are running this PR now as a new GFDL MOM6 candidate PR will come late this week. In ths way I can do clean test for the upcoming new code.

**Comment by FernandoAndrade-NOAA** [comment]
FYI added small fix to move directory checks a little lower after the mkdir commands in `rt.sh` , otherwise clean runs would result in errors due to those directories not yet being created.

**Comment by zach1221** [comment]
Hera seems to be running through all the tests fine, but it's just taking a while. I'll go ahead and get the rest started.

**Comment by zach1221** [comment]
I had to reset the jenkins runner, so I'm going to give the pipeline another try, but I've got the tests going manually in the background just in case.

**Comment by jkbk2004** [comment]
> I had to reset the jenkins runner, so I'm going to give the pipeline another try, but I've got the tests going manually in the background just in case.

Orion/Hercules went thru unexpected power outage. They are restored but maintenance is scheduled today.

**Comment by zach1221** [comment]
Testing is complete. I have followed up on the mom6 sub-pr to begin the merging process.

**Comment by jiandewang** [comment]
just merged MOM6 (hash # 0730606b), is it the time for me to do the submodule revert ?

**Comment by jiandewang** [comment]
revert MOM6 submodule done

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Why are these two new log files tests/logs/RT-run-Derecho.log and tests/logs/RT-run-Hercules.log committed to the repository?

This PR did not change the baselines yet tests/test_changes.list file indicates that 14 tests had changes, why? Shouldn't this file be empty if there are no baseline changes?

**Comment by DeniseWorthen** [comment]
Did @jiandewang ever commit a test change list? It seems the current list is from #2173. So does that mean that EPIC regenerated baselines those tests, even if that was not required?

**Comment by DusanJovic-NOAA** [comment]
The "bl_date.conf" has not be updated in this PR, which means no baseline changes. In that case "test_changes.list" must be empty, by definition. Conversely, whenever "bl_date.conf" is updated the "test_changes.list" file must not be empty, also by definition.

**Comment by DeniseWorthen** [comment]
Agreed. Does there need to be a logic check in the RT scripts to verify that the two conditions are met? Or do we rely on CMs checking that the two conditions agree?

In this case, I don't see that an updated test_changes.list was ever committed.

**Comment by BrianCurtis-NOAA** [comment]
I did approve it, so I missed those as well. Thanks for catching them. @jkbk2004 can we get those files removed from the repo in Ufuk's PR ?

**Comment by jkbk2004** [comment]
> I did approve it, so I missed those as well. Thanks for catching them. @jkbk2004 can we get those files removed from the repo in Ufuk's PR ?

@BrianCurtis-NOAA sure! @zach1221 @FernandoAndrade-NOAA FYI

**Comment by jiandewang** [comment]
> Did @jiandewang ever commit a test change list? It seems the current list is from #2173. So does that mean that EPIC regenerated baselines those tests, even if that was not required?

I did committed an empty test_changes.list at the time when I generated this PR. Just re-cloned my original PR (created on Apr 15, hash # dc550f05).  test_changes.list is an empty file

**Comment by jiandewang** [comment]
> @BrianCurtis-NOAA I saw you merged some of your fixing in this PR, are you plan to process this PR today ?

I suspect the original empty test_changes.list was overwritten by this step, this is why @DeniseWorthen think it is from https://github.com/ufs-community/ufs-weather-model/pull/2173

**Comment by DeniseWorthen** [comment]
@jiandewang That is probably what happened, because as someone updates their (or someone else's) PR branch as develop moves along, they need to remember to always "git checkout --ours test_changes.list".

**Pull request merged**
