### PR TITLE
release/public-v1: bug fix for threading issue in stochastic physics

### PR DESCRIPTION
**Pull request by climbfuji**
This PR only updates the submodule pointers (and .gitmodules for the code review). For a description, see https://github.com/NOAA-EMC/fv3atm/pull/62.

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Regression tests passed on Cheyenne using both GNU and Intel. Hera is now in maintenance it seems, I cannot log in and check the results of the tests (kicked them off last night).

[rt_cheyenne_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4185948/rt_cheyenne_gnu.log)
[rt_cheyenne_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4185949/rt_cheyenne_intel.log)

**Comment by climbfuji** [comment]
I think we can start merging the fv3atm PR, and wait with the final ufs-weather-model PR until hera comes back and I can get the logs.

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
Ok, this PR didn't have the regression test logs from hera.intel before it was merged. I am attaching them here, all tests pass.

[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4186707/rt_hera_intel.log)
[Compile_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/4186708/Compile_hera.intel.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/4186710/RegressionTests_hera.intel.log)

Please let me know if you want me to make a quick follow-up PR to commit `Compile_hera.intel.log` and `RegressionTests_hera.intel.log`. Thanks

**Comment by junwang-noaa** [comment]
Sorry for missing that. Please make a  follow-up PR. Thanks

Jun

**Comment by climbfuji** [comment]
See here: https://github.com/ufs-community/ufs-weather-model/pull/57

**Comment by junwang-noaa** [comment]
Committed, thanks.

**Pull request merged**
