### PR TITLE
Add unit test capability for weather model

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
*Unit test script and related files implemented under test dir
*A number of TEST_NAME's were tested (see attached figure)
tests

*To make sure it does not interfere with RT, rt.sh was run and finished successfully with ecflow
*To make sure it does not interfere with RT, rt.sh was run and finished successfully with rocoto (except fv3_wrtGauss_nemsio_c768)

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Please delete tests/ecflow_run directory. It should not be in the repository.

**Comment by DusanJovic-NOAA** [comment]
And also tests/log_hera.intel.

**Comment by MinsukJi-NOAA** [comment]
I apologize.  It's done.

> Please delete tests/ecflow_run directory. It should not be in the repository.

**Comment by MinsukJi-NOAA** [comment]
Updated unit test results:
tests2

**Comment by MinsukJi-NOAA** [comment]
Closing this PR as it is merged into develop (#94).

**Pull request closed without merging**
