### PR TITLE
Update FV3 (Thompson MP and RRTMGP), CMEPS, documentation and CI

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

* This PR combines several PR's:
  - #658 from @climbfuji  for FV3 update
  - #665 from @DeniseWorthen for CMEPS update
  - #593 from @MinsukJi-NOAA for documentation update
  - CI update which includes:
    - Add L127 control tests to CI; INLINE_POST now working
    - Add cpld_dbg test to CI
    - Update the ubuntu-hpc container to the latest g2, g2tmpl, upp libraries (see #646)

### Issue(s) addressed

* https://github.com/NCAR/ccpp-physics/issues/680
* https://github.com/NOAA-EMC/CMEPS/issues/50
* #465 #466 #467 

### Initial tests on Hera against BL of 20210616
Failed tests for Intel:
```
cpld_control 001 (only RESTART/ufs.cpld.cpl.r.2016-10-04-00000.nc, expected)
cpld_decomp 003 (only RESTART/ufs.cpld.cpl.r.2016-10-04-00000.nc, expected)
cpld_ca 004 (only RESTART/ufs.cpld.cpl.r.2016-10-04-00000.nc, expected)
cpld_control_c192 005 (only RESTART/ufs.cpld.cpl.r.2016-10-05-00000.nc, expected)
cpld_control_c384 007 (only RESTART/ufs.cpld.cpl.r.2016-10-03-43200.nc, expected)
cpld_bmark_v16 009 (only RESTART/ufs.cpld.cpl.r.2013-04-01-21600.nc, expected)
cpld_bmark_v16_nsst 011 (only RESTART/ufs.cpld.cpl.r.2013-04-01-21600.nc, expected)
cpld_bmark_wave_v16 012 (only RESTART/ufs.cpld.cpl.r.2013-04-01-21600.nc, expected)
cpld_bmark_wave_v16_noahmp 013 (also in Dom's testing)
cpld_control_wave 014 (only RESTART/ufs.cpld.cpl.r.2016-10-04-00000.nc, expected)
cpld_debug 015 (only RESTART/ufs.cpld.cpl.r.2016-10-03-21600.nc, expected)

control_rrtmgp 030 (also in Dom's testing)
control_thompson 036 (also in Dom's testing)
control_thompson_no_aero 037 (also in Dom's testing)

regional_quilt_RRTMGP 045 (also in Dom's testing)

fv3_gsd 046 (also in Dom's testing)
fv3_rrfs_v1alpha 047 (also in Dom's testing)
fv3_HAFS_v0_hwrf_thompson 051 (also in Dom's testing)
fv3_esg_HAFS_v0_hwrf_thompson 052 (also in Dom's testing)

control_rrtmgp_debug 061 (also in Dom's testing)
control_thompson_extdiag_debug 068 (MISSING baseline)
fv3_rrfs_v1alpha_debug 073 (also in Dom's testing)

datm_control_cfsr 076 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_control_gefs 078 (only RESTART/DATM_GEFS.cpl.r.2011-10-02-00000.nc, expected)
datm_bulk_cfsr 079 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_bulk_gefs 080 (only RESTART/DATM_GEFS.cpl.r.2011-10-02-00000.nc, expected)
datm_mx025_cfsr 081 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_mx025_gefs 082 (only RESTART/DATM_GEFS.cpl.r.2011-10-02-00000.nc, expected)
datm_debug_cfsr 083 (only RESTART/DATM_CFSR.cpl.r.2011-10-01-21600.nc, expected)
datm_cdeps_control_cfsr 084 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_control_gefs 086 (only RESTART/DATM_GEFS.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_bulk_cfsr 087 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_bulk_gefs 088 (only RESTART/DATM_GEFS.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_mx025_cfsr 089 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_mx025_gefs 090 (only RESTART/DATM_GEFS.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_multiple_files_cfsr 091 (only RESTART/DATM_CFSR.cpl.r.2011-10-02-00000.nc, expected)
datm_cdeps_debug_cfsr 092 (only RESTART/DATM_CFSR.cpl.r.2011-10-01-21600.nc, expected)
```
Failed tests for Gnu:
```
control_rrtmgp 005 (also in Dom's testing)
fv3_rrfs_v1alpha 011
fv3_rrfs_v1alpha_debug 017
control_thompson_extdiag_debug 022 (MISSING baseline)
control_rrtmgp_debug 023 (also in Dom's testing)

cpld_control 028 (only RESTART/ufs.cpld.cpl.r.2016-10-04-00000.nc, expected)
cpld_debug 029 (only RESTART/ufs.cpld.cpl.r.2016-10-03-21600.nc, expected)
```
### Initial CI tests
All passed: https://github.com/ufs-community/ufs-weather-model/actions/runs/1005274763

### Final tests
- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/runs/3020204994

## Dependencies

* https://github.com/NOAA-EMC/fv3atm/pull/331
* https://github.com/NCAR/ccpp-physics/pull/679
* https://github.com/NOAA-EMC/CMEPS/pull/51

### CODE REVIEW

**Review by DeniseWorthen — APPROVED** [review]
CMEPS changes look good; RT testing is exactly as expected

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/661328414/20210708071513/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_2426
Baseline creation and move successful
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/661328414/20210708081837/ufs-weather-model
Please make changes and add the following label back:
cheyenne-intel-BL

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by climbfuji — COMMENTED** [review]
Just to confirm, you reverted my temporary change in `tests/fv3_conf/control_run.IN` and added the new diag table `diag_table_gfsv16_thompson_extdiag` to the current input data set? If so, thanks for catching that from the notes in my PR!

**Comment by DeniseWorthen** [comment]
@climbfuji The diag_table fix was was done at 2b0ae64

**Review by climbfuji — APPROVED** [review]
Thanks for incorporating all my changes and testing them while I was on leave.

**Pull request merged**
