### PR TITLE
update MOM6 to its main repository 20231218 commit (disable FPEs) + Add stochastic physics pattern update frequency options within SPP and LNDP ('sppint' and 'lndpint') #2077 + Updates to ufs.configure for use in global applications #2074 + Doc Updates #2030

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [ ] Add list of all failed regression tests in "Regression Tests" section.

### Description

- MOM6 main repository was updated on 20231218 to fix its CI test issue. See detail at https://github.com/mom-ocean/MOM6/pull/1617. The change has no impact on UFSWM S2S results.
- updates several templates `ufs.configure.*.IN` used in the global applications so that they can be shared between the ufs-weather-model regression testing framework and the global applications.
- moves the templates by adding `_esmf` for ESMF-managed threading and `_fast` where the wave coupling is in the fast loop (as opposed to `_slow` where it was in the slow loop)
- updates the files under `tests/` to use the appropriately renamed template.
- option for users to apply a stochastic physics pattern update frequency which will keep the pattern fixed for 'sppint' or 'lndpint' seconds for SPP and LNDP stochastic physics, respectively.
- Updated links and test information in `Configurations.rst` to correspond with the new arrangement of RRFS/regional tests
- Modified information on the LND & CDEPS Input files required for land configurations
- Updated `nems.configure` references to `ufs.configure`
- Added crosslinks in various sections so that other UFS documentation projects can take advantage of intersphinx mapping to link to the WM docs. 

### Commit Message
- Update MOM6 to its main repository 20231218 updating (disable FPEs)
- Updates ufs.configure templates for use in global-applications.
- Adds the stochastic pattern interval (sppint) option to SPP and (lndpint) to the land perturbations (LNDP)
- Doc update for LND & CDEPS Input files required for land configurations

UFSWM issue #2079, MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/123 and MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/124
### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [x] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Git Issues and PRs fixed/closed By This PR

- close UFSWM #2079, close MOM6 isseu https://github.com/NOAA-EMC/MOM6/issues/123
- #2074 and part of https://github.com/ufs-community/ufs-weather-model/pull/2010
- #2077 and https://github.com/ufs-community/ufs-weather-model/issues/2071
- #2030 and https://github.com/ufs-community/ufs-weather-model/issues/2029

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [x] MOM6
- [ ] NOAHMP
- [ ] WW3
- [x] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jiandewang** [comment]
@jkbk2004 could you add this to commit queue ? this is a very simple PR without BL change so it can be combined with others.

**Comment by jiandewang** [comment]
full rt.sh successful on HERA and log file being committed to PR branch, it can also be seen at
https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/RegressionTests_hera.log

**Comment by jkbk2004** [comment]
@jiandewang I was checking develop branch. Looks like running ok on hera : /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_79405/cpld_control_p8_mixedmode_intel. Can you double check?

**Comment by DeniseWorthen** [comment]
@jiandewang Looks like you need to update FV3 also.

**Comment by jiandewang** [comment]
@DeniseWorthen this is the steps I just did:
(1) checkout my PR branch, .... submodule update --init --recursive
(2) git remote add upstream https://github.com/ufs-community/ufs-weather-model
(3) git fetch upstream
(4) git merge upstream/develop
(5) git checkout --ours tests/logs/RegressionTests_hera.log
(6) git status, ...... here I saw RegressionTests_hera.log anf fv3 have been changed, but don't understand why fv3 is involved
(7) git add tests/logs/RegressionTests_hera.log fv3
(8) git commit -m 'xxxxxx'
(9) git push origin mybranch

now I saw there is one file in fv3 that has been changed in my PR which shouldn't, see
https://github.com/ufs-community/ufs-weather-model/pull/2080/files

what's wrong in my doing above ?
the requirement to commit run log to users PR branch is something new and I think we need to have someone put a standard step on wiki page as I am sure I am not the only one who is not familiar with this.

**Comment by DeniseWorthen** [comment]
@jiandewang The commit you merged in (spack-stack) included an update to FV3. So it should have shown as updated. You needed to commit that update to your branch.

We used to always have folks commit the logs, then we tried having them attach the logs, but most people continued to commit the log. So I think people are used to committing. Once you commit the log showing you've run the full RT, then you should just keep merging to the top of develop and not worry about your log being different.

**Comment by jiandewang** [comment]
@DeniseWorthen is my step (7) doing the fv3 updating ? I must mess up one step but can't figure out which one.
also when you say "keep merging to the top of develop and not worry about your log being different", do you mean I do "checkout --ours" each time I do the sync ?

**Comment by DeniseWorthen** [comment]
@jiandewang Starting from your d436f2d4 commit (when you added the logs), I merge upstream develop:

I see

```
Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   tests/logs/RegressionTests_hera.log

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   AQM (modified content)
	modified:   FV3 (new commits)
```

You need ``git add FV3`` to update FV3 in your branch. 

For the log, I think I messed you up. You had already committed the log, showing that you passed all the RTs. At that point, you should have kept "their" log....ie, the new one from the develop branch. As you continually keep your develop branch up-to-date, each new set of logs will get updated from the develop branch. 

So once you get your FV3 fixed, you should be able to checkout the log from the develop branch and fix what I told you wrong.

**Comment by jiandewang** [comment]
@DeniseWorthen I just reset my branch back to my original commit log, let me do the sync tomorrow with fresh brain. Thanks for your help but I am still puzzled on fv3 issue.

**Comment by jiandewang** [comment]
@DeniseWorthen I didn't do submodule update after the merging, this is why my branch shows differences with develop on fv3. I think my branch is in the right shape now, can you check that for me ?

**Comment by DeniseWorthen** [comment]
@jiandewang Yes, that looks correct.

**Comment by jkbk2004** [comment]
@jiandewang can you sync up the branch? We may combine in some other no baseline change PRs to this pr: #2074, #2077, #2030. We will double check the status of these PRs and coordinate to combine tomorrow.

**Comment by jiandewang** [comment]
@jkbk2004 just sync-ed my branch, thanks

**Comment by jkbk2004** [comment]
@jiandewang #2030 #2074 #2077 look ready to be combined to this pr. Can you combine in those PRs? Let me know if you want me to combine.

**Comment by jiandewang** [comment]
> @jiandewang #2030 #2074 #2077 look ready to be combined to this pr. Can you combine in those PRs? Let me know if you want me to combine.

@jkbk2004 I prefer you do the combination

**Comment by jkbk2004** [comment]
A quick sanity check ran ok as expected after combining PRs: cpld_control_p8_mixedmode_intel. All looks good. @aerorahul @JeffBeck-NOAA @gspetro-NOAA FYI: feel free to check. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA This PR is ready.

**Comment by BrianCurtis-NOAA** [comment]
Did each of the PR's that were combined into this one have a completed RegressionTests log showing no tests changed?

**Comment by jkbk2004** [comment]
> Did each of the PR's that were combined into this one have a completed RegressionTests log showing no tests changed?

I can run quickly on hera for full test.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA The PR ran ok on hera.

**Comment by jkbk2004** [comment]
Alright! all tests are done. we start merging process.

**Comment by jiandewang** [comment]
just merged MOM6, hash # 60c397b

**Review by sadeghitabas — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
