### PR TITLE
update mesh cap

### LINKED ISSUE #1406: Unstructured meshes and domain decomposition using WW3 mesh cap
This Epic includes work to extend the mesh cap to support unstructured meshes, Domain Decomposition and PLDIB library.

### LINKED ISSUE #1408: Update WW3 meshcap for recent development
## Description
Update WW3 mesh cap for updates. See applicable PR https://github.com/NOAA-EMC/WW3/pull/780 for details

## Related to

Required for #1407 
Required for #1406

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Updates the WW3 mesh cap to add desired features. This PR does not implement those features (e.g. using a nml file instead of the inp file for WW3 or utilizing gridded netCDF output) but could be added if desired.

### Issue(s) addressed

- fixes #1408 
- required by #1406 
- https://github.com/NOAA-EMC/WW3/issues/679
- https://github.com/NOAA-EMC/WW3/issues/674
- https://github.com/NOAA-EMC/WW3/issues/673

## Testing

All baselines on hera.intel and hera.gnu were B4B at 1bed727c. Tests were repeated at 24eb369 and again passed for both hera.intel and hera.gnu.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/WW3/pull/780

### CODE REVIEW

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @MatthewMasarik-NOAA aqm #1405 is ready. We can reschedule this pr after #1405. What do you think?

**Comment by JessicaMeixner-NOAA** [comment]
It's my understanding that the AQM has operational needs to get in ASAP, so that sounds okay to me.

**Comment by jkbk2004** [comment]
> It's my understanding that the AQM has operational needs to get in ASAP, so that sounds okay to me.

Thanks! I will update commit table.

**Comment by jkbk2004** [comment]
We can work on this pr. I will start testing this afternoon.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1025354010/20220916233015/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1025354010/20220916233006/ufs-weather-model
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test control_restart_p8 043 failed in run_test failed 
[RT] Error: Test regional_netcdf_parallel 052 failed in run_test failed 
[RT] Error: Test regional_3km_decomp 054 failed in run_test failed 
[RT] Error: Test rap_control 055 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 061 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 062 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 066 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl 069 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 070 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 071 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_radar_tten_warm 072 failed in run_test failed 
[RT] Error: Test control_csawmgt 074 failed in run_test failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 125 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
slurm issue on jet and gaea: jobs ran ok with resubmission

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen You can work on merging WW3. All RT's passed.

**Comment by JessicaMeixner-NOAA** [comment]
@BrianCurtis-NOAA @DeniseWorthen WW3 submodule has been merged.

**Review by BrianCurtis-NOAA — APPROVED** [review]
Hash's all good.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
