### PR TITLE
lateral boundary fix for regional runs

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR fixes a transient increase in noise caused by incorrect processing of winds along the lateral boundary on the final acoustic time step before fresh boundary information is ingested into the model.   Answers for regional runs will be changed by this PR.  Codes changes are limited to within atmos_cubed_sphere.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<[1038](https://github.com/ufs-community/ufs-weather-model/issues/1038)>
- fixes #<[169](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/169)>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? 

Changes were initially developed on WCOSS (Cray and Dell p3) with Intel builds.  

Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
 - waiting on noaa-emc/fv3atm/pull/<482>https://github.com/NOAA-EMC/fv3atm/pull/482
 - waiting on NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/<173>  https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/173

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@MatthewPyle-NOAA We will start the commit process for this PR today, after the Jet RT is completed for the previous PR. I will run the two WCOSS machines and we'll use the Auto-BL for the remaining. 

Since Orion is on maintenance today, we will not be ready to merge until tomorrow. Will you be available to manage the submodule updates tomorrow?

**Comment by MatthewPyle-NOAA** [comment]
Yes @DeniseWorthen I am ready to deal with it tomorrow.

**Comment by DeniseWorthen** [comment]
@MatthewPyle-NOAA Are there any GOCART related changes in your PR?

**Comment by MatthewPyle-NOAA** [comment]
> @MatthewPyle-NOAA Are there any GOCART related changes in your PR?

Nope - changes are limited to atmos_cubed_sphere.  Think I see why you asked the question looking at the files changed.  Will see if I can figure out where that originated.

**Comment by MatthewPyle-NOAA** [comment]
@DeniseWorthen I updated the hash for GOCART in my branch - thanks for catching that!

**Comment by DeniseWorthen** [comment]
Great. Would you now please update ``BL_DATE`` in rt.sh to 20220224

**Comment by DeniseWorthen** [comment]
I'm going to go ahead and start all the jobs. The Hera jobs are stuck in the Q and still haven't created the baselines.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/852144837/20220224224508/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/852144837/20220225005127/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
There's no obvious explanation for the jet RT failure. It looks like the rt.sh launched but then just stopped before starting to compile anything. I'll re-label.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/852144837/20220225020011/ufs-weather-model
[RT] Error: Test hafs_regional_atm_wav 097 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by MatthewPyle-NOAA** [comment]
Any thoughts/explanations for what happened on jet with the hafs_regional_atm_wav test?  I don't have access to that computer.

**Comment by DeniseWorthen** [comment]
One of the baseline files (atmf006.nc) is corrupted so it is failing comparison. I will generate a new baseline for that test, replace the existing baseline for that test and then run the verify.

**Comment by DeniseWorthen** [comment]
We're ready to commit once the submodules have been merged and updated.

**Review by DeniseWorthen — APPROVED** [review]
Approving in advance of submodule reverts.

**Comment by MatthewPyle-NOAA** [comment]
Thanks for getting across the finish line, @junwang-noaa @DeniseWorthen @BrianCurtis-NOAA !

**Pull request merged**
