### PR TITLE
Update WCOSS2 libraries for spack-stack 1.6.0 (Combined PR #2301)

### LINKED ISSUE #2036: Testing ESMF 8.6.0 in ufs weather model
## Description
ESMF 8.6.0 is released, it needs to be tested in ufs-weather-model.

### LINKED ISSUE #2037: Testing fms 2023.04 in ufs weather model
## Description
FMS 2023.04 was released last week, it contains the diag_table bug fix in FMS 2023.02.01 and fixes related to the gnu compiler in FMS 2023.03. It needs to be tested in ufs weather model.

### LINKED ISSUE #2232: WCOSS2: pio install does not seem to support pnetcdf
## Description

PR #2145 brought in a change where CICE switched to use pnetcdf in PIO instead of hdf5. This worked on all machines except WCOSS2.

This leads us to believe that the PIO install on WCOSS2 was not built with proper pnetcdf support.

Efforts are ongoing trying to determine the specific of any build differences between spack-stack and the hpc-stack on WCOSS2.

### To Reproduce:

Run cpld_control_gfsv17 intel RT with develop branch of UFSWM (From PR #2145 ) on WCOSS2 dev machine

### Needs alongside solving of this issue
1. Remove temporary workaround in default_vars.sh for WCOSS2

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

This PR brings in the necessary changes to match the libraries set for Spack-Stack 1.6.0

- ESMF 8.6.0
- FMS 2024.03
- pnetcdf 1.12.2
- MAPL - 2.40.3 to use ESMF 8.6.0

This PR also merged with #2301 which are miscellaneous changes to rt.sh to address a few issues related to the new verbose setting and cleaned up wording on failed tests.

### Commit Message:

```
* UFSWM
  * Bring in changes for WCOSS2 to match the spack-stack 1.6.0 setup
  * Bring in updated pnetcdf/pio for CICE
  * Small rt.sh changes to improve verbosity and wording on test failures.
```

### Priority:

* High: Needed for spack-stack 1.6.0 and pnetcdf/pio upgrades

### UFSWM:

* Closes #2037
* Closes #2036  
* Closes #2232 
* Closes #2301 

### Sub component Pull Requests:

* None

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.
  * this test is only changing on WCOSS2 not any other platforms (cpld_control_gfsv17_iau_intel).

### Input data Changes:

* None.

### Library Changes/Upgrades:

* Updates already completed.
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Since this is strictly a WCOSS2 PR, we should be able to skip testing on all other platforms. This should make this PR go quick enough we might be able to fit both spack PR's back to back in the same day.

**Comment by BrianCurtis-NOAA** [comment]
OK @jkbk2004 since I have only added rt.sh changes from Dusan, it would be good to have a sanity check on Hera full suite. Could your team run that? I will get WCOSS2 RT suite started now, and probably completed later this evening.

**Comment by zach1221** [comment]
> OK @jkbk2004 since I have only added rt.sh changes from Dusan, it would be good to have a sanity check on Hera full suite. Could your team run that? I will get WCOSS2 RT suite started now, and probably completed later this evening.

I'll run on Hera.

**Comment by BrianCurtis-NOAA** [comment]
Since WCOSS2 does have a test change, we will need a new bl_date, but with the RDHPCS systems we can just create a symlink to the previous develop-date.

**Comment by zach1221** [comment]
[RegressionTest_hera.log](https://github.com/user-attachments/files/15507900/RegressionTest_hera.log)

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 @zach1221 we are ready for merge.

**Comment by zach1221** [comment]
> @jkbk2004 @zach1221 we are ready for merge.

@BrianCurtis-NOAA  Ok, do you not want the ORT logs? They're almost finished. Either way is fine with me.

**Comment by BrianCurtis-NOAA** [comment]
> > @jkbk2004 @zach1221 we are ready for merge.
> 
> @BrianCurtis-NOAA Ok, do you not want the ORT logs? They're almost finished. Either way is fine with me.

Yes, thats fine. I did forget about those.

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Comment by zach1221** [comment]
@DusanJovic-NOAA @jkbk2004 Ok, we're ready for final review at this time.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
