### PR TITLE
Run fewer tests on S4

### LINKED ISSUE #1700: Update S4 RT support
## Description

Several coupled regression tests do not need to be run on S4 as the system is too small to support them.

## Solution

Run the same tests that are run on Jet.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
## Description

Restrict tests to be run on S4 to just those that run on Jet as S4 is limited in size and scope.

### Input data additions/changes
- [x] No changes are expected to input data.

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 

## Subcomponents involved:
- [x] none

## Commit Queue Checklist:

- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers

## Linked PR's and Issues:

Fixes #1700 

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DavidHuber-NOAA we are considering to combine this pr to #1728.

**Comment by jkbk2004** [comment]
Ok! as some tests are already underway on #1728 side, let me directly push the change of rt.conf there.

**Comment by DavidHuber-NOAA** [comment]
@jkbk2004 Great, thank you!  And apologies for the late PR.

**Comment by jkbk2004** [comment]
merged with #1728

**Pull request closed without merging**
