### PR TITLE
new ccpp SDFs added to support RRFS multiphysics ensemble and add tob in ocean output (#2019)

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [ ] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

A decision has been made for RRFS ensemble to apply a multiphysics approach. Five new ccpp SDFs are added in support of the RRFS ensemble development.

### Subcomponent Pull Requests

https://github.com/NOAA-EMC/fv3atm/pull/721

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by JiliDong-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13419026/RegressionTests_hera.log)
attached RT log on Hera

**Comment by JiliDong-NOAA** [comment]
RT log updated
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13507841/RegressionTests_hera.log)

**Comment by zach1221** [comment]
Hi, @JiliDong-NOAA . Can you sync up your branch, please?

**Comment by JiliDong-NOAA** [comment]
> Hi, @JiliDong-NOAA . Can you sync up your branch, please?

Done.

**Comment by JiliDong-NOAA** [comment]
another minor change by adding one variable in ocean output to diag_table (from @jiandewang). No changes on RT as shown in the latest Hera log
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13520240/RegressionTests_hera.log)

**Comment by jkbk2004** [comment]
merged with #1784

**Pull request closed without merging**
