### PR TITLE
fixed issue with decomp-change RT failures with ugwpv1 and made other…

### PR DESCRIPTION
**Pull request by mdtoy**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Updated .gitmodules to point to FV3atm repo and branch that points to ccpp-physics repo and branch containing bug fixes to ugwpv1 (issue #742).  The code is now provides reproducibility under domain decomposition changes.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes issue ufs-community/ufs-weather-model/#742

## Testing

The changes were tested with the standard ccpp "rt.sh" RT script on hera.intel.

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).   N/A

Do PRs in upstream repositories need to be merged first?  No.
If so add the "waiting for other repos" label and list the upstream PRs
- noaa-emc/fv3atm [#386](https://github.com/NOAA-EMC/fv3atm/pull/386)
- ccpp PR[#728](https://github.com/NCAR/ccpp-physics/pull/728)

### CODE REVIEW

**Comment by aerorahul** [comment]
@mdtoy 
Can you please retain the sections in the PR template and fill out the relevant information.
The template is provided so that the code-managers and reviewers can efficiently find the relevant information and check boxes as the review progresses.
Thanks!

**Comment by mdtoy** [comment]
@aerorahul I had left only the sections of the PR template that were relevant to this PR.  How do I bring back the original template?  Thanks.

**Comment by DeniseWorthen** [comment]
Open your PR text for editing (the three horizontal lines in upper right hand corner). Then go to the file .github/pull_request_template.md, use the pencil icon to start editing it; copy and then paste into your opened PR text. Then save the updated PR text.

**Comment by mdtoy** [comment]
Thanks, Denise.

**Comment by climbfuji** [comment]
@mdtoy To clarify, will this PR change the results for the UGWP v1 regression tests?

**Comment by mdtoy** [comment]
Yes, it will.

**Comment by binli2337** [comment]
@mdtoy I can add the deleted sections of the PR template under "Testing".

**Comment by DeniseWorthen** [comment]
Closing; code changes committed in PR #835

**Pull request closed without merging**
