### PR TITLE
Feature reorg ozphys

### PR DESCRIPTION
**Pull request by dustinswales**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: /scratch1/BMC/gmtb/Dustin.Swales/UFS/ozone_phys/ufs-weather-model/tests/logs/RegressionTests_hera.log
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
This PR contains a reorganization of the NRL (2015) ozone physics parameterization. 

## Linked Issues and Pull Requests
None

### Associated UFSWM Issue to close
None

### Subcomponent Pull Requests
[NOAA-EMC/f3atm/pull/662](https://github.com/NOAA-EMC/fv3atm/pull/661)
[ufs-community/ccpp-physics/662](https://github.com/ufs-community/ccpp-physics/pull/75)

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by jkbk2004** [comment]
@dustinswales we can start working on this pr. Can you sync up branch?

**Comment by dustinswales** [comment]
@jkbk2004 Synced up

**Comment by jkbk2004** [comment]
@dustinswales @grantfirl build failures: 
```
fail_compile_atm_dyn32_debug_gnu        fail_compile_atm_gnu
fail_compile_atm_dyn32_intel            fail_compile_s2swa_32bit_intel
fail_compile_atm_dyn32_phy32_debug_gnu  fail_compile_s2swa_32bit_pdlib_debug_intel
fail_compile_atm_dyn64_phy32_debug_gnu  fail_compile_s2swa_32bit_pdlib_intel
fail_compile_atm_dyn64_phy32_gnu
Calling CCPP code generator (ccpp_prebuild.py) for suites --suites=FV3_GFS_v16,FV3_GFS_v16_flake,FV3_GFS_v17_p8,FV3_GFS_v17_p8_rrtmgp,FV3_GFS_v15_thompson_mynn_lam3km,FV3_WoFS_v0,FV3_GFS_v17_p8_mynn,FV3_GFS_v17_p8_ugwpv1 ...
CMake Error at FV3/ccpp/CMakeLists.txt:40 (message):
  An error occured while running ccpp_prebuild.py, check
  /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_111654/compile_atm_dyn32_intel/build_fv3_atm_dyn32_intel/FV3/ccpp/ccpp_prebuild.{out,err}
```

**Comment by DeniseWorthen** [comment]
Checking 
```
/scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_111654/compile_atm_dyn32_intel/build_fv3_atm_dyn32_intel/FV3/ccpp/ccpp_prebuild.err
```

INFO: Checking for existence of schemes in suites ...
CRITICAL: Scheme ozphys_2015 in suite FV3_GFS_v17_p8_ugwpv1 cannot be found
CRITICAL: Scheme phys_tend in suite FV3_GFS_v17_p8_ugwpv1 cannot be found
Traceback (most recent call last):

**Comment by dustinswales** [comment]
@jkbk2004 @DeniseWorthen 
Sorry, I missed changes needed by two SDFs.
Should be working now.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA FYI: issue was fixed and it runs ok.

**Comment by jkbk2004** [comment]
We can start merging process.

**Comment by zach1221** [comment]
@dustinswales fv3atm pr is merged. Please revert the .gitmodule url change, and update the submodule hash. Fv3atm hash: 29a9e833b9ee3ebb02523edc002aed47afe8e876

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
