### PR TITLE
WCOSS2/Acorn update DT_ATMOS to 120 for run completion using "faster" compile, also re-enable 3 hafs tests for WCOSS2.

### LINKED ISSUE #1742: regional_atmaq_faster fails to run on both Acorn and WCOSS2 from PR #1731
## Description

regional_atmaq_faster fails to run on both Acorn and WCOSS2 from PR #1731 

### To Reproduce:

Acorn: /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_192131 
WCOSS2 (Cactus): /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_57197

## Output

```
FATAL from PE   116: compute_qs: saturation vapor pressure table overflow, nbad=      1

Image              PC                Routine            Line        Source             
fv3.exe            0000000003D64156  Unknown               Unknown  Unknown
fv3.exe            0000000002A789BE  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
fv3.exe            0000000002A7817A  mpp_mod_mp_mpp_er         149  mpp_util.inc
fv3.exe            0000000002948DEC  fms_mod_mp_fms_er         505  fms.F90
```

### LINKED ISSUE #1896: Re-enable 3 HAFS tests currently disabled on WCOSS2
## Description

There was a previous PR which fixed an issue where when we used an old python file for baseline comparison it would ERROR out. This has been fixed recently, and those tests need to be enabled on rt.conf

I have tested these three and they compare OK now.

## Solution

remove `wcoss2` from the following lines:
https://github.com/ufs-community/ufs-weather-model/blob/04a65015cb9cf9f3b92f598c27cddc4e8918c43a/tests/rt.conf#L246-L249

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## PR Author Checklist:

- [X] I have linked PR's from all sub-components involved in section below. 
- [X] I am confirming reviews are completed in ALL sub-component PR's.
- [X] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: N/A
- [X] I have added the list of all failed regression tests to "Anticipated changes" section.
- [X] I have filled out all sections of the template.

## Description

The test "regional_atmaq_faster" would not run to completion on WCOSS2/Acorn with an instability from the saturation vapor pressure late in the model run time, but by changing the DT_ATMOS to 120, it is now able to run to completion and compare with its baselines successfully.

This PR also enabled three tests on WCOSS2 for hafs that were disabled previously.

### Associated UFSWM Issue to close

Closes #1742
Closes #1896 

### Subcomponent Pull Requests

N/A

### Blocking Dependencies

None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [X] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

regional_atmaq_faster will be added on both Acorn and WCOSS2
bring back baselines for:
- hafs_regional_docn
- hafs_regional_docs_oisst
- hafs_regional_datm_cdeps
</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I a little confused about how it was failing previously. Did it not run to completion because it is unstable at the longer timestep (the model blew up)? Or, did it run to completion but failed baseline comparison?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I a little confused about how it was failing previously. Did it not run to completion because it is unstable at the longer timestep (the model blew up)? Or, did it run to completion but failed baseline comparison?

It would fail at some point later in the model run time with a saturation vapor pressure issue.

Instability

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA In the issue description you wrote "it is not able to run to completion and compare with its baselines". It never gets to comparing with a baseline if it fails during the run, right?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA In the issue description you wrote "it is not able to run to completion and compare with its baselines". It never gets to comparing with a baseline if it fails during the run, right?

Typo, should say "it is _now_ able to run to completion and compare with its baselines"

**Comment by zach1221** [comment]
Hey @BrianCurtis-NOAA . I think we're ready to start here, if you can resolve conflicts.

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 OK done. We don't need a new bl_date because i'm just adding "new" tests.

**Comment by BrianCurtis-NOAA** [comment]
Baselines copied over, onto comparisons for WCOSS/Acorn.

**Comment by BrianCurtis-NOAA** [comment]
Acorn slow, still 138 tasks. I'll check it later.

**Comment by FernandoAndrade-NOAA** [comment]
On Hera, regional_atmaq_faster_intel failed most comparisons:
```
/scratch1/NCEPDEV/stmp2/Fernando.Andrade-maldonado/FV3_RT/rt_6253/regional_atmaq_faster_intel
Checking test 183 regional_atmaq_faster_intel results ....
 Comparing sfcf000.nc ............ALT CHECK......NOT OK
 Comparing sfcf003.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.nc ............ALT CHECK......NOT OK
 Comparing atmf000.nc ............ALT CHECK......NOT OK
 Comparing atmf003.nc ............ALT CHECK......NOT OK
 Comparing atmf006.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20190801.180000.coupler.res .........OK
 Comparing RESTART/20190801.180000.fv_core.res.nc .........OK
 Comparing RESTART/20190801.180000.fv_core.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20190801.180000.fv_srf_wnd.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20190801.180000.fv_tracer.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20190801.180000.phy_data.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20190801.180000.sfc_data.nc ............ALT CHECK......NOT OK
```

**Comment by jkbk2004** [comment]
I am ok to update current baseline of regional_atmaq_faster_intel with new one across RDHPCS. @BrianCurtis-NOAA what do you think?

**Comment by BrianCurtis-NOAA** [comment]
Yes, the test will have new baselines across the board.

**Comment by zach1221** [comment]
> Jenkins-ci ORTs failed

Platform team is running tests on the jenkins-ci issue, so there may be some failure notifications.

**Comment by jkbk2004** [comment]
All tests are done. We can merge this pr. @FernandoAndrade-NOAA thanks for pushing hera log.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
