### PR TITLE
Use hpc-stack for Actions CI

### LINKED ISSUE #240: Use hpc-stack container for CI test
## Description
User hpc-stack container for actions CI test

## Solution
hpc-stack container with gnu tool chain will be used as a base container within which utest is built and run.

## Alternatives
N/A

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
## Description
Use hpc-stack (with upp support) in docker container used by CI.
Minor change in rt_utils.sh to fail regression test if comp_ncfile.py fails to load required modules.

### Issue(s) addressed
Resolves #240 #277 #296 

## Testing
GitHub Actions tested for working properly: https://github.com/MinsukJi-NOAA/ufs-weather-model/actions/runs/379981603

### CODE REVIEW

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA @MinsukJi-NOAA We originally planned to include this in my PRs (https://github.com/ufs-community/ufs-weather-model/pull/297 & Co). I though this would only be touching ci files, but given the change in `rt_utils.sh` I am reluctant to pull this into my PR. I already completed the regression testing on hera.intel, hera.gnu, orion.intel, and I am close to completing gaea.intel, too. Thoughts?

**Comment by junwang-noaa** [comment]
@climbfuji If possible, I do hope to get this fix in as soon as possible.  Can we help on rerunning RT on hera/orion?

**Comment by MinsukJi-NOAA** [comment]
@climbfuji , Better solution is in the pipe to address #296. I will revert back the rt_utils.sh change for now.

**Comment by climbfuji** [comment]
@junwang-noaa wants to include the change. I'll pull your PR in and rerun on hera.intel, hera.gnu, orion.intel, gaea.intel.

**Comment by climbfuji** [comment]
Please convert your PR into "ready for review", I'll mention it in my PR. Thanks!

**Comment by junwang-noaa** [comment]
Minsuk, I found a bug in compile.sh:

mv ${BUILD_DIR}/ufs_model ${PATHTR}/tests/${BUILD_NAME}.exe
cp ${PATHTR}/modulefiles/${MACHINE_ID}/fv3 ${PATHTR}/tests/modules.${BUILD_NAME}

should be:
mv ${BUILD_DIR}/ufs_model ${PATHTR}/tests/${BUILD_NAME}.exe
if [[ "${MAKE_OPT}" == *"DEBUG=Y"* ]]; then
cp ${PATHTR}/modulefiles/${MACHINE_ID}/fv3_debug ${PATHTR}/tests/modules.${BUILD_NAME}
else
cp ${PATHTR}/modulefiles/${MACHINE_ID}/fv3 ${PATHTR}/tests/modules.${BUILD_NAME}
fi

Would you mind adding it in your PR? Thanks.

**Comment by climbfuji** [comment]
Note. This PR was pulled into https://github.com/ufs-community/ufs-weather-model/pull/297. However, the change in `rt_utils.sh` to fix a problem with silently failing regression tests if `comp_ncfile.py` fails to load required modules (commit 2eaea2e184bdebfd07bcce37194339e1720c5035) had to be reverted manually.

I suggest closing this PR and issues #240 and #277, but keep issue #296 open.

**Comment by MinsukJi-NOAA** [comment]
> Note. This PR was pulled into #297. However, the change in `rt_utils.sh` to fix a problem with silently failing regression tests if `comp_ncfile.py` fails to load required modules (commit [2eaea2e](https://github.com/ufs-community/ufs-weather-model/commit/2eaea2e184bdebfd07bcce37194339e1720c5035)) had to be reverted manually.
> 
> I suggest closing this PR and issues #240 and #277, but keep issue #296 open.

I agree.

**Pull request closed without merging**
