### PR TITLE
fix crash when using clm lake and GFS PBL/sfclay

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [ ] I have run the full RT suite on either Hera/Hercules AND have attached the log to this PR below this line:
  - LOG: 
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [ ] I have filled out all sections of the template.

## Description

This PR is to fix the RRFS ensemble member crash when combining clm lake and GFS PBL/sfclay:

https://github.com/ufs-community/ufs-weather-model/issues/2055

A new flag is created to track new freezing lake ice and let sfc_diff to calculate stability variables over the new icy grids for GFS PBL in the second surface loop, which otherwise will remain as missing values.

### Associated UFSWM Issue to close

https://github.com/ufs-community/ufs-weather-model/issues/2055

### Subcomponent Pull Requests

https://github.com/NOAA-EMC/fv3atm/pull/742
https://github.com/NOAA-EMC/CMEPS/pull/105
https://github.com/ufs-community/ccpp-physics/pull/148
### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by JiliDong-NOAA** [comment]
@SamuelTrahanNOAA I have the PR here to fix the crash when using clm lake and GFS PBL/sfclay in RRFS ensemble. No RT baseline changes expected. Could this PR be combined with your clm lake bug fix PR if time/schedule permits?

**Comment by SamuelTrahanNOAA** [comment]
> I have the PR here to fix the crash when using clm lake and GFS PBL/sfclay in RRFS ensemble. No RT baseline changes expected. Could this PR be combined with your clm lake bug fix PR if time/schedule permits?

Have you run the regression tests to ensure the baselines do not change?

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - Do you approve of combining this with the other CLM Lake pull request (#2044)? This PR is as urgent as that one and fixes the other half of the CLM Lake troubles.

**Comment by JiliDong-NOAA** [comment]
> > I have the PR here to fix the crash when using clm lake and GFS PBL/sfclay in RRFS ensemble. No RT baseline changes expected. Could this PR be combined with your clm lake bug fix PR if time/schedule permits?
> 
> Have you run the regression tests to ensure the baselines do not change?

Yes, I did run full RT on Hera. Just have RT log uploaded.

[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13717259/RegressionTests_hera.log)

**Comment by SamuelTrahanNOAA** [comment]
> Yes, I did run full RT on Hera. Just have RT log uploaded.

Excellent. Once @jkbk2004 says it's okay, I will combine the three PRs into one.

**Comment by JiliDong-NOAA** [comment]
> > Yes, I did run full RT on Hera. Just have RT log uploaded.
> 
> Excellent. Once @jkbk2004 says it's okay, I will combine the three PRs into one.

Thanks @SamuelTrahanNOAA . Now I will change the new flag name as Jun suggested in all submodules.

https://github.com/NOAA-EMC/CMEPS/pull/105#pullrequestreview-1788932597

**Comment by JiliDong-NOAA** [comment]
> > > Yes, I did run full RT on Hera. Just have RT log uploaded.
> > 
> > 
> > Excellent. Once @jkbk2004 says it's okay, I will combine the three PRs into one.
> 
> Thanks @SamuelTrahanNOAA . Now I will change the new flag name as Jun suggested in all submodules.
> 
> [NOAA-EMC/CMEPS#105 (review)](https://github.com/NOAA-EMC/CMEPS/pull/105#pullrequestreview-1788932597)

flag name change done.

**Comment by SamuelTrahanNOAA** [comment]
@JiliDong-NOAA - Please let me know when this PR is in its final form. The combined PR is scheduled for testing tomorrow. If you take too long, I won't be able to combine them in time.

**Comment by SamuelTrahanNOAA** [comment]
The FV3 submodule has doesn't match the hash of https://github.com/NOAA-EMC/fv3atm/pull/742

FV3 submodule hash = 1e814d6e1ed9d17b6461461e081d99693f426ae3
https://github.com/NOAA-EMC/fv3atm/pull/742 PR branch hash = beb11529977c30963fe6f583f214134efdbf7579

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA - Please let me know when this PR is in its final form. The combined PR is scheduled for testing tomorrow. If you take too long, I won't be able to combine them in time.

I think it is ready for combining. I have synced with the latest develop and addressed all reviewers' comments.

**Comment by JiliDong-NOAA** [comment]
> The FV3 submodule has doesn't match the hash of [NOAA-EMC/fv3atm#742](https://github.com/NOAA-EMC/fv3atm/pull/742)
> 
> FV3 submodule hash = 1e814d6e1ed9d17b6461461e081d99693f426ae3 [NOAA-EMC/fv3atm#742](https://github.com/NOAA-EMC/fv3atm/pull/742) PR branch hash = beb11529977c30963fe6f583f214134efdbf7579

Could you double check? I have updated FV3 12 minutes ago.

snapshot

**Comment by SamuelTrahanNOAA** [comment]
I've merged all components into #2044. It should be correct in that branch.

**Comment by JiliDong-NOAA** [comment]
> I've merged all components into #2044. It should be correct in that branch.

Thanks @SamuelTrahanNOAA !

**Pull request closed without merging**
