### PR TITLE
Add extra variables to get ice temperature for marine DA

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch: 
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14065452/RegressionTests_hera.log)
- [x] Add list of all failed regression tests in "Regression Tests" section.

### Description
The marine DA needs ice temperature as model output from CICE.  This PR adds the requested variables and @guillaumevernieres confirmed these are the variables needed:
f_sitempsnic f_sitemptop and f_sitempbot

### Commit Message
Add ice temperature in CICE output

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [x] Normal

### Blocking Dependencies
No

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
cpld_control_gfsv17_iau_intel   The ice history file changes with the added variables.  I have confirmed that creating a new baseline, all tests pass.

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Here's the log comparing with new baseline: 
[RegressionTests_hera_newbaseline.log](https://github.com/ufs-community/ufs-weather-model/files/14065471/RegressionTests_hera_newbaseline.log)

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Why is a new baseline required? We don't compare ice history output in the RTs.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Why is a new baseline required? We don't compare ice history output in the RTs.

@DeniseWorthen there's one ice history file: https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/cpld_control_gfsv17_iau#L49

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Thanks. I forgot that Jun added both ocean and ice history comparisons to that test.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
