### PR TITLE
Update ESMF to 8.2.0bs14; Add a cplocn2atm namelist option to control one-way or two-way atmosphere-ocean coupling (was PR 767)

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- Updates the ESMF version used in ufs-weather-model.

- Add a cplocn2atm namelist option in FV3atm input.nml to control one-way or two-way atmosphere-ocean coupling. Similar to the cplwav2atm namelist option, the cplocn2atm namelist option turns on/off the ocean model component feedback (e.g., SST) to the atmosphere model component. This is useful to control the one-way or two-way atmosphere-ocean coupling, as well as to configure different combinations for the atmosphere-ocean-wave coupling in HAFS and/or other applications.

### Issue(s) addressed

- #712 
- FV3 https://github.com/NOAA-EMC/fv3atm/issues/372
- Makes wall clock default 30mins except on Gaea where it is 60mins; removes wall clock setting in individual tests
- Updates stack on Cheyenne to hpc/1.2.0

## Testing

No baseline changes were found when tested on hera.intel.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1191805292

## Dependencies

- waiting on noaa-emc/fv3atm/pull/376

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/721418715/20210830220012/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_2616
Test control_atm_aerosols 109 failed failed 
Test control_atm_aerosols 109 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by DeniseWorthen** [comment]
I ran both hera intel and gnu baselines with this branch just before the PR778 was merged. Now the control_atm_aerosols test is failing with

```
  7: forrtl: severe (174): SIGSEGV, segmentation fault occurred
  7: Image              PC                Routine            Line        Source
  7: fv3.exe            00000000043FB4EC  Unknown               Unknown  Unknown
  7: libpthread-2.17.s  00002ABF1D6CE630  Unknown               Unknown  Unknown
  7: fv3.exe            00000000044CCFA3  Unknown               Unknown  Unknown
  7: fv3.exe            0000000000B0CFC6  esmf_vmmod_mp_esm        5351  ESMF_VM.F90
  7: fv3.exe            0000000001F83161  mapl_commsmod_mp_         285  MAPL_Comms.F90
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/721418715/20210830220005/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_44615
Test control_c192 025 failed failed 
Test control_c192 025 failed in run_test failed 
Test control_lseaspray 033 failed failed 
Test control_lseaspray 033 failed in run_test failed 
Test regional_control 043 failed failed 
Test regional_control 043 failed in run_test failed 
Test regional_quilt_netcdf_parallel 048 failed failed 
Test regional_quilt_netcdf_parallel 048 failed in run_test failed 
Test regional_quilt_2threads 046 failed failed 
Test regional_quilt_2threads 046 failed in run_test failed 
Test cpld_restart_bmark_v16 011 failed failed 
Test cpld_restart_bmark_v16 011 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/721418715/20210830220011/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_278219
Test control_csawmg_debug 066 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by junwang-noaa** [comment]
I think the changes in PR#778 is independent to the ESMF lib update. I am curious what happened.

**Comment by DeniseWorthen** [comment]
1. Gaea jobs were all timed-outs
2. Jet job ran to completion, but the rt log file was not created (``sbatch: error: Batch job submission failed: Socket timed out on send/recv operation`` at end of ``run_066_control_csawmg_debug.log``)
3. Dell had compile failures:
```
FAILED TESTS:
Test compile 003 failed failed
Test compile 009 failed failed
Test compile 010 failed failed
Test compile 011 failed failed
Test compile 012 failed failed
Test compile 002 failed failed
Test compile 016 failed failed
Test compile 018 failed failed
```
These all appear to be the same issue:

``/gpfs/dell2/ptmp/Denise.Worthen/ufs-weather-model/build.sh: line 14: ESMFMKFILE: Please set ESMFMKFILE environment variable``

**Comment by DeniseWorthen** [comment]
It looks like we're missing the ``esmf/8_2_0_beta_snapshot_14-debug`` build on wcoss-dell. 

I can see the ``esmf/8_2_0_beta_snapshot_14`` build if I manually load the modules so I'm not sure why the compile jobs failed.

**Comment by DeniseWorthen** [comment]
@junwang-noaa I went back and checked and when I ran on Friday I only ran the coupled, DATM, CDEPS tests so the control_atm_aerosols  failure with bs14 is probably a real failure but I don't know what in bs14 is causing the failure.

**Comment by junwang-noaa** [comment]
@rmontuoro We are bringing ESMF820bs14 to UFS, but the control_atm_aerosols failed, do you know if there is any change required for atm-aerosol coupling? @rsdunlapiv @theurich FYI,

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen can you please make these changes (2 files)? They are for CI library updates to ESMF820bs14.
```
diff --git a/tests/ci/Dockerfile b/tests/ci/Dockerfile
index f95e5d1..34feec3 100644
--- a/tests/ci/Dockerfile
+++ b/tests/ci/Dockerfile
@@ -1,4 +1,4 @@
-From noaaemc/ubuntu-hpc:v1.5b
+From noaaemc/ubuntu-hpc:v1.6b
 
 ENV HOME=/home/builder
 COPY --chown=builder:builder . $HOME/ufs-weather-model

diff --git a/tests/ci/ci.sh b/tests/ci/ci.sh
index 57a96c1..7702ed3 100755
--- a/tests/ci/ci.sh
+++ b/tests/ci/ci.sh
@@ -81,7 +81,7 @@ elif [ $RUN == "true" ]; then
                 -e "RT_MACHINE=linux.gnu" -e "RT_COMPILER=gnu" \
                 -w "/home/builder/ufs-weather-model/tests" \
                 -v DataVolume:/home/builder/data/NEMSfv3gfs/input-data-20210528 \
-                --shm-size=512m --name my-container noaaemc/ubuntu-hpc:v1.5b \
+                --shm-size=512m --name my-container noaaemc/ubuntu-hpc:v1.6b \
                 /bin/bash -c "./utest -n ${TEST_NAME} -c ${TEST_CASE} -x"
 
   cd $GITHUB_WORKSPACE

```

**Review by junwang-noaa — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/721418715/20210903173006/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_26156
Test fv3_rap 052 failed failed 
Test fv3_rap 052 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by DeniseWorthen** [comment]
All RTs complete; ready for merge on Tuesday.

**Comment by junwang-noaa** [comment]
Denise, thanks for getting all the RT done!

**Review by climbfuji — APPROVED** [review]
Thank you for the much needed cleanup of the WLCLK settings!

**Pull request merged**
