### PR TITLE
Minor bugfixes for CCPP v6

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR only contains minor bugfixes for CCPP-framework and CCPP-physics and should not affect UFS RTs at all (will test to confirm)

### Issue(s) addressed

https://github.com/NCAR/ccpp-physics/issues/927
https://github.com/NCAR/ccpp-framework/issues/450

## Testing

All tests in rt.conf pass with existing baselines.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/924
https://github.com/NCAR/ccpp-framework/pull/451
https://github.com/NOAA-EMC/fv3atm/pull/541

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@grantfirl We will work on your PR today, are your branches up to date?

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
> @grantfirl We will work on your PR today, are your branches up to date?

Yes, this is ready to work on.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/944854842/20220525011648/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA It looks to me that  the tests are still running on jet . Not sure why we got this message.

**Comment by jkbk2004** [comment]
> @BrianCurtis-NOAA It looks to me that  the tests are still running on jet . Not sure why we got this message.

@junwang-noaa maybe a python try/except hiccup with slurm pending warning... But yes jobs still running

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/944854842/20220525011511/ufs-weather-model
[RT] Error: Test control_c384gdas_wav 125 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/944854842/20220525011507/ufs-weather-model
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 095 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA It looks to me that  the tests are still running on jet . Not sure why we got this message.

@junwang-noaa Jet is notoriously error prone it seems to me. If jobs are still running on Jet but the error message appeared on here, that means Jet killed the AutoRT but ecflow is still running things. There will be no logs automatically pushed and i'm not confident all jobs will run.

**Comment by junwang-noaa** [comment]
@grantfirl The cray/dell log files are under /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog

**Comment by DeniseWorthen** [comment]
gaea.intel failure is

```
 65: fv3.exe: lib/darshan-common.c:262: darshan_track_common_val_counters: Assertion `found == counter' failed.
 65: forrtl: error (76): Abort trap signal
```

probably just needs to be re-run.

**Comment by jkbk2004** [comment]
> > @BrianCurtis-NOAA It looks to me that  the tests are still running on jet . Not sure why we got this message.
> 
> @junwang-noaa Jet is notoriously error prone it seems to me. If jobs are still running on Jet but the error message appeared on here, that means Jet killed the AutoRT but ecflow is still running things. There will be no logs automatically pushed and i'm not confident all jobs will run.

@BrianCurtis-NOAA yeah, slurm pending issues dumped fail_tests: cpld_debug_p8 006, hafs_regional_atm_thompson_gfdlsf 088, hafs_regional_datm_cdeps 094. I will see if I can run these three cases manually.

**Comment by grantfirl** [comment]
The control_c384gdas_wav failed for me the first time (time-out) on hera.intel too. It passed while running separately.

**Comment by grantfirl** [comment]
> /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog

Thanks. They've been added/pushed.

**Comment by junwang-noaa** [comment]
The control_c384gdas_wav was reran and it finished successfully on hera_intel.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/944854842/20220525114517/ufs-weather-model
[RT] Error: Test control_c384 018 failed in run_test failed 
[RT] Error: Test control_c384gdas 019 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 088 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 091 failed in run_test failed 
[RT] Error: Test hafs_regional_datm_cdeps 094 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
> _**Automated RT Failure Notification**_ Machine: jet Compiler: intel Job: RT [RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/944854842/20220525114517/ufs-weather-model [RT] Error: Test control_c384 018 failed in run_test failed [RT] Error: Test control_c384gdas 019 failed in run_test failed [RT] Error: Test hafs_regional_atm_thompson_gfdlsf 088 failed in run_test failed [RT] Error: Test hafs_regional_atm_ocn_wav 091 failed in run_test failed [RT] Error: Test hafs_regional_datm_cdeps 094 failed in run_test failed Please make changes and add the following label back: jet-intel-RT

@BrianCurtis-NOAA @junwang-noaa if I run manually on jet, hafs_regional_atm_thompson_gfdlsf ran ok but all others seem to have slurm unknown status and pending issues.

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@grantfirl RT passed, please merge CCPP PRs. Thanks

**Comment by grantfirl** [comment]
@junwang-noaa The FV3 submodule pointer has been updated and .gitmodules reverted.

**Pull request merged**
