### PR TITLE
Update utest and ci

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- Update utest script: Handle global, regional, and coupled tests
- Update CI workflow: When builds are complete, instead of saving the entire docker image (~730 MB) as an artifact, only save the executable (~77 MB) to save time (~7 min) and improve robustness. This will be important as more tests are added to the CI, and/or larger-size images (e.g. intel oneAPI) are used
- Add regional thread and decomposition tests to CI
- Fix to run threads on its own core in ec2 for thread tests
- Use a slightly different ubuntu-hpc image to match the uid and gid within ec2 instances

### Issue(s) addressed
#543 
Includes the code changes in #560, and thus replaces #560.

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

None

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/654368039/20210602171513/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_202775
Test cpld_debugfrac 028 failed in run_test failed 
Test cpld_debug 027 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by MinsukJi-NOAA** [comment]
Coupled model restart utest is passing with Intel and GNU, so it is added to the CI.

**Comment by junwang-noaa** [comment]
so the coupled model test is working with gnu compiler?

**Comment by MinsukJi-NOAA** [comment]
> so the coupled model test is working with gnu compiler?

Yes, it is working with gnu in a docker container. I tested it on Hera yesterday, and it was working as well.

**Comment by BrianCurtis-NOAA** [comment]
AutoRT: orion jobs sitting in pending, jet started but lots pending still. Will need to add labels on once Hera is back online.

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/654368039/20210602191514/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_39017
Test control_c384gdas 036 failed in check_result failed 
Test control_c384gdas 036 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by MinsukJi-NOAA** [comment]
Runtime error occurs when running control (with L127) test in a docker. However, the exact same configuration runs fine with GNU on Hera.
https://github.com/ufs-community/ufs-weather-model/runs/2732472388?check_suite_focus=true
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
free(): invalid next size (normal)
Program received signal SIGABRT: Process abort signal.
#3  0x561f5bacd317 in __mersenne_twister_MOD_random_number_t
	at /home/builder/ufs-weather-model/stochastic_physics/mersenne_twister.F:362
#4  0x561f5bacde03 in __mersenne_twister_MOD_random_number_s
	at /home/builder/ufs-weather-model/stochastic_physics/mersenne_twister.F:325
```

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/654368039/20210602141510/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_227346
Test cpld_controlfrac 003 failed in check_result failed 
Test cpld_controlfrac 003 failed in run_test failed 
Test cpld_restart_bmarkfrac_v16 022 failed in check_result failed 
Test cpld_restart_bmarkfrac_v16 022 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
> Machine: jet
> Compiler: intel
> Job: RT
> Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/654368039/20210602191514/ufs-weather-model
> Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_39017
> Test control_c384gdas 036 failed in check_result failed
> Test control_c384gdas 036 failed in run_test failed
> Please make changes and add the following label back:
> jet-intel-RT

that test failed on this file:  Comparing GFSFLX.GrbF00 .........NOT OK

**Comment by MinsukJi-NOAA** [comment]
> Runtime error occurs when running control (with L127) test in a docker. However, the exact same configuration runs fine with GNU on Hera.
> https://github.com/ufs-community/ufs-weather-model/runs/2732472388?check_suite_focus=true

With QUILTING=.false., control is able to run.

**Comment by junwang-noaa** [comment]
Can we add:
if  [ $UNIT_TEST == false ] then
export WRITE_DOPOST=true
fi
in tests/tests/control? Maybe also set UNIT_TEST=false in default_vars.sh

**Comment by MinsukJi-NOAA** [comment]
* On Orion, the following 4 tests were re-ran to pass:
cpld_controlfrac, cpld_restartfrac, cpld_bmarkfrac_v16, cpld_restart_bmarkfrac_v16
* On Jet, the following 1 test was re-ran to pass:
control_c384gdas

**Comment by MinsukJi-NOAA** [comment]
All RT's passed. I can spend a couple of hours to include control in CI. Or we can exclude control at this time and include via a future commit.

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]
Do we know why the control L127 + post tests don't work in Docker?

**Comment by MinsukJi-NOAA** [comment]
> Do we know why the control L127 + post tests don't work in Docker?

@junwang-noaa suggested WRITE_DOPOST=false, which made control L127 to work in Docker. I do not know the underlying reason.

**Comment by junwang-noaa** [comment]
POST needs more memory, but currently we are only using one EC2 node with
48 PEs for the test. We need to request more memory to run inline post.

**Pull request merged**
