### PR TITLE
Introduce namelist flag xr_cnvcld to control if suspended grid-mean convective cloud condensate should be included in cloud fraction and optical depth calculation in radiation in the GFS suite. 

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:

This PR introduces namelist flag xr_cnvcld to control if suspended grid-mean convective cloud condensate should be included in cloud fraction and optical depth calculation in radiation in the GFS suite.

The default setting is .true. so all regression tests passes (on Hera). We recommend using .false. for C96 resolution.

### Commit Message:

```
* UFSWM - 
  * FV3 - 
    * ccpp-physics - 
```

### Priority:

* Normal.
Needed for the SFS project. 

### UFSWM:

https://github.com/ufs-community/ufs-weather-model/issues/2184

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/799
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/184
 
### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by zach1221** [comment]
Hi, @lisa-bengtsson could you add a commit message for this PR, summarizing your code changes?

**Comment by jkbk2004** [comment]
@lisa-bengtsson can you sync up the branch? We may schedule to commit this pr. possibly tomorrow.

**Comment by lisa-bengtsson** [comment]
@zach1221 @jkbk2004 I have synced up the branch and added a commit message explaining the update.

**Comment by jkbk2004** [comment]
merged with #2202

**Pull request closed without merging**
