### PR TITLE
Add optional 'time_unlimited' logical flag to model_configure

### LINKED ISSUE #1521: Add unlimited to time dimension in gaussian_grid netcdf output
## Description
gaussian_grid netcdf output files include "time" as a dimension but it is not defined as an unlimited dimension. @DeniseWorthen reports that this is not true when tiled netcdf output is used. It appears that this option was disabled for parallel netcdf output due to performance issues on Hera. Lack of a record dimension causes a number of follow on issues, particularly with the use of netcdf operators. 

## Solution
Allow for users to enable unlimited definition for netcdf output.  

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Add new model_configure parameter (logical flag) 'time_unlimited'. This flag is set to .false.by default. When the user sets it to .true. explicitly in the model_configure file the time dimension in fv3atm history files will be a record dimension (ie. unlimited)

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1521

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? Yes.
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/fv3atm/pull/612

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Currently when we write tiled output, the netcdf time dimension is unlimited. By setting time_unlimited to false by default, will this mean tiled output does not have an unlimited time dimension?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Currently when we write tiled output, the netcdf time dimension is unlimited. By setting time_unlimited to false by default, will this mean tiled output does not have an unlimited time dimension?

Tiled history files (each tile in a separate file) are created using esmf io, and are not affected by the option.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can I check if you are working today? If so, we may combine this pr with #1538.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA can I check if you are working today? If so, we may combine this pr with #1538.

Yes, I'm working today. Let me first sync my branches with develop

**Comment by DusanJovic-NOAA** [comment]
> > @DusanJovic-NOAA can I check if you are working today? If so, we may combine this pr with #1538.
> 
> Yes, I'm working today. Let me first sync my branches with develop

Should I merge #1538 into this PR?

**Comment by jkbk2004** [comment]
Yes, go ahead to merge in #1538.  Its PR template update. All no baseline change. It's good to combine.

**Comment by DusanJovic-NOAA** [comment]
Merged #1538

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1163629247/20221227181518/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1163629247/20221227203006/ufs-weather-model
[RT] Error: Test control_c384 028 failed in run_test failed 
[RT] Error: Test control_c384gdas 029 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA On gaea, can you take a look at /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_16491_troubleshoot? I think this is similar issue as cheyenne for control_c384 and control_c384gdas.

**Comment by jkbk2004** [comment]
> @DusanJovic-NOAA On gaea, can you take a look at /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_16491_troubleshoot? I think this is similar issue as cheyenne for control_c384 and control_c384gdas.

I am not sure if we need @uturuncoglu 's opinion. We thought memory issue. But just in case we need think from esmf's point of view. @uturuncoglu We created https://github.com/ufs-community/ufs-weather-model/issues/1549. we started seeing this issue from cheyenne but it seems to be happening on gaea as well.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA On gaea, can you take a look at /lustre/f2/scratch/Jong.Kim/FV3_RT/rt_16491_troubleshoot? I think this is similar issue as cheyenne for control_c384 and control_c384gdas.

Let me try to run the tests with fewer tasks per node on gaea for these two tests.

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Gaea using TPN=18 for control_c384 and control_c384gdas.

**Comment by jkbk2004** [comment]
> Regression test passed on Gaea using TPN=18 for control_c384 and control_c384gdas.

cool! Let me finish up the RT log on gaea. I will try on cheyenne as well.

**Comment by DeniseWorthen** [comment]
I'm confused why the changes in this PR have any impact on the resource needs. The unlimited option is off by default, correct? So why are we seeing a resource impact?

**Comment by DusanJovic-NOAA** [comment]
> I'm confused why the changes in this PR have any impact on the resource needs. The unlimited option is off by default, correct? So why are we seeing a resource impact?

The changes in this PR are not the reason for the failures but probably the switching to esmf managed threading, few commits earlier. For some reason these two tests occasionally fail on gaea and/or cheyenne most probably due to memory limits.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Thanks, that is also what I suspect. But I didn't think the esmf-managed threading changed any of the resource allocations, so that jobs running w/ 1 thread before were still running w/ one thread after etc.

**Comment by jkbk2004** [comment]
I am turning on control_c384 on cheyenne. It runs ok with TPN =18.

**Comment by DusanJovic-NOAA** [comment]
Is see in PR #1523 in this commit (https://github.com/ufs-community/ufs-weather-model/pull/1523/commits/a941652398b9e86befaf4b4338cd5a64baecc67f) I changed the number of threads for c384 tests to 1 after @jkbk2004 reported failure on gaea (https://github.com/ufs-community/ufs-weather-model/pull/1523#issuecomment-1363587468). That seemed to solve the issue then. But in this PR these two tests failed again.

**Comment by DeniseWorthen** [comment]
This feels like playing whack-a-mole.

**Comment by jkbk2004** [comment]
I will watch. odd seems to be reduced. BTW, I think the git yaml script to pick up git.run.id might be a bit outdated. I will test on my side.

**Comment by jkbk2004** [comment]
So, all tests set. we can start merging process.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA fv3 pr was merged.

**Review by DeniseWorthen — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
