### PR TITLE
WM Documentation Updates

### LINKED ISSUE #2029: Update WM Documentation
## Description
The WM documentation needs updates to reflect changes such as the reorganization of RRFS/regional RTs, the name change from `nems.configure` to `ufs.configure`, and the use of the WM in the Land DA System. 

## Solution
Update the documentation to correspond to these changes. 

## Alternatives
N/A

## Related to
N/A

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
## PR Author Checklist:
- [X] I have linked PR's from all sub-components involved in section below. N/A
- [X] I am confirming reviews are completed in ALL sub-component PR's.
- [ ] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: N/A --> text-only changes to documentation 
  - Documentation for my fork builds here: https://gsp-wm.readthedocs.io/en/text-landda-v1.2/
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section. N/A
- [X] I have filled out all sections of the template.

## Description
- Updated links and test information in `Configurations.rst` to correspond with the new arrangement of RRFS/regional tests
- Modified information on the LND & CDEPS Input files required for land configurations
- Updated `nems.configure` references to `ufs.configure`
- Added crosslinks in various sections so that other UFS documentation projects can take advantage of intersphinx mapping to link to the WM docs. 

## Commit Message
```
- PI10 Documentation Updates (Closes #2029)
```

## Linked Issues and Pull Requests
Close #2029 

### Subcomponent Pull Requests
N/A

### Blocking Dependencies
N/A

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [X] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

### New Libraries
- [X] Not Needed

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Could you please edit the PR title to something more descriptive?

**Comment by gspetro-NOAA** [comment]
@DeniseWorthen Apologies! I have updated to reflect that these are documentation updates.

**Comment by DeniseWorthen** [comment]
@gspetro-NOAA We're adding a Commit Message requirement to the PRs. Please add one in the space provided.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@gspetro-NOAA can you sync up the branch? We will consider to combine with some other no baseline change PRs.

**Comment by jkbk2004** [comment]
merged with #2080

**Pull request closed without merging**
