### PR TITLE
MYNNsfc uniform real kind

### PR DESCRIPTION
**Pull request by dustinswales**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
This change modifies REAL-type variables and specific REAL-type constants so that they uniformly utilize the kind=kind_phys definition for REAL types found in the CCPP-physics machine.F file. This reduces casting and recasting of REALs between types of differing precision. Additional changes include changing occurances of ALOG to LOG to support more than single precision REALs as needed when kind=kind_phys is defined in that manner.
Opened on behalf of @timsliwinski-noaa.

There are no changes to the UFS regression test baselines on Cheyenne using Intel.

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we like to start working on this pr alone if @binli2337 and @dustinswales are off for holidays.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA we like to start working on this pr alone if @binli2337 and @dustinswales are off for holidays.

Which PR? This one?

**Comment by jkbk2004** [comment]
> > @DusanJovic-NOAA we like to start working on this pr alone if @binli2337 and @dustinswales are off for holidays.
> 
> Which PR? This one?

Bin's PR is #1541. Dustins' is #1522. #1541 is simple. I think you can force to push the #1541 change into this pr. But feel free.

**Comment by jkbk2004** [comment]
OOPS! I am in wrong pr conversation

**Comment by jkbk2004** [comment]
@dustinswales if you are working this week, we can start working on this pr from today.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1149990905/20230105194512/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by ChunxiZhang-NOAA** [comment]
@dustinswales @jkbk2004 I noticed that this PR points to the new ccpp-framework hash, which is in climbfuji/ccpp-framework repo but not in NCAR/ccpp-framework. Looks like the new commit in climbfuji/ccpp-framework has not been merged into NCAR/ccpp-framework yet.

**Comment by grantfirl** [comment]
> @dustinswales @jkbk2004 I noticed that this PR points to the new ccpp-framework hash, which is in climbfuji/ccpp-framework repo but not in NCAR/ccpp-framework. Looks like the new commit in climbfuji/ccpp-framework has not been merged into NCAR/ccpp-framework yet.

@ChunxiZhang-NOAA I think that this is "by design". It is being treated like any other CCPP PR. The supermodules point to the PR branch until everything is tested. The fv3atm PR branch will be updated to point to the NCAR/ccpp-framework after we start merging.

**Comment by ChunxiZhang-NOAA** [comment]
> > @dustinswales @jkbk2004 I noticed that this PR points to the new ccpp-framework hash, which is in climbfuji/ccpp-framework repo but not in NCAR/ccpp-framework. Looks like the new commit in climbfuji/ccpp-framework has not been merged into NCAR/ccpp-framework yet.
> 
> @ChunxiZhang-NOAA I think that this is "by design". It is being treated like any other CCPP PR. The supermodules point to the PR branch until everything is tested. The fv3atm PR branch will be updated to point to the NCAR/ccpp-framework after we start merging.

@grantfirl I see, thanks. I didn't realize this PR was combined with the ccpp-framework PR until now.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dustinswales fv3atm dependency 611 was merged. can you update submodule point and revert branch on gitmodules one more time?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
