### PR TITLE
Rremove nems_datm related code, update CDEPS, and remove run directories that are no longer needed by other tests

### LINKED ISSUE #1002: Remove NEMS_datm related code from ufs-weather-model
## Description

The NEMS_datm component has been removed from the ufs-weather-model, but code related to NEMS_datm still exists in CMakeLists.txt, cmake/configure_apps.cmake, and driver/EARTH_GRID_COMP.F90. These three files need to be updated.

## Solution
Revise CMakeLists.txt, cmake/configure_apps.cmake and driver/EARTH_GRID_COMP.F90 to remove NEMS_datm related code.

### LINKED ISSUE #1003: Remove run directories that are no longer needed by other tests during the regression tests
## Description

During regression tests, many run directories are created and those run directories are removed only after all the tests are completed. To reduce disk space used during the tests, the "run_test.sh" script needs to be updated to remove run directories that are no longer needed by other tests during the regression tests.

## Solution
Revise run_test.sh.

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [x] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
The NEMS_datm component has been removed from the ufs-weather-model, but NEMS_datm related code still exists in the following files:
CMakeLists.txt
cmake/configure_apps.cmake
driver/EARTH_GRID_COMP.F90

The above three files will be updated to remove NEMS_datm related code.

During regression tests, many run directories are created and those run directories are removed only after all the tests are completed. To reduce disk space used during the tests, the "run_test.sh" script will be revised to remove run directories that are no longer needed by other tests during the regression tests.

### Issue(s) addressed

- fixes #1002
- fixes #1003 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
No dependencies

### CODE REVIEW

**Comment by binli2337** [comment]
@DeniseWorthen The two new files are located on Hera:
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20211210/DATM_CDEPS/CFSR/201110/cfsr.2011100206.nc
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20211210/DATM_CDEPS/CFSR3072x1536/201110/cfsr.2011100206_3072x1536.nc

Thanks!

**Comment by DeniseWorthen** [comment]
I've added the required file to the Cheyenne input directory.

**Comment by binli2337** [comment]
@DeniseWorthen Thanks.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/817099860/20220120161511/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_30990
Test datm_cdeps_multiple_files_cfsr 112 failed in run_test failed 
Test datm_cdeps_3072x1536_cfsr 113 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Review by junwang-noaa — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
