### PR TITLE
WW3:  Fix Intel CI

### LINKED ISSUE #1889: WW3:  fix Intel CI
## Description
The Intel CI for sub-component WW3 is currently broken for branch, `dev/ufs-weather-model`.  A fix is requested so that the Intel CI functions correctly again.

### To Reproduce:
Push changes on the `dev/ufs-weather-model` branch to a Github-hosted WW3 repository.  From the Github Actions tab, observe the CI failure for the Intel workflow.

## Additional context
- needed for noaa-emc/ww3/pull/1069

## Output
NA.

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [ ] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG:   _Please see note below in section, Regression Tests._
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
This PR applies a fix to the Intel Github CI workflow.  The GNU workflow is also updated at the same time.

### Associated UFSWM Issue to close
- closes #1889 

### Subcomponent Pull Requests
- noaa-emc/ww3/pull/1069

### Blocking Dependencies
None.

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

_Note:  The regression tests have not been run because the only changes this PR introduces are restricted to the Github CI workflow.  Regression tests would not exercise any of that code.  That said I can run them no problem if having the logs as proof is useful. Please let me know if so._

### Libraries
- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 this is a good PR to merge with another as it does not change baselines and is just a hash change. It seems ready to go.

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA please bring these up to date with respective authoritative repositories

@BrianCurtis-NOAA thanks for syncing my branch.

**Comment by jkbk2004** [comment]
> @jkbk2004 this is a good PR to merge with another as it does not change baselines and is just a hash change. It seems ready to go.

Sure! We can merge after a quick sanity check. @zach1221 @FernandoAndrade-NOAA FYI

**Comment by zach1221** [comment]
> > @jkbk2004 this is a good PR to merge with another as it does not change baselines and is just a hash change. It seems ready to go.
> 
> Sure! We can merge after a quick sanity check. @zach1221 @FernandoAndrade-NOAA FYI

Ok, I'll run the regression tests on Hera then and we can move forward after that.

**Comment by zach1221** [comment]
@MatthewMasarik-NOAA ok the sanity check has been complete on Hera, and RT logs posted. We can begin the merging process now. I'll follow up on the WW3 PR for it to be merged.

**Comment by JessicaMeixner-NOAA** [comment]
The WW3 PR has been merged.

**Comment by zach1221** [comment]
@MatthewMasarik-NOAA WW3 PR #1069 is merged. Please update submodule pointer and revert the .gitmodule url.
hash: 97e6a63ebf9a9030fcdae6ad5cf85a0bc91fa37f

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA WW3 PR #1069 is merged. Please update submodule pointer and revert the .gitmodule url. hash: 97e6a63ebf9a9030fcdae6ad5cf85a0bc91fa37f

@zach1221 OK, will do

**Comment by MatthewMasarik-NOAA** [comment]
@zach1221  Should be set

update: whoops, i see i made a mistake on the submodule pointer. i'm correcting it right now

**Comment by MatthewMasarik-NOAA** [comment]
Resolved.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
