### PR TITLE
Coupling merra2 aerosol climatology and GOCART forecasted aerosols with the Thompson microphysics scheme

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR is associated with the ccpp-physics PR[#2](https://github.com/ufs-community/ccpp-physics/pull/2) to add the coupling capability between merra2 aerosol climatology or GOCART forecasted aerosols with the Thompson microphysics scheme. Two new RTs were added into rt.conf, e.g., merra2_thompson and atmaero_control_p8_rad_micro. Otherwise, it will not change the BL. 

### Issue(s) addressed
- fixes #<[4](https://github.com/ufs-community/ccpp-physics/issues/4)>

## Testing
A full set of RTs is done on hera.intel. ORTs for these two new RT passed on hera.intel, please see attached file for one of the tests.
[OpnReqTests_atmaero_control_p8_rad_micro_hera.intel.log.txt](https://github.com/ufs-community/ufs-weather-model/files/9699188/OpnReqTests_atmaero_control_p8_rad_micro_hera.intel.log.txt)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
- waiting on ufs-community/ccpp-physics/pull/<[2](https://github.com/ufs-community/ccpp-physics/pull/2)>
- waiting on noaa-emc/fv3atm/pull/<[588](https://github.com/NOAA-EMC/fv3atm/pull/588)>

### CODE REVIEW

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA we can start working on this pr. Once the branch synced up, I will add baseline change label and new BL_DATE.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 My branch synced with the latest develop branch just now.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1065652889/20220929181510/ufs-weather-model
[BL] Error: Test compile_001 failed in run_compile failed 
[BL] Error: Test compile_002 failed in run_compile failed 
[BL] Error: Test compile_003 failed in run_compile failed 
[BL] Error: Test compile_004 failed in run_compile failed 
[BL] Error: Test compile_005 failed in run_compile failed 
[BL] Error: Test compile_006 failed in run_compile failed 
[BL] Error: Test compile_007 failed in run_compile failed 
[BL] Error: Test compile_008 failed in run_compile failed 
[BL] Error: Test compile_009 failed in run_compile failed 
[BL] Error: Test compile_010 failed in run_compile failed 
[BL] Error: Test compile_011 failed in run_compile failed 
[BL] Error: Test compile_012 failed in run_compile failed 
[BL] Error: Test compile_013 failed in run_compile failed 
[BL] Error: Test compile_014 failed in run_compile failed 
[BL] Error: Test compile_015 failed in run_compile failed 
[BL] Error: Test compile_016 failed in run_compile failed 
[BL] Error: Test compile_017 failed in run_compile failed 
[BL] Error: Test compile_018 failed in run_compile failed 
[BL] Error: Test compile_021 failed in run_compile failed 
[BL] Error: Test compile_022 failed in run_compile failed 
[BL] Error: Test compile_023 failed in run_compile failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by jkbk2004** [comment]
On orion, it seems to force to use "module load git/2.28.0" on autoRT. Manual runs are working ok. On jet, ecflow issue continues. EPIC CM will issue help desk ticket. jet/rocoto work well but cpld_esmfthreads_p8 (TASKS issue in rocoto run, manual/single run works). #1431 might be helpful for the rocoto tasks cal.

**Comment by jkbk2004** [comment]
All the tests are done. We can start merging in the PR. Dependency PRs first. @ChunxiZhang-NOAA go ahead to merge in ccpp pr.

**Comment by ChunxiZhang-NOAA** [comment]
> All the tests are done. We can start merging in the PR. Dependency PRs first. @ChunxiZhang-NOAA go ahead to merge in ccpp pr.

@jkbk2004 I've merged the ccpp PR in. I also updated the fv3atm pointer. fv3atm is ready to merge.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA fv3atm pr merged. We can ask final approval and merge this pr after reverting branch in gitmodules and update fv3atm submodule pointer.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 gitmodules is reverted and fv3atm submodule pointer is modified.

**Pull request merged**
