### PR TITLE
Update Hera and Orion modulefiles to use hpc-stack libs

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

Update Hera(Intel), Orion and WCOSS Dell modulefiles to use hpc-stack libs
New baselines required on Hera (Intel), Orion and WCOSS Dell.

## Testing

Regression tests performed on Hera, Orion and WCOSS Dell against new baselines. Hera (GNU) and WCOSS Cray baselines are identical with the previous commits.

## Dependencies

N/A

### CODE REVIEW

**Comment by junwang-noaa** [comment]
When will we have the hpc-stack on wcoss too? Or we just keep the current module files on wcoss?

**Comment by climbfuji** [comment]
Can we combine this PR with my PR https://github.com/ufs-community/ufs-weather-model/pull/191? Seems to make sense to me.

**Comment by DusanJovic-NOAA** [comment]
I don't know. We should ask NCEPLIBS group. As you can see in one of my commits in this PR (1ab591448e4e2c37b3de683d8b4879f43de5d837) I actually tested it on WCOSS Dell using my hpc-stack build. But that's not 'official' build.

**Comment by DusanJovic-NOAA** [comment]
> Can we combine this PR with my PR #191? Seems to make sense to me.

Sure.

**Comment by climbfuji** [comment]
> > Can we combine this PR with my PR #191? Seems to make sense to me.
> 
> Sure.

Great. Then I suggest that I pull in your PR and that we try to make this change today after Clara's code is merged. I can then update the CCPP tendencies PR over the weekend (should be little work) so that we will be ready to roll on Monday.

**Review by aerorahul — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
The code changes look good to me, but I'd hope we test the same module file in s2s and confirm the same module files work for both before we do the commit

**Comment by climbfuji** [comment]
Ok, then in this case let's not merge it with my PR and do it after the CCPP tendencies. Glad I didn't pull it in yet.

**Comment by DusanJovic-NOAA** [comment]
Difference  (24h lowest layer temperature) between this commit and the previous one are on the order of magnitude as the difference between the butterfly test run and the control run of the previous commit:

d_output1

d_output2

**Review by climbfuji — APPROVED** [review]

**Comment by junwang-noaa** [comment]
Using hpc-stack library, following RT tests show differences while others are not:

fv3_cpt_ccpp
fv3_csawmg_ccpp
fv3_gfsv16_csawmg_ccpp
fv3_gfsv16_csawmgt_ccpp
fv3_gsd_ccpp
fv3_gsd_debug_ccpp
fv3_gsd_diag3d_debug_ccpp
fv3_hrrr_ccpp
fv3_rap_ccpp
fv3_rrfs_v1beta_ccpp
fv3_rrfs_v1beta_debug_ccpp

Taking fv3_csawmg_ccpp test as an example, butterfly test was conducted, the results are at
develop branch :  /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20200917/INTEL/fv3_csawmg_ccpp
dev+butterfly:    /scratch1/NCEPDEV/stmp2/Dusan.Jovic/FV3_RT/rt_88545/fv3_ccpp_csawmg_prod/dynf024.nemsio
hpc-stack branch: /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20200918/INTEL/fv3_csawmg_ccpp

Looking at the tmpsfc field in the phyf025.nemsio files in the above three directory:
dev: tmpsfc
butterfly: tmpsfc.2
stack: tmpsfc.3

From grads, the max/min difference of (tmpsfc-tmpsfc.2) is 8 and -8, the average of (tmpsfc-tmpsfc.2) is  0.00210166, the std is 0.27809.
From grads, the max/min difference of (tmpsfc-tmpsfc.3) is 8 and -6. the average of (tmpsfc-tmpsfc.2) is  0.000960768, the std is 0.250452

From the results the change from hpc-stack is comparable to that from butterfly test. While Dom is debugging the code that causes the difference, if he finds anything that needs to be fixes, he will submit a separate PR. With the results, we will commit the code.

**Pull request merged**
