### PR TITLE
Support IntelLLVM compiler

### LINKED ISSUE #2025: Upgrade to Intel LLVM Compilers
## Description

The 'classic' Intel compilers (`ifort`, `icc`, and `icpc`) are now discontinued and the new LLVM compilers (`ifx` and `icx`) are the only option starting with version 2024.

## Solution

All supported machines with working versions of the LLVM compilers should be upgraded to the LLVM suite.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Add preliminary support for Intel LLVM compiler. Added new top-level `cmake/IntelLLVM.cmake` configuration file. Update CMakeLists.txt in various submodules to recognize IntelLLVM as supported compiler and add Intel LLVM compiler flags.

Useful porting guide: https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-ifort-to-ifx.html 

At this moment I only tried to build the model on Hercules.

In order to use new compiler you need to set the following three environment variables:

export I_MPI_CC=icx
export I_MPI_CXX=icpx
export I_MPI_F90=ifx

### Commit Message:

```
* UFSWM -  Add support for Intel LLVM compiler
  * CICE -  Add support for Intel LLVM compiler
  * FV3 -  Add support for Intel LLVM compiler
    * ccpp-physics -  Add support for Intel LLVM compiler
    * atmos_cubed_sphere -  Add support for Intel LLVM compiler 
    * upp -  Add support for Intel LLVM compiler 
  * WW3 - Add support for Intel LLVM compiler
```

### Priority:

* Normal

### UFSWM:

* Closes #2025

### Sub component Pull Requests:

* FV3: NOAA-EMC/fv3atm/pull/861
  * ccpp-physics: ufs-community/ccpp-physics/pull/220
  * atmos_cubed_sphere: NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/353
  * upp: NOAA-EMC/UPP/pull/1001
* WW3: NOAA-EMC/WW3/pull/1276
* CICE: NOAA-EMC/CICE/pull/91

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Is this something for only Hercules, or will other systems be implementing IntelLLVM ?

**Comment by DusanJovic-NOAA** [comment]
> Is this something for only Hercules, or will other systems be implementing IntelLLVM ?

Eventually we must switch to IntelLLVM on all platforms. When, I don't know. But classic Intel compilers are now deprecated, see:
https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes.html

**NOTE:**  Intel® Fortran Compiler Classic (ifort) is now deprecated and will be discontinued in late 2024. Intel recommends that customers transition now to using the LLVM-based Intel® Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. For more information on ifx, see the Intel® Fortran Compiler Developer Guide and Reference and the Porting Guide for ifort Users to ifx.

**Comment by DusanJovic-NOAA** [comment]
Compilation with Intel LLVM on Hera fails with this error:
```
/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/support_intelllvm/ufs-weather-model/MOM6-interface/
MOM6/src/framework/MOM_unit_testing.F90(128): error #5533: Feature found on this line is not 
yet supported in ifx                                                                         
  test%proc => proc
--^
compilation aborted for /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/support_intelllvm/ufs-weath
er-model/MOM6-interface/MOM6/src/framework/MOM_unit_testing.F90 (code 3)
make[2]: *** [MOM6-interface/CMakeFiles/mom6_obj.dir/build.make:1765: MOM6-interface/CMakeFil
es/mom6_obj.dir/MOM6/src/framework/MOM_unit_testing.F90.o] Error 3
```

**Comment by DusanJovic-NOAA** [comment]
All coupled debug tests fail on Hercules with this error:
```
179: forrtl: severe (408): fort: (3): Subscript #3 of the array UVEL has value 0 which is less than the lower bound of 1
179: 
179: Image              PC                Routine            Line        Source             
179: ufs_model          000000000B5A1262  accum_hist               2318  ice_history.F90
179: ufs_model          000000000B4BFB6F  initializerealize         835  ice_comp_nuopc.F90
179: ufs_model          0000000000B94024  Unknown               Unknown  Unknown
179: ufs_model          0000000000B97F9F  Unknown               Unknown  Unknown
179: ufs_model          0000000000D0EBC7  Unknown               Unknown  Unknown
179: ufs_model          0000000000CFB022  Unknown               Unknown  Unknown
```
This is looks like a bug in the ifx.

**Comment by DeniseWorthen** [comment]
@NickSzapiro-NOAA Would you please take a look at what is happening here w/ CICE? You'll need to get from @DusanJovic-NOAA build instructions and maybe a sandbox run directory.

**Comment by NickSzapiro-NOAA** [comment]
Of course, @DeniseWorthen @DusanJovic-NOAA. Please let me know if there are any special instructions needed to reproduce. On first pass, it's curious that the ice speed may be the first call to accum_hist with an array that was not allocated:
https://github.com/NOAA-EMC/CICE/blob/emc/develop/cicecore/cicedyn/analysis/ice_history.F90#L2317-L2320

**Comment by DusanJovic-NOAA** [comment]
I was able to create a small test program that reproduces an error identical to the one we see in CICE. Dom (@climbfuji) confirmed that it works with the latest Intel LLVM compiler (ifx (IFX) 2024.1.0 20240308), so it is probably just a bug in the older versions.

Version on Hercules is (ifx (IFX) 2023.1.0 20230320). On Hera it's even older (ifx (IFORT) 2022.0.0 20211123), and that version can not even compile the code with MOM6. See above error.

We need to find a machine (NOAA R&D) on which we can get the latest version of Intel LLVM compiler (2024.1.0) installed.

**Comment by climbfuji** [comment]
I can install it on Hercules in the EPIC spack-stack space, but we still need to manage building all dependencies with it.

**Comment by junwang-noaa** [comment]
If it is confirmed that the latest Intel LLVM compiler fixes the issue, let's ask sysadmin to install the latest version.

**Comment by DusanJovic-NOAA** [comment]
> I can install it on Hercules in the EPIC spack-stack space, but we still need to manage building all dependencies with it.

Eventually yes, but for now I think we can still build all libraries (spack-stack) with ifort (but the new version 2024) and only the model with ifx. Object files and module files should be binary compatible between ifort and ifx.

According to Intel:
_... Binaries and libraries generated with ifort can be linked with binaries and libraries built with ifx, and .mod files generated with one compiler can be used by the other (64-bit targets only). Both compilers use the the same runtime libraries. ..._

**Comment by climbfuji** [comment]
Except that there's no more icc anc icpc, so at least for those we have to switch to icx and icpx. It should be fairly straightforward to build just the dependencies for the ufs-weather-model with ifort and/or ifx and get all the other packages compiled in a second step.

**Comment by NickSzapiro-NOAA** [comment]
@DusanJovic-NOAA Does filling worka first (https://github.com/NOAA-EMC/CICE/blob/emc/develop/cicecore/cicedyn/analysis/ice_history.F90#L2321-L2331) give a temporary fix?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Does filling worka first (https://github.com/NOAA-EMC/CICE/blob/emc/develop/cicecore/cicedyn/analysis/ice_history.F90#L2321-L2331) give a temporary fix?

I think it should. Looks like having an array expression (that depends on iblk) as an actual subroutine argument is what fails.

**Comment by DusanJovic-NOAA** [comment]
Currently debug builds fail (on Hera) with the following error:

```
[100%] Linking Fortran executable ufs_model
ld: cannot find -lpioc
ld: attempted static link of dynamic object `/apps/oneapi/compiler/2023.2.0/linux/compiler/lib/intel64_lin/libiomp5.so'
make[2]: *** [CMakeFiles/ufs_model.dir/build.make:121: ufs_model] Error 1
make[1]: *** [CMakeFiles/Makefile2:328: CMakeFiles/ufs_model.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

That's why all debug tests are currently disabled in `rt_intelllvm.conf`.

All non-debug tests successfully compile, execute and reproduce it's own outputs, ie:

```
./rt.sh -l rt_intelllvm.conf -e -c
./rt.sh -l rt_intelllvm.conf -e -m  
```
is successful.

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA So this looks to me a compiler build issue. Would you please send an email to hera admin?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA So this looks to me a compiler build issue. Would you please send an email to hera admin?

On Hera we currently use spack-stack 1.6.0 which loads `intel/2022.1.2` module. When I try to build the model using the ifx compiler from that module, I get the following syntax error:

```
/scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/support_intelllvm/ufs-weather-model/MOM6-interface/MOM6/src/framework/MOM_unit_testing.F90(128): error #5533: Feature found on this line is not yet supported in ifx
 test%proc => proc
--^
compilation aborted for /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/support_intelllvm/ufs-weather-model/MOM6-interface/MOM6/src/framework/MOM_unit_testing.F90 (code 3)
make[2]: *** [MOM6-interface/CMakeFiles/
```
which is the same error I mentioned here https://github.com/ufs-community/ufs-weather-model/pull/2224#issuecomment-2037267214

That's why I tried to load `intel/2023.2.0` which unfortunately fails at linking when debugging is turned on.

Maybe we need to try to rebuild the spack-stack with intel/2023.2.0.

I do not think this is the issue of how the compilers are installed.

**Comment by DeniseWorthen** [comment]
We have an intel 2023.2.0 build on hera, I was using it to test the long-run issue. See [comment](https://github.com/ufs-community/ufs-weather-model/issues/2320#issuecomment-2195661222)

**Comment by DusanJovic-NOAA** [comment]
> We have an intel 2023.2.0 build on hera, I was using it to test the long-run issue. See [comment](https://github.com/ufs-community/ufs-weather-model/issues/2320#issuecomment-2195661222)

Thanks. Let me try.

**Comment by DusanJovic-NOAA** [comment]
> > We have an intel 2023.2.0 build on hera, I was using it to test the long-run issue. See [comment](https://github.com/ufs-community/ufs-weather-model/issues/2320#issuecomment-2195661222)
> 
> Thanks. Let me try.

Using llvm compilers from intel 2023.2.0 module fixed the syntax error in MOM6, but unfortunately there is still linker error:

```[100%] Linking Fortran executable ufs_model
ld: attempted static link of dynamic object `/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/ue-intel-2023.2.0/install/intel/2023.2.0/netcdf-c-4.9.2-dngd6i2/lib/libnetcdf.so'
make[2]: *** [CMakeFiles/ufs_model.dir/build.make:128: ufs_model] Error 1
make[1]: *** [CMakeFiles/Makefile2:480: CMakeFiles/ufs_model.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by DusanJovic-NOAA** [comment]
`cpld_debug_gfsv17` regression test fails on hercules with this error using intel llvm compiler:

```
179: forrtl: severe (408): fort: (3): Subscript #3 of the array UVEL has value 0 which is less than the lower bound of 1
179: 
179: Image              PC                Routine            Line        Source             
179: ufs_model          000000000BD723D2  accum_hist               2360  ice_history.F90
179: ufs_model          000000000BBB4FA5  initializerealize         888  ice_comp_nuopc.F90
179: ufs_model          0000000000ADFFC4  Unknown               Unknown  Unknown
179: ufs_model          0000000000AE3F3F  Unknown               Unknown  Unknown
179: ufs_model          000000000115437A  Unknown               Unknown  Unknown
179: ufs_model          00000000012E9188  Unknown               Unknown  Unknown
```
Subscript 3 of the array UVEL is `iblk`, which is a do loop index (`do iblk = 1, nblocks`). I do not see how `iblk` can be zero. If I comment out the $OMP directives before this do loop, test finishes successfully. @DeniseWorthen do you see any reason why `iblk` becomes 0. This could be a compiler issue, since this code works with classic intel and gnu compilers.

**Comment by DusanJovic-NOAA** [comment]
I wrote this short test program that reproduces the error I see in CICE:
```fortran
program test1
  implicit none
  integer :: iblk
  real :: u(2,2,3)

  u = 7.0
!$OMP PARALLEL DO PRIVATE(iblk)
  do iblk = 1, 3
     call sub(u(:,:,iblk)*2.0)
  end do
!$OMP END PARALLEL DO

contains
  subroutine sub(f)
    real, intent(in) :: f(:,:)
    return
  end subroutine sub
end program test1
```

It fails when I build it with ifx 2023.1.0:

```bash
$ ifx --version
ifx (IFX) 2023.1.0 20230320
Copyright (C) 1985-2023 Intel Corporation. All rights reserved.

$ ifx -qopenmp -O0 -check all test_ifx_openmp.F90

$ OMP_NUM_THREADS=3 ./a.out
forrtl: severe (408): fort: (3): Subscript #3 of the array U has value 0 which is less than the lower bound of 1

Image              PC                Routine            Line        Source
a.out              00000000004053F2  Unknown               Unknown  Unknown
a.out              000000000040523D  Unknown               Unknown  Unknown
libc.so.6          00007F4D55584EB0  Unknown               Unknown  Unknown
libc.so.6          00007F4D55584F60  __libc_start_main     Unknown  Unknown
a.out              0000000000405155  Unknown               Unknown  Unknown
```
but works with ifort:

```
$ ifort --version
ifort (IFORT) 2021.9.0 20230302
Copyright (C) 1985-2023 Intel Corporation.  All rights reserved.

$ ifort -qopenmp -O0 -check all test_ifx_openmp.F90

$ OMP_NUM_THREADS=3 ./a.out
```
and ifx 2024.1.0

```
$ ifx --version
ifx (IFX) 2024.1.0 20240308
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.

$ ifx -qopenmp -O0 -check all test_ifx_openmp.F90

$ OMP_NUM_THREADS=3 ./a.out
```

To me this looks like a compiler bug. My suggestion is that we conditionally comment out OMP directives for that specific do loop in ice_history.F90

**Comment by climbfuji** [comment]
@DusanJovic-NOAA I tried this with the very latest `ifx@2024.2.0` and got a different error message:
```
ubuntu@ip-10-0-1-156:~/sandpit$ ifx --version
ifx (IFX) 2024.2.0 20240602
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.

ubuntu@ip-10-0-1-156:~/sandpit$ which ifx
/opt/intel/oneapi/compiler/2024.2/bin/ifx

ubuntu@ip-10-0-1-156:~/sandpit$ ifx -qopenmp -O0 -check all -o test_ifx_bug.x test_ifx_bug.F90

ubuntu@ip-10-0-1-156:~/sandpit$ OMP_NUM_THREADS=3 ./test_ifx_bug.x
==4030377==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x40cf52 in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
    #1 0x79be39a29eba in call_init csu/../csu/libc-start.c:145:3
    #2 0x79be39a29eba in __libc_start_main csu/../csu/libc-start.c:379:5
    #3 0x40cfc4 in _start (/home/ubuntu/sandpit/test_ifx_bug.x+0x40cfc4) (BuildId: e1671860202a96129dac2b4735ca5d800854a361)

  Uninitialized value was created by an allocation of 'a.i.i' in the stack frame
    #0 0x40c48a in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c

SUMMARY: MemorySanitizer: use-of-uninitialized-value fast_mem_ops.c in _GLOBAL__sub_I_fast_mem_ops.c
Exiting
```

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA I tried this with the very latest `ifx@2024.2.0` and got a different error message:
> 
> ```
> ubuntu@ip-10-0-1-156:~/sandpit$ ifx --version
> ifx (IFX) 2024.2.0 20240602
> Copyright (C) 1985-2024 Intel Corporation. All rights reserved.
> 
> ubuntu@ip-10-0-1-156:~/sandpit$ which ifx
> /opt/intel/oneapi/compiler/2024.2/bin/ifx
> 
> ubuntu@ip-10-0-1-156:~/sandpit$ ifx -qopenmp -O0 -check all -o test_ifx_bug.x test_ifx_bug.F90
> 
> ubuntu@ip-10-0-1-156:~/sandpit$ OMP_NUM_THREADS=3 ./test_ifx_bug.x
> ==4030377==WARNING: MemorySanitizer: use-of-uninitialized-value
>     #0 0x40cf52 in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
>     #1 0x79be39a29eba in call_init csu/../csu/libc-start.c:145:3
>     #2 0x79be39a29eba in __libc_start_main csu/../csu/libc-start.c:379:5
>     #3 0x40cfc4 in _start (/home/ubuntu/sandpit/test_ifx_bug.x+0x40cfc4) (BuildId: e1671860202a96129dac2b4735ca5d800854a361)
> 
>   Uninitialized value was created by an allocation of 'a.i.i' in the stack frame
>     #0 0x40c48a in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
> 
> SUMMARY: MemorySanitizer: use-of-uninitialized-value fast_mem_ops.c in _GLOBAL__sub_I_fast_mem_ops.c
> Exiting
> ```

Looks like they introduced regression in 2024.2.0. Anyway I added an `#ifndef` to skip OMP for that particular do loop in CICE if Intel LLVM is used. Hopefully just a temporary fix until the issue is finally resolved.

**Comment by DusanJovic-NOAA** [comment]
> > @DusanJovic-NOAA I tried this with the very latest `ifx@2024.2.0` and got a different error message:
> > ```
> > ubuntu@ip-10-0-1-156:~/sandpit$ ifx --version
> > ifx (IFX) 2024.2.0 20240602
> > Copyright (C) 1985-2024 Intel Corporation. All rights reserved.
> > 
> > ubuntu@ip-10-0-1-156:~/sandpit$ which ifx
> > /opt/intel/oneapi/compiler/2024.2/bin/ifx
> > 
> > ubuntu@ip-10-0-1-156:~/sandpit$ ifx -qopenmp -O0 -check all -o test_ifx_bug.x test_ifx_bug.F90
> > 
> > ubuntu@ip-10-0-1-156:~/sandpit$ OMP_NUM_THREADS=3 ./test_ifx_bug.x
> > ==4030377==WARNING: MemorySanitizer: use-of-uninitialized-value
> >     #0 0x40cf52 in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
> >     #1 0x79be39a29eba in call_init csu/../csu/libc-start.c:145:3
> >     #2 0x79be39a29eba in __libc_start_main csu/../csu/libc-start.c:379:5
> >     #3 0x40cfc4 in _start (/home/ubuntu/sandpit/test_ifx_bug.x+0x40cfc4) (BuildId: e1671860202a96129dac2b4735ca5d800854a361)
> > 
> >   Uninitialized value was created by an allocation of 'a.i.i' in the stack frame
> >     #0 0x40c48a in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
> > 
> > SUMMARY: MemorySanitizer: use-of-uninitialized-value fast_mem_ops.c in _GLOBAL__sub_I_fast_mem_ops.c
> > Exiting
> > ```
> 
> Looks like they introduced regression in 2024.2.0. Anyway I added an `#ifndef` to skip OMP for that particular do loop in CICE if Intel LLVM is used. Hopefully just a temporary fix until the issue is finally resolved.

I just installed 2024.02 on my laptop, and surprisingly the test program does not crash.

```
dusan@fedora: ~/test_ifx
$ which ifx
~/intel/oneapi/compiler/2024.2/bin/ifx

dusan@fedora: ~/test_ifx
$ ifx --version
ifx (IFX) 2024.2.0 20240602
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.


dusan@fedora: ~/test_ifx
$ ifx -qopenmp -O0 -check all ./test_ifx_openmp.F90

dusan@fedora: ~/test_ifx
$ OMP_NUM_THREADS=3 ./a.out

dusan@fedora: ~/test_ifx
```
Could this be an installation issue or maybe OS differences.

**Comment by climbfuji** [comment]
> > > @DusanJovic-NOAA I tried this with the very latest `ifx@2024.2.0` and got a different error message:
> > > ```
> > > ubuntu@ip-10-0-1-156:~/sandpit$ ifx --version
> > > ifx (IFX) 2024.2.0 20240602
> > > Copyright (C) 1985-2024 Intel Corporation. All rights reserved.
> > > 
> > > ubuntu@ip-10-0-1-156:~/sandpit$ which ifx
> > > /opt/intel/oneapi/compiler/2024.2/bin/ifx
> > > 
> > > ubuntu@ip-10-0-1-156:~/sandpit$ ifx -qopenmp -O0 -check all -o test_ifx_bug.x test_ifx_bug.F90
> > > 
> > > ubuntu@ip-10-0-1-156:~/sandpit$ OMP_NUM_THREADS=3 ./test_ifx_bug.x
> > > ==4030377==WARNING: MemorySanitizer: use-of-uninitialized-value
> > >     #0 0x40cf52 in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
> > >     #1 0x79be39a29eba in call_init csu/../csu/libc-start.c:145:3
> > >     #2 0x79be39a29eba in __libc_start_main csu/../csu/libc-start.c:379:5
> > >     #3 0x40cfc4 in _start (/home/ubuntu/sandpit/test_ifx_bug.x+0x40cfc4) (BuildId: e1671860202a96129dac2b4735ca5d800854a361)
> > > 
> > >   Uninitialized value was created by an allocation of 'a.i.i' in the stack frame
> > >     #0 0x40c48a in _GLOBAL__sub_I_fast_mem_ops.c fast_mem_ops.c
> > > 
> > > SUMMARY: MemorySanitizer: use-of-uninitialized-value fast_mem_ops.c in _GLOBAL__sub_I_fast_mem_ops.c
> > > Exiting
> > > ```
> > 
> > 
> > Looks like they introduced regression in 2024.2.0. Anyway I added an `#ifndef` to skip OMP for that particular do loop in CICE if Intel LLVM is used. Hopefully just a temporary fix until the issue is finally resolved.
> 
> I just installed 2024.02 on my laptop, and surprisingly the test program does not crash.
> 
> ```
> dusan@fedora: ~/test_ifx
> $ which ifx
> ~/intel/oneapi/compiler/2024.2/bin/ifx
> 
> dusan@fedora: ~/test_ifx
> $ ifx --version
> ifx (IFX) 2024.2.0 20240602
> Copyright (C) 1985-2024 Intel Corporation. All rights reserved.
> 
> 
> dusan@fedora: ~/test_ifx
> $ ifx -qopenmp -O0 -check all ./test_ifx_openmp.F90
> 
> dusan@fedora: ~/test_ifx
> $ OMP_NUM_THREADS=3 ./a.out
> 
> dusan@fedora: ~/test_ifx
> ```
> 
> Could this be an installation issue or maybe OS differences.

Mine was ubuntu 22.04

**Comment by NickSzapiro-NOAA** [comment]
@DusanJovic-NOAA If https://github.com/ufs-community/ufs-weather-model/pull/2430 continues ok to merge, the changes to CICE in cicecore/cicedyn/analysis/ice_history.F90 should be via PR to new EMC/CICE develop branch

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA If #2430 continues ok to merge, the changes to CICE in cicecore/cicedyn/analysis/ice_history.F90 should be via PR to new EMC/CICE develop branch

Okay. Once the 2430 is merged, I'll update my branch.

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hera 
[RegressionTests_hera.log](https://github.com/user-attachments/files/17097655/RegressionTests_hera.log)

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA We can commit this pr today. Please, go ahead to sync up branch.

**Comment by DusanJovic-NOAA** [comment]
@jkbk2004 We would to update CICE submodule to use an updated PR and branch that includes both LLVM updates and some other updates from upstream. Results are expected to still be b4b.

**Comment by jkbk2004** [comment]
> @jkbk2004 We would to update CICE submodule to use an updated PR and branch that includes both LLVM updates and some other updates from upstream. Results are expected to still be b4b.
@DusanJovic-NOAA I will confirm.

**Comment by DusanJovic-NOAA** [comment]
CICE submodule has been updated. Ready for regression testing.

**Comment by grantfirl** [comment]
@DusanJovic-NOAA We've been asked to add someone to our CODEOWNERS file in the ccpp-physics repo and we're trying to find a convenient PR to do this in so that we don't open a separate PR for this small task. Of course, it doesn't affect any testing, but you would need to merge a PR into https://github.com/ufs-community/ccpp-physics/pull/220 and update submodule hashes. Would you be willing to do this? If not, no big deal. If yes, I'll prepare a PR into your branch for https://github.com/ufs-community/ccpp-physics/pull/220.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA We've been asked to add someone to our CODEOWNERS file in the ccpp-physics repo and we're trying to find a convenient PR to do this in so that we don't open a separate PR for this small task. Of course, it doesn't affect any testing, but you would need to merge a PR into [ufs-community/ccpp-physics#220](https://github.com/ufs-community/ccpp-physics/pull/220) and update submodule hashes. Would you be willing to do this? If not, no big deal. If yes, I'll prepare a PR into your branch for [ufs-community/ccpp-physics#220](https://github.com/ufs-community/ccpp-physics/pull/220).

Sure. I can do that. Please open PR to my ccpp-physics branch. @jkbk2004 Please hold on for few more minutes with starting RT.

**Comment by grantfirl** [comment]
> > @DusanJovic-NOAA We've been asked to add someone to our CODEOWNERS file in the ccpp-physics repo and we're trying to find a convenient PR to do this in so that we don't open a separate PR for this small task. Of course, it doesn't affect any testing, but you would need to merge a PR into [ufs-community/ccpp-physics#220](https://github.com/ufs-community/ccpp-physics/pull/220) and update submodule hashes. Would you be willing to do this? If not, no big deal. If yes, I'll prepare a PR into your branch for [ufs-community/ccpp-physics#220](https://github.com/ufs-community/ccpp-physics/pull/220).
> 
> Sure. I can do that. Please open PR to my ccpp-physics branch. @jkbk2004 Please hold on for few more minutes with starting RT.

@DusanJovic-NOAA Thanks. See https://github.com/DusanJovic-NOAA/ccpp-physics/pull/1

**Comment by DusanJovic-NOAA** [comment]
Merged ccpp-physics PR, and updated submodules. Please double check and if everything looks good I think we can finally start RT

**Comment by grantfirl** [comment]
> Merged ccpp-physics PR, and updated submodules. Please double check and if everything looks good I think we can finally start RT

@DusanJovic-NOAA Thanks for granting this last-minute request!

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA Can you edit the template in the Changes section? I don't think we're changing any baselines or have new input data or need any library bumps.

**Comment by BrianCurtis-NOAA** [comment]
nevermind, i didn't refresh my page

**Comment by NickSzapiro-NOAA** [comment]
The CICE #ifndef LLVM PR was merged at CICE-Consortium. Here is a new EMC/CICE branch (https://github.com/NickSzapiro-NOAA/CICE/tree/cice_llvm) and PR (https://github.com/NOAA-EMC/CICE/pull/93) for use in this PR.

It is the same lines of code for us in CICE and cleaner git history. If can use, there is no need to repeat testing.

**Comment by jkbk2004** [comment]
@NickSzapiro-NOAA @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA We will start merging process for this pr.

**Comment by zach1221** [comment]
> @NickSzapiro-NOAA @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA We will start merging process for this pr.

Should we wait for ORTs or no? Fernando and I have been trying to run on Hera, but the jobs have sat in pending.

**Comment by BrianCurtis-NOAA** [comment]
> > @NickSzapiro-NOAA @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA We will start merging process for this pr.
> 
> Should we wait for ORTs or no? Fernando and I have been trying to run on Hera, but the jobs have sat in pending.

I think it's OK to skip those here.

**Comment by NickSzapiro-NOAA** [comment]
For CICE, is it ok to change to this PR (https://github.com/NOAA-EMC/CICE/pull/93) and branch (https://github.com/NickSzapiro-NOAA/CICE/tree/cice_llvm) instead?

**Comment by jkbk2004** [comment]
> For CICE, is it ok to change to this PR ([NOAA-EMC/CICE#93](https://github.com/NOAA-EMC/CICE/pull/93)) and branch (https://github.com/NickSzapiro-NOAA/CICE/tree/cice_llvm) instead?

@NickSzapiro-NOAA I don't want to keep pushing code changes to this pr since all tests are done. You can bring up changes to next pr #2437.

**Comment by grantfirl** [comment]
> @NickSzapiro-NOAA @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA We will start merging process for this pr.

@jkbk2004 Shall I go ahead and merge https://github.com/ufs-community/ccpp-physics/pull/220 to start?

**Comment by jkbk2004** [comment]
> > @NickSzapiro-NOAA @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA We will start merging process for this pr.
> 
> @jkbk2004 Shall I go ahead and merge [ufs-community/ccpp-physics#220](https://github.com/ufs-community/ccpp-physics/pull/220) to start?

@grantfirl give us about two hours more. @NickSzapiro-NOAA wants to switch around cice feature branches. but no actual code base changes.

**Comment by NickSzapiro-NOAA** [comment]
Apologies for the last minute changes but commit of cice_llvm branch to EMC/CICE instead seems preferable in the interests of cleaner git history. Just to be explicit, we're talking about the same 4 narrow code changes in cicecore/cicedyn/analysis/ice_history.F90 and cicecore/drivers/nuopc/cmeps/ice_prescribed_mod.F90 in
https://github.com/NOAA-EMC/CICE/compare/develop...NickSzapiro-NOAA:CICE:sync_cice
vs
https://github.com/NOAA-EMC/CICE/compare/develop...NickSzapiro-NOAA:CICE:cice_llvm

I just tried to make a sanity check of cpld_control_gfsv17 on hercules with cice_llvm branch. Compile is successful but Disk quota is full today so run stops. @jkbk2004 @BrianCurtis-NOAA I don't want to delay commit queue but not sure what to do. It is the same lines of code that have already been tested...

If switch is ok, PR closes CICE issue https://github.com/NOAA-EMC/CICE/pull/93 instead

Update: cpld_control_gfsv17 passed b4b on hercules with cice_llvm branch @jkbk2004 @BrianCurtis-NOAA

**Comment by jkbk2004** [comment]
@NickSzapiro-NOAA Let's go with https://github.com/NOAA-EMC/CICE/pull/93. Please, go ahead to merge the CICE pr. @grantfirl Please, go ahead to merge https://github.com/ufs-community/ccpp-physics/pull/220

**Comment by jkbk2004** [comment]
@FernandoAndrade-NOAA @gspetro-NOAA will you merge https://github.com/NOAA-EMC/UPP/pull/1001?

**Comment by grantfirl** [comment]
> @NickSzapiro-NOAA Let's go with [NOAA-EMC/CICE#93](https://github.com/NOAA-EMC/CICE/pull/93). Please, go ahead to merge the CICE pr. @grantfirl Please, go ahead to merge [ufs-community/ccpp-physics#220](https://github.com/ufs-community/ccpp-physics/pull/220)

@jkbk2004 Done

**Comment by NickSzapiro-NOAA** [comment]
CICE is merged too

**Comment by MatthewMasarik-NOAA** [comment]
@jkbk2004, WW3 is merged.

**Comment by WenMeng-NOAA** [comment]
> @FernandoAndrade-NOAA @gspetro-NOAA will you merge [NOAA-EMC/UPP#1001](https://github.com/NOAA-EMC/UPP/pull/1001)?

@jkbk2004 @DusanJovic-NOAA UPP is merged.

**Review by jkbk2004 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Pull request merged**
