### PR TITLE
New Thompson cloud fraction (updated subroutine cal_cldfra3)

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR currently only updates the submodule pointers for fv3atm and ccpp-physics for the code changes described in https://github.com/NCAR/ccpp-physics/pull/795 and https://github.com/NOAA-EMC/fv3atm/pull/432: the addition of a new cloud fraction scheme for Thompson MP.

The changes for Thompson MP require new baselines for all regression tests using the scheme.

### Issue(s) addressed

This PR is one step towards addressing the issue described in https://github.com/NCAR/ccpp-physics/issues/765 (additional changes will be merged in a separate PR).

## Testing

Regression tests will be run on all tier-1 platforms at the time of commit.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [n/a] opnReqTest for newly added/changed feature
- [skip] CI (due to a wrong fv3atm submodule pointer in ufs-weather-model develop, `repo_check` fails)

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/781
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/432

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/787186483/20211209213008/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_57962
Test compile 001 failed failed 
Test compile 001 failed failed 
Test compile 002 failed failed 
Test compile 002 failed failed 
Test compile 003 failed failed 
Test compile 003 failed failed 
Test compile 004 failed failed 
Test compile 004 failed failed 
Test compile 005 failed failed 
Test compile 005 failed failed 
Test compile 006 failed failed 
Test compile 006 failed failed 
Test compile 007 failed failed 
Test compile 007 failed failed 
Test compile_001 failed in run_compile failed 
Test compile_002 failed in run_compile failed 
Test compile_003 failed in run_compile failed 
Test compile_004 failed in run_compile failed 
Test compile_005 failed in run_compile failed 
Test compile_006 failed in run_compile failed 
Test compile_007 failed in run_compile failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/787186483/20211209200012/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_64555
Test cpld_control_p7_rrtmgp 002 failed failed 
Test cpld_control_p7_rrtmgp 002 failed in run_test failed 
Test control_p7_rrtmgp 019 failed failed 
Test control_p7_rrtmgp 019 failed in run_test failed 
Test regional_RRTMGP 024 failed failed 
Test regional_RRTMGP 024 failed in run_test failed 
Test control_rrtmgp 030 failed failed 
Test control_rrtmgp 030 failed in run_test failed 
Test control_rrtmgp_c192 031 failed failed 
Test control_rrtmgp_c192 031 failed in run_test failed 
Test hafs_regional_datm_cdeps 072 failed failed 
Test hafs_regional_datm_cdeps 072 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: cheyenne
> Compiler: intel
> Job: BL
> Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/787186483/20211209200012/ufs-weather-model
> Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_64555
> Test cpld_control_p7_rrtmgp 002 failed failed
> Test cpld_control_p7_rrtmgp 002 failed in run_test failed
> Test control_p7_rrtmgp 019 failed failed
> Test control_p7_rrtmgp 019 failed in run_test failed
> Test regional_RRTMGP 024 failed failed
> Test regional_RRTMGP 024 failed in run_test failed
> Test control_rrtmgp 030 failed failed
> Test control_rrtmgp 030 failed in run_test failed
> Test control_rrtmgp_c192 031 failed failed
> Test control_rrtmgp_c192 031 failed in run_test failed
> Test hafs_regional_datm_cdeps 072 failed failed
> Test hafs_regional_datm_cdeps 072 failed in run_test failed
> Please make changes and add the following label back:
> cheyenne-intel-BL

This was my mistake, now fixed. Will rerun.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/787186483/20211209221515/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_414890
/work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211209/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/787186483/20211209220012/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_387695
Baseline creation and move successful
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/787186483/20211209231032/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_71980
Test cpld_control_p7 001 failed in check_result failed 
Test cpld_control_p7 001 failed in run_test failed 
Test cpld_control_p7_rrtmgp 002 failed in check_result failed 
Test cpld_control_p7_rrtmgp 002 failed in run_test failed 
Test cpld_2threads_p7 003 failed in check_result failed 
Test cpld_2threads_p7 003 failed in run_test failed 
Test cpld_decomp_p7 004 failed in check_result failed 
Test cpld_decomp_p7 004 failed in run_test failed 
Test cpld_mpi_p7 005 failed in check_result failed 
Test cpld_mpi_p7 005 failed in run_test failed 
Test cpld_bmark_p7 006 failed in check_result failed 
Test cpld_bmark_p7 006 failed in run_test failed 
Test cpld_bmark_mpi_p7 007 failed in check_result failed 
Test cpld_bmark_mpi_p7 007 failed in run_test failed 
Test cpld_control_c96_p7 008 failed in check_result failed 
Test cpld_control_c96_p7 008 failed in run_test failed 
Test cpld_control_c192_p7 010 failed in check_result failed 
Test cpld_control_c192_p7 010 failed in run_test failed 
Test cpld_control_c384_p7 012 failed in check_result failed 
Test cpld_control_c384_p7 012 failed in run_test failed 
Test cpld_debug_p7 014 failed in check_result failed 
Test cpld_debug_p7 014 failed in run_test failed 
Test control 015 failed in check_result failed 
Test control 015 failed in run_test failed 
Test control_decomp 016 failed in check_result failed 
Test control_decomp 016 failed in run_test failed 
Test control_2threads 017 failed in check_result failed 
Test control_2threads 017 failed in run_test failed 
Test control_fhzero 019 failed in check_result failed 
Test control_fhzero 019 failed in run_test failed 
Test control_CubedSphereGrid 020 failed in check_result failed 
Test control_CubedSphereGrid 020 failed in run_test failed 
Test control_latlon 021 failed in check_result failed 
Test control_latlon 021 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 022 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel 022 failed in run_test failed 
Test control_c48 023 failed in check_result failed 
Test control_c48 023 failed in run_test failed 
Test control_c192 024 failed in check_result failed 
Test control_c192 024 failed in run_test failed 
Test control_c384 025 failed in check_result failed 
Test control_c384 025 failed in run_test failed 
Test control_c384gdas 026 failed in check_result failed 
Test control_c384gdas 026 failed in run_test failed 
Test control_stochy 027 failed in check_result failed 
Test control_stochy 027 failed in run_test failed 
Test control_lndp 029 failed in check_result failed 
Test control_lndp 029 failed in run_test failed 
Test control_p7 030 failed in check_result failed 
Test control_p7 030 failed in run_test failed 
Test control_p7_rrtmgp 031 failed in check_result failed 
Test control_p7_rrtmgp 031 failed in run_test failed 
Test control_decomp_p7 033 failed in check_result failed 
Test control_decomp_p7 033 failed in run_test failed 
Test control_2threads_p7 034 failed in check_result failed 
Test control_2threads_p7 034 failed in run_test failed 
Test regional_control 035 failed in check_result failed 
Test regional_control 035 failed in run_test failed 
Test regional_noquilt 037 failed in check_result failed 
Test regional_noquilt 037 failed in run_test failed 
Test regional_2threads 038 failed in check_result failed 
Test regional_2threads 038 failed in run_test failed 
Test regional_hafs 039 failed in check_result failed 
Test regional_hafs 039 failed in run_test failed 
Test regional_netcdf_parallel 040 failed in check_result failed 
Test regional_netcdf_parallel 040 failed in run_test failed 
Test regional_RRTMGP 041 failed in check_result failed 
Test regional_RRTMGP 041 failed in run_test failed 
Test fv3_gsd 042 failed in check_result failed 
Test fv3_gsd 042 failed in run_test failed 
Test fv3_rrfs_v1alpha 043 failed in check_result failed 
Test fv3_rrfs_v1alpha 043 failed in run_test failed 
Test fv3_rap 044 failed in check_result failed 
Test fv3_rap 044 failed in run_test failed 
Test fv3_hrrr 045 failed in check_result failed 
Test fv3_hrrr 045 failed in run_test failed 
Test fv3_rrfs_v1beta 046 failed in check_result failed 
Test fv3_rrfs_v1beta 046 failed in run_test failed 
Test control_rrtmgp 047 failed in check_result failed 
Test control_rrtmgp 047 failed in run_test failed 
Test control_rrtmgp_c192 048 failed in check_result failed 
Test control_rrtmgp_c192 048 failed in run_test failed 
Test control_csawmg 049 failed in check_result failed 
Test control_csawmg 049 failed in run_test failed 
Test control_csawmgt 050 failed in check_result failed 
Test control_csawmgt 050 failed in run_test failed 
Test control_flake 051 failed in check_result failed 
Test control_flake 051 failed in run_test failed 
Test control_ras 052 failed in check_result failed 
Test control_ras 052 failed in run_test failed 
Test control_thompson 053 failed in check_result failed 
Test control_thompson 053 failed in run_test failed 
Test control_thompson_no_aero 054 failed in check_result failed 
Test control_thompson_no_aero 054 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 055 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson 055 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 056 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 056 failed in run_test failed 
Test control_wam 057 failed in check_result failed 
Test control_wam 057 failed in run_test failed 
Test control_debug 058 failed in check_result failed 
Test control_debug 058 failed in run_test failed 
Test control_2threads_debug 059 failed in check_result failed 
Test control_2threads_debug 059 failed in run_test failed 
Test control_CubedSphereGrid_debug 060 failed in check_result failed 
Test control_CubedSphereGrid_debug 060 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel_debug 061 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel_debug 061 failed in run_test failed 
Test control_stochy_debug 062 failed in check_result failed 
Test control_stochy_debug 062 failed in run_test failed 
Test control_lndp_debug 063 failed in check_result failed 
Test control_lndp_debug 063 failed in run_test failed 
Test control_rrtmgp_debug 064 failed in check_result failed 
Test control_rrtmgp_debug 064 failed in run_test failed 
Test control_csawmg_debug 065 failed in check_result failed 
Test control_csawmg_debug 065 failed in run_test failed 
Test control_csawmgt_debug 066 failed in check_result failed 
Test control_csawmgt_debug 066 failed in run_test failed 
Test control_ras_debug 067 failed in check_result failed 
Test control_ras_debug 067 failed in run_test failed 
Test control_diag_debug 068 failed in check_result failed 
Test control_diag_debug 068 failed in run_test failed 
Test control_debug_p7 069 failed in check_result failed 
Test control_debug_p7 069 failed in run_test failed 
Test control_thompson_debug 070 failed in check_result failed 
Test control_thompson_debug 070 failed in run_test failed 
Test control_thompson_no_aero_debug 071 failed in check_result failed 
Test control_thompson_no_aero_debug 071 failed in run_test failed 
Test control_thompson_extdiag_debug 072 failed in check_result failed 
Test control_thompson_extdiag_debug 072 failed in run_test failed 
Test regional_debug 073 failed in check_result failed 
Test regional_debug 073 failed in run_test failed 
Test fv3_gsd_debug 074 failed in check_result failed 
Test fv3_gsd_debug 074 failed in run_test failed 
Test fv3_gsd_diag_debug 075 failed in check_result failed 
Test fv3_gsd_diag_debug 075 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 076 failed in check_result failed 
Test fv3_rrfs_v1beta_debug 076 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 077 failed in check_result failed 
Test fv3_rrfs_v1alpha_debug 077 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 078 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 078 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 079 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 079 failed in run_test failed 
Test hafs_regional_atm 080 failed in check_result failed 
Test hafs_regional_atm 080 failed in run_test failed 
Test hafs_regional_atm_ocn 081 failed in check_result failed 
Test hafs_regional_atm_ocn 081 failed in run_test failed 
Test hafs_regional_atm_wav 082 failed in check_result failed 
Test hafs_regional_atm_wav 082 failed in run_test failed 
Test hafs_regional_atm_ocn_wav 083 failed in check_result failed 
Test hafs_regional_atm_ocn_wav 083 failed in run_test failed 
Test hafs_regional_1nest_atm 084 failed in check_result failed 
Test hafs_regional_1nest_atm 084 failed in run_test failed 
Test hafs_regional_telescopic_2nests_atm 085 failed in check_result failed 
Test hafs_regional_telescopic_2nests_atm 085 failed in run_test failed 
Test hafs_global_1nest_atm 086 failed in check_result failed 
Test hafs_global_1nest_atm 086 failed in run_test failed 
Test hafs_global_multiple_4nests_atm 087 failed in check_result failed 
Test hafs_global_multiple_4nests_atm 087 failed in run_test failed 
Test hafs_regional_docn 088 failed in check_result failed 
Test hafs_regional_docn 088 failed in run_test failed 
Test hafs_regional_docn_oisst 089 failed in check_result failed 
Test hafs_regional_docn_oisst 089 failed in run_test failed 
Test hafs_regional_datm_cdeps 090 failed in check_result failed 
Test hafs_regional_datm_cdeps 090 failed in run_test failed 
Test datm_cdeps_control_cfsr 091 failed in check_result failed 
Test datm_cdeps_control_cfsr 091 failed in run_test failed 
Test datm_cdeps_control_gefs 093 failed in check_result failed 
Test datm_cdeps_control_gefs 093 failed in run_test failed 
Test datm_cdeps_stochy_gefs 094 failed in check_result failed 
Test datm_cdeps_stochy_gefs 094 failed in run_test failed 
Test datm_cdeps_bulk_cfsr 095 failed in check_result failed 
Test datm_cdeps_bulk_cfsr 095 failed in run_test failed 
Test datm_cdeps_bulk_gefs 096 failed in check_result failed 
Test datm_cdeps_bulk_gefs 096 failed in run_test failed 
Test datm_cdeps_mx025_cfsr 097 failed in check_result failed 
Test datm_cdeps_mx025_cfsr 097 failed in run_test failed 
Test datm_cdeps_mx025_gefs 098 failed in check_result failed 
Test datm_cdeps_mx025_gefs 098 failed in run_test failed 
Test datm_cdeps_multiple_files_cfsr 099 failed in check_result failed 
Test datm_cdeps_multiple_files_cfsr 099 failed in run_test failed 
Test datm_cdeps_debug_cfsr 100 failed in check_result failed 
Test datm_cdeps_debug_cfsr 100 failed in run_test failed 
Test control_atmwav 101 failed in check_result failed 
Test control_atmwav 101 failed in run_test failed 
Test control_c384gdas_wav 102 failed in check_result failed 
Test control_c384gdas_wav 102 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Submodule pointer for fv3atm is correct (283bd50), `.gitmodules` reverted. Ready to merge.

**Pull request merged**
