### PR TITLE
Outerloopwave

### LINKED ISSUE #1501: Use outerloop wave coupling in gfsv17 test
## Description
Due to the wave model speed, outerloop coupling is necessary for reasonable runtimes of the wave model.  While science testing is still ongoing, one regression test should have outerloop coupling for the wave model. 

## Solution
In combination with the future gfsv17 single regression test, use outerloop wave coupling.  The coupling sequence is from @DeniseWorthen

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR adds the wave component to use the outerloop in the "cpld_control_gfsv17" (intended to build on the test @lisa-bengtsson is adding in #1480 and could be combined with that PR, but wanted to show that the tests passed with this alone).  The coupling sequence and underlying work that made this possible was done by @DeniseWorthen, this is just turning it on in a test. 

This PR should not change answers to existing tests, but does add a test, so a baseline for that test should be created. 

### Issue(s) addressed
- fixes #1501

## Testing

Created a baseline and compared new test to the baseline.  Ran "./opnReqTest -n cpld_control_gfsv17 -c dbg,dcp,rst,std,thr" on hera. 

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

None

Do PRs in upstream repositories need to be merged first?
No

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Is the added test meant to be the same test that @lisa-bengtsson  is working on in PR #1480?

**Comment by JessicaMeixner-NOAA** [comment]
> Is the added test meant to be the same test that @lisa-bengtsson is working on in PR #1480?

Yes it is. I can just make this to a PR to her fork, but since it's different aspects, incase there were issues with anything I wanted to do the testing separately first.  Also, if there are any changes to any naming conventions anyone would like to see, I'm happy to make those changes as well.

**Comment by DeniseWorthen** [comment]
Thanks, so there won't be an outer-loop version and an inner loop version of the cpld_control_gfsv17. Is that right?  

Not a big fan of the label "outwav" but not sure what else to choose.

Also---doesn't this require a new mod-def file, if the wave model is in the outer loop?

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen Correct, just an outerloop version (no additional inner loop version). 

I'm open to other suggestions, couldn't think of a great name myself either obviously.  

While we could have a new mod_def file to have a larger time-step internally, it's not required either.

**Comment by JessicaMeixner-NOAA** [comment]
Closing as this is include in PR #1480

**Pull request closed without merging**
