### PR TITLE
(1) update MOM6 to its main 20220729 commit (GFDL-candidate-20220721) (2) cap update: supporting traditional and ESMF-managed threading

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description
MOM6 main repo is updated on 20220729, need to make corresponding updating in UFS.
No answer change is expected.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes UFS #1357 
- fixes MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/98

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by jiandewang** [comment]
@junwang-noaa since NCAR reported that there is no issue in their system for the nuopc cap code modification, I added your MOM6 cap code change (https://github.com/NOAA-EMC/MOM6/pull/100) in this PR.

**Comment by jkbk2004** [comment]
@jiandewang We are going to merge in #1354 now since it doesn't need any test. Then, we can start working on this PR.

**Comment by jiandewang** [comment]
@jkbk2004 sounds good, my branch is up to date.

**Comment by jiandewang** [comment]
@jkbk2004 I see #1354 is closing to be finalized, but not sure when we will do the merging. Note I will be out of home 6-9:30pm today.

**Comment by jiandewang** [comment]
@jkbk2004 I just updated my branch. I think you cat start the run.

**Comment by jkbk2004** [comment]
@jiandewang sure! only mom6 unit test and file parser update. no change on baseline, right?

**Comment by jiandewang** [comment]
Yes no BL change

**Review by binli2337 — APPROVED** [review]
Looks good. Thanks!

**Comment by BrianCurtis-NOAA** [comment]
There are some acorn issues that will take a bit to look through. Don't block merge please.

**Comment by jkbk2004** [comment]
> There are some acorn issues that will take a bit to look through. Don't block merge please.

Sure! we may go ahead to merge in a bit. I will add you to approve the PR.

**Comment by jkbk2004** [comment]
@jiandewang Yeah, go ahead to update mom6 submodule pointer and revert .gitmodules.

**Review by BrianCurtis-NOAA — APPROVED** [review]
Approving now as my extended weekend starts now. Have a great weekend everyone.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jiandewang** [comment]
MOM6 submodule reverted.

**Comment by jiandewang** [comment]
thanks for everybody's collaboration.

**Pull request merged**
