### PR TITLE
Use threading to speed up MERRA2 aerosol interpolation and NoahMP initialization

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR only updates the submodule pointer for ccpp-physics for the changes described in https://github.com/NCAR/ccpp-physics/pull/605.

### Issue(s) addressed

Fixes https://github.com/NCAR/ccpp-physics/issues/608

## Testing

The updated code was tested against the existing code with one or more OpenMP threads, and the results are b4b identical. Timing improves for the aerosol interpolation step for large setups, for example for C768L127 I see a factor of 2 speedup for the `aerinterpol` step in the `time_vary` group when using four threads. The difference is not gigantic over all, but every little bit helps.

Regression tests will be run against the existing baselines on all tier-1 platforms:

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/605
https://github.com/NOAA-EMC/fv3atm/pull/268
https://github.com/ufs-community/ufs-weather-model/pull/507

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@climbfuji Does this PR requires new/updated input data? Also does it change results?

**Comment by climbfuji** [comment]
> @climbfuji Does this PR requires new/updated input data? Also does it change results?

No, it doesn't. I didn't add the label, but said so in the description above:
> The updated code was tested against the existing code with one or more OpenMP threads, and the results are b4b identical.

**Comment by climbfuji** [comment]
> @climbfuji Does this PR requires new/updated input data? Also does it change results?

No, it doesn't. I didn't add the label, but said so in the description above:
> The updated code was tested against the existing code with one or more OpenMP threads, and the results are b4b identical.

**Comment by junwang-noaa** [comment]
Thanks. I was confused about the checkbox "If new or updated input data is required by this PR, it is clearly stated in the text of the PR."

**Review by junwang-noaa — APPROVED** [review]
Need to update to the develop branch before the commit process starts

**Comment by climbfuji** [comment]
This was merged as part of https://github.com/ufs-community/ufs-weather-model/pull/520, but didn't get flagged as merged automatically because we do squashed merges in the ufs-weather-model.

**Pull request closed without merging**
