### PR TITLE
Remove WCOSS (Dell and Cray) support from regression tests; Ignore checksum option and performance with (1,1) io layout in FV3

### LINKED ISSUE #1295: Remove WCOSS (Dell and Cray) support from regression tests
WCOSS (dell and Cray) will be decommissioned by the end of this month. We stopped running regression tests on these two machines.
All WCOSS specific code in regression test scripts and configuration files should be removed.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Remove WCOSS specific code from regression test scripts and configuration files.
Update FV3 (combining with #1275)

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1295

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss2.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

N/A

### CODE REVIEW

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA can you also remove the dell/cray related files under modulefiles/ and cmake/?

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @junwang-noaa all RT tests pass. I think we can start merging. I noticed there is an issue on run-CI. I guess modulefiles. Sounds like we need to hold run-ci for a while until epic side catch up CI portion. We can merge in fv3atm 556 first.

**Comment by junwang-noaa** [comment]
@jkbk2004 Do you have a timeline when EPIC will take over CI?

**Comment by jkbk2004** [comment]
> @jkbk2004 Do you have a timeline when EPIC will take over CI?

@junwang-noaa I am willing to check and update the scripts in the ci directory. But epic will prefer to add the option of the jenkins-ci label. 2 weeks (epic's single sprint interval) is a bit tight. But I think we can make a progress in 4 weeks (2 sprints). I need to check docker containers and think about how to pull in input files to jenkins-based aws.

**Comment by junwang-noaa** [comment]
From the commit queue, I think 4 weeks might be too long.

**Comment by jkbk2004** [comment]
> From the commit queue, I think 4 weeks might be too long.

@junwang-noaa I agree. Then, I have to speed up to get my hands on ci scripts. I think I should be able to test and play the run-ci with my fork branch. If I get stuck, I will call Minsuk for a few questions.

**Review by jkbk2004 — APPROVED** [review]

**Comment by DusanJovic-NOAA** [comment]
Ready for merge.

**Pull request merged**
