### PR TITLE
Add support for optional arguments in ccpp physics and framework AND add end of run restart functionality to MOM6 (was #2286)

### LINKED ISSUE #2285: add writing end of run restart file in MOM6
currently MOM6 nuopc_cap lack the capability to write out end of restart file if restart_n is not a factor of the total run length. This updating will allow the writing of end of run restart file regardless of restart_n setting. Thanks for Daniel Sarmiento's work.

### PR DESCRIPTION
**Pull request by climbfuji**
## Commit Queue Requirements:
- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
    - [x] I couldn't - `test_changes.list` was empty from previous PR, and since my PRs don't change results I can't commit an unmodified file (see https://github.com/ufs-community/ufs-weather-model/pull/2205/commits/5588f99715cf16d9c7cb8d35314ffb4e9dd0c00a)
---
## Description:

This set of PRs adds support for optional arguments in CCPP physics schemes to the metadata and framework, with related changes in fv3atm, gfdl_atmos_cubed_sphere, and stochastic_physics.

From 2286:
This PR allows the user to create restart files at the end of a run in MOM using the write_restart_at_endofrun configuration option in CMEPS.

### Commit Message:
```
* UFSWM - Add support for optional arguments in ccpp physics and framework 
  * FV3 - [Add support for optional arguments in ccpp physics and framework](https://github.com/NOAA-EMC/fv3atm/pull/807#top)
    * ccpp-physics - Introduce optional arguments in ccpp schemes and metadata
    * ccpp-framework - Add support (and tests) for optional arguments in ccpp_prebuild
    * atmos_cubed_sphere - Set cdata%thrd_cnt in driver/fvGFS/atmosphere.F90
  * MOM6 - Add end of run restart functionality to MOM6
  * stochastic_physics - Add optional attribute for variables where necessary
```

### Priority:

* High: Timeline - my transition to NRL (selfish, I know, sorry) and another large set of PRs (conversion to contiguous arrays) waiting for these changes

### UFSWM Issues:
* Closes #2285 

### Sub component Pull Requests:

This is part of a large set of PRs:
- https://github.com/NOAA-EMC/fv3atm/pull/807
- https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/338
- https://github.com/NCAR/ccpp-framework/pull/552 
- https://github.com/NCAR/ccpp-framework/pull/556 (can be scheduled and merged anytime beforehand)
- https://github.com/ufs-community/ccpp-physics/pull/189
- https://github.com/NOAA-PSL/stochastic_physics/pull/79
- MOM6: PR https://github.com/NOAA-EMC/MOM6/pull/133 (PR#2286)

### UFSWM Blocking Dependencies:
* None.

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes - **everything is bit-for-bit identical!**

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by climbfuji** [comment]
@jkbk2004 This PR and sub-component PRs are finally ready for review. Everything is b4b identical!

**Comment by jkbk2004** [comment]
@climbfuji sounds good! we will try to schedule to commit sometime next week.

**Comment by FernandoAndrade-NOAA** [comment]
Hi @climbfuji, this PR is next for testing, please go ahead and sync / reesolve merge conflicts. Please also merge in changes from #2286, there should be no baseline changes from that PR as well.

**Comment by climbfuji** [comment]
Well, there are several merge conflicts in ccpp-physics. This will take a bit to resolve :-(

**Comment by climbfuji** [comment]
I think I got it - let me run a quick compile of all suites on my mac

**Comment by climbfuji** [comment]
@FernandoAndrade-NOAA I think this is good now. It compiled successfully on my macOS. I didn't run any tests on Hera after merging in the latest changes from develop and @jiandewang's PR.

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA @zach1221  FYI getting started with RTs for this PR.

**Comment by jiandewang** [comment]
@climbfuji can you modify tilte for this PR to add "Add end of run restart functionality to MOM6 #2286" ? Thanks

**Comment by climbfuji** [comment]
> @climbfuji can you modify tilte for this PR to add "Add end of run restart functionality to MOM6 #2286" ? Thanks

Of course, done!

**Comment by jiandewang** [comment]
> > @climbfuji can you modify tilte for this PR to add "Add end of run restart functionality to MOM6 #2286" ? Thanks
> 
> Of course, done!

thanks. You modified the title as fast as lighting

**Comment by BrianCurtis-NOAA** [comment]
@FernandoAndrade-NOAA can you bring in the PR information from the combined PR into this one?

**Comment by FernandoAndrade-NOAA** [comment]
Ok, we should be all set to continue the merge process, I'll leave a note on the component PRs.

**Comment by jiandewang** [comment]
> Ok, we should be all set to continue the merge process, I'll leave a note on the component PRs.

time ot merge MOM6 ?

**Comment by FernandoAndrade-NOAA** [comment]
> > Ok, we should be all set to continue the merge process, I'll leave a note on the component PRs.
> 
> time ot merge MOM6 ?

Yes please go ahead and merge in MOM6, we should be all set there.

**Comment by jiandewang** [comment]
just merged MOM6. Hash # b32aea7bf3

**Comment by climbfuji** [comment]
fv3atm should be ready to merge, please check

**Comment by FernandoAndrade-NOAA** [comment]
> fv3atm should be ready to merge, please check

All component PRs merged in, please go ahead and revert gitmodules / update hashes, thanks!

**Comment by climbfuji** [comment]
Thanks for shepherding this PR set through - should be good to go

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
