### PR TITLE
add SPP support to G-F deep convection

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

1. add stochastic parameterization perturbations support to Grell-Freitas deep convection parameterization by passing stochastic patterns to mass transport, vertical mass flux profile and closures
2. fix reproducibility issue in G-F deep convection at high resolutions (ichoice option switched to 0)

### Subcomponent Pull Requests

fv3atm:
- Depends on https://github.com/NOAA-EMC/fv3atm/pull/688

ccpp-physics:
- Depends on https://github.com/ufs-community/ccpp-physics/pull/98

stochastic_physics:
- Depends on https://github.com/NOAA-PSL/stochastic_physics/pull/63

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [x] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by JiliDong-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12500186/RegressionTests_hera.log)
RT on Hera log here. All passed successfully.

**Comment by JiliDong-NOAA** [comment]
stochastic physics PR has been approved

**Comment by jkbk2004** [comment]
> stochastic physics PR has been approved

@JiliDong-NOAA thanks for the note! #1823 is on-going. We should be able to schedule to commit this PR late this afternoon or tomorrow after merging #1823.

**Comment by zach1221** [comment]
@JiliDong-NOAA PR#1823 is merged. Can you please sync up your branch? Then we can begin testing.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA PR#1823 is merged. Can you please sync up your branch? Then we can begin testing.

done.

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins ci logs attached, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1876#1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/12556672/ufs-weather-model.ort-docker-pipeline.PR-1876.1.Console.Jenkins.txt)

**Comment by FernandoAndrade-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Job: RT
[RT] Repo location: /lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1483594336/20230908073124/ufs-weather-model
Please make changes and add the following label back: jet-RT

**Comment by BrianCurtis-NOAA** [comment]
No Acorn today. Please skip.

**Comment by zach1221** [comment]
> No Acorn today. Please skip.

Thanks Brian.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, other machines have finished their testing. This should be ready to continue the merge process, I'll leave a note in the sub PRs.

**Comment by dustinswales** [comment]
@FernandoAndrade-NOAA Physics merged

**Comment by jkbk2004** [comment]
@JiliDong-NOAA FV3 pr was merged. Can you update hash and revert change in gitmodules? correct hash is https://github.com/NOAA-EMC/fv3atm/commit/9b5825b7a6c0c07a3d936d0222917677209a07f0

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA FV3 pr was merged. Can you update hash and revert change in gitmodules? correct hash is [NOAA-EMC/fv3atm@9b5825b](https://github.com/NOAA-EMC/fv3atm/commit/9b5825b7a6c0c07a3d936d0222917677209a07f0)

FV3 updated.

**Comment by zach1221** [comment]
@JiliDong-NOAA stochastic physics PR has been merged. Please update submodule pointer and revert change in .gitmodule url.
hash: 1ee7cc9a8b5d5733b391127ca31059b497ecdea8

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA stochastic physics PR has been merged. Please update submodule pointer and revert change in .gitmodule url. hash: 1ee7cc9a8b5d5733b391127ca31059b497ecdea8

done.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
