### PR TITLE
Smoke, dust, and MYNN updates

### LINKED ISSUE #1659: issue for RRFS-SD upgrade
1. The FV3_HRRR and FV3_HRRR_smoke are unified as one suite of FV3_HRRR. If the input namelist option rrfs_sd is false, it runs as the standard alone RRFS. IF rrfs_sd is true, it runs with smoke and dust for RRFS-SD. The meteorological fields are identical between the runs with rrfs_sd=T or rrfs_sd=F.

2. There are three tracers of smoke, dust (fine dust), coarsepm (mainly from coarse dust emission) in RRFS-SD. Smoke and fine dust could be used for PM2.5, and coarsepm could be used for PM10 diagnostics.

3. There is just one field_table, which contains smoke, dust and coarsepm tracers. If the input namelist option rrfs_sd is false, it runs as the standard alone RRFS. IF rrfs_sd is true, it runs with smoke, find dust and coarsepm for RRFS-SD. The meteorological fields are identical between the runs with rrfs_sd=T or rrfs_sd=F.

4. The dry deposition velocity of smoke, fine dust and coarsepm is an input variable to MYNN-EDMF PBL.

5. The smoke and dust codes are significantly cleaned and improved, and significantly improved the model integration speed. According to the test on Hera and WCOSS2, the additional computing cost of RRFS-SD is less than 5% than atmospheric only RRFS.

6. An update of smoke/dust direct and indirect feedback.

7. Emission bugfix and clean-up in FENGSHA dust scheme. The issue of unrealistic strong dust emission was resolved.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description
RRFS-Smoke is improved, cleaned, and rebranded as RRFS-SD. Now with smoke, dust, and coarsepm tracer handling, it adds dry deposition velocity to MYNN-EDMF, updates the smoke/dust direct and indirect feedback. There are bug fixes: switch to non-aerosol-aware in the GF scheme and correct emission bug in FENGSHA. RRFS CONUS 13km tests all run smoke, and there is just one field_table.

These changes are from @haiqinli and @joeolson42, except the regression tests, which are from me.

### Input data additions/changes
- [x] There will be new input data. 
- [x] Input data will be updated. 

Input data is here:

/scratch2/BMC/wrfruc/Samuel.Trahan/gsl-pr/HaiqinPR/RT/NEMSfv3gfs/input-data-20221101

Updates:

FV3_aeroclim/ - some aerosol climatology data
FV3_input_data_conus13km/INPUT/ - a few new files

### Anticipated changes to regression tests:
- [x] Changes are expected to the following tests: smoke tests, and anything that #1636 changes

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):

This PR already includes #1636 since it requires those changes.

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- closes https://github.com/ufs-community/ufs-weather-model/issues/1659
- waiting on https://github.com/ufs-community/ccpp-physics/pull/54
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/635

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [x] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
I just updated this to the top of develop, and merged changes from @haiqinli to address reviewer comments in the submodules. I'm retesting now.

**Comment by grantfirl** [comment]
For RTs, the following tests are expected to fail from #1636:

Expected test failures for Hera-Intel:
regional_control 042 failed in check_result
regional_decomp 044 failed in check_result
regional_2threads 045 failed in check_result
regional_noquilt 046 failed in check_result
regional_netcdf_parallel 047 failed in check_result
regional_2dwrtdecomp 048 failed in check_result
regional_wofs 049 failed in check_result
rap_control 050 failed in check_result
regional_spp_sppt_shum_skeb 051 failed in check_result
rap_decomp 052 failed in check_result
rap_2threads 053 failed in check_result
rap_sfcdiff 055 failed in check_result
rap_sfcdiff_decomp 056 failed in check_result
hrrr_control 058 failed in check_result
hrrr_control_decomp 059 failed in check_result
hrrr_control_2threads 060 failed in check_result
rrfs_v1beta 062 failed in check_result
rrfs_v1nssl 063 failed in check_result
rrfs_v1nssl_nohailnoccn 064 failed in check_result
rrfs_conus13km_hrrr_warm 065 failed in check_result
rrfs_smoke_conus13km_hrrr_warm 066 failed in check_result
rrfs_conus13km_radar_tten_warm 067 failed in check_result
rrfs_conus13km_hrrr_warm_2threads 068 failed in check_result
rrfs_conus13km_radar_tten_warm_2threads 069 failed in check_result
regional_control_faster 075 failed in check_result
rrfs_conus13km_hrrr_warm_debug 076 failed in check_result
rrfs_conus13km_radar_tten_warm_debug 077 failed in check_result
regional_debug 087 failed in check_result
rap_control_debug 088 failed in check_result
hrrr_control_debug 089 failed in check_result
rap_unified_drag_suite_debug 090 failed in check_result
rap_diag_debug 091 failed in check_result
rap_cires_ugwp_debug 092 failed in check_result
rap_unified_ugwp_debug 093 failed in check_result
rap_lndp_debug 094 failed in check_result
rap_flake_debug 095 failed in check_result
rap_progcld_thompson_debug 096 failed in check_result
rap_noah_debug 097 failed in check_result
rap_sfcdiff_debug 098 failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug 099 failed in check_result
rrfs_v1beta_debug 100 failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32 102 failed in check_result
rap_control_dyn32_phy32 103 failed in check_result
hrrr_control_dyn32_phy32 104 failed in check_result
rap_2threads_dyn32_phy32 105 failed in check_result
hrrr_control_2threads_dyn32_phy32 106 failed in check_result
hrrr_control_decomp_dyn32_phy32 107 failed in check_result
rap_control_dyn64_phy32 110 failed in check_result
rap_control_debug_dyn32_phy32 111 failed in check_result
hrrr_control_debug_dyn32_phy32 112 failed in check_result
rap_control_dyn64_phy32_debug 113 failed in check_result

Expected failures for Hera-Gnu:
rap_control 005 failed in check_result
rap_decomp 006 failed in check_result
rap_2threads 007 failed in check_result
rap_sfcdiff 009 failed in check_result
rap_sfcdiff_decomp 010 failed in check_result
hrrr_control 012 failed in check_result
hrrr_control_2threads 013 failed in check_result
hrrr_control_decomp 014 failed in check_result
rrfs_v1beta 016 failed in check_result
rrfs_conus13km_hrrr_warm 017 failed in check_result
rrfs_smoke_conus13km_hrrr_warm 018 failed in check_result
rrfs_conus13km_radar_tten_warm 019 failed in check_result
rrfs_conus13km_radar_tten_warm_2threads 020 failed in check_result
regional_debug 022 failed in check_result
rap_control_debug 023 failed in check_result
hrrr_control_debug 024 failed in check_result
rap_diag_debug 025 failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug 026 failed in check_result
rap_progcld_thompson_debug 027 failed in check_result
rrfs_v1beta_debug 028 failed in check_result
rrfs_conus13km_hrrr_warm_debug 032 failed in check_result
rrfs_conus13km_radar_tten_warm_debug 033 failed in check_result
rap_control_dyn32_phy32 035 failed in check_result
hrrr_control_dyn32_phy32 036 failed in check_result
rap_2threads_dyn32_phy32 037 failed in check_result
hrrr_control_2threads_dyn32_phy32 038 failed in check_result
hrrr_control_decomp_dyn32_phy32 039 failed in check_result
rap_control_dyn64_phy32 042 failed in check_result
rap_control_debug_dyn32_phy32 043 failed in check_result
hrrr_control_debug_dyn32_phy32 044 failed in check_result
rap_control_dyn64_phy32_debug 045 failed in check_result

**Comment by grantfirl** [comment]
See #1636 for uploaded RT logs on Hera/Intel/GNU for existing tests and one uploaded log showing a successful reproduction of the newly added control_p8_mynn test.

**Comment by SamuelTrahanNOAA** [comment]
@haiqinli found two important fields were missing from the new rrfs_smoke regression tests, so I've added them and I'm double-checking that the jobs reproduce those fields under 2threads and debug variants.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA Can you go ahead to attach a RT log if you have one. We can start working working on.

**Comment by SamuelTrahanNOAA** [comment]
This PR is ready for final testing and merge. My final round of testing is complete, and @haiqinli has examined the test output. Everything looks in order.

**Comment by jkbk2004** [comment]
I will add new BL date.

**Comment by SamuelTrahanNOAA** [comment]
> Can you go ahead to attach a RT log if you have one. We can start working working on.

I put in the hera.intel log. Unfortunately, I clobbered my hera.gnu log. I can rerun the tests, but it'll take 2 hours or more.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I will start rsync the new input files across RDHPCS.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - You need to copy the new input data everywhere before running the tests.

The hera RTPWD path is hard-coded to the area with the new data. That'll need to be corrected once you have the data in the right place.

**Comment by jkbk2004** [comment]
I updated /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101 with new input files

**Comment by SamuelTrahanNOAA** [comment]
I reverted the hard-coded path in rt.sh. That script should match develop now.

**Comment by jkbk2004** [comment]
Jenkins pipeline is under migration. we will skip Jenkin-ci.

**Comment by zach1221** [comment]
Jenkins is down currently, so I cannot run jenkins-ci. However, ORTs std,bit,dbg,dcp,mpi,thr,rst did pass against the new control_p8_mynn case when I ran manually on Hera.

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1277691005/20230324194527/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by SamuelTrahanNOAA** [comment]
I can't access the directory with the failing run on orion (`/work/noaa/epic-ps/jongkim/autort/pr/1277691005/20230324194527/ufs-weather-model`). Can someone tell me what failed?

**Comment by jkbk2004** [comment]
> I can't access the directory with the failing run on orion (`/work/noaa/epic-ps/jongkim/autort/pr/1277691005/20230324194527/ufs-weather-model`). Can someone tell me what failed?

Sounds like git clone failure on Orion. I think git/2.28 version issue spreading. Let me try to manually run and see how it goes.

**Comment by zach1221** [comment]
Good morning, @SamuelTrahanNOAA . I think we're ready to start merge process. Are you able to merge your ccpp PR?

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Comment by SamuelTrahanNOAA** [comment]
> Are you able to merge your ccpp PR?

No, but if you post a message on that PR's page asking for it to be merged, someone is likely to respond soon.

**Comment by jkbk2004** [comment]
I left a message in ccpp pr.

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA Since we have the threads/decomp/restart/debug for the tests/tests/rrfs_smoke_conus13km_hrrr_warm test, we may not also need threads/decomp tests for tests/tests/rrfs_smoke_conus13km_hrrr_warm_debug. Maybe this can be cleaned up later? Thanks

**Comment by SamuelTrahanNOAA** [comment]
> Since we have the threads/decomp/restart/debug for the tests/tests/rrfs_smoke_conus13km_hrrr_warm test, we may not also need threads/decomp tests for tests/tests/rrfs_smoke_conus13km_hrrr_warm_debug. Maybe this can be cleaned up later? Thanks

I want to leave the extra variants for a while, for investigating the reproducibility issues in the RRFS. That's why I put them in.

**Comment by junwang-noaa** [comment]
I see. So the decomp and restart tests do not work at this time. We expect additional PRs to fix the issue.

**Comment by SamuelTrahanNOAA** [comment]
> I see. So the decomp and restart tests do not work at this time. We expect additional PRs to fix the issue.

They're operational requirements, so they have to be fixed eventually.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA fv3 pr was merged. We can merge the pr with submodule pointer update and reverting change  in gitmodules.

**Comment by SamuelTrahanNOAA** [comment]
Somehow I dismissed @DusanJovic-NOAA's stale review. I don't recall doing that... was it automatic?

**Comment by SamuelTrahanNOAA** [comment]
The .gitmodules matches develop, and FV3 points to the NOAA-EMC fv3atm develop.

**Comment by grantfirl** [comment]
> Somehow I dismissed @DusanJovic-NOAA's stale review. I don't recall doing that... was it automatic?

Yep, it's automatic when you push a new commit after a review approval. Perhaps there is a setting somewhere...

**Review by jkbk2004 — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
> > Somehow I dismissed @DusanJovic-NOAA's stale review. I don't recall doing that... was it automatic?
> Yep, it's automatic when you push a new commit after a review approval. Perhaps there is a setting somewhere...

@SamuelTrahanNOAA This is correct. It's to ensure the latest code changes are getting reviewed. EPIC can change it in the repo settings as they see fit.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
