### PR TITLE
Remove legacy gnumake build from fv3atm and NEMS, remove legacy Python 2.7 support, rename v16beta to v16 and RT updates

### LINKED ISSUE #373: Remove legacy gnumake build from development branches
## Description

Remove gnumake build from development branches.

We identified that the legacy gnumake build is no longer required for the development branches. The last application still using the gnumake build is HAFS, they are using their own fork/branch and a plan to transition to cmake is in place.

## Solution

Remove all gnumake related files from all submodules that no longer need it (makefiles, dependency makers, ...). Clean up NEMS repository (incl. NCEPLIBS-pyprodutils).

## Alternatives

Keep carrying around legacy systems that are not tested and likely don't work anymore.

### LINKED ISSUE #376: Remove support for legacy Python 2.7
## Description
The top-level `CMakeLists.txt` is still looking for Python 2.7 if Python 3 cannot be found.

## Solution
Make sure that every system that we are running on (tier-1 and tier-2) has Python 3 (they better do) - update the modulefiles if necessary. Remove check for Python 2.7 from top-level `CMakeLists.txt`, only look for Python 3.

## Alternatives
Keep supporting Python 2, even though it is no longer developed and support will end soon.

## Related to
See https://github.com/ufs-community/ufs-weather-model/pull/357#discussion_r556843485

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Changes in this PR:
- Update submodules fv3atm and NEMS to remove legacy gnumake build.
- Remove support for Python 2.7 from top-level CMakeLists.txt.
- Rename v16beta to v16 in regression tests and suite definition files
- Reduce forecast length of test fv3_ccpp_gfs_v16_RRTMGP_c192L127 from 24h to 12h (from @junwang-noaa)
- Update path to input directory in `tests/fv3_conf/ccpp_regional_run.IN` (from @junwang-noaa)
- Remove `export CCPP_LIB_DIR=...` from all regression tests (from @DusanJovic-NOAA)

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/373.
Fixes https://github.com/ufs-community/ufs-weather-model/issues/376.

## Testing

Regression testing done on all tier-1 platforms.

No updates of the input data.

Regression test results will change due to the other updates in this PR (not the gnumake removal).

## Dependencies

https://github.com/NOAA-EMC/fv3atm/pull/234
https://github.com/NOAA-EMC/NEMS/pull/89
https://github.com/ufs-community/ufs-weather-model/pull/384

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
Is the PR ready for RT?

**Review by MinsukJi-NOAA — COMMENTED** [review]
It seems that Jet and Cheyenne are still using Python 2.7.
https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L286
https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L305

**Comment by climbfuji** [comment]
> It seems that Jet and Cheyenne are still using Python 2.7.
> 
> https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L286
> 
> 
> https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L305

Good point - I will need to fix those and update the PR accordingly.

**Comment by climbfuji** [comment]
> > It seems that Jet and Cheyenne are still using Python 2.7.
> > https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L286
> > 
> > https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L305
> 
> Good point - I will need to fix those and update the PR accordingly.

Turns out that this would just work fine, even though the cmake build is now looking for python 3 only.  But since the PR says "remove legacy Python 2.7 support", I made the changes in `rt.sh`. Will push the commit shortly, only affects the `jet` and `cheyenne` sections, none of the others, and works fine on both systems it seems.

**Comment by climbfuji** [comment]
> > > It seems that Jet and Cheyenne are still using Python 2.7.
> > > https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L286
> > > 
> > > https://github.com/ufs-community/ufs-weather-model/blob/6a4c30762764637c361b310645a4fb3abd93feca/tests/rt.sh#L305
> > 
> > 
> > Good point - I will need to fix those and update the PR accordingly.
> 
> Turns out that this would just work fine, even though the cmake build is now looking for python 3 only. But since the PR says "remove legacy Python 2.7 support", I made the changes in `rt.sh`. Will push the commit shortly, only affects the `jet` and `cheyenne` sections, none of the others, and works fine on both systems it seems.

Done, please check commit https://github.com/ufs-community/ufs-weather-model/pull/384/commits/cbe3d69e64af931faa92e1946d8fc814151686bf.

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by climbfuji** [comment]
jet is such a mess at the moment. I could create the baseline, but verifying against it fails because of faulty nodes, file system mounts, ... - let's merge this PR once the CI tests passed. If I manage to run `rt.sh` during the day, I will attach the logs as a comment to this PR.

**Comment by junwang-noaa** [comment]
Thanks for running RT on jet, that is fine to me.

**Comment by climbfuji** [comment]
CI tests passed. I am now pushing the jet.intel log (finally successful) with "skip-ci" - this PR is ready to merge.

**Pull request merged**
