### PR TITLE
fix grv function used by NST

### LINKED ISSUE #130: grv function used by NST assumes wrong argument
# Description

The NST model uses the function ``grv`` to give the latitude dependence of gravity. 

https://github.com/ufs-community/ccpp-physics/blob/c2ec9e5e165dac07a991424bd22bb0667cf32017/physics/module_nst_water_prop.f90#L485-L500

This function assumes the argument is the latitude but the value actually used by ``sfc_nst.f`` is the sin(latitude).

https://github.com/ufs-community/ccpp-physics/blob/c2ec9e5e165dac07a991424bd22bb0667cf32017/physics/sfc_nst.f#L372

## Additional Context

See [gravity forumla 1980](http://www-gpsg.mit.edu/~tah/12.221_2005/grs80_corr.pdf) for the definition of gravity=f(latitude) used in this module.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hercules.log](https://github.com/ufs-community/ufs-weather-model/files/13366446/RegressionTests_hercules.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Fixes the argument used by the ``grv`` function. 

### Associated UFSWM Issue to close

- fixes https://github.com/ufs-community/ccpp-physics/issues/130

### Subcomponent Pull Requests

- depends on https://github.com/ufs-community/ccpp-physics/pull/131
- depends on https://github.com/NOAA-EMC/fv3atm/pull/722

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

Few tests pass. They include ``hrrr`` tests, ``datm_cdeps`` tests and some ``hafs`` tests. 

Three tests timed out on the initial test, but ran successfully when retested. The three tests which timed-out were

```
Test 115 conus13km_debug_intel FAIL
Test 129 hafs_regional_specified_moving_1nest_atm_intel FAIL
Test 133 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL
```

The following tests failed with non-B4B comparisons.
```
Test 001 cpld_control_p8_mixedmode_intel FAIL
Test 002 cpld_control_p8_intel FAIL
Test 004 cpld_control_qr_p8_intel FAIL
Test 006 cpld_2threads_p8_intel FAIL
Test 007 cpld_decomp_p8_intel FAIL
Test 008 cpld_mpi_p8_intel FAIL
Test 009 cpld_control_ciceC_p8_intel FAIL
Test 010 cpld_control_c192_p8_intel FAIL
Test 012 cpld_bmark_p8_intel FAIL
Test 014 cpld_control_noaero_p8_intel FAIL
Test 015 cpld_control_nowave_noaero_p8_intel FAIL
Test 016 cpld_debug_p8_intel FAIL
Test 017 cpld_debug_noaero_p8_intel FAIL
Test 019 cpld_control_c48_intel FAIL
Test 020 cpld_control_p8_faster_intel FAIL
Test 021 control_flake_intel FAIL
Test 022 control_CubedSphereGrid_intel FAIL
Test 023 control_CubedSphereGrid_parallel_intel FAIL
Test 024 control_latlon_intel FAIL
Test 025 control_wrtGauss_netcdf_parallel_intel FAIL
Test 026 control_c48_intel FAIL
Test 027 control_c192_intel FAIL
Test 028 control_c384_intel FAIL
Test 029 control_c384gdas_intel FAIL
Test 030 control_stochy_intel FAIL
Test 032 control_lndp_intel FAIL
Test 033 control_iovr4_intel FAIL
Test 034 control_iovr5_intel FAIL
Test 035 control_p8_intel FAIL
Test 036 control_p8_ugwpv1_intel FAIL
Test 038 control_noqr_p8_intel FAIL
Test 040 control_decomp_p8_intel FAIL
Test 041 control_2threads_p8_intel FAIL
Test 042 control_p8_lndp_intel FAIL
Test 043 control_p8_rrtmgp_intel FAIL
Test 044 control_p8_mynn_intel FAIL
Test 045 merra2_thompson_intel FAIL
Test 046 regional_control_intel FAIL
Test 048 regional_decomp_intel FAIL
Test 049 regional_2threads_intel FAIL
Test 050 regional_noquilt_intel FAIL
Test 051 regional_netcdf_parallel_intel FAIL
Test 052 regional_2dwrtdecomp_intel FAIL
Test 053 regional_wofs_intel FAIL
Test 054 rap_control_intel FAIL
Test 056 rap_decomp_intel FAIL
Test 057 rap_2threads_intel FAIL
Test 059 rap_sfcdiff_intel FAIL
Test 060 rap_sfcdiff_decomp_intel FAIL
Test 066 rrfs_v1beta_intel FAIL
Test 067 rrfs_v1nssl_intel FAIL
Test 068 rrfs_v1nssl_nohailnoccn_intel FAIL
Test 069 control_csawmg_intel FAIL
Test 070 control_csawmgt_intel FAIL
Test 071 control_ras_intel FAIL
Test 073 control_p8_faster_intel FAIL
Test 074 regional_control_faster_intel FAIL
Test 075 control_CubedSphereGrid_debug_intel FAIL
Test 076 control_wrtGauss_netcdf_parallel_debug_intel FAIL
Test 077 control_stochy_debug_intel FAIL
Test 078 control_lndp_debug_intel FAIL
Test 079 control_csawmg_debug_intel FAIL
Test 080 control_csawmgt_debug_intel FAIL
Test 081 control_ras_debug_intel FAIL
Test 082 control_diag_debug_intel FAIL
Test 083 control_debug_p8_intel FAIL
Test 084 regional_debug_intel FAIL
Test 085 rap_control_debug_intel FAIL
Test 089 rap_unified_drag_suite_debug_intel FAIL
Test 090 rap_diag_debug_intel FAIL
Test 091 rap_cires_ugwp_debug_intel FAIL
Test 092 rap_unified_ugwp_debug_intel FAIL
Test 093 rap_lndp_debug_intel FAIL
Test 094 rap_progcld_thompson_debug_intel FAIL
Test 095 rap_noah_debug_intel FAIL
Test 096 rap_sfcdiff_debug_intel FAIL
Test 097 rap_noah_sfcdiff_cires_ugwp_debug_intel FAIL
Test 098 rrfs_v1beta_debug_intel FAIL
Test 099 rap_clm_lake_debug_intel FAIL
Test 100 rap_flake_debug_intel FAIL
Test 102 rap_control_dyn32_phy32_intel FAIL
Test 104 rap_2threads_dyn32_phy32_intel FAIL
Test 112 rap_control_dyn64_phy32_intel FAIL
Test 113 rap_control_debug_dyn32_phy32_intel FAIL
Test 115 conus13km_debug_intel FAIL
Test 119 rap_control_dyn64_phy32_debug_intel FAIL
Test 120 hafs_regional_atm_intel FAIL
Test 121 hafs_regional_atm_thompson_gfdlsf_intel FAIL
Test 123 hafs_regional_atm_wav_intel FAIL
Test 125 hafs_regional_1nest_atm_intel FAIL
Test 126 hafs_regional_telescopic_2nests_atm_intel FAIL
Test 127 hafs_global_1nest_atm_intel FAIL
Test 128 hafs_global_multiple_4nests_atm_intel FAIL
Test 129 hafs_regional_specified_moving_1nest_atm_intel FAIL
Test 130 hafs_regional_storm_following_1nest_atm_intel FAIL
Test 132 hafs_global_storm_following_1nest_atm_intel FAIL
Test 133 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL
Test 155 control_p8_atmlnd_sbs_intel FAIL
Test 156 atmwav_control_noaero_p8_intel FAIL
Test 157 control_atmwav_intel FAIL
Test 158 atmaero_control_p8_intel FAIL
Test 159 atmaero_control_p8_rad_intel FAIL
Test 160 atmaero_control_p8_rad_micro_intel FAIL
Test 161 regional_atmaq_intel FAIL
Test 162 regional_atmaq_debug_intel FAIL
Test 163 regional_atmaq_faster_intel FAIL
Test 164 control_c48_gnu FAIL
Test 165 control_stochy_gnu FAIL
Test 166 control_ras_gnu FAIL
Test 167 control_p8_gnu FAIL
Test 168 control_p8_ugwpv1_gnu FAIL
Test 169 control_flake_gnu FAIL
Test 170 rap_control_gnu FAIL
Test 171 rap_decomp_gnu FAIL
Test 172 rap_2threads_gnu FAIL
Test 174 rap_sfcdiff_gnu FAIL
Test 175 rap_sfcdiff_decomp_gnu FAIL
Test 183 rrfs_v1beta_gnu FAIL
Test 184 control_diag_debug_gnu FAIL
Test 185 regional_debug_gnu FAIL
Test 186 rap_control_debug_gnu FAIL
Test 190 rap_diag_debug_gnu FAIL
Test 191 rap_noah_sfcdiff_cires_ugwp_debug_gnu FAIL
Test 192 rap_progcld_thompson_debug_gnu FAIL
Test 193 rrfs_v1beta_debug_gnu FAIL
Test 194 control_ras_debug_gnu FAIL
Test 195 control_stochy_debug_gnu FAIL
Test 196 control_debug_p8_gnu FAIL
Test 197 rap_flake_debug_gnu FAIL
Test 198 rap_clm_lake_debug_gnu FAIL
Test 199 rap_control_dyn32_phy32_gnu FAIL
Test 201 rap_2threads_dyn32_phy32_gnu FAIL
Test 209 rap_control_dyn64_phy32_gnu FAIL
Test 210 rap_control_debug_dyn32_phy32_gnu FAIL
Test 216 rap_control_dyn64_phy32_debug_gnu FAIL
Test 217 cpld_control_p8_gnu FAIL
Test 218 cpld_control_nowave_noaero_p8_gnu FAIL
Test 219 cpld_debug_p8_gnu FAIL
Test 220 cpld_control_pdlib_p8_gnu FAIL
Test 221 cpld_debug_pdlib_p8_gnu FAIL
```
</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by grantfirl** [comment]
@DeniseWorthen Since https://github.com/ufs-community/ufs-weather-model/pull/1993 doesn't change baselines, would you be interested in combining them?

**Comment by DeniseWorthen** [comment]
I would prefer not to combine them since the grv fix changes nearly every baseline. We can of course combine #1993 with any other PR which does not change baselines.

**Comment by jkbk2004** [comment]
To bring in the bug fix, we can start working on this PR today. @DeniseWorthen @SadeghTabas-NOAA it will be appreciated if WCOSS2/Acorn tests can be covered on your side. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI

**Comment by sadeghitabas** [comment]
@jkbk2004 As I talked to @BrianCurtis-NOAA, I don't have sudo permission on wcoss2 and this PR requires BL updates, I'll talk to @junwang-noaa to get the permission by next week.

**Comment by DeniseWorthen** [comment]
@jkbk2004 I am able to do this PR on WCOSS2.

**Comment by zach1221** [comment]
Ok, looks like testing is wrapped up. Let's proceed with the merging process.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
