### PR TITLE
Add optional scaling to RRTMGP flux adjustment

### PR DESCRIPTION
**Pull request by dustinswales**
## Description
This PR contains improvements to how the LW heating-rate profile is updated between calls to the RRTMGP radiation scheme.
The adjusted net LW flux is computed following Hogan and Bozzo 2015 (10.1002/2015MS000455). Optionally, the flux adjustment can be damped with height using a logistic function.

## Testing
This was tested on Hera using the Intel compilers. Baselines for the c192l127 RRTMGP regression test will need to be updated.

## Dependencies
https://github.com/dustinswales/fv3atm/tree/hotfix_AddPLimitToLWJacAdj
https://github.com/dustinswales/ccpp-physics/tree/hotfix_AddPLimitToLWJacAdj

## Waiting for other repos
https://github.com/NOAA-EMC/fv3atm/pull/319
https://github.com/NCAR/ccpp-physics/pull/668

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]

**Comment by junwang-noaa** [comment]
Dustin, would you please sync your code with the latest develop branch? Thanks

**Comment by climbfuji** [comment]
I'll take care of this when I pull in the code changes from Dustin into a combined PR.

**Comment by climbfuji** [comment]
This PR has been pulled into https://github.com/ufs-community/ufs-weather-model/pull/658 and will be merged as part of it.

**Comment by climbfuji** [comment]
This PR was merged as part of https://github.com/ufs-community/ufs-weather-model/pull/619

**Pull request closed without merging**
