### PR TITLE
[production/RRFS.v1] Updates .gitmodules to use production/RRFS.v1 branches

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [ ] Add list of all failed regression tests in "Regression Tests" section.

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [x] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

## Changes

Updates the .gitmodules file to point at the production/RRFS.v1 branches of FV3 and stochastic_physics
### Subcomponent (with links)

 
[X] FV3
- NOAA-EMC/fv3atm/pull/784
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [ ] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [ ] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@MatthewPyle-NOAA would you like to update the fv3atm production/RRFS.v1 branch to point to the dycore RRFS.v1 branch? Thanks

**Comment by MatthewPyle-NOAA** [comment]
Thanks for making the title more descriptive, @BrianCurtis-NOAA.  Can you shed any light on what is needed for a minimal change such as this one for a production branch (i.e., are RT results required)?  Thanks!

**Comment by MatthewPyle-NOAA** [comment]
> @MatthewPyle-NOAA would you like to update the fv3atm production/RRFS.v1 branch to point to the dycore RRFS.v1 branch? Thanks

Yes, was planning to do that once this was done.  I thought I needed to work from the top down, but maybe I could get the groundwork in place for fv3atm as well now.

**Comment by BrianCurtis-NOAA** [comment]
> Thanks for making the title more descriptive, @BrianCurtis-NOAA. Can you shed any light on what is needed for a minimal change such as this one for a production branch (i.e., are RT results required)? Thanks!

My recommendation would be to work from the ground up. As far as what tests to run, it would be ill advised to run the full suite and ill advised to run no tests. You might want to take rt.conf and create rt_rrfsv1.conf from that, and use the -l option in rt.sh `./rt.sh -l rt_rrfsv1.conf` to run your smaller set of tests. In AQM we only had regional_atmaq and regional_atmaq_debug tests running for production updates.

**Comment by junwang-noaa** [comment]
@MatthewPyle-NOAA you can make an FV3ATM PR as a dependent PR, we can commit that first and then commit the UFS WM PR.

**Comment by MatthewPyle-NOAA** [comment]
> @MatthewPyle-NOAA you can make an FV3ATM PR as a dependent PR, we can commit that first and then commit the UFS WM PR.

Okay, so I think I have it backwards.  We want FV3ATM processed first, then UFS WM?

**Comment by junwang-noaa** [comment]
Yes. Starting from bottom up.

**Pull request closed without merging**
