### PR TITLE
Update fv3atm io routines to use same type kind for both axes and data variables

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

This PR updates fv3atm io routines to use the same data type (float or double) for axes in restart files as data type used for data variables. This will make a temporary fix in restart write routine in the write grid component unnecessary and make everything consistent and restart files written by FMS and write grid component will be identical.

### Subcomponent Pull Requests

https://github.com/NOAA-EMC/fv3atm/issues/696
- Depends on https://github.com/NOAA-EMC/fv3atm/pull/697
- Depends on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/283

### Blocking Dependencies

None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

atmaero_control_p8
atmaero_control_p8_rad
atmaero_control_p8_rad_micro
atmwav_control_noaero_p8
control_atmwav
control_c384gdas
control_c48
control_p8_faster
control_p8
control_p8_mynn
control_p8_rrtmgp
conus13km_control
cpld_bmark_p8
cpld_control_c192_p8
cpld_control_c48
cpld_control_c96_noaero_p8
cpld_control_ciceC_p8
cpld_control_gfsv17
cpld_control_noaero_p8_agrid
cpld_control_noaero_p8
cpld_control_p8_faster
cpld_control_p8
cpld_control_p8_mixedmode
cpld_control_pdlib_p8
cpld_debug_noaero_p8
cpld_debug_p8
cpld_debug_pdlib_p8
hafs_global_1nest_atm
hafs_global_multiple_4nests_atm
hafs_regional_1nest_atm
hafs_regional_storm_following_1nest_atm
hrrr_c3
hrrr_control_dyn32_phy32
hrrr_control
hrrr_gf
merra2_thompson
rap_control_dyn32_phy32
rap_control_dyn64_phy32
rap_control
rap_sfcdiff
regional_atmaq_debug
regional_atmaq_faster
regional_atmaq
rrfs_v1beta

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12608853/RegressionTests_hera.log)

**Comment by zach1221** [comment]
Hey, @BrianCurtis-NOAA . I think we can start testing on this PR.

Edit: Once @DusanJovic-NOAA syncs with develop/resolves conflict.

**Comment by zach1221** [comment]
Some problems with jenkins-ci connecting to EC2 instance, so running the ORTs manually on Hera in the meantime.

**Comment by SamuelTrahanNOAA** [comment]
I've tested #1893 on Hera using this PR as the baseline. (That's the 20230922 baseline.) That means #1893 should be ready to go when you merge this.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA thanks for the note! @BrianCurtis-NOAA acorn is running on this pr, right?

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we can merge with fv3 hash update.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
