### PR TITLE
[production/RRFS.v1] Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)

### PR DESCRIPTION
**Pull request by jordanschnell**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:
For ebb_dcycle==1 (retrospective fire emissions), the 3-d emissions were incorrectly assgined assigned at all levels using the surface data.

### Commit Message:
Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)
```
* UFSWM - 
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - 
    * ccpp-physics - Fix improperly assigned fire emissions for ebb_dcycle==1 for retrospectives (NOT operational!)
    * atmos_cubed_sphere - 
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 - 
  * stochastic_physics - 
```

### Priority:
* High: Time-sensitive project.
* High: Reason: Retrospective experiments with smoke and ebb_dcycle=1 will use the wrong wildfire emissions

### Sub component Pull Requests:
* FV3: NOAA-EMC/fv3atm#812
  * ccpp-physics: ufs-community/ccpp-physics#191

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
053 conus13km_control_intel failed in check_result
conus13km_control_intel 053 failed in run_test
059 conus13km_debug_intel failed in check_result
conus13km_debug_intel 059 failed in run_test
060 conus13km_debug_qr_intel failed in check_result
conus13km_debug_qr_intel 060 failed in run_test
061 conus13km_debug_2threads_intel failed in check_result
conus13km_debug_2threads_intel 061 failed in run_test
062 conus13km_radar_tten_debug_intel failed in check_result
conus13km_radar_tten_debug_intel 062 failed in run_test

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates  

---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@jordanschnell @MatthewPyle-NOAA Should we prepare to schedule to commit this pr to the rrfs.v1 production branch? Should same feature be added to develop branch?

**Comment by grantfirl** [comment]
@jordanschnell Please pull in the latest production/RRFS.v1 code for testing.

**Comment by MatthewPyle-NOAA** [comment]
> @jordanschnell @MatthewPyle-NOAA Should we prepare to schedule to commit this pr to the rrfs.v1 production branch? Should same feature be added to develop branch?

@jkbk2004 yes on scheduling to get this into the rrfs.v1 production branch.  I don't know enough about it to know if it also needs to go to the develop branch.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA I am going to start testing on hera and hercules. @grantfirl we can figure out how to bring another pr to develop branch, right?

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 I've started testing on WCOSS.

**Comment by MatthewPyle-NOAA** [comment]
My initial test on WCOSS confirmed the @jordanschnell result of those five tests failing.

**Comment by grantfirl** [comment]
> @MatthewPyle-NOAA I am going to start testing on hera and hercules. @grantfirl we can figure out how to bring another pr to develop branch, right?

@jkbk2004 Yes. I can add it with the others. I need to figure out whether some of the PRs into the RRFS production branch can be safely combined into fewer PRs for develop.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA note that I updated bl_date.conf to BL_DATE=20240410 since 5 cases changes results. Can you make sure about that on wcoss2?

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 - yes, I did that on WCOSS2.  But you've reminded me that I need to mirror the new develop-20240410 directory to the other side of WCOSS2.

**Comment by jkbk2004** [comment]
> @jkbk2004 - yes, I did that on WCOSS2. But you've reminded me that I need to mirror the new develop-20240410 directory to the other side of WCOSS2.

Then, we can start merging process.

**Comment by jordanschnell** [comment]
@grantfirl , tried the same procedure -- met with:

Screenshot 2024-04-11 at 1 34 22 PM

**Comment by jkbk2004** [comment]
> @grantfirl , tried the same procedure -- met with:
> 
> Screenshot 2024-04-11 at 1 34 22 PM

Sounds like I raced to push. But this pr looks good to merge.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jordanschnell** [comment]
> > @grantfirl , tried the same procedure -- met with:
> > Screenshot 2024-04-11 at 1 34 22 PM
> 
> Sounds like I raced to push. But this pr looks good to merge.

Thanks, @jkbk2004!

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good from my perspective....

**Pull request merged**
