### PR TITLE
Add Scotch 7.0.3 modules to WCOSS2 

### LINKED ISSUE #1859: Add scotch library to WCOSS2 module files
## Description
Dogwood and Cactus now have the scotch library installed.  The SCOTCH library needs to be added to the module file and scotch tests can be turned on. 

## Solution
Add the following to wcoss2 module file:
```
 prepend_path("MODULEPATH", "/apps/prod/lmodules/INTEL_cray_mpich/19.1.3.304/cray-mpich/8.1.9")
scotch_ver=os.getenv("scotch_ver") or "7.0.3"
load(pathJoin("scotch",scotch_ver))
```

## Alternatives
If there's another scotch module on wcoss2 that's preferred to be used. 

## Related to
n/a

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG for hera: 
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12362414/RegressionTests_hera.log)
  - LOG for wcoss2 (compared against new baseline pointing to temporary input for WW3): 
[RegressionTests_wcoss2.log](https://github.com/ufs-community/ufs-weather-model/files/12362417/RegressionTests_wcoss2.log)

- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
Add Scotch 7.0.3 modules to WCOSS2 and turn on PDLIB regression tests. 

### Associated UFSWM Issue to close
- Closes #1859

### Subcomponent Pull Requests
None 

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

### Input data
- [ ] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [x] New input data. 
  - [ ] Updated input data.

The input data in WW3_input_data_20220624 which is on hera needs to be copied to the WCOSS2 input locations for the extra files needed for the pdlib cases to be turned on. 

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

No changes are expected to any existing regression tests.  On WCOSS2, new tests were enabled so baselines for the pdlib tests will need to be added.   

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

This uses the existing SCOTCH installs on WCOSS2. 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
FYI: Unstructured grids is being delayed to HR3, so this is not needed for HR2. I did a test on dogwood just for the pdlib cases and a full set on cactus in addition to the normal hera test.

**Comment by JessicaMeixner-NOAA** [comment]
I just retested the pdlib tests on cactus after the last PR that updated modules to confirm things still worked.  -- They do.  Still missing the additional WW3 inputs though.

**Comment by zach1221** [comment]
@JessicaMeixner-NOAA I think we're looking to begin testing this PR next. Can you tell us where the location of the new input data is so we can sync it to the input data 20221101 directories?
@jkbk2004

**Comment by JessicaMeixner-NOAA** [comment]
It's on hera here: /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/WW3_input_data_20220624 

Just the files needed for the unstructured grid are missing on WCOSS2.  

FYI While this is certainly not my call we could just add the two new test baselines to the existing baselines on wcoss2 instead of creating new baselines everywhere.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I think we'll start working here next. Are you able to copy the new input data Jessica mentioned above to WCOSS?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I think we'll start working here next. Are you able to copy the new input data Jessica mentioned above to WCOSS?

If it's on Hera I rsync from there.

**Comment by jkbk2004** [comment]
> > @BrianCurtis-NOAA I think we'll start working here next. Are you able to copy the new input data Jessica mentioned above to WCOSS?
> 
> If it's on Hera I rsync from there.

```
Jong.Kim@hfe09:/scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/WW3_input_data_20220624$ ls
createmoddefs        mod_def.exp.global_270k  mod_def.mx025      mod_def.pointsatmw
mesh.glo_1deg.nc     mod_def.glo_15mxt        mod_def.mx025lite  rmp_src_to_dst_conserv_002_001.nc
mesh.global_270k.nc  mod_def.glo_1deg         mod_def.mx050      rmp_src_to_dst_conserv_003_001.nc
mesh.gwes_30m.nc     mod_def.gnh_10m          mod_def.mx100      wind.natl_6m
mesh.hafs.nc         mod_def.gsh_15m          mod_def.natl_6m
mod_def.aoc_9km      mod_def.gwes_30m         mod_def.points
```

**Comment by zach1221** [comment]
ORTs passed. Jenkins-ci logs attached.
[Jenkins-ci 1871 ORTs.pdf](https://github.com/ufs-community/ufs-weather-model/files/12498393/Jenkins-ci.1871.ORTs.pdf)

**Comment by BrianCurtis-NOAA** [comment]
As soon as Dogwood becomes available, I'll get started on that.

**Review by sadeghitabas — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
