### PR TITLE
HR4 and SFS baseline update: Improve convection/radiation interaction in the GFS physics suite 

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

The GFS physics suite at 100km yields too large cloud cover and optical depth, causing too much cloud shielding and a drift in Sea Surface Temperatures, SST for seasonal prediction. This is an issue for the Seasonal Forecast System baseline. The issue was identified to be related to too much convective cloud condensate passed in from the cumulus convection scheme.

A scale adaptive solution is proposed and tested for SFS and GFS resolutions, outputting updraft values of in-cloud condensate. We propose to add this change to SFS baselines as well as the HR4 prototype of the GFS. In testing we also tune the minimum background diffusivity in the inversion layer near the PBL top (xkinv1) from xkinv1=0.4 to xkinv1=0.15 in order to not reduce convective clouds too much in marine stratocumulus.

### Commit Message:

```

  * FV3 - update pointer to ccpp-physics
    * ccpp-physics - update convection and PBL schemes to improve cloud/convection interaction
   
```

### Priority:

* High: Time-sensitive project (HR4 of GFS and SFS baselines)

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/851
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/216
  

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
@lisa-bengtsson It looks like there was a merge issue with the test_changes.list and the Hera log. I'm seeing that those files need to be merged manually (contains "<<<HEAD" etc.). Could you check this?

**Comment by jkbk2004** [comment]
@lisa-bengtsson can you sync up branch? I like to test on my side as well.

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson can you sync up branch? I like to test on my side as well.

I just synced up the branch, after addressing the issue causing seg fault. Could you kindly test on your end? I will restart the full RT suite now.

**Comment by zach1221** [comment]
@lisa-bengtsson could you add user epic-cicd-jenkins as a collaborator to this PR's branch? It's just to enable the pipeline to post logs.

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson can you sync up branch? I like to test on my side as well.

sure, how do I do that?

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson could you add user epic-cicd-jenkins as a collaborator to this PR's branch? It's just to enable the pipeline to post logs.

Sure, how do I do that?

**Comment by jkbk2004** [comment]
> > @lisa-bengtsson could you add user epic-cicd-jenkins as a collaborator to this PR's branch? It's just to enable the pipeline to post logs.
> 
> Sure, how do I do that?

@lisa-bengtsson You can add the user epic-cicd-jenkins in your repo: settings/access/Collaborators-and-Teams

**Comment by lisa-bengtsson** [comment]
> > > @lisa-bengtsson could you add user epic-cicd-jenkins as a collaborator to this PR's branch? It's just to enable the pipeline to post logs.
> > 
> > 
> > Sure, how do I do that?
> 
> @lisa-bengtsson You can add the user epic-cicd-jenkins in your repo: settings/access/Collaborators-and-Teams

Ok, I added epic-cicd-jenkins from my fork, hopefully that works?

**Comment by FernandoAndrade-NOAA** [comment]
Hera baseline creation timed out for `cpld_control_nowave_noaero_p8 gnu`, rerunning. The rest of the tests seem to be fine. @BrianCurtis-NOAA FYI we are starting testing for this PR.

**Comment by zach1221** [comment]
Ok I think we're ready to begin merge process.

**Comment by grantfirl** [comment]
@zach1221 https://github.com/ufs-community/ccpp-physics/pull/216 is merged and https://github.com/NOAA-EMC/fv3atm/pull/851 is updated and ready for merge.

**Comment by zach1221** [comment]
@lisa-bengtsson FV3atm [PR-815 ](https://github.com/NOAA-EMC/fv3atm/pull/851) is merged. Please update hash and revert .gitmodule url.
Hash: https://github.com/NOAA-EMC/fv3atm/commit/2527c11754f1b8144dcbfb59952d0e06446a0166

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
