### PR TITLE
Use optional chunksizes argument in register_restart_field calls (combining PRs #1853 & 1834)

### LINKED ISSUE #217: using fms chunksize and compression options in dycore
**Is your feature request related to a problem? Please describe.**
In the fms issue https://github.com/NOAA-GFDL/FMS/issues/1035, the feature of using chunksize and compression options in writing netcdf files were request. The fms team made code updates and a PR (https://github.com/NOAA-GFDL/FMS/pull/1043). With the new FMS features in fms2_io, the dycore needs to be updated to writing out restart files using the new feature, which is critical to speed up the RRFS model which NCEP plans to implement v1 version next year (some initial test with hard code chunksize showed the cycled hourly RRFS run time reduced 50%. May I ask if there is any plan to update the dycore code to use the new feature? Thank you!  

**Describe the solution you'd like**
Update the fms2 io interface code to allow using chunksize and compression options. 

**Describe alternatives you've considered**
Currently we don't have alternative way to use chunksize or compression options when writing out restart files.

**Additional context**

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR updates the register_restart_field calls to pass optional argument 'chunksizes'. Chunk sizes are equal to the corresponding dimension size. This change will speed up reading the restart in RRFS DA.

**IMPORTANT:** This PR needs FMS 2022.04 https://github.com/NOAA-EMC/hpc-stack/issues/494

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/217

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [x] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/595
- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/223
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/683 (1853)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA We are handling priority of aqm pr this week. I will touch base with you about lib update status.: maybe tomorrow.

**Comment by DusanJovic-NOAA** [comment]
@jkbk2004  Compilation of this branch fails on Orion due to missing read permission of the fms/2022.04 installation directory:
```
$ ls -l /work/noaa/epic-ps/hpc-stack/libs/intel/2022.1.2/intel-2022.1.2/impi-2022.1.2/fms
total 12
drwxrwsr-x 5 jongkim epic-ps 4096 Sep 14 09:56 2022.01
drwxrwsr-x 5 jongkim epic-ps 4096 Sep 12 20:19 2022.03
drwxr-s--- 5 jongkim epic-ps 4096 Nov 16 10:17 2022.04

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA I am trying to confirm fms-2022.04 on cheyenne/gnu and I am rescheduling #1488. So, I think we can start to commit PRs related to new fms version. I mean anytime once I confirm on cheyenne/gnu. One question... Do you think this draft PR can be combined to @binli2337 #1514?

In my opinion this PR and #1514 should be two separate PRs. If 1514 update is urgent go ahead with that PR first.

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA In your PR, would you please remove fms_io_nml in the fv3atm namelist templates (tests/parm/*nml.IN) and instead add fms2_io_nml? UFS WM does not use fms_io any more, the code is using fms2_io. Thanks.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA In your PR, would you please remove fms_io_nml in the fv3atm namelist templates (tests/parm/*nml.IN) and instead add fms2_io_nml? UFS WM does not use fms_io any more, the code is using fms2_io. Thanks.

Which options should we set in fms2_io_nml namelist?
What about mpp_io_nml namelist? I think we can remove it as well.

**Comment by jkbk2004** [comment]
@natalie-perlin fms-2023.01 was released this week: https://github.com/NOAA-GFDL/FMS/releases/tag/2023.01 can you install the new version across hera, orion, and cheyenne first ?

**Comment by natalie-perlin** [comment]
@jkbk2004 - we are looking at standard installation stacks with netcdf/4.7.4 first priority, correct?

**Comment by jkbk2004** [comment]
> @jkbk2004 - we are looking at standard installation stacks with netcdf/4.7.4 first priority, correct?

correct. once new fms is confirmed on top of current modulefiles, this pr can move on, I think.

**Comment by natalie-perlin** [comment]
Done with the fms/2023.01 installations for the platforms Gaea, Cheyenne, Orion, Hera, Jet, in standard EPIC-maintained hpc-stack locations 
See comments for locations:
https://github.com/ufs-community/ufs-weather-model/issues/1649#issuecomment-1500405157
https://github.com/ufs-community/ufs-weather-model/issues/1649#issuecomment-1500673746

**Hera:**
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/intel-2022.1.2
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-10.2
**Orion:**
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2
**Cheyenne:**
/glade/work/epicufsrt/contrib/hpc-stack/intel2022.1
/glade/work/epicufsrt/contrib/hpc-stack/gnu10.1.0/
**Jet:**
/mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-2022.1.2
/mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274
**Gaea:**
/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0_noarch

**Comment by FernandoAndrade-NOAA** [comment]
@DusanJovic-NOAA Could you sync your branch with the latest develop and include the changes from PR #1717 as well? 1717 contains no baseline change. Thank you

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Could you sync your branch with the latest develop and include the changes from PR #1717 as well? 1717 contains no baseline change. Thank you

I think fms 2023.01 is not yet available on all platforms. wcoss2 for example. @Hang-Lei-NOAA can you confirm?

**Comment by DusanJovic-NOAA** [comment]
Updated WW3 from #1717

**Comment by jkbk2004** [comment]
@natalie-perlin just to make sure FMS-2023.01 is installed across RDHPCS.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA it sounds like we need a bit more time to make sure about FMS-2023.01 installation. Can we move to #1702 today ?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA it sounds like we need a bit more time to make sure about FMS-2023.01 installation. Can we move to #1702 today ?

Sure. 1702 is synced with the develop

**Comment by natalie-perlin** [comment]
> @natalie-perlin just to make sure FMS-2023.01 is installed across RDHPCS.

@jkbk2004 - it was installed on all the platforms the EPIC maintains software stacks (and has access to) - Gaea, Hera, Orion,  Jet, Cheyenne.

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA Is FMS 2023.01 installed on WCOSS2 and Acorn?

**Comment by Hang-Lei-NOAA** [comment]
@Brian Curtis - NOAA Affiliate ***@***.***> It has been
installed on acorn, but it has not been sent to NCO for WCOSS2, which I
need confirmation from the UFS team after your testing.

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA Brian tested the ufs wm with fms 2023.01 with hdf5 1.14.0 and netcdf 4.9.2 under /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/libs3/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9. it is working as expected. @DusanJovic-NOAA would you please test with your branch? You can see the acorn module file at:  /lfs/h1/emc/nems/noscrub/jun.wang/ufs-wm/20230314/netcdf492/ufs-weather-model/modulefiles/ufs_acorn.intel.lua. 
Thanks

**Comment by DusanJovic-NOAA** [comment]
> @Hang-Lei-NOAA Brian tested the ufs wm with fms 2023.01 with hdf5 1.14.0 and netcdf 4.9.2 under /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/libs3/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9. it is working as expected. @DusanJovic-NOAA would you please test with your branch? You can see the acorn module file at: /lfs/h1/emc/nems/noscrub/jun.wang/ufs-wm/20230314/netcdf492/ufs-weather-model/modulefiles/ufs_acorn.intel.lua. Thanks

@junwang-noaa I ran one test (control_p8) using your ufs_acon.intel.lua in my branch and it finished successfully.

**Comment by Hang-Lei-NOAA** [comment]
@Jun Wang - NOAA Federal ***@***.***> So, I can submit the code
delivery today

**Comment by natalie-perlin** [comment]
@Hang-Lei-NOAA @DusanJovic-NOAA -
Do updates on WCOSS2 and acorn that include netcdf/4.9.2 also include esmf/8.4.2 and mapl/2.35.2 ?

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA would you please make request to install the fms 2023.01/ESMF 8.4.2 along with netcdf 1.14.0/netcdf 4.9.2 on wcoss2? Thanks

**Comment by Hang-Lei-NOAA** [comment]
@Jun Wang - NOAA Federal ***@***.***> The previous ticket will be
updated to install the  ESMF 8.4.2 along with netcdf 1.14.0/netcdf 4.9.2 on
wcoss2. New ticket after that will be for fms/2023.01.
@Natalie Perlin - NOAA Affiliate ***@***.***> Our tests of
fms/2023.01 are based on these new libs. So, code delivery will be the same.

**Comment by DeniseWorthen** [comment]
This PR no longer includes a WW3 component, right?

**Comment by DusanJovic-NOAA** [comment]
> This PR no longer includes a WW3 component, right?

I just reverted WW3 submodule.

**Comment by MatthewPyle-NOAA** [comment]
Is this just being held up waiting for various libraries to be installed?  Some RRFS developers asked me about the status.  Thanks!

**Comment by jkbk2004** [comment]
> Is this just being held up waiting for various libraries to be installed? Some RRFS developers asked me about the status. Thanks!

@MatthewPyle-NOAA sorry for slow process but we are waiting for wcoss2 code delivery with #1745. It can happen anytime soon.

**Comment by SamuelTrahanNOAA** [comment]
This could potentially be combined with #1769, which refactors the fv3atm code that this PR updates.

**Comment by DusanJovic-NOAA** [comment]
For the changes in this PR to work as expected we need FMS 2023.01. I think we can merge it now (before we update ufs-weather-model to FMS 2023.01) but the chunking will not work since it needs netcdf4 option added to fms2 io in that version.
@jkbk2004 @junwang-noaa what do you suggest, should we wait for 2023.01 or merge this PR now and once we actually switch to 2023.01 we can then enable netcdf4 fm2io option.

**Comment by DusanJovic-NOAA** [comment]
Another option is to update to FMS 2023.01 now, on all platforms except wcoss2, assuming it is installed. wcoss2 uses it's own modulefile anyway. Not the ufs_common.

**Comment by junwang-noaa** [comment]
I would suggest to go with the second option. Let's merge this PR with FMS 2023.01 on all platforms except wcoss2. This will give us opportunity to test/verify this feature on other platform. The library will be updated in PR#1745.

**Comment by DusanJovic-NOAA** [comment]
> I would suggest to go with the second option. Let's merge this PR with FMS 2023.01 on all platforms except wcoss2. This will give us opportunity to test/verify this feature on other platform. The library will be updated in PR#1745.

Just to confirm in this PR we will update fms in ufs_common.lua to 2023.01, correct?

**Comment by junwang-noaa** [comment]
Yes. But you may want to check acorn as it is using the ufs_common too.

**Comment by DusanJovic-NOAA** [comment]
I see this error on Acorn, when I run test with fms/2023.01:

```
++ date +%s
+ echo -n ' 1685630831,'
+ cd /lfs/h2/emc/ptmp/dusan.jovic/FV3_RT/rt_22715/control_p8_intel
+ set +x

Currently Loaded Modules:
  1) craype-x86-rome      (H)  18) pio/2.5.7
  2) libfabric/1.11.0.0.  (H)  19) esmf/8.3.0b09
  3) craype-network-ofi   (H)  20) fms/2023.01
  4) envvar/1.0                21) bacio/2.4.1
  5) PrgEnv-intel/8.1.0        22) crtm/2.4.0
  6) craype/2.7.13             23) g2/3.4.5
  7) cray-mpich/8.1.9          24) g2tmpl/1.10.2
  8) cmake/3.20.2              25) ip/3.3.3
  9) hpc/1.2.0                 26) sp/2.3.3
 10) intel/19.1.3.304          27) w3emc/2.9.2
 11) hpc-intel/19.1.3.304      28) gftl-shared/v1.5.0
 12) hpc-cray-mpich/8.1.9      29) mapl/2.22.0-esmf-8.3.0b09
 13) jasper/2.0.25             30) ufs_common
 14) zlib/1.2.11               31) ifi/20230118-intel-19.1.3.304
 15) libpng/1.6.37             32) modules.fv3
 16) hdf5/1.10.6               33) cray-pals/1.2.2
 17) netcdf/4.7.4

  Where:
   H:  Hidden Module



++ date
+ echo 'Model started:  ' Thu Jun 1 14:47:13 UTC 2023
+ export OMP_STACKSIZE=512M
+ OMP_STACKSIZE=512M
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ export OMP_PLACES=cores
+ OMP_PLACES=cores
+ export ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
+ ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
+ export ESMF_RUNTIME_PROFILE=ON
+ ESMF_RUNTIME_PROFILE=ON
+ export ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
+ ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
+ mpiexec -n 256 -ppn 128 -depth 1 ./fv3.exe

FATAL from PE     0: NetCDF: Name contains illegal characters: netcdf_add_variable: file:RESTART/20210322.180000.fv_core.res.ncvariable:xaxis_1
```

This is using develop branch with this change:
```
alogin03:/lfs/h1/emc/eib/noscrub/dusan.jovic/ufs/develop/ufs-weather-model> git diff
diff --git a/modulefiles/ufs_common.lua b/modulefiles/ufs_common.lua
index 6b9c9d40..5a3a4156 100644
--- a/modulefiles/ufs_common.lua
+++ b/modulefiles/ufs_common.lua
@@ -10,7 +10,7 @@ local ufs_modules = {
   {["netcdf"]      = "4.7.4"},
   {["pio"]         = "2.5.7"},
   {["esmf"]        = "8.3.0b09"},
-  {["fms"]         = "2022.04"},
+  {["fms"]         = "2023.01"},
   {["bacio"]       = "2.4.1"},
   {["crtm"]        = "2.4.0"},
   {["g2"]          = "3.4.5"},
```

**Comment by DusanJovic-NOAA** [comment]
Compilation fails on gaea:
```
+ set +x
Lmod has detected the following error: The following module(s) are unknown:
"fms/2023.01" "cray-mpich/7.7.11"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "fms/2023.01" "cray-mpich/7.7.11"

Also make sure that all modulefiles written in TCL start with the string
#%Module

Executing this command requires loading "cray-mpich/7.7.11" which failed while
processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    ufs_gaea.intel   /lustre/f2/dev/ncep/Dusan.Jovic/ufs/restart_chunksizes/ufs-weather-model/modulefiles/ufs_gaea.intel.luaExecuting this command requires loading "fms/2023.01" which failed while
processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    ufs_common       /lustre/f2/dev/ncep/Dusan.Jovic/ufs/restart_chunksizes/ufs-weather-model/modulefiles/ufs_common.lua
    ufs_gaea.intel   /lustre/f2/dev/ncep/Dusan.Jovic/ufs/restart_chunksizes/ufs-weather-model/modulefiles/ufs_gaea.intel.lua
```

Looks like fms 2023.01 module is not available in the current hpc-stack location. See my previous comment about the issue on Acorn.

We need a separate PR that just updates FMS library to 2023.01

After that I can update this PR, retest everything and we can schedule a merge or combine it with some other PR

**Comment by zach1221** [comment]
For what it's worth, I tested this PR on Hera using fms/2023.01 and all intel/gnu cases in rt.conf passed.

**Comment by hu5970** [comment]
Any progress on install  fms/2023.01  on NOAA machines and possible merge this PR to develop branch? Thanks, Ming

**Comment by jkbk2004** [comment]
> Any progress on install fms/2023.01 on NOAA machines and possible merge this PR to develop branch? Thanks, Ming

@hu5970 #1745 was merged in to support fms-2023-01. So develop branch reflects fms-2023-01. We will work on this PR when Dusan come back from vacation.

**Comment by hu5970** [comment]
That is great. Thanks.

**Comment by JacobCarley-NOAA** [comment]
FYI - I heard from NCO that the following libraries are available now on WCOSS2: `hdf5/1.14.0 netcdf/4.9.2 esmf/8.4.2 fms/2023.01 mapl/2.35.2`

I believe @MatthewPyle-NOAA has used them and can confirm. So hopefully the library part is no longer blocking this, especially since https://github.com/ufs-community/ufs-weather-model/pull/1745 has gone it.

**Comment by jkbk2004** [comment]
> FYI - I heard from NCO that the following libraries are available now on WCOSS2: `hdf5/1.14.0 netcdf/4.9.2 esmf/8.4.2 fms/2023.01 mapl/2.35.2`
> 
> I believe @MatthewPyle-NOAA has used them and can confirm. So hopefully the library part is no longer blocking this, especially since #1745 has gone it.

Correct! I think we can schedule this PR once @DusanJovic-NOAA returns from PTO.

**Comment by zach1221** [comment]
Hi, @DusanJovic-NOAA , hope all's well. How would you feel about combining PRs #1853 and #1834 into this PR?

**Comment by DusanJovic-NOAA** [comment]
I merged #1834 and I'm running full test on Hera. If it passes I'll try to merge #1853 and retest.

**Comment by DusanJovic-NOAA** [comment]
Full test on Hera passed: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12469607/RegressionTests_hera.log)

**Comment by zach1221** [comment]
> Full test on Hera passed: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12469607/RegressionTests_hera.log)

Thank you, @DusanJovic-NOAA . This log is the combination of 1467 and 1834 or all three including 1853?

**Comment by DusanJovic-NOAA** [comment]
> > Full test on Hera passed: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12469607/RegressionTests_hera.log)
> 
> Thank you, @DusanJovic-NOAA . This log is the combination of 1467 and 1834 or all three including 1853?

I merged my other two branches into this one, so this PR now includes #1834 and #1853.

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins ci logs attached, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1467#1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/12477275/ufs-weather-model.ort-docker-pipeline.PR-1467.1.Console.Jenkins.txt)

**Comment by BrianCurtis-NOAA** [comment]
> Jenkins ci logs attached, ORTs passed.
> [ufs-weather-model » ort-docker-pipeline » PR-1467#1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/12477275/ufs-weather-model.ort-docker-pipeline.PR-1467.1.Console.Jenkins.txt)

Great, I'll start Acorn/WCOSS2 now.

**Comment by BrianCurtis-NOAA** [comment]
I wanted to double check. This PR has a label of "Baseline change", but the logs don't show a new baseline date nor any failed tests from Dusan's runs.

I just ran new baselines on WCOSS2/Acorn, but now I don't think I need them?

**Comment by SamuelTrahanNOAA** [comment]
There are two quilting restart tests that no longer need their own baselines because their output matches the non-quilting control. That was the purpose of 1853; it changed the precision of some variables so the quilting and non-quilting restarts match.

- hrrr_control_qr_dyn32_phy32_gnu
- hrrr_control_qr_dyn32_phy32_intel

You can see this in the rt.conf changes and the tests/tests directory changes.

**Comment by zach1221** [comment]
Testing is complete. I'll follow up on the cubed sphere #223 sub-pr to begin the merging process.

**Review by jkbk2004 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
