### PR TITLE
Mean to inst field names, part I 

### LINKED ISSUE #1800: clarify "mean" and "inst" coupled fields exchanged
## Description

As a legacy from the NEMS mediator, many fields are exported or imported from the ATM with the name ``mean``. For example, ATM imports ``mean_ice_volume`` when in fact the field from CICE is an instantaneous field since the ATM and ICE are running concurrently in the fast loop. 

Even when coupling to ocean, the fields sent to the ocean from the ATM should be the instantaneous fields, since the mediator itself forms the average of these fields over the fast coupling loop in order to create the mean field to the ocean. Generally, these fields sent to the ocean are called ``mean`` fields, but they are the average of the ``inst`` fields from ATM or ICE (or merged between ATM and ICE). 

This issue arose while investigating the shortwave fields in issue #1767 

## Solution

Impose consistency in the fields which are imported or exported. For example, the ATM should export ``inst_sensi_heat_flx``, not ``mean_sensi_heat_flx`` for the ocean. For ATM exports, these two fields are not identical at every modelAdvance, but nearly so.

In the cases examined so far, changing to the instantaneous export fields shows very small (O~10-15) differences in the export fields in the first few hours after the initial time, after which differences start increasing as the model adjusts to the accumulated small differences.

Changing of ``mean_ice_volume`` to ``inst_ice_volume`` should not result in differences however, since in this case it is only the name of the field changing, and not the content.

In most cases, imposing this consistency on the ATM side will require only a modification to the fd_nems.yaml since both ``mean`` and ``inst`` fields are available the export field setup.

## Related to

- required by #1648

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12837808/RegressionTests_hera.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Changes some field names going TO ATM from CICE or CMEPS to remove "mean" prefix. Also renames the FV3 export fields prec,fprec and prec_rate_conv as ``inst`` rather than ``mean``. 

This is the first part of a 2 part commit sequence to change from mean->inst field names. This first part will not change baselines against those created using the second of the two dependent PRs.

Logs will be posted once the dependent PRs have been merged.

### Associated UFSWM Issue to close

- incrementally resolves #1800 
### Subcomponent Pull Requests

- https://github.com/NOAA-EMC/fv3atm/pull/704

### Blocking Dependencies

- waiting on https://github.com/ufs-community/ufs-weather-model/pull/1894
- waiting on https://github.com/ufs-community/ufs-weather-model/pull/1906

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
I am running the logs now after the two dependent PRs have been merged.

**Comment by zach1221** [comment]
> I am running the logs now after the two dependent PRs have been merged.

Ok, great. We can start this PR once your tests are finished. 

Edit: let's wait, and get 1925 done before 1907.

**Comment by DeniseWorthen** [comment]
I made a boo-boo running the logs and need to start over :-(

**Comment by zach1221** [comment]
> I made a boo-boo running the logs and need to start over :-(

Ah, yes. It happens to us all. All good.

**Comment by DeniseWorthen** [comment]
@zach1221 When you squash merge, can you make the commit message just this

```
remove mean prefix for fields imported to FV3atm from CICE or CMEPS
rename fv3atm export fields for snow and rain as inst
```

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Comment by zach1221** [comment]
> @zach1221 When you squash merge, can you make the commit message just this
> 
> ```
> remove mean prefix for fields imported to FV3atm from CICE or CMEPS
> rename fv3atm export fields for snow and rain as inst
> ```

Yes, I can.

**Pull request merged**
