### PR TITLE
(1) update MOM6 to its main branch 20220902 commit (2) update GNU to include s2swa tests

### LINKED ISSUE #1400: update MOM6 to main branch 20220902 commit
MOM6 main branch was updated on 20220902, need to make corresponding updating in dev/emc and UFS, see detail at https://github.com/NOAA-EMC/MOM6/issues/103. Since there is some changes in how SPPT temperature limiter is being calculated, a new BL is needed for stochastic case

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.
the SPPT temperature limiter calculation method is being changed, thus the stochastic test case will require new baseline
- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?
update MOM6 to its main branch 20220902 commit, this is originally based on dev-emc-candidate-20220828 to MOM6 main branch but with minor modification on SPPT temperature limiter

### Issue(s) addressed
UFS #1400 and MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/103
MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/104
Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1400 and MOM6 issue https://github.com/NOAA-EMC/MOM6/issues/103

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x ] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x ] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/MOM6/pull/104

### CODE REVIEW

**Comment by jkbk2004** [comment]
@jiandewang we can start working on the pr. can we combine in #1388 ?

**Comment by DeniseWorthen** [comment]
@jiandewang once you update your branch, I will make a PR to add the S2SWA test for GNU (script level changes only).

**Comment by jiandewang** [comment]
@DeniseWorthen just updated my branch

**Comment by jiandewang** [comment]
> @jiandewang we can start working on the pr. can we combine in #1388 ?

yes we can combine them

**Comment by jkbk2004** [comment]
> > @jiandewang we can start working on the pr. can we combine in #1388 ?
> 
> yes we can combine them

@jiandewang #1388 needs only changes in rt_gnu.conf. I think its possible to manually add in but @DeniseWorthen will you create pr to jiande's branch?

**Comment by DeniseWorthen** [comment]
I made a PR to @jiandewang UWM branch a couple of hours ago.

**Comment by jiandewang** [comment]
just saw that, merged. 
Do I need to launch rt.sh on wcoss2 manually ?

**Comment by jkbk2004** [comment]
@jiandewang thanks! I will add new BL_DATE and start testing RT runs on RDHPCs. @BrianCurtis-NOAA will test on wcoss2

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 on baseline creation: Failed test hafs_regional_atm_wav (test 073) walltime 1813 exceeded limit 1800.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1048155862/20220912180010/ufs-weather-model
[BL] Error: Test compile_017 failed in run_compile failed 
[BL] Error: Test compile_018 failed in run_compile failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by jkbk2004** [comment]
@jiandewang all tests are done. we can start merging in [pr #104](https://github.com/NOAA-EMC/MOM6/pull/104).

**Review by binli2337 — COMMENTED** [review]
Looks good. The pr will be approved once the submodule is updated.

**Comment by jkbk2004** [comment]
git issue on orion was reported to help desk.
`Unable to checkout '09bdf00e500d99e2b8811c0571258f86c14efc30' in submodule path 'HYCOM-interface/HYCOM'`

**Comment by BrianCurtis-NOAA** [comment]
> git issue on orion was reported to help desk. `Unable to checkout '09bdf00e500d99e2b8811c0571258f86c14efc30' in submodule path 'HYCOM-interface/HYCOM'`

It looks like that hash does not exist inside
[https://github.com/NOAA-EMC/HYCOM-src](https://github.com/NOAA-EMC/HYCOM-src)

**Comment by jiandewang** [comment]
> > git issue on orion was reported to help desk. `Unable to checkout '09bdf00e500d99e2b8811c0571258f86c14efc30' in submodule path 'HYCOM-interface/HYCOM'`
> 
> It looks like that hash does not exist inside https://github.com/NOAA-EMC/HYCOM-src

I just had a fresh checkout, HYCOM head hash is 8d2470214

**Comment by jkbk2004** [comment]
sounds like we need to create issue to hafs team. But I am able to clone on other machines.
`From https://github.com/NOAA-EMC/HYCOM-src
 * branch            09bdf00e500d99e2b8811c0571258f86c14efc30 -> FETCH_HEAD
Submodule path 'HYCOM-interface/HYCOM': checked out '09bdf00e500d99e2b8811c0571258f86c14efc30''

**Comment by jiandewang** [comment]
MOM6 PR merged, let me know when it's time to switch submodule in UFS

**Comment by jiandewang** [comment]
> sounds like we need to create issue to hafs team. But I am able to clone on other machines. `From https://github.com/NOAA-EMC/HYCOM-src
> 
> * branch            09bdf00e500d99e2b8811c0571258f86c14efc30 -> FETCH_HEAD
>   Submodule path 'HYCOM-interface/HYCOM': checked out '09bdf00e500d99e2b8811c0571258f86c14efc30''

my fresh clone for the branch of this PR shows
-b7e077699ca1054104cc93342a038941346bef04 FV3/upp/sorc/ncep_post.fd/post_gtg.fd
 a342b1b215c3d915948b1220843f9b30ea159401 GOCART (rt-v5_29_1_BPL91_1-exRT4-453-ga342b1b)
+8d247021484c5cb7f8ded897c1e2020c028ef7e9 HYCOM-interface/HYCOM (2.3.01-52-g8d24702)
 where does "09bdf00e5" come from ?

**Comment by jiandewang** [comment]
> > sounds like we need to create issue to hafs team. But I am able to clone on other machines. `From https://github.com/NOAA-EMC/HYCOM-src
> > 
> > * branch            09bdf00e500d99e2b8811c0571258f86c14efc30 -> FETCH_HEAD
> >   Submodule path 'HYCOM-interface/HYCOM': checked out '09bdf00e500d99e2b8811c0571258f86c14efc30''
> 
> my fresh clone for the branch of this PR shows -b7e077699ca1054104cc93342a038941346bef04 FV3/upp/sorc/ncep_post.fd/post_gtg.fd a342b1b215c3d915948b1220843f9b30ea159401 GOCART (rt-v5_29_1_BPL91_1-exRT4-453-ga342b1b) +8d247021484c5cb7f8ded897c1e2020c028ef7e9 HYCOM-interface/HYCOM (2.3.01-52-g8d24702) where does "09bdf00e5" come from ?

now I see
Submodule path 'HYCOM-interface/HYCOM': checked out '09bdf00e500d99e2b8811c0571258f86c14efc30'
seems github is having issue at this moment, I just cloned on HERA and tried git submodule status  --recursive and got the following:
 e22724738fd104327fee7c3c7ffc805ccabd619f FV3/upp (upp_v10.2.0-9-ge227247)
 b7e077699ca1054104cc93342a038941346bef04 FV3/upp/sorc/ncep_post.fd/post_gtg.fd
fatal: not a git repository: '.git'
fatal: failed to recurse into submodule 'sorc/ncep_post.fd/post_gtg.fd'
fatal: failed to recurse into submodule 'upp'
fatal: failed to recurse into submodule 'FV3'

**Comment by BrianCurtis-NOAA** [comment]
@jiandewang Should HYCOM in UFS be at the HEAD of the emc/develop branch?

**Comment by jiandewang** [comment]
> @jiandewang Should HYCOM in UFS be at the HEAD of the emc/develop branch?

yes, this is what's inside .gitmodules
[submodule "HYCOM"]
  path = HYCOM-interface/HYCOM
  url = https://github.com/NOAA-EMC/HYCOM-src
  branch = emc/develop

and my fresh clone for the above is
* emc/develop 8d24702 Add hybthn to blkdat.input

**Comment by jiandewang** [comment]
can someone repeat what I just did:
   147  11:40   git clone https://github.com/jiandewang/ufs-weather-model
   148  11:40   cd ufs-weather-model/
   149  11:40   git branch -a
   150  11:40   git checkout feature/update-MOM6-20220902
   151  11:40   git submodule update --init --recursive

cd HYCOM-interface/HYCOM
git branch -v

what I got is
* (HEAD detached at 09bdf00) 09bdf00 Add :: symbol to read from nems.configure.Required for ESMF 8bs20+. (#1)
  emc/develop                8d24702 Add hybthn to blkdat.input

it should point to emc.develop, not the HEAD
so something has been changed on HYCOM during the past couple of days (maybe someone used forced push ?)

my cloned directory on HERA: /scratch1/NCEPDEV/climate/Jiande.Wang/MOM6-update/MOM6-update-20220902/Final/ufs-weather-model

during the submodule update --init --recursive, it had
From https://github.com/NOAA-EMC/HYCOM-src
 * branch            09bdf00e500d99e2b8811c0571258f86c14efc30 -> FETCH_HEAD
this shouldn't be there

I also cloned the ufs develop branch, and got the same thing

**Comment by jkbk2004** [comment]
> can someone repeat what I just did: 147 11:40 git clone https://github.com/jiandewang/ufs-weather-model 148 11:40 cd ufs-weather-model/ 149 11:40 git branch -a 150 11:40 git checkout feature/update-MOM6-20220902 151 11:40 git submodule update --init --recursive
> 
> cd HYCOM-interface/HYCOM git branch -v
> 
> what I got is
> 
> * (HEAD detached at 09bdf00) 09bdf00 Add :: symbol to read from nems.configure.Required for ESMF 8bs20+. ([Update ufs-weather-model/develop with changes from gmtb/develop as of 2019/10/16 #1](https://github.com/ufs-community/ufs-weather-model/pull/1))
>   emc/develop                8d24702 Add hybthn to blkdat.input
> 
> it should point to emc.develop, not the HEAD so something has been changed on HYCOM during the past couple of days (maybe someone used forced push ?)
> 
> my cloned directory on HERA: /scratch1/NCEPDEV/climate/Jiande.Wang/MOM6-update/MOM6-update-20220902/Final/ufs-weather-model
> 
> during the submodule update --init --recursive, it had From https://github.com/NOAA-EMC/HYCOM-src
> 
> * branch            09bdf00e500d99e2b8811c0571258f86c14efc30 -> FETCH_HEAD
>   this shouldn't be there
> 
> I also cloned the ufs develop branch, and got the same thing

Yes, I see the same on other machines. BTW, we need to use 'module load git/2.28.0' on orion.

**Comment by jkbk2004** [comment]
I checked out a ufs-wm hash around early June. 
'-09bdf00e500d99e2b8811c0571258f86c14efc30 HYCOM-interface/HYCOM'
Same hycom hash was used then. I think we are ok to merge this pr. We just need to make sure about hycom hash with hafs team.

**Comment by BrianCurtis-NOAA** [comment]
Please hold while we track down this HYCOM issue.

**Comment by DeniseWorthen** [comment]
The hycom hash should not have changed. Brian and I have checked w/ Bin Liu. The emc/develop branch in our fork was updated---and we're not clear why. Please don't merge until we can straighten this out. The issue is that we cannot find the hash [09bdf00](https://github.com/NOAA-EMC/HYCOM-src/commit/09bdf00e500d99e2b8811c0571258f86c14efc30) currently in emc/develop.

For instance: git clone https://github.com/NOAA-EMC/HYCOM-src.git
git checkout 09bdf00e50
error: pathspec '09bdf00e50' did not match any file(s) known to git

**Comment by DusanJovic-NOAA** [comment]
The last event in NOAA-EMC/HYCOM-src repo that changed the HEAD of the emc/develop branch from 09bdf00 to 8d24702 was:

```json
[
  {
    "id": "23923922315",
    "type": "PushEvent",
    "actor": {
      "id": 11394126,
      "login": "aerorahul",
      "display_login": "aerorahul",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aerorahul",
      "avatar_url": "https://avatars.githubusercontent.com/u/11394126?"
    },
    "repo": {
      "id": 389701838,
      "name": "NOAA-EMC/HYCOM-src",
      "url": "https://api.github.com/repos/NOAA-EMC/HYCOM-src"
    },
    "payload": {
      "push_id": 10978986151,
      "size": 66,
      "distinct_size": 1,
      "ref": "refs/heads/emc/develop",
      "head": "8d247021484c5cb7f8ded897c1e2020c028ef7e9",
      "before": "09bdf00e500d99e2b8811c0571258f86c14efc30",
      "commits": [
        {
          "sha": "8c5cc444f5065d5fd8c74582db95c360e0e4a99f",
          "author": {
            "email": "33480590+TillRasmussen@users.noreply.github.com",
            "name": "TRasmussen"
          },
          "message": "Merge pull request #2 from HYCOM/master\n\nUpdate from upstream",
          "distinct": false,
          "url": "https://api.github.com/repos/NOAA-EMC/HYCOM-src/commits/8c5cc444f5065d5fd8c74582db95c360e0e4a99f"
        },
        . . .
      ]
    },
    "public": true,
    "created_at": "2022-09-09T19:58:45Z",
    "org": {
      "id": 37810995,
      "login": "NOAA-EMC",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/NOAA-EMC",
      "avatar_url": "https://avatars.githubusercontent.com/u/37810995?"
    }
  },
  . . .
]
```

**Comment by jkbk2004** [comment]
> The last event in NOAA-EMC/HYCOM-src repo that changed the HEAD of the emc/develop branch from 09bdf00 to 8d24702 was:
> 
> ```json
> [
>   {
>     "id": "23923922315",
>     "type": "PushEvent",
>     "actor": {
>       "id": 11394126,
>       "login": "aerorahul",
>       "display_login": "aerorahul",
>       "gravatar_id": "",
>       "url": "https://api.github.com/users/aerorahul",
>       "avatar_url": "https://avatars.githubusercontent.com/u/11394126?"
>     },
>     "repo": {
>       "id": 389701838,
>       "name": "NOAA-EMC/HYCOM-src",
>       "url": "https://api.github.com/repos/NOAA-EMC/HYCOM-src"
>     },
>     "payload": {
>       "push_id": 10978986151,
>       "size": 66,
>       "distinct_size": 1,
>       "ref": "refs/heads/emc/develop",
>       "head": "8d247021484c5cb7f8ded897c1e2020c028ef7e9",
>       "before": "09bdf00e500d99e2b8811c0571258f86c14efc30",
>       "commits": [
>         {
>           "sha": "8c5cc444f5065d5fd8c74582db95c360e0e4a99f",
>           "author": {
>             "email": "33480590+TillRasmussen@users.noreply.github.com",
>             "name": "TRasmussen"
>           },
>           "message": "Merge pull request #2 from HYCOM/master\n\nUpdate from upstream",
>           "distinct": false,
>           "url": "https://api.github.com/repos/NOAA-EMC/HYCOM-src/commits/8c5cc444f5065d5fd8c74582db95c360e0e4a99f"
>         },
>         . . .
>       ]
>     },
>     "public": true,
>     "created_at": "2022-09-09T19:58:45Z",
>     "org": {
>       "id": 37810995,
>       "login": "NOAA-EMC",
>       "gravatar_id": "",
>       "url": "https://api.github.com/orgs/NOAA-EMC",
>       "avatar_url": "https://avatars.githubusercontent.com/u/37810995?"
>     }
>   },
>   . . .
> ]
> ```

Looks like coaps people from fsu

**Comment by DeniseWorthen** [comment]
@jkbk2004 The FSU folks do not have write permission to the emc fork. Only Bin Liu, Rahul, Jun, Dan Rosen and "the bot" have write permission.

**Comment by jkbk2004** [comment]
@DeniseWorthen so we need to ask hafs to come with urgent pr to sync up hycom, right? But it sounds like they need to evaluate hycom code changes first.

**Comment by DeniseWorthen** [comment]
@jkbk2004 We do not want to update the hycom hash in our fork. Bin Liu will make a force push back to our emc fork to recover our history.

**Comment by BinLiu-NOAA** [comment]
The commit hash of [09bdf00](https://github.com/NOAA-EMC/HYCOM-src/commit/09bdf00e500d99e2b8811c0571258f86c14efc30) has now been forced pushed and restored in NOAA-EMC HYCOM-src fork.
https://github.com/NOAA-EMC/HYCOM-src

**Comment by jiandewang** [comment]
just made a fresh clone, this is what I have now for HYCOM:
* (HEAD detached at 09bdf00) 09bdf00 Add :: symbol to read from nems.configure.Required for ESMF 8bs20+. (#1)
  emc/develop                09bdf00 Add :: symbol to read from nems.configure.Required for ESMF 8bs20+. (#1)

is it suppose to point to emc/develop ? 

UFS code location: /scratch1/NCEPDEV/climate/Jiande.Wang/MOM6-update/MOM6-update-20220902/Final/ufs-weather-model/

**Comment by DeniseWorthen** [comment]
@jiandewang When I do a fresh checkout of UWM, I get the hash for Hycom as [09bdf00](https://github.com/NOAA-EMC/HYCOM-src/commit/09bdf00e500d99e2b8811c0571258f86c14efc30). That is our current hash in the develop branch of UWM. The commit message for that hash is "Add :: symbol to read from nems.configure.Required for ESMF 8bs20+. (#1)".

**Comment by jkbk2004** [comment]
I checked hycom source codes that we used to test against fresh clone. All looks good.

**Comment by jiandewang** [comment]
> @jiandewang When I do a fresh checkout of UWM, I get the hash for Hycom as [09bdf00](https://github.com/NOAA-EMC/HYCOM-src/commit/09bdf00e500d99e2b8811c0571258f86c14efc30). That is our current hash in the develop branch of UWM. The commit message for that hash is "Add :: symbol to read from nems.configure.Required for ESMF 8bs20+. (#1)".

yes I got the same thing. What puzzled me is the location of the *
if you do a git branch -v under HYCOM-interface/HYCOM
* (HEAD detached at 09bdf00) 09bdf00 
  emc/develop                09bdf00 Add :: symbol 

what I mean is the * should located on emc/develop (note here * is showing as dot, but if you do on one of the machine, you will see the *)

**Comment by jiandewang** [comment]
> I checked hycom source codes that we used to test against fresh clone. All looks good.

let me know when it's the time to do submodule switch

**Comment by jkbk2004** [comment]
> > I checked hycom source codes that we used to test against fresh clone. All looks good.
> 
> let me know when it's the time to do submodule switch
@jiandewang please, go ahead to update submodule pointer and revert branch on gitmodules.

**Comment by jiandewang** [comment]
MOM6 submodule switched

**Review by DeniseWorthen — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
