### PR TITLE
Update NEMS and CMEPS, add CDEPS tests, fix bugs in the datm_bulk_gefs test

### LINKED ISSUE #42: Update land-sea masks used in CDEPS for cfsr and gefs data sources
The land-sea masks used in CDEPS for cfsr and gefs data sources are different from those used in NEMS_datm. The file "mediator/med_map_mod.F90" needs to be revised.

### LINKED ISSUE #99: Update NEMS to include CDEPS component
To build the mom6_cice6_cdeps application, the following two files need to be updated:

 1. NEMS/src/module_EARTH_GRID_COM.F90
 2. CMakeLists.txt at ufs-weather-model application level

### LINKED ISSUE #456: Incorrect dimensional settings in datm_bulk_gefs regression test
## Description

In the current datm_bulk_gefs test, IATM is set to 1760 and JATM is set to 880.

The correct settings should be:
IATM=1536
JATM=768

## Additional context
After the regression test for "datm_bulk_gefs" is done, the restart file "DATM_GEFS.cpl.r.2011-10-02-00000.nc" shows incorrect horizontal dimensions for variables from data atmosphere model.

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
1. Update NEMS component for CDEPS data atmosphere model.
2. Update CMEPS to revise land-sea masks used for cfsr and gefs data sources in CDEPS.
3. Update CMakeLists.txt to build the mom6_cice6_cdeps application.
4. Use a new ESMF configuration file for CDEPS model instead of the XML configuration file.
5. Use new input forcing files that are CF-1.0 compliant in time axis.
6. Use new input mesh files that are generated from existing grid files.
7. Add 8 cdeps regression tests.
8. Fix bugs in the datm_bulk_gefs test.

### Issue(s) addressed
fixes: https://github.com/NOAA-EMC/NEMS/issues/99
fixes: https://github.com/NOAA-EMC/CMEPS/issues/42
fixes: https://github.com/ufs-community/ufs-weather-model/issues/456

### Related pull requests
https://github.com/NOAA-EMC/NEMS/pull/92
https://github.com/NOAA-EMC/CMEPS/pull/43

## Testing
Regression tests will be done on Hera, Orion, WCOSS-p3, WCOSS-Cray, Gaea, Jet and Cheyenne.

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Looks like Dom snuck in the rt.sh fix I mentioned in the meeting earlier last week. I will test with the Cheyenne gnu label to make sure we're good.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/work/briancurtis/git/BrianCurtis-NOAA/ufs-weather-model/tests/auto/pr/621044763/20210504073009/ufs-weather-model
Please manually delete: /glade/scratch/briancurtis/FV3_RT/rt_55193
Test fv3_thompson 007 failed in run_test failed 
Test fv3_rrfs_v1alpha 009 failed in run_test failed 
Test fv3_multigases 026 failed in run_test failed 
Test fv3_gsd 006 failed in run_test failed 
Test fv3_rrfs_v1beta 010 failed in run_test failed 
Test fv3_thompson_no_aero 008 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 011 failed in run_test failed 
Test fv3_gfsv16_ugwpv1_warmstart 014 failed in run_test failed 
Test fv3_gfsv16_ugwpv1 013 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 012 failed in run_test failed 
Test fv3_gfs_v16_RRTMGP 005 failed in run_test failed 
Test fv3_gfs_v16 002 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-BL

**Comment by binli2337** [comment]
@BrianCurtis-NOAA Jet-intel baselines have been created.

**Comment by binli2337** [comment]
@BrianCurtis-NOAA Jet-intel tests are running.

**Comment by BrianCurtis-NOAA** [comment]
OK Thanks. Things are looking good so far!

**Comment by binli2337** [comment]
@BrianCurtis-NOAA WCOSS-Cray tests are running too. Thanks.

**Comment by BrianCurtis-NOAA** [comment]
Just checked on the Orion job, it's stuck Pending on the 123 node task.

**Comment by DeniseWorthen** [comment]
is that the only test that is still pending?

**Comment by BrianCurtis-NOAA** [comment]
> is that the only test that is still pending?

Yes

**Comment by DusanJovic-NOAA** [comment]
Requesting 123 nodes (4920 cpus) is a little too much for a (regression) test. I think.

**Comment by junwang-noaa** [comment]
Which test is this?

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/621044763/20210504153013/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_281281
Test fv3_wrtGauss_nemsio_c768 101 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Noting that we've decided to skip the fv3_wrtGauss_nemsio_c768 for now on Orion on purpose.

**Comment by DeniseWorthen** [comment]
both nems and cmeps have been merged so please revert your gitmodules and update. Thanks.

**Comment by MinsukJi-NOAA** [comment]
> both nems and cmeps have been merged so please revert your gitmodules and update. Thanks.

@binli2337 please specify run-ci in the commit message of your latest commit before the push to the Github

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
