### PR TITLE
[FV3] Add a new RT for the SDF FV3_WoFS_v0

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
This PR is created (1) in favor of PR[#1158](https://github.com/ufs-community/ufs-weather-model/pull/1158), which adds a  new suite definition file (FV3_WoFS_v0) to FV3  to use the NSSL cloud microphysics scheme with Noah LSM for the next UFS-SRW v2.1.0 app release.  (2) to add CCPP Scientific Documentation updates for UFS-SRW v2.1.0

This PR adds a new regression test (RT) named regional_3km_wofs, which mainly follows the RT regional_3km.  The settings for namelist parameters possibly have room to optimize. **No baseline changes other than the newly added RT.**

## Testing
The RT regional_3km_wofs is a regional configuration at 3 km grid spacing. The ORT test was successful but only for dcp and thr. The current ORT for the regional configuration doesn't support mpi, rst and debug. 
The log file for ORT test:
baseline dir = /scratch1/NCEPDEV/stmp4/Chunxi.Zhang/FV3_OPNREQ_TEST/OPNREQ_TEST/fv3_regional_3km_wofs_std_base
working dir  = /scratch1/NCEPDEV/stmp2/Chunxi.Zhang/FV3_OPNREQ_TEST/opnReqTest_303105/regional_3km_wofs_dcp
Checking test dcp regional_3km_wofs results ....
 Comparing dynf000.nc .........OK
 Comparing dynf006.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf006.nc .........OK
 Comparing PRSLEV.GrbF00 .........OK
 Comparing PRSLEV.GrbF06 .........OK
 Comparing NATLEV.GrbF00 .........OK
 Comparing NATLEV.GrbF06 .........OK

 0: The total amount of wall time                        = 559.146204
 0: The maximum resident set size (KB)                   = 704192

Test dcp regional_3km_wofs PASS

baseline dir = /scratch1/NCEPDEV/stmp4/Chunxi.Zhang/FV3_OPNREQ_TEST/OPNREQ_TEST/fv3_regional_3km_wofs_std_base
working dir  = /scratch1/NCEPDEV/stmp2/Chunxi.Zhang/FV3_OPNREQ_TEST/opnReqTest_303105/regional_3km_wofs_std_base
Checking test std_base regional_3km_wofs results ....
Moving baseline std_base regional_3km_wofs files ....
 Moving dynf000.nc .........OK
 Moving dynf006.nc .........OK
 Moving phyf000.nc .........OK
 Moving phyf006.nc .........OK
 Moving PRSLEV.GrbF00 .........OK
 Moving PRSLEV.GrbF06 .........OK
 Moving NATLEV.GrbF00 .........OK
 Moving NATLEV.GrbF06 .........OK

  0: The total amount of wall time                        = 338.523577
  0: The maximum resident set size (KB)                   = 629408

Test std_base regional_3km_wofs PASS

baseline dir = /scratch1/NCEPDEV/stmp4/Chunxi.Zhang/FV3_OPNREQ_TEST/OPNREQ_TEST/fv3_regional_3km_wofs_std_base
working dir  = /scratch1/NCEPDEV/stmp2/Chunxi.Zhang/FV3_OPNREQ_TEST/opnReqTest_303105/regional_3km_wofs_thr
Checking test thr regional_3km_wofs results ....
 Comparing dynf000.nc .........OK
 Comparing dynf006.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf006.nc .........OK
 Comparing PRSLEV.GrbF00 .........OK
 Comparing PRSLEV.GrbF06 .........OK
 Comparing NATLEV.GrbF00 .........OK
 Comparing NATLEV.GrbF06 .........OK

  0: The total amount of wall time                        = 233.675934
  0: The maximum resident set size (KB)                   = 494200

Test thr regional_3km_wofs PASS

OPERATION REQUIREMENT TEST WAS SUCCESSFUL

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies
- waiting on noaa-emc/fv3atm/pull/<[594](https://github.com/NOAA-EMC/fv3atm/pull/594)>
- waiting on ufs-community/ccpp-physics/pull/<[14](https://github.com/ufs-community/ccpp-physics/pull/14)>

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]
Looks good to me.

**Comment by DeniseWorthen** [comment]
@ChunxiZhang-NOAA can we close the older PR (#1158)?

**Comment by ChunxiZhang-NOAA** [comment]
@DeniseWorthen Yes, please close the old PR#1158.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA #1443 was merged. Once the branch gets synced, we can start working on this PR. @BrianCurtis-NOAA I will add new BL_DATE and start create new baseline for regional_3km_wofs.

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA #1443 was merged. Once the branch gets synced, we can start working on this PR. @BrianCurtis-NOAA I will add new BL_DATE and start create new baseline for regional_3km_wofs.

@jkbk2004 Ok, thanks. I will sync my branch ASAP.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA can you sync and resolve the conflict? so that we can start working on the PR.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 I am waiting for @mzhangw  to sync her branch because ccpp-physics points to her branch.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 I've synced my branches. It is ready for the commit process.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA thanks! @BrianCurtis-NOAA I will manually create new baseline regional_3km_wofs and start testing from hera and cheyenne.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 you can skip Acorn. It was testing OK when i last checked yesterday afternoon (tests still running), but couldn't get to the logs this AM due to machine limits for today.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA all tests are done. we can start merging in dependencies.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Ok, ccpp-physics #[14](https://github.com/ufs-community/ccpp-physics/pull/14) was merged just now. I will change the pointer for fv3atm first.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA merged [fv3atm pr 594](https://github.com/NOAA-EMC/fv3atm/pull/594). so with hash update and revert gitmodules, we can merge in this pr here.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 @BrianCurtis-NOAA @RatkoVasic-NOAA Done.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
