### PR TITLE
Use HTML comments in github templates

### LINKED ISSUE #1537: Upgrade templates to use HTML comments
## Description
Current UFSWM Templates are helpful but with so many words can get in the way when reading through pull requests and issues.

## Solution
Add comments for help in template sections

## Alternatives
Cleaning up wording, but it seems all information is helpful and should stay.

## Related to
N/A

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Description

This PR brings in template changes to reflect better all that is involved in our pull request tasks and help us process them quicker. It also brings in HTML comments to make the PR/Issues/Bugs appear cleaner on the outside but providing ample information to the submitter.

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [X] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

## Commit Queue Checklist:

- [X] Link PR's from all sub-components involved
- [X] Confirm reviews completed in sub-component PR's
- [X] Add all appropriate labels to this PR.
- [X] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [X] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Closes ufs-community/ufs-weather-model/issues/1537

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
Testing not required.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA I don't understand what "HTML comments" are. Also, where did the information regarding any input data update go? 

For the "anticipated changes", I still think we need to be very explicit about what we expect. It is not until the bottom that you say that we expect a list of any changed tests. I think as it is now, we'll get a lot of single word answers in the top section (yes, no). Can we have something like:

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I don't understand what "HTML comments" are. Also, where did the information regarding any input data update go?

HTML comments are `<!-- (text here) -->` This tells the browser to not show that content similar to how ! in FORTRAN tells the compiler to ignore that line.

Using HTML comments in the templates allows us to provide guidance for filling out the template without needing to be deleted or having all that information clogging the important information we want to see.

The information regarding the input data was held in comments, but your idea has inspired me to make a similar change for input data.

@DeniseWorthen Make sure to checkout the raw code, so you can see the HTML comments: https://raw.githubusercontent.com/BrianCurtis-NOAA/ufs-weather-model/comment_templates/.github/pull_request_template.md

**Comment by DeniseWorthen** [comment]
I see. Thanks. Thanks for adding the input data sections. Do you think the difference between "adding" input data and "changing" input data is clear?

**Comment by jkbk2004** [comment]
was merged with #1535.

**Pull request closed without merging**
