### PR TITLE
Port to stampede2 for XSEDE. skip-ci

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
## Description

Port to stampede2 for XSEDE users.

### Issue(s) addressed

#460
https://github.com/NOAA-EMC/global-workflow/issues/280

## Testing

No testing is required.

On stampede2, the following regression tests have been built and run:

`
COMPILE | SUITES=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled,FV3_GFS_v16_coupled S2S=Y WW3=Y`
`RUN     | cpld_bmark_wave`
`RUN     | cpld_bmarkfrac_wave`
`RUN     | cpld_bmarkfrac_wave_v16
`

## Dependencies

No

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Will we be maintaining a full baseline on Stampede?

**Comment by MinsukJi-NOAA** [comment]
> Will we be maintaining a full baseline on Stampede?

I strongly doubt that. The tests I did on Stampede were just completing the simulations, not comparing with baselines.

**Comment by DeniseWorthen** [comment]
I see. But the use will be primarily Prototype-like runs by groups outside of EMC using a workflow. Is that right?

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen , that is my understanding.

**Comment by climbfuji** [comment]
> @DeniseWorthen , that is my understanding.

I "ported" the ufs-weather-model to stampede twice in the past. If regression tests are not run, who makes sure that the code keeps working there? That didn't even work with Cheyenne, even when it was a tier-2 (post commit regression testing) platform.

**Comment by MinsukJi-NOAA** [comment]
@climbfuji. Good point. As Denise mentioned, groups outside EMC will use the global workflow. Maybe any changes specific to stampede should be in the global-workflow repository? For sure, the changes in rt.sh and fv3_slurm.IN_stampede are not needed. I am not sure if modulefiles/stampede/fv3 is directly used by global workflow either (probably not).

**Review by junwang-noaa — APPROVED** [review]
Code changes look good to me, assuming they were tested on stampede2.

**Comment by MinsukJi-NOAA** [comment]
Changes merged in via #477. Thanks @DusanJovic-NOAA!

**Pull request closed without merging**
