### PR TITLE
Hotfix to update with cubed sphere bug fix 

### PR DESCRIPTION
**Pull request by jkbk2004**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

Random crash for the following regional cases: a floating-point exception in subroutine a2b_ord2 in FV3/atmos_cubed_sphere/model/a2b_edge.F90
 * conus13km_debug_intel
 * conus13km_debug_2threads_intel
 * hafs_regional_storm_following_1nest_atm_ocn_debug_intel

### Commit Message:

```
* UFSWM - 
  * FV3 - 
    * ccpp-physics - 
    * atmos_cubed_sphere - bug fix to address debug mode crashes caused by floating-point exception in subroutine a2b_ord2 in model/a2b_edge.F90
```

### Priority:

* Critical Bugfix: Reason

### UFSWM:

* None

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/858
  * atmos_cubed_sphere: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/349

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
Cubed sphere bug report at: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/346 @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI. I will come list of crashing cases and turn off them.

**Comment by SamuelTrahanNOAA** [comment]
The crashing cases I'm seeing are to test the current operational HAFS and proposed operational RRFS in debug mode. Turning them off really isn't an option. The developer needs to fix this, and the broken changes should be reverse-merged.

**Comment by jkbk2004** [comment]
@XiaqiongZhou-NOAA The crashing issue points to #2327.

**Comment by jkbk2004** [comment]
@XiaqiongZhou-NOAA OOPS! sorry the crashing issue is with https://github.com/ufs-community/ufs-weather-model/pull/2327 you are correct. we don't need to turn off the SFS case.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA This PR is ready.

**Comment by BrianCurtis-NOAA** [comment]
Acorn can be skipped still.

**Comment by zach1221** [comment]
Ok let's start to merge.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
