### PR TITLE
 bug fix: disable concurrency in GFS_phys_time_vary_init NetCDF calls AND #2040 and #2043

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Hercules AND have attached the log to this PR below this line:
  - LOG: committed to branch
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

#### NOTE: Two PRs are included in this one
- #2040 
- #2043

Occasionally, the model will fail in FV3/ccpp/physics/physics/GFS_phys_time_vary.fv3.F90 during the first physics timestep. This is caused by heap corruption earlier, during gfs_phys_time_vary_init. After much debugging, I tracked down the problem.

The NetCDF library is not thread-safe:

- https://docs.unidata.ucar.edu/netcdf-c/current/faq.html#Are-the-netCDF-libraries-thread-safe
> The C-based libraries are not thread-safe. C-based libraries are those that depend on the C library, which currently include all language interfaces except for the Java interface

We're calling a non-thread-safe library in a threaded region. There are multiple NetCDF calls going concurrently. The fix is  to read the NetCDF files one at a time.

## Commit Message
General clean-up, and CCPP concurrency bug fixes
1. Remove nfhout, nfhmax_hf, nfhout_hf and nsout from fv3atm and the regression tests. ( NOAA-EMC/fv3atm/issues/731 )
2. Add comments to smc pert and fix bug in stc pert ( #2042 )
3. Disable concurrency in NetCDF calls within CCPP GFS_phys_time_vary_init subroutine to avoid crashes

### Associated UFSWM Issue to close
These two PRs are combined with this one. They should be closed when this is merged.

- closes #2040 
- closes #2043

### Subcomponent Pull Requests

- https://github.com/NOAA-EMC/fv3atm/pull/735
- https://github.com/NOAA-PSL/stochastic_physics/pull/70 (PR 2043)
- https://github.com/ufs-community/ccpp-physics/pull/138

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [x] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.

### Regression Tests:
- [x] No changes are expected to any regression test.

</details>

### Libraries

- [x] Not Needed

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
This PR is innocuous and self-contained. It can be combined with just about anything. Ideally, it should be merged with PRs that don't change the results.

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA I've been talking with the NetCDF folks and they have been working on a threadsafe NetCDF, and we're just finding out if that work has been merged or will be soon. The process to move to whatever version of NetCDF that is will of course take a while. That was FYI. My question is if this code is easily "reversible" once the thread-safe NetCDF is available?

**Comment by SamuelTrahanNOAA** [comment]
> My question is if this code is easily "reversible" once the thread-safe NetCDF is available?

The thread-safe NetCDF may not be available on all machines. We would need a way to turn on and off threading during that region.

Turning it back on 100% of the time is a simple matter of putting the OpenMP directives back in. I don't think we'll want it on unconditionally.

How to turn it on conditionally... we need to research and design. The NetCDF library would have to be able to report that it is thread safe. (Even if the code is capable of being built thread-safe, it may not necessarily build that way everywhere. It might be a compile-time flag when building the library.) Certainly, we need a flag to force the code to run single-threaded regardless of NetCDF library, in case something goes wrong. And then there's the matter of deciding how to turn off threading in that region.

**Comment by SamuelTrahanNOAA** [comment]
There's one other consideration. We're better off using netcdf-parallel to read across all ranks. It'll stress the filesystem less than we're doing now. Ultimately, it is the fastest option. This would be done at the model level, where we read most fix files already.

**Comment by SamuelTrahanNOAA** [comment]
I've merged the top of #2040 and #2043 into this PR's branch.

Unfortunately, two hashes mismatch for #2043:

- stochastic_physics in https://github.com/ufs-community/ufs-weather-model/pull/2043
- stochastic_physics in https://github.com/NOAA-PSL/stochastic_physics/pull/70

The one in https://github.com/ufs-community/ufs-weather-model/pull/2043 doesn't exist in the repository. I'm pointing to https://github.com/NOAA-PSL/stochastic_physics/pull/70 instead. I need the correct hash from @yuanxue2870 before I continue testing.

**Comment by SamuelTrahanNOAA** [comment]
It turns out this hash is correct:

- https://github.com/NOAA-PSL/stochastic_physics/pull/70

See that page for the discussion.

**Comment by SamuelTrahanNOAA** [comment]
@DusanJovic-NOAA - Could you please confirm I merged your changes into this branch correctly?

**Comment by DusanJovic-NOAA** [comment]
I think you need to update .gitmodules to point to your fv3atm fork/branch.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 @BrianCurtis-NOAA - This PR is ready for testing. Notes:

- This PR now includes #2040
- Also includes #2043
- Due to the combined the stochastic_physics component will update.
- Hera tests have passed; log file is committed.
- I'm also running Jet tests, but they'll take another half hour or more to finish. 184 of 190 tests have passed, 5 are running, and 1 is waiting for a dependency to finish

**Comment by jkbk2004** [comment]
@zach1221 @BrianCurtis-NOAA @FernandoAndrade-NOAA FYI: this pr is ready to commit today.

**Comment by SamuelTrahanNOAA** [comment]
My Jet regression tests finished. I've committed those logs. That means:

1. Hera passed for me
2. Jet passed for me

Independent testing is important. UFS code managers should retest both systems.

**Comment by jkbk2004** [comment]
Sure! @SamuelTrahanNOAA we will proceed to test on the rest of the machines.

**Comment by SamuelTrahanNOAA** [comment]
> Sure! @SamuelTrahanNOAA we will proceed to test on the rest of the machines.

@jkbk2004 - I may have been unclear in my statement. I was asking you to retest Jet and Hera.

> Independent testing is important. UFS code managers should retest both systems.

**Comment by jkbk2004** [comment]
> > Sure! @SamuelTrahanNOAA we will proceed to test on the rest of the machines.
> 
> @jkbk2004 - I may have been unclear in my statement. I was asking you to retest Jet and Hera.
> 
> > Independent testing is important. UFS code managers should retest both systems.

@SamuelTrahanNOAA Yeah, we are catching up now.

**Comment by SamuelTrahanNOAA** [comment]
> Jenkins-ci ORTs failed

Can someone provide details?

@DusanJovic-NOAA changed parts of the regression test system. That's the only way I can conceive of this PR breaking jenkins.

**Comment by DusanJovic-NOAA** [comment]
My branch (remove_nfhout) is one commit behind the develop. I need up merge it with develop and resolve any potential conflict if there are any.
Where is the Jenkins-ci ORTs log file? Which test(s) is Jenkins running?

**Comment by SamuelTrahanNOAA** [comment]
> My branch (remove_nfhout) is one commit behind the develop. I need up merge it with develop and resolve any potential conflict if there are any.

I updated the combined branch to develop. There was a conflict in rt_utils.sh, but it appeared to be whitespace differences.

**Comment by zach1221** [comment]
> My branch (remove_nfhout) is one commit behind the develop. I need up merge it with develop and resolve any potential conflict if there are any. Where is the Jenkins-ci ORTs log file? Which test(s) is Jenkins running?

Error from jenkins-ci, looks like all the ORTs failed with the same error.
/home/builder/ufs-weather-model/tests/opnReqTests/wrt_env.sh: line 1: NFHOUT: unbound variable

**Comment by SamuelTrahanNOAA** [comment]
> > My branch (remove_nfhout) is one commit behind the develop. I need up merge it with develop and resolve any potential conflict if there are any. Where is the Jenkins-ci ORTs log file? Which test(s) is Jenkins running?
> 
> Error from jenkins-ci, looks like all the ORTs failed with the same error. /home/builder/ufs-weather-model/tests/opnReqTests/wrt_env.sh: line 1: NFHOUT: unbound variable

Please try again. I removed the old variables from opnReqTests.

**Comment by zach1221** [comment]
I'm still getting a failure for regional_atmaq on Gaea C5, here:
/lustre/f2/scratch/Zachary.Shrader/FV3_RT/rt_151345/regional_atmaq_intel/ , where the srun just terminates.
Edit: attempting to adjust the TPN in the tests/tests/regional_atmaq file to see if that resolves

And the regional_netcdf_parallel_intel failure on Hercules from issue [2015](https://github.com/ufs-community/ufs-weather-model/issues/2015) continues, and I haven't been able to get it to pass yet. It seems to be more persistent than in the past.
Edit:  there may be a missing baseline for regional_netcdf_parallel_intel on hercules.

**Comment by SamuelTrahanNOAA** [comment]
> I'm still getting a failure for regional_atmaq on Gaea C5, here: /lustre/f2/scratch/Zachary.Shrader/FV3_RT/rt_151345/regional_atmaq_intel/ , where the srun just terminates. Edit: attempting to adjust the TPN in the tests/tests/regional_atmaq file to see if that resolves

Nothing in this PR should affect that job.

I have a ticket open for a similar UPP failure. With certain inputs, UPP will freeze forever in MPI_Finalize. This only happens on GAEA-C5. The admins have passed the ticket on to the vendor. I haven't heard back in several weeks.

> And the regional_netcdf_parallel_intel failure on Hercules from issue [2015](https://github.com/ufs-community/ufs-weather-model/issues/2015) continues, and I haven't been able to get it to pass yet. It seems to be more persistent than in the past. Edit: there may be a missing baseline for regional_netcdf_parallel_intel on hercules.

The NetCDF fixes in here are for *reading* NetCDF files, not writing. I don't expect it to fix #2015

**Comment by zach1221** [comment]
Ok I think we're ready now to begin the merging process.

**Comment by SamuelTrahanNOAA** [comment]
I added a commit message to the PR description:

```
General clean-up, and CCPP concurrency bug fixes
1. Remove nfhout, nfhmax_hf, nfhout_hf and nsout from fv3atm and the regression tests.
2. Add comments to smc pert and fix bug in stc pert
3. Disable concurrency in NetCDF calls within CCPP GFS_phys_time_vary_init subroutine to avoid crashes
```

**Comment by SamuelTrahanNOAA** [comment]
Could @DusanJovic-NOAA and @yuanxue2870 please review the commit message?

```
General clean-up, and CCPP concurrency bug fixes
1. Remove nfhout, nfhmax_hf, nfhout_hf and nsout from fv3atm and the regression tests.
2. Add comments to smc pert and fix bug in stc pert
3. Disable concurrency in NetCDF calls within CCPP GFS_phys_time_vary_init subroutine to avoid crashes
```

When this PR is merged, that text will be the description of the changes recorded forever in the repository.

**Comment by DeniseWorthen** [comment]
@SamuelTrahanNOAA You make a good point about "combined" PRs. In the future, the PR selected to carry the individual PRs will be able to just grab and add.

**Comment by DusanJovic-NOAA** [comment]
> Could @DusanJovic-NOAA and @yuanxue2870 please review the commit message?
> 
> ```
> General clean-up, and CCPP concurrency bug fixes
> 1. Remove nfhout, nfhmax_hf, nfhout_hf and nsout from fv3atm and the regression tests.
> 2. Add comments to smc pert and fix bug in stc pert
> 3. Disable concurrency in NetCDF calls within CCPP GFS_phys_time_vary_init subroutine to avoid crashes
> ```
> 
> When this PR is merged, that text will be the description of the changes recorded forever in the repository.

Looks good.

**Comment by yuanxue2870** [comment]
Looks good to me.

Thanks,
Yuan

-------------------------------------------------

Yuan Xue

Physical Scientist III - Land Data Assimilation

Lynker at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Rm. 2870

College Park, MD 20740

***@***.***

-------------------------------------------------

**Comment by BrianCurtis-NOAA** [comment]
General question here about commit messages, since this PR is next. Should we include in all commit messages which subcomponents were changed, say a line like "Components Updated: FV3, stochastic physics" ?

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA I've made changes to your commit messages as I want to see how the links for the issues travel inside the commit message. I hope that this works.

**Comment by SamuelTrahanNOAA** [comment]
This PR is ready for final testing and merge. I have reverted .gitmodules. All subcomponent hashes match the head of their correct branch.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
