### PR TITLE
Update CMEPS for HAFS integration; Add datm-mom6-cice6 and coupled-model tests on Gaea

### LINKED ISSUE #317: Create baselines on Gaea for the coupled and datm tests
## Description
RT baseline will be created for the coupled tests and datm-mom6-cice6 tests on Gaea.

## Solution
The RT baseline will be located at /lustre/f2/pdata/esrl/gsd/ufs/ufs-weather-model on Gaea.

In the future, new baseline directories will be created whenever simulation results are changed due to updates in the develop branch of ufs-weather-model.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

* Update NOAA-EMC/CMEPS for recent merge of support/HAFS branch at ESCOMP/CMEPS.
* Updates CMEPS-interface/CMakeList.txt after the CMEPS/nems/util subdirectory was moved to CMEPS/util. 
* Adds coupled and datm tests for Gaea.intel

### Issue(s) addressed

CMEPS Issue [#32](https://github.com/NOAA-EMC/CMEPS/issues/32)
ufs-weather-model Issue #406 

## Testing

The update has been tested on Cheyenne.Intel and is bit-identical to current baselines. 
## Dependencies

CMEPS PR [#33](https://github.com/NOAA-EMC/CMEPS/pull/33)

co-author: @binli2337

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
Hi @DeniseWorthen, Following Friday's discussion, do you want to combine this pull request with the HAFS CMEPS/CDEPS related NEMS updates (which does not change results either)? If so, I will work with @danrosen25 and Ufuk to make the NEMS fork/branch ready so that you can point to that branch. Thanks! -Bin

**Comment by DeniseWorthen** [comment]
Thanks @BinLiu-NOAA Would you prefer to make a PR from your own ufs-weather fork for both the NEMS and CMEPS changes? That makes more sense since you can fully document the changes and credit the folks who did the work.

**Comment by BinLiu-NOAA** [comment]
> Thanks @BinLiu-NOAA Would you prefer to make a PR from your own ufs-weather fork for both the NEMS and CMEPS changes? That makes more sense since you can fully document the changes and credit the folks who did the work.

Thanks, @DeniseWorthen! Either way would work fine for us. I am having a conversation with Dan R. and Ufuk on this this afternoon. Will try to follow up after discussing with them. Thanks! - Bin

**Comment by BinLiu-NOAA** [comment]
Hi @DeniseWorthen and @junwang-noaa, I had some conversations and discussions with @uturuncoglu (Ufuk) and @danrosen25 yesterday. With the Friday afternoon's PIO related discussions, Ufuk is still working on the PIO related changes for CDEPS/CMEPS coupling for NEMS. Most likely, it will not be ready by this Friday. With that, @DeniseWorthen, please feel free to just update the CMEPS in this pull request. We will work on another pull request for the HAFS/CDEPS/CMEPS/NEMS related changes in the future. Thanks! - Bin

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
I've had a single test failure on Gaea (2 remaining). The cpld_bmark_v16 test failed with an error:

fv3.exe            0000000001B1B311  esmfpio_spmd_util         343  pio_spmd_utils.F90.in
fv3.exe            0000000001AED63E  esmfbox_rearrange         305  box_rearrange.F90.in
fv3.exe            0000000001A9B666  esmfrearrange_mp_          80  rearrange.F90.in

I tried copying the run directory and running that test again and it failed in the same way.

**Comment by climbfuji** [comment]
> I've had a single test failure on Gaea (2 remaining). The cpld_bmark_v16 test failed with an error:
> 
> fv3.exe 0000000001B1B311 esmfpio_spmd_util 343 pio_spmd_utils.F90.in
> fv3.exe 0000000001AED63E esmfbox_rearrange 305 box_rearrange.F90.in
> fv3.exe 0000000001A9B666 esmfrearrange_mp_ 80 rearrange.F90.in
> 
> I tried copying the run directory and running that test again and it failed in the same way.

Oh oh ... better ask @edwardhartnett for help.

**Comment by DeniseWorthen** [comment]
Final tests are re-running on Gaea.

**Review by climbfuji — APPROVED** [review]
Approved - but needs updating CMEPS, reversing the `.gitmodules` change and the new gaea log file.

**Pull request merged**
