### PR TITLE
Update modules with hpc-stack v1.1.0

### PR DESCRIPTION
**Pull request by kgerheiser**
hpc-stack v1.1.0 has been installed and tested on Orion, Hera (GNU and Intel), WCOSS Dell and WCOSS Cray.

## Description

Update modules to use hpc-stack v1.1.0

### Issue(s) addressed

The model has been using an unofficial test version of hpc-stack

## Testing

The full set of regression tests was run on all machines included in this PR, and all passed.

Orion, Hera (GNU and Intel), WCOSS Dell and WCOSS Cray.

## Note

There is an issue with WCOSS Dell. On that machine `LMOD_EXACT_MATCH` is set to `yes`. That causes problems when trying to load the `fv3` module (when it loads NetCDF). `LMOD_EXACT_MATCH` is set from the default loaded module `EnvVars/1.0.3`. 

Running `module unload EnvVars/1.0.3`, or `setenv LMOD_EXACT_MATCH no` from within the `fv3` module does not work. However, running it from your shell and then loading `fv3` does work. The regression tests run `module purge` before loading so they aren't affected.

This means that if you want to manually load `fv3`, you either unload `EnvVars/1.0.3` or set `LMOD_EXACT_MATCH=no` before.

Any advice on this?

### CODE REVIEW

**Comment by junwang-noaa** [comment]
In general, we do ask developers to do "module purge" before load fv3 as you never know what user's env is, there might be many conflicted modules loaded.

**Comment by climbfuji** [comment]
> In general, we do ask developers to do "module purge" before load fv3 as you never know what user's env is, there might be many conflicted modules loaded.

Except for gaea. You cannot do module purge there or your environment is broken. I have been/am making sure that the module files contain the necessary switches.

@kgerheiser you'll soon see a PR from me to your `feature/hpc-v1.1.0` branch with the updates for Cheyenne and Gaea. 

We'll need to rerun the regression tests once it is your turn in the commit queue.

**Comment by DusanJovic-NOAA** [comment]
Will this version be installed on WCOSS2 Acorn?

**Comment by kgerheiser** [comment]
I'm sure we can get something on Acorn. I haven't tried it myself, but I know other people have.

There's an in-progress PR to bring hpc-stack to WCOSS2.

Update: 

Trying it now

**Comment by climbfuji** [comment]
@kgerheiser please merge my PR https://github.com/kgerheiser/ufs-weather-model/pull/1 into your branch - thanks!

**Comment by kgerheiser** [comment]
@DusanJovic-NOAA I was able to get hpc-stack with LMod to build on WCOSS2. I'll do an official installation next week.

**Comment by kgerheiser** [comment]
@DusanJovic-NOAA 

hpc-stack v1.1.0 is available on WCOSS2 at `module use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/v1.1.0/modulefiles/stack`

**Comment by climbfuji** [comment]
@kgerheiser this PR is scheduled for Friday 12/18/2020, together with minor bugfixes for the CCPP Unified Gravity Wave Drag parameterization. The update should require a new baseline on hera (date tag in `rt.sh` will likely be `develop-20201218`), for all other platforms we should be able to copy over the at that time current baselines.

Please pull in the latest code changes from the ufs-weather-model develop (on Thursday after https://github.com/ufs-community/ufs-weather-model/pull/323 was merged), update `.gitmodules` and the submodule pointer for fv3atm to point to https://github.com/climbfuji/fv3atm, branch "ugwp_bugfix_fv3atm" (this is a temporary change that will be reverted and the submodule pointer updated after the fv3atm PR was merged). See https://github.com/NOAA-EMC/fv3atm/pull/216.

**Review by junwang-noaa — COMMENTED** [review]
It seems jet module file is missing. Otherwise, it is good.

**Comment by kgerheiser** [comment]
Dom included that in a different commit where he fixed something else on Jet.

**Comment by climbfuji** [comment]
> Dom included that in a different commit where he fixed something else on Jet.

That's right. The modulefile still says
```
# At this time (2020/11/30), this is the pre-release version 1.0.0
```
but it is actually the final version (because the pre-release was declared the release after all tests passed on the various platforms). I suggest removing that one line. (ignore that it says 1.0.0 when it actually is 1.1.0)

**Comment by climbfuji** [comment]
@kgerheiser it is time to start updating your branch, if possible. We have just one more round of commits to come in before it is turn for your commit (with Mike's ccpp-physics/my fv3atm branches). I updated the fv3atm PR yesterday. Do you know what to do?

**Comment by kgerheiser** [comment]
Alright, so I re-based my commits to the head of develop and have the latest changes. I also need to point to a different fv3 submodule?

**Comment by climbfuji** [comment]
> Alright, so I re-based my commits to the head of develop and have the latest changes. I also need to point to a different fv3 submodule?

Yes please:
```
cd FV3
git remote add dom https://github.com/climbfuji/fv3atm
git remote update
git checkout dom/ugwp_bugfix_fv3atm
cd ..

# edit .gitmodules and change the FV3 section so that it reads:
[submodule "FV3"]
  path = FV3
  url = https://github.com/climbfuji/fv3atm
  branch = ugwp_bugfix_fv3atm

git add FV3 .gitmodules
git commit -m "Update .gitmodules and submodule pointer for fv3atm for code review and testing"
git push your_fork your_branch
```
Make sense?

**Comment by kgerheiser** [comment]
Done

**Comment by climbfuji** [comment]
> Done

Looks great, thanks! Once the current PRs are in, I will update fv3atm one more time. You'll need to check out my branch again and update the submodule pointer, and pull in the latest changes into ufs-weather-model. Should be ready in a few hours, I'll let you know.

**Comment by climbfuji** [comment]
@kgerheiser I updated fv3atm - the new hash is 067e1ce593b059bbe6235b95e59f4d9c69aef84a. Can you please check out the latest version of my fv3atm branch and update the submodule pointer in your ufs-weather-model PR. Thanks!

**Comment by kgerheiser** [comment]
Done

**Comment by climbfuji** [comment]
Note. Because of the changes in https://github.com/NCAR/ccpp-physics/pull/532, the results for the two tests `fv3_ccpp_rap` and `fv3_ccpp_hrrr` will change. This tests are only run on hera.intel.

**Comment by junwang-noaa** [comment]
Dom, Can you explain why the results of the two tests will change?
According to the comments in #532, unified_ugwp.F90 change doesn't alter
results. Change in drag_suite.F90 will not have impact unless the
gsd_diss_ht_opt is hardcoded to 1 in the drag_suite.F90 as it is a local
variable. Maybe I missed something?

**Comment by climbfuji** [comment]
I misread the comment from @mdtoy. There should be no baseline change then. Will confirm first thing when the ufs-weather-model PR has been updated.

**Comment by climbfuji** [comment]
@kgerheiser ufs-weather-model has just been updated. Please pull in the latest changes from develop and push to your PR. 

Note that I was probably mistaken about the baseline results change, looks like we do not need to create a new one (testing now).

**Comment by climbfuji** [comment]
Update and correction of my previous statement. No baseline change. I ran the following tests on hera.intel with the fv3atm/ccpp-physics changes, and the results are b4b identical with the 20201217 baseline:
```
COMPILE | CCPP=Y SUITES=FV3_GFS_2017_gfdlmp,FV3_CPT_v0,FV3_GSD_v0,FV3_GFS_v15_thompson,FV3_RAP,FV3_HRRR,FV3_RRFS_v1beta 32BIT=Y
RUN     | fv3_ccpp_gfdlmp_32bit                                                                                                
RUN     | fv3_ccpp_gfdlmprad_32bit_post                                                                                        
RUN     | fv3_ccpp_cpt                                                                                                         
RUN     | fv3_ccpp_gsd                                                                                                         
RUN     | fv3_ccpp_rap                                                                                                         
RUN     | fv3_ccpp_hrrr                                                                                                        
RUN     | fv3_ccpp_thompson                                                                                                    
RUN     | fv3_ccpp_thompson_no_aero                                                                                            
RUN     | fv3_ccpp_rrfs_v1beta                                                                                                 
```
Thanks, @junwang-noaa for correcting me.

**Comment by kgerheiser** [comment]
Done

Does everything look correct? FV3 should point back to the actual repository now, right?

Should I cleanup the branch history at all?

**Comment by climbfuji** [comment]
> Done
> 
> Does everything look correct? FV3 should point back to the actual repository now, right?
> 
> Should I cleanup the branch history at all?

Actually, no. fv3atm still needs to point to my PR (hash 067e1ce593b059bbe6235b95e59f4d9c69aef84a), same as `.gitmodules`. No need to cleanup the history, this will be done in the squashed merge. Thanks!

**Comment by climbfuji** [comment]
Thanks, Kyle, looks good now.

**Comment by climbfuji** [comment]
I will run the tests for: hera.{gnu,intel}, cheyenne.{gnu,intel}. jet.intel, gaea.intel, orion.intel - somebody needs to do wcoss_cray and wcoss_dell_p3, please. @junwang-noaa @DusanJovic-NOAA

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA <https://github.com/DusanJovic-NOAA>can you help?

**Comment by climbfuji** [comment]
Note: gaea is not behaving well today (filesystem issues, as per email from the sysadmins last night). We may have to skip that platform if they don't fix it in time.

**Comment by DusanJovic-NOAA** [comment]
I'll run tests on Cray and Dell.

**Comment by climbfuji** [comment]
Update. So far I have completed:
```
	modified:   tests/RegressionTests_cheyenne.gnu.log
	modified:   tests/RegressionTests_cheyenne.intel.log
	modified:   tests/RegressionTests_hera.gnu.log
	modified:   tests/RegressionTests_hera.intel.log
	modified:   tests/RegressionTests_orion.intel.log
```
Will wait for jet before sending those to @kgerheiser

**Comment by climbfuji** [comment]
Update: jet.intel tests finished. I will merge ccpp-physics now and update my fv3atm submodule pointer. Once the fv3atm PR is merged, I will send a PR to @kgerheiser with my log files, Dusan's log files (please send them me), and the fv3atm/`.gitmodules` update. This should kick off the final CI tests when it gets merged.

**Review by junwang-noaa — APPROVED** [review]
fv3 needs to point back to the EMC develop branch.

**Comment by climbfuji** [comment]
> fv3 needs to point back to the EMC develop branch.

I'll take care of this when I send Kyle my regression test logs (after I got the wcoss logs from Dusan).

**Comment by climbfuji** [comment]
@kgerheiser please merge https://github.com/kgerheiser/ufs-weather-model/pull/2 into your branch, final step for this PR. Thanks!

**Comment by kgerheiser** [comment]
Merged

**Comment by climbfuji** [comment]
> Merged

Thanks! All we have to do now is wait for 150mins or so until the tests are complete. Happy weekend and Happy Holidays!

**Comment by climbfuji** [comment]
gaea seems to have recovered. I am running the tests now just for the sake of completeness. If it works, I'll just attach them to this PR in form of a comment.

**Comment by climbfuji** [comment]
> gaea seems to have recovered. I am running the tests now just for the sake of completeness. If it works, I'll just attach them to this PR in form of a comment.

Regression tests on gaea passed. Attaching here.

[RegressionTests_gaea.intel.log](https://github.com/ufs-community/ufs-weather-model/files/5718182/RegressionTests_gaea.intel.log)

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
@DusanJovic-NOAA Green light - CI tests passed, Jun and I already approved.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
