### PR TITLE
CCPP updates: UGWPv1 decomp bug fixes, remove Julie from CODEOWNERS; bug fix in tests/run_compile.sh

### LINKED ISSUE #742: control_ugwpv1 fails when changing the decomp
## Description

Changing the decomp in the ``control_ugwpv1`` test and running against the current baseline fails. 

This was found while developing the the update to the low resolution coupled tests (which use ugwpv1,noahmp,nsst) and includes both cpld_decomp, cpld_2threads tests. The test version of cpld_decomp failed. 

To determine the cause, I added a decomp change to the ``control_noahmp`` and the ``control_ugwpv1`` test for the develop branch. The ``control_noahmp`` test passed with the decomp change, but the ``control_ugwpv1`` test failed:

```
baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20210805/INTEL/control_ugwpv1
working dir  = /scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_15393/control_ugwpv1
Checking test 002 control_ugwpv1 results ....
 Comparing sfcf000.nc ............ALT CHECK......NOT OK
 Comparing sfcf024.nc ............ALT CHECK......NOT OK
 Comparing atmf000.nc ............ALT CHECK......NOT OK
 Comparing atmf024.nc ............ALT CHECK......NOT OK
 Comparing GFSFLX.GrbF00 .........NOT OK
 Comparing GFSFLX.GrbF24 .........NOT OK
 Comparing GFSPRS.GrbF00 .........NOT OK
 Comparing GFSPRS.GrbF24 .........NOT OK

  0: The total amount of wall time                        = 462.757400

Test 002 control_ugwpv1 FAIL
```

### To Reproduce:

Check out the develop branch. Add the following decomp change to the control_ugwpv1 test and run the test against the current baseline.

```
diff --git a/tests/tests/control_ugwpv1 b/tests/tests/control_ugwpv1
index 773e5ae..764425d 100644
--- a/tests/tests/control_ugwpv1
+++ b/tests/tests/control_ugwpv1
@@ -33,6 +33,9 @@ export IAER=5111
 export WLCLK=30
 export DO_UGWP_V1=.T.

+export INPES=6
+export JNPES=4
+
 export FV3_RUN=control_run.IN
 export CCPP_SUITE=FV3_GFS_v16_ugwpv1
 export INPUT_NML=control_ugwpv1.nml.IN
```

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

Update submodule pointer for fv3atm for the changes described in the associated PRs below:

- Substantial changes in UGWPv1 to fix problem of lack of reproducibility when changing the domain decomposition layout.
- Remove Julie from `CODEOWNERS` files in both ccpp-framework and ccpp-physics.

See https://github.com/NCAR/ccpp-physics/pull/728 for a detailed description of the UGWPv1 updates.

Also: bug fix in `tests/run_compile.sh` to correctly catch failed compile jobs (e.g. when the disk runs full) from @DusanJovic-NOAA 

No new input data required, but the results for the following regression tests will change:

- For GNU:
```
control_ugwpv1
control_ugwpv1_debug
```
- For Intel:
```
control_ugwpv1
control_ugwpv1_debug
cpld_bmark_wave_v16_p7b
fv3_hrrr
fv3_rap
```
These baseline changes are expected, because all of these tests utilize UGWPv1.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/742

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [X] CI - https://github.com/ufs-community/ufs-weather-model/pull/835/commits/52ddbce76229651de3d5ef469aa15550a251ac36

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/747
- waiting on https://github.com/NCAR/ccpp-framework/pull/402
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/402

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/745008573/20210928191514/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_16035
Test control_thompson_extdiag_debug 076 failed failed 
Test control_thompson_extdiag_debug 076 failed in run_test failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: hera
> Compiler: intel
> Job: RT
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/745008573/20210928191514/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_16035
> Test control_thompson_extdiag_debug 076 failed failed
> Test control_thompson_extdiag_debug 076 failed in run_test failed
> Test cpld_bmark_v16 010 failed failed
> Test cpld_bmark_v16 010 failed in run_test failed
> Please make changes and add the following label back:
> hera-intel-RT

Both jobs hang right at the beginning, a slurm issue? Will recover the regression test log file, rerun those two jobs manually, append to the log file and commit.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/745008573/20210928140009/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_304452
Test control_c384gdas_wav 093 failed failed 
Test control_c384gdas_wav 093 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: orion
> Compiler: intel
> Job: BL
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/745008573/20210928140009/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_304452
> Test control_c384gdas_wav 093 failed failed
> Test control_c384gdas_wav 093 failed in run_test failed
> Please make changes and add the following label back:
> orion-intel-BL

Timeout ... and somehow a weird message about out of memory. Something to keep in mind, just in case this happens again:
```
...
33 min. TEST 093 control_c384gdas_wav is running,  status: R jobid 3214774
Slurm unknown status -. Check sacct ...
3214774                   TIMEOUT        rt_304452_093
3214774.bat+            CANCELLED                batch
3214774.ext+        OUT_OF_MEMORY               extern
3214774.0                  FAILED              fv3.exe
34 min. TEST 093 control_c384gdas_wav is TIMEOUT,  status: - jobid 3214774
```

EDIT: This was the baseline creation step, and everything is under @BrianCurtis-NOAA's user/permissions ... will create baseline again, manually ...

**Comment by DeniseWorthen** [comment]
So auto-RT works on orion because nothing needs to be moved, but auto-BL does not work on orion, correct?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
> So auto-RT works on orion because nothing needs to be moved, but auto-BL does not work on orion, correct?

Well, the one test failed because of a timeout, but I couldn't access the remaining baseline that was created under Brian's stmp directory. Otherwise I would have copied that, rerun only the one job to create the missing baseline, and then verify against it. Now I had to create the entire baseline again.

**Review by junwang-noaa — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by climbfuji** [comment]
fv3atm hash correct, ready to merge

**Pull request merged**
