### PR TITLE
support ufs-weather-model using Rocky 8 on CSPs

### LINKED ISSUE #2455: Support ufs-weather-model using Rocky 8 on CSPs
## Description
With CSPs current default OS is Rocky 8, and PW will stop support CentOS on CSPs from 1/1/2025, we need to make ufs-weather-model to support Rocky 8 on CSPs.

## Solution
Modify CSPs (noaacloud) module to use spack-stack compiled with Rocky 8.

## Alternatives
N/A

## Related to
https://github.com/NOAA-EMC/UPP/pull/1034 (Already merged).

### PR DESCRIPTION
**Pull request by weihuang-jedi**
## Description:
Support ufs-weather-model using Rocky 8 on CSPs, with current ParallelWorks default OS is Rocky 8, and will only support Rocky 8 after 1/1/2025.

### Commit Message:
Have already merged the changes for UPP.

* UFSWM - 
  * FV3 - 
    * upp - (changed committed)

### Priority:

* Normal

## Git Tracking

* Closes https://github.com/ufs-community/ufs-weather-model/issues/2455

### Sub component Pull Requests:

* FV3:
  * upp https://github.com/NOAA-EMC/UPP/pull/1034

### UFSWM Blocking Dependencies:

* None

---
## Changes

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

- spack-stack Rocky 8 on CSPs

  

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by zach1221** [comment]
Hi, @weihuang-jedi were you able to get the RTs to run on one of the CSPs? The test cases are compiling but failing during the actual test run on AWS Rocky 8 with the below now.

"/lustre/stmp2/Zachary.Shrader/FV3_RT/rt_22966/control_c384_intel" has too many
non-modulefiles (159). Please make sure that modulefiles are in their own
directory and not mixed in with non-modulefiles (e.g. source code)"

**Comment by zach1221** [comment]
@jkbk2004 @FernandoAndrade-NOAA I think this PR is ready. Feel free to combine it with another.

**Comment by aerorahul** [comment]
@jkbk2004 can we get an estimate on when this PR may be merged?  This PR is required in support of SFS applications on the cloud.

**Review by aerorahul — APPROVED** [review]
lgtm

**Comment by jkbk2004** [comment]
@aerorahul Sorry for delay! We can combine this pr to next one (likely #2461) and plan to merge by Monday or at least by Tuesday morning. Is it ok?

**Comment by jkbk2004** [comment]
@weihuang-jedi can you sync up branch?

**Comment by weihuang-jedi** [comment]
Resynced with develop on 11/12/24.

**Comment by jkbk2004** [comment]
merged with #2461

**Pull request closed without merging**
