### PR TITLE
Hafs moving nest grid debug test

### LINKED ISSUE #1588: hafs_regional_storm_following_1nest_atm_ocn failed with debug test
## Description
Hafs group reported that the hafs_regional_storm_following_1nest_atm_ocn test failed in debug mode. The error showed in the moving nest lat info in the module_wrt_grid_comp.F90. 

### To Reproduce:
From Biju:
I ran regression tests with "hafs_regional_storm_following_1nest_atm_ocn_wav" and "hafs_regional_storm_following_1nest_atm_ocn" with DEBUG flag on.

The first one (hafs_regional_storm_following_1nest_atm_ocn_wav) completed successfully, but the second one(hafs_regional_storm_following_1nest_atm_ocn) failed with the error: 

forrtl: error (72): floating overflow
Image              PC                Routine            Line        Source
fv3.exe            000000000FDCDAAB  Unknown               Unknown  Unknown
libpthread-2.31.s  000014EB7A0AF8C0  Unknown               Unknown  Unknown
fv3.exe            0000000005C1454B  module_wrt_grid_c         759  module_wrt_grid_comp.F90

One difference I noticed between these two runs is that in the first one, the output_grid is (rotated_latlon,rotated_latlon), while in the second one, the output_grid is (regional_latlon, regional_latlon_moving).

### PR DESCRIPTION
**Pull request by junwang-noaa**
## Description
This PR fixes the issue with the initialization of the moving nest output grid on write grid component.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 
- [x] a new test is added: hafs_regional_storm_following_1nest_atm_ocn_debug

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE6
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Depends on:  https://github.com/NOAA-EMC/fv3atm/pull/622
Closes https://github.com/ufs-community/ufs-weather-model/issues/1588

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [x] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@BinLiu-NOAA @BijuThomas-NOAA @ZhanZhang-NOAA FYI.

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa We're only missing ORT results for the new test and to verify that you have run the full RT suite somewhere.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA The test being added is actually an ORT itself.

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa, Thanks for quickly fixing this issue! The code/script changes and the added HAFS debug test look good to me. @BijuThomas-NOAA, could you please help to conduct a test from your end to confirm the debug build can now work fine for the HAFS moving-nesting configuration with the regional_latlon_moving output grid option? Thanks!

**Comment by BijuThomas-NOAA** [comment]
@junwang-noaa Thanks for the fix!  I tested debug build with regional_storm_following_1nest_atm_ocn_debug  (output_grid: regional_latlon) on Orion and the test was completed successfully

**Review by BinLiu-NOAA — APPROVED** [review]
Thanks for quickly fixing this! The code/script changes and the added HAFS debug test look good to me.

**Comment by jkbk2004** [comment]
@junwang-noaa can you sync up? @jiandewang will pick up from there.

**Comment by jkbk2004** [comment]
@jiandewang is quick. BTW, @junwang-noaa can you create a direct pr to https://github.com/jiandewang/ufs-weather-model/tree/feature/update-MOM6-20230206 ? I think that's a quickest way to combine the PRs.

**Comment by jiandewang** [comment]
> @jiandewang is quick. BTW, @junwang-noaa can you create a direct pr to https://github.com/jiandewang/ufs-weather-model/tree/feature/update-MOM6-20230206 ? I think that's a quickest way to combine the PRs.

just merged, Jun works as fast as lighting, same for me. Now we have a clean PR

**Comment by jkbk2004** [comment]
merged with #1606

**Pull request closed without merging**
