### PR TITLE
Update WW3: Sync develop branch to dev/ufs-weather-model branch - 2023-jun-27

### LINKED ISSUE #1808: WW3:  Update dev/ufs-weather-model branch with develop
## Description
The WW3 component needs it's `dev/ufs-weather-model` branch to have updates from the `develop` branch since last sync.

## Solution
Sync the WW3 `dev/ufs-weather-model` branch with current `develop`.

## Alternatives
NA.

## Related to
- required to support noaa-emc/ww3/issues/1028

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
## Description
Updates the WW3 component by syncing changes in the `develop` branch to the `dev/ufs-weather-model` branch.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):
NA

## Commit Queue Checklist:
- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Depends on NOAA-EMC/WW3/pull/1029
- Closes #1808

## Testing Day Checklist:
- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

* Tested on `hera`, `intel`/`gnu`:
  * _Note:  The logs below capture the successful completion of all RT's. In the first run, all RT's were successful in (i.)  **except** RT (234) `cpld_control_p8_gnu`, which was terminated due to time limit.  This is confirmed by the `err` log in (ii.).  Lastly, `cpld_control_p8_gnu` was re-ran and completed successfully as confirmed in (iii.)._ 
  1. [FAIL-cpld_control_p8_gnu-RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/11896209/FAIL-cpld_control_p8_gnu-RegressionTests_hera.log.txt)
  2. [TIMEOUT-cpld_control_p8_gnu-err.txt](https://github.com/ufs-community/ufs-weather-model/files/11896214/TIMEOUT-cpld_control_p8_gnu-err.txt)
  3. [PASS-cpld_control_p8_gnu-RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/11896220/PASS-cpld_control_p8_gnu-RegressionTests_hera.log.txt)

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [ ] Cheyenne
  - GNU
    - [x] Hera
    - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Hey @MatthewMasarik-NOAA, can you try the cpld_control_p8_gnu test with the changes in PR #1810 and see if it fixes your issue?

**Comment by MatthewMasarik-NOAA** [comment]
> Hey @MatthewMasarik-NOAA, can you try the cpld_control_p8_gnu test with the changes in PR #1810 and see if it fixes your issue?

Hi @BrianCurtis-NOAA, sure thing.  I'll let you know shortly.

**Comment by DeniseWorthen** [comment]
I'm curious why the re-test you did shows a wall clock time of 2234s. That test has been running right at the 30min limit (~1800s). Why is this test running so much slower w/ your changes?

Current develop branch:
```
  0: The total amount of wall time                        = 1757.157913
  0: The maximum resident set size (KB)                   = 1429100

Test 234 cpld_control_p8_gnu PASS
```

**Comment by MatthewMasarik-NOAA** [comment]
> Why is this test running so much slower w/ your changes?

I'm not sure.. this is the first I'm aware of the timing.  I'm going to try @BrianCurtis-NOAA's updates now  and see what that gives.

**Comment by DeniseWorthen** [comment]
Because there has been an issue w/ hera.gnu, we've extended the wall clock for just hera.gnu for the coupled tests. It's curently set at 40mins, which has been working because the test usually requires just a smidge over the 30min wall clock default. I looked at the PR changes and I don't see anything obvious that would cause WW3 to run slower.

**Comment by MatthewMasarik-NOAA** [comment]
From tailing the output files during the simulation, it seemed like the initialization took awhile.  Once the model started integrating time steps it marched along quickly.

**Comment by MatthewMasarik-NOAA** [comment]
The RT `cpld_control_p8_gnu` is re-running now with #1810 merged in, it will complete in ~30mins.

**Comment by MatthewMasarik-NOAA** [comment]
@BrianCurtis-NOAA @DeniseWorthen, with Brian's updates from #1810 the re-run completed in ~31mins ([pr_1810-cpld_control_p8_gnu-out.txt](https://github.com/ufs-community/ufs-weather-model/files/11897873/pr_1810-cpld_control_p8_gnu-out.txt)).  Ps, run directory `/scratch1/NCEPDEV/stmp2/Matthew.Masarik/FV3_RT/rt_29811/cpld_control_p8_gnu`.

@BrianCurtis-NOAA let me know if you want me to push the updates from your pr to this branch, or how to proceed

[pr_1810-cpld_control_p8_gnu-RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/11897941/pr_1810-cpld_control_p8_gnu-RegressionTests_hera.log.txt)

**Comment by BrianCurtis-NOAA** [comment]
We may get #1810 in sooner, but @jkbk2004 note that #1810 should go in before/with this PR.

**Comment by MatthewMasarik-NOAA** [comment]
Okay, sounds good.

**Comment by MatthewMasarik-NOAA** [comment]
Tests re-run on hera today with #1810 included for runtime fix (branch on my fork including pr 1810: [MatthewMasarik-NOAA/ufs-weather-model/syncww3_2023jun27_incl_pr1810](https://github.com/MatthewMasarik-NOAA/ufs-weather-model/tree/syncww3_2023jun27_incl_pr1810)).

[RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/11938025/RegressionTests_hera.log.txt)

**Comment by MatthewMasarik-NOAA** [comment]
Tests re-run after #1775 merged, 2023-jul-05.  Contains ORT bug fix PR #1810.

[2023-jul-05_RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/11961093/2023-jul-05_RegressionTests_hera.log.txt)

**Comment by MatthewMasarik-NOAA** [comment]
[RegressionTests_hera.log.txt](https://github.com/ufs-community/ufs-weather-model/files/12073973/RegressionTests_hera.log.txt) - all tests PASS.

**Comment by MatthewMasarik-NOAA** [comment]
RT's up-to-date with #1777 are currently running on orion.

**Comment by BrianCurtis-NOAA** [comment]
If it helps, you only need to run Hera logs once you're done making commits to your PR (not including bringing repositories up to date). If CM's do things correctly it should be the same once your PR hits the top of the commit queue.

**Comment by MatthewMasarik-NOAA** [comment]
> If it helps, you only need to run Hera logs once you're done making commits to your PR (not including bringing repositories up to date). If CM's do things correctly it should be the same once your PR hits the top of the commit queue.

Okay, I can say that I haven't made any new commits, but I did just update the UFS repo after the merge.  I submitted RT's to confirm all is well will my PR after the latest update.  Am I understanding correctly that it's not necessary to re-run the RT's after merges?

**Comment by BrianCurtis-NOAA** [comment]
> > If it helps, you only need to run Hera logs once you're done making commits to your PR (not including bringing repositories up to date). If CM's do things correctly it should be the same once your PR hits the top of the commit queue.
> 
> Okay, I can say that I haven't made any new commits, but I did just update the UFS repo after the merge. I submitted RT's to confirm all is well will my PR after the latest update. Am I understanding correctly that it's not necessary to re-run the RT's after merges?

Correct, it is not required to re-run RT's after merges.

**Comment by MatthewMasarik-NOAA** [comment]
> Correct, it is not required to re-run RT's after merges.

Great, I copy.  Thank you for clarifying.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I think we're going to transition back to PR 1815, since it looks ready now.

**Comment by zach1221** [comment]
Hi, @MatthewMasarik-NOAA . PR 1815 has been merged, so we may continue now working/testing through this one. Can you please sync up you branch with develop?

**Comment by MatthewMasarik-NOAA** [comment]
> Hi, @MatthewMasarik-NOAA . PR 1815 has been merged, so we may continue now working/testing through this one. Can you please sync up you branch with develop?

Hi @zach1221, done.

**Comment by zach1221** [comment]
Thanks, @MatthewMasarik-NOAA . 

@BrianCurtis-NOAA , I'm going to run jenkins-ci again, just to be safe. Then if all's successful we can begin Regression testing on this PR.

**Comment by zach1221** [comment]
Please see jenkins-ci logs for 1811. ORTs passed. We may begin Regression Testing now.
[PR 1811 Jenkins-CI ORT log.pdf](https://github.com/ufs-community/ufs-weather-model/files/12152278/PR.1811.Jenkins-CI.ORT.log.pdf)

**Comment by zach1221** [comment]
Ok, as discussed in our Code Managers meeting, it does look like I'm able to run tests on Cheyenne now. So, I'll post the log for those tests here as soon as possible.

**Comment by MatthewMasarik-NOAA** [comment]
Curious if there's an ETA for this merging today?

**Comment by zach1221** [comment]
Hi, @MatthewMasarik-NOAA , I'm attempting to get the RTs to complete on Cheyenne but have disk quota issues. @BrianCurtis-NOAA is it alright if we skip Cheyenne for this PR, and I'll work to get the issue resolved for the next?

**Comment by MatthewMasarik-NOAA** [comment]
> Hi, @MatthewMasarik-NOAA , I'm attempting to get the RTs to complete on Cheyenne but have disk quota issues. @BrianCurtis-NOAA is it alright if we skip Cheyenne for this PR, and I'll work to get the issue resolved for the next?

Thanks @zach1221, no worries.  I was just curious so I'd be nearby if needed.

**Comment by zach1221** [comment]
@MatthewMasarik-NOAA , understood. Well the WW3 sub-pr has been merged. Can you please update the submodule pointer and revert the change in gitmodules?
WW3 hash 59c554a12df3a04e0402ce5f17bb32cbbac193b2

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA , understood. Well the WW3 sub-pr has been merged. Can you please update the submodule pointer and revert the change in gitmodules?
> WW3 hash 59c554a12df3a04e0402ce5f17bb32cbbac193b2

@zach1221, I believe this should be done now.

**Comment by zach1221** [comment]
Thanks, @MatthewMasarik-NOAA . Sending out final reviews now.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
