### PR TITLE
Fire Coupling FV3ATM and Community Fire Behavior Model

### LINKED ISSUE #1982: Fire Behavior Modeling
## Description
As part of the effort to advance UFS infrastructure in support of fire modeling the CGD ESMF team and RAL Fire Behavior team have developed capabilities to couple UFSATM to the [community fire behavior model](https://ral.ucar.edu/model/community-fire-behavior-model) through NUOPC.

- [UFS SRW App with Fire Behavior Modeling](https://github.com/esmf-org/ufs-srweather-app/tree/feature/ufs_fire)
- [UFS Weather Modeling Forecast Executable with Fire Behavior Coupling](https://github.com/esmf-org/ufs-weather-model/tree/feature/ufs_fire)
- [NCAR RAL Fire Behavior Component](https://github.com/NCAR/fire_behavior/tree/develop)

The work is nearing the point at which development can be integrated into the community forecast executable and SRW community application. We would like to add a new regression test with the following

- New regional 3km US Colorado grid used for atmospheric and land modeling
- High resolution (500m) fire geogrid, which is encompassed within the 3km US Colorado grid, for modeling the Cameron Peak Fire
- Utilize existing CCPP suite_FV3_HRRR
- New namelist options for fire coupling
- UFSATM <-> Fire Behavior two-way coupling field exchanges through NUOPC connectors.

### PR DESCRIPTION
**Pull request by danrosen25**
## Commit Queue Requirements:
- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR adds the [Community Fire Behavior Model ](https://ral.ucar.edu/model/community-fire-behavior-model)component to the UFS weather model. The additional model is added to a single application 'ATMF' and requires modifications to fv3atm, ccpp/physics, and CMEPS.

This work is co-authored by @masih-e and @pedro-jm

### Commit Message:
```
* UFSWM - The fire_behavior component has been added and a new application created 'ATMF'. This work also includes a new regression test 'cpld_regional_atm_fbh' for testing two-way coupling of the atm component (fv3atm) and fbh component (fire_behavior)
  * CMEPS - CMEPS required modifications to be aligned with the changes to the ccpp physics package
  * FV3 - the fv3 cap has been modified to export atmosphere forcing data to the fire component when 'cpl_fire' is set to true. It will also import new fields for physics.
    * ccpp-physics - the ccpp physics package has been modified to add heat fluxes, upward specific humidity flux, and a smoke tracer from the fire component.
```

### Priority:
* Normal

### UFSWM:
* Closes #1982

### Sub component Pull Requests:
* CMEPS: https://github.com/NOAA-EMC/CMEPS/pull/117
* FV3: https://github.com/NOAA-EMC/fv3atm/pull/815
  * ccpp-physics: https://github.com/ufs-community/ccpp-physics/pull/193
* fire_beahvior: NEW COMPONENT TO BE FORKED FROM https://github.com/NCAR/fire_behavior

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* PR Adds New Tests/Baselines: 'cpld_regional_atm_fbh'. Baseline data has yet to be created as some of the work on the fire_behavior component is in progress.
* No Changes to Existing Tests

### Input data Changes:
* New input data for fire coupling. FIRE_BEHAVIOR_input_data and FV3_fire_input_data. These folder have been added to the input data and tested on derecho.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
@danrosen25 Is the commit hash for the `fire_behavior` submodule in this PR correct? I noticed that the latest commit in develop is now [`65b3ab81a3fc4f24ce1965bdf61b520b5281cdbf`.](https://github.com/NCAR/fire_behavior/commit/65b3ab81a3fc4f24ce1965bdf61b520b5281cdbf)

**Comment by grantfirl** [comment]
> @danrosen25 Is the commit hash for the `fire_behavior` submodule in this PR correct? I noticed that the latest commit in develop is now [`65b3ab81a3fc4f24ce1965bdf61b520b5281cdbf`.](https://github.com/NCAR/fire_behavior/commit/65b3ab81a3fc4f24ce1965bdf61b520b5281cdbf)

I did just kick off UFS pretest RTs using that commit, so please let me know if I should switch back to the older one that is referenced here in the PR.

**Comment by masih-e** [comment]
We tested the 05cad173feeb598431e3ef5f17c2df6562c8d101 commit for this PR. The later developments may not be ready for FV3. @pedro-jm

**Comment by grantfirl** [comment]
> * https://github.com/NCAR/fire_behavior

OK, thanks. I ran into some issues during testing related to the PR branches of fv3atm and ccpp-physics being out-of-date a bit, so I've made some changes in fv3atm in order to merge in the latest develop there and bring in the latest develop to the ccpp/physics branch. If they test OK, I'll submit PRs into the existing PR branches for you guys to review/approve that should be ready for the merge queue.

**Comment by grantfirl** [comment]
> > * https://github.com/NCAR/fire_behavior
> 
> OK, thanks. I ran into some issues during testing related to the PR branches of fv3atm and ccpp-physics being out-of-date a bit, so I've made some changes in fv3atm in order to merge in the latest develop there and bring in the latest develop to the ccpp/physics branch. If they test OK, I'll submit PRs into the existing PR branches for you guys to review/approve that should be ready for the merge queue.

@masih-e @danrosen25 

OK, regression testing was successful after pulling in the latest develop branches and applying some updated code changes to your existing changes in atmos_model.F90. I used the 05cad173feeb598431e3ef5f17c2df6562c8d101 commit of the fire_behavior submodule. I'm submitting PRs into all of your PR branches. We'll need to merge from the bottom up, starting from the ccpp/physics one.

**Comment by grantfirl** [comment]
Here is a list of PRs, in order of merging:
https://github.com/esmf-org/ccpp-physics/pull/1
https://github.com/esmf-org/fv3atm/pull/1 (this will be updated with the new commit of ccpp-physics after it is merged before we can merge this one)
https://github.com/esmf-org/CMEPS/pull/1
https://github.com/esmf-org/ufs-weather-model/pull/1 (this will be updated with the new commit of fv3atm and CMEPS once those PRs are merged)

Please see https://github.com/esmf-org/ufs-weather-model/pull/1 for the RT logs:
tests/logs/RegressionTests_hera.log
tests/test_changes.list

You will see that everything passed except for the new test, which is expected. These tests were conducted with the PRs into your branches listed above, so everything should be working as you all intended.

**Comment by danrosen25** [comment]
Hi @grantfirl,
This works for me. @masih-e ?  And I just want to confirm that these should pull in as a merge commit, right?

**Comment by grantfirl** [comment]
> Hi @grantfirl, This works for me. @masih-e ? And I just want to confirm that these should pull in as a merge commit, right?

Ya, you should just be able to press the merge button in the individual PRs. But, like I said, they need to go in order because after the lowest submodule is merged, the supermodule PR branch needs to have the commit hash of the submodule updated. I will update my PR branches into yours once the lowest level ccpp-physics PR is merged.

**Comment by masih-e** [comment]
It looks good to me. Thanks

**Comment by danrosen25** [comment]
@grantfirl 
I pulled in your synchronization work, thanks. @jkbk2004 helped us get the input data in place for the new test case `cpld_regional_atm_fbh`, which simulates the Cameron Peak Fire. The control data is not in place (this is why it should fail). We made a new test because it's more efficient, because it's a small atmospheric domain, and because it still accurately executes a real simulation.

**Comment by jkbk2004** [comment]
@danrosen25 can you change the draft status to PR and sync up branches ? we might be able to schedule to commit on Monday or Tuesday.

**Comment by danrosen25** [comment]
> @danrosen25 can you change the draft status to PR and sync up branches ? we might be able to schedule to commit on Monday or Tuesday.

Are we supposed to change PR to ready even though they still point to forked repositories. fv3atm still points to ccpp in esmf-org because the ccpp repo hasn't been merged. It feels like technically the PRs aren't ready to be merged until this is done, one step at a time.

**Comment by jkbk2004** [comment]
@danrosen25 once branches are synced up and a pre-test is ok, we can schedule to commit with full test across all machines.  We will start merging sub component PRs if all regression tests pass with required approvals. Looks like physics branch is up to date. I can help to sync up fv3 branch.

**Comment by jkbk2004** [comment]
@danrosen25 I was running a pre-test on hera. I see build failure error with compile_s2s_aoflux_intel.
```
ERROR: Variable do_fire_coupling requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surface_composites_post SUBROUTINE_\
GFS_surface_composites_post_run not provided by the model
ERROR: Variable kinematic_surface_upward_sensible_heat_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_\
surface_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
/scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/merge/rt-2220/FV3/ccpp/framework/scripts/ccpp_prebuild.py:486: DeprecationWarning: The\
 'warn' function is deprecated, use 'warning' instead
  logging.warn("Unconditionally allocated host-model variable {0} is  optional in {1}".format(
WARNING: Unconditionally allocated host-model variable surface_upward_latent_heat_flux_over_ocean_from_mediator is  optional in\ MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
WARNING: Unconditionally allocated host-model variable surface_upward_sensible_heat_flux_over_ocean_from_mediator is  optional \
in MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
ERROR: Variable surface_upward_specific_humidity_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surfac\
e_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
```
error messages at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_3285083/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/CMEPS-interface/ccpp_prebuild.{out,err}
All other cases are running ok w/o any crash issue.

**Comment by danrosen25** [comment]
@jkbk2004 I believe they've been tightening the ccpp prebuild checks so that conditional variables passed into ccpp schemes are properly attributed with optional and properly allocated within conditional statements. I'll have to take a look when I have a moment.

**Comment by grantfirl** [comment]
> @danrosen25 I was running a pre-test on hera. I see build failure error with compile_s2s_aoflux_intel.
> 
> ```
> ERROR: Variable do_fire_coupling requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surface_composites_post SUBROUTINE_\
> GFS_surface_composites_post_run not provided by the model
> ERROR: Variable kinematic_surface_upward_sensible_heat_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_\
> surface_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
> /scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/merge/rt-2220/FV3/ccpp/framework/scripts/ccpp_prebuild.py:486: DeprecationWarning: The\
>  'warn' function is deprecated, use 'warning' instead
>   logging.warn("Unconditionally allocated host-model variable {0} is  optional in {1}".format(
> WARNING: Unconditionally allocated host-model variable surface_upward_latent_heat_flux_over_ocean_from_mediator is  optional in\ MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
> WARNING: Unconditionally allocated host-model variable surface_upward_sensible_heat_flux_over_ocean_from_mediator is  optional \
> in MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
> ERROR: Variable surface_upward_specific_humidity_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surfac\
> e_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
> ```
> 
> error messages at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_3285083/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/CMEPS-interface/ccpp_prebuild.{out,err} All other cases are running ok w/o any crash issue.

@jkbk2004 @danrosen25 Are we sure that the right CMEPS code was checked out? This error shouldn't show up given the changes in https://github.com/NOAA-EMC/CMEPS/pull/117. This also didn't show up in my pre-tests which is odd.

**Comment by grantfirl** [comment]
> > @danrosen25 I was running a pre-test on hera. I see build failure error with compile_s2s_aoflux_intel.
> > ```
> > ERROR: Variable do_fire_coupling requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surface_composites_post SUBROUTINE_\
> > GFS_surface_composites_post_run not provided by the model
> > ERROR: Variable kinematic_surface_upward_sensible_heat_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_\
> > surface_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
> > /scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/merge/rt-2220/FV3/ccpp/framework/scripts/ccpp_prebuild.py:486: DeprecationWarning: The\
> >  'warn' function is deprecated, use 'warning' instead
> >   logging.warn("Unconditionally allocated host-model variable {0} is  optional in {1}".format(
> > WARNING: Unconditionally allocated host-model variable surface_upward_latent_heat_flux_over_ocean_from_mediator is  optional in\ MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
> > WARNING: Unconditionally allocated host-model variable surface_upward_sensible_heat_flux_over_ocean_from_mediator is  optional \
> > in MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
> > ERROR: Variable surface_upward_specific_humidity_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surfac\
> > e_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error messages at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_3285083/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/CMEPS-interface/ccpp_prebuild.{out,err} All other cases are running ok w/o any crash issue.
> 
> @jkbk2004 @danrosen25 Are we sure that the right CMEPS code was checked out? This error shouldn't show up given the changes in [NOAA-EMC/CMEPS#117](https://github.com/NOAA-EMC/CMEPS/pull/117).



> > @danrosen25 I was running a pre-test on hera. I see build failure error with compile_s2s_aoflux_intel.
> > ```
> > ERROR: Variable do_fire_coupling requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surface_composites_post SUBROUTINE_\
> > GFS_surface_composites_post_run not provided by the model
> > ERROR: Variable kinematic_surface_upward_sensible_heat_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_\
> > surface_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
> > /scratch2/NCEPDEV/marine/Jong.Kim/UFS-RT/merge/rt-2220/FV3/ccpp/framework/scripts/ccpp_prebuild.py:486: DeprecationWarning: The\
> >  'warn' function is deprecated, use 'warning' instead
> >   logging.warn("Unconditionally allocated host-model variable {0} is  optional in {1}".format(
> > WARNING: Unconditionally allocated host-model variable surface_upward_latent_heat_flux_over_ocean_from_mediator is  optional in\ MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
> > WARNING: Unconditionally allocated host-model variable surface_upward_sensible_heat_flux_over_ocean_from_mediator is  optional \
> > in MODULE_sfc_ocean SCHEME_sfc_ocean SUBROUTINE_sfc_ocean_run
> > ERROR: Variable surface_upward_specific_humidity_flux_of_fire requested by MODULE_GFS_surface_composites_post SCHEME_GFS_surfac\
> > e_composites_post SUBROUTINE_GFS_surface_composites_post_run not provided by the model
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error messages at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_3285083/compile_s2s_aoflux_intel/build_fv3_s2s_aoflux_intel/CMEPS-interface/ccpp_prebuild.{out,err} All other cases are running ok w/o any crash issue.
> 
> @jkbk2004 @danrosen25 Are we sure that the right CMEPS code was checked out? This error shouldn't show up given the changes in [NOAA-EMC/CMEPS#117](https://github.com/NOAA-EMC/CMEPS/pull/117). I also didn't have this error in my pretests, which is odd.

**Comment by grantfirl** [comment]
@danrosen25 @jkbk2004 I've pulled in the latest develop branches into the chain of PR branches (locally -- I haven't pushed) and am retesting on Hera. I'll let you know how it goes.

**Comment by grantfirl** [comment]
> @danrosen25 @jkbk2004 I've pulled in the latest develop branches into the chain of PR branches (locally -- I haven't pushed) and am retesting on Hera. I'll let you know how it goes.

@jkbk2004 @danrosen25 

After pulling in the latest develop branches for all submodules that have changes, I'm still not seeing any failures other than the expected new test: cpld_regional_atm_fbh intel. @danrosen25 Do you know how to pull in the latest develop code into every submodule, or would you like me to submit PRs to update your PR branches again?

**Comment by jkbk2004** [comment]
@danrosen25 Can you convert draft status to a PR as we like to schedule to commit?

**Comment by zach1221** [comment]
@grantfirl can you please sync up this PR?

**Comment by grantfirl** [comment]
> @grantfirl can you please sync up this PR?

Finished, although I noticed that the super-linter CI test is failing due to the lack of a new-line character at the end-of-file of fd_ufs.yaml. This isn't my work, but shall I push a fix for this really quick so that the CI test passes?

**Comment by BrianCurtis-NOAA** [comment]
Could you also make changes to: https://github.com/esmf-org/ufs-weather-model/blob/feature/ufs_fire_cpl/.github/pull_request_template.md adding the new component where applicable?

**Comment by grantfirl** [comment]
@danrosen25 @zach1221 

FYI, the CI tests required a couple of small fixes. Please review if you see fit.
https://github.com/ufs-community/ufs-weather-model/pull/2220/commits/da51eaeb2ec936aab618975a53783db6291f2ec7
https://github.com/ufs-community/ufs-weather-model/pull/2220/commits/a859b1acf58f86110b5dfb42c0445b2ea0fa39cb

**Comment by grantfirl** [comment]
> Could you also make changes to: https://github.com/esmf-org/ufs-weather-model/blob/feature/ufs_fire_cpl/.github/pull_request_template.md adding the new component where applicable?

Done. 

@zach1221 @BrianCurtis-NOAA I see that this work requires new input data that is currently staged on Derecho. I'm not sure if this has been staged yet on other platforms. I haven't checked, although I believe that it is missing on Hera.

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 make sure we get PR's labeled correctly.

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA It looks like the data is already available on Hera, you should be good to go to sync over

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA It looks like the data is already available on Hera, you should be good to go to sync over

Looks like WCOSS2/Acorn are not syncing anything so it may have came over in a previous sync?

**Comment by BrianCurtis-NOAA** [comment]
Not run on Acorn/WCOSS2 anyways, but the data will be there if that changes. We are adding a new test and changing no others, so just noting there is no need for a bl-date change, none has been made yet either.

**Comment by BrianCurtis-NOAA** [comment]
Can't start RT's on Acorn until later this afternoon/evening due to system testing.

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 Logs are at: /scratch1/NCEPDEV/stmp2/Brian.Curtis/RegressionTests_wcoss2.log on Hera. Is this accessible to you @grantfirl ?

**Comment by zach1221** [comment]
@grantfirl @danrosen25 are you able to give me access to push logs to this PR?

**Comment by danrosen25** [comment]
> @grantfirl @danrosen25 are you able to give me access to push logs to this PR?

If you accept the invitation to esmf-org:ufs-weather-model then I'll add you to this branch.

**Comment by zach1221** [comment]
> > @grantfirl @danrosen25 are you able to give me access to push logs to this PR?
> 
> If you accept the invitation to esmf-org:ufs-weather-model then I'll add you to this branch.

Ok I've accepted.

**Comment by BrianCurtis-NOAA** [comment]
Acorn Logs are at: /scratch1/NCEPDEV/stmp2/Brian.Curtis/RegressionTests_acorn.log on Hera

**Comment by grantfirl** [comment]
> WCOSS2 Logs are at: /scratch1/NCEPDEV/stmp2/Brian.Curtis/RegressionTests_wcoss2.log on Hera. Is this accessible to you @grantfirl ?

Thanks. This has been committed and pushed.

**Comment by FernandoAndrade-NOAA** [comment]
I will need to be added as well in order to push hera, gaea, and jet RT logs @danrosen25

**Comment by danrosen25** [comment]
@FernandoAndrade-NOAA, Added but I'll have to add you to the branch protections after you accept.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA, Added but I'll have to add you to the branch protections after you accept.

Accepted, thank you

**Comment by zach1221** [comment]
Derecho is still down, so I think we should skip and begin the merging process.

**Comment by zach1221** [comment]
@danrosen25 FV3atm and CMEPS subcomponent PRs have been merged. Please revert the change in .gitmodule urls and update the submodule hashes.
FV3atm hash: https://github.com/NOAA-EMC/fv3atm/commit/a9364591091c836984a40107729720705847c195
CMEPS hash: https://github.com/NOAA-EMC/CMEPS/commit/dc977bcadd1ade1a528dee75f1ad45e8bd80ca0a

**Comment by grantfirl** [comment]
> @danrosen25 FV3atm and CMEPS subcomponent PRs have been merged. Please revert the change in .gitmodule urls and update the submodule hashes. FV3atm hash: [NOAA-EMC/fv3atm@a936459](https://github.com/NOAA-EMC/fv3atm/commit/a9364591091c836984a40107729720705847c195) CMEPS hash: [NOAA-EMC/CMEPS@dc977bc](https://github.com/NOAA-EMC/CMEPS/commit/dc977bcadd1ade1a528dee75f1ad45e8bd80ca0a)

@danrosen25 @zach1221 Finished.

**Review by jkbk2004 — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@grantfirl Were we staying away from the top of the develop branch for fire behavior? I notice the hashes are not the same.

**Comment by grantfirl** [comment]
> @grantfirl Were we staying away from the top of the develop branch for fire behavior? I notice the hashes are not the same.

@BrianCurtis-NOAA Yes. I asked the same question when I updated this code to the top of the develop branches. See comments in this PR upthread: https://github.com/ufs-community/ufs-weather-model/pull/2220#issuecomment-2299523576

**Comment by BrianCurtis-NOAA** [comment]
> > @grantfirl Were we staying away from the top of the develop branch for fire behavior? I notice the hashes are not the same.
> 
> @BrianCurtis-NOAA Yes. I asked the same question when I updated this code to the top of the develop branches. See comments in this PR upthread: [#2220 (comment)](https://github.com/ufs-community/ufs-weather-model/pull/2220#issuecomment-2299523576)

Thanks Grant!

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by danrosen25** [comment]
@zach1221 @grantfirl @jkbk2004 
So it's technically the wrong repository for fire behavior. It's still going to work but it currently points to the NCAR (upstream) instead of the NOAA-EMC fork.
https://github.com/ufs-community/ufs-weather-model/blob/25ee7f6ca087ee19991e684a3c83e451921d5770/.gitmodules#L51

I should have pointed this out.

**Comment by jkbk2004** [comment]
@danrosen25 Is this https://github.com/NOAA-EMC/fire_behavior the one to be used?

**Comment by danrosen25** [comment]
> @danrosen25 Is this https://github.com/NOAA-EMC/fire_behavior the one to be used?

Yes, the identical revision being used was forked into the repo:
https://github.com/NOAA-EMC/fire_behavior/commit/05cad173feeb598431e3ef5f17c2df6562c8d101

**Pull request merged**
