### PR TITLE
Preliminary cmake options files for Gaea C5, Derecho, Hercules to support SRW runs

### PR DESCRIPTION
**Pull request by natalie-perlin**
## Description
This PR adds preliminary cmake configurations for new platforms Gaea, Derecho, Hercules. It will enable for the UFS-SRW to use and test these platforms for Atmospheric-only runs, while testing of UFS WM  supporting all of its components is still undergoing. 
SRW fundamental tests were successfully run on Derecho and Gaea C5.

## Linked Issues and Pull Requests
This addresses issues:
https://github.com/ufs-community/ufs-srweather-app/issues/884
https://github.com/ufs-community/ufs-srweather-app/issues/885
https://github.com/ufs-community/ufs-srweather-app/issues/886

Dependencies:
https://github.com/ufs-community/ufs-srweather-app/pull/894
https://github.com/ufs-community/ufs-srweather-app/pull/898
https://github.com/ufs-community/ufs-srweather-app/pull/911 (Still work-in-progress)

### Subcomponents involved:
- [x] none

### Input data
- [x] No changes are expected to input data.

### Regression Tests:
- [x] No changes are expected to any regression test.

### Libraries

- [x] Not Needed

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]
Looks good to me.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good!

**Comment by natalie-perlin** [comment]
@DavidHuber-NOAA - could it be approved?

**Comment by DavidHuber-NOAA** [comment]
@natalie-perlin Yes, I did approve it.  However, I'm not a code manager, so you will need an additional code manager approval for this to be mergeable.

**Comment by jkbk2004** [comment]
We will coordinate to combine with existing PRs. @natalie-perlin do you have timeline ?

**Comment by junwang-noaa** [comment]
Did someone run UFS WM full RT with these updates? The description only mentioned SRW fundamental tests.

**Comment by jkbk2004** [comment]
This PR should be combined to #1773, #1784, #1836.

**Comment by DusanJovic-NOAA** [comment]
Why is AVX2 set to ON in gaea_c5 file, it is a default, no need to set it again. My understanding is that gaea C5 is similar to WCOSS2  and on WCOSS2 we were told to not use AVX2 option. Similar recommendation was also given for C5.

I do not see anything specific to SRW in this PR. Please remove "to support SRW runs" from the PR title. Why are these changes preliminary?

**Comment by natalie-perlin** [comment]
@DusanJovic-NOAA - after coordinating with Gaea C5 team, they confirmed that it could be OK to use AVX2 on Gaea C5 if this works for the code (as per @ulmononian ) and generates no issues. Testing have not been done with the other components of the UFS besides the FV3.

@junwang-noaa , @jkbk2004 - 

These features only related to the SRW: this would allow UFS-WM to be checked out and have these cmake options already available for buildding and running the SRW tests and workflow. 

If this is not a desired behavior, and could only be merged with #1784 , #1836 , there is no reason to keep this PR, as it has no purpose. Closing it.

**Comment by junwang-noaa** [comment]
@natalie-perlin My understanding is that we are trying to get reproducible results between gaea c5 and wcoss2, is there any special request that we don't maintain that capability any more? 

The previous procedure for a new platform is that the common features such as the module file update should be applied to all the applications to avoid code diverge. Does EPIC have a different procedure now on how to port the ufs weather model to new platform for all the applications? If yes, would you please let us know how to take care other applications and how to maintain the shared module files? Thanks

**Comment by natalie-perlin** [comment]
@junwang-noaa - 
Thank you for your comment!  I proceeded with testing the SRW on Gaea C5 without these specific cmake options, and it seems to be working successfully. If this is indeed anticipated, SRW testing could proceed with only SRW modulefiles changes.

**Pull request closed without merging**
