### PR TITLE
Bugfix for nest namelists, includes "feature/update mom6 20210402"

### LINKED ISSUE #64: update MOM6 code from GFDL (20210402)
It was noticed that the codes between EMC dev/emc and GFDL main branch contain some minor difference due to a mistakenly clicking of button by GFDL on 20210308's updating. A hot fixing will bring two sides' code on the same page again. See detail at https://github.com/NOAA-GFDL/MOM6/pull/1358

GFDL updated main branch on 20210402 (see detail at https://github.com/NOAA-GFDL/MOM6/pull/1358#event-4545482872). This updating will make EMC and GFDL main repository on the same page.

### LINKED ISSUE #264: Nests reading wrong namelist section atmos_model_nml
## Description

The current code in fv3atm has a bug when running nested models. The atmos_model_nml section, which contains options such as ccpp_suite, blocksize, fhdiag, is currently read in fv3atm before atmosphere_init is called. This is required, because atmosphere_init needs ccpp_suite.

However, the capability to read the correct namelist for the nests is only turned on during atmosphere_init. The nests currently read the wrong namelist section `atmos_model_nml`), namely that of the parent. This means that all values in that section are potentially wrong: `ccpp_suite`, `blocksize`, `fdiag`, ...

For a detailed description of the solution, see https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/86.

This bug is fixed in PRs https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/86 and https://github.com/NOAA-EMC/fv3atm/pull/263.

### LINKED ISSUE #489: update MOM6 code to make EMC code on the same page as GFDL
## Description
This is a placeholder for the upcoming GFDL's MOM6 code main branch updating (https://github.com/NOAA-GFDL/MOM6/pull/1358).
It was noticed that the codes between EMC dev/emc and GFDL main branch contain some minor difference due to a mistakenly clicking of button by GFDL on 20210308's updating. A hot fixing will bring two sides' code on the same page again.

Details will be added here after the finalization of GFDL's main branch updating.
updating: GFDL updated their MOM6 main branch on 20210402, so EMC will need to make corresponding updating.

**Solution**
Merge GFDL's 20210402 commit to EMC MOM6 repository, test in UFS and update MOM6 and ufs-weather-model upon success. No answer change is expected and there is no any input file change.

**Related to**
- related MOM6 issue (https://github.com/NOAA-EMC/MOM6/issues/64)

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR
- updates the submodule pointer for fv3atm to fix a bug when reading namelist section `atmos_model_nml` for nests (see associated PRs for more information)
- prepends the model output of regression test runs on Cheyenne with the rank, similar to what is done on other platforms, and uses the economy queue (to save core-hours)
- contains the changes from PR https://github.com/ufs-community/ufs-weather-model/pull/514 (feature/update mom6 20210402)

### Issue(s) addressed

- fixes https://github.com/NOAA-EMC/fv3atm/issues/264
- fixes ufs-weather-model #489 
- fixes https://github.com/NOAA-EMC/MOM6/issues/64

## Testing

No answer changes expected for the regression tests. No change to baselines, no new input data. Regression tests passed on:

- [X] hera.intel
- [X] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/86
https://github.com/NOAA-EMC/fv3atm/pull/263
https://github.com/ufs-community/ufs-weather-model/pull/488

### CODE REVIEW

**Comment by jiandewang** [comment]
@climbfuji I just updated my origin MOM6 updating PR to include today's ufs-weather-model commit, please let me know on what you need me to do for the next

**Comment by jiandewang** [comment]
@climbfuji can you switch MOM6 to https://github.com/jiandewang/MOM6/tree/feature/update-to-GFDL-20210402 in your PR branch ?

**Comment by climbfuji** [comment]
> @climbfuji can you switch MOM6 to https://github.com/jiandewang/MOM6/tree/feature/update-to-GFDL-20210402 in your PR branch ?

This was done automatically when pulling in your PR - I am showing hash c549ae9d93531b104492654d257e4949293d3c3a in my code base, which is the latest commit in your MOM6 PR (https://github.com/NOAA-EMC/MOM6/pull/65/commits).

I am going to run the tests on hera with Intel and GNU now. If those pass I will let you know so that you can start on wcoss (but please wait for the hera tests to finish). Thanks!

**Comment by jiandewang** [comment]
@climbfuji c549ae9d is the right hash # for MOM6

**Review by junwang-noaa — COMMENTED** [review]
Looks good to me.

**Comment by climbfuji** [comment]
@jiandewang regression tests passed against existing baselines on hera.intel and hera.gnu, logs updated in the PR. I kicked off the ci tests, once those are done I will add the auto-rt labels for the other platforms and run on Cheyenne. Please run rt.sh on the wcoss platforms (on Monday, no rush). Thanks!

**Comment by climbfuji** [comment]
> @jiandewang regression tests passed against existing baselines on hera.intel and hera.gnu, logs updated in the PR. I kicked off the ci tests, once those are done I will add the auto-rt labels for the other platforms and run on Cheyenne. Please run rt.sh on the wcoss platforms (on Monday, no rush). Thanks!

I wanted to clarify how to run the tests for the correct branch. On each of the wcoss systems, please do
```
git checkout -b bugfix_nests_namelist_and_unnecessary_recompiling --recursive https://github.com/climbfuji/ufs-weather-model
```
to check out the correct code.

@junwang-noaa @MinsukJi-NOAA CI tests passed for commit https://github.com/ufs-community/ufs-weather-model/pull/488/commits/2126475007448681208fe7662e0921f7a7291dcd.

**Comment by jiandewang** [comment]
@climbfuji thanks for the information, will run it on wcoss

**Comment by junwang-noaa** [comment]
@climbfuji <https://github.com/climbfuji> Thanks for confirming the
successful run of CI tests.

**Comment by jiandewang** [comment]
@climbfuji wcoss runs finished successfully, see RT log on HERA: /scratch2/NCEPDEV/climate/Jiande.Wang/For-others/For-Dom. Let me know when it's the time for me to ask for reviewers to approve the MOM6 PR and do the merging.

**Comment by climbfuji** [comment]
Regression tests passed on all platforms, ci tests passed as well. @jiandewang the mom6 PR https://github.com/NOAA-EMC/MOM6/pull/65 can be merged. @junwang-noaa the fv3atm PR https://github.com/NOAA-EMC/fv3atm/pull/263 can be merged. Thanks!

**Comment by DeniseWorthen** [comment]
@climbfuji Could you edit the PR title to add that it includes the MOM6 update?

**Comment by jiandewang** [comment]
> Regression tests passed on all platforms, ci tests passed as well. @jiandewang the mom6 PR [NOAA-EMC/MOM6#65](https://github.com/NOAA-EMC/MOM6/pull/65) can be merged. @junwang-noaa the fv3atm PR [NOAA-EMC/fv3atm#263](https://github.com/NOAA-EMC/fv3atm/pull/263) can be merged. Thanks!

MOM6 PR has been merged to dev/emc

**Comment by junwang-noaa** [comment]
FV3 PR was merged.

**Review by DeniseWorthen — APPROVED** [review]
Looks OK and ready to merge after submodules are reverted.

**Comment by climbfuji** [comment]
Submodule pointers have been updated, I verified them to be correct.

**Review by junwang-noaa — APPROVED** [review]

**Review by jiandewang — APPROVED** [review]

**Pull request merged**
