### PR TITLE
Fix -check all runtime errors (for CCPP) using zero-size allocations

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [X] Add list of all failed regression tests in "Regression Tests" section.

### Description
This PR at least partially addresses https://github.com/ufs-community/ufs-weather-model/issues/2023 (at least any runtime errors associated with the CCPP). The strategy is to simply make sure that every variable is allocated, although for variables that had been conditionally-allocated to save memory, they are now being allocated with zero size. This has a ripple effect in other repos where one needs to change from checking whether a variable is allocated to whether the size is > 0.

**The change to Intel.cmake was used for testing only and I can remove this if we're not ready to permanently add it.**

### Commit Message

Add zero-size variable allocations to pass the `-check all` compiler option for CCPP-related code.

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [X] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Blocking Dependencies
- waiting on https://github.com/ufs-community/ccpp-physics/pull/159
- waiting on a PR for https://github.com/climbfuji/ccpp-framework/tree/feature/dummy_allocate_inactive
- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/315
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/767

### Git Issues Fixed By This PR
Partially addresses https://github.com/ufs-community/ufs-weather-model/issues/2023

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- https://github.com/NOAA-EMC/fv3atm/pull/767
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [X] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@grantfirl can you sync up? I want to test on hercules/gnu.

**Comment by grantfirl** [comment]
> @grantfirl can you sync up? I want to test on hercules/gnu.

@jkbk2004 Done

**Comment by jkbk2004** [comment]
@grantfirl This PR runs ok on hercules/gnu. Please, go ahead to sync up branch one more time. We can work on this pr. @zach1221 @FernandoAndrade-NOAA Can you pick up from here? @BrianCurtis-NOAA FYI.

**Comment by grantfirl** [comment]
> @grantfirl This PR runs ok on hercules/gnu. Please, go ahead to sync up branch one more time. We can work on this pr. @zach1221 @FernandoAndrade-NOAA Can you pick up from here? @BrianCurtis-NOAA FYI.

Recall that this needs to go into the production/RRFS.v1 branch that was just created. I just updated the target, and it looks like there are a bunch of unintended changes, likely because the release branch was cut from an older commit whereas my changes started from the top of develop. I think that I may need to do some surgery here, or perhaps just close this PR and start fresh with the release branch and then add my changes. 

@zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA @MatthewPyle-NOAA

**Comment by jkbk2004** [comment]
@grantfirl thanks for the note! @MatthewPyle-NOAA we can capture subcomponent production branch with this pr. @zach1221 @FernandoAndrade-NOAA @BrianCurtis-NOAA we need a bit more time, I think.

**Comment by jkbk2004** [comment]
@grantfirl I am ok to close and open a new one.

**Comment by grantfirl** [comment]
This is replaced by https://github.com/ufs-community/ufs-weather-model/pull/2158 which points to the RRFS release branch. This will likely NOT need to go to the develop branch since a longer-term fix is forthcoming.

**Pull request closed without merging**
