### PR TITLE
ccpp-physics #806, #807, #813, and ort modifications

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- CCPP Physics changes: see https://github.com/NOAA-EMC/fv3atm/pull/447.
- UFS weather model changes for ORT updates following changes in https://github.com/ufs-community/ufs-weather-model/pull/965

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

Expected test failures (7 tests related to rttmgp) were verified on Hera and Cheyenne.
- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1603586633

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/447

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@grantfirl please update your wrapper_806_807_813 branch to the latest fv3atm.

**Comment by grantfirl** [comment]
> @grantfirl please update your wrapper_806_807_813 branch to the latest fv3atm.

Done

**Comment by grantfirl** [comment]
The following RTs will fail due to changes in RRTMGP diagnostics:
cpld_control_p7_rrtmgp
control_p7_rrtmgp
regional_RRTMGP
control_rrtmgp
control_rrtmgp_c192
control_rrtmgp_debug
rap_rrtmgp_debug

All other RTs on Hera passed for me.

**Comment by MinsukJi-NOAA** [comment]
> The following RTs will fail due to changes in RRTMGP diagnostics: cpld_control_p7_rrtmgp control_p7_rrtmgp regional_RRTMGP control_rrtmgp control_rrtmgp_c192 control_rrtmgp_debug rap_rrtmgp_debug
> 
> All other RTs on Hera passed for me.

Can you confirm that new baselines are needed?

**Comment by grantfirl** [comment]
> 

Yes, new baselines are needed for the RRTMGP tests.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/806774931/20211220094509/ufs-weather-model
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/806774931/20211220164508/ufs-weather-model
Please make changes and add the following label back:
hera-intel-RT

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/806774931/20211220111509/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_63183
Test cpld_control_p7_rrtmgp 002 failed in check_result failed 
Test cpld_control_p7_rrtmgp 002 failed in run_test failed 
Test control_p7_rrtmgp 031 failed in check_result failed 
Test control_p7_rrtmgp 031 failed in run_test failed 
Test regional_RRTMGP 041 failed in check_result failed 
Test regional_RRTMGP 041 failed in run_test failed 
Test control_rrtmgp 048 failed in check_result failed 
Test control_rrtmgp 048 failed in run_test failed 
Test control_rrtmgp_c192 049 failed in check_result failed 
Test control_rrtmgp_c192 049 failed in run_test failed 
Test control_rrtmgp_debug 065 failed in check_result failed 
Test control_rrtmgp_debug 065 failed in run_test failed 
Test rap_rrtmgp_debug 081 failed in check_result failed 
Test rap_rrtmgp_debug 081 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/806774931/20211220194514/ufs-weather-model
/lfs4/HFIP/h-nems/emc.nemspara/RT/NEMSfv3gfs//develop-20211220/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/806774931/20211220134520/ufs-weather-model
/work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211220/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/806774931/20211220194515/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211220/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/806774931/20211220123011/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_29800
Test control_rrtmgp 006 failed in check_result failed 
Test control_rrtmgp 006 failed in run_test failed 
Test control_rrtmgp_debug 029 failed in check_result failed 
Test control_rrtmgp_debug 029 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by MinsukJi-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: cheyenne Compiler: gnu Job: RT Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/806774931/20211220123011/ufs-weather-model Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_29800 Test control_rrtmgp 006 failed in check_result failed Test control_rrtmgp 006 failed in run_test failed Test control_rrtmgp_debug 029 failed in check_result failed Test control_rrtmgp_debug 029 failed in run_test failed Please make changes and add the following label back: cheyenne-gnu-RT

There are only 2 active rrtmgp tests on gnu - Failed tests verified.

**Comment by junwang-noaa** [comment]
cray and dell log files are on hera at: /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA Please update fv3 in your branch

**Pull request merged**
