### PR TITLE
Remove all IPD and all REPRO tests from rt.conf

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**

### CODE REVIEW

**Comment by climbfuji** [comment]
This looks great! I was hoping to fix the NEMSAppBuilder test as part of the commit, but I see that most tests have already been completed. Do you want to do this as part of the next commit?

**Comment by ligiabernardet** [comment]
A much anticipated PR! Thank you to all that worked on this project over
the last couple of years.

**Comment by DusanJovic-NOAA** [comment]
> This looks great! I was hoping to fix the NEMSAppBuilder test as part of the commit, but I see that most tests have already been completed. Do you want to do this as part of the next commit?

Not in this commit. I want this merge to change only one file, rt,conf. Nothing else.

**Comment by climbfuji** [comment]
Sure, no problem. Can you run on hera when it comes back up, or should I?

**Comment by DusanJovic-NOAA** [comment]
Yes, please do. We have very limited resources available to us these days on Hera.

**Comment by climbfuji** [comment]
> Yes, please do. We have very limited resources available to us these days on Hera.

This will have to wait until tomorrow, I still can't log into hera - maintenance seems to be ongoing.

**Comment by climbfuji** [comment]
> > Yes, please do. We have very limited resources available to us these days on Hera.
> 
> This will have to wait until tomorrow, I still can't log into hera - maintenance seems to be ongoing.

Kicked off the tests - you can `tail -f /scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove_ipd_tests-20200506/tests/rt_hera_intel.log` to check the status and copy the logs when finished, or wait for me to come back in about 2 hours ...

**Review by junwang-noaa — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
