### PR TITLE
Update fms to 2021.04

### LINKED ISSUE #1105: Using FMS 2021.04 in ufs-weather-model
## Description
FMS 2022.01 is coming soon. It contains the updates including an option to ignore checksums. Ufs-weather-model will be updated to use FMS 2022.01.

20220321 Update: GFDL found  potential performance regression for GFDL models with FMS 2022.01. We will update FMS to 2021.04 in ufs-weather-model.

## Solution
When FMS 2022.01 is released, the fms lib will be added on all the ufs-weather-model supported platforms and tested in ufs-weather-model. A PR will be made to ufs-weather-model to use the new version.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Update FMS library to version 2021.04.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1105

## Testing

How were these changes tested? Yes.
What compilers / HPCs was it tested with? Intel on Hera.
Are the changes covered by regression tests? Yes.
Have regression tests and unit tests (utests) been run? Yes.
On which platforms and with which compilers? Hera/Intel. Two tests did not reproduce current baselines (cpld_debug_p8
 and datm_cdeps_debug_cfsr)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

Do PRs in upstream repositories need to be merged first? No.

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
On Hera using GNU compiler one regression test failed to reproduce the current baselines:

```
$ cat log_hera.gnu/rt_038_cpld_debug_noaero_p8.log    

baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220318/GNU/cpld_debug_noaero_p8
working dir  = /scratch1/NCEPDEV/stmp2/Dusan.Jovic/FV3_RT/rt_22816/cpld_debug_noaero_p8
Checking test 038 cpld_debug_noaero_p8 results ....
 Comparing sfcf006.tile1.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.tile2.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.tile3.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.tile4.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.tile5.nc ............ALT CHECK......NOT OK
 Comparing sfcf006.tile6.nc ............ALT CHECK......NOT OK
 Comparing atmf006.tile1.nc ............ALT CHECK......NOT OK
 Comparing atmf006.tile2.nc ............ALT CHECK......NOT OK
 Comparing atmf006.tile3.nc ............ALT CHECK......NOT OK
 Comparing atmf006.tile4.nc ............ALT CHECK......NOT OK
 Comparing atmf006.tile5.nc ............ALT CHECK......NOT OK
 Comparing atmf006.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc ............SKIP for gnu compilers
 Comparing RESTART/fv_core.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_core.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_srf_wnd.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/phy_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/MOM.res.nc ............ALT CHECK......NOT OK
 Comparing RESTART/iced.2021-03-22-43200.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-22-43200.nc ............ALT CHECK......NOT OK

  0: The total amount of wall time                        = 580.744840
  0: The maximum resident set size (KB)                   = 873040

Test 038 cpld_debug_noaero_p8 FAIL Tries: 2


```

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA Would you please check the timing for other tests?

**Comment by DusanJovic-NOAA** [comment]
Full regression test passed on Gaea. Wall clock time is comparable to the current version, for example:

```diff
 baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20220318/INTEL/cpld_control_c384_p8
-working dir  = /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_16447/cpld_control_c384_p8
+working dir  = /lustre/f2/scratch/Dusan.Jovic/FV3_RT/rt_11823/cpld_control_c384_p8
 Checking test 012 cpld_control_c384_p8 results ....
  Comparing sfcf006.nc .........OK
  Comparing atmf006.nc .........OK
@@ -731,14 +727,14 @@ Checking test 012 cpld_control_c384_p8 results ....
  Comparing RESTART/iced.2021-03-22-43200.nc .........OK
  Comparing RESTART/ufs.cpld.cpl.r.2021-03-22-43200.nc .........OK
 
-  0: The total amount of wall time                        = 1486.791853
-  0: The maximum resident set size (KB)                   = 2720940
+  0: The total amount of wall time                        = 1437.298908
+  0: The maximum resident set size (KB)                   = 2735980
 
 Test 012 cpld_control_c384_p8 PASS
```

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/886073998/20220325090044/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/886073998/20220325140726/ufs-weather-model
[RT] Error: Test hafs_regional_telescopic_2nests_atm 105 failed in run_test failed 
Please make changes and add the following label back: orion-intel-BL

**Pull request merged**
