### PR TITLE
Multiple domains quilting restart

### LINKED ISSUE #1628: Using fv3atm write grid component to write out restart files for multiple domains
## Description
This issue is an follow-up to the issue #1587. In issue #1587, the FV3ATM write grid component is able to write restart files for one domain (either 6 tile global domain or a single regional domain). In this issue, the capability of writing multiple domain restart files will be verified and sample tests will be added.

## Solution
Extend the write grid component restart capability to write out restart files on multiple domains including moving nest domains.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

This PR updates fv3atm write grid component to allow writing the restart files for multiple domains (nests). Three new tests were added which compare the RESTART files written by the write grid component with restart files written by the FMS

Fixes: https://github.com/ufs-community/ufs-weather-model/issues/1628

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

 hafs_global_1nest_atm                                                                                              
 hafs_global_multiple_4nests_atm
 hafs_regional_1nest_atm
 hafs_regional_storm_following_1nest_atm

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
FV3ATM: [#650](https://github.com/NOAA-EMC/fv3atm/pull/650)
GFDL Cubed Sphere: [#268](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/268)

Please link the related issues to be closed with this PR, whether in this repository, or in another repository.
EXAMPLE: Closes NOAA-EMC/fv3atm/issues/<issue_number>
-->

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Please link FV3 and atmos_cubed_sphere PR's. Please run GNU/Intel RT's and note Tests that change.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA we can start working on this pr. Can you sync up branches?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA we can start working on this pr. Can you sync up branches?

Merged.

**Comment by zach1221** [comment]
@DusanJovic-NOAA do you have GNU/Intel RT logs from runs on either Hera or Cheyenne?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA do you have GNU/Intel RT logs from runs on either Hera or Cheyenne?

[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11498235/RegressionTests_hera.intel.log)

This is a hera log from my test I ran yesterday. I do not have gnu log, but since gnu test does not run HAFS I do not expect changes in the baselines.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I'm going to start testing through this PR next.

**Comment by zach1221** [comment]
Jenkins-ci logs attached. ORTs passed. I will now begin manually creating the new baselines for the below tests.
hafs_global_1nest_atm
hafs_global_multiple_4nests_atm
hafs_regional_1nest_atm
hafs_regional_storm_following_1nest_atm
[ufs-weather-model » ort-docker-pipeline » PR-1722 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11500540/ufs-weather-model.ort-docker-pipeline.PR-1722.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1325978724/20230517150041/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by zach1221** [comment]
Disregard the Orion error above, it's jenkins pipeline related.

**Comment by zach1221** [comment]
I'm receiving failures on cheyenne.intel only for the following hafs qr cases. hafs_regional_1nest_atm_qr, hafs_global_1nest_atm_qr, hafs_global_multiple_4nests_atm_qr, and hafs_regional_storm_following_1nest_atm_qr. Everything else passes but these. I think it's related to mpt/2.25 on cheyenne.
image

**Comment by jkbk2004** [comment]
@zach1221 how many new hafs qr cases failing on cheyenne.intel? to me it sounds like hdf issue.

**Comment by zach1221** [comment]
@jkbk2004 All four of the new Hafs qr cases are failing on cheyenne.intel.

**Comment by zach1221** [comment]
@jkbk2004 I can try to run these cases with hdf5 1.14.0

**Comment by jkbk2004** [comment]
It sounds like new cases are running with -DDEBUG=ON.  At least not crashing but very slowly: /glade/scratch/jongkim/pr-1722-intel/jongkim/FV3_RT/rt_60395/hafs_regional_1nest_atm_qr. looks like crash is system/compiler/mpt issue. Not practical to run the new cases on cheyenne. @DusanJovic-NOAA @zach1221 can we agree to turn the new cases off on cheyenne?

**Comment by DusanJovic-NOAA** [comment]
> It sounds like new cases are running with -DDEBUG=ON. At least not crashing but very slowly: /glade/scratch/jongkim/pr-1722-intel/jongkim/FV3_RT/rt_60395/hafs_regional_1nest_atm_qr. looks like crash is system/compiler/mpt issue. Not practical to run the new cases on cheyenne. @DusanJovic-NOAA @zach1221 can we agree to turn the new cases off on cheyenne?

I agree, turn off 4 new hafs tests on cheyenne.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA Do you have any insight into the exact line it is complaining about? https://github.com/DusanJovic-NOAA/fv3atm/blob/0379fd48f24dd67cab6f8b88b2b77fabfa7afc71/io/module_write_restart_netcdf.F90#L452

**Comment by zach1221** [comment]
I can create a new issue regarding the hafs qr error on cheyenne.intel.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Do you have any insight into the exact line it is complaining about? https://github.com/DusanJovic-NOAA/fv3atm/blob/0379fd48f24dd67cab6f8b88b2b77fabfa7afc71/io/module_write_restart_netcdf.F90#L452

I don't. That's the function that actually writes the array into a file. The error message is 'NetCDF: HDF error' , so I assume it's something wrong in the netcdf or hdf5 library. @zach1221 Did you try to run one of these 4 tests using hdf5 1.14.0?

**Comment by zach1221** [comment]
Hi, @DusanJovic-NOAA. Yes, I tried hdf5 1.14.0 with hafs_regional_1nest_atm_qr, but received the same error message posted above. Perhaps it would be worth it to try with netcdf updated to version 4.9.4 as well.

**Comment by zach1221** [comment]
Ok, I'll continue investigating the failure in the UFS-WM issues queue. In the meantime, @DusanJovic-NOAA, if you want to turn off the 4 new hafs tests on cheyenne then I think we're ready to proceed final review/approvals.

**Comment by DusanJovic-NOAA** [comment]
> Ok, I'll continue investigating the failure in the UFS-WM issues queue. In the meantime, @DusanJovic-NOAA, if you want to turn off the 4 new hafs tests on cheyenne then I think we're ready to proceed final review/approvals.

I disabled those 4 tests on cheyenne

**Review by DeniseWorthen — DISMISSED** [review]

**Review by BrianCurtis-NOAA — DISMISSED** [review]

**Comment by zach1221** [comment]
Apologies I sent the reviews out before the fv3 submodule pointer was updated and gitmodules were reverted. Can you please provide your approval again? @DeniseWorthen @BrianCurtis-NOAA

**Review by DeniseWorthen — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
