### PR TITLE
Changes to regression test files for recent changes to RRTMG and RRTMGP.

### PR DESCRIPTION
**Pull request by dustinswales**
This PR contains changes to regression test files relating to recent changes to RRTMG and RRTMGP.

The gfs_physics namelist was modified to accommodate new functionality. Changes to the RT setup for RRTMG and RRTMGP were modified.  

Also, GP has input files that need to be updated. These are provided with the rte-rrtmgp code, ccpp/physics/physics/rte-rrtmgp/rrtmgp/data/. Is there a way that we can set up the RT's to use this location when staging input files for the RTs? Just one less place for confusion.

This PR is dependent on:
- FV3: https://github.com/NOAA-EMC/fv3atm/pull/193
- CCPP: https://github.com/NCAR/ccpp-physics/pull/514

### CODE REVIEW

**Review by climbfuji — CHANGES_REQUESTED** [review]
@dustinswales can you turn on the RRTMGP regression tests again in `tests/rt.conf` and `tests/rt_gnu.conf` ? Do they pass?

Also, please update `.gitmodules` temporarily to point to your fv3atm fork and your branch  develop-emc-b955f81? Thanks.

**Comment by dustinswales** [comment]
@climbfuji 
The GP tests fail the RT's because the GP input data that gets staged needs updating. (This should really be pulled in directly from the rte-rrtmgp code) I don't know where to look to do this. But if I run the RTs and go into the failed GP RTs run directories and import the updated files, it runs. Of course there is no baseline to compare to for the v15p2 or v16beta w/ GP.

**Comment by climbfuji** [comment]
> @climbfuji
> The GP tests fail the RT's because the GP input data that gets staged needs updating. (This should really be pulled in directly from the rte-rrtmgp code) I don't know where to look to do this. But if I run the RTs and go into the failed GP RTs run directories and import the updated files, it runs. Of course there is no baseline to compare to for the v15p2 or v16beta w/ GP.

That's good to know! I can help with staging the new data and creating the baselines. Please point me to the files that need to be updated and I can take care of it.

**Comment by dustinswales** [comment]
@climbfuji 
The files used for the gas-optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/rrtmgp/data. 
For the GP cloud optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/extensions/cloud_optics

**Comment by climbfuji** [comment]
> @climbfuji
> The files used for the gas-optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/rrtmgp/data.
> For the GP cloud optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/extensions/cloud_optics

Where should these files go? Replace the contents of `/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/`?
```
[Dom.Heinzeller@hfe09 INTEL]$ ls -l /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/
total 46444
-rw-r--r-- 1 emc.nemspara nems    32212 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-lw.nc
-rw-r--r-- 1 emc.nemspara nems    28888 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-sw.nc
-rw-r--r-- 1 emc.nemspara nems 32530992 Oct 20 00:43 rrtmgp-data-lw-g256-2018-12-04.nc
-rw-r--r-- 1 emc.nemspara nems 14954928 Oct 20 00:43 rrtmgp-data-sw-g224-2018-12-04.nc
```
(of course not replace , but replace in the next version of the baseline)

**Comment by dustinswales** [comment]
> > @climbfuji
> > The files used for the gas-optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/rrtmgp/data.
> > For the GP cloud optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/extensions/cloud_optics
> 
> Where should these files go? Replace the contents of `/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/`?
> 
> ```
> [Dom.Heinzeller@hfe09 INTEL]$ ls -l /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/
> total 46444
> -rw-r--r-- 1 emc.nemspara nems    32212 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-lw.nc
> -rw-r--r-- 1 emc.nemspara nems    28888 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-sw.nc
> -rw-r--r-- 1 emc.nemspara nems 32530992 Oct 20 00:43 rrtmgp-data-lw-g256-2018-12-04.nc
> -rw-r--r-- 1 emc.nemspara nems 14954928 Oct 20 00:43 rrtmgp-data-sw-g224-2018-12-04.nc
> ```
> 
> (of course not replace , but replace in the next version of the baseline)

This is correct.

**Comment by climbfuji** [comment]
> > > @climbfuji
> > > The files used for the gas-optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/rrtmgp/data.
> > > For the GP cloud optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/extensions/cloud_optics
> > 
> > 
> > Where should these files go? Replace the contents of `/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/`?
> > ```
> > [Dom.Heinzeller@hfe09 INTEL]$ ls -l /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/
> > total 46444
> > -rw-r--r-- 1 emc.nemspara nems    32212 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-lw.nc
> > -rw-r--r-- 1 emc.nemspara nems    28888 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-sw.nc
> > -rw-r--r-- 1 emc.nemspara nems 32530992 Oct 20 00:43 rrtmgp-data-lw-g256-2018-12-04.nc
> > -rw-r--r-- 1 emc.nemspara nems 14954928 Oct 20 00:43 rrtmgp-data-sw-g224-2018-12-04.nc
> > ```
> > 
> > 
> > (of course not replace , but replace in the next version of the baseline)
> 
> This is correct.

Thanks, will do so.

**Comment by climbfuji** [comment]
> > > > @climbfuji
> > > > The files used for the gas-optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/rrtmgp/data.
> > > > For the GP cloud optics: https://github.com/earth-system-radiation/rte-rrtmgp/tree/dtc/ccpp/extensions/cloud_optics
> > > 
> > > 
> > > Where should these files go? Replace the contents of `/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/`?
> > > ```
> > > [Dom.Heinzeller@hfe09 INTEL]$ ls -l /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20201103/INTEL/FV3_input_data_RRTMGP/
> > > total 46444
> > > -rw-r--r-- 1 emc.nemspara nems    32212 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-lw.nc
> > > -rw-r--r-- 1 emc.nemspara nems    28888 Oct 20 00:43 rrtmgp-cloud-optics-coeffs-sw.nc
> > > -rw-r--r-- 1 emc.nemspara nems 32530992 Oct 20 00:43 rrtmgp-data-lw-g256-2018-12-04.nc
> > > -rw-r--r-- 1 emc.nemspara nems 14954928 Oct 20 00:43 rrtmgp-data-sw-g224-2018-12-04.nc
> > > ```
> > > 
> > > 
> > > (of course not replace , but replace in the next version of the baseline)
> > 
> > 
> > This is correct.
> 
> Thanks, will do so.

@dustinswales FYI, finally doing this on orion because hera remains unusable. I see that the two cloud optics coeffs files are identical between what is currently in the baseline and what is in the rte-rrtmgp repository (at least at the hash currently used inside ccpp-physics), while the two other files are different:
```
Orion-login-4[9] dheinzel$ diff ./FV3/ccpp/physics/physics/rte-rrtmgp/extensions/cloud_optics/rrtmgp-cloud-optics-coeffs-sw.nc /work/noaa/gmtb/dheinzel/TMP_NEW_BASELINE_RRTMGP_20201110/FV3_input_data_RRTMGP/rrtmgp-cloud-optics-coeffs-sw.nc

Orion-login-4[10] dheinzel$ diff ./FV3/ccpp/physics/physics/rte-rrtmgp/extensions/cloud_optics/rrtmgp-cloud-optics-coeffs-lw.nc /work/noaa/gmtb/dheinzel/TMP_NEW_BASELINE_RRTMGP_20201110/FV3_input_data_RRTMGP/rrtmgp-cloud-optics-coeffs-lw.nc

Orion-login-4[12] dheinzel$ diff ./FV3/ccpp/physics/physics/rte-rrtmgp/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc /work/noaa/gmtb/dheinzel/TMP_NEW_BASELINE_RRTMGP_20201110/FV3_input_data_RRTMGP/rrtmgp-data-sw-g224-2018-12-04.nc
Binary files ./FV3/ccpp/physics/physics/rte-rrtmgp/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc and /work/noaa/gmtb/dheinzel/TMP_NEW_BASELINE_RRTMGP_20201110/FV3_input_data_RRTMGP/rrtmgp-data-sw-g224-2018-12-04.nc differ

Orion-login-4[13] dheinzel$ diff ./FV3/ccpp/physics/physics/rte-rrtmgp/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc /work/noaa/gmtb/dheinzel/TMP_NEW_BASELINE_RRTMGP_20201110/FV3_input_data_RRTMGP/rrtmgp-data-lw-g256-2018-12-04.nc
Binary files ./FV3/ccpp/physics/physics/rte-rrtmgp/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc and /work/noaa/gmtb/dheinzel/TMP_NEW_BASELINE_RRTMGP_20201110/FV3_input_data_RRTMGP/rrtmgp-data-lw-g256-2018-12-04.nc differ
```

Can you confirm? in this case I only need to update the latter two files.

**Comment by dustinswales** [comment]
@climbfuji 
This is correct. The cloud-optics files are unchanged.

**Comment by climbfuji** [comment]
> @climbfuji
> This is correct. The cloud-optics files are unchanged.

Ok, thanks. Will try to re-enable the RRTMGP regression tests and use those files. Any other changes I need to make for the regression tests, or have you done everything in ufs-weather-model?

**Comment by dustinswales** [comment]
@climbfuji 
I think I got everything for the RTs in the UFS.

**Comment by climbfuji** [comment]
> @climbfuji
> I think I got everything for the RTs in the UFS.

We'll need to make a bunch of changes wrt iovr_{lw,sw} for some of the regression tests. I'll send a PR your way soon!

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
A note on the regression testing. Compared to the existing baseline, the following tests fail (therefore a new baseline):

- These tests fail because of a missing baseline to compare against (new tests):
```
fv3_ccpp_gfs_v15p2_RRTMGP 041 failed in check_result
fv3_ccpp_gfs_v16beta_RRTMGP 042 failed in check_result
fv3_ccpp_gfs_v15p2_RRTMGP_debug 051 failed in check_result
fv3_ccpp_gfs_v16beta_RRTMGP_debug 052 failed in check_result
```
- These tests fail because of a small change to diagnostic cloud output when HWRF RRTMG (`iovr=4`) is used. This is ok, the changes are only in the diagnostic output, small and only in one field (`tcdc_avebndcl` --> `IntDiag(nb)%fluxr(:,18)`)
```
fv3_ccpp_HAFS_v0_hwrf_thompson 047 failed in check_result
fv3_ccpp_HAFS_v0_hwrf_thompson_debug 058 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson 048 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson_debug 059 failed in check_result
```

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
need to revert fv3 after fv3 PR is committed.

**Comment by climbfuji** [comment]
Submodule pointer looks ok, ready to merge!

**Pull request merged**
