### PR TITLE
[production/AQM.v7] Update WCOSS2 Intel lua for production available packages/libraries.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Description

Update WCOSS2 Intel .lua for production available libraries/packages

### Input data additions/changes
- [X] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [X] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

## Commit Queue Checklist:

- [X] Link PR's from all sub-components involved
- [X] Confirm reviews completed in sub-component PR's
- [X] Add all appropriate labels to this PR.
- [X] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [X] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

No dependencies. Only UFSWM change.

## Testing Day Checklist:

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [X] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- WCOSS2
  - [X] Dogwood/Cactus

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA I can't add you as a reviewer somehow. Please review this, ASAP.

**Review by chan-hoo — APPROVED** [review]

**Review by JianpingHuang-NOAA — COMMENTED** [review]
Please delete version numbers from the module lua files and add version numbers in build.ver and run.ver files under ~/version.

**Comment by JianpingHuang-NOAA** [comment]
Please an example from AQMv6 operational system at 
/lfs/h1/ops/prod/packages/aqm.v6.1.7/modulefiles/aqm > vim 6.1.2.lua
/lfs/h1/ops/prod/packages/aqm.v6.1.7/versions > vi build.ver

**Comment by BrianCurtis-NOAA** [comment]
The .lua files handle the version numbers from the build.ver and run.ver files AND set defaults if it doesn't see those _ver variables
so we don't need to change anything like that in the ufs-weather-model, any change of package version in the workflow will make its way into the ufs-weather-model OK

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, as @BrianCurtis-NOAA said, the update of the `build.ver` and `run.ver` is not part of this PR. I've already updated them in the production branch of the ufs srw app.

**Review by JianpingHuang-NOAA — APPROVED** [review]

**Comment by JianpingHuang-NOAA** [comment]
Thanks

**Pull request merged**
