### PR TITLE
Update WW3 for porting and threading issues 

### LINKED ISSUE #367: Fully coupled test case (cpld_bmarkfrac_wave_v16) not thread-safe
## Description
It has been reported by @SMoorthi-emc and @shansun6 that when running cpld_bmarkfrac_wave_v16 test with and without threads do not reproduce each other.   

### To Reproduce:

Run cpld_bmarkfrac_wave_v16 and then run cpld_bmarkfrac_wave_v16 with multiple threads 

## Additional context

Going to try to run with different aspects of wave coupling turned on or off (ie, no wave feedback to ocean) to narrow down area to look for what part of the code is not thread safe.  Will update when have more information. 

@SMoorthi-emc to turn off OMP parts of WW3, remove [OMPG OMPH](https://github.com/NOAA-EMC/WW3/blob/develop/model/esmf/switch#L6-L7)  from WW3/model/esmf/switch

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Description

This PR updates WW3 to the latest develop branch, which has updates for threading (see Issue #367)
it also has updates for WW3 to be able to be build on gaea, jet and theoretically with gnu compilers although that has not been tested.  

### Issue(s) addressed

- fixes #367

## Testing

How were these changes tested? On hera 
What compilers / HPCs was it tested with? intel 
Are the changes covered by regression tests? No, tests should be added for testing WW3 thread safe and tests should be turned on for waves on other platforms.   The WW3 thread safe test ran into an issue that we are having issues with the number of MPI tasks changing answers (Issue #427 ) which will be addressed in another PR.   The code compiles on Gaea but I did not have access to an account that can run the tests (request has been submitted), so the tests were not turned on.  Theoretically the code should be able to compile on jet now as well. 
Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? hera.intel so far

## Dependencies

The PR in WW3 is merged https://github.com/NOAA-EMC/WW3/pull/315

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Does this fix the bug that WW3 was crashing at runtime if built with -qopenmp?

**Comment by JessicaMeixner-NOAA** [comment]
> Does this fix the bug that WW3 was crashing at runtime if built with -qopenmp?

@BrianCurtis-NOAA I don't actually remember that issue, can you help refresh my memory?  WW3 should be getting compiled with -qopenmp:  https://github.com/NOAA-EMC/WW3/blob/develop/model/bin/cmplr.env#L160-L167

**Comment by BrianCurtis-NOAA** [comment]
I can't remember why but It was built OK with -qopenmp but somehow kept crashing at runtime.
If you want it to build with -qopenmp in UFS you will want to un-comment the multiple
`#if(OpenMP_Fortran_FOUND)
#  target_link_libraries(mom6 PRIVATE OpenMP::OpenMP_Fortran)
#endif()`
in MOM6-interface/CMakeLists.txt

**Comment by JessicaMeixner-NOAA** [comment]
@BrianCurtis-NOAA WW3 is not yet getting options from the upper level cmake for build, so I'm puzzled to why other models using openMP would cause WW3 to crash? I know the atm-wav coupled can both use open mp.  Since you put MOM6 as your example, I'm wondering if this is an MOM6/S2S issue that you see even without WW3?   I don't think this PR would solve the issue you are describing.  This was just for if you ran WW3 with 1 or 2 threads that it would give you the same answer when two-way coupled to the atm model.

**Comment by BrianCurtis-NOAA** [comment]
I see I read this wrong. You can ignore me.

**Comment by JessicaMeixner-NOAA** [comment]
Merged with the latest ufs-weather-model and also updated WW3 to the top of it's develop branch.  hera.intel logs updated. 

This PR could be combined with another one, or whatever is most convenient.

**Comment by DeniseWorthen** [comment]
Merged in PR #383

**Pull request closed without merging**
