### PR TITLE
Use saved routehandles in fv3 cap init phase

### LINKED ISSUE #1433: Add run time options to save/load route handles to/from external file.
## Description
Computing remapping route handles in fv3atm is computationally expensive, especially for large model and output grids. Since these are not changed from run to run in production, we can speed up the initialization phase by saving computed route handles once, and use them in subsequent runs, speeding up the initialization.  

## Solution
Add run time options to save/load route handles to/from external file.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR adds new runtime configuration option (use_saved_routehandles:) to the model_configure file, which when set to true will save compute remapping route handles to a file, and use it in the subsequent runs avoiding computation of routehandles again. Subsequent runs must use the same compute and output domains and same domain decomposition.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1433

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? Yes.
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/585

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA We are about to merge in #1438. Then we can start working on this pr. Can we combine in @RatkoVasic-NOAA 's #1418 ?

**Comment by DusanJovic-NOAA** [comment]
My branches are up to date.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @DusanJovic-NOAA it seems like Ratko is not available this afternoon. Let's start working on this PR first and then we will commit #1418 Monday or Tuesday. I will update the commit queue table accordingly.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1064282637/20220930230007/ufs-weather-model
[RT] Error: Test compile_011 failed in run_compile failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA All tests are done. We can start merging process. [fv3atm pr 585]([](https://github.com/NOAA-EMC/fv3atm/pull/585)) first.

**Comment by BrianCurtis-NOAA** [comment]
@DusanJovic-NOAA @jkbk2004 FV3 merged: https://github.com/NOAA-EMC/fv3atm/commit/a01627fd33a7c5fd5d9682e4dae0058f3dbee425

**Review by DeniseWorthen — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
