### PR TITLE
Additional template variables for CICE namelist

### LINKED ISSUE #1999: export component defaults instead of application defaults for coupled configs
## Description

ATM defaults (fv3) are set in ``default_vars`` but the other component defaults (eg ice, ocean, wave) are set at the application level (ie, ``export_cpl``). This means that defaults for the ICE component are repeated in both the ``export_cpl`` and ``export_datm_cdeps``. Similarly for both MOM6 and WW3. This is error-prone. 

## Solution

Add component defaults for CICE, MOM6, HYCOM and WW3. Additional OCN or ATM models (eg as part of new coastal app) would then have their own component specific defaults.

### PR DESCRIPTION
**Pull request by aerorahul**
## PR Author Checklist:

- [X] I have linked PR's from all sub-components involved in section below. 
- [X] I am confirming reviews are completed in ALL sub-component PR's.
- [ ] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [X] I have filled out all sections of the template.

## Description
This PR:
- adds a function `export_cice6` in `default_vars.sh` defining additional template variables used in the CICE6 namelist `ice_in_template`.  This is done to avoid repetition in the functions `export_cpl` and `export_datm_cdeps`
- calls the function `export_cice6` in `export_cpl` and `export_datm_cdeps`
- updates the `ice_in_template` to templatize the additional variables defined in `export_cice6`.

This work is needed to allow the GFS/GEFS applications to use the model hosted templates.

## Linked Issues and Pull Requests
This work is part of #1664 

- resolves #1999 for the ICE model

### Subcomponent Pull Requests
None

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [X] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
I'd like to combine this with a similar fix for MOM6 and renaming the templates to .IN. Working on a testing branch now.

**Comment by BrianCurtis-NOAA** [comment]
I think we're just waiting on a verification Hera log showing all baselines passing before this can be added to the commit queue or merged with another PR.

**Comment by aerorahul** [comment]
> @aerorahul please bring these up to date with respective authoritative repositories
> 
> * ufs-weather-model **NOT** up to date
> * fv3 **NOT** up to date

done.

**Comment by DeniseWorthen** [comment]
@aerorahul Please take a look at PR #2010, which incorporates this and other changes.

**Comment by aerorahul** [comment]
> @aerorahul Please take a look at PR #2010, which incorporates this and other changes.

@DeniseWorthen 
The changes to `ice_in.IN` in #2010 are consistent with those in this PR.  
Thank you for updating the other templates as well.  That will need additional work in the global-workflow and we look forward to it.
I think this PR can be closed as the changes are incorporated in #2010

**Pull request closed without merging**
