### PR TITLE
* Update CDEPS; Add coupled C48-5deg ocean+ice warm-start and restart test (was #1336)

### LINKED ISSUE #1284: Update CDEPS componet to include the latest changes from ESCOMP/CDEPS
## Description
Update CDEPS component to include the latest changes from ESCOMP/CDEPS.

## Solution
1. Update CDEPS component.
2. Update parameters "taxmode01" and "stream_vectors01" in datm streams files.
3. Revised GEFS forcing files will be used. The reference time in the revised GEFS forcing files is changed from 0001-01-01 00:00:00 to 1970-01-01 00:00:00.0.

## Related issue and pull request:
https://github.com/NOAA-EMC/CDEPS/issues/46
https://github.com/NOAA-EMC/CDEPS/pull/47

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
Update CDEPS component to include the latest changes from ESCOMP/CDEPS.

Update parameters "taxmode01" and "stream_vectors01" in datm streams files.

Revised GEFS forcing files will be used. The reference time in the revised GEFS forcing files is changed from 0001-01-01 00:00:00 to 1970-01-01 00:00:00.0.

The revised GEFS forcing files are located at /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20220414/DATM_CDEPS/GEFS_NEW on Hera.

### Issue(s) addressed

- fixes #1284 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [NA] wcoss2.intel Not available
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting for https://github.com/NOAA-EMC/CDEPS/pull/47

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/autort/tests/auto/pr/978191845/20220722121513/ufs-weather-model
[BL] Error: Test cpld_bmark_p8 004 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by DeniseWorthen** [comment]
This was a time-out for the cpld_bmark_p8 on cheyenne.intel

**Comment by jkbk2004** [comment]
Sure! I will check that.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/978191845/20220723123014/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/978191845/20220724221514/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by jkbk2004** [comment]
@junwang-noaa @BinLiu-NOAA @BrianCurtis-NOAA @binli2337 all tests are passed. can we go ahead to start merging?

**Comment by binli2337** [comment]
@junwang-noaa Please review NOAA-EMC/CDEPS PR #47. Thanks.

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
From wcoss2.intel:
```
/lfs/h2/emc/nems/noscrub/brian.curtis/git/binli2337/ufs-weather-model/CDEPS-interface/CDEPS/dshr/dshr_mod.F90(1068): error #6404: Th
is name does not have a type, and must have an explicit type.   [PIO_FILL]
    rcode = pio_set_fill(pioid, PIO_FILL, oldmode)
--------------------------------^
/lfs/h2/emc/nems/noscrub/brian.curtis/git/binli2337/ufs-weather-model/CDEPS-interface/CDEPS/dshr/dshr_mod.F90(1068): error #6404: Th
is name does not have a type, and must have an explicit type.   [PIO_SET_FILL]
    rcode = pio_set_fill(pioid, PIO_FILL, oldmode)
------------^
```
From this compile:
```
+ cmake /lfs/h2/emc/nems/noscrub/brian.curtis/git/binli2337/ufs-weather-model -DAPP=HAFS-ALL -DCCPP_SUITES=FV3_HAFS_v0_gfdlmp_tedmf,
FV3_HAFS_v0_gfdlmp_tedmf_nonsst -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release
```

**Review by DeniseWorthen — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
> From wcoss2.intel:
> 
> ```
> /lfs/h2/emc/nems/noscrub/brian.curtis/git/binli2337/ufs-weather-model/CDEPS-interface/CDEPS/dshr/dshr_mod.F90(1068): error #6404: Th
> is name does not have a type, and must have an explicit type.   [PIO_FILL]
>     rcode = pio_set_fill(pioid, PIO_FILL, oldmode)
> --------------------------------^
> /lfs/h2/emc/nems/noscrub/brian.curtis/git/binli2337/ufs-weather-model/CDEPS-interface/CDEPS/dshr/dshr_mod.F90(1068): error #6404: Th
> is name does not have a type, and must have an explicit type.   [PIO_SET_FILL]
>     rcode = pio_set_fill(pioid, PIO_FILL, oldmode)
> ------------^
> ```
> 
> From this compile:
> 
> ```
> + cmake /lfs/h2/emc/nems/noscrub/brian.curtis/git/binli2337/ufs-weather-model -DAPP=HAFS-ALL -DCCPP_SUITES=FV3_HAFS_v0_gfdlmp_tedmf,
> FV3_HAFS_v0_gfdlmp_tedmf_nonsst -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release
> ```

@BinLiu-NOAA Looks like this HAFS test is failing on WCOSS2. I'm guessing it's the INTEL compiler version they use on there as the newer INTEL version on RDHPCS machines are going OK.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA thanks for checking the issue on wcoss2. @binli2337 I will go ahead to merge in a bit.

**Pull request merged**
