### PR TITLE
Add no_nsst regression tests

### PR DESCRIPTION
**Pull request by climbfuji**
Add regression tests for no_nsst CCPP suites.

Associated PR: https://github.com/NOAA-EMC/fv3atm/pull/69

For regression testing see below.

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]
We need to update the RT log files. Once that is done, we can commit fv3 pull request.

**Comment by climbfuji** [comment]
Regression tests against newly created baseline pass for Cheyenne+Intel, logs have been updated.

[rt_cheyenne_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4226496/rt_cheyenne_intel.log)

**Comment by climbfuji** [comment]
@DusanJovic-NOAA @junwang-noaa can you please rsync /scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_INTEL/ to the new date tag?
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/ufs-public-release-20200219/

Thanks!

**Comment by DusanJovic-NOAA** [comment]
Synced ``/scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_INTEL`` to ``ufs-public-release-20200219``

**Comment by climbfuji** [comment]
Regression tests against newly created baseline pass for Cheyenne+GNU, logs have been updated.

[rt_cheyenne_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/4227503/rt_cheyenne_gnu.log)

**Comment by climbfuji** [comment]
> Synced `/scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_INTEL` to `ufs-public-release-20200219`

Thanks, kicked off the final tests a few minutes ago ...

**Comment by climbfuji** [comment]
Regression tests against newly created baseline pass for Hera+Intel, logs have been updated.

[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4227934/rt_hera_intel.log)

**Pull request merged**
