### PR TITLE
Refactor surface restart logic in FV3GFS_io.F90 to not use hard-coded indices.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR are specified below.

- [ ] ~~Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.~~

- [ ] ~~New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.~~

## Description

The surface restart used hard-coded indices, which makes it difficult to add new restart variables, especially if different land surface schemes need different numbers of variables. This is problematic for developer @tanyasmirnova who has that exact problem.

### Issue(s) addressed

https://github.com/NOAA-EMC/fv3atm/issues/604

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

fv3atm = https://github.com/NOAA-EMC/fv3atm/pull/605

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA we are trying to merge in #1518. I want to see if this pr can be combined into #1467. @DusanJovic-NOAA would it be ok?

**Comment by SamuelTrahanNOAA** [comment]
I don't see any conflicts.

**Comment by DusanJovic-NOAA** [comment]
> @SamuelTrahanNOAA we are trying to merge in #1518. I want to see if this pr can be combined into #1467. @DusanJovic-NOAA would it be ok?

I'm ok with that.

**Comment by SamuelTrahanNOAA** [comment]
@DusanJovic-NOAA - could you please check that I merged your PR into mine correctly?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA - could you please check that I merged your PR into mine correctly?

Looks correct. Thanks.

**Comment by SamuelTrahanNOAA** [comment]
I have merged the HAFS PR #1518 into this one, and successfully run the hera.intel and hera.gnu tests.

**Comment by SamuelTrahanNOAA** [comment]
Oh, also #1467 is in this PR. The tests passed with the #1497 + #1467 combination, and with the #1497 + #1467 + #1518 combination.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA #1518 was merged. Can you sync up and resolve conflicts one more time? No baseline change with the pr. So the test will go smoothly.

**Comment by SamuelTrahanNOAA** [comment]
It is merged and I'm running a test of hera.gnu now, to convince myself it still works.

**Comment by BrianCurtis-NOAA** [comment]
> It is merged and I'm running a test of hera.gnu now, to convince myself it still works.

I'm running on Acorn/Cactus, I'll let you know it anything comes up.

**Comment by SamuelTrahanNOAA** [comment]
My hera.gnu tests passed.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 or @BrianCurtis-NOAA - You should rerun the hera.gnu tests, to make sure they pass for you, not just for me.

**Comment by jkbk2004** [comment]
All tests are done. We can start merging process. [cubed sphere pr 223 first](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/223)

**Comment by SamuelTrahanNOAA** [comment]
I'm sitting at a computer, ready to update my branches, as soon as https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/223 is merged.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA Do you think you can revert the change of #1467? A bug was reported on fms side: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/223. We need to hold #1467

**Comment by jkbk2004** [comment]
> @SamuelTrahanNOAA Do you think you can revert the change of #1467? A bug was reported on fms side: [NOAA-GFDL/GFDL_atmos_cubed_sphere#223](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/223). We need to hold #1467

@DusanJovic-NOAA FYI

**Comment by SamuelTrahanNOAA** [comment]
Yes, but you'll have to give me a few hours to check things. I should have it by this afternoon certainly, and maybe earlier.

**Comment by SamuelTrahanNOAA** [comment]
I'll probably do some forced pushes to revert to the state of the branches before merging #1467, and then merge #1518. It's not the most elegant way, but it's the quickest and easiest.

**Comment by jkbk2004** [comment]
Sure! I will stand by. I think I will run RT on a few machines to make sure once you are ready.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 I have reapplied the changes to the top of develop and I did a force push to replace the entire branch. It passes hera.gnu and hera.intel. You will need to re-run the other tests.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA can we double check on wcoss2? I am going to test on other machines.

**Comment by SamuelTrahanNOAA** [comment]
The automatic checks are failing due to a strange error:

```
Run helper_id=$(cat ~/id_file)
cat: /home/runner/id_file: No such file or directory
Error: Process completed with exit code 1.
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1127767038/20221219203009/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by SamuelTrahanNOAA** [comment]
Are the tests running? I don't see any jobs under emc.nemspara on Jet, and the github checks are failing because of an internal error.

**Comment by jkbk2004** [comment]
@zach1221 is manually testing on jet. I am running on cheyenne as well.

**Comment by jkbk2004** [comment]
> The automatic checks are failing due to a strange error:
> 
> ```
> Run helper_id=$(cat ~/id_file)
> cat: /home/runner/id_file: No such file or directory
> Error: Process completed with exit code 1.
> ```

I don't worry about this error. It tries to pick up git workflow run id. It was used in run-ci to handle the label.

**Comment by jkbk2004** [comment]
jet is very slow. Tests are running ok but only halfway overnight. We can skip jet. @SamuelTrahanNOAA we can start merging process.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA fv3atm dependency was merged. we can merge in this pr with submodule update and revert in gitmodules.

**Comment by SamuelTrahanNOAA** [comment]
I'm pointing to the NOAA-EMC fv3atm develop now.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
