### PR TITLE
Convert real(kind_phys) vegetation, slope and soil type arrays into integer arrays without affecting input/output files, update submodule pointer for CMakeModules (updates to FindNetCDF.cmake and FindESMF.cmake), switch to EMC hpc-stack on gaea, update utest/opnReqTest

### LINKED ISSUE #273: Transfer Gaea responsibilities from Dom to EMC
@climbfuji currently manages hpc-stack on Gaea. That responsibility should be transferred to EMC.

@climbfuji how do you want to do this?

With the next release of hpc-stack? Or if you want to transfer the current installation to me with `chown`?

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR only updates the submodule pointers for fv3atm and ccpp-physics for the changes described in the dependent PRs below (convert real(kind_phys) vegetation, slope and soil type arrays into integer arrays without affecting input/output files).

Also included:
- Update submodule pointer for CMakeModules (updates to `FindNetCDF.cmake` and `FindESMF.cmake`)
- Gaea only: switch to hpc-stack maintained by EMC (@kgerheiser)
- Update to utest (now opnReqTest) CI testing from @MinsukJi-NOAA 

No changes to the input files.

**Update 2021/09/30** The regression test `fv3_gsd` now has different results with Intel on Hera. It starts at 24h forecast time with a minimal difference in one of the tiles, and then propagates to all tiles. The regression test `fv3_gsd_debug` (running out to 6h only) is b4b identical. With GNU, both the 48h forecast `fv3_gsd` and the 6h forecast `fv3_gsd_debug` are b4b identical. I then ran the DEBUG version out to 48h, and the results between the original code andd this PR were identical. Thus, the b4b difference for `fv3_gsd` with Intel in PROD mode is due to an optimization round-off difference in RUC LSM.

**Update 2021/10/01** Switching to hpc-stack maintained by EMC (@kgerheiser) on gaea changes the "results" for the following regression tests - on gaea only, of course, and only in the Grib2 files produced by the regional inline post:
```
Dom.Heinzeller@gaea12:/lustre/f2/scratch/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove-noah-wrfv4-bugfix-mp-thompson/tests [intel|esrl_bmcs]> cat log_gaea.intel/rt_038_regional_quilt_2threads.log

baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20210928/INTEL/fv3_regional_quilt
working dir  = /lustre/f2/scratch/Dom.Heinzeller/FV3_RT/rt_38214/regional_quilt_2threads
Checking test 038 regional_quilt_2threads results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc .........OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

 0: The total amount of wall time                        = 267.801442

Test 038 regional_quilt_2threads FAIL

Dom.Heinzeller@gaea12:/lustre/f2/scratch/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove-noah-wrfv4-bugfix-mp-thompson/tests [intel|esrl_bmcs]> cat log_gaea.intel/rt_041_regional_quilt_RRTMGP.log

baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20210928/INTEL/fv3_regional_quilt_RRTMGP
working dir  = /lustre/f2/scratch/Dom.Heinzeller/FV3_RT/rt_38214/regional_quilt_RRTMGP
Checking test 041 regional_quilt_RRTMGP results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc .........OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

 0: The total amount of wall time                        = 469.675394

Test 041 regional_quilt_RRTMGP FAIL

Dom.Heinzeller@gaea12:/lustre/f2/scratch/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove-noah-wrfv4-bugfix-mp-thompson/tests [intel|esrl_bmcs]> cat log_gaea.intel/rt_037_regional_quilt.log

baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20210928/INTEL/fv3_regional_quilt
working dir  = /lustre/f2/scratch/Dom.Heinzeller/FV3_RT/rt_38214/regional_quilt
Checking test 037 regional_quilt results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc .........OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

 0: The total amount of wall time                        = 858.850208

Test 037 regional_quilt FAIL
```
@WenMeng-NOAA helped me to look at the differences, and they are only in the grib2 header section. The data itself is 100% identical. Please look at the discussion in https://github.com/NOAA-EMC/hpc-stack/issues/337 (towards the bottom) for more details.

### Issue(s) addressed

- fixes https://github.com/NCAR/ccpp-physics/issues/704
- fixes https://github.com/NOAA-EMC/hpc-stack/issues/273

### Initial regression testing

Full regression tests passed on hera.intel against existing baseline.

### Final regression testing

Regression tests will be run on all tier-1 platforms:

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1303798496

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/730
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/388

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20210930154516/ufs-weather-model
Please make changes and add the following label back:
hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20210930154949/ufs-weather-model
Please make changes and add the following label back:
hera-gnu-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: hera
> Compiler: intel
> Job: RT
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20210930154516/ufs-weather-model
> Please make changes and add the following label back:
> hera-intel-RT

This was because of the wrong permissions for `run_compile.sh`, the executable flags got removed in my PR accidentally. I fixed it in https://github.com/ufs-community/ufs-weather-model/pull/804/commits/429302aaed6f37182620959754a7df8e91febf6a and resubmitted hera-intel-RT, will do the same with GNU once/if it comes back with the same error.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20210930160013/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_18085
Test fv3_gsd 043 failed in check_result failed 
Test fv3_gsd 043 failed in run_test failed 
Test cpld_restart_c384 009 failed failed 
Test cpld_restart_c384 009 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20211001183022/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_11974
Test cpld_control_c384_p7 004 failed failed 
Test cpld_control_c384_p7 004 failed in run_test failed 
Test hafs_regional_docn_oisst 062 failed failed 
Test hafs_regional_docn_oisst 062 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: hera
> Compiler: intel
> Job: BL
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20211001183022/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_11974
> Test cpld_control_c384_p7 004 failed failed
> Test cpld_control_c384_p7 004 failed in run_test failed
> Test hafs_regional_docn_oisst 062 failed failed
> Test hafs_regional_docn_oisst 062 failed in run_test failed
> Please make changes and add the following label back:
> hera-intel-BL

Both tests timed out - this happens very often recently, especially for the coupled control c384 tests. Will do the rest manually.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/734707651/20211001131516/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_324273
Test cpld_control_wave_p7 002 failed failed 
Test cpld_control_wave_p7 002 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by climbfuji** [comment]
> /work/noaa/nems/emc.nemspara/autort/pr/734707651/20211001131516/ufs-weather-model

```
4 min. TEST 002 cpld_control_wave_p7 is running,  status: R jobid 3242582
Slurm unknown status -. Check sacct ...
3242582                    FAILED        rt_324273_002
3242582.bat+               FAILED                batch
3242582.ext+        OUT_OF_MEMORY               extern
3242582.0       CANCELLED by 8555              fv3.exe
```

Note the out of memory message. The P7 tests are probably sailing close to the limit.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20211003031514/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_16988
Test datm_cdeps_mx025_gefs 086 failed failed 
Test datm_cdeps_mx025_gefs 086 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: hera
> Compiler: intel
> Job: RT
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20211003031514/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_16988
> Test datm_cdeps_mx025_gefs 086 failed failed
> Test datm_cdeps_mx025_gefs 086 failed in run_test failed
> Please make changes and add the following label back:
> hera-intel-RT

Something is wrong recently with hera ...
```
29 min. TEST 086 datm_cdeps_mx025_gefs is running,  status: R jobid 23821372
30 min. TEST 086 datm_cdeps_mx025_gefs is running,  status: R jobid 23821372
Slurm unknown status CG. Check sacct ...
23821372                  TIMEOUT         rt_16988_086
23821372.ba+            CANCELLED                batch
23821372.ex+            COMPLETED               extern
23821372.0                TIMEOUT              fv3.exe
31 min. TEST 086 datm_cdeps_mx025_gefs is TIMEOUT,  status: CG jobid 23821372
```

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@DusanJovic-NOAA @junwang-noaa @MinsukJi-NOAA I merged in the changes from Minsuk (https://github.com/climbfuji/ufs-weather-model/pull/11) and added the run-ci and hera-intel-rt labels. The submodule pointer for fv3atm is also updated and correct. Please check the PR again while the regression tests / CI tests are running. Thanks!

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
CI tests passed, waiting for final hera-intel RT runs. If those come back successfully, whoever gets to it first please merge.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20211004134511/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_2258
Test cpld_restart_c384_p7 009 failed failed 
Test cpld_restart_c384_p7 009 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by MinsukJi-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: hera Compiler: intel Job: RT Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/734707651/20211004134511/ufs-weather-model Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_2258 Test cpld_restart_c384_p7 009 failed failed Test cpld_restart_c384_p7 009 failed in run_test failed Please make changes and add the following label back: hera-intel-RT

cpld_restart_c384_p7 run never got started and eventually timed out. Will manually run this case.

**Comment by MinsukJi-NOAA** [comment]
Hera Intel RT passed, and this PR is ready for merge.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/734707651/20211001181505/ufs-weather-model
Please make changes and add the following label back:
gaea-intel-BL

**Pull request merged**
