### PR TITLE
CLM Lake pressure is not density and GFS Diagnostics: weasdi is not snodi + #2047, #2053, and #2056

### LINKED ISSUE #2015: multiple netcdf_parallel tests fail on hercules
## Description

The control_wrtGauss_netcdf_parallel_intel fails on hercules (intel) with the following error:

```
2023-11-29 11:42:48.544357 +0000 ERROR /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.5.0-rc1/cache/build_stage/spack-s\
tage-nccmp-1.9.0.1-4n5sfwacmwzksu4hkop5vwvjpqowwa3o/spack-src/src/nccmp_data.c:3675 NetCDF: HDF error
```

which results in 

```
 Comparing atmf024.nc ............ALT CHECK......ERROR
```

### To Reproduce:

Attempt to run this test on Hercules, check the ``atmf024.nc_nccmp.log`` file in the run directory for the error message.

## Additional context

The issue was first noted in PR #1990.

### LINKED ISSUE #2055: crash when running GFS PBL/sfclay and clm lake in RRFS ensemble
## Description

A couple of RRFS ensemble members crashed with GFS PBL (TKE-EDMF)/sfclay and clm lake combined. This happened when lake water was frozen to lake ice in clm lake.

The reason for the crash is because clm lake is called between surface layer scheme and PBL scheme. If there is a state change in clm lake, particularly water turning into ice, stability related variables over ice will be missing and cause the crash.

### To Reproduce:
1. perform a forecast with GFS PBL/sfclayer combined with clm lake
2. wait for lake water turning into lake ice, which could happen in winter time further north
3. model crashed with AVOST error message from RUC LSM

## Output
      
AVOST IN VILKA     Table index=  -2147483648

 I,J=           1           1 LU_index =           17 Psfc[hPa] =

NaN Tsfc =    262.537014420372

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Hercules AND have attached the log to this PR below this line:
  - LOG: Hera log is committed to branch.
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

***PRs #2047, #2053, and #2056 are combined into this one.***

Fixes two bugs:

1. CLM Lake was using near-surface pressure in place of near-surface density.
2. GFS_diagnostics was outputting weasdi (water equivalent snow depth over ice) in place of snodi (snow depth over ice)

Fixes are from @tanyasmirnova 

## Commit Message

```
FV3 diagnostic fixes, CCPP fixes for model crashes, new PR template

- UFS:
    - commit message in PR template (#2053)
    - fix hercules crashes (#2015)
- CMEPS & FV3: Bad data from in CCPP CLM Lake physics scheme caused model crashes
    - Communicate changes to lake ice (Closes #2055, NOAA-EMC/CMEPS#105, NOAA-EMC/fv3atm#741) 
    - unit mismatch (NOAA-EMC/fv3atm#736)
- FV3: correct errors in diagnostic calculations
    - snodi had weasdi data in it (NOAA-EMC/fv3atm#736)
    - revisions to RUC LSM snowfall melting and accumulation (NOAA-EMC/fv3atm#739)
```

### Associated UFSWM Issue to close
- closes #2047
- closes #2056 

- fixes #2015

Due to combining #2056:

- fixes #2055 

### Subcomponent Pull Requests
- waiting on https://github.com/ufs-community/ccpp-physics/pull/139
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/736
- waiting on https://github.com/NOAA-EMC/CMEPS/pull/105

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.

### Regression Tests:
- [x] Changes are expected to the following tests:

All tests with "hrrr" or "clm_lake" in their name.

<details> <summary>List of tests in rt.conf format</summary>

```bash
COMPILE | rrfs | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_RAP_sfcdiff,FV3_HRRR,FV3_RRFS_v1beta,FV3_RRFS_v1nssl -D32BIT=ON | | fv3 |
RUN | hrrr_control                                      | - noaacloud                | baseline |
RUN | hrrr_control_decomp                               | - noaacloud                |          |
RUN | hrrr_control_2threads                             | - noaacloud                |          |
RUN | hrrr_control_restart                              | - noaacloud                |          | hrrr_control
COMPILE | atm_debug_dyn32 | intel | -DAPP=ATM -DDEBUG=ON -D32BIT=ON -DCCPP_SUITES=FV3_HRRR,FV3_GFS_v16,FV3_GFS_v16_csawmg,FV3_GFS_v16_ras,FV3_GFS_v17_p8,FV3_GFS_v15_thompson_mynn_lam3km,FV3_RAP,FV3_RAP_unified_ugwp,FV3_RAP_cires_ugwp,FV3_RAP_flake,FV3_RAP_clm_lake,FV3_RAP_noah,FV3_RAP_sfcdiff,FV3_RAP_noah_sfcdiff_cires_ugwp,FV3_RRFS_v1beta,FV3_HRRR_c3,FV3_HRRR_gf,FV3_global_nest_v1 | - noaacloud  | fv3 |
RUN | hrrr_control_debug                                | - noaacloud                  | baseline |
RUN | hrrr_gf_debug                                     | - noaacloud                  | baseline |
RUN | hrrr_c3_debug                                     | - noaacloud                  | baseline |
RUN | rap_clm_lake_debug                                | - noaacloud                  | baseline |
COMPILE | rrfs_dyn32_phy32 | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR -D32BIT=ON -DCCPP_32BIT=ON |  - noaacloud  | fv3 |
RUN | hrrr_control_dyn32_phy32                          | - noaacloud                  | baseline |
RUN | hrrr_control_2threads_dyn32_phy32                 | - derecho noaacloud          |          |
RUN | hrrr_control_decomp_dyn32_phy32                   | - noaacloud                  |          |
RUN | hrrr_control_restart_dyn32_phy32                  | - noaacloud                  |          | hrrr_control_dyn32_phy32
COMPILE | rrfs_dyn32_phy32_debug | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR,FV3_HRRR_gf -D32BIT=ON -DCCPP_32BIT=ON -DDEBUG=ON | - noaacloud  | fv3 |
RUN | hrrr_control_debug_dyn32_phy32                    |  - noaacloud                 | baseline |
COMPILE | rrfs | gnu | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_RAP_sfcdiff,FV3_HRRR,FV3_RRFS_v1beta -D32BIT=ON | + hera hercules | fv3 |
RUN | hrrr_control                                      | + hera hercules            | baseline |
RUN | hrrr_control_noqr                                 | + hera hercules            |          |
RUN | hrrr_control_2threads                             | + hera hercules            |          |
RUN | hrrr_control_decomp                               | + hera hercules            |          |
RUN | hrrr_control_restart                              | + hera hercules            |          | hrrr_control
RUN | hrrr_control_restart_noqr                         | + hera hercules            |          | hrrr_control_noqr
COMPILE | atm_dyn32_debug | gnu | -DAPP=ATM -D32BIT=ON -DDEBUG=ON | + hera hercules | fv3 |
RUN | hrrr_control_debug                                | + hera hercules            | baseline |
RUN | hrrr_gf_debug                                     | + hera hercules            | baseline |
RUN | hrrr_c3_debug                                     | + hera hercules            | baseline |
RUN | rap_clm_lake_debug                                | + hera hercules            | baseline |
COMPILE | rrfs_dyn32_phy32 | gnu | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR -D32BIT=ON -DCCPP_32BIT=ON | + hera hercules | fv3 |
RUN | hrrr_control_dyn32_phy32                          | + hera hercules            | baseline |
RUN | hrrr_control_2threads_dyn32_phy32                 | + hera hercules            |          |
RUN | hrrr_control_decomp_dyn32_phy32                   | + hera hercules            |          |
RUN | hrrr_control_restart_dyn32_phy32                  | + hera hercules            |          | hrrr_control_dyn32_phy32
COMPILE | atm_dyn32_phy32_debug | gnu | -DAPP=ATM -D32BIT=ON -DCCPP_32BIT=ON -DDEBUG=ON | + hera hercules | fv3 |
RUN | hrrr_control_debug_dyn32_phy32                    | + hera hercules            | baseline |
```

</details>

### Libraries

- [x] Not Needed

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 @FernandoAndrade-NOAA - I'd like to combine PR #2047 into this one. The RRFS model needs them urgently. They're both small tweaks to RRFS physics code, which change answers for (mostly) RRFS physics variants.

**Comment by jkbk2004** [comment]
> @jkbk2004 @FernandoAndrade-NOAA - I'd like to combine PR #2047 into this one. The RRFS model needs them urgently. They're both small tweaks to RRFS physics code, which change answers for (mostly) RRFS physics variants.

Sure! I updated the queue table to work on this pr after #2041.

**Comment by SamuelTrahanNOAA** [comment]
> > @jkbk2004 @FernandoAndrade-NOAA - I'd like to combine PR #2047 into this one. The RRFS model needs them urgently. They're both small tweaks to RRFS physics code, which change answers for (mostly) RRFS physics variants.
> 
> Sure! I updated the queue table to work on this pr after #2041.

I'll wait until tomorrow to merge #2047 into this PR. That'll give more time for people to look at the PRs independently.

**Review by tanyasmirnova — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
I am waiting to hear back from @JiliDong-NOAA about the status of #2056 

On a local working copy, I've merged #2047 and #2056 into this PR. Conflicts were easy to resolve. I'd rather not test twice. I'm waiting to hear back from @JiliDong-NOAA that #2056 is ready for final testing.

**Comment by SamuelTrahanNOAA** [comment]
> I am waiting to hear back from @JiliDong-NOAA about the status of #2056
> 
> On a local working copy, I've merged #2047 and #2056 into this PR. Conflicts were easy to resolve. I'd rather not test twice. I'm waiting to hear back from @JiliDong-NOAA that #2056 is ready for final testing.

Jili says the PR #2056 is ready for testing. I'll begin momentarily.

https://github.com/ufs-community/ufs-weather-model/pull/2056#issuecomment-1863458959

**Comment by SamuelTrahanNOAA** [comment]
@JiliDong-NOAA - Please confirm that I merged your changes into this branch correctly.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA - Please confirm that I merged your changes into this branch correctly.

Looks good to me. thanks again @SamuelTrahanNOAA !

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA PR template is updated in #2053: single file change. As test goes on, we can combine that feature to this pr as well.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA PR template is updated in #2053: single file change. As test goes on, we can combine that feature to this pr as well.

I don't understand what you're saying. Are you asking me to update my PR description? Or merge #2053? Or both? I'm happy to merge a harmless PR into this one.

**Comment by jkbk2004** [comment]
> > @SamuelTrahanNOAA PR template is updated in #2053: single file change. As test goes on, we can combine that feature to this pr as well.
> 
> I don't understand what you're saying. Are you asking me to update my PR description? Or merge #2053? Or both? I'm happy to merge a harmless PR into this one.

Yes, I merge in the PR template update to this pr. @BrianCurtis-NOAA The PR template update in #2053 is ready, right?

**Comment by BrianCurtis-NOAA** [comment]
> > > @SamuelTrahanNOAA PR template is updated in #2053: single file change. As test goes on, we can combine that feature to this pr as well.
> > 
> > 
> > I don't understand what you're saying. Are you asking me to update my PR description? Or merge #2053? Or both? I'm happy to merge a harmless PR into this one.
> 
> Yes, I merge in the PR template update to this pr. @BrianCurtis-NOAA The PR template update in #2053 is ready, right?

Yes, it's OK to go.

**Comment by SamuelTrahanNOAA** [comment]
@tanyasmirnova @JiliDong-NOAA - Please confirm the commit message in the PR description is correct.

@BrianCurtis-NOAA @jkbk2004 - It looks like #2053 isn't merged into this branch yet. Once it is in here, the commit message will have to be updated.

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA @jkbk2004 FYI: I found out that if you include github markup links for issue numbers, it will automatically include the title of the issue in the commit message, you don't need to type it out. So in each commit message I expect that the github issues will be linked. (i.e. #2055 or NOAA-EMC/fv3atm/issues/737 )

**Comment by SamuelTrahanNOAA** [comment]
> FYI: I found out that if you include github markup links for issue numbers, it will automatically include the title of the issue in the commit message, you don't need to type it out. So in each commit message I expect that the github issues will be linked. (i.e. #2055 or [NOAA-EMC/fv3atm/issues/737](https://github.com/NOAA-EMC/fv3atm/issues/737) )

@BrianCurtis-NOAA - Please provide a modified commit message. That will give us an example of the format you're looking for.

**Comment by JiliDong-NOAA** [comment]
> @tanyasmirnova @JiliDong-NOAA - Please confirm the commit message in the PR description is correct.
> 
> @BrianCurtis-NOAA @jkbk2004 - It looks like #2053 isn't merged into this branch yet. Once it is in here, the commit message will have to be updated.

commit message looks good to me

**Comment by BrianCurtis-NOAA** [comment]
> > FYI: I found out that if you include github markup links for issue numbers, it will automatically include the title of the issue in the commit message, you don't need to type it out. So in each commit message I expect that the github issues will be linked. (i.e. #2055 or [NOAA-EMC/fv3atm/issues/737](https://github.com/NOAA-EMC/fv3atm/issues/737) )
> 
> @BrianCurtis-NOAA - Please provide a modified commit message. That will give us an example of the format you're looking for.

```
snodi diagnostic fix; CCPP bug fixes for RUC LSM and CLM Lake

UFSWM:
- Fixes crash when running GFS PBL/sfclay and clm lake in RRFS ensemble (Closes #2055) 

CMEPS:
- add flag to track lake freezing for clm lake (NOAA-EMC/CMEPS#105)

FV3:
- pressure is not density and weasdi is not snodi (NOAA-EMC/fv3atm#736)
- fix crash when using clm lake and GFS PBL/sfclay (NOAA-EMC/fv3atm#742)
- revisions to snowfall melting and accumulation (NOAA-EMC/fv3atm#739)

```
Since the UFSWM is mostly an aggregate from its components it's going to be important to link to the pull requests coming from those components, and if there are any UFSWM issues, we can use the commit message to close them.

If people want to dig deeper into the changes they can click the links the commit message will have to the respective PR's. The first line should contain a concise sentence describing the changes coming in. The rest should contain a list of PR's titles and include links.

Hopefully this helps demonstrate the importance of good PR (and issue) titles.

**Comment by BrianCurtis-NOAA** [comment]
@SamuelTrahanNOAA I hope the above helps. What you wrote is great, can you bring it down to one sentence (or two, is OK for large changes like this)?

**Comment by zach1221** [comment]
Dusan's recommended fix from [2015](https://github.com/ufs-community/ufs-weather-model/issues/2015) added to hercules fv3_slurm file. Tests passed for regional_netcdf_parallel and the two wrtGauss cases, so were re-enabled for hercules.

**Comment by jkbk2004** [comment]
We can start merging process.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Are we adding the template? @SamuelTrahanNOAA any changes you'd prefer to make to the commit message?

**Comment by SamuelTrahanNOAA** [comment]
@BrianCurtis-NOAA - How is this?

There are so many PRs and issues involved, I had to trim the list down a bit.

```
FV3 diagnostic fixes and CCPP bug fixes for model crashes

- UFS: commit message in PR template (#2053)
- CMEPS & FV3: Bad data from in CCPP CLM Lake physics scheme caused model crashes
    - Communicate changes to lake ice (Closes #2055, NOAA-EMC/CMEPS#105, NOAA-EMC/fv3atm#741) 
    - unit mismatch (NOAA-EMC/fv3atm#736)
- FV3: correct errors in diagnostic calculations
    - snodi had weasdi data in it (NOAA-EMC/fv3atm#736)
    - revisions to snowfall melting and accumulation (NOAA-EMC/fv3atm#739)
```

**Comment by SamuelTrahanNOAA** [comment]
@BrianCurtis-NOAA - Sorry, I missed a bit

```
FV3 diagnostic fixes, CCPP fixes for model crashes, new PR template

- UFS: commit message in PR template (#2053)
- CMEPS & FV3: Bad data from in CCPP CLM Lake physics scheme caused model crashes
    - Communicate changes to lake ice (Closes #2055, NOAA-EMC/CMEPS#105, NOAA-EMC/fv3atm#741) 
    - unit mismatch (NOAA-EMC/fv3atm#736)
- FV3: correct errors in diagnostic calculations
    - snodi had weasdi data in it (NOAA-EMC/fv3atm#736)
    - revisions to RUC LSM snowfall melting and accumulation (NOAA-EMC/fv3atm#739)
```

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA - Sorry, I missed a bit
> 
> ```
> FV3 diagnostic fixes, CCPP fixes for model crashes, new PR template
> 
> - UFS: commit message in PR template (#2053)
> - CMEPS & FV3: Bad data from in CCPP CLM Lake physics scheme caused model crashes
>     - Communicate changes to lake ice (Closes #2055, NOAA-EMC/CMEPS#105, NOAA-EMC/fv3atm#741) 
>     - unit mismatch (NOAA-EMC/fv3atm#736)
> - FV3: correct errors in diagnostic calculations
>     - snodi had weasdi data in it (NOAA-EMC/fv3atm#736)
>     - revisions to RUC LSM snowfall melting and accumulation (NOAA-EMC/fv3atm#739)
> ```

Yeah I too was trying to piece together all the changes. This look good. Thanks.

**Comment by SamuelTrahanNOAA** [comment]
Is there an issue I should cite for #2053? Or is it solely a PR?

**Comment by BrianCurtis-NOAA** [comment]
> Is there an issue I should cite for #2053? Or is it solely a PR?

Just the PR.

**Comment by DeniseWorthen** [comment]
This PR should also close Issue #2015

**Comment by SamuelTrahanNOAA** [comment]
> This PR should also close Issue #2015

@BrianCurtis-NOAA @jkbk2004 - I have updated the commit message to reflect this:

```
FV3 diagnostic fixes, CCPP fixes for model crashes, new PR template

- UFS:
    - commit message in PR template (#2053)
    - fix hercules crashes (#2015)
- CMEPS & FV3: Bad data from in CCPP CLM Lake physics scheme caused model crashes
    - Communicate changes to lake ice (Closes #2055, NOAA-EMC/CMEPS#105, NOAA-EMC/fv3atm#741) 
    - unit mismatch (NOAA-EMC/fv3atm#736)
- FV3: correct errors in diagnostic calculations
    - snodi had weasdi data in it (NOAA-EMC/fv3atm#736)
    - revisions to RUC LSM snowfall melting and accumulation (NOAA-EMC/fv3atm#739)
```

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA all sub component PRs were merged.

**Comment by SamuelTrahanNOAA** [comment]
This PR is ready for final review and merge. I've reverted .gitmodules. The FV3 and CMEPS point to their authoritative branches and URLs.

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
