### PR TITLE
Reorganization of ccpp-physics

### PR DESCRIPTION
**Pull request by dustinswales**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: /scratch1/BMC/gmtb/Dustin.Swales/UFS/reorg_phys/ufs-weather-model/tests/logs/RegressionTests_hera.log
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description
Reorganization of the ccpp-physics repository, and upstream dependencies.

### Associated UFSWM Issue to close
N/A

## Commit Message
This PR contains changes to the CCPP prebuild step to accommodate a reorganization of the ccpp-physics repository. 
- Re-organization of physical parameterizations into process and scheme subdirectories
- Modifications to CCPP metadata files to accommodate source file location changes
- File location update referenced in CMEPS
- No changes to the results are introduced here, only to file locations.

### Subcomponent Pull Requests
- https://github.com/NOAA-EMC/CMEPS/pull/103
- https://github.com/NOAA-EMC/fv3atm/pull/733
- https://github.com/ufs-community/ccpp-physics/pull/99

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

No changes to baselines or input data needed.

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@dustinswales We're adding a Commit Message requirement to the PRs. Please provide one in the space provided.

**Comment by jkbk2004** [comment]
@dustinswales can you sync up the branch?

**Comment by zach1221** [comment]
@dustinswales would you be able to combine the changes from PR #2017 into this ?

**Comment by zach1221** [comment]
Seems there is some serious slowness on Orion. Some of the cases are just failing in the queue. I will report the issue, however it may be best to skip Orion for this PR.

**Comment by zach1221** [comment]
Ok Orion seems to be good now. I think we can begin the merge process now.

**Comment by zach1221** [comment]
@dustinswales CMEPS PR[#103](https://github.com/NOAA-EMC/CMEPS/pull/103) is merged. Please revert changes in .gitmodule url and update submodule hash: https://github.com/NOAA-EMC/CMEPS/commit/f8f7ba76ac8b0687695c2a76deaf45ab5c2e39f3

**Comment by zach1221** [comment]
@dustinswales fv3atm is now merged as well. Hash: https://github.com/NOAA-EMC/fv3atm/commit/997907fe89b18fcc53405cf6722942810bf09eed

**Review by BrianCurtis-NOAA — CHANGES_REQUESTED** [review]
The Commit message should use github linking to issues related to these changes (whether or not they are in UFSWM). Please update it. Let me know if I can help clarify anything.

**Comment by jkbk2004** [comment]
> The Commit message should use github linking to issues related to these changes (whether or not they are in UFSWM). Please update it. Let me know if I can help clarify anything.

@BrianCurtis-NOAA Commit messages were updated.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
