### PR TITLE
Orion changes for switch to new OS - Rocky-9

### LINKED ISSUE #2332: Orion Rocky9 OS migration
## Description

New Spack stack installation: full regression test is underway
```
help([[
loads UFS Model prerequisites for Orion/Intel
]])

prepend_path("MODULEPATH", "/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env-rocky9/install/modulefiles/Core")

stack_intel_ver=os.getenv("stack_intel_ver") or "2021.9.0"
load(pathJoin("stack-intel", stack_intel_ver))

stack_impi_ver=os.getenv("stack_impi_ver") or "2021.9.0"
load(pathJoin("stack-intel-oneapi-mpi", stack_impi_ver))

cmake_ver=os.getenv("cmake_ver") or "3.23.1"
load(pathJoin("cmake", cmake_ver))

load("ufs_common")

nccmp_ver=os.getenv("nccmp_ver") or "1.9.0.1"
load(pathJoin("nccmp", nccmp_ver))

setenv("CC", "mpiicc")
setenv("CXX", "mpiicpc")
setenv("FC", "mpiifort")
setenv("CMAKE_Platform", "orion.intel")

whatis("Description: UFS build environment")
```

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
## Commit Queue Requirements:
- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel RT suite (compared to current baselines) on Orion (changes related to Orion)
- [x] Commit 'test_changes.list' from previous step
---
## Description:
Orion switched from CentOS to Rocky operating system. Modulefiles updated to run the model.

### Priority:
* High: Model cannot work without this changes on Orion

### UFSWM:
* Closes #2332 

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None
---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.
Since architecture and OS is same as Hercules, it was expected to have same results as on Hercules. I created symbolic link from Hercules to Orion baselines:
```
/work/noaa/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240614 -> /work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/develop-20240614
```
 Also, I added two new baselines for two tests that were not run on Hercules:
```
control_wam_debug_intel
gnv1_nested_intel
```

### Input data Changes:
* None.

### Library Changes/Upgrades:
* Libraries already updated
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by aerorahul** [comment]
@WenMeng-NOAA 
Can the UPP update be included in this PR?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Can the UPP update be included in this PR?

@aerorahul The UPP side will work on this upgrade soon. I will let you know when the change is committed in the develop branch at the UPP repository.

**Comment by aerorahul** [comment]
> > @WenMeng-NOAA Can the UPP update be included in this PR?
> 
> @aerorahul The UPP side will work on this upgrade soon. I will let you know when the change is committed in the develop branch at the UPP repository.

I hope this is available w/ the ufs-weather-model as the analysis post-processing requires an offline UPP executable.

**Comment by WenMeng-NOAA** [comment]
> > > @WenMeng-NOAA Can the UPP update be included in this PR?
> > 
> > 
> > @aerorahul The UPP side will work on this upgrade soon. I will let you know when the change is committed in the develop branch at the UPP repository.
> 
> I hope this is available w/ the ufs-weather-model as the analysis post-processing requires an offline UPP executable.

@aerorahul Yes, after the UPP develop is updated, the upp submodule update can be included in this PR or Sam's PR #2326 if it will be processed first.

**Comment by jkbk2004** [comment]
merged with #2324

**Pull request closed without merging**
