### PR TITLE
Bug/debugww3fix

### LINKED ISSUE #1133: CMake build for WW3 fails when compiling S2SW with -DDEBUG=ON
## Description
Compiling UWM app S2SW in debug mode fails with a conflict between compile flag -DDEBUG=ON used at the app level and an internal WW3 variable named DEBUG

### To Reproduce:
Check out current develop branch. Compile S2SW in debug mode:

```
./compile.sh hera.intel '-DAPP=S2SW -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v16_coupled_p8' '' YES NO 2>&1 | tee compile.log
```

The compile log shows a compile failure

```
/apps/cmake/3.20.1/bin/cmake -E touch CICE-interface/CMakeFiles/cice.dir/CICE/icepack/columnphysics/icepack_fsd.F90.o.provides.build
/tmp/ifort8M9ebj.i90: remark #5415: Feature not yet implemented: check shape
/scratch2/NCEPDEV/climate/Denise.Worthen/WORK/ufs-weather-model/WW3/model/src/w3gsrumd.F90(626): error #5082: Syntax error, found INTEGER_CONSTANT '1' when expecting one of: <IDENTIFIER>
                              NCB, NNP, 1 ) RESULT(GSU)
----------------------------------------^
/scratch2/NCEPDEV/climate/Denise.Worthen/WORK/ufs-weather-model/WW3/model/src/w3gsrumd.F90(636): error #5082: Syntax error, found INTEGER_CONSTANT '1' when expecting one of: <IDENTIFIER> %FILL
      LOGICAL, INTENT(IN), OPTIONAL :: 1
```

The source code shows that the "1" is a replacement for the WW3 variable ``DEBUG``

```
      FUNCTION W3GSUC_PTR_R4( IJG, LLG, ICLO, XG, YG, &
                              NCB, NNP, DEBUG ) RESULT(GSU)
!     Single precision pointer interface
      TYPE(T_GSU)         :: GSU
      LOGICAL, INTENT(IN) :: IJG
      LOGICAL, INTENT(IN) :: LLG
      INTEGER, INTENT(IN) :: ICLO
      REAL(4), POINTER    :: XG(:,:)
      REAL(4), POINTER    :: YG(:,:)
      INTEGER, INTENT(IN), OPTIONAL :: NCB
      INTEGER, INTENT(IN), OPTIONAL :: NNP
      LOGICAL, INTENT(IN), OPTIONAL :: DEBUG

```

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This is a PR that updates WW3,  the dev/ufs-weather-model branch with the NOAA-EMC develop branch merged in.  The update of note is a fix for when WW3 is compiled with DEBUG flags.  See issue:   This fix was provided by @kgerheiser 

No answers are changed with this PR.  No new input is required. 

### Issue(s) addressed

- fixes #1133

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

The following regression tests passed: hera.intel gaea.intel wcoss_cray 
The following regression tests are running but have not yet completed: wcoss_dell_p3, orion.intel 
I do not have access to jet or Cheyenne. 

The following ORT test passed: 
`./opnReqTest -n cpld_control_c96_p8 -c thr,rst,dbg,fhz
`
and the log file was included. 

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/WW3/pull/648

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Is it OK we can combine this PR with Dom's PR #1130 which does not change results?

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa I think that would be great! Please let me know if there's anything I need to do.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Do you plan to make further changes in your ww3 branch, if not, we can ask @climbfuji  to point to your ww3 branch in his ufs-weather-model branch.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa No I do not plan to make any further changes to the WW3 branch.

**Comment by climbfuji** [comment]
@JessicaMeixner-NOAA @junwang-noaa I pulled the changes from this PR into https://github.com/ufs-community/ufs-weather-model/pull/1130, as requested.

**Comment by JessicaMeixner-NOAA** [comment]
Combined with https://github.com/ufs-community/ufs-weather-model/pull/1130

**Pull request closed without merging**
