### PR TITLE
public-v2: Update documentation and LICENSE.md from develop to release/public-v2

### PR DESCRIPTION
**Pull request by JulieSchramm**
## Description

This PR updates the documentation and LICENSE.md from develop to release/public-v2.
Note this documenetation was merged from release/public-v1, and has not been updated
during its short life on the develop branch.

### Issue(s) addressed

Need documentation from develop for release/public-v2 branch for SRW App release

## Testing

No testing required, changes to subdirectory doc and LICENSE.md only.

## Dependencies

None

### CODE REVIEW

**Comment by climbfuji** [comment]
Shouldn't this documentation be updated to release/public-v2 / ufs-v2.0.0 / SRW App 1.0.0 everywhere it mentions release/public-v1 / ufs-v1.1.0 / MRW app v1.1.0? Or are you planning to do that afterwards?

**Comment by JulieSchramm** [comment]
I was going to do that later.

**Comment by climbfuji** [comment]
> I was going to do that later.
> […](#)

@junwang-noaa is that ok with you or do you want to wait for Julie to update the documentation as part of this PR?

**Comment by junwang-noaa** [comment]
I prefer to update the document for public-v2 as the current changes in
this PR are purely public release v1.1.0 related, maybe at least
update those version number to v2.

**Review by junwang-noaa — APPROVED** [review]
I see currently we don't have ufs-v2.0.0 yet, I assume after the tag ufs-v2.0.0 is created, this documentation will be reviewed to confirm the repo/tag is working as described.

**Comment by climbfuji** [comment]
> I see currently we don't have ufs-v2.0.0 yet, I assume after the tag ufs-v2.0.0 is created, this documentation will be reviewed to confirm the repo/tag is working as described.

That's correct.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
