### PR TITLE
fix the fdiag for GEFS EP4

### LINKED ISSUE #1420: ATM diag_time is not correct when model restarts from the middle of fhzero.
## Description
When ufs-weather-model restarts from the middle of fhzero (fhzero=6, restarts from f03), the previous diag_time in the code is not correctly set. In this case(fhzero=6, restarts from f03), when model integration reaches f06, the previous bucket empty time should be 6 hours ago, but it shows 3 hours ago.  

### To Reproduce:
run p8 restarting from f03. 

## Additional context

model integration to f06 from the current model: 
 ---isec,seconds       10800       21600
  gfs diags time since last bucket empty:    3.00000000000000      hrs

correct diag_time when model integration to f06 
 ---isec,seconds       21600       21600
  gfs diags time since last bucket empty:    6.00000000000000      hrs

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

### LINKED ISSUE #1635: Update atm model component log file name
## Description
Since we are moving to the coupled system, the logf file that indicates the completion of FV3TAM model output files will be updated to have component model name in the file name. The goal is to have consistent log file name log.$MODEL_NAME.fXXX for all the model components.   

## Solution
The logfXXX file will become: log.fv3.fXXX or atm.log.fXXX

### PR DESCRIPTION
**Pull request by junwang-noaa**
## Description
This PR is to fix issue https://github.com/ufs-community/ufs-weather-model/issues/1420, where the GEFS reforecast needs to start the model in the middle of fhzero (fhzero=6, but model starts at fh=3), the model bucket time needs to be set to the beginning of the model start time. Also since model now is using the flexible output_fh to control history file output time, the option for the special case to output the history files after the first restart time is removed.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
https://github.com/NOAA-EMC/fv3atm/pull/643

Please link the related issues to be closed with this PR, whether in this repository, or in another repository.
Closes https://github.com/ufs-community/ufs-weather-model/issues/1420
Closes https://github.com/ufs-community/ufs-weather-model/issues/1635

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [ ] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Review by BrianCurtis-NOAA — DISMISSED** [review]
Looks good code-wise.

**Comment by junwang-noaa** [comment]
Full RT passed on hera. RT log file: /scratch1/NCEPDEV/nems/Jun.Wang/nems/vlab/20230410/ufs-weather-model/tests/RegressionTests_hera.intel.log

**Comment by jkbk2004** [comment]
@junwang-noaa #1407 was merged. Can you sync up branch? we will work on this pr. @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA FYI

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Please check EMC Slack CM Channel.

**Comment by BrianCurtis-NOAA** [comment]
Acorn and WCOSS2 are inaccessible today. I will try as soon as I know they are back up.

**Comment by FernandoAndrade-NOAA** [comment]
Attached are the Jenkins CI logs, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1704 #2 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11206293/ufs-weather-model.ort-docker-pipeline.PR-1704.2.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1307465216/20230412021515/ufs-weather-model
[RT] Error: Test cpld_control_p8 048 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /mnt/lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1307465216/20230412015210/ufs-weather-model
[RT] Error: Test control_c384gdas 027 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
If there is a failure from AutoRT, it would be good to know what the failure was, even if its just hitting wallclock. Helps keep track if wallclock limits are becoming a problem with UFSWM. Please post in PR comment.

**Comment by jkbk2004** [comment]
Gaea c4 is not available. All tests are done. We can start merging process.

**Review by sadeghitabas — DISMISSED** [review]

**Comment by sadeghitabas** [comment]
@junwang-noaa Please update the gitmodule pointer.

**Comment by jkbk2004** [comment]
Jet and hera.gnu failed cases were time out issues. Jobs ran ok with resubmission.

**Comment by jkbk2004** [comment]
@junwang-noaa fv3 pr was merged. can you update hash and revert change in gitmodules? correct hash is https://github.com/NOAA-EMC/fv3atm/commit/f964b4b5e4807363f891c8b2e7a10a8534f109a6

**Comment by junwang-noaa** [comment]
@jkbk2004 Done.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/role.epic/autort/pr/1307465216/20230411215211/ufs-weather-model
Please make changes and add the following label back: gaea-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Noting Acorn skipped due to #1705

**Pull request merged**
