### PR TITLE
Radiation changes for prototype 8

### PR DESCRIPTION
**Pull request by dustinswales**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR contains changes to underlying the ccpp-physics and FV3 repositories. 
Changes to ccpp-physics are to accommodate new features in RRTMGP for P8.
Changes to FV3 are isolated to infrastructure improvements to facilitate the ccpp-physics changes.

Changes to this repository are minimal, only some housekeeping to cleanup the RRTGMP regression tests.

### Issue(s) addressed
https://github.com/ufs-community/ufs-weather-model/issues/1093

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [ ] wcoss_cray: Skip due to maintenance
- [x] wcoss_dell_p3
- [x] opnReqTest for newly added/changed feature
- [x] CI

## Waiting for other repos

- waiting on https://github.com/NCAR/ccpp-physics/pull/858
- waiting on https://github.com/NCAR/ccpp-physics/pull/871
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/498

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@dustinswales Would you please add an issue in ufs-weather-model issue page (https://github.com/ufs-community/ufs-weather-model/issues/new/choose) for this PR? According to github issue doc :"Issues let you track your work on GitHub, where development happens". It includes both bug fixes and new features. Every the ufs-weather-model PR needs to have an issue associated with it. Thanks

**Comment by junwang-noaa** [comment]
@dustinswales Which RT tests will change results in this PR? Would you please give a description on the namelist changes (e.g. what changes need to be made in workflow to use the new feature, will workflow runs fail if no change is made?)

**Comment by dustinswales** [comment]
@junwang-noaa 

All of the GP baselines need to be updated. For several different reasons.

First, As part of this PR I did some cleanup of the RRTMGP RTs.
Before I was maintaining separate nml's for the RRTMGP tests, these are gone and the RRTMGP nml options are in the tests/tests/********* files that had an RRTMGP counterpart.
RRTMGP nml options added to: tests/parm/control.nml, cpld_control.nml, rap.nml*, regional.nml,
Files removed:  tests/parm/control_rrtmgp.nml, cpld_control_rrtmgp.nml, regional_rrtmgp.nml
*rap.nml was the outlier, already having the RRTMGP nml options imported from the tests/tests/rap_rrtmgp.*

Having these nml's separate was causing problems with the GP tests, they were "drifting" from their default RRTMG counterparts. 

Secondly, there are now gocart aerosols for P8b, which will change our baselines now.

Also, the Thompson MP coupling to RRTMGP, exercised in the RAP suite, has been revised.

**Comment by MinsukJi-NOAA** [comment]
@dustinswales please bring your branch up to date with the ufs weather model and its components ([96dffa1](https://github.com/ufs-community/ufs-weather-model/commit/96dffa15a7f0a98c9120d36f31196c273c9232f2)) in preparation for your PR.

**Comment by BrianCurtis-NOAA** [comment]
You will need to manually get the logs and get them to a place for Dustin as my account isn't a collaborator in his Repo/fork

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/874677429/20220405164515/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/874677429/20220405200316/ufs-weather-model
[RT] Error: Test rap_diag_debug 081 failed in check_result failed 
[RT] Error: Test rap_diag_debug 081 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/874677429/20220405223009/ufs-weather-model
[RT] Error: Test cpld_debug_p8 008 failed in run_test failed 
[RT] Error: Test regional_RRTMGP 039 failed in run_test failed 
[RT] Error: Test rap_diag_debug 081 failed in check_result failed 
[RT] Error: Test rap_diag_debug 081 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by junwang-noaa** [comment]
@dustinswales 1) I saw you added cpld_control_p8_rrtmgp test, can it be added to rt.conf instead of cpld_bmark_p7_rrtmgp? 
2) would you please run ORT test with the new test control_p8_rrtmgp? I think you may also need to have a cpld_control_c96_noaero_p8_rrtmgp test based on [cpld_control_c96_noaero_p8](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/cpld_control_c96_noaero_p8) for ORT test.

**Comment by dustinswales** [comment]
@junwang-noaa 
I made the changes you suggested to the RTs. I'm running the ORTs now

**Comment by DeniseWorthen** [comment]
Thanks for the latest update. Could you please remove the following tests from the tests directory and in rt.conf:
cpld_bmark_p7
control_p7_rrtmgp

and remove cpld_control_p7.nml.IN from the tests/parm directory

Since all coupled regression tests should now use RRTMGP, you can add the default settings in default_vars after [LN 1191](https://github.com/ufs-community/ufs-weather-model/blob/96dffa15a7f0a98c9120d36f31196c273c9232f2/tests/default_vars.sh#L1191)

```
# P8 RRTMGP
export CCPP_SUITE=FV3_GFS_v17_coupled_p8
export DO_RRTMGP=.true.
export DOGP_CLDOPTICS_LUT=.true.
export DOGP_LWSCAT=.true.
```

However, for the standalone P8 tests, since RRTMGP is not a default, you will need to add the above RRTMGP settings to the  the individual standalone P8 tests.

**Comment by dustinswales** [comment]
@DeniseWorthen 
Done.

**Comment by DeniseWorthen** [comment]
@dustinswales The RRTMGP defaults need to be added to these tests

control_2threads_p8
control_debug_p8
control_decomp_p8
control_restart_p8

```
# P8 RRTMGP
export DO_RRTMGP=.true.
export DOGP_CLDOPTICS_LUT=.true.
export DOGP_LWSCAT=.true.
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/874677429/20220406183011/ufs-weather-model
[BL] Error: Test cpld_control_c192_p8 004 failed in run_test failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/874677429/20220406233014/ufs-weather-model
[BL] Error: Test cpld_debug_p8 003 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_thompson_gfdlsf 071 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by junwang-noaa** [comment]
@dustinswales the cpld_debug_p8 on jet and the cpld_control_c192_p8 test on orion ran out of wall clock time. The resources for these cpld C96 tests and cpld_control_c192_p8 on orion need to be adjusted in default_vars.sh:
```
git diff default_vars.sh
...
@@ -76,9 +76,9 @@ elif [[ $MACHINE_ID = wcoss_dell_p3 ]]; then
   OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
   NPROC_ICE_cpl_bmrk_mpi=48

-  TASKS_cpl_c192=288; TPN_cpl_c192=28; INPES_cpl_c192=4; JNPES_cpl_c192=8
-  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
-  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
+  TASKS_cpl_c192=384; TPN_cpl_c192=28; INPES_cpl_c192=6; JNPES_cpl_c192=8
+  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 299"
+  CHM_cpl_c192="0 287"; OPB_cpl_c192="300 359"; IPB_cpl_c192="360 383"
...
@@ -222,9 +222,9 @@ elif [[ $MACHINE_ID = orion.* ]]; then
   OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
   NPROC_ICE_cpl_bmrk_mpi=48

-  TASKS_cpl_c192=288; TPN_cpl_c192=40; INPES_cpl_c192=4; JNPES_cpl_c192=8
-  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
-  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
+  TASKS_cpl_c192=384; TPN_cpl_c192=40; INPES_cpl_c192=6; JNPES_cpl_c192=8
+  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 299"
+  CHM_cpl_c192="0 287"; OPB_cpl_c192="300 359"; IPB_cpl_c192="360 383"
...
@@ -345,9 +345,9 @@ elif [[ $MACHINE_ID = jet.* ]]; then
   TASKS_cpl_atmw_gdas=552; TPN_cpl_atmw_gdas=12; INPES_cpl_atmw_gdas=6; JNPES_cpl_atmw_gdas=8
   THRD_cpl_atmw_gdas=2; WPG_cpl_atmw_gdas=24; APB_cpl_atmw_gdas="0 311"; WPB_cpl_atmw_gdas="312 551"

-  TASKS_cpl_c96=192; TPN_cpl_c96=24; INPES_cpl_c96=3; JNPES_cpl_c96=8
-  THRD_cpl_c96=1; WPG_cpl_c96=6;  MPB_cpl_c96="0 143"; APB_cpl_c96="0 149"
-  CHM_cpl_c96="0 143"; OPB_cpl_c96="150 179"; IPB_cpl_c96="180 191"
+  TASKS_cpl_c96=240; TPN_cpl_c96=24; INPES_cpl_c96=4; JNPES_cpl_c96=8
+  THRD_cpl_c96=1; WPG_cpl_c96=6;  MPB_cpl_c96="0 191"; APB_cpl_c96="0 197"
+  CHM_cpl_c96="0 191"; OPB_cpl_c96="198 227"; IPB_cpl_c96="228 239"
```

Can you commit the changes to your branch? Thanks

FYI, in general, we noticed ~10-20% time increase and ~10% memory increase in the RT tests with RRTMGP compared to the same tests previously using RRTMG.

**Comment by yangfanglin** [comment]
~10% increase of CPU time is expected.   20% increase is a surprise.  
Do we see similar increases and variability on all platforms ?

**Comment by junwang-noaa** [comment]
Yes, this is based on results at Cheyenne, gaea and hera.

**Comment by yangfanglin** [comment]
Do we have the numbers from WCOSS ?
@dustinswales do you have any comments on the variability of CPU cost ?

**Comment by dustinswales** [comment]
@yangfanglin 
Sorry, I don't have any information on performance beyond Hera.

**Comment by MinsukJi-NOAA** [comment]
> Do we have the numbers from WCOSS ? @dustinswales do you have any comments on the variability of CPU cost ?

For cpld_control_c192_p8 on WCOSS Dell, RRTMG takes 28.4 minutes. Looks like RRTMGP will need at least 32 minutes. That's about 13% increase. @junwang-noaa's new set of PETS gets RRTMGP to finish in 24 minutes.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/874677429/20220407173019/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@grantfirl can we merge the ccpp physics PR#871? Thanks

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Pull request merged**
