### PR TITLE
Production/GFS.v16: Update upp to 8.2.0 for GFS V16.3 Implementation

### LINKED ISSUE #1368: Update upp lib to 8.2.0 for GFS V16.3 Implementation
## Description
To support GFS V16.3 implementation, upp lib upgrade is needed.

## Solution
Update upp to 8.2.0 for WCOSS2, Hera and Orion.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add? Is a change of answers expected from this PR? Are any library updates included in this PR (modulefiles etc.)?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1368

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? No
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA Currently the GFSv16 standalone atm is supported on hera and orion too, would you please also update the crtm in orion.intel and hera.intel/fv3? Thank you!

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa The crtm/2.4.0 is not available the hpc-stack for GFS V16 support (/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/stack on hera and /apps/contrib/NCEP/libs/hpc-stack-gfsv16/modulefiles/stack on orion). I am not sure if the UFS for GFS V16 is using that hpc-stack or not.

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA Can you install the crtm/2.4.0 for GFSv16 on hera and orion? Thanks

**Comment by Hang-Lei-NOAA** [comment]
Hi Jun

The crtm v2.4.0 has been on Hera and wcoss2acorn for several months. Please
directly use it.

I have just finished recreate orion library system after Kyle’s leave. I
will double check if the crtm v2.4.0 on orion is correct and fix any
necessary updates.

Please change your library path on orion

The hpc-stack on orion has been updated on:
Orion: /apps/contrib/NCEP/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/stack

Please try and let me know if you have any problems.

Thanks
Hang!

Thanks.
Hang

**Comment by WenMeng-NOAA** [comment]
@Hang-Lei-NOAA For GFS V16.3.0 support, crtm/2.4.0 and upp/8.2.0 need to be installed with intel/2018 instead of intel/2022.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Updated crtm to 2.4.0 on Hera and Orion. We have been waiting for upp/8.2.0 installed on WCOSS2.

**Comment by junwang-noaa** [comment]
@WenMeng-NOAA The upp/8.2.0 and crtm/2.4.0 was committed in PR#1459, #1426, this PR can be closed.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Thanks for the heads-up.

**Pull request closed without merging**
