### PR TITLE
Updating nemelist templates and configuration files to have consistent format as the global workflow; Update CDEPS (was #1741)

### LINKED ISSUE #1663: Updating the global tests namelist and configuration file format
## Description
This is task 1 listed in issue #1248 (UFS WM regression test namelist template updates). The nemalist templates and configuration files (model_configure and nems.configure) used in the global RT tests will be cleaned up and updated to have consistent format as the global workflow. This goal is to remove the discrepancy between RT test runs and the global workflow runs.  

## Solution
Update global test namelist templates, model_configure and nems.configure files to make sure ufs wm RT test and global workflow have same format configuration files. Will work with global workflow team as the global workflow may also need to be updated.

### PR DESCRIPTION
**Pull request by sadeghitabas**
## Description
The nemalist templates and configuration files (model_configure and nems.configure) used in the global RT tests will be cleaned up and updated to have consistent format as the global workflow. This goal is to remove the discrepancy between RT test runs and the global workflow runs.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [x] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):
Linked PR: https://github.com/ufs-community/ufs-weather-model/pull/1741

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
- Closes #1663
- Linked PR: https://github.com/ufs-community/ufs-weather-model/pull/1741
- CDEPS subcomponent (https://github.com/NOAA-EMC/CDEPS/pull/55)

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@SadeghTabas-NOAA The changes to the run sequence in the cpld_noaero test are not correct. That test runs the waves in the fast loop; it looks like you've made it match the slow loop case (_outwav).

**Comment by junwang-noaa** [comment]
@DeniseWorthen This is one of the incremental updates to match the RT configurations with the global workflow. The global workflow now has wave in slow loop. @aerorahul @JessicaMeixner-NOAA please confirm if wave needs to be in slow loop for the coupled tests.

**Comment by DeniseWorthen** [comment]
@junwang-noaa That will be a major change in the current regression tests for the coupled model.

**Review by aerorahul — DISMISSED** [review]
While the global-workflow does not use these edited files, we intend to use the templates for `cpld_control.nml.IN` and `model_configure.IN` in the very near future.
This PR will help ensuring that a RT and a global-workflow test for coupled configurations remains consistent and as similar as possible.

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
Please make changes and add the following label back: orion-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1304019799/20230509230911/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1304019799/20230510040012/ufs-weather-model
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230510041514/ufs-weather-model
[RT] Error: Test control_c48 001 failed in check_result failed 
[RT] Error: Test control_c48 001 failed in run_test failed 
[RT] Error: Test control_stochy 002 failed in check_result failed 
[RT] Error: Test control_stochy 002 failed in run_test failed 
[RT] Error: Test control_ras 003 failed in check_result failed 
[RT] Error: Test control_ras 003 failed in run_test failed 
[RT] Error: Test control_p8 004 failed in check_result failed 
[RT] Error: Test control_p8 004 failed in run_test failed 
[RT] Error: Test control_flake 005 failed in check_result failed 
[RT] Error: Test control_flake 005 failed in run_test failed 
[RT] Error: Test control_diag_debug 023 failed in check_result failed 
[RT] Error: Test control_diag_debug 023 failed in run_test failed 
[RT] Error: Test control_ras_debug 031 failed in check_result failed 
[RT] Error: Test control_ras_debug 031 failed in run_test failed 
[RT] Error: Test control_stochy_debug 032 failed in check_result failed 
[RT] Error: Test control_stochy_debug 032 failed in run_test failed 
[RT] Error: Test cpld_control_p8 051 failed in check_result failed 
[RT] Error: Test cpld_control_p8 051 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 052 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 052 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 053 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 053 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230510040020/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in run_test failed 
[RT] Error: Test cpld_control_p8 003 failed in check_result failed 
[RT] Error: Test cpld_control_p8 003 failed in run_test failed 
[RT] Error: Test cpld_control_qr_p8 005 failed in check_result failed 
[RT] Error: Test cpld_control_qr_p8 005 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 007 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 007 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 008 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 008 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 009 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 009 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 011 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 011 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 016 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 016 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 017 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 017 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 019 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 019 failed in run_test failed 
[RT] Error: Test cpld_control_c48 020 failed in check_result failed 
[RT] Error: Test cpld_control_c48 020 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 021 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 021 failed in run_test failed 
[RT] Error: Test cpld_control_p8_faster 023 failed in check_result failed 
[RT] Error: Test cpld_control_p8_faster 023 failed in run_test failed 
[RT] Error: Test control_CubedSphereGrid 025 failed in check_result failed 
[RT] Error: Test control_CubedSphereGrid 025 failed in run_test failed 
[RT] Error: Test control_CubedSphereGrid_parallel 026 failed in check_result failed 
[RT] Error: Test control_CubedSphereGrid_parallel 026 failed in run_test failed 
[RT] Error: Test control_latlon 027 failed in check_result failed 
[RT] Error: Test control_latlon 027 failed in run_test failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel 028 failed in check_result failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel 028 failed in run_test failed 
[RT] Error: Test control_c192 030 failed in check_result failed 
[RT] Error: Test control_c192 030 failed in run_test failed 
[RT] Error: Test control_c384 031 failed in check_result failed 
[RT] Error: Test control_c384 031 failed in run_test failed 
[RT] Error: Test control_c384gdas 032 failed in run_test failed 
[RT] Error: Test control_stochy 033 failed in check_result failed 
[RT] Error: Test control_stochy 033 failed in run_test failed 
[RT] Error: Test control_lndp 035 failed in check_result failed 
[RT] Error: Test control_lndp 035 failed in run_test failed 
[RT] Error: Test control_iovr4 036 failed in check_result failed 
[RT] Error: Test control_iovr4 036 failed in run_test failed 
[RT] Error: Test control_iovr5 037 failed in check_result failed 
[RT] Error: Test control_iovr5 037 failed in run_test failed 
[RT] Error: Test control_p8 038 failed in check_result failed 
[RT] Error: Test control_p8 038 failed in run_test failed 
[RT] Error: Test control_qr_p8 040 failed in check_result failed 
[RT] Error: Test control_qr_p8 040 failed in run_test failed 
[RT] Error: Test control_decomp_p8 042 failed in check_result failed 
[RT] Error: Test control_decomp_p8 042 failed in run_test failed 
[RT] Error: Test control_2threads_p8 043 failed in check_result failed 
[RT] Error: Test control_2threads_p8 043 failed in run_test failed 
[RT] Error: Test control_p8_lndp 044 failed in check_result failed 
[RT] Error: Test control_p8_lndp 044 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 045 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 045 failed in run_test failed 
[RT] Error: Test merra2_thompson 047 failed in check_result failed 
[RT] Error: Test merra2_thompson 047 failed in run_test failed 
[RT] Error: Test control_ras 080 failed in check_result failed 
[RT] Error: Test control_ras 080 failed in run_test failed 
[RT] Error: Test control_wam 081 failed in check_result failed 
[RT] Error: Test control_wam 081 failed in run_test failed 
[RT] Error: Test control_p8_faster 082 failed in check_result failed 
[RT] Error: Test control_p8_faster 082 failed in run_test failed 
[RT] Error: Test control_CubedSphereGrid_debug 087 failed in check_result failed 
[RT] Error: Test control_CubedSphereGrid_debug 087 failed in run_test failed 
[RT] Error: Test control_stochy_debug 089 failed in check_result failed 
[RT] Error: Test control_stochy_debug 089 failed in run_test failed 
[RT] Error: Test hafs_regional_atm 124 failed in check_result failed 
[RT] Error: Test hafs_regional_atm 124 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn 126 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn 126 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_wav 127 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_wav 127 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 128 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 128 failed in run_test failed 
[RT] Error: Test hafs_global_1nest_atm 131 failed in check_result failed 
[RT] Error: Test hafs_global_1nest_atm 131 failed in run_test failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 132 failed in check_result failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 132 failed in run_test failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 133 failed in check_result failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 133 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 139 failed in check_result failed 
[RT] Error: Test hafs_regional_docn 139 failed in run_test failed 
[RT] Error: Test hafs_regional_docn_oisst 140 failed in check_result failed 
[RT] Error: Test hafs_regional_docn_oisst 140 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 159 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 159 failed in run_test failed 
[RT] Error: Test atmwav_control_noaero_p8 160 failed in check_result failed 
[RT] Error: Test atmwav_control_noaero_p8 160 failed in run_test failed 
[RT] Error: Test control_atmwav 161 failed in check_result failed 
[RT] Error: Test control_atmwav 161 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 162 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 162 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1304019799/20230517110050/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by sadeghitabas** [comment]
@jkbk2004 Could you please have look and see why the tests get failed? I already tested those on Hera and Orion and it was working fine. The branch is up to date. Thanks

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1304019799/20230517120051/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230517160021/ufs-weather-model
[RT] Error: Test cpld_control_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 016 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 016 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 019 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 019 failed in run_test failed 
[RT] Error: Test cpld_control_c48 020 failed in check_result failed 
[RT] Error: Test cpld_control_c48 020 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 021 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 021 failed in run_test failed 
[RT] Error: Test cpld_control_pdlib_p8 024 failed in check_result failed 
[RT] Error: Test cpld_control_pdlib_p8 024 failed in run_test failed 
[RT] Error: Test cpld_debug_pdlib_p8 027 failed in check_result failed 
[RT] Error: Test cpld_debug_pdlib_p8 027 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230517161513/ufs-weather-model
[RT] Error: Test cpld_control_nowave_noaero_p8 052 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 052 failed in run_test failed 
[RT] Error: Test cpld_control_pdlib_p8 054 failed in check_result failed 
[RT] Error: Test cpld_control_pdlib_p8 054 failed in run_test failed 
[RT] Error: Test cpld_debug_pdlib_p8 055 failed in check_result failed 
[RT] Error: Test cpld_debug_pdlib_p8 055 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230517170018/ufs-weather-model
[RT] Error: Test cpld_control_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 016 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 016 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 019 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 019 failed in run_test failed 
[RT] Error: Test cpld_control_c48 020 failed in check_result failed 
[RT] Error: Test cpld_control_c48 020 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 021 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 021 failed in run_test failed 
[RT] Error: Test cpld_control_pdlib_p8 024 failed in check_result failed 
[RT] Error: Test cpld_control_pdlib_p8 024 failed in run_test failed 
[RT] Error: Test cpld_debug_pdlib_p8 027 failed in check_result failed 
[RT] Error: Test cpld_debug_pdlib_p8 027 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230517171517/ufs-weather-model
[RT] Error: Test cpld_control_nowave_noaero_p8 052 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 052 failed in run_test failed 
[RT] Error: Test cpld_control_pdlib_p8 054 failed in check_result failed 
[RT] Error: Test cpld_control_pdlib_p8 054 failed in run_test failed 
[RT] Error: Test cpld_debug_pdlib_p8 055 failed in check_result failed 
[RT] Error: Test cpld_debug_pdlib_p8 055 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by DeniseWorthen** [comment]
@jkbk2004 I suggest killing if possible any remaining RTs on jet or cheyenne. There is obviously an issue w/ the pr.

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1304019799/20230517160011/ufs-weather-model
[RT] Error: Test cpld_control_noaero_p8 012 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in run_test failed 
[RT] Error: Test cpld_control_c48 017 failed in check_result failed 
[RT] Error: Test cpld_control_c48 017 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1304019799/20230517170013/ufs-weather-model
[RT] Error: Test cpld_control_noaero_p8 012 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in run_test failed 
[RT] Error: Test cpld_control_c48 017 failed in check_result failed 
[RT] Error: Test cpld_control_c48 017 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1304019799/20230517213012/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20230515/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1304019799/20230522130014/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by zach1221** [comment]
Hey @SadeghTabas-NOAA can you resolve your conflict please and re-sync your branch? I think we'll need to restart the tests, but I'll handle. @BrianCurtis-NOAA fyi, we'll start testing this PR next.

**Comment by sadeghitabas** [comment]
@zach1221 It looks like it has conflict with the recent update. I'll make it ready in a moment.

**Comment by zach1221** [comment]
Thanks, @SadeghTabas-NOAA . Additionally, if you're agreeable to it, we'd like to combine this PR with #1741 . Are you comfortable with this? If so, the easiest way to do this would be to create a PR directly to Bin's fork branch.

**Comment by sadeghitabas** [comment]
> Thanks, @SadeghTabas-NOAA . Additionally, if you're agreeable to it, we'd like to combine this PR with #1741 . Are you comfortable with this? If so, the easiest way to do this would be to create a PR directly to Bin's fork branch.

The branch is updated. Sure I'll combine them once the auto RT tests are done. Thanks

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1304019799/20230522153015/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by sadeghitabas** [comment]
@zach1221  Could you please check why the orion rt gets failed? I don't have access to the epic project. Thanks

**Comment by zach1221** [comment]
@SadeghTabas-NOAA Yes, once the PRs are combined we'll have to re-run all the tests anyway, including Orion.  If you're ready, go ahead to create the PR into Bin's branch so we can combine with 1741.

**Comment by sadeghitabas** [comment]
> @SadeghTabas-NOAA Yes, once the PRs are combined we'll have to re-run all the tests anyway, including Orion. If you're ready, go ahead to create the PR into Bin's branch so we can combine with 1741.

OK. I'm waiting for PR1741 to be synced. I'll merge it to my PR after that. Thanks

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1304019799/20230522203017/ufs-weather-model
[RT] Error: Test cpld_debug_p8 014 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by zach1221** [comment]
@SadeghTabas-NOAA it looks like Bin has synced up his 1741 PR, can you please create a PR to his forked branch?

**Comment by sadeghitabas** [comment]
> @SadeghTabas-NOAA it looks like Bin has synced up his 1741 PR, can you please create a PR to his forked branch?

Sure I combine it with this PR.

**Comment by DeniseWorthen** [comment]
Do we have sub-component PR reviews complete for this PR?

**Comment by sadeghitabas** [comment]
> Do we have sub-component PR reviews complete for this PR?

@DeniseWorthen Hi, PR1699 (without subcomponent changes) is linked with PR1741 (with CDEPS updates). As I combined these PRs I added the check mark for the subcomponent CDEPS (please let me know if I'm wrong). @zach1221 mentioned that both PRs will be tested once they combined. Thanks

**Comment by zach1221** [comment]
@SadeghTabas-NOAA @binli2337 are there any additional sub-component PRs for 1699 and 1741? I did not see any listed, but if there are, please let me know and I can link to them under the "Linked PRs" section above and ensure they're reviewed. Is CDEPS sub-pr [55](https://github.com/NOAA-EMC/CDEPS/pull/55) part of 1741?

**Comment by DeniseWorthen** [comment]
@SadeghTabas-NOAA It is fine what you did. But I don't see that the CDEPS subcomponent (https://github.com/NOAA-EMC/CDEPS/pull/55) has been reviewed and approved yet.

edit: I've added the CDEPS PR to the above list of linked PRs

**Comment by sadeghitabas** [comment]
> @SadeghTabas-NOAA @binli2337 are there any additional sub-component PRs for 1699 and 1741? I did not see any listed, but if there are, please let me know and I can link to them under the "Linked PRs" section above and ensure they're reviewed. Is CDEPS sub-pr [55](https://github.com/NOAA-EMC/CDEPS/pull/55) part of 1741?

@zach1221 The original PR1699 does not have any subcomponent involved.

**Comment by zach1221** [comment]
Jenkins-ci logs attached. ORTs all passed.
[ufs-weather-model » ort-docker-pipeline » PR-1699 #2 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11546807/ufs-weather-model.ort-docker-pipeline.PR-1699.2.Console.Jenkins.pdf)

**Comment by SadeghTabas-NOAA** [comment]
> @SadeghTabas-NOAA It is fine what you did. But I don't see that the CDEPS subcomponent ([NOAA-EMC/CDEPS#55](https://github.com/NOAA-EMC/CDEPS/pull/55)) has been reviewed and approved yet.
> 
> edit: I've added the CDEPS PR to the above list of linked PRs

**Comment by sadeghitabas** [comment]
Sorry I closed the PR accidentally. I reopened it. I just wanted to say that I think the PR1741 was reviewed yesterday and the reviews gone once the branch updated. Sorry for the inconvenience.

**Comment by zach1221** [comment]
@SadeghTabas-NOAA I think everything's ok. Review was requested on the 1741 sub-pr, but has not been provided yet.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I know we talked previously but just wanted to make note of it here. Once the review/approval is given on the  CDEPS sub-pr #55 . We can begin testing of this merged PR.

**Comment by zach1221** [comment]
Ok, most of the tests are finished. I'll attempt to add Orion logs later this evening, assuming I'm able to login.

**Comment by zach1221** [comment]
Testing is now complete on this PR.

**Comment by zach1221** [comment]
The CDEPS subcomponent PR [#55](https://github.com/NOAA-EMC/CDEPS/pull/55/) has been merged. It doesn't look like any submodules pointers need to be updated or gitmodules reverted in this combined PR, so I'll go ahead to send out final reviews.

**Review by DeniseWorthen — DISMISSED** [review]

**Comment by jkbk2004** [comment]
@SadeghTabas-NOAA @zach1221 correct cdeps hash is https://github.com/NOAA-EMC/CDEPS/commit/2aa6bfbb62ebeecd7da964b8074f6c3c41c7d1eb. Can we make sure?

**Comment by DeniseWorthen** [comment]
@SadeghTabas-NOAA I don't think the hash is correct.

**Comment by zach1221** [comment]
@SadeghTabas-NOAA Can you update the CDEPS hash from fa0a925 to the correct hash of https://github.com/NOAA-EMC/CDEPS : 2aa6bfbb62ebeecd7da964b8074f6c3c41c7d1eb

**Comment by sadeghitabas** [comment]
I updated the submodule pointer. Sorry for inconvenience. Thanks

**Comment by zach1221** [comment]
Thanks, @SadeghTabas-NOAA ! Resending reviews

**Review by DeniseWorthen — APPROVED** [review]
Looks good.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
