### PR TITLE
use instantaneous fields for coupling

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's. (NA)
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13061117/RegressionTests_hera.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Changes field aliases to allow export of instantaneous fields rather than mean. The ``inst`` and ``mean`` fields are not B4b, but are generally ~O-12 different. See figures https://github.com/ufs-community/ufs-weather-model/issues/1800#issuecomment-1758272639. 

Logs will be run after the two dependent PRs are merged.

### Associated UFSWM Issue to close

- closes Issue #1800 
- required by #1648 

### Blocking Dependencies

- depends on ufs-community/ufs-weather-model/pull/1947
- depends on #1948

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

Changes are expected for all global coupled, hafs regional and atm-land tests.

</details>

```sh
tests/logs/log_hera: grep FAIL rt_* 
rt_001_cpld_control_p8_mixedmode_intel.log:71:Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
rt_002_cpld_control_gfsv17_intel.log:70:Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
rt_004_cpld_control_p8_intel.log:71:Test 004 cpld_control_p8_intel FAIL Tries: 2
rt_006_cpld_control_qr_p8_intel.log:71:Test 006 cpld_control_qr_p8_intel FAIL Tries: 2
rt_008_cpld_2threads_p8_intel.log:59:Test 008 cpld_2threads_p8_intel FAIL Tries: 2
rt_009_cpld_decomp_p8_intel.log:59:Test 009 cpld_decomp_p8_intel FAIL Tries: 2
rt_010_cpld_mpi_p8_intel.log:59:Test 010 cpld_mpi_p8_intel FAIL Tries: 2
rt_011_cpld_control_ciceC_p8_intel.log:71:Test 011 cpld_control_ciceC_p8_intel FAIL Tries: 2
rt_012_cpld_control_c192_p8_intel.log:59:Test 012 cpld_control_c192_p8_intel FAIL Tries: 2
rt_014_cpld_bmark_p8_intel.log:54:Test 014 cpld_bmark_p8_intel FAIL Tries: 2
rt_016_cpld_control_noaero_p8_intel.log:70:Test 016 cpld_control_noaero_p8_intel FAIL Tries: 2
rt_017_cpld_control_nowave_noaero_p8_intel.log:68:Test 017 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
rt_018_cpld_debug_p8_intel.log:59:Test 018 cpld_debug_p8_intel FAIL Tries: 2
rt_019_cpld_debug_noaero_p8_intel.log:58:Test 019 cpld_debug_noaero_p8_intel FAIL Tries: 2
rt_020_cpld_control_noaero_p8_agrid_intel.log:68:Test 020 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
rt_021_cpld_control_c48_intel.log:56:Test 021 cpld_control_c48_intel FAIL Tries: 2
rt_022_cpld_control_p8_faster_intel.log:71:Test 022 cpld_control_p8_faster_intel FAIL Tries: 2
rt_023_cpld_control_pdlib_p8_intel.log:70:Test 023 cpld_control_pdlib_p8_intel FAIL Tries: 2
rt_026_cpld_debug_pdlib_p8_intel.log:58:Test 026 cpld_debug_pdlib_p8_intel FAIL Tries: 2
rt_134_hafs_regional_atm_ocn_intel.log:15:Test 134 hafs_regional_atm_ocn_intel FAIL Tries: 2
rt_136_hafs_regional_atm_ocn_wav_intel.log:17:Test 136 hafs_regional_atm_ocn_wav_intel FAIL Tries: 2
rt_147_hafs_regional_storm_following_1nest_atm_ocn_intel.log:15:Test 147 hafs_regional_storm_following_1nest_atm_ocn_intel FAIL Tries: 2
rt_149_hafs_regional_storm_following_1nest_atm_ocn_debug_intel.log:13:Test 149 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL Tries: 2
rt_150_hafs_regional_storm_following_1nest_atm_ocn_wav_intel.log:17:Test 150 hafs_regional_storm_following_1nest_atm_ocn_wav_intel FAIL Tries: 2
rt_151_hafs_regional_docn_intel.log:14:Test 151 hafs_regional_docn_intel FAIL Tries: 2
rt_152_hafs_regional_docn_oisst_intel.log:14:Test 152 hafs_regional_docn_oisst_intel FAIL Tries: 2
rt_171_control_p8_atmlnd_sbs_intel.log:91:Test 171 control_p8_atmlnd_sbs_intel FAIL Tries: 2
rt_235_cpld_control_p8_gnu.log:71:Test 235 cpld_control_p8_gnu FAIL Tries: 2
rt_236_cpld_control_nowave_noaero_p8_gnu.log:68:Test 236 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
rt_237_cpld_debug_p8_gnu.log:59:Test 237 cpld_debug_p8_gnu FAIL Tries: 2
rt_238_cpld_control_pdlib_p8_gnu.log:70:Test 238 cpld_control_pdlib_p8_gnu FAIL Tries: 2
rt_239_cpld_debug_pdlib_p8_gnu.log:58:Test 239 cpld_debug_pdlib_p8_gnu FAIL Tries: 2
```

Regression tests were re-run on Hera at 3747dcd, confirming previous results. 
### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [ ] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by zach1221** [comment]
@ulmononian I'm not sure if you're the best contact for this or Dom, but I'm having trouble with failing gnu tests on Hercules, as mvapich insists a slurm module must also be loaded. However, it still fails to load when the slurm module is also loaded.
image

**Comment by jkbk2004** [comment]
> @ulmononian I'm not sure if you're the best contact for this or Dom, but I'm having trouble with failing gnu tests on Hercules, as mvapich insists a slurm module must also be loaded. However, it still fails to load when the slurm module is also loaded. image

@ulmononian @natalie-perlin can we follow up with the spack stack issue on hercules?

**Comment by zach1221** [comment]
> > @ulmononian I'm not sure if you're the best contact for this or Dom, but I'm having trouble with failing gnu tests on Hercules, as mvapich insists a slurm module must also be loaded. However, it still fails to load when the slurm module is also loaded. image
> 
> @ulmononian @natalie-perlin can we follow up with the spack stack issue on hercules?

I'm talking to Natalie now.

**Comment by DeniseWorthen** [comment]
@zach1221 What changed on Hercules between Nov 2 (the last time we have a log) and now?

**Comment by zach1221** [comment]
> @zach1221 What changed on Hercules between Nov 2 (the last time we have a log) and now?

Not certain yet exactly, but Dom suspects hercules admins changes something with the slurm modules.

**Comment by jkbk2004** [comment]
> > @zach1221 What changed on Hercules between Nov 2 (the last time we have a log) and now?
> 
> Not certain yet exactly, but Dom suspects hercules admins changes something with the slurm modules.

If we need re-installation of spack stack, then I think we should keep moving the PR and address the issue in next pr. Certainly, admin updated slurm on hercules. @BrianCurtis-NOAA what do you think?

**Comment by BrianCurtis-NOAA** [comment]
> > > @zach1221 What changed on Hercules between Nov 2 (the last time we have a log) and now?
> > 
> > 
> > Not certain yet exactly, but Dom suspects hercules admins changes something with the slurm modules.
> 
> If we need re-installation of spack stack, then I think we should keep moving the PR and address the issue in next pr. Certainly, admin updated slurm on hercules. @BrianCurtis-NOAA what do you think?

I think we can run on hercules now: https://github.com/ufs-community/ufs-weather-model/issues/1985

**Comment by zach1221** [comment]
@BrianCurtis-NOAA Yes, I'm going to re-try gnu on hercules now with 1.5.0.

**Comment by zach1221** [comment]
Ok, we're finally done with regression testing. Sending out final reviews now.

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Pull request merged**
