### PR TITLE
Noah MP updates for Prototype 8 (GFSv17)

### PR DESCRIPTION
**Pull request by HelinWei-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

[fv3atm PR 387](https://github.com/NOAA-EMC/fv3atm/pull/387)
[ccpp-physics PR 729](https://github.com/NCAR/ccpp-physics/pull/729)
[UPP PR 378](https://github.com/NOAA-EMC/UPP/pull/378)

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

All results will be changed because of the modified physics and extra fields in the model output

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

New diag_table is needed for those extra land ouputs

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

1. Add some extra surface fields required to close the offline energy/water budget computation. These fields are listed below:

LAND FRACTION
INST PREC ADVEC HEAT
WATER IN AQUIFER
ACM EIWATER(CANOPY WATER EVAPORATION)
ACM PLANTTR( PLANT TRANSPIRATION)
ACM SOILSE (BARE SOIL EVAPORATION)
AVE PREC ADVEC HEAT

2. The surface loop control/iteration removal when Noah MP is used
 
- Surface skin temperature is determined inside the Noah MP LSM with its own surface scheme/iteration.
- 'guess_run'/iteration (for determination of skin temperature with weak winds) in surface loop control is set to 'false' when Noah MP LSM (lsm=2) is used.

3. New coupling interface

- The land model provides feedback to the atmospheric boundary layer. The required bulk Richard number input to the boundary layer scheme is computed using grid-aggregated momentum (from the roughness lengths over the tiles and vegetation fraction) and thermal roughness (from interpolation of kB^-1 from the tiles) lengths.

4. The addition of GFS surface scheme in Noah MP surface layer call

- To be consistent with the surface layer treatment for the other part of the surface in the model, the original
GFS surface layer scheme is added to the Noah MP surface layer option.

5. Fix the inout issue of smc in Noah LSM (sflx.f)

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [ ] orion.intel, no access
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1527389832

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?

No. 

If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211129193014/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211119/GNU
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211129193202/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211119/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-intel-BL

**Comment by DusanJovic-NOAA** [comment]
Please update BL_DATE in rt.sh.

**Comment by DusanJovic-NOAA** [comment]
Compilation fails with this error message:
```
+ make -j 8 VERBOSE=1
/gpfs/hps3/emc/meso/save/Dusan.Jovic/ufs/pr927/ufs-weather-model/FV3/ccpp/physics/physics/GFS_surface_generic.F90(294): error #6451: A dummy argument name is required in this context.   [DTF]
        real(kind=kind_phys),                   intent(in) :: dtf
--------------------------------------------------------------^                                                                                                                                                      
compilation aborted for /gpfs/hps3/emc/meso/save/Dusan.Jovic/ufs/pr927/ufs-weather-model/FV3/ccpp/physics/physics/GFS_surface_generic.F90 (code 1)
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/physics/GFS_surface_generic.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

**Comment by climbfuji** [comment]
> Compilation fails with this error message:
> 
> ```
> + make -j 8 VERBOSE=1
> /gpfs/hps3/emc/meso/save/Dusan.Jovic/ufs/pr927/ufs-weather-model/FV3/ccpp/physics/physics/GFS_surface_generic.F90(294): error #6451: A dummy argument name is required in this context.   [DTF]
>         real(kind=kind_phys),                   intent(in) :: dtf
> --------------------------------------------------------------^                                                                                                                                                      
> compilation aborted for /gpfs/hps3/emc/meso/save/Dusan.Jovic/ufs/pr927/ufs-weather-model/FV3/ccpp/physics/physics/GFS_surface_generic.F90 (code 1)
> make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/physics/GFS_surface_generic.F90.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make: *** [all] Error 2
> ```

I was expecting something like this, and I have more questions on that variable - `dtf` was removed from the argument list, but neither the declaration that Dusan pointed out nor the entry in the CCPP metadata was removed. This shouldn't compile (and it doesn't). @grantfirl FYI

**Comment by HelinWei-NOAA** [comment]
Sorry. I accidentally removed this variable from the argument list when I
did the code cleanup this morning. I have added it back with this commit
<https://github.com/HelinWei-NOAA/ccpp-physics/commit/8867777febae068886f433d8e7de0feaef2d8b2e>

**Comment by DusanJovic-NOAA** [comment]
@HelinWei-NOAA Please update your fv3atm branch and then your ufs-weather-model branch.

**Comment by HelinWei-NOAA** [comment]
updated

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211130030013/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_7052
Test control 001 failed failed 
Test control 001 failed in run_test failed 
Test control_c48 002 failed failed 
Test control_c48 002 failed in run_test failed 
Test control_stochy 003 failed failed 
Test control_stochy 003 failed in run_test failed 
Test control_flake 004 failed failed 
Test control_flake 004 failed in run_test failed 
Test control_rrtmgp 005 failed failed 
Test control_rrtmgp 005 failed in run_test failed 
Test control_thompson 006 failed failed 
Test control_thompson 006 failed in run_test failed 
Test control_thompson_no_aero 007 failed failed 
Test control_thompson_no_aero 007 failed in run_test failed 
Test control_ras 008 failed failed 
Test control_ras 008 failed in run_test failed 
Test fv3_gsd 012 failed failed 
Test fv3_gsd 012 failed in run_test failed 
Test control_debug 015 failed failed 
Test control_debug 015 failed in run_test failed 
Test control_diag_debug 016 failed failed 
Test control_diag_debug 016 failed in run_test failed 
Test regional_control_debug 017 failed failed 
Test regional_control_debug 017 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 018 failed failed 
Test fv3_rrfs_v1alpha_debug 018 failed in run_test failed 
Test fv3_gsd_debug 020 failed failed 
Test fv3_gsd_debug 020 failed in run_test failed 
Test fv3_gsd_diag_debug 021 failed failed 
Test fv3_gsd_diag_debug 021 failed in run_test failed 
Test control_thompson_debug 022 failed failed 
Test control_thompson_debug 022 failed in run_test failed 
Test control_thompson_no_aero_debug 023 failed failed 
Test control_thompson_no_aero_debug 023 failed in run_test failed 
Test control_thompson_extdiag_debug 024 failed failed 
Test control_thompson_extdiag_debug 024 failed in run_test failed 
Test control_rrtmgp_debug 025 failed failed 
Test control_rrtmgp_debug 025 failed in run_test failed 
Test control_ras_debug 026 failed failed 
Test control_ras_debug 026 failed in run_test failed 
Test control_stochy_debug 027 failed failed 
Test control_stochy_debug 027 failed in run_test failed 
Test control_debug_p7 028 failed failed 
Test control_debug_p7 028 failed in run_test failed 
Test cpld_debug_p7 032 failed failed 
Test cpld_debug_p7 032 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-BL

**Comment by junwang-noaa** [comment]
@HelinWei-NOAA The hera gnu RT reported with following error in
/scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_7052/control/err:
116:
116: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
116:
116: Backtrace for this error:
116: #1  0x2583e96 in __gfs_surface_generic_post_MOD_gfs_surface_generic_post_run
116:    at /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211130030013/ufs-weather-model/FV3/ccpp/physics/physics/GFS_surface_generic.F90:338

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211130031517/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_22495
Test cpld_debug_p7 006 failed failed 
Test cpld_debug_p7 006 failed in run_test failed 
Test control 007 failed failed 
Test control 007 failed in run_test failed 
Test control_CubedSphereGrid 008 failed failed 
Test control_CubedSphereGrid 008 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 009 failed failed 
Test control_wrtGauss_netcdf_parallel 009 failed in run_test failed 
Test control_c48 010 failed failed 
Test control_c48 010 failed in run_test failed 
Test control_c192 011 failed failed 
Test control_c192 011 failed in run_test failed 
Test control_c384 012 failed failed 
Test control_c384 012 failed in run_test failed 
Test control_c384gdas 013 failed failed 
Test control_c384gdas 013 failed in run_test failed 
Test control_stochy 014 failed failed 
Test control_stochy 014 failed in run_test failed 
Test control_lndp 015 failed failed 
Test control_lndp 015 failed in run_test failed 
Test regional_control 017 failed failed 
Test regional_control 017 failed in run_test failed 
Test regional_quilt 019 failed failed 
Test regional_quilt 019 failed in run_test failed 
Test regional_quilt_hafs 020 failed failed 
Test regional_quilt_hafs 020 failed in run_test failed 
Test regional_quilt_netcdf_parallel 021 failed failed 
Test regional_quilt_netcdf_parallel 021 failed in run_test failed 
Test regional_quilt_RRTMGP 022 failed failed 
Test regional_quilt_RRTMGP 022 failed in run_test failed 
Test fv3_gsd 023 failed failed 
Test fv3_gsd 023 failed in run_test failed 
Test fv3_rap 025 failed failed 
Test fv3_rap 025 failed in run_test failed 
Test fv3_hrrr 026 failed failed 
Test fv3_hrrr 026 failed in run_test failed 
Test control_rrtmgp 028 failed failed 
Test control_rrtmgp 028 failed in run_test failed 
Test control_rrtmgp_c192 029 failed failed 
Test control_rrtmgp_c192 029 failed in run_test failed 
Test control_csawmg 030 failed failed 
Test control_csawmg 030 failed in run_test failed 
Test control_csawmgt 031 failed failed 
Test control_csawmgt 031 failed in run_test failed 
Test control_flake 032 failed failed 
Test control_flake 032 failed in run_test failed 
Test control_ras 033 failed failed 
Test control_ras 033 failed in run_test failed 
Test control_thompson 034 failed failed 
Test control_thompson 034 failed in run_test failed 
Test control_thompson_no_aero 035 failed failed 
Test control_thompson_no_aero 035 failed in run_test failed 
Test control_wam 038 failed failed 
Test control_wam 038 failed in run_test failed 
Test control_debug 039 failed failed 
Test control_debug 039 failed in run_test failed 
Test control_CubedSphereGrid_debug 040 failed failed 
Test control_CubedSphereGrid_debug 040 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel_debug 041 failed failed 
Test control_wrtGauss_netcdf_parallel_debug 041 failed in run_test failed 
Test control_stochy_debug 042 failed failed 
Test control_stochy_debug 042 failed in run_test failed 
Test control_lndp_debug 043 failed failed 
Test control_lndp_debug 043 failed in run_test failed 
Test control_rrtmgp_debug 044 failed failed 
Test control_rrtmgp_debug 044 failed in run_test failed 
Test control_csawmg_debug 045 failed failed 
Test control_csawmg_debug 045 failed in run_test failed 
Test control_csawmgt_debug 046 failed failed 
Test control_csawmgt_debug 046 failed in run_test failed 
Test control_ras_debug 047 failed failed 
Test control_ras_debug 047 failed in run_test failed 
Test control_diag_debug 048 failed failed 
Test control_diag_debug 048 failed in run_test failed 
Test control_debug_p7 049 failed failed 
Test control_debug_p7 049 failed in run_test failed 
Test control_thompson_debug 050 failed failed 
Test control_thompson_debug 050 failed in run_test failed 
Test control_thompson_no_aero_debug 051 failed failed 
Test control_thompson_no_aero_debug 051 failed in run_test failed 
Test control_thompson_extdiag_debug 052 failed failed 
Test control_thompson_extdiag_debug 052 failed in run_test failed 
Test regional_control_debug 053 failed failed 
Test regional_control_debug 053 failed in run_test failed 
Test regional_quilt_debug 054 failed failed 
Test regional_quilt_debug 054 failed in run_test failed 
Test fv3_gsd_debug 055 failed failed 
Test fv3_gsd_debug 055 failed in run_test failed 
Test fv3_gsd_diag_debug 056 failed failed 
Test fv3_gsd_diag_debug 056 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 057 failed failed 
Test fv3_rrfs_v1beta_debug 057 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 058 failed failed 
Test fv3_rrfs_v1alpha_debug 058 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 059 failed failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 059 failed in run_test failed 
Test hafs_regional_atm 061 failed failed 
Test hafs_regional_atm 061 failed in run_test failed 
Test hafs_regional_atm_ocn 062 failed failed 
Test hafs_regional_atm_ocn 062 failed in run_test failed 
Test hafs_regional_atm_wav 063 failed failed 
Test hafs_regional_atm_wav 063 failed in run_test failed 
Test hafs_regional_atm_ocn_wav 064 failed failed 
Test hafs_regional_atm_ocn_wav 064 failed in run_test failed 
Test hafs_regional_1nest_atm 065 failed failed 
Test hafs_regional_1nest_atm 065 failed in run_test failed 
Test hafs_regional_telescopic_2nests_atm 066 failed failed 
Test hafs_regional_telescopic_2nests_atm 066 failed in run_test failed 
Test hafs_global_1nest_atm 067 failed failed 
Test hafs_global_1nest_atm 067 failed in run_test failed 
Test hafs_global_multiple_4nests_atm 068 failed failed 
Test hafs_global_multiple_4nests_atm 068 failed in run_test failed 
Test hafs_regional_docn 069 failed failed 
Test hafs_regional_docn 069 failed in run_test failed 
Test hafs_regional_docn_oisst 070 failed failed 
Test hafs_regional_docn_oisst 070 failed in run_test failed 
Test control_atmwav 080 failed failed 
Test control_atmwav 080 failed in run_test failed 
Test control_c384gdas_wav 081 failed failed 
Test control_c384gdas_wav 081 failed in run_test failed 
Test control_atm_aerosols 082 failed failed 
Test control_atm_aerosols 082 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by HelinWei-NOAA** [comment]
Jun,

Thank you for testing. I have fixed the issue. pahi is only available when
running Noah MP.

Helin

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211130130010/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_24291
Test fv3_rrfs_v1alpha_debug 018 failed failed 
Test fv3_rrfs_v1alpha_debug 018 failed in run_test failed 
Test control_debug_p7 028 failed failed 
Test control_debug_p7 028 failed in run_test failed 
Test cpld_debug_p7 032 failed failed 
Test cpld_debug_p7 032 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-BL

**Comment by junwang-noaa** [comment]
@HelinWei-NOAA The three tests failed with error:

The 135: forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
135: Image              PC                Routine            Line        Source
135: fv3.exe            000000000DE2D09E  Unknown               Unknown  Unknown
135: libpthread-2.17.s  00002AB6E1717630  Unknown               Unknown  Unknown
135: fv3.exe            000000000791C998  noahmpdrv_mp_noah         980  sfc_noahmp_drv.F90
135: fv3.exe            000000000622B87A  oupled_nsstnoahmp        5867  ccpp_FV3_GFS_v16_coupled_nsstNoahmpUGWPv1_physics_cap.F90
135: fv3.exe            0000000005DA3163  ccpp_static_api_m         283  ccpp_static_api.F90

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/784997109/20211130131512/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_4130
Test cpld_debug_p7 006 failed failed 
Test cpld_debug_p7 006 failed in run_test failed 
Test control_debug_p7 049 failed failed 
Test control_debug_p7 049 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 057 failed failed 
Test fv3_rrfs_v1beta_debug 057 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 058 failed failed 
Test fv3_rrfs_v1alpha_debug 058 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 059 failed failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 059 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by junwang-noaa** [comment]
@HelinWei-NOAA The intel run directory is at: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_4130
please go to the failed test directories to check errors. Thanks

**Comment by MinsukJi-NOAA** [comment]
I will make a PR to @HelinWei-NOAA's branch for the regional CI fix.

**Comment by HelinWei-NOAA** [comment]
> I will make a PR to @HelinWei-NOAA's branch for the regional CI fix.

I just merged this PR to my branch.

**Comment by DusanJovic-NOAA** [comment]
WCOSS RT log files:
/scratch1/NCEPDEV/stmp2/Dusan.Jovic/pr927/RegressionTests_wcoss_cray.log
/scratch1/NCEPDEV/stmp2/Dusan.Jovic/pr927/RegressionTests_wcoss_dell_p3.log

@HelinWei-NOAA please commit these two log files

**Comment by HelinWei-NOAA** [comment]
> WCOSS RT log files: /scratch1/NCEPDEV/stmp2/Dusan.Jovic/pr927/RegressionTests_wcoss_cray.log /scratch1/NCEPDEV/stmp2/Dusan.Jovic/pr927/RegressionTests_wcoss_dell_p3.log
> 
> @HelinWei-NOAA please commit these two log files

done

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
