### PR TITLE
update cmeps, fix debug compile, rename nems.configure files for coupled model

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## Description

This PR updates to the latest CMEPS emc/develop. 
It implements a fix to use the fv3_debug module if debug=Y and fv3_debug is available 
It shortens the names of the nems.configure files for the coupled model

### Issue(s) addressed

Issue #253 
Issue #249 
Issue #246 

## Testing

New baselines will be required on all supported platforms.

## Dependencies

Dependent CMEPS [#22](https://github.com/NOAA-EMC/CMEPS/pull/22)

Co-authors: @aerorahul

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
the ufs-weather-model changes look good.

**Comment by aerorahul** [comment]
FYI -- The CMEPS PR hyperlink in the description is pointing to a UFS-weather-model PR # 22.

**Review by climbfuji — APPROVED** [review]
Thanks for removing the extraneous whitespaces. The `fv3_debug` changes look good, too.

**Comment by DeniseWorthen** [comment]
All logs have been now been posted.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
