### PR TITLE
Update WW3 with latest develop

### LINKED ISSUE #1551: Update to point latest WW3 dev/ufs-weather-model branch with HAFSv1 needed updates
## Description
Update to point latest WW3 dev/ufs-weather-model branch with HAFSv1 needed updates.

## Solution
@JessicaMeixner-NOAA is working on updating the corresponding WW3 branch, and we will update the submodule WW3 accordingly.

## Alternatives
N/A.

## Related to
- waiting on NOAA-EMC/WW3/pull/<>

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## Description

Updates WW3 with recent updates from develop which include: 
* Update ww3_gint to interpolate restart files (https://github.com/NOAA-EMC/WW3/pull/962)
* Extend loop to include ghost points for VA (https://github.com/NOAA-EMC/WW3/pull/975)
* Reorders some loops in PDLIB_EXPLICIT_BLOCK for efficiency (https://github.com/NOAA-EMC/WW3/pull/979)

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

### Combined with PR's (If Applicable):

Can combine with any PR that doesn't change WW3 code beyond this update. 

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
Closes https://github.com/ufs-community/ufs-weather-model/issues/1551 

WW3 PR: https://github.com/NOAA-EMC/WW3/pull/982

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Can orion.intel replace the required hera/cheyenne.intel?   The queue was faster on orion and I overlooked that it's hera specifically that was asked for here.  The hera.gnu is in the queue  and I will post both logs when completed. 

@MatthewMasarik-NOAA is on vacation and wont be back until Monday so I wont have a review on the WW3 side complete until then.

**Comment by BrianCurtis-NOAA** [comment]
@JessicaMeixner-NOAA any Intel will do. Yeah Hera has my job still with 1 node waiting since about 11. Good luck with an entire GNU suite!

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 If you have some time, can you run this PR through cheyenne.gnu comparing to current baselines? Might go a LOT faster than Hera currently.

**Comment by jkbk2004** [comment]
> @jkbk2004 If you have some time, can you run this PR through cheyenne.gnu comparing to current baselines? Might go a LOT faster than Hera currently.

sure!

**Comment by JessicaMeixner-NOAA** [comment]
[RegressionTests_orion.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11226263/RegressionTests_orion.intel.log)
Here's the orion log.

**Comment by jkbk2004** [comment]
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11228299/RegressionTests_cheyenne.gnu.log)

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @jkbk2004 !

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA we are considering to combine with #1669. no baseline changes. Would that be ok?

**Comment by JessicaMeixner-NOAA** [comment]
Sounds great!

**Review by MatthewMasarik-NOAA — APPROVED** [review]
**Code review** Pass

**RTs**  Pass
- @JessicaMeixner-NOAA has posted successful intel (orion) RT logs:  https://github.com/ufs-community/ufs-weather-model/pull/1710#issuecomment-1507577066
- @jkbk2004 posted successful gnu (cheyenne) RT logs: https://github.com/ufs-community/ufs-weather-model/pull/1710#issuecomment-1507848301

Approved.

**Comment by jkbk2004** [comment]
merged with #1669

**Pull request closed without merging**
