### PR TITLE
Add option to write 3d soilt, soilw and soill variables to a history file

### LINKED ISSUE #1055: Add vertical dimension to certain surface fields
## Description
This discussion started in https://github.com/ufs-community/ufs-weather-model/issues/1052 but continuing it here.

Many of the fields in the `sfcfNNN.nc` files look like so:
```
	float soilt1(time, tile, grid_yt, grid_xt) ;
	float soilt2(time, tile, grid_yt, grid_xt) ;
	float soilt3(time, tile, grid_yt, grid_xt) ;
	float soilt4(time, tile, grid_yt, grid_xt) ;
```
Which is 4 layers of soil temperature. 

I think it would make more sense for these fields to be instead like so:
```
	float soilt(time, tile, zsoil, grid_yt, grid_xt) ;
```
or something like that.

This would greatly simplify I/O routines as it would be a few variables with a vertical dimension rather than k*variables where k is the number of layers. I also suspect that the total file size would decrease with fewer variables being defined (but not sure by how much).

## Solution
Update fields that should have a vertical component to include one in the write-grid component output.

## Alternatives
Keep the files as is.

## Related to
The UPP and other downstream users may depend on this change?

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13754603/RegressionTests_hera.log)

- [x] Add list of all failed regression tests in "Regression Tests" section.

### Description

This PR adds three 3D soil variables (soilt, soilw and soill) to a history file if corresponding entries are specified in diag_table file. The new 3d versions of these variables is identical to a set of 2d variables currently available (soilt1, soilt2, etc). For example, replacing:
```
> "gfs_sfc",     "soilt1",      "soilt1"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilt2",      "soilt2"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilt3",      "soilt3"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilt4",      "soilt4"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilw1",      "soilw1"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilw2",      "soilw2"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilw3",      "soilw3"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "soilw4",      "soilw4"     "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "slc_1",       "soill1",    "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "slc_2",       "soill2",    "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "slc_3",       "soill3",    "fv3_history2d",  "all",  .false.,  "none",  2
> "gfs_sfc",     "slc_4",       "soill4",    "fv3_history2d",  "all",  .false.,  "none",  2
```
with
```
< "gfs_sfc",     "soilt",       "soilt"      "fv3_history2d",  "all",  .false.,  "none",  2
< "gfs_sfc",     "soilw",       "soilw"      "fv3_history2d",  "all",  .false.,  "none",  2
< "gfs_sfc",     "soill",       "soill",     "fv3_history2d",  "all",  .false.,  "none",  2
```

will write 3D version of the above soil variables to a history file

### Commit Message

Add option to write 3d soilt, soilw and soill variables to a history file

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [x] Normal

### Git Issues Fixed By This PR

Closes #1055

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3 NOAA-EMC/fv3atm/pull/744
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

control_CubedSphereGrid_parallel

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
Hi @DusanJovic-NOAA, please go ahead and sync your branches with the latest develop, we'd like to get started on testing this PR next, thank you.

**Comment by DusanJovic-NOAA** [comment]
@FernandoAndrade-NOAA Done.

**Comment by FernandoAndrade-NOAA** [comment]
Gaea failed 4 tests, these failures do not look like standard timeouts. I'm checking up on the `err` to see what may be going on.
```
control_c384_intel 040 failed in run_test
control_decomp_p8_intel 053 failed in run_test
rap_sfcdiff_intel 072 failed in run_test
rap_noah_sfcdiff_cires_ugwp_debug_intel 110 failed in run_test
```

**Comment by FernandoAndrade-NOAA** [comment]
> Gaea failed 4 tests, these failures do not look like standard timeouts. I'm checking up on the `err` to see what may be going on.
> 
> ```
> control_c384_intel 040 failed in run_test
> control_decomp_p8_intel 053 failed in run_test
> rap_sfcdiff_intel 072 failed in run_test
> rap_noah_sfcdiff_cires_ugwp_debug_intel 110 failed in run_test
> ```

rundir: `/gpfs/f5/epic/scratch/Fernando.Andrade-maldonado/FV3_RT/rt_238940/`

**Comment by FernandoAndrade-NOAA** [comment]
@jkbk2004 @zach1221 FYI, the control_c384 intel rerun with develop passed, so the issues may be coming from the PR updates. It should also be noted that gaea seems to have a bit of performance degradation since last night.

**Comment by FernandoAndrade-NOAA** [comment]
Given the recent email regarding issues with Gaea jobs failing after yesterday's maintenance that should now be resolved, I'm rerunning the failed tests to verify if it was just a system issue.

**Comment by FernandoAndrade-NOAA** [comment]
Double checking the log diff, the `rap_sfcdiff_restart` is missing from the Gaea log, likely due to the issues from the maintenance. I'm rerunning that as well. The other 4 reported test failures passed fine this time and have their success appended to the Gaea log.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, I think we're good to continue with the merge process in the fv3 sub pr. @zach1221 FYI

**Comment by zach1221** [comment]
@DusanJovic-NOAA fv3atm pr is merged. Please update hash and revert .gitmodule url.
https://github.com/NOAA-EMC/fv3atm/commit/0fe9ba3020ad2f744ead7323bda414497aa33632

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
