### PR TITLE
Fix atmospheric model's field import

### LINKED ISSUE #401: Replacing single NUOPC run phase with two sequential run phases leads to surface layer differences in P7 configurations
## Description
Large differences in surface layer quantities occur in fully coupled (P7) experiments when running the atmosphere component (ATM) using two sequential run phases (phase1, phase2) instead of a single one. Such differences appear after the first coupling time step, and are most evident for surface temperature, 2m temperature, and surface heat fluxes.

### To Reproduce:
This issue was observed on Hera using Intel compilers.

To reproduce, please edit the UFS weather model's run sequence in the `nems.configure` file and replace `ATM` as follows:

```
[...]
ATM phase1
ATM phase2
[...]
```

### PR DESCRIPTION
**Pull request by rmontuoro**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR fixes the coupling issue described in [#401](https://github.com/NOAA-EMC/fv3atm/issues/401), which occurs when running the atmospheric model's with separate run phases.

### Issue(s) addressed

- fixes noaa-emc/fv3atm/issues/401

## Testing

These changes were tested on the following platforms:

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [ ] wcoss_dell_p3: not run due to Venus issues
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1304893686

## Dependencies

- waiting on noaa-emc/fv3atm/pull/406

### CODE REVIEW

**Comment by climbfuji** [comment]
@BrianCurtis-NOAA @Junwang-noaa I removed the Cheyenne labels so that they won't overwrite my logs once Brian fixed the problem.

**Comment by BrianCurtis-NOAA** [comment]
Note: Cheyenne missing a file in AutoRT, issue fixed.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/749037300/20211004140010/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_367581
Test cpld_control_c192_p7 006 failed failed 
Test cpld_control_c192_p7 006 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Comment by MinsukJi-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: orion Compiler: intel Job: RT Repo location: /work/noaa/nems/emc.nemspara/autort/pr/749037300/20211004140010/ufs-weather-model Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_367581 Test cpld_control_c192_p7 006 failed failed Test cpld_control_c192_p7 006 failed in run_test failed Please make changes and add the following label back: orion-intel-RT

cpld_control_c192_p7 timed out. Will manually run cpld_control_c192_p7 and cpld_restart_c192_p7

**Comment by MinsukJi-NOAA** [comment]
@rmontuoro , can you please run regression tests on Cray and Dell?

**Comment by junwang-noaa** [comment]
Venus has a bad network switch. the RT does not get identical results from mars. We will skip dell RT for this PR.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
fv3atm was merged, new hash is 95ff1ca

**Review by climbfuji — COMMENTED** [review]
Will approve after `.gitmodules` and submodule pointer update.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
