### PR TITLE
Add traditional threading templates for global apps and append `_esmf` for templates using ESMF-managed threading.

### PR DESCRIPTION
**Pull request by aerorahul**
## Description:
This PR:
- adds traditional threading `ufs.configure` templates for global applications where missing
- appends `_esmf` to those global applications that uses ESMF managed threading 
- full RT pr-test result on hera:
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14559111/RegressionTests_hera.log)

### Commit Message:
```
* UFSWM - Allow flexibility to use traditional or ESMF-managed threading for global apps.
```

### Priority:
* Normal.

### UFSWM:
* Related to #1764 
* Will address https://github.com/NOAA-EMC/global-workflow/issues/2277

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* No Baseline Changes.

### Input data Changes:
* None

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004. Without an objection from @aerorahul , this would be a good PR to combine with @DeniseWorthen #2172

**Comment by jkbk2004** [comment]
> @jkbk2004. Without an objection from @aerorahul , this would be a good PR to combine with @DeniseWorthen #2172

Sure! We can combine those two PRs.

**Comment by aerorahul** [comment]
> > @jkbk2004. Without an objection from @aerorahul , this would be a good PR to combine with @DeniseWorthen #2172
> 
> Sure! We can combine those two PRs.

Thanks @BrianCurtis-NOAA and @jkbk2004

**Comment by DeniseWorthen** [comment]
Combined with #2172. Closing.

**Pull request closed without merging**
