### PR TITLE
Bugfix for convection (prog closure) and gravity wave drag (for stochastic perturbations) needed for GFS/GEFS prototypes

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
## Description

Solves issues: https://github.com/ufs-community/ufs-weather-model/issues/1693 and https://github.com/ufs-community/ccpp-physics/issues/6 (merged in from @mdtoyNOAA PR)

This PR updates the prognostic closure in samfdeepcnv.f and samfshalcnv.f for HR2:
1) correction (bug-fix) of convective cloud condensate passed to progsigma_calc.F90 routine
2) Update to only consider positive buoyant levels in integral (to make it general if a convection scheme can have negative buoyant levels between cloud base and cloud top)
3) Update to make the prognostic closure general to pass in q-tendency due to turbulence from any PBL scheme. 
4) Move out computation of q-tendency due to dynamics from progsigma_clac.F90 (to samfshalcnv and samfdeepcnv) because other convection schemes compute this term in a pre/post step. I will update samf* routines to use pre/post convection in the future. 

The impact of these changes on the results are small, two months verification with this update can be seen here (the PR corresponds to the experiment called prog_fix2)
https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/progcb/

PR merged in from @mdtoyNOAA:
This PR fixes a bug that occurs when running stochastic physics. As part of ccpp-physics [PR#22](https://github.com/ufs-community/ccpp-physics/pull/22), the order in which subroutines "gwdps_run" and "drag_suite_run" were called by subroutine "unified_ugwp_run" was reversed. Subroutine "drag_suite_run" is called last, but the variable "RDXZB" (the level of the dividing streamline for blocking) is initialized, which zeros out the value that was calculated in "gwdps_run". RDXZB is needed outside of the unified_ugwp subroutine by stochastic physics. This caused stochastic physics runs to crash. The bug was not caught by regression testing.

The problem has been fixed by changing the declaration of "RDXZB" from "intent(out)" to "intent(inout)" in drag_suite.F90 and drag_suite.meta, and initializing it in drag_suite.F90 only when the GSL drag suite blocking is performed, i.e., when "do_gsl_drag_ls_bl" is equal to .true.

*** This fix needs to be done for running the GEFS.v13 reanalysis and reforecasts.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 
cpld_control_gfsv17 due to updates aimed for HR2. 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on NOAA-EMC/fv3atm/pull/639
- Depends on ufs-community/ccpp-physics/pull/57
- Solves issue: https://github.com/ufs-community/ufs-weather-model/issues/1693
- Solves issue [Issue #62](https://github.com/ufs-community/ccpp-physics/issues/62). 
- Combined in https://github.com/ufs-community/ufs-weather-model/pull/1696

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@lisa-bengtsson can you sync up branch to resolve conflicts? RegressionTests_hera.intel.log is empty in the branch. It might be easier to attach in the PR (not push into the branch) if hera.intel test is done on your side.

**Comment by lisa-bengtsson** [comment]
The cpld_control_gfsv17 test fails which is unexpected, as the code I'm updating is only exercised at resolutions higher than 30km, and the cpld_control_gfsv17 test is run at C96 resolution. I'm thinking since I am also updating some input/output arguments, the difference with the baseline could be due to some optimization. However, yesterday I ran two tests of cpld_control_gfsv17 with the added -DDEBUG=ON in the compile line. One from the latest "top of develop" ufs-weather-model", and one from this PR, and the output files still differ. Could I expect differences with the baseline due to such updates in arguments passed in/out even with the debug compile flag on? I'm not sure how to proceed. Plotting the differences shows very small diffs, the files are identical after output hour 0.

**Comment by jkbk2004** [comment]
> The cpld_control_gfsv17 test fails which is unexpected, as the code I'm updating is only exercised at resolutions higher than 30km, and the cpld_control_gfsv17 test is run at C96 resolution. I'm thinking since I am also updating some input/output arguments, the difference with the baseline could be due to some optimization. However, yesterday I ran two tests of cpld_control_gfsv17 with the added -DDEBUG=ON in the compile line. One from the latest "top of develop" ufs-weather-model", and one from this PR, and the output files still differ. Could I expect differences with the baseline due to such updates in arguments passed in/out even with the debug compile flag on? I'm not sure how to proceed. Plotting the differences shows very small diffs, the files are identical after output hour 0.

@lisa-bengtsson if cpld_control_gfsv17 runs thru those subroutines with in/out update, chances are to get the results changed, right?. I think I can try sticking a few print statement in the middle to make sure.

**Comment by lisa-bengtsson** [comment]
> > The cpld_control_gfsv17 test fails which is unexpected, as the code I'm updating is only exercised at resolutions higher than 30km, and the cpld_control_gfsv17 test is run at C96 resolution. I'm thinking since I am also updating some input/output arguments, the difference with the baseline could be due to some optimization. However, yesterday I ran two tests of cpld_control_gfsv17 with the added -DDEBUG=ON in the compile line. One from the latest "top of develop" ufs-weather-model", and one from this PR, and the output files still differ. Could I expect differences with the baseline due to such updates in arguments passed in/out even with the debug compile flag on? I'm not sure how to proceed. Plotting the differences shows very small diffs, the files are identical after output hour 0.
> 
> @lisa-bengtsson if cpld_control_gfsv17 runs thru those subroutines with in/out update, chances are to get the results changed, right?. I think I can try sticking a few print statement in the middle to make sure.

Yes, cpld_control_gfsv17 does run through those subroutines, and I think you are right that chances that updated argument in/out could change results, I just don't really know how to conclude that this is the case. I was hoping it would reproduce with the DEBUG flag on, because then it would point to some optimization. If you could add some print statements that would be fantastic, Hera is unfortunately down today.

**Comment by lisa-bengtsson** [comment]
When Hera comes back up I will run through the operational regression tests.

**Comment by BrianCurtis-NOAA** [comment]
Hera is back up.

**Comment by jkbk2004** [comment]
@lisa-bengtsson test shows cpld_control_gfsv17 runs thru the code changes on progsigma_calc.f90, samfdeepcnv.f, etc.  so, baseline change makes a sense, I guess.

**Comment by lisa-bengtsson** [comment]
The OpnReqTest for cpld_control_gfsv17_hera.intel.log passes:

[OpnReqTests_cpld_control_gfsv17_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11154297/OpnReqTests_cpld_control_gfsv17_hera.intel.log)

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson test shows cpld_control_gfsv17 runs thru the code changes on progsigma_calc.f90, samfdeepcnv.f, etc. so, baseline change makes a sense, I guess.

Yes, I think you are right, since the ORT's passes I also believe it is OK. I will update the description of this PR to also create new baselines for the cpld_control_gfsv17 test.

**Comment by lisa-bengtsson** [comment]
@jkbk2004 I updated to the top of develop and then merged in the gravity wave drag PR in ccpp/physics. Please let me know the next step.

**Comment by jkbk2004** [comment]
@mdtoyNOAA #1696 is combined into this pr. Please, go ahead to confirm.  @lisa-bengtsson Can you update the PR title to reflect #1696?

**Comment by BrianCurtis-NOAA** [comment]
Has both GNU and Intel tests been run on Hera or Cheyenne?

**Comment by lisa-bengtsson** [comment]
@BrianCurtis-NOAA No, I have not tested both of them. Only intel for a subset of the RT's, as I cannot run the whole RT in less than a day.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA No, I have not tested both of them. Only intel for a subset of the RT's, as I cannot run the whole RT in less than a day.

OK. @jkbk2004 can EPIC run GNU/Intel on either Hera or Cheyenne to see if we expect the tests that fail? It's a requirement before being added to the commit queue, and I know this is a high priority.

**Comment by jkbk2004** [comment]
sure! we can follow on a full test while jenkins-ci runs.

**Comment by zach1221** [comment]
Please see jenkins-ci logs attached. ORTs have passed.
[ufs-weather-model » ort-docker-pipeline » PR-1677 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11163577/ufs-weather-model.ort-docker-pipeline.PR-1677.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/11163595/RegressionTests_hera.intel.log)

**Comment by jkbk2004** [comment]
As expected, we just need to update baseline for cpld_control_gfsv17  on hera.intel. But we need to confirm cpld_control_p8cpld_control_p8 on hera.gnu. Seems like crashing: Fatal error in PMPI_WaitFatal error in PMPI_Wait. I just resubmitted that case. @lisa-bengtsson experiment is at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_303/cpld_control_p8/err

**Comment by jkbk2004** [comment]
@zach1221 How is the cpld case running on jenkins-ci?

**Comment by zach1221** [comment]
@jkbk2004 cpld_control_nowave_noaero_p8 dbg, and rst ORTs passed on jenkins-ci. I've posted the logs above from the entire run.

**Comment by lisa-bengtsson** [comment]
> As expected, we just need to update baseline for cpld_control_gfsv17 on hera.intel. But we need to confirm cpld_control_p8cpld_control_p8 on hera.gnu. Seems like crashing: Fatal error in PMPI_WaitFatal error in PMPI_Wait. I just resubmitted that case. @lisa-bengtsson experiment is at /scratch1/NCEPDEV/stmp2/Jong.Kim/FV3_RT/rt_303/cpld_control_p8/err

Ok, thanks. I don't really know what could be different between GNU and intel, is there a GNU debug test that could give some more info?

**Comment by jkbk2004** [comment]
Resubmitted cpld_control_p8 PASS on hera.gnu. It was time out issue. I am attaching hera.gnu log

**Comment by jkbk2004** [comment]
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/11163904/RegressionTests_hera.gnu.log)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1288371135/20230405204555/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by jkbk2004** [comment]
All test are done. we can start merging process.

**Review by DusanJovic-NOAA — DISMISSED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Once the commit to update hash and .gitmodules comes in it will override Dusan's approval. What I do is wait for that final commit and then request final approvals.

**Comment by lisa-bengtsson** [comment]
Sorry @BrianCurtis-NOAA it seems that I pushed old logfiles when updating .gitmodules, can I revert that somehow? So sorry.

**Comment by BrianCurtis-NOAA** [comment]
@lisa-bengtsson Actually it looks like you were fine until you force-pushed. Unfortunately the force push reverted log files and the BL_DATE in rt.sh to an old value.

**Comment by lisa-bengtsson** [comment]
oh no, there was a conflict with rt.sh and the logfiles with my branch as they were pushed from others and I screwed up. Can I revert to the last successful commit and try to update .gitmodules again?

**Comment by jkbk2004** [comment]
@lisa-bengtsson it seems it doesn't recover fully with git revert 68aa. I think I have a backup local files ok for logs. Do you want me to push the logs again and fix with new bl_date?

**Comment by lisa-bengtsson** [comment]
@jkbk2004 yes, thank you. So sorry about the trouble.

**Comment by jkbk2004** [comment]
@lisa-bengtsson sorry I was in meeting. the fv3 pr was merged. can you update fv3 pointer? correct one is https://github.com/NOAA-EMC/fv3atm/commit/decb0b9baa89e30885d00be208aa476667fe9922

**Comment by jkbk2004** [comment]
@DeniseWorthen @BrianCurtis-NOAA sounds like all set. Please, go head for final reviews and approvals.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
Tag [EP4](https://github.com/ufs-community/ufs-weather-model/releases/tag/EP4) has been created

**Pull request merged**
