### PR TITLE
P8c: Added capability for cdmbgwd(1) to scale GSL blocking drag

### PR DESCRIPTION
**Pull request by mdtoyNOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

Made a minor change to physics/drag_suite.F90, which activates the namelist variable cdmbgwd(1) and allows it to scale the calculation of the surface stress due to the GSL blocking drag.
 
Is a change of answers expected from this PR?  Yes.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
- fixes [#874](https://github.com/NCAR/ccpp-physics/issues/874)  (in NCAR/ccpp-physics repo)

## Testing

These changes were tested on Hera with the Intel compiler.  Regression test log is available at:
/scratch1/BMC/wrfruc/mtoy/git_local/ufs-weather-model/tests/RegressionTests_hera.intel.log

Baseline test results are on Hera at:
/scratch1/BMC/wrfruc/mtoy/git_local/ufs-weather-model/REGRESSION_TEST_INTEL.2022_03_11/

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

1. https://github.com/NOAA-EMC/fv3atm/pull/502
2. https://github.com/NCAR/ccpp-physics/pull/879

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@mdtoyNOAA May I ask if your PR will change results? I saw the 4th item (results change) is checked, but the hera intel log file shows no baseline change. Which test will be impacted by your code updates? Do we need to create new baseline for this PR?

**Comment by mdtoyNOAA** [comment]
The PR has the potential to change the test results if the namelist variable cdmbgwd(1) (i.e., the first-index array value) has a value other than 1. If it is set to one in the test, then there will be no change from previous tests.

**Comment by junwang-noaa** [comment]
@mdtoyNOAA It looks to me the autort can't push to your branch. The following RT log files are ready and I put them on hera, please commit to your branch.

/scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog: 

RegressionTests_gaea.intel.log  RegressionTests_hera.intel.log
RegressionTests_hera.gnu.log    RegressionTests_wcoss_cray.log

**Comment by mdtoyNOAA** [comment]
@junwang-noaa   Done.

**Comment by junwang-noaa** [comment]
@mdtoyNOAA Please see jet log file RegressionTests_jet.intel.log  and orion log file RegressionTests_orion.intel.log
 under /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog

**Comment by junwang-noaa** [comment]
@mdtoyNOAA The dell log file RegressionTests_wcoss_dell_p3.log is now under /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog.

Please commit the dell/jet/orion log files to your branch. Thanks

**Comment by junwang-noaa** [comment]
@mdtoyNOAA The cheyenne log files RegressionTests_cheyenne.gnu.log  RegressionTests_cheyenne.intel.log are under:

/scratch1/NCEPDEV/nems/Brian.Curtis

Please commit to your branch. Thanks

**Comment by junwang-noaa** [comment]
@mdtoyNOAA @grantfirl @ChunxiZhang-NOAA All the RT passed. Once Mike commits the log files, we can start commit.

**Comment by grantfirl** [comment]
> @mdtoyNOAA @grantfirl @ChunxiZhang-NOAA All the RT passed. Once Mike commits the log files, we can start commit.

OK, I'll wait for @mdtoyNOAA to commit the log files and then push the commit button on https://github.com/NCAR/ccpp-physics/pull/879 when he's done.

**Comment by mdtoyNOAA** [comment]
@junwang-noaa @grantfirl @ChunxiZhang-NOAA   I pushed my latest commit to my fork.  This includes the new RegressionTest logs.  Let me know if there is an "Orion" one as well.  If so, please point me to it and I'll include it as well.  Otherwise, you're good to go.

**Comment by junwang-noaa** [comment]
@mdtoyNOAA We still need two log files, they are on hera at:

/scratch1/NCEPDEV/nems/Brian.Curtis/RegressionTests_cheyenne.intel.log
/scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_orion.intel.log

**Comment by mdtoyNOAA** [comment]
@junwang-noaa I don't have "read access" to /scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog/RegressionTests_orion.intel.log   Can you please change your permissions to this file so I can copy it over?
Also, will there be any more RegressionTest log files after these two?

**Comment by junwang-noaa** [comment]
@mdtoyNOAA please try now

**Comment by mdtoyNOAA** [comment]
@junwang-noaa  That worked.  Thanks.  Are there any more RegressionTest logs????

**Comment by junwang-noaa** [comment]
@mdtoyNOAA No, please commit the two log files, Then we can start committing the code

**Comment by mdtoyNOAA** [comment]
@junwang-noaa  Done.

**Comment by grantfirl** [comment]
FYI, https://github.com/NCAR/ccpp-physics/pull/879 has been merged. @mdtoyNOAA , please revert the changes to .gitmodules in your fv3atm PR branch and update the ccpp/physics submodule pointer to the latest main branch commit (https://github.com/NCAR/ccpp-physics/commit/a8e0f0c8fccad4b93a172af5bcd07d8bdff00344)

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by mdtoyNOAA** [comment]
@grantfirl    Done (maybe).  I updated .gitmodules to:
[submodule "ccpp/physics"]
  path = ccpp/physics
  url = https://github.com/NCAR/ccpp-physics
  branch = main

Is this correct?  Are there going to be more steps along the way after this one?  Also, I'm not sure if my submodules are up to date.

**Comment by grantfirl** [comment]
> @grantfirl Done (maybe). I updated .gitmodules to: [submodule "ccpp/physics"] path = ccpp/physics url = https://github.com/NCAR/ccpp-physics branch = main
> 
> Is this correct? Are there going to be more steps along the way after this one? Also, I'm not sure if my submodules are up to date.

That is correct. The only thing left to do is the following:

- cd into ccpp/physics
- git checkout main
- git pull (this should pull in the latest commit a8e...)
- cd up to FV3
- git add ccpp/physics
- git commit -m "update ccpp/physics submodule pointer"
- git push

This should be the last step in order to get the fv3atm PR merged. The same thing will need to happen in ufs-weather-model though once the fv3atm PR is merged (i.e. revert .gitmodules and update the fv3atm submodule pointer to the latest develop branch).

**Comment by junwang-noaa** [comment]
@mdtoyNOAA Now in your ufs-weather-model branch, please update fv3 submodule to point to the noaa-emc fv3atm develop branch with revision: [c02869a](https://github.com/NOAA-EMC/fv3atm/commit/c02869a6a4558e804ef5da067d3d71a0c53cc5b3)

**Review by junwang-noaa — APPROVED** [review]

**Comment by mdtoyNOAA** [comment]
@junwang-noaa  Done.

**Comment by mdtoyNOAA** [comment]
@junwang-noaa <https://github.com/junwang-noaa>    Is there an Orion log?  You only pointed to “wcoss_dell” and “jet.intel” logs.

**Pull request merged**
