### PR TITLE
Add unstructured wave grid to gfsv17 targeted tests 

### LINKED ISSUE #1860: Update cpld_control_gfsv17 to use unstructured grids
## Description
We are targeting an unstructured grid for the wave component for GFSv17, therefore we should update the cpld_control_gfsv17 test to use an unstructured grid. 

## Solution
Use unstructured grid for wave model

## Alternatives
We could keep this as a structured grid, but ideally we should move to the unstructured. 

## Related to
n/a

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
## PR Author Checklist:

- [ ] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG:    
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12857125/RegressionTests_hera.log)

- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [ ] I have filled out all sections of the template.

## Description
HR3 is moving to unstructured grids for the wave model. This PR builds off another HR3 related PR: https://github.com/ufs-community/ufs-weather-model/pull/1923 

### Associated UFSWM Issue to close
Closes https://github.com/ufs-community/ufs-weather-model/issues/1860 

### Subcomponent Pull Requests
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [ ] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:
      Added additional tests.  These tests will require a new baseline.  However, there's no anticipation of answer changes to any existing test. 

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 I ran a full set of regression tests over the weekend against a freshly created baseline.  The logs have just been posted.  I know this PR will be merged with @mdtoyNOAA PR #1923 should I make a PR to his branch now? Or should I add all the subcomponent details to his PR here?  I'm thinking it'll be easier to add this to @mdtoyNOAA's branch as the subcomponent PRs are there, but happy to do either way.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa I have removed the extra tests and have only kept 1 GFSv17 test. Please let me know if I've overlooked anything else that should be removed or you'd like additional changes

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA May I ask which test will be used in the GFSv17 HR3,  cpld_control_gfsv17 or cpld_control_gfsv17_ugwpv1_pdlib? If cpld_control_gfsv17_ugwpv1_pdlib is the one, can we rename cpld_control_gfsv17_ugwpv1_pdlib to cpld_control-gfsv17? Also is there any other use of cpld_control_gfsv17 while cpld_control_gfsv17_ugwpv1_pdlib is used in future HR experiments? I am asking because the IAU test is currently based on cpld_control_gfsv17, I hope these tests are all based on latest GFSv17 configuration. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
Hi @junwang-noaa we'll be using cpld_control_gfsv17_ugwpv1_pdlib 

I can rename this test as desired and update the IAU test accordingly.  Should have it done by this afternoon so hopefully this will not delay this PR in the queue.

**Comment by lisa-bengtsson** [comment]
could the cpld benchmark test be updated to use this prototype? It is currently based on P8 and we don't have a high resolution RT for the later prototypes.

**Comment by JessicaMeixner-NOAA** [comment]
My plan is to only update the GFSv17 tests, particularly as the wave updates are only valid for GFS not GEFS.

**Comment by junwang-noaa** [comment]
It looks to me the FV3 is pointing to a user's branch, would you please add the FV3 PR/CCPP PR dependency info? I'd suggest to confirm all the related PRs are reviewed and tested in order to speed up the code commit. My understanding is that code managers are working on Dom's PR today.

**Comment by JessicaMeixner-NOAA** [comment]
This PR builds on #1923 where  there is an update to FV3.  The updates here will be merged to that PR. That PR has all of the dependency information.

**Comment by junwang-noaa** [comment]
I'd appreciate you close this PR and move discussions to PR#1923. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
Happy to move the discussion to PR #1923,  I thought this PR would only be closed when PR#1923 was merged.  Apologies for not understanding the current code management practices, I'll close this now.  @mdtoyNOAA I'll have PR to your PR branch later today with the requested updates from this thread.

**Pull request closed without merging**
