### PR TITLE
Merge latest RUC LSM into community develop

### PR DESCRIPTION
**Pull request by tanyasmirnova**
## Description
This PR merges changes from RRFS_dev to UFS community develop related to:

1. Introducing new variables for fractional vegetation and soil data and and read this data in FV3GFS_io.F90.
2. Updated snow model in RUC LSM
3. Changes in the output related to LSM-produced variables.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- NOAA-EMC/fv3atm/pull/633
- ufs-community/ccpp-physics/pull/49
- https://github.com/NOAA-EMC/CMEPS/pull/84

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
I see you put `Draft:` into the title. Thank you for that. If you want to make it a draft in GitHub, you can convert it to draft by clicking the link in the Reviewers section on the right side, you should see something like: `Still in progress? Convert to draft`. Click `Convert to draft`.

**Comment by grantfirl** [comment]
@tanyasmirnova Have these changes been tested yet? If not, do you need some assistance?

**Comment by tanyasmirnova** [comment]
@grantfirl Thank you for your question. I am still addressing your comments and the code is still changing. However @RatkoVasic-NOAA started performing a regression tests for my PR. We had a show stopper with compiling -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_sfcocn -DCMEPS_AOFLUX=ON. It appears that CMEPS_AOFLUX has its own meta file that needs to be updated. This is where we are right now.

**Comment by uturuncoglu** [comment]
@tanyasmirnova CMEPS is also defined as CCPP host model for calculating atmosphere-ocean fluxes on exchange grid. So, it has own data structures and metadata file. Let me know if you need help.

**Comment by tanyasmirnova** [comment]
@uturuncoglu I am adding some variables to MED_typedefs.meta. I have a questions: what section should I put xlat_d, xlon_d. They are defined under Grid property in GFS_typedefs.meta:
    allocate (Grid%xlat_d (IM))
    allocate (Grid%xlon_d (IM))

**Comment by tanyasmirnova** [comment]
@uturuncoglu I think I figured it out.

**Comment by tanyasmirnova** [comment]
@grantfirl @uturuncoglu When I added missing variables to CMEPS metadata, I got the following error in compilation with CMEPS:Compiling CMEPS with CCPP support.
Calling CCPP code generator (ccpp_prebuild.py) for suites --suites=FV3_sfc_ocean ...
-- CCPP prebuild step completed successfully
-- Configuring done
CMake Error at MOM6-interface/CMakeLists.txt:28 (add_library):
  Cannot find source file:

    MOM6/src/equation_of_state/TEOS10/gsw_chem_potential_water_t_exact.f90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CICE-interface/CMakeLists.txt:71 (add_library):
  Cannot find source file:

    CICE/icepack/columnphysics/icepack_aerosol.F90

The log file is in /scratch1/BMC/gsd-fv3-dev/smirnova/ccpp_fv3/ufs_community_6mar23/tests/comp_CMEPS.log

Could you suggest us how to fix this error?

**Comment by uturuncoglu** [comment]
@uturuncoglu I suggest to have clean build by changing "${BUILD_JOBS:-4}" parameter in ./build.sh (in the root model directory) and make it run with 1 thread like "${BUILD_JOBS:-1}". So, this will allow you to compile model component sequentially and make the error more apparent. Form your error output, it seems that the problem is on other components. BTW, I could only access to Orion and Cheyenne. So, if you want me to look at we need to compile on those platforms.

**Comment by RatkoVasic-NOAA** [comment]
@uturuncoglu Ufuk, I updated Tanya's branch so you can try to compile on Orion or Cheyenne. Here is the procedure:
```
git clone -b ufsdev_ruclsm https://github.com/tanyasmirnova/ufs-weather-model.git
cd ufs-weather-model
git submodule update --init --recursive

ls -l CMEPS-interface/CMEPS/ufs/ccpp/data/  <---- changes are here

cd tests
compile.sh @machine.compiler@ "-DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_sfcocn -DCMEPS_AOFLUX=ON"
```

**Comment by grantfirl** [comment]
@tanyasmirnova @RatkoVasic-NOAA @uturuncoglu @DeniseWorthen  It was pointed out in the UFS code management meeting that we'll need a PR in CMEPS for the changes there that should be linked to this PR.

`ufsdev_ruclsm->emc/develop`

**Comment by tanyasmirnova** [comment]
Thank you very much, Everybody, for your help. Ratko, could you please make a PR in CMEPS?

**Comment by RatkoVasic-NOAA** [comment]
> Thank you very much, Everybody, for your help. Ratko, could you please make a PR in CMEPS?

I can do the PR, but compilation is still failing.

**Comment by uturuncoglu** [comment]
@tanyasmirnova @RatkoVasic-NOAA I ll look at this today. I am out of office now.

**Comment by RatkoVasic-NOAA** [comment]
> @tanyasmirnova @RatkoVasic-NOAA @uturuncoglu @DeniseWorthen It was pointed out in the UFS code management meeting that we'll need a PR in CMEPS for the changes there that should be linked to this PR.
> 
> `ufsdev_ruclsm->emc/develop`

PR https://github.com/NOAA-EMC/CMEPS/pull/84 is in.

**Comment by tanyasmirnova** [comment]
@RatkoVasic-NOAA @uturuncoglu @SamuelTrahanNOAA Sam is on board to help with testing of this PR. The SD with CMEPS is still not compiling.

**Comment by uturuncoglu** [comment]
@tanyasmirnova @RatkoVasic-NOAA I think I fixed the issue. The model was giving error like following,

```
/glade/scratch/turuncu/ufs-weather-model/tests/build_fv3_test/CMEPS-interface/physics/ccpp_static_api_med.F90(42): error #6580: Name in only-list does not exist or is not accessible.   [CON_KARMAN]
   use MED_typedefs, only: con_karman
---------------------------^
/glade/scratch/turuncu/ufs-weather-model/tests/build_fv3_test/CMEPS-interface/physics/ccpp_static_api_med.F90(198): error #6404: This name does not have a type, and must have an explicit type.   [CON_KARMAN]
                  con_rd=con_rd,con_rocp=con_rocp,con_karman=con_karman)
-------------------------------------------------------------^
```

and the `karman` constant is defined as following in the `FV3/ccpp/physics/physics/physcons.F90`

```
real(kind=kind_phys),parameter:: karman     =0.4_kind_phys                       !< Von Karman constant
```

so, it could not find `con_karman` since it is not in the `physcons` and it is not included with use statement. It think you need to do following change in the `CMEPS/ufs/ccpp/data/MED_typedefs.F90`. 

```
+++ b/ufs/ccpp/data/MED_typedefs.F90
@@ -7,6 +7,7 @@ module MED_typedefs
   use physcons, only: con_hvap, con_cp, con_rd, con_eps, con_rocp
   use physcons, only: con_epsm1, con_fvirt, con_g 
   use physcons, only: con_tice
+  use physcons, only: con_karman => karman
 
   implicit none
```
This compiles without any issue in my side.

**Comment by SamuelTrahanNOAA** [comment]
Actually, @RatkoVasic-NOAA already fixed it by changing the name to `karman` in the MED_typedefs.meta and using the `karman` from physcons. It compiles for both @tanyasmirnova and I now.

**Comment by uturuncoglu** [comment]
@SamuelTrahanNOAA Thanks. I did not aware of it. Anyway, double fix is always better then the single one.

**Comment by RatkoVasic-NOAA** [comment]
> Actually, @RatkoVasic-NOAA already fixed it by changing the name to `karman` in the MED_typedefs.meta and using the `karman` from physcons. It compiles for both @tanyasmirnova and I now.

That was @tanyasmirnova change, I just submitted it :-)

**Comment by SamuelTrahanNOAA** [comment]
Tanya has been diligintly working on getting the regression tests to pass, but we're left with these six that change results for unknown reasons:

-    hafs_regional_specified_moving_1nest_atm
-    hafs_regional_storm_following_1nest_atm
-    hafs_regional_storm_following_1nest_atm_ocn
-    hafs_global_storm_following_1nest_atm
-    hafs_regional_storm_following_1nest_atm_ocn_debug
-    hafs_regional_storm_following_1nest_atm_ocn_wav

**Comment by SamuelTrahanNOAA** [comment]
I have independently tested the restart bug fix, and the only test whose value changes is rrfs_smoke_conus13km_hrrr_warm. That means the hafs test changes can't be blamed on the restart fix.

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA sounds a bit more time is needed to figure out those hafs cases, right?

**Comment by SamuelTrahanNOAA** [comment]
I think the HAFS cases are due to bug fixes like correcting metadata and real kinds, but we're still trying to pinpoint exactly what change caused it. There are now only five unaccounted for:

 - hafs_regional_specified_moving_1nest_atm
 - hafs_regional_storm_following_1nest_atm
 - hafs_regional_storm_following_1nest_atm_ocn
 - hafs_global_storm_following_1nest_atm
 - hafs_regional_storm_following_1nest_atm_ocn_wav

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA no need to rush. do you think we can let #1672 (easy case with no baseline change and just CICE update) go first today?

**Comment by SamuelTrahanNOAA** [comment]
> No need to rush. do you think we can let https://github.com/ufs-community/ufs-weather-model/pull/1672 (easy case with no baseline change and just CICE update) go first today?

There is a need to rush, since this has to be merged by the end of the week. If you think there's enough time to merge both, then yes, go ahead.

**Comment by jkbk2004** [comment]
> > No need to rush. do you think we can let #1672 (easy case with no baseline change and just CICE update) go first today?
> 
> There is a need to rush, since this has to be merged by the end of the week. If you think there's enough time to merge both, then yes, go ahead.

Sure! we should be ok with timeline.

**Comment by SamuelTrahanNOAA** [comment]
I isolated the HAFS differences down to these:

1. Change from `real` to `real(kind_phys)` in namelist_soilveg_ruc.F90 and set_soilveg_ruc.F90. HAFS uses these variables even though it is not running RUC LSM. Changing the HAFS results is expected here.
2. Move four fields from CCPP_typedefs to GFS_typedefs so they can be output. They're now zeroed every FHZERO  hours. This changes the results of the moving nest only. This may be changing due to unrelated issues in the moving nest implementation.

I'd like to hear from the HAFS developers on this: @BinLiu-NOAA @BijuThomas-NOAA

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA I forgot to remove mosaic_lu and mosaic_soil from namelist_soilveg_ruc.F90 and set_soilveg_ruc.F90 when I moved them to namelist options in GFS_typedefs.F90.
The diffs will be:
diff --git a/physics/namelist_soilveg_ruc.F90 b/physics/namelist_soilveg_ruc.F90
index d71d2ebf..d93dc5c6 100644
--- a/physics/namelist_soilveg_ruc.F90
+++ b/physics/namelist_soilveg_ruc.F90
@@ -45,7 +45,6 @@
       INTEGER DEFINED_VEG
       INTEGER DEFINED_SOIL
       INTEGER DEFINED_SLOPE
-      INTEGER MOSAIC_LU
 !> -- soils
       real(kind_phys) BB(MAX_SOILTYP)
       real(kind_phys) DRYSMC(MAX_SOILTYP)
@@ -63,5 +62,4 @@
       real(kind_phys) SATDKnoah(MAX_SOILTYP)
       real(kind_phys) SATPSInoah(MAX_SOILTYP)
       real(kind_phys) MAXSMCnoah(MAX_SOILTYP)
-      INTEGER MOSAIC_SOIL
       end module namelist_soilveg_ruc
diff --git a/physics/set_soilveg_ruc.F90 b/physics/set_soilveg_ruc.F90
index f04a4964..7c4f0ffd 100644
--- a/physics/set_soilveg_ruc.F90
+++ b/physics/set_soilveg_ruc.F90
@@ -36,8 +36,7 @@
      &  RSMAX_DATA, BARE, GLACIER, NATURAL, CROP, URBAN,                &
      &  DEFINED_VEG, DEFINED_SOIL, DEFINED_SLOPE,                       &
      &  BB, DRYSMC, HC, MAXSMC, REFSMC, SATPSI, SATDK, SATDW,           &
-     &  WLTSMC, QTZ, mosaic_soil, mosaic_lu,                            &
-     &  REFSMCnoah, WLTSMCnoah, MAXSMCnoah
+     &  WLTSMC, QTZ, REFSMCnoah, WLTSMCnoah, MAXSMCnoah
 
       ! Initialize error-handling
       errflg = 0
@@ -235,9 +234,6 @@
       endif
 !  end if veg table
 
-! - set mosaic_lu=1 when info for fractional landuse is available
-      mosaic_lu = 0
-
.....       topt_data =298.0
       cmcmax_data =0.2e-3
       cfactr_data =0.5
@@ -440,9 +436,6 @@
            endif
          END DO
 
-! - set mosaic_soil=1 when info for fractional landuse is available
-      mosaic_soil = 0
-
 ! PT 5/18/2015 - changed to FALSE to match atm_namelist setting
 ! PT LPARAM is not used anywhere
       LPARAM =.FALSE.
(END)

**Comment by SamuelTrahanNOAA** [comment]
@tanyasmirnova - github has made a complete wreck of your post. Could you please push the changes instead?

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA One more change has to be done in namelist_soilveg_ruc.F90 and set_soilveg_ruc.F90:
Screenshot 2023-03-28 at 3 36 10 PM
Screenshot 2023-03-28 at 3 38 52 PM

**Comment by tanyasmirnova** [comment]
Some variables in /scratch1/NCEPDEV/stmp2/Samuel.Trahan/FV3_RT/rt_143256/hafs_regional_specified_moving_1nest_atm look very noisy. For example:
Screenshot 2023-03-28 at 3 52 23 PM
Screenshot 2023-03-28 at 3 51 48 PM

**Comment by SamuelTrahanNOAA** [comment]
The baseline also has this problem. Here are plots of this:

```
ncview /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20230324/INTEL/hafs_regional_specified_moving_1nest_atm/sfc.nest02.f006.nc
```

transpiration-baseline
pcloud

**Comment by SamuelTrahanNOAA** [comment]
We can proceed with this pull request. It does *not* cause the HAFS nest motion issue; that issue is already present in the baseline.

**Comment by SamuelTrahanNOAA** [comment]
My previous comment had an error. The four fields that are moved are still instantaneous. All that is changed is where they are stored.

**Comment by BinLiu-NOAA** [comment]
In a separate email thread discussion among @SamuelTrahanNOAA, @tanyasmirnova, @wramstrom and @BinLiu-NOAA, we confirm that the temporal statistical (average, minimum, maximum, accumulate, etc.) variables are known to not function properly for the moving nest domain. This is currently known and expected. Thanks!

**Comment by grantfirl** [comment]
FYI, the RT logs for the MYNN SFC PR before combining can be found here: https://github.com/ufs-community/ccpp-physics/pull/58

**Comment by zach1221** [comment]
@SamuelTrahanNOAA do you still want to combine #1660 and #1678 into this PR?

**Comment by SamuelTrahanNOAA** [comment]
> do you still want to combine https://github.com/ufs-community/ufs-weather-model/pull/1660 and https://github.com/ufs-community/ufs-weather-model/pull/1678 into this PR?

Both #1660 and #1678 are in here, plus one bug fix to #1660 that isn't in that PR. (Missing `num` in a `!$omp` clause.) I just updated this to the top of develop.

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - Please proceed with testing. I am confident that the combination of #1646 + #1660 + #1678 works. I have not tested them with the top of today's develop yet. That is unlikely to break this PR because today's develop only changed CICE. Nothing in this PR involves CICE.

**Comment by zach1221** [comment]
@SamuelTrahanNOAA I see the new input data box is checked. If there is new input data we will need to re-sync it first, before testing. Can you tell us where the new data is?

**Comment by SamuelTrahanNOAA** [comment]
> I see the new input data box is checked

@tanyasmirnova @joeolson42 - Is there new input data for these PRs?

I'm 99% certain that the "new input data" box was checked by accident. Can you confirm this?

**Comment by SamuelTrahanNOAA** [comment]
Both #1678 and #1660 say they do *not* need new input data. That means we just need a confirmation from @tanyasmirnova that this PR also does not need new input data.

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA @joeolson42 Actually, the change in FV3GFS_io.F90 is reading in extra variables that were added to the oro* files: fractional soil and fractional vegetation. This data is optional and the code should work even when it is not available (similar to lake fraction and lake depth).

**Comment by SamuelTrahanNOAA** [comment]
We've run the tests (several times) without that new data. We don't even know if the regression tests will work with the new data. Are you okay with merging this PR without the new data?

**Comment by zach1221** [comment]
@BrianCurtis-NOAA @DeniseWorthen fyi we're going to start testing this PR next.

**Comment by SamuelTrahanNOAA** [comment]
@tanyasmirnova - Instead of delaying this PR, I suggest we put the new data in a later PR. We're planning to make a new 13km RRFS test case with correct lake data. When we do that, we'll add the fractional information to that test. For now, we'll leave the fractional data absent.

How does that sound?

**Comment by tanyasmirnova** [comment]
Yes, I am ok with merging this PR  without a new data. This data is optional, and so far it is not used. But the code is in place to read it when it is available.

**Comment by zach1221** [comment]
Ok, I'll mark the "No changes are expected to input data." box.

**Comment by tanyasmirnova** [comment]
Sounds good. We can make the PR for additional data later.

**Comment by zach1221** [comment]
Jenkins-ci logs attached. ORTs against this PR have passed.
[ufs-weather-model » ort-docker-pipeline » PR-1646 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11106235/ufs-weather-model.ort-docker-pipeline.PR-1646.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1268571848/20230329183016/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by zach1221** [comment]
Disregard the Orion error above, I think it's jenkins pipeline related.

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1268571848/20230329230010/ufs-weather-model
[BL] Error: Test cpld_control_p8 033 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1268571848/20230329172210/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_32224
Test hafs_regional_atm 082 failed in run_test failed 
Test hafs_global_multiple_4nests_atm 090 failed in run_test failed 
Test hafs_regional_datm_cdeps 099 failed in run_test failed 
Test control_p8_atmlnd_sbs 114 failed in run_test failed 
Test compile_008 failed in run_compile failed 
Test compile_022 failed in run_compile failed 
Test compile_030 failed in run_compile failed 
Test compile_031 failed in run_compile failed 
Test compile_033 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by support-epic** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1268571848/20230329173710/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_2743
Test cpld_control_c192_p8 005 failed in run_test failed 
Test regional_debug 062 failed in run_test failed 
Test hrrr_control_debug 064 failed in run_test failed 
Test rap_cires_ugwp_debug 066 failed in run_test failed 
Test rap_flake_debug 068 failed in run_test failed 
Test rap_progcld_thompson_debug 069 failed in run_test failed 
Test regional_spp_sppt_shum_skeb_dyn32_phy32 075 failed in run_test failed 
Test rap_control_dyn32_phy32 076 failed in run_test failed 
Test hrrr_control_dyn32_phy32 077 failed in run_test failed 
Test hafs_regional_storm_following_1nest_atm_ocn_debug 095 failed in run_test failed 
Test datm_cdeps_lnd_gswp3 113 failed in run_test failed 
Test compile_008 failed in run_compile failed 
Test compile_013 failed in run_compile failed 
Test compile_017 failed in run_compile failed 
Test compile_022 failed in run_compile failed 
Test compile_023 failed in run_compile failed 
Test compile_024 failed in run_compile failed 
Test compile_026 failed in run_compile failed 
Test compile_029 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by SamuelTrahanNOAA** [comment]
I checked some of these failed jobs on Cheyenne, and they succeeded eventually. It looks like some were submitted more than once. Not sure what's going on.

**Comment by zach1221** [comment]
It looks like there is issues with the pipeline. Checking now to see if any of the baselines completed. Hera.gnu was mostly done, and cpld_control_p8 was timing out. I ran that one manually.

**Comment by zach1221** [comment]
Hera gnu/intel and orion baselines are complete. The others are work in progress. I'm reporting jenkins issue as well.

**Comment by BrianCurtis-NOAA** [comment]
Cactus/Acorn testing was started around 9AM. Part of #1679

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/epic-ps/jongkim/autort/pr/1268571848/20230330090012/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by zach1221** [comment]
@tanyasmirnova or @SamuelTrahanNOAA could you try to add me as a contributor to this PR? I'm trying to push logs to it and I'm unable, due to permissions I think.

**Comment by BrianCurtis-NOAA** [comment]
> @tanyasmirnova or @SamuelTrahanNOAA could you try to add me as a contributor to this PR? I'm trying to push logs to it and I'm unable, due to permissions I think.

This can happen, yes, if you are not a contributor to their fork of UFSWM. They will need to add you on their end.

**Comment by grantfirl** [comment]
@tanyasmirnova Since this is your branch, you will need to do this. Go to your fork of ufs-weather-model on GitHub. Click on Settings -> Collaborators -> Add people and search/add @zach1221

**Comment by tanyasmirnova** [comment]
@zach1221 Hello, I added you to ufs-weather-model. Do I need to add you to FV3, ccpp... as well?

**Comment by grantfirl** [comment]
> @zach1221 Hello, I added you to ufs-weather-model. Do I need to add you to FV3, ccpp... as well?

@tanyasmirnova It's just ufs-weather-model due to the need to push RT logs to your PR branch, so no.

**Comment by zach1221** [comment]
Thank you, @tanyasmirnova! I've received the invitation.

**Comment by BrianCurtis-NOAA** [comment]
Acorn and WCOSS2 RT Logs on Hera at: /scratch1/NCEPDEV/nems/Brian.Curtis can you retrieve those @zach1221

**Comment by zach1221** [comment]
@BrianCurtis-NOAA , yes thank you. I'll get them

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1268571848/20230329233008/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20230329/INTEL
Please make changes and add the following label back: gaea-intel-BL

**Comment by zach1221** [comment]
Testing on jet/gaea has been quite slow. Pushing to have those finished by 2pm, then we can move forward with merging process.

**Comment by SamuelTrahanNOAA** [comment]
> Testing on jet/gaea has been quite slow. Pushing to have those finished by 2pm, then we can move forward with merging process.

I have access to some Jet projects that have a very high priority (FairShare rating) so if you find it impossible to run on Jet, I can do that for you.

**Comment by zach1221** [comment]
Thanks, @SamuelTrahanNOAA . I think Jet is almost finished, so I dont want to ask you to do that quite yet.

**Comment by zach1221** [comment]
Ok, tests are done, we should be able to move forward with this PR. I think we need to have reviews/approval completed in the sub-prs linked [#49](https://github.com/ufs-community/ccpp-physics/pull/49)  and [#633](https://github.com/NOAA-EMC/fv3atm/pull/633). I can follow up in those PRs separately.

**Comment by grantfirl** [comment]
> Ok, tests are done, we should be able to move forward with this PR. I think we need to have reviews/approval completed in the sub-prs linked [#49](https://github.com/ufs-community/ccpp-physics/pull/49) and [#633](https://github.com/NOAA-EMC/fv3atm/pull/633). I can follow up in those PRs separately.

[#49](https://github.com/ufs-community/ccpp-physics/pull/49) has approval and is ready to merge.

**Comment by zach1221** [comment]
Thanks, @grantfirl . Feel free to merge ccpp

**Comment by SamuelTrahanNOAA** [comment]
The ccpp has been merged and we're waiting on fv3atm

**Comment by jkbk2004** [comment]
@SamuelTrahanNOAA @tanyasmirnova fv3 pr was merged. Go ahead to update submodule pointer and revert change in gitmodules.

**Comment by SamuelTrahanNOAA** [comment]
The CMEPS PR still needs to be merged.

https://github.com/NOAA-EMC/CMEPS/pull/84

**Comment by SamuelTrahanNOAA** [comment]
I did update the FV3 submodule, but until the CMEPS PR is merged, I cannot update that one.

**Comment by DeniseWorthen** [comment]
Sorry @SamuelTrahanNOAA Someone marked that the subcomponent PRs were approved, but CMEPS has not been. Hopefully Jun or Brian can quickly approve.

**Comment by DeniseWorthen** [comment]
CMEPS is merged hash [91bcb84](https://github.com/NOAA-EMC/CMEPS/commit/91bcb847e9e5cac48f1ed3676cfcb1764c45b51d)

**Comment by SamuelTrahanNOAA** [comment]
The .gitmodules is reverted, and the FV3 & CMEPS point to their authoritative branches. You can merge this now.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
