### PR TITLE
MYNN SFC OpenACC Acceleration

### PR DESCRIPTION
**Pull request by grantfirl**
## PR Author Checklist:

- [X] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [X] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12589777/RegressionTests_hera.log)

- [X] I have added the list of all failed regression tests to "Anticipated changes" section.
- [X] I have filled out all sections of the template.

## Description
See https://github.com/ufs-community/ccpp-physics/pull/97 for a complete description.

Overview from the developer:

With very minimal changes to the original code of the scheme, the MYNN surface scheme has been enhanced with OpenACC statements which introduce the capability for offloading computational execution to OpenACC-supported accelerator devices (e.g. Nvidia GPUs). Since the scheme operates by looping multiple times over independent vertical columns, the overall computational strategy maps well to GPU hardware where multiple iterations of each loop can be run in parallel with SIMD methods. Data movement has been optimized to ensure data transfers from host memory to device memory are limited as data movement is a significant source of latency when performing offloading to accelerator devices. Performance increases on a GPU ranged from a 3.3x slowdown to a 41.9x speedup versus CPU execution (See the Performance section for more information).

### Subcomponent Pull Requests

https://github.com/NOAA-EMC/fv3atm/pull/693
https://github.com/ufs-community/ccpp-physics/pull/97

### Blocking Dependencies

None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [X] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [X] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [X] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [X] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by grantfirl** [comment]
I'm rerunning RTs on Hera since the first set ran into memory issues apparently.

**Comment by zach1221** [comment]
> I'm rerunning RTs on Hera since the first set ran into memory issues apparently.

Sounds good @grantfirl . Keep us posted. Once those Hera logs are ready I think we can start working this PR.

**Comment by grantfirl** [comment]
> > I'm rerunning RTs on Hera since the first set ran into memory issues apparently.
> 
> Sounds good @grantfirl . Keep us posted. Once those Hera logs are ready I think we can start working this PR.

@zach1221 OK, RTs on Hera finished successfully, and I attached the log in the description.

**Comment by zach1221** [comment]
ORTs passed. Jenkins-ci logs attached.
[Jenkins-ci 1891 ORTs.pdf](https://github.com/ufs-community/ufs-weather-model/files/12591659/Jenkins-ci.1891.ORTs.pdf)

**Comment by jkbk2004** [comment]
Jet system issue. System is very crowded. Skip jet!

**Comment by zach1221** [comment]
> Jet system issue. System is very crowded. Skip jet!

Sure. I should have the hera logs ready soon.

**Comment by jkbk2004** [comment]
Jet queue is not moving even today. So confirm to skip jet. @grantfirl we can start merging process. @zach1221 FYI

**Comment by zach1221** [comment]
> Jet queue is not moving even today. So confirm to skip jet. @grantfirl we can start merging process. @zach1221 FYI

I've followed up with Grant on ccpp-physics pr #[97](https://github.com/ufs-community/ccpp-physics/pull/97)  .

**Comment by jkbk2004** [comment]
> > Jet queue is not moving even today. So confirm to skip jet. @grantfirl we can start merging process. @zach1221 FYI
> 
> I've followed up with Grant on ccpp-physics pr #[97](https://github.com/ufs-community/ccpp-physics/pull/97) .

@zach1221 Thanks!

**Comment by grantfirl** [comment]
The ccpp-physics PR is merged and the fv3atm PR is updated and ready for merge. @zach1221 @jkbk2004

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
