### PR TITLE
Gaea software stack location update after C3 and C4 partition upgrades

### PR DESCRIPTION
**Pull request by natalie-perlin**
## Description
New software stack on Gaea following C3 and C4 partitions upgrade:
**/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-classic-2022.0.2/modulefiles/stack**
All regression tests passed successfully.

Files changed:
`./modulefiles/ufs_gaea.intel.lua`
`./tests/RegressionTests_gaea.intel.log`

### Top of commit queue on: TBD

[RegressionTests_gaea.intel.log_all.txt](https://github.com/NOAA-EPIC/ufs-weather-model/files/11517473/RegressionTests_gaea.intel.log_all.txt)

### Input data additions/changes
- [x] No changes are expected to input data.

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Software stack for Gaea C3 and C4 partitions is fully functional and tested

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [x] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
[RegressionTests_gaea.intel.log_all.txt](https://github.com/NOAA-EPIC/ufs-weather-model/files/11517491/RegressionTests_gaea.intel.log_all.txt)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@natalie-perlin We are about to commit #1752. We can combine this pr to #1752. Please, go ahead to sync up your branch. It will be great if you can create a direct pr to #1752. Or I will go ahead to directly apply this gaea lua file to #1752. All credit will be deserved.

**Comment by natalie-perlin** [comment]
@jkbk2004 - Great! Glad to hear about the progress. I'll try to make a PR into #1752 .

**Comment by jkbk2004** [comment]
> @jkbk2004 - Great! Glad to hear about the progress. I'll try to make a PR into #1752 .

cool! git will allow to create a direct pr to fork branch: https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/updcmeps If you see an issue, let us know. Single file change. We can take an easy way.

**Comment by DeniseWorthen** [comment]
@natalie-perlin Please just update your branch to the latest develop. I can then just add your remote and merge. Thanks.

**Comment by DeniseWorthen** [comment]
@jkbk2004 Please refrain from making a push directly to my branch.

**Comment by jkbk2004** [comment]
> @jkbk2004 Please refrain from making a push directly to my branch.

Sure!

**Comment by natalie-perlin** [comment]
@DeniseWorthen @jkbk2004 -
Updating my branch to the recent develop requires resolving conflicts in tests/logs/RegressionTests_gaea.log. There are too many differences (new baseline for Gaea, 320 differences) to resolve by hand.  Is there a better way to force using HEAD version and quickly resolve all the conflicts ? As in 
```
<<<<<<< HEAD:tests/RegressionTests_gaea.intel.log
  0: The total amount of wall time                        = 304.194119
  0: The maximum resident set size (KB)                   = 1488356
=======
  0: The total amount of wall time                        = 303.511933
  0: The maximum resident set size (KB)                   = 1503728
>>>>>>> develop:tests/logs/RegressionTests_gaea.log

```

**Comment by jkbk2004** [comment]
> @DeniseWorthen @natalie-perlin - Updating my branch to the recent develop requires resolving conflicts in tests/logs/RegressionTests_gaea.log. There are too many differences (new baseline for Gaea, 320 differences) to resolve by hand. Is there a better way to force using HEAD version and quickly resolve all the conflicts ? As in
> 
> ```
> <<<<<<< HEAD:tests/RegressionTests_gaea.intel.log
>   0: The total amount of wall time                        = 304.194119
>   0: The maximum resident set size (KB)                   = 1488356
> =======
>   0: The total amount of wall time                        = 303.511933
>   0: The maximum resident set size (KB)                   = 1503728
> >>>>>>> develop:tests/logs/RegressionTests_gaea.log
> ```

As you attached log files, we are ok to drop your log. See if you can use git checkout --theirs

**Comment by natalie-perlin** [comment]
@jkbk2004 - thank you for the tip, done!
The branch gaea-update in my repository is successfully merged with the updates from develop branch.

**Comment by natalie-perlin** [comment]
@jkbk2004 @DeniseWorthen -
is there anything else to do besides updating my branch? Do I still make a PR into https://github.com/ufs-community/ufs-weather-model/pull/1752 , i.e. https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/updcmeps

**Comment by DeniseWorthen** [comment]
@natalie-perlin I've added your changes to PR #1752. You do not need to make a PR, but please check that the combined PR contains your expected changes. Thanks.

**Comment by natalie-perlin** [comment]
@DeniseWorthen - another way to combine these could be if I'd open a pull request/ PR into your branch (not a direct pull).

**Comment by DeniseWorthen** [comment]
@natalie-perlin I'm not sure what the issue is. I've pulled your branch into the combined PR #1752. I did that after you updated your branch to develop (I added your fork as a remote and merged it into my PR branch.) You do not need to do anything at this point, other than make sure that your changes are correct in #1752

**Comment by natalie-perlin** [comment]
@DeniseWorthen - thank you again! I was not aware of the other ways on how to combine these!

**Comment by zach1221** [comment]
@natalie-perlin combined PR#[1752](https://github.com/ufs-community/ufs-weather-model/pull/1752) has been merged into community develop. I will go ahead and close this PR.

**Pull request closed without merging**
