### PR TITLE
Fix wave init

### LINKED ISSUE #870: Wave model cannot restart if mediator flag is set to startup
**Describe the bug**
The wave model cannot start if wave information is not in the coupler.  The solution should be to set
start_type = startup in the nems.configure file, but when doing this, WW3 gets the wrong model time.

**To Reproduce**
set KEEP to true in rt.sh
Run the cpld_control_p8 and cpld_restart_p8 tests.
In the cpld_restart_p8 directory change
start_type = continue to
start_type = initial
and model will have an error with a time mismatch.

**Expected behavior**

The wave model should be initialing with the current time, not the forecast start time.

### LINKED ISSUE #1546: Wave model cannot restart if mediator flag is set to startup
## Description
Full description is in https://github.com/NOAA-EMC/WW3/issues/870

### To Reproduce:
set KEEP to true in rt.sh
Run the cpld_control_p8 and cpld_restart_p8 tests.
In the cpld_restart_p8 directory change
start_type = continue to
start_type = initial
and model will have an error with a time mismatch.

## Additional context
- needed for Ensemble Prototype 4 experiments.

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

### PR DESCRIPTION
**Pull request by pjpegion**
## Description

Fixes the logic for a restart when there are not wave in the coupler and start_type needs to be set to initial. This is needed for EP4 which will use warm starts from the replay, but the wave initial conditions are not part of the replay, so they are not in the mediator.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

cpld_control_p8 and cpld_restart_p8

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [x] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- fixes #1546 
- fixes noaa-emc/ww3/issues/870
- Depends on noaa-emc/WW3/pull/871

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@pjpegion I'm not sure I understand by "not wave in the coupler" Do you mean that the wave fields are not in the coupler restart file?

**Comment by pjpegion** [comment]
yes, it should have said waves are not in the mediator/coupler restart files.

**Comment by DeniseWorthen** [comment]
Thanks for the clarification. You said you tested w/ cpld_control and cpld_restart. But if the issue is that you don't have the wave ICs from the replay, wouldn't the test have been to run w/o waves for the control case and then try to restart with that but with waves included?

**Comment by pjpegion** [comment]
@DeniseWorthen I will do that test to confirm it works in that situation

**Comment by pjpegion** [comment]
@DeniseWorthen I did the following tests which all worked
1.  run cpld_control_p8 without waves, dropping restarts at FH012 and used those restarts to initialized the 2 tests below
2. run cpld_restart_p8 with waves model and wave restart from a different run
3. run cpld_restart_p8 with wave, but no restart and wave model started at rest.

**Comment by BrianCurtis-NOAA** [comment]
I've brought in the new PR template and copied over the appropriate text. Please fix what I may have missed. This is still waiting on WW3 review of that code, and then you will need to run the full RT suite with an up-to-date (as possible) branch before this makes it into the commit queue.

**Comment by BrianCurtis-NOAA** [comment]
Also I wasn't sure if this needed new baselines, but assumed it did. Please remove that label if I am incorrect.

**Comment by DeniseWorthen** [comment]
@pjpegion I believe the fix I had proposed for adding a time-offset is cleaner than your proposed change. It leaves intact the logic of initial/continue and adds a time-offset for fhrot in the same way the driver does.

**Comment by pjpegion** [comment]
@DeniseWorthen I remember you suggesting the time offset. Did you code that up?

**Comment by DeniseWorthen** [comment]
@pjpegion yes, I did code it up.  I added a few log messages regarding the clock, but those aren't really required. You can see the change in wav_comp_nuopc in this [branch](https://github.com/DeniseWorthen/WW3/tree/feature/update_and_philfix). For some reason I can't find your fork to compare to. 

Note this branch also fixed CI for the dev/ufs-weather-model branch and updated to the latest develop so additional changes are present.

**Comment by BrianCurtis-NOAA** [comment]
Still waiting on Intel/GNU logs from Hera or Cheyenne showing the anticipated RT's are the only ones failing.

**Comment by zach1221** [comment]
Hi, @pjpegion. In anticipation of working to test this PR next, would you be able to resolve the conflicts and provide Intel/GNU logs for Hera or Cheyenne?

**Comment by JessicaMeixner-NOAA** [comment]
@pjpegion is on leave this week so I'm helping him w/resolving the conflicts and can provide the intel/gnu for hera.

**Comment by zach1221** [comment]
@JessicaMeixner-NOAA Ok, understood. Thank you!

**Comment by JessicaMeixner-NOAA** [comment]
Okay the WW3 branch for this PR has been updated.  And I have a PR with the updated and merge conflicts resolved and is here: https://github.com/pjpegion/ufs-weather-model/pull/14 


I'll post gnu/intel hera logs as soon as i have them.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @pjpegion the pr still needs work. Meanwhile, we like to check next pr #1642 as well. FYI @zach1221 @BrianCurtis-NOAA

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 #1642 isn't ready yet either.

**Comment by pjpegion** [comment]
@JessicaMeixner-NOAA cleaned up my mess.

**Comment by jkbk2004** [comment]
> @JessicaMeixner-NOAA cleaned up my mess.

Cool!

**Comment by JessicaMeixner-NOAA** [comment]
[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10961366/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10961367/RegressionTests_hera.intel.log)
Here are the two logs requested.  Note that the baselines do not change in my tests.

**Comment by zach1221** [comment]
Please see jenkins-ci ORT logs attached. Everything passed ok.
[ufs-weather-model » ort-docker-pipeline » PR-1547 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10962804/ufs-weather-model.ort-docker-pipeline.PR-1547.1.Console.Jenkins.pdf)

**Comment by jkbk2004** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1173997832/20230314014543/ufs-weather-model
[RT] Error: Test cpld_decomp_p8 006 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 015 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by JessicaMeixner-NOAA** [comment]
I re-ran the 2 failed jobs on gaea this morning and both passed: /lustre/f2/scratch/ncep/Jessica.Meixner/ufs-weather-model/tests/RegressionTests_gaea.intel.log

**Comment by zach1221** [comment]
@JessicaMeixner-NOAA thank you. I'll kill my tests running and use your logs.

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004  let me know when you're ready for me to merge in the WW3 update.

**Review by DeniseWorthen — DISMISSED** [review]

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA sure! go ahead to merge ww3 pr.

**Comment by JessicaMeixner-NOAA** [comment]
The WW3 PR has been merged.  The hash from the sqush commit for WW3 is: af544dca5bf49bf3c3ad8d47b786e8211dcf4bba

I dont know if @pjpegion is out for the day yet or not, but if he is maybe someone w/maintainer privelages can push the revert to his branch?

**Comment by pjpegion** [comment]
I'm here, and will do the update to my branch.

**Review by BrianCurtis-NOAA — APPROVED** [review]
Hash looks good.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
