### PR TITLE
Land surface upgrades for HR4

### PR DESCRIPTION
**Pull request by HelinWei-NOAA**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

To address some concerns from HR3 especially the surface cold biases we have finalized some land surface upgrades after carrying out extensive tests and evaluation.

- remove vegetation type-dependent for the diagnostic option (opt_diag) used in HR3
- use radiative temperature as skin temperature
- use single loop alternative approach to address some flux inconsistence below and above the canopy
- fix the thermal roughness bug (the one for bared portion in the composition is not the same as the one used in the bared title)
- adjust some momentum roughness length
- use the interpolated temp between the skin temp and the first soil temp to get the initial snow temp based on snow depth
- use constant snow thermal conductivity to reduce the snow insulation effects
- fix radiation parameter bugs for grassland/cropland
- adjust albedo parameter for each soil color category

### Commit Message:

```
* UFSWM - 
 
  * FV3 - 
    * ccpp-physics - 

  * NOAHMP - 

```

### Priority:

* Normal.

### UFSWM:

* Closes #
* None

### Sub component Pull Requests:

* FV3: NOAA-EMC/fv3atm#855
  * ccpp-physics: ufs-community/ccpp-physics#219

* FV3:
  * ccpp-physics:
  * atmos_cubed_sphere:

* NOAHMP:
  * https://github.com/NOAA-EMC/noahmp/pull/11

### Regression Test Changes (Please commit test_changes.list):

this PR creates new baselines, changes baselines 

Please make sure you have properly submitted test_changes.list

* PR Adds New Tests/Baselines.
* PR Updates/Changes Baselines.

  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by yangfanglin** [comment]
@uturuncoglu do you need to update the land component model for this upgrade ?

**Comment by uturuncoglu** [comment]
@yangfanglin I think this PR also updates the component model right. Please double check that both component model and ccpp/physics have same version of code. As I see this PR makes some variables optional, I am not sure how that needs to be handled in the component model but if the RTs related with component model passes without any issue, I think it is good to know.

**Comment by jkbk2004** [comment]
@HelinWei-NOAA can you sync up branches? we hope to get this pr ready to commit.

**Comment by jkbk2004** [comment]
@yangfanglin feel free to review and approve https://github.com/NOAA-EMC/noahmp/pull/11. We will do pre-test to make sure.

**Comment by HelinWei-NOAA** [comment]
@jkbk2004 Done
> @HelinWei-NOAA can you sync up branches? we hope to get this pr ready to commit.

**Comment by FernandoAndrade-NOAA** [comment]
It seems the NOAHMP sub PR was merged early. In that case I'd recommend the commit ID be synced again and we continue with testing. If there's an issue, we will need to roll back the changes from the early merge in the subcomponent. The FV3 sub PR also still needs an initial approval.

@BrianCurtis-NOAA @zach1221

**Comment by FernandoAndrade-NOAA** [comment]
@HelinWei-NOAA please go ahead and revert .gitmodules NOAHMP section and update the hash, it should now be 3ac32f0
Please also be sure to fill out the commit message section of the PR description.

**Comment by HelinWei-NOAA** [comment]
> @HelinWei-NOAA please go ahead and revert .gitmodules NOAHMP section and update the hash, it should now be 3ac32f0 Please also be sure to fill out the commit message section of the PR description.

@FernandoAndrade-NOAA Done

**Comment by BrianCurtis-NOAA** [comment]
@HelinWei-NOAA please make sure to update what you want for the commit message in the top section. It will be used once we get to the merge stage.

**Comment by FernandoAndrade-NOAA** [comment]
Acorn will be skipped this PR, I'll let CCPP to continue with the merge process.

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Comment by zach1221** [comment]
@HelinWei-NOAA please let us know what commit message you'd like for this PR.

**Comment by HelinWei-NOAA** [comment]
the land surface upgrades for HR4
> @HelinWei-NOAA please let us know what commit message you'd like for this PR.

**Pull request merged**
