### PR TITLE
Enable debugging features in CCPP physics caps, bug fixes and cleanup for CCPP variables and metadata, port model to XSEDE Expanse, switch WW3 from develop to dev/ufs-weather-model

### LINKED ISSUE #883: Re-enable regression test fv3_gsd_diag_debug / fix bug of using wrong temperature over water in RUC LSM
## Description

As discussed in length in https://github.com/ufs-community/ufs-weather-model/pull/821, a bug fix is required to initialize cold start runs with RUC LSM correctly over water points:

```
diff --git a/physics/sfc_drv_ruc.meta b/physics/sfc_drv_ruc.meta
index 52b76825..692f1712 100644
--- a/physics/sfc_drv_ruc.meta
+++ b/physics/sfc_drv_ruc.meta
@@ -199,7 +199,7 @@
   intent = in
   optional = F
 [tsfc_wat]
-  standard_name = surface_skin_temperature_over_water
+  standard_name = sea_surface_temperature
   long_name = surface skin temperature over water
   units = K
   dimensions = (horizontal_dimension)
```
This will change the results for all regression tests using RUC LSM.

Once this change is made, re-enable regression test `fv3_gsd_diag_debug` in `rt.conf`.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR updates the submodule pointers for fv3atm (GFDL_atmos_cubed_sphere, ccpp-framework, ccpp-physics) and stochastic_physics for the changes described in detail in the associated PRs below:

It also ports the model to the XSede Expanse system (contributed by @MinsukJi-NOAA).

Switch WW3 from develop to dev/ufs-weather-model (i.e. pull #850 into this PR). This changes the results (metadata) for two regression tests, see #850 for more information. No change to input data.

Also: bug fix in `run_compile.sh`, replace `UNIT_TEST` with `OPNREQ_TEST`.

Update 10/22/2021: The bug fixes for issue https://github.com/ufs-community/ufs-weather-model/issues/883 change the results of all regression tests using RUC LSM.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/883
Fixes https://github.com/NCAR/ccpp-framework/issues/405

## Testing

Regression tests were run on Cheyenne with Intel and GNU against the existing baselines on 10/04/2021. All tests passed.

[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/7281461/RegressionTests_cheyenne.gnu.log)
[RegressionTests_cheyenne.intel.log](https://github.com/ufs-community/ufs-weather-model/files/7281462/RegressionTests_cheyenne.intel.log)

Update 10/22/2021: with the updates for RUC LSM and WW3, the following baselines change (confirmed by manually comparing the Hera Intel 20211019 and 20211022 baselines):
```
cpld_bmark_p7 (20130402.060000.out_pnt.points differs)
cpld_control_wave_p7 (20210322.180000.out_pnt.points differs)
fv3_gsd (RESTART/sfc_data.tile{1-6} differ, nothing else)
fv3_gsd_debug (RESTART/sfc_data.tile{1-6} differ, nothing else)
fv3_hrrr (RESTART/sfc_data.tile{1-6} differ, nothing else)
fv3_rap (RESTART/sfc_data.tile{1-6} differ, nothing else)
```

Full regression tests will be run on all tier-1 platforms when it is time to merge:

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [X] CI - https://github.com/ufs-community/ufs-weather-model/pull/850/commits/7f1241573dbc0593612e2a99e681e866e76dea49

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/749
- waiting on https://github.com/NCAR/ccpp-framework/pull/404
- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/148
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/407/files
- waiting on https://github.com/noaa-psd/stochastic_physics/pull/48
- waiting on https://github.com/NOAA-EMC/NEMS/pull/110

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@climbfuji Expanse run also requires minor, build related changes in NEMS and WW3:
- https://github.com/MinsukJi-NOAA/NEMS/commit/d6b934fd267be97a9361d2cc7cbf97c2dc50e715
- https://github.com/MinsukJi-NOAA/WW3/commit/b427489e2c8efe7a2b582fa59471902da5fe7a98

WW3 is tricky because UFS is not using the top of develop

**Comment by climbfuji** [comment]
> @climbfuji Expanse run also requires minor, build related changes in NEMS and WW3:
> 
> * [MinsukJi-NOAA/NEMS@d6b934f](https://github.com/MinsukJi-NOAA/NEMS/commit/d6b934fd267be97a9361d2cc7cbf97c2dc50e715)
> * [MinsukJi-NOAA/WW3@b427489](https://github.com/MinsukJi-NOAA/WW3/commit/b427489e2c8efe7a2b582fa59471902da5fe7a98)
> 
> WW3 is tricky because UFS is not using the top of develop

Are there pull requests? Or should we, as part of this PR, only make the changes for the uncoupled model and only include the NEMS changes (but not the WW3 changes)?

**Comment by MinsukJi-NOAA** [comment]
There are no pull requests for NEMS and WW3. I can create a PR to NEMS.

Expanse users run the P7 configuration. So, although WW3 is not needed for debugging the thread issue on Expanse, I think it will be beneficial to include WW3.

Also, I see a few missing files (e.g. detect_machine.sh, default_vars.sh, etc.): https://github.com/MinsukJi-NOAA/ufs-weather-model/commit/72baaaf4eafff589d2bbf2da5010bceaaa0e9e54

@junwang-noaa @DusanJovic-NOAA Any suggestions on how to bring WW3 changes to UFS?

**Comment by JessicaMeixner-NOAA** [comment]
@MinsukJi-NOAA would you like me to open a PR with your changes to expanse in WW3?

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA would you like me to open a PR with your changes to expanse in WW3?

@JessicaMeixner-NOAA that would be great. Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
@MinsukJi-NOAA The WW3 PR is here: https://github.com/NOAA-EMC/WW3/pull/485

**Comment by MinsukJi-NOAA** [comment]
@JessicaMeixner-NOAA will the WW3 code changes go into WW3 develop branch? But I see that UFS is using `435298b`

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA will the WW3 code changes go into WW3 develop branch? But I see that UFS is using `435298b`

Yes, there should not be answer changes though.    @aliabdolali or I can triple check this to confirm.  I also know that @aliabdolali is going to make a branch of WW3 for UFS at some point.  I'm not sure what the status of that is, but if required we could perhaps make that branch and add your changes there (as well as to the WW3 develop branch).

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA what P7 configuration tests are run on Expanse? Do these tests have ww3 in it? It looks to me the threading test does not have ww3 in it, is that correct?

**Comment by climbfuji** [comment]
> There are no pull requests for NEMS and WW3. I can create a PR to NEMS.
> 
> Expanse users run the P7 configuration. So, although WW3 is not needed for debugging the thread issue on Expanse, I think it will be beneficial to include WW3.
> 
> Also, I see a few missing files (e.g. detect_machine.sh, default_vars.sh, etc.): [MinsukJi-NOAA@72baaaf](https://github.com/MinsukJi-NOAA/ufs-weather-model/commit/72baaaf4eafff589d2bbf2da5010bceaaa0e9e54)
> 
> @junwang-noaa @DusanJovic-NOAA Any suggestions on how to bring WW3 changes to UFS?

Thanks @MinsukJi-NOAA. Please create a PR to my ufs-weather-model branch with the missing files. I will point to your NEMS branch in my PR. Not sure what I should do with WW3, maybe I will leave this to the next set of PRs.

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA what P7 configuration tests are run on Expanse? Do these tests have ww3 in it? It looks to me the threading test does not have ww3 in it, is that correct?

The hash is `b26a89` for the P7 configuration referred to. The test being run on Expanse is `cpld_bmark_wave_v16_p7b`, which includes `WW3`. The threading issue (https://github.com/ufs-community/ufs-weather-model/issues/705) most likely does not involve `WW3` since `control_2threads` fails.

**Comment by climbfuji** [comment]
@MinsukJi-NOAA @junwang-noaa @DusanJovic-NOAA Adding Expanse support also means that we should think about how to maintain it. Similar to the S4 discussion with @DavidHuber-NOAA, we should have an agreement (and for now a manual system/reminder, in the future hopefully automated) to run the regression tests once a month? (create + verify each time with a temporary baseline only?)

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA @junwang-noaa @DusanJovic-NOAA Adding Expanse support also means that we should think about how to maintain it. Similar to the S4 discussion with @DavidHuber-NOAA, we should have an agreement (and for now a manual system/reminder, in the future hopefully automated) to run the regression tests once a month? (create + verify each time with a temporary baseline only?)

Once a month seems doable to me. One thing to note is that we need the hpc-stack updated occasionally as well.

**Comment by climbfuji** [comment]
> > @MinsukJi-NOAA @junwang-noaa @DusanJovic-NOAA Adding Expanse support also means that we should think about how to maintain it. Similar to the S4 discussion with @DavidHuber-NOAA, we should have an agreement (and for now a manual system/reminder, in the future hopefully automated) to run the regression tests once a month? (create + verify each time with a temporary baseline only?)
> 
> Once a month seems doable to me. One thing to note is that we need the hpc-stack updated occasionally as well.

I am pretty sure that almost every monthly test will require copying over new input data sets and/or updating hpc-stack. It would be really good if we could automate at least the testing, for example leveraging the auto-rt code. If the tests fail, we will know that whether we have to update the input data set, or the stack, or ...

**Comment by DusanJovic-NOAA** [comment]
> > > @MinsukJi-NOAA @junwang-noaa @DusanJovic-NOAA Adding Expanse support also means that we should think about how to maintain it. Similar to the S4 discussion with @DavidHuber-NOAA, we should have an agreement (and for now a manual system/reminder, in the future hopefully automated) to run the regression tests once a month? (create + verify each time with a temporary baseline only?)
> > 
> > 
> > Once a month seems doable to me. One thing to note is that we need the hpc-stack updated occasionally as well.
> 
> I am pretty sure that almost every monthly test will require copying over new input data sets and/or updating hpc-stack. It would be really good if we could automate at least the testing, for example leveraging the auto-rt code. If the tests fail, we will know that whether we have to update the input data set, or the stack, or ...

Who is using, or will be using, this computer? And for what purpose? If it's going to be used for development, then we need to make sure develop branch is working all the time.

**Comment by climbfuji** [comment]
> > > > @MinsukJi-NOAA @junwang-noaa @DusanJovic-NOAA Adding Expanse support also means that we should think about how to maintain it. Similar to the S4 discussion with @DavidHuber-NOAA, we should have an agreement (and for now a manual system/reminder, in the future hopefully automated) to run the regression tests once a month? (create + verify each time with a temporary baseline only?)
> > > 
> > > 
> > > Once a month seems doable to me. One thing to note is that we need the hpc-stack updated occasionally as well.
> > 
> > 
> > I am pretty sure that almost every monthly test will require copying over new input data sets and/or updating hpc-stack. It would be really good if we could automate at least the testing, for example leveraging the auto-rt code. If the tests fail, we will know that whether we have to update the input data set, or the stack, or ...
> 
> Who is using, or will be using, this computer? And for what purpose? If it's going to be used for development, then we need to make sure develop branch is working all the time.

As far as I know, Ben Cash and Christiane Jablonowski are actively using Expanse, because it's one of the machines that sits outside the NOAA firewalls. Minsuk helped them with getting the model up and running, and then I was brought in because of issues/crashes with the threaded tests. Maybe Ben or Minsuk can provide more input on what the plan for Expanse is.

**Comment by MinsukJi-NOAA** [comment]
> > > > > @MinsukJi-NOAA @junwang-noaa @DusanJovic-NOAA Adding Expanse support also means that we should think about how to maintain it. Similar to the S4 discussion with @DavidHuber-NOAA, we should have an agreement (and for now a manual system/reminder, in the future hopefully automated) to run the regression tests once a month? (create + verify each time with a temporary baseline only?)
> > > > 
> > > > 
> > > > Once a month seems doable to me. One thing to note is that we need the hpc-stack updated occasionally as well.
> > > 
> > > 
> > > I am pretty sure that almost every monthly test will require copying over new input data sets and/or updating hpc-stack. It would be really good if we could automate at least the testing, for example leveraging the auto-rt code. If the tests fail, we will know that whether we have to update the input data set, or the stack, or ...
> > 
> > 
> > Who is using, or will be using, this computer? And for what purpose? If it's going to be used for development, then we need to make sure develop branch is working all the time.
> 
> As far as I know, Ben Cash and Christiane Jablonowski are actively using Expanse, because it's one of the machines that sits outside the NOAA firewalls. Minsuk helped them with getting the model up and running, and then I was brought in because of issues/crashes with the threaded tests. Maybe Ben or Minsuk can provide more input on what the plan for Expanse is.

I don't see anyone doing development on it. They are doing coupled wave benchmark runs as part of the XSEDE project. I have to point out though current XSEDE allocation will expire at the end of this year...

**Comment by benjamin-cash** [comment]
I am currently running P7 ensembles as part of a funded project to make ensemble runs with the coupled model to provide additional data for the development effort as well as to do scientific analysis. I would imagine that Expanse and Stampede2, along with Cheyenne/Derecho, will be prime targets for community users of UFS going forward. 

If anyone has any other questions about this project just let me know. :)

**Comment by aliabdolali** [comment]
I am working on a bug fix that caused a compilation problem on our RDHPC for wave tests.

**Comment by aliabdolali** [comment]
@climbfuji I am not sure about it, are you merging #860 to your PR? I am asking this because under files changed, I still see an older commit in WW3.

**Comment by climbfuji** [comment]
> @climbfuji I am not sure about it, are you merging #860 to your PR? I am asking this because under files changed, I still see an older commit in WW3.

I am confused about what I am supposed to do with WW3. I am pointing to the following hash:
```
commit 1fab3f7238a22f42d0d5cc01e8de1aff80d1b988 (HEAD)
Author: Jessica Meixner <jessica.meixner@noaa.gov>
Date:   Thu Oct 7 10:18:06 2021 -0400

    Porting updates for Expanse (#490)

    Ports to expanse
```

Should I point to 435298b instead? Does this contain the Expanse port from @JessicaMeixner-NOAA?

**Comment by climbfuji** [comment]
Or should I include your PR aliabdolali:feature/create_ww3_branch ? That one updates the WW3 hash from 435298b to cad636d

**Comment by aliabdolali** [comment]
> Or should I include your PR aliabdolali:feature/create_ww3_branch ? That one updates the WW3 hash from 435298b to cad636d

Jessica is on leave. My understanding is that #850 and #860 will go together (according to the commit queue). So I think the right approach would be to include my PR unless @junwang-noaa has another idea.

**Comment by climbfuji** [comment]
> > Or should I include your PR aliabdolali:feature/create_ww3_branch ? That one updates the WW3 hash from 435298b to cad636d
> 
> Jessica is on leave. My understanding is that #850 and #860 will go together (according to the commit queue). So I think the right approach would be to include my PR unless @junwang-noaa has another idea.

Happy to do so - will wait for @junwang-noaa to confirm. Thanks for the heads up.

**Comment by MinsukJi-NOAA** [comment]
@climbfuji please make the following change to tests/ci/repo_check.sh to reflect the change in WW3 repo branch. CI needs to be skipped for this PR because of this.
```
diff --git a/tests/ci/repo_check.sh b/tests/ci/repo_check.sh
index 843e0045..e2cf8ec2 100755
--- a/tests/ci/repo_check.sh
+++ b/tests/ci/repo_check.sh
@@ -36,7 +36,7 @@ cice[branch]='emc/develop'
 cice[dir]='CICE-interface/CICE'
 
 ww3[repo]='https://github.com/NOAA-EMC/WW3'
-ww3[branch]='develop'
+ww3[branch]='dev/ufs-weather-model'
 ww3[dir]='WW3'
 
 stoch[repo]='https://github.com/noaa-psd/stochastic_physics'

```

**Comment by climbfuji** [comment]
> @climbfuji please make the following change to tests/ci/repo_check.sh to reflect the change in WW3 repo branch. CI needs to be skipped for this PR because of this.
> 
> ```
> diff --git a/tests/ci/repo_check.sh b/tests/ci/repo_check.sh
> index 843e0045..e2cf8ec2 100755
> --- a/tests/ci/repo_check.sh
> +++ b/tests/ci/repo_check.sh
> @@ -36,7 +36,7 @@ cice[branch]='emc/develop'
>  cice[dir]='CICE-interface/CICE'
>  
>  ww3[repo]='https://github.com/NOAA-EMC/WW3'
> -ww3[branch]='develop'
> +ww3[branch]='dev/ufs-weather-model'
>  ww3[dir]='WW3'
>  
>  stoch[repo]='https://github.com/noaa-psd/stochastic_physics'
> ```

Done in https://github.com/ufs-community/ufs-weather-model/pull/850/commits/9833a7abd6e548894a197e30ffe17886428918f7 - I added the `run-ci` label, do you expect those tests to run successfully?

**Comment by MinsukJi-NOAA** [comment]
> > @climbfuji please make the following change to tests/ci/repo_check.sh to reflect the change in WW3 repo branch. CI needs to be skipped for this PR because of this.
> > ```
> > diff --git a/tests/ci/repo_check.sh b/tests/ci/repo_check.sh
> > index 843e0045..e2cf8ec2 100755
> > --- a/tests/ci/repo_check.sh
> > +++ b/tests/ci/repo_check.sh
> > @@ -36,7 +36,7 @@ cice[branch]='emc/develop'
> >  cice[dir]='CICE-interface/CICE'
> >  
> >  ww3[repo]='https://github.com/NOAA-EMC/WW3'
> > -ww3[branch]='develop'
> > +ww3[branch]='dev/ufs-weather-model'
> >  ww3[dir]='WW3'
> >  
> >  stoch[repo]='https://github.com/noaa-psd/stochastic_physics'
> > ```
> 
> Done in [9833a7a](https://github.com/ufs-community/ufs-weather-model/commit/9833a7abd6e548894a197e30ffe17886428918f7) - I added the `run-ci` label, do you expect those tests to run successfully?

Looks like CI is running -- maybe because of the hashes from develop and dev/ufs-weather-model are the same.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/749328747/20211022103016/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_47577
Test control_thompson_no_aero_debug 023 failed failed 
Test control_thompson_no_aero_debug 023 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-BL

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022163025/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_151428
Baseline creation and move successful
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022184926/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_149379
Test cpld_control_c192_p7 005 failed failed 
Test cpld_control_c192_p7 005 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: jet
> Compiler: intel
> Job: BL
> Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022163025/ufs-weather-model
> Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_151428
> Baseline creation and move successful
> Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022184926/ufs-weather-model
> Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_149379
> Test cpld_control_c192_p7 005 failed failed
> Test cpld_control_c192_p7 005 failed in run_test failed
> Please make changes and add the following label back:
> jet-intel-BL

Sigh. The usual timeout. We need to do something about this test. I'll rerun the failed BL job manually, complete the baseline and add the RT label afterwards.

**Comment by DusanJovic-NOAA** [comment]
> > _**Automated RT Failure Notification**_
> > Machine: jet
> > Compiler: intel
> > Job: BL
> > Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022163025/ufs-weather-model
> > Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_151428
> > Baseline creation and move successful
> > Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022184926/ufs-weather-model
> > Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_149379
> > Test cpld_control_c192_p7 005 failed failed
> > Test cpld_control_c192_p7 005 failed in run_test failed
> > Please make changes and add the following label back:
> > jet-intel-BL
> 
> Sigh. The usual timeout. We need to do something about this test. I'll rerun the failed BL job manually, complete the baseline and add the RT label afterwards.

If you want you can try adding changes I made in this branch:
https://github.com/DusanJovic-NOAA/ufs-weather-model/commits/ecf_tries

**Comment by climbfuji** [comment]
> > > _**Automated RT Failure Notification**_
> > > Machine: jet
> > > Compiler: intel
> > > Job: BL
> > > Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022163025/ufs-weather-model
> > > Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_151428
> > > Baseline creation and move successful
> > > Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/749328747/20211022184926/ufs-weather-model
> > > Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_149379
> > > Test cpld_control_c192_p7 005 failed failed
> > > Test cpld_control_c192_p7 005 failed in run_test failed
> > > Please make changes and add the following label back:
> > > jet-intel-BL
> > 
> > 
> > Sigh. The usual timeout. We need to do something about this test. I'll rerun the failed BL job manually, complete the baseline and add the RT label afterwards.
> 
> If you want you can try adding changes I made in this branch: https://github.com/DusanJovic-NOAA/ufs-weather-model/commits/ecf_tries

Please remind me again before I work on my next PR in a bit more than a week. I am hesitant to update this PR so late in the process (most regression tests finished so far). Thanks!

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@DusanJovic-NOAA All submodule PRs have been merged and I verified the hashes. Please review and merge if ok. Thanks!

**Pull request merged**
