### PR TITLE
Update .gitmodules and submodule pointer for fv3atm for code review and testing

### PR DESCRIPTION
**Pull request by tanyasmirnova**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [ ] Add list of all failed regression tests in "Regression Tests" section.

### Description

The output of surface runoff is changed from instantaneous to accumulated surface runoff in the RUC LSM driver.
### Priority
- [x] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [ ] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
- [ ] Normal

### Git Issues Fixed By This PR

https://github.com/ufs-community/ccpp-physics/issues/164

## Changes
One-line change in the RUC LSM driver: lsm_ruc.F90

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [ ] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [ ] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by grantfirl** [comment]
@tanyasmirnova Has this gone through RTs? Do you need us to help?

**Comment by tanyasmirnova** [comment]
@grantfirl @haiqinli Grant, I haven't run RT because this one-line change fixes the diagnostic variable and does not change the model performance. I asked @haiqinli to merge it into his next PR.

**Comment by grantfirl** [comment]
@jkbk2004 This PR can be closed because it has been brought into https://github.com/ufs-community/ufs-weather-model/pull/2147. Although it is directed at the RRFS release branch, these changes will make their way to develop after the release.

**Comment by jkbk2004** [comment]
This pr is followed up with https://github.com/ufs-community/ufs-weather-model/pull/2147.

**Pull request closed without merging**
