### PR TITLE
[production/RRFS.v1] Thompson-Eidhammer microphysics code formatting

### PR DESCRIPTION
**Pull request by grantfirl**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [X] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [N/A] Commit 'test_changes.list' from previous step
---
## Description:
This PR is the first of many that will modernized, modularize, and streamline Thompson-Eidhammer microphysics.

This PR includes:

The addition of parameterized kind: REAL -> real(kind_phys)
Consistent indentation
Removal of GOTO statements
Add physical constant metadata needed by Thompson MP

### Commit Message:

```
* UFSWM - Thompson-Eidhammer microphysics code formatting
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - Thompson-Eidhammer microphysics code formatting
    * ccpp-physics - Thompson-Eidhammer microphysics code formatting
    * atmos_cubed_sphere - 
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 - 
  * stochastic_physics - 
```

### Priority:

* High: RRFS.v1 release

### UFSWM:

* None

### Sub component Pull Requests:

* AQM:
* CDEPS:
* CICE:
* CMEPS:
* CMakeModules:
* FV3:https://github.com/NOAA-EMC/fv3atm/pull/790
  * ccpp-physics:https://github.com/ufs-community/ccpp-physics/pull/179
  * atmos_cubed_sphere:
* GOCART:
* HYCOM:
* MOM6:
* NOAHMP:
* WW3:
* stochastic_physics:
* None

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

This PR only changes baselines due to changes in physical constants, which are now passed in and consistent with other physics schemes instead of redefining them.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by grantfirl** [comment]
@MatthewPyle-NOAA @AndersJensen-NOAA This PR is ready to test. All tests that use Thompson MP are expected to change baseline results. Since this is for a release, I'm assuming that we'll want to run verification statistics on this code as well to make sure the skill doesn't change right before release?

**Comment by jkbk2004** [comment]
@grantfirl the branch looks synced ok. hera is down today. I will go ahead to run tests on orion/hercules. @MatthewPyle-NOAA FYI

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 What is the best practice for a PR such as this one where answers are expected to change?  Do we document which tests failed in an initial run of the regression test suite ahead of creating a fresh baseline?   Thanks!

**Comment by jkbk2004** [comment]
> @jkbk2004 What is the best practice for a PR such as this one where answers are expected to change? Do we document which tests failed in an initial run of the regression test suite ahead of creating a fresh baseline? Thanks!

@MatthewPyle-NOAA We can confirm with pre-test. Usually on hera but down today. I let a test run on hercules now. I will attach log. We can go from there to reset bl_date.conf for new date.

**Comment by MatthewPyle-NOAA** [comment]
Thanks @jkbk2004 I'm running a pre-test on WCOSS now.

**Comment by grantfirl** [comment]
@jkbk2004 @MatthewPyle-NOAA I'm also running RTs on Jet right now and will check the list of failures to make sure that all tests that fail use Thompson MP. I've also given @AndersJensen-NOAA the paths for the RT rundirs and baselines so that he can double check the results.

**Comment by jkbk2004** [comment]
As expected, all cases are changing. I am resetting with a new BL_DATE.
```
001 rap_control_intel failed in check_result
002 regional_spp_sppt_shum_skeb_intel failed in check_result
003 rap_decomp_intel failed in check_result
004 rap_2threads_intel failed in check_result
006 rap_sfcdiff_intel failed in check_result
007 rap_sfcdiff_decomp_intel failed in check_result
009 hrrr_control_intel failed in check_result
010 hrrr_control_decomp_intel failed in check_result
011 hrrr_control_2threads_intel failed in check_result
013 rrfs_v1beta_intel failed in check_result
016 control_p8_faster_intel failed in check_result
017 regional_control_faster_intel failed in check_result
026 control_debug_p8_intel failed in check_result
027 regional_debug_intel failed in check_result
028 rap_control_debug_intel failed in check_result
029 hrrr_control_debug_intel failed in check_result
030 hrrr_gf_debug_intel failed in check_result
031 hrrr_c3_debug_intel failed in check_result
032 rap_unified_drag_suite_debug_intel failed in check_result
033 rap_diag_debug_intel failed in check_result
034 rap_cires_ugwp_debug_intel failed in check_result
035 rap_unified_ugwp_debug_intel failed in check_result
036 rap_lndp_debug_intel failed in check_result
037 rap_progcld_thompson_debug_intel failed in check_result
038 rap_noah_debug_intel failed in check_result
039 rap_sfcdiff_debug_intel failed in check_result
040 rap_noah_sfcdiff_cires_ugwp_debug_intel failed in check_result
041 rrfs_v1beta_debug_intel failed in check_result
042 rap_clm_lake_debug_intel failed in check_result
043 rap_flake_debug_intel failed in check_result
044 gnv1_c96_no_nest_debug_intel failed in check_result
045 regional_spp_sppt_shum_skeb_dyn32_phy32_intel failed in check_result
046 rap_control_dyn32_phy32_intel failed in check_result
047 hrrr_control_dyn32_phy32_intel failed in check_result
048 rap_2threads_dyn32_phy32_intel failed in check_result
049 hrrr_control_2threads_dyn32_phy32_intel failed in check_result
050 hrrr_control_decomp_dyn32_phy32_intel failed in check_result
053 conus13km_control_intel failed in check_result
056 rap_control_dyn64_phy32_intel failed in check_result
057 rap_control_debug_dyn32_phy32_intel failed in check_result
058 hrrr_control_debug_dyn32_phy32_intel failed in check_result
059 conus13km_debug_intel failed in check_result
060 conus13km_debug_qr_intel failed in check_result
061 conus13km_debug_2threads_intel failed in check_result
062 conus13km_radar_tten_debug_intel failed in check_result
063 rap_control_dyn64_phy32_debug_intel failed in check_result
```

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 Good to see we had a consistent list of tests that failed.  I'm creating new a new baseline for WCOSS.

**Comment by jkbk2004** [comment]
@grantfirl @MatthewPyle-NOAA All tests ran ok on hera/orion/hercules.

**Comment by MatthewPyle-NOAA** [comment]
@grantfirl @jkbk2004 All good with new baselines on wcoss.

**Comment by jkbk2004** [comment]
@grantfirl We can have time if you want to finish test on jet. Or it will be good as well, if you want to start merging https://github.com/ufs-community/ccpp-physics/pull/179.

**Comment by grantfirl** [comment]
> @grantfirl We can have time if you want to finish test on jet. Or it will be good as well, if you want to start merging [ufs-community/ccpp-physics#179](https://github.com/ufs-community/ccpp-physics/pull/179).

I couldn't get any throughput on Jet and ran the rt.conf_rrfs on Hera with identical failures as listed. I'm OK to merge, although I think that @MatthewPyle-NOAA and @AndersJensen-NOAA would like to double-check that the changed results still look good scientifically.

Anders has the paths of the baselines and RT output on Hera to make some comparisons.

**Comment by jkbk2004** [comment]
Sure! We can merge once @MatthewPyle-NOAA @AndersJensen-NOAA confirm the results.

**Comment by MatthewPyle-NOAA** [comment]
I will trust @AndersJensen-NOAA on confirming the results.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA You mean to go for merging?

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 I meant that once @AndersJensen-NOAA is good with it, I will be as well.

**Comment by grantfirl** [comment]
@jkbk2004 @MatthewPyle-NOAA Via a separate email, @AndersJensen-NOAA confirms that the results change related to this PR is not detrimental to forecasts and is OK to merge. We can choose to merge this as-is, or we can combine https://github.com/ufs-community/ufs-weather-model/pull/2170 into this one. Although that one is also expected to change results for any suites using MYNN PBL, those results changes are desired for the RRFS release. @jkbk2004 @MatthewPyle-NOAA Do we merge this as-is, or should we combine and maybe run another set of RTs for the combined changes? I'm fine with either decision. Thoughts?

**Comment by MatthewPyle-NOAA** [comment]
@grantfirl I'm fine either way - whatever seems easiest for you.

**Comment by grantfirl** [comment]
> @grantfirl I'm fine either way - whatever seems easiest for you.

I'm thinking that this was the only one that needed "extra" scientific validation and we can go ahead and merge since all the tests have been run and baselines updated. We'll either need new baselines for the combined PR or for the new PR by itself, so there will be more testing either way. It's probably easiest just to merge this and move on to the next one.

**Comment by grantfirl** [comment]
@MatthewPyle-NOAA I can go ahead and start the merge.

**Comment by grantfirl** [comment]
@jkbk2004 @MatthewPyle-NOAA Updated and ready to approve/merge

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good to me....

**Pull request merged**
