### PR TITLE
Rt hires

### LINKED ISSUE #942: Inconsistent 'calendar' parameter used in model_configure templates
Various model_configure templates in tests/parm directory are setting calendar parameter to 'julian' while other are not (commented out):
```
esg_HAFS_v0_hwrf-model_configure.IN:calendar:                'julian'
model_configure_hafs_shared.IN:calendar:                'julian'
model_configure_hafs.IN:calendar:                'julian'
cpt.nml.IN:#       calendar = 'julian'
wam.nml.IN:#       calendar = 'julian'
model_configure_regional.IN:calendar:                'julian'
csawmg3shoc127.nml.IN:#       calendar = 'julian'
model_configure_fhout.IN:calendar:                'julian'
csawmgshoc.nml.IN:#       calendar = 'julian'
gsd_sar-model_configure.IN:calendar:                'julian'
stretched-nest-quilt-model_configure.IN:calendar:                'julian'
datm_cdeps_configure.IN:calendar:                'julian'
model_configure.IN:calendar:                'julian'
```
The default value is 'gregorian' (set in fv3_cap.F90) which is consistent with the default calendar set during ESMF initialization (see main program). Why are we using Julian calendar?

### LINKED ISSUE #1461: Replacing regional regression tests with more realistic ones
## Description
Current regional regression tests are obsolete. We have new configurations running in parallel runs.
These tests will replace old, low resolution tests with new, high resolution tests (over small domain).
Test "3km" is becoming new "control", and all tests will use same configuration and ICs.

## Solution
I'm preparing new tests to replace previous ones.
For now, on Hera, these are finished:
regional_control
regional_restart
regional_decomp
regional_2threads
regional_noquilt
regional_netcdf_parallel
regional_2dwrtdecomp

~~And this one is failing:
regional_debug
(reported in Bug Issue #1462 )~~ <--- Sam's commit #1437 solved issue.

## Alternatives
N/A

## Related to
Nothing for now.

## NOTE
This will change initial conditions substantially and we will have to replace whole input directory rather than just update existing one.

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.
Issue #1461 

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.
New tests make new results.
**Should create new develop-2022XXXX directory**

- [x] **New input data is required and created on Hera machine. Should be resynched to other platforms.**

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

Replaced old regional regression tests with new, using latest configuration from LAMDX parallel. It is in 3km resolution over small domain.
@DusanJovic-NOAA removed variable "calendar" from namelists (model_configure*.IN) and replaced calendar variable values in input directory in files coupler.res from 2 --> 3
```(Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)```

### Issue(s) addressed

- fixes #1461
- fixes #942

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

No dependences

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
I think we can remove the following directories from the new input-data:

FV3_input_data_gsd/FV3_input_data_C96_with_aerosols/
FV3_input_data_regional_esg/
FV3_input_data_sar/
GOCART/p7/
GOCART/ExtData/
WW3_input_data_20211113/
WW3_input_data_20220418/

most of the files from AQM/NEXUS - confirmed by @BrianCurtis-NOAA only NEXUS_Expt.nc is needed

**Comment by RatkoVasic-NOAA** [comment]
I an remove those directories from my input-data-20221101 directory on Hera and run full tests.
Who can confirm that directories GOCART and WW3 are not in use?

**Comment by RatkoVasic-NOAA** [comment]
I removed those directories and ran tests on Hera. Tests PASSED.

**Review by DusanJovic-NOAA — COMMENTED** [review]
tests/rt.sh file permissions has been changed from 755 to 644. Please revert.

**Comment by RatkoVasic-NOAA** [comment]
> tests/rt.sh file permissions has been changed from 755 to 644. Please revert.

I guess it happens when you solve conflict using github's web based tools.

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA I may start rsync if input-data-20221101 is ready on hera.

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 I see two new directories in input-data-20220414 : 
DATM_GSWP3_input_data
NOAHMP_IC
Are they added recently?
Should I add those to input-data-20221101?

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 
OK, I see they are used in datm_cdeps_lnd_gswp3 and datm_cdeps_lnd_gswp3_rst.
I'll copy those directories on Hera and WCOSS2, and you can rsync to othermachines.

**Comment by uturuncoglu** [comment]
@RatkoVasic-NOAA Yes, those are added as a part of external land component PR.

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA we can start testing this pr. I am going to create new baselines from hera first.

**Comment by jkbk2004** [comment]
@RatkoVasic-NOAA can you resolve the conflicts?

**Comment by RatkoVasic-NOAA** [comment]
@jkbk2004 done. Preparing BLs on WCOSS2.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1099069436/20221108173918/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1099069436/20221108173918/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1099069436/20221108173918/ufs-weather-model
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1099069436/20221108174836/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20221108/INTEL
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1099069436/20221108234506/ufs-weather-model
[BL] Error: Test regional_spp_sppt_shum_skeb 037 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1099069436/20221108173918/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1099069436/20221108193457/ufs-weather-model
[RT] Error: Test cpld_restart_bmark_p8 011 failed in check_result failed 
[RT] Error: Test cpld_restart_bmark_p8 011 failed in run_test failed 
[RT] Error: Test regional_debug 094 failed in check_result failed 
[RT] Error: Test regional_debug 094 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_wav 125 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_wav 125 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 126 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 126 failed in run_test failed 
[RT] Error: Test hafs_regional_telescopic_2nests_atm 128 failed in check_result failed 
[RT] Error: Test hafs_regional_telescopic_2nests_atm 128 failed in run_test failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 130 failed in check_result failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 130 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 134 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 134 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 136 failed in check_result failed 
[RT] Error: Test hafs_regional_docn 136 failed in run_test failed 
[RT] Error: Test hafs_regional_docn_oisst 137 failed in check_result failed 
[RT] Error: Test hafs_regional_docn_oisst 137 failed in run_test failed 
[RT] Error: Test hafs_regional_datm_cdeps 138 failed in check_result failed 
[RT] Error: Test hafs_regional_datm_cdeps 138 failed in run_test failed 
[RT] Error: Test datm_cdeps_restart_cfsr 140 failed in check_result failed 
[RT] Error: Test datm_cdeps_restart_cfsr 140 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 147 failed in check_result failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 147 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_gefs 148 failed in check_result failed 
[RT] Error: Test datm_cdeps_mx025_gefs 148 failed in run_test failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 150 failed in check_result failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 150 failed in run_test failed 
[RT] Error: Test datm_cdeps_gfs 151 failed in check_result failed 
[RT] Error: Test datm_cdeps_gfs 151 failed in run_test failed 
[RT] Error: Test datm_cdeps_debug_cfsr 152 failed in check_result failed 
[RT] Error: Test datm_cdeps_debug_cfsr 152 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3_rst 154 failed in check_result failed 
[RT] Error: Test datm_cdeps_lnd_gswp3_rst 154 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 155 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 155 failed in run_test failed 
[RT] Error: Test control_atmwav 156 failed in check_result failed 
[RT] Error: Test control_atmwav 156 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 157 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 157 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 158 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 158 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 159 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 159 failed in run_test failed 
[RT] Error: Test regional_atmaq 160 failed in check_result failed 
[RT] Error: Test regional_atmaq 160 failed in run_test failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1099069436/20221108234515/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1099069436/20221109015618/ufs-weather-model
[RT] Error: Test regional_2threads 046 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by jkbk2004** [comment]
It sounds like cheyenne and jet have issue with regional_2threads. All other cases ran ok but regional_2threads.

**Comment by BrianCurtis-NOAA** [comment]
> It sounds like cheyenne and jet have issue with regional_2threads. All other cases ran ok but regional_2threads.

What is the issue?

**Comment by jkbk2004** [comment]
job is hanging and killed: PBS: job killed: walltime 992 exceeded limit 900

**Comment by BrianCurtis-NOAA** [comment]
> job is hanging and killed: PBS: job killed: walltime 992 exceeded limit 900

Does it take a long time in a specific part of the run? If it consistently is exceeding walltime, then it needs to be addressed in this PR, as the first assumption is that this PR is causing the issue.

**Comment by jkbk2004** [comment]
It finishes around 200 ~ 300 sec on hera and orion.

**Comment by DusanJovic-NOAA** [comment]
I can try to reproduce the regional_2threads test run on jet.

**Comment by jkbk2004** [comment]
> I can try to reproduce the regional_2threads test run on jet.

@DusanJovic-NOAA Awesome! I am trying to confirm about the number of nodes for the threads test on cheyenne. regional_control runs fine. Please, give a try and keep me posted.

**Comment by DusanJovic-NOAA** [comment]
The regional_2threads indeed times out after 900s. The regional_control finishes in ~460 seconds. The run with 2 threads should not run that much slower. Let me try to run (global) control vs control_2threads

**Comment by DusanJovic-NOAA** [comment]
I think we need to explicitly request multiple cpus per task when we run threaded tests. Let me try this change:
```diff
$ git diff fv3_conf/fv3_slurm.IN_jet
diff --git a/tests/fv3_conf/fv3_slurm.IN_jet b/tests/fv3_conf/fv3_slurm.IN_jet
index aecc783c..0790b5bf 100644
--- a/tests/fv3_conf/fv3_slurm.IN_jet
+++ b/tests/fv3_conf/fv3_slurm.IN_jet
@@ -36,7 +36,7 @@ export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"
 # Avoid job errors because of filesystem synchronization delays
 sync && sleep 1
 
-srun --label -n @[TASKS] ./fv3.exe
+srun --label -n @[TASKS] --cpus-per-task=@[THRD] ./fv3.exe
 
 echo "Model ended:    " `date`
 echo -n " $( date +%s )," >> job_timestamp.txt
```

**Comment by DusanJovic-NOAA** [comment]
With the above change in fv3_slurm.IN_jet the regional_2threads run finished in ~260sec.

**Comment by DusanJovic-NOAA** [comment]
I pushed the change to Ratko's branch. Please rerun the test on Jet.

**Comment by jkbk2004** [comment]
> I pushed the change to Ratko's branch. Please rerun the test on Jet.

@DusanJovic-NOAA Great! do you think --npernode will same thing for cheyenne's mpiexec_mpt? let me try.

**Comment by BrianCurtis-NOAA** [comment]
> I pushed the change to Ratko's branch. Please rerun the test on Jet.

@DusanJovic-NOAA is this something we should be doing on all machines we run that test on?

**Comment by DusanJovic-NOAA** [comment]
> > I pushed the change to Ratko's branch. Please rerun the test on Jet.
> 
> @DusanJovic-NOAA is this something we should be doing on all machines we run that test on?

We can test this change on other machines that are using slurm scheduler.

**Comment by DusanJovic-NOAA** [comment]
> > > I pushed the change to Ratko's branch. Please rerun the test on Jet.
> > 
> > 
> > @DusanJovic-NOAA is this something we should be doing on all machines we run that test on?
> 
> We can test this change on other machines that are using slurm scheduler.

I added `--cpus-per-task=@[THRD]` to hera job card template and ran 4 tests, control, control_2threads, regional and regional_2threads, and all tests passed.

**Comment by jkbk2004** [comment]
I am wondering one issue about the setup of TASKS/INPES/JNPES of regional_control/regional_2thread. On cheyenne, regional_control job_card sets `#PBS -l select=4:ncpus=36:mpiprocs=36 and mpiexec_mpt -p %g: -np 144 ./fv3.exe`  and
regional_2thread job_card sets `#PBS -l select=7:ncpus=18:mpiprocs=18 and mpiexec_mpt -p %g: -np 126 ./fv3.exe`. This doesn't makes a sense. Another problem is both cases set with `export TASKS=120`. The numbers don't match. @RatkoVasic-NOAA @DusanJovic-NOAA @BrianCurtis-NOAA It could be a bug on setting the cases on cheyenne.

**Comment by RatkoVasic-NOAA** [comment]
I don't know who set up cheyenne parameters originally. Most of us here don't have access to that machine.
Yes, those numbers look odd.
Can we just skip that test on cheyenne in rt.conf?

**Comment by jkbk2004** [comment]
I agree to turn off regional_2thread on cheyenne and move on for merging. I am going to create an issue about this. If all agrees, then probably we can start merging tomorrow morning. @DusanJovic-NOAA @BrianCurtis-NOAA what do you think?

**Comment by DusanJovic-NOAA** [comment]
> I am wondering one issue about the setup of TASKS/INPES/JNPES of regional_control/regional_2thread. On cheyenne, regional_control job_card sets `#PBS -l select=4:ncpus=36:mpiprocs=36 and mpiexec_mpt -p %g: -np 144 ./fv3.exe` and regional_2thread job_card sets `#PBS -l select=7:ncpus=18:mpiprocs=18 and mpiexec_mpt -p %g: -np 126 ./fv3.exe`. This doesn't makes a sense. Another problem is both cases set with `export TASKS=120`. The numbers don't match. @RatkoVasic-NOAA @DusanJovic-NOAA @BrianCurtis-NOAA It could be a bug on setting the cases on cheyenne.

The number of processes (-np) is calculated by multiplying number of nodes with number_of_tasks_per_node. So for regional_control that is 4\*36 = 144, for regional_2threads it is 7\*18 = 126.

wcoss2, is also using PBS. Try to set some of the pbs options specified there, specifically 'place=vscatter' and mpiexec options '-ppn @[TPN] -depth @[THRD]'. I do not know if mpiexec_mpt ob cheyenne is the same as mpiexec on wcoss.

I also do not have access to cheyenne.

**Comment by BrianCurtis-NOAA** [comment]
Let me give it a go on Cheyenne before we write off the RT on Cheyenne.

**Comment by BrianCurtis-NOAA** [comment]
```
diff --git a/tests/fv3_conf/fv3_qsub.IN_cheyenne b/tests/fv3_conf/fv3_qsub.IN_cheyenne
index 2cc648b8..b87293ce 100644
--- a/tests/fv3_conf/fv3_qsub.IN_cheyenne
+++ b/tests/fv3_conf/fv3_qsub.IN_cheyenne
@@ -4,7 +4,7 @@
 #PBS -N @[JBNME]
 #PBS -A @[ACCNR]
 #PBS -q @[QUEUE]
-#PBS -l select=@[NODES]:ncpus=@[TPN]:mpiprocs=@[TPN]
+#PBS -l select=@[NODES]:ncpus=@[TPN]:mpiprocs=@[TPN]:ompthreads=@[THRD]
 #PBS -l walltime=00:@[WLCLK]:00
 
 set -eux
@@ -34,7 +34,7 @@ export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"
 # Avoid job errors because of filesystem synchronization delays
 sync && sleep 1
 
-mpiexec_mpt -p %g: -np @[TASKS] ./fv3.exe
+mpiexec_mpt -p %g: -np @[TASKS] omplace ./fv3.exe
 
 echo "Model ended:    " `date`
 echo -n " $( date +%s )," >> job_timestamp.txt
```

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Please try those changes with a few tests and re-run the regional_2threads as well for the logs.

**Comment by jkbk2004** [comment]
> @jkbk2004 Please try those changes with a few tests and re-run the regional_2threads as well for the logs.

sure!

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
With @BrianCurtis-NOAA contribution of omplace, regional_2threads passes ok now. @DusanJovic-NOAA @RatkoVasic-NOAA @ChunxiZhang-NOAA this pr is ready.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
