### PR TITLE
Develop drag suite intent mods -- Changed UGWP diagnostic variable declaration intents from 'out' to 'inout'

### LINKED ISSUE #37: Possible correction to declaration intent for diagnostic variables in drag_suite.F90
# Description

The UGWP diagnostic variables listed below are declared with "intent(out)" in unified_ugwp.F90 (subroutine "unified_ugwp_run") and are initialized in the same subroutine.  These variables are then passed to subroutine "drag_suite_run".  In subroutine "drag_suite_run" (in drag_suite.F90), these variables are declared with "intent(out)", and then calculations are performed on most of the grid points.  If a grid point is skipped (mainly ocean points), then the initialized value holds.  Because of this, I believe the variables should be declared with "intent(inout)" instead of "intent(out)" in "drag_suite_run".

List of effected diagnostic variables:
dusfc_ms(:),dvsfc_ms(:), dusfc_bl(:),dvsfc_bl(:), dusfc_ss(:),dvsfc_ss(:), dusfc_fd(:),dvsfc_fd(:)
dtaux2d_ms(:,:),dtauy2d_ms(:,:),  dtaux2d_bl(:,:),dtauy2d_bl(:,:),dtaux2d_ss(:,:),dtauy2d_ss(:,:), dtaux2d_fd(:,:),dtauy2d_fd(:,:), 

## Steps to Reproduce

This "bug" does not appear to be causing any issues.  I changed the declaration in drag_suite.F90 from intent "out" to "inout", and there was no change in the results.  I'm not a computer scientist, but I believe the correct way is to declare the variables in drag_suite.F90 as "inout", since they come in to the subroutine already initialized.

Please let me know if this should indeed be changed and I can issue a PR with this minor change.

## Additional Context

* Machine:  Hera
* Compiler:  Intel
* Suite Definition File or Scheme: unified_ugwp

## Output

N/A

### PR DESCRIPTION
**Pull request by mdtoyNOAA**
## Description
This pull request fixes [Issue #37](https://github.com/ufs-community/ccpp-physics/issues/37) of the ufs-community/ccpp-physics repository.  The UGWP diagnostic variables (i.e., dusfc_ms, dvsfc_ms, tdaux2d_ms, datauy2d_ms, etc.) are declared with "intent(out)" and initialized in module unified_ugwp.F90, then they are passed to subroutine "drag_suite_run" (in drag_suite.F90).  In this subroutine, the UGWP diagnostic variables should have been declared with "intent(inout)" instead of "intent(out)".  This PR fixes this.
This PR does not change any results.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [x] No changes are expected to any regression test. 
- [ ] Changes are expected to the following tests: 

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

Dependent pull requests:
- https://github.com/NOAA-EMC/fv3atm/pull/627 (FV3ATM)
- https://github.com/ufs-community/ccpp-physics/pull/40   (CCPP-PHYSICS)

Related issue:
- fixes https://github.com/ufs-community/ccpp-physics/issues/37

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@mdtoyNOAA We are currently working on #1529. As discussed before, this pr can be combined to #1597. I will check again after we merge in #1529. We can coordinate with @binli2337 then.

**Comment by mdtoyNOAA** [comment]
> @mdtoyNOAA We are currently working on #1529. As discussed before, this pr can be combined to #1597. I will check again after we merge in #1529. We can coordinate with @binli2337 then.

@jkbk2004 Sounds good.

**Comment by DeniseWorthen** [comment]
It does not appear that the GNU suite was run. Also FV3 is out of date.

**Comment by mdtoyNOAA** [comment]
@jkbk2004 I've merged the latest changes to "ufs-weather-model" and "FV3ATM" in my fork.  Would you like me to retest Intel and test GNU?

**Comment by jkbk2004** [comment]
@mdtoyNOAA you are bringing in the change from gsl fork branches. It's a bit tricky. Easiest solution is to go with community develop and emc fv3 develop. Since this pr is small change, I think it's doable to re-create pr. What do you think? we are still working on #1529. There is enough time.

**Comment by mdtoyNOAA** [comment]
@jkbk2004 Actually, I am not bringing in changes from the GSL fork branches.  Although I did originally fork my ufs-weather-model repo from NOAA-GSL, the branches related to this PR are strictly based on the ufs-community repos.  To double check this, I just cloned my ufs-weather-model repo into a fresh directory and "git diffed" each component, i.e., ufs-weather-model, fv3atm, and ccpp/physics, and they are all synched (except for my "inout" mods) to the ufs-community repos/branches.  So, I shouldn't need to redo the PR.  Please let me know if you agree.

**Comment by jkbk2004** [comment]
> @jkbk2004 Actually, I am not bringing in changes from the GSL fork branches. Although I did originally fork my ufs-weather-model repo from NOAA-GSL, the branches related to this PR are strictly based on the ufs-community repos. To double check this, I just cloned my ufs-weather-model repo into a fresh directory and "git diffed" each component, i.e., ufs-weather-model, fv3atm, and ccpp/physics, and they are all synched (except for my "inout" mods) to the ufs-community repos/branches. So, I shouldn't need to redo the PR. Please let me know if you agree.

cool! sounds at least synching branch is working. Once we don't see conflictions to resolve, we are fine.

**Comment by jkbk2004** [comment]
@mdtoyNOAA hera is very slow from yesterday. Do you have access to Cheyenne? I can help to make a quick test on cheyenne with gnu.

**Comment by mdtoyNOAA** [comment]
> @mdtoyNOAA hera is very slow from yesterday. Do you have access to Cheyenne? I can help to make a quick test on cheyenne with gnu.

@jkbk2004 No, I don't have access to Cheyenne.

**Comment by jkbk2004** [comment]
@mdtoyNOAA let me give a quick test on cheyenne. Anyway, we like to start working on this pr today with combining to #1597

**Comment by jkbk2004** [comment]
[RegressionTests_cheyenne.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/10771626/RegressionTests_cheyenne.gnu.log)

cheyenn.gnu reproduces

**Comment by jkbk2004** [comment]
@mdtoyNOAA Ok! #1529 was merged in. So, we can start working to combine this pr to #1597. Can you sync up ccpp and fv3 one more time? I will ask @binli2337 to point to your fv3 branch in his pr.

**Comment by mdtoyNOAA** [comment]
@jkbk2004 I am working on it right now.  Can you confirm that there have been changes to the submodules 'WW3' and 'upp'?

**Comment by jkbk2004** [comment]
Yes, upp was update: https://github.com/NOAA-EMC/UPP/tree/b37f8ab7b0f298346d79a37e0c5d4a64037fd4d4
ww3 no update and the hash is still in last month: https://github.com/NOAA-EMC/WW3/tree/b93b9f00118f6fb316fd2289dff10b1455357f3f

**Comment by mdtoyNOAA** [comment]
Sorry, I meant ’NOAHMP-interface/noahmp’.

**Comment by jkbk2004** [comment]
Oh! you are correct. noah-mp was update.

**Comment by mdtoyNOAA** [comment]
@jkbk2004 I updated my UPP branch and it looks like the latest hash is '84cp0b8f', not 'b37f8ab7'.  Should I revert back to this older hash?


Gitlog below:

commit 84cb0b8ff4d72506edddff6204d00f39bc3f035a (HEAD, origin/develop, origin/HEAD)
Author: YaliMao-NOAA <53870326+YaliMao-NOAA@users.noreply.github.com>
Date:   Wed Feb 15 21:27:43 2023 -0500

    update gtg code revision (#632)
    
    Co-authored-by: yali mao <yali.mao@dlogin02.dogwood.wcoss2.ncep.noaa.gov>

commit ad56e5ca699728df7b300e3624807a6d21dcf186
Author: Gillian Petro <96886803+gspetro-NOAA@users.noreply.github.com>
Date:   Tue Feb 14 10:21:31 2023 -0500

    Update documentation for variables in CALGUST.f and CALHEL.f (#630)
    
    * Correct DEPTH param in CALHEL
    
    * add def for LPBL and ZPBL
    
    * reorder variables in header
    
    ---------
    
    Co-authored-by: gspetro <gillian.s.petro@gmail.com>

commit 8c7ca6f36a0347b457e5de89b3b40c79a87ca353
Author: EricJames-NOAA <eric.james@noaa.gov>
Date:   Mon Feb 13 18:09:04 2023 -0700

    Small changes to exp2 ceiling and SLP output (#629)
    
    * Correcting name of MAPS SLP variable in post_avblflds.xml, and removing from RRFS postxconfig file, and a slight change to exp2 ceiling diagnostic.
    
    * Small change to MDLFLD to make sure REFD at -10C still gets output after getting rid of MSLMA output.
    
    * Adding change logs.
    
    * Adding NCEP local use for MSLMA

commit b37f8ab7b0f298346d79a37e0c5d4a64037fd4d4
Author: WenMeng-NOAA <48260754+WenMeng-NOAA@users.noreply.github.com>
Date:   Mon Feb 13 09:43:43 2023 -0500

**Comment by jkbk2004** [comment]
upp b37f8ab7 is the one we are using.

**Comment by mdtoyNOAA** [comment]
@jkbk2004 Okay, I think I have it synched and pushed properly.  Let me know if it looks okay.  Thanks.

**Comment by jkbk2004** [comment]
@mdtoyNOAA one thing to confirm. this pr has not much to do with noahmp, right? Only code change comes from ccpp. So, @binli2337 can simply poin to your fv3 branch to combine the PRs, right?

**Comment by mdtoyNOAA** [comment]
That’s correct.  This PR has nothing to do with noahmp.

**Pull request closed without merging**
