### PR TITLE
Consider sea surface currents in air-sea flux calculation for ufs atmosphere-ocean coupling

### LINKED ISSUE #106: Update ccpp-physics used in CMEPS
The ccpp-physics component is updated to include a new option to consider sea surface current in the computation of air-sea fluxes. The ccpp-physics code used in CMEPS will need to be updated to be consistent with those changes in ccpp-physics.

### LINKED ISSUE #156: Consider sea surface ocean current in the estimation of air-sea fluxes
## Description
The surface layer scheme will be updated to include sea surface ocean current in the computation of air-sea fluxes.

## Solution
Several subroutines in ccpp-physics will be updated.

## Alternatives (optional)
If applicable, add a description of any alternative solutions or features you've considered.

## Related to (optional)

### LINKED ISSUE #312: Downscaling sea surface current field from parent grid to nested grid
**Is your feature request related to a problem? Please describe.**
The surface ocean current will be included in the computation of air-sea fluxes in both parent grid and nested grid. The code needs to be updated to transfer the surface current filed from parent grid to the nested grid.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Related PR: #311

### LINKED ISSUE #753: Consider surface ocean current in the computation of air-sea fluxes
## Description
The surface layer scheme will be updated to include surface ocean current in the computation of air-sea fluxes.

## Solution
The ccpp-physics, GFDL_atmos_cubed_sphere and fv3atm will be updated.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms? Yes, on Hera
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? The baseline results will not change.
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
https://github.com/ufs-community/ccpp-physics/pull/155

### LINKED ISSUE #1975: Enable taking into account sea surface current in atmosphere-ocean coupling
## Description

Currently, sea surface current (SSC) is not considered in ufs-weather-model atmosphere-ocean coupling. We would like to take into account the SSC impact on air-sea momentum and enthalpy flux calculations by using the SSC-relative winds.

## Solution

Passing SSC from ocean model component (e.g., MOM6) through CMEPS into FV3ATM, and within FV3ATM (and ccpp-physics) taking into consideration SSC when calculating air-sea momentum and enthalpy fluxes. Currently some HAFS developers (e.g., @binli2337) is working to enable this capability for the UFS HAFS application.

## Alternatives

Do not consider SSC impacts on atmosphere-ocean coupling.

## Related to

- fixed by ufs-community/ufs-weather-model/pull/2104
- fixed by NOAA-EMC/fv3atm/pull/755
- fixed by NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
- fixed by ufs-community/ccpp-physics/pull/155
- fixed by NOAA-EMC/CMEPS/pull/107

### PR DESCRIPTION
**Pull request by binli2337**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full RT suite (compared to current baselines) on either Hera/Derecho/Hercules AND have committed the log to my PR branch.
- [ ] Add list of all failed regression tests in "Regression Tests" section.

### Description

This PR adds capability of considering sea surface current's impact on air-sea flux calculation for atmosphere-ocean coupling.
### Commit Message

Enable the capability of considering sea surface current's impact on air-sea flux calculation for atmosphere-ocean coupling. A namelist option is added to control whether or not to use this feature (default is off). Fixes #1975

Co-authored by: @binli2337, @BinLiu-NOAA, @WeiguoWang-NOAA, @BijuThomas-NOAA, @hyunsookkim-NOAA, @XuLi-NOAA, @MariaAristizabal-NOAA, @JohnSteffen-NOAA

### Priority
- [ ] Critical Bugfix (This PR contains a critical bug fix and should be prioritized.)
- [x] High (This PR contains a feature or fix needed for a time-sensitive project (eg, retrospectives, implementations))
  - Needed for HAFSv2 upgrade code freeze
- [ ] Normal

### Blocking Dependencies

- requires https://github.com/NOAA-EMC/fv3atm/pull/755
- requires https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
- requires https://github.com/ufs-community/ccpp-physics/pull/155
- requires https://github.com/NOAA-EMC/CMEPS/pull/107

### Git Issues Fixed By This PR

- Closes ufs-community/ufs-weather-model/issues/1975
- Closes NOAA-EMC/fv3atm/issues/753
- Closes ufs-community/ccpp-physics/issues/156
- Closes NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/312
- Closes NOAA-EMC/CMEPS/issues/106

### Subcomponent (with links)

- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [x] CMEPS
  - NOAA-EMC/CMEPS/pull/107
- [ ] CMakeModules
- [x] FV3
  - NOAA-EMC/fv3atm/pull/755
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:
<details><summary>FAILED REGRESSION TESTS</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [ ] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
@binli2337 can you sync up branches? As we discussed, we will try to combine #2098 to this PR from physics PR level. I am moving to https://github.com/ufs-community/ccpp-physics/pull/155 to follow up there.

**Comment by BinLiu-NOAA** [comment]
> @binli2337 can you sync up branches? As we discussed, we will try to combine #2098 to this PR from physics PR level. I am moving to [ufs-community/ccpp-physics#155](https://github.com/ufs-community/ccpp-physics/pull/155) to follow up there.

@jkbk2004 This PR branch and all its submodules have been synced with their corresponding ufs-weather-model develop branch. Thanks!

**Comment by BinLiu-NOAA** [comment]
A quick follow-up is that, the full RT set went through on WCOSS2 successfully, confirming no answer changing for the baseline. 

Meanwhile, a note is that, the gnv1_nested_intel test failed in the first try during result checking/comparing against baseline, however the second try of the gnv1_nested_intel test succeeded without issues. Another note is that, I encountered the similar issue (first try failed, second run succeeded) for this gnv1_nested_intel test while testing another PR branch.

With that, I think this PR/branch is ready to proceed for next steps. Thanks!

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA We need Logs from Hera committed to the PR branch before proceeding (Hera adds GNU compile/test).

**Comment by zach1221** [comment]
> @BinLiu-NOAA We need Logs from Hera committed to the PR branch before proceeding (Hera adds GNU compile/test).

@DeniseWorthen I can run them, if needed to move forward. My ecflow seems to work ok on hera now.

**Comment by BinLiu-NOAA** [comment]
> > @BinLiu-NOAA We need Logs from Hera committed to the PR branch before proceeding (Hera adds GNU compile/test).
> 
> @DeniseWorthen I can run them, if needed to move forward. My ecflow seems to work ok on hera now.

Thanks, @zach1221!

**Comment by binli2337** [comment]
@DeniseWorthen Have you started the runs? I can do it.

**Comment by DeniseWorthen** [comment]
No, I have not started RTs (didn't think I needed to).

**Comment by BinLiu-NOAA** [comment]
@binli2337 and @DeniseWorthen, I just checked. And @zach1221 is currently running RTs on Hera for this PR. Thanks!

**Comment by zach1221** [comment]
> @binli2337 and @DeniseWorthen, I just checked. And @zach1221 is currently running RTs on Hera for this PR. Thanks!

Yes, I have them going. A little more than  halfway there.

**Comment by zach1221** [comment]
@binli2337 fyi, we're going to work PR #2098 currently and will work this one afterwards.

**Comment by zach1221** [comment]
Hera logs attached. No changes.

[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14103745/RegressionTests_hera.log)

**Comment by zach1221** [comment]
@binli2337 can you please sync up your branch here? We'll begin testing against this PR next.

**Comment by binli2337** [comment]
@zach1221 OK. Thanks!

**Comment by zach1221** [comment]
> @zach1221 OK. Thanks!

@binli2337 are you able to sync it up for us? There are still some conflicts with FV3.

**Comment by BinLiu-NOAA** [comment]
@zach1221 It should be synced right now. Thanks!

**Comment by BinLiu-NOAA** [comment]
@zach1221, wondering if this PR is ready for the final RT processing. Also, feel free to let us know if help is needed to run the full set of RTs on WCOSS2. Thanks!

**Comment by zach1221** [comment]
> @zach1221, wondering if this PR is ready for the final RT processing. Also, feel free to let us know if help is needed to run the full set of RTs on WCOSS2. Thanks!

Hi, @BinLiu-NOAA  sorry for the late reply. Yes, the tests are running. We're working to get them finished as soon as possible. Brian should be taking care of WCOSS tests.

**Comment by FernandoAndrade-NOAA** [comment]
In addition to `cpld_debug_gfsv17_intel`, the `hafs_regional_atm_ocn_wav_intel` test has also failed with a timeout on Jet. However, it should be noted the failure was properly reported on the test summary at the end.

**Comment by BinLiu-NOAA** [comment]
Much appreciated, @zach1221, @FernandoAndrade-NOAA, @BrianCurtis-NOAA! Hopefully, the RTs will go through smoothly. Thanks!

**Comment by zach1221** [comment]
Regression testing is complete. We can proceed with the merging process on ccpp-physics and cubed-sphere. 
@binli2337 @BinLiu-NOAA

**Comment by DeniseWorthen** [comment]
@binli2337  cmeps is merged [8cd4a32](https://github.com/NOAA-EMC/CMEPS/commit/8cd4a32809a68102b38b4001fc9d55b31bf5c1c1)

**Comment by zach1221** [comment]
@binli2337 fv3atm is merged now as well. https://github.com/NOAA-EMC/fv3atm/commit/8db821cb944f5a6f2586a42926434cca91fcac94

**Comment by binli2337** [comment]
@zach1221 I will merge FV3 now.

**Comment by binli2337** [comment]
It is ready for review. Thanks!

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Pull request merged**
