### PR TITLE
Feature: NSSL Microphysics support

### LINKED ISSUE #1079: Add NSSL microphysics to the CCPP
## Description
The NSSL MP scheme should be added to the authoritative CCPP repo because "the NSSL scheme is used in NSSL's daily FV3 convection-allowing forecasts, and the scheme itself is aimed at this scale (dx <= 4km). Testing is underway also with a preliminary Warn-on-Forecast FV3 ensemble", according to @MicroTed. The SRW App in particular needs this.

## Solution

- Add NSSL code to ccpp-physics
- Add support for additional hydrometeor species in GFDL_atmos_cubed_sphere
- Add support for new variables, etc. in fv3atm (particularly GFS_typedefs)
- Add SDFs as appropriate in fv3atm
- Add RTs to exercise the new scheme in ufs-weather-model

## Alternatives
None

## Related to
https://github.com/NCAR/ccpp-physics/pull/761
https://github.com/NOAA-EMC/fv3atm/pull/472
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/171
https://github.com/ufs-community/ufs-weather-model/pull/1032
https://github.com/NCAR/ccpp-scm/pull/277

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

From @MicroTed in https://github.com/NOAA-EMC/fv3atm/pull/472:
Supports CCPP with new NSSL microphysics scheme, which has separate hydrometeor categories for graupel and hail (Mansell et al. 2010, JAS). This PR allows fv3atm to compile correctly with CCPP+NSSL, but a further update to atmos_cubed_sphere is needed to run correctly. The NSSL scheme is used in NSSL's daily FV3 convection-allowing forecasts, and the scheme itself is aimed at this scale (dx <= 4km). Testing is underway also with a preliminary Warn-on-Forecast FV3 ensemble.

The NSSL scheme has namelist options to enable/disable the hail category (i.e., can be 6- or 7-class) and to enable/disable prediction of idealized CCN number concentration.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/1079

## Testing

Passed all existing RTs on Hera/intel. New RTs exercise the new scheme with and without hail and CCN.

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/761
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/171
https://github.com/NOAA-EMC/fv3atm/pull/472

### CODE REVIEW

**Comment by binli2337** [comment]
@grantfirl Please update your branch. This PR is next. Thanks.

**Comment by grantfirl** [comment]
> @grantfirl Please update your branch. This PR is next. Thanks.

This one is still a work in progress with respect to setting up regression test to use the new functionality, so it is still a draft PR. This and submodule branches will be updated when they're ready to review/test. I'll communicate when it is ready.

**Comment by grantfirl** [comment]
@binli2337 This is ready to start official testing.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/834905739/20220228030012/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220224/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by junwang-noaa** [comment]
@grantfirl Please change the BL_DATE to 20220228 in ufs-weather-model/tests/rt.sh? Thanks

**Comment by grantfirl** [comment]
> @grantfirl Please change the BL_DATE to 20220228 in ufs-weather-model/tests/rt.sh? Thanks

Done

**Comment by junwang-noaa** [comment]
@grantfirl The RT failed on wcoss dell. 8 compile jobs can't get compiled. We got error message:

ifort: error #10106: Fatal error in /gpfs/dell1/usrx/local/prod/intel/2018UP04/compilers_and_libraries_2018.5.274/linux/bin/intel64/fortcom, terminated by kill signal
compilation aborted for /gpfs/dell2/emc/modeling/noscrub/Jun.Wang/nems/vlab/20220228/ufs-weather-model/FV3/ccpp/data/GFS_typedefs.F90 (code 1)
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o] Error 1
make[1]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2

Bin Li tried to compile with your branch on dell, and he got same error. We need some time to debug.

RT passed on wcoss cray.

**Comment by grantfirl** [comment]
> 

OK, thanks for the update. Please let me know if I can be of any assistance, although I don't have wcoss access.

**Comment by climbfuji** [comment]
> OK, thanks for the update. Please let me know if I can be of any assistance, although I don't have wcoss access.

I can help tonight if needed.

**Comment by junwang-noaa** [comment]
@climbfuji That would be great, thank you very much! So far I don't see any obvious reason why it failed.

**Comment by kgerheiser** [comment]
I would try compiling with a different optimization level.

**Comment by junwang-noaa** [comment]
@kgerheiser That's good suggestion, actually all the debug jobs compiled successfully.

**Comment by MicroTed** [comment]
The 'terminated by kill signal' doesn't sound like a simple code error. Like it is hitting a wall time limit, perhaps? Do all 8 failures fail on the same file?

Would verbose output from make provide any more details?

**Comment by junwang-noaa** [comment]
Yes, all the filed compile jobs failed in GFS_typedefs.F90, I think the size of this file might be too big. It does not hit wall clock time.

Also we are using the largest memory on the transfer node.

**Comment by junwang-noaa** [comment]
@grantfirl @ChunxiZhang-NOAA @MicroTed @DomHeinzeller Currently the compile jobs are submitted to the transfer node to support simultaneous multiple builds. It can't work on login node or compute nodes. There is a memory limit on the transfer node. So here are two proposed solutions: 1) compile GFS_typedefs.F90 with optimization -O instead of -O2.  2) break GFS_typedefs.F90 into small files.  I think we can first try 1). Since the GFS_typedefs.F90 is processed in FV3/ccpp/config/ccpp_prebuild_config.py, would you please let me know how to change the optimization option for GFS_typedefs.F90 only? Thanks

**Comment by kgerheiser** [comment]
@junwang-noaa this looks like it will be an issue with #1074 as well. Turning down the optimization might work for this file, but it's likely to rear its head again.

To set compile flags for one file you can use this:
`set_source_files_properties(GFS_typedefs.F90 PROPERTIES COMPILE_FLAGS -O1)`

**Comment by climbfuji** [comment]
> @grantfirl @ChunxiZhang-NOAA @MicroTed @DomHeinzeller Currently the compile jobs are submitted to the transfer node to support simultaneous multiple builds. It can't work on login node or compute nodes. There is a memory limit on the transfer node. So here are two proposed solutions: 1) compile GFS_typedefs.F90 with optimization -O instead of -O2. 2) break GFS_typedefs.F90 into small files. I think we can first try 1). Since the GFS_typedefs.F90 is processed in FV3/ccpp/config/ccpp_prebuild_config.py, would you please let me know how to change the optimization option for GFS_typedefs.F90 only? Thanks

@junwang-noaa Sorry that I didn't work on this yesterday, I had access problems to wcoss. And Kyle (thanks @kgerheiser!) already figured out the problem. I can make the changes to compile `GFS_typedefs.F90` with `-O1` instead of `-O2`, but maybe removing just the AVX2 flags may be good enough. There isn't any real computation in this file, thus the impact will be negligible, regardless of the optimization level.

Another option is to reduce the number of build jobs, but I think it's already down to 3.

As @kgerheiser said the problem will come back inevitably if the memory is that small. The question is for how much longer the ufs-weather-model develop code will be tested and run on wcoss and which steps will allow us to bridge the time until we are all on wcoss2.

**Comment by climbfuji** [comment]
> @junwang-noaa this looks like it will be an issue with #1074 as well. Turning down the optimization might work for this file, but it's likely to rear its head again.
> 
> To set compile flags for one file you can use this: `set_source_files_properties(GFS_typedefs.F90 PROPERTIES COMPILE_FLAGS -O1)`

You have to do that in ccpp-physics, not in fv3atm, and the logic in there is a little more complicated, but it's not too difficult.

**Comment by grantfirl** [comment]
> > @grantfirl @ChunxiZhang-NOAA @MicroTed @DomHeinzeller Currently the compile jobs are submitted to the transfer node to support simultaneous multiple builds. It can't work on login node or compute nodes. There is a memory limit on the transfer node. So here are two proposed solutions: 1) compile GFS_typedefs.F90 with optimization -O instead of -O2. 2) break GFS_typedefs.F90 into small files. I think we can first try 1). Since the GFS_typedefs.F90 is processed in FV3/ccpp/config/ccpp_prebuild_config.py, would you please let me know how to change the optimization option for GFS_typedefs.F90 only? Thanks
> 
> @junwang-noaa Sorry that I didn't work on this yesterday, I had access problems to wcoss. And Kyle (thanks @kgerheiser!) already figured out the problem. I can make the changes to compile `GFS_typedefs.F90` with `-O1` instead of `-O2`, but maybe removing just the AVX2 flags may be good enough. There isn't any real computation in this file, thus the impact will be negligible, regardless of the optimization level.
> 
> Another option is to reduce the number of build jobs, but I think it's already down to 3.
> 
> As @kgerheiser said the problem will come back inevitably if the memory is that small. The question is for how much longer the ufs-weather-model develop code will be tested and run on wcoss and which steps will allow us to bridge the time until we are all on wcoss2.

Thanks @climbfuji. I'm following this discussion to learn from those more knowledgeable in the UFS build system to potentially be of more help in the future. Out of curiosity, following @kgerheiser and @climbfujji responses, one would simply add the proposed change near the following line: https://github.com/NOAA-EMC/fv3atm/blob/develop/ccpp/CMakeLists.txt#L118? Or somewhere else?

**Comment by DomHeinzeller** [comment]
I’ll try to send you the changes before my next meeting in 20mins ...

**Comment by MicroTed** [comment]
Does module_mp_nssl_2mom.F90 compile successfully? Or does it not get to that point yet. It has almost 20k lines of code, but maybe the structure is simpler.

**Comment by junwang-noaa** [comment]
Currently each compile job will take one transfer node. So it does not matter how many compile jobs run at the same time. A single compile job also failed with the same error. Dom, will you submit a PR in ccpp-physics to compile GFS_typedefs.F90 with -O1? Since we are still supporting dell at this time, we need to fix the issue before we can commit the code. Meanwhile, I do think we may need to consider rewriting the GFS_typedefs.F90 to smaller files, maybe one data type for each file.

**Comment by climbfuji** [comment]
> Currently each compile job will take one transfer node. So it does not matter how many compile jobs run at the same time. A single compile job also failed with the same error. Dom, will you submit a PR in ccpp-physics to compile GFS_typedefs.F90 with -O1? Since we are still supporting dell at this time, we need to fix the issue before we can commit the code. Meanwhile, I do think we may need to consider rewriting the GFS_typedefs.F90 to smaller files, maybe one data type for each file.

Sorry for not being clear. I was talking about this (the make -j argument). You could reduce it from 4 to 2 and see if that helps.
```
if [[ $MACHINE_ID == cheyenne.* ]] ; then
    BUILD_JOBS=${BUILD_JOBS:-3}
elif [[ $MACHINE_ID == wcoss_dell_p3 ]] ; then
    BUILD_JOBS=${BUILD_JOBS:-4}
    source $PATHTR/tests/module-setup.sh
fi

BUILD_JOBS=${BUILD_JOBS:-8}
```

**Comment by climbfuji** [comment]
Won’t be able to get this in until the top of the hour … stay tuned.

**Comment by junwang-noaa** [comment]
The compile failed when there is only one compile job in rt.conf. Currently I have been running following rt.conf without success:

COMPILE | -DAPP=S2SW -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1,FV3_GFS_v16_coupled_p7_rrtmgp,FV3_GFS_v16_coupled_p8      | - wcoss_cray                            | fv3 |
RUN     | cpld_control_p8                                                                                                         | - wcoss_cray                            | fv3 |

**Comment by DomHeinzeller** [comment]
This is NOT about the number of compile jobs. This is about the number of threads that make uses to build in parallel.

**Comment by junwang-noaa** [comment]
@DomHeinzeller Thanks, changing BUILD_JOBS from 4 to 1 (one dell only), the compile job works. I am using that setting to create baseline on dell now.

**Comment by junwang-noaa** [comment]
I saw some compile jobs failed with BUILD_JOBS=1, the same error message:

+ make -j 1 VERBOSE=1
/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/bin64/mpiifort: line 745: 35295 Bus error               (core dumped) ifort -DFV3 -DINTERNAL_FILE_NML -DMOIST_CAPPA -DMPI -DNEMS_GSM -DOVERLOAD_R4 -DUSE_COND -I/gpfs/dell2/ptmp/Jun.Wang/FV3_RT/rt_29931/compile_001/build_fv3_001/FV3/ccpp/physics -I/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.5.274/w3nco/2.4.1/include_d -I/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.5.274/impi-18.0.1/netcdf/4.7.4/include -g '-traceback' '-fpp' '-fno-alias' '-auto' '-safe-cray-ptr' '-ftz' '-assume' 'byterecl' '-nowarn' '-sox' '-align' 'array64byte' '-qno-opt-dynamic-align' '-O2' '-debug' 'minimal' '-fp-model' 'source' '-qoverride-limits' '-qopt-prefetch=3' '-march=core-avx2' '-O2' '-fPIC' '-real-size' 64 '-no-prec-div' '-no-prec-sqrt' '-qopenmp' -c /gpfs/dell2/emc/modeling/noscrub/Jun.Wang/nems/vlab/20220228/test/ufs-weather-model/FV3/ccpp/data/GFS_typedefs.F90 -o 'CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o' -I/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/intel64/include -I/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/intel64/include
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o] Error 135
make[2]: *** Deleting file `FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o'
make[1]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2

**Comment by junwang-noaa** [comment]
I think we do need the optimization change for GFS_typedefs.F90

**Comment by junwang-noaa** [comment]
> @junwang-noaa this looks like it will be an issue with #1074 as well. Turning down the optimization might work for this file, but it's likely to rear its head again.
> 
> To set compile flags for one file you can use this: `set_source_files_properties(GFS_typedefs.F90 PROPERTIES COMPILE_FLAGS -O1)`

The compile still failed when adding this line in FV3/ccpp/CMakeLists.txt or FV3/ccpp/physics/CMakeLists.txt. It looks to me the  GFS_typedefs.F90 is processed through FV3/ccpp/config/ccpp_prebuild_config.py and the build.make file is created afterwards.

**Comment by climbfuji** [comment]
Yes, this doesn’t work because there is a path associated with the file, and that path is host-model dependent.

**Comment by junwang-noaa** [comment]
@DomHeinzeller I added your fix, it does not work. The compile line has both -O2 and -O1. The error message is:

+ make -j 1 VERBOSE=1
/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/bin64/mpiifort: line 745:  7956 Bus error               (core dumped) ifort -DFV3 -DINTERNAL_FILE_NML -DMOIST_CAPPA -DMPI -DNEMS_GSM -DOVERLOAD_R4 -DUSE_COND -I/gpfs/dell2/ptmp/Jun.Wang/FV3_RT/rt_53381/compile_001/build_fv3_001/FV3/ccpp/physics -I/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.5.274/w3nco/2.4.1/include_d -I/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.5.274/impi-18.0.1/netcdf/4.7.4/include -g '-traceback' '-fpp' '-fno-alias' '-auto' '-safe-cray-ptr' '-ftz' '-assume' 'byterecl' '-nowarn' '-sox' '-align' 'array64byte' '-qno-opt-dynamic-align' '-O2' '-debug' 'minimal' '-fp-model' 'source' '-qoverride-limits' '-qopt-prefetch=3' '-march=core-avx2' '-O2' '-fPIC' '-real-size' 64 '-no-prec-div' '-no-prec-sqrt' '-qopenmp' '-O1' -c /gpfs/dell2/emc/modeling/noscrub/Jun.Wang/nems/vlab/20220228/test/ufs-weather-model/FV3/ccpp/data/GFS_typedefs.F90 -o 'CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o' -I/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/intel64/include -I/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/intel64/include
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o] Error 135
make[2]: *** Deleting file `FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o'
make[1]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2
make: *** [all] Error 2

**Comment by climbfuji** [comment]
> @DomHeinzeller I added your fix, it does not work. The compile line has both -O2 and -O1. The error message is:
> 
> * make -j 1 VERBOSE=1
>   /usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/bin64/mpiifort: line 745:  7956 Bus error               (core dumped) ifort -DFV3 -DINTERNAL_FILE_NML -DMOIST_CAPPA -DMPI -DNEMS_GSM -DOVERLOAD_R4 -DUSE_COND -I/gpfs/dell2/ptmp/Jun.Wang/FV3_RT/rt_53381/compile_001/build_fv3_001/FV3/ccpp/physics -I/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.5.274/w3nco/2.4.1/include_d -I/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.5.274/impi-18.0.1/netcdf/4.7.4/include -g '-traceback' '-fpp' '-fno-alias' '-auto' '-safe-cray-ptr' '-ftz' '-assume' 'byterecl' '-nowarn' '-sox' '-align' 'array64byte' '-qno-opt-dynamic-align' '-O2' '-debug' 'minimal' '-fp-model' 'source' '-qoverride-limits' '-qopt-prefetch=3' '-march=core-avx2' '-O2' '-fPIC' '-real-size' 64 '-no-prec-div' '-no-prec-sqrt' '-qopenmp' '-O1' -c /gpfs/dell2/emc/modeling/noscrub/Jun.Wang/nems/vlab/20220228/test/ufs-weather-model/FV3/ccpp/data/GFS_typedefs.F90 -o 'CMakeFiles/ccpp_physics.dir/**/data/GFS_typedefs.F90.o' -I/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/intel64/include -I/usrx/local/prod/intel/2018UP04/compilers_and_libraries/linux/mpi/intel64/include
>   make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/**/data/GFS_typedefs.F90.o] Error 135
>   make[2]: *** Deleting file `FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/__/data/GFS_typedefs.F90.o'
>   make[1]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/all] Error 2
>   make: *** [all] Error 2

The fix "works", because it adds `-O1` after `-O2` - but it doesn't solve the problem on wcoss :-(

We can try `-O0` instead or something more complicated (remove AVX2 flags, for example).

**Comment by junwang-noaa** [comment]
@grantfirl @DomHeinzeller With Dom's update in ccpp/physics/CMakelists.txt, the baseline creation finished successfully on dell. I will run final RT when your ufs-weather-model branch is updated.

**Comment by grantfirl** [comment]
@junwang-noaa The ufs-weather-model PR branch has been updated with https://github.com/NCAR/ccpp-physics/pull/869 and should be ready for final testing.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/834905739/20220303193034/ufs-weather-model
Please make changes and add the following label back: hera-gnu-RT

**Comment by grantfirl** [comment]
Did something happen to Hera? It looks like hera-gnu failed but I can't find the path from the autort notification and hera-intel is apparently still going?

**Comment by junwang-noaa** [comment]
I can't find the code directory either. Let's resubmit it. The cray and dell log files are on hera at:

/scratch1/NCEPDEV/stmp2/Jun.Wang/wcosslog

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@grantfirl would you please commit CCPP PR? Thanks

**Comment by grantfirl** [comment]
> @grantfirl would you please commit CCPP PR? Thanks

Gladly. Done.

**Comment by junwang-noaa** [comment]
Thanks, after Lauren commits dycore PR, we will need Ted to update his fv3atm branch.

**Comment by MicroTed** [comment]
@junwang-noaa OK, I'll try to keep an eye out on that

**Comment by junwang-noaa** [comment]
@grantfirl Would you please add an issue in ufs-weather-model issue page (https://github.com/ufs-community/ufs-weather-model/issues/new/choose) for this PR? According to [github issue doc](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) :"Issues let you track your work on GitHub, where development happens". It includes both bug fixes and new features. Every the ufs-weather-model PR needs to have an issue associated with it. Thanks

**Comment by grantfirl** [comment]
> @grantfirl Would you please add an issue in ufs-weather-model issue page (https://github.com/ufs-community/ufs-weather-model/issues/new/choose) for this PR? According to [github issue doc](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) :"Issues let you track your work on GitHub, where development happens". It includes both bug fixes and new features. Every the ufs-weather-model PR needs to have an issue associated with it. Thanks

OK, done. Fixes #1079

**Comment by junwang-noaa** [comment]
@grantfirl The FV3 PR is merged, revision: [47d391c](https://github.com/NOAA-EMC/fv3atm/commit/47d391c09a9b7a8c6fe5fff76c61921487891785)

**Pull request merged**
