### PR TITLE
Jet build config update, Hera GNU support, FV3 dycore GNU bugfix

### PR DESCRIPTION
**Pull request by climbfuji**
This PR contains
- an update to fix GNU compiler issues for the FV3 dycore (GFDL_atmos_cubed_sphere)
- support for using the GNU compiler on Hera (Update modulefile for hera.gnu #147)
- an update of `build.sh` from branch release/public-v1
- an update/bugfix for the Jet build config to pass the correct SIMD flags to CCPP

Associated PRs:
https://github.com/ufs-community/ufs-weather-model/pull/151/files
https://github.com/NOAA-EMC/fv3atm/pull/131
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/22

For regression testing information, see below **NOT YET**.

### CODE REVIEW

**Comment by climbfuji** [comment]
This code compiles on macOS with gcc+gfortran and clang+gfortran, with Python 2.7 and 3.7.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA do you want to enable hera.gnu as tier-1 platform with this PR? If so, please rsync /scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_GNU/ to /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20200611/GNU/

Please let me know. Thanks!

**Comment by DusanJovic-NOAA** [comment]
> @junwang-noaa @DusanJovic-NOAA do you want to enable hera.gnu as tier-1 platform with this PR? If so, please rsync /scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_GNU/ to /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20200611/GNU/
> 
> Please let me know. Thanks!

Yes.

Synced to develop-20200611/GNU

**Comment by climbfuji** [comment]
Regression testing on hera.intel using rt.conf: all tests pass, regression test logs updated in the PR.

[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/4806757/rt_hera_intel.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_gnu.conf`: all tests pass, regression test logs updated in the PR.

[rt_hera_gnu_create.log](https://github.com/ufs-community/ufs-weather-model/files/4806844/rt_hera_gnu_create.log)
[rt_hera_gnu_verify.log](https://github.com/ufs-community/ufs-weather-model/files/4806845/rt_hera_gnu_verify.log)

**Comment by climbfuji** [comment]
Regression testing on orion.intel, wcoss_cray and wcoss_dell_p3 all pass. Regression test logs updated in the PR.

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
