### PR TITLE
Thompson subcycling for develop, add missing hera.gnu debug modulefile

### LINKED ISSUE #596: Implement subcycling capability for Thompson microphysics
## Description

Thompson microphysics is less stable than GFDDL MP at long time steps used by the UFS, not only but in particular due to the missing fast physics calls in the FV3 dycore.

A duct tape solution thus far was to apply a tendency limiter that put a cap on the heating rates coming out of Thompson MP. This is unphysical and has in the past, when using too restrictive values, inhibited the formation of hurricanes etc.

## Solution

One possible solution is to leverage the subcycling capability in CCPP to call Thompson MP with a higher frequency (i.e. shorter time step) than the rest of the physics. This should allow us to remove the tendency limiter and let the microphysics do its job as it should.

## Alternatives

Alternative solutions are currently explored such as constraining Thompson MP in a different way than the basic tendency limiter.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

Implement a subcycling capability for Thompson MP in CCPP and exercise it in the UFS regression tests. This ufs-weather-model PR only updates the submodule pointer for fv3atm for the changes w.r.t. Thompson MP described in the associated PRs below.

Additional changes:
- add missing modulefile `ufs_hera.gnu_debug`
- bugfix in `compile.sh` to copy the correct modulefile when DEBUG is used

The changes to the suite FV3_GSD_noah/FV3_GFS_v16_thompspn (run Thompson MP with 4/2 subcycles) change the answer of several Thompson MP based regression tests. No new input data required.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/596

## Testing

Preliminary regression testing on Hera with GNU and Intel against existing baseline (2021/05/26): all tests that are expected to pass do pass, and all tests that are expected to fail do fail with b4b mismatches (but they all run to completion):

[rt_hera_gnu_verify_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/6549235/rt_hera_gnu_verify_against_existing.log)
[rt_hera_gnu_verify_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/6549236/rt_hera_gnu_verify_against_existing_fail_test.log)

[rt_hera_initel_verify_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/6549237/rt_hera_initel_verify_against_existing.log)
[rt_hera_initel_verify_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/6549238/rt_hera_initel_verify_against_existing_fail_test.log)

Full regression tests will be run on all tier-1 platforms when it is time to commit.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

https://github.com/NCAR/ccpp-framework/pull/379
https://github.com/NCAR/ccpp-physics/pull/676
https://github.com/NOAA-EMC/fv3atm/pull/328
https://github.com/ufs-community/ufs-weather-model/pull/632

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/666296517/20210609150010/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_37383
Test fv3_HAFS_v0_hwrf_thompson_debug 024 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 025 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 012 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 013 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 017 failed in run_test failed 
Test regional_control_debug 015 failed in run_test failed 
Test fv3_gsd_debug 018 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 016 failed in run_test failed 
Test control_thompson_no_aero_debug 020 failed in run_test failed 
Test control_thompson 005 failed in run_test failed 
Test control_thompson_debug 019 failed in run_test failed 
Test control_thompson_no_aero 006 failed in run_test failed 
Test fv3_gsd 009 failed in run_test failed 
Test fv3_rrfs_v1alpha 010 failed in run_test failed 
Test fv3_rrfs_v1beta 011 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-BL

**Comment by climbfuji** [comment]
> Machine: cheyenne
> Compiler: gnu
> Job: BL
> Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/666296517/20210609150010/ufs-weather-model
> Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_37383
> Test fv3_HAFS_v0_hwrf_thompson_debug 024 failed in run_test failed
> Test fv3_esg_HAFS_v0_hwrf_thompson_debug 025 failed in run_test failed
> Test fv3_HAFS_v0_hwrf_thompson 012 failed in run_test failed
> Test fv3_esg_HAFS_v0_hwrf_thompson 013 failed in run_test failed
> Test fv3_rrfs_v1beta_debug 017 failed in run_test failed
> Test regional_control_debug 015 failed in run_test failed
> Test fv3_gsd_debug 018 failed in run_test failed
> Test fv3_rrfs_v1alpha_debug 016 failed in run_test failed
> Test control_thompson_no_aero_debug 020 failed in run_test failed
> Test control_thompson 005 failed in run_test failed
> Test control_thompson_debug 019 failed in run_test failed
> Test control_thompson_no_aero 006 failed in run_test failed
> Test fv3_gsd 009 failed in run_test failed
> Test fv3_rrfs_v1alpha 010 failed in run_test failed
> Test fv3_rrfs_v1beta 011 failed in run_test failed
> Please make changes and add the following label back:
> cheyenne-gnu-BL

@BrianCurtis-NOAA this is because you stopped them because of the GitHub token change, correct?

**Comment by BrianCurtis-NOAA** [comment]
I haven't stopped anything yet. and haven't switched accesstoken on Cheyenne either.

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/666296517/20210609210014/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_8771
Test fv3_esg_HAFS_v0_hwrf_thompson 041 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 041 failed in run_test failed 
Test control_thompson 026 failed failed 
Test control_thompson 026 failed in run_test failed 
Test control_thompson_no_aero 027 failed failed 
Test control_thompson_no_aero 027 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 040 failed failed 
Test fv3_HAFS_v0_hwrf_thompson 040 failed in run_test failed 
Test regional_control 029 failed failed 
Test regional_control 029 failed in run_test failed 
Test regional_quilt_netcdf_parallel 033 failed failed 
Test regional_quilt_netcdf_parallel 033 failed in run_test failed 
Test regional_quilt 031 failed failed 
Test regional_quilt 031 failed in run_test failed 
Test regional_quilt_hafs 032 failed failed 
Test regional_quilt_hafs 032 failed in run_test failed 
Test regional_quilt_RRTMGP 034 failed failed 
Test regional_quilt_RRTMGP 034 failed in run_test failed 
Test fv3_rrfs_v1beta 039 failed failed 
Test fv3_rrfs_v1beta 039 failed in run_test failed 
Test fv3_rrfs_v1alpha 036 failed failed 
Test fv3_rrfs_v1alpha 036 failed in run_test failed 
Test fv3_gsd 035 failed failed 
Test fv3_gsd 035 failed in run_test failed 
Test fv3_hrrr 038 failed failed 
Test fv3_hrrr 038 failed in run_test failed 
Test fv3_rap 037 failed failed 
Test fv3_rap 037 failed in run_test failed 
Test cpld_control_c192 003 failed in run_test failed 
Test cpld_control_c384 004 failed in run_test failed 
Test datm_debug_cfsr 069 failed in run_test failed 
Test cpld_bmark_wave_v16 007 failed in run_test failed 
Test cpld_bmark_v16_nsst 006 failed in run_test failed 
Test cpld_bmark_v16 005 failed in run_test failed 
Test cpld_bmark_wave_v16_noahmp 008 failed in run_test failed 
Test control_merra2 019 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 013 failed in run_test failed 
Test control_stochy 015 failed in run_test failed 
Test control_lndp 017 failed in run_test failed 
Test control_lheatstrg 018 failed in run_test failed 
Test control_ca 016 failed in run_test failed 
Test control 011 failed in run_test failed 
Test datm_cdeps_debug_cfsr 075 failed in run_test failed 
Test control_CubedSphereGrid 012 failed in run_test failed 
Test control_c192 014 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/666296517/20210609160019/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_101837
Test fv3_rap 039 failed in run_test failed 
Test fv3_rrfs_v1alpha 038 failed in run_test failed 
Test fv3_rrfs_v1beta 041 failed in run_test failed 
Test fv3_gsd 037 failed in run_test failed 
Test fv3_hrrr 040 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/666296517/20210609151508/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_73241
Test regional_quilt_RRTMGP 034 failed failed 
Test regional_quilt_RRTMGP 034 failed in run_test failed 
Test regional_quilt_netcdf_parallel 033 failed in run_test failed 
Test regional_quilt_hafs 032 failed in run_test failed 
Test regional_quilt 031 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 040 failed in run_test failed 
Test regional_control 029 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 041 failed in run_test failed 
Test fv3_rap 037 failed in run_test failed 
Test fv3_gsd 035 failed in run_test failed 
Test fv3_rrfs_v1alpha 036 failed in run_test failed 
Test fv3_hrrr 038 failed in run_test failed 
Test fv3_rrfs_v1beta 039 failed in run_test failed 
Test control_thompson_no_aero 027 failed in run_test failed 
Test control_thompson 026 failed in run_test failed 
Test datm_cdeps_mx025_gefs 076 failed in run_test failed 
Test datm_cdeps_control_gefs 072 failed in run_test failed 
Test datm_cdeps_control_cfsr 071 failed in run_test failed 
Test datm_cdeps_bulk_cfsr 073 failed in run_test failed 
Test datm_cdeps_bulk_gefs 074 failed in run_test failed 
Test cpld_control_wave 009 failed in run_test failed 
Test datm_debug_cfsr 070 failed in run_test failed 
Test datm_cdeps_debug_cfsr 077 failed in run_test failed 
Test datm_mx025_gefs 069 failed in run_test failed 
Test datm_cdeps_mx025_cfsr 075 failed in run_test failed 
Test cpld_bmark_wave_v16 007 failed in run_test failed 
Test cpld_bmark_wave_v16_noahmp 008 failed in run_test failed 
Test control_c384gdas 016 failed in run_test failed 
Test cpld_bmark_v16_nsst 006 failed in run_test failed 
Test cpld_bmark_v16 005 failed in run_test failed 
Test datm_mx025_cfsr 068 failed in run_test failed 
Test cpld_control_c192 003 failed in run_test failed 
Test datm_bulk_gefs 067 failed in run_test failed 
Test cpld_control_c384 004 failed in run_test failed 
Test control_c192 014 failed in run_test failed 
Test control_c384 015 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by MinsukJi-NOAA** [comment]
Both Dell and Cray baseline creation jobs are failing.
On Cray,
```
FAILED TESTS: 
Test fv3_gsd 023 failed failed 
Test fv3_gsd 023 failed in run_test failed 
Test fv3_rrfs_v1alpha 024 failed failed 
Test fv3_rrfs_v1alpha 024 failed in run_test failed 
Test fv3_rrfs_v1beta 027 failed failed 
Test fv3_rrfs_v1beta 027 failed in run_test failed 
Test fv3_hrrr 026 failed failed 
Test fv3_hrrr 026 failed in run_test failed 
Test fv3_rap 025 failed failed 
Test fv3_rap 025 failed in run_test failed 
Test regional_quilt 019 failed failed 
Test regional_quilt 019 failed in run_test failed 
Test regional_control 017 failed failed 
Test regional_control 017 failed in run_test failed 
Test regional_quilt_hafs 020 failed failed 
Test regional_quilt_hafs 020 failed in run_test failed 
Test regional_quilt_netcdf_parallel 021 failed failed 
Test regional_quilt_netcdf_parallel 021 failed in run_test failed 
Test regional_quilt_RRTMGP 022 failed failed 
Test regional_quilt_RRTMGP 022 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 028 failed failed 
Test fv3_HAFS_v0_hwrf_thompson 028 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 029 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 029 failed in run_test failed 
```
Example error messages are:
```
 af create fcst fieldbundle, name=atmrc=           0   
 af create fcst fieldbundle, name=sfc_nearest_stodrc=           0   
 af create fcst fieldbundle, name=sfc_bilinearrc=           0   
 in fcst,init total time:    5.90406203269958    
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source    
fv3.exe            00000000036BD12D  Unknown               Unknown  Unknown
fv3.exe            0000000003F7A4C0  Unknown               Unknown  Unknown
fv3.exe            00000000034245C3  module_mp_thompso        1418  module_mp_thompson.F90
fv3.exe            0000000003450F44  mp_thompson_mp_mp         587  mp_thompson.F90
fv3.exe            000000000303A788  ccpp_fv3_gsd_v0_p        2726  ccpp_FV3_GSD_v0_physics_cap.F90
fv3.exe            0000000002F5C1E2  ccpp_static_api_m         664  ccpp_static_api.F90
fv3.exe            0000000002F5A1D1  ccpp_driver_mp_cc         188  CCPP_driver.F90
```
I am trying again on Cray right now.
regional_control on CI also failed: https://github.com/ufs-community/ufs-weather-model/runs/2788036632?check_suite_focus=true

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/666296517/20210609214514/ufs-weather-model
Please make changes and add the following label back:
jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/666296517/20210609210013/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_43666
Baseline creation and move successful
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/666296517/20210609214529/ufs-weather-model
Please make changes and add the following label back:
jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
OK. I'm not sure if it was my auth token being old, but either way the updated AutoRT auth tokens are set and i've restarted all AutoRT jobs through labels. If there are any failures from here, then most likely it is a code issue and not AutoRT failure.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/666296517/20210609154508/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_69021
Test fv3_HAFS_v0_hwrf_thompson_debug 024 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 025 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 012 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 013 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 017 failed in run_test failed 
Test fv3_rrfs_v1alpha 010 failed in run_test failed 
Test fv3_gsd_debug 018 failed in run_test failed 
Test regional_control_debug 015 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 016 failed in run_test failed 
Test fv3_rrfs_v1beta 011 failed in run_test failed 
Test fv3_gsd 009 failed in run_test failed 
Test control_thompson_debug 019 failed in run_test failed 
Test control_thompson_no_aero_debug 020 failed in run_test failed 
Test control_thompson 005 failed in run_test failed 
Test control_thompson_no_aero 006 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
Note sure how helpful this is:
I've went through 4 of those tests and they all have a lot of
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/666296517/20210609214522/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_7787
Test fv3_gsd 035 failed failed 
Test fv3_gsd 035 failed in run_test failed 
Test fv3_rrfs_v1alpha 036 failed failed 
Test fv3_rrfs_v1alpha 036 failed in run_test failed 
Test fv3_hrrr 038 failed failed 
Test fv3_hrrr 038 failed in run_test failed 
Test fv3_rrfs_v1beta 039 failed failed 
Test fv3_rrfs_v1beta 039 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 040 failed failed 
Test fv3_HAFS_v0_hwrf_thompson 040 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 041 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 041 failed in run_test failed 
Test regional_quilt_hafs 032 failed failed 
Test regional_quilt_hafs 032 failed in run_test failed 
Test regional_control 029 failed failed 
Test regional_control 029 failed in run_test failed 
Test regional_quilt 031 failed failed 
Test regional_quilt 031 failed in run_test failed 
Test regional_quilt_RRTMGP 034 failed failed 
Test regional_quilt_RRTMGP 034 failed in run_test failed 
Test regional_quilt_netcdf_parallel 033 failed failed 
Test regional_quilt_netcdf_parallel 033 failed in run_test failed 
Test fv3_rap 037 failed failed 
Test fv3_rap 037 failed in run_test failed 
Test control_thompson 026 failed failed 
Test control_thompson 026 failed in run_test failed 
Test control_thompson_no_aero 027 failed failed 
Test control_thompson_no_aero 027 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by MinsukJi-NOAA** [comment]
The exact same tests failed again on Cray.

On Dell, these failed (all overlap with Cray failed jobs):
fv3_gsd, fv3_rrfs_v1alpha, fv3_rrfs_v1beta, fv3_hrrr, fv3_rap, regional_control, regional_quilt, regional_quilt_hafs, regional_quilt_netcdf_parallel, regional_quilt_RRTMGP

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/666296517/20210609164515/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_275485
Test control_thompson_no_aero 029 failed failed 
Test control_thompson 028 failed failed 
Test control_thompson_no_aero 029 failed in run_test failed 
Test control_thompson 028 failed in run_test failed 
Test fv3_gsd 037 failed failed 
Test fv3_gsd 037 failed in run_test failed 
Test fv3_rrfs_v1alpha 038 failed failed 
Test fv3_rrfs_v1alpha 038 failed in run_test failed 
Test regional_control 031 failed failed 
Test regional_control 031 failed in run_test failed 
Test regional_quilt 033 failed failed 
Test regional_quilt 033 failed in run_test failed 
Test regional_quilt_hafs 034 failed failed 
Test regional_quilt_hafs 034 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 042 failed failed 
Test fv3_HAFS_v0_hwrf_thompson 042 failed in run_test failed 
Test fv3_rap 039 failed failed 
Test fv3_hrrr 040 failed failed 
Test fv3_rap 039 failed in run_test failed 
Test fv3_hrrr 040 failed in run_test failed 
Test fv3_rrfs_v1beta 041 failed failed 
Test fv3_rrfs_v1beta 041 failed in run_test failed 
Test regional_quilt_netcdf_parallel 035 failed failed 
Test regional_quilt_netcdf_parallel 035 failed in run_test failed 
Test regional_quilt_RRTMGP 036 failed failed 
Test regional_quilt_RRTMGP 036 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 043 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 043 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/666296517/20210609160011/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_25460
Test regional_quilt_hafs 032 failed in run_test failed 
Test regional_quilt 031 failed in run_test failed 
Test regional_control 029 failed in run_test failed 
Test regional_quilt_netcdf_parallel 033 failed in run_test failed 
Test regional_quilt_RRTMGP 034 failed in run_test failed 
Test fv3_rrfs_v1alpha 036 failed in run_test failed 
Test fv3_rap 037 failed in run_test failed 
Test fv3_rrfs_v1beta 039 failed in run_test failed 
Test fv3_hrrr 038 failed in run_test failed 
Test fv3_gsd 035 failed in run_test failed 
Test control_thompson_no_aero 027 failed in run_test failed 
Test control_thompson 026 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 040 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 041 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/666296517/20210609220012/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_125284
Test control_thompson 028 failed failed 
Test control_thompson 028 failed in run_test failed 
Test control_thompson_no_aero 029 failed failed 
Test control_thompson_no_aero 029 failed in run_test failed 
Test regional_quilt_netcdf_parallel 035 failed failed 
Test regional_quilt_netcdf_parallel 035 failed in run_test failed 
Test regional_quilt_hafs 034 failed failed 
Test regional_quilt_hafs 034 failed in run_test failed 
Test regional_control 031 failed failed 
Test regional_control 031 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 040 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 040 failed in run_test failed 
Test fv3_gsd 037 failed failed 
Test fv3_gsd 037 failed in run_test failed 
Test fv3_rrfs_v1alpha 038 failed failed 
Test fv3_rrfs_v1alpha 038 failed in run_test failed 
Test regional_quilt 033 failed failed 
Test regional_quilt 033 failed in run_test failed 
Test regional_quilt_RRTMGP 036 failed failed 
Test regional_quilt_RRTMGP 036 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 039 failed failed 
Test fv3_HAFS_v0_hwrf_thompson 039 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-BL

**Comment by climbfuji** [comment]
I made a stupid mistake in the last-minute code changes based on the code review. It's fixed now, regression tests have been kicked off manually on all systems. I also started the CI tests just now.

**Comment by junwang-noaa** [comment]
Dom, just to confirm, you are also running RT on wcoss, please let me know
if you have any issue, I can help to run RT on wcoss.

**Comment by climbfuji** [comment]
> Dom, just to confirm, you are also running RT on wcoss, please let me know if you have any issue, I can help to run RT on wcoss.
> […](#)

Thanks a lot. Seems to be working. I created the baseline on cray, will start verification after copying it over. Dell is still busy creating baselines. The biggest bottleneck is hera. If all other platforms finish except hera, we may have to do the merge w/o waiting for hera to finish ...

**Comment by junwang-noaa** [comment]
OK, let's see what we have by tomorrow morning.

**Comment by climbfuji** [comment]
CI tests passed for commit a3910a9.

**Comment by climbfuji** [comment]
Regression tests passed on all machines. I pushed the gaea.intel log directly from the machine, all others I copied to my laptop, but didn't commit them yet. This way I can show users how to pull in the updates to simulate what they need to do when auto-rt pushes some of the log files.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
Thanks for adding the hera_gnu debug modules. 
Once all the RT log files are committed, the code can be committed.

**Pull request merged**
