### PR TITLE
Fix/cpld sfs rt + Pull in units updates from FV3 #2467

### LINKED ISSUE #2474: cpld_control_sfs test needs updated parameter values
## Description
The cpld_control_sfs test needs updated parameter values to reflect the more optimal settings. This fix was in PR #2425 but will be separated since that PR already contains another baseline change to cpld_control_sfs.

Original issue was brought up here: https://github.com/ufs-community/ufs-weather-model/pull/2425#discussion_r1750868087 

## Additional context
The new settings are the following: 
```
export NUDGE_QV=.false.
export VTDM4=0.05
```
This should only affect the cpld_control_sfs test.

### PR DESCRIPTION
**Pull request by dpsarmie**
## Commit Queue Requirements:
- [X] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR updates certain variable values in the cpld_control_sfs test. These updated variables represent the most up-to-date version that is being run by Global Workflow.

### Commit Message:
```
* UFSWM - Updates cpld_control_sfs to use the most up-to-date configuration specs
* UFSWM - Update units attributes in netCDF output to be machine-readable
  * FV3 - Update units attributes in netCDF output to be machine-readable
    * atmos_cubed_sphere - Update units attributes in netCDF output to be machine-readable
```

### Priority:
* Normal

### UFSWM:
* Closes #2474 

### Sub component Pull Requests:
* FV3: NOAA-EMC/fv3atm#859
  * atmos_cubed_sphere: NOAA-GFDL/GFDL_atmos_cubed_sphere#356

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* cpld_control_sfs baseline changes

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@dpsarmie can you sync up branch? Also, we want to combine in #2467. just need to point to https://github.com/DWesl/fv3atm/tree/sty-unit-consistency.

**Comment by jkbk2004** [comment]
W can start merging process.

**Comment by jkbk2004** [comment]
@dpsarmie new fv3 hash is https://github.com/NOAA-EMC/fv3atm/commit/bd785e50f90985fb1330e36852297af38293415b

**Review by zach1221 — APPROVED** [review]

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA We need to re-create baselines. it looks like the feature branch pointer was messed up. I only see cosmetic unit issue like
```
23c23
<               pfull:units = "mb" ;
---
>               pfull:units = "mbar" ;
28c28
<               phalf:units = "mb" ;
---
>               phalf:units = "mbar" ;
423c423
<               lhtfl_ave:units = "w/m**2" ;
---
>               lhtfl_ave:units = "W/m**2" ;
```

**Comment by BrianCurtis-NOAA** [comment]
I won't be able to complete WCOSS2 for at least this week. Maintenance.

**Comment by jkbk2004** [comment]
Baselines were restored across RDHPCS w/o problems.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
