### PR TITLE
Feature/update mom6 20210402

### PR DESCRIPTION
**Pull request by jiandewang**
# PR Checklist

- [x ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
GFDL updated main branch on 20210402 (see detail at https://github.com/NOAA-GFDL/MOM6/pull/1358#issuecomment-811919139). This updating will make EMC and GFDL main repository on the same page.

### Issue(s) addressed

- fixes ufs-weather-model #489 
- fixes noaa-emc/MOM6/ https://github.com/NOAA-EMC/MOM6/issues/64

## Testing

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies
- noaa-emc/MOM6/pull/<65>https://github.com/NOAA-EMC/MOM6/pull/65

### CODE REVIEW

**Comment by climbfuji** [comment]
Does this PR change baselines? If not, can we combine it with another PR?

**Comment by jiandewang** [comment]
> Does this PR change baselines? If not, can we combine it with another PR?

no answer change, no any new input file required

**Comment by DeniseWorthen** [comment]
@jiandewang I do want to change some files at the app level to set a default value for the new ``allow_landmask_changes`` parameter setting. this will allow me to test the feature using the develop branch. I will make a PR to your branch today.

**Comment by jiandewang** [comment]
@DeniseWorthen your change will be in MOM_input_template, right?

**Comment by DeniseWorthen** [comment]
@jiandewang Yes, only in default_vars, and the input templates.

**Comment by climbfuji** [comment]
This PR is combined with/pulled into https://github.com/ufs-community/ufs-weather-model/pull/488 and will be merged as part of it.

**Comment by climbfuji** [comment]
#488 has been merged, this PR can be closed.

**Pull request closed without merging**
