### PR TITLE
Move Noah MP init to CCPP and update Noah MP regression tests, ice flux init bug fix in CCPP

### LINKED ISSUE #437: Enable test fv3_ccpp_gfs_v16_RRTMGP_2thrd on wcoss_cray
## Description

PR https://github.com/ufs-community/ufs-weather-model/pull/418 added regression test `fv3_ccpp_gfs_v16_RRTMGP_2thrd`, but they way the test was written doesn't work on wcoss_cray.

## Solution
The following change from @DusanJovic-NOAA will allow us to run test `fv3_ccpp_gfs_v16_RRTMGP_2thrd` on wcoss_cray (re-enable in `rt.conf`):
```
diff --git a/tests/parm/ccpp_v16_c96_rrtmgp.nml.IN b/tests/parm/ccpp_v16_c96_rrtmgp.nml.IN
index 1eb9124..0d6df12 100644
--- a/tests/parm/ccpp_v16_c96_rrtmgp.nml.IN
+++ b/tests/parm/ccpp_v16_c96_rrtmgp.nml.IN
@@ -41,7 +41,7 @@ deflate_level=1
 /
 
 &fv_core_nml
-  layout = 3,8
+  layout = @[INPES],@[JNPES]
   io_layout = 1,1
   npx = 97
   npy = 97
diff --git a/tests/tests/fv3_ccpp_gfs_v16_RRTMGP_2thrd b/tests/tests/fv3_ccpp_gfs_v16_RRTMGP_2thrd
index d009b4d..ec4d6d1 100644
--- a/tests/tests/fv3_ccpp_gfs_v16_RRTMGP_2thrd
+++ b/tests/tests/fv3_ccpp_gfs_v16_RRTMGP_2thrd
@@ -74,7 +74,12 @@ export LIST_FILES="atmos_4xdaily.tile1.nc \
 
 export_fv3
 export THRD=2
+export TASKS=$TASKS_thrd
 export TPN=$TPN_thrd
+export INPES=$INPES_thrd
+export JNPES=$JNPES_thrd
+export WRTTASK_PER_GROUP=12
+
 DT_ATMOS="1200"
 export DO_RRTMGP=.T.
```

## Alternatives
Don't run the test on wcoss_cray.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR does several things:

1. Update the submodule pointer for fv3atm (Move the Noah MP initialization of surface fields from fv3atm to CCPP) from @climbfuji.
2. Updates to Noah MP regression tests from @helinwei-noaa.
3. Apply a bugfix to the recently added RRTMGP threading tests and enable the test on wcoss_cray (from @DusanJovic-NOAA)
4. Initialize ice flux in CMEPSA bug fix in ccpp-physics from @shansun6

### Issue(s) addressed

This finally completes step 2 of https://github.com/NOAA-EMC/fv3atm/issues/214.

Fixes https://github.com/ufs-community/ufs-weather-model/issues/437.

## Testing

Regression tests will be run on all tier-1 platforms. Results change for regression tests using Noah MP, all others remain the same. This has been verified at the time when these PRs were created using both Intel and GNU on Hera.

New baselines created and used for verification on (logs updated in PR) on all tier-1 platforms:
- cheyenne.gnu
- cheyenne.intel
- gaea.intel
- hera.gnu
- hera.intel
- jet.intel
- orion.intel (auto-rt)
- wcoss_cray
- wcoss_dell_p3

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/575
https://github.com/NOAA-EMC/fv3atm/pull/249
https://github.com/ufs-community/ufs-weather-model/pull/425

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by barlage — APPROVED** [review]

**Comment by climbfuji** [comment]
Everyone, I ran `rt.sh` on hera with Intel and GNU now that the Noah MP changes themselves are complete (hash 865041622493f2f4641466abbec171ccfc11c03c for ufs-weather-model in this branch and submodule hashes referred to). All tests pass against the existing baseline except those using Noah MP, as expected. The tests that do not match the existing baseline all run to completion, i.e. they are ok.

**Intel**
```
fv3_ccpp_gfdlmprad_noahmp
fv3_ccpp_rrfs_v1beta
fv3_ccpp_rrfs_v1beta_debug
```
[rt_hera_intel_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/6051378/rt_hera_intel_against_existing.log)
[rt_hera_intel_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/6051379/rt_hera_intel_against_existing_fail_test.log)

**GNU**
```
fv3_ccpp_rrfs_v1beta_debug
fv3_ccpp_rrfs_v1beta
```
[rt_hera_gnu_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/6052327/rt_hera_gnu_against_existing.log)
[rt_hera_gnu_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/6052328/rt_hera_gnu_against_existing_fail_test.log)

I am going to pull in ccpp-physics PR https://github.com/NCAR/ccpp-physics/pull/563 (Initialize ice flux in CMEPSA bug fix), which I anticipate may change some of the coupled regression test results. I am also going to pull in a auto-rt PR (work in progress) that enables auto-rt on cheyenne and potentially includes a few bug fixes for that system, too.

**Comment by climbfuji** [comment]
Log Name:rt_auto_cheyenne.gnu_20210226141306.log
Log Location:/glade/work/heinzell/fv3/ufs-weather-model/auto-rt/control-20210226/tests/auto
Logs are kept for one month

**Comment by BrianCurtis-NOAA** [comment]
Log Name:rt_auto_20210302000010.log
Log Location:/mnt/lfs4/HFIP/h-nems/Brian.Curtis/git/ufs-community/ufs-weather-model/tests/auto
Logs are kept for one month

**Comment by climbfuji** [comment]
> Log Name:rt_auto_20210302000010.log
> Log Location:/mnt/lfs4/HFIP/h-nems/Brian.Curtis/git/ufs-community/ufs-weather-model/tests/auto
> Logs are kept for one month

@DusanJovic-NOAA looks like the auto-rt tests failed on jet, run manually?

**Comment by BrianCurtis-NOAA** [comment]
Log Name:rt_auto_20210301183005.log
Log Location:/work/noaa/nems/bcurtis/git/ufs-community/ufs-weather-model/tests/auto
Logs are kept for one month

**Comment by DusanJovic-NOAA** [comment]
jet.intel log file is here:
/lfs4/HFIP/hfv3gfs/Dusan.Jovic/ufs/pr425/ufs-weather-model/tests/RegressionTests_jet.intel.log

**Comment by climbfuji** [comment]
> jet.intel log file is here:
> /lfs4/HFIP/hfv3gfs/Dusan.Jovic/ufs/pr425/ufs-weather-model/tests/RegressionTests_jet.intel.log

Thanks, Dusan!

**Review by junwang-noaa — APPROVED** [review]
Need to point fv3 back to emc develop branch.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA ci tests passed, please merge. Thanks!

**Pull request merged**
