### PR TITLE
Remove redundant surface variables and update to send correct pointers to JEDI in fv3atm

### LINKED ISSUE #370: Remove several redundant variables for surface composite physics
## Description

Several interstitial variables used in the composite physics are redundant and can be removed without changing the results. This results in an easier-to-understand code, lower memory footprint and potentially increased runtime performance.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR only update the submodule pointers for fv3atm and ccpp-physiics for the following code changes:
- Remove redundant surface variables to reduce memory footprint and to simplify the code (from @mzhangw)
- Send/export correct pointers to JEDI (from @mark-a-potts)

No new input data required, no baseline changes.

### Issue(s) addressed

Fixes https://github.com/NOAA-EMC/fv3atm/issues/370.

## Testing

**Preliminary testing**

Code change in [#363](https://github.com/NOAA-EMC/fv3atm/pull/363) do not affect the ufs-weather-model runs. Code changes in [#366](https://github.com/NOAA-EMC/fv3atm/pull/366) were tested on orion.intel against the existing baseline by @mzhangw, all tests passed.

**Final regression testing**

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [-] cheyenne.intel - skip due to PBS outage and `rt.sh` being killed at 1:00am after all tests except one passed
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/747/commits/cce9caf7e38c1bfaf9c2625b9d5b4fe7c12e1c23

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/717
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/368

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/712354257/20210816101509/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_47931
Test control_c384gdas 026 failed in run_test failed 
Test control 016 failed failed 
Test control 016 failed in run_test failed 
Test fv3_gsd_debug 077 failed failed 
Test fv3_gsd_debug 077 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 080 failed failed 
Test fv3_rrfs_v1alpha_debug 080 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 079 failed failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 081 failed failed 
Test control_decomp 017 failed failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 081 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 079 failed in run_test failed 
Test control_decomp 017 failed in run_test failed 
Test fv3_gsd_diag_debug 078 failed failed 
Test fv3_gsd_diag_debug 078 failed in run_test failed 
Test cpld_control_c192 006 failed failed 
Test cpld_control_c192 006 failed in run_test failed 
Test cpld_control 001 failed failed 
Test control_c192 024 failed failed 
Test control_c384 025 failed failed 
Test cpld_control 001 failed in run_test failed 
Test control_c192 024 failed in run_test failed 
Test cpld_control_wave 014 failed failed 
Test control_c384 025 failed in run_test failed 
Test cpld_control_wave 014 failed in run_test failed 
Test cpld_ca 005 failed failed 
Test cpld_ca 005 failed in run_test failed 
Test cpld_control_c384 008 failed failed 
Test control_c48 023 failed failed 
Test cpld_control_c384 008 failed in run_test failed 
Test control_c48 023 failed in run_test failed 
Test control_ca 029 failed in run_test failed 
Test control_lseaspray 032 failed in run_test failed 
Test control_flake 037 failed in run_test failed 
Test control_stochy 027 failed in run_test failed 
Test control_lndp 030 failed in run_test failed 
Test control_noahmp 042 failed in run_test failed 
Test control_lheatstrg 031 failed in run_test failed 
Test control_ras 039 failed in run_test failed 
Test control_ugwpv1 038 failed in run_test failed 
Test control_rrtmgp 034 failed in run_test failed 
Test control_thompson_no_aero 041 failed in run_test failed 
Test control_thompson 040 failed in run_test failed 
Test fv3_rrfs_v1alpha 051 failed in run_test failed 
Test fv3_gsd 050 failed in run_test failed 
Test fv3_rrfs_v1beta 054 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 055 failed in run_test failed 
Test fv3_rap 052 failed in run_test failed 
Test fv3_hrrr 053 failed in run_test failed 
Test control_2threads 018 failed failed 
Test control_2threads 018 failed in run_test failed 
Test datm_control_cfsr 088 failed in run_test failed 
Test cpld_bmark_v16_nsst 012 failed failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_wave_v16 013 failed failed 
Test cpld_bmark_v16_nsst 012 failed in run_test failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Test cpld_bmark_wave_v16 013 failed in run_test failed 
Test regional_restart 044 failed in run_test failed 
Test datm_control_gefs 090 failed in run_test failed 
Test datm_control_iau_gefs 091 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 056 failed in run_test failed 
Test regional_quilt_netcdf_parallel 048 failed in run_test failed 
Test regional_quilt_hafs 047 failed in run_test failed 
Test datm_cdeps_control_gefs 099 failed in run_test failed 
Test datm_cdeps_control_cfsr 097 failed in run_test failed 
Test datm_bulk_cfsr 092 failed in run_test failed 
Test datm_debug_cfsr 096 failed in run_test failed 
Test regional_quilt_RRTMGP 049 failed in run_test failed 
Test datm_cdeps_bulk_gefs 101 failed in run_test failed 
Test datm_bulk_gefs 093 failed in run_test failed 
Test datm_cdeps_bulk_cfsr 100 failed in run_test failed 
Test datm_cdeps_multiple_files_cfsr 104 failed in run_test failed 
Test datm_cdeps_debug_cfsr 105 failed in run_test failed 
Test control_atmwav 106 failed in run_test failed 
Test control_csawmgt 036 failed in run_test failed 
Test control_csawmg 035 failed in run_test failed 
Test control_merra2 033 failed in run_test failed 
Test hafs_regional_atm 083 failed in run_test failed 
Test hafs_regional_docn 085 failed in run_test failed 
Test hafs_regional_atm_ocn 084 failed in run_test failed 
Test datm_mx025_cfsr 094 failed in run_test failed 
Test hafs_regional_docn_oisst 086 failed in run_test failed 
Test control_rrtmgp_debug 066 failed failed 
Test control_rrtmgp_debug 066 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 022 failed failed 
Test control_wrtGauss_netcdf_parallel 022 failed in run_test failed 
Test cpld_debug 015 failed failed 
Test cpld_debug 015 failed in run_test failed 
Test control_csawmg_debug 067 failed failed 
Test control_csawmg_debug 067 failed in run_test failed 
Test control_merra2_debug 065 failed failed 
Test control_merra2_debug 065 failed in run_test failed 
Test control_csawmgt_debug 068 failed failed 
Test control_csawmgt_debug 068 failed in run_test failed 
Test datm_mx025_gefs 095 failed in run_test failed 
Test datm_cdeps_mx025_gefs 103 failed in run_test failed 
Test hafs_regional_datm_cdeps 087 failed in run_test failed 
Test cpld_2threads 003 failed failed 
Test cpld_2threads 003 failed in run_test failed 
Test cpld_decomp 004 failed failed 
Test cpld_decomp 004 failed in run_test failed 
Test control_fhzero 020 failed failed 
Test control_fhzero 020 failed in run_test failed 
Test control_CubedSphereGrid 021 failed failed 
Test control_CubedSphereGrid 021 failed in run_test failed 
Test datm_cdeps_mx025_cfsr 102 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/712354257/20210816103009/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_4566
Test fv3_HAFS_v0_hwrf_thompson 014 failed failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 030 failed failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 030 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 014 failed in run_test failed 
Test fv3_gsd 011 failed failed 
Test fv3_gsd 011 failed in run_test failed 
Test control_flake 005 failed failed 
Test control_flake 005 failed in run_test failed 
Test control_noahmp_debug 029 failed failed 
Test control_noahmp_debug 029 failed in run_test failed 
Test control_ras 010 failed failed 
Test control_ras 010 failed in run_test failed 
Test control_ras_debug 028 failed failed 
Test control_ras_debug 028 failed in run_test failed 
Test control_diag_debug 017 failed failed 
Test control_diag_debug 017 failed in run_test failed 
Test control_thompson_no_aero_debug 024 failed failed 
Test control_thompson_no_aero_debug 024 failed in run_test failed 
Test fv3_gsd_debug 021 failed failed 
Test fv3_gsd_debug 021 failed in run_test failed 
Test control_thompson_debug 023 failed failed 
Test control_thompson_debug 023 failed in run_test failed 
Test control_rrtmgp_debug 026 failed failed 
Test control_rrtmgp_debug 026 failed in run_test failed 
Test control_thompson 007 failed failed 
Test control_thompson 007 failed in run_test failed 
Test control_rrtmgp 006 failed failed 
Test control_rrtmgp 006 failed in run_test failed 
Test control_thompson_extdiag_debug 025 failed failed 
Test control_thompson_extdiag_debug 025 failed in run_test failed 
Test control_debug 016 failed failed 
Test control_debug 016 failed in run_test failed 
Test control_stochy 004 failed failed 
Test control_stochy 004 failed in run_test failed 
Test fv3_rrfs_v1beta 013 failed failed 
Test fv3_rrfs_v1beta 013 failed in run_test failed 
Test control_ugwpv1 009 failed failed 
Test control_ugwpv1 009 failed in run_test failed 
Test fv3_rrfs_v1alpha 012 failed failed 
Test control_ugwpv1_debug 027 failed failed 
Test fv3_rrfs_v1alpha 012 failed in run_test failed 
Test control_ugwpv1_debug 027 failed in run_test failed 
Test control 001 failed failed 
Test control 001 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 019 failed failed 
Test fv3_rrfs_v1alpha_debug 019 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 020 failed failed 
Test fv3_rrfs_v1beta_debug 020 failed in run_test failed 
Test fv3_gsd_diag_debug 022 failed failed 
Test fv3_gsd_diag_debug 022 failed in run_test failed 
Test control_c48 003 failed failed 
Test control_c48 003 failed in run_test failed 
Test control_thompson_no_aero 008 failed failed 
Test control_thompson_no_aero 008 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by climbfuji** [comment]
Seems there was a major outage of the PBS queueing system on Cheyenne, I see lots of these errors:
```
...
13 min. TEST 003 control_c48 is running,  status: R jobid 9911071
Connection refused
qstat: cannot connect to server chadmin2.ib0.cheyenne.ucar.edu (errno=111)
Connection refused
qstat: cannot connect to server chadmin2.ib0.cheyenne.ucar.edu (errno=111)
Connection refused
qstat: cannot connect to server chadmin2.ib0.cheyenne.ucar.edu (errno=111)
14 min. TEST 003 control_c48 is finished,  status: - jobid 9911071
```

Will try auto-rt again for cheyenne.intel and cheyenne.gnu, hoping that the system has recovered.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/712354257/20210816111508/ufs-weather-model
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by climbfuji** [comment]
Re: Cheyenne
```
UNSCHEDULED OUTAGE NOTIFICATION

The Cheyenne cluster's PBS server is currently experiencing problems. All PBS commands including qsub and qstat are unavailable.  CISL is aware of the problem and working to restore PBS as soon as possible.

START: Mon Aug 16 2021 11:05 AM MDT
END: Unknown

SERVICES AFFECTED
CISL Status
```
Will wait until outage is resolved.

**Comment by BrianCurtis-NOAA** [comment]
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/712354257/20210816111925/ufs-weather-model
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by climbfuji** [comment]
```
NOTIFICATION UPDATE

CISL has determined the root cause of the problem that caused Cheyenne's PBS server to fail earlier today. The server has been restored and jobs that were queued before the server crash are now running. Submitting new jobs via qsub is not yet possible but is expected to be available later this afternoon. Users will be notified when PBS is fully restored.

Posted by Mick Coady
____________________
```

**Comment by climbfuji** [comment]
Cheyenne/Intel: same issue as previously, this time with test `cpld_restart_bmark_v16`:
```
...
143 min. TEST 011 cpld_restart_bmark_v16 is waiting in a queue,  status: Q jobid 9922793
144 min. TEST 011 cpld_restart_bmark_v16 is waiting in a queue,  status: Q jobid 9922793
145 min. TEST 011 cpld_restart_bmark_v16 is waiting in a queue,  status: Q jobid 9922793
146 min. TEST 011 cpld_restart_bmark_v16 is waiting in a queue,  status: Q jobid 9922793
run_test.sh terminated PID=67521
++ [[ pbs = \p\b\s ]]
++ echo 'run_util.sh: interrupt_job qsub_id = 9922793'
run_util.sh: interrupt_job qsub_id = 9922793
```
terminated at 1:00 am exactly.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
fv3atm hash is correct (6bad820), ready to merge

**Comment by BrianCurtis-NOAA** [comment]
I've doubled checked the hash's. They're good to go!

**Comment by climbfuji** [comment]
> I've doubled checked the hash's. They're good to go!

Thanks, Brian. I'll merge myself ...

**Pull request merged**
