### PR TITLE
MYNN sfclay (RAP suite) restart reproducibility

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR turns on the `rap_restart` tests. Bit-for-bit reproducibility is achieved with the bug fixes for MYNN sfclay in the associated fv3atm and ccpp-physics PRs.

The bug fixes for MYNN sfclay in the ccpp-physics PR change the results for all physics suites that use MYNN sfclay, i.e. all RAP suites.

### Issue(s) addressed

This is the first step to address issue https://github.com/ufs-community/ufs-weather-model/issues/953 - more work is needed in a follow-up PR for the `decomp` problem.

### Preliminary regression testing

Regression testing against existing baseline on Hera with GNU: The following tests fail with b4b mismatches, but run to completion:
```
log_hera.gnu/rt_011_rap_control.log
log_hera.gnu/rt_012_rap_2threads.log
log_hera.gnu/rt_016_hrrr_control.log
log_hera.gnu/rt_017_rrfs_v1beta.log
log_hera.gnu/rt_021_rap_control_debug.log
log_hera.gnu/rt_022_rap_diag_debug.log
log_hera.gnu/rt_024_rrfs_v1beta_debug.log
```

Regression testing against existing baseline on Hera with Intel: The following tests fail with b4b mismatches, but run to completion:
```
log_hera.intel/rt_042_rap_control.log
log_hera.intel/rt_043_rap_2threads.log
log_hera.intel/rt_047_hrrr_control.log
log_hera.intel/rt_048_rrfs_v1beta.log
log_hera.intel/rt_074_rap_control_debug.log
log_hera.intel/rt_075_rap_unified_drag_suite_debug.log
log_hera.intel/rt_076_rap_diag_debug.log
log_hera.intel/rt_077_rap_cires_ugwp_debug.log
log_hera.intel/rt_078_rap_unified_ugwp_debug.log
log_hera.intel/rt_079_rap_noah_debug.log
log_hera.intel/rt_080_rap_rrtmgp_debug.log
log_hera.intel/rt_081_rap_lndp_debug.log
log_hera.intel/rt_083_rap_flake_debug.log
log_hera.intel/rt_085_rrfs_v1beta_debug.log
```

### Final regression testing

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/984/commits/cc73201091ada1ed8cd563cd499835b4ca108429

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/822
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/455

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/811585879/20211229171513/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_17436
Test rap_control 042 failed in check_result failed 
Test rap_control 042 failed in run_test failed 
Test rap_2threads 043 failed in check_result failed 
Test rap_2threads 043 failed in run_test failed 
Test hrrr_control 047 failed in check_result failed 
Test hrrr_control 047 failed in run_test failed 
Test rrfs_v1beta 048 failed in check_result failed 
Test rrfs_v1beta 048 failed in run_test failed 
Test rap_control_debug 074 failed in check_result failed 
Test rap_control_debug 074 failed in run_test failed 
Test rap_unified_drag_suite_debug 075 failed in check_result failed 
Test rap_unified_drag_suite_debug 075 failed in run_test failed 
Test rap_diag_debug 076 failed in check_result failed 
Test rap_diag_debug 076 failed in run_test failed 
Test rap_cires_ugwp_debug 077 failed in check_result failed 
Test rap_cires_ugwp_debug 077 failed in run_test failed 
Test rap_unified_ugwp_debug 078 failed in check_result failed 
Test rap_unified_ugwp_debug 078 failed in run_test failed 
Test rap_noah_debug 079 failed in run_test failed 
Test rap_rrtmgp_debug 080 failed in check_result failed 
Test rap_rrtmgp_debug 080 failed in run_test failed 
Test rap_lndp_debug 081 failed in check_result failed 
Test rap_lndp_debug 081 failed in run_test failed 
Test rap_flake_debug 083 failed in check_result failed 
Test rap_flake_debug 083 failed in run_test failed 
Test rrfs_v1beta_debug 085 failed in check_result failed 
Test rrfs_v1beta_debug 085 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/811585879/20211229173013/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_868
Test rap_control 011 failed in check_result failed 
Test rap_control 011 failed in run_test failed 
Test rap_2threads 012 failed in check_result failed 
Test rap_2threads 012 failed in run_test failed 
Test hrrr_control 016 failed in check_result failed 
Test hrrr_control 016 failed in run_test failed 
Test rrfs_v1beta 017 failed in check_result failed 
Test rrfs_v1beta 017 failed in run_test failed 
Test rap_control_debug 021 failed in check_result failed 
Test rap_control_debug 021 failed in run_test failed 
Test rap_diag_debug 022 failed in check_result failed 
Test rap_diag_debug 022 failed in run_test failed 
Test rrfs_v1beta_debug 024 failed in check_result failed 
Test rrfs_v1beta_debug 024 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-RT

**Comment by SamuelTrahanNOAA** [comment]
This will change the results of the new tests in #986 so I'll need #984 to be finalized before I regenerate baselines for #986.

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/811585879/20220106074519/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_288626
Test rap_noah_debug 056 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/811585879/20220106140011/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_15703
Test rap_noah_debug 056 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/811585879/20220106070013/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_53243
Test rap_noah_debug 056 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/811585879/20220106134508/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_32808
Test rap_noah_debug 055 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/811585879/20220106134512/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_100955
Test rap_noah_debug 056 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-BL

**Comment by climbfuji** [comment]
Fixed the problem and added all labels once more.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/811585879/20220106090014/ufs-weather-model
/glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20220106/GNU
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
cheyenne-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/811585879/20220106160019/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20220106/GNU
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-gnu-BL

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Hash for fv3atm is correct (7eb0ee2a641c2a87628056f5b84b58f7037f1560), ready to merge.

**Pull request merged**
