### PR TITLE
release/public-v2: update build.sh for macOS, update regression tests, update modulefiles

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR:
- moves the clang test for turning off OpenMP from `cmake/configure_macosx.gnu.cmake` to `CMakeLists.txt` so that it works with `build.sh`
- updates `build.sh` to use the correct `readlink` command on macOS
- add gfortran-10 compiler flags
- update all modulefiles to use the NCEPLIBS ufs-v2.0.0 umbrella module
- update `tests/rt.conf` to run regression tests specific to the SRW App
- remove all unsupported regression test scripts/configuration files (for the SRW App) in `parm`, `tests/fv3_conf`, `tests/tests`
- updates the fv3atm submodule pointer for the changes in the associated PRs listed below

Caveats:
- not all of the regression tests are working, the problematic ones have been commented out in `tests/rt.conf` with a short note about the failure
- in addition there are two temporary regression test configurations, `rt_gnu.conf` and `rt_jet_intel.conf` for systems that have problems with more tests
- fixing these falls into the category of bugfixes, which are allowed after the code freeze on October 30, 2020

## Testing

New baselines will be created on most tier-1 platforms of the SRW App release (hera.intel, hera.gnu, cheyenne.intel, cheyenne.gnu, jet.intel, gaea.intel; gaea.intel may be skipped if cluster problems are not resolved in time)

**UPDATE:**
- Regression tests ran successfully on cheyenne.intel, cheyenne.gnu, hera.intel, hera.gnu, jet.intel. Logs updated in the PR.
- Currently on hold (system problems): gaea.intel.

## Dependencies

https://github.com/NOAA-EMC/fv3atm/pull/190
https://github.com/ufs-community/ufs-weather-model/pull/248

### CODE REVIEW

**Comment by mkavulich** [comment]
@climbfuji When I attempt to build the ufs-weather-model as part of the ufs-srweather-app, I run into an error in the ccpp prebuild step:

```
Found Python: /Users/kavulich/miniconda3/bin/python3.7
Calling CCPP code generator (ccpp_prebuild.py) for SUITES = FV3_CPT_v0,FV3_GFS_2017_gfdlmp,FV3_GFS_2017_gfdlmp_regional,FV3_GSD_SAR,FV3_GSD_v0,FV3_GFS_v15p2,FV3_GFS_v16beta,FV3_RRFS_v1beta
CMake Error at CMakeLists.txt:139 (message):
  An error occured while running ccpp_prebuild.py, check
  /Users/kavulich/workdir/UFS/test_Doms_code/ufs-srweather-app/build/src/ufs_weather_model/src/ufs_weather_model-build/ccpp_prebuild.{out,err}


-- Configuring incomplete, errors occurred!
See also "/Users/kavulich/workdir/UFS/test_Doms_code/ufs-srweather-app/build/src/ufs_weather_model/src/ufs_weather_model-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [src/ufs_weather_model/src/ufs_weather_model-stamp/ufs_weather_model-configure] Error 1
make[1]: *** [src/CMakeFiles/ufs_weather_model.dir/all] Error 2
make: *** [all] Error 2
```

I was initially curious if maybe this was related to my python environment, but I do not see this error when building the release branch.

I also attached the cmake log referenced above but it doesn't seem to have any useful information. Let me know if you need any more info. 

[CMakeOutput.log](https://github.com/ufs-community/ufs-weather-model/files/5461933/CMakeOutput.log)


Oh and this is on MacOS High Sierra, by the way.

**Comment by climbfuji** [comment]
> @climbfuji When I attempt to build the ufs-weather-model as part of the ufs-srweather-app, I run into an error in the ccpp prebuild step:
> 
> ```
> Found Python: /Users/kavulich/miniconda3/bin/python3.7
> Calling CCPP code generator (ccpp_prebuild.py) for SUITES = FV3_CPT_v0,FV3_GFS_2017_gfdlmp,FV3_GFS_2017_gfdlmp_regional,FV3_GSD_SAR,FV3_GSD_v0,FV3_GFS_v15p2,FV3_GFS_v16beta,FV3_RRFS_v1beta
> CMake Error at CMakeLists.txt:139 (message):
>   An error occured while running ccpp_prebuild.py, check
>   /Users/kavulich/workdir/UFS/test_Doms_code/ufs-srweather-app/build/src/ufs_weather_model/src/ufs_weather_model-build/ccpp_prebuild.{out,err}
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/kavulich/workdir/UFS/test_Doms_code/ufs-srweather-app/build/src/ufs_weather_model/src/ufs_weather_model-build/CMakeFiles/CMakeOutput.log".
> make[2]: *** [src/ufs_weather_model/src/ufs_weather_model-stamp/ufs_weather_model-configure] Error 1
> make[1]: *** [src/CMakeFiles/ufs_weather_model.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> I was initially curious if maybe this was related to my python environment, but I do not see this error when building the release branch.
> 
> I also attached the cmake log referenced above but it doesn't seem to have any useful information. Let me know if you need any more info.
> 
> [CMakeOutput.log](https://github.com/ufs-community/ufs-weather-model/files/5461933/CMakeOutput.log)

Please look in these files: `/Users/kavulich/workdir/UFS/test_Doms_code/ufs-srweather-app/build/src/ufs_weather_model/src/ufs_weather_model-build/ccpp_prebuild.{out,err}` - I guess that you are trying to use this branch, but it only has two suites left (FV3/ccpp/suites/).

**Comment by mkavulich** [comment]
> Please look in these files: `/Users/kavulich/workdir/UFS/test_Doms_code/ufs-srweather-app/build/src/ufs_weather_model/src/ufs_weather_model-build/ccpp_prebuild.{out,err}` - I guess that you are trying to use this branch, but it only has two suites left (FV3/ccpp/suites/).

That was indeed the issue, sorry I missed those log files. It looks like the ufs-srweather-app needs to be updated to only build the supported suites, I can open a PR for that.

When I make that change it now compiles for gnu-10 compilers on my High Sierra machine! I think I just need to make an update to UFS_UTILS to include the same flags and the full app will build. Thanks for working on this.

**Review by mkavulich — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]
Please point fv3 back to release/public-v2, then we can merge the code.

**Comment by climbfuji** [comment]
> Please point fv3 back to release/public-v2, then we can merge the code.

Done, please check. Thanks!

**Pull request merged**
