### PR TITLE
Update to esmf-bs47 across all platforms; add export of openwater_frac_in_atm from FV3 when coupled

### LINKED ISSUE #494: Update ESMF to bs47 across all platforms
## Description

Update from esmf-bs27 to esmf-bs47

## Solution

Implement ``module load esmf/8_1_0_beta_snapshot_47`` or ``module load esmf/8_1_0_beta_snapshot_47-debug`` in fv3 and fv3_debug

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

* Updates ESMF from bs27 to bs47 across all platforms
* Adds export of openwater_frac_in_atm from FV3 when coupled
* Adds needed field in fd_nems.yaml

### Issue(s) addressed

- fixes #494 
- partial fix to issue #366. FV3atm will export the required field but no use will be made of it until changes are made in the CMEPS mediator.

## Testing

ESMF changes: Testing on hera.intel and wcoss-dell-p3 show comparison failures for these tests and files (all other files pass either alt or direct comparison):

fv3_regional_quilt:  NATLEV.GrbF00 and NATLEV.GrbF24 
fv3_esg_HAFS_v0_hwrf_thompson and fv3_esg_HAFS_v0_hwrf_thompson_debug : phyf000 and dynf000 

On dell-p3, some tests failed because of compile failures for 016 and 017 (job killed after reaching LSF run time limit)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

CMEPS [#39](https://github.com/NOAA-EMC/CMEPS/pull/39)
FV3-ATM [#266](https://github.com/NOAA-EMC/fv3atm/pull/266)

This PR is to be combined with PR #475

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@junwang-noaa esmf/8.1.0bs47 does not seem to be available on wcoss-cray

I tried: 
```
module use /gpfs/hps3/emc/nems/noscrub/emc.nemspara/soft/modulefiles
module avail
```
Screen Shot 2021-03-30 at 3 50 57 PM

**Comment by junwang-noaa** [comment]
Hang installed it at NCEPLIBS location:
The esmf 810bs47 has been added to the NCEPLIBS-v1.3.0 on wcoss-cray.
module load
/gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules/esmf/810bs47

**Comment by DeniseWorthen** [comment]
Thanks. It looks like it is compiling now.

**Comment by DeniseWorthen** [comment]
@MinsukJi-NOAA Testing this branch on wcoss-cray gave failures for the alt compare, for example:

```
Comparing phyf000.tile1.nc ............ALT CHECK......ERROR
```

Can you take a look? My run directory is /gpfs/hps3/emc/marine/noscrub/Denise.Worthen/ufs_bs47

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA Testing this branch on wcoss-cray gave failures for the alt compare, for example:
> 
> ```
> Comparing phyf000.tile1.nc ............ALT CHECK......ERROR
> ```
> 
> Can you take a look? My run directory is /gpfs/hps3/emc/marine/noscrub/Denise.Worthen/ufs_bs47

ALT CHECK kicks in when CMP fails. Taking a look at your log file, there are 44 failed test cases of phyf000.tile.1.nc.
I think there are two issues here:
1. phyf000 is not b4b identical
2. compare_ncfile.py fail.
Issue 2 was encountered by @junwang-noaa previously, but I never got to the bottom of it. I will create an issue for this.

**Comment by DeniseWorthen** [comment]
Thanks Minsuk. I was expecting that the forecast files would need alt check but I was surprised it turned up as "error". The comparison doesn't continue past that so the tests are flagged as failing.

**Comment by DeniseWorthen** [comment]
I reran the wcoss-cray tests with the forecast files moved to the end of the compare list. All non-forecast files compare "OK" against the current baseline.

**Comment by DeniseWorthen** [comment]
Merged into PR #475; closing.

**Pull request closed without merging**
