### PR TITLE
Add lsm_cold_start variable for RUC LSM SCM support and gwdps bugfix (combined)

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This pull request only adds a new lsm_cold_start variable that is necessary to add to the CCPP version of RUC LSM in order for it to be used with the CCPP SCM. This change should have no effect on FV3/UFS and all RTs have passed on Hera/Intel.

(Update)
This pull request also pulls in @SMoorthi-emc 's bugfix for gwdps.f. These changes require new baselines for the list of tests given below.

### Issue(s) addressed

https://github.com/NCAR/ccpp-physics/issues/833
https://github.com/NCAR/ccpp-physics/issues/831
https://github.com/NOAA-EMC/fv3atm/issues/473

## Testing

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/834
https://github.com/NOAA-EMC/fv3atm/pull/475

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@grantfirl Would you combine @SMoorthi-emc PR#1035 in your PR? It looks to me more files are changed in this PR .

**Comment by binli2337** [comment]
@grantfirl After you combine PR#1035 into your PR, please set BL_DATE=20220207 in rt.sh. Please let me know if you have any questions. Thanks.

**Comment by grantfirl** [comment]
The following list of tests need new baselines after the code changes in ccpp/physics/physics/gwdps.f:
control 016 failed in check_result
control 016 failed in run_test
control_decomp 017 failed in check_result
control_decomp 017 failed in run_test
control_2dwrtdecomp 018 failed in check_result
control_2dwrtdecomp 018 failed in run_test
control_2threads 019 failed in check_result
control_2threads 019 failed in run_test
control_fhzero 021 failed in check_result
control_fhzero 021 failed in run_test
control_CubedSphereGrid 022 failed in check_result
control_CubedSphereGrid 022 failed in run_test
control_latlon 023 failed in check_result
control_latlon 023 failed in run_test
control_wrtGauss_netcdf_parallel 024 failed in check_result
control_wrtGauss_netcdf_parallel 024 failed in run_test
control_c48 025 failed in check_result
control_c48 025 failed in run_test
control_c192 026 failed in check_result
control_c192 026 failed in run_test
control_c384 027 failed in check_result
control_c384 027 failed in run_test
control_c384gdas 028 failed in check_result
control_c384gdas 028 failed in run_test
control_stochy 029 failed in check_result
control_stochy 029 failed in run_test
control_lndp 031 failed in check_result
control_lndp 031 failed in run_test
control_iovr4 032 failed in check_result
control_iovr4 032 failed in run_test
control_iovr5 033 failed in check_result
control_iovr5 033 failed in run_test
regional_control 039 failed in check_result
regional_control 039 failed in run_test
regional_control_2dwrtdecomp 041 failed in check_result
regional_control_2dwrtdecomp 041 failed in run_test
regional_noquilt 042 failed in check_result
regional_noquilt 042 failed in run_test
regional_2threads 043 failed in check_result
regional_2threads 043 failed in run_test
regional_hafs 044 failed in check_result
regional_hafs 044 failed in run_test
regional_netcdf_parallel 045 failed in check_result
regional_netcdf_parallel 045 failed in run_test
regional_RRTMGP 046 failed in check_result
regional_RRTMGP 046 failed in run_test
rrfs_v1beta 053 failed in check_result
rrfs_v1beta 053 failed in run_test
control_rrtmgp 056 failed in check_result
control_rrtmgp 056 failed in run_test
control_rrtmgp_c192 057 failed in check_result
control_rrtmgp_c192 057 failed in run_test
control_csawmg 058 failed in check_result
control_csawmg 058 failed in run_test
control_csawmgt 059 failed in check_result
control_csawmgt 059 failed in run_test
control_flake 060 failed in check_result
control_flake 060 failed in run_test
control_ras 061 failed in check_result
control_ras 061 failed in run_test
control_thompson 062 failed in check_result
control_thompson 062 failed in run_test
control_thompson_no_aero 063 failed in check_result
control_thompson_no_aero 063 failed in run_test
control_wam 064 failed in check_result
control_wam 064 failed in run_test
control_debug 065 failed in check_result
control_debug 065 failed in run_test
control_2threads_debug 066 failed in check_result
control_2threads_debug 066 failed in run_test
control_CubedSphereGrid_debug 067 failed in check_result
control_CubedSphereGrid_debug 067 failed in run_test
control_wrtGauss_netcdf_parallel_debug 068 failed in check_result
control_wrtGauss_netcdf_parallel_debug 068 failed in run_test
control_stochy_debug 069 failed in check_result
control_stochy_debug 069 failed in run_test
control_lndp_debug 070 failed in check_result
control_lndp_debug 070 failed in run_test
control_rrtmgp_debug 071 failed in check_result
control_rrtmgp_debug 071 failed in run_test
control_csawmg_debug 072 failed in check_result
control_csawmg_debug 072 failed in run_test
control_csawmgt_debug 073 failed in check_result
control_csawmgt_debug 073 failed in run_test
control_ras_debug 074 failed in check_result
control_ras_debug 074 failed in run_test
control_diag_debug 075 failed in check_result
control_diag_debug 075 failed in run_test
control_thompson_debug 077 failed in check_result
control_thompson_debug 077 failed in run_test
control_thompson_no_aero_debug 078 failed in check_result
control_thompson_no_aero_debug 078 failed in run_test
control_thompson_extdiag_debug 079 failed in check_result
control_thompson_extdiag_debug 079 failed in run_test
control_thompson_progcld_thompson_debug 080 failed in check_result
control_thompson_progcld_thompson_debug 080 failed in run_test
regional_debug 081 failed in check_result
regional_debug 081 failed in run_test
rap_cires_ugwp_debug 085 failed in check_result
rap_cires_ugwp_debug 085 failed in run_test
rap_unified_ugwp_debug 086 failed in check_result
rap_unified_ugwp_debug 086 failed in run_test
rap_noah_sfcdiff_cires_ugwp_debug 092 failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug 092 failed in run_test
rrfs_v1beta_debug 094 failed in check_result
rrfs_v1beta_debug 094 failed in run_test
control_wam_debug 095 failed in check_result
control_wam_debug 095 failed in run_test
hafs_regional_atm 096 failed in check_result
hafs_regional_atm 096 failed in run_test
hafs_regional_atm_thompson_gfdlsf 097 failed in check_result
hafs_regional_atm_thompson_gfdlsf 097 failed in run_test
hafs_regional_atm_ocn 098 failed in check_result
hafs_regional_atm_ocn 098 failed in run_test
hafs_regional_atm_wav 099 failed in check_result
hafs_regional_atm_wav 099 failed in run_test
hafs_regional_atm_ocn_wav 100 failed in check_result
hafs_regional_atm_ocn_wav 100 failed in run_test
hafs_regional_1nest_atm 101 failed in check_result
hafs_regional_1nest_atm 101 failed in run_test
hafs_regional_telescopic_2nests_atm 102 failed in check_result
hafs_regional_telescopic_2nests_atm 102 failed in run_test
hafs_global_1nest_atm 103 failed in check_result
hafs_global_1nest_atm 103 failed in run_test
hafs_regional_docn 105 failed in check_result
hafs_regional_docn 105 failed in run_test
hafs_regional_docn_oisst 106 failed in check_result
hafs_regional_docn_oisst 106 failed in run_test
control_atmwav 119 failed in check_result
control_atmwav 119 failed in run_test
control_c384gdas_wav 120 failed in check_result
control_c384gdas_wav 120 failed in run_test
control_atm_aerosols 121 failed in check_result
control_atm_aerosols 121 failed in run_test

**Comment by grantfirl** [comment]
@junwang-noaa @binli2337 Finished with the combination. This should be ready to work on by UFS code managers now.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/839514645/20220207160008/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/839514645/20220207180352/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: jet Compiler: intel Job: BL [BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/839514645/20220207160008/ufs-weather-model [BL] Baseline creation and move successful [RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/839514645/20220207180352/ufs-weather-model Please make changes and add the following label back: jet-intel-BL

My guess is something with tfe1 on Jet isn't working quite right still, it wasn't able to connect to ecflow and just failed out. I'll put on the RT label right now to see if it was just a temporary issue.

**Comment by binli2337** [comment]
@BrianCurtis-NOAA Thanks.

**Review by junwang-noaa — APPROVED** [review]

**Comment by binli2337** [comment]
@grantfirl The wcoss log files are at: /scratch1/NCEPDEV/stmp2/Bin.Li/wcoss. Please add the files to your branch. Thanks.

**Comment by grantfirl** [comment]
@binli2337 Done.

**Comment by binli2337** [comment]
@DusanJovic-NOAA Could you review this PR? Thanks.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by binli2337** [comment]
@grantfirl Please update FV3 submodule and .gitmodules. Thanks.

**Comment by grantfirl** [comment]
> @grantfirl Please update FV3 submodule and .gitmodules. Thanks.

@binli2337 Done

**Pull request merged**
