### PR TITLE
Misc NRL bugfixes

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

See the descriptions in https://github.com/NCAR/ccpp-physics/pull/954 and https://github.com/NOAA-EMC/fv3atm/pull/576 for details.

### Issue(s) addressed

https://github.com/NCAR/ccpp-physics/issues/955

## Testing

See https://github.com/NOAA-EMC/fv3atm/pull/576 for testing details.

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

https://github.com/NOAA-EMC/fv3atm/pull/576
https://github.com/NCAR/ccpp-physics/pull/954

### CODE REVIEW

**Comment by jkbk2004** [comment]
@grantfirl sorry for delaying. we will merge in #1399 around lunch time today. and then we can start working on this PR.

**Comment by jkbk2004** [comment]
@grantfirl can you sync up branch? and then I will add new BL_DATE. we can start working on this pr.

**Comment by grantfirl** [comment]
> @grantfirl can you sync up branch? and then I will add new BL_DATE. we can start working on this pr.

OK @jkbk2004 This PR and all submodule PRs have been updated/synced with the latest develop/main branches after the AQM merge.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1035943918/20220909193022/ufs-weather-model
[BL] Error: Test compile_017 failed in run_compile failed 
[BL] Error: Test compile_018 failed in run_compile failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/1035943918/20220910003007/ufs-weather-model
[BL] Error: Test hafs_global_storm_following_1nest_atm 092 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 Could you start adding comments with reasons for failure seen on machines (orion & gaea in this case). It would be good to know and keep track of.

**Comment by jkbk2004** [comment]
gaea failure was "Slurm unknown status": it ran ok with re-submission. On orion, it seems there is a git issue: HYCOM: manually ran. Following up with help desk.

**Comment by jkbk2004** [comment]
@grantfirl all tests are done. we can start merging in dependencies: ccpp first.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
@jkbk2004 ccpp-physics has been merged and the fv3atm PR branch has been updated.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@grantfirl we can merge in after updating fv3 pointer and reverting branch in gitmodules.

**Comment by grantfirl** [comment]
@jkbk2004 OK, should be good to go now.

**Comment by BrianCurtis-NOAA** [comment]
Just noting that tests also passed on Acorn.

**Pull request merged**
