### PR TITLE
[production/RRFS.v1] Update module_write_netcdf to avoid hangs in RRFS runs

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
### Commit Message:

```
* UFSWM - 
  * AQM - 
  * CDEPS - 
  * CICE - 
  * CMEPS - 
  * CMakeModules - 
  * FV3 - 
    * ccpp-physics - 
    * atmos_cubed_sphere - 
  * GOCART - 
  * HYCOM - 
  * MOM6 - 
  * NOAHMP - 
  * WW3 - 
  * stochastic_physics - 
```

### Priority:

* Critical Bugfix: Reason
* High: Reason
* Normal

### UFSWM:

* Closes #
* None

### Sub component Pull Requests:

* AQM:
* CDEPS:
* CICE:
* CMEPS:
* CMakeModules:
* FV3:
  * ccpp-physics:
  * atmos_cubed_sphere:
* GOCART:
* HYCOM:
* MOM6:
* NOAHMP:
* WW3:
* stochastic_physics:
* None

### UFSWM Blocking Dependencies:

* Blocked by #
* None

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.
* PR Updates/Changes Baselines.
* No Baseline Changes.

### Input data Changes:

* None.
* New input data.
* Updated input data.

### Library Changes/Upgrades:

* Required
  * Library names w/versions:
  * Git Stack Issue (JCSDA/spack-stack#)
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [ ] Orion
  - [x] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by hu5970** [comment]
The tests with RRFS_A on development machine are successful. Please merge this PR.

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA #2193 is on-going. So it's good timing to work on this pr as well. I need to test if we can use Hera rocky8 in this pr.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can you convert draft pr to pr?

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA We can start merging process if we don't need to test on more than hera/hercules/wcoss2 machines. #2193  ran all ok. So, I think we are good to merge the pr.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Looks good to me...approving.

**Comment by MatthewPyle-NOAA** [comment]
@jkbk2004 Can help with merging later today - let me know what you need me to do.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA can you update fv3 hash: https://github.com/NOAA-EMC/fv3atm/commit/c01786de120534604f686e206c5be6005d96f55b ?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA can you update fv3 hash: [NOAA-EMC/fv3atm@c01786d](https://github.com/NOAA-EMC/fv3atm/commit/c01786de120534604f686e206c5be6005d96f55b) ?

Done.

**Review by MatthewPyle-NOAA — APPROVED** [review]
Thanks @DusanJovic-NOAA

**Comment by jkbk2004** [comment]
@MatthewPyle-NOAA All looks good. This pr can be merged.

**Pull request merged**
