### PR TITLE
 bug fix from @tanyasmirnova for rrfs crashes during restart

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description
This fix from @tanyasmirnova eliminates the crash described in #1655

Adds a regression test `rrfs_conus13km_hrrr_warm_restart_mismatch` which runs the restart of `rrfs_conus13km_hrrr_warm`. The restart does *not* match the control due to unknown bugs. Instead, the restart test has its own baseline and compares against that. This is to ensure the restart keeps working, at least for the 13km CONUS test case. (Though, it should be noted that the conus13km regression test didn't crash with the bug.)

### Input data additions/changes
- [x] No changes are expected to input data.

### Anticipated changes to regression tests:
- [x] *New regression test* on all platforms.
- [x] No changes are expected to any existing regression tests.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:
Depends on https://github.com/NOAA-EMC/fv3atm/pull/636
Related issue #1655

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [ ] Hera
    - [ ] Orion
    - [ ] Jet
    - [ ] Gaea
    - [ ] Cheyenne
  - GNU
    - [ ] Hera
    - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Review by tanyasmirnova — DISMISSED** [review]

**Comment by SamuelTrahanNOAA** [comment]
@jkbk2004 - I suggest you combine this PR with either #1646 (which updates the same LSM and is from the same developer) or #1633, which adds restart functionality.

**Comment by SamuelTrahanNOAA** [comment]
This should definitely be merged during or before #1646 to ensure the updated LSM has the restart bug fixes needed for it to function properly.

**Comment by jkbk2004** [comment]
merged with #1646

**Comment by tanyasmirnova** [comment]
@SamuelTrahanNOAA @grantfirl @dustinswales @zach1221 @jkbk2004 @RatkoVasic-NOAA @BrianCurtis-NOAA @uturuncoglu Thank you ALL very much for your amazing work to make this merge happen, and happen on time. Have a great weekend!

**Pull request closed without merging**
