### PR TITLE
Update develop from gsd/develop 2020/11/20: Unified gravity wave drag, updates to other GSL physics

### LINKED ISSUE #135: Compile with DEBUG=Y must add "--debug" to ccpp_prebuild.py
This used to be the case, however, it doesn't work any longer.
```
./compile_cmake.sh $PWD/.. hera.intel 'CCPP=Y DEBUG=Y'
```
does not add `--debug` to the `ccpp_prebuild.py` command.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR updates the GSL physics. Changes:
- add unified gravity wave drag (called unified ugwp) that combines the UGWP v1 with the GSL drag suite
- replace high-resolution SAR (standalone regional) regression test with 25km SAR regression test
- update submodule pointer for fv3atm for the changes described in the associated PRs listed below
- add `rt_ccpp_dev.conf` that contains the developmental CCPP tests used by GSL and DTC (so that folks are aware of what is tested and how by DTC and GSL, in addition to what is in `rt.conf` and `rt_gnu.conf`)
- turn on calls to `gcycle`/`sfcsub` for RUC LSM
- regression test configuration scripts for MYNN surface layer
- add `fv3_debug` modules for cheyenne.intel and cheyenne.gnu (per request from @DeniseWorthen)
- bugfix in `rt.sh` to copy two missing input directories `fv3_regional_quilt_netcdf_parallel` and `fv3_stretched_nest_debug` when creating new baselines using `rt.sh -c`
- enable regression testing on Gaea with Intel using the current hpc-stack-nco installation, can now use ecflow
- update of CI tests and small bugfix when comparing results using `tests/compare_ncfile.py` from @MinsukJi-NOAA (see https://github.com/ufs-community/ufs-weather-model/pull/299 for details) - note, the update to `tests/compare_ncfile.py` had to be reverted

**Note 1.** This PR needs to be squashed at merge time, because it the commit history shows all the individual commits from the previous merges (which were squashed as well). Following this commit, the gsd/develop branches in the NOAA-GSL fork will be deleted and we will start with a clean plate from develop for our new branches gsl/develop.

**Note 2.** While this PR is ready for review, I am expecting that I will have to update the modulefiles for a few platforms (not tier-1): linux.gnu (to fix the hpc-stack issue), gaea.intel, cheyenne.intel, cheyenne.gnu, possibly jet.intel.

**Note 3.** I added a temporary script to create a new, temporary regression test input data directory called `create_tmp_baseline.sh`. It takes three arguments: (1) existing regression test baseline dir, (2) new temporary regression test baseline dir (must not exist yet), (3) whether to copy S2S baselines or not (Y|N). Once the regression testing has finished on all platforms, I will remove the script before merging.

### Regression testing against existing baselines
- on hera.intel using `rt.conf`: the following tests fail as expected because of updates to the GSL physics (but they all run to completion):
```
fv3_ccpp_thompson 043 failed in check_result
fv3_ccpp_thompson_no_aero 044 failed in check_result
fv3_ccpp_HAFS_v0_hwrf_thompson_debug 065 failed in check_result
fv3_ccpp_thompson_no_aero_debug 063 failed in check_result
fv3_ccpp_thompson_debug 062 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson_debug 066 failed in check_result
fv3_ccpp_hrrr 042 failed in check_result
fv3_ccpp_rap 041 failed in check_result
fv3_ccpp_rrfs_v1beta 045 failed in check_result
fv3_ccpp_gsd 040 failed in check_result
fv3_ccpp_gsd_debug 060 failed in check_result
fv3_ccpp_rrfs_v1beta_debug 064 failed in check_result
fv3_ccpp_HAFS_v0_hwrf_thompson 054 failed in check_result
fv3_ccpp_gsd_diag3d_debug 061 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson 055 failed in check_result
```
[rt_hera_intel_against_existing_baseline.log](https://github.com/ufs-community/ufs-weather-model/files/5580965/rt_hera_intel_against_existing_baseline.log)
[rt_hera_intel_against_existing_baseline_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/5580966/rt_hera_intel_against_existing_baseline_fail_test.log)

- on hera.gnu using `rt_gnu.conf`: the following tests fail as expected because of updates to the GSL physics (but they all run to completion):
```
fv3_ccpp_HAFS_v0_hwrf_thompson_debug 019 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson_debug 020 failed in check_result
fv3_ccpp_thompson 008 failed in check_result
fv3_ccpp_thompson_no_aero 009 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson 012 failed in check_result
fv3_ccpp_rrfs_v1beta 010 failed in check_result
fv3_ccpp_HAFS_v0_hwrf_thompson 011 failed in check_result
fv3_ccpp_gsd 007 failed in check_result
```
[rt_hera_gnu_against_existing_baseline.log](https://github.com/ufs-community/ufs-weather-model/files/5580969/rt_hera_gnu_against_existing_baseline.log)
[rt_hera_gnu_against_existing_baseline_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/5580970/rt_hera_gnu_against_existing_baseline_fail_test.log)

### Final regression testing on Tier-1 and Tier-2 platforms

Regression tests passed on cheyenne.gnu, cheyenne.intel, hera.gnu, hera.intel, gaea.intel, orion.intel, wcoss_cray, wcoss_dell_p3; logs updated in the PR.

### Additional testing

Additional tests on cheyenne.intel using `rt_ccpp_dev.conf`: first create new baseline (to make sure all tests work), then verify against it (to check b4b reproducibility in restarts etc.): all tests pass.

[rt_ccpp_dev_cheyenne_intel_create.log](https://github.com/ufs-community/ufs-weather-model/files/5592371/rt_ccpp_dev_cheyenne_intel_create.log)
[rt_ccpp_dev_cheyenne_intel_verify.log](https://github.com/ufs-community/ufs-weather-model/files/5592372/rt_ccpp_dev_cheyenne_intel_verify.log)

## Dependencies

https://github.com/NCAR/ccpp-framework/pull/338
https://github.com/NCAR/ccpp-physics/pull/521
https://github.com/NOAA-EMC/fv3atm/pull/202
https://github.com/ufs-community/ufs-weather-model/pull/297

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
`fv3_ccpp_wrtGauss_netcdf_parallel` test failed on WCOSS Dell:
```
baseline dir = /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20201124/fv3_wrtGauss_netcdf_parallel_ccpp
working dir  = /gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_138156/fv3_ccpp_wrtGauss_netcdf_parallel_prod
Checking test 008 fv3_ccpp_wrtGauss_netcdf_parallel results ....
 Comparing atmos_4xdaily.tile1.nc .........OK
 Comparing atmos_4xdaily.tile2.nc .........OK
 Comparing atmos_4xdaily.tile3.nc .........OK
 Comparing atmos_4xdaily.tile4.nc .........OK
 Comparing atmos_4xdaily.tile5.nc .........OK
 Comparing atmos_4xdaily.tile6.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc ............ALT CHECK......NOT OK
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc ............ALT CHECK......OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_core.res.tile2.nc .........OK
 Comparing RESTART/fv_core.res.tile3.nc .........OK
 Comparing RESTART/fv_core.res.tile4.nc .........OK
 Comparing RESTART/fv_core.res.tile5.nc .........OK
 Comparing RESTART/fv_core.res.tile6.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile2.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile3.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile4.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile5.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile6.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc .........OK
 Comparing RESTART/fv_tracer.res.tile2.nc .........OK
 Comparing RESTART/fv_tracer.res.tile3.nc .........OK
 Comparing RESTART/fv_tracer.res.tile4.nc .........OK
 Comparing RESTART/fv_tracer.res.tile5.nc .........OK
 Comparing RESTART/fv_tracer.res.tile6.nc .........OK
 Comparing RESTART/phy_data.tile1.nc .........OK
 Comparing RESTART/phy_data.tile2.nc .........OK
 Comparing RESTART/phy_data.tile3.nc .........OK
 Comparing RESTART/phy_data.tile4.nc .........OK
 Comparing RESTART/phy_data.tile5.nc .........OK
 Comparing RESTART/phy_data.tile6.nc .........OK
 Comparing RESTART/sfc_data.tile1.nc .........OK
 Comparing RESTART/sfc_data.tile2.nc .........OK
 Comparing RESTART/sfc_data.tile3.nc .........OK
 Comparing RESTART/sfc_data.tile4.nc .........OK
 Comparing RESTART/sfc_data.tile5.nc .........OK
 Comparing RESTART/sfc_data.tile6.nc .........OK
Test 008 fv3_ccpp_wrtGauss_netcdf_parallel FAIL
```

**Comment by DusanJovic-NOAA** [comment]
Files are not bit-identical, but both data and metadata are identical:
```
$ nccmp -d /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20201124/fv3_wrtGauss_netcdf_parallel_ccpp/phyf024.nc /gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_138156/fv3_ccpp_wrtGauss_netcdf_parallel_prod/phyf024.nc

$ nccmp -m /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20201124/fv3_wrtGauss_netcdf_parallel_ccpp/phyf024.nc /gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_138156/fv3_ccpp_wrtGauss_netcdf_parallel_prod/phyf024.nc

```

**Comment by DusanJovic-NOAA** [comment]
```
$ ./compare_ncfile.py /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20201124/fv3_wrtGauss_netcdf_parallel_ccpp/phyf024.nc /gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_138156/fv3_ccpp_wrtGauss_netcdf_parallel_prod/phyf024.nc

./compare_ncfile.py:12: UserWarning: WARNING: missing_value not used since it
cannot be safely cast to variable data type
  diff = nc2[varname][:]-nc1[varname][:]

```

**Comment by junwang-noaa** [comment]
Is anything related to compare_ncfile.py changed? I saw Chan-hoo's test
passed on dell/hera.

**Comment by climbfuji** [comment]
> `fv3_ccpp_wrtGauss_netcdf_parallel` test failed on WCOSS Dell:
> 
> ```
> baseline dir = /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/RT/NEMSfv3gfs/develop-20201124/fv3_wrtGauss_netcdf_parallel_ccpp
> working dir  = /gpfs/dell2/ptmp/Dusan.Jovic/FV3_RT/rt_138156/fv3_ccpp_wrtGauss_netcdf_parallel_prod
> Checking test 008 fv3_ccpp_wrtGauss_netcdf_parallel results ....
>  Comparing atmos_4xdaily.tile1.nc .........OK
>  Comparing atmos_4xdaily.tile2.nc .........OK
>  Comparing atmos_4xdaily.tile3.nc .........OK
>  Comparing atmos_4xdaily.tile4.nc .........OK
>  Comparing atmos_4xdaily.tile5.nc .........OK
>  Comparing atmos_4xdaily.tile6.nc .........OK
>  Comparing phyf000.nc .........OK
>  Comparing phyf024.nc ............ALT CHECK......NOT OK
>  Comparing dynf000.nc .........OK
>  Comparing dynf024.nc ............ALT CHECK......OK
>  Comparing RESTART/coupler.res .........OK
>  Comparing RESTART/fv_core.res.nc .........OK
>  Comparing RESTART/fv_core.res.tile1.nc .........OK
>  Comparing RESTART/fv_core.res.tile2.nc .........OK
>  Comparing RESTART/fv_core.res.tile3.nc .........OK
>  Comparing RESTART/fv_core.res.tile4.nc .........OK
>  Comparing RESTART/fv_core.res.tile5.nc .........OK
>  Comparing RESTART/fv_core.res.tile6.nc .........OK
>  Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
>  Comparing RESTART/fv_srf_wnd.res.tile2.nc .........OK
>  Comparing RESTART/fv_srf_wnd.res.tile3.nc .........OK
>  Comparing RESTART/fv_srf_wnd.res.tile4.nc .........OK
>  Comparing RESTART/fv_srf_wnd.res.tile5.nc .........OK
>  Comparing RESTART/fv_srf_wnd.res.tile6.nc .........OK
>  Comparing RESTART/fv_tracer.res.tile1.nc .........OK
>  Comparing RESTART/fv_tracer.res.tile2.nc .........OK
>  Comparing RESTART/fv_tracer.res.tile3.nc .........OK
>  Comparing RESTART/fv_tracer.res.tile4.nc .........OK
>  Comparing RESTART/fv_tracer.res.tile5.nc .........OK
>  Comparing RESTART/fv_tracer.res.tile6.nc .........OK
>  Comparing RESTART/phy_data.tile1.nc .........OK
>  Comparing RESTART/phy_data.tile2.nc .........OK
>  Comparing RESTART/phy_data.tile3.nc .........OK
>  Comparing RESTART/phy_data.tile4.nc .........OK
>  Comparing RESTART/phy_data.tile5.nc .........OK
>  Comparing RESTART/phy_data.tile6.nc .........OK
>  Comparing RESTART/sfc_data.tile1.nc .........OK
>  Comparing RESTART/sfc_data.tile2.nc .........OK
>  Comparing RESTART/sfc_data.tile3.nc .........OK
>  Comparing RESTART/sfc_data.tile4.nc .........OK
>  Comparing RESTART/sfc_data.tile5.nc .........OK
>  Comparing RESTART/sfc_data.tile6.nc .........OK
> Test 008 fv3_ccpp_wrtGauss_netcdf_parallel FAIL
> ```

I get failures of both parallel tests on hera.intel, orion.intel, gaea.intel. Running `compare_ncfile.py` manually shows no differences for the file I tested. I assume it has to do with the environment in the ecflow job that doesn't run the Python script correctly. Testing this now. This has nothing to do with the GSL physics changes or any other changes in this PR, it's simply because of the bugfixes in PR #299 that I pulled in (beforehand these errors went unnoticed and the file comparison test was flagged as OK).

**Comment by MinsukJi-NOAA** [comment]
Current behavior of compare_ncfile.py with `2>&1` stderr redirection
When two files are the same: no output; exit code is 0; RT pass
When two files are different: output to stdout; exit code is 1; RT fail
When the program fails: output to stderr; exit code is 1; RT fail
When the program displays warning messages (what Dusan observed): output to stderr; RT fail

Please make sure your ecflow_server instances are correct (ps aux | grep ecflow | grep $USER)
/scratch1/NCEPDEV/nems/emc.nemspara/soft/miniconda3/bin on Hera
/work/noaa/nems/emc.nemspara/soft/miniconda3/bin on Orion

**Comment by climbfuji** [comment]
> Current behavior of compare_ncfile.py with `2>&1` stderr redirection
> When two files are the same: no output; exit code is 0; RT pass
> When two files are different: output to stdout; exit code is 1; RT fail
> When the program fails: output to stderr; exit code is 1; RT fail
> When the program displays warning messages (what Dusan observed): output to stderr; RT fail
> 
> Please make sure your ecflow_server instances are correct (ps aux | grep ecflow | grep $USER)
> /scratch1/NCEPDEV/nems/emc.nemspara/soft/miniconda3/bin on Hera
> /work/noaa/nems/emc.nemspara/soft/miniconda3/bin on Orion

Note: on hera, I had the old ecflow server still running, so that could have been one part of the issue. However, on orion and hera, I had a new ecflow server running that was started as part of the rt.sh call. So the ecflow server alone is not the issue.

**Review by MinsukJi-NOAA — APPROVED** [review]
Looks good to me.

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]
I've been able to build on cheyenne using fv3_debug. Thanks for providing this.

**Comment by climbfuji** [comment]
Thanks everyone - let's wait for the CI tests to complete before merging.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA all CI tests passed, do you want to merge the PR?

**Pull request merged**
