### PR TITLE
Add hi-res regional test on small domain

### LINKED ISSUE #1054: Regional hi-res, small domain new regression test
## Description
Regional group asked to test 3km resolution regional application.

## Solution
Since full domain would take a lot of time and CPU resources, we came up with very small domain (350x200 points) with 6 hours run in ~4.5 minutes real time.

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.
Issue #1054 

- [x] Already added new test results to Hera, WCOSS-Dell and WCOSS-Cray in directories:
 develop-20220228
 develop-20220304

- [x] Already added new initial conditions on Hera, WCOSS-Dell and WCOSS-Cray (in input-data-20211210)

## Instructions: All subsequent sections of text should be filled in as appropriate.

Added hi res regional case on small domain to test it before every commit to develop branch.

## Description

This addition was done by request of the CAM group.

### Issue(s) addressed

- fixes #1054 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI (Not run; needs updates after aero update; PR #1119 )
 
## NOTE ##
Since I tested this on only 3 machines (Hera, WCOSS-Dell and WCOSS-Cray) I put in rt.conf: "+ hera.intel wcoss_cray wcoss2". I don't have access to other machines. You may want to add this test to all other machines. Just add new ICs in input-data-20211210/fv3_regional_3km_small subdirectory. And results to develop-2022****/fv3_regional_3km_small

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@RatkoVasic-NOAA Can you  add the required input for all platforms where you have nemspara access? I will add it to Cheyenne.

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA Can you add the required input for all platforms where you have nemspara access? I will add it to Cheyenne.

I have access only to Hera, wcoss-cray and wcoss-dell. I did it at those machines.

**Comment by DeniseWorthen** [comment]
@RatkoVasic-NOAA I assume you want to run the test on all platforms; I've added the input-data (there's an issue w/ orion but it will be there soon). If you want it tested on all platforms, please modify your rt.conf.

**Comment by DeniseWorthen** [comment]
Then please update your branch to the latest develop. Can you add the results to the latest baselines on hera and the wcoss and run the complete baselines? I will run the single test for the remaining platforms and then run the verify. Thanks.

**Comment by RatkoVasic-NOAA** [comment]
> 

@DeniseWorthen there are some problems with e-mail. Other people are complaining too. I sent you 5-6 emails in the meantime, my guess is that you haven't received them?

**Comment by DeniseWorthen** [comment]
No, I have not received any emails.

**Comment by RatkoVasic-NOAA** [comment]
> No, I have not received any emails.

please call me on 310-895-1479

**Comment by RatkoVasic-NOAA** [comment]
> No, I have not received any emails.

/scratch1/NCEPDEV/stmp4/Ratko.Vasic/rv_001/tests/log_hera.intel

**Comment by DeniseWorthen** [comment]
Sorry---deleted my previous comment! Totally confused for a moment.

**Comment by DeniseWorthen** [comment]
I think the problem is that you removed the required suite for the control_p8 tests:
```
diff --git a/tests/rt.conf b/tests/rt.conf
index 49347a9c..8d0154ff 100644
--- a/tests/rt.conf
+++ b/tests/rt.conf
@@ -31,7 +31,7 @@ RUN     | cpld_debug_p8
 # PROD tests                                                                                                                                                                      #
 ###################################################################################################################################################################################

-COMPILE | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP,FV3_GFS_v16_p7_rrtmgp,FV3_GFS_v17_p8 -D32BIT=ON   |                | fv3 |
+COMPILE | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP,FV3_GFS_v16_p7_rrtmgp,FV3_GFS_v16_p8,FV3_GFS_v15_thompson_mynn_lam3km -D32BIT=ON |    | fv3 |
```

We need v17_p8, not v16_p8

**Comment by RatkoVasic-NOAA** [comment]
I see, I'll correct this.
Good catch!!!
I guess that line was changed by previous commit and mine. I missed that 16 was upgraded to 17.

**Comment by DeniseWorthen** [comment]
I am running the gnu tests on both platforms; there are no changes expected, but we need the full RT log set. I've started the test on jet manually.

**Comment by RatkoVasic-NOAA** [comment]
Hera: REGRESSION TEST WAS SUCCESSFUL
Surge: REGRESSION TEST WAS SUCCESSFUL
Venus: 
control_ras_debug 077 failed in run_test
hafs_regional_1nest_atm 104 failed in run_test
I'll run it again.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/872589284/20220317134523/ufs-weather-model
[RT] Error: Test control_csawmg_debug 075 failed in run_test failed 
[RT] Error: Test control_debug_p8 079 failed in run_test failed 
Please make changes and add the following label back: orion-intel-RT

**Comment by DeniseWorthen** [comment]
I can't find any reason for the 2 failures on Orion. The jobs compiled but didn't seem to run. I'll repeat those two tests.

**Comment by RatkoVasic-NOAA** [comment]
@DeniseWorthen 
reg tests on wcoss-dell 077 (control_diag_debug) and 104 (hafs_regional_telescopic_2nests_atm) failed.

I submitted rt.sh again.

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA May I ask what is the error message for the two tests failed on dell?

**Comment by RatkoVasic-NOAA** [comment]
@junwang-noaa I deleted that run, and ran rt.sh again.
Now there are 3 different failing runs:

rap_diag_debug 087 failed in run_test
hafs_regional_atm 099 failed in run_test
hafs_regional_atm_thompson_gfdlsf 100 failed in run_test

They did their job, but later hanged and exceeded wallclock.
My code directory: /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/REG_RT/rv_002/tests/
RT run directory: /gpfs/dell2/ptmp/Ratko.Vasic/FV3_RT/rt_50987/

**Comment by junwang-noaa** [comment]
Thanks for the information, so these are random failures, the tests hang and there is no error message with "User defined signal 2".  Would you please rerun the three tests? Thanks

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA I think the issue with the failed tests has nothing to do with your PR. We had some reports on failed tests on dell in the past weeks, but without error message documented. Rerunning failed tests usually succeeds. So please keep your first RT log file on dell, write down the error message in your PR. If the rerunning of the three tests finishes successfully. Please combine the two log files, and commit in your branch. This way we can track this issue.  Sometimes the developers just rerun the RT until it is successful, so we lost the track from which PR the issue started. Thanks

**Comment by RatkoVasic-NOAA** [comment]
@junwang-noaa I ran last three tests and they passed. I combined log files into one (RegressionTests_wcoss_dell_p3.log) and pushed it to my branch.

**Review by junwang-noaa — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Pull request merged**
