### PR TITLE
Feature/addnsst test

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [ ] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ ] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Adds 35d noahmp_nsst test; switches v16_noahmp and v16_noahmp_nsst to using mushy thermodynamics for CICE.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
I tested both the noahmp and the noahmp_nsst 35d tests with the mushy turned on and both correctly started up using mushy thermodynamics.

**Review by junwang-noaa — APPROVED** [review]
Thanks for testing, let's commit this PR. I will use 20130401 case to test the updated atmos namelist.

**Comment by DeniseWorthen** [comment]
Do we want to also point to a new input-data-directory date in rt.sh? We'd then move the existing input-data-20210608 to that new name.

**Comment by junwang-noaa** [comment]
Yes, that would be good.

**Comment by DeniseWorthen** [comment]
OK. I checked w/ Jiande and he said the change would have no impact since all his jobs have currently started. 

@JessicaMeixner-NOAA I will move the ``input-data-20210608`` on Hera to ``prototype7-input-data-20210608`` and change the rt.sh to use that directory when running from the p7b branch. If changes are required to the input for the mini-ps, you will be able to make those changes in that directory (or create a new one) without impacting the current baselines.

**Pull request merged**
