### PR TITLE
switch WW3 from develop to dev/ufs-weather-model

### LINKED ISSUE #861: create dev/ufs-weather-model branch on WW3 repo
## Description
In order to facilitate the ufs-weather-model development, a branch on the main repository of the WW3 model should be created of the develop branch and the ufs-weather-model should be directed to that branch.

### PR DESCRIPTION
**Pull request by aliabdolali**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description
1- dev/ufs-weather-model branch is created on ww3 repo. 
2- The ufs-weather-model wave component is changed from develop to dev/ufs-weather-model.
3- sync ww3 as of Oct 6th 2021.
The tests ran successfully. There is no need to update the inputs but there are expected changes for the following tests:
_cpld_control_wave_p7_
`Comparing 20210322.180000.out_pnt.points .........NOT OK`
and
_cpld_bmark_p7_
`Comparing 20130401.060000.out_pnt.points .........NOT OK`

The base for these two tests contains wave point outputs, which has changed due to https://github.com/NOAA-EMC/WW3/pull/483 in WW3 repo.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #861 
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@aliabdolali Please complete the PR template. 

Also, why do the two files you mention have changed results? Is it related to meta-data or the actual fields?

**Comment by aliabdolali** [comment]
> @aliabdolali Please complete the PR template.
> 
> Also, why do the two files you mention have changed results? Is it related to meta-data or the actual fields?

@DeniseWorthen i updated the PR. The two tests with wave components have wave point outputs, which should change due to a commit in WW3.

**Comment by JessicaMeixner-NOAA** [comment]
It's a change in meta-data, not the actual fields. It's because of WW3  PR https://github.com/NOAA-EMC/WW3/pull/483  the version number changed (https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/w3iopomd.ftn#L103): 
`      CHARACTER(LEN=10), PARAMETER, PRIVATE :: VEROPT = '2021-04-06'
`

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Thanks for the clarification. It is good to know when test changes are actually due to issues like that because it allows us to consider combining various "baseline changing" PRs.

**Comment by climbfuji** [comment]
@junwang-noaa is it correct that you want me to pull this into #850 ? Note that #850 doesn't change results, which is what I want, because there are so many changes combined. If I add #860, then it will change results for cpld_control_wave_p7 and cpld_bmark_p7 as @aliabdolali described above.

**Comment by junwang-noaa** [comment]
@DomHeinzeller Since ww3 PRs have higher priority, we have to either commit this ww3 PR, then move #850 to a later date. OR have the two PR combined. If we do combined PR, Ali will copy the baseline to a new baseline directory and update the two files in the two tests (@aliabdolali , will the atm_wav tests also change results?), then we run full RT against the baseline. Please let me know which way you prefer.

**Comment by climbfuji** [comment]
> @DomHeinzeller Since ww3 PRs have higher priority, we have to either commit this ww3 PR, then move #850 to a later date. OR have the two PR combined. If we do combined PR, Ali will copy the baseline to a new baseline directory and update the two files in the two tests (@aliabdolali , will the atm_wav tests also change results?), then we run full RT against the baseline. Please let me know which way you prefer.

Alright, let's combine them. I will manually make sure that none of the other results changed (by comparing the new and old baselines)

**Comment by aliabdolali** [comment]
@junwang-noaa is the commit queue up to date?

**Comment by climbfuji** [comment]
This PR was pulled into https://github.com/ufs-community/ufs-weather-model/pull/850 and will be merged as part of it.

**Comment by climbfuji** [comment]
@aliabdolali I already made the repo check change in my PR. I am not going to pull in any further updates from your PR, so no need to make any changes here.

**Comment by aliabdolali** [comment]
> @aliabdolali I already made the repo check change in my PR. I am not going to pull in any further updates from your PR, so no need to make any changes here.

awesome, thanks

**Comment by DeniseWorthen** [comment]
Closed. Code committed with PR #850

**Pull request closed without merging**
