### PR TITLE
production/GFS.v16:  Comet porting for production/GFS.v16 (#470)

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR allows the production/GFS.v16 branch of the UFS-weather-model to build and run on SDSC Comet platform.

### Issue(s) addressed

https://github.com/ufs-community/ufs-weather-model/issues/470

## Testing

No testing is required as the changes only concern/affect Comet platform. Intel/Intelmpi is used to build and run fv3_gfdlmprad_32bit_post regression test on Comet.

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/NEMS/pull/93

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
Latest update b371c00 includes these changes:
* FV3 changes are reverted since they are ccpp related
* WW3 changes are reverted since they are not used on Comet
* Now that WW3 is not compiled on Comet, use netcdf 4.7.4 instead of 4.6.1

**Comment by MinsukJi-NOAA** [comment]
I can also remove the rt-related changes since Comet is not a platform we support, and carry out any regression testing on. Also, since WW3 is not used on Comet, I am not aware of any existing regression testing (the test case in rt.conf_gfs includes WW3).

**Comment by JessicaMeixner-NOAA** [comment]
@MinsukJi-NOAA is the porting to comet on the production/gfsv16 branch in WW3 no longer necessary?  

Also these updates going to be allowed to go onto the production branch of gfsv16?  I ask because if an emergency fix is necessary this would cause additional file changes (unrelated to a potential emergency fix) on the production branch which might not be accepted by NCO.

**Comment by junwang-noaa** [comment]
@arunchawla-NOAA Please see Jessica's question and let us know how to move forward. We had several discussions on where the porting production/GFSv16 code changes for R2O project will go. This PR has no impact on operational run.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request closed without merging**
