### PR TITLE
Update  CICE; add CMEPS fix for GNU and turn on cpld test for GNU; update 35d scripts from P7a mini-release

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [X] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

- Updates CICE in ufs-weather. Details of the changes can be found in the associated CICE [PR #26](https://github.com/NOAA-EMC/CICE/pull/26) and Icepack [PR #4](https://github.com/NOAA-EMC/Icepack/pull/4)
- Updates the ``ice_in_template`` for changes due to the time manager update. This removes ``istep0`` and instead sets the ``year_init``, ``month_init`` and ``day_init``.
- Updates ``ice_in_template`` used by ufs-weather-model by removing many unused namelists or settings. This will make it easier to update CICE because the frequent namelist changes (e.g. renaming settings) will not need to be propagated to ufs-weather unless we actually make use of those settings. 
- Sets ``tr_FY`` (the tracer for First Year ice) to false and removes the associated ``frz_onset`` and ``melt_onset`` variables from the history files. These are diagnostic fields which only make sense for multi-year climate runs. They are reset at July 1 a d Jan 1 of each year and therefore have no real meaning in either the Regression testing or the 35-day long runs done for the S2S prototypes.

- Makes fix for unitialized AccumCnts in CMEPS and turn on coupled GNU tests in rt_gnu.conf
- Update 35d scripts from P7a

### Issue(s) addressed

- fixes CICE issue [#27](https://github.com/NOAA-EMC/CICE/issues/27)
- fixes CMEPS issue [#48](https://github.com/NOAA-EMC/CMEPS/issues/48)
## Testing

Testing on Gaea.intel shows that this PR changes baselines solely because the time-manager update results in the ``frz_onset`` restart field to be initialized at 999. Previously, the ``frz_onset`` field would be initialized as the starting julian day. This field is not required for B4B restarts.  All other files compared are B4B with current baselines. Removing the ``frz_onset`` variable causes the comparison to fail.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3

## Dependencies

- CICE PR [#26](https://github.com/NOAA-EMC/CICE/pull/26)
- Icepack PR [#4](https://github.com/NOAA-EMC/Icepack/pull/4)
- CMEPS PR [#49](https://github.com/NOAA-EMC/CMEPS/pull/49)

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/659317000/20210603214512/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_24338
Baseline creation and move successful
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/659317000/20210603232418/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_26377
Test regional_quilt_2threads 054 failed in check_result failed 
Test regional_quilt_2threads 054 failed in run_test failed 
Test regional_control 051 failed in check_result failed 
Test regional_control 051 failed in run_test failed 
Test regional_quilt 053 failed in check_result failed 
Test regional_quilt 053 failed in run_test failed 
Test regional_quilt_hafs 055 failed in check_result failed 
Test regional_quilt_hafs 055 failed in run_test failed 
Test regional_quilt_netcdf_parallel 056 failed in check_result failed 
Test regional_quilt_netcdf_parallel 056 failed in run_test failed 
Test regional_quilt_RRTMGP 057 failed in check_result failed 
Test regional_quilt_RRTMGP 057 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by DeniseWorthen** [comment]
The identical gaea situation happened to me on dell-p3. The baseline looked to create successfully but in fact the 6th compile job failed silently. The baselines report that they were successfully created, but all the jobs which depend on the 6th compile job (``COMPILE | APP=ATM SUITES=FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP 32BIT=Y``) don't run so when the verify step runs, it fails w/ missing baselines for these regional tests. This can have nothing to do w/ auto-bl.

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/659317000/20210603164509/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_361786
Test cpld_control_c384 006 failed in run_test failed 
Test cpld_controlfrac_c384 007 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-BL

**Comment by DeniseWorthen** [comment]
Issues: 
1) On Orion, the two failed tests were time-outs during the run.
2) On Gaea, the attempt to manually compile and re-run the baselines for the Regional tests timed-out in the compile. 
3) On Jet, the jobs never started. I can't even check out my branch, I suspect this is a space issue
4.0K	./Minsuk.Ji,.
32K	./Bin.Li
3.2G	./Brian.Curtis
2.1G	./Mikyung.Lee
660M	./Denise.Worthen
2.0T	./Jun.Wang
9.9T	./emc.nemspara
24K	./Dusan.Jovic
12T	.

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/659317000/20210604063012/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_114369
Test control_ras_debug 079 failed in check_result failed 
Test control_ras_debug 079 failed in run_test failed 
Test control_lheatstrg_debug 073 failed in check_result failed 
Test control_lheatstrg_debug 073 failed in run_test failed 
Test control_debug 067 failed in check_result failed 
Test control_debug 067 failed in run_test failed 
Test control_ugwpv1_debug 078 failed in check_result failed 
Test control_ugwpv1_debug 078 failed in run_test failed 
Test control_lndp_debug 072 failed in check_result failed 
Test control_lndp_debug 072 failed in run_test failed 
Test control_stochy_debug 071 failed in check_result failed 
Test control_stochy_debug 071 failed in run_test failed 
Test control_CubedSphereGrid_debug 069 failed in check_result failed 
Test control_CubedSphereGrid_debug 069 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel_debug 070 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel_debug 070 failed in run_test failed 
Test control_rrtmgp_debug 075 failed in check_result failed 
Test control_rrtmgp_debug 075 failed in run_test failed 
Test control_thompson_no_aero_debug 081 failed in check_result failed 
Test control_thompson_no_aero_debug 081 failed in run_test failed 
Test control_thompson_debug 080 failed in check_result failed 
Test control_thompson_debug 080 failed in run_test failed 
Test control_2threads_debug 068 failed in check_result failed 
Test control_2threads_debug 068 failed in run_test failed 
Test cpld_debugfrac 029 failed in check_result failed 
Test cpld_debugfrac 029 failed in run_test failed 
Test control_merra2_debug 074 failed in check_result failed 
Test control_merra2_debug 074 failed in run_test failed 
Test cpld_debug 028 failed in check_result failed 
Test cpld_debug 028 failed in run_test failed 
Test control_csawmgt_debug 077 failed in check_result failed 
Test control_csawmgt_debug 077 failed in run_test failed 
Test control_csawmg_debug 076 failed in check_result failed 
Test control_csawmg_debug 076 failed in run_test failed 
Test cpld_ca 007 failed in check_result failed 
Test cpld_ca 007 failed in run_test failed 
Test cpld_controlfrac 003 failed in check_result failed 
Test cpld_controlfrac 003 failed in run_test failed 
Test cpld_2threads 005 failed in check_result failed 
Test cpld_2threads 005 failed in run_test failed 
Test cpld_control 001 failed in check_result failed 
Test cpld_control 001 failed in run_test failed 
Test cpld_decomp 006 failed in check_result failed 
Test cpld_decomp 006 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 065 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson 065 failed in run_test failed 
Test control 030 failed in check_result failed 
Test control 030 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 087 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson_debug 087 failed in run_test failed 
Test control_2threads 032 failed in check_result failed 
Test control_2threads 032 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 035 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel 035 failed in run_test failed 
Test control_decomp 031 failed in check_result failed 
Test control_decomp 031 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 088 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 088 failed in run_test failed 
Test control_CubedSphereGrid 034 failed in check_result failed 
Test control_CubedSphereGrid 034 failed in run_test failed 
Test cpld_control_wave 027 failed in check_result failed 
Test cpld_control_wave 027 failed in run_test failed 
Test control_c192 036 failed in check_result failed 
Test control_c192 036 failed in run_test failed 
Test cpld_controlfrac_c192 010 failed in check_result failed 
Test cpld_controlfrac_c192 010 failed in run_test failed 
Test control_ca 040 failed in check_result failed 
Test control_ca 040 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 066 failed in run_test failed 
Test cpld_control_c192 008 failed in check_result failed 
Test cpld_control_c192 008 failed in run_test failed 
Test control_lheatstrg 042 failed in check_result failed 
Test control_lheatstrg 042 failed in run_test failed 
Test control_c384gdas 038 failed in check_result failed 
Test control_c384gdas 038 failed in run_test failed 
Test control_c384 037 failed in check_result failed 
Test control_c384 037 failed in run_test failed 
Test control_lndp 041 failed in check_result failed 
Test control_lndp 041 failed in run_test failed 
Test control_stochy 039 failed in check_result failed 
Test control_stochy 039 failed in run_test failed 
Test control_rrtmgp 044 failed in check_result failed 
Test control_rrtmgp 044 failed in run_test failed 
Test control_ugwpv1 048 failed in check_result failed 
Test control_ugwpv1 048 failed in run_test failed 
Test regional_quilt_2threads 056 failed in check_result failed 
Test regional_quilt_2threads 056 failed in run_test failed 
Test control_thompson 050 failed in check_result failed 
Test control_thompson 050 failed in run_test failed 
Test control_noahmp 052 failed in check_result failed 
Test control_noahmp 052 failed in run_test failed 
Test control_flake 047 failed in check_result failed 
Test control_flake 047 failed in run_test failed 
Test control_csawmg 045 failed in check_result failed 
Test control_csawmg 045 failed in run_test failed 
Test control_merra2 043 failed in check_result failed 
Test control_merra2 043 failed in run_test failed 
Test control_ras 049 failed in check_result failed 
Test control_ras 049 failed in run_test failed 
Test control_thompson_no_aero 051 failed in check_result failed 
Test control_thompson_no_aero 051 failed in run_test failed 
Test regional_control 053 failed in check_result failed 
Test regional_control 053 failed in run_test failed 
Test regional_quilt 055 failed in check_result failed 
Test regional_quilt 055 failed in run_test failed 
Test fv3_hrrr 063 failed in check_result failed 
Test fv3_hrrr 063 failed in run_test failed 
Test fv3_rap 062 failed in check_result failed 
Test fv3_rap 062 failed in run_test failed 
Test regional_quilt_hafs 057 failed in check_result failed 
Test regional_quilt_hafs 057 failed in run_test failed 
Test fv3_rrfs_v1alpha 061 failed in check_result failed 
Test fv3_rrfs_v1alpha 061 failed in run_test failed 
Test regional_quilt_netcdf_parallel 058 failed in check_result failed 
Test regional_quilt_netcdf_parallel 058 failed in run_test failed 
Test control_csawmgt 046 failed in check_result failed 
Test control_csawmgt 046 failed in run_test failed 
Test fv3_gsd 060 failed in check_result failed 
Test fv3_gsd 060 failed in run_test failed 
Test regional_quilt_RRTMGP 059 failed in check_result failed 
Test regional_quilt_RRTMGP 059 failed in run_test failed 
Test cpld_bmark 016 failed in check_result failed 
Test cpld_bmark 016 failed in run_test failed 
Test fv3_rrfs_v1beta 064 failed in check_result failed 
Test fv3_rrfs_v1beta 064 failed in run_test failed 
Test datm_bulk_cfsr 092 failed in check_result failed 
Test datm_bulk_cfsr 092 failed in run_test failed 
Test datm_control_gefs 091 failed in check_result failed 
Test datm_control_gefs 091 failed in run_test failed 
Test datm_bulk_gefs 093 failed in check_result failed 
Test datm_bulk_gefs 093 failed in run_test failed 
Test cpld_bmarkfrac_v16_nsst 021 failed in check_result failed 
Test cpld_bmarkfrac_v16_nsst 021 failed in run_test failed 
Test datm_control_cfsr 089 failed in check_result failed 
Test datm_control_cfsr 089 failed in run_test failed 
Test fv3_rrfs_v1beta_debug 085 failed in check_result failed 
Test fv3_rrfs_v1beta_debug 085 failed in run_test failed 
Test regional_control_debug 082 failed in check_result failed 
Test regional_control_debug 082 failed in run_test failed 
Test fv3_gsd_debug 083 failed in check_result failed 
Test fv3_gsd_debug 083 failed in run_test failed 
Test fv3_rrfs_v1alpha_debug 086 failed in check_result failed 
Test fv3_rrfs_v1alpha_debug 086 failed in run_test failed 
Test datm_cdeps_control_cfsr 097 failed in check_result failed 
Test datm_cdeps_control_cfsr 097 failed in run_test failed 
Test cpld_controlfrac_c384 014 failed in run_test failed 
Test cpld_control_c384 012 failed in check_result failed 
Test cpld_control_c384 012 failed in run_test failed 
Test datm_debug_cfsr 096 failed in check_result failed 
Test datm_debug_cfsr 096 failed in run_test failed 
Test datm_cdeps_bulk_gefs 101 failed in check_result failed 
Test datm_cdeps_bulk_gefs 101 failed in run_test failed 
Test datm_cdeps_control_gefs 099 failed in check_result failed 
Test datm_cdeps_control_gefs 099 failed in run_test failed 
Test datm_cdeps_bulk_cfsr 100 failed in check_result failed 
Test datm_cdeps_bulk_cfsr 100 failed in run_test failed 
Test datm_cdeps_multiple_files_cfsr 103 failed in check_result failed 
Test datm_cdeps_multiple_files_cfsr 103 failed in run_test failed 
Test cpld_bmarkfrac 018 failed in check_result failed 
Test cpld_bmarkfrac 018 failed in run_test failed 
Test datm_cdeps_debug_cfsr 104 failed in check_result failed 
Test datm_cdeps_debug_cfsr 104 failed in run_test failed 
Test cpld_bmarkfrac_v16 020 failed in check_result failed 
Test cpld_bmarkfrac_v16 020 failed in run_test failed 
Test cpld_bmarkfrac_wave_v16_noahmp 026 failed in check_result failed 
Test cpld_bmarkfrac_wave_v16_noahmp 026 failed in run_test failed 
Test cpld_bmarkfrac_wave_v16 025 failed in check_result failed 
Test cpld_bmarkfrac_wave_v16 025 failed in run_test failed 
Test fv3_gsd_diag3d_debug 084 failed in check_result failed 
Test fv3_gsd_diag3d_debug 084 failed in run_test failed 
Test control_atmwav 105 failed in check_result failed 
Test control_atmwav 105 failed in run_test failed 
Test cpld_bmark_wave 023 failed in check_result failed 
Test cpld_bmark_wave 023 failed in run_test failed 
Test datm_mx025_gefs 095 failed in check_result failed 
Test datm_mx025_gefs 095 failed in run_test failed 
Test datm_cdeps_mx025_gefs 102 failed in check_result failed 
Test datm_cdeps_mx025_gefs 102 failed in run_test failed 
Test datm_mx025_cfsr 094 failed in check_result failed 
Test datm_mx025_cfsr 094 failed in run_test failed 
Test cpld_bmarkfrac_wave 024 failed in check_result failed 
Test cpld_bmarkfrac_wave 024 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Comment by DeniseWorthen** [comment]
The Orion failure was caused by me not moving the baselines into an INTEL subdirectory.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Machine: orion
Compiler: intel
Job: RT
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/659317000/20210604074510/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_454393
Test cpld_controlfrac 003 failed in check_result failed 
Test cpld_controlfrac 003 failed in run_test failed 
Test cpld_control_c384 012 failed in run_test failed 
Test cpld_controlfrac_c384 014 failed in run_test failed 
Please make changes and add the following label back:
orion-intel-RT

**Pull request merged**
