### PR TITLE
Pbl tapering

### LINKED ISSUE #1898: Run cellular automata on a single tile, ensure consistent decomposition of CA domain with atm domain.
## Description
Currently the CA only works if ntiles=6. 
In addition, the CA domain decomposition is not guaranteed to be an "ncells" factor of the atmosphere domain decomposition. 

## Solution
Add possibility to run with ntiles=1, in cyclic domain with no contact surfaces. 
Ensure consistency in the decomposition between atm and CA domains, by introducing xextent and yextent in the mpp_define_mosaic.

### LINKED ISSUE #1908: Update stochastic physics to create a EP5 tag

### PR DESCRIPTION
**Pull request by pjpegion**
## PR Author Checklist:

- [X] I have linked PR's from all sub-components involved in section below. 
- [X] I am confirming reviews are completed in ALL sub-component PR's.
- [X] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: 
- [ ] I have added the list of all failed regression tests to "Anticipated changes" section.
- [X] I have filled out all sections of the template.

## Description
This PR adds additional tapering of the SPPT perturbations in the lower levels of the atmospheric model

From the included #1904 which closes #1898:
Add possibility to run the CA on a single tile by adding a cubed-sphere, single face tile with no contact surfaces in the CA domain specification.
Ensure decomposition of domain is proportional between the atmosphere domain and the higher resolution CA domain.

### Associated UFSWM Issue to close
Closes: #1908

### Subcomponent Pull Requests
- Depends on NOAA-PSL/stochastic_physics/pull/68

### Blocking Dependencies
None

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [x] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Comment by pjpegion** [comment]
@jkbk2004  This PR is for a few lines of code in the stochastic physics repo and is a very minor change.  I ran the full suite of regression tests on hera, and they all pass.  Can this get added to an existing regression test in the queue since EMC needs this for the next ensemble protoype?

**Comment by JongilHan66** [comment]
> @jkbk2004 This PR is for a few lines of code in the stochastic physics repo and is a very minor change. I ran the full suite of regression tests on hera, and they all pass. Can this get added to an existing regression test in the queue since EMC needs this for the next ensemble protoype?

I have no idea on the next ensemble prototype. Could you contact Bing Fu who is now a GEFS leader?

**Comment by bingfu-NOAA** [comment]
@JongilHan66 Hi Jongil, we will start running EP5 experiment on Oct 1. The EP5 tag will be created based on the model including this PR, please help to merge it at the earliest convenience.

**Comment by pjpegion** [comment]
@JongilHan66 I meant to tag Jong Kim, not you.

**Comment by bingfu-NOAA** [comment]
Then I think the comments should go to Jong Kim @jkbk2004 
we will start running EP5 experiment on Oct 1. The EP5 tag will be created based on the model including this PR, please help to merge it at the earliest convenience.

**Comment by pjpegion** [comment]
PR #1904 has been merged with this PR.

**Comment by jkbk2004** [comment]
@pjpegion Can you go ahead to sync up? No baseline change, so we can let tests move on.

**Comment by pjpegion** [comment]
done

**Comment by FernandoAndrade-NOAA** [comment]
It looks like the sub component PR dependency was already merged into its authoritative branch. @pjpegion could you revert .gtimodules and update the hash for stochastic physics?

**Comment by lisa-bengtsson** [comment]
@pjpegion can you update the description of this PR since it merged in https://github.com/ufs-community/ufs-weather-model/pull/1904 

It closes issue https://github.com/ufs-community/ufs-weather-model/issues/1898 and includes an update to be able to run the cellular automata on a single face tile. It also includes an update to ensure that consistent decomposition between the FV3 domain and the higher resolution CA domain.

**Comment by FernandoAndrade-NOAA** [comment]
Looks like there are failures on the jenkins ci side due to allocation being exceeded again, running manually on hera.

**Comment by zach1221** [comment]
> Looks like there are failures on the jenkins ci side due to allocation being exceeded again, running manually on hera.

I'll work with platform today to get the issue fixed.

**Comment by pjpegion** [comment]
I was traveling yesterday. Do you still need me to update .gitmodules?

**Comment by FernandoAndrade-NOAA** [comment]
> I was traveling yesterday. Do you still need me to update .gitmodules?

Yes please go ahead and revert .gitmodules and update the hash for stochastic as the sub PR is already merged in

**Comment by pjpegion** [comment]
ok, done

**Comment by BrianCurtis-NOAA** [comment]
WCOSS has 2 timeouts, but there is a known machine issue with slowness. I've verified with more time the tests pass, but will not be making any changes to the UFS code at this time.

**Comment by FernandoAndrade-NOAA** [comment]
Ok this should be ready for merging, continuing with final reviews

**Review by sadeghitabas — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
