### PR TITLE
Update CICE, use -init=snan,arrays for Intel debug

### LINKED ISSUE #44: Update CICE to Consortium Main
The following PRs have been merged to Consortium Main. NOAA-EMC needs to be updated accordingly.

-  #633. This appears to implement a flux scheme similar to what UMW has implemented for the aoflux calculation using CDEPS with ``flux_scheme=-1``. 
- #639. **This PR changes baselines**
- #647 
- #658. This PR updates icepack to allow compilation with Intel and ``-init=snan,arrays``

### LINKED ISSUE #580: Adding "-init=snan,arrays" to Intel DEBUG flags in top-level CMakeLists.txt leads to model crashes in FV3 dycore
## Description

Before the recent CCPP cleanup PR (https://github.com/ufs-community/ufs-weather-model/pull/548), additional flags were used for CCPP when compiling with Intel in DEBUG mode: `-init=snan,arrays`.

These flags are useful to detect uninitialized data and we should add them to the entire ufs-weather-model code (in `cmake/Intel.cmake`).

However, doing so leads to crashes in the FV3 dycore, this is for the example of the regression test `fv3_gfs_v16_debug`, but it is the same for all debug tests with Intel:
```
+ srun ./fv3.exe
 in fcst comp init, ntasks=         144
 num_atmos_calls=          18 time_init=        2016          10           3
           0           0           0 time_atmos=        2016          10
           3           0           0           0 time_end=        2016
          10           3           6           0           0 dt_atmos=
        1200 Run_length=       21600
 INPUT source not found  F  set source=No Source Attribute
forrtl: error (182): floating invalid - possible uninitialized real/complex variable.
Image              PC                Routine            Line        Source
fv3.exe            0000000008B6392E  Unknown               Unknown  Unknown
fv3.exe            0000000008FD0760  Unknown               Unknown  Unknown
fv3.exe            000000000609E228  Unknown               Unknown  Unknown
fv3.exe            0000000005B56BF9  external_ic_mod_m        3300  external_ic.F90
fv3.exe            0000000008AD45F3  Unknown               Unknown  Unknown
fv3.exe            0000000008A81ADF  Unknown               Unknown  Unknown
fv3.exe            0000000008A4F335  Unknown               Unknown  Unknown
fv3.exe            0000000005B42107  external_ic_mod_m        3232  external_ic.F90
fv3.exe            0000000005A38200  external_ic_mod_m         734  external_ic.F90
fv3.exe            0000000005A216AD  external_ic_mod_m         290  external_ic.F90
fv3.exe            00000000053F87EC  fv_restart_mod_mp         321  fv_restart.F90
fv3.exe            000000000395FB47  atmosphere_mod_mp         432  atmosphere.F90
fv3.exe            00000000033AD771  atmos_model_mod_m         421  atmos_model.F90
fv3.exe            0000000002D98F95  module_fcst_grid_         383  module_fcst_grid_comp.F90
fv3.exe            0000000001ACAEF3  _ZN5ESMCI6FTable1        2036  ESMCI_FTable.C
fv3.exe            0000000001ACE89A  ESMCI_FTableCallE         765  ESMCI_FTable.C
fv3.exe            00000000021A8E19  _ZN5ESMCI2VM5ente        1211  ESMCI_VM.C
fv3.exe            0000000001ACC377  c_esmc_ftablecall         922  ESMCI_FTable.C
```
Note that there is no stack trace from the FMS library, because it is now an external library and not compiled with debug flags.

As a temporary workaround, until the dycore is fixed, I am going to add the missing flags back for CCPP only in PR https://github.com/NOAA-EMC/fv3atm/pull/300.

### To Reproduce:
Add the following line after line 10 in `cmake/Intel.cmake`:
```
set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -init=snan,arrays")
```
Run any of the DEBUG regression tests with Intel.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Updates CICE for the latest Consortium main. See CICE Issue [#44](https://github.com/NOAA-EMC/CICE/issues/44) for a list of updates included. In particular, this PR will update the icepack submodule to include a fix which allows ``-init=snan,arrays`` to be used in debug mode.

The following change is required in ice_in:

```
index a91ed08d..77176455 100644
--- a/tests/parm/ice_in_template
+++ b/tests/parm/ice_in_template
@@ -105,7 +105,8 @@
     mu_rdg          = 3
     Cf              = 17.
     Ktens           = 0.
-    e_ratio         = 2.
+    e_yieldcurve    = 2.
+    e_plasticpot    = 2.
     coriolis        = 'latitude'
     kridge          = 1
     ktransport      = 1
```
### Issue(s) addressed

- fixes #580 
- fixes https://github.com/NOAA-EMC/CICE/issues/44

## Testing

On hera.intel at eb25340, all ``cpld`` and all ``datm_cdeps`` tests run to completion but fail comparison. This is due to a baseline-changing PR (round-off level) being brought in with the update to CICE-Consortium/main. 

All other tests pass. All debug tests run to completion.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/CICE/pull/43

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/791172115/20211214141510/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211213/GNU
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-gnu-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/791172115/20211214141727/ufs-weather-model
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20211213/INTEL
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back:
hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/791172115/20211214104510/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_3814
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 066 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson_debug 066 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by DeniseWorthen** [comment]
The fv3_esg_HAFS_v0_hwrf_thompson_debug failure on Cheyenne.intel was a MPT:shepherd error. I tried copying the run directory and got the same failure. I'll try w/ a clean checkout and build.

**Comment by DeniseWorthen** [comment]
fv3_esg_HAFS_v0_hwrf_thompson_debug still fails with MPT:shepherd error on cheyenne.intel. My experience is this is usually a memory issue, so I tried setting more resources and the job did complete. 

The only change that could be responsible for the failure is switching to -init=snan,arrays. I don't know anything about this test, or why the compile change would cause the job to fail.

**Comment by DeniseWorthen** [comment]
We're only missing Jet, which is on maintenance today. I'll start those when Jet returns tonight. We should be ready first thing for commit tomorrow morning.

**Review by climbfuji — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
