### PR TITLE
Update inline post for RRFS and HAFS

### LINKED ISSUE #1359: Update inline post for two requests from RRFS and HAFS
## Description
There are two requests from RRFS and HAFS developments:

- Output lat/lon of four corner point for RRFS rotated lat/lon grid.
- Read instant model top longwave from model so it can be output in HAFS products.

## Solution
Update in-line post read interface and upp submodule revision with the latest UPP commits at UPP github.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.

## Description

This PR will update FV3 component for inline post changes:

- Output lat/lon of four corner points in text file for RRFS rotated lat-lon gird

- Read instant model top longwave from model

- Update upp submodule revision with the recent commits from UPP repository.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #1359 

## Testing

How were these changes tested? Yes. What compilers / HPCs was it tested with? Intel on WCOSS2.  Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Yes.  Have regression tests and unit tests (utests) been run?  On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [ ] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/567

### CODE REVIEW

**Comment by jkbk2004** [comment]
@WenMeng-NOAA We can start working on this PR. Can you sync up to develop branch? Since change is on write grid component, do we expect baseline will change?

**Comment by DeniseWorthen** [comment]
@WenMeng-NOAA I see that you checked the box that baselines will change for one or more test. But I don't see that you've added information about the testing. Have you tested this PR yet on any platform to verify which tests change and that all tests run to completion?

**Comment by WenMeng-NOAA** [comment]
@DeniseWorthen That's my early testing. After the PR #1305 committed, there should be no baseline changed in the UFS RT test from my testing on WCOSS2 last week. I will revert that check box. Thanks!

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA We can start working on this PR. Can you sync up to develop branch? Since change is on write grid component, do we expect baseline will change?

Will do it. There should be no baseline changed in my PR now.

**Comment by WenMeng-NOAA** [comment]
@jkbk2004 My UFS branch and FV3 branch are up to date now. Please let me know if any actions are needed from my end. Thanks!

**Comment by jkbk2004** [comment]
Thanks for the information! I will go ahead to start testing on hera/intel/gnu first.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1012916008/20220816191508/ufs-weather-model
[RT] Error: Test datm_cdeps_mx025_cfsr 141 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1012916008/20220816221515/ufs-weather-model
[RT] Error: Test control_ras 071 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_wav 115 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
@WenMeng-NOAA merged the fv PR. Can you revert gitmodule branch pointer and update fv3 submodule pointer?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA merged the fv PR. Can you revert gitmodule branch pointer and update fv3 submodule pointer?

@jkbk2004 Done.

**Review by DeniseWorthen — APPROVED** [review]
Hashes are correct.

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
