### PR TITLE
CCPP: Update consistency checks and effective radii calculation for Thompson MP

### LINKED ISSUE #1006: Simplify effective radii computation for Thompson MP in GFS_rrtmg_pre.F90
## Description

The organically grown code in `GFS_rrtmg_pre.F90` creates several unnecessary local arrays for computing the effective radii for Thompson MP in a very confusing way. This should be simplified to improve the readability of the code and reduce the computational/storage overhead.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR contains changes in ccpp-physics (Update consistency checks and effective radii calculation for Thompson MP) and adds two new regression tests for both Intel and GNU that use the new prognostic cloud scheme `progcld_thompson` with GFS v16 and with RAP. The new cloud scheme is activated by setting `icloud == 3` in `input.nml`.

Existing regression test baselines do not change, but the two new tests need their own results.

Also included:
- Remove old and unused test `fv3_multigases_debug`
- Fix typo in GitHub pull request template

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/1006
https://github.com/ufs-community/ufs-weather-model/issues/1007

### Preliminary regression testing 2022/01/09

On Hera with Intel and GNU, all existing regression tests verify against the baseline results. The two new tests `control_thompson_progcld_thompson_debug` and `rap_progcld_thompson_debug` run to completion, but do not have a baseline to compare against.

[rt_hera_gnu_verify_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/7836531/rt_hera_gnu_verify_against_existing_fail_test.log)
[rt_hera_gnu_verify_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/7836532/rt_hera_gnu_verify_against_existing.log)
[rt_hera_intel_verify_against_existing_fail_test.log](https://github.com/ufs-community/ufs-weather-model/files/7836534/rt_hera_intel_verify_against_existing_fail_test.log)
[rt_hera_intel_verify_against_existing.log](https://github.com/ufs-community/ufs-weather-model/files/7836535/rt_hera_intel_verify_against_existing.log)

### Final regression testing

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- (n/a) opnReqTest for newly added/changed feature
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/1000/commits/67ad4530a3ee5252beb505c89b14d5382de36d2c

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/786
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/462

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by binli2337** [comment]
@climbfuji Your PR is next. Thanks.

**Comment by climbfuji** [comment]
Ok, thanks! I am on it.

**Comment by climbfuji** [comment]
Running auto-rt against existing baselines on hera with Intel and GNU first, all tests should pass except the two newly added tests. Once that is done, I will update BL_DATE and generate new baselines.

Also running CI now.

**Comment by junwang-noaa** [comment]
@climbfuji do you want to add the two tests to the current baseline and run RT against it instead of creating new baseline?

**Comment by climbfuji** [comment]
> @climbfuji do you want to add the two tests to the current baseline and run RT against it instead of creating new baseline?

I will have time to do this tonight, yes.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/815494368/20220119203017/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_3555
Test rrfs_conus13km_hrrr_warm 050 failed in check_result failed 
Test rrfs_conus13km_hrrr_warm 050 failed in run_test failed 
Test rrfs_conus13km_radar_tten_warm 051 failed in check_result failed 
Test rrfs_conus13km_radar_tten_warm 051 failed in run_test failed 
Test control_thompson_progcld_thompson_debug 076 failed in check_result failed 
Test control_thompson_progcld_thompson_debug 076 failed in run_test failed 
Test rap_progcld_thompson_debug 089 failed in check_result failed 
Test rap_progcld_thompson_debug 089 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/815494368/20220119204517/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_22814
Test rrfs_conus13km_hrrr_warm 018 failed in check_result failed 
Test rrfs_conus13km_hrrr_warm 018 failed in run_test failed 
Test rrfs_conus13km_radar_tten_warm 019 failed in check_result failed 
Test rrfs_conus13km_radar_tten_warm 019 failed in run_test failed 
Test rap_progcld_thompson_debug 026 failed in check_result failed 
Test rap_progcld_thompson_debug 026 failed in run_test failed 
Test control_thompson_progcld_thompson_debug 031 failed in check_result failed 
Test control_thompson_progcld_thompson_debug 031 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-RT

**Comment by climbfuji** [comment]
@junwang-noaa (@SamuelTrahanNOAA FYI) It's necessary to produce new baselines. The reason for the unexpected failure of the two tests `rrfs_conus13km_hrrr_warm` and `rrfs_conus13km_radar_tten_warm` is that the `diag_table` used by these two tests contain the cloud effective radii `cieffr`, `cleffr`, `cseffr`. The output of these radii was previously commented out in `FV3/io/FV3GFS_io.F90`, but this PR enables them.

Before the two `rrfs_conus13km` tests were added, none of the diag tables had those cloud effective radii, hence no change to the results. But those two tests do. Since they run to completion and since the variables contain valid and good data (I checked), it's not a problem to have these variables in the output.

I'll update `BL_DATE` to 20220120 and add the labels to create new baselines. I'll do the wcoss-es as well tonight, unless my VPN doesn't work (I'll let you know).

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/815494368/20220119233017/ufs-weather-model
Please make changes and add the following label back:
gaea-intel-BL

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: gaea
> Compiler: intel
> Job: BL
> Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/815494368/20220119233017/ufs-weather-model
> Please make changes and add the following label back:
> gaea-intel-BL

Is there a problem on gaea? Filesystem? That directory doesn't even exist:
```
[23:40:41]emc.nemspara@gaea11:/lustre/f2/pdata/ncep/emc.nemspara/autort/pr/815494368/20220119233017
-->ls -lart
total 65
drwxr-sr-x 3 emc.nemspara ncep 33280 Jan 19 23:30 ..
drwxr-sr-x 2 emc.nemspara ncep 33280 Jan 19 23:30 .
```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/815494368/20220119234512/ufs-weather-model
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/815494368/20220120001513/ufs-weather-model
Please make changes and add the following label back:
gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
Repo location: /work/noaa/nems/emc.nemspara/autort/pr/815494368/20220119173009/ufs-weather-model
Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_439630
Please make changes and add the following label back:
orion-intel-BL

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: orion
> Compiler: intel
> Job: BL
> Repo location: /work/noaa/nems/emc.nemspara/autort/pr/815494368/20220119173009/ufs-weather-model
> Please manually delete: /work/noaa/stmp/bcurtis/stmp/bcurtis/FV3_RT/rt_439630
> Please make changes and add the following label back:
> orion-intel-BL

Weird: baseline creation was successful:
```

  0: The total amount of wall time                        = 668.970810
  0: The maximum resident set size (KB)                   = 1207860

Test 091 control_c384gdas_wav PASS


REGRESSION TEST WAS SUCCESSFUL
Wed Jan 19 18:25:33 CST 2022
Elapsed time: 00h:54m:00s. Have a nice day!
```

Will try to manually verify against this baseline ...

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/815494368/20220119233009/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_74647
Baseline creation and move successful
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/815494368/20220120020916/ufs-weather-model
Please make changes and add the following label back:
jet-intel-BL

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Submodule pointer for fv3atm is correct (12a5441), ready to merge.

**Pull request merged**
