### PR TITLE
Update module_write_netcdf to avoid hangs in RRFS runs

### LINKED ISSUE #2174: Write component hangs in nf90_enddef with planned operational RRFS
## Description

The head of develop hangs while writing NetCDF output files in the write component when running the version of RRFS planned for operations. This happens regardless of the compression settings or lack thereof. The behavior is like so:

1. Model runs normally.
2. Data is sent to a write component.
3. The write component writes metadata to the file.
4. The write component gets stuck in an nf90_enddef call. Some MPI ranks leave the call prematurely and the rest are stuck in an MPI_Allreduce within nf90_enddef. This is on line 483 of FV3/io/module_write_netcdf.F90 (see stack trace).

Commenting out some of the variables in the diag_table will prevent this problem. There isn't one specific set of variables that seem to cause it. Turning off the lake model or smoke model prevents the hang, but one should note that disables writing of many variables.

Using one thread (no OpenMP) appears to reduce the frequency of the hangs. Increasing the write component ranks by enormous amounts appears to increase the frequency of hangs. This conclusion is uncertain since we haven't run enough tests to get a statistically representative sample set.

I have been unable to reproduce the problem when the model is compiled in debug mode.

This problem has been confirmed on Jet, Hera, and WCOSS2, but hasn't been tested on other machines.

From lots of forum searching, this problem has been identified in the distant past when the model sends different metadata at different ranks. For example, 13 variables on one rank, but 14 on the others. Or one rank sends three attributes and the others sent five. I haven't investigated that possibility, but I don't see how it is possible in the code.

#### 1. Executables were compiled like so:

```bash
target=jet # or wcoss2
opts="-DAPP=HAFSW -DCCPP_SUITES=FV3_HRRR_gf,FV3_global_nest_v1 -D32BIT=ON -DCCPP_32BIT=ON -DFASTER=ON"
./compile.sh "$target" "$opts" 32bit intel YES NO
```

#### 2. Copy one of these test directories:

Jet: `/lfs4/BMC/nrtrr/Samuel.Trahan/smoke/sudheer-case`
Hera: `/scratch2/BMC/wrfruc/Samuel.Trahan/rrfs/sudheer-case`
Cactus: `/lfs/h2/oar/esrl/noscrub/samuel.trahan/ming-io-hang`

#### 3. Edit the job script

Each machine's test directory contains a `job.sh` script. Edit it as needed to point to your code.

#### 4. Run the job script.

Send the script to `sbatch` on Jet or `qsub` on Cactus. Do *not* run it on a login node.

## Additional context
This problem exists in the version of RRFS planned to go operational.

## Output

This stack trace comes from gdb analyzing a running write component MPI rank while it is hanging waiting for an MPI_Allreduce. The arguments in the stack trace may be meaningless because gdb has trouble interpreting Intel-compiled code. However, the line numbers and function calls should be correct. Some may have been optimized out.

<details> <summary>stack trace of stuck MPI process</summary>

```
#0  0x00002b6eab22803a in MPIDI_SHMGR_release_generic (opcode=2893772520, mpir_comm=0x7ffca32a54c8, root=27, localbuf=0x1ec, count=-1405432336, datatype=1329139008, errflag=0x7ffca32b2548, knomial_factor=4, 
    algo_type=MPIDI_SHMGR_ALGO_FLAT) at ../../src/mpid/ch4/src/intel/ch4_shm_coll_templates.h:206
#1  0x00002b6eab21bf85 in MPIDI_SHMGR_Release_bcast (comm=0x2b6eac7b76e8 <PVAR_TIMER_idle+8>, buf=0x7ffca32a54c8, count=27, datatype=492, errflag=0x2b6eac3acdf0 <MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX>, algo_type=1329139008, radix=0)
    at ../../src/mpid/ch4/src/intel/ch4_shm_coll.c:2619
#2  0x00002b6eab118690 in MPIDI_Allreduce_intra_composition_zeta (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, op=<optimized out>, comm_ptr=<optimized out>, errflag=<optimized out>, 
    ch4_algo_parameters_container=<optimized out>) at ../../src/mpid/ch4/src/intel/ch4_coll_impl.h:1078
#3  MPID_Allreduce_invoke (sendbuf=0xffffffffffffffff, recvbuf=0x7ffca32b2598, count=<optimized out>, datatype=<optimized out>, op=<optimized out>, comm=<optimized out>, errflag=<optimized out>, 
    ch4_algo_parameters_container=<optimized out>) at ../../src/mpid/ch4/src/intel/ch4_coll_select_utils.c:1831
#4  MPIDI_coll_invoke (coll_sig=0x2b6eac7b76e8 <PVAR_TIMER_idle+8>, container=0x7ffca32a54c8, req=0x1b) at ../../src/mpid/ch4/src/intel/ch4_coll_select_utils.c:3359
#5  0x00002b6eab0f47ec in MPIDI_coll_select (coll_sig=0x2b6eac7b76e8 <PVAR_TIMER_idle+8>, req=0x7ffca32a54c8) at ../../src/mpid/ch4/src/intel/ch4_coll_globals_default.c:130
#6  0x00002b6eab237387 in MPID_Allreduce (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, op=<optimized out>, comm=<optimized out>, errflag=<optimized out>)
    at ../../src/mpid/ch4/src/intel/ch4_coll.h:77
#7  MPIR_Allreduce (sendbuf=0x2b6eac7b76e8 <PVAR_TIMER_idle+8>, recvbuf=0x7ffca32a54c8, count=27, datatype=492, op=-1405432336, comm_ptr=0x2b6f4f390d40, errflag=0x7ffca32b2548) at ../../src/mpi/coll/intel/coll_impl.c:265
#8  0x00002b6eab0926e1 in PMPI_Allreduce (sendbuf=0x2b6eac7b76e8 <PVAR_TIMER_idle+8>, recvbuf=0x7ffca32a54c8, count=27, datatype=492, op=-1405432336, comm=1329139008) at ../../src/mpi/coll/allreduce/allreduce.c:417
#9  0x00002b6eabbade7e in PMPI_File_set_size (fh=0x2b6eac7b76e8 <PVAR_TIMER_idle+8>, size=140723045946568) at ../../../../../src/mpi/romio/mpi-io/set_size.c:69
#10 0x00002b6eafcc20e5 in H5FD__mpio_truncate () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#11 0x00002b6eafca8445 in H5FD_truncate () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#12 0x00002b6eafc922ad in H5F__flush () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#13 0x00002b6eafc964ee in H5F_flush_mounts () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#14 0x00002b6eafefb4ad in H5VL__native_file_specific () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#15 0x00002b6eafee6571 in H5VL_file_specific () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#16 0x00002b6eafc7ec02 in H5Fflush () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.14.0-7pcehjm/lib/libhdf5.so.310
#17 0x00002b6ea848fe82 in nc4_enddef_netcdf4_file () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/netcdf-c-4.9.2-lg6bcpf/lib/libnetcdf.so.19
#18 0x00002b6ea848fe09 in NC4__enddef () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/netcdf-c-4.9.2-lg6bcpf/lib/libnetcdf.so.19
#19 0x00002b6ea8407d50 in nc_enddef () from /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/netcdf-c-4.9.2-lg6bcpf/lib/libnetcdf.so.19
#20 0x00002b6ea7f841fb in netcdf::nf90_enddef (ncid=-532069714, h_minfree=-532069809, v_align=<error reading variable: Cannot access memory at address 0x1b>, v_minfree=<error reading variable: Cannot access memory at address 0x1ec>, 
    r_align=1) at ./netcdf_file.F90:82
#21 0x0000000002bcb8d0 in get_dimlen_if_exists (ncid=<optimized out>, dim_name=<optimized out>, grid=..., dim_len=<optimized out>, rc=<optimized out>, .tmp.DIM_NAME.len_V$5138=<optimized out>)
    at /lfs4/BMC/nrtrr/Samuel.Trahan/smoke/community-20240228/FV3/io/module_write_netcdf.F90:483
#22 module_write_netcdf::write_netcdf (wrtfb=..., 
    filename='\000' <repeats 24 times>, '\061\000\000\000\000\000\000\000int\000\270\177\000\000\330\027\272[\270\177\000\000\000\000\000\000\000\000\000\000!\001\000\000\000\000\000\000\060\000\000\000\000\000\000\000\061', '\000' <repe
ats 23 times>, '\340^]\b', '\000' <repeats 20 times>, '\241\000\000\000\000\000\000\000\001\000\000\000\t\000\000\000\300\'+\243\374\177', '\000' <repeats 26 times>, '\001', '\000' <repeats 47 times>..., 
    use_parallel_netcdf=<error reading variable: Cannot access memory at address 0x1b>, mpi_comm=<error reading variable: Cannot access memory at address 0x1ec>, mype=1, grid_id=64, rc=0, .tmp.FILENAME.len_V$3649=10)
    at /lfs4/BMC/nrtrr/Samuel.Trahan/smoke/community-20240228/FV3/io/module_write_netcdf.F90:208
#23 0x00000000027782f6 in rtll (tlmd=<optimized out>, tphd=<optimized out>, almd=<optimized out>, aphd=<optimized out>, tlm0d=<optimized out>, tph0d=<optimized out>)
    at /lfs4/BMC/nrtrr/Samuel.Trahan/smoke/community-20240228/FV3/io/module_wrt_grid_comp.F90:2422
#24 module_wrt_grid_comp::wrt_run (wrt_comp=..., imp_state_write=..., exp_state_write=<error reading variable: Cannot access memory at address 0x1b>, clock=<error reading variable: Cannot access memory at address 0x1ec>, rc=1)
    at /lfs4/BMC/nrtrr/Samuel.Trahan/smoke/community-20240228/FV3/io/module_wrt_grid_comp.F90:2052
#25 0x0000000000acc092 in ESMCI::FTable::callVFuncPtr(char const*, ESMCI::VM*, int*) ()
    at /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-6zav654sh2mjenj4s3h4w433vhg5oqzy/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:2167
```
</details>

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
### Commit Message:

```
* UFSWM - Update module_write_netcdf to avoid hangs in RRFS runs
  * FV3 - Update module_write_netcdf to avoid hangs in RRFS runs
```

### Priority:

* Normal

### UFSWM:

* Closes #2174

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/803

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
I've asked the people who run RRFS parallels to try this fix so we can confirm it works for a large number of cases.

**Comment by MatthewPyle-NOAA** [comment]
@SamuelTrahanNOAA Is this being tested in any RRFS parallels yet?  Thanks!

**Comment by SamuelTrahanNOAA** [comment]
Ming Hu is testing it in parallels. One cycle failed so far, but it looks like an unrelated failure. (Yet another problem to debug.) That cycle was scrubbed, so we can't reproduce the new failure yet.

I'm unable to make a regression test case for this configuration. I can *almost* do it with the conus13km cases, but the lack of one input field for the GF scheme prevents me from having all of the fields.

**Comment by hu5970** [comment]
We have a few days parallel test with this PR and it does fixed the hang problem. Please move forward with this PR.
Could you also make a PR to production/RRFS.v1 branch?

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hera [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14791510/RegressionTests_hera.log)

**Comment by MatthewPyle-NOAA** [comment]
@DusanJovic-NOAA Will echo what @hu5970 said that we'll need this in the production/RRFS.v1 release branch as well.  Is needed more critically there as that is what we're using for the RRFS.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Will echo what @hu5970 said that we'll need this in the production/RRFS.v1 release branch as well. Is needed more critically there as that is what we're using for the RRFS.

@MatthewPyle-NOAA @hu5970 I'll add the changes to the production/RRFS.v1 release branch and open a PR

**Comment by MatthewPyle-NOAA** [comment]
Thanks @DusanJovic-NOAA!

**Comment by DusanJovic-NOAA** [comment]
> Thanks @DusanJovic-NOAA!

@MatthewPyle-NOAA @hu5970 Please check the RRFS.v1 branch PRs and run few RRFS parallel runs to confirm that everything works as expected:

https://github.com/ufs-community/ufs-weather-model/pull/2212

https://github.com/NOAA-EMC/fv3atm/pull/810

**Comment by zach1221** [comment]
Hi, @DusanJovic-NOAA . Can you sync up your branch, please? As we're planning to test against this PR next.

**Comment by DusanJovic-NOAA** [comment]
> Hi, @DusanJovic-NOAA . Can you sync up your branch, please? As we're planning to test against this PR next.

Done.

**Comment by BrianCurtis-NOAA** [comment]
Acorn issues have been resolved, hopefully. I am running current develop branch against baselines and will start testing with Acorn on the next PR. It can be skipped for this PR.

**Comment by zach1221** [comment]
@DusanJovic-NOAA fv3atm pr is merged. Please updated hash/gitmodule url.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
