### PR TITLE
Fix dumpfields=true option by using ESMF_FieldBundleWrite

### LINKED ISSUE #838: Incorrect check for out-of-bounds in State_SetScalar
## Description

Bug encountered and investigated by @zhanglikate with debugging help from @DusanJovic-NOAA and myself. Credit goes mostly to zhanglikate who did a fantastic amount of debugging and testing in an impressively short time.

There is an out-of-bounds access (element 0) if one forgets to set these variables in ufs.configure:

- `flds_scalar_index_nx`
- `flds_scalar_index_ny`
- `flds_scalar_index_ntile`

This bug is in `State_SetScalar` here in `cpl/module_cplscalars.F90`:

```f90
       if (scalar_id < 0 .or. scalar_id > flds_scalar_num) then ! <--- bug is here, not detecting scalar_id=0
          call ESMF_LogWrite(trim(subname)//": ERROR in scalar_id", ESMF_LOGMSG_INFO)
          rc = ESMF_FAILURE
          return
       endif
       farrayptr(scalar_id,1) = scalar_value  ! <--- crash is here with scalar_id=0
```

When one of the three `flds_scalar_index_` variables is missing, scalar_id is 0. The "if" block doesn't catch it because it looks for `scalar_id < 0` instead of `scalar_id <= 0`

### To Reproduce:
*What compilers/machines are you seeing this with?*
Irrelevant. The bug is clear in the code.

*Give explicit steps to reproduce the behavior.*
1. Forget to set flds_scalar_index_ntile
2. Compile in debug mode
3. Run a coupled case
4. Witness the crash

## Additional context

The bug started with this commit:

- https://github.com/NOAA-EMC/fv3atm/commit/1cac9d31d139b0069deb31034e2257a2a945a573#diff-6de27573584241240a2b726af0011e6d1c01e32b522b945d237332cdcd6d2dbf

## Output

The stack trace:

```
  0: forrtl: severe (408): fort: (3): Subscript #1 of the array FARRAYPTR has value 0 which is less than the lower bound of 1
   0:
   0: Image              PC                Routine            Line        Source
   0: ufs_model.x        00000000154A2F7F  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000004277D04  module_cplscalars         124  module_cplscalars.F90
   0: ufs_model.x        000000000423F623  module_fcst_grid_         518  module_fcst_grid_comp.F90
   0: ufs_model.x        0000000000AA0B84  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA472F  Unknown               Unknown  Unknown
   0: ufs_model.x        000000000095097A  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000011EDB99  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA1FCA  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000009701B0  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000CA1351  Unknown               Unknown  Unknown
   0: ufs_model.x        000000000425983F  module_fcst_grid_        1266  module_fcst_grid_comp.F90
   0: ufs_model.x        0000000000AA0B84  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA472F  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000950B87  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000011EDB99  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA1FCA  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000009701B0  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000CA1351  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000004224D4C  fv3atm_cap_mod_mp         997  fv3_cap.F90
   0: ufs_model.x        00000000006B00D8  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000006B003A  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000006B06E3  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000004843AB  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000041F0296  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA0B84  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA472F  Unknown               Unknown  Unknown
   0: ufs_model.x        000000000095097A  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000011EDB99  Unknown               Unknown  Unknown
   0: ufs_model.x        0000000000AA1FCA  Unknown               Unknown  Unknown
   0: ufs_model.x        00000000009701B0  Unknown               Unknown  Unknown
```

### LINKED ISSUE #1765: dumpfields=true fails in module_fcst_grid_comp.F90 for coupled model
## Description

The nems.configure variable ``dumpfields=true`` should allow the coupling fields to be written from the component itself. This feature was previously working in the fv3_cap, but now fails with the following error:

```
20230522 132033.780 ERROR            PET000 ESMCI_IO.C:542 ESMCI::IO::write() Operation not yet supported  - tile count of 6 != 1 - not supported yet
20230522 132033.791 ERROR            PET000 ESMCI_IO.C:942 ESMCI::IO::close() Unable to close file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMCI_IO.C:482 ESMCI::IO::write() Operation not yet supported  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMCI_ArrayBundle.C:493 ESMCI::ArrayBundle::write() Unable to write to file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMCI_ArrayBundle_F.C:436 c_esmc_arraybundlewrite() Unable to write to file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMF_ArrayBundle.F90:3976 ESMF_ArrayBundleWrite() Unable to write to file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 module_fcst_grid_comp.F90:1638 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 module_fcst_grid_comp.F90:298 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 module_fcst_grid_comp.F90:865 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 fv3_cap.F90:396 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 ATM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:700 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2577 Unable to write to file  - Phase 'IPDvXp01' Initialize for modelComp 2: ATM did not return ESMF_SUCCESS
20230522 132033.791 ERROR            PET000 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:1286 Unable to write to file  - Passing error in return code
20230522 132033.792 ERROR            PET000 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:457 Unable to write to file  - Passing error in return code
20230522 132033.792 ERROR            PET000 UFS.F90:386 Unable to write to file  - Aborting UFS
```

CMEPS has the capability in the mediator history files to write the fields it receives but it is sometimes useful to confirm that the fields imported by CMEPS are identical to those exported by FV3. This is no longer possible. 

### To Reproduce:

Run any of the global coupled configurations using the RT system. Use the run directory and set ``DumpFields = true`` in the ATM configuration attributes in ``nems.configure``.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

This PR fixes `dumpfields=true` option in FV3 which can be used to write all coupling fields (from import and export states) by using updated version of ESMF's `ESMF_FieldBundleWrite` function instead of old `ESMFIO_Write`.

### Commit Message:

```
* UFSWM - Fix dumpfields=true option in FV3 by using ESMF_FieldBundleWrite
  * FV3 - Fix dumpfields=true option by using ESMF_FieldBundleWrite
```

### Priority:

* Normal

### UFSWM:

* Closes #1765
* Closes https://github.com/NOAA-EMC/fv3atm/issues/838

### Sub component Pull Requests:

* FV3: NOAA-EMC/fv3atm#856

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
"Pull Request Tests / Check if repos are up to date (pull_request)" failed with this error:

```
Run helper_id=$(cat ~/id_file)
cat: /home/runner/id_file: No such file or directory
Error: Process completed with exit code 1.
```

This check should be either fixed or disabled, This test error is misleading.

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on Hera:
[RegressionTests_hera.log](https://github.com/user-attachments/files/16128677/RegressionTests_hera.log)

**Comment by DusanJovic-NOAA** [comment]
Regression test passed on WCOSS2:
[RegressionTests_wcoss2.log](https://github.com/user-attachments/files/16132297/RegressionTests_wcoss2.log)

**Comment by zach1221** [comment]
@DusanJovic-NOAA we're ready to move to this PR. Can you please sync up your branch?

**Comment by FernandoAndrade-NOAA** [comment]
#2352 was merged in, please resync and resolve conflicts so we can get started with testing this PR, thank you.

**Comment by DusanJovic-NOAA** [comment]
> #2352 was merged in, please resync and resolve conflicts so we can get started with testing this PR, thank you.

Done.

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA FYI for testing

**Review by junwang-noaa — COMMENTED** [review]
Do you want to commit test_changes.list to confirm there is no change in the baseline?

**Comment by DusanJovic-NOAA** [comment]
> Do you want to commit test_changes.list to confirm there is no change in the baseline?

Done. 4124fe8

**Review by junwang-noaa — DISMISSED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
Ok, we should be all set to start the merge process, I'll let the FV3 sub PR know.

**Comment by FernandoAndrade-NOAA** [comment]
FV3 was merged in, @DusanJovic-NOAA please go ahead and sync/revert .gitmodules

**Review by zach1221 — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
