### PR TITLE
Enable GOCART in fully coupled configurations

### LINKED ISSUE #731: Enable UFS-Aerosols in P7
## Description

Coupling with UFS-Aerosols needs to be enabled in the atmosphere component when a fully coupled configuration is used for P7 evaluation runs.

See fv3atm issue [#361](https://github.com/NOAA-EMC/fv3atm/issues/361).

### PR DESCRIPTION
**Pull request by rmontuoro**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

This PR adds the GOCART component (UFS-Aerosols) to both the S2S and S2SW apps. The changes also include PR #725 .

No baseline changes are required except for `control_atm_aerosols`, which needs to be regenerated due to updates brought in by PR #725.

### Issue(s) addressed

- fixes #731 

## Testing

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
-  cheyenne.intel skipped. RT log file not created because of control_c384gdas_wav test resource requirement is too high, resulting in this job hanging in the Q
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI

## Dependencies

- waiting on https://github.com/NOAA-EMC/fv3atm/pull/362
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/357
- waiting on https://github.com/NCAR/ccpp-physics/pull/714
- waiting on #725

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@rmontuoro will s2s run with gocart by default with your change? It seems to me your change will compile the s2s with gocart, but people can turn off gocart if the namelist cplchem is not set, is that correct?

**Comment by rmontuoro** [comment]
@junwang-noaa - GOCART will be built into the executable for S2S and S2SW, but it only runs if it is included in the run sequence set in `nems.configure`. If GOCART is not used, `cplchem` should be set to `.false.`

**Comment by junwang-noaa** [comment]
@rmontuoro gocart can only be built on hera while we run cpld tests (s2s/s2sw) on other platforms, so your change will break RT on those platforms.

**Comment by rmontuoro** [comment]
@junwang-noaa - Agree. Hopefully this is a temporary issue. What do you suggest? I could create a new app (S2SWA) for the time being.

**Comment by arunchawla-NOAA** [comment]
what are the other issues that need to be fixed to enable gocart to run as a coupled model on other platforms? We should not be creating yet another app (S2SWA). There has been a proliferation of apps and we need to fix the issues that are precluding us to build and test fully coupled models

**Comment by rmontuoro** [comment]
The development branch of MAPL no longer requires Python's Pandas package. I submitted a change that was just merged into the authoritative repository. This remove the Pandas dependency from UFS-Aerosols, which I believe was the major roadblock to porting to other platforms.
 
Additional issues were stemming from building hpc-stack with an early version of the Intel 18 compiler on WCOSS.

I agree that creating yet another app is not advisable. For the time being, we could still build the fully coupled model including GOCART by using proper CMake settings.

**Comment by rmontuoro** [comment]
I have removed GOCART from the S2S and S2SW apps.

**Review by climbfuji — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/702980852/20210812183039/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_28253
Test control_c192 015 failed failed 
Test control_c192 015 failed in run_test failed 
Test fv3_gsd_diag_debug 066 failed failed 
Test fv3_gsd_diag_debug 066 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 045 failed failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 045 failed in run_test failed 
Test control_csawmg 025 failed failed 
Test control_csawmg 025 failed in run_test failed 
Please make changes and add the following label back:
hera-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
> Machine: hera
> Compiler: intel
> Job: BL
> Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/702980852/20210812183039/ufs-weather-model
> Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_28253
> Test control_c192 015 failed failed
> Test control_c192 015 failed in run_test failed
> Test fv3_gsd_diag_debug 066 failed failed
> Test fv3_gsd_diag_debug 066 failed in run_test failed
> Test fv3_esg_HAFS_v0_hwrf_thompson 045 failed failed
> Test fv3_esg_HAFS_v0_hwrf_thompson 045 failed in run_test failed
> Test control_csawmg 025 failed failed
> Test control_csawmg 025 failed in run_test failed
> Please make changes and add the following label back:
> hera-intel-BL

@DusanJovic-NOAA They all timed out. FYI.

**Review by DeniseWorthen — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
fv3atm hash is correct, I will merge

**Pull request merged**
