### PR TITLE
Bug fix for cloud effective radius for convective clouds (HR1)

### PR DESCRIPTION
**Pull request by ChunxiZhang-NOAA**
## Description
This is an emergency bug fix for cloud effective radius for convective clouds in ccpp-physics (Issuehttps://github.com/ufs-community/ccpp-physics/issues/36).

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

All cpld and control_p8 related PRs failed as expected.
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/10510611/RegressionTests_hera.intel.log)

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved
- [x] Confirm reviews completed in sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

Dependencies:
 - Depends on ufs-community/ccpp-physics/pull/35
 - Depends on NOAA-EMC/fv3atm/pull/621

Issue:
 - ufs-community/ccpp-physics/issues/36

## Testing Day Checklist:
- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [x] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
With an urgency of this pr, I will start testing while we collect the reviews. @ChunxiZhang-NOAA I am adding new BL_DATE.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]

**Review by sadeghitabas — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1217200031/20230126114209/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_60961
Test hafs_regional_atm_ocn 082 failed in run_test failed 
Test hafs_regional_atm_wav 083 failed in run_test failed 
Test hafs_regional_atm_ocn_wav 084 failed in run_test failed 
Test hafs_regional_1nest_atm 085 failed in run_test failed 
Test hafs_regional_telescopic_2nests_atm 086 failed in run_test failed 
Test hafs_global_multiple_4nests_atm 088 failed in run_test failed 
Test hafs_regional_storm_following_1nest_atm_ocn 091 failed in run_test failed 
Test hafs_regional_docn 094 failed in run_test failed 
Test hafs_regional_docn_oisst 095 failed in run_test failed 
Test hafs_regional_datm_cdeps 096 failed in run_test failed 
Test control_p8_atmlnd_sbs 110 failed in run_test failed 
Test atmaero_control_p8 112 failed in run_test failed 
Test atmaero_control_p8_rad 113 failed in run_test failed 
Test atmaero_control_p8_rad_micro 114 failed in run_test failed 
Test regional_atmaq 115 failed in run_test failed 
Test regional_atmaq_debug 116 failed in run_test failed 
Test compile_019 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1217200031/20230126181517/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1217200031/20230126191156/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA ORT issue was from #1523 We need to update ORT script. @zach1221 is going to create issue. And hopefully we can keep moving with the pr.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1217200031/20230126154209/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by jkbk2004** [comment]
sounds like there is epicufsrt diskquota issue on cheyenne

**Comment by zach1221** [comment]
ORT issue opened here [#1586](https://github.com/ufs-community/ufs-weather-model/issues/1586)

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1217200031/20230126175717/ufs-weather-model
[RT] Error: Test regional_atmaq_debug 151 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @SadeghTabas-NOAA RDHPCS tests are done. ORT issue should be addressed in separate PR. This PR can move on for merging after wcoss2 tests.

**Comment by BrianCurtis-NOAA** [comment]
I haven't had a chance to run on WCOSS2. It's not available today until maybe 3PM. If that's too late, let me know.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA if ok, we can plan to merge by Monday morning ?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 I can merge it in early Monday afternoon.

**Comment by BrianCurtis-NOAA** [comment]
Dogwood just opened up. Starting RT.

**Comment by jkbk2004** [comment]
> Dogwood just opened up. Starting RT.

Cool!

**Comment by BrianCurtis-NOAA** [comment]
Since everything looks OK this morning, I'll start the upstream merge process.

**Comment by jkbk2004** [comment]
> Since everything looks OK this morning, I'll start the upstream merge process.

@BrianCurtis-NOAA Thanks!

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA the fv3atm pr was merged.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
