### PR TITLE
Update build system and regression testing on Acorn

### LINKED ISSUE #810: Updates for WCOSS2 TDS (Acorn)
Minor updates in the build system are required on Acorn. Primarily updates in modulefiles. Regression test is also updated.

See PR #809

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Update the build system to support WCOSS2 TDS (Acorn) and update regression test scripts. No changes in baselines is expected. No new input data required.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #810

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first? No.

### CODE REVIEW

**Comment by climbfuji** [comment]
I will test this as soon as I get access to acorn (@arunchawla-NOAA is working on it, thanks a lot).

**Comment by climbfuji** [comment]
@DusanJovic-NOAA do you want to include the submodule pointer update for CMakeModules (https://github.com/NOAA-EMC/CMakeModules/pull/57) in this PR?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA do you want to include the submodule pointer update for CMakeModules ([NOAA-EMC/CMakeModules#57](https://github.com/NOAA-EMC/CMakeModules/pull/57)) in this PR?

@junwang-noaa already merged this branch in #819 and started regression testing.

**Comment by climbfuji** [comment]
> > @DusanJovic-NOAA do you want to include the submodule pointer update for CMakeModules ([NOAA-EMC/CMakeModules#57](https://github.com/NOAA-EMC/CMakeModules/pull/57)) in this PR?
> 
> @junwang-noaa already merged this branch in #819 and started regression testing.

Ah ok, no problem. I can add it to my next PR then.

**Comment by climbfuji** [comment]
> > > @DusanJovic-NOAA do you want to include the submodule pointer update for CMakeModules ([NOAA-EMC/CMakeModules#57](https://github.com/NOAA-EMC/CMakeModules/pull/57)) in this PR?
> > 
> > 
> > @junwang-noaa already merged this branch in #819 and started regression testing.
> 
> Ah ok, no problem. I can add it to my next PR then.

Done.

**Comment by junwang-noaa** [comment]
Committed through PR#819, close PR.

**Pull request closed without merging**
