### PR TITLE
add temperature limiter for SPPT in MOM6

### LINKED ISSUE #96: ocean SPPT can cause the model to crash
I have run into a case where the mode crashed with ocean SPPT on. I have noticed that I put in a check for negative salinity, but no check for unphysical cold temperatures after the perturbation.  I have a one-line fix to limit the temperature to -1.8.

### LINKED ISSUE #1332: ocean SPPT can cause the ocean model to crash
## Description
I am running with ensemble initial conditions, and I have one member that has large perturbations in it. These perturbations cause large physics tendencies, which are interacting with SPPT to produce a temperature in the ocean that is too cold, and the model fails when this blob of cold water reaches the surface.  

### To Reproduce:
I have a specific case with my own initial conditions, so it will not easy for someone to reproduce.

## Additional context
There is a check in the ocean model's SPPT that prevents salinity to go negative, and there needs to be a check to prevent water temperatures from getting too cold.

### PR DESCRIPTION
**Pull request by pjpegion**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR puts in a limiter in ocean sppt, which put a floor of -1.8C on the temperature after stochastic physics. 

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1332
- fixes NOAA-EMC/MOM6/issues/96

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

I have tested on hera with intel.  The datm_cdeps_stochy_gefs test does not pass, which is expected.

- [ ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on NOAA-EMC/MOM6/pull/97

### CODE REVIEW

**Comment by jiandewang** [comment]
@pjpegion I will include it in https://github.com/ufs-community/ufs-weather-model/pull/1302

**Comment by jswhit** [comment]
Why limit at -1.8K?  I presume it's to prevent the formation of ice - but should the number be hardcoded?

**Comment by DeniseWorthen** [comment]
You could make the limit a function of the salinity, for example -0.054*salinity (which is where the -1.8 comes from, assuming salinity max ~34ppt).

**Comment by pjpegion** [comment]
@jswhit @DeniseWorthen I will change it to be salinity dependent like Denise recommended.  Thanks!

**Comment by DeniseWorthen** [comment]
Closed via #1302

**Pull request closed without merging**
