### PR TITLE
Use inline post with cubed sphere history output

### LINKED ISSUE #1803: Use inline post with cubed sphere history output
## Description
The model now has the capability to write out cubed sphere history files in a similar format to the Gaussian grid history files. We plan to use these as the input to JEDI rather than the FMS restart files (we need the cubed sphere grid for JEDI-based DA and restart files will be unsustainable at operational resolution, particularly for 80 ensemble members x 7 valid times.). 

Currently, if you try to run UFS with cubed sphere history and the inline post together, the model will error because the UPP does not accept cubed sphere grids. It is likely this configuration is the one we would need for any version of the global UFS that uses JEDI for its atmospheric data assimilation. 

One other thing to note: if 'netcdf' is the file type, it will write out six tile files, only 'netcdf_parallel' will write out a single atmf006.nc file with a tile dimension. Not sure if this is by design or not, we would ideally want to use the single file with tile dimension if possible to conform to the current workflow/data structure as much as possible.

## Solution
Have the model (ESMF?) interpolate to an appropriate Gaussian grid for the inline post immediately before passing the fields to the post when writing out cubed sphere history.

## Alternatives
- Allow the model to write out both Gaussian and cubed sphere (but 2x the data is inefficient...)
- Have the UPP/inline post natively handle cubed sphere grids

## Related to
Cycling with JEDI for hybrid 4DEnVar configuration as in the operational GDAS

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

Add new model_configure parameter (history_file_on_native_grid) to allow history outputs on native (cubed sphere) grid to be created when inline post is enabled.

Fixes: https://github.com/ufs-community/ufs-weather-model/issues/1803

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:   control_CubedSphereGrid_parallel

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Library Updates/Changes

- [ ] Not Needed
- [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
- [ ] Add issue link from JCSDA/spack-stack following this item

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- Depends on https://github.com/NOAA-EMC/fv3atm/pull/680

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12016975/RegressionTests_hera.log)

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA do you want to add test to use the option history_file_on_native_grid?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA do you want to add test to use the option history_file_on_native_grid?

I don't know, should we add new test? We already have so many tests.

**Comment by junwang-noaa** [comment]
I'd suggest of adding a low resolution one, just to make sure the feature is working to support DA development.

**Comment by DusanJovic-NOAA** [comment]
How about changing the `control_CubedSphereGrid_parallel` test, by enabling inline post, which is currently turned off, and adding a new option to the model_configure to create native grid output files?

**Review by junwang-noaa — DISMISSED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
@DusanJovic-NOAA, would you be ok with introducing the changes to the remaining tests in #1832 into this PR? 
The two remaining would be 
```
hrrr_control_qr_dyn32_phy32 (intel)
hrrr_control_qr_dyn32_phy32 (gnu)
```

**Comment by DusanJovic-NOAA** [comment]
I changed two hrrr_control_qr_dyn32_phy32 tests to compare against the same baseline as hrrr_control_dyn32_phy32 and ran regression test but it failed:

```
$ cat logs/log_hera/rt_002_hrrr_control_qr_dyn32_phy32_intel.log 

baseline dir = /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20230720/hrrr_control_dyn32_phy32_intel
working dir  = /scratch1/NCEPDEV/stmp2/Dusan.Jovic/FV3_RT/rt_270108/hrrr_control_qr_dyn32_phy32_intel
Checking test 002 hrrr_control_qr_dyn32_phy32_intel results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf009.nc .........OK
 Comparing sfcf012.nc .........OK
 Comparing atmf000.nc .........OK
 Comparing atmf009.nc .........OK
 Comparing atmf012.nc .........OK
 Comparing GFSFLX.GrbF00 .........OK
 Comparing GFSFLX.GrbF09 .........OK
 Comparing GFSFLX.GrbF12 .........OK
 Comparing GFSPRS.GrbF00 .........OK
 Comparing GFSPRS.GrbF09 .........OK
 Comparing GFSPRS.GrbF12 .........OK
 Comparing RESTART/20210322.120000.coupler.res .........OK
 Comparing RESTART/20210322.120000.fv_core.res.nc .........OK
 Comparing RESTART/20210322.120000.fv_core.res.tile1.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_core.res.tile2.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_core.res.tile3.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_core.res.tile4.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_core.res.tile5.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_core.res.tile6.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_srf_wnd.res.tile1.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_srf_wnd.res.tile2.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_srf_wnd.res.tile3.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_srf_wnd.res.tile4.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_srf_wnd.res.tile5.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_srf_wnd.res.tile6.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_tracer.res.tile1.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_tracer.res.tile2.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_tracer.res.tile3.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_tracer.res.tile4.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_tracer.res.tile5.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.fv_tracer.res.tile6.nc ............ALT CHECK......OK
 Comparing RESTART/20210322.120000.phy_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.phy_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.phy_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.phy_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.phy_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.phy_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.sfc_data.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.sfc_data.tile2.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.sfc_data.tile3.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.sfc_data.tile4.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.sfc_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/20210322.120000.sfc_data.tile6.nc ............ALT CHECK......NOT OK

  0: The total amount of wall time                        = 193.250397
  0: The maximum resident set size (KB)                   = 968648

Test 002 hrrr_control_qr_dyn32_phy32_intel FAIL
```
All history outputs, grib files and dynamics restart files are identical, but physics are not. This is not expected.

This will require more debugging, unfortunately we can not combine these changes with this PR at this moment.

**Comment by FernandoAndrade-NOAA** [comment]
Understood, thanks for verifying! We'll begin testing for this PR after 1811 gets merged in.

**Comment by FernandoAndrade-NOAA** [comment]
> Understood, thanks for verifying! We'll begin testing for this PR after 1811 gets merged in.

Apologies for any confusion, there's been some shift in the commit queue testing order: 1794 current, 1825, and then this PR. I'll post an update once we're ready to work on this PR.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, #1825 has been merged in, please go ahead and sync up your branches and any resolve conflicts. We'll begin testing shortly after.
@DusanJovic-NOAA

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA Getting started with jenkins ci for this PR

**Comment by FernandoAndrade-NOAA** [comment]
Jenkins ci log attached, ORTs passed.
[ufs-weather-model » ort-docker-pipeline » PR-1831 #1 Console [Jenkins].txt](https://github.com/ufs-community/ufs-weather-model/files/12197557/ufs-weather-model.ort-docker-pipeline.PR-1831.1.Console.Jenkins.txt)

**Comment by zach1221** [comment]
Good morning, @DusanJovic-NOAA . Can you can that I'm added to your branch here as a contributor? Trying to push logs to this PR, and am being told I'm not authorized.

**Comment by zach1221** [comment]
> Good morning, @DusanJovic-NOAA . Can you can that I'm added to your branch here as a contributor? Trying to push logs to this PR, and am being told I'm not authorized.

Disregard, problem on my end.

**Comment by zach1221** [comment]
Testing is complete. I will follow up on fv3atm sub-pr #680 .

**Comment by zach1221** [comment]
@DusanJovic-NOAA fv3atm PR [#680 ](https://github.com/NOAA-EMC/fv3atm/pull/680) has been merged. Please update the sub-module pointer and revert the changes in gitmodules
fv3atm hash: f595b972ab0a099a8ef13ddad313ec2c0d8672d4

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA fv3atm PR [#680 ](https://github.com/NOAA-EMC/fv3atm/pull/680) has been merged. Please update the sub-module pointer and revert the changes in gitmodules fv3atm hash: f595b972ab0a099a8ef13ddad313ec2c0d8672d4

Done

**Comment by zach1221** [comment]
> > @DusanJovic-NOAA fv3atm PR [#680 ](https://github.com/NOAA-EMC/fv3atm/pull/680) has been merged. Please update the sub-module pointer and revert the changes in gitmodules fv3atm hash: f595b972ab0a099a8ef13ddad313ec2c0d8672d4
> 
> Done

Thank you! Requests for final reviews have been sent.

**Review by sadeghitabas — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
