### PR TITLE
Allow instantaneous SW and LW fluxes to be used when cpllnd=.true.

### LINKED ISSUE #710: allow instantaneous down LW and SW to be used by when cpllnd=true
## Description

When ``cpllnd=.true``, only the "mean" downward LW and SW fluxes are available for the export state. To resolve issue ufs-community/ufs-weather-model/issues/1800, the "inst" values need to be moved inside the ``cpllnd=.true.`` block.

## Solution

Add ``Coupling%dlwsfci_cpl`` and ``Coupling%dswsfci_cpl`` to the ``cpllnd=.true.`` blocks where needed. 

## Testing:

UWM RTs were run at and all tests are B4B since at this time the new variables are not being accessed. 

Logs posted at https://github.com/ufs-community/ufs-weather-model/pull/1943

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:

- required by ufs-community/ufs-weather-model/pull/1942
- associated issue ufs-community/ufs-weather-model/issues/1800

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [ ] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/12917028/RegressionTests_hera.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Allows SW and LW instantaneous export fields for when coupled to external land component.

### Associated UFSWM Issue to close

- closes https://github.com/NOAA-EMC/fv3atm/issues/710
- required by https://github.com/ufs-community/ufs-weather-model/pull/1942 

### Subcomponent Pull Requests

- https://github.com/NOAA-EMC/fv3atm/pull/711
- https://github.com/ufs-community/ccpp-physics/pull/118

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [x] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Hercules
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment
</details>

### CODE REVIEW

**Review by uturuncoglu — APPROVED** [review]
@DeniseWorthen At this point I am not using `inst_down_lw_flx` and `inst_down_sw_flx` in NoahMP cap but using `Faxa_swdn` and `Faxa_lwdn` which are pointing mean values. Since, all the components under UFS Weather Model are switching to instantaneous fields, maybe NoahMP needs to switch those. Let me know what you think?

**Comment by uturuncoglu** [comment]
@DeniseWorthen Do you also plan to do changes in `CMEPS/mediator/esmFldsExchange_nems_mod.F90`? I think the other configurations under UFS Weather model are still using `Faxa_lwdn` which is the mean field if you check in fd_nems.yaml.

**Comment by DeniseWorthen** [comment]
@uturuncoglu Yes, there is a follow-on #1942 to this one which will switch the remaining field aliases to be ``inst``. I've been making a series of PRs to get everything aligned, and I want the final PR to be only a change of alias, no code changes. Unfortunately I missed this cpllnd change that is needed in the #1925 that was just committed. That change was for the fields going TO atm.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Okay. Thanks for the clarification. I think this PR good to go. In any case, I don't think but if I had issue in the land PR, I could fixed in there.

**Comment by DeniseWorthen** [comment]
@uturuncoglu I think it would be good to clean up the un-used fields in the ``cpllnd`` logical blocks. It isn't clear to me if you might end up using those in the future (the banded SW down for example) and so want to retain them, or if they really aren't required for the LND component after all.

**Comment by uturuncoglu** [comment]
@DeniseWorthen I could not see the place that land uses the banded SW down. Could you point me the code? Maybe this is already fixed in my PR but not sure. It would be nice to double check.

**Comment by DeniseWorthen** [comment]
@uturuncoglu I was looking at 
      
https://github.com/NOAA-EMC/fv3atm/blob/a13a239a746cb95c74bbe5841f300cb75f8b80d9/ccpp/data/GFS_typedefs.F90#L2875-L2882

In your original commit to add the land component, these got moved from just a cpflx block into the cplflx or cpllnd block. These are actually the net SWs---I called them the down SWs by mistake.

**Comment by uturuncoglu** [comment]
@DeniseWorthen Okay. Those are not used by land and it is not required by NoahMP. In the sbs (and also fully coupled - in the outstanding PR) configuration FV3 is not coupled with ocean and only coupled by land (so, in this case cplflx = false but cpllnd = true) and maybe those parts are only required to satisfy some internal logic in the FV3 side since it was assuming that cplflx is always true if it is coupled. Does it makes sense?

**Comment by DeniseWorthen** [comment]
I'm a little confused, myself. Originally (prior to your first land PR), those fields were only in the cplflx block. But, they're actually not needed when coupling to ocean either (swnet is only needed by HAFS). I can try moving them back to the cplflx block and see if I can get a failure.

**Comment by DeniseWorthen** [comment]
This PR should *not* have been closed. This happens when you mistakenly 'sync' to develop on github and it discards the commits that are actually present in the PR.

**Comment by DeniseWorthen** [comment]
Re-opening

**Comment by DeniseWorthen** [comment]
I guess I can't re-open. I will need to re-create.

**Pull request closed without merging**
