### PR TITLE
Aqm bugfixes + New AQM Debug RT (#1505), INLINE_POST default (#1503), WCOSS2 MAPL Enable Tests (#1507)

### LINKED ISSUE #44: AQM should run with a debug build of UFSWM
An NCO requirement is to run the UFSWM AQM with Debug build.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
This PR brings in a new regression test (regional_atmaq_debug) to make sure that AQM changes don't break the ability for ATMAQ app to run in Debug mode.

### Issue(s) addressed
- fixes noaa-emc/aqm/issues/44
- closes #1503 
- closes #1507 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- acorn.intel (skip due to queue down)
- [x] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies
- waiting on NOAA-EMC/AQM/pull/43

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
ORT Results
```
baseline dir = /scratch1/NCEPDEV/stmp4/Brian.Curtis/FV3_OPNREQ_TEST/OPNREQ_TEST/regional_atmaq_debug_bit_base
working dir  = /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_OPNREQ_TEST/opnReqTest_23636/regional_atmaq_debug_bit_base
Checking test bit_base regional_atmaq_debug results ....
Moving baseline bit_base regional_atmaq_debug files ....
 Moving sfcf000.nc .........OK
 Moving sfcf001.nc .........OK
 Moving atmf000.nc .........OK
 Moving atmf001.nc .........OK
 Moving RESTART/coupler.res .........OK
 Moving RESTART/fv_core.res.nc .........OK
 Moving RESTART/fv_core.res.tile1.nc .........OK
 Moving RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Moving RESTART/fv_tracer.res.tile1.nc .........OK
 Moving RESTART/phy_data.nc .........OK
 Moving RESTART/sfc_data.nc .........OK

  0: The total amount of wall time                        = 1212.429568
  0: The maximum resident set size (KB)                   = 1055764

Test bit_base regional_atmaq_debug PASS

baseline dir = /scratch1/NCEPDEV/stmp4/Brian.Curtis/FV3_OPNREQ_TEST/OPNREQ_TEST/regional_atmaq_debug_std_base
working dir  = /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_OPNREQ_TEST/opnReqTest_23636/regional_atmaq_debug_std_base
Checking test std_base regional_atmaq_debug results ....
Moving baseline std_base regional_atmaq_debug files ....
 Moving sfcf000.nc .........OK
 Moving sfcf001.nc .........OK
 Moving atmf000.nc .........OK
 Moving atmf001.nc .........OK
 Moving RESTART/coupler.res .........OK
 Moving RESTART/fv_core.res.nc .........OK
 Moving RESTART/fv_core.res.tile1.nc .........OK
 Moving RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Moving RESTART/fv_tracer.res.tile1.nc .........OK
 Moving RESTART/phy_data.nc .........OK
 Moving RESTART/sfc_data.nc .........OK

  0: The total amount of wall time                        = 1271.699074
  0: The maximum resident set size (KB)                   = 1200060

Test std_base regional_atmaq_debug PASS


baseline dir = /scratch1/NCEPDEV/stmp4/Brian.Curtis/FV3_OPNREQ_TEST/OPNREQ_TEST/regional_atmaq_debug_std_base
working dir  = /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_OPNREQ_TEST/opnReqTest_23636/regional_atmaq_debug_thr
Checking test thr regional_atmaq_debug results ....
 Comparing sfcf000.nc .........OK
 Comparing sfcf001.nc .........OK
 Comparing atmf000.nc .........OK
 Comparing atmf001.nc .........OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc .........OK
 Comparing RESTART/phy_data.nc .........OK
 Comparing RESTART/sfc_data.nc .........OK

  0: The total amount of wall time                        = 1068.725104
  0: The maximum resident set size (KB)                   = 1197900

Test thr regional_atmaq_debug PASS
```

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA sounds like all sets. I am adding bl labels from hera.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 only need to run regional_atmaq and regional_atmaq_debug creation i believe. The others should not change. Might be easiest to do that manually, and run the AutoRT afterwards.

**Comment by jkbk2004** [comment]
> @jkbk2004 only need to run regional_atmaq and regional_atmaq_debug creation i believe. The others should not change. Might be easiest to do that manually, and run the AutoRT afterwards.

sure!

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/1139478807/20221130234511/ufs-weather-model
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 051 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1139478807/20221130233017/ufs-weather-model
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 118 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_wav 120 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 121 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 122 failed in run_test failed 
[RT] Error: Test hafs_regional_datm_cdeps 124 failed in run_test failed 
[RT] Error: Test regional_atmaq 146 failed in run_test failed 
[RT] Error: Test regional_atmaq_debug 147 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by jkbk2004** [comment]
With turning off regional_atmaq_debug on jet, we are good to start merging process.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
