### PR TITLE
Couple convective clouds to radiation

### PR DESCRIPTION
**Pull request by grantfirl**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ ] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR
are specified below.

- [X] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

Opened on behalf of @Qingfu-Liu:
This PR contains adds the convective cloud water (liquid water + ice water) in the calculations of Cloud Water Path and Ice Water Path for radiation cloud properties.
For RRTMG radiation, only one file changed: radiation_clouds.f (code changed by Ruiyu Sun)
For RRTMGP radiation, one file has changed and there is an upstream change needed in NOAA-EMC/fv3atm for a new interstitial variable.

This will change the baselines for any RT using the Thompson MP scheme
[TestingAndEvaluation_PR9.pdf](https://github.com/ufs-community/ccpp-physics/files/9678514/TestingAndEvaluation_PR9.pdf)

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [X] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel
- [x] cheyenne.gnu
- [x] gaea.intel
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

https://github.com/ufs-community/ccpp-physics/pull/9
https://github.com/NOAA-EMC/fv3atm/pull/589

### CODE REVIEW

**Comment by jkbk2004** [comment]
@grantfirl we can start working on this pr. Can you sync up branches?

**Comment by grantfirl** [comment]
@jkbk2004 OK, branches are synced.

**Comment by jkbk2004** [comment]
All RT tests are done. we can start merging process. @grantfirl @ChunxiZhang-NOAA ccpp dependency can be merged first.

**Comment by grantfirl** [comment]
@jkbk2004 The ccpp-physics PR has been merged. I've requested that the fv3atm PR branch owner update their submodules/.gitmodules to continue the merge process.

**Comment by dustinswales** [comment]
@jkbk2004 fv3atm has been updated.

**Comment by jkbk2004** [comment]
thanks @dustinswales can you update submodule pointer and revert gitmodules on fv3atm side here?

**Comment by jkbk2004** [comment]
> thanks @dustinswales can you update submodule pointer and revert gitmodules on fv3atm side here?

@grantfirl please, go ahead to update hash and revert the branch.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by grantfirl** [comment]
> > thanks @dustinswales can you update submodule pointer and revert gitmodules on fv3atm side here?
> 
> @grantfirl please, go ahead to update hash and revert the branch.

@jkbk2004 Done

**Review by jkbk2004 — APPROVED** [review]

**Pull request merged**
