### PR TITLE
Updates for the Community Convective Cloud (C3) scheme

### PR DESCRIPTION
**Pull request by haiqinli**
## Description
1. Name the new unified convective parameterization as "Community Convective Cloud (c3) parameterization";
2. Update the aerosol-aware for GF;
3. Merge the aerosol-aware and RRFS configuration from GF into C3;
4. Make the closures as input namelist options for C3 and GF.

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] There will be new input data. 
- [ ] Input data will be updated. 

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test. 
- [x] Changes are expected to the following tests: 

 The following RT's are failed as expected because of the GF updates.
rap_2threads_dyn32_phy32       rap_control_dyn32_phy32.err       rap_flake_debug                    rap_sfcdiff_decomp
rap_2threads                  rap_control_dyn64_phy32_debug  rap_lndp_debug                     rap_sfcdiff
rap_cires_ugwp_debug           rap_control_dyn64_phy32       rap_noah_debug                     rap_unified_drag_suite_debug
rap_clm_lake_debug             rap_control                    rap_noah_sfcdiff_cires_ugwp_debug  rap_unified_ugwp_debug
rap_control_debug_dyn32_phy32  rap_decomp                     rap_progcld_thompson_debug
rap_control_debug             rap_diag_debug                 rap_sfcdiff_debug

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [x] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### CODE REVIEW

**Comment by jkbk2004** [comment]
We are about to merge in #1752. If you are available, we can follow on this pr. Have you tested this pr wither on hera or cheyenne?

**Comment by jkbk2004** [comment]
Also, can you update the PR description to link in fv3 and ccpp PRs?

**Comment by haiqinli** [comment]
@jkbk2004 Yes, I tested it on Hera a few weeks ago. Sure, I will sync the ccpp-physics and also update the link to fv3atm and ufs-weather-model. Thanks.

**Comment by jkbk2004** [comment]
Sure! go ahead to sync up.

**Comment by DeniseWorthen** [comment]
@jkbk2004 This PR template is not complete. It appears sections were removed.

**Review by DeniseWorthen — CHANGES_REQUESTED** [review]
Both CDEPS and CMEPS are out of date

**Comment by haiqinli** [comment]
@DeniseWorthen I reestablished the develop-c3 branch with the latest version ufs-weather-model. But it seems the PR was automatically closed.

**Comment by haiqinli** [comment]
@DeniseWorthen I reestablished the develop-c3 branch with the latest version ufs-weather-model. But it seems the PR was automatically closed. Thus I reopen this PR. Thanks.

**Comment by haiqinli** [comment]
The develop-c3

**Comment by jkbk2004** [comment]
@haiqinli it's still closed. If you need time, we can let #1769 go first.

**Comment by haiqinli** [comment]
@jkbk2004 This PR is ready. I tried to reopen this PR, but was not successful. Would you like to reopen this PR? Thanks.

**Comment by haiqinli** [comment]
@jkbk2004 @DeniseWorthen Actually the regression test of this PR with Intel compiler on Hera just successfully done at /scratch1/BMC/gsd-fv3-dev/Haiqin.Li/HFIP/Commit/ufs-weather-model/tests/logs/RegressionTests_hera.log. I am starting the GNU/Hera regression test.

**Comment by haiqinli** [comment]
Try to reopen this PR.

**Comment by haiqinli** [comment]
@jkbk2004 @DeniseWorthen 
I was not able to update CDEPS and CMEPS. Then I reestablished the develop-c3 branch. Unfortunately, the PR was automatically closed, and I could not reopen it.
If both of us could not reopen this PR, I may open a new supplementary PR, which may only take a few minutes.

**Comment by jkbk2004** [comment]
Looks like branch was deleted after pr was closed. Git is not going to let pr reopen if there is change/commit with pr closed. I agree with opening a new pr. BTW, #1769 is ready. So we can schedule new pr after we merge #1769.

**Comment by haiqinli** [comment]
@jkbk2004 I am starting a new PR, and it should be ready in just a new minutes. I don't want my PR to de delayed. Thanks.

**Comment by haiqinli** [comment]
@jkbk2004 I created a new PR of https://github.com/ufs-community/ufs-weather-model/pull/1795, and it has successfully passed the Intel/Hera and GNU/Hera regression test, and it is ready. I hope my PR will be merged as scheduled. Thanks.

**Pull request closed without merging**
