### PR TITLE
Cleanup CCPP cmake build, reduce number of compile jobs, use atparse for variable substitution in MOM and CICE input files

### LINKED ISSUE #384: CCPP must define its targets and dependencies correctly
## Description

ccpp-framework and ccpp-physics must define their (cmake) targets and dependencies correctly, so that `ccpp/CMakeLists.txt` can be cleaned up.

### LINKED ISSUE #783: Switch to "atparse" instead of "edit_inputs" for ice_in and MOM_input templates
## Description
The ice_in and MOM_input templates should be processed in the same manner as other input namelists rather than with the ``sed`` command and the ``edit_inputs`` function.

## Solution

Switch required templates to use ``@[configuration_setting]`` and add required ``atparse`` commands in ``run_test.sh``

### LINKED ISSUE #792: Reduce  number of compile jobs for regression testing
## Description

Background: The Intel compiler has limitations in terms of how many CCPP suites can be compiled into the executable at the same time. Too many suites lead to internal compiler errors. Therefore compile jobs have been broken up in the past.

The existing compile jobs take a long time, because there are so many of them. They should be combined to the extent that the Intel compilers permit it.

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [n/a] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Description

- Update submodule pointers for fv3atm, ccpp-framework and ccpp-physics for the changes described in the associated PRs below (cleanup CCPP cmake build)
- Reduce the number of compile jobs by combining compilations that only differ in the `-DCCPP_SUITES` argument to the extent that the Intel compilers allow it (i.e. do not abort with internal compiler errors)
- Ensure that only one WW3 compile job is running at any given time (no clean out-of-source build) - from @DusanJovic-NOAA 
- Contains PR #784 "Use atparse for variable substitution in MOM and CICE input files" from @DeniseWorthen 
- Also: increase wallclock time on Gaea to 2hrs (120mins) to deal with temporary variability in run times

### Issue(s) addressed

- fixes https://github.com/NOAA-EMC/fv3atm/issues/384
- fixes https://github.com/ufs-community/ufs-weather-model/issues/792
- fixes https://github.com/ufs-community/ufs-weather-model/issues/783

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [X] CI - https://github.com/ufs-community/ufs-weather-model/pull/791/commits/6bbc7098a2b21f3946f760d316b72d100e8d111f

## Dependencies

Associated PRs:

- waiting on https://github.com/NCAR/ccpp-framework/pull/382
- waiting on https://github.com/NCAR/ccpp-physics/pull/705
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/383

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/731093042/20210909201511/ufs-weather-model
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/731093042/20210910021510/ufs-weather-model
Please make changes and add the following label back:
hera-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/731093042/20210909202140/ufs-weather-model
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/731093042/20210910020010/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_3912
Test compile 003 failed failed 
Test compile 007 failed failed 
Test compile 006 failed failed 
Test compile 008 failed failed 
Test compile 001 failed failed 
Test compile 004 failed failed 
Test compile 002 failed failed 
Test compile 009 failed failed 
Test compile 005 failed failed 
Test compile 014 failed failed 
Test compile 015 failed failed 
Please make changes and add the following label back:
hera-intel-RT

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/731093042/20210913184505/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_11198
Test cpld_control_c384 008 failed failed 
Test cpld_control_c384 008 failed in run_test failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Test control_c384 026 failed failed 
Test control_c384 026 failed in run_test failed 
Test control_c384gdas 027 failed failed 
Test control_c384gdas 027 failed in run_test failed 
Test regional_control 035 failed failed 
Test regional_control 035 failed in run_test failed 
Test regional_quilt 037 failed failed 
Test regional_quilt 037 failed in run_test failed 
Test fv3_gsd 042 failed failed 
Test fv3_gsd 042 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by DusanJovic-NOAA** [comment]
> _**Automated RT Failure Notification**_
> Machine: gaea
> Compiler: intel
> Job: RT
> Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/731093042/20210913184505/ufs-weather-model
> Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_11198
> Test cpld_control_c384 008 failed failed
> Test cpld_control_c384 008 failed in run_test failed
> Test cpld_bmark_v16 010 failed failed
> Test cpld_bmark_v16 010 failed in run_test failed
> Test control_c384 026 failed failed
> Test control_c384 026 failed in run_test failed
> Test control_c384gdas 027 failed failed
> Test control_c384gdas 027 failed in run_test failed
> Test regional_control 035 failed failed
> Test regional_control 035 failed in run_test failed
> Test regional_quilt 037 failed failed
> Test regional_quilt 037 failed in run_test failed
> Test fv3_gsd 042 failed failed
> Test fv3_gsd 042 failed in run_test failed
> Please make changes and add the following label back:
> gaea-intel-RT

Usual timeout failure:

```
  0:  in fcst run phase 2, na=          90
  0: slurmstepd: error: *** STEP 268887148.0 ON nid00751 CANCELLED AT 2021-09-13T20:15:37 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 268887148 ON nid00751 CANCELLED AT 2021-09-13T20:15:37 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.

```

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/731093042/20210913184516/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_197364
Test control_c48 023 failed in check_result failed 
Test control_c48 023 failed in run_test failed 
Test control_wrtGauss_netcdf_parallel 022 failed in check_result failed 
Test control_wrtGauss_netcdf_parallel 022 failed in run_test failed 
Test control_CubedSphereGrid 021 failed in check_result failed 
Test control_CubedSphereGrid 021 failed in run_test failed 
Test control 016 failed in check_result failed 
Test control 016 failed in run_test failed 
Test cpld_control 001 failed in check_result failed 
Test cpld_control 001 failed in run_test failed 
Test control_decomp 017 failed in check_result failed 
Test control_decomp 017 failed in run_test failed 
Test control_fhzero 020 failed in check_result failed 
Test control_fhzero 020 failed in run_test failed 
Test cpld_ca 004 failed in check_result failed 
Test cpld_ca 004 failed in run_test failed 
Test cpld_2threads 003 failed in check_result failed 
Test cpld_2threads 003 failed in run_test failed 
Test control_2threads 018 failed in check_result failed 
Test control_2threads 018 failed in run_test failed 
Test regional_control 034 failed in check_result failed 
Test regional_control 034 failed in run_test failed 
Test cpld_control_c192 005 failed in check_result failed 
Test cpld_control_c192 005 failed in run_test failed 
Test cpld_control_c384 007 failed in check_result failed 
Test cpld_control_c384 007 failed in run_test failed 
Test cpld_bmark_wave_v16 012 failed in check_result failed 
Test cpld_bmark_wave_v16 012 failed in run_test failed 
Test cpld_bmark_v16 009 failed in check_result failed 
Test cpld_bmark_v16 009 failed in run_test failed 
Test control_c192 024 failed in check_result failed 
Test control_c192 024 failed in run_test failed 
Test cpld_bmark_v16_nsst 011 failed in check_result failed 
Test cpld_bmark_v16_nsst 011 failed in run_test failed 
Test cpld_control_wave 014 failed in check_result failed 
Test cpld_control_wave 014 failed in run_test failed 
Test cpld_bmark_wave_v16_p7b 013 failed in check_result failed 
Test cpld_bmark_wave_v16_p7b 013 failed in run_test failed 
Test control_c384 025 failed in check_result failed 
Test control_c384 025 failed in run_test failed 
Test control_lndp 030 failed in check_result failed 
Test control_lndp 030 failed in run_test failed 
Test control_stochy 027 failed in check_result failed 
Test control_stochy 027 failed in run_test failed 
Test control_ca 029 failed in check_result failed 
Test control_ca 029 failed in run_test failed 
Test control_lheatstrg 031 failed in check_result failed 
Test control_lheatstrg 031 failed in run_test failed 
Test control_lseaspray 032 failed in check_result failed 
Test control_lseaspray 032 failed in run_test failed 
Test datm_control_gefs 090 failed in run_test failed 
Test regional_quilt 036 failed in check_result failed 
Test regional_quilt 036 failed in run_test failed 
Test fv3_rrfs_v1alpha 041 failed in check_result failed 
Test fv3_rrfs_v1alpha 041 failed in run_test failed 
Test fv3_rap 042 failed in check_result failed 
Test fv3_rap 042 failed in run_test failed 
Test control_merra2 033 failed in check_result failed 
Test control_merra2 033 failed in run_test failed 
Test control_c384gdas 026 failed in check_result failed 
Test control_c384gdas 026 failed in run_test failed 
Test fv3_gsd 040 failed in check_result failed 
Test fv3_gsd 040 failed in run_test failed 
Test regional_quilt_netcdf_parallel 038 failed in check_result failed 
Test regional_quilt_netcdf_parallel 038 failed in run_test failed 
Test regional_quilt_hafs 037 failed in check_result failed 
Test regional_quilt_hafs 037 failed in run_test failed 
Test fv3_hrrr 043 failed in check_result failed 
Test fv3_hrrr 043 failed in run_test failed 
Test fv3_rrfs_v1beta 044 failed in check_result failed 
Test fv3_rrfs_v1beta 044 failed in run_test failed 
Test control_ras 050 failed in check_result failed 
Test control_ras 050 failed in run_test failed 
Test regional_quilt_RRTMGP 039 failed in check_result failed 
Test regional_quilt_RRTMGP 039 failed in run_test failed 
Test control_ugwpv1 049 failed in check_result failed 
Test control_ugwpv1 049 failed in run_test failed 
Test control_rrtmgp 045 failed in check_result failed 
Test control_rrtmgp 045 failed in run_test failed 
Test control_flake 048 failed in check_result failed 
Test control_flake 048 failed in run_test failed 
Test control_thompson 051 failed in check_result failed 
Test control_thompson 051 failed in run_test failed 
Test fv3_HAFS_v0_hwrf_thompson 054 failed in check_result failed 
Test fv3_HAFS_v0_hwrf_thompson 054 failed in run_test failed 
Test control_thompson_no_aero 052 failed in check_result failed 
Test control_thompson_no_aero 052 failed in run_test failed 
Test control_csawmg 046 failed in check_result failed 
Test control_csawmg 046 failed in run_test failed 
Test control_noahmp 053 failed in check_result failed 
Test control_noahmp 053 failed in run_test failed 
Test control_csawmgt 047 failed in check_result failed 
Test control_csawmgt 047 failed in run_test failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 055 failed in check_result failed 
Test fv3_esg_HAFS_v0_hwrf_thompson 055 failed in run_test failed 
Test hafs_regional_docn 085 failed in check_result failed 
Test hafs_regional_docn 085 failed in run_test failed 
Test hafs_regional_atm_ocn 084 failed in check_result failed 
Test hafs_regional_atm_ocn 084 failed in run_test failed 
Test hafs_regional_docn_oisst 086 failed in check_result failed 
Test hafs_regional_docn_oisst 086 failed in run_test failed 
Test hafs_regional_atm 083 failed in check_result failed 
Test hafs_regional_atm 083 failed in run_test failed 
Test control_atmwav 106 failed in check_result failed 
Test control_atmwav 106 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/731093042/20210913213007/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_25654
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Test cpld_bmark_v16_nsst 012 failed failed 
Test cpld_bmark_v16_nsst 012 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: gaea
> Compiler: intel
> Job: RT
> Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/731093042/20210913213007/ufs-weather-model
> Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_25654
> Test cpld_bmark_v16 010 failed failed
> Test cpld_bmark_v16 010 failed in run_test failed
> Test cpld_bmark_v16_nsst 012 failed failed
> Test cpld_bmark_v16_nsst 012 failed in run_test failed
> Please make changes and add the following label back:
> gaea-intel-RT

It doesn't make any sense to rerun by simply adding the label, tests will time out again. Will upload the log in a second.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/731093042/20210914101510/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_26714
Test control_ras 010 failed in run_test failed 
Test control 001 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-gnu-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/731093042/20210914100012/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_71724
Test cpld_control_c192 006 failed in run_test failed 
Test control_flake 049 failed in run_test failed 
Test control_csawmgt 048 failed in run_test failed 
Test control_thompson 052 failed in run_test failed 
Test cpld_bmark_v16 010 failed failed 
Test cpld_bmark_v16 010 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/731093042/20210914160006/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_3648
Test compile 009 failed failed 
Test control_thompson_no_aero 053 failed failed 
Test control_thompson_no_aero 053 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-RT

**Comment by climbfuji** [comment]
Cheyenne tests failed due to disk quota issues (presumably), I cleared the scratch area, will add labels for GNU and Intel one after the other. Gaea: Will rerun failed tests manually.

**Comment by climbfuji** [comment]
Except for orion, all regression tests finished and were successful. On Orion, we still have several jobs in the queue.

**Comment by climbfuji** [comment]
> Except for orion, all regression tests finished and were successful. On Orion, we still have several jobs in the queue.

All tests on orion passed so far, one remaining one is still running. I am going to start merging ccpp-framework and ccpp-physics.

**Comment by climbfuji** [comment]
I verified hash for fv3atm to be correct (85c2648).

**Pull request merged**
