### PR TITLE
Sync WW3 develop with dev/ufs-weather-model, Oct 12th 2022

### PR DESCRIPTION
**Pull request by MatthewMasarik-NOAA**
# PR Checklist                                                                                                                                                 
                                                                                                                                                               
- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.                                                                                                                                     
                                                                                                                                                               
- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR                                                                                                                                             
                                                                                                                                                               
- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR                                  
are specified below.                                                                                                                                           
                                                                                                                                                               
- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.                               
                                                                                                                                                               
- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.             
                                                                                                                                                               
## Instructions: All subsequent sections of text should be filled in as appropriate.                                                                           
                                                                                                                                                               
The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model.                                                                                                                                                 
                                                                                                                                                               
## Description                                                                                                                                                 
                                                                                                                                                               
* Provide a detailed description of what this PR does. What bug does it fix, or what feature does it add?                                                      
   * This PR updates the WW3 component by syncing it's `dev/ufs-weather-model` branch with `develop`.                                                          
                                                                                                                                                               
* Is a change of answers expected from this PR?                                                                                                                
   * Yes.  Some answers were expected to change due to noaa-emc/ww3/pull/741.
     * This WW3 PR causes answers to change because of a change in the peak frequency.
     * In the UFS RT's **only** the WW3 output (`out_grd.*`) changes as a result.
     * The tests that require a new baseline are limited to:
      ```bash
        Test cpld_control_p8
        Test cpld_2threads_p8 
        Test cpld_esmfthreads_p8 
        Test cpld_decomp_p8 
        Test cpld_mpi_p8  
        Test cpld_control_ciceC_p8  
        Test cpld_control_c192_p8  
        Test cpld_control_noaero_p8
      ```
        * The rest of the tests are unchanged.
   * A baseline has successfully been created/matched and can be found at:  `/scratch1/NCEPDEV/stmp4/Matthew.Masarik/FV3_RT/REGRESSION_TEST_INTEL`.
   * _Note: compile_011 was not successful.  This has been documented at:_ #1450                                                                                
                                                                                                                                                               
* Are any library updates included in this PR (modulefiles etc.)?                                                                                              
  * No.                                                                                                                                                        

* Coauthor
  * @JessicaMeixner-NOAA  
 
                                                                                                    
### Issue(s) addressed                                                                                                                                         
                                                                                                                                                               
Link the issues to be closed with this PR, whether in this repository, or in another repository.                                                               
- addresses #1452                                                                                                                                              
                                                                                                                                                               
## Testing                                                                                                                                                     
                                                                                                                                                               
How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)                                                                                                                                                        
                                                                                                                                                               
Tested on hera.intel.                                                                                                                                          
                                                                                                                                                               
- [x] hera.intel                                                                                                                                               
- [x] hera.gnu                                                                                                                                                 
- [x] orion.intel                                                                                                                                              
- [x] cheyenne.intel                                                                                                                                           
- [x] cheyenne.gnu                                                                                                                                             
- [x] gaea.intel                                                                                                                                               
- [x] jet.intel                                                                                                                                                
- [x] wcoss2.intel                                                                                                                                             
- [x] acorn.intel                                                                                                                                              
- [ ] opnReqTest for newly added/changed feature                                                                                                               
- [x] CI                                                                                                                                                       
                                                                                                                                                               
## Dependencies                                                                                                                                                
                                                                                                                                                               
If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).                    
                                                                                                                                                               
Do PRs in upstream repositories need to be merged first?                                                                                                       
- waiting on noaa-emc/ww3/pull/817.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA When I was testing the changes in develop for my own use, I found that not all the tests which use WW3 had changed baselines. Can you please document in the PR which tests actually failed comparison due to PR #741?

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA When I was testing the changes in develop for my own use, I found that not all the tests which use WW3 had changed baselines. Can you please document in the PR which tests actually failed comparison due to PR #741?

Hi @DeniseWorthen , sure.  I just updated the PR template so all the info is in one place.

**Comment by jkbk2004** [comment]
@MatthewMasarik-NOAA we are putting #1456 and #1460 on hold for today. If this PR is ready, we may start testing.

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA we are putting #1456 and #1460 on hold for today. If this PR is ready, we may start testing.

@jkbk2004, Yes this PR is ready for testing.  Please proceed.

**Comment by zach1221** [comment]
Jenkins-ci run logs attached. 
[ufs-weather-model » ort-docker-pipeline » PR-1454 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/9860364/ufs-weather-model.ort-docker-pipeline.PR-1454.1.Console.Jenkins.pdf)

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 are we ready for the WW3 PR to be merged?

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @MatthewMasarik-NOAA All tests are done. We can start merging in [ww3#817](https://github.com/NOAA-EMC/WW3/pull/817). @BrianCurtis-NOAA do you see any other last minute update?

**Comment by MatthewMasarik-NOAA** [comment]
> @JessicaMeixner-NOAA @MatthewMasarik-NOAA All tests are done. We can start merging in [ww3#817](https://github.com/NOAA-EMC/WW3/pull/817). @BrianCurtis-NOAA do you see any other last minute update?

@jkbk2004, I've updated the .gitmodules

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
