### PR TITLE
Update fv3atm to FMS2 io.

### LINKED ISSUE #551: Update fv3atm code to fms2_io
FMS library will deprecate and eventually remove fms_io and mpp_io modules from future releases. Code must be updated to replace (or remove) any use of those modules with newer fms2_io.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsibility to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Update fv3atm to use new fms2 io modules.
Is a change of answers expected from this PR? No.
Are any library updates included in this PR (modulefiles etc.)? No.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes NOAA-EMC/fv3atm/issues/551

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/fv3atm/pull/560

### CODE REVIEW

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA I want to check if we can combine in #1305 to this PR? Orion still down but Jet is back. So we can start testing today.

**Comment by DusanJovic-NOAA** [comment]
Please ask PR #1305 owner to open PR to my branch.

**Comment by jkbk2004** [comment]
> Please ask PR #1305 owner to open PR to my branch.

Sure!

**Comment by junwang-noaa** [comment]
@jkbk2004 @DusanJovic-NOAA I'd like to take a little longer time on PR#1305, please go ahead to commit PR#1317.

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA sounds like we will work on this only today. Jun said more time is needed for the esmf-threading PR. I will start testing from cheyenne around noon.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/989057130/20220728163013/ufs-weather-model
[RT] Error: Test control_c384gdas 028 failed in run_test failed 
Please make changes and add the following label back: jet-intel-RT

**Comment by DeniseWorthen** [comment]
@jkbk2004 We need approval and merge on the fv3 side.

**Comment by BrianCurtis-NOAA** [comment]
Code looks good. Waiting to approve for revert and hash check.

**Review by DeniseWorthen — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
