### PR TITLE
Fix bug in state_diagnose to accept 4d variables. Update CCPP Framework to support IAP model. Update weekly tests

### LINKED ISSUE #1314: aerosols breaks diagnose_cplFields for FV3
## Description
The setting of ``dbug_flag`` in nems.configure for the coupled model triggers the reporting of the min, max and sum of each connected import or export field for FV3. When the app is S2SWA, this produces an error in the PET logs connected to FV3.

### To Reproduce:
Run both ``cpld_control_p8`` (app=S2SWA) and ``cpld_control_noaero_p8`` (app=S2SW) but change the ``default_vars`` value of dbug_flag

index 28807b10..c9117d04 100755
--- a/tests/default_vars.sh
+++ b/tests/default_vars.sh
@@ -609,7 +609,7 @@ export coupling_interval_fast_sec=${DT_ATMOS}

 export RESTART_N=${FHMAX}
 export CPLMODE=nems_frac
-export cap_dbug_flag=0
+export cap_dbug_flag=6
 export use_coldstart=false
 export use_mommesh=true
 export RUNTYPE=startup

The log files for the cpld_control_noaero_p8 show no ERROR messages. 

For the cpld_control_p8, the PET logs show on import:

```
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:ice_fraction    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_ir_dif_albedo    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_ir_dir_albedo    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_vis_dif_albedo    0.000000      0.000000      0.000000
20220706 125643.987 INFO             PET000 (FV3: state_diagnose) :IS:inst_ice_vis_dir_albedo    0.000000      0.000000      0.000000
20220706 125643.987 ERROR            PET000 ESMF_LocalArrayGet.F90:3006 ESMF_LocalArrayGetData Arguments are incompatible  - farrayPtr rank does not match LocalArray rank
20220706 125643.987 ERROR            PET000 ESMF_ArrayGet.F90:2140 ESMF_ArrayGetFPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125643.987 ERROR            PET000 ESMF_FieldGet.F90:2875 ESMF_FieldGetDataPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125643.987 ERROR            PET000 module_cap_cpl.F90:227 Arguments are incompatible  - Passing error in return code
20220706 125643.988 INFO             PET000 UFS Aerosols: Advancing from 2021-03-22T06:00:00 to 2021-03-22T06:12:00
```

and on export:

```
20220706 125743.681 INFO             PET000 (FV3: state_diagnose) :ES:inst_temp_height_surface    284.7190      298.7269      112714.1
20220706 125743.681 INFO             PET000 (FV3: state_diagnose) :ES:inst_temp_levels    179.5572      298.2122     0.1222354E+08
20220706 125743.681 ERROR            PET000 ESMF_LocalArrayGet.F90:3006 ESMF_LocalArrayGetData Arguments are incompatible  - farrayPtr rank does not match LocalArray rank
20220706 125743.681 ERROR            PET000 ESMF_ArrayGet.F90:2140 ESMF_ArrayGetFPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125743.681 ERROR            PET000 ESMF_FieldGet.F90:2875 ESMF_FieldGetDataPtr Arguments are incompatible  - Internal subroutine call returned Error
20220706 125743.681 ERROR            PET000 module_cap_cpl.F90:227 Arguments are incompatible  - Passing error in return code
```

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
Fix bug in state_diagnose to accept 4d variables.

### Issue(s) addressed
fixes #1314  
closes #1330 
closes #1338 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss2.intel
- [x] acorn.intel
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on NOAA-EMC/fv3atm/pull/564
- waiting on https://github.com/NCAR/ccpp-framework/pull/452

### CODE REVIEW

**Comment by jkbk2004** [comment]
@binli2337 @climbfuji can we combine #1330 and #1338 to this PR?

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 I think i've got it all figured out. @climbfuji @binli2337 please let me know if you think i've missed something.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/1008908016/20220803150827/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1008908016/20220803100012/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 004 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 005 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 007 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 009 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 013 failed in run_test failed 
Please make changes and add the following label back: orion-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
> _**Automated RT Failure Notification**_ Machine: orion Compiler: intel Job: RT [RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1008908016/20220803100012/ufs-weather-model [RT] Error: Test cpld_control_p8 001 failed in run_test failed [RT] Error: Test cpld_2threads_p8 003 failed in run_test failed [RT] Error: Test cpld_decomp_p8 004 failed in run_test failed [RT] Error: Test cpld_mpi_p8 005 failed in run_test failed [RT] Error: Test cpld_control_ciceC_p8 006 failed in run_test failed [RT] Error: Test cpld_control_c192_p8 007 failed in run_test failed [RT] Error: Test cpld_bmark_p8 009 failed in run_test failed [RT] Error: Test cpld_debug_p8 013 failed in run_test failed Please make changes and add the following label back: orion-intel-RT

I know Orion has been having issues since it's last PM. @jkbk2004 see if you have luck with a manual run.

**Comment by jkbk2004** [comment]
> > _**Automated RT Failure Notification**_ Machine: orion Compiler: intel Job: RT [RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/1008908016/20220803100012/ufs-weather-model [RT] Error: Test cpld_control_p8 001 failed in run_test failed [RT] Error: Test cpld_2threads_p8 003 failed in run_test failed [RT] Error: Test cpld_decomp_p8 004 failed in run_test failed [RT] Error: Test cpld_mpi_p8 005 failed in run_test failed [RT] Error: Test cpld_control_ciceC_p8 006 failed in run_test failed [RT] Error: Test cpld_control_c192_p8 007 failed in run_test failed [RT] Error: Test cpld_bmark_p8 009 failed in run_test failed [RT] Error: Test cpld_debug_p8 013 failed in run_test failed Please make changes and add the following label back: orion-intel-RT
> 
> I know Orion has been having issues since it's last PM. @jkbk2004 see if you have luck with a manual run.

sure! I will give a try.

**Review by binli2337 — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@DeniseWorthen @climbfuji time for final reviews please.

**Review by DeniseWorthen — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
