### PR TITLE
Update CICE, update ice_in for consistency w/ G-W (was #2069)

### LINKED ISSUE #1986: Update CICE6 to 6.5.0 release
## Description
CICE 6.5.0 release is out. It will be updated in the UFS -weather-model.

### LINKED ISSUE #2068: Allow use of `ice_in.IN` in global applications
## Description
There are a few inconsistencies in `ice_in.IN` that is preventing the use of it in the global application.

## Solution
Eliminate the inconsistencies

## Alternatives
Short of managing a second copy, there are none.

## Related to
Follow-up to #2010

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## PR Author Checklist:

- [x] I have linked PR's from all sub-components involved in section below. 
- [x] I am confirming reviews are completed in ALL sub-component PR's.
- [x] I have run the full RT suite on either Hera/Cheyenne AND have attached the log to this PR below this line:
  - LOG: [RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/13600515/RegressionTests_hera.log)
- [x] I have added the list of all failed regression tests to "Anticipated changes" section.
- [x] I have filled out all sections of the template.

## Description

Update CICE to include latest changes in Consortium/main. Updates ``ice_in`` for consistency w/ G-W.

### Commit Message ###

```
Update CICE to include latest changes in Consortium/main
- implement improvements to the areafact calculation for remapping (CICE-Consortium/CICE#849)
- use -puny when limiting fluxes in icepack (CICE-Consortium/Icepack#474)
- add cpl_frazil namelist (CICE-Consortium/CICE#889) 
- update ice_in for consistency w/ G-W
```
### Associated UFSWM Issues to close

- closes #1986
- closes #2068  

### Subcomponent Pull Requests

- NOAA-EMC/CICE#72
- Dependency of NOAA-EMC/global-workflow#2051

### Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [x] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

### Input data
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Regression Tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

41 Tests fail to run and 41 tests fail to compare

```
grep check_result RegressionTests_hera.log| wc -l
      41
grep run_test RegressionTests_hera.log| wc -l
      41
```

The failed tests are any test using CICE

```
7378:001 cpld_control_p8_mixedmode_intel failed in check_result
7380:002 cpld_control_gfsv17_intel failed in check_result
7382:005 cpld_mpi_gfsv17_intel failed in check_result
7384:006 cpld_debug_gfsv17_intel failed in check_result
7386:007 cpld_control_p8_intel failed in check_result
7388:009 cpld_control_qr_p8_intel failed in check_result
7390:011 cpld_2threads_p8_intel failed in check_result
7392:012 cpld_decomp_p8_intel failed in check_result
7394:013 cpld_mpi_p8_intel failed in check_result
7396:014 cpld_control_ciceC_p8_intel failed in check_result
7398:015 cpld_control_c192_p8_intel failed in check_result
7400:017 cpld_bmark_p8_intel failed in check_result
7402:019 cpld_control_noaero_p8_intel failed in check_result
7404:020 cpld_control_nowave_noaero_p8_intel failed in check_result
7406:021 cpld_debug_p8_intel failed in check_result
7408:022 cpld_debug_noaero_p8_intel failed in check_result
7410:023 cpld_control_noaero_p8_agrid_intel failed in check_result
7412:024 cpld_control_c48_intel failed in check_result
7414:025 cpld_control_p8_faster_intel failed in check_result
7416:026 cpld_control_pdlib_p8_intel failed in check_result
7418:029 cpld_debug_pdlib_p8_intel failed in check_result
7420:150 datm_cdeps_control_cfsr_intel failed in check_result
7422:152 datm_cdeps_control_gefs_intel failed in check_result
7424:153 datm_cdeps_iau_gefs_intel failed in check_result
7426:154 datm_cdeps_stochy_gefs_intel failed in check_result
7428:155 datm_cdeps_ciceC_cfsr_intel failed in check_result
7430:156 datm_cdeps_bulk_cfsr_intel failed in check_result
7432:157 datm_cdeps_bulk_gefs_intel failed in check_result
7434:158 datm_cdeps_mx025_cfsr_intel failed in check_result
7436:159 datm_cdeps_mx025_gefs_intel failed in check_result
7438:160 datm_cdeps_multiple_files_cfsr_intel failed in check_result
7440:161 datm_cdeps_3072x1536_cfsr_intel failed in check_result
7442:162 datm_cdeps_gfs_intel failed in check_result
7444:163 datm_cdeps_debug_cfsr_intel failed in check_result
7446:164 datm_cdeps_control_cfsr_faster_intel failed in check_result
7448:231 cpld_control_p8_gnu failed in check_result
7450:232 cpld_control_nowave_noaero_p8_gnu failed in check_result
7452:233 cpld_debug_p8_gnu failed in check_result
7454:234 cpld_control_pdlib_p8_gnu failed in check_result
7456:235 cpld_debug_pdlib_p8_gnu failed in check_result
7458:236 datm_cdeps_control_cfsr_gnu failed in check_result
```
<details><summary>Tests effected by changes in this PR:</summary>

</details>

### Libraries

- [x] Not Needed
- [ ] Needed
  - [ ] Create separate issue in [JCSDA/spack-stack](https://github.com/JCSDA/spack-stack) asking for update to library. Include library name, library version.
  - [ ] Add issue link from JCSDA/spack-stack following this item 

<details><summary>Code Managers Log</summary>

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.
  - [ ] N/A

### Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment
</details>

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Why am I getting a CICE not up to date message. This PR updates CICE. What "authoritative repository" is it checking against?

**Comment by FernandoAndrade-NOAA** [comment]
I'm checking in with the platform team on this, but I believe this may be caused by the authoritative 50aa2c9 hash not showing up in your weather model's cice commit history, while your sub PR branch does show it within the history.

**Comment by DeniseWorthen** [comment]
And what do you consider 'authoritative'? It should be NOAA-EMC's fork, right?

**Comment by FernandoAndrade-NOAA** [comment]
Right I'm looking at NOAA-EMC emc/develop

**Comment by DeniseWorthen** [comment]
I don't understand. The current noaa-emc is at 50aa2c9. This PR contains that commit.

**Comment by FernandoAndrade-NOAA** [comment]
I'm seeing your weather model branch's cice is b14cedf from Nov 28 while your cice sub pr linked in the description is pointing to cefa7cd from Dec 6th

**Comment by DeniseWorthen** [comment]
ok, hold on. I think I know what's what.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, this should be good to go now, @jkbk2004, @zach1221, @BrianCurtis-NOAA FYI starting tests for this PR.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA @junwang-noaa Could one of you please review the CICE PR? Thanks.

**Comment by DeniseWorthen** [comment]
@FernandoAndrade-NOAA Sorry for the confusion.

**Comment by DeniseWorthen** [comment]
I still don't have CICE PR approvals @junwang-noaa @BrianCurtis-NOAA

**Comment by jkbk2004** [comment]
All tests are successfully done. We can start merging process. @DeniseWorthen Can you merge in the CICE pr?

**Review by sadeghitabas — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@jkbk2004 Why is the commit message not what I posted?

**Comment by jkbk2004** [comment]
> @jkbk2004 Why is the commit message not what I posted?

@DeniseWorthen Do you mean to keep/save same commit message you posted in description to squash-merge commit log?

**Comment by DeniseWorthen** [comment]
That is the whole point of asking the developer to provide the commit message, isn't it? Why else would we ask for it to be provided?

**Comment by BrianCurtis-NOAA** [comment]
> > @jkbk2004 Why is the commit message not what I posted?
> 
> @DeniseWorthen Do you mean to keep/save same commit message you posted in description to squash-merge commit log?

@jkbk2004 We've discussed this already. Please squash and merge using the commit message provided and reviewed by other code managers in the PR template. Please also communicate this to EPIC's CM's so they are aware of this part of the process.

**Comment by jkbk2004** [comment]
> > > @jkbk2004 Why is the commit message not what I posted?
> > 
> > 
> > @DeniseWorthen Do you mean to keep/save same commit message you posted in description to squash-merge commit log?
> 
> @jkbk2004 We've discussed this already. Please squash and merge using the commit message provided and reviewed by other code managers in the PR template. Please also communicate this to EPIC's CM's so they are aware of this part of the process.

Sure!

**Pull request merged**
