### PR TITLE
update to MOM6 main 20240729 commit (gfdl-to-main-2024-05-31)

### LINKED ISSUE #2380: update to MOM6 main 20240729 commit (gfdl-to-main-2024-05-31)
MOM6 main repo. merged the "gfdl-to-main-2024-05-31" on 20240729 (see detail at https://github.com/mom-ocean/MOM6/pull/1631). Need to pull it into dev/emc correspondingly.
Note this PR will require a new BL because

- a new variable "h_ML" is being added in the restart file (see detail at https://github.com/mom-ocean/MOM6/commit/7305528fd99bc09bda648693cd7130e4627de25c)

- a bug fixing on "incorrect PPM:H3 tracer advection stencil" (see detail at https://github.com/NOAA-EMC/MOM6/commit/3fac1c5ab53335e6e07086f373fd3142b704ec25). Note we can retain original answer by setting USE_HUYNH_STENCIL_BUG=True but here we are going to use its default value (False) since this is a real bug fixing.

we will also set DEFAULT_ANSWER_DATE=20231231 in 5x5 setting as currently it is using its default value which is too aggressive (suggested by GFDL)

### PR DESCRIPTION
**Pull request by jiandewang**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

MOM6 main repo. merged the "gfdl-to-main-2024-05-31" on 20240729 (see detail at https://github.com/mom-ocean/MOM6/pull/1631). Need to pull it into dev/emc correspondingly.
Note this PR will require a new BL because

a new variable "h_ML" is being added in the restart file (see detail at https://github.com/mom-ocean/MOM6/commit/7305528fd99bc09bda648693cd7130e4627de25c)

a bug fixing on "incorrect PPM:H3 tracer advection stencil" (see detail at https://github.com/NOAA-EMC/MOM6/commit/3fac1c5ab53335e6e07086f373fd3142b704ec25). Note we can retain original answer by setting USE_HUYNH_STENCIL_BUG=True. 

we will also set DEFAULT_ANSWER_DATE=20231231 in 5x5 setting as currently it is using its default value which is too aggressive (suggested by GFDL)

### Commit Message:
          add MOM_dynamics_split_RK2b.F90 and MOM_EOS_base_type.F90 in cmake list
          add extra 16PE for cpld_debug_pdlib job
          set DEFAULT_ANSWER_DATE=20231231 in 5x5 case
          using MOM6 restart file as BL for sfs and hafs_mom jobs
          switching FIX_USTAR_GUSTLESS_BUG to USTAR_GUSTLESS_BUG in MOM_input
          USE_HUYNH_STENCIL_BUG=True (false will have mpi jobs fail to match their control)

Please provide concise information for The UFS-WM and/or each sub-component:

  * MOM6 - 

### Priority:
* High: Time-sensitive project.

* High: Reason: this PR has been lasted for 2 months to reach final stage and a new MOM6 PR has arrived. Need to finish this PR before I can do any clean test for the new PR.

### UFSWM:
* Closes #2380 

### Sub component Pull Requests:
* MOM6: https://github.com/NOAA-EMC/MOM6/pull/136

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* PR Updates/Changes Baselines.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [ ] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@jiandewang can you sync up branch?

**Comment by jiandewang** [comment]
@jkbk2004 just sync-ed my PR branch

**Comment by jiandewang** [comment]
note for hafs_regional_storm_following_1nest_atm_ocn_wav_mom6 and cpld_control_sfs, you need to create RESTART directory inside BL dir and copy MOM*res*nc to it.

**Comment by jiandewang** [comment]
are we running this PR ? I don't see any email traffic on it today.

**Comment by zach1221** [comment]
> are we running this PR ? I don't see any email traffic on it today.

Yes, tests are running.

**Review by DeniseWorthen — DISMISSED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
Leaving a note that Jet will likely have to be skipped. There is a system issue preventing git clones, I've let the system admins know so they can take a look.

**Comment by FernandoAndrade-NOAA** [comment]
Apologies for the delayed Hera and Gaea logs. RTs were started, but I am unable to log onto the machines to check up on the results due to the token login issues today.

**Comment by DusanJovic-NOAA** [comment]
@BrianCurtis-NOAA is on leave today, but he submitted rt on WCOSS2 before leaving, and asked me to take a look at rt logs after it finishes. I see this:

```
SYNOPSIS:
Starting Date/Time: 20240815 12:48:40
Ending Date/Time: 20240815 14:05:55
Total Time: 01h:17m:56s
Compiles Completed: 33/33
Tests Completed: 153/156
Failed Tests:
* TEST cpld_mpi_gfsv17_intel: FAILED: UNABLE TO COMPLETE COMPARISON
-- LOG: /lfs/h2/emc/nems/noscrub/brian.curtis/git/jiandewang/ufs-weather-model/tests/logs/log_wcoss2/run_cpld_mpi_gfsv17_intel.log
* TEST cpld_mpi_p8_intel: FAILED: UNABLE TO COMPLETE COMPARISON
-- LOG: /lfs/h2/emc/nems/noscrub/brian.curtis/git/jiandewang/ufs-weather-model/tests/logs/log_wcoss2/run_cpld_mpi_p8_intel.log
* TEST cpld_mpi_pdlib_p8_intel: FAILED: UNABLE TO COMPLETE COMPARISON
-- LOG: /lfs/h2/emc/nems/noscrub/brian.curtis/git/jiandewang/ufs-weather-model/tests/logs/log_wcoss2/run_cpld_mpi_pdlib_p8_intel.log
```
in `/lfs/h2/emc/nems/noscrub/brian.curtis/git/jiandewang/ufs-weather-model/tests/logs/RegressionTests_wcoss2.log`

The log file of one of the failed test (cpld_mpi_gfsv17_intel):
```$ more logs/log_wcoss2/rt_cpld_mpi_gfsv17_intel.log

baseline dir = /lfs/h2/emc/nems/noscrub/emc.nems/RT/NEMSfv3gfs/develop-20240813/cpld_control_gfsv17_intel
working dir  = /lfs/h2/emc/ptmp/brian.curtis/FV3_RT/rt_174779/cpld_mpi_gfsv17_intel
Checking test cpld_mpi_gfsv17_intel results ....
 Comparing sfcf021.tile1.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf021.tile2.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf021.tile3.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf021.tile4.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf021.tile5.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf021.tile6.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf021.tile1.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf021.tile2.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf021.tile3.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf021.tile4.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf021.tile5.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf021.tile6.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf024.tile1.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf024.tile2.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf024.tile3.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf024.tile4.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf024.tile5.nc .....USING NCCMP......NOT IDENTICAL
 Comparing sfcf024.tile6.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf024.tile1.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf024.tile2.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf024.tile3.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf024.tile4.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf024.tile5.nc .....USING NCCMP......NOT IDENTICAL
 Comparing atmf024.tile6.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.coupler.res .....USING CMP......OK
 Comparing RESTART/20210323.060000.fv_core.res.nc .....USING NCCMP......OK
 Comparing RESTART/20210323.060000.fv_core.res.tile1.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_core.res.tile2.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_core.res.tile3.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_core.res.tile4.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_core.res.tile5.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_core.res.tile6.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile1.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile2.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile3.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile4.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile5.nc .....USING NCCMP......NOT IDENTICAL
 Comparing RESTART/20210323.060000.fv_srf_wnd.res.tile6.nc .....USING NCCMP......NOT IDENTICAL
 etc....
```
Looks like those three cpld_mpi tests are not reproducible.

**Comment by jiandewang** [comment]
@DusanJovic-NOAA thanks for catching the issue, let me repeat on wcoss2 to see what's going on

**Comment by DusanJovic-NOAA** [comment]
I ran on WCOSS2:
```
./rt.sh -l cpld_mpi.conf -e -c && ./rt.sh -l cpld_mpi.conf -e -m
```
where `cpld_mpi.conf`  is:
```
$ cat cpld_mpi.conf
COMPILE | s2swa_32bit_pdlib  | intel | -DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON | - noaacloud | fv3 |
RUN | cpld_control_gfsv17                | - noaacloud                          | baseline |
RUN | cpld_mpi_gfsv17                    | - noaacloud                          |          |

COMPILE | s2swa | intel | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | | fv3 |
RUN | cpld_control_p8                    | - noaacloud                          | baseline |
RUN | cpld_mpi_p8                        | - noaacloud                          |          |

COMPILE | s2sw_pdlib | intel | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 -DPDLIB=ON | - noaacloud | fv3 |
RUN | cpld_control_pdlib_p8              | - noaacloud                          | baseline |
RUN | cpld_mpi_pdlib_p8                  | - noaacloud                          |          | cpld_control_pdlib_p8
```
and it failed, which means mpi version of these three cpld tests do not reproduce their control test.

BTW does `cpld_mpi_pdlib_p8` really depend on `cpld_control_pdlib_p8`?

**Comment by jiandewang** [comment]
@DusanJovic-NOAA Thanks again for your testing. Actually I am also doing the same testing at this moment. I think I found the root casue which is related to one of the bug fixing from GFDL. Give me one more hour and I will have clear clue on it. I will need you re-run and re-create the BL.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Thanks again for your testing. Actually I am also doing the same testing at this moment. I think I found the root casue which is related to one of the bug fixing from GFDL. Give me one more hour and I will have clear clue on it. I will need you re-run and re-create the BL.

No problem.

**Comment by jiandewang** [comment]
@DusanJovic-NOAA I narrow down the issue and shall be able to provide you a new hash to re-generate BL and verify in 15 minutes

**Comment by jiandewang** [comment]
@DusanJovic-NOAA can you re-checkout the PR branch and re-create BL and verify. It should be
commit 09690a092f727349365fac81c2d2096127bb8f12 (HEAD -> feature/update-MOM6-20240531, origin/feature/update-MOM6-20240531)
Author: jiandewang <jiande.wang@noaa.gov>
Date:   Thu Aug 15 14:37:13 2024 -0400
    set USE_HUYNH_STENCIL_BUG = True

**Comment by jiandewang** [comment]
@FernandoAndrade-NOAA after @DusanJovic-NOAA confirmed his work on wcoss2, I will need you repeat the BL generation and verification on other platforms. Apologize for the extra work.

**Comment by DusanJovic-NOAA** [comment]
> @FernandoAndrade-NOAA after @DusanJovic-NOAA confirmed his work on wcoss2, I will need you repeat the BL generation and verification on other platforms. Apologize for the extra work.

Three cpld_mpi test that previously failed, finished successfully now.

**Comment by jkbk2004** [comment]
> > @FernandoAndrade-NOAA after @DusanJovic-NOAA confirmed his work on wcoss2, I will need you repeat the BL generation and verification on other platforms. Apologize for the extra work.
> 
> Three cpld_mpi test that previously failed, finished successfully now.

I see last commit has no impact on results as well. I will confirm with a full test on Hercules. @DusanJovic-NOAA can you push wcoss2 log when the test is finished?

**Comment by jiandewang** [comment]
@DusanJovic-NOAA thanks for doing the testing. Can you confirm that you ran all the MOM6 related jobs? My last commit requires new BL for all coupled jobs.

**Comment by jiandewang** [comment]
@jkbk2004 you are 99% correct on what you found on other machines. The last commit does not change answers for non-wcoss2 machines except for one job which is hafs-mom6 (sorry I can't provide the exact test name as I am not in front of computer). For this test all cmp will say OK except the first MOM restart file. The reason is this test saves a variable "age" in the restart file and this variable has value changes. This variable is not being saved by all other coupled jobs, this is why all other jobs are not impacted by my last commit.

**Comment by jiandewang** [comment]
@jkbk2004 so you need to re-generate BL for this hafs-mom6 job on all machines

**Comment by jkbk2004** [comment]
> @jkbk2004 so you need to re-generate BL for this hafs-mom6 job on all machines

@jiandewang thanks for the information! @FernandoAndrade-NOAA @zach1221 FYI

**Comment by FernandoAndrade-NOAA** [comment]
@DusanJovic-NOAA Are we skipping Acorn for this PR?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA Are we skipping Acorn for this PR?

Yes.

**Comment by jkbk2004** [comment]
Hera is very busy. I see a long job queue on Hera. Jet lfs4 issue continues.  If we need to recover anything, we need to follow on those tow machine with next pr.

**Comment by FernandoAndrade-NOAA** [comment]
Looks like we'll be skipping hera and jet due to system issues this PR then, we'll catch up on the next PR @jkbk2004

**Comment by DeniseWorthen** [comment]
@FernandoAndrade-NOAA The next PR is currently scheduled to be my warmstart PR. If you plan on skipping baseline creation on Hera, then the next PR must create all baselines---mine only requires one. 

I'm also not clear on what the hurry is. It is late on Friday afternoon. Are you planning to start a new PR today?

**Comment by zach1221** [comment]
@DeniseWorthen I think this PR is listed as high priority above, so we were trying to get it merged before weekend.

**Comment by DeniseWorthen** [comment]
And anyone running RTs this weekend on hera will fail.

**Comment by jiandewang** [comment]
MOM6 merged (hash # 00f8ea20), submodule reverted

**Comment by jiandewang** [comment]
> And anyone running RTs this weekend on hera will fail.

hafs_regional_storm_following_1nest_atm_ocn_wav_mom6 will fail on HERA

**Comment by jiandewang** [comment]
> > And anyone running RTs this weekend on hera will fail.
> 
> hafs_regional_storm_following_1nest_atm_ocn_wav_mom6 will fail on HERA

I just checked HERA BL /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240813/hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel/RESTART

-rw-r--r-- 1 role.epic epic 4197540137 Aug 16 13:41 20200825.150000.MOM.res.nc
-rw-r--r-- 1 role.epic epic 2276048626 Aug 16 13:41 20200825.150000.MOM.res_1.nc

these two were generated ~1.5hr ago so they will be fine

**Review by jkbk2004 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Comment by jiandewang** [comment]
@jkbk2004 @FernandoAndrade-NOAA my test indicates" BL for hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel" has not been updated on HERA. This job will fail if people run latest UWM. It will show "20200825.150000.MOM.res.nc" not identical.

**Comment by jiandewang** [comment]
> > > And anyone running RTs this weekend on hera will fail.
> > 
> > 
> > hafs_regional_storm_following_1nest_atm_ocn_wav_mom6 will fail on HERA
> 
> I just checked HERA BL /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240813/hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel/RESTART
> 
> -rw-r--r-- 1 role.epic epic 4197540137 Aug 16 13:41 20200825.150000.MOM.res.nc -rw-r--r-- 1 role.epic epic 2276048626 Aug 16 13:41 20200825.150000.MOM.res_1.nc
> 
> these two were generated ~1.5hr ago so they will be fine

the above is what I checked Friday around 4pm, they are correct one (I compared them with my own run and got b4b). but now (Sat. 6:40pm) I got
-rw-r--r-- 1 role.epic epic 4197540137 Aug 16 20:21 20200825.150000.MOM.res.nc
-rw-r--r-- 1 role.epic epic 2276048626 Aug 16 20:21 20200825.150000.MOM.res_1.nc
from the time stamp of file being generated, apparently there is updating on them and the new one is not correct

**Comment by jkbk2004** [comment]
@jiandewang let me check with develop branch

**Comment by jiandewang** [comment]
I compared these two yesterday
/scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240813_/hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel/RESTART

/scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20240813/hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel/RESTART

they are not the same, and the BL directory "develop-20240813" contained the correct MOM restart file. But right now when I compare them, they are the same. So somehow files in "develop-20240813_" was being copied to develop-20240813" in the past half day which shouldn't.

**Comment by jiandewang** [comment]
> @jiandewang let me check with develop branch

@jkbk2004 a clean way to do is re-run this job and replace the MOM restart file in BL dir.

**Comment by jkbk2004** [comment]
> > @jiandewang let me check with develop branch
> 
> @jkbk2004 a clean way to do is re-run this job and replace the MOM restart file in BL dir.

@jiandewang recovered ok.

**Pull request merged**
