### PR TITLE
fv3atm: Split GFS_typedefs.F90, rename CCPP_interstitial, import ccpp_t from ccpp_types; contains bug fix for WW3 debug

### LINKED ISSUE #495: Replace use of `ccpp_api` with `ccpp_types` in CCPP_driver.F90
See https://github.com/NOAA-EMC/fv3atm/blob/47d391c09a9b7a8c6fe5fff76c61921487891785/ccpp/driver/CCPP_driver.F90#L3

Type `ccpp_t` should be imported directly from `ccpp_types` instead of the legacy `ccpp_api`. The latter previously provided a consistent API into CCPP when the dynamical CCPP was used. With the introduction of the static CCPP and the auto-generated `ccpp_static_api`, the old `ccpp_api` became redundant. Because of its name being similar to the static API, its use causes confusion.

A similar change should be made in the SCM, and the `ccpp_api` should be removed from the CCPP framework.

Also use this chance to clean up some code in CCPP_driver.F90, for example the locally defined pointer `cdata` is no longer used.

### LINKED ISSUE #506: Split GFS_typedefs.F90 to avoid running out of memory when compiling with optimization
## Description

Compiling `GFS_typedefs.F90` with production flags led to problems on systems that had too little memory avaiable (WCOSS). Therefore, a change was introduced recently to compile `GFS_typedefs.F90` without optimization. By splitting this file, it should (may?) be possible to remove this workaround.

## Solution
Move `GFS_interstitial_type` from `GFS_typedefs.F90` to `CCPP_typedefs.F90`, because this is where it belongs to: It's an interstitial data type required by CCPP.

## Alternatives
Keep as is.

### LINKED ISSUE #507: Rename `CCPP_interstitial_type` and `CCPP_interstitial` (variable)
## Description
In https://github.com/NOAA-EMC/fv3atm/issues/506, it is proposed to move `GFS_interstitial_type` from `GFS_typedefs.F90` to `CCPP_typedefs.F90`. This file already has an interstitial DDT `CCPP_interstitial_type` that is used for the FV3 dycore. The latter name `CCPP_interstitial_type` is confusing, because `GFS_interstitial_type` is also an interstitial type used by CCPP.

## Solution
A PR to the FV3 dycore was made (https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/181), in which a new name is proposed. Once agreed upon, the definition in fv3atm must be changed accordingly.

## Alternatives
Keep as is.

### LINKED ISSUE #1133: CMake build for WW3 fails when compiling S2SW with -DDEBUG=ON
## Description
Compiling UWM app S2SW in debug mode fails with a conflict between compile flag -DDEBUG=ON used at the app level and an internal WW3 variable named DEBUG

### To Reproduce:
Check out current develop branch. Compile S2SW in debug mode:

```
./compile.sh hera.intel '-DAPP=S2SW -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v16_coupled_p8' '' YES NO 2>&1 | tee compile.log
```

The compile log shows a compile failure

```
/apps/cmake/3.20.1/bin/cmake -E touch CICE-interface/CMakeFiles/cice.dir/CICE/icepack/columnphysics/icepack_fsd.F90.o.provides.build
/tmp/ifort8M9ebj.i90: remark #5415: Feature not yet implemented: check shape
/scratch2/NCEPDEV/climate/Denise.Worthen/WORK/ufs-weather-model/WW3/model/src/w3gsrumd.F90(626): error #5082: Syntax error, found INTEGER_CONSTANT '1' when expecting one of: <IDENTIFIER>
                              NCB, NNP, 1 ) RESULT(GSU)
----------------------------------------^
/scratch2/NCEPDEV/climate/Denise.Worthen/WORK/ufs-weather-model/WW3/model/src/w3gsrumd.F90(636): error #5082: Syntax error, found INTEGER_CONSTANT '1' when expecting one of: <IDENTIFIER> %FILL
      LOGICAL, INTENT(IN), OPTIONAL :: 1
```

The source code shows that the "1" is a replacement for the WW3 variable ``DEBUG``

```
      FUNCTION W3GSUC_PTR_R4( IJG, LLG, ICLO, XG, YG, &
                              NCB, NNP, DEBUG ) RESULT(GSU)
!     Single precision pointer interface
      TYPE(T_GSU)         :: GSU
      LOGICAL, INTENT(IN) :: IJG
      LOGICAL, INTENT(IN) :: LLG
      INTEGER, INTENT(IN) :: ICLO
      REAL(4), POINTER    :: XG(:,:)
      REAL(4), POINTER    :: YG(:,:)
      INTEGER, INTENT(IN), OPTIONAL :: NCB
      INTEGER, INTENT(IN), OPTIONAL :: NNP
      LOGICAL, INTENT(IN), OPTIONAL :: DEBUG

```

### PR DESCRIPTION
**Pull request by climbfuji**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This PR updates the submodule pointer for fv3atm and its submodules for the changes described in https://github.com/NOAA-EMC/fv3atm/pull/508.

It also contains the submodule pointer update for WW3 from PR https://github.com/ufs-community/ufs-weather-model/pull/1142, contributed by @JessicaMeixner-NOAA.

### Issue(s) addressed

Fixes https://github.com/NCAR/ccpp-framework/issues/442
Fixes https://github.com/NOAA-EMC/fv3atm/issues/495
Fixes https://github.com/NOAA-EMC/fv3atm/issues/506
Fixes https://github.com/NOAA-EMC/fv3atm/issues/507
Fixes https://github.com/ufs-community/ufs-weather-model/issues/1133

## Testing

Preliminary regression testing on Hera with Intel and GNU:

All tests pass against existing baselines.

[RegressionTests_hera.gnu.log](https://github.com/ufs-community/ufs-weather-model/files/8312644/RegressionTests_hera.gnu.log)
[RegressionTests_hera.intel.log](https://github.com/ufs-community/ufs-weather-model/files/8312645/RegressionTests_hera.intel.log)

For  ORT testing of the WW3 bug fix, see https://github.com/ufs-community/ufs-weather-model/pull/1142.

Full regression tests will be run on all platforms prior to committing the code.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- (n/a) opnReqTest for newly added/changed feature
- [x] CI - https://github.com/ufs-community/ufs-weather-model/pull/1130/commits/dc814db431768b66e8c159dfbb2227e61bd144b8

## Dependencies

Waiting on https://github.com/NCAR/ccpp-framework/pull/443
Waiting on https://github.com/NCAR/ccpp-physics/pull/887
Waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/181
Waiting on https://github.com/NOAA-EMC/fv3atm/pull/508

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
I tried running a full set of RTs on Wcoss Dell: All tests passed.
Then tried running with the changes shown [here](https://github.com/NCAR/ccpp-physics/commit/4d808f85fb91952e4f1ed1bb9ce2cb4950457042) reverted: jobs are still running, but 5 compile jobs failed as of now.

**Comment by junwang-noaa** [comment]
@climbfuji Please see Minsuk's comments above. I think we don't need to compile GFS_typedefs.F90 with -O0 with the code change, do you have any clue why we still need to compile it differently?

**Comment by climbfuji** [comment]
> @climbfuji Please see Minsuk's comments above. I think we don't need to compile GFS_typedefs.F90 with -O0 with the code change, do you have any clue why we still need to compile it differently?

I don't. Presumable the GFS_interstitial_type wasn't the problem, maybe the additions to the other types when NSSL MP was added? At any rate, it is a good cleanup to split the file imo.

**Comment by binli2337** [comment]
@climbfuji Please update your branch. I will run tests on wcoss once your branch is updated. Thanks.

**Comment by climbfuji** [comment]
Thanks Bin, I can work on this tonight and run the tests. There is still no resolution on the GFDL_atmos_cubed_sphere question (see linked PR in the description above). Before this doesn’t get resolved, it doesn’t make sense to run any of the tests.

**Comment by MinsukJi-NOAA** [comment]
@climbfuji please make the following 2 file changes with the commit message: "Update esmf library to 8.3.0b09 for ubuntu-hpc docker image"
```
diff --git a/tests/ci/Dockerfile b/tests/ci/Dockerfile
index 5a243fa2..4e0fa546 100644
--- a/tests/ci/Dockerfile
+++ b/tests/ci/Dockerfile
@@ -1,4 +1,4 @@
-From noaaemc/ubuntu-hpc:v1.9b
+From noaaemc/ubuntu-hpc:v1.10b
 
 ENV HOME=/home/builder
 COPY --chown=builder:builder . $HOME/ufs-weather-model

diff --git a/tests/ci/ci.sh b/tests/ci/ci.sh
index 79b674fb..0ea1a2f6 100755
--- a/tests/ci/ci.sh
+++ b/tests/ci/ci.sh
@@ -81,7 +81,7 @@ elif [ $RUN == "true" ]; then
                 -e "RT_MACHINE=linux.gnu" -e "RT_COMPILER=gnu" \
                 -w "/home/builder/ufs-weather-model/tests" \
                 -v DataVolume:/home/builder/data/NEMSfv3gfs \
-                --shm-size=512m --name my-container noaaemc/ubuntu-hpc:v1.9b \
+                --shm-size=512m --name my-container noaaemc/ubuntu-hpc:v1.10b \
                 /bin/bash -c "./opnReqTest -n ${TEST_NAME} -c ${TEST_CASE} -x"
 
   cd $GITHUB_WORKSPACE
```

**Comment by junwang-noaa** [comment]
@climbfuji Dycore PR is approved, please also add the changes from Minsul for CI test. Thanks

**Comment by climbfuji** [comment]
> @climbfuji Dycore PR is approved, please also add the changes from Minsul for CI test. Thanks

I think I have all the updates included by now. I kicked off the CI tests and the Hera Intel/GNU auto-rt runs. Let's wait for them to come back before starting any of the other runs.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: RT
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/884225286/20220412003006/ufs-weather-model
[RT] Error: Test cpld_restart_c192_p8 009 failed in run_test failed 
Please make changes and add the following label back: gaea-intel-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: gaea
> Compiler: intel
> Job: RT
> [RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/884225286/20220412003006/ufs-weather-model
> [RT] Error: Test cpld_restart_c192_p8 009 failed in run_test failed
> Please make changes and add the following label back: gaea-intel-RT

Error: "insufficient virtual memory" - will rerun this test.

**Comment by climbfuji** [comment]
First round of regression test on wcoss_dell_p3 failed for one test:
```
Dom.Heinzeller@v71a3:/gpfs/dell3/ptmp/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-split-gfs-typedefs/dell/tests [intel|GFS-DEV]> cat /gpfs/dell2/ptmp/Dom.Heinzeller/FV3_RT/rt_17979/cpld_debug_p8/err
...
[0]   ... DONE microphysical lookup tables
[2] Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_send_ud.c at line 2143: vc_reserve_area->RNDV_SEND_STATUS == RNDV_SEND_WAITING_FIN_REPLY
[2] internal ABORT - process 2
```
Will try again.

**Comment by climbfuji** [comment]
> > _**Automated RT Failure Notification**_
> > Machine: gaea
> > Compiler: intel
> > Job: RT
> > [RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/884225286/20220412003006/ufs-weather-model
> > [RT] Error: Test cpld_restart_c192_p8 009 failed in run_test failed
> > Please make changes and add the following label back: gaea-intel-RT
> 
> Error: "insufficient virtual memory" - will rerun this test.

On gaea, the same job failed again. Same place, but this time I can't find an error message that hints to OOM. I think it still is, though:
```
  0:   ... DONE microphysical lookup tables
srun: error: nid00715: tasks 144-177,179: Killed
srun: launch/slurm: _step_signal: Terminating StepId=269003355.0
  0: slurmstepd: error: *** STEP 269003355.0 ON nid00682 CANCELLED AT 2022-04-12T03:40:40 ***
274: forrtl: error (78): process killed (SIGTERM)
274: Image              PC                Routine            Line        Source
274: fv3.exe            0000000005F0046E  Unknown               Unknown  Unknown
274: fv3.exe            000000000603C360  Unknown               Unknown  Unknown
274: fv3.exe            000000000610B8A5  Unknown               Unknown  Unknown
274: fv3.exe            00000000060FD816  Unknown               Unknown  Unknown
274: fv3.exe            00000000060A482A  Unknown               Unknown  Unknown
274: fv3.exe            0000000001359033  _ZN5ESMCI3VMK4rec        4605  ESMCI_VMKernel.C
274: fv3.exe            0000000000DAAD87  _ZN5ESMCI3XXE4exe        4085  ESMCI_DELayout.C
274: fv3.exe            0000000000DA91DB  _ZN5ESMCI3XXE4exe        5409  ESMCI_DELayout.C
274: fv3.exe            0000000000DA91DB  _ZN5ESMCI3XXE4exe        5409  ESMCI_DELayout.C
274: fv3.exe            0000000001706343  _ZN5ESMCI11ArrayB        1680  ESMCI_ArrayBundle.C
274: fv3.exe            000000000107FC42  c_esmc_arraybundl         717  ESMCI_ArrayBundle_F.C
274: fv3.exe            0000000000B5A592  esmf_arraybundlem        2945  ESMF_ArrayBundle.F90
274: fv3.exe            000000000092EF35  esmf_fieldbundlem       16626  ESMF_FieldBundle.F90
274: fv3.exe            00000000004669A5  nuopc_connector_m        6345  NUOPC_Connector.F90
274: fv3.exe            0000000000D64EB3  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
```

**Comment by DeniseWorthen** [comment]
@climbfuji I tested changing inpes,jnpes to 6,8 and then adjusting the tasks allowed the restart job to run and the mediator file reproduces the control. I'm running the control and restart tests again now to confirm. I can point you to the additional log file when it finishes.

```
diff --git a/tests/default_vars.sh b/tests/default_vars.sh
index 02613d5b..55e8bccb 100755
--- a/tests/default_vars.sh
+++ b/tests/default_vars.sh
@@ -536,9 +536,9 @@ elif [[ $MACHINE_ID = gaea.* ]]; then
   OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
   NPROC_ICE_cpl_bmrk_mpi=48

-  TASKS_cpl_c192=288; TPN_cpl_c192=36; INPES_cpl_c192=4; JNPES_cpl_c192=8
-  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
-  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
+  TASKS_cpl_c192=384; TPN_cpl_c192=36; INPES_cpl_c192=6; JNPES_cpl_c192=8
+  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 299"
+  CHM_cpl_c192="0 287"; OPB_cpl_c192="300 359"; IPB_cpl_c192="360 383"
   NPROC_ICE_cpl_c192=24
```

**Comment by climbfuji** [comment]
> @climbfuji I tested changing inpes,jnpes to 6,8 and then adjusting the tasks allowed the restart job to run and the mediator file reproduces the control. I'm running the control and restart tests again now to confirm. I can point you to the additional log file when it finishes.
> 
> ```
> diff --git a/tests/default_vars.sh b/tests/default_vars.sh
> index 02613d5b..55e8bccb 100755
> --- a/tests/default_vars.sh
> +++ b/tests/default_vars.sh
> @@ -536,9 +536,9 @@ elif [[ $MACHINE_ID = gaea.* ]]; then
>    OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
>    NPROC_ICE_cpl_bmrk_mpi=48
> 
> -  TASKS_cpl_c192=288; TPN_cpl_c192=36; INPES_cpl_c192=4; JNPES_cpl_c192=8
> -  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
> -  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
> +  TASKS_cpl_c192=384; TPN_cpl_c192=36; INPES_cpl_c192=6; JNPES_cpl_c192=8
> +  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 299"
> +  CHM_cpl_c192="0 287"; OPB_cpl_c192="300 359"; IPB_cpl_c192="360 383"
>    NPROC_ICE_cpl_c192=24
> ```

Thanks @DeniseWorthen. I tried a different change and that also worked fine:
```
--- a/tests/default_vars.sh
+++ b/tests/default_vars.sh
@@ -536,7 +536,7 @@ elif [[ $MACHINE_ID = gaea.* ]]; then
   OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
   NPROC_ICE_cpl_bmrk_mpi=48

-  TASKS_cpl_c192=288; TPN_cpl_c192=36; INPES_cpl_c192=4; JNPES_cpl_c192=8
+  TASKS_cpl_c192=288; TPN_cpl_c192=18; INPES_cpl_c192=4; JNPES_cpl_c192=8
   THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
   CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
   NPROC_ICE_cpl_c192=24
```
Please let me know what you (@DeniseWorthen @junwang-noaa prefer and I'll either use your changes and your log file, or mine).

**Comment by junwang-noaa** [comment]
@climbfuji I'd suggest to use what Denise provided as gaea and dell will have the same layout.

**Comment by climbfuji** [comment]
> @climbfuji I'd suggest to use what Denise provided as gaea and dell will have the same layout.

Ok, I'll do that in an hour or so (or later if Denise's runs are taking longer), together with the Orion tests.

**Comment by DeniseWorthen** [comment]
The control/restart c192 log is here on gaea (assuming you'll just append to the existing log).

/lustre/f2/pdata/ncep/Denise.Worthen/ufs-weather-model/tests

**Comment by climbfuji** [comment]
@junwang-noaa @DeniseWorthen CI and RT completed, I made the gaea changes in `default_vars.sh` as per Denise's instructions.

Should I merge the CCPP PRs?

**Comment by JessicaMeixner-NOAA** [comment]
Let me know when you are ready for the WW3 PR to be merged as well.

**Comment by climbfuji** [comment]
> Let me know when you are ready for the WW3 PR to be merged as well.

Yes, please go ahead. Thanks!

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
WW3 PR is merged.  Hash is: [d00e431](https://github.com/NOAA-EMC/WW3/commit/d00e431a28a4225fdd8f8303e1c12b5a01e0d85e)

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Ready to merge as far as I am concerned.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: RT
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/884225286/20220411193019/ufs-weather-model
Please make changes and add the following label back: orion-intel-RT

**Comment by climbfuji** [comment]
> _**Automated RT Failure Notification**_
> Machine: orion
> Compiler: intel
> Job: RT
> [RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/884225286/20220411193019/ufs-weather-model
> Please make changes and add the following label back: orion-intel-RT

Too late :-) I already ran it successfully with my other account. Guess the errors were due to the disk `stmp` filling up.

**Pull request merged**
