### PR TITLE
NRL Neptune model 32-bit physics support

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR are specified below.

- [ ] ~~Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.~~

- [ ] ~~New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.~~

## Description

Adds ccpp-physics changes needed to support 32-bit physics on Neptune. This does not add 32-bit physics to FV3, which requires quite a lot more changes in several repositories.

### Issue(s) addressed

Implements what this PR was supposed to:

https://github.com/NCAR/ccpp-physics/pull/797

Which is about half of this batch of changes from NRL:

https://github.com/NCAR/ccpp-physics/pull/772

## Testing

Original testing was done on Neptune model by NRL. After that, it was tested in UFS, with these changes disabled. Finally, another set of branches (not in this PR) were developed that can successfully compile UFS for 32-bit physics, but not yet run it that way.

- [ ] hera.intel  (cannot test because Hera stmp is full)
- [x] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [x] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/918
https://github.com/NOAA-EMC/fv3atm/pull/532

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
As of this posting, this PR is up-to-date with all components and has passed intel compiler tests (on jet) and gnu compiler tests (on hera).

**Comment by SamuelTrahanNOAA** [comment]
I have changed the `.gitmodules` from ssh to https due to permission problems.

**Comment by BrianCurtis-NOAA** [comment]
This will be merged into #1227

**Comment by SamuelTrahanNOAA** [comment]
> This will be merged into https://github.com/ufs-community/ufs-weather-model/pull/1227

Not yet. It is failing after the cleanup of machine.F. I have a fix, and I am testing it now.

**Comment by BrianCurtis-NOAA** [comment]
> > This will be merged into #1227
> 
> Not yet. It is failing after the cleanup of machine.F. I have a fix, and I am testing it now.

We would just be merging in your .gitmodules changes. I will wait until you give me the OK before I run RT's in that PR though.

**Comment by SamuelTrahanNOAA** [comment]
@BrianCurtis-NOAA It works now. The issue was in FV3/ccpp/physics/machine.F, not the .gitmodules.

**Comment by BrianCurtis-NOAA** [comment]
I thought the other PR would have closed this. This was merged in #1227

**Pull request closed without merging**
