### PR TITLE
Enable Thompson microphysics with UFS-Aerosols and update GOCART

### LINKED ISSUE #1047: Enable Thompson microphysics when coupling with UFS-Aerosols
## Description
Due to legacy settings implemented for GEFS-Aerosols, the Thompson microphysics scheme cannot be selected when the UFS weather model is run with prognostic aerosols (UFS-Aerosols).

This update is required to perform prototype 8 experiments.

## Solution
The Thompson MP scheme should be enabled when coupling with UFS-Aerosols, making sure that both microphysics and aerosol tracers are properly processed and diffused by PBL schemes.

### LINKED ISSUE #1048: Update GOCART to version 2.0.2
## Description
The GOCART submodule needs to be updated to point to a more recent GOCART version (2.0.2). This change also requires updating GOCART's resource files (`*.rc`) used in regression tests.

This update is required for prototype 8 experiments.

### PR DESCRIPTION
**Pull request by rmontuoro**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description

This update allows the Thompson microphysics scheme to be used with prognostic aerosols (UFS-Aerosols) (#1047) and updates GOCART to version 2.0.2 (#1048).

### Issue(s) addressed

- fixes #1047 
- fixes #1048 

## Testing

This PR was tested on Hera/Intel and Orion/Intel platforms and regression test logs are included.
No changes to the baseline are introduced.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI

## Dependencies

- https://github.com/NOAA-EMC/fv3atm/pull/484

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@rmontuoro @JessicaMeixner-NOAA Since we are going to have the P8 RT test with aerosol in PR#969, is this PR required to be committed before PR#969 or the coupled aerosol RT test will still run with GFDLMP in #969 and then be changed to Thompson MP in this PR?

**Comment by rmontuoro** [comment]
@junwang-noaa - This PR is ready, so it can be merged as soon as possible.

**Comment by junwang-noaa** [comment]
@rmontuoro Just to confirm, you want this PR to be committed before PR#969, is that correct? Also can you recommend some reviewers? Thanks

**Comment by rmontuoro** [comment]
@junwang-noaa - Yes, this PR can be committed before PR #969. We expect PR #969 to be ready shortly, too.
Note that current PR #969 requires the changes included in this PR.

**Comment by junwang-noaa** [comment]
@rmontuoro This PR is in the commit queue with commit date planned on 2/18. Please get your branches synced with the top of develop branches after tomorrow's commit. Thanks

**Comment by rmontuoro** [comment]
The following regression tests failed (did not reproduce the baseline) on WCOSS Dell P3:
```
control_fhzero
control_wrtGauss_netcdf_parallel
control_wrtGauss_netcdf_parallel_debug
hafs_global_multiple_4nests_atm
hafs_regional_1nest_atm
hafs_regional_telescopic_2nests_atm
regional_netcdf_parallel
```

**Comment by junwang-noaa** [comment]
@rmontuoro I ran RT with the develop branch on dell, the RT passed. I am going to run RT on dell with your branch.

**Comment by junwang-noaa** [comment]
@rmontuoro The RT finished successfully on dell. The log file is at: /gpfs/dell2/emc/modeling/noscrub/Jun.Wang/nems/vlab/20220221/ufs-weather-model/tests/RegressionTests_wcoss_dell_p3.log, please commit to your branch. Thanks

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
