### PR TITLE
Add AQM Regression Test and documentation for AQM & Update upp submodule to fix in-line post issues for RRFS and HAFS

### LINKED ISSUE #1098: Add UFS-AQM documentation
## Description
UFS-AQM documentation will be added to ufs-weather-model documentation page with develop branch

## Solution
Start from Raffaele's presentation: 
https://docs.google.com/presentation/d/1Vmov-AazHwfwCYJYCkCoFUbOk6N5IptBidZQ5QsqfHU
The documentation will be added to: 
https://ufs-weather-model.readthedocs.io/en/latest/

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### LINKED ISSUE #1099: Add UFS-AQM regression test
## Description
A UFS-AQM regression test will be set up and added to ufs-weather-model regression test suite. It will work on the ufs-weather-model supported platforms.  

## Solution
Once the UFS-AQM build system is set up, a UFS-AQM regression test will be set up and run in the ufs-weather-model regression test suite.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

### LINKED ISSUE #1258: Template files for tests consisting of different components othen those of the current coupled tests configuration
## Description
I was in the process of adding back a test case consisting of atm, ocn and ice components (cpld_control_c96_noaero_p8) for CI purposes (#1253 #1249) and found that a new nems.configure file is required because the current template includes the wave component. Also found that a new cpld_control_run.IN file is required because, when restarting, the current template looks for a restart file for the wave component.

The reason for this issue is to gather any feedback and provide reference in the future.

## Solution
Two possible solutions may be:
1) Have separate template files for each test having different components 
2) Have common template files  for all tests and allow conditionals in the template files

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
# PR Checklist

- [X] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [X] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [X] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [X] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Description
A regression test using the newest AQM subcomponent was created.
Documentation for using AQM in UFSWM is also included.

### Issue(s) addressed
- fixes #1099
- fixes #1098
- fixes #1258 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss2.intel
- [x] opnReqTest for newly added/changed feature
- [] CI (skipping)

## Dependencies
NOAA-EMC/AQM/pull/4
NOAA-EMC/CMAQ/pull/1
NOAA-EMC/fv3atm/pull/558

## Linked PR's
Closes #1286

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 This PR is ready again. I've ran regional_atmaq on hera.intel, cheyenne.intel, wcoss2.intel and all compared OK. I ran the full suite minus regional_atmaq on cheyenne.intel and wcoss2.intel and cheyenne.gnu and they all passed.

**Comment by BrianCurtis-NOAA** [comment]
@jkbk2004 This PR is ready again. I've ran regional_atmaq on hera.intel, cheyenne.intel, wcoss2.intel and all compared OK. I ran the full suite minus regional_atmaq on cheyenne.intel and wcoss2.intel and cheyenne.gnu and they all passed.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/982694128/20220713194513/ufs-weather-model
Please make changes and add the following label back: jet-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
[BL] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/982694128/20220713183009/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/982694128/20220713214030/ufs-weather-model
[RT] Error: Test compile_010 failed in run_compile failed 
Please make changes and add the following label back: gaea-intel-BL

**Comment by BrianCurtis-NOAA** [comment]
ORT Passed in my previous PR: https://github.com/ufs-community/ufs-weather-model/pull/1272#issuecomment-1163605340

**Comment by jkbk2004** [comment]
@DusanJovic-NOAA @ChunxiZhang-NOAA @DeniseWorthen All tests are done. With final reviews, we can move on to merge the PR.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA can we start merging process of the dependencies?

**Comment by jkbk2004** [comment]
@WenMeng-NOAA all tests are done. we can start merging in [fv3atm pr558](https://github.com/NOAA-EMC/fv3atm/pull/558).

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Thanks for brining the AQM documentation!

**Comment by WenMeng-NOAA** [comment]
Thanks!

**Pull request merged**
